/* Tech Robot · unitat 6 «Comptar i recordar» (variables) */
Object.assign(TBADGE, {
  u6comp: { id: 'u6comp', ico: '🧮', n: 'Comptador/a|Contador/a', d: 'Has fet servir la primera variable: el comptador d\'en Bit.|Has usado tu primera variable: el contador de Bit.' },
  u6rec: { id: 'u6rec', ico: '🏆', n: 'Rècord de punts|Récord de puntos', d: 'Has sumat i restat punts i has fet que en Bit reaccioni a un número.|Has sumado y restado puntos y has hecho que Bit reaccione a un número.' },
  u6merc: { id: 'u6merc', ico: '🍎', n: 'Recol·lector/a|Recolector/a', d: 'Projecte acabat: el mercat de l\'illa ho té tot comptat.|Proyecto terminado: el mercado de la isla lo tiene todo contado.' }
});
ROBOT_UNITS[6] = { t: 'Comptar i recordar|Contar y recordar', d: 'Variables|Variables', color: '#14A3B8', s: [
  /* ---------- Sessió 1 · El comptador d'en Bit ---------- */
  { id: 'r6-1', t: "El comptador d'en Bit|El contador de Bit", min: 35, badge: 'u6comp',
    learn: ['Una variable és una capsa amb nom que recorda un número.|Una variable es una caja con nombre que recuerda un número.',
      '«Suma» i «Resta» canvien el número; «Posa el comptador a…» el substitueix per un de nou.|«Suma» y «Resta» cambian el número; «Pon el contador a…» lo sustituye por uno nuevo.',
      'Abans de comptar, convé posar el comptador a 0.|Antes de contar, conviene poner el contador a 0.'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Recordes la unitat anterior? Què és una <b>funció</b>?|¿Recuerdas la unidad anterior? ¿Qué es una <b>función</b>?',
        opts: ['Un grup de blocs amb un nom, que puc fer servir moltes vegades|Un grupo de bloques con un nombre, que puedo usar muchas veces', 'Un bloc que fa girar en Bit|Un bloque que hace girar a Bit', 'Un error del programa|Un error del programa'], a: 0,
        ex: "Una funció posa nom a uns quants blocs. Avui posarem nom a una altra cosa: a un <b>número</b>.|Una función pone nombre a unos cuantos bloques. Hoy pondremos nombre a otra cosa: a un <b>número</b>." },
      { k: 'story', ph: 'missio', who: 'both', scene: 'illa', title: 'La cursa del far|La carrera del faro',
        t: "Diumenge hi ha la <b>cursa del far</b>! En Numi vol saber quantes passes fa cada corredor, però amb tants números… impossible recordar-los tots de memòria! En Bit té una idea: <b>guardar el número en una capsa amb nom</b>.|¡El domingo es la <b>carrera del faro</b>! Numi quiere saber cuántos pasos da cada corredor, pero con tantos números… ¡imposible recordarlos todos de memoria! Bit tiene una idea: <b>guardar el número en una caja con nombre</b>." },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy',
        art: () => `<div class="tlegend">${[['add', "Fa créixer el número del comptador.|Hace crecer el número del contador."], ['sub', "Fa baixar el número del comptador.|Hace bajar el número del contador."], ['setv', "Esborra el número d'abans i hi posa el nou.|Borra el número de antes y pone el nuevo."]].map(([k, d]) => `<div class="tlg" style="flex-wrap:wrap;row-gap:6px"><span class="tb c-var tpb"><span class="tbi">${BIT_ICO[k]}</span><span class="tbl">${bitLabel(bitNew(k))}</span></span><span>${tx(d)}</span></div>`).join('')}</div>`,
        t: "BIP! Us presento el meu <b>comptador</b>. És una capsa on guardo un número. Amb aquests tres blocs nous el puc fer créixer, fer baixar o tornar a començar.|¡BIP! Os presento mi <b>contador</b>. Es una caja donde guardo un número. Con estos tres bloques nuevos lo puedo hacer crecer, hacer bajar o volver a empezar." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Variable|Variable', t: 'Una capsa amb nom que recorda|Una caja con nombre que recuerda', anim: 'u6box',
          x: "Una <span class='hl'>variable</span> és com una capsa amb un <b>nom</b> escrit a fora i un <b>número</b> a dins. En Bit la fa servir per <b>recordar</b> un número i canviar-lo quan cal. El marcador d'un partit o el comptador de passes d'un rellotge funcionen igual.|Una <span class='hl'>variable</span> es como una caja con un <b>nombre</b> escrito fuera y un <b>número</b> dentro. Bit la usa para <b>recordar</b> un número y cambiarlo cuando hace falta. El marcador de un partido o el contador de pasos de un reloj funcionan igual.",
          tip: "La variable d'en Bit es diu <b>comptador</b> i comença a 0, si el repte no diu el contrari.|La variable de Bit se llama <b>contador</b> y empieza en 0, si el reto no dice lo contrario." },
        { k: 'Suma|Suma', t: 'Suma 1 a cada passa|Suma 1 en cada paso', demo: { w: { map: ['.....', '>###F', '.....'], vname: 'comptador|contador' }, prog: '4{ f add:1 }' },
          x: "El bloc <b>Suma 1 al comptador</b> fa créixer el número de la capsa. Mira el marcador de dalt: cada vegada que en Bit avança, el comptador suma 1. A la bandera val 4: en Bit ha <b>recordat</b> quantes passes ha fet.|El bloque <b>Suma 1 al contador</b> hace crecer el número de la caja. Mira el marcador de arriba: cada vez que Bit avanza, el contador suma 1. En la bandera vale 4: Bit ha <b>recordado</b> cuántos pasos ha dado." },
        { k: 'Tres blocs|Tres bloques', t: 'Suma, resta i posa|Suma, resta y pon', anim: 'u6ops',
          x: "<b>Suma</b> fa créixer el número. <b>Resta</b> el fa baixar. <b>Posa el comptador a…</b> s'oblida del número d'abans i hi posa el nou. Per triar quant sumes o restes, toca el bloc i fes servir els botons <b>−</b> i <b>+</b>.|<b>Suma</b> hace crecer el número. <b>Resta</b> lo hace bajar. <b>Pon el contador a…</b> se olvida del número de antes y pone el nuevo. Para elegir cuánto sumas o restas, toca el bloque y usa los botones <b>−</b> y <b>+</b>." },
        { k: 'El marcador|El marcador', t: 'Quant ha de valer?|¿Cuánto tiene que valer?', demo: { w: { map: ['......', '>####F', '......'], count: 5 }, prog: '5{ f add:1 }' },
          x: "Damunt del món hi ha el <b>marcador</b>: primer, el que val ara el comptador; després de la ratlla, el número que demana el repte. Per superar-lo, en Bit ha d'arribar a la bandera i el comptador ha de valer <b>exactament</b> aquest número.|Encima del mundo está el <b>marcador</b>: primero, lo que vale ahora el contador; después de la raya, el número que pide el reto. Para superarlo, Bit tiene que llegar a la bandera y el contador tiene que valer <b>exactamente</b> ese número." },
        { k: 'Compte!|¡Cuidado!', t: 'Sumar no és posar|Sumar no es poner', anim: 'u6setadd',
          x: "Si el comptador val 4, <b>Suma 1</b> el deixa a 5, però <b>Posa el comptador a 1</b> el deixa a 1. Posar <b>esborra</b> el que hi havia!|Si el contador vale 4, <b>Suma 1</b> lo deja en 5, pero <b>Pon el contador a 1</b> lo deja en 1. ¡Poner <b>borra</b> lo que había!",
          bad: "«Posa el comptador a 1» hi afegeix 1.|«Pon el contador a 1» le añade 1.", good: "«Posa el comptador a 1» hi deixa un 1, valgués el que valgués abans.|«Pon el contador a 1» deja un 1, valiera lo que valiera antes." }
      ] },
      { k: 'quiz', ph: 'descobreix', q: "Una variable recorda un número que pot canviar. On en trobaries una?|Una variable recuerda un número que puede cambiar. ¿Dónde encontrarías una?",
        opts: ["Al marcador d'un partit de bàsquet|En el marcador de un partido de baloncesto", 'A la pilota del partit|En la pelota del partido', 'A la cistella|En la canasta'], a: 0,
        ex: "El marcador té un nom (els dos equips) i un número que canvia cada vegada que algú encistella.|El marcador tiene un nombre (los dos equipos) y un número que cambia cada vez que alguien encesta." },
      { k: 'unplug', ph: 'mans', ico: '🫙', title: 'La capsa dels números|La caja de los números',
        t: "Necessites un pot o una capsa, un paper per escriure-hi un nom i uns quants botons, macarrons o pedretes.|Necesitas un bote o una caja, un papel para escribir un nombre y unos cuantos botones, macarrones o piedrecitas.",
        steps: ["Escriu un nom a la capsa: per exemple, <b>comptador</b>. Ja tens una variable!|Escribe un nombre en la caja: por ejemplo, <b>contador</b>. ¡Ya tienes una variable!",
          "Algú de casa dona ordres: <b>«Suma 2»</b>, <b>«Resta 1»</b>, <b>«Posa el comptador a 0»</b>… Tu poses o treus botons.|Alguien de casa da órdenes: <b>«Suma 2»</b>, <b>«Resta 1»</b>, <b>«Pon el contador a 0»</b>… Tú pones o quitas botones.",
          "Abans d'obrir la capsa, endevina quants botons hi ha. Després compteu-los!|Antes de abrir la caja, adivina cuántos botones hay. ¡Después contadlos!",
          "Canvieu els papers: ara dones tu les ordres.|Cambiad los papeles: ahora das tú las órdenes."],
        tip: "Si t'equivoques, no passa res: torneu a fer les ordres a poc a poc, una a una.|Si te equivocas, no pasa nada: volved a hacer las órdenes despacio, una a una." },
      { k: 'quiz', ph: 'prova', q: "Prediu! El comptador comença a 0. Quant valdrà quan en Bit acabi aquest programa?|¡Predice! El contador empieza en 0. ¿Cuánto valdrá cuando Bit termine este programa?",
        art: () => '<div class="tdprog">' + tDemoChips(TQ('f add:1 f add:1 f add:1')).replace(/class="tdb /g, 'class="tdb did ') + '</div>',
        opts: ['3|3', '1|1', '6|6'], a: 0, keep: true, ex: "Cada «Suma 1» fa créixer el comptador: 1, 2, 3. Els «Endavant» no el canvien.|Cada «Suma 1» hace crecer el contador: 1, 2, 3. Los «Adelante» no lo cambian." },
      { k: 'quiz', ph: 'prova', q: "I ara? Llegeix els blocs d'un en un, de dalt a baix.|¿Y ahora? Lee los bloques de uno en uno, de arriba abajo.",
        art: () => '<div class="tdprog">' + tDemoChips(TQ('setv:2 add:3 sub:1')).replace(/class="tdb /g, 'class="tdb did ') + '</div>',
        opts: ['4|4', '6|6', '2|2'], a: 0, keep: true, ex: "Posa a 2 → val 2. Suma 3 → val 5. Resta 1 → val 4.|Pon a 2 → vale 2. Suma 3 → vale 5. Resta 1 → vale 4." },
      { k: 'spot', ph: 'investiga', q: "En Bit havia de sumar 1 a cada passa, però a la bandera el comptador val 2 i no 4. Pots executar-lo per veure-ho. <b>Toca el bloc equivocat.</b>|Bit tenía que sumar 1 en cada paso, pero en la bandera el contador vale 2 y no 4. Puedes ejecutarlo para verlo. <b>Toca el bloque equivocado.</b>",
        w: { map: ['.....', '>###F', '.....'], count: 4 }, prog: TPX('f add:1 f sub:1! f add:1 f add:1'),
        ex: "És el «Resta 1»: fa baixar el comptador en lloc de fer-lo pujar. Havia de ser «Suma 1».|Es el «Resta 1»: hace bajar el contador en lugar de hacerlo subir. Tenía que ser «Suma 1»." },
      { k: 'move', ph: 'pausa', secs: 25, t: "Fes de comptador amb el cos! Fes <b>5 salts</b> i, a cada salt, aixeca un dit. Ara <b>resta 2</b>: abaixa dos dits. Quants en tens? Ara <b>posa't a 0</b>: tanca els punys!|¡Haz de contador con el cuerpo! Da <b>5 saltos</b> y, en cada salto, levanta un dedo. Ahora <b>resta 2</b>: baja dos dedos. ¿Cuántos tienes? Ahora <b>ponte a 0</b>: ¡cierra los puños!" },
      { k: 'build', ph: 'repte', q: "Primer repte: porta en Bit a la bandera i fes que el comptador <b>compti les passes</b>. Mira el marcador: n'ha de valer 5.|Primer reto: lleva a Bit a la bandera y haz que el contador <b>cuente los pasos</b>. Mira el marcador: tiene que valer 5.",
        w: { map: ['......', '>####F', '......'], count: 5 }, pal: ['fwd', 'add', 'rep'], sol: TQ('5{ f add:1 }'),
        hint: "Després de cada Endavant, un «Suma 1». Si vols menys blocs, fes-ho dins d'un Repeteix.|Después de cada Adelante, un «Suma 1». Si quieres menos bloques, hazlo dentro de un Repite." },
      { k: 'build', ph: 'repte', q: "<b>Compte enrere!</b> Per començar la cursa, el comptador val 4. Fes que en Bit <b>resti 1 a cada passa</b>: quan arribi a la bandera, ha de valer 0.|<b>¡Cuenta atrás!</b> Para empezar la carrera, el contador vale 4. Haz que Bit <b>reste 1 en cada paso</b>: cuando llegue a la bandera, tiene que valer 0.",
        w: { map: ['.....', '>###F', '.....'], v0: 4, count: 0 }, pal: ['fwd', 'sub', 'rep'], sol: TQ('4{ f sub:1 }'),
        hint: "4, 3, 2, 1… 0! Cada passa, un «Resta 1».|4, 3, 2, 1… ¡0! Cada paso, un «Resta 1»." },
      { k: 'build', ph: 'repte', q: "Ara compta els <b>girs</b>, no les passes. Però atenció: el comptador encara té un 7 d'una cursa d'abans! <b>Posa'l a 0</b> abans de començar.|Ahora cuenta los <b>giros</b>, no los pasos. Pero atención: ¡el contador aún tiene un 7 de una carrera de antes! <b>Ponlo a 0</b> antes de empezar.",
        w: { map: ['>#.F.', '.#.#.', '.###.'], v0: 7, count: 3 }, pal: ['fwd', 'left', 'right', 'add', 'setv'], sol: TQ('setv:0 f r add:1 f f l add:1 f f l add:1 f f'),
        hint: "El primer bloc ha de ser «Posa el comptador a 0». Després, un «Suma 1» just després de cada gir.|El primer bloque tiene que ser «Pon el contador a 0». Después, un «Suma 1» justo después de cada giro.",
        after: "Posar el comptador a 0 al principi es diu <b>inicialitzar</b> la variable. Els programadors ho fan sempre!|Poner el contador a 0 al principio se llama <b>inicializar</b> la variable. ¡Los programadores lo hacen siempre!" },
      { k: 'build', ph: 'repte', q: "Aquest programa compta bé les passes… però a la bandera el comptador val 0! <b>Troba el bug i arregla'l.</b>|Este programa cuenta bien los pasos… ¡pero en la bandera el contador vale 0! <b>Encuentra el bug y arréglalo.</b>",
        w: { map: ['RR...', '>###F', 'RR...'], count: 4 }, pal: ['fwd', 'add', 'setv', 'rep'], prog: TQ('4{ f add:1 } setv:0'), sol: TQ('setv:0 4{ f add:1 }'),
        hint: "Mira l'últim bloc: què li fa al comptador just quan en Bit arriba?|Mira el último bloque: ¿qué le hace al contador justo cuando Bit llega?" },
      { k: 'create', ph: 'crea', name: 'El meu comptador de passes|Mi contador de pasos',
        q: "Ara decideixes tu el camí! Porta en Bit a la bandera <b>passant per les 3 estrelles</b>, i fes que el comptador digui <b>quantes passes ha fet</b>. Abans d'executar-lo, endevina el número.|¡Ahora decides tú el camino! Lleva a Bit a la bandera <b>pasando por las 3 estrellas</b>, y haz que el contador diga <b>cuántos pasos ha dado</b>. Antes de ejecutarlo, adivina el número.",
        crit: ['Recull les 3 estrelles i acaba a la bandera|Recoge las 3 estrellas y termina en la bandera', 'El comptador val el mateix que el nombre de passes|El contador vale lo mismo que el número de pasos'],
        check: p => { const r = bitFinal({ map: ['>..*..', '.R....', '....*.', '.*.R..', '.....F'] }, p); return r.S.v === r.S.trail.length - 1 ? null : "En Bit arriba, però el comptador no diu quantes passes ha fet. Posa un «Suma 1» a cada Endavant!|Bit llega, pero el contador no dice cuántos pasos ha dado. ¡Pon un «Suma 1» en cada Adelante!"; },
        w: { map: ['>..*..', '.R....', '....*.', '.*.R..', '.....F'] }, pal: ['fwd', 'left', 'right', 'add', 'sub', 'setv', 'rep'],
        sol: TQ('4{ f add:1 } r 2{ f add:1 } r 3{ f add:1 } l 2{ f add:1 } l 4{ f add:1 }') },
      { k: 'quiz', ph: 'tanca', q: 'Per acabar: què és una <b>variable</b>?|Para terminar: ¿qué es una <b>variable</b>?',
        opts: ['Una capsa amb nom que recorda un número|Una caja con nombre que recuerda un número', 'Un bloc que fa avançar en Bit|Un bloque que hace avanzar a Bit', 'Un tipus de bucle|Un tipo de bucle'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: 'Quin bloc fa que el comptador torni a començar des de 0?|¿Qué bloque hace que el contador vuelva a empezar desde 0?',
        opts: [tChip('setv'), tChip('add'), tChip('sub')], a: 0, ex: "«Posa el comptador a 0» esborra el número d'abans. Restar només el fa baixar una mica.|«Pon el contador a 0» borra el número de antes. Restar solo lo hace bajar un poco." },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 2 · Recollir i comptar ---------- */
  { id: 'r6-2', t: 'Recollir i comptar|Recoger y contar', min: 35,
    learn: ["Per comptar coses mentre en Bit camina: «Si hi ha una estrella, suma 1».|Para contar cosas mientras Bit camina: «Si hay una estrella, suma 1».",
      'El mateix programa compta bé a totes les illes, encara que cadascuna tingui un nombre diferent de coses.|El mismo programa cuenta bien en todas las islas, aunque cada una tenga un número diferente de cosas.',
      '«Suma 1» ha d\'anar a dins del «Si»; a fora, comptaria totes les passes.|«Suma 1» tiene que ir dentro del «Si»; fuera, contaría todos los pasos.'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "El comptador val 5. En Bit fa <b>Posa el comptador a 0</b> i després <b>Suma 2</b>. Quant val ara?|El contador vale 5. Bit hace <b>Pon el contador a 0</b> y después <b>Suma 2</b>. ¿Cuánto vale ahora?",
        opts: ['2|2', '7|7', '3|3'], a: 0, keep: true, ex: "«Posa a 0» esborra el 5. Després, 0 + 2 = 2.|«Pon a 0» borra el 5. Después, 0 + 2 = 2." },
      { k: 'quiz', ph: 'recorda', q: "Recordes els sensors d'en Bit? Què fa el bloc <b>Si hi ha un obstacle davant</b>?|¿Recuerdas los sensores de Bit? ¿Qué hace el bloque <b>Si hay un obstáculo delante</b>?",
        opts: ['Fa els blocs de dins només si davant hi ha un obstacle|Hace los bloques de dentro solo si delante hay un obstáculo', 'Fa els blocs de dins sempre|Hace los bloques de dentro siempre', 'Treu els obstacles del camí|Quita los obstáculos del camino'], a: 0,
        ex: "El «Si» mira el món i decideix. Avui li farem mirar una cosa nova: si hi ha una estrella.|El «Si» mira el mundo y decide. Hoy le haremos mirar una cosa nueva: si hay una estrella." },
      { k: 'story', ph: 'missio', who: 'both', scene: 'moll', title: "La pluja d'estrelles|La lluvia de estrellas",
        t: "Aquesta nit hi ha hagut una <b>pluja d'estrelles</b> i n'han caigut un munt a les platges de l'illa! En Numi vol saber <b>quantes n'hi ha a cada platja</b>. En Bit les recollirà… i les comptarà mentre camina.|¡Esta noche ha habido una <b>lluvia de estrellas</b> y han caído un montón en las playas de la isla! Numi quiere saber <b>cuántas hay en cada playa</b>. Bit las recogerá… y las contará mientras camina." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Comptar|Contar', t: 'Comptar mentre recullo|Contar mientras recojo', demo: { w: { map: ['.....', '>*#*#', '.....'], vname: 'comptador|contador' }, prog: 'f add:1 f f add:1 f' },
          x: "Quan omples una cistella de pomes, cada poma que hi poses és <b>una més</b>. En Bit fa el mateix: aquí el programa té un «Suma 1» just després de cada estrella. Al final, el comptador diu quantes n'ha recollit.|Cuando llenas una cesta de manzanas, cada manzana que pones es <b>una más</b>. Bit hace lo mismo: aquí el programa tiene un «Suma 1» justo después de cada estrella. Al final, el contador dice cuántas ha recogido." },
        { k: 'Si… suma|Si… suma', t: 'Si hi ha una estrella, suma 1|Si hay una estrella, suma 1', demo: { w: { map: ['.....', '>*#**', '.....'], vname: 'comptador|contador' }, prog: '4{ f if:gem{ add:1 } }' },
          x: "A cada casella, en Bit es pregunta: <b>hi ha una estrella?</b> Si n'hi ha, suma 1. Si no, no fa res i continua. Mira com el comptador només puja quan trepitja una estrella.|En cada casilla, Bit se pregunta: <b>¿hay una estrella?</b> Si la hay, suma 1. Si no, no hace nada y sigue. Mira cómo el contador solo sube cuando pisa una estrella." },
        { k: 'Moltes illes|Muchas islas', t: 'Un programa per a totes les platges|Un programa para todas las playas', anim: 'u6islands',
          x: "Si escrius «Suma 3», només funciona a la platja que té 3 estrelles. En canvi, «Si hi ha una estrella, suma 1» funciona a <b>totes</b>: el programa no sap quantes n'hi ha, però les <b>compta</b>.|Si escribes «Suma 3», solo funciona en la playa que tiene 3 estrellas. En cambio, «Si hay una estrella, suma 1» funciona en <b>todas</b>: el programa no sabe cuántas hay, pero las <b>cuenta</b>.",
          tip: "Als reptes amb pestanyes «Illa 1 · Illa 2», el mateix programa s'executa a totes les illes, una darrere l'altra.|En los retos con pestañas «Isla 1 · Isla 2», el mismo programa se ejecuta en todas las islas, una detrás de otra." },
        { k: 'Altres coses|Otras cosas', t: 'També es poden comptar caixes i girs|También se pueden contar cajas y giros', demo: { w: { map: ['>#b#.', '...b.', '...#F'], vname: 'comptador|contador' }, prog: '3{ f if:box{ add:1 } } r 2{ f if:box{ add:1 } } l f' },
          x: "El comptador pot comptar el que vulguis: estrelles, <b>caixes</b>, passes, girs… Aquí en Bit pregunta <b>si hi ha una caixa</b> i compta les caixes del moll sense agafar-les.|El contador puede contar lo que quieras: estrellas, <b>cajas</b>, pasos, giros… Aquí Bit pregunta <b>si hay una caja</b> y cuenta las cajas del muelle sin cogerlas." },
        { k: 'Compte!|¡Cuidado!', t: 'Dins del «Si», no a fora|Dentro del «Si», no fuera', anim: 'u6inside',
          x: "Si poses «Suma 1» <b>a fora</b> del «Si», en Bit suma a cada passa, hi hagi estrella o no. Ha d'anar <b>a dins</b>: així només suma quan la pregunta diu que sí.|Si pones «Suma 1» <b>fuera</b> del «Si», Bit suma en cada paso, haya estrella o no. Tiene que ir <b>dentro</b>: así solo suma cuando la pregunta dice que sí.",
          bad: "«Suma 1» a sota del «Si», a fora: compta totes les passes.|«Suma 1» debajo del «Si», fuera: cuenta todos los pasos.", good: "«Suma 1» a dins del «Si»: compta només les estrelles.|«Suma 1» dentro del «Si»: cuenta solo las estrellas." }
      ] },
      { k: 'quiz', ph: 'prova', q: "Prediu! En Bit fa aquest programa en aquesta platja. Quant valdrà el comptador?|¡Predice! Bit hace este programa en esta playa. ¿Cuánto valdrá el contador?",
        art: () => '<div class="tdprog">' + tDemoChips(TQ('3{ f if:gem{ add:1 } }')).replace(/class="tdb /g, 'class="tdb did ') + '</div>',
        w: { map: ['....', '>*#*', '....'] }, opts: ['2|2', '3|3', '1|1'], a: 0, keep: true,
        ex: "Avança 3 caselles, però només 2 tenen estrella: el «Si» diu que sí 2 vegades.|Avanza 3 casillas, pero solo 2 tienen estrella: el «Si» dice que sí 2 veces." },
      { k: 'seq', ph: 'mans', q: "Així compta en Bit a cada casella. <b>Ordena els passos.</b>|Así cuenta Bit en cada casilla. <b>Ordena los pasos.</b>",
        items: ['Avança una casella|Avanza una casilla', 'Mira si hi ha una estrella|Mira si hay una estrella', "Si n'hi ha, suma 1 al comptador|Si la hay, suma 1 al contador", 'Torna a començar amb la casella següent|Vuelve a empezar con la casilla siguiente'],
        ex: "Primer arriba, després mira, després decideix. I tot això es repeteix: és un bucle amb un «Si» a dins.|Primero llega, después mira, después decide. Y todo esto se repite: es un bucle con un «Si» dentro." },
      { k: 'unplug', ph: 'mans', ico: '🥄', title: 'Compta sense saber-ho|Cuenta sin saberlo',
        t: "Amb algú de casa i 5 gots de plàstic (o tasses) i unes quantes culleres.|Con alguien de casa y 5 vasos de plástico (o tazas) y unas cuantas cucharas.",
        steps: ["Mentre tu no mires, l'altra persona posa els gots en fila i amaga culleres a sota d'alguns.|Mientras tú no miras, la otra persona pone los vasos en fila y esconde cucharas debajo de algunos.",
          "Tu fas de Bit: avances got a got i, <b>si hi ha una cullera, suma 1</b> (aixeca un dit).|Tú haces de Bit: avanzas vaso a vaso y, <b>si hay una cuchara, suma 1</b> (levanta un dedo).",
          "Al final, digues el número que tens als dits.|Al final, di el número que tienes en los dedos.",
          "Torneu-ho a fer amagant un altre nombre de culleres. El teu «programa» és el mateix, però el número canvia!|Volved a hacerlo escondiendo otro número de cucharas. Tu «programa» es el mismo, ¡pero el número cambia!"] },
      { k: 'spot', ph: 'investiga', q: "En Bit havia de sumar 1 per cada estrella, però a la bandera el comptador val 6. <b>Toca el bloc equivocat.</b>|Bit tenía que sumar 1 por cada estrella, pero en la bandera el contador vale 6. <b>Toca el bloque equivocado.</b>",
        w: { map: ['.......', '>*#*#*F', '.......'], count: 3, vname: "comptador d'estrelles|contador de estrellas" }, prog: TPX('6{ f if:gem{ add:2! } }'),
        ex: "El «Suma 2» compta cada estrella dues vegades: 3 estrelles × 2 = 6. Havia de ser «Suma 1».|El «Suma 2» cuenta cada estrella dos veces: 3 estrellas × 2 = 6. Tenía que ser «Suma 1»." },
      { k: 'move', ph: 'pausa', secs: 25, t: "Estrelles de mar! Camina per l'aula: cada vegada que la mestra o el mestre digui <b>«estrella!»</b>, fes un salt i suma 1 amb els dits. Si diu <b>«roca!»</b>, queda't quiet. Quantes estrelles has comptat?|¡Estrellas de mar! Camina por el aula: cada vez que la maestra o el maestro diga <b>«¡estrella!»</b>, da un salto y suma 1 con los dedos. Si dice <b>«¡roca!»</b>, quédate quieto. ¿Cuántas estrellas has contado?" },
      { k: 'build', ph: 'repte', q: "Recull totes les estrelles d'aquesta platja i <b>compta-les</b>. Acaba a la bandera.|Recoge todas las estrellas de esta playa y <b>cuéntalas</b>. Termina en la bandera.",
        w: { map: ['>**#.', '...*.', '...*F'], count: 4, vname: "comptador d'estrelles|contador de estrellas" }, pal: ['fwd', 'left', 'right', 'rep', 'if', 'add'], conds: ['gem'],
        sol: TQ('3{ f if:gem{ add:1 } } r 2{ f if:gem{ add:1 } } l f'),
        hint: "Pots posar «Suma 1» després de cada estrella, o fer servir «Si hi ha una estrella» dins d'un Repeteix.|Puedes poner «Suma 1» después de cada estrella, o usar «Si hay una estrella» dentro de un Repite." },
      { k: 'build', ph: 'repte', q: "Tres platges, <b>un sol programa</b>. Cada platja té un nombre diferent d'estrelles: el comptador les ha de comptar bé a totes. Mira les pestanyes «Illa».|Tres playas, <b>un solo programa</b>. Cada playa tiene un número diferente de estrellas: el contador las tiene que contar bien en todas. Mira las pestañas «Isla».",
        w: { map: ['.......', '>*#*#*F', '.......'], count: 3, vname: "comptador d'estrelles|contador de estrellas",
          alts: [{ map: ['.......', '>##*##F', '.......'], count: 1 }, { map: ['.......', '>**#**F', '.......'], count: 4 }] },
        pal: ['fwd', 'rep', 'if', 'add'], conds: ['gem'], sol: TQ('6{ f if:gem{ add:1 } }'),
        hint: "No posis el número: fes que en Bit pregunti a cada casella. Repeteix 6 vegades: Endavant i «Si hi ha una estrella, suma 1».|No pongas el número: haz que Bit pregunte en cada casilla. Repite 6 veces: Adelante y «Si hay una estrella, suma 1»." },
      { k: 'build', ph: 'repte', q: "Recordes les funcions? Escriu la funció <b>«passa i compta»</b> (avança i, si hi ha una estrella, suma 1) i fes-la servir per recórrer les dues platges.|¿Recuerdas las funciones? Escribe la función <b>«pasa y cuenta»</b> (avanza y, si hay una estrella, suma 1) y úsala para recorrer las dos playas.",
        w: { map: ['>##*.', '...#.', '...*.', '...#F'], count: 2, vname: "comptador d'estrelles|contador de estrellas", alts: [{ map: ['>*#*.', '...*.', '...*.', '...*F'], count: 5 }] },
        pal: ['fwd', 'left', 'right', 'rep', 'if', 'add', 'call'], conds: ['gem'], fnEdit: ['A'], fnName: { A: 'passa i compta|pasa y cuenta' },
        sol: TQ('3{ A } r 3{ A } l A'), solFns: { A: TQ('f if:gem{ add:1 }') },
        hint: "Dins de la funció: Endavant i «Si hi ha una estrella, suma 1». Al programa: 3 vegades la funció, gira, 3 vegades més, gira i una última.|Dentro de la función: Adelante y «Si hay una estrella, suma 1». En el programa: 3 veces la función, gira, 3 veces más, gira y una última." },
      { k: 'build', ph: 'repte', q: "Ara en Bit compta les <b>caixes</b> del moll (sense agafar-les). Però el programa compta totes les passes! <b>Arregla'l</b> perquè funcioni a les dues illes.|Ahora Bit cuenta las <b>cajas</b> del muelle (sin cogerlas). ¡Pero el programa cuenta todos los pasos! <b>Arréglalo</b> para que funcione en las dos islas.",
        w: { map: ['.......', '>b##b#F', '.......'], count: 2, vname: 'comptador de caixes|contador de cajas', alts: [{ map: ['.......', '>#bbb#F', '.......'], count: 3 }] },
        pal: ['fwd', 'rep', 'if', 'add'], conds: ['box', 'gem'], prog: TQ('6{ f if:box{ } add:1 }'), sol: TQ('6{ f if:box{ add:1 } }'),
        hint: "El «Suma 1» és a fora del «Si». Esborra'l i posa'n un de nou a dins (toca l'espai buit de dins del «Si»).|El «Suma 1» está fuera del «Si». Bórralo y pon uno nuevo dentro (toca el espacio vacío de dentro del «Si»)." },
      { k: 'create', ph: 'crea', name: 'La platja de les estrelles|La playa de las estrellas',
        q: "Tria el teu camí per aquesta platja: recull les <b>4 estrelles</b>, compta-les amb <b>«Si hi ha una estrella»</b> i acaba a la bandera. Hi ha molts camins bons!|Elige tu camino por esta playa: recoge las <b>4 estrellas</b>, cuéntalas con <b>«Si hay una estrella»</b> y termina en la bandera. ¡Hay muchos caminos buenos!",
        crit: ['Recull les 4 estrelles i acaba a la bandera|Recoge las 4 estrellas y termina en la bandera', 'El comptador val 4|El contador vale 4', 'Fa servir «Si hi ha una estrella»|Usa «Si hay una estrella»'],
        check: p => bitCountK(p, ['if']) ? null : "Funciona, però compta les estrelles amb un «Si hi ha una estrella». Així el programa serviria per a qualsevol platja!|Funciona, pero cuenta las estrellas con un «Si hay una estrella». ¡Así el programa serviría para cualquier playa!",
        w: { map: ['>.*...', '.R..*.', '*..R..', '...*.R', '.....F'], count: 4, vname: "comptador d'estrelles|contador de estrellas" }, pal: ['fwd', 'left', 'right', 'rep', 'if', 'add'], conds: ['gem'],
        sol: TQ('4{ f if:gem{ add:1 } } r 3{ f if:gem{ add:1 } } r 4{ f if:gem{ add:1 } } r f if:gem{ add:1 } r r 2{ f } l 5{ f }') },
      { k: 'quiz', ph: 'tanca', q: "Per comptar només les estrelles, on ha d'anar el bloc «Suma 1»?|Para contar solo las estrellas, ¿dónde tiene que ir el bloque «Suma 1»?",
        opts: ["A dins del «Si hi ha una estrella»|Dentro del «Si hay una estrella»", "A sota del «Si», a fora|Debajo del «Si», fuera", 'Al principi del programa|Al principio del programa'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "Per què «Si hi ha una estrella, suma 1» és millor que posar «Suma 3» directament?|¿Por qué «Si hay una estrella, suma 1» es mejor que poner «Suma 3» directamente?",
        opts: ['Perquè funciona encara que cada platja tingui un nombre diferent d\'estrelles|Porque funciona aunque cada playa tenga un número diferente de estrellas', 'Perquè té més blocs|Porque tiene más bloques', 'Perquè en Bit va més de pressa|Porque Bit va más deprisa'], a: 0,
        ex: "El programa no ha de saber el número: el descobreix comptant.|El programa no tiene que saber el número: lo descubre contando." },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 3 · Punts i rècords ---------- */
  { id: 'r6-3', t: 'Punts i rècords|Puntos y récords', min: 35, badge: 'u6rec',
    learn: ['Cada cosa pot valer punts diferents: «Suma 2», «Suma 5», «Resta 1»…|Cada cosa puede valer puntos diferentes: «Suma 2», «Suma 5», «Resta 1»…',
      'La condició «el comptador valgui 3» és certa només quan val exactament 3.|La condición «el contador valga 3» es cierta solo cuando vale exactamente 3.',
      'Amb un «Si» que mira el comptador, en Bit pot reaccionar quan arriba a un número.|Con un «Si» que mira el contador, Bit puede reaccionar cuando llega a un número.'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "Per comptar només les estrelles, on va el bloc «Suma 1»?|Para contar solo las estrellas, ¿dónde va el bloque «Suma 1»?",
        opts: ["A dins del «Si hi ha una estrella»|Dentro del «Si hay una estrella»", "A fora del «Si», just a sota|Fuera del «Si», justo debajo", "No cal cap «Si»|No hace falta ningún «Si»"], a: 0,
        ex: "A dins, només suma quan hi ha estrella. A fora, suma a cada passa.|Dentro, solo suma cuando hay estrella. Fuera, suma en cada paso." },
      { k: 'story', ph: 'missio', who: 'both', scene: 'poble', title: 'La gimcana de la festa major|La gincana de la fiesta mayor',
        t: "És la festa major del poble i hi ha una <b>gimcana</b>! Cada prova dona punts: les estrelles en valen 2, les caixes 5… i trepitjar un bassal de fang en resta! En Bit vol fer un <b>rècord</b>. Per saber-ho, cal un bon <b>marcador</b>.|¡Es la fiesta mayor del pueblo y hay una <b>gincana</b>! Cada prueba da puntos: las estrellas valen 2, las cajas 5… ¡y pisar un charco de barro resta! Bit quiere hacer un <b>récord</b>. Para saberlo, hace falta un buen <b>marcador</b>." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Punts|Puntos', t: 'Cada cosa pot valer diferent|Cada cosa puede valer diferente', anim: 'u6points',
          x: "Al bàsquet, una cistella pot valer 1, 2 o 3 punts. A la gimcana d'en Bit, una estrella val <b>2</b> i una caixa val <b>5</b>. Per això el bloc «Suma» té un número que pots canviar: «Suma 2», «Suma 5»…|En el baloncesto, una canasta puede valer 1, 2 o 3 puntos. En la gincana de Bit, una estrella vale <b>2</b> y una caja vale <b>5</b>. Por eso el bloque «Suma» tiene un número que puedes cambiar: «Suma 2», «Suma 5»…" },
        { k: 'Restar|Restar', t: 'Perdre punts|Perder puntos', demo: { w: { map: ['......', '>*r*rF', '......'], vname: 'comptador|contador' }, prog: '5{ f if:gem{ add:2 } if:floor:r{ sub:1 } }' },
          x: "Els bassals de fang (el terra vermell) <b>resten 1 punt</b>. Mira el marcador: puja 2 a cada estrella i baixa 1 a cada bassal. Un programa pot tenir dos «Si», un per a cada cosa.|Los charcos de barro (el suelo rojo) <b>restan 1 punto</b>. Mira el marcador: sube 2 en cada estrella y baja 1 en cada charco. Un programa puede tener dos «Si», uno para cada cosa." },
        { k: 'Variables amb nom|Variables con nombre', t: 'Comptador, marcador, punts…|Contador, marcador, puntos…', anim: 'u6box',
          x: "Una variable pot tenir el nom que li escaiguin: <b>comptador</b>, <b>marcador</b>, <b>punts</b>… El nom ens diu <b>què</b> recorda. Als reptes d'avui, la variable d'en Bit es diu <b>marcador</b>. I, abans de començar una partida, el marcador sempre es posa a 0!|Una variable puede tener el nombre que mejor le vaya: <b>contador</b>, <b>marcador</b>, <b>puntos</b>… El nombre nos dice <b>qué</b> recuerda. En los retos de hoy, la variable de Bit se llama <b>marcador</b>. Y, antes de empezar un partido, ¡el marcador siempre se pone a 0!" },
        { k: 'Quan arribi a…|Cuando llegue a…', t: 'Si el comptador val 3…|Si el contador vale 3…', demo: { w: { map: ['......', '>####F', '......'], vname: 'comptador|contador' }, prog: '5{ f add:1 if:cnt=3{ light:g } }' },
          x: "Un «Si» també pot mirar el comptador, amb la condició <b>«el comptador valgui 3»</b>. Aquí en Bit suma 1 a cada passa i, just quan el comptador val 3, <b>encén el llum verd</b>. Així en Bit reacciona quan arriba a un número.|Un «Si» también puede mirar el contador, con la condición <b>«el contador valga 3»</b>. Aquí Bit suma 1 en cada paso y, justo cuando el contador vale 3, <b>enciende la luz verde</b>. Así Bit reacciona cuando llega a un número." },
        { k: 'Compte!|¡Cuidado!', t: 'Exactament 3, ni més ni menys|Exactamente 3, ni más ni menos', anim: 'u6jump',
          x: "La condició «el comptador valgui 3» només és certa quan val <b>exactament 3</b>. Si el comptador salta de 2 en 2 (0, 2, 4, 6…), <b>mai</b> no valdrà 3 i el «Si» no farà res!|La condición «el contador valga 3» solo es cierta cuando vale <b>exactamente 3</b>. Si el contador salta de 2 en 2 (0, 2, 4, 6…), ¡<b>nunca</b> valdrá 3 y el «Si» no hará nada!",
          bad: "«Valgui 3» vol dir «3 o més».|«Valga 3» quiere decir «3 o más».", good: "«Valgui 3» vol dir exactament 3.|«Valga 3» quiere decir exactamente 3." }
      ] },
      { k: 'quiz', ph: 'descobreix', q: "A la gimcana, cada estrella val 2 punts. En Bit en recull 3. Quants punts té?|En la gincana, cada estrella vale 2 puntos. Bit recoge 3. ¿Cuántos puntos tiene?",
        opts: ['6|6', '3|3', '5|5'], a: 0, keep: true, ex: "2 + 2 + 2 = 6. Cada estrella fa «Suma 2».|2 + 2 + 2 = 6. Cada estrella hace «Suma 2»." },
      { k: 'unplug', ph: 'mans', ico: '🧦', title: 'El marcador de mitjons|El marcador de calcetines',
        t: "Amb algú de casa, una cistella (o una capsa) i 5 mitjons fets una bola. Necessiteu un paper per fer de marcador.|Con alguien de casa, una cesta (o una caja) y 5 calcetines hechos una bola. Necesitáis un papel para hacer de marcador.",
        steps: ["Abans de començar, <b>poseu el marcador a 0</b>.|Antes de empezar, <b>poned el marcador a 0</b>.",
          "Llança els mitjons d'un en un. Si entra a la cistella: <b>suma 2</b>. Si cau a terra: <b>resta 1</b>.|Lanza los calcetines de uno en uno. Si entra en la cesta: <b>suma 2</b>. Si cae al suelo: <b>resta 1</b>.",
          "Si el marcador arriba a valer <b>exactament 6</b>, crideu «Rècord!».|Si el marcador llega a valer <b>exactamente 6</b>, gritad «¡Récord!».",
          "Canvieu els papers i compareu els punts.|Cambiad los papeles y comparad los puntos."],
        tip: "Si el marcador baixa de 0, apunteu-lo igualment: és un repte de comptar, no una competició.|Si el marcador baja de 0, apuntadlo igualmente: es un reto de contar, no una competición." },
      { k: 'quiz', ph: 'prova', q: "Prediu! Quants punts tindrà el marcador quan en Bit acabi?|¡Predice! ¿Cuántos puntos tendrá el marcador cuando Bit termine?",
        art: () => '<div class="tdprog">' + tDemoChips(TQ('setv:0 add:5 sub:1 add:2')).replace(/class="tdb /g, 'class="tdb did ') + '</div>',
        opts: ['6|6', '8|8', '2|2'], a: 0, keep: true, ex: "0 → 5 → 4 → 6. Cada bloc canvia el número que hi havia.|0 → 5 → 4 → 6. Cada bloque cambia el número que había." },
      { k: 'predict', ph: 'prova', q: "En Bit suma 1 a cada passa i <b>gira a l'esquerra quan el comptador val 2</b>. On acabarà?|Bit suma 1 en cada paso y <b>gira a la izquierda cuando el contador vale 2</b>. ¿Dónde terminará?",
        w: { map: ['..B..', '..#C.', '>###A'] }, prog: TQ('4{ f add:1 if:cnt=2{ l } }'), a: 'B',
        ex: "Després de 2 passes, el comptador val 2 i en Bit gira cap amunt. Les altres 2 passes les fa pujant.|Después de 2 pasos, el contador vale 2 y Bit gira hacia arriba. Los otros 2 pasos los da subiendo." },
      { k: 'spot', ph: 'investiga', q: "El llum verd s'havia d'encendre quan el comptador valgués 3, però no s'encén mai! <b>Toca el bloc que ho fa fallar.</b>|¡La luz verde tenía que encenderse cuando el contador valiera 3, pero no se enciende nunca! <b>Toca el bloque que lo hace fallar.</b>",
        w: { map: ['......', '>####F', '......'], lights: ['g'] }, prog: TPX('5{ f add:2! if:cnt=3{ light:g } }'),
        ex: "Amb «Suma 2», el comptador fa 2, 4, 6… i se salta el 3. Amb «Suma 1» passaria per 1, 2, 3!|Con «Suma 2», el contador hace 2, 4, 6… y se salta el 3. ¡Con «Suma 1» pasaría por 1, 2, 3!" },
      { k: 'move', ph: 'pausa', secs: 25, t: "Gimcana de punts! Fes <b>2 salts</b> (suma 2), <b>1 gir</b> (resta 1) i <b>5 passes de gegant</b> (suma 5). Quants punts tens? Si tens exactament 6, aixeca els braços: rècord!|¡Gincana de puntos! Da <b>2 saltos</b> (suma 2), <b>1 giro</b> (resta 1) y <b>5 pasos de gigante</b> (suma 5). ¿Cuántos puntos tienes? Si tienes exactamente 6, levanta los brazos: ¡récord!" },
      { k: 'build', ph: 'repte', q: "Primera prova de la gimcana! Cada <b>estrella val 2 punts</b> i la <b>caixa en val 5</b>. Fes que el marcador sumi els punts i arriba a la bandera.|¡Primera prueba de la gincana! Cada <b>estrella vale 2 puntos</b> y la <b>caja vale 5</b>. Haz que el marcador sume los puntos y llega a la bandera.",
        w: { map: ['.......', '>*##b*F', '.......'], count: 9, vname: 'marcador|marcador' }, pal: ['fwd', 'add', 'rep'], sol: TQ('f add:2 f f f add:5 f add:2 f'),
        hint: "Toca un bloc «Suma» que ja hagis posat i fes servir + per canviar-ne el número. Estrella: Suma 2. Caixa: Suma 5.|Toca un bloque «Suma» que ya hayas puesto y usa + para cambiar su número. Estrella: Suma 2. Caja: Suma 5." },
      { k: 'build', ph: 'repte', q: "Segona prova: estrelles (+2) i bassals de fang vermells (−1). Fes un programa que compti bé els punts <b>a les dues illes</b>.|Segunda prueba: estrellas (+2) y charcos de barro rojos (−1). Haz un programa que cuente bien los puntos <b>en las dos islas</b>.",
        w: { map: ['.......', '>*r*#*F', '.......'], count: 5, vname: 'marcador|marcador', alts: [{ map: ['.......', '>r*rr*F', '.......'], count: 1 }] },
        pal: ['fwd', 'rep', 'if', 'add', 'sub'], conds: ['gem', 'floor:r'], sol: TQ('6{ f if:gem{ add:2 } if:floor:r{ sub:1 } }'),
        hint: "A dins del Repeteix: Endavant, un «Si hi ha una estrella» amb «Suma 2» i un altre «Si» amb el terra vermell i «Resta 1». Toca el «Si» per canviar-ne la condició.|Dentro del Repite: Adelante, un «Si hay una estrella» con «Suma 2» y otro «Si» con el suelo rojo y «Resta 1». Toca el «Si» para cambiar su condición." },
      { k: 'build', ph: 'repte', q: "<b>Premi!</b> Recull i compta les estrelles. A la bandera, si el comptador val 3, encén el <b>llum verd</b> (premi); si no, el <b>llum vermell</b>. Funciona a les tres illes?|<b>¡Premio!</b> Recoge y cuenta las estrellas. En la bandera, si el contador vale 3, enciende la <b>luz verde</b> (premio); si no, la <b>luz roja</b>. ¿Funciona en las tres islas?",
        w: { map: ['.......', '>*#*#*F', '.......'], count: 3, lights: ['g'], vname: "comptador d'estrelles|contador de estrellas",
          alts: [{ map: ['.......', '>*###*F', '.......'], count: 2, lights: ['r'] }, { map: ['.......', '>**#*#F', '.......'], count: 3, lights: ['g'] }] },
        pal: ['fwd', 'rep', 'if', 'else', 'add', 'light'], conds: ['gem', 'cnt=3'], colors: ['g', 'r'],
        sol: TQ('6{ f if:gem{ add:1 } } if:cnt=3{ light:g } else{ light:r }'),
        hint: "Primer, el Repeteix que compta. Després del bucle, un «Si» amb la condició «el comptador valgui 3» i «si no». Toca el «Si» per afegir el «si no».|Primero, el Repite que cuenta. Después del bucle, un «Si» con la condición «el contador valga 3» y «si no». Toca el «Si» para añadir el «si no»." },
      { k: 'build', ph: 'repte', q: "<b>Repte de rècord!</b> Cada estrella fa sonar «do» i, quan en Bit n'ha recollit 3, ha de sonar «sol» <b>una sola vegada</b>. Però aquest programa toca «sol» massa vegades. Per què? <b>Arregla'l.</b>|<b>¡Reto de récord!</b> Cada estrella hace sonar «do» y, cuando Bit ha recogido 3, tiene que sonar «sol» <b>una sola vez</b>. Pero este programa toca «sol» demasiadas veces. ¿Por qué? <b>Arréglalo.</b>",
        w: { map: ['.......', '>***#*F', '.......'], count: 4, melody: ['do', 'do', 'do', 'sol', 'do'], vname: "comptador d'estrelles|contador de estrellas",
          alts: [{ map: ['.......', '>*#*#*F', '.......'], count: 3, melody: ['do', 'do', 'do', 'sol'] }] },
        pal: ['fwd', 'rep', 'if', 'add', 'note'], conds: ['gem', 'cnt=3'], notes: ['do', 'sol'],
        prog: TQ('6{ f if:gem{ add:1 note:do } if:cnt=3{ note:sol } }'), sol: TQ('6{ f if:gem{ add:1 note:do if:cnt=3{ note:sol } } }'),
        hint: "Quan el comptador val 3, continua valent 3 a les passes sense estrella, i el «Si» torna a sonar. Posa el «Si el comptador…» a <b>dins</b> del «Si hi ha una estrella»: així només mira el comptador quan acaba de sumar.|Cuando el contador vale 3, sigue valiendo 3 en los pasos sin estrella, y el «Si» vuelve a sonar. Pon el «Si el contador…» <b>dentro</b> del «Si hay una estrella»: así solo mira el contador cuando acaba de sumar." },
      { k: 'create', ph: 'crea', name: 'La meva gimcana de punts|Mi gincana de puntos',
        q: "Inventa les regles de la teva gimcana! Tria quants punts val cada estrella, la caixa i el bassal vermell. Recull les 3 estrelles, arriba a la bandera i, <b>quan el marcador valgui 10, encén el llum verd</b>.|¡Inventa las reglas de tu gincana! Elige cuántos puntos vale cada estrella, la caja y el charco rojo. Recoge las 3 estrellas, llega a la bandera y, <b>cuando el marcador valga 10, enciende la luz verde</b>.",
        crit: ['Recull les 3 estrelles i acaba a la bandera|Recoge las 3 estrellas y termina en la bandera', 'Cada cosa suma (o resta) els punts que has triat|Cada cosa suma (o resta) los puntos que has elegido', 'Quan el marcador val 10, s\'encén el llum verd|Cuando el marcador vale 10, se enciende la luz verde'],
        check: p => { const r = bitFinal({ map: ['>.*.b.', '.R.R..', '.*..*.', '..r..F'] }, p); return JSON.stringify(p).includes('"cnt=10"') && r.S.leds.includes('g') ? null : "En Bit arriba, però el llum verd s'ha d'encendre amb un «Si» que miri si el marcador val 10. Ajusta els punts perquè hi arribi exactament!|Bit llega, pero la luz verde se tiene que encender con un «Si» que mire si el marcador vale 10. ¡Ajusta los puntos para que llegue exactamente!"; },
        w: { map: ['>.*.b.', '.R.R..', '.*..*.', '..r..F'], vname: 'marcador|marcador' }, pal: ['fwd', 'left', 'right', 'rep', 'if', 'add', 'sub', 'setv', 'light'], conds: ['cnt=10', 'gem', 'box', 'floor:r'], colors: ['g', 'y', 'r'],
        sol: TQ('f f add:3 f f add:1 f r f f r f add:3 f f f add:3 if:cnt=10{ light:g } l f l 4{ f }') },
      { k: 'quiz', ph: 'tanca', q: "El marcador fa 0, 2, 4, 6, 8… Quan serà certa la condició «el marcador valgui 5»?|El marcador hace 0, 2, 4, 6, 8… ¿Cuándo será cierta la condición «el marcador valga 5»?",
        opts: ['Mai: el marcador se salta el 5|Nunca: el marcador se salta el 5', 'Quan valgui 6, que és més que 5|Cuando valga 6, que es más que 5', 'Al principi|Al principio'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "Quin bloc faries servir quan en Bit trepitja un bassal i perd 1 punt?|¿Qué bloque usarías cuando Bit pisa un charco y pierde 1 punto?",
        opts: [tChip('sub'), tChip('add'), tChip('setv')], a: 0, ex: "Restar fa baixar el marcador sense esborrar els punts que ja tenia.|Restar hace bajar el marcador sin borrar los puntos que ya tenía." },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 4 · Projecte: el recol·lector de fruita ---------- */
  { id: 'r6-4', t: 'Projecte: el recol·lector de fruita|Proyecto: el recolector de fruta', min: 40, proj: true, badge: 'u6merc',
    learn: ['Abans de programar amb una variable, cal decidir què compta, amb quin número comença i quan canvia.|Antes de programar con una variable, hay que decidir qué cuenta, con qué número empieza y cuándo cambia.',
      'Una mateixa variable pot sumar coses que valen diferent: cada fruita 1 i cada caixa 5.|Una misma variable puede sumar cosas que valen diferente: cada fruta 1 y cada caja 5.',
      'Has acabat el projecte de la unitat de les variables!|¡Has terminado el proyecto de la unidad de las variables!'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "Quan és certa la condició «el comptador valgui 3»?|¿Cuándo es cierta la condición «el contador valga 3»?",
        opts: ['Només quan el comptador val exactament 3|Solo cuando el contador vale exactamente 3', 'Quan val 3 o més|Cuando vale 3 o más', 'Sempre|Siempre'], a: 0 },
      { k: 'quiz', ph: 'recorda', q: "Un programa ha de comptar les fruites d'illes diferents. Quina parella de blocs fa servir?|Un programa tiene que contar las frutas de islas diferentes. ¿Qué pareja de bloques usa?",
        opts: ["«Si hi ha una estrella» amb «Suma 1» a dins|«Si hay una estrella» con «Suma 1» dentro", "Un «Suma 5» al final|Un «Suma 5» al final", "«Posa el comptador a 0» a cada passa|«Pon el contador a 0» en cada paso"], a: 0 },
      { k: 'story', ph: 'missio', who: 'both', scene: 'poble', title: "El mercat de l'illa|El mercado de la isla",
        t: "Dissabte hi ha <b>mercat</b> a la plaça! En Bit ajudarà els pagesos: ha de <b>collir la fruita</b> dels camps, portar les <b>caixes de fruita</b> a les parades i, sobretot, <b>comptar-ho tot</b> perquè ningú no s'equivoqui amb els números.|¡El sábado hay <b>mercado</b> en la plaza! Bit ayudará a los agricultores: tiene que <b>recoger la fruta</b> de los campos, llevar las <b>cajas de fruta</b> a los puestos y, sobre todo, <b>contarlo todo</b> para que nadie se equivoque con los números." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Planificar|Planificar', t: 'Quatre preguntes abans de començar|Cuatro preguntas antes de empezar', anim: 'u6plan',
          x: "Abans de programar amb una variable, fes-te quatre preguntes: <b>què</b> vull comptar? Amb <b>quin número</b> comença? <b>Quan</b> suma (i quant)? <b>Quant</b> ha de valer al final? Si tens les respostes, el programa és molt més fàcil.|Antes de programar con una variable, hazte cuatro preguntas: ¿<b>qué</b> quiero contar? ¿Con <b>qué número</b> empieza? ¿<b>Cuándo</b> suma (y cuánto)? ¿<b>Cuánto</b> tiene que valer al final? Si tienes las respuestas, el programa es mucho más fácil." },
        { k: 'Caixes|Cajas', t: 'Una caixa plena val 5|Una caja llena vale 5', demo: { w: { map: ['.....', '>b#H.', '.....'], vname: 'comptador|contador' }, prog: 'setv:0 f p f f d add:5' },
          x: "Cada caixa porta <b>5 fruites</b>. Quan en Bit la deixa a la parada, suma 5 al comptador de fruites del mercat. Fixa't que suma <b>després</b> de deixar-la: primer la feina, després el compte.|Cada caja lleva <b>5 frutas</b>. Cuando Bit la deja en el puesto, suma 5 al contador de frutas del mercado. Fíjate en que suma <b>después</b> de dejarla: primero el trabajo, después la cuenta." },
        { k: 'Tot junt|Todo junto', t: 'Fruites soltes i caixes|Frutas sueltas y cajas', demo: { w: { map: ['......', '>*b*H.', '......'], vname: 'comptador|contador' }, prog: 'f if:gem{ add:1 } f p f if:gem{ add:1 } f d add:5' },
          x: "La mateixa variable pot comptar coses que valen diferent: cada <b>fruita</b> que en Bit cull és +1 i cada <b>caixa</b> que deixa a la parada és +5. Al final, el comptador diu quantes fruites hi ha al mercat: 1 + 1 + 5 = 7.|La misma variable puede contar cosas que valen diferente: cada <b>fruta</b> que Bit recoge es +1 y cada <b>caja</b> que deja en el puesto es +5. Al final, el contador dice cuántas frutas hay en el mercado: 1 + 1 + 5 = 7." },
        { k: 'Compte!|¡Cuidado!', t: 'A zero al principi, no al mig|A cero al principio, no en medio', anim: 'u6setadd',
          x: "Si el comptador porta números d'un altre dia, <b>posa'l a 0 al principi</b>. Però si poses «Posa el comptador a 0» al mig del programa, s'esborra tot el que havies comptat!|Si el contador trae números de otro día, <b>ponlo a 0 al principio</b>. Pero si pones «Pon el contador a 0» en medio del programa, ¡se borra todo lo que habías contado!",
          bad: "«Posa a 0» al mig: s'esborra el compte.|«Pon a 0» en medio: se borra la cuenta.", good: "«Posa a 0» com a primer bloc: el compte comença net.|«Pon a 0» como primer bloque: la cuenta empieza limpia." }
      ] },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy', w: { map: ['......', '>*b*H.', '......'] },
        t: "BIP! Les meves regles del mercat: les <b>estrelles</b> són fruites i cadascuna val <b>+1</b>. Cada <b>caixa</b> plena que deixo a una <b>parada</b> (la casa) val <b>+5</b>. Només puc portar una caixa cada vegada!|¡BIP! Mis reglas del mercado: las <b>estrellas</b> son frutas y cada una vale <b>+1</b>. Cada <b>caja</b> llena que dejo en un <b>puesto</b> (la casa) vale <b>+5</b>. ¡Solo puedo llevar una caja cada vez!" },
      { k: 'seq', ph: 'mans', q: "Un bon recol·lector té un pla. <b>Ordena el pla d'en Bit.</b>|Un buen recolector tiene un plan. <b>Ordena el plan de Bit.</b>",
        items: ['Posar el comptador a 0|Poner el contador a 0', 'Collir les fruites i sumar 1 per cadascuna|Recoger las frutas y sumar 1 por cada una', 'Agafar la caixa|Coger la caja', 'Deixar-la a la parada i sumar 5|Dejarla en el puesto y sumar 5', 'Comprovar que el comptador val el que toca|Comprobar que el contador vale lo que toca'],
        ex: "Primer s'inicialitza la variable, després es compta mentre es treballa i al final es comprova.|Primero se inicializa la variable, después se cuenta mientras se trabaja y al final se comprueba." },
      { k: 'parsons', ph: 'prova', q: "La primera feina del mercat! <b>Ordena els blocs</b>: en Bit cull la fruita, porta la caixa a la parada i ho compta tot (6 fruites).|¡El primer trabajo del mercado! <b>Ordena los bloques</b>: Bit recoge la fruta, lleva la caja al puesto y lo cuenta todo (6 frutas).",
        w: { map: ['......', '>*b#H.', '......'], count: 6, vname: 'comptador de fruites|contador de frutas' }, pool: TQ('f add:1 f p f f d add:5'), sol: TQ('f add:1 f p f f d add:5'),
        hint: "Primer la fruita (Endavant i Suma 1). Després la caixa: agafar-la, portar-la i, a la parada, deixar-la i sumar 5.|Primero la fruta (Adelante y Suma 1). Después la caja: cogerla, llevarla y, en el puesto, dejarla y sumar 5." },
      { k: 'build', ph: 'repte', q: "Els camps de fruita fan una U. Escriu la funció <b>«cull»</b> (avança i, si hi ha fruita, suma 1) i compta la fruita dels <b>dos camps</b> amb el mateix programa.|Los campos de fruta hacen una U. Escribe la función <b>«recoge»</b> (avanza y, si hay fruta, suma 1) y cuenta la fruta de los <b>dos campos</b> con el mismo programa.",
        w: { map: ['>*#*#', '....*', 'F#**#'], count: 5, vname: 'comptador de fruites|contador de frutas', alts: [{ map: ['>##*#', '....#', 'F*###'], count: 2 }] },
        pal: ['fwd', 'left', 'right', 'rep', 'if', 'add', 'call'], conds: ['gem'], fnEdit: ['A'], fnName: { A: 'cull|recoge' },
        sol: TQ('4{ A } r 2{ A } r 4{ A }'), solFns: { A: TQ('f if:gem{ add:1 }') },
        hint: "La funció: Endavant i «Si hi ha una estrella, suma 1». El camí: 4 vegades la funció, gira a la dreta, 2 vegades, gira a la dreta i 4 vegades més.|La función: Adelante y «Si hay una estrella, suma 1». El camino: 4 veces la función, gira a la derecha, 2 veces, gira a la derecha y 4 veces más." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de recol·lector: <b>cull 3 fruites</b> imaginàries dels arbres (estira't ben amunt tres vegades) i compta en veu alta. Ara <b>porta una caixa</b> pesada fins a la parada (camina amb els braços davant) i crida: «Més 5!» Quantes en tens?|Haz de recolector: <b>recoge 3 frutas</b> imaginarias de los árboles (estírate bien arriba tres veces) y cuenta en voz alta. Ahora <b>lleva una caja</b> pesada hasta el puesto (camina con los brazos delante) y grita: «¡Más 5!» ¿Cuántas tienes?" },
      { k: 'build', ph: 'repte', q: "Dues caixes, dues parades i fruites pel camí. Reparteix-ho tot i fes que el comptador digui <b>quantes fruites arriben al mercat</b>.|Dos cajas, dos puestos y frutas por el camino. Repártelo todo y haz que el contador diga <b>cuántas frutas llegan al mercado</b>.",
        w: { map: ['>*b#H.', '....#.', '..H*b.'], count: 12, vname: 'comptador de fruites|contador de frutas' },
        pal: ['fwd', 'left', 'right', 'pick', 'drop', 'rep', 'if', 'add'], conds: ['gem', 'box'],
        sol: TQ('f add:1 f p f f d add:5 r f f p r f add:1 f d add:5'),
        hint: "Fes-ho a trossos: fruita (+1), caixa, parada (+5); després baixa fins a la segona caixa, fruita (+1) i parada (+5). 1 + 5 + 1 + 5 = 12.|Hazlo a trozos: fruta (+1), caja, puesto (+5); después baja hasta la segunda caja, fruta (+1) y puesto (+5). 1 + 5 + 1 + 5 = 12." },
      { k: 'spot', ph: 'investiga', q: "El comptador de fruites havia d'acabar a 6, però acaba a 5. Executa'l i mira el marcador. <b>Toca el bloc que esborra el compte.</b>|El contador de frutas tenía que terminar en 6, pero termina en 5. Ejecútalo y mira el marcador. <b>Toca el bloque que borra la cuenta.</b>",
        w: { map: ['......', '>*b#H.', '......'], count: 6, vname: 'comptador de fruites|contador de frutas' }, prog: TPX('f add:1 f p f setv:0! f d add:5'),
        ex: "«Posa el comptador a 0» al mig del camí esborra la fruita que ja havia comptat. Havia d'anar al principi (o no ser-hi).|«Pon el contador a 0» en medio del camino borra la fruta que ya había contado. Tenía que ir al principio (o no estar)." },
      { k: 'build', ph: 'repte', q: "Tres camins de fruiters, un sol programa: en Bit agafa la caixa, cull la fruita que trobi pel camí i ho deixa tot a la parada. Cada camí té una quantitat diferent de fruita!|Tres caminos de frutales, un solo programa: Bit coge la caja, recoge la fruta que encuentre por el camino y lo deja todo en el puesto. ¡Cada camino tiene una cantidad diferente de fruta!",
        w: { map: ['.......', '>b*#*#H', '.......'], count: 7, vname: 'comptador de fruites|contador de frutas',
          alts: [{ map: ['.......', '>b**#*H', '.......'], count: 8 }, { map: ['.......', '>b####H', '.......'], count: 5 }] },
        pal: ['fwd', 'pick', 'drop', 'rep', 'if', 'add'], conds: ['gem', 'box'], sol: TQ('f p 4{ f if:gem{ add:1 } } f d add:5'),
        hint: "Primer agafa la caixa. Després, 4 vegades: Endavant i «Si hi ha una estrella, suma 1». Al final, ves a la parada, deixa la caixa i suma 5.|Primero coge la caja. Después, 4 veces: Adelante y «Si hay una estrella, suma 1». Al final, ve al puesto, deja la caja y suma 5." },
      { k: 'create', ph: 'crea', name: 'El recol·lector de fruita|El recolector de fruta',
        q: "<b>Projecte final de la unitat!</b> El comptador encara té <b>3 fruites</b> d'ahir. Posa'l a 0, cull les <b>4 fruites</b>, porta les <b>2 caixes</b> a les <b>2 parades</b> i fes que el comptador digui quantes fruites hi ha al mercat. Fes el pla abans de posar blocs!|<b>¡Proyecto final de la unidad!</b> El contador todavía tiene <b>3 frutas</b> de ayer. Ponlo a 0, recoge las <b>4 frutas</b>, lleva las <b>2 cajas</b> a los <b>2 puestos</b> y haz que el contador diga cuántas frutas hay en el mercado. ¡Haz el plan antes de poner bloques!",
        crit: ['Cull les 4 fruites i reparteix les 2 caixes|Recoge las 4 frutas y reparte las 2 cajas', 'Fa servir una variable: el comptador comença a 0|Usa una variable: el contador empieza en 0', 'Al final, el comptador val 14 (4 + 5 + 5)|Al final, el contador vale 14 (4 + 5 + 5)'],
        check: p => bitCountK(p, ['add', 'sub', 'setv']) ? null : "Funciona, però el projecte ha de fer servir el comptador: suma les fruites i les caixes!|Funciona, pero el proyecto tiene que usar el contador: ¡suma las frutas y las cajas!",
        w: { map: ['>..*..H', '.R...R.', '..b..*.', '*..~...', '.R..b.R', 'H..*...'], v0: 3, count: 14, vname: 'comptador de fruites|contador de frutas' },
        pal: ['fwd', 'left', 'right', 'pick', 'drop', 'rep', 'if', 'add', 'sub', 'setv'], conds: ['gem', 'box'],
        sol: TQ('setv:0 r 3{ f } add:1 l f f l f p r r 3{ f } r f f d add:5 r r 3{ f } add:1 l f r f p l f f r f add:1 f l f f d add:5 l 3{ f } add:1') },
      { k: 'quiz', ph: 'tanca', q: "Abans de programar amb una variable, quina pregunta et fas?|Antes de programar con una variable, ¿qué pregunta te haces?",
        opts: ['Què vull comptar i amb quin número comença?|¿Qué quiero contar y con qué número empieza?', 'De quin color és en Bit?|¿De qué color es Bit?', 'Quants blocs de gir tinc?|¿Cuántos bloques de giro tengo?'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "En Bit cull 2 fruites (+1 cadascuna) i deixa 1 caixa a la parada (+5). Quant val el comptador si començava a 0?|Bit recoge 2 frutas (+1 cada una) y deja 1 caja en el puesto (+5). ¿Cuánto vale el contador si empezaba en 0?",
        opts: ['7|7', '3|3', '10|10'], a: 0, keep: true, ex: "1 + 1 + 5 = 7.|1 + 1 + 5 = 7." },
      { k: 'feel', ph: 'tanca' }
    ] }
] };
