/* ===== Numi Tech · cursos =====
   Contingut propi de Numi (no és de cap altra plataforma). Les idees de fons —primer sense pantalla, predir abans
   d'executar (PRIMM), ordenar blocs (problemes de Parsons), usar → modificar → crear— són pedagogia publicada i
   d'ús lliure; els textos, els mons i els reptes són nostres.
   Cada curs: 8 unitats × 4 sessions (la 4a, projecte) ≈ un curs escolar d'una sessió per setmana.
   Les sessions sense «steps» surten com a «en preparació». */

// icones dels cursos (petites, en línia)
const TCI = {
  robot: '<svg viewBox="0 0 32 32"><path d="M16 4v4" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"/><circle cx="16" cy="4" r="2.2" fill="currentColor"/><rect x="6" y="8" width="20" height="15" rx="5" fill="currentColor"/><rect x="9.5" y="11.5" width="13" height="8" rx="3" fill="#fff" opacity=".9"/><circle cx="13" cy="15.5" r="1.8" fill="currentColor"/><circle cx="19" cy="15.5" r="1.8" fill="currentColor"/><rect x="9" y="24" width="4" height="4" rx="1.4" fill="currentColor"/><rect x="19" y="24" width="4" height="4" rx="1.4" fill="currentColor"/></svg>',
  robotica: '<svg viewBox="0 0 32 32"><rect x="6" y="9" width="20" height="13" rx="4" fill="currentColor"/><circle cx="10" cy="24" r="4" fill="currentColor"/><circle cx="22" cy="24" r="4" fill="currentColor"/><circle cx="10" cy="24" r="1.6" fill="#fff"/><circle cx="22" cy="24" r="1.6" fill="#fff"/><path d="M26 13c2 0 3 1 3 3s-1 3-3 3" fill="none" stroke="currentColor" stroke-width="2"/><path d="M28.5 10.5c3 1 4 3 4 5.5s-1 4.5-4 5.5" fill="none" stroke="currentColor" stroke-width="1.6" opacity=".6"/><rect x="9" y="12" width="9" height="5" rx="1.5" fill="#fff" opacity=".9"/></svg>',
  creadors: '<svg viewBox="0 0 32 32"><rect x="3" y="6" width="26" height="18" rx="4" fill="currentColor"/><path d="M13 11v8l7-4z" fill="#fff"/><rect x="9" y="26" width="14" height="3" rx="1.5" fill="currentColor"/></svg>',
  web: '<svg viewBox="0 0 32 32"><rect x="3" y="5" width="26" height="22" rx="4" fill="currentColor"/><rect x="3" y="5" width="26" height="6" rx="3" fill="currentColor" opacity=".7"/><circle cx="7" cy="8" r="1.2" fill="#fff"/><circle cx="11" cy="8" r="1.2" fill="#fff"/><path d="M12 16l-4 3 4 3M20 16l4 3-4 3M17.5 14.5l-3 9" stroke="#fff" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg>',
  digital: '<svg viewBox="0 0 32 32"><path d="M16 3l11 4v8c0 7-5 12-11 14C10 27 5 22 5 15V7z" fill="currentColor"/><path d="M11 16l4 4 7-8" stroke="#fff" stroke-width="2.8" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg>'
};
// què fa cada bloc (llegenda de les explicacions)
const TBLK = {
  fwd: "Avança una casella cap on mira.|Avanza una casilla hacia donde mira.",
  left: "Gira cap a la seva esquerra, sense moure's de casella.|Gira hacia su izquierda, sin moverse de casilla.",
  right: "Gira cap a la seva dreta, sense moure's de casella.|Gira hacia su derecha, sin moverse de casilla.",
  pick: "Agafa la caixa de la casella on és.|Coge la caja de la casilla donde está.",
  drop: "Deixa la caixa a la casa on és.|Deja la caja en la casa donde está.",
  rep: "Repeteix els blocs de dins tantes vegades com diu el número.|Repite los bloques de dentro tantas veces como dice el número."
};
const TBADGE = {
  algo: { id: 'algo', ico: '🧩', n: 'Primer algorisme|Primer algoritmo', d: 'Has escrit el teu primer programa.|Has escrito tu primer programa.' },
  gir: { id: 'gir', ico: '🧭', n: 'Brúixola|Brújula', d: 'Ja no et perds amb la dreta i l\'esquerra del robot.|Ya no te pierdes con la derecha y la izquierda del robot.' },
  bug: { id: 'bug', ico: '🐞', n: 'Caçabugs|Cazabugs', d: 'Has trobat i arreglat errors en programes.|Has encontrado y arreglado errores en programas.' },
  rep: { id: 'rep', ico: '📦', n: 'Repartidor/a|Repartidor/a', d: 'Primer projecte acabat: el repartiment de l\'illa.|Primer proyecto terminado: el reparto de la isla.' }
};
// blocs per escriure programes ràpid: TP('f f r f') → [{k:'fwd'},…]. També bucles, condicions, funcions i més:
//   f l r p d (endavant, esquerra, dreta, agafa, deixa) · w (espera) · A B (crida la funció) · c:r (pinta) · L:g (llum) · n:mi (nota)
//   + o +3 (suma al comptador) · 0 (comptador a 0) · 4[ … ] (repeteix 4) · u:goal[ … ] (repeteix fins que) · i:wall[ … ] e[ … ] (si… si no…)
//   Les condicions poden ser wall free freeR freeL goal gem fruit box home floor:r cnt:5. Amb «!» al final es marca el bloc (pas «investiga»).
function TP(s, mark) {
  const tk = String(s).replace(/\[/g, '[ ').replace(/\]/g, ' ] ').trim().split(/\s+/).filter(Boolean);
  let i = 0;
  const one = { f: 'fwd', l: 'left', r: 'right', p: 'pick', d: 'drop', w: 'wait', 0: 'zero' };
  const list = () => {
    const out = [];
    while (i < tk.length) {
      let t = tk[i++]; if (t === ']') break;
      const x = t.endsWith('!') || t.endsWith('![') ? (t = t.replace('!', ''), 1) : 0;
      let b;
      if (t.endsWith('[')) {
        const h = t.slice(0, -1);
        if (/^\d+$/.test(h)) b = { k: 'rep', n: +h, b: list() };
        else if (h.startsWith('u:')) b = { k: 'until', c: h.slice(2), b: list() };
        else if (h.startsWith('i:')) { b = { k: 'if', c: h.slice(2), b: list(), e: null }; if (tk[i] === 'e[') { i++; b.e = list(); } }
        else throw new Error('TP: ' + t);
      }
      else if (one[t]) b = { k: one[t] };
      else if (/^[A-B]$/.test(t)) b = { k: 'call', f: t };
      else if (t.startsWith('c:')) b = { k: 'paint', c: t.slice(2) };
      else if (t.startsWith('L:')) b = { k: 'light', c: t.slice(2) };
      else if (t.startsWith('n:')) b = { k: 'note', n: t.slice(2) };
      else if (/^\+\d*$/.test(t)) b = { k: 'inc', n: +t.slice(1) || 1 };
      else throw new Error('TP: ' + t);
      if (x && mark) b.x = 1;
      out.push(b);
    }
    return out;
  };
  return list();
}
// el mateix però marcant amb x el bloc que s'ha de tocar (pas «investiga»): 'f f r! f'
const TPX = s => TP(s, true);
// funcions i botons: TF({A:'f f r', '@a':'L:g'}) → {A:[…], '@a':[…]}
const TF = o => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, Array.isArray(v) ? v : TP(v)]));
// un bloc dibuixat dins d'un text o d'una opció
const tChip = k => () => `<span class="tb c-${BIT_CAT[k]} tpb inl"><span class="tbi">${BIT_ICO[k]}</span><span class="tbl">${bitLabel({ k })}</span></span>`;
const TK_MOV = ['fwd', 'left', 'right'], TK_REP = ['fwd', 'left', 'right', 'pick', 'drop'];
const bitCountK = (list, ks) => (list || []).reduce((n, b) => n + (ks.includes(b.k) ? 1 : 0) + bitCountK(b.b, ks) + bitCountK(b.e, ks), 0);

const TECH = [
  { id: 'robot', ico: TCI.robot, color: '#2F6BFF', name: 'Tech Robot|Tech Robot', short: 'Robot|Robot', age: '7-9 anys|7-9 años',
    desc: "Pensament computacional amb en Bit, el robot de l'illa: ordres, bucles, sensors, funcions i variables, amb reptes i projectes.|Pensamiento computacional con Bit, el robot de la isla: órdenes, bucles, sensores, funciones y variables, con retos y proyectos.",
    units: [
      { t: 'Ordres en ordre|Órdenes en orden', d: 'Algorismes, girs i errors|Algoritmos, giros y errores', color: '#2F6BFF', s: [
        { id: 'r1-1', t: 'Què és un algorisme?|¿Qué es un algoritmo?', min: 35, badge: 'algo',
          learn: ["Un algorisme és una llista d'instruccions en ordre per fer una tasca.|Un algoritmo es una lista de instrucciones en orden para hacer una tarea.",
            'Un programa és un algorisme que una màquina pot seguir.|Un programa es un algoritmo que una máquina puede seguir.',
            'Girar no mou en Bit de casella: només el fa mirar cap a un altre costat.|Girar no mueve a Bit de casilla: solo lo hace mirar hacia otro lado.'],
          steps: [
            { k: 'story', ph: 'missio', who: 'both', scene: 'illa', t: "Hola! Avui coneixeràs en <b>Bit</b>, el robot de l'illa. És molt treballador, però té un secret: <b>només fa exactament el que li dius</b>. Ni més, ni menys.|¡Hola! Hoy conocerás a <b>Bit</b>, el robot de la isla. Es muy trabajador, pero tiene un secreto: <b>solo hace exactamente lo que le dices</b>. Ni más, ni menos." },
            { k: 'story', ph: 'missio', who: 'bit', scene: 'illa', mood: 'happy', t: "BIP BIP! Hola! Per moure'm necessito <b>ordres</b>. Si me les dones bé, arribaré on vulguis. Si me les dones malament… pam! Contra una roca.|¡BIP BIP! ¡Hola! Para moverme necesito <b>órdenes</b>. Si me las das bien, llegaré donde quieras. Si me las das mal… ¡pum! Contra una roca." },
            { k: 'learn', ph: 'descobreix', cards: [
              { k: 'Algorisme|Algoritmo', t: "Què és un algorisme?|¿Qué es un algoritmo?", anim: 'algo',
                x: "Un <span class='hl'>algorisme</span> és una llista d'instruccions, <b>en ordre</b>, per aconseguir alguna cosa. Una recepta, les instruccions d'un joc de construcció o el camí per anar a l'escola són algorismes.|Un <span class='hl'>algoritmo</span> es una lista de instrucciones, <b>en orden</b>, para conseguir algo. Una receta, las instrucciones de un juego de construcción o el camino para ir al cole son algoritmos.",
                tip: "Els ordinadors i els robots no endevinen què vols: només saben seguir algorismes.|Los ordenadores y los robots no adivinan lo que quieres: solo saben seguir algoritmos." },
              { k: "L'ordre|El orden", t: "L'ordre importa|El orden importa", anim: 'order',
                x: "Si canvies l'ordre dels passos, el resultat canvia. Primer el mitjó i després la sabata… a l'inrevés no funciona!|Si cambias el orden de los pasos, el resultado cambia. Primero el calcetín y después el zapato… ¡al revés no funciona!" },
              { k: "Les ordres d'en Bit|Las órdenes de Bit", t: 'Tres ordres per començar|Tres órdenes para empezar', demo: { w: { map: ['.....', '>##..', '..##F'] }, prog: TP('f f r f l f f') },
                x: "En Bit entén tres ordres: <b>Endavant</b> (avança una casella cap on mira), <b>Gira a l'esquerra</b> i <b>Gira a la dreta</b>. Mira com el programa de la dreta el porta a la bandera, bloc a bloc.|Bit entiende tres órdenes: <b>Adelante</b> (avanza una casilla hacia donde mira), <b>Gira a la izquierda</b> y <b>Gira a la derecha</b>. Mira cómo el programa lo lleva a la bandera, bloque a bloque." },
              { k: 'Compte!|¡Cuidado!', t: 'Girar no el mou|Girar no lo mueve', anim: 'turn',
                x: "Quan en Bit gira, <b>es queda a la mateixa casella</b>: només canvia cap on mira. Per això, després d'un gir gairebé sempre cal un <b>Endavant</b>.|Cuando Bit gira, <b>se queda en la misma casilla</b>: solo cambia hacia dónde mira. Por eso, después de un giro casi siempre hace falta un <b>Adelante</b>.",
                bad: "«Gira a la dreta» el mou una casella a la dreta.|«Gira a la derecha» lo mueve una casilla a la derecha.", good: "«Gira a la dreta» només el fa mirar a la seva dreta.|«Gira a la derecha» solo lo hace mirar a su derecha." },
              { k: 'Programa|Programa', t: 'Un programa és un algorisme per a una màquina|Un programa es un algoritmo para una máquina', demo: { w: { map: ['>#R', '.#F'] }, prog: TP('f r f l f') },
                x: "Quan escrivim l'algorisme amb blocs que en Bit entén, en diem <span class='hl'>programa</span>. En tocar <b>Executa</b>, en Bit fa els blocs <b>un a un, de dalt a baix</b>.|Cuando escribimos el algoritmo con bloques que Bit entiende, lo llamamos <span class='hl'>programa</span>. Al tocar <b>Ejecuta</b>, Bit hace los bloques <b>uno a uno, de arriba abajo</b>." }
            ] },
            { k: 'quiz', ph: 'missio', q: "Una llista d'instruccions, en ordre, per fer una tasca es diu <b>algorisme</b>. Quina d'aquestes coses és un algorisme?|Una lista de instrucciones, en orden, para hacer una tarea se llama <b>algoritmo</b>. ¿Cuál de estas cosas es un algoritmo?",
              opts: ['La recepta per fer un pastís, pas a pas|La receta para hacer un pastel, paso a paso', 'Un pastís de xocolata|Un pastel de chocolate', 'Una cuina molt gran|Una cocina muy grande'], a: 0,
              ex: "La recepta diu què has de fer i en quin ordre: és un algorisme. El pastís és el resultat.|La receta dice qué tienes que hacer y en qué orden: es un algoritmo. El pastel es el resultado." },
            { k: 'seq', ph: 'mans', q: "Els algorismes són a tot arreu. <b>Ordena els passos</b> per rentar-te les dents.|Los algoritmos están en todas partes. <b>Ordena los pasos</b> para lavarte los dientes.",
              items: ['Agafa el raspall|Coge el cepillo', 'Posa-hi pasta de dents|Ponle pasta de dientes', "Raspalla't les dents|Cepíllate los dientes", "Esbandeix-te la boca|Enjuágate la boca"],
              ex: "Si canvies l'ordre, no funciona: en un algorisme, <b>l'ordre importa</b>.|Si cambias el orden, no funciona: en un algoritmo, <b>el orden importa</b>." },
            { k: 'unplug', ph: 'mans', ico: '🤖', title: 'Fes de robot|Haz de robot',
              t: "Necessites algú de casa. Una persona fa de <b>programador/a</b> i l'altra, de <b>robot</b>.|Necesitas a alguien de casa. Una persona hace de <b>programador/a</b> y la otra, de <b>robot</b>.",
              steps: ["Trieu un lloc on ha d'arribar el robot: la porta de la cuina, el sofà…|Elegid un sitio al que tiene que llegar el robot: la puerta de la cocina, el sofá…",
                "El programador només pot dir tres ordres: <b>un pas endavant</b>, <b>gira a l'esquerra</b> i <b>gira a la dreta</b>.|El programador solo puede decir tres órdenes: <b>un paso adelante</b>, <b>gira a la izquierda</b> y <b>gira a la derecha</b>.",
                "El robot fa EXACTAMENT el que li diuen, encara que sigui un error.|El robot hace EXACTAMENTE lo que le dicen, aunque sea un error.",
                "Quan arribeu, canvieu els papers.|Cuando lleguéis, cambiad los papeles."],
              tip: "Si el robot xoca amb un moble, no passa res: és un <b>error</b> del programa. Torneu a començar i arregleu-lo.|Si el robot choca con un mueble, no pasa nada: es un <b>error</b> del programa. Volved a empezar y arregladlo." },
            { k: 'hand', ph: 'prova', q: 'Mou tu en Bit fins a la bandera amb els botons.|Mueve tú a Bit hasta la bandera con los botones.',
              w: { map: ['...R.', '>##..', '..#..', '..##F'] } },
            { k: 'story', ph: 'prova', who: 'numi', t: "El que acabes de fer és un <b>programa</b>: una llista d'ordres que una màquina pot seguir. Els programadors no mouen el robot amb la mà: <b>primer escriuen el programa</b> i després l'executen.|Lo que acabas de hacer es un <b>programa</b>: una lista de órdenes que una máquina puede seguir. Los programadores no mueven el robot con la mano: <b>primero escriben el programa</b> y después lo ejecutan." },
            { k: 'predict', ph: 'prova', q: 'En Bit seguirà aquest programa. <b>On acabarà?</b> Tria A, B o C.|Bit seguirá este programa. <b>¿Dónde terminará?</b> Elige A, B o C.',
              w: { map: ['..C..', 'A###B', '..#..', '..^..'] }, prog: TP('f f r f f'), a: 'B', ex: "En Bit mira amunt i gira a la seva dreta: queda mirant cap a la dreta.|Bit mira arriba y gira a su derecha: queda mirando hacia la derecha." },
            { k: 'quiz', ph: 'investiga', w: { map: ['...', '.>.', '...'] }, q: "En Bit mira cap a la dreta. Si li dius <b>Gira a l'esquerra</b>, cap on mirarà?|Bit mira hacia la derecha. Si le dices <b>Gira a la izquierda</b>, ¿hacia dónde mirará?",
              opts: ['↑ Amunt|↑ Arriba', '↓ Avall|↓ Abajo', '← Esquerra|← Izquierda'], a: 0, ex: "Un gir és un quart de volta: de mirar a la dreta passa a mirar amunt.|Un giro es un cuarto de vuelta: de mirar a la derecha pasa a mirar arriba." },
            { k: 'move', ph: 'pausa', secs: 25, t: "Aixeca't i fes de Bit: <b>2 passos endavant, gira a la dreta, 1 pas endavant, gira a l'esquerra</b>. Ara, a l'inrevés, per tornar al lloc!|Levántate y haz de Bit: <b>2 pasos adelante, gira a la derecha, 1 paso adelante, gira a la izquierda</b>. ¡Ahora, al revés, para volver al sitio!" },
            { k: 'build', ph: 'repte', q: "El teu primer programa! Posa blocs i toca <b>Executa</b> per portar en Bit a la bandera.|¡Tu primer programa! Pon bloques y toca <b>Ejecuta</b> para llevar a Bit a la bandera.",
              w: { map: ['.....', '>###F', '.....'] }, pal: TK_MOV, sol: TP('f f f f'), hint: 'Compta quantes caselles hi ha fins a la bandera.|Cuenta cuántas casillas hay hasta la bandera.' },
            { k: 'build', ph: 'repte', q: 'Ara hi ha un revolt. Porta en Bit a la bandera.|Ahora hay una curva. Lleva a Bit a la bandera.',
              w: { map: ['>##RR', 'R.#RR', 'R.#..', 'R.##F'] }, pal: TK_MOV, sol: TP('f f r f f f l f f'), hint: 'Primer avança fins al revolt i després gira cap a la bandera.|Primero avanza hasta la curva y después gira hacia la bandera.' },
            { k: 'build', ph: 'repte', q: "Compte amb les roques i l'aigua! Fes que en Bit arribi a la bandera.|¡Cuidado con las rocas y el agua! Haz que Bit llegue a la bandera.",
              w: { map: ['>#R~.', '.##R.', 'R.###F', '~~....'].map(r => r.padEnd(6, '.')) }, pal: TK_MOV, sol: TP('f r f l f r f l f f f'), hint: 'Fes-ho a trossos: primer fins a la primera baixada.|Hazlo a trozos: primero hasta la primera bajada.' },
            { k: 'build', ph: 'repte', q: "Ui! Aquest programa té un error i en Bit xoca. <b>Troba'l i arregla'l</b> (toca un bloc per esborrar-lo o moure'l).|¡Uy! Este programa tiene un error y Bit choca. <b>Encuéntralo y arréglalo</b> (toca un bloque para borrarlo o moverlo).",
              w: { map: ['>###R', '...#.', '...F.'] }, pal: TK_MOV, prog: TP('f f f f r f f'), sol: TP('f f f r f f'), hint: 'Mira quantes vegades avança abans de girar.|Mira cuántas veces avanza antes de girar.' },
            { k: 'create', ph: 'crea', name: 'El meu primer camí|Mi primer camino', q: "Ara decideixes tu! Porta en Bit a la bandera <b>passant per les 3 estrelles</b>. Hi ha molts camins possibles: inventa el teu.|¡Ahora decides tú! Lleva a Bit a la bandera <b>pasando por las 3 estrellas</b>. Hay muchos caminos posibles: inventa el tuyo.",
              crit: ['Recull les 3 estrelles|Recoge las 3 estrellas', 'Acaba a la bandera|Termina en la bandera'],
              w: { map: ['>.*...', '..R.*.', '.R..R.', '..*...', 'R...RF'] }, pal: TK_MOV, sol: TP('f f f f r f r f l f f r f l l f f f r f') },
            { k: 'quiz', ph: 'tanca', q: 'Per acabar: què és un <b>algorisme</b>?|Para terminar: ¿qué es un <b>algoritmo</b>?', opts: ["Instruccions en ordre per fer una tasca|Instrucciones en orden para hacer una tarea", 'Un robot que pensa sol|Un robot que piensa solo', 'Un error del programa|Un error del programa'], a: 0 },
            { k: 'quiz', ph: 'tanca', q: "Quin bloc fa que en Bit canviï de casella?|¿Qué bloque hace que Bit cambie de casilla?", opts: [tChip('fwd'), tChip('right'), tChip('left')], a: 0, ex: "Els girs el fan mirar cap a un altre costat, però no el mouen.|Los giros lo hacen mirar hacia otro lado, pero no lo mueven." },
            { k: 'feel', ph: 'tanca' }
          ] },
        { id: 'r1-2', t: "La dreta i l'esquerra d'en Bit|La derecha y la izquierda de Bit", min: 35, badge: 'gir',
          learn: ["La dreta i l'esquerra depenen de cap on mira en Bit.|La derecha y la izquierda dependen de hacia dónde mira Bit.",
            'Dos girs iguals fan mitja volta.|Dos giros iguales hacen media vuelta.', "Per programar un robot, posa't al seu lloc.|Para programar un robot, ponte en su lugar."],
          steps: [
            { k: 'quiz', ph: 'recorda', q: 'Recordes què fa el bloc <b>Gira a la dreta</b>?|¿Recuerdas qué hace el bloque <b>Gira a la derecha</b>?', opts: ['En Bit es gira cap a la seva dreta, sense canviar de casella|Bit se gira hacia su derecha, sin cambiar de casilla', 'En Bit va una casella cap a la dreta|Bit va una casilla hacia la derecha', 'En Bit fa una volta sencera|Bit da una vuelta entera'], a: 0 },
            { k: 'story', ph: 'missio', who: 'both', scene: 'poble', t: "Avui en Bit ha de repartir el diari pel poble. Però hi ha un problema: quan en Bit ve cap a tu, <b>la seva dreta és la teva esquerra</b>!|Hoy Bit tiene que repartir el periódico por el pueblo. Pero hay un problema: cuando Bit viene hacia ti, ¡<b>su derecha es tu izquierda</b>!" },
            { k: 'learn', ph: 'descobreix', cards: [
              { k: 'Punt de vista|Punto de vista', t: "La dreta de qui?|¿La derecha de quién?", anim: 'mirror',
                x: "La dreta i l'esquerra depenen de <b>cap on mira cadascú</b>. Si en Bit ve cap a tu, la seva dreta queda a la teva esquerra.|La derecha y la izquierda dependen de <b>hacia dónde mira cada uno</b>. Si Bit viene hacia ti, su derecha queda a tu izquierda." },
              { k: 'Quatre direccions|Cuatro direcciones', t: 'Una volta sencera|Una vuelta entera', demo: { w: { map: ['...', '.^.', '...'] }, prog: TP('r r r r'), speed: 1000 },
                x: "Cada gir és un <b>quart de volta</b>. Amb quatre girs iguals, en Bit dona la volta sencera i torna a mirar on mirava.|Cada giro es un <b>cuarto de vuelta</b>. Con cuatro giros iguales, Bit da la vuelta entera y vuelve a mirar donde miraba." },
              { k: 'Mitja volta|Media vuelta', t: 'Dos girs iguals|Dos giros iguales', demo: { w: { map: ['.^.', '.#.', '.F.'] }, prog: TP('r r f f') },
                x: "Dos girs iguals fan <b>mitja volta</b>: si en Bit mira amunt i gira dues vegades, acaba mirant avall.|Dos giros iguales hacen <b>media vuelta</b>: si Bit mira arriba y gira dos veces, acaba mirando abajo." },
              { k: 'El truc|El truco', t: "Posa't al seu lloc|Ponte en su lugar", demo: { w: { map: ['..v..', '..#..', 'F##..'] }, prog: TP('f f r f f') },
                x: "En Bit mira avall i gira <b>a la seva dreta</b>… i a la pantalla va cap a l'<b>esquerra</b>! Imagina que ets en Bit: mira cap on mira ell i pensa on tens la mà dreta.|Bit mira abajo y gira <b>a su derecha</b>… ¡y en la pantalla va hacia la <b>izquierda</b>! Imagina que eres Bit: mira hacia donde mira él y piensa dónde tienes la mano derecha.",
                tip: "També pots girar la tauleta o el cap. No és fer trampa: és el que fan els programadors de robots!|También puedes girar la tablet o la cabeza. No es hacer trampa: ¡es lo que hacen los programadores de robots!" }
            ] },
            { k: 'unplug', ph: 'mans', ico: '🪞', title: 'El mirall|El espejo', t: 'Amb algú de casa:|Con alguien de casa:',
              steps: ["Poseu-vos cara a cara.|Poneos cara a cara.", "Tots dos aixequeu la mà <b>dreta</b>. Les mans queden a costats diferents!|Los dos levantad la mano <b>derecha</b>. ¡Las manos quedan en lados diferentes!",
                "Ara poseu-vos l'un darrere l'altre, mirant cap al mateix lloc, i torneu-ho a fer.|Ahora poneos uno detrás del otro, mirando hacia el mismo sitio, y volved a hacerlo.",
                "Conclusió: per saber cap on gira algú, <b>posa't al seu lloc</b>.|Conclusión: para saber hacia dónde gira alguien, <b>ponte en su lugar</b>."] },
            { k: 'story', ph: 'prova', who: 'numi', w: { map: ['...', '.v.', '...'] }, t: "Truc de programador: per saber cap on girarà, <b>imagina't que ets en Bit</b>. Si mira avall (cap a tu) i gira a la seva dreta, a la pantalla anirà cap a l'<b>esquerra</b>.|Truco de programador: para saber hacia dónde girará, <b>imagina que eres Bit</b>. Si mira abajo (hacia ti) y gira a su derecha, en la pantalla irá hacia la <b>izquierda</b>." },
            { k: 'quiz', ph: 'prova', w: { map: ['...', '.v.', '...'] }, q: 'En Bit mira avall. Si gira <b>a la dreta</b>, cap on mirarà a la pantalla?|Bit mira abajo. Si gira <b>a la derecha</b>, ¿hacia dónde mirará en la pantalla?',
              opts: ["← Cap a l'esquerra de la pantalla|← Hacia la izquierda de la pantalla", '→ Cap a la dreta de la pantalla|→ Hacia la derecha de la pantalla', '↑ Amunt|↑ Arriba'], a: 0, ex: "Posa't al lloc d'en Bit: la seva dreta és la teva esquerra.|Ponte en el lugar de Bit: su derecha es tu izquierda." },
            { k: 'hand', ph: 'mans', q: "En Bit comença mirant avall. Porta'l fins a la bandera.|Bit empieza mirando abajo. Llévalo hasta la bandera.", w: { map: ['..v..', '..#..', '###..', 'F....'] } },
            { k: 'predict', ph: 'prova', q: 'On acabarà en Bit?|¿Dónde terminará Bit?', w: { map: ['...A.', '...#.', '.B##<', '...#.', '...C.'] }, prog: TP('f l f f'), a: 'C', ex: "En Bit mira a l'esquerra; si gira a la seva esquerra, queda mirant avall.|Bit mira a la izquierda; si gira a su izquierda, queda mirando abajo." },
            { k: 'predict', ph: 'prova', q: 'I ara? Fixa\'t en els dos girs seguits.|¿Y ahora? Fíjate en los dos giros seguidos.', w: { map: ['..B..', '..#..', '..^#C', '..#..', '..A..'] }, prog: TP('r r f f'), a: 'A', ex: 'Dos girs a la dreta fan mitja volta: ara mira avall.|Dos giros a la derecha hacen media vuelta: ahora mira abajo.' },
            { k: 'spot', ph: 'investiga', q: 'Aquest programa porta en Bit a la bandera. <b>Toca el bloc que el fa girar cap a la bandera.</b>|Este programa lleva a Bit a la bandera. <b>Toca el bloque que lo hace girar hacia la bandera.</b>', w: { map: ['....', '..F.', '>##.'] }, prog: TPX('f f l! f') },
            { k: 'move', ph: 'pausa', secs: 25, t: "Fes <b>4 girs a la dreta</b>, un quart de volta cada vegada. On mires ara? Exacte: on miraves al principi! Ara fes-ne 4 a l'esquerra.|Haz <b>4 giros a la derecha</b>, un cuarto de vuelta cada vez. ¿Dónde miras ahora? Exacto: ¡donde mirabas al principio! Ahora haz 4 a la izquierda." },
            { k: 'build', ph: 'repte', q: 'Porta el diari fins a la bandera. En Bit comença mirant avall!|Lleva el periódico hasta la bandera. ¡Bit empieza mirando abajo!', w: { map: ['vRF..', '#R#..', '###..'] }, pal: TK_MOV, sol: TP('f f l f f l f f'), hint: "Posa't al lloc d'en Bit abans de cada gir.|Ponte en el lugar de Bit antes de cada giro." },
            { k: 'build', ph: 'repte', q: 'Un camí en forma de U. Porta en Bit a la bandera.|Un camino en forma de U. Lleva a Bit a la bandera.', w: { map: ['>###.', 'RRR#.', 'F###.'] }, pal: TK_MOV, sol: TP('f f f r f f r f f f'), hint: 'Quan baixa, mira avall. Per tornar cap a l\'esquerra, cap on ha de girar?|Cuando baja, mira abajo. Para volver hacia la izquierda, ¿hacia dónde tiene que girar?' },
            { k: 'build', ph: 'repte', q: "Un camí ple d'aigua. Compte amb cada gir!|Un camino lleno de agua. ¡Cuidado con cada giro!", w: { map: ['..##F.', '~~#~~.', '###~..', '#~~~..', '^.....'] }, pal: TK_MOV, sol: TP('f f r f f l f f r f f'), hint: 'Primer amunt, després a la dreta, després amunt…|Primero arriba, después a la derecha, después arriba…' },
            { k: 'create', ph: 'crea', name: 'El repartidor de diaris|El repartidor de periódicos', q: 'Reparteix el diari a les <b>3 estrelles</b> i acaba a la bandera. En Bit comença mirant avall.|Reparte el periódico en las <b>3 estrellas</b> y termina en la bandera. Bit empieza mirando abajo.',
              crit: ['Passa per les 3 estrelles|Pasa por las 3 estrellas', 'Acaba a la bandera|Termina en la bandera'], w: { map: ['..v..*', '.R..R.', '*..R..', '..R..*', '.....F'] }, pal: TK_MOV, sol: TP('f f r f f r f f r f f f f f r f f f f') },
            { k: 'quiz', ph: 'tanca', q: "En Bit mira a l'esquerra (←) i gira a la dreta. Cap on mira ara?|Bit mira a la izquierda (←) y gira a la derecha. ¿Hacia dónde mira ahora?", opts: ['↑ Amunt|↑ Arriba', '↓ Avall|↓ Abajo', '→ Dreta|→ Derecha'], a: 0 },
            { k: 'quiz', ph: 'tanca', q: 'Quin és el millor truc per no equivocar-te amb els girs?|¿Cuál es el mejor truco para no equivocarte con los giros?', opts: ["Posar-me al lloc d'en Bit i mirar cap on mira ell|Ponerme en el lugar de Bit y mirar hacia donde mira él", 'Girar sempre a la dreta|Girar siempre a la derecha', "Provar a l'atzar fins que surti|Probar al azar hasta que salga"], a: 0 },
            { k: 'feel', ph: 'tanca' }
          ] },
        { id: 'r1-3', t: "Caça l'error|Caza el error", min: 35, badge: 'bug',
          learn: ['Un error en un programa es diu <i>bug</i>.|Un error en un programa se llama <i>bug</i>.', "Depurar és trobar l'error i canviar només el bloc equivocat.|Depurar es encontrar el error y cambiar solo el bloque equivocado.", 'Amb «Pas a pas» veus què fa cada bloc.|Con «Paso a paso» ves qué hace cada bloque.'],
          steps: [
            { k: 'quiz', ph: 'recorda', w: { map: ['...', '.^.', '...'] }, q: 'En Bit mira amunt i fa: <b>Gira a la dreta, Gira a la dreta</b>. Cap on mira?|Bit mira arriba y hace: <b>Gira a la derecha, Gira a la derecha</b>. ¿Hacia dónde mira?', opts: ['↓ Avall|↓ Abajo', '↑ Amunt|↑ Arriba', '→ Dreta|→ Derecha'], a: 0, ex: 'Dos girs iguals: mitja volta.|Dos giros iguales: media vuelta.' },
            { k: 'story', ph: 'missio', who: 'numi', scene: 'taller', t: "Als programadors els passa sovint: escriuen un programa i… no fa el que volien! Un error en un programa es diu <b>bug</b>, que en anglès vol dir «bestiola».|A los programadores les pasa a menudo: escriben un programa y… ¡no hace lo que querían! Un error en un programa se llama <b>bug</b>, que en inglés quiere decir «bicho»." },
            { k: 'story', ph: 'missio', who: 'numi', title: 'La bestiola de 1947|El bicho de 1947', t: "El 1947, un equip de científics va trobar una arna atrapada dins d'un ordinador gegant que fallava. La van enganxar al quadern amb una nota! La paraula <i>bug</i> ja existia, però aquesta història la va fer famosa. Buscar i arreglar errors es diu <b>depurar</b>.|En 1947, un equipo de científicos encontró una polilla atrapada dentro de un ordenador gigante que fallaba. ¡La pegaron en el cuaderno con una nota! La palabra <i>bug</i> ya existía, pero esta historia la hizo famosa. Buscar y arreglar errores se llama <b>depurar</b>." },
            { k: 'learn', ph: 'descobreix', cards: [
              { k: 'Bug|Bug', t: 'Què és un bug?|¿Qué es un bug?', anim: 'bug',
                x: "Un <span class='hl'>bug</span> és un error en un programa: un bloc que no hauria de ser-hi, que falta o que està malament. Tots els programadors en fan; els bons els saben <b>trobar</b>.|Un <span class='hl'>bug</span> es un error en un programa: un bloque que no debería estar, que falta o que está mal. Todos los programadores los cometen; los buenos los saben <b>encontrar</b>." },
              { k: 'Tipus de bugs|Tipos de bugs', t: 'Els quatre bugs més habituals|Los cuatro bugs más habituales', anim: 'bugtypes',
                x: "Gairebé sempre és un d'aquests: <b>falta</b> un bloc, <b>sobra</b> un bloc, un bloc <b>equivocat</b> (esquerra en lloc de dreta) o els blocs en <b>mal ordre</b>.|Casi siempre es uno de estos: <b>falta</b> un bloque, <b>sobra</b> un bloque, un bloque <b>equivocado</b> (izquierda en lugar de derecha) o los bloques en <b>mal orden</b>." },
              { k: 'Pas a pas|Paso a paso', t: 'A càmera lenta|A cámara lenta', anim: 'step',
                x: "El botó <b>Pas a pas</b> fa un sol bloc cada vegada. Així veus exactament què fa cada bloc i on comença el problema.|El botón <b>Paso a paso</b> hace un solo bloque cada vez. Así ves exactamente qué hace cada bloque y dónde empieza el problema." },
              { k: 'Arreglar|Arreglar', t: 'Canvia només el que falla|Cambia solo lo que falla', demo: { w: { map: ['..F.', '>##.', 'RRRR'] }, prog: TP('f f r f'), speed: 950 },
                x: "Aquí en Bit gira a la dreta i xoca. L'error és <b>un sol bloc</b>: havia de girar a l'esquerra. Quan el trobis, canvia només aquest bloc i torna-ho a provar.|Aquí Bit gira a la derecha y choca. El error es <b>un solo bloque</b>: tenía que girar a la izquierda. Cuando lo encuentres, cambia solo ese bloque y vuelve a probar.",
                bad: "Esborrar-ho tot i començar de nou cada vegada.|Borrarlo todo y empezar de nuevo cada vez.", good: "Trobar el bloc que falla i canviar només aquest.|Encontrar el bloque que falla y cambiar solo ese." }
            ] },
            { k: 'story', ph: 'prova', who: 'bit', mood: 'happy', t: 'Com es caça un bug? Així:|¿Cómo se caza un bug? Así:', box: "<ol><li><b>Executa</b> el programa i mira on falla.</li><li>Toca <b>Pas a pas</b>: faig un sol bloc cada vegada.</li><li>Quan trobis el bloc equivocat, canvia <b>només aquell</b>.</li><li>Torna-ho a provar.</li></ol>|<ol><li><b>Ejecuta</b> el programa y mira dónde falla.</li><li>Toca <b>Paso a paso</b>: hago un solo bloque cada vez.</li><li>Cuando encuentres el bloque equivocado, cambia <b>solo ese</b>.</li><li>Vuelve a probarlo.</li></ol>" },
            { k: 'spot', ph: 'investiga', q: 'Aquest programa hauria de portar en Bit a la bandera, però xoca. Pots executar-lo per veure-ho. <b>Toca el bloc equivocat.</b>|Este programa debería llevar a Bit a la bandera, pero choca. Puedes ejecutarlo para verlo. <b>Toca el bloque equivocado.</b>', w: { map: ['..F.', '>##.', 'RRRR'] }, prog: TPX('f f r! f'), ex: "És el gir: a la dreta en Bit mira avall, cap a les roques. Havia de girar a l'esquerra.|Es el giro: a la derecha Bit mira abajo, hacia las rocas. Tenía que girar a la izquierda." },
            { k: 'spot', ph: 'investiga', q: 'Aquí sobra un bloc. <b>Toca el que sobra.</b>|Aquí sobra un bloque. <b>Toca el que sobra.</b>', w: { map: ['..F.', '>##R'] }, prog: TPX('f f f! l f'), ex: 'El tercer «Endavant» el fa xocar amb la roca.|El tercer «Adelante» lo hace chocar con la roca.' },
            { k: 'build', ph: 'repte', q: "En Bit s'ha de quedar a la bandera, però se'n passa. Arregla el programa.|Bit tiene que quedarse en la bandera, pero se pasa. Arregla el programa.", w: { map: ['>###F.', '......'], paths: false }, pal: TK_MOV, prog: TP('f f f f f'), sol: TP('f f f f'), hint: "Toca l'últim bloc i esborra'l.|Toca el último bloque y bórralo." },
            { k: 'build', ph: 'repte', q: 'Aquest programa s\'equivoca en un gir. Fes-lo <b>pas a pas</b> per trobar on.|Este programa se equivoca en un giro. Hazlo <b>paso a paso</b> para encontrar dónde.', w: { map: ['####.', '#R.#.', '#R.F.', '^....'] }, pal: TK_MOV, prog: TP('f f f r f f f l f f'), sol: TP('f f f r f f f r f f'), hint: "L'últim gir ha de fer que en Bit miri avall.|El último giro tiene que hacer que Bit mire abajo." },
            { k: 'move', ph: 'pausa', secs: 25, t: "Fes 5 salts de granota endavant, gira a la dreta i fes 3 passes de gegant. Oh, un bug! Has girat cap a l'altre costat? Torna enrere i arregla-ho!|Haz 5 saltos de rana hacia delante, gira a la derecha y da 3 pasos de gigante. ¡Oh, un bug! ¿Has girado hacia el otro lado? ¡Vuelve atrás y arréglalo!" },
            { k: 'parsons', ph: 'repte', q: 'Els blocs estan barrejats. <b>Posa\'ls en ordre</b> perquè en Bit arribi a la bandera.|Los bloques están mezclados. <b>Ponlos en orden</b> para que Bit llegue a la bandera.', w: { map: ['>#RR', 'R#RR', 'R##F'] }, pool: TP('f r f f l f f'), sol: TP('f r f f l f f'), hint: 'Primer avança una casella i després gira cap avall.|Primero avanza una casilla y después gira hacia abajo.' },
            { k: 'build', ph: 'repte', q: 'Aquest té <b>dos</b> errors: un gir equivocat i un bloc que falta. Troba\'ls tots dos.|Este tiene <b>dos</b> errores: un giro equivocado y un bloque que falta. Encuéntralos los dos.', w: { map: ['vR.F.', '#R.#.', '####.', '.....'] }, pal: TK_MOV, prog: TP('f f r f f f l f'), sol: TP('f f l f f f l f f'), hint: "En Bit mira avall: per anar cap a la dreta de la pantalla ha de girar a la seva esquerra.|Bit mira abajo: para ir hacia la derecha de la pantalla tiene que girar a su izquierda." },
            { k: 'create', ph: 'crea', name: 'Un camí per endevinar|Un camino para adivinar', q: "Crea un camí fins a la bandera <b>amb almenys 3 girs</b>. Després ensenya'l a algú de casa i, abans d'executar-lo, pregunta-li: <b>on creus que acabarà en Bit?</b>|Crea un camino hasta la bandera <b>con al menos 3 giros</b>. Después enséñaselo a alguien de casa y, antes de ejecutarlo, pregúntale: <b>¿dónde crees que terminará Bit?</b>",
              crit: ['Almenys 3 girs|Al menos 3 giros', 'Acaba a la bandera|Termina en la bandera'], check: p => bitCountK(p, ['left', 'right']) >= 3 ? null : "Funciona, però hi ha menys de 3 girs. Fes un camí més divertit!|Funciona, pero hay menos de 3 giros. ¡Haz un camino más divertido!",
              w: { map: ['>.....', '..R...', '....R.', '.R....', '...R.F'] }, pal: TK_MOV, sol: TP('f r f f l f f r f l f f r f') },
            { k: 'quiz', ph: 'tanca', q: 'Què vol dir <b>depurar</b> un programa?|¿Qué quiere decir <b>depurar</b> un programa?', opts: ['Buscar i arreglar els errors|Buscar y arreglar los errores', 'Esborrar-lo i començar de nou|Borrarlo y empezar de nuevo', 'Fer-lo més llarg|Hacerlo más largo'], a: 0 },
            { k: 'quiz', ph: 'tanca', q: 'Quin botó t\'ajuda a veure exactament on falla un programa?|¿Qué botón te ayuda a ver exactamente dónde falla un programa?', opts: ['Pas a pas|Paso a paso', 'Buida el programa|Vacía el programa', 'Velocitat ×2|Velocidad ×2'], a: 0 },
            { k: 'feel', ph: 'tanca' }
          ] },
        { id: 'r1-4', t: "Projecte: el repartidor de l'illa|Proyecto: el repartidor de la isla", min: 40, proj: true, badge: 'rep',
          learn: ['Les ordres «Agafa» i «Deixa» fan accions sense moure en Bit.|Las órdenes «Coge» y «Deja» hacen acciones sin mover a Bit.', 'Descompondre és partir un problema gran en trossos petits.|Descomponer es partir un problema grande en trozos pequeños.', 'Has acabat el teu primer projecte!|¡Has terminado tu primer proyecto!'],
          steps: [
            { k: 'quiz', ph: 'recorda', q: 'Un programa fa xocar en Bit. Què és el primer que fas?|Un programa hace chocar a Bit. ¿Qué es lo primero que haces?', opts: ['Executar-lo pas a pas per veure on falla|Ejecutarlo paso a paso para ver dónde falla', 'Esborrar-ho tot|Borrarlo todo', "Afegir blocs a l'atzar|Añadir bloques al azar"], a: 0 },
            { k: 'story', ph: 'missio', who: 'both', scene: 'moll', title: 'El nou repartidor|El nuevo repartidor', blocks: ['pick', 'drop'], t: "Gran notícia: en Bit és el nou <b>repartidor de l'illa</b>! Ha d'agafar les caixes i portar-les a les cases. Per això aprendrà dues ordres noves.|Gran noticia: ¡Bit es el nuevo <b>repartidor de la isla</b>! Tiene que coger las cajas y llevarlas a las casas. Para eso aprenderá dos órdenes nuevas." },
            { k: 'learn', ph: 'descobreix', cards: [
              { k: "Ordres d'acció|Órdenes de acción", t: 'Agafa i Deixa|Coge y Deja', demo: { w: { map: ['.....', '>b#H.', '.....'] }, prog: TP('f p f f d') },
                x: "<b>Agafa la caixa</b> i <b>Deixa la caixa</b> no mouen en Bit: fan una acció a la casella on és. Per això abans cal arribar-hi amb <b>Endavant</b>.|<b>Coge la caja</b> y <b>Deja la caja</b> no mueven a Bit: hacen una acción en la casilla donde está. Por eso antes hay que llegar con <b>Adelante</b>." },
              { k: 'Descompondre|Descomponer', t: 'Un problema gran, a trossos|Un problema grande, a trozos', anim: 'decompose',
                x: "Repartir una caixa sembla difícil, però són quatre problemes petits: anar a la caixa, agafar-la, anar a la casa i deixar-la. Això es diu <span class='hl'>descompondre</span>.|Repartir una caja parece difícil, pero son cuatro problemas pequeños: ir a la caja, cogerla, ir a la casa y dejarla. Esto se llama <span class='hl'>descomponer</span>." },
              { k: 'Planificar|Planificar', t: 'Primer el pla, després els blocs|Primero el plan, después los bloques', anim: 'plan',
                x: "Els programadors no comencen posant blocs a l'atzar: primer pensen què ha de passar, ho parteixen en trossos i després ho passen a blocs. Al final ho proven i ho milloren.|Los programadores no empiezan poniendo bloques al azar: primero piensan qué tiene que pasar, lo parten en trozos y después lo pasan a bloques. Al final lo prueban y lo mejoran.",
                tip: "Si et perds, digues el pla en veu alta: «primer vaig a la caixa, després…»|Si te pierdes, di el plan en voz alta: «primero voy a la caja, después…»" }
            ] },
            { k: 'story', ph: 'missio', who: 'bit', mood: 'happy', w: { map: ['.....', '>b#H.', '.....'] }, t: "BIP! Només puc portar <b>una caixa cada vegada</b>. Si no hi ha caixa, no la puc agafar, i només la puc deixar en una <b>casa</b>.|¡BIP! Solo puedo llevar <b>una caja cada vez</b>. Si no hay caja, no la puedo coger, y solo la puedo dejar en una <b>casa</b>." },
            { k: 'parsons', ph: 'prova', q: 'El primer repartiment! <b>Ordena els blocs</b> i executa el programa.|¡El primer reparto! <b>Ordena los bloques</b> y ejecuta el programa.', w: { map: ['.....', '>b#H.', '.....'] }, pool: TP('f p f f d'), sol: TP('f p f f d'), hint: 'Primer ha d\'arribar a la caixa i agafar-la.|Primero tiene que llegar a la caja y cogerla.' },
            { k: 'seq', ph: 'mans', q: "Un problema gran es resol millor a trossos. <b>Ordena els trossos</b> de la feina del repartidor.|Un problema grande se resuelve mejor a trozos. <b>Ordena los trozos</b> del trabajo del repartidor.", items: ['Anar fins a la caixa|Ir hasta la caja', 'Agafar la caixa|Coger la caja', 'Anar fins a la casa|Ir hasta la casa', 'Deixar la caixa|Dejar la caja'], ex: 'Això es diu <b>descompondre</b>: partir un problema gran en problemes petits.|Esto se llama <b>descomponer</b>: partir un problema grande en problemas pequeños.' },
            { k: 'build', ph: 'repte', q: 'Porta la caixa a la casa. Pensa-ho a trossos!|Lleva la caja a la casa. ¡Piénsalo a trozos!', w: { map: ['##H..', 'bR...', '#R...', '^R...'] }, pal: TK_REP, sol: TP('f f p f r f f d'), hint: 'Tros 1: fins a la caixa (2 caselles amunt). Tros 2: agafa-la. Tros 3: fins a la casa.|Trozo 1: hasta la caja (2 casillas arriba). Trozo 2: cógela. Trozo 3: hasta la casa.' },
            { k: 'move', ph: 'pausa', secs: 30, t: "Fes de repartidor: agafa un coixí (la caixa) i porta'l a l'altra punta de l'habitació fent només <b>passos rectes i girs de robot</b>. Deixa'l i torna!|Haz de repartidor: coge un cojín (la caja) y llévalo al otro lado de la habitación dando solo <b>pasos rectos y giros de robot</b>. ¡Déjalo y vuelve!" },
            { k: 'build', ph: 'repte', q: 'Dues caixes i dues cases. Recorda: <b>una caixa cada vegada</b>.|Dos cajas y dos casas. Recuerda: <b>una caja cada vez</b>.', w: { map: ['.......', '>b#Hb#H', '.......'] }, pal: TK_REP, sol: TP('f p f f d f p f f d'), hint: "Reparteix la primera caixa del tot abans d'anar a buscar la segona.|Reparte la primera caja del todo antes de ir a buscar la segunda." },
            { k: 'spot', ph: 'investiga', q: 'Aquest repartidor falla. <b>Toca el bloc que està fora de lloc.</b>|Este repartidor falla. <b>Toca el bloque que está fuera de lugar.</b>', w: { map: ['.....', '>b#H.', '.....'] }, prog: TPX('f d! p f f d'), ex: 'No pot deixar una caixa que encara no porta.|No puede dejar una caja que aún no lleva.' },
            { k: 'build', ph: 'repte', q: 'Repartiment amb girs: dues caixes, dues cases. Fes-ho tros a tros.|Reparto con giros: dos cajas, dos casas. Hazlo trozo a trozo.', w: { map: ['...b#H', '...#..', 'b##H..', '#.....', '^.....'] }, pal: TK_REP, sol: TP('f f p r f f f d l f f p r f f d'), hint: 'Primer la caixa de baix fins a la casa del mig. Després, amunt fins a la segona caixa.|Primero la caja de abajo hasta la casa del medio. Después, arriba hasta la segunda caja.' },
            { k: 'create', ph: 'crea', name: 'El gran repartiment|El gran reparto', q: "<b>Projecte final de la unitat!</b> Reparteix les 3 caixes a les 3 cases. Planifica-ho a trossos i fes servir «Pas a pas» si alguna cosa falla.|<b>¡Proyecto final de la unidad!</b> Reparte las 3 cajas en las 3 casas. Planifícalo a trozos y usa «Paso a paso» si algo falla.",
              crit: ['Reparteix les 3 caixes|Reparte las 3 cajas', 'Una caixa cada vegada|Una caja cada vez'], w: { map: ['b...RH', '.R....', '..b.R.', 'H.R...', '....b.', '>R...H'].map(r => r.replace('>R', '^R')) }, pal: TK_REP,
              sol: TP('f r f f f f p r f l f d l f f l f f r f l f p f l f r f d r f f f p r f f f r f l f f l f d') },
            { k: 'quiz', ph: 'tanca', q: 'Què vol dir <b>descompondre</b> un problema?|¿Qué quiere decir <b>descomponer</b> un problema?', opts: ['Partir-lo en trossos més petits|Partirlo en trozos más pequeños', 'Fer-lo més difícil|Hacerlo más difícil', 'Deixar-lo per a un altre dia|Dejarlo para otro día'], a: 0 },
            { k: 'quiz', ph: 'tanca', q: 'Quina d\'aquestes ordres <b>no</b> mou en Bit de casella?|¿Cuál de estas órdenes <b>no</b> mueve a Bit de casilla?', opts: [tChip('pick'), tChip('fwd')], a: 0, ex: 'Agafar i deixar són accions: en Bit es queda on és.|Coger y dejar son acciones: Bit se queda donde está.' },
            { k: 'feel', ph: 'tanca' }
          ] }
      ] },
      { t: 'Repeteix!|¡Repite!', d: 'Bucles i patrons|Bucles y patrones', color: '#20A464', s: [{ id: 'r2-1', t: 'Repetir sense cansar-se|Repetir sin cansarse' }, { id: 'r2-2', t: 'Troba el patró|Encuentra el patrón' }, { id: 'r2-3', t: "El llapis d'en Bit|El lápiz de Bit" }, { id: 'r2-4', t: "Projecte: el mosaic de l'illa|Proyecto: el mosaico de la isla", proj: true }] },
      { t: 'Llums, sons i botons|Luces, sonidos y botones', d: 'Esdeveniments|Eventos', color: '#E5489A', s: [{ id: 'r3-1', t: 'Llums de colors|Luces de colores' }, { id: 'r3-2', t: 'Música amb en Bit|Música con Bit' }, { id: 'r3-3', t: 'Quan premo el botó…|Cuando pulso el botón…' }, { id: 'r3-4', t: 'Projecte: la coreografia|Proyecto: la coreografía', proj: true }] },
      { t: 'En Bit veu el món|Bit ve el mundo', d: 'Sensors i condicions|Sensores y condiciones', color: '#E8A317', s: [{ id: 'r4-1', t: 'Si hi ha una paret…|Si hay una pared…' }, { id: 'r4-2', t: 'Els colors del terra|Los colores del suelo' }, { id: 'r4-3', t: 'Si… i si no…|Si… y si no…' }, { id: 'r4-4', t: 'Projecte: el laberint|Proyecto: el laberinto', proj: true }] },
      { t: 'Ordres noves|Órdenes nuevas', d: 'Funcions|Funciones', color: '#8B5CF6', s: [{ id: 'r5-1', t: 'Posa nom a un grup de blocs|Ponle nombre a un grupo de bloques' }, { id: 'r5-2', t: 'Funcions dins de bucles|Funciones dentro de bucles' }, { id: 'r5-3', t: 'Pocs blocs, molta feina|Pocos bloques, mucho trabajo' }, { id: 'r5-4', t: 'Projecte: la ciutat dels robots|Proyecto: la ciudad de los robots', proj: true }] },
      { t: 'Comptar i recordar|Contar y recordar', d: 'Variables|Variables', color: '#14A3B8', s: [{ id: 'r6-1', t: "El comptador d'en Bit|El contador de Bit" }, { id: 'r6-2', t: 'Recollir i comptar|Recoger y contar' }, { id: 'r6-3', t: 'Punts i rècords|Puntos y récords' }, { id: 'r6-4', t: 'Projecte: el recol·lector de fruita|Proyecto: el recolector de fruta', proj: true }] },
      { t: 'Fins que…|Hasta que…', d: 'Bucles amb condició|Bucles con condición', color: '#F08A24', s: [{ id: 'r7-1', t: 'Repeteix fins que arribis|Repite hasta que llegues' }, { id: 'r7-2', t: 'Camins de llargada desconeguda|Caminos de longitud desconocida' }, { id: 'r7-3', t: 'Combinem-ho tot|Combinémoslo todo' }, { id: 'r7-4', t: 'Projecte: rescat a la cova|Proyecto: rescate en la cueva', proj: true }] },
      { t: 'El meu projecte|Mi proyecto', d: 'Projecte final del curs|Proyecto final del curso', color: '#20306A', s: [{ id: 'r8-1', t: 'Dissenya el teu repte|Diseña tu reto' }, { id: 'r8-2', t: 'Construeix-lo i prova\'l|Constrúyelo y pruébalo' }, { id: 'r8-3', t: 'Que el provi algú altre|Que lo pruebe otra persona' }, { id: 'r8-4', t: 'Presentació i diploma|Presentación y diploma', proj: true }] }
    ] },
  { id: 'robotica', ico: TCI.robotica, color: '#E2574C', soon: true, name: 'Tech Robòtica|Tech Robótica', short: 'Robòtica|Robótica', age: '9-13 anys|9-13 años',
    desc: "Un robot amb motors i sensors en un simulador: distància, línia, llum i so. Seguir línies, esquivar obstacles, aparcar sol, sumo i missions de rescat.|Un robot con motores y sensores en un simulador: distancia, línea, luz y sonido. Seguir líneas, esquivar obstáculos, aparcar solo, sumo y misiones de rescate.",
    units: [
      { t: 'Què és un robot?|¿Qué es un robot?', d: 'Sensors, cervell i motors|Sensores, cerebro y motores', s: [{ id: 'k1-1', t: 'Robots al nostre voltant|Robots a nuestro alrededor' }, { id: 'k1-2', t: 'Motors i velocitat|Motores y velocidad' }, { id: 'k1-3', t: 'Girar sobre si mateix|Girar sobre sí mismo' }, { id: 'k1-4', t: 'Projecte: el passeig|Proyecto: el paseo', proj: true }] },
      { t: 'Moviment precís|Movimiento preciso', d: 'Distància, angles i llapis|Distancia, ángulos y lápiz', s: [{ id: 'k2-1', t: 'Velocitat × temps|Velocidad × tiempo' }, { id: 'k2-2', t: 'Polígons|Polígonos' }, { id: 'k2-3', t: 'Cercles i corbes|Círculos y curvas' }, { id: 'k2-4', t: 'Projecte: el robot artista|Proyecto: el robot artista', proj: true }] },
      { t: 'Sensor de distància|Sensor de distancia', d: 'Ultrasons|Ultrasonidos', s: [{ id: 'k3-1', t: 'Com mesura un robot?|¿Cómo mide un robot?' }, { id: 'k3-2', t: 'Para abans del mur|Para antes del muro' }, { id: 'k3-3', t: 'Esquiva obstacles|Esquiva obstáculos' }, { id: 'k3-4', t: 'Projecte: aparcament automàtic|Proyecto: aparcamiento automático', proj: true }] },
      { t: 'Seguir la línia|Seguir la línea', d: 'Sensor de llum reflectida|Sensor de luz reflejada', s: [{ id: 'k4-1', t: 'Blanc o negre?|¿Blanco o negro?' }, { id: 'k4-2', t: 'La vora de la línia|El borde de la línea' }, { id: 'k4-3', t: 'Dos sensors i cruïlles|Dos sensores y cruces' }, { id: 'k4-4', t: 'Projecte: el tren de mercaderies|Proyecto: el tren de mercancías', proj: true }] },
      { t: 'Llum, so i LED|Luz, sonido y LED', d: 'Robots que avisen|Robots que avisan', s: [{ id: 'k5-1', t: 'El robot papallona|El robot mariposa' }, { id: 'k5-2', t: 'Alarmes|Alarmas' }, { id: 'k5-3', t: 'El fanal automàtic|La farola automática' }, { id: 'k5-4', t: 'Projecte: la casa intel·ligent|Proyecto: la casa inteligente', proj: true }] },
      { t: 'Control intel·ligent|Control inteligente', d: 'Variables i control proporcional|Variables y control proporcional', s: [{ id: 'k6-1', t: 'Velocitat que canvia|Velocidad que cambia' }, { id: 'k6-2', t: 'Com més lluny, més de pressa|Cuanto más lejos, más deprisa' }, { id: 'k6-3', t: 'Segueix el líder|Sigue al líder' }, { id: 'k6-4', t: 'Projecte: el cotxe autònom|Proyecto: el coche autónomo', proj: true }] },
      { t: 'Missions|Misiones', d: 'Reptes de robòtica|Retos de robótica', s: [{ id: 'k7-1', t: 'El robot aspirador|El robot aspirador' }, { id: 'k7-2', t: 'Sumo|Sumo' }, { id: 'k7-3', t: 'Rescat|Rescate' }, { id: 'k7-4', t: 'Projecte: la cursa contrarellotge|Proyecto: la carrera contrarreloj', proj: true }] },
      { t: 'El meu robot|Mi robot', d: 'Projecte final|Proyecto final', s: [{ id: 'k8-1', t: 'Dissenya la missió|Diseña la misión' }, { id: 'k8-2', t: 'Programa i prova|Programa y prueba' }, { id: 'k8-3', t: 'Del simulador al robot de veritat|Del simulador al robot de verdad' }, { id: 'k8-4', t: 'Presentació i diploma|Presentación y diploma', proj: true }] }
    ] },
  { id: 'creadors', ico: TCI.creadors, color: '#F08A24', soon: true, name: 'Tech Creadors|Tech Creadores', short: 'Creadors|Creadores', age: '8-11 anys|8-11 años',
    desc: "Programació amb blocs per crear animacions, històries interactives i videojocs propis, amb personatges, sons, punts i nivells.|Programación con bloques para crear animaciones, historias interactivas y videojuegos propios, con personajes, sonidos, puntos y niveles.",
    units: [
      { t: "Primers passos a l'escenari|Primeros pasos en el escenario", d: 'Personatges i moviment|Personajes y movimiento', s: [{ id: 'g1-1', t: 'El meu primer personatge|Mi primer personaje' }, { id: 'g1-2', t: 'Moure i parlar|Mover y hablar' }, { id: 'g1-3', t: 'Fons i escenes|Fondos y escenas' }, { id: 'g1-4', t: 'Projecte: presenta\'t|Proyecto: preséntate', proj: true }] },
      { t: 'Animació|Animación', d: 'Vestits, bucles i temps|Disfraces, bucles y tiempo', s: [{ id: 'g2-1', t: 'Dibuixos que es mouen|Dibujos que se mueven' }, { id: 'g2-2', t: 'Bucles per sempre|Bucles para siempre' }, { id: 'g2-3', t: 'Molts personatges alhora|Muchos personajes a la vez' }, { id: 'g2-4', t: "Projecte: l'aquari|Proyecto: el acuario", proj: true }] },
      { t: 'Interacció|Interacción', d: 'Esdeveniments i teclat|Eventos y teclado', s: [{ id: 'g3-1', t: 'Quan toco el personatge…|Cuando toco el personaje…' }, { id: 'g3-2', t: 'Les fletxes del teclat|Las flechas del teclado' }, { id: 'g3-3', t: 'Missatges entre personatges|Mensajes entre personajes' }, { id: 'g3-4', t: 'Projecte: el conte interactiu|Proyecto: el cuento interactivo', proj: true }] },
      { t: 'Coordenades|Coordenadas', d: 'On és cada cosa|Dónde está cada cosa', s: [{ id: 'g4-1', t: 'x i y|x e y' }, { id: 'g4-2', t: 'Anar a un punt|Ir a un punto' }, { id: 'g4-3', t: 'Rebotar a les vores|Rebotar en los bordes' }, { id: 'g4-4', t: 'Projecte: el laberint|Proyecto: el laberinto', proj: true }] },
      { t: 'Condicions|Condiciones', d: 'Xocs i decisions|Choques y decisiones', s: [{ id: 'g5-1', t: 'Si toca…|Si toca…' }, { id: 'g5-2', t: 'Colors que avisen|Colores que avisan' }, { id: 'g5-3', t: 'I, o, no|Y, o, no' }, { id: 'g5-4', t: 'Projecte: atrapa la fruita|Proyecto: atrapa la fruta', proj: true }] },
      { t: 'Variables|Variables', d: 'Punts, vides i temps|Puntos, vidas y tiempo', s: [{ id: 'g6-1', t: 'El marcador|El marcador' }, { id: 'g6-2', t: 'Vides i fi de partida|Vidas y fin de partida' }, { id: 'g6-3', t: 'Compte enrere|Cuenta atrás' }, { id: 'g6-4', t: 'Projecte: la mascota virtual|Proyecto: la mascota virtual', proj: true }] },
      { t: 'Atzar i dificultat|Azar y dificultad', d: 'Jocs que sorprenen|Juegos que sorprenden', s: [{ id: 'g7-1', t: 'Nombres a l\'atzar|Números al azar' }, { id: 'g7-2', t: 'Clons|Clones' }, { id: 'g7-3', t: 'Cada cop més difícil|Cada vez más difícil' }, { id: 'g7-4', t: 'Projecte: esquiva els meteorits|Proyecto: esquiva los meteoritos', proj: true }] },
      { t: 'El meu videojoc|Mi videojuego', d: 'Projecte final|Proyecto final', s: [{ id: 'g8-1', t: 'La idea i el pla|La idea y el plan' }, { id: 'g8-2', t: 'Construir-lo|Construirlo' }, { id: 'g8-3', t: 'Provar-lo i millorar-lo|Probarlo y mejorarlo' }, { id: 'g8-4', t: 'Presentació i diploma|Presentación y diploma', proj: true }] }
    ] },
  { id: 'web', ico: TCI.web, color: '#14A3B8', soon: true, name: 'Tech Web|Tech Web', short: 'Web|Web', age: '11-14 anys|11-14 años',
    desc: "Com funciona internet i com es fa una web de veritat: HTML, CSS i disseny per al mòbil, fins a publicar la teva pròpia pàgina.|Cómo funciona internet y cómo se hace una web de verdad: HTML, CSS y diseño para el móvil, hasta publicar tu propia página.",
    units: [
      { t: 'Com funciona internet|Cómo funciona internet', d: 'Servidors, adreces i navegadors|Servidores, direcciones y navegadores', s: [{ id: 'w1-1', t: "El viatge d'una pàgina|El viaje de una página" }, { id: 'w1-2', t: 'Adreces i dominis|Direcciones y dominios' }, { id: 'w1-3', t: 'Què hi ha dins una web?|¿Qué hay dentro de una web?' }, { id: 'w1-4', t: 'Projecte: el mapa d\'internet|Proyecto: el mapa de internet', proj: true }] },
      { t: 'HTML|HTML', d: 'Títols, paràgrafs i llistes|Títulos, párrafos y listas', s: [{ id: 'w2-1', t: 'Etiquetes|Etiquetas' }, { id: 'w2-2', t: 'Títols i paràgrafs|Títulos y párrafos' }, { id: 'w2-3', t: 'Llistes|Listas' }, { id: 'w2-4', t: 'Projecte: la recepta|Proyecto: la receta', proj: true }] },
      { t: 'Imatges i enllaços|Imágenes y enlaces', d: 'Connectar pàgines|Conectar páginas', s: [{ id: 'w3-1', t: 'Imatges|Imágenes' }, { id: 'w3-2', t: 'Enllaços|Enlaces' }, { id: 'w3-3', t: 'Citar les fonts|Citar las fuentes' }, { id: 'w3-4', t: 'Projecte: la fitxa d\'un animal|Proyecto: la ficha de un animal', proj: true }] },
      { t: 'CSS|CSS', d: 'Colors i lletres|Colores y letras', s: [{ id: 'w4-1', t: 'Donar estil|Dar estilo' }, { id: 'w4-2', t: 'Colors|Colores' }, { id: 'w4-3', t: 'Tipus de lletra|Tipos de letra' }, { id: 'w4-4', t: 'Projecte: el pòster|Proyecto: el póster', proj: true }] },
      { t: 'Caixes|Cajas', d: 'Marges, vores i espais|Márgenes, bordes y espacios', s: [{ id: 'w5-1', t: 'Tot és una caixa|Todo es una caja' }, { id: 'w5-2', t: 'Marges i farciment|Márgenes y relleno' }, { id: 'w5-3', t: 'Vores i ombres|Bordes y sombras' }, { id: 'w5-4', t: 'Projecte: la targeta del videojoc|Proyecto: la tarjeta del videojuego', proj: true }] },
      { t: 'Disposició|Disposición', d: 'Files, columnes i graelles|Filas, columnas y rejillas', s: [{ id: 'w6-1', t: 'Una al costat de l\'altra|Una al lado de la otra' }, { id: 'w6-2', t: 'Graelles|Rejillas' }, { id: 'w6-3', t: 'Taules|Tablas' }, { id: 'w6-4', t: "Projecte: l'àlbum de fotos|Proyecto: el álbum de fotos", proj: true }] },
      { t: 'Per al mòbil|Para el móvil', d: 'Disseny adaptable|Diseño adaptable', s: [{ id: 'w7-1', t: 'Pantalles petites|Pantallas pequeñas' }, { id: 'w7-2', t: 'Botons i efectes|Botones y efectos' }, { id: 'w7-3', t: 'Detecta la web falsa|Detecta la web falsa' }, { id: 'w7-4', t: 'Projecte: la guia de Lleida|Proyecto: la guía de Lleida', proj: true }] },
      { t: 'La meva web|Mi web', d: 'Projecte final|Proyecto final', s: [{ id: 'w8-1', t: 'Planificar|Planificar' }, { id: 'w8-2', t: 'Construir|Construir' }, { id: 'w8-3', t: 'Revisar i millorar|Revisar y mejorar' }, { id: 'w8-4', t: 'Presentació i diploma|Presentación y diploma', proj: true }] }
    ] },
  { id: 'digital', ico: TCI.digital, color: '#3CC47C', soon: true, name: 'Tech Digital|Tech Digital', short: 'Digital|Digital', age: '8-14 anys|8-14 años',
    desc: "Ciutadania digital: contrasenyes, privadesa, bulos, respecte a la xarxa, què és (i què no és) la intel·ligència artificial i com cuidar-se davant les pantalles.|Ciudadanía digital: contraseñas, privacidad, bulos, respeto en la red, qué es (y qué no es) la inteligencia artificial y cómo cuidarse frente a las pantallas.",
    units: [
      { t: 'Segur a la xarxa|Seguro en la red', d: 'Contrasenyes i privadesa|Contraseñas y privacidad', s: [{ id: 'd1-1', t: 'Contrasenyes fortes|Contraseñas fuertes' }, { id: 'd1-2', t: 'Què compartim?|¿Qué compartimos?' }, { id: 'd1-3', t: "L'empremta digital|La huella digital" }, { id: 'd1-4', t: 'Projecte: el meu decàleg|Proyecto: mi decálogo', proj: true }] },
      { t: 'Pensar abans de creure|Pensar antes de creer', d: 'Bulos, IA i benestar|Bulos, IA y bienestar', s: [{ id: 'd2-1', t: 'Caçadors de bulos|Cazadores de bulos' }, { id: 'd2-2', t: 'Què és la intel·ligència artificial?|¿Qué es la inteligencia artificial?' }, { id: 'd2-3', t: 'Respecte a la xarxa|Respeto en la red' }, { id: 'd2-4', t: 'Projecte: la campanya|Proyecto: la campaña', proj: true }] }
    ] }
];

/* ===== Tech Robot · unitats 2-8 =====
   Cada sessió s'omple amb bot2Sess(id, {t, min, badge, learn, steps}) sobre el catàleg de dalt (es mantenen els ids).
   Les animacions noves són a TANI_ROBOT (tech-bot.js); les demostracions en directe amb bucles es creen aquí amb bot2Live(). */
function bot2Sess(id, o) { const c = TECH.find(x => x.id === 'robot'); for (const u of c.units) for (const s of u.s) if (s.id === id) Object.assign(s, o); }
