/* Teoria de les unitats noves de primària (Decret 175/2022), en català|castellà.
   Mateix format que theory.js (hook, parts, words, mistakes, recap i tip); s'hi afegeix sense tocar la resta. */
Object.assign(THEORY, {
"c1-9": {
"hook": "Al regle, al termòmetre i als botons de l'ascensor, els números fan fila. I el calendari et diu quin dia és avui i quant falta per a la festa!|En la regla, en el termómetro y en los botones del ascensor, los números hacen fila. ¡Y el calendario te dice qué día es hoy y cuánto falta para la fiesta!",
"parts": [
{ "t": "La recta numèrica|La recta numérica", "x": "A la <b>recta numèrica</b> els números van en ordre, d'esquerra a dreta, i cada un té el seu lloc. Entre dues marques sempre hi ha la mateixa distància. Com més a la dreta, més gran és el número.|En la <b>recta numérica</b> los números van en orden, de izquierda a derecha, y cada uno tiene su sitio. Entre dos marcas siempre hay la misma distancia. Cuanto más a la derecha, mayor es el número.",
  "ex": ["La recta va del 0 al 10|La recta va del 0 al 10", "Hi ha escrit el 5. La fletxa és 3 marques més enllà|Está escrito el 5. La flecha está 3 marcas más allá", "5, 6, 7, 8: la fletxa és al <span class=\"hl\">8</span>|5, 6, 7, 8: la flecha está en el <span class=\"hl\">8</span>"] },
{ "t": "Salts de 10 en 10|Saltos de 10 en 10", "x": "De vegades les marques no van d'1 en 1. Si de 0 a 100 hi ha 10 marques, cada salt val <b>10</b>: 0, 10, 20, 30… Busca el número escrit més a prop i compta salts des d'allà.|A veces las marcas no van de 1 en 1. Si de 0 a 100 hay 10 marcas, cada salto vale <b>10</b>: 0, 10, 20, 30… Busca el número escrito más cerca y cuenta saltos desde allí.",
  "ex": ["Hi ha escrit el 50|Está escrito el 50", "Dues marques més: 60 i 70|Dos marcas más: 60 y 70", "La fletxa és al <span class=\"hl\">70</span>|La flecha está en el <span class=\"hl\">70</span>"] },
{ "t": "Els dies de la setmana|Los días de la semana", "x": "La setmana té <b>7 dies</b>: dilluns, dimarts, dimecres, dijous, divendres, dissabte i diumenge. Dissabte i diumenge són el cap de setmana. Després de diumenge, la setmana torna a començar.|La semana tiene <b>7 días</b>: lunes, martes, miércoles, jueves, viernes, sábado y domingo. Sábado y domingo son el fin de semana. Después del domingo, la semana vuelve a empezar.",
  "ex": ["Avui és dijous|Hoy es jueves", "Demà serà divendres|Mañana será viernes", "Ahir va ser <span class=\"hl\">dimecres</span>|Ayer fue <span class=\"hl\">miércoles</span>"] },
{ "t": "Els mesos de l'any|Los meses del año", "x": "Un any té <b>12 mesos</b>: gener, febrer, març, abril, maig, juny, juliol, agost, setembre, octubre, novembre i desembre. Quan s'acaba el desembre, comença un any nou pel gener.|Un año tiene <b>12 meses</b>: enero, febrero, marzo, abril, mayo, junio, julio, agosto, septiembre, octubre, noviembre y diciembre. Cuando se acaba diciembre, empieza un año nuevo por enero.",
  "ex": ["Som al març|Estamos en marzo", "El mes següent és l'abril|El mes siguiente es abril", "El 23 d'abril és <span class=\"hl\">Sant Jordi</span>|El 23 de abril es <span class=\"hl\">Sant Jordi</span>"] }
],
"words": [["recta numèrica|recta numérica", "una línia amb els números en ordre|una línea con los números en orden"], ["marca|marca", "cada ratlleta de la recta|cada rayita de la recta"], ["demà|mañana", "el dia que ve després d'avui|el día que viene después de hoy"], ["ahir|ayer", "el dia que va ser abans d'avui|el día que fue antes de hoy"], ["cap de setmana|fin de semana", "dissabte i diumenge|sábado y domingo"]],
"mistakes": [["«Compto també la marca d'on surto.»|«Cuento también la marca de donde salgo.»", "Compta només els salts: del 5 al 8 hi ha 3 salts (6, 7 i 8).|Cuenta solo los saltos: del 5 al 8 hay 3 saltos (6, 7 y 8)."], ["«Després de diumenge ve dissabte.»|«Después del domingo viene el sábado.»", "Després de diumenge la setmana torna a començar: dilluns.|Después del domingo la semana vuelve a empezar: lunes."]],
"recap": ["A la recta, més a la dreta vol dir més gran.|En la recta, más a la derecha quiere decir mayor.", "Mira de quant en quant van les marques abans de comptar.|Mira de cuánto en cuánto van las marcas antes de contar.", "La setmana té 7 dies i l'any, 12 mesos.|La semana tiene 7 días y el año, 12 meses."],
"tip": "Per trobar un número a la recta, busca el número escrit que tingui més a prop i compta salts des d'allà.|Para encontrar un número en la recta, busca el número escrito que tenga más cerca y cuenta saltos desde allí."
},
"c2-8": {
"hook": "Amb la recta veus d'un cop d'ull quin número és més gran, i amb el calendari saps quants dies falten per a les vacances.|Con la recta ves de un vistazo qué número es mayor, y con el calendario sabes cuántos días faltan para las vacaciones.",
"parts": [
{ "t": "Quant val cada marca?|¿Cuánto vale cada marca?", "x": "Abans de llegir una recta, mira quant val cada salt. Si de 0 a 1.000 hi ha 10 marques, cada marca val <b>100</b>. Si de 300 a 400 hi ha 10 marques, cada marca val <b>10</b>.|Antes de leer una recta, mira cuánto vale cada salto. Si de 0 a 1.000 hay 10 marcas, cada marca vale <b>100</b>. Si de 300 a 400 hay 10 marcas, cada marca vale <b>10</b>.",
  "ex": ["De 300 a 400 hi ha 10 marques|De 300 a 400 hay 10 marcas", "Cada marca val 10|Cada marca vale 10", "La tercera marca és el <span class=\"hl\">330</span>|La tercera marca es el <span class=\"hl\">330</span>"] },
{ "t": "El full del calendari|La hoja del calendario", "x": "Al calendari, cada <b>columna</b> és un dia de la setmana i cada <b>fila</b> és una setmana. Per saber quin dia de la setmana és una data, busca el número i mira quin dia hi ha dalt de tot de la seva columna.|En el calendario, cada <b>columna</b> es un día de la semana y cada <b>fila</b> es una semana. Para saber qué día de la semana es una fecha, busca el número y mira qué día hay arriba del todo de su columna.",
  "ex": ["Busca el dia 17|Busca el día 17", "És a la columna de dalt «dj»|Está en la columna de arriba «J»", "El 17 és <span class=\"hl\">dijous</span>|El 17 es <span class=\"hl\">jueves</span>"] },
{ "t": "Quants dies falten?|¿Cuántos días faltan?", "x": "Per saber quants dies falten d'un dia a un altre del mateix mes, resta: <b>dia que esperes − dia d'avui</b>.|Para saber cuántos días faltan de un día a otro del mismo mes, resta: <b>día que esperas − día de hoy</b>.",
  "ex": ["Avui és dia 5 i la festa és el 12|Hoy es día 5 y la fiesta es el 12", "12 − 5 = 7|12 − 5 = 7", "Falten <span class=\"hl\">7 dies</span>|Faltan <span class=\"hl\">7 días</span>"] },
{ "t": "D'aquí a una setmana|Dentro de una semana", "x": "Una setmana són <b>7 dies</b>: al calendari és la mateixa columna, una fila més avall. Si el 3 és dimarts, el 10, el 17 i el 24 també són dimarts. Els mesos tenen 30 o 31 dies, i el febrer, 28 (29 els anys de traspàs).|Una semana son <b>7 días</b>: en el calendario es la misma columna, una fila más abajo. Si el 3 es martes, el 10, el 17 y el 24 también son martes. Los meses tienen 30 o 31 días, y febrero, 28 (29 los años bisiestos).",
  "ex": ["El 3 és dimarts|El 3 es martes", "3 + 7 = 10|3 + 7 = 10", "El 10 també és <span class=\"hl\">dimarts</span>|El 10 también es <span class=\"hl\">martes</span>"] }
],
"words": [["calendari|calendario", "la taula amb tots els dies del mes|la tabla con todos los días del mes"], ["columna|columna", "una línia de dalt a baix|una línea de arriba abajo"], ["fila|fila", "una línia d'esquerra a dreta|una línea de izquierda a derecha"], ["setmana|semana", "7 dies seguits|7 días seguidos"]],
"mistakes": [["«Del 5 al 12 falten 8 dies: 5, 6, 7… 12.»|«Del 5 al 12 faltan 8 días: 5, 6, 7… 12.»", "Si comptes avui i l'últim dia, en comptes un de més. Resta: 12 − 5 = 7.|Si cuentas hoy y el último día, cuentas uno de más. Resta: 12 − 5 = 7."], ["«De 0 a 1.000, cada marca val 1.»|«De 0 a 1.000, cada marca vale 1.»", "Mira quantes marques hi ha: si en són 10, cada una val 1.000 ÷ 10 = 100.|Mira cuántas marcas hay: si son 10, cada una vale 1.000 ÷ 10 = 100."]],
"recap": ["Primer mira quant val cada marca de la recta.|Primero mira cuánto vale cada marca de la recta.", "Al calendari, la columna et diu el dia de la setmana.|En el calendario, la columna te dice el día de la semana.", "Per saber quants dies falten, resta.|Para saber cuántos días faltan, resta."],
"tip": "Els dies que cauen el mateix dia de la setmana són a la mateixa columna: van sempre de 7 en 7.|Los días que caen el mismo día de la semana están en la misma columna: van siempre de 7 en 7."
},
"c3-10": {
"hook": "Els trens surten a les 17:45, el calendari marca les vacances i els programes prenen decisions: tot això són matemàtiques!|Los trenes salen a las 17:45, el calendario marca las vacaciones y los programas toman decisiones: ¡todo eso son matemáticas!",
"parts": [
{ "t": "La recta fins al 10.000|La recta hasta el 10.000", "x": "A les rectes amb números grans, cada marca pot valer 1.000, 100 o 10. Busca dos números escrits, compta quantes marques hi ha entre ells i reparteix: així saps quant val cada marca.|En las rectas con números grandes, cada marca puede valer 1.000, 100 o 10. Busca dos números escritos, cuenta cuántas marcas hay entre ellos y reparte: así sabes cuánto vale cada marca.",
  "ex": ["De 2.000 a 3.000 hi ha 10 marques|De 2.000 a 3.000 hay 10 marcas", "Cada marca val 100|Cada marca vale 100", "La quarta marca és el <span class=\"hl\">2.400</span>|La cuarta marca es el <span class=\"hl\">2.400</span>"] },
{ "t": "Dates|Fechas", "x": "Els mesos no tenen tots els mateixos dies: n'hi ha de <b>30</b>, de <b>31</b> i el febrer en té 28 (29 els anys de traspàs). Quan comptes dies i s'acaba el mes, continua per l'1 del mes següent. Una setmana són 7 dies.|Los meses no tienen todos los mismos días: los hay de <b>30</b>, de <b>31</b> y febrero tiene 28 (29 los años bisiestos). Cuando cuentas días y se acaba el mes, sigue por el 1 del mes siguiente. Una semana son 7 días.",
  "ex": ["Avui és el 28 d'abril. D'aquí a 5 dies?|Hoy es 28 de abril. ¿Dentro de 5 días?", "L'abril té 30 dies: 29, 30, i 1, 2 i 3 de maig|Abril tiene 30 días: 29, 30, y 1, 2 y 3 de mayo", "Serà el <span class=\"hl\">3 de maig</span>|Será el <span class=\"hl\">3 de mayo</span>"] },
{ "t": "El rellotge de 24 hores|El reloj de 24 horas", "x": "El dia té <b>24 hores</b>. Els rellotges digitals compten de les 0:00 a les 23:59. A la tarda i a la nit, sumem 12 a l'hora del rellotge de busques: les 3 de la tarda són les 15:00. Per saber quant dura una cosa, resta l'hora del final i la del principi.|El día tiene <b>24 horas</b>. Los relojes digitales cuentan de las 0:00 a las 23:59. Por la tarde y por la noche, sumamos 12 a la hora del reloj de agujas: las 3 de la tarde son las 15:00. Para saber cuánto dura algo, resta la hora del final y la del principio.",
  "ex": ["Són les 5 de la tarda|Son las 5 de la tarde", "5 + 12 = 17|5 + 12 = 17", "El rellotge digital marca <span class=\"hl\">17:00</span>|El reloj digital marca <span class=\"hl\">17:00</span>"] },
{ "t": "Si… llavors… si no|Si… entonces… si no", "x": "Un programa pot prendre decisions: «<b>si</b> passa això, <b>llavors</b> fes això; <b>si no</b>, fes allò altre». Primer mira si la condició és certa o falsa, i després fa només una de les dues parts.|Un programa puede tomar decisiones: «<b>si</b> pasa esto, <b>entonces</b> haz esto; <b>si no</b>, haz aquello». Primero mira si la condición es verdadera o falsa, y después hace solo una de las dos partes.",
  "ex": ["n = 7; si n > 5 llavors digues «gran», si no digues «petit»|n = 7; si n > 5 entonces di «grande», si no di «pequeño»", "7 > 5 és cert|7 > 5 es verdad", "El programa diu <span class=\"hl\">«gran»</span>|El programa dice <span class=\"hl\">«grande»</span>"] }
],
"words": [["data|fecha", "el dia i el mes, com el 3 de maig|el día y el mes, como el 3 de mayo"], ["24 hores|24 horas", "la manera d'escriure les hores sense dir «de la tarda»|la manera de escribir las horas sin decir «de la tarde»"], ["durada|duración", "el temps que passa entre el principi i el final|el tiempo que pasa entre el principio y el final"], ["condició|condición", "una pregunta que pot ser certa o falsa|una pregunta que puede ser verdadera o falsa"]],
"mistakes": [["«Les 15:00 són les 5 de la tarda.»|«Las 15:00 son las 5 de la tarde.»", "Resta 12: 15 − 12 = 3. Són les 3 de la tarda.|Resta 12: 15 − 12 = 3. Son las 3 de la tarde."], ["«Si la condició és falsa, el programa no fa res.»|«Si la condición es falsa, el programa no hace nada.»", "Si hi ha la part «si no», fa aquesta part.|Si está la parte «si no», hace esa parte."]],
"recap": ["Mira quant val cada marca abans de llegir la recta.|Mira cuánto vale cada marca antes de leer la recta.", "Els mesos tenen 30 o 31 dies (el febrer, 28 o 29).|Los meses tienen 30 o 31 días (febrero, 28 o 29).", "A la tarda, sumem 12 per tenir l'hora de 24 hores.|Por la tarde, sumamos 12 para tener la hora de 24 horas.", "Un «si… llavors… si no» fa només una de les dues parts.|Un «si… entonces… si no» hace solo una de las dos partes."],
"tip": "Per saber quant dura una cosa que passa d'una hora a l'altra, compta primer fins a l'hora en punt i després suma la resta.|Para saber cuánto dura algo que pasa de una hora a otra, cuenta primero hasta la hora en punto y después suma el resto."
},
"c4-11": {
"hook": "Mira les bigues d'un pont, les rajoles del terra o un estel: hi ha triangles i quadrilàters per tot arreu. Classificar-los és com posar-los nom i cognom.|Mira las vigas de un puente, las baldosas del suelo o una cometa: hay triángulos y cuadriláteros por todas partes. Clasificarlos es como ponerles nombre y apellido.",
"parts": [
{ "t": "Triangles segons els costats|Triángulos según los lados", "x": "Un triangle és <b>equilàter</b> si té els tres costats iguals, <b>isòsceles</b> si en té dos d'iguals i <b>escalè</b> si els té tots diferents. Les ratlletes iguals sobre els costats volen dir que aquests costats fan el mateix.|Un triángulo es <b>equilátero</b> si tiene los tres lados iguales, <b>isósceles</b> si tiene dos iguales y <b>escaleno</b> si los tiene todos diferentes. Las rayitas iguales sobre los lados quieren decir que esos lados miden lo mismo.",
  "ex": ["Costats: 5 cm, 5 cm i 8 cm|Lados: 5 cm, 5 cm y 8 cm", "N'hi ha dos d'iguals|Hay dos iguales", "És <span class=\"hl\">isòsceles</span>|Es <span class=\"hl\">isósceles</span>"] },
{ "t": "Triangles segons els angles|Triángulos según los ángulos", "x": "Un triangle és <b>rectangle</b> si té un angle recte (90°), <b>obtusangle</b> si té un angle obtús (més de 90°) i <b>acutangle</b> si els tres angles són aguts (menys de 90°). Els tres angles d'un triangle sempre sumen 180°, i per això només en pot tenir un de recte o d'obtús.|Un triángulo es <b>rectángulo</b> si tiene un ángulo recto (90°), <b>obtusángulo</b> si tiene un ángulo obtuso (más de 90°) y <b>acutángulo</b> si los tres ángulos son agudos (menos de 90°). Los tres ángulos de un triángulo siempre suman 180°, y por eso solo puede tener uno recto u obtuso.",
  "ex": ["Angles: 30°, 60° i 90°|Ángulos: 30°, 60° y 90°", "Té un angle de 90°|Tiene un ángulo de 90°", "És <span class=\"hl\">rectangle</span>|Es <span class=\"hl\">rectángulo</span>"] },
{ "t": "Rectes paral·leles i perpendiculars|Rectas paralelas y perpendiculares", "x": "Dues rectes són <b>paral·leles</b> si no es tallen mai, com les vies del tren. Són <b>perpendiculars</b> si es tallen fent quatre angles rectes, com una creu. I són <b>oblíqües</b> si es tallen però sense fer angles rectes.|Dos rectas son <b>paralelas</b> si no se cortan nunca, como las vías del tren. Son <b>perpendiculares</b> si se cortan formando cuatro ángulos rectos, como una cruz. Y son <b>oblicuas</b> si se cortan pero sin formar ángulos rectos.",
  "ex": ["Dues rectes es tallen|Dos rectas se cortan", "El quadradet de la cantonada diu 90°|El cuadradito de la esquina dice 90°", "Són <span class=\"hl\">perpendiculars</span>|Son <span class=\"hl\">perpendiculares</span>"] },
{ "t": "Els quadrilàters|Los cuadriláteros", "x": "Els polígons de 4 costats són quadrilàters. Si tenen els costats <b>paral·lels dos a dos</b> són paral·lelograms: el <b>quadrat</b> (4 costats iguals i 4 angles rectes), el <b>rectangle</b> (4 angles rectes), el <b>rombe</b> (4 costats iguals, sense angles rectes) i el <b>romboide</b>. El <b>trapezi</b> només té dos costats paral·lels i el <b>trapezoide</b> no en té cap.|Los polígonos de 4 lados son cuadriláteros. Si tienen los lados <b>paralelos dos a dos</b> son paralelogramos: el <b>cuadrado</b> (4 lados iguales y 4 ángulos rectos), el <b>rectángulo</b> (4 ángulos rectos), el <b>rombo</b> (4 lados iguales, sin ángulos rectos) y el <b>romboide</b>. El <b>trapecio</b> solo tiene dos lados paralelos y el <b>trapezoide</b> no tiene ninguno.",
  "ex": ["4 costats iguals, sense angles rectes|4 lados iguales, sin ángulos rectos", "Té els costats paral·lels dos a dos|Tiene los lados paralelos dos a dos", "És un <span class=\"hl\">rombe</span>|Es un <span class=\"hl\">rombo</span>"] }
],
"words": [["equilàter|equilátero", "amb els tres costats iguals|con los tres lados iguales"], ["isòsceles|isósceles", "amb dos costats iguals|con dos lados iguales"], ["escalè|escaleno", "amb tots els costats diferents|con todos los lados diferentes"], ["paral·leles|paralelas", "rectes que no es tallen mai|rectas que no se cortan nunca"], ["perpendiculars|perpendiculares", "rectes que es tallen fent angles rectes|rectas que se cortan formando ángulos rectos"], ["paral·lelogram|paralelogramo", "quadrilàter amb els costats paral·lels dos a dos|cuadrilátero con los lados paralelos dos a dos"]],
"mistakes": [["«Un quadrat girat és un rombe.»|«Un cuadrado girado es un rombo.»", "Si té 4 costats iguals i 4 angles rectes, és un quadrat encara que estigui girat.|Si tiene 4 lados iguales y 4 ángulos rectos, es un cuadrado aunque esté girado."], ["«Un triangle rectangle té tots els angles rectes.»|«Un triángulo rectángulo tiene todos los ángulos rectos.»", "Només en té un de recte; els altres dos sumen 90°.|Solo tiene uno recto; los otros dos suman 90°."]],
"recap": ["Pels costats: equilàter, isòsceles o escalè.|Por los lados: equilátero, isósceles o escaleno.", "Pels angles: acutangle, rectangle o obtusangle.|Por los ángulos: acutángulo, rectángulo u obtusángulo.", "Paral·leles no es tallen; perpendiculars es tallen en angle recte.|Paralelas no se cortan; perpendiculares se cortan en ángulo recto.", "Quadrat, rectangle, rombe i romboide són paral·lelograms.|Cuadrado, rectángulo, rombo y romboide son paralelogramos."],
"tip": "Mira les marques del dibuix: les ratlletes iguals volen dir costats iguals i el quadradet a una cantonada vol dir angle recte.|Mira las marcas del dibujo: las rayitas iguales quieren decir lados iguales y el cuadradito en una esquina quiere decir ángulo recto."
},
"c4-12": {
"hook": "Horaris de tren, dies que falten per a una excursió i cercadors que fan servir I, O i NO: avui toca pensar com un rellotge i com un ordinador.|Horarios de tren, días que faltan para una excursión y buscadores que usan Y, O y NO: hoy toca pensar como un reloj y como un ordenador.",
"parts": [
{ "t": "La recta fins al 100.000|La recta hasta el 100.000", "x": "Amb números grans, la recta funciona igual: busca dos números escrits, mira quantes marques hi ha entre ells i descobreix quant val cada marca. Pot valer 10.000, 1.000, 100…|Con números grandes, la recta funciona igual: busca dos números escritos, mira cuántas marcas hay entre ellos y descubre cuánto vale cada marca. Puede valer 10.000, 1.000, 100…",
  "ex": ["De 40.000 a 50.000 hi ha 10 marques|De 40.000 a 50.000 hay 10 marcas", "Cada marca val 1.000|Cada marca vale 1.000", "La setena marca és el <span class=\"hl\">47.000</span>|La séptima marca es el <span class=\"hl\">47.000</span>"] },
{ "t": "Quin dia de la setmana serà?|¿Qué día de la semana será?", "x": "Cada 7 dies es repeteix el mateix dia de la setmana. Per saber quin dia serà, compta els dies que passen, treu les setmanes senceres i avança només els dies que sobren.|Cada 7 días se repite el mismo día de la semana. Para saber qué día será, cuenta los días que pasan, quita las semanas enteras y avanza solo los días que sobran.",
  "ex": ["El 3 de maig és dimecres. I el 20?|El 3 de mayo es miércoles. ¿Y el 20?", "Passen 17 dies: 2 setmanes i 3 dies|Pasan 17 días: 2 semanas y 3 días", "Dimecres + 3 dies = <span class=\"hl\">dissabte</span>|Miércoles + 3 días = <span class=\"hl\">sábado</span>"] },
{ "t": "Durades|Duraciones", "x": "Una hora té <b>60 minuts</b>, no 100. Si una cosa comença en una hora i acaba en la següent, compta primer els minuts fins a l'hora en punt i després suma els que falten.|Una hora tiene <b>60 minutos</b>, no 100. Si algo empieza en una hora y acaba en la siguiente, cuenta primero los minutos hasta la hora en punto y después suma los que faltan.",
  "ex": ["De les 16:40 a les 17:25|De las 16:40 a las 17:25", "Fins a les 17:00: 20 min. Fins a les 17:25: 25 min més|Hasta las 17:00: 20 min. Hasta las 17:25: 25 min más", "20 + 25 = <span class=\"hl\">45 minuts</span>|20 + 25 = <span class=\"hl\">45 minutos</span>"] },
{ "t": "I, O, NO|Y, O, NO", "x": "Els programes combinen condicions. Amb <b>I</b> s'han de complir les dues coses alhora. Amb <b>O</b> n'hi ha prou que se'n compleixi una (o les dues). <b>NO</b> gira la condició: el que era cert passa a ser fals.|Los programas combinan condiciones. Con <b>Y</b> se tienen que cumplir las dos cosas a la vez. Con <b>O</b> basta con que se cumpla una (o las dos). <b>NO</b> da la vuelta a la condición: lo que era verdad pasa a ser falso.",
  "ex": ["Figures vermelles I quadrades|Figuras rojas Y cuadradas", "Han de ser vermelles i també quadrades|Tienen que ser rojas y también cuadradas", "Només compten els <span class=\"hl\">quadrats vermells</span>|Solo cuentan los <span class=\"hl\">cuadrados rojos</span>"] }
],
"words": [["setmana sencera|semana entera", "7 dies justos|7 días justos"], ["durada|duración", "el temps que dura una cosa|el tiempo que dura algo"], ["I|Y", "s'han de complir les dues condicions|se tienen que cumplir las dos condiciones"], ["O|O", "n'hi ha prou amb una condició|basta con una condición"], ["NO|NO", "gira la condició|da la vuelta a la condición"]],
"mistakes": [["«Vermelles O rodones: compto només les que són les dues coses.»|«Rojas O redondas: cuento solo las que son las dos cosas.»", "Amb O compten totes les vermelles i totes les rodones (sense repetir-ne cap).|Con O cuentan todas las rojas y todas las redondas (sin repetir ninguna)."], ["«De les 16:40 a les 17:25 hi ha 85 minuts.»|«De las 16:40 a las 17:25 hay 85 minutos.»", "Una hora té 60 minuts: 20 minuts fins a les 17:00 i 25 més, 45 minuts.|Una hora tiene 60 minutos: 20 minutos hasta las 17:00 y 25 más, 45 minutos."]],
"recap": ["Cada 7 dies torna el mateix dia de la setmana.|Cada 7 días vuelve el mismo día de la semana.", "Una hora són 60 minuts.|Una hora son 60 minutos.", "I: les dues coses. O: com a mínim una. NO: al revés.|Y: las dos cosas. O: como mínimo una. NO: al revés."],
"tip": "Amb I la condició és difícil de complir; amb O, és fàcil. Si dubtes, comprova-ho figura per figura.|Con Y la condición es difícil de cumplir; con O, es fácil. Si dudas, compruébalo figura por figura."
},
"c5-10": {
"hook": "Per cuinar, fer esport, viatjar o guardar fotos al mòbil, cal saber passar d'una unitat a una altra.|Para cocinar, hacer deporte, viajar o guardar fotos en el móvil, hay que saber pasar de una unidad a otra.",
"parts": [
{ "t": "L'escala de la longitud|La escalera de la longitud", "x": "Les unitats de longitud formen una escala: <b>km, hm, dam, m, dm, cm, mm</b>. Cada graó val 10 vegades el de sota. Per baixar (de gran a petita) multipliquem per 10 a cada graó; per pujar (de petita a gran) dividim per 10. La capacitat funciona igual: <b>kl, hl, dal, l, dl, cl, ml</b>.|Las unidades de longitud forman una escalera: <b>km, hm, dam, m, dm, cm, mm</b>. Cada peldaño vale 10 veces el de abajo. Para bajar (de grande a pequeña) multiplicamos por 10 en cada peldaño; para subir (de pequeña a grande) dividimos entre 10. La capacidad funciona igual: <b>kl, hl, dal, l, dl, cl, ml</b>.",
  "ex": ["3 m a centímetres|3 m a centímetros", "De m a cm hi ha 2 graons: × 100|De m a cm hay 2 peldaños: × 100", "3 m = <span class=\"hl\">300 cm</span>|3 m = <span class=\"hl\">300 cm</span>"] },
{ "t": "Massa i capacitat|Masa y capacidad", "x": "1 kg = <b>1.000 g</b>, 1 g = 1.000 mg i una tona (t) són 1.000 kg. Una ampolla d'aigua gran fa 1,5 l, i <b>1 litre = 1 dm³</b>: el que hi cap en un cub de 10 cm de costat.|1 kg = <b>1.000 g</b>, 1 g = 1.000 mg y una tonelada (t) son 1.000 kg. Una botella de agua grande tiene 1,5 l, y <b>1 litro = 1 dm³</b>: lo que cabe en un cubo de 10 cm de lado.",
  "ex": ["1,5 kg a grams|1,5 kg a gramos", "1 kg = 1.000 g|1 kg = 1.000 g", "1,5 × 1.000 = <span class=\"hl\">1.500 g</span>|1,5 × 1.000 = <span class=\"hl\">1.500 g</span>"] },
{ "t": "La superfície|La superficie", "x": "La superfície es mesura amb quadrats: <b>m², dm², cm²</b>. Aquí cada graó val <b>100</b>, perquè un quadrat d'1 dm de costat té 10 × 10 = 100 cm². Per a camps i boscos fem servir l'<b>hectàrea</b>: 1 ha = 10.000 m², un quadrat de 100 m de costat.|La superficie se mide con cuadrados: <b>m², dm², cm²</b>. Aquí cada peldaño vale <b>100</b>, porque un cuadrado de 1 dm de lado tiene 10 × 10 = 100 cm². Para campos y bosques usamos la <b>hectárea</b>: 1 ha = 10.000 m², un cuadrado de 100 m de lado.",
  "ex": ["4 m² a dm²|4 m² a dm²", "Cada graó de superfície val 100|Cada peldaño de superficie vale 100", "4 m² = <span class=\"hl\">400 dm²</span>|4 m² = <span class=\"hl\">400 dm²</span>"] },
{ "t": "El temps i les dades|El tiempo y los datos", "x": "El temps no va de 10 en 10: 1 h = <b>60 min</b> i 1 min = <b>60 s</b>. Les dades digitals es mesuren en <b>bytes, KB, MB, GB i TB</b>: cada unitat són unes 1.000 vegades l'anterior (exactament, 1.024). Una foto del mòbil ocupa uns quants MB; una pel·lícula, uns quants GB.|El tiempo no va de 10 en 10: 1 h = <b>60 min</b> y 1 min = <b>60 s</b>. Los datos digitales se miden en <b>bytes, KB, MB, GB y TB</b>: cada unidad son unas 1.000 veces la anterior (exactamente, 1.024). Una foto del móvil ocupa unos cuantos MB; una película, unos cuantos GB.",
  "ex": ["2 h 15 min a minuts|2 h 15 min a minutos", "2 × 60 = 120|2 × 60 = 120", "120 + 15 = <span class=\"hl\">135 min</span>|120 + 15 = <span class=\"hl\">135 min</span>"] }
],
"words": [["metre (m)|metro (m)", "la unitat principal de longitud|la unidad principal de longitud"], ["gram (g)|gramo (g)", "unitat de massa; 1.000 g fan 1 kg|unidad de masa; 1.000 g hacen 1 kg"], ["litre (l)|litro (l)", "unitat de capacitat; 1 l = 1 dm³|unidad de capacidad; 1 l = 1 dm³"], ["metre quadrat (m²)|metro cuadrado (m²)", "un quadrat d'1 m de costat|un cuadrado de 1 m de lado"], ["hectàrea (ha)|hectárea (ha)", "10.000 m²|10.000 m²"], ["megabyte (MB)|megabyte (MB)", "unes 1.000 KB|unos 1.000 KB"]],
"mistakes": [["«150 minuts són 1 h 50 min.»|«150 minutos son 1 h 50 min.»", "Una hora són 60 minuts, no 100: 150 = 60 + 60 + 30, és a dir, 2 h 30 min.|Una hora son 60 minutos, no 100: 150 = 60 + 60 + 30, es decir, 2 h 30 min."], ["«1 m² = 100 cm².»|«1 m² = 100 cm².»", "A la superfície cada graó val 100: 1 m² = 100 dm² = 10.000 cm².|En la superficie cada peldaño vale 100: 1 m² = 100 dm² = 10.000 cm²."], ["«Per passar de cm a m, multiplico.»|«Para pasar de cm a m, multiplico.»", "De petita a gran es divideix: 250 cm = 2,5 m.|De pequeña a grande se divide: 250 cm = 2,5 m."]],
"recap": ["Longitud i capacitat: cada graó × 10.|Longitud y capacidad: cada peldaño × 10.", "Massa: 1 t = 1.000 kg, 1 kg = 1.000 g.|Masa: 1 t = 1.000 kg, 1 kg = 1.000 g.", "Superfície: cada graó × 100; 1 ha = 10.000 m².|Superficie: cada peldaño × 100; 1 ha = 10.000 m².", "Temps: 1 h = 60 min = 3.600 s.|Tiempo: 1 h = 60 min = 3.600 s."],
"tip": "Pensa-ho abans de calcular: si passes a una unitat més petita, et sortirà un número més gran (3 m = 300 cm), i al revés.|Piénsalo antes de calcular: si pasas a una unidad más pequeña, te saldrá un número mayor (3 m = 300 cm), y al revés."
},
"c5-11": {
"hook": "Les rajoles, els senyals de trànsit i les ales d'una papallona amaguen polígons i simetries.|Las baldosas, las señales de tráfico y las alas de una mariposa esconden polígonos y simetrías.",
"parts": [
{ "t": "Rectes i angles|Rectas y ángulos", "x": "Recorda: les rectes <b>paral·leles</b> no es tallen mai, les <b>perpendiculars</b> es tallen fent angles rectes i les <b>oblíqües</b> es tallen sense fer-ne. Als plànols dels carrers ho veuràs sovint.|Recuerda: las rectas <b>paralelas</b> no se cortan nunca, las <b>perpendiculares</b> se cortan formando ángulos rectos y las <b>oblicuas</b> se cortan sin formarlos. En los planos de las calles lo verás a menudo.",
  "ex": ["Dos carrers que no es troben mai|Dos calles que no se encuentran nunca", "Sempre a la mateixa distància|Siempre a la misma distancia", "Són <span class=\"hl\">paral·lels</span>|Son <span class=\"hl\">paralelas</span>"] },
{ "t": "Nom i cognom dels triangles|Nombre y apellido de los triángulos", "x": "Un triangle té un nom pels angles (acutangle, rectangle o obtusangle) i un altre pels costats (equilàter, isòsceles o escalè). Per exemple, un triangle amb un angle recte i dos costats iguals és <b>rectangle i isòsceles</b>.|Un triángulo tiene un nombre por los ángulos (acutángulo, rectángulo u obtusángulo) y otro por los lados (equilátero, isósceles o escaleno). Por ejemplo, un triángulo con un ángulo recto y dos lados iguales es <b>rectángulo e isósceles</b>.",
  "ex": ["Angles: 90°, 45° i 45°|Ángulos: 90°, 45° y 45°", "Té un angle recte i dos costats iguals|Tiene un ángulo recto y dos lados iguales", "És <span class=\"hl\">rectangle i isòsceles</span>|Es <span class=\"hl\">rectángulo e isósceles</span>"] },
{ "t": "Polígons regulars|Polígonos regulares", "x": "Un polígon és <b>regular</b> si té tots els costats iguals i tots els angles iguals. Segons els costats es diuen triangle (3), quadrilàter (4), pentàgon (5), hexàgon (6), heptàgon (7), octàgon (8), enneàgon (9) i decàgon (10). El rectangle no és regular (té costats diferents) i el rombe tampoc (té angles diferents).|Un polígono es <b>regular</b> si tiene todos los lados iguales y todos los ángulos iguales. Según los lados se llaman triángulo (3), cuadrilátero (4), pentágono (5), hexágono (6), heptágono (7), octágono (8), eneágono (9) y decágono (10). El rectángulo no es regular (tiene lados diferentes) y el rombo tampoco (tiene ángulos diferentes).",
  "ex": ["Un senyal de STOP té 8 costats iguals|Una señal de STOP tiene 8 lados iguales", "I els 8 angles també són iguals|Y los 8 ángulos también son iguales", "És un <span class=\"hl\">octàgon regular</span>|Es un <span class=\"hl\">octágono regular</span>"] },
{ "t": "Eixos de simetria|Ejes de simetría", "x": "Un <b>eix de simetria</b> és una línia que parteix la figura en dues meitats que coincideixen quan la doblegues. Un polígon regular en té tants com costats. El rectangle en té 2 (però les diagonals <b>no</b> ho són), el rombe en té 2 (les seves diagonals), el triangle isòsceles 1 i el romboide, cap.|Un <b>eje de simetría</b> es una línea que parte la figura en dos mitades que coinciden al doblarla. Un polígono regular tiene tantos como lados. El rectángulo tiene 2 (pero las diagonales <b>no</b> lo son), el rombo tiene 2 (sus diagonales), el triángulo isósceles 1 y el romboide, ninguno.",
  "ex": ["Un hexàgon regular|Un hexágono regular", "Té 6 costats iguals|Tiene 6 lados iguales", "Té <span class=\"hl\">6 eixos</span> de simetria|Tiene <span class=\"hl\">6 ejes</span> de simetría"] }
],
"words": [["polígon regular|polígono regular", "amb tots els costats i tots els angles iguals|con todos los lados y todos los ángulos iguales"], ["eix de simetria|eje de simetría", "línia que parteix una figura en dues meitats iguals|línea que parte una figura en dos mitades iguales"], ["diagonal|diagonal", "segment que uneix dos vèrtexs no veïns|segmento que une dos vértices no vecinos"], ["oblíqües|oblicuas", "rectes que es tallen sense fer angle recte|rectas que se cortan sin formar ángulo recto"]],
"mistakes": [["«La diagonal d'un rectangle és un eix de simetria.»|«La diagonal de un rectángulo es un eje de simetría.»", "Si el doblegues per la diagonal, les puntes no coincideixen: el rectangle només en té 2.|Si lo doblas por la diagonal, las puntas no coinciden: el rectángulo solo tiene 2."], ["«El rombe és regular perquè té els costats iguals.»|«El rombo es regular porque tiene los lados iguales.»", "També cal que tingui tots els angles iguals; dels quadrilàters, només el quadrat és regular.|También hace falta que tenga todos los ángulos iguales; de los cuadriláteros, solo el cuadrado es regular."]],
"recap": ["Regular = costats iguals i angles iguals.|Regular = lados iguales y ángulos iguales.", "Un polígon regular té tants eixos de simetria com costats.|Un polígono regular tiene tantos ejes de simetría como lados.", "Els triangles tenen nom pels angles i pels costats.|Los triángulos tienen nombre por los ángulos y por los lados."],
"tip": "Per saber si una línia és un eix, imagina que plegues el paper per allà: les dues parts han de quedar exactament una sobre l'altra.|Para saber si una línea es un eje, imagina que doblas el papel por ahí: las dos partes tienen que quedar exactamente una sobre la otra."
},
"c5-12": {
"hook": "Els decimals viuen entre els nombres naturals, i els robots (i els personatges dels jocs) poden fer moltes coses alhora.|Los decimales viven entre los números naturales, y los robots (y los personajes de los juegos) pueden hacer muchas cosas a la vez.",
"parts": [
{ "t": "Dècimes a la recta|Décimas en la recta", "x": "Entre dos nombres naturals, com el 2 i el 3, hi caben les <b>dècimes</b>: si partim el tros en 10 parts, cada marca és 0,1. Així trobem 2,1; 2,2; 2,3… El 2,5 és just al mig.|Entre dos números naturales, como el 2 y el 3, caben las <b>décimas</b>: si partimos el trozo en 10 partes, cada marca es 0,1. Así encontramos 2,1; 2,2; 2,3… El 2,5 está justo en el medio.",
  "ex": ["Del 2 al 3 hi ha 10 marques|Del 2 al 3 hay 10 marcas", "Cada marca és 0,1|Cada marca es 0,1", "La setena marca és el <span class=\"hl\">2,7</span>|La séptima marca es el <span class=\"hl\">2,7</span>"] },
{ "t": "Centèsimes a la recta|Centésimas en la recta", "x": "Si fem zoom entre 2,3 i 2,4 i el partim en 10 parts més, cada marca és una <b>centèsima</b>: 2,31; 2,32… fins a 2,39. Recorda que 2,4 = 2,40.|Si hacemos zoom entre 2,3 y 2,4 y lo partimos en 10 partes más, cada marca es una <b>centésima</b>: 2,31; 2,32… hasta 2,39. Recuerda que 2,4 = 2,40.",
  "ex": ["Del 2,3 al 2,4 hi ha 10 marques|Del 2,3 al 2,4 hay 10 marcas", "Cada marca és 0,01|Cada marca es 0,01", "La cinquena marca és el <span class=\"hl\">2,35</span>|La quinta marca es el <span class=\"hl\">2,35</span>"] },
{ "t": "Programes alhora|Programas a la vez", "x": "Quan dos programes comencen alhora (tots dos quan es clica la bandera), treballen <b>al mateix temps</b>: el temps total és el del que triga més. Si un espera un missatge de l'altre per començar, van un darrere l'altre i els temps se sumen.|Cuando dos programas empiezan a la vez (los dos al hacer clic en la bandera), trabajan <b>al mismo tiempo</b>: el tiempo total es el del que tarda más. Si uno espera un mensaje del otro para empezar, van uno detrás de otro y los tiempos se suman.",
  "ex": ["El gat fa 4 passos i el gos, 6, alhora|El gato da 4 pasos y el perro, 6, a la vez", "Treballen al mateix temps|Trabajan al mismo tiempo", "Acaben als <span class=\"hl\">6 segons</span>|Acaban a los <span class=\"hl\">6 segundos</span>"] },
{ "t": "Dos robots alhora|Dos robots a la vez", "x": "Si dos robots fan les seves ordres alhora, a cada segon tots dos fan un pas. Per saber si es trobaran, mou-los <b>pas a pas</b> i mira on és cada un al mateix moment.|Si dos robots hacen sus órdenes a la vez, en cada segundo los dos dan un paso. Para saber si se encontrarán, muévelos <b>paso a paso</b> y mira dónde está cada uno en el mismo momento.",
  "ex": ["Pas 1: cada robot fa la seva primera ordre|Paso 1: cada robot hace su primera orden", "Pas 2: cada robot fa la segona|Paso 2: cada robot hace la segunda", "Si coincideixen a la mateixa casella, <span class=\"hl\">es troben</span>|Si coinciden en la misma casilla, <span class=\"hl\">se encuentran</span>"] }
],
"words": [["dècima|décima", "una de les 10 parts d'una unitat: 0,1|una de las 10 partes de una unidad: 0,1"], ["centèsima|centésima", "una de les 100 parts d'una unitat: 0,01|una de las 100 partes de una unidad: 0,01"], ["alhora|a la vez", "al mateix temps|al mismo tiempo"], ["missatge|mensaje", "un avís que un programa envia a un altre|un aviso que un programa envía a otro"]],
"mistakes": [["«2,45 és més gran que 2,5 perquè 45 és més que 5.»|«2,45 es mayor que 2,5 porque 45 es más que 5.»", "2,5 = 2,50, i a la recta 2,50 és més a la dreta que 2,45.|2,5 = 2,50, y en la recta 2,50 está más a la derecha que 2,45."], ["«Si un robot triga 4 s i l'altre 6 s, alhora triguen 10 s.»|«Si un robot tarda 4 s y el otro 6 s, a la vez tardan 10 s.»", "Alhora treballen al mateix temps: acaben quan acaba el més lent, als 6 s.|A la vez trabajan al mismo tiempo: acaban cuando acaba el más lento, a los 6 s."]],
"recap": ["Entre dos naturals hi ha 10 dècimes; entre dues dècimes, 10 centèsimes.|Entre dos naturales hay 10 décimas; entre dos décimas, 10 centésimas.", "Alhora: el temps total és el del més llarg.|A la vez: el tiempo total es el del más largo.", "Un darrere l'altre: els temps se sumen.|Uno detrás de otro: los tiempos se suman."],
"tip": "A la recta, abans de llegir, pregunta't: quant val cada marca? I amb els robots, fes servir els dits: un dit per a cada robot.|En la recta, antes de leer, pregúntate: ¿cuánto vale cada marca? Y con los robots, usa los dedos: un dedo para cada robot."
},
"c6-10": {
"hook": "«La meitat», «0,5» i «50 %» són el mateix nombre dit de tres maneres. Les rebaixes, les notes i les receptes les fan servir totes.|«La mitad», «0,5» y «50 %» son el mismo número dicho de tres maneras. Las rebajas, las notas y las recetas las usan todas.",
"parts": [
{ "t": "De fracció a decimal|De fracción a decimal", "x": "Una fracció és una divisió: divideix el numerador entre el denominador. 3/4 = 3 ÷ 4 = <b>0,75</b>. Si el denominador és 10 o 100 és directe: 7/10 = 0,7 i 35/100 = 0,35.|Una fracción es una división: divide el numerador entre el denominador. 3/4 = 3 ÷ 4 = <b>0,75</b>. Si el denominador es 10 o 100 es directo: 7/10 = 0,7 y 35/100 = 0,35.",
  "ex": ["2/5|2/5", "2 ÷ 5 = 0,4|2 ÷ 5 = 0,4", "2/5 = <span class=\"hl\">0,4</span>|2/5 = <span class=\"hl\">0,4</span>"] },
{ "t": "De decimal a percentatge|De decimal a porcentaje", "x": "Un <b>percentatge</b> diu quantes parts de cada 100. Per passar d'un decimal a percentatge, multiplica per 100: 0,75 = 75 %. I al revés, divideix per 100: 40 % = 0,4.|Un <b>porcentaje</b> dice cuántas partes de cada 100. Para pasar de un decimal a porcentaje, multiplica por 100: 0,75 = 75 %. Y al revés, divide entre 100: 40 % = 0,4.",
  "ex": ["0,4|0,4", "0,4 × 100 = 40|0,4 × 100 = 40", "0,4 = <span class=\"hl\">40 %</span>|0,4 = <span class=\"hl\">40 %</span>"] },
{ "t": "Ordenar nombres de tota mena|Ordenar números de todo tipo", "x": "Per comparar fraccions, decimals i percentatges, passa-ho tot a la mateixa forma, per exemple a decimal, i després ordena. 3/4 = 0,75; 70 % = 0,70; 0,8 = 0,80.|Para comparar fracciones, decimales y porcentajes, pásalo todo a la misma forma, por ejemplo a decimal, y después ordena. 3/4 = 0,75; 70 % = 0,70; 0,8 = 0,80.",
  "ex": ["3/4, 70 % i 0,8|3/4, 70 % y 0,8", "0,75; 0,70 i 0,80|0,75; 0,70 y 0,80", "70 % &lt; 3/4 &lt; <span class=\"hl\">0,8</span>|70 % &lt; 3/4 &lt; <span class=\"hl\">0,8</span>"] },
{ "t": "Fraccions a la recta|Fracciones en la recta", "x": "Per situar una fracció a la recta, parteix cada unitat en tantes parts com diu el denominador i compta tantes marques com diu el numerador. Si el numerador és més gran que el denominador, la fracció passa de l'1.|Para situar una fracción en la recta, parte cada unidad en tantas partes como dice el denominador y cuenta tantas marcas como dice el numerador. Si el numerador es mayor que el denominador, la fracción pasa del 1.",
  "ex": ["On és 5/4?|¿Dónde está 5/4?", "Cada unitat en 4 parts; compta 5 marques|Cada unidad en 4 partes; cuenta 5 marcas", "Una marca després de l'1: <span class=\"hl\">5/4</span>|Una marca después del 1: <span class=\"hl\">5/4</span>"] }
],
"words": [["numerador|numerador", "el número de dalt: les parts que agafem|el número de arriba: las partes que cogemos"], ["denominador|denominador", "el número de baix: en quantes parts dividim|el número de abajo: en cuántas partes dividimos"], ["percentatge (%)|porcentaje (%)", "parts de cada 100|partes de cada 100"], ["equivalents|equivalentes", "que valen el mateix, com 1/2 i 2/4|que valen lo mismo, como 1/2 y 2/4"]],
"mistakes": [["«1/4 = 0,4.»|«1/4 = 0,4.»", "1/4 = 1 ÷ 4 = 0,25.|1/4 = 1 ÷ 4 = 0,25."], ["«El 0,5 % és la meitat.»|«El 0,5 % es la mitad.»", "La meitat és el 50 %; el 0,5 % és molt poca cosa (5 de cada 1.000).|La mitad es el 50 %; el 0,5 % es muy poco (5 de cada 1.000)."], ["«El 30 % és més que 1/2 perquè 30 és més que 1.»|«El 30 % es más que 1/2 porque 30 es más que 1.»", "1/2 = 50 %, que és més que el 30 %.|1/2 = 50 %, que es más que el 30 %."]],
"recap": ["Fracció → decimal: divideix.|Fracción → decimal: divide.", "Decimal → percentatge: × 100.|Decimal → porcentaje: × 100.", "Per ordenar, passa-ho tot a decimal.|Para ordenar, pásalo todo a decimal."],
"tip": "Aprèn-te les parelles més famoses: 1/2 = 0,5 = 50 %, 1/4 = 0,25 = 25 %, 3/4 = 0,75 = 75 % i 1/10 = 0,1 = 10 %.|Apréndete las parejas más famosas: 1/2 = 0,5 = 50 %, 1/4 = 0,25 = 25 %, 3/4 = 0,75 = 75 % y 1/10 = 0,1 = 10 %."
},
"c6-11": {
"hook": "Comprar amb cap vol dir saber quin paquet surt més bé, entendre l'IVA del tiquet i saber com funcionen els interessos del banc.|Comprar con cabeza quiere decir saber qué paquete sale mejor, entender el IVA del tique y saber cómo funcionan los intereses del banco.",
"parts": [
{ "t": "El millor preu|El mejor precio", "x": "Per comparar paquets diferents, calcula el <b>preu unitari</b>: el preu d'una unitat o d'un quilo. Preu unitari = preu ÷ quantitat. El paquet gran no sempre és el que surt més bé!|Para comparar paquetes diferentes, calcula el <b>precio unitario</b>: el precio de una unidad o de un kilo. Precio unitario = precio ÷ cantidad. ¡El paquete grande no siempre es el que sale mejor!",
  "ex": ["4 iogurts per 2,40 € o 6 per 3,30 €|4 yogures por 2,40 € o 6 por 3,30 €", "2,40 ÷ 4 = 0,60 €; 3,30 ÷ 6 = 0,55 €|2,40 ÷ 4 = 0,60 €; 3,30 ÷ 6 = 0,55 €", "Surt més bé el <span class=\"hl\">de 6</span>|Sale mejor el <span class=\"hl\">de 6</span>"] },
{ "t": "L'IVA|El IVA", "x": "L'<b>IVA</b> és un impost que s'afegeix al preu i que va a l'Estat per pagar serveis de tothom. A Espanya, el general és del <b>21 %</b>; el dels restaurants i el transport, del 10 %; i el del pa, la llet i els llibres, del 4 %. Preu final = preu + IVA.|El <b>IVA</b> es un impuesto que se añade al precio y que va al Estado para pagar servicios de todos. En España, el general es del <b>21 %</b>; el de los restaurantes y el transporte, del 10 %; y el del pan, la leche y los libros, del 4 %. Precio final = precio + IVA.",
  "ex": ["200 € sense IVA, amb IVA del 21 %|200 € sin IVA, con IVA del 21 %", "IVA: 200 × 21 ÷ 100 = 42 €|IVA: 200 × 21 ÷ 100 = 42 €", "Preu final: <span class=\"hl\">242 €</span>|Precio final: <span class=\"hl\">242 €</span>"] },
{ "t": "Els interessos|Los intereses", "x": "Si guardes diners al banc, et paguen un tant per cent cada any: és l'<b>interès</b>. Si en demanes (un préstec), el pagues tu. Amb l'<b>interès simple</b> cobres el mateix cada any: interès = capital × % ÷ 100 × anys.|Si guardas dinero en el banco, te pagan un tanto por ciento cada año: es el <b>interés</b>. Si pides (un préstamo), lo pagas tú. Con el <b>interés simple</b> cobras lo mismo cada año: interés = capital × % ÷ 100 × años.",
  "ex": ["500 € al 2 % durant 3 anys|500 € al 2 % durante 3 años", "Cada any: 500 × 2 ÷ 100 = 10 €|Cada año: 500 × 2 ÷ 100 = 10 €", "En 3 anys: <span class=\"hl\">30 €</span>|En 3 años: <span class=\"hl\">30 €</span>"] },
{ "t": "Superfície i volum|Superficie y volumen", "x": "A la superfície cada graó val 100 (m², dm², cm²) i 1 ha = 10.000 m². Al volum cada graó val <b>1.000</b>: 1 m³ = 1.000 dm³ i 1 dm³ = 1.000 cm³. I es relaciona amb la capacitat: <b>1 dm³ = 1 l</b>, 1 cm³ = 1 ml i 1 m³ = 1.000 l.|En la superficie cada peldaño vale 100 (m², dm², cm²) y 1 ha = 10.000 m². En el volumen cada peldaño vale <b>1.000</b>: 1 m³ = 1.000 dm³ y 1 dm³ = 1.000 cm³. Y se relaciona con la capacidad: <b>1 dm³ = 1 l</b>, 1 cm³ = 1 ml y 1 m³ = 1.000 l.",
  "ex": ["Un aquari de 5 dm × 3 dm × 4 dm|Un acuario de 5 dm × 3 dm × 4 dm", "5 × 3 × 4 = 60 dm³|5 × 3 × 4 = 60 dm³", "Hi caben <span class=\"hl\">60 litres</span>|Caben <span class=\"hl\">60 litros</span>"] }
],
"words": [["preu unitari|precio unitario", "el preu d'una unitat o d'un quilo|el precio de una unidad o de un kilo"], ["IVA|IVA", "impost sobre el valor afegit: un % que s'afegeix al preu|impuesto sobre el valor añadido: un % que se añade al precio"], ["interès|interés", "el que paga el banc per guardar-hi diners (o el que pagues tu per demanar-ne)|lo que paga el banco por guardar dinero (o lo que pagas tú por pedirlo)"], ["capital|capital", "els diners que guardes o que demanes|el dinero que guardas o que pides"], ["metre cúbic (m³)|metro cúbico (m³)", "un cub d'1 m de costat: 1.000 litres|un cubo de 1 m de lado: 1.000 litros"]],
"mistakes": [["«El paquet gran sempre surt més barat.»|«El paquete grande siempre sale más barato.»", "Calcula el preu de cada unitat: de vegades el petit surt més bé.|Calcula el precio de cada unidad: a veces el pequeño sale mejor."], ["«1 m³ = 100 dm³.»|«1 m³ = 100 dm³.»", "Al volum cada graó val 1.000: 1 m³ = 1.000 dm³ = 1.000 litres.|En el volumen cada peldaño vale 1.000: 1 m³ = 1.000 dm³ = 1.000 litros."]],
"recap": ["Preu unitari = preu ÷ quantitat.|Precio unitario = precio ÷ cantidad.", "Preu amb IVA = preu + el % d'IVA.|Precio con IVA = precio + el % de IVA.", "Interès simple: el mateix cada any.|Interés simple: lo mismo cada año.", "1 dm³ = 1 l i 1 m³ = 1.000 l.|1 dm³ = 1 l y 1 m³ = 1.000 l."],
"tip": "Per calcular un %, troba primer l'1 % (divideix entre 100) i després multiplica: el 21 % de 300 és 3 × 21 = 63.|Para calcular un %, encuentra primero el 1 % (divide entre 100) y después multiplica: el 21 % de 300 es 3 × 21 = 63."
},
"c6-12": {
"hook": "Els mapes del mòbil, els gràfics de les notícies i els videojocs fan servir coordenades, dades i programes amb bucles.|Los mapas del móvil, los gráficos de las noticias y los videojuegos usan coordenadas, datos y programas con bucles.",
"parts": [
{ "t": "Els enters a la recta|Los enteros en la recta", "x": "A l'esquerra del 0 hi ha els nombres <b>negatius</b>: −1, −2, −3… Com més a l'esquerra, més petit: −8 és més petit que −3. Moure's cap a la dreta vol dir sumar i cap a l'esquerra, restar.|A la izquierda del 0 están los números <b>negativos</b>: −1, −2, −3… Cuanto más a la izquierda, más pequeño: −8 es menor que −3. Moverse hacia la derecha quiere decir sumar y hacia la izquierda, restar.",
  "ex": ["Ets al −3 i fas 5 salts cap a la dreta|Estás en el −3 y das 5 saltos hacia la derecha", "−3 + 5|−3 + 5", "Arribes al <span class=\"hl\">2</span>|Llegas al <span class=\"hl\">2</span>"] },
{ "t": "Coordenades cartesianes|Coordenadas cartesianas", "x": "Dues rectes numèriques perpendiculars formen els <b>eixos</b>: l'eix <b>x</b> (horitzontal) i l'eix <b>y</b> (vertical). Cada punt té dues coordenades, (x, y): primer quant avances cap a la dreta i després quant puges. El punt (3, 5) i el (5, 3) són diferents!|Dos rectas numéricas perpendiculares forman los <b>ejes</b>: el eje <b>x</b> (horizontal) y el eje <b>y</b> (vertical). Cada punto tiene dos coordenadas, (x, y): primero cuánto avanzas hacia la derecha y después cuánto subes. ¡El punto (3, 5) y el (5, 3) son diferentes!",
  "ex": ["Surt del (0, 0)|Sal del (0, 0)", "Avança 3 cap a la dreta i puja 5|Avanza 3 hacia la derecha y sube 5", "Ets al punt <span class=\"hl\">(3, 5)</span>|Estás en el punto <span class=\"hl\">(3, 5)</span>"] },
{ "t": "La mediana|La mediana", "x": "La <b>mediana</b> és el valor del mig quan ordenes les dades de més petita a més gran. Si n'hi ha un nombre parell, és la mitjana dels dos del mig. Un valor molt gran estira la mitjana, però gairebé no mou la mediana.|La <b>mediana</b> es el valor del centro cuando ordenas los datos de menor a mayor. Si hay un número par de datos, es la media de los dos del centro. Un valor muy grande estira la media, pero casi no mueve la mediana.",
  "ex": ["Dades: 9, 3, 21, 5, 7|Datos: 9, 3, 21, 5, 7", "Ordenades: 3, 5, 7, 9, 21|Ordenados: 3, 5, 7, 9, 21", "La mediana és <span class=\"hl\">7</span>|La mediana es <span class=\"hl\">7</span>"] },
{ "t": "Bucles dins de bucles|Bucles dentro de bucles", "x": "Un bucle pot anar dins d'un altre: si el de fora es repeteix 3 vegades i el de dins 4, l'ordre de dins es fa <b>3 × 4 = 12</b> vegades. Quan un programa no fa el que volíem, cal <b>trobar l'error</b>: segueix-lo pas a pas i mira on es desvia.|Un bucle puede ir dentro de otro: si el de fuera se repite 3 veces y el de dentro 4, la orden de dentro se hace <b>3 × 4 = 12</b> veces. Cuando un programa no hace lo que queríamos, hay que <b>encontrar el error</b>: síguelo paso a paso y mira dónde se desvía.",
  "ex": ["repeteix 3 vegades: repeteix 4 vegades: n = n + 1|repite 3 veces: repite 4 veces: n = n + 1", "La suma es fa 3 × 4 = 12 vegades|La suma se hace 3 × 4 = 12 veces", "Si n comença a 0, acaba a <span class=\"hl\">12</span>|Si n empieza en 0, acaba en <span class=\"hl\">12</span>"] }
],
"words": [["nombre negatiu|número negativo", "un nombre més petit que 0, com −4|un número menor que 0, como −4"], ["eix x|eje x", "l'eix horitzontal|el eje horizontal"], ["eix y|eje y", "l'eix vertical|el eje vertical"], ["coordenades|coordenadas", "la parella (x, y) que diu on és un punt|la pareja (x, y) que dice dónde está un punto"], ["mediana|mediana", "el valor del mig de les dades ordenades|el valor del centro de los datos ordenados"], ["bucle niat|bucle anidado", "un bucle dins d'un altre|un bucle dentro de otro"]],
"mistakes": [["«El punt (2, 5) és 2 amunt i 5 a la dreta.»|«El punto (2, 5) está 2 arriba y 5 a la derecha.»", "Primer va la x (cap a la dreta) i després la y (cap amunt): 2 a la dreta i 5 amunt.|Primero va la x (hacia la derecha) y después la y (hacia arriba): 2 a la derecha y 5 arriba."], ["«La mediana de 9, 3, 7 és 3, que és el del mig.»|«La mediana de 9, 3, 7 es 3, que es el del centro.»", "Primer s'ordena: 3, 7, 9. La mediana és 7.|Primero se ordena: 3, 7, 9. La mediana es 7."], ["«−8 és més gran que −3 perquè 8 és més que 3.»|«−8 es mayor que −3 porque 8 es más que 3.»", "A la recta, −8 és més a l'esquerra: −8 &lt; −3.|En la recta, −8 está más a la izquierda: −8 &lt; −3."]],
"recap": ["Els negatius són a l'esquerra del 0.|Los negativos están a la izquierda del 0.", "Coordenades (x, y): primer la dreta, després amunt.|Coordenadas (x, y): primero a la derecha, después arriba.", "Mediana: ordena i agafa el del mig.|Mediana: ordena y coge el del centro.", "Bucle dins de bucle: multiplica les repeticions.|Bucle dentro de bucle: multiplica las repeticiones."],
"tip": "Per recordar l'ordre de les coordenades: «primer camino, després pujo». La x va abans que la y, com a l'abecedari.|Para recordar el orden de las coordenadas: «primero camino, después subo». La x va antes que la y, como en el abecedario."
}
});
