/* Tech 3D · Nivell 1 · unitat 3 «Moure, girar i escalar» (m3-1 … m3-4)
   Contingut propi de Numi. Fil narratiu: el Taller de Bit i la Nuvi (la impressora 3D) reben l'encàrrec de l'escola del
   barri: un robot de peces per a la Setmana de la Robòtica. m3-1 moure amb precisió (dit, números i quadrícula magnètica),
   m3-2 girar (15°, 45°, 90°; en z i tombant en x/y), m3-3 escalar (una mida, proporcional, doble i meitat, figures 2:1) i
   m3-4 el projecte: el robot de peces a partir d'una fitxa tècnica.
   Models: peces { id, t, s: [x, y, z] (mm), p: centre, r: graus, c: color }, placa de 200 × 200 mm centrada a l'origen. */
Object.assign(TBADGE, {
  m31_prec: { id: 'm31_prec', ico: '🎯', n: 'Mà de precisió|Mano de precisión', d: 'Col·loques les peces al mil·límetre, amb el dit i amb números.|Colocas las piezas al milímetro, con el dedo y con números.' },
  m32_gir: { id: 'm32_gir', ico: '🔄', n: 'Mestre/a del gir|Maestro/a del giro', d: 'Gires peces 15°, 45° i 90°, en planta i tombant-les de costat.|Giras piezas 15°, 45° y 90°, en planta y tumbándolas de lado.' },
  m33_esc: { id: 'm33_esc', ico: '🔍', n: "Lupa d'escala|Lupa de escala", d: 'Fas peces i figures al doble i a la meitat sense deformar-les.|Haces piezas y figuras al doble y a la mitad sin deformarlas.' },
  m34_rob: { id: 'm34_rob', ico: '🤖', n: 'Constructor/a de robots|Constructor/a de robots', d: 'Projecte acabat: un robot de peces fet amb una fitxa tècnica, amb peces mogudes, girades i escalades.|Proyecto terminado: un robot de piezas hecho con una ficha técnica, con piezas movidas, giradas y escaladas.' }
});
COURSE_UNITS[3] = (() => {
  const P = (id, t, s, p, c, o = {}) => ({ id, t, s, p, r: o.r || [0, 0, 0], c, ...o });
  // B: la z que es dona és la de la BASE (com a la pestanya Posició) i h és l'alçada real de la peça (girada o no)
  const B = (id, t, s, x, y, z0, c, o = {}) => P(id, t, s, [x, y, z0 + (o.h ?? s[2]) / 2], c, o);
  const cub = (x, y, z0 = 0, id = 'a1', c = '#7C5CFF', m = 20) => B(id, 'box', [m, m, m], x, y, z0, c);
  // ---- m3-1 · moure amb precisió ----
  const PUNTS = [B('a', 'cyl', [12, 12, 12], 35, 15, 0, '#E8453C'), B('b', 'cyl', [12, 12, 12], 15, 35, 0, '#3D7BF4'), B('c', 'cyl', [12, 12, 12], -35, 15, 0, '#2FB36D'), B('d', 'cyl', [12, 12, 12], 35, -15, 0, '#F7C531'), B('e', 'cyl', [12, 12, 12], -15, -35, 0, '#EC5FA8')];
  const TRES0 = [B('a1', 'cyl', [16, 16, 16], -45, 25, 0, '#3D7BF4'), B('a2', 'box', [16, 16, 16], -20, 0, 0, '#FF8A3D'), B('a3', 'cone', [16, 16, 20], 5, -25, 0, '#2FB36D')];
  const TRES1 = [B('a1', 'cyl', [16, 16, 16], -20, 25, 0, '#3D7BF4'), B('a2', 'box', [16, 16, 16], 5, 0, 0, '#FF8A3D'), B('a3', 'cone', [16, 16, 20], 30, -25, 0, '#2FB36D')];
  const CAP = B('cap', 'box', [30, 20, 20], 0, 0, 0, '#5BC0EB'), BOCA = B('boca', 'box', [14, 2, 3], 0, -10, 5, '#2A2F3A');
  const CARA0 = [CAP, BOCA, B('u1', 'sph', [6, 6, 6], -30, -30, 0, '#2A2F3A'), B('u2', 'sph', [6, 6, 6], 30, -30, 0, '#2A2F3A')];
  const CARA1 = [CAP, BOCA, B('u1', 'sph', [6, 6, 6], -8, -10, 10, '#2A2F3A'), B('u2', 'sph', [6, 6, 6], 8, -10, 10, '#2A2F3A')];
  const CAPSA = B('capsa', 'box', [40, 30, 16], 0, 0, 0, '#F5893A');
  const TAPA0 = [CAPSA, B('tapa', 'box', [42, 32, 4], 3, -2, 16, '#E8453C')], TAPA1 = [CAPSA, B('tapa', 'box', [42, 32, 4], 0, 0, 16, '#E8453C')];
  const TORRE0 = [B('t1', 'cyl', [30, 30, 12], -40, 20, 0, '#3D7BF4'), B('t2', 'cyl', [20, 20, 8], 0, 35, 0, '#2FB36D'), B('t3', 'cyl', [10, 10, 5], 35, 25, 0, '#F7C531')];
  const TORRE1 = [B('t1', 'cyl', [30, 30, 12], 0, 0, 0, '#3D7BF4'), B('t2', 'cyl', [20, 20, 8], 0, 0, 12, '#2FB36D'), B('t3', 'cyl', [10, 10, 5], 0, 0, 20, '#F7C531')];
  // ---- m3-2 · girar ----
  const bar = (id, x, y, rz, c, l = 50) => B(id, 'box', [l, 10, 10], x, y, 0, c, { r: [0, 0, rz] });
  const BARRES = [bar('b0', -35, 25, 0, '#3D7BF4', 36), bar('b30', 35, 25, 30, '#2FB36D', 36), bar('b45', -35, -25, 45, '#F7C531', 36), bar('b90', 35, -25, 90, '#EC5FA8', 36)];
  const PLAT = B('plat', 'box', [30, 30, 20], 25, 0, 0, '#9AA3B5');
  const RAMPA0 = [PLAT, B('rampa', 'wedge', [30, 30, 20], -40, 0, 0, '#F5893A')], RAMPA1 = [PLAT, B('rampa', 'wedge', [30, 30, 20], -5, 0, 0, '#F5893A', { r: [0, 0, 180] })];
  const CARRO = B('carro', 'box', [30, 30, 10], 0, 0, 8, '#E8453C');
  const roda = (id, x, y, c = '#2A2F3A', rot = true) => rot ? B(id, 'cyl', [16, 16, 6], x, y, 0, c, { r: [0, 90, 0], h: 16 }) : B(id, 'cyl', [16, 16, 6], x, y, 0, c);
  const CARRO0 = [CARRO, roda('w1', -40, 35, '#2A2F3A', false), roda('w2', 40, 35, '#2A2F3A', false)], CARRO1 = [CARRO, roda('w1', -18, 0), roda('w2', 18, 0)];
  const ESF = B('esfera', 'cyl', [60, 60, 4], 0, 0, 0, '#F3F3EE'), MIN = B('minuts', 'box', [4, 24, 2], 0, 12, 4, '#2A2F3A'), PUNT = B('eix', 'cyl', [6, 6, 3], 0, 0, 4, '#E8453C');
  const MARQ = [B('m12', 'box', [4, 6, 2], 0, 25, 4, '#3D7BF4'), B('m3', 'box', [6, 4, 2], 25, 0, 4, '#3D7BF4'), B('m6', 'box', [4, 6, 2], 0, -25, 4, '#3D7BF4'), B('m9', 'box', [6, 4, 2], -25, 0, 4, '#3D7BF4')];
  const RELL0 = [ESF, ...MARQ, MIN, PUNT, B('hores', 'box', [4, 16, 2], 50, 30, 0, '#E8453C')], RELL1 = [ESF, ...MARQ, MIN, PUNT, B('hores', 'box', [4, 16, 2], 8, 0, 4, '#E8453C', { r: [0, 0, 90] })];
  const CILS = [B('dret', 'cyl', [14, 14, 36], -30, 0, 0, '#3D7BF4'), B('x90', 'cyl', [14, 14, 36], 0, 0, 0, '#2FB36D', { r: [90, 0, 0], h: 14 }), B('y90', 'cyl', [14, 14, 36], 32, 0, 0, '#FF8A3D', { r: [0, 90, 0], h: 14 })];
  // ---- m3-3 · escalar ----
  const ARBRE = (x, k = 1, id = 'p') => [B(id + 't', 'cyl', [6 * k, 6 * k, 10 * k], x, 0, 0, '#A0683A'), B(id + 'c', 'cone', [16 * k, 16 * k, 16 * k], x, 0, 10 * k, '#2FB36D')];
  const NINOT_MAL = [B('n1', 'sph', [40, 40, 40], 0, 0, 0, '#F3F3EE'), B('n2', 'sph', [28, 28, 28], 0, 0, 20, '#F3F3EE'), B('nas', 'cone', [6, 6, 10], 0, -14, 31, '#F5893A', { r: [90, 0, 0], h: 6 })];
  const CASA = B('casa', 'box', [40, 30, 30], 0, 0, 0, '#F5893A'), TEU = B('teulada', 'pyr', [46, 36, 16], 0, 0, 30, '#E8453C');
  const PORTA0 = [CASA, TEU, B('porta', 'box', [24, 2, 30], 0, -15.5, 0, '#A0683A')], PORTA1 = [CASA, TEU, B('porta', 'box', [12, 2, 15], 0, -15.5, 0, '#A0683A')];
  // ---- m3-4 · el robot de peces (la fitxa tècnica) ----
  const RODES = [roda('r1', -16, 0), roda('r2', 16, 0)], COS = B('cos', 'box', [26, 18, 24], 0, 0, 4, '#7C5CFF');
  const brac = (id, x, rot = true) => rot ? B(id, 'box', [6, 6, 20], x, 0, 20, '#FF8A3D', { r: [0, 90, 0], h: 6 }) : B(id, 'box', [6, 6, 20], x, 0, 0, '#FF8A3D');
  const CAPR = B('cap', 'box', [20, 16, 14], 0, 0, 28, '#5BC0EB'), ULLS = [B('u1', 'sph', [6, 6, 6], -5, -8, 32, '#2A2F3A'), B('u2', 'sph', [6, 6, 6], 5, -8, 32, '#2A2F3A')];
  const ANT = [B('antena', 'cyl', [2, 2, 8], 0, 0, 42, '#9AA3B5'), B('bola', 'sph', [6, 6, 6], 0, 0, 50, '#E8453C')];
  const ROBOT = [...RODES, COS, brac('b1', -23), brac('b2', 23), CAPR, ...ULLS, ...ANT];
  const RB1 = [...RODES, COS], RB2 = [...RB1, CAPR, ...ULLS], RB3 = [...RB2, brac('b1', -23), brac('b2', 23)];
  const RODES_DRETES = [B('r1', 'cyl', [16, 16, 6], -16, 0, 0, '#2A2F3A'), B('r2', 'cyl', [16, 16, 6], 16, 0, 0, '#2A2F3A')];
  const CILS3 = [B('c1', 'cyl', [12, 12, 30], -30, 0, 0, '#3D7BF4'), B('c2', 'cyl', [12, 12, 30], 0, 0, 0, '#2FB36D', { r: [0, 90, 0], h: 12 }), B('c3', 'cyl', [12, 12, 30], 30, 0, 0, '#FF8A3D', { r: [90, 0, 0], h: 12 })];
  return {
  t: 'Moure, girar i escalar|Mover, girar y escalar', d: 'Mesures en mil·límetres|Medidas en milímetros', color: '#3D7BF4',
  s: [
    /* ---------- Sessió 1 · Moure amb precisió ---------- */
    { id: 'm3-1', t: 'Moure amb precisió|Mover con precisión', min: 45, badge: 'm31_prec',
      learn: ["Una peça es mou arrossegant-la amb el dit o escrivint la posició exacta, en mil·límetres, a la pestanya Posició.|Una pieza se mueve arrastrándola con el dedo o escribiendo la posición exacta, en milímetros, en la pestaña Posición.",
        "La quadrícula magnètica fa saltar la peça de 10, 5 o 1 mm: 10 mm per anar de pressa i 1 mm per afinar.|La cuadrícula magnética hace saltar la pieza de 10, 5 o 1 mm: 10 mm para ir deprisa y 1 mm para afinar.",
        "Moure és sumar o restar: una peça a x = 10 que es mou 25 mm a la dreta queda a x = 35.|Mover es sumar o restar: una pieza en x = 10 que se mueve 25 mm a la derecha queda en x = 35."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "Un cub de <b>20 mm</b> és a sobre d'un altre cub de 20 mm. A quina <b>z</b> comença el de dalt?|Un cubo de <b>20 mm</b> está encima de otro cubo de 20 mm. ¿En qué <b>z</b> empieza el de arriba?",
          opts: ['z = 20|z = 20', 'z = 10|z = 10', 'z = 40|z = 40'], a: 0,
          ex: "El de sota va de z = 0 a z = 20: el de dalt comença just on s'acaba, a z = 20.|El de debajo va de z = 0 a z = 20: el de arriba empieza justo donde acaba, en z = 20." },
        { k: 'm3look', ph: 'recorda', q: 'Mirem des de dalt. Quines són les coordenades <b>x</b> i <b>y</b> del cub?|Miramos desde arriba. ¿Cuáles son las coordenadas <b>x</b> e <b>y</b> del cubo?', model: { parts: [cub(30, -20, 0, 'q')] }, view: 'top', lock: true,
          opts: ['x = 30, y = −20|x = 30, y = −20', 'x = −20, y = 30|x = −20, y = 30', 'x = 30, y = 20|x = 30, y = 20'], a: 0,
          ex: "És 3 quadrets a la dreta de l'origen (x = 30) i 2 quadrets cap a davant, a baix de la imatge (y = −20).|Está 3 cuadritos a la derecha del origen (x = 30) y 2 cuadritos hacia delante, abajo en la imagen (y = −20)." },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'fab', title: "L'encàrrec de l'escola|El encargo de la escuela",
          t: "Ha arribat un encàrrec de l'<b>escola del barri</b>: per a la Setmana de la Robòtica volen un <b>robot de peces</b> a l'entrada, i ens han enviat una fitxa amb totes les mides en <b>mil·límetres</b>. La Nuvi imprimeix exactament el que dibuixem: si una peça queda 2 mm torta, el robot sortirà tort. Abans de construir-lo, avui aprendrem a <b>moure amb precisió</b>!|Ha llegado un encargo de la <b>escuela del barrio</b>: para la Semana de la Robótica quieren un <b>robot de piezas</b> en la entrada, y nos han enviado una ficha con todas las medidas en <b>milímetros</b>. Nuvi imprime exactamente lo que dibujamos: si una pieza queda 2 mm torcida, el robot saldrá torcido. Antes de construirlo, ¡hoy aprenderemos a <b>mover con precisión</b>!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Dues maneres|Dos maneras', t: 'Amb el dit o amb números|Con el dedo o con números', media: { k: 'model', model: { parts: [cub(-30, 10, 0, 'q', '#7C5CFF')] }, target: { parts: [cub(25, -15, 0, 'g')] } },
            x: "<b>Arrossegar</b> la peça amb el dit (o el ratolí) és ràpid: la portes a prop d'on vols. Per deixar-la <b>exacta</b>, toca-la i escriu els números a la pestanya <b>Posició</b>: x, y i z, en mil·límetres. Els bons dissenyadors fan les dues coses: primer arrosseguen i després afinen amb números.|<b>Arrastrar</b> la pieza con el dedo (o el ratón) es rápido: la llevas cerca de donde quieres. Para dejarla <b>exacta</b>, tócala y escribe los números en la pestaña <b>Posición</b>: x, y y z, en milímetros. Los buenos diseñadores hacen las dos cosas: primero arrastran y después afinan con números.",
            tip: 'El cub transparent és el <b>fantasma</b>: marca on ha d\'anar la peça.|El cubo transparente es el <b>fantasma</b>: marca dónde tiene que ir la pieza.' },
          { k: 'La quadrícula magnètica|La cuadrícula magnética', t: 'Salts de 10, 5 o 1 mm|Saltos de 10, 5 o 1 mm', anim: 'm31snap',
            x: "Quan arrossegues, la peça no es mou de qualsevol manera: <b>salta</b> de punt en punt de la quadrícula, com si fos un imant. El botó <b>⊞ mm</b> de sota la vista canvia el salt: <b>10 mm</b> per anar de pressa, <b>5 mm</b> per als punts del mig i <b>1 mm</b> per afinar. Si el fantasma és a 37 mm, només hi arribaràs amb el salt d'1 mm!|Cuando arrastras, la pieza no se mueve de cualquier manera: <b>salta</b> de punto en punto de la cuadrícula, como si fuera un imán. El botón <b>⊞ mm</b> de debajo de la vista cambia el salto: <b>10 mm</b> para ir deprisa, <b>5 mm</b> para los puntos del medio y <b>1 mm</b> para afinar. Si el fantasma está a 37 mm, ¡solo llegarás con el salto de 1 mm!",
            tip: 'Els botons − i + dels camps numèrics també fan servir aquest salt.|Los botones − y + de los campos numéricos también usan este salto.' },
          { k: 'Moure és sumar|Mover es sumar', t: 'De x = 10 a x = 35: +25 mm|De x = 10 a x = 35: +25 mm', anim: 'm31mou',
            x: "Moure una peça és <b>sumar o restar</b> a la seva posició. Si és a x = 10 i la vols <b>25 mm a la dreta</b>, fas 10 + 25 = <b>35</b>. Cap a l'esquerra, restes: 10 − 25 = <b>−15</b>. Amb la y passa el mateix (endavant i enrere) i amb la z (amunt i avall).|Mover una pieza es <b>sumar o restar</b> a su posición. Si está en x = 10 y la quieres <b>25 mm a la derecha</b>, haces 10 + 25 = <b>35</b>. Hacia la izquierda, restas: 10 − 25 = <b>−15</b>. Con la y pasa lo mismo (adelante y atrás) y con la z (arriba y abajo).",
            bad: 'Per moure-la 25 mm, escric 25 a la x.|Para moverla 25 mm, escribo 25 en la x.', good: 'Per moure-la 25 mm, sumo 25 a la x que ja tenia.|Para moverla 25 mm, sumo 25 a la x que ya tenía.' },
          { k: 'Per què tanta precisió?|¿Por qué tanta precisión?', t: 'La Nuvi fa exactament el que dibuixes|Nuvi hace exactamente lo que dibujas', media: { k: 'model', model: { parts: TAPA0 } },
            x: "Si la tapa d'una capsa queda <b>3 mm</b> desplaçada, sobresurt per un costat i no tanca bé. La impressora no ho arregla: fabrica el model tal com és. Per això, al taller, les peces importants es col·loquen <b>al mil·límetre</b>.|Si la tapa de una caja queda <b>3 mm</b> desplazada, sobresale por un lado y no cierra bien. La impresora no lo arregla: fabrica el modelo tal como es. Por eso, en el taller, las piezas importantes se colocan <b>al milímetro</b>.",
            tip: 'Gira la vista: la tapa sobresurt per la dreta i pel davant.|Gira la vista: la tapa sobresale por la derecha y por delante.' },
          { k: 'Amb el teclat|Con el teclado', t: 'Les fletxes mouen de mil·límetre en mil·límetre|Las flechas mueven de milímetro en milímetro', media: { k: 'model', model: { parts: PUNTS }, view: 'top' },
            x: "A l'ordinador, toca una peça i fes servir les <b>fletxes</b>: ← i → la mouen en <b>x</b>, ↑ i ↓ la mouen en <b>y</b>, i Re Pàg / Av Pàg, en <b>z</b>. Cada toc és <b>1 mm</b>; si mantens premuda la tecla de majúscules (⇧), són <b>10 mm</b>.|En el ordenador, toca una pieza y usa las <b>flechas</b>: ← y → la mueven en <b>x</b>, ↑ y ↓ la mueven en <b>y</b>, y Re Pág / Av Pág, en <b>z</b>. Cada toque es <b>1 mm</b>; si mantienes pulsada la tecla de mayúsculas (⇧), son <b>10 mm</b>.",
            tip: "Aquests cilindres són a mig quadret: el vermell és a x = 35, y = 15.|Estos cilindros están a medio cuadrito: el rojo está en x = 35, y = 15." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '📐', title: 'El dictat de moviments|El dictado de movimientos', t: 'Per parelles, amb la placa de paper (la fitxa), un regle i una goma d\'esborrar que fa de peça:|Por parejas, con la placa de papel (la ficha), una regla y una goma de borrar que hace de pieza:',
          steps: ["Poseu la goma a l'origen (0, 0), al centre de la placa.|Poned la goma en el origen (0, 0), en el centro de la placa.",
            "Una persona dicta tres moviments: «+30 en x», «−20 en y», «+15 en x». L'altra mou la goma amb el regle, sense dir res.|Una persona dicta tres movimientos: «+30 en x», «−20 en y», «+15 en x». La otra mueve la goma con la regla, sin decir nada.",
            'Abans de mesurar, calculeu on hauria de ser: sumeu i resteu els moviments de cada eix.|Antes de medir, calculad dónde debería estar: sumad y restad los movimientos de cada eje.',
            'Comproveu-ho amb el regle. Si coincideix, canvieu els papers!|Comprobadlo con la regla. Si coincide, ¡cambiad los papeles!'],
          tip: 'Recordeu: x positiva cap a la dreta i y positiva cap al fons. 30 + 15 = 45: la goma ha d\'acabar a (45, −20).|Recordad: x positiva hacia la derecha e y positiva hacia el fondo. 30 + 15 = 45: la goma tiene que acabar en (45, −20).' },
        { k: 'm3look', ph: 'prova', q: 'Toca el cilindre que és a <b>x = 35, y = 15</b>.|Toca el cilindro que está en <b>x = 35, y = 15</b>.', model: { parts: PUNTS }, view: 'top', pick: 'a',
          no: "Aquest no. Compta quadrets: x = 35 és 3 quadrets i mig a la dreta, i y = 15 és quadret i mig cap al fons.|Este no. Cuenta cuadritos: x = 35 es 3 cuadritos y medio a la derecha, e y = 15 es cuadrito y medio hacia el fondo.",
          ex: 'Cada quadret fa 10 mm: 35 mm són 3 quadrets i mig.|Cada cuadrito mide 10 mm: 35 mm son 3 cuadritos y medio.' },
        { k: 'm3look', ph: 'investiga', q: 'El cub és a <b>x = 10</b>. Si el mous <b>25 mm a l\'esquerra</b>, a quina x quedarà?|El cubo está en <b>x = 10</b>. Si lo mueves <b>25 mm a la izquierda</b>, ¿en qué x quedará?', model: { parts: [cub(10, 0, 0, 'q', '#2FB36D')] }, view: 'top', lock: true,
          opts: ['x = −15|x = −15', 'x = 35|x = 35', 'x = −25|x = −25'], a: 0,
          ex: "A l'esquerra es resta: 10 − 25 = −15. Passa per l'origen i queda 15 mm a l'altre costat.|A la izquierda se resta: 10 − 25 = −15. Pasa por el origen y queda 15 mm al otro lado." },
        { k: 'move', ph: 'pausa', title: 'Peça de precisió|Pieza de precisión', secs: 30, t: "Imagina que ets una peça a la placa: un salt gran a la dreta (<b>+10 mm</b>), un passet petit a l'esquerra (<b>−1 mm</b>), un salt cap endavant (<b>+10 en y</b>) i amunt (<b>+z</b>)! Ara al revés, cada cop més de pressa.|Imagina que eres una pieza en la placa: un salto grande a la derecha (<b>+10 mm</b>), un pasito pequeño a la izquierda (<b>−1 mm</b>), un salto hacia delante (<b>+10 en y</b>) ¡y arriba (<b>+z</b>)! Ahora al revés, cada vez más deprisa." },
        { k: 'm3build', ph: 'repte', q: 'Porta el cub al fantasma, a <b>x = 35, y = −15</b>. Amb el salt de 5 mm hi arribaràs arrossegant.|Lleva el cubo al fantasma, a <b>x = 35, y = −15</b>. Con el salto de 5 mm llegarás arrastrando.',
          start: { parts: [cub(0, 0)] }, palette: ['box'], snap: 5, target: { parts: [cub(35, -15)] },
          checks: [{ k: 'match', target: { parts: [cub(35, -15)] }, th: 0.95, t: 'El cub és dins del fantasma|El cubo está dentro del fantasma' }, { k: 'onplate' }],
          hint: 'Toca el cub i, a la pestanya Posició, escriu 35 a la x i −15 a la y.|Toca el cubo y, en la pestaña Posición, escribe 35 en la x y −15 en la y.', sol: { parts: [cub(35, -15)] } },
        { k: 'm3build', ph: 'repte', q: 'Mou cada peça <b>exactament 25 mm a la dreta</b>. Calcula la x nova de cada una (x + 25).|Mueve cada pieza <b>exactamente 25 mm a la derecha</b>. Calcula la x nueva de cada una (x + 25).',
          start: { parts: TRES0 }, palette: ['box', 'cyl', 'cone'], target: { parts: TRES1 },
          checks: [{ k: 'match', target: { parts: TRES1 }, th: 0.93, t: 'Les tres peces són als fantasmes|Las tres piezas están en los fantasmas' }, { k: 'part', t: 'cone', at: [30, -25, null], tol: 0.6, txt: 'El con és a x = 30|El cono está en x = 30' }, { k: 'onplate' }],
          hint: 'El cilindre és a x = −45: −45 + 25 = −20. La caixa: −20 + 25 = 5. El con: 5 + 25 = 30. La y no canvia.|El cilindro está en x = −45: −45 + 25 = −20. La caja: −20 + 25 = 5. El cono: 5 + 25 = 30. La y no cambia.', sol: { parts: TRES1 } },
        { k: 'm3build', ph: 'repte', q: 'Posa els ulls al robot: a <b>x = −8</b> i <b>x = 8</b>, a la cara del davant (<b>y = −10</b>) i amb la base a <b>z = 10</b>.|Pon los ojos al robot: en <b>x = −8</b> y <b>x = 8</b>, en la cara de delante (<b>y = −10</b>) y con la base en <b>z = 10</b>.',
          start: { parts: CARA0 }, palette: ['sph'], target: { parts: CARA1 },
          checks: [{ k: 'part', t: 'sph', at: [-8, -10, 13], tol: 0.6, txt: "L'ull esquerre és a (−8, −10, 10)|El ojo izquierdo está en (−8, −10, 10)" }, { k: 'part', t: 'sph', at: [8, -10, 13], tol: 0.6, txt: "L'ull dret és a (8, −10, 10)|El ojo derecho está en (8, −10, 10)" }, { k: 'one' }, { k: 'onplate' }],
          hint: "Toca un ull i, a Posició, escriu x = −8, y = −10 i z = 10. Després, l'altre amb x = 8.|Toca un ojo y, en Posición, escribe x = −8, y = −10 y z = 10. Después, el otro con x = 8.", sol: { parts: CARA1 },
          done: 'Ara el robot et mira! Els ulls sobresurten la meitat per davant de la cara.|¡Ahora el robot te mira! Los ojos sobresalen la mitad por delante de la cara.' },
        { k: 'm3fix', ph: 'repte', q: '<b>La tapa no tapa:</b> està desplaçada i sobresurt. Centra-la a sobre de la capsa.|<b>La tapa no tapa:</b> está desplazada y sobresale. Céntrala encima de la caja.',
          start: { parts: TAPA0 }, fix: ['tapa'], palette: ['box'],
          checks: [{ k: 'part', t: 'box', s: [42, 32, 4], at: [0, 0, null], tol: 0.5, txt: 'La tapa és centrada a (0, 0)|La tapa está centrada en (0, 0)' }, { k: 'size', ax: 'x', v: 42, tol: 0.5, t: 'Amplada total: 42 mm (no sobresurt)|Anchura total: 42 mm (no sobresale)' }, { k: 'size', ax: 'y', v: 32, tol: 0.5, t: 'Fondària total: 32 mm|Fondo total: 32 mm' }, { k: 'one' }],
          hint: 'La tapa és a x = 3, y = −2. Per centrar-la, posa x = 0 i y = 0 a Posició. La z no la toquis.|La tapa está en x = 3, y = −2. Para centrarla, pon x = 0 e y = 0 en Posición. La z no la toques.', sol: { parts: TAPA1 } },
        { k: 'm3build', ph: 'repte', extra: true, q: '<b>Torre de precisió:</b> apila els tres cilindres al centre. A quina z comença cada un?|<b>Torre de precisión:</b> apila los tres cilindros en el centro. ¿En qué z empieza cada uno?',
          start: { parts: TORRE0 }, palette: ['cyl'], target: { parts: TORRE1 },
          checks: [{ k: 'match', target: { parts: TORRE1 }, th: 0.93, t: 'La torre és com el fantasma|La torre es como el fantasma' }, { k: 'size', ax: 'z', v: 25, tol: 0.5, t: 'Alçada total: 25 mm|Altura total: 25 mm' }, { k: 'one' }, { k: 'onplate' }],
          hint: "Tots a x = 0, y = 0. El gran fa 12 mm: el mitjà comença a z = 12. El mitjà fa 8 mm: el petit comença a 12 + 8 = 20.|Todos en x = 0, y = 0. El grande mide 12 mm: el mediano empieza en z = 12. El mediano mide 8 mm: el pequeño empieza en 12 + 8 = 20.", sol: { parts: TORRE1 } },
        { k: 'm3free', ph: 'crea', q: "<b>La teva inicial.</b> Construeix la primera lletra del teu nom amb peces, col·locades amb números. Les peces s'han de tocar, sense espais.|<b>Tu inicial.</b> Construye la primera letra de tu nombre con piezas, colocadas con números. Las piezas se tienen que tocar, sin espacios.",
          name: 'La meva inicial|Mi inicial', palette: ['box', 'cyl', 'sph', 'wedge'],
          crit: ['La lletra té almenys 3 peces|La letra tiene al menos 3 piezas', 'Les peces es toquen: no hi ha espais ni trossos solts|Las piezas se tocan: no hay espacios ni trozos sueltos', 'Has fet servir la pestanya Posició per afinar|Has usado la pestaña Posición para afinar'],
          checks: [{ k: 'count', min: 3 }, { k: 'one' }, { k: 'onplate' }],
          sol: { parts: [B('a1', 'box', [10, 50, 8], -15, 0, 0, '#7C5CFF'), B('a2', 'box', [30, 10, 8], 0, 20, 0, '#7C5CFF'), B('a3', 'box', [24, 10, 8], -3, 0, 0, '#FF8A3D'), B('a4', 'box', [30, 10, 8], 0, -20, 0, '#7C5CFF')] } },
        { k: 'quiz', ph: 'tanca', q: 'Una peça és a <b>x = 15</b> i la mous <b>20 mm a l\'esquerra</b>. On queda?|Una pieza está en <b>x = 15</b> y la mueves <b>20 mm a la izquierda</b>. ¿Dónde queda?', opts: ['x = −5|x = −5', 'x = 35|x = 35', 'x = −20|x = −20'], a: 0,
          ex: "A l'esquerra es resta: 15 − 20 = −5.|A la izquierda se resta: 15 − 20 = −5." },
        { k: 'quiz', ph: 'tanca', q: 'Quin salt de la quadrícula fas servir per <b>afinar</b> fins al mil·límetre?|¿Qué salto de la cuadrícula usas para <b>afinar</b> hasta el milímetro?', opts: ['1 mm|1 mm', '10 mm|10 mm', '5 mm|5 mm'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* ---------- Sessió 2 · Girar ---------- */
    { id: 'm3-2', t: 'Girar|Girar', min: 45, badge: 'm32_gir',
      learn: ['Girar fa voltar una peça al voltant del seu centre; a la pestanya Gir, cada toc de + o − la gira 15°.|Girar hace dar vueltas a una pieza alrededor de su centro; en la pestaña Giro, cada toque de + o − la gira 15°.',
        "90° és un quart de volta, 180° mitja volta i 45° la meitat de 90°; un angle negatiu gira cap a l'altre costat.|90° es un cuarto de vuelta, 180° media vuelta y 45° la mitad de 90°; un ángulo negativo gira hacia el otro lado.",
        'Girar en z fa voltar la peça com una baldufa; girar en x o en y la tomba de costat, com un tronc ajagut.|Girar en z hace girar la pieza como una peonza; girar en x o en y la tumba de lado, como un tronco tumbado.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Una peça és a <b>x = 20</b> i la vols <b>35 mm a l\'esquerra</b>. Quina x hi escrius?|Una pieza está en <b>x = 20</b> y la quieres <b>35 mm a la izquierda</b>. ¿Qué x escribes?', opts: ['x = −15|x = −15', 'x = 55|x = 55', 'x = −35|x = −35'], a: 0,
          ex: "A l'esquerra es resta: 20 − 35 = −15.|A la izquierda se resta: 20 − 35 = −15." },
        { k: 'quiz', ph: 'recorda', q: "En un rellotge, quant gira l'agulla dels minuts en un <b>quart d'hora</b>?|En un reloj, ¿cuánto gira la aguja de los minutos en un <b>cuarto de hora</b>?", opts: ['Un quart de volta|Un cuarto de vuelta', 'Mitja volta|Media vuelta', 'Una volta sencera|Una vuelta entera'], a: 0,
          ex: "En 15 minuts va de les 12 a les 3: un quart de volta. Avui l'anomenarem <b>90°</b>.|En 15 minutos va de las 12 a las 3: un cuarto de vuelta. Hoy lo llamaremos <b>90°</b>." },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'fab', title: 'Braços i rodes|Brazos y ruedas',
          t: "La fitxa del robot diu: <b>braços estirats</b> i <b>rodes de costat</b>. Però totes les peces surten de la paleta dretes i rectes! La Nuvi diu que, així, el robot sembla un pal d'escombra. Avui aprendrem a <b>girar</b> peces: 15°, 45°, 90°… i a tombar-les de costat.|La ficha del robot dice: <b>brazos estirados</b> y <b>ruedas de lado</b>. ¡Pero todas las piezas salen de la paleta derechas y rectas! Nuvi dice que, así, el robot parece un palo de escoba. Hoy aprenderemos a <b>girar</b> piezas: 15°, 45°, 90°… y a tumbarlas de lado." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Girar|Girar', t: 'Una volta al voltant del centre|Una vuelta alrededor del centro', anim: 'm32gir',
            x: "Quan gires una peça, <b>volta al voltant del seu centre</b>, com una porta giratòria: les dues puntes es mouen alhora. A la pestanya <b>Gir</b>, cada toc de <b>+</b> o <b>−</b> la gira <b>15°</b>. També pots escriure l'angle directament: 45, 90…|Cuando giras una pieza, <b>da vueltas alrededor de su centro</b>, como una puerta giratoria: las dos puntas se mueven a la vez. En la pestaña <b>Giro</b>, cada toque de <b>+</b> o <b>−</b> la gira <b>15°</b>. También puedes escribir el ángulo directamente: 45, 90…",
            tip: 'Des de dalt (vista de planta), el gir en z es veu molt clar.|Desde arriba (vista de planta), el giro en z se ve muy claro.' },
          { k: 'Els angles|Los ángulos', t: '15°, 45°, 90° i 180°|15°, 45°, 90° y 180°', anim: 'm32ang',
            x: "Una volta sencera són <b>360°</b>. <b>90°</b> és un quart de volta (com la cantonada d'un full), <b>180°</b> és mitja volta i <b>45°</b> és la meitat de 90°. Amb tocs de 15°: 3 tocs fan 45° i 6 tocs fan 90°.|Una vuelta entera son <b>360°</b>. <b>90°</b> es un cuarto de vuelta (como la esquina de una hoja), <b>180°</b> es media vuelta y <b>45°</b> es la mitad de 90°. Con toques de 15°: 3 toques hacen 45° y 6 toques hacen 90°." },
          { k: 'Positiu o negatiu|Positivo o negativo', t: 'Cap a quin costat gira?|¿Hacia qué lado gira?', media: { k: 'model', model: { parts: [B('p', 'box', [44, 8, 8], -28, 0, 0, '#3D7BF4', { r: [0, 0, 30] }), B('n', 'box', [44, 8, 8], 28, 0, 0, '#FF8A3D', { r: [0, 0, -30] })] }, view: 'top' },
            x: "Mirant des de dalt, un angle <b>positiu</b> (+30°) gira la peça <b>al revés de les agulles del rellotge</b>, i un angle <b>negatiu</b> (−30°) la gira cap a l'altre costat. La barra blava està girada +30° i la taronja, −30°: són com un mirall l'una de l'altra.|Mirando desde arriba, un ángulo <b>positivo</b> (+30°) gira la pieza <b>al revés de las agujas del reloj</b>, y un ángulo <b>negativo</b> (−30°) la gira hacia el otro lado. La barra azul está girada +30° y la naranja, −30°: son como un espejo la una de la otra.",
            tip: "Si s'ha girat cap al costat que no volies, canvia el signe del número.|Si se ha girado hacia el lado que no querías, cambia el signo del número." },
          { k: 'Tombar|Tumbar', t: 'Girar en x i en y|Girar en x y en y', anim: 'm32eix',
            x: "Girar en <b style=\"color:#2F5BEA\">z</b> fa voltar la peça sense aixecar-la, com una baldufa. Girar en <b style=\"color:#E5484D\">x</b> o en <b style=\"color:#22A06B\">y</b> la <b>tomba</b>: una peça dreta passa a estar ajaguda. Amb 90° en y, queda estirada al llarg de l'eix x; amb 90° en x, al llarg de l'eix y.|Girar en <b style=\"color:#2F5BEA\">z</b> hace girar la pieza sin levantarla, como una peonza. Girar en <b style=\"color:#E5484D\">x</b> o en <b style=\"color:#22A06B\">y</b> la <b>tumba</b>: una pieza de pie pasa a estar tumbada. Con 90° en y, queda estirada a lo largo del eje x; con 90° en x, a lo largo del eje y.",
            tip: 'Quan la tombes, la peça continua tocant la placa: el taller manté la base a terra.|Cuando la tumbas, la pieza sigue tocando la placa: el taller mantiene la base en el suelo.' },
          { k: 'Compte!|¡Cuidado!', t: 'Formes que semblen no girar|Formas que parecen no girar', media: { k: 'model', model: { parts: CILS } },
            x: "Un <b>cilindre dret</b> o una esfera són iguals per tots els costats: si els gires en z, no notes cap canvi. Per tombar el cilindre cal girar-lo en <b>x</b> o en <b>y</b>: el blau és dret, el verd està girat 90° en x i el taronja, 90° en y.|Un <b>cilindro de pie</b> o una esfera son iguales por todos los lados: si los giras en z, no notas ningún cambio. Para tumbar el cilindro hay que girarlo en <b>x</b> o en <b>y</b>: el azul está de pie, el verde está girado 90° en x y el naranja, 90° en y.",
            bad: "He girat el cilindre 90° en z i no ha canviat: el gir no funciona.|He girado el cilindro 90° en z y no ha cambiado: el giro no funciona.", good: 'Un cilindre dret és igual per tots els costats: per tombar-lo, el giro en x o en y.|Un cilindro de pie es igual por todos los lados: para tumbarlo, lo giro en x o en y.' }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🕐', title: 'El rellotge de paper|El reloj de papel', t: "Amb el cercle d'angles de la fitxa, una tira de paper i la punta d'un llapis:|Con el círculo de ángulos de la ficha, una tira de papel y la punta de un lápiz:",
          steps: ['Posa la tira sobre la línia de 0° i clava-la pel mig amb la punta del llapis.|Pon la tira sobre la línea de 0° y clávala por el medio con la punta del lápiz.',
            'Gira-la 15°, després 45° i després 90°. On apunta cada vegada?|Gírala 15°, después 45° y después 90°. ¿Hacia dónde apunta cada vez?',
            "Ara gira-la −45°: cap a quin costat va?|Ahora gírala −45°: ¿hacia qué lado va?",
            "En parella: un diu un angle i l'altre el fa amb la tira. Canvieu cada 3 angles.|En pareja: uno dice un ángulo y el otro lo hace con la tira. Cambiad cada 3 ángulos."],
          tip: 'La tira gira pel mig, com les peces del taller: les dues puntes es mouen alhora.|La tira gira por el medio, como las piezas del taller: las dos puntas se mueven a la vez.' },
        { k: 'm3look', ph: 'prova', q: 'Toca la barra que està girada <b>45°</b>.|Toca la barra que está girada <b>45°</b>.', model: { parts: BARRES }, view: 'top', pick: 'b45',
          no: 'Aquesta no. 45° és la meitat d\'un quart de volta: la barra queda just en diagonal, entre la línia vermella i la verda.|Esta no. 45° es la mitad de un cuarto de vuelta: la barra queda justo en diagonal, entre la línea roja y la verde.',
          ex: "La blava no està girada (0°), la verda està a 30°, la groga a 45° (diagonal perfecta) i la rosa a 90°.|La azul no está girada (0°), la verde está a 30°, la amarilla a 45° (diagonal perfecta) y la rosa a 90°." },
        { k: 'm3look', ph: 'investiga', q: "Aquesta falca fa una rampa que <b>baixa cap a la dreta</b>. Quant l'has de girar en z perquè baixi cap a l'<b>esquerra</b>?|Esta cuña hace una rampa que <b>baja hacia la derecha</b>. ¿Cuánto tienes que girarla en z para que baje hacia la <b>izquierda</b>?",
          model: { parts: [B('f', 'wedge', [40, 24, 20], 0, 0, 0, '#F5893A')] }, opts: ['180°|180°', '90°|90°', '45°|45°'], a: 0,
          ex: "Amb mitja volta (180°), la part alta passa a l'altre costat. Amb 90°, la rampa baixaria cap al fons o cap a davant.|Con media vuelta (180°), la parte alta pasa al otro lado. Con 90°, la rampa bajaría hacia el fondo o hacia delante." },
        { k: 'move', ph: 'pausa', title: 'Gira com una peça|Gira como una pieza', secs: 30, t: "Posa't dret: gira <b>90°</b> (un quart de volta) a l'esquerra, 90° més i <b>180°</b> per tornar a mirar endavant. Ara fes-ho a salts de <b>45°</b>: quants salts calen per fer una volta sencera?|Ponte de pie: gira <b>90°</b> (un cuarto de vuelta) a la izquierda, 90° más y <b>180°</b> para volver a mirar adelante. Ahora hazlo a saltos de <b>45°</b>: ¿cuántos saltos hacen falta para dar una vuelta entera?" },
        { k: 'm3build', ph: 'repte', q: '<b>La creu.</b> Gira la barra lila <b>90°</b> i posa-la al centre, creuada amb la blava.|<b>La cruz.</b> Gira la barra lila <b>90°</b> y ponla en el centro, cruzada con la azul.',
          start: { parts: [bar('b1', 0, 0, 0, '#3D7BF4'), bar('b2', 0, 35, 0, '#7C5CFF')] }, palette: ['box'], target: { parts: [bar('g1', 0, 0, 0, '#3D7BF4'), bar('g2', 0, 0, 90, '#7C5CFF')] },
          checks: [{ k: 'match', target: { parts: [bar('g1', 0, 0, 0, '#3D7BF4'), bar('g2', 0, 0, 90, '#7C5CFF')] }, th: 0.92, t: 'La creu és com el fantasma|La cruz es como el fantasma' }, { k: 'one' }, { k: 'onplate' }],
          hint: 'Toca la barra lila. A Gir, posa 90 a la z (o fes 6 tocs de +). Després, a Posició, x = 0 i y = 0.|Toca la barra lila. En Giro, pon 90 en la z (o haz 6 toques de +). Después, en Posición, x = 0 e y = 0.', sol: { parts: [bar('b1', 0, 0, 0, '#3D7BF4'), bar('b2', 0, 0, 90, '#7C5CFF')] } },
        { k: 'm3build', ph: 'repte', q: '<b>Una X.</b> Ara les barres s\'han de creuar en diagonal: una a <b>45°</b> i l\'altra a <b>−45°</b>.|<b>Una X.</b> Ahora las barras se tienen que cruzar en diagonal: una a <b>45°</b> y la otra a <b>−45°</b>.',
          start: { parts: [bar('b1', 0, 25, 0, '#F7C531'), bar('b2', 0, -25, 0, '#EC5FA8')] }, palette: ['box'], target: { parts: [bar('g1', 0, 0, 45), bar('g2', 0, 0, -45)] },
          checks: [{ k: 'match', target: { parts: [bar('g1', 0, 0, 45), bar('g2', 0, 0, -45)] }, th: 0.9, t: 'La X és com el fantasma|La X es como el fantasma' }, { k: 'one' }, { k: 'onplate' }],
          hint: 'Una barra: z = 45 a Gir (3 tocs de +). L\'altra: z = −45 (3 tocs de −). Totes dues a x = 0, y = 0.|Una barra: z = 45 en Giro (3 toques de +). La otra: z = −45 (3 toques de −). Las dos en x = 0, y = 0.', sol: { parts: [bar('b1', 0, 0, 45, '#F7C531'), bar('b2', 0, 0, -45, '#EC5FA8')] } },
        { k: 'm3build', ph: 'repte', q: "<b>La rampa.</b> La rampa ha de <b>pujar</b> fins a la plataforma grisa. Gira la falca i enganxa-la a la plataforma.|<b>La rampa.</b> La rampa tiene que <b>subir</b> hasta la plataforma gris. Gira la cuña y pégala a la plataforma.",
          start: { parts: RAMPA0 }, palette: ['wedge'], target: { parts: RAMPA1 },
          checks: [{ k: 'match', target: { parts: RAMPA1 }, th: 0.92, t: 'La rampa és com el fantasma|La rampa es como el fantasma' }, { k: 'one' }, { k: 'onplate' }],
          hint: 'Gira la falca 180° en z (mitja volta): la part alta quedarà cap a la plataforma. Després, x = −5 i y = 0.|Gira la cuña 180° en z (media vuelta): la parte alta quedará hacia la plataforma. Después, x = −5 e y = 0.', sol: { parts: RAMPA1 } },
        { k: 'm3build', ph: 'repte', q: "<b>Les rodes.</b> Tomba els dos cilindres <b>90° en y</b> i posa'ls als costats del carro, a x = −18 i x = 18.|<b>Las ruedas.</b> Tumba los dos cilindros <b>90° en y</b> y ponlos a los lados del carro, en x = −18 y x = 18.",
          start: { parts: CARRO0 }, palette: ['cyl'], target: { parts: CARRO1 },
          checks: [{ k: 'part', t: 'cyl', s: [6, 16, 16], tol: 0.8, txt: 'Hi ha una roda tombada de costat|Hay una rueda tumbada de lado' }, { k: 'match', target: { parts: CARRO1 }, th: 0.92, t: 'El carro és com el fantasma|El carro es como el fantasma' }, { k: 'one' }, { k: 'onplate' }],
          hint: 'Toca un cilindre. A Gir, posa 90 a la y: queda ajagut. Després, a Posició, x = 18, y = 0 i z = 0. L\'altre, igual però a x = −18.|Toca un cilindro. En Giro, pon 90 en la y: queda tumbado. Después, en Posición, x = 18, y = 0 y z = 0. El otro, igual pero en x = −18.', sol: { parts: CARRO1 } },
        { k: 'm3build', ph: 'repte', extra: true, q: "<b>El rellotge de la plaça.</b> Gira l'agulla vermella perquè marqui <b>les 3</b> i posa-la a sobre de la cara del rellotge.|<b>El reloj de la plaza.</b> Gira la aguja roja para que marque <b>las 3</b> y ponla encima de la cara del reloj.",
          start: { parts: RELL0 }, palette: ['box'], view: 'top', target: { parts: RELL1 },
          checks: [{ k: 'part', t: 'box', s: [16, 4, 2], at: [8, 0, 5], tol: 0.6, txt: "L'agulla de les hores apunta a les 3|La aguja de las horas apunta a las 3" }, { k: 'match', target: { parts: RELL1 }, th: 0.97, t: 'El rellotge és com el fantasma|El reloj es como el fantasma' }, { k: 'one' }],
          hint: "Gira l'agulla 90° en z. Després, a Posició: x = 8, y = 0 i z = 4 (just a sobre de la cara).|Gira la aguja 90° en z. Después, en Posición: x = 8, y = 0 y z = 4 (justo encima de la cara).", sol: { parts: RELL1 } },
        { k: 'm3free', ph: 'crea', q: '<b>La rosa dels vents.</b> Fes una estrella amb almenys <b>3 barres</b> creuades al mateix centre, cada una girada un angle diferent (0°, 45°, 90°…).|<b>La rosa de los vientos.</b> Haz una estrella con al menos <b>3 barras</b> cruzadas en el mismo centro, cada una girada un ángulo distinto (0°, 45°, 90°…).',
          name: 'La meva rosa dels vents|Mi rosa de los vientos', palette: ['box', 'cyl', 'sph', 'cone', 'pyr', 'star'],
          crit: ['Almenys 3 barres que es creuen al mateix centre|Al menos 3 barras que se cruzan en el mismo centro', 'Cada barra té un gir diferent|Cada barra tiene un giro distinto', 'Tot és una sola peça i toca la placa|Todo es una sola pieza y toca la placa'],
          checks: [{ k: 'count', t: 'box', min: 3, txt: 'Almenys 3 barres (caixes)|Al menos 3 barras (cajas)' }, { k: 'one' }, { k: 'onplate' }],
          sol: { parts: [bar('a1', 0, 0, 0, '#E8453C', 70), bar('a2', 0, 0, 90, '#E8453C', 70), bar('a3', 0, 0, 45, '#3D7BF4', 46), bar('a4', 0, 0, -45, '#3D7BF4', 46), B('a5', 'cyl', [14, 14, 14], 0, 0, 0, '#F7C531')] } },
        { k: 'quiz', ph: 'tanca', q: 'Quants tocs de 15° calen per girar una peça <b>90°</b>?|¿Cuántos toques de 15° hacen falta para girar una pieza <b>90°</b>?', opts: ['6|6', '9|9', '4|4'], a: 0, ex: '6 × 15° = 90°.|6 × 15° = 90°.' },
        { k: 'quiz', ph: 'tanca', q: 'Vols posar un cilindre dret <b>ajagut</b>, com un tronc. Què fas?|Quieres poner un cilindro de pie <b>tumbado</b>, como un tronco. ¿Qué haces?', opts: ['El giro 90° en x o en y|Lo giro 90° en x o en y', 'El giro 90° en z|Lo giro 90° en z', "Li canvio l'alçada|Le cambio la altura"], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* ---------- Sessió 3 · Més gran, més petit ---------- */
    { id: 'm3-3', t: 'Més gran, més petit|Más grande, más pequeño', min: 45, badge: 'm33_esc',
      learn: ["Escalar és canviar les mides d'una peça: si en canvies una, s'estira; si les canvies totes alhora (Proporcional), creix sense deformar-se.|Escalar es cambiar las medidas de una pieza: si cambias una, se estira; si las cambias todas a la vez (Proporcional), crece sin deformarse.",
        'El doble (2:1) vol dir multiplicar cada mida per 2, i la meitat (1:2), dividir-la entre 2.|El doble (2:1) quiere decir multiplicar cada medida por 2, y la mitad (1:2), dividirla entre 2.',
        "Quan escales una figura de diverses peces, també es multipliquen les alçades i les distàncies on va cada peça.|Cuando escalas una figura de varias piezas, también se multiplican las alturas y las distancias donde va cada pieza."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Una barra està girada <b>45°</b>. Quants graus més l\'has de girar perquè quedi a <b>90°</b>?|Una barra está girada <b>45°</b>. ¿Cuántos grados más tienes que girarla para que quede a <b>90°</b>?', opts: ['45°|45°', '90°|90°', '135°|135°'], a: 0, ex: '45° + 45° = 90°.|45° + 45° = 90°.' },
        { k: 'quiz', ph: 'recorda', q: 'Quin és <b>el doble</b> de 15 mm? I <b>la meitat</b> de 40 mm?|¿Cuál es <b>el doble</b> de 15 mm? ¿Y <b>la mitad</b> de 40 mm?', opts: ['30 mm i 20 mm|30 mm y 20 mm', '17 mm i 38 mm|17 mm y 38 mm', '30 mm i 80 mm|30 mm y 80 mm'], a: 0,
          ex: 'El doble és multiplicar per 2 (15 × 2 = 30) i la meitat és dividir entre 2 (40 ÷ 2 = 20).|El doble es multiplicar por 2 (15 × 2 = 30) y la mitad es dividir entre 2 (40 ÷ 2 = 20).' },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'fab', title: 'Al doble i a la meitat|Al doble y a la mitad',
          t: "L'escola ha vist el primer esbós del robot i li agrada molt! Però ara demanen dues coses: un robot <b>el doble de gran</b> per a l'entrada i robotets de <b>la meitat</b> per a cada classe. La Nuvi avisa: «Si m'envieu les peces deformades, us faré robots aixafats!» Avui aprendrem a <b>escalar</b> sense deformar.|¡La escuela ha visto el primer boceto del robot y le gusta mucho! Pero ahora piden dos cosas: un robot <b>el doble de grande</b> para la entrada y robotitos de <b>la mitad</b> para cada clase. Nuvi avisa: «¡Si me enviáis las piezas deformadas, os haré robots aplastados!» Hoy aprenderemos a <b>escalar</b> sin deformar." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Una sola mida|Una sola medida', t: 'Estirar una peça|Estirar una pieza', media: { k: 'model', model: { parts: [B('a', 'box', [20, 20, 20], -40, 0, 0, '#7C5CFF'), B('b', 'box', [50, 20, 20], 0, 0, 0, '#3D7BF4'), B('c', 'box', [20, 20, 40], 40, 0, 0, '#2FB36D')] } },
            x: "A la pestanya <b>Mida</b> hi ha tres números: l'amplada (<b style=\"color:#E5484D\">x</b>), la fondària (<b style=\"color:#22A06B\">y</b>) i l'alçada (<b style=\"color:#2F5BEA\">z</b>). Si en canvies <b>només una</b>, la peça s'estira en aquella direcció: el cub lila de 20 mm amb x = 50 es converteix en la barra blava, i amb z = 40, en la torre verda.|En la pestaña <b>Medida</b> hay tres números: la anchura (<b style=\"color:#E5484D\">x</b>), el fondo (<b style=\"color:#22A06B\">y</b>) y la altura (<b style=\"color:#2F5BEA\">z</b>). Si cambias <b>solo una</b>, la pieza se estira en esa dirección: el cubo lila de 20 mm con x = 50 se convierte en la barra azul, y con z = 40, en la torre verde.",
            tip: "Quan canvies l'alçada, la base no es mou: la peça creix cap amunt.|Cuando cambias la altura, la base no se mueve: la pieza crece hacia arriba." },
          { k: 'Proporcional|Proporcional', t: 'El cadenat: totes les mides alhora|El candado: todas las medidas a la vez', anim: 'm33esc',
            x: "Si actives <b>Proporcional</b> (el cadenat), quan canvies una mida <b>les altres canvien igual</b>. La peça es fa més gran o més petita però <b>no es deforma</b>: un cub continua sent un cub, i una esfera, una esfera.|Si activas <b>Proporcional</b> (el candado), cuando cambias una medida <b>las otras cambian igual</b>. La pieza se hace más grande o más pequeña pero <b>no se deforma</b>: un cubo sigue siendo un cubo, y una esfera, una esfera.",
            bad: "Per fer el cub el doble, només li canvio l'alçada a 40.|Para hacer el cubo el doble, solo le cambio la altura a 40.", good: 'Per fer-lo el doble, multiplico per 2 totes les mides: 40 × 40 × 40.|Para hacerlo el doble, multiplico por 2 todas las medidas: 40 × 40 × 40.' },
          { k: 'Doble i meitat|Doble y mitad', t: '2:1 i 1:2|2:1 y 1:2', media: { k: 'model', model: { parts: [B('a', 'box', [10, 10, 10], -35, 0, 0, '#F7C531'), B('b', 'box', [20, 20, 20], -10, 0, 0, '#FF8A3D'), B('c', 'box', [40, 40, 40], 30, 0, 0, '#E8453C')] } },
            x: "<b>El doble</b> s'escriu <b>2:1</b>: cada mida es multiplica per 2 (20 mm → 40 mm). <b>La meitat</b> s'escriu <b>1:2</b>: cada mida es divideix entre 2 (20 mm → 10 mm). Aquí tens el cub taronja de 20 mm, la seva meitat (groc) i el seu doble (vermell).|<b>El doble</b> se escribe <b>2:1</b>: cada medida se multiplica por 2 (20 mm → 40 mm). <b>La mitad</b> se escribe <b>1:2</b>: cada medida se divide entre 2 (20 mm → 10 mm). Aquí tienes el cubo naranja de 20 mm, su mitad (amarillo) y su doble (rojo).",
            tip: "Les maquetes de trens o d'edificis també tenen escala: 1:100 vol dir que tot és 100 vegades més petit que de veritat.|Las maquetas de trenes o de edificios también tienen escala: 1:100 quiere decir que todo es 100 veces más pequeño que de verdad." },
          { k: '⭐ Saber més|⭐ Saber más', t: 'El doble ocupa 8 vegades més|El doble ocupa 8 veces más', anim: 'm33dob',
            x: "<b>Només si tens curiositat:</b> si fas un cub el doble d'ample, de fons i d'alt, a dins hi caben <b>8 cubs petits</b> (2 × 2 × 2). Per això una peça al doble gasta 8 vegades més plàstic i la Nuvi tarda molt més a imprimir-la!|<b>Solo si tienes curiosidad:</b> si haces un cubo el doble de ancho, de fondo y de alto, dentro caben <b>8 cubos pequeños</b> (2 × 2 × 2). ¡Por eso una pieza al doble gasta 8 veces más plástico y Nuvi tarda mucho más en imprimirla!" },
          { k: 'Figures de diverses peces|Figuras de varias piezas', t: 'També es dobla on comença cada peça|También se dobla dónde empieza cada pieza', media: { k: 'model', model: { parts: [...ARBRE(-30, 1, 'p'), ...ARBRE(15, 2, 'g')] } },
            x: "Un arbre té un tronc i una copa. Per fer-lo al <b>doble</b>, dobles les mides de cada peça… i també <b>l'alçada on comença la copa</b>: abans començava a z = 10 i ara comença a z = 20. Si no, la copa quedaria enfonsada dins del tronc.|Un árbol tiene un tronco y una copa. Para hacerlo al <b>doble</b>, doblas las medidas de cada pieza… y también <b>la altura donde empieza la copa</b>: antes empezaba en z = 10 y ahora empieza en z = 20. Si no, la copa quedaría hundida dentro del tronco.",
            tip: 'Gira la vista i compara-les: tenen exactament la mateixa forma.|Gira la vista y compáralos: tienen exactamente la misma forma.' }
        ] },
        { k: 'unplug', ph: 'mans', ico: '✏️', title: 'Dibuixa al doble|Dibuja al doble', t: 'Amb la fitxa de les dues quadrícules i un llapis:|Con la ficha de las dos cuadrículas y un lápiz:',
          steps: ['A la quadrícula petita hi ha un robot dibuixat. Compta quants quadrets fa cada part.|En la cuadrícula pequeña hay un robot dibujado. Cuenta cuántos cuadritos mide cada parte.',
            'A la quadrícula gran, dibuixa\'l al doble: cada quadret es converteix en 2 quadrets.|En la cuadrícula grande, dibújalo al doble: cada cuadrito se convierte en 2 cuadritos.',
            'Compara: té la mateixa forma? A quin quadret comença el cap, ara?|Compara: ¿tiene la misma forma? ¿En qué cuadrito empieza la cabeza, ahora?',
            'Repte: dibuixa\'l a la meitat (cada 2 quadrets, 1).|Reto: dibújalo a la mitad (cada 2 cuadritos, 1).'],
          tip: "Si una part et queda més ampla o més estreta del compte, el robot es deforma: compta-ho bé abans de dibuixar.|Si una parte te queda más ancha o más estrecha de la cuenta, el robot se deforma: cuéntalo bien antes de dibujar." },
        { k: 'm3look', ph: 'prova', q: 'Toca la caixa que és <b>el doble</b> de la groga en <b>totes</b> les mides.|Toca la caja que es <b>el doble</b> de la amarilla en <b>todas</b> las medidas.',
          model: { parts: [B('petita', 'box', [20, 10, 10], -45, 0, 0, '#F7C531'), B('x2', 'box', [40, 10, 10], -10, 25, 0, '#3D7BF4'), B('doble', 'box', [40, 20, 20], 30, 0, 0, '#2FB36D'), B('mig', 'box', [30, 15, 15], -5, -25, 0, '#EC5FA8')] }, pick: 'doble',
          no: "Aquesta no. Mira-la de costat: el doble ha de ser 2 vegades més ample, 2 vegades més fondo i 2 vegades més alt.|Esta no. Mírala de lado: el doble tiene que ser 2 veces más ancho, 2 veces más hondo y 2 veces más alto.",
          ex: "La groga fa 20 × 10 × 10 mm; la verda, 40 × 20 × 20 mm: totes les mides × 2. La blava només s'ha estirat en x.|La amarilla mide 20 × 10 × 10 mm; la verde, 40 × 20 × 20 mm: todas las medidas × 2. La azul solo se ha estirado en x." },
        { k: 'm3look', ph: 'investiga', q: "Aquest ninot de neu s'ha fet al doble, però alguna cosa no va bé. Què ha passat?|Este muñeco de nieve se ha hecho al doble, pero algo no va bien. ¿Qué ha pasado?", model: { parts: NINOT_MAL }, view: 'front',
          opts: ["El cap està enfonsat: no s'ha doblat l'alçada on comença|La cabeza está hundida: no se ha doblado la altura donde empieza", 'El cap és massa petit|La cabeza es demasiado pequeña', 'El cos no toca la placa|El cuerpo no toca la placa'], a: 0,
          ex: "El cos ara fa 40 mm, però el cap continua començant a z = 20, com al ninot petit. Al doble, hauria de començar a z = 40.|El cuerpo ahora mide 40 mm, pero la cabeza sigue empezando en z = 20, como en el muñeco pequeño. Al doble, tendría que empezar en z = 40." },
        { k: 'move', ph: 'pausa', title: 'Gegant i formiga|Gigante y hormiga', secs: 30, t: "Fes-te <b>el doble</b> de gran: estira't amunt i obre els braços! Ara <b>la meitat</b>: ajup-te ben petit. Alterna: gegant, formiga, gegant… cada cop més de pressa.|Hazte <b>el doble</b> de grande: ¡estírate hacia arriba y abre los brazos! Ahora <b>la mitad</b>: agáchate muy pequeño. Alterna: gigante, hormiga, gigante… cada vez más deprisa." },
        { k: 'm3build', ph: 'repte', q: '<b>El tauler de la taula.</b> Estira el cub perquè faci <b>60 mm</b> d\'amplada, 20 de fondària i <b>6 d\'alçada</b>.|<b>El tablero de la mesa.</b> Estira el cubo para que mida <b>60 mm</b> de anchura, 20 de fondo y <b>6 de altura</b>.',
          start: { parts: [cub(0, 0, 0, 'a1', '#A0683A')] }, palette: ['box'], target: { parts: [B('g', 'box', [60, 20, 6], 0, 0, 0, '#A0683A')] },
          checks: [{ k: 'part', t: 'box', s: [60, 20, 6], tol: 0.5, txt: 'La peça fa 60 × 20 × 6 mm|La pieza mide 60 × 20 × 6 mm' }, { k: 'match', target: { parts: [B('g', 'box', [60, 20, 6], 0, 0, 0, '#A0683A')] }, th: 0.92, t: 'És al lloc del fantasma|Está en el lugar del fantasma' }, { k: 'onplate' }],
          hint: 'Sense el cadenat: a Mida, escriu 60 a la x i 6 a la z. La y ja fa 20.|Sin el candado: en Medida, escribe 60 en la x y 6 en la z. La y ya mide 20.', sol: { parts: [B('a1', 'box', [60, 20, 6], 0, 0, 0, '#A0683A')] } },
        { k: 'm3build', ph: 'repte', q: '<b>El cub gegant.</b> Fes el cub <b>el doble de gran</b> sense deformar-lo.|<b>El cubo gigante.</b> Haz el cubo <b>el doble de grande</b> sin deformarlo.',
          start: { parts: [cub(0, 0, 0, 'a1', '#E8453C')] }, palette: ['box'], target: { parts: [cub(0, 0, 0, 'g', '#E8453C', 40)] },
          checks: [{ k: 'part', t: 'box', s: [40, 40, 40], tol: 0.5, txt: 'El cub fa 40 × 40 × 40 mm|El cubo mide 40 × 40 × 40 mm' }, { k: 'match', target: { parts: [cub(0, 0, 0, 'g', '#E8453C', 40)] }, th: 0.95, t: 'És al lloc del fantasma|Está en el lugar del fantasma' }, { k: 'onplate' }],
          hint: 'Activa Proporcional (el cadenat) i escriu 40 a qualsevol mida: totes canviaran alhora.|Activa Proporcional (el candado) y escribe 40 en cualquier medida: todas cambiarán a la vez.', sol: { parts: [cub(0, 0, 0, 'a1', '#E8453C', 40)] } },
        { k: 'm3build', ph: 'repte', q: '<b>La bola a la meitat.</b> Fes la bola <b>la meitat</b> de gran i posa-la a dalt de la columna.|<b>La bola a la mitad.</b> Haz la bola <b>la mitad</b> de grande y ponla arriba de la columna.',
          start: { parts: [B('col', 'cyl', [16, 16, 30], 20, 0, 0, '#9AA3B5'), B('a1', 'sph', [40, 40, 40], -35, 0, 0, '#2FB36D')] }, palette: ['sph'],
          target: { parts: [B('col', 'cyl', [16, 16, 30], 20, 0, 0, '#9AA3B5'), B('g', 'sph', [20, 20, 20], 20, 0, 30, '#2FB36D')] },
          checks: [{ k: 'part', t: 'sph', s: [20, 20, 20], tol: 0.5, txt: 'La bola fa 20 mm (la meitat de 40)|La bola mide 20 mm (la mitad de 40)' }, { k: 'match', target: { parts: [B('col', 'cyl', [16, 16, 30], 20, 0, 0, '#9AA3B5'), B('g', 'sph', [20, 20, 20], 20, 0, 30, '#2FB36D')] }, th: 0.92, t: 'La bola és a dalt de la columna|La bola está arriba de la columna' }, { k: 'one' }],
          hint: 'Amb Proporcional, escriu 20 a la mida. Després, a Posició: x = 20, y = 0 i z = 30, on s\'acaba la columna.|Con Proporcional, escribe 20 en la medida. Después, en Posición: x = 20, y = 0 y z = 30, donde acaba la columna.',
          sol: { parts: [B('col', 'cyl', [16, 16, 30], 20, 0, 0, '#9AA3B5'), B('a1', 'sph', [20, 20, 20], 20, 0, 30, '#2FB36D')] } },
        { k: 'm3build', ph: 'repte', q: "<b>L'arbre al doble.</b> Al fantasma de la dreta, fes l'arbre petit a escala <b>2:1</b>. Compte amb on comença la copa!|<b>El árbol al doble.</b> En el fantasma de la derecha, haz el árbol pequeño a escala <b>2:1</b>. ¡Cuidado con dónde empieza la copa!",
          start: { parts: ARBRE(-35, 1, 'p') }, palette: ['cyl', 'cone'], target: { parts: [...ARBRE(-35, 1, 'p'), ...ARBRE(20, 2, 'g')] },
          checks: [{ k: 'part', t: 'cyl', s: [12, 12, 20], at: [20, 0, 10], tol: 0.6, txt: 'Tronc de 12 × 12 × 20 mm a x = 20|Tronco de 12 × 12 × 20 mm en x = 20' }, { k: 'part', t: 'cone', s: [32, 32, 32], at: [20, 0, 36], tol: 0.6, txt: 'Copa de 32 mm que comença a z = 20|Copa de 32 mm que empieza en z = 20' }, { k: 'match', target: { parts: [...ARBRE(-35, 1, 'p'), ...ARBRE(20, 2, 'g')] }, th: 0.9, t: 'Els dos arbres són com els fantasmes|Los dos árboles son como los fantasmas' }, { k: 'onplate' }],
          hint: 'Tronc: 6 × 6 × 10 → 12 × 12 × 20, a x = 20. Copa: 16 → 32 en totes les mides, a x = 20 i amb la base a z = 20 (on s\'acaba el tronc).|Tronco: 6 × 6 × 10 → 12 × 12 × 20, en x = 20. Copa: 16 → 32 en todas las medidas, en x = 20 y con la base en z = 20 (donde acaba el tronco).',
          sol: { parts: [...ARBRE(-35, 1, 'p'), ...ARBRE(20, 2, 'g')] } },
        { k: 'm3fix', ph: 'repte', extra: true, q: "<b>La porta gegant.</b> La porta ha de fer <b>la meitat</b> d'alt que la casa (15 mm) i 12 mm d'ample. Arregla-la!|<b>La puerta gigante.</b> La puerta tiene que medir <b>la mitad</b> de alto que la casa (15 mm) y 12 mm de ancho. ¡Arréglala!",
          start: { parts: PORTA0 }, fix: ['porta'], palette: ['box'],
          checks: [{ k: 'part', t: 'box', s: [12, 2, 15], tol: 0.5, txt: 'La porta fa 12 × 2 × 15 mm|La puerta mide 12 × 2 × 15 mm' }, { k: 'match', target: { parts: PORTA1 }, th: 0.95, t: 'La porta és a terra, al mig de la façana|La puerta está en el suelo, en el medio de la fachada' }, { k: 'one' }],
          hint: 'Sense el cadenat: a Mida, x = 12 i z = 15. La base no es mou, així que continuarà tocant a terra.|Sin el candado: en Medida, x = 12 y z = 15. La base no se mueve, así que seguirá tocando el suelo.', sol: { parts: PORTA1 } },
        { k: 'm3free', ph: 'crea', q: "<b>Robot i robot gegant.</b> Fes un robot senzill (cos i cap, com a mínim) i, al costat, el mateix robot <b>al doble</b>: totes les mides i alçades × 2.|<b>Robot y robot gigante.</b> Haz un robot sencillo (cuerpo y cabeza, como mínimo) y, al lado, el mismo robot <b>al doble</b>: todas las medidas y alturas × 2.",
          name: 'Robot i robot gegant|Robot y robot gigante', palette: ['box', 'cyl', 'sph', 'cone', 'pyr'],
          crit: ['Un robot petit amb almenys cos i cap|Un robot pequeño con al menos cuerpo y cabeza', 'Al costat, el mateix robot al doble (mides i alçades × 2)|Al lado, el mismo robot al doble (medidas y alturas × 2)', 'Tots dos toquen la placa i no tenen peces soltes|Los dos tocan la placa y no tienen piezas sueltas'],
          checks: [{ k: 'count', min: 4 }, { k: 'onplate' }],
          sol: { parts: [B('a1', 'box', [16, 10, 16], -30, 0, 0, '#7C5CFF'), B('a2', 'box', [12, 10, 10], -30, 0, 16, '#5BC0EB'), B('a3', 'box', [32, 20, 32], 20, 0, 0, '#7C5CFF'), B('a4', 'box', [24, 20, 20], 20, 0, 32, '#5BC0EB')] } },
        { k: 'quiz', ph: 'tanca', q: 'Una caixa fa <b>10 × 20 × 30 mm</b>. Com és <b>al doble</b>?|Una caja mide <b>10 × 20 × 30 mm</b>. ¿Cómo es <b>al doble</b>?', opts: ['20 × 40 × 60 mm|20 × 40 × 60 mm', '20 × 20 × 30 mm|20 × 20 × 30 mm', '12 × 22 × 32 mm|12 × 22 × 32 mm'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Per a què serveix el botó <b>Proporcional</b>?|¿Para qué sirve el botón <b>Proporcional</b>?', opts: ['Perquè totes les mides canviïn alhora i la peça no es deformi|Para que todas las medidas cambien a la vez y la pieza no se deforme', 'Per girar la peça|Para girar la pieza', 'Per portar-la al centre|Para llevarla al centro'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* ---------- Sessió 4 · Projecte: el robot de peces ---------- */
    { id: 'm3-4', t: 'Projecte: el robot de peces|Proyecto: el robot de piezas', min: 45, proj: true, badge: 'm34_rob',
      learn: ['Una fitxa tècnica diu les mides, la posició i el gir de cada peça: seguir-la fa que el model surti com s\'havia pensat.|Una ficha técnica dice las medidas, la posición y el giro de cada pieza: seguirla hace que el modelo salga como se había pensado.',
        "Un model gran es construeix per parts i de baix a dalt: cada peça comença on s'acaba la de sota.|Un modelo grande se construye por partes y de abajo arriba: cada pieza empieza donde acaba la de debajo.",
        'Moure, girar i escalar es combinen: les rodes i els braços es tomben 90° i el cap es fa a la mida justa.|Mover, girar y escalar se combinan: las ruedas y los brazos se tumban 90° y la cabeza se hace a la medida justa.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Fas un cub de 20 mm <b>al doble</b> amb Proporcional. Quines mides té ara?|Haces un cubo de 20 mm <b>al doble</b> con Proporcional. ¿Qué medidas tiene ahora?', opts: ['40 × 40 × 40 mm|40 × 40 × 40 mm', '40 × 20 × 20 mm|40 × 20 × 20 mm', '22 × 22 × 22 mm|22 × 22 × 22 mm'], a: 0 },
        { k: 'm3look', ph: 'recorda', q: 'Toca el cilindre girat <b>90° en y</b>. Pista: queda ajagut al llarg de la línia vermella (l\'eix x).|Toca el cilindro girado <b>90° en y</b>. Pista: queda tumbado a lo largo de la línea roja (el eje x).', model: { parts: CILS3 }, pick: 'c2',
          no: 'Aquest no. El girat en y queda estirat d\'esquerra a dreta, com la línia vermella.|Este no. El girado en y queda estirado de izquierda a derecha, como la línea roja.', ex: 'El blau és dret, el verd està girat 90° en y (al llarg de x) i el taronja, 90° en x (al llarg de y).|El azul está de pie, el verde está girado 90° en y (a lo largo de x) y el naranja, 90° en x (a lo largo de y).' },
        { k: 'story', ph: 'missio', who: 'both', scene: 'fab', title: 'La fitxa del robot|La ficha del robot',
          t: "Avui és el gran dia! A la taula del taller hi ha la <b>fitxa tècnica</b> del robot que ens ha encarregat l'escola: quines peces té, quines mides fan i on va cada una. La Nuvi ja s'ha escalfat i espera el model. Farem servir tot el que hem après: <b>moure, girar i escalar</b>. Som-hi!|¡Hoy es el gran día! En la mesa del taller está la <b>ficha técnica</b> del robot que nos ha encargado la escuela: qué piezas tiene, qué medidas tienen y dónde va cada una. Nuvi ya se ha calentado y espera el modelo. Usaremos todo lo que hemos aprendido: <b>mover, girar y escalar</b>. ¡Vamos!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'La fitxa tècnica|La ficha técnica', t: 'Mides, posició i gir de cada peça|Medidas, posición y giro de cada pieza', anim: 'm34fit',
            x: "Una <b>fitxa tècnica</b> és com una recepta: diu quines peces hi ha, quines <b>mides</b> fan (en mm), on van (<b>posició</b>, amb la z de la base) i si estan <b>girades</b>. Els enginyers la fan servir perquè qualsevol persona pugui construir exactament el mateix objecte.|Una <b>ficha técnica</b> es como una receta: dice qué piezas hay, qué <b>medidas</b> tienen (en mm), dónde van (<b>posición</b>, con la z de la base) y si están <b>giradas</b>. Los ingenieros la usan para que cualquier persona pueda construir exactamente el mismo objeto." },
          { k: 'El robot|El robot', t: 'El robot de l\'escola, peça a peça|El robot de la escuela, pieza a pieza', media: { k: 'model', model: { parts: ROBOT } },
            x: "Aquest és el robot que farem: dues <b>rodes</b> tombades, un <b>cos</b>, dos <b>braços</b> estirats, un <b>cap</b> amb dos ulls i una <b>antena</b> amb una bola. En total, 10 peces. Gira'l per veure'l de tots els costats.|Este es el robot que haremos: dos <b>ruedas</b> tumbadas, un <b>cuerpo</b>, dos <b>brazos</b> estirados, una <b>cabeza</b> con dos ojos y una <b>antena</b> con una bola. En total, 10 piezas. Gíralo para verlo desde todos los lados.",
            tip: 'Les rodes i els braços són peces dretes girades 90° en y.|Las ruedas y los brazos son piezas de pie giradas 90° en y.' },
          { k: 'Pla de treball|Plan de trabajo', t: 'Per parts i de baix a dalt|Por partes y de abajo arriba', anim: 'm34pla',
            x: "Un model gran es fa <b>per parts</b> i <b>de baix a dalt</b>: primer les rodes (toquen la placa), després el cos, el cap a sobre, els braços als costats i, al final, els detalls. Així sempre saps a quina alçada va la peça següent.|Un modelo grande se hace <b>por partes</b> y <b>de abajo arriba</b>: primero las ruedas (tocan la placa), después el cuerpo, la cabeza encima, los brazos a los lados y, al final, los detalles. Así siempre sabes a qué altura va la pieza siguiente." },
          { k: 'Les alçades|Las alturas', t: "Cada peça comença on s'acaba la de sota|Cada pieza empieza donde acaba la de debajo", media: { k: 'model', model: { parts: ROBOT }, view: 'front' },
            x: "El cos comença a <b>z = 4</b> (queda 4 mm per sobre del terra, entre les rodes) i fa 24 mm d'alt: s'acaba a 4 + 24 = <b>28</b>. Per tant, el cap comença a <b>z = 28</b>, fa 14 mm i s'acaba a 42, on comença l'antena. <b>Sumar alçades</b> és la clau perquè res floti ni s'enfonsi.|El cuerpo empieza en <b>z = 4</b> (queda 4 mm por encima del suelo, entre las ruedas) y mide 24 mm de alto: acaba en 4 + 24 = <b>28</b>. Por tanto, la cabeza empieza en <b>z = 28</b>, mide 14 mm y acaba en 42, donde empieza la antena. <b>Sumar alturas</b> es la clave para que nada flote ni se hunda." },
          { k: 'Revisa|Revisa', t: 'Comprova cada part abans de seguir|Comprueba cada parte antes de seguir', media: { k: 'model', model: { parts: ROBOT }, view: 'right' },
            x: "Quan acabis una part, compara-la amb la fitxa: mides, posició i gir. Les <b>comprovacions</b> de sota la vista es posen en verd quan una part està bé. Mira el robot des de davant i des del costat: si alguna peça flota o s'enfonsa, es veu de seguida.|Cuando acabes una parte, compárala con la ficha: medidas, posición y giro. Las <b>comprobaciones</b> de debajo de la vista se ponen en verde cuando una parte está bien. Mira el robot desde delante y desde el lado: si alguna pieza flota o se hunde, se ve enseguida.",
            bad: 'Faig totes les peces de cop i al final miro si encaixen.|Hago todas las piezas de golpe y al final miro si encajan.', good: 'Faig una part, la comprovo i després passo a la següent.|Hago una parte, la compruebo y después paso a la siguiente.' }
        ] },
        { k: 'unplug', ph: 'mans', ico: '📝', title: 'Llegeix la fitxa|Lee la ficha', t: 'Amb la fitxa tècnica del robot (imprimible) i un llapis:|Con la ficha técnica del robot (imprimible) y un lápiz:',
          steps: ['Llegeix la taula de peces i encercla les que estan girades.|Lee la tabla de piezas y rodea las que están giradas.',
            'Calcula on comença cada peça (z): suma les alçades de baix a dalt i escriu-ho a la columna buida.|Calcula dónde empieza cada pieza (z): suma las alturas de abajo arriba y escríbelo en la columna vacía.',
            'Dibuixa el robot vist de davant a la quadrícula, amb les mides.|Dibuja el robot visto de delante en la cuadrícula, con las medidas.',
            'Compara amb el company: us surten les mateixes alçades?|Compara con el compañero: ¿os salen las mismas alturas?'],
          tip: "Si una alçada no us quadra, mireu quina peça hi ha a sota i on s'acaba.|Si una altura no os cuadra, mirad qué pieza hay debajo y dónde acaba." },
        { k: 'm3look', ph: 'prova', q: 'El cos comença a <b>z = 4</b> i fa <b>24 mm</b> d\'alt. A quina z ha de començar el cap?|El cuerpo empieza en <b>z = 4</b> y mide <b>24 mm</b> de alto. ¿En qué z tiene que empezar la cabeza?', model: { parts: RB1 }, view: 'front',
          opts: ['z = 28|z = 28', 'z = 24|z = 24', 'z = 4|z = 4'], a: 0, ex: '4 + 24 = 28: el cap comença just on s\'acaba el cos.|4 + 24 = 28: la cabeza empieza justo donde acaba el cuerpo.' },
        { k: 'm3fix', ph: 'investiga', q: "Ui! Al robot li han quedat les <b>rodes dretes</b>. Arregla-les perquè quedin de costat (90° en y).|¡Uy! Al robot se le han quedado las <b>ruedas de pie</b>. Arréglalas para que queden de lado (90° en y).",
          start: { parts: [...RODES_DRETES, COS] }, fix: ['r1', 'r2'], palette: ['cyl'],
          checks: [{ k: 'part', t: 'cyl', s: [6, 16, 16], at: [-16, 0, 8], tol: 0.6, txt: 'Roda esquerra tombada a x = −16|Rueda izquierda tumbada en x = −16' }, { k: 'part', t: 'cyl', s: [6, 16, 16], at: [16, 0, 8], tol: 0.6, txt: 'Roda dreta tombada a x = 16|Rueda derecha tumbada en x = 16' }, { k: 'one' }, { k: 'onplate' }],
          hint: 'Toca una roda i, a Gir, posa 90 a la y. Mira a Posició que continuï a x = −16 (o 16), y = 0, z = 0.|Toca una rueda y, en Giro, pon 90 en la y. Mira en Posición que siga en x = −16 (o 16), y = 0, z = 0.', sol: { parts: RB1 } },
        { k: 'move', ph: 'pausa', title: 'El ball del robot|El baile del robot', secs: 30, t: "Mou-te com un robot: braços estirats a <b>90°</b>, gira el cap <b>45°</b> a la dreta i a l'esquerra, fes voltar les mans com si fossin rodes… i atura't en sec!|Muévete como un robot: brazos estirados a <b>90°</b>, gira la cabeza <b>45°</b> a la derecha y a la izquierda, haz girar las manos como si fueran ruedas… ¡y párate en seco!" },
        { k: 'm3build', ph: 'repte', q: '<b>Pas 1: el cap.</b> Fes el cap de <b>20 × 16 × 14 mm</b> i posa\'l a sobre del cos (base a z = 28).|<b>Paso 1: la cabeza.</b> Haz la cabeza de <b>20 × 16 × 14 mm</b> y ponla encima del cuerpo (base en z = 28).',
          start: { parts: [...RB1, B('cap', 'box', [20, 20, 20], -45, 30, 0, '#5BC0EB')] }, palette: ['box'], target: { parts: [...RB1, CAPR] },
          checks: [{ k: 'part', t: 'box', s: [20, 16, 14], at: [0, 0, 35], tol: 0.6, txt: 'Cap de 20 × 16 × 14 mm a sobre del cos|Cabeza de 20 × 16 × 14 mm encima del cuerpo' }, { k: 'match', target: { parts: [...RB1, CAPR] }, th: 0.94, t: 'El robot és com el fantasma|El robot es como el fantasma' }, { k: 'one' }],
          hint: 'A Mida: x = 20, y = 16 i z = 14 (sense el cadenat). A Posició: x = 0, y = 0 i z = 28.|En Medida: x = 20, y = 16 y z = 14 (sin el candado). En Posición: x = 0, y = 0 y z = 28.', sol: { parts: [...RB1, CAPR] } },
        { k: 'm3build', ph: 'repte', q: "<b>Pas 2: els ulls.</b> Fes les boles de <b>6 mm</b> i posa-les a la cara: x = −5 i x = 5, y = −8, base a z = 32.|<b>Paso 2: los ojos.</b> Haz las bolas de <b>6 mm</b> y ponlas en la cara: x = −5 y x = 5, y = −8, base en z = 32.",
          start: { parts: [...RB1, CAPR, B('u1', 'sph', [20, 20, 20], -45, -30, 0, '#2A2F3A'), B('u2', 'sph', [20, 20, 20], 45, -30, 0, '#2A2F3A')] }, palette: ['sph'], target: { parts: RB2 },
          checks: [{ k: 'part', t: 'sph', s: [6, 6, 6], at: [-5, -8, 35], tol: 0.6, txt: 'Ull a (−5, −8, 32)|Ojo en (−5, −8, 32)' }, { k: 'part', t: 'sph', s: [6, 6, 6], at: [5, -8, 35], tol: 0.6, txt: 'Ull a (5, −8, 32)|Ojo en (5, −8, 32)' }, { k: 'one' }, { k: 'onplate' }],
          hint: 'Amb Proporcional, escriu 6 a la mida de cada bola. Després, a Posició: x = −5 (o 5), y = −8 i z = 32.|Con Proporcional, escribe 6 en la medida de cada bola. Después, en Posición: x = −5 (o 5), y = −8 y z = 32.', sol: { parts: RB2 } },
        { k: 'm3build', ph: 'repte', q: "<b>Pas 3: els braços.</b> Tomba cada braç <b>90° en y</b> i enganxa'l a un costat del cos: x = −23 i x = 23, base a z = 20.|<b>Paso 3: los brazos.</b> Tumba cada brazo <b>90° en y</b> y pégalo a un lado del cuerpo: x = −23 y x = 23, base en z = 20.",
          start: { parts: [...RB2, brac('b1', -45, false), brac('b2', 45, false)] }, palette: ['box'], target: { parts: RB3 },
          checks: [{ k: 'part', t: 'box', s: [20, 6, 6], at: [-23, 0, 23], tol: 0.6, txt: 'Braç esquerre estirat a x = −23|Brazo izquierdo estirado en x = −23' }, { k: 'part', t: 'box', s: [20, 6, 6], at: [23, 0, 23], tol: 0.6, txt: 'Braç dret estirat a x = 23|Brazo derecho estirado en x = 23' }, { k: 'sym', ax: 'x', th: 0.95 }, { k: 'one' }],
          hint: 'Toca un braç: a Gir, y = 90. A Posició: x = −23, y = 0 i z = 20. L\'altre, igual però a x = 23.|Toca un brazo: en Giro, y = 90. En Posición: x = −23, y = 0 y z = 20. El otro, igual pero en x = 23.', sol: { parts: RB3 } },
        { k: 'm3build', ph: 'repte', extra: true, q: "<b>Pas 4: l'antena.</b> Un cilindre de <b>2 × 2 × 8 mm</b> a sobre del cap i una bola de <b>6 mm</b> a la punta.|<b>Paso 4: la antena.</b> Un cilindro de <b>2 × 2 × 8 mm</b> encima de la cabeza y una bola de <b>6 mm</b> en la punta.",
          start: { parts: [...RB3, B('antena', 'cyl', [20, 20, 20], -45, 35, 0, '#9AA3B5'), B('bola', 'sph', [20, 20, 20], 45, 35, 0, '#E8453C')] }, palette: ['cyl', 'sph'], target: { parts: ROBOT },
          checks: [{ k: 'part', t: 'cyl', s: [2, 2, 8], at: [0, 0, 46], tol: 0.6, txt: 'Antena de 2 × 2 × 8 mm a sobre del cap|Antena de 2 × 2 × 8 mm encima de la cabeza' }, { k: 'part', t: 'sph', s: [6, 6, 6], at: [0, 0, 53], tol: 0.6, txt: 'Bola de 6 mm a la punta (z = 50)|Bola de 6 mm en la punta (z = 50)' }, { k: 'one' }, { k: 'onplate' }],
          hint: 'El cap s\'acaba a z = 42: l\'antena comença a z = 42 i s\'acaba a 50. La bola comença a z = 50. Totes dues a x = 0, y = 0.|La cabeza acaba en z = 42: la antena empieza en z = 42 y acaba en 50. La bola empieza en z = 50. Las dos en x = 0, y = 0.', sol: { parts: ROBOT } },
        { k: 'm3free', ph: 'crea', q: "<b>El teu robot.</b> Ara el robot és teu: canvia'n els colors, gira un braç 45° per saludar, afegeix-hi un accessori (un barret, una motxilla…). Que continuï d'una sola peça i sobre la placa.|<b>Tu robot.</b> Ahora el robot es tuyo: cambia sus colores, gira un brazo 45° para saludar, añádele un accesorio (un sombrero, una mochila…). Que siga siendo una sola pieza y sobre la placa.",
          name: 'El meu robot de peces|Mi robot de piezas', start: { parts: ROBOT }, palette: ['box', 'cyl', 'sph', 'cone', 'pyr', 'wedge', 'torus', 'star', 'heart'],
          crit: ['Té totes les peces de la fitxa: rodes, cos, braços, cap, ulls i antena|Tiene todas las piezas de la ficha: ruedas, cuerpo, brazos, cabeza, ojos y antena', "Hi has afegit almenys un detall teu (un accessori, un braç girat…)|Le has añadido al menos un detalle tuyo (un accesorio, un brazo girado…)", 'És una sola peça i toca la placa|Es una sola pieza y toca la placa'],
          checks: [{ k: 'count', min: 11, txt: 'Almenys 11 peces (les 10 de la fitxa i una de teva)|Al menos 11 piezas (las 10 de la ficha y una tuya)' }, { k: 'colors', min: 3 }, { k: 'one' }, { k: 'onplate' }],
          sol: { parts: [...ROBOT, B('motxilla', 'box', [16, 6, 16], 0, 12, 8, '#2FB36D')] } },
        { k: 'quiz', ph: 'tanca', q: 'Quin és el millor ordre per construir un model gran?|¿Cuál es el mejor orden para construir un modelo grande?', opts: ['De baix a dalt, part per part|De abajo arriba, parte por parte', 'Primer els detalls petits|Primero los detalles pequeños', 'Totes les peces alhora i després moure-les|Todas las piezas a la vez y después moverlas'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'A la fitxa, una roda diu «gir: 0°, 90°, 0°». Què vol dir?|En la ficha, una rueda dice «giro: 0°, 90°, 0°». ¿Qué quiere decir?', opts: ['Que està girada 90° en y|Que está girada 90° en y', 'Que està girada 90° en x|Que está girada 90° en x', 'Que no està girada|Que no está girada'], a: 0,
          ex: "Els tres números van en ordre: x, y, z. El 90 és al mig: gir en y.|Los tres números van en orden: x, y, z. El 90 está en el medio: giro en y." },
        { k: 'feel', ph: 'tanca' }
      ] }
  ] };
})();
