/* Tech Creadors · unitat 2 «Animació» (vestits, esperar, bucles, rebotar, molts personatges alhora) · l'aquari del moll */
Object.assign(TBADGE, {
  g_vestits: { id: 'g_vestits', ico: '🎞️', n: 'Animador/a|Animador/a', d: "Has fet la teva primera animació canviant de vestit amb «espera» perquè es vegi.|Has hecho tu primera animación cambiando de disfraz con «espera» para que se vea." },
  g_persempre: { id: 'g_persempre', ico: '🔁', n: 'Bucle infinit|Bucle infinito', d: "Has fet animacions que no s'acaben mai amb «repeteix» i «per sempre».|Has hecho animaciones que no se acaban nunca con «repite» y «por siempre»." },
  g_alhora: { id: 'g_alhora', ico: '🎼', n: "Director/a d'orquestra|Director/a de orquesta", d: 'Has fet que molts personatges es moguin alhora, cadascun amb els seus guions.|Has hecho que muchos personajes se muevan a la vez, cada uno con sus guiones.' },
  g_aquari: { id: 'g_aquari', ico: '🐠', n: "Guarda de l'aquari|Guarda del acuario", d: "Has acabat el projecte de l'aquari animat: molts animals, bucles i vestits.|Has terminado el proyecto del acuario animado: muchos animales, bucles y disfraces." }
});
COURSE_UNITS[2] = { t: 'Animació|Animación', d: 'Vestits, bucles i temps|Disfraces, bucles y tiempo', color: '#C447A8', s: [

  /* ---------- Sessió 1 · Dibuixos que es mouen (vestits i esperar) ---------- */
  { id: 'g2-1', t: 'Dibuixos que es mouen|Dibujos que se mueven', min: 40, badge: 'g_vestits',
    learn: ["Un personatge té diversos <b>vestits</b> (dibuixos) i, si els canviem de pressa, sembla que es mou.|Un personaje tiene varios <b>disfraces</b> (dibujos) y, si los cambiamos deprisa, parece que se mueve.",
      "«Vestit següent» passa al dibuix següent i «posa el vestit» tria un número concret.|«Disfraz siguiente» pasa al dibujo siguiente y «pon el disfraz» elige un número concreto.",
      "Sense «espera», els canvis són tan ràpids que no es veuen: l'espera dona temps a mirar.|Sin «espera», los cambios son tan rápidos que no se ven: la espera da tiempo a mirar."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "Recordes l'escenari? On és el punt <b>x: 0, y: 0</b>?|¿Recuerdas el escenario? ¿Dónde está el punto <b>x: 0, y: 0</b>?",
        opts: ["Just al mig de l'escenari|Justo en el medio del escenario", 'A la cantonada de dalt a la dreta|En la esquina de arriba a la derecha', 'A baix de tot, a la vora|Abajo del todo, en el borde'], a: 0,
        ex: "El (0, 0) és el centre: la x creix cap a la dreta i la y, cap amunt.|El (0, 0) es el centro: la x crece hacia la derecha y la y, hacia arriba." },
      { k: 'quiz', ph: 'recorda', q: 'Quin bloc fa que un personatge parli amb una bafarada?|¿Qué bloque hace que un personaje hable con un bocadillo?',
        opts: ['«Digues Hola! durant 2 segons»|«Di ¡Hola! durante 2 segundos»', '«Mou-te 10 passos»|«Muévete 10 pasos»', '«Gira 15 graus»|«Gira 15 grados»'], a: 0 },
      { k: 'story', ph: 'missio', who: 'both', scene: 'moll', title: "L'aquari del moll|El acuario del muelle",
        t: "Al moll de l'illa obriran un <b>aquari</b> nou! La Marina, la guarda, vol posar una pantalla gegant a l'entrada amb peixos, crancs i meduses. Però hi ha un problema: tots els dibuixos estan <b>quiets</b>, com fotos.|¡En el muelle de la isla abrirán un <b>acuario</b> nuevo! Marina, la guardiana, quiere poner una pantalla gigante en la entrada con peces, cangrejos y medusas. Pero hay un problema: todos los dibujos están <b>quietos</b>, como fotos." },
      { k: 'story', ph: 'missio', who: 'numi', mood: 'think',
        t: "Com ho fan els dibuixos animats per moure's? Avui descobrirem el seu secret: els <b>vestits</b> i el temps d'<b>espera</b>. Al final de la sessió faràs la teva primera animació!|¿Cómo lo hacen los dibujos animados para moverse? Hoy descubriremos su secreto: los <b>disfraces</b> y el tiempo de <b>espera</b>. ¡Al final de la sesión harás tu primera animación!" },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Animació|Animación', t: 'Què és un dibuix animat?|¿Qué es un dibujo animado?', anim: 'g2flip',
          x: "Un dibuix animat són <b>molts dibuixos</b>, gairebé iguals, que es mostren un darrere l'altre <b>molt de pressa</b>. Els nostres ulls no veuen els salts: veuen <span class='hl'>moviment</span>. És com un llibret que passes amb el dit.|Un dibujo animado son <b>muchos dibujos</b>, casi iguales, que se muestran uno tras otro <b>muy deprisa</b>. Nuestros ojos no ven los saltos: ven <span class='hl'>movimiento</span>. Es como una libreta que pasas con el dedo.",
          tip: "Al cinema, a cada segon passen 24 imatges. A l'escenari de Numi, 30.|En el cine, en cada segundo pasan 24 imágenes. En el escenario de Numi, 30." },
        { k: 'Vestits|Disfraces', t: 'Cada personatge té vestits|Cada personaje tiene disfraces', anim: 'g2cost',
          x: "Un <span class='hl'>vestit</span> és un dels dibuixos d'un personatge. El peix en té 2: amb la cua amunt i amb la cua avall. El bloc <b>vestit següent</b> canvia el dibuix pel següent. Quan arriba a l'últim, torna al primer.|Un <span class='hl'>disfraz</span> es uno de los dibujos de un personaje. El pez tiene 2: con la cola arriba y con la cola abajo. El bloque <b>disfraz siguiente</b> cambia el dibujo por el siguiente. Cuando llega al último, vuelve al primero." },
        { k: 'Un vestit concret|Un disfraz concreto', t: '«Posa el vestit…»|«Pon el disfraz…»',
          media: { k: 'stage', w: { bg: 'parc', sprites: [{ id: 'mascota', art: 'mascota', x: 0, y: -20, size: 140, rot: 'none' }] }, prog: '@mascota flag{ costume:1 say:"Bon dia!|¡Buenos días!",1.5 costume:2 say:"Tinc gana…|Tengo hambre…",1.5 costume:3 say:"Zzz…|Zzz…",1.5 }', time: 6 },
          x: "La mascota té 4 vestits: 1 content, 2 té gana, 3 dorm i 4 trist. El bloc <b>posa el vestit 3</b> la posa a dormir, porti el vestit que porti. Serveix per triar <b>un dibuix concret</b> pel seu número.|La mascota tiene 4 disfraces: 1 contenta, 2 tiene hambre, 3 duerme y 4 triste. El bloque <b>pon el disfraz 3</b> la pone a dormir, lleve el disfraz que lleve. Sirve para elegir <b>un dibujo concreto</b> por su número.",
          tip: "Posa «posa el vestit 1» al principi del programa: així sempre comença igual.|Pon «pon el disfraz 1» al principio del programa: así siempre empieza igual." },
        { k: 'Esperar|Esperar', t: 'El bloc «espera»|El bloque «espera»',
          media: { k: 'stage', w: { bg: 'aquari', sprites: [{ id: 'medusa', art: 'medusa', x: 0, y: 0, size: 160, rot: 'none' }] }, prog: '@medusa flag{ next wait:1 next wait:1 next wait:1 next wait:1 next }', time: 5 },
          x: "<b>Espera 1 segons</b> atura el guió una estona abans de fer el bloc següent. Entre dos canvis de vestit, l'espera ens dona temps de <b>veure</b> cada dibuix. Amb esperes curtes (0,2 segons) l'animació va ràpida; amb esperes llargues, a poc a poc.|<b>Espera 1 segundos</b> para el guion un rato antes de hacer el bloque siguiente. Entre dos cambios de disfraz, la espera nos da tiempo de <b>ver</b> cada dibujo. Con esperas cortas (0,2 segundos) la animación va rápida; con esperas largas, despacio." },
        { k: 'Compte!|¡Cuidado!', t: "Sense espera, no es veu res|Sin espera, no se ve nada", anim: 'g2wait',
          x: "L'ordinador fa els blocs molt i molt de pressa. Si poses dos «vestit següent» seguits, el dibuix canvia i torna en menys d'un segon: <b>no es veu</b>. Posa sempre una <b>espera</b> entre canvi i canvi.|El ordenador hace los bloques muy muy deprisa. Si pones dos «disfraz siguiente» seguidos, el dibujo cambia y vuelve en menos de un segundo: <b>no se ve</b>. Pon siempre una <b>espera</b> entre cambio y cambio.",
          bad: "Vestit següent, vestit següent, vestit següent: el personatge sembla quiet.|Disfraz siguiente, disfraz siguiente, disfraz siguiente: el personaje parece quieto.", good: "Vestit següent, espera 0,5, vestit següent, espera 0,5: ara sí que es mou.|Disfraz siguiente, espera 0,5, disfraz siguiente, espera 0,5: ahora sí que se mueve." }
      ] },
      { k: 'seq', ph: 'mans', q: "La mascota <b>dorm</b>, al cap d'una estona <b>es desperta contenta</b> i diu «Bon dia!». Ordena els blocs del programa.|La mascota <b>duerme</b>, al cabo de un rato <b>se despierta contenta</b> y dice «¡Buenos días!». Ordena los bloques del programa.",
        items: ['Quan comença (bandera verda)|Al empezar (bandera verde)', 'Posa el vestit 3 (dorm)|Pon el disfraz 3 (duerme)', 'Espera 2 segons|Espera 2 segundos', 'Posa el vestit 1 (contenta)|Pon el disfraz 1 (contenta)', 'Digues «Bon dia!»|Di «¡Buenos días!»'],
        ex: "Primer la posem a dormir, després esperem perquè es vegi i, finalment, es desperta i parla.|Primero la ponemos a dormir, después esperamos para que se vea y, finalmente, se despierta y habla." },
      { k: 'unplug', ph: 'mans', ico: '📒', title: 'El llibret animat|La libreta animada',
        t: "Fes la teva pròpia animació de paper! Necessites una llibreta petita o 8 papers enganxosos i un llapis.|¡Haz tu propia animación de papel! Necesitas una libreta pequeña o 8 papeles adhesivos y un lápiz.",
        steps: ["A l'última pàgina, dibuixa una pilota a dalt de tot.|En la última página, dibuja una pelota arriba del todo.",
          "A la pàgina d'abans, dibuixa-la una mica més avall (es transparenta i es veu la d'abans).|En la página de antes, dibújala un poco más abajo (se transparenta y se ve la de antes).",
          "Continua fins que la pilota toqui el terra i, a les últimes pàgines, torna-la a pujar.|Sigue hasta que la pelota toque el suelo y, en las últimas páginas, vuelve a subirla.",
          "Passa les pàgines de pressa amb el dit: la pilota bota! Cada pàgina és un <b>vestit</b>.|Pasa las páginas deprisa con el dedo: ¡la pelota bota! Cada página es un <b>disfraz</b>."],
        tip: "Si passes les pàgines a poc a poc, veus dibuixos separats. De pressa, veus moviment. És el mateix que fa l'espera!|Si pasas las páginas despacio, ves dibujos separados. Deprisa, ves movimiento. ¡Es lo mismo que hace la espera!" },
      { k: 'quiz', ph: 'prova', q: "El gat té <b>2 vestits</b> i comença amb el vestit 1. El programa fa <b>3 vegades</b> «vestit següent». Amb quin vestit acaba?|El gato tiene <b>2 disfraces</b> y empieza con el disfraz 1. El programa hace <b>3 veces</b> «disfraz siguiente». ¿Con qué disfraz termina?",
        opts: ['Amb el vestit 2|Con el disfraz 2', 'Amb el vestit 1|Con el disfraz 1', 'Amb el vestit 3|Con el disfraz 3'], a: 0,
        ex: "1 → 2 → 1 → 2. Quan arriba a l'últim vestit, torna a començar pel primer. El vestit 3 no existeix!|1 → 2 → 1 → 2. Cuando llega al último disfraz, vuelve a empezar por el primero. ¡El disfraz 3 no existe!" },
      { k: 'sspot', ph: 'investiga', q: "El peix hauria de moure la cua cada mig segon (vestit 1, 2, 1, 2), però a la meitat <b>es queda quiet</b>. Toca el bloc equivocat.|El pez debería mover la cola cada medio segundo (disfraz 1, 2, 1, 2), pero a la mitad <b>se queda quieto</b>. Toca el bloque equivocado.",
        w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: 0, y: 0, size: 150, rot: 'lr' }] },
        prog: '@peix flag{ costume:1 wait:0.5 costume:2 wait:0.5 costume:2! wait:0.5 costume:1 }',
        ex: "Aquest bloc posa el vestit 2 quan el peix ja porta el vestit 2: no canvia res. Hi havia d'anar el vestit 1.|Este bloque pone el disfraz 2 cuando el pez ya lleva el disfraz 2: no cambia nada. Tenía que ir el disfraz 1." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de personatge animat! <b>Vestit 1</b>: braços avall. <b>Vestit 2</b>: braços amunt. Canvia de vestit cada vegada que comptis fins a 2 (espera de 2 segons). Ara més de pressa: cada segon!|¡Haz de personaje animado! <b>Disfraz 1</b>: brazos abajo. <b>Disfraz 2</b>: brazos arriba. Cambia de disfraz cada vez que cuentes hasta 2 (espera de 2 segundos). Ahora más deprisa: ¡cada segundo!" },
      { k: 'stage', ph: 'repte', q: "Fes que el peix <b>mogui la cua</b>: ha de canviar de vestit almenys <b>4 vegades</b>, amb una espera entre canvi i canvi perquè es vegi.|Haz que el pez <b>mueva la cola</b>: tiene que cambiar de disfraz al menos <b>4 veces</b>, con una espera entre cambio y cambio para que se vea.",
        w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: 0, y: 10, size: 150, rot: 'lr' }], time: 5, goal: [{ k: 'costumes', s: 'peix', min: 4 }] },
        edit: ['peix'], hats: ['flag'], pal: ['next', 'wait'],
        sol: '@peix flag{ next wait:0.5 next wait:0.5 next wait:0.5 next }',
        hint: "Toca «vestit següent» i després «espera». Repeteix-ho fins que en tinguis 4 de cada.|Toca «disfraz siguiente» y después «espera». Repítelo hasta que tengas 4 de cada." },
      { k: 'stage', ph: 'repte', q: "La mascota té gana i després son. Fes que <b>digui alguna cosa</b> i que canviï de vestit <b>2 vegades</b>: primer el vestit 2 (té gana) i després el 3 (dorm).|La mascota tiene hambre y después sueño. Haz que <b>diga algo</b> y que cambie de disfraz <b>2 veces</b>: primero el disfraz 2 (tiene hambre) y después el 3 (duerme).",
        w: { bg: 'parc', sprites: [{ id: 'mascota', art: 'mascota', x: 0, y: -10, size: 140, rot: 'none' }], time: 6, goal: [{ k: 'said', s: 'mascota' }, { k: 'costumes', s: 'mascota', min: 2 }] },
        edit: ['mascota'], hats: ['flag'], pal: ['costume', 'say', 'wait'], texts: ['Tinc gana!|¡Tengo hambre!', 'Quina son…|Qué sueño…', 'Bona nit!|¡Buenas noches!'],
        sol: '@mascota flag{ costume:2 say:"Tinc gana!|¡Tengo hambre!",2 costume:3 say:"Bona nit!|¡Buenas noches!",2 }',
        hint: "Toca el número del bloc «posa el vestit» per triar el vestit 2 o el 3.|Toca el número del bloque «pon el disfraz» para elegir el disfraz 2 o el 3." },
      { k: 'stage', ph: 'repte', q: "Ui! La papallona hauria de batre les ales, però <b>no es mou gens</b>. Mira els números dels blocs i arregla el programa.|¡Uy! La mariposa debería batir las alas, pero <b>no se mueve nada</b>. Mira los números de los bloques y arregla el programa.",
        w: { bg: 'bosc', sprites: [{ id: 'papallona', art: 'papallona', x: 0, y: 20, size: 150, rot: 'none' }], time: 4, goal: [{ k: 'costumes', s: 'papallona', min: 3 }] },
        edit: ['papallona'], hats: ['flag'], pal: ['costume', 'next', 'wait'],
        prog: '@papallona flag{ costume:1 wait:0.4 costume:1 wait:0.4 costume:1 wait:0.4 costume:1 }',
        sol: '@papallona flag{ costume:2 wait:0.4 costume:1 wait:0.4 costume:2 wait:0.4 costume:1 }',
        hint: "Si sempre poses el vestit 1, el dibuix no canvia mai. Alterna el 2 i l'1 (o fes servir «vestit següent»).|Si siempre pones el disfraz 1, el dibujo no cambia nunca. Alterna el 2 y el 1 (o usa «disfraz siguiente»)." },
      { k: 'stage', ph: 'repte', q: "El cotxe arrenca! Fes que <b>avanci</b> pel carrer i que les rodes <b>girin</b> (que canviï de vestit almenys 4 vegades).|¡El coche arranca! Haz que <b>avance</b> por la calle y que las ruedas <b>giren</b> (que cambie de disfraz al menos 4 veces).",
        w: { bg: 'ciutat', sprites: [{ id: 'cotxe', art: 'cotxe', x: -160, y: -130, rot: 'lr' }], time: 5, goal: [{ k: 'costumes', s: 'cotxe', min: 4 }, { k: 'dx', s: 'cotxe', min: 80 }] },
        edit: ['cotxe'], hats: ['flag'], pal: ['move', 'next', 'wait'],
        sol: '@cotxe flag{ next move:25 wait:0.2 next move:25 wait:0.2 next move:25 wait:0.2 next move:25 }',
        hint: "Fes parelles: «vestit següent» i «mou-te 25 passos», amb una espera curta. Uf, quants blocs… La setmana que ve en trobarem un que ho fa més curt!|Haz parejas: «disfraz siguiente» y «muévete 25 pasos», con una espera corta. Uf, cuántos bloques… ¡La semana que viene encontraremos uno que lo hace más corto!" },
      { k: 'screate', ph: 'crea', name: 'La meva primera animació|Mi primera animación',
        q: "Ara decideixes tu! En Numi surt a l'escenari del teatre. Inventa una petita animació: que <b>parli</b>, que <b>canviï de cara</b> (té 4 vestits: normal, content, pensant i trist) i que es vegi cada canvi.|¡Ahora decides tú! Numi sale al escenario del teatro. Inventa una pequeña animación: que <b>hable</b>, que <b>cambie de cara</b> (tiene 4 disfraces: normal, contento, pensando y triste) y que se vea cada cambio.",
        crit: ['Diu alguna cosa|Dice algo', 'Canvia de vestit almenys 3 vegades|Cambia de disfraz al menos 3 veces', 'Fa servir «espera» perquè es vegin els canvis|Usa «espera» para que se vean los cambios'],
        w: { bg: 'escenari', sprites: [{ id: 'numi', art: 'numi', x: 0, y: -30, size: 150, rot: 'none' }], time: 8, goal: [{ k: 'said', s: 'numi' }, { k: 'costumes', s: 'numi', min: 3 }] },
        edit: ['numi'], hats: ['flag'], pal: ['say', 'think', 'costume', 'next', 'wait', 'move', 'turn'], texts: ['Hola a tothom!|¡Hola a todos!', 'Què faré ara?|¿Qué haré ahora?', 'Ja ho sé!|¡Ya lo sé!', 'Oh, no…|Oh, no…'],
        check: P => JSON.stringify(P.numi || {}).includes('"k":"wait"') ? null : "Posa algun bloc «espera» perquè es vegin els canvis de vestit.|Pon algún bloque «espera» para que se vean los cambios de disfraz.",
        sol: '@numi flag{ costume:1 say:"Hola a tothom!|¡Hola a todos!",2 costume:3 think:"Què faré ara?|¿Qué haré ahora?",2 costume:2 say:"Ja ho sé!|¡Ya lo sé!",1 wait:1 costume:1 }' },
      { k: 'quiz', ph: 'tanca', q: 'Per què posem una <b>espera</b> entre dos canvis de vestit?|¿Por qué ponemos una <b>espera</b> entre dos cambios de disfraz?',
        opts: ["Perquè, si no, canvien tan de pressa que no es veuen|Porque, si no, cambian tan deprisa que no se ven", 'Perquè el personatge es cansa|Porque el personaje se cansa', "Perquè sense espera el programa no funciona|Porque sin espera el programa no funciona"], a: 0 },
      { k: 'quiz', ph: 'tanca', q: 'Quin bloc canvia el dibuix del personatge pel dibuix que ve després?|¿Qué bloque cambia el dibujo del personaje por el dibujo que viene después?',
        opts: ['«Vestit següent»|«Disfraz siguiente»', '«Mou-te 10 passos»|«Muévete 10 pasos»', '«Espera 1 segons»|«Espera 1 segundos»'], a: 0,
        ex: "«Posa el vestit…» també canvia el dibuix, però tria un número concret.|«Pon el disfraz…» también cambia el dibujo, pero elige un número concreto." },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 2 · Bucles per sempre (repeteix, per sempre, rebotar) ---------- */
  { id: 'g2-2', t: 'Bucles per sempre|Bucles para siempre', min: 40, badge: 'g_persempre',
    learn: ["Un <b>bucle</b> repeteix els blocs de dins: «repeteix 10 vegades» compta les voltes i «per sempre» no s'acaba mai.|Un <b>bucle</b> repite los bloques de dentro: «repite 10 veces» cuenta las vueltas y «por siempre» no se acaba nunca.",
      "Els blocs que hi ha a sota d'un «per sempre» no s'arriben a fer mai.|Los bloques que hay debajo de un «por siempre» no se llegan a hacer nunca.",
      "«Si toques la vora, rebota», dins del bucle, fa que el personatge doni la volta i no surti de l'escenari.|«Si tocas el borde, rebota», dentro del bucle, hace que el personaje dé la vuelta y no salga del escenario."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "El peix té 2 vestits i ara porta el <b>vestit 2</b>. Què passa si fa «vestit següent»?|El pez tiene 2 disfraces y ahora lleva el <b>disfraz 2</b>. ¿Qué pasa si hace «disfraz siguiente»?",
        opts: ['Torna al vestit 1|Vuelve al disfraz 1', "Es queda amb el vestit 2|Se queda con el disfraz 2", 'Desapareix|Desaparece'], a: 0,
        ex: "Després de l'últim vestit, torna a començar pel primer.|Después del último disfraz, vuelve a empezar por el primero." },
      { k: 'quiz', ph: 'recorda', q: 'Per a què serveix el bloc <b>espera</b> en una animació?|¿Para qué sirve el bloque <b>espera</b> en una animación?',
        opts: ['Per donar temps a veure cada dibuix|Para dar tiempo a ver cada dibujo', 'Per fer el personatge més gran|Para hacer el personaje más grande', 'Per esborrar el programa|Para borrar el programa'], a: 0 },
      { k: 'story', ph: 'missio', who: 'both', scene: 'moll', title: 'El tanc gran|El tanque grande',
        t: "La Marina està contenta: el peix de la setmana passada ja mou la cua! Però… només 2 segons. «La pantalla ha d'estar encesa <b>tot el dia</b>», diu. «El peix ha de nedar i nedar sense parar.»|Marina está contenta: ¡el pez de la semana pasada ya mueve la cola! Pero… solo 2 segundos. «La pantalla tiene que estar encendida <b>todo el día</b>», dice. «El pez tiene que nadar y nadar sin parar.»" },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'think',
        t: "BIP… Vestit següent, espera, vestit següent, espera, vestit següent… fins a la nit? Necessitaria mil blocs! Hi ha d'haver un bloc que <b>repeteixi</b> per mi. Es diu <b>bucle</b>!|BIP… Disfraz siguiente, espera, disfraz siguiente, espera, disfraz siguiente… ¿hasta la noche? ¡Necesitaría mil bloques! Tiene que haber un bloque que <b>repita</b> por mí. ¡Se llama <b>bucle</b>!" },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Patrons|Patrones', t: 'El tros que es repeteix|El trozo que se repite', anim: 'g2loop',
          x: "Mira el programa de l'esquerra: «vestit següent» i «espera» surten <b>3 vegades</b>, sempre iguals. Això és un <span class='hl'>patró</span>. En comptes d'escriure'l 3 vegades, el posem una sola vegada dins d'un <span class='hl'>bucle</span>.|Mira el programa de la izquierda: «disfraz siguiente» y «espera» salen <b>3 veces</b>, siempre iguales. Eso es un <span class='hl'>patrón</span>. En vez de escribirlo 3 veces, lo ponemos una sola vez dentro de un <span class='hl'>bucle</span>." },
        { k: 'Repeteix|Repite', t: '«Repeteix 8 vegades»|«Repite 8 veces»',
          media: { k: 'stage', w: { bg: 'aquari', sprites: [{ id: 'medusa', art: 'medusa', x: 0, y: 0, size: 160, rot: 'none' }] }, prog: '@medusa flag{ rep:8{ next wait:0.3 } }', time: 4 },
          x: "El bloc <b>repeteix 8 vegades</b> fa els blocs que té <b>a dins</b>, de dalt a baix, i quan acaba torna a començar. Quan ha fet les 8 voltes, s'acaba i el programa continua amb el bloc de sota.|El bloque <b>repite 8 veces</b> hace los bloques que tiene <b>dentro</b>, de arriba abajo, y cuando termina vuelve a empezar. Cuando ha hecho las 8 vueltas, se acaba y el programa sigue con el bloque de debajo.",
          tip: "Per posar blocs dins del bucle, toca l'espai buit que hi ha a dins i després tria els blocs.|Para poner bloques dentro del bucle, toca el espacio vacío que hay dentro y después elige los bloques." },
        { k: 'Per sempre|Por siempre', t: 'Un bucle que no s’acaba mai|Un bucle que no se acaba nunca',
          media: { k: 'stage', w: { bg: 'cel', sprites: [{ id: 'ocell', art: 'ocell', x: 0, y: 20, size: 160, rot: 'lr' }] }, prog: '@ocell flag{ forever{ next wait:0.25 } }', time: 6 },
          x: "El bloc <b>per sempre</b> repeteix els blocs de dins una vegada i una altra, <b>sense parar</b>, fins que toques el botó d'aturar. És perfecte per a animacions que han de durar tota l'estona, com l'ocell que bat les ales.|El bloque <b>por siempre</b> repite los bloques de dentro una vez y otra, <b>sin parar</b>, hasta que tocas el botón de parar. Es perfecto para animaciones que tienen que durar todo el rato, como el pájaro que bate las alas." },
        { k: 'Rebotar|Rebotar', t: '«Si toques la vora, rebota»|«Si tocas el borde, rebota»', anim: 'g2bounce',
          x: "Un peix que fa «mou-te 5 passos» per sempre acaba <b>sortint de l'escenari</b>. El bloc <b>si toques la vora, rebota</b> mira si el personatge toca la vora i, si la toca, li fa <b>donar la volta</b>: si anava cap a la dreta (direcció 90), ara va cap a l'esquerra (-90).|Un pez que hace «muévete 5 pasos» por siempre acaba <b>saliendo del escenario</b>. El bloque <b>si tocas el borde, rebota</b> mira si el personaje toca el borde y, si lo toca, le hace <b>dar la vuelta</b>: si iba hacia la derecha (dirección 90), ahora va hacia la izquierda (-90)." },
        { k: 'Compte!|¡Cuidado!', t: "Després de «per sempre», res|Después de «por siempre», nada", anim: 'g2never',
          x: "Com que «per sempre» no s'acaba mai, el programa <b>no arriba mai</b> als blocs que hi ha a sota. I el bloc «rebota» ha d'anar <b>a dins</b> del bucle: així es comprova a cada pas.|Como «por siempre» no se acaba nunca, el programa <b>no llega nunca</b> a los bloques que hay debajo. Y el bloque «rebota» tiene que ir <b>dentro</b> del bucle: así se comprueba en cada paso.",
          bad: "Per sempre { mou-te 5 passos } i, a sota, rebota.|Por siempre { muévete 5 pasos } y, debajo, rebota.", good: "Per sempre { mou-te 5 passos, rebota }.|Por siempre { muévete 5 pasos, rebota }." }
      ] },
      { k: 'quiz', ph: 'mans', q: "Aquest programa fa caminar el gat: <b>mou-te 10 · vestit següent · mou-te 10 · vestit següent · mou-te 10 · vestit següent</b>. Com el pots escriure amb un bucle?|Este programa hace caminar al gato: <b>muévete 10 · disfraz siguiente · muévete 10 · disfraz siguiente · muévete 10 · disfraz siguiente</b>. ¿Cómo lo puedes escribir con un bucle?",
        opts: ['Repeteix 3 vegades { mou-te 10, vestit següent }|Repite 3 veces { muévete 10, disfraz siguiente }', 'Repeteix 6 vegades { mou-te 10 }|Repite 6 veces { muévete 10 }', 'Repeteix 3 vegades { vestit següent }|Repite 3 veces { disfraz siguiente }'], a: 0,
        ex: "El patró és la parella «mou-te 10 i vestit següent», i surt 3 vegades.|El patrón es la pareja «muévete 10 y disfraz siguiente», y sale 3 veces." },
      { k: 'unplug', ph: 'mans', ico: '🔍', title: 'Caçadors de bucles|Cazadores de bucles',
        t: "A casa hi ha moltes coses que es repeteixen! Busca-les amb algú de la família.|¡En casa hay muchas cosas que se repiten! Búscalas con alguien de la familia.",
        steps: ["Busca 3 coses que es repeteixin <b>un nombre de vegades</b>: pujar els graons de l'escala, els 3 tocs del rellotge…|Busca 3 cosas que se repitan <b>un número de veces</b>: subir los peldaños de la escalera, los 3 toques del reloj…",
          "Busca 3 coses que es repeteixin <b>sense parar</b>, «per sempre»: les agulles del rellotge, el dia i la nit…|Busca 3 cosas que se repitan <b>sin parar</b>, «por siempre»: las agujas del reloj, el día y la noche…",
          "Per a cadascuna, digues quin és el tros que es repeteix.|Para cada una, di cuál es el trozo que se repite.",
          "Apunta-les en dues columnes: «Repeteix N vegades» i «Per sempre».|Apúntalas en dos columnas: «Repite N veces» y «Por siempre»."],
        tip: "Un semàfor és un bucle per sempre: verd, groc, vermell… i torna a començar.|Un semáforo es un bucle por siempre: verde, ámbar, rojo… y vuelve a empezar." },
      { k: 'quiz', ph: 'prova', q: "El cranc fa <b>repeteix 4 vegades { mou-te 10 passos }</b>. Quants passos avança en total?|El cangrejo hace <b>repite 4 veces { muévete 10 pasos }</b>. ¿Cuántos pasos avanza en total?",
        opts: ['40 passos|40 pasos', '14 passos|14 pasos', '10 passos|10 pasos'], a: 0,
        ex: "4 voltes de 10 passos: 10 + 10 + 10 + 10 = 40.|4 vueltas de 10 pasos: 10 + 10 + 10 + 10 = 40." },
      { k: 'sfree', ph: 'prova', q: "Toca la bandera verda i mira el peix. Neda <b>per sempre</b>. Què fa quan arriba a la vora? Quan ho hagis vist, toca el botó d'aturar.|Toca la bandera verde y mira el pez. Nada <b>por siempre</b>. ¿Qué hace cuando llega al borde? Cuando lo hayas visto, toca el botón de parar.",
        w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -60, y: 20, size: 120, rot: 'lr' }] },
        prog: '@peix flag{ forever{ move:5 bounce } }' },
      { k: 'sspot', ph: 'investiga', q: "L'ocell hauria de batre les ales i, al final, dir «Adéu!». Però <b>no ho diu mai</b>. Toca el bloc que no s'arriba a fer mai.|El pájaro debería batir las alas y, al final, decir «¡Adiós!». Pero <b>no lo dice nunca</b>. Toca el bloque que no se llega a hacer nunca.",
        w: { bg: 'cel', sprites: [{ id: 'ocell', art: 'ocell', x: 0, y: 20, size: 140, rot: 'lr' }] },
        prog: '@ocell flag{ forever{ next wait:0.25 } say:"Adéu!|¡Adiós!",2! }',
        ex: "Està a sota d'un «per sempre»: com que el bucle no s'acaba, el programa no hi arriba mai.|Está debajo de un «por siempre»: como el bucle no se acaba, el programa no llega nunca." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Bucle humà! <b>Repeteix 4 vegades</b>: aplaudeix i salta. Ara, <b>per sempre</b>: camina sense parar pel teu lloc… fins que algú digui «Atura!».|¡Bucle humano! <b>Repite 4 veces</b>: aplaude y salta. Ahora, <b>por siempre</b>: camina sin parar en tu sitio… ¡hasta que alguien diga «¡Para!»." },
      { k: 'stage', ph: 'repte', q: "Fes que la medusa mogui els tentacles <b>6 vegades</b>. Només pots fer servir <b>3 blocs</b>: necessitaràs un bucle!|Haz que la medusa mueva los tentáculos <b>6 veces</b>. Solo puedes usar <b>3 bloques</b>: ¡necesitarás un bucle!",
        w: { bg: 'aquari', sprites: [{ id: 'medusa', art: 'medusa', x: 0, y: 0, size: 150, rot: 'none' }], time: 5, goal: [{ k: 'costumes', s: 'medusa', min: 6 }] },
        edit: ['medusa'], hats: ['flag'], pal: ['next', 'wait', 'rep'], max: 3,
        sol: '@medusa flag{ rep:6{ next wait:0.3 } }',
        hint: "Posa primer el bucle «repeteix» i, a dins, «vestit següent» i «espera». Canvia el 10 per un 6.|Pon primero el bucle «repite» y, dentro, «disfraz siguiente» y «espera». Cambia el 10 por un 6." },
      { k: 'stage', ph: 'repte', q: "Ara el peix ha de <b>nedar sense parar</b> d'una banda a l'altra de l'aquari, <b>sense sortir</b> mai de l'escenari.|Ahora el pez tiene que <b>nadar sin parar</b> de un lado al otro del acuario, <b>sin salir</b> nunca del escenario.",
        w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -100, y: 20, size: 110, rot: 'lr' }], time: 5, goal: [{ k: 'moved', s: 'peix', min: 600 }, { k: 'at', s: 'peix', r: [-240, -180, 240, 180] }] },
        edit: ['peix'], hats: ['flag'], pal: ['move', 'bounce', 'next', 'wait', 'rep', 'forever'],
        sol: '@peix flag{ forever{ move:6 bounce } }',
        hint: "Dins d'un «per sempre», posa «mou-te» i «si toques la vora, rebota».|Dentro de un «por siempre», pon «muévete» y «si tocas el borde, rebota»." },
      { k: 'stage', ph: 'repte', q: "El cranc camina per la sorra. Fes que <b>es mogui</b> d'un costat a l'altre <b>per sempre</b> i que, alhora, <b>mogui les potes</b> (canviï de vestit).|El cangrejo camina por la arena. Haz que <b>se mueva</b> de un lado a otro <b>por siempre</b> y que, a la vez, <b>mueva las patas</b> (cambie de disfraz).",
        w: { bg: 'aquari', sprites: [{ id: 'cranc', art: 'cranc', x: 0, y: -130, size: 110, rot: 'lr' }], time: 6, goal: [{ k: 'moved', s: 'cranc', min: 300 }, { k: 'costumes', s: 'cranc', min: 6 }, { k: 'at', s: 'cranc', r: [-240, -180, 240, 180] }] },
        edit: ['cranc'], hats: ['flag'], pal: ['move', 'bounce', 'next', 'wait', 'rep', 'forever'],
        sol: '@cranc flag{ forever{ move:10 next wait:0.1 bounce } }',
        hint: "Dins del «per sempre» hi caben 4 blocs: moure, vestit següent, una espera curta i rebotar.|Dentro del «por siempre» caben 4 bloques: mover, disfraz siguiente, una espera corta y rebotar." },
      { k: 'stage', ph: 'repte', q: "Aquest ocell bat les ales, però <b>se'n va de l'escenari</b> i no torna. Troba l'error i arregla'l.|Este pájaro bate las alas, pero <b>se va del escenario</b> y no vuelve. Encuentra el error y arréglalo.",
        w: { bg: 'cel', sprites: [{ id: 'ocell', art: 'ocell', x: -120, y: 40, size: 110, rot: 'lr' }], time: 6, goal: [{ k: 'moved', s: 'ocell', min: 300 }, { k: 'costumes', s: 'ocell', min: 4 }, { k: 'at', s: 'ocell', r: [-240, -180, 240, 180] }] },
        edit: ['ocell'], hats: ['flag'], pal: ['move', 'bounce', 'next', 'wait', 'forever'],
        prog: '@ocell flag{ forever{ move:12 next wait:0.1 } bounce }',
        sol: '@ocell flag{ forever{ move:12 next wait:0.1 bounce } }',
        hint: "On és el bloc «rebota»? Si és a sota del «per sempre», no es fa mai. Esborra'l i torna'l a posar a dins del bucle.|¿Dónde está el bloque «rebota»? Si está debajo del «por siempre», no se hace nunca. Bórralo y vuelve a ponerlo dentro del bucle." },
      { k: 'screate', ph: 'crea', name: 'La pantalla que no para|La pantalla que no para',
        q: "En Vuit, el pop, serà la imatge de l'aquari quan no hi hagi ningú. Programa'l perquè <b>nedi per sempre</b>, <b>reboti</b> a les vores i <b>canviï de cara</b> mentre neda. Tria tu els números!|Vuit, el pulpo, será la imagen del acuario cuando no haya nadie. Prográmalo para que <b>nade por siempre</b>, <b>rebote</b> en los bordes y <b>cambie de cara</b> mientras nada. ¡Elige tú los números!",
        crit: ['Neda per sempre amb un bucle|Nada por siempre con un bucle', 'Rebota i no surt mai de l’escenari|Rebota y no sale nunca del escenario', 'Canvia de vestit mentre es mou|Cambia de disfraz mientras se mueve'],
        w: { bg: 'aquari', sprites: [{ id: 'vuit', art: 'vuit', x: 0, y: 0, dir: 45, size: 110, rot: 'none' }], time: 6, goal: [{ k: 'moved', s: 'vuit', min: 300 }, { k: 'costumes', s: 'vuit', min: 4 }, { k: 'at', s: 'vuit', r: [-240, -180, 240, 180] }] },
        edit: ['vuit'], hats: ['flag'], pal: ['move', 'turn', 'bounce', 'say', 'costume', 'next', 'wait', 'rep', 'forever'], texts: ["Benvinguts a l'aquari!|¡Bienvenidos al acuario!", 'Glu, glu!|¡Glu, glu!'],
        check: P => JSON.stringify(P.vuit || {}).includes('"k":"forever"') ? null : "Fes servir un bucle «per sempre» perquè la pantalla no pari mai.|Usa un bucle «por siempre» para que la pantalla no pare nunca.",
        sol: '@vuit flag{ forever{ move:12 bounce next wait:0.1 } }' },
      { k: 'quiz', ph: 'tanca', q: 'Quina diferència hi ha entre <b>repeteix 10 vegades</b> i <b>per sempre</b>?|¿Qué diferencia hay entre <b>repite 10 veces</b> y <b>por siempre</b>?',
        opts: ["«Repeteix» s'acaba després de 10 voltes; «per sempre» no s'acaba mai|«Repite» se acaba después de 10 vueltas; «por siempre» no se acaba nunca", 'Cap: fan el mateix|Ninguna: hacen lo mismo', "«Per sempre» va més de pressa|«Por siempre» va más deprisa"], a: 0 },
      { k: 'quiz', ph: 'tanca', q: 'On has de posar <b>si toques la vora, rebota</b> perquè el peix no surti mai?|¿Dónde tienes que poner <b>si tocas el borde, rebota</b> para que el pez no salga nunca?',
        opts: ['A dins del bucle, al costat de «mou-te»|Dentro del bucle, junto a «muévete»', 'A sota del «per sempre»|Debajo del «por siempre»', "Abans del bucle, una sola vegada|Antes del bucle, una sola vez"], a: 0,
        ex: "A dins del bucle es comprova a cada pas que fa el peix.|Dentro del bucle se comprueba en cada paso que da el pez." },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 3 · Molts personatges alhora ---------- */
  { id: 'g2-3', t: 'Molts personatges alhora|Muchos personajes a la vez', min: 40, badge: 'g_alhora',
    learn: ["Cada personatge té els seus propis guions: a dalt tries de qui els vols veure o programar.|Cada personaje tiene sus propios guiones: arriba eliges de quién los quieres ver o programar.",
      "Quan toques la bandera verda, tots els guions «quan comença» comencen alhora.|Cuando tocas la bandera verde, todos los guiones «al empezar» empiezan a la vez.",
      "Amb dos guions, un personatge pot fer dues coses alhora, cadascuna al seu ritme.|Con dos guiones, un personaje puede hacer dos cosas a la vez, cada una a su ritmo."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "Què passa amb un bloc que és <b>a sota</b> d'un bucle «per sempre»?|¿Qué pasa con un bloque que está <b>debajo</b> de un bucle «por siempre»?",
        opts: ["No s'arriba a fer mai|No se llega a hacer nunca", 'Es fa abans del bucle|Se hace antes del bucle', 'Es fa a cada volta del bucle|Se hace en cada vuelta del bucle'], a: 0 },
      { k: 'quiz', ph: 'recorda', q: 'Un peix fa <b>per sempre { mou-te 5 passos }</b>, sense rebotar. Què li passarà?|Un pez hace <b>por siempre { muévete 5 pasos }</b>, sin rebotar. ¿Qué le pasará?',
        opts: ["Sortirà de l'escenari i no tornarà|Saldrá del escenario y no volverá", 'Es pararà a la vora|Se parará en el borde', 'Donarà la volta sol|Dará la vuelta solo'], a: 0,
        ex: "Sense «si toques la vora, rebota», ningú no li diu que ha de donar la volta.|Sin «si tocas el borde, rebota», nadie le dice que tiene que dar la vuelta." },
      { k: 'story', ph: 'missio', who: 'both', scene: 'moll', title: 'Tots a l’aigua!|¡Todos al agua!',
        t: "El gran tanc de l'aquari no té només un peix: hi ha el peix, el cranc, la medusa, la tortuga i en Vuit, el pop! La Marina vol que a la pantalla <b>tots es moguin alhora</b>, cadascun a la seva manera.|El gran tanque del acuario no tiene solo un pez: ¡están el pez, el cangrejo, la medusa, la tortuga y Vuit, el pulpo! Marina quiere que en la pantalla <b>todos se muevan a la vez</b>, cada uno a su manera." },
      { k: 'story', ph: 'missio', who: 'numi', mood: 'happy',
        t: "El secret és que <b>cada personatge té els seus guions</b>. El peix té els seus, el cranc els seus… I quan toques la bandera verda, tots comencen <b>al mateix moment</b>, com una orquestra quan el director aixeca la batuta.|El secreto es que <b>cada personaje tiene sus guiones</b>. El pez tiene los suyos, el cangrejo los suyos… Y cuando tocas la bandera verde, todos empiezan <b>en el mismo momento</b>, como una orquesta cuando el director levanta la batuta." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Guions|Guiones', t: 'Cada personatge, els seus guions|Cada personaje, sus guiones',
          media: { k: 'stage', w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -80, y: 60, rot: 'lr' }, { id: 'cranc', art: 'cranc', x: 60, y: -130, rot: 'lr' }, { id: 'medusa', art: 'medusa', x: 150, y: 40, rot: 'none' }] },
            prog: '@peix flag{ forever{ move:4 bounce } } @cranc flag{ forever{ move:2 bounce } } @medusa flag{ forever{ next wait:0.4 } }', time: 8 },
          x: "Aquí hi ha tres personatges i <b>cadascun té el seu guió</b>: el peix neda, el cranc camina i la medusa mou els tentacles. A l'editor, a dalt de tot, toques un personatge per veure els seus guions o per programar-lo.|Aquí hay tres personajes y <b>cada uno tiene su guion</b>: el pez nada, el cangrejo camina y la medusa mueve los tentáculos. En el editor, arriba del todo, tocas un personaje para ver sus guiones o para programarlo." },
        { k: 'Alhora|A la vez', t: 'Tots comencen alhora|Todos empiezan a la vez',
          media: { k: 'stage', w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -190, y: 50, rot: 'lr' }, { id: 'tuga', art: 'tuga', x: -190, y: -80, size: 90, rot: 'lr' }] },
            prog: '@peix flag{ rep:70{ move:5 } } @tuga flag{ rep:70{ move:2 } }', time: 4 },
          x: "Quan toques la bandera verda, <b>tots els guions «quan comença»</b> es posen en marxa <b>al mateix moment</b>. El peix i la tortuga surten junts, però el peix fa passos de 5 i la tortuga, de 2: el número de «mou-te» decideix qui va més de pressa.|Cuando tocas la bandera verde, <b>todos los guiones «al empezar»</b> se ponen en marcha <b>en el mismo momento</b>. El pez y la tortuga salen juntos, pero el pez da pasos de 5 y la tortuga, de 2: el número de «muévete» decide quién va más deprisa." },
        { k: 'Dos guions|Dos guiones', t: 'Un personatge, dues feines|Un personaje, dos tareas', anim: 'g2para',
          x: "Un personatge pot tenir <b>dos guions</b> «quan comença». El guió 1 el fa nedar i rebotar; el guió 2 li canvia el vestit. Funcionen <b>alhora</b>, cadascun al seu ritme: el peix neda llis i mou la cua cada mig segon.|Un personaje puede tener <b>dos guiones</b> «al empezar». El guion 1 lo hace nadar y rebotar; el guion 2 le cambia el disfraz. Funcionan <b>a la vez</b>, cada uno a su ritmo: el pez nada suave y mueve la cola cada medio segundo." },
        { k: 'El ritme|El ritmo', t: 'Ràpid o a poc a poc|Rápido o despacio',
          media: { k: 'stage', w: { bg: 'aquari', sprites: [{ id: 'medusa', art: 'medusa', x: -110, y: 10, size: 130, rot: 'none' }, { id: 'medusa2', art: 'medusa', x: 110, y: 10, size: 130, rot: 'none', name: 'Medusa 2|Medusa 2' }] },
            prog: '@medusa flag{ forever{ next wait:0.15 } } @medusa2 flag{ forever{ next wait:0.8 } }', time: 6 },
          x: "Les dues meduses tenen el mateix guió, però amb una <b>espera</b> diferent: 0,15 segons la de l'esquerra i 0,8 la de la dreta. Com més curta és l'espera, més ràpida és l'animació. Així cada animal pot tenir el seu caràcter.|Las dos medusas tienen el mismo guion, pero con una <b>espera</b> diferente: 0,15 segundos la de la izquierda y 0,8 la de la derecha. Cuanto más corta es la espera, más rápida es la animación. Así cada animal puede tener su carácter." },
        { k: 'Compte!|¡Cuidado!', t: "Una espera que fa anar a salts|Una espera que hace ir a saltos",
          media: { k: 'stage', w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -60, y: 20, size: 110, rot: 'lr' }] }, prog: '@peix flag{ forever{ move:30 next wait:0.6 bounce } }', time: 6 },
          x: "Aquest peix ho fa tot en un sol bucle, amb una espera de 0,6 segons. Com que l'espera també atura el «mou-te», el peix va <b>a salts</b>. Si vols que nedi llis i mogui la cua a poc a poc, fes <b>dos guions</b>: un per moure i un altre per als vestits.|Este pez lo hace todo en un solo bucle, con una espera de 0,6 segundos. Como la espera también para el «muévete», el pez va <b>a saltos</b>. Si quieres que nade suave y mueva la cola despacio, haz <b>dos guiones</b>: uno para mover y otro para los disfraces.",
          bad: "Un sol bucle amb «mou-te» i una espera llarga: el peix va a salts.|Un solo bucle con «muévete» y una espera larga: el pez va a saltos.", good: "Guió 1: mou-te i rebota. Guió 2: vestit següent i espera.|Guion 1: muévete y rebota. Guion 2: disfraz siguiente y espera." }
      ] },
      { k: 'unplug', ph: 'mans', ico: '🥁', title: "L'orquestra de casa|La orquesta de casa",
        t: "Necessites 2 o 3 persones de casa. Cadascú tindrà el seu «guió» i tots començareu alhora.|Necesitas 2 o 3 personas de casa. Cada uno tendrá su «guion» y todos empezaréis a la vez.",
        steps: ["Repartiu els guions: una persona <b>per sempre: aplaudeix</b>; una altra <b>per sempre: dos cops a la taula</b>; una altra <b>per sempre: xiuxiueja «xim-pum»</b>.|Repartid los guiones: una persona <b>por siempre: aplaude</b>; otra <b>por siempre: dos golpes en la mesa</b>; otra <b>por siempre: susurra «chim-pum»</b>.",
          "Algú fa de bandera verda: diu «Comença!» i tothom arrenca alhora.|Alguien hace de bandera verde: dice «¡Empieza!» y todo el mundo arranca a la vez.",
          "Ara canvieu el ritme: un ho fa a poc a poc (una espera llarga) i un altre, de pressa.|Ahora cambiad el ritmo: uno lo hace despacio (una espera larga) y otro, deprisa.",
          "Repte: una sola persona amb <b>dos guions</b>: amb els peus marca el pas i amb les mans aplaudeix més a poc a poc.|Reto: una sola persona con <b>dos guiones</b>: con los pies marca el paso y con las manos aplaude más despacio."],
        tip: "Cada persona és com un personatge: fa el seu guió sense esperar els altres.|Cada persona es como un personaje: hace su guion sin esperar a los demás." },
      { k: 'quiz', ph: 'mans', q: "A l'escenari hi ha 3 personatges i cadascun té un guió <b>«quan comença»</b>. Què passa quan toques la bandera verda?|En el escenario hay 3 personajes y cada uno tiene un guion <b>«al empezar»</b>. ¿Qué pasa cuando tocas la bandera verde?",
        opts: ['Els 3 guions comencen alhora|Los 3 guiones empiezan a la vez', "Primer el del primer personatge, després el del segon…|Primero el del primer personaje, después el del segundo…", 'Només comença el guió del primer personatge|Solo empieza el guion del primer personaje'], a: 0 },
      { k: 'sfree', ph: 'prova', q: "Toca la bandera verda i mira el tanc. Després, toca cada animal a dalt per veure els seus guions. <b>Qui va més de pressa?</b>|Toca la bandera verde y mira el tanque. Después, toca cada animal arriba para ver sus guiones. <b>¿Quién va más deprisa?</b>",
        w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -100, y: 80, rot: 'lr' }, { id: 'cranc', art: 'cranc', x: 40, y: -130, rot: 'lr' }, { id: 'tuga', art: 'tuga', x: 100, y: -10, size: 90, rot: 'lr', dir: -90 }] },
        prog: '@peix flag{ forever{ move:6 bounce } } flag{ forever{ next wait:0.3 } } @cranc flag{ forever{ move:2 next wait:0.2 bounce } } @tuga flag{ forever{ move:1 bounce } }' },
      { k: 'quiz', ph: 'prova', q: "Al tanc que acabes de veure, quin animal tenia el bloc <b>mou-te 6 passos</b>?|En el tanque que acabas de ver, ¿qué animal tenía el bloque <b>muévete 6 pasos</b>?",
        opts: ['El peix, que és el més ràpid|El pez, que es el más rápido', 'La tortuga, que va a poc a poc|La tortuga, que va despacio', 'El cranc, que camina per la sorra|El cangrejo, que camina por la arena'], a: 0,
        ex: "Com més gran és el número de «mou-te», més lluny va a cada pas. El peix també tenia dos guions: un per nedar i un per a la cua.|Cuanto más grande es el número de «muévete», más lejos va en cada paso. El pez también tenía dos guiones: uno para nadar y otro para la cola." },
      { k: 'sspot', ph: 'investiga', q: "El peix neda bé, però mou la cua <b>molt a poc a poc</b>. Mira els seus dos guions i toca el bloc que el fa tan lent.|El pez nada bien, pero mueve la cola <b>muy despacio</b>. Mira sus dos guiones y toca el bloque que lo hace tan lento.",
        w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -60, y: 20, size: 110, rot: 'lr' }] },
        prog: '@peix flag{ forever{ move:4 bounce } } flag{ forever{ next wait:3! } }',
        ex: "Una espera de 3 segons entre canvi i canvi és molt llarga: la cua gairebé no es mou. Amb 0,3 segons aniria molt millor.|Una espera de 3 segundos entre cambio y cambio es muy larga: la cola casi no se mueve. Con 0,3 segundos iría mucho mejor." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de dos guions alhora! Amb els peus, <b>per sempre</b>: un pas al lloc a cada segon. Amb les mans, <b>per sempre</b>: obre i tanca els dits molt de pressa. Aguantes 10 segons sense barrejar-los?|¡Haz de dos guiones a la vez! Con los pies, <b>por siempre</b>: un paso en el sitio cada segundo. Con las manos, <b>por siempre</b>: abre y cierra los dedos muy deprisa. ¿Aguantas 10 segundos sin mezclarlos?" },
      { k: 'stage', ph: 'repte', q: "Fes que el peix i el cranc <b>es moguin alhora</b> i reboten a les vores. Recorda: toca cada personatge a dalt per programar-lo.|Haz que el pez y el cangrejo <b>se muevan a la vez</b> y reboten en los bordes. Recuerda: toca cada personaje arriba para programarlo.",
        w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -80, y: 60, rot: 'lr' }, { id: 'cranc', art: 'cranc', x: 60, y: -130, rot: 'lr' }], time: 5, goal: [{ k: 'moved', s: 'peix', min: 200 }, { k: 'moved', s: 'cranc', min: 200 }, { k: 'at', s: 'peix', r: [-240, -180, 240, 180] }, { k: 'at', s: 'cranc', r: [-240, -180, 240, 180] }] },
        edit: ['peix', 'cranc'], hats: ['flag'], pal: ['move', 'bounce', 'next', 'wait', 'forever'],
        sol: '@peix flag{ forever{ move:5 bounce } } @cranc flag{ forever{ move:3 bounce } }',
        hint: "Programa primer el peix. Després toca el cranc, a dalt, i fes-li el seu guió.|Programa primero el pez. Después toca el cangrejo, arriba, y hazle su guion." },
      { k: 'stage', ph: 'repte', q: "La medusa té <b>dos guions</b> buits. Al primer, fes-la pujar i baixar per sempre (amb «rebota»). Al segon, fes que mogui els tentacles per sempre.|La medusa tiene <b>dos guiones</b> vacíos. En el primero, hazla subir y bajar por siempre (con «rebota»). En el segundo, haz que mueva los tentáculos por siempre.",
        w: { bg: 'aquari', sprites: [{ id: 'medusa', art: 'medusa', x: 0, y: 0, dir: 0, size: 120, rot: 'none' }], time: 5, goal: [{ k: 'moved', s: 'medusa', min: 300 }, { k: 'costumes', s: 'medusa', min: 6 }, { k: 'at', s: 'medusa', r: [-240, -180, 240, 180] }] },
        edit: ['medusa'], hats: ['flag'], pal: ['move', 'bounce', 'next', 'wait', 'forever'],
        prog: '@medusa flag{ } flag{ }',
        sol: '@medusa flag{ forever{ move:3 bounce } } flag{ forever{ next wait:0.4 } }',
        hint: "Toca l'espai buit del segon guió per posar-hi blocs. Guió 1: per sempre { mou-te, rebota }. Guió 2: per sempre { vestit següent, espera }.|Toca el espacio vacío del segundo guion para poner bloques. Guion 1: por siempre { muévete, rebota }. Guion 2: por siempre { disfraz siguiente, espera }." },
      { k: 'stage', ph: 'repte', q: "La cursa de l'aquari! El peix i la tortuga surten alhora. Fes que, al cap de 4 segons, el peix ja sigui a prop de la <b>bandera</b> i la tortuga encara a la <b>primera meitat</b> del camí.|¡La carrera del acuario! El pez y la tortuga salen a la vez. Haz que, al cabo de 4 segundos, el pez ya esté cerca de la <b>bandera</b> y la tortuga todavía en la <b>primera mitad</b> del camino.",
        w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -200, y: 50, rot: 'lr' }, { id: 'tuga', art: 'tuga', x: -200, y: -80, size: 90, rot: 'lr' }, { id: 'meta', art: 'bandera', x: 205, y: -10, name: 'Meta|Meta' }], time: 4,
          goal: [{ k: 'at', s: 'peix', r: [140, -180, 240, 180] }, { k: 'at', s: 'tuga', r: [-160, -180, 0, 180] }] },
        edit: ['peix', 'tuga'], hats: ['flag'], pal: ['move', 'wait', 'rep', 'forever'],
        sol: '@peix flag{ forever{ move:3 } } @tuga flag{ forever{ move:1 } }',
        hint: "Tots dos poden fer «per sempre { mou-te }». El secret és el número: el peix necessita passos més llargs que la tortuga (prova 3 i 1).|Los dos pueden hacer «por siempre { muévete }». El secreto es el número: el pez necesita pasos más largos que la tortuga (prueba 3 y 1)." },
      { k: 'stage', ph: 'repte', q: "Dos peixos haurien de nedar per l'aquari, però el <b>peix petit</b> gairebé no es mou. Mira el seu guió i arregla'l.|Dos peces deberían nadar por el acuario, pero el <b>pez pequeño</b> casi no se mueve. Mira su guion y arréglalo.",
        w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -100, y: 60, rot: 'lr' }, { id: 'peix2', art: 'peix', x: 100, y: -50, size: 70, dir: -90, rot: 'lr', name: 'Peix petit|Pez pequeño' }], time: 5,
          goal: [{ k: 'moved', s: 'peix', min: 300 }, { k: 'moved', s: 'peix2', min: 300 }, { k: 'at', s: 'peix', r: [-240, -180, 240, 180] }, { k: 'at', s: 'peix2', r: [-240, -180, 240, 180] }] },
        edit: ['peix', 'peix2'], hats: ['flag'], pal: ['move', 'bounce', 'next', 'wait', 'forever'],
        prog: '@peix flag{ forever{ move:5 bounce } } @peix2 flag{ forever{ move:5 wait:3 bounce } }',
        sol: '@peix flag{ forever{ move:5 bounce } } @peix2 flag{ forever{ move:5 bounce } }',
        hint: "Compara el guió del peix petit amb el del peix gran. Quin bloc té de més?|Compara el guion del pez pequeño con el del pez grande. ¿Qué bloque tiene de más?" },
      { k: 'screate', ph: 'crea', name: 'El fons marí|El fondo marino',
        q: "Ara el tanc és teu! Programa el peix, el cranc i la medusa com vulguis: que <b>es moguin alhora</b>, cadascun al seu ritme, i que algun <b>canviï de vestit</b>. Pots fer dos guions a un mateix animal.|¡Ahora el tanque es tuyo! Programa el pez, el cangrejo y la medusa como quieras: que <b>se muevan a la vez</b>, cada uno a su ritmo, y que alguno <b>cambie de disfraz</b>. Puedes hacer dos guiones a un mismo animal.",
        crit: ['El peix i el cranc es mouen alhora|El pez y el cangrejo se mueven a la vez', 'Algun animal canvia de vestit|Algún animal cambia de disfraz', 'Ningú no surt de l’escenari|Nadie sale del escenario'],
        w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -100, y: 70, rot: 'lr' }, { id: 'cranc', art: 'cranc', x: 60, y: -130, rot: 'lr' }, { id: 'medusa', art: 'medusa', x: 140, y: 30, rot: 'none' }], time: 6,
          goal: [{ k: 'moved', s: 'peix', min: 150 }, { k: 'moved', s: 'cranc', min: 100 }, { k: 'at', s: 'peix', r: [-240, -180, 240, 180] }, { k: 'at', s: 'cranc', r: [-240, -180, 240, 180] }] },
        edit: ['peix', 'cranc', 'medusa'], hats: ['flag'], pal: ['move', 'turn', 'bounce', 'say', 'costume', 'next', 'wait', 'rep', 'forever'], texts: ['Glu, glu!|¡Glu, glu!', 'Hola, peix!|¡Hola, pez!'],
        prog: '@peix flag{ } flag{ } @cranc flag{ } flag{ } @medusa flag{ } flag{ }',
        check: P => /"k":"(next|costume)"/.test(JSON.stringify(P)) ? null : "Fes que algun animal canviï de vestit (amb «vestit següent» o «posa el vestit»).|Haz que algún animal cambie de disfraz (con «disfraz siguiente» o «pon el disfraz»).",
        sol: '@peix flag{ forever{ move:5 bounce } } flag{ forever{ next wait:0.3 } } @cranc flag{ forever{ move:2 bounce } } @medusa flag{ forever{ next wait:0.6 } }' },
      { k: 'quiz', ph: 'tanca', q: 'Com pots fer que un personatge <b>es mogui i canviï de vestit</b> a ritmes diferents?|¿Cómo puedes hacer que un personaje <b>se mueva y cambie de disfraz</b> a ritmos diferentes?',
        opts: ['Amb dos guions «quan comença»: un per moure i un per als vestits|Con dos guiones «al empezar»: uno para mover y otro para los disfraces', 'Posant-ho tot en un bucle amb una espera molt llarga|Poniéndolo todo en un bucle con una espera muy larga', 'No es pot fer|No se puede hacer'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: 'Vols que el cranc vagi <b>més a poc a poc</b> que el peix. Què fas?|Quieres que el cangrejo vaya <b>más despacio</b> que el pez. ¿Qué haces?',
        opts: ['Li poso un número més petit a «mou-te»|Le pongo un número más pequeño en «muévete»', 'Li poso un número més gran a «mou-te»|Le pongo un número más grande en «muévete»', 'El programo després del peix|Lo programo después del pez'], a: 0,
        ex: "Passos més curts = més a poc a poc. L'ordre en què els programes no importa: tots comencen alhora.|Pasos más cortos = más despacio. El orden en que los programas no importa: todos empiezan a la vez." },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 4 · Projecte: l'aquari ---------- */
  { id: 'g2-4', t: "Projecte: l'aquari|Proyecto: el acuario", min: 45, proj: true, badge: 'g_aquari',
    learn: ["Un projecte gran es fa a trossos: primer la idea i el pla, després un personatge darrere l'altre.|Un proyecto grande se hace a trozos: primero la idea y el plan, después un personaje tras otro.",
      'Després de cada tros, el provem i el millorem abans de continuar.|Después de cada trozo, lo probamos y lo mejoramos antes de continuar.',
      "Amb vestits, esperes, bucles i molts guions alhora, l'aquari sembla viu.|Con disfraces, esperas, bucles y muchos guiones a la vez, el acuario parece vivo."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Hi ha 4 animals amb guions «quan comença». Quan toques la bandera verda…|Hay 4 animales con guiones «al empezar». Cuando tocas la bandera verde…',
        opts: ['…tots comencen alhora|…todos empiezan a la vez', '…comencen d’un en un|…empiezan de uno en uno', '…només es mou l’últim|…solo se mueve el último'], a: 0 },
      { k: 'quiz', ph: 'recorda', q: "L'alga s'ha de gronxar <b>tota l'estona</b> que la pantalla estigui encesa. Quin bucle fas servir?|El alga tiene que balancearse <b>todo el rato</b> que la pantalla esté encendida. ¿Qué bucle usas?",
        opts: ['Per sempre|Por siempre', 'Repeteix 3 vegades|Repite 3 veces', 'Cap: només «vestit següent»|Ninguno: solo «disfraz siguiente»'], a: 0 },
      { k: 'story', ph: 'missio', who: 'both', scene: 'moll', title: 'La gran inauguració|La gran inauguración',
        t: "Dissabte s'inaugura l'aquari del moll! La Marina té la pantalla gegant preparada, però li falta el més important: <b>l'aquari animat</b>. Ha demanat a cada programador/a de la classe que en faci un. El millor de tot: cadascú decideix com serà el seu.|¡El sábado se inaugura el acuario del muelle! Marina tiene la pantalla gigante preparada, pero le falta lo más importante: <b>el acuario animado</b>. Ha pedido a cada programador/a de la clase que haga uno. Lo mejor de todo: cada uno decide cómo será el suyo." },
      { k: 'story', ph: 'missio', who: 'numi', mood: 'think',
        t: "Un aquari amb molts animals és un projecte gran. Si ho programes tot de cop, és fàcil perdre's. Farem com els programadors de veritat: <b>pensar, planificar, construir a trossos i provar</b>.|Un acuario con muchos animales es un proyecto grande. Si lo programas todo de golpe, es fácil perderse. Haremos como los programadores de verdad: <b>pensar, planificar, construir a trozos y probar</b>." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'El projecte|El proyecto', t: 'Com es fa un projecte|Cómo se hace un proyecto', anim: 'g2plan',
          x: "1. Tens una <b>idea</b>: quins animals hi haurà? 2. Fas un <b>pla</b> en paper: què farà cada animal? 3. <b>Construeixes a trossos</b>: un animal, i després un altre. 4. <b>Proves</b> cada tros. 5. El <b>millores</b> i tornes a provar.|1. Tienes una <b>idea</b>: ¿qué animales habrá? 2. Haces un <b>plan</b> en papel: ¿qué hará cada animal? 3. <b>Construyes a trozos</b>: un animal, y después otro. 4. <b>Pruebas</b> cada trozo. 5. Lo <b>mejoras</b> y vuelves a probar." },
        { k: 'Un exemple|Un ejemplo', t: "L'aquari de mostra|El acuario de muestra",
          media: { k: 'stage', w: { bg: 'aquari', sprites: [{ id: 'alga', art: 'alga', x: -170, y: -110, size: 120, rot: 'none' }, { id: 'peix', art: 'peix', x: -60, y: 70, rot: 'lr' }, { id: 'medusa', art: 'medusa', x: 130, y: 40, rot: 'none', dir: 0 }, { id: 'cranc', art: 'cranc', x: 40, y: -135, size: 80, rot: 'lr' }] },
            prog: '@alga flag{ forever{ next wait:0.6 } } @peix flag{ forever{ move:4 bounce } } flag{ forever{ next wait:0.3 } } @medusa flag{ forever{ move:1 bounce } } flag{ forever{ next wait:0.5 } } @cranc flag{ say:"Benvinguts!|¡Bienvenidos!",2 forever{ move:2 next wait:0.2 bounce } }', time: 10 },
          x: "Aquest és l'aquari que va fer la Marina per provar la pantalla. Fixa't que <b>cada animal és un tros</b>: l'alga es gronxa, el peix neda i mou la cua (dos guions), la medusa puja i baixa a poc a poc i el cranc saluda i camina.|Este es el acuario que hizo Marina para probar la pantalla. Fíjate en que <b>cada animal es un trozo</b>: el alga se balancea, el pez nada y mueve la cola (dos guiones), la medusa sube y baja despacio y el cangrejo saluda y camina." },
        { k: 'Compte!|¡Cuidado!', t: 'Prova cada tros|Prueba cada trozo',
          media: { k: 'stage', w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -150, y: 40, rot: 'lr' }, { id: 'peix2', art: 'peix', x: -150, y: -60, rot: 'lr', name: 'Peix 2|Pez 2' }] }, prog: '@peix flag{ forever{ move:5 } } @peix2 flag{ forever{ move:5 bounce } }', time: 5 },
          x: "Mira els dos peixos: el de dalt <b>se'n va</b> perquè li falta «rebota», i el de baix torna. Si ho haguessis programat tot de cop, costaria molt trobar l'error. Per això, cada vegada que acabes un animal, <b>toca la bandera i mira'l</b>.|Mira los dos peces: el de arriba <b>se va</b> porque le falta «rebota», y el de abajo vuelve. Si lo hubieras programado todo de golpe, costaría mucho encontrar el error. Por eso, cada vez que terminas un animal, <b>toca la bandera y míralo</b>.",
          bad: 'Programo tots els animals i provo al final.|Programo todos los animales y pruebo al final.', good: 'Programo un animal, el provo i, quan funciona, passo al següent.|Programo un animal, lo pruebo y, cuando funciona, paso al siguiente.' }
      ] },
      { k: 'seq', ph: 'mans', q: 'Ordena els passos per fer el projecte de l’aquari.|Ordena los pasos para hacer el proyecto del acuario.',
        items: ["Pensar la idea: quins animals hi haurà?|Pensar la idea: ¿qué animales habrá?", 'Fer el pla en paper: què farà cada animal|Hacer el plan en papel: qué hará cada animal', "Programar el primer animal|Programar el primer animal", 'Provar-lo amb la bandera verda|Probarlo con la bandera verde', "Millorar-lo i passar a l'animal següent|Mejorarlo y pasar al animal siguiente"],
        ex: "Primer pensar i planificar, després construir a trossos, provant cada tros.|Primero pensar y planificar, después construir a trozos, probando cada trozo." },
      { k: 'unplug', ph: 'mans', ico: '📝', title: 'El pla del meu aquari|El plan de mi acuario',
        t: "Abans de programar, fes el pla en un paper (a classe ho fem amb la fitxa del pla).|Antes de programar, haz el plan en un papel (en clase lo hacemos con la ficha del plan).",
        steps: ['Dibuixa el tanc i els animals que hi posaràs (com a mínim 3).|Dibuja el tanque y los animales que pondrás (como mínimo 3).',
          "Al costat de cada animal, escriu què farà: nedar, caminar, gronxar-se, parlar…|Al lado de cada animal, escribe qué hará: nadar, caminar, balancearse, hablar…",
          'Marca quins faran servir «per sempre» i quins canviaran de vestit.|Marca cuáles usarán «por siempre» y cuáles cambiarán de disfraz.',
          "Decideix l'ordre: quin animal programaràs primer?|Decide el orden: ¿qué animal programarás primero?"],
        tip: "Un bon pla és curt i clar. No cal que sigui un dibuix perfecte!|Un buen plan es corto y claro. ¡No hace falta que sea un dibujo perfecto!" },
      { k: 'sfree', ph: 'prova', q: "Aquest és l'aquari de mostra de la Marina. Toca la bandera i, després, toca cada animal a dalt per veure els seus guions. Quins blocs reconeixes?|Este es el acuario de muestra de Marina. Toca la bandera y, después, toca cada animal arriba para ver sus guiones. ¿Qué bloques reconoces?",
        w: { bg: 'aquari', sprites: [{ id: 'alga', art: 'alga', x: -170, y: -110, size: 120, rot: 'none' }, { id: 'peix', art: 'peix', x: -60, y: 70, rot: 'lr' }, { id: 'medusa', art: 'medusa', x: 130, y: 40, rot: 'none', dir: 0 }, { id: 'cranc', art: 'cranc', x: 40, y: -135, size: 80, rot: 'lr' }] },
        prog: '@alga flag{ forever{ next wait:0.6 } } @peix flag{ forever{ move:4 bounce } } flag{ forever{ next wait:0.3 } } @medusa flag{ forever{ move:1 bounce } } flag{ forever{ next wait:0.5 } } @cranc flag{ say:"Benvinguts!|¡Bienvenidos!",2 forever{ move:2 next wait:0.2 bounce } }' },
      { k: 'sspot', ph: 'investiga', q: "En aquest aquari, la medusa <b>deixa de moure els tentacles</b> al cap d'una estona, però els altres continuen. Toca el bloc que caldria canviar.|En este acuario, la medusa <b>deja de mover los tentáculos</b> al cabo de un rato, pero los demás siguen. Toca el bloque que habría que cambiar.",
        w: { bg: 'aquari', sprites: [{ id: 'alga', art: 'alga', x: -170, y: -110, size: 120, rot: 'none' }, { id: 'medusa', art: 'medusa', x: 100, y: 30, size: 120, rot: 'none' }] },
        prog: '@alga flag{ forever{ next wait:0.6 } } @medusa flag{ rep:3!{ next wait:0.5 } }',
        ex: "«Repeteix 3 vegades» s'acaba al cap de 3 voltes. Per a una pantalla que no para, cal «per sempre».|«Repite 3 veces» se acaba al cabo de 3 vueltas. Para una pantalla que no para, hace falta «por siempre»." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Sigues un animal de l'aquari! Tria'n un i fes el seu moviment <b>per sempre</b>: el peix neda amb les mans, el cranc camina de costat, la medusa s'ajup i s'aixeca… Atura't quan diguin «Atura!».|¡Sé un animal del acuario! Elige uno y haz su movimiento <b>por siempre</b>: el pez nada con las manos, el cangrejo camina de lado, la medusa se agacha y se levanta… Párate cuando digan «¡Para!»." },
      { k: 'stage', ph: 'repte', q: "Tros 1: l'alga. Fes que es <b>gronxi tota l'estona</b> (que canviï de vestit sense parar). Només pots fer servir 3 blocs.|Trozo 1: el alga. Haz que se <b>balancee todo el rato</b> (que cambie de disfraz sin parar). Solo puedes usar 3 bloques.",
        w: { bg: 'aquari', sprites: [{ id: 'alga', art: 'alga', x: 0, y: -60, size: 170, rot: 'none' }], time: 5, goal: [{ k: 'costumes', s: 'alga', min: 8 }] },
        edit: ['alga'], hats: ['flag'], pal: ['next', 'wait', 'rep', 'forever'], max: 3,
        sol: '@alga flag{ forever{ next wait:0.5 } }',
        hint: "Per sempre { vestit següent, espera 0,5 segons }.|Por siempre { disfraz siguiente, espera 0,5 segundos }." },
      { k: 'stage', ph: 'repte', q: "Tros 2: el peix. Té dos guions buits. Fes que <b>nedi i reboti</b> amb un guió i que <b>mogui la cua</b> amb l'altre.|Trozo 2: el pez. Tiene dos guiones vacíos. Haz que <b>nade y rebote</b> con un guion y que <b>mueva la cola</b> con el otro.",
        w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: -60, y: 40, size: 110, rot: 'lr' }], time: 5, goal: [{ k: 'moved', s: 'peix', min: 400 }, { k: 'costumes', s: 'peix', min: 6 }, { k: 'at', s: 'peix', r: [-240, -180, 240, 180] }] },
        edit: ['peix'], hats: ['flag'], pal: ['move', 'bounce', 'next', 'wait', 'forever'],
        prog: '@peix flag{ } flag{ }',
        sol: '@peix flag{ forever{ move:4 bounce } } flag{ forever{ next wait:0.3 } }',
        hint: "Guió 1: per sempre { mou-te 4 passos, rebota }. Guió 2: per sempre { vestit següent, espera 0,3 }.|Guion 1: por siempre { muévete 4 pasos, rebota }. Guion 2: por siempre { disfraz siguiente, espera 0,3 }." },
      { k: 'stage', ph: 'repte', q: "Tros 3: el cranc. Primer ha de <b>dir una benvinguda</b> als visitants i, després, <b>caminar per la sorra per sempre</b>, rebotant.|Trozo 3: el cangrejo. Primero tiene que <b>decir una bienvenida</b> a los visitantes y, después, <b>caminar por la arena por siempre</b>, rebotando.",
        w: { bg: 'aquari', sprites: [{ id: 'cranc', art: 'cranc', x: -60, y: -130, size: 110, rot: 'lr' }], time: 7, goal: [{ k: 'said', s: 'cranc' }, { k: 'moved', s: 'cranc', min: 200 }, { k: 'at', s: 'cranc', r: [-240, -180, 240, 180] }] },
        edit: ['cranc'], hats: ['flag'], pal: ['say', 'move', 'bounce', 'next', 'wait', 'forever'], texts: ["Benvinguts a l'aquari!|¡Bienvenidos al acuario!", 'Hola, visitants!|¡Hola, visitantes!'],
        sol: `@cranc flag{ say:"Benvinguts a l'aquari!|¡Bienvenidos al acuario!",2 forever{ move:8 next wait:0.1 bounce } }`,
        hint: "La benvinguda va abans del bucle (només es diu una vegada). La caminada va a dins del «per sempre».|La bienvenida va antes del bucle (solo se dice una vez). El paseo va dentro del «por siempre»." },
      { k: 'screate', ph: 'crea', name: 'El meu aquari|Mi acuario',
        q: "És l'hora del teu aquari! Segueix el teu pla i programa els animals que vulguis, <b>un a un</b>, provant cada tros. Que sigui un aquari viu: molts animals alhora, bucles, vestits… i una benvinguda!|¡Es la hora de tu acuario! Sigue tu plan y programa los animales que quieras, <b>uno a uno</b>, probando cada trozo. Que sea un acuario vivo: muchos animales a la vez, bucles, disfraces… ¡y una bienvenida!",
        crit: ['Com a mínim 3 animals fan alguna cosa alhora|Como mínimo 3 animales hacen algo a la vez', 'Fas servir «per sempre» i canvis de vestit|Usas «por siempre» y cambios de disfraz', 'El peix neda sense sortir de l’escenari|El pez nada sin salir del escenario', 'Algun animal diu una benvinguda|Algún animal dice una bienvenida'],
        w: { bg: 'aquari', sprites: [{ id: 'alga', art: 'alga', x: -190, y: -110, size: 120, rot: 'none' }, { id: 'peix', art: 'peix', x: -60, y: 80, rot: 'lr' }, { id: 'medusa', art: 'medusa', x: 150, y: 50, rot: 'none' }, { id: 'cranc', art: 'cranc', x: 30, y: -135, size: 80, rot: 'lr' }, { id: 'vuit', art: 'vuit', x: -110, y: -20, size: 80, rot: 'none' }], time: 8,
          goal: [{ k: 'moved', s: 'peix', min: 150 }, { k: 'at', s: 'peix', r: [-240, -180, 240, 180] }, { k: 'said' }] },
        edit: ['alga', 'peix', 'medusa', 'cranc', 'vuit'], hats: ['flag'], pal: ['move', 'turn', 'bounce', 'say', 'think', 'costume', 'next', 'wait', 'rep', 'forever'],
        texts: ["Benvinguts a l'aquari!|¡Bienvenidos al acuario!", 'Glu, glu!|¡Glu, glu!', 'Quina aigua més fresca!|¡Qué agua más fresca!'],
        prog: '@alga flag{ } @peix flag{ } flag{ } @medusa flag{ } flag{ } @cranc flag{ } @vuit flag{ } flag{ }',
        check: P => { const s = JSON.stringify(P); const n = Object.values(P).filter(H => /"k":/.test(JSON.stringify(H))).length;
          return n < 3 ? "Programa com a mínim 3 animals: toca'ls a dalt per triar-los.|Programa como mínimo 3 animales: tócalos arriba para elegirlos." : !s.includes('"k":"forever"') ? "Fes servir algun «per sempre» perquè l'aquari no pari.|Usa algún «por siempre» para que el acuario no pare." : !/"k":"(next|costume)"/.test(s) ? 'Fes que algun animal canviï de vestit.|Haz que algún animal cambie de disfraz.' : null; },
        sol: `@alga flag{ forever{ next wait:0.6 } } @peix flag{ forever{ move:4 bounce } } flag{ forever{ next wait:0.3 } } @medusa flag{ forever{ next wait:0.5 } } @cranc flag{ say:"Benvinguts a l'aquari!|¡Bienvenidos al acuario!",2 forever{ move:2 next wait:0.2 bounce } }` },
      { k: 'quiz', ph: 'tanca', q: 'Quina és la millor manera de fer un projecte gran?|¿Cuál es la mejor manera de hacer un proyecto grande?',
        opts: ['Fer un pla i construir-lo a trossos, provant cada tros|Hacer un plan y construirlo a trozos, probando cada trozo', 'Posar tots els blocs de cop i provar al final|Poner todos los bloques de golpe y probar al final', 'Copiar el projecte d’un company/a|Copiar el proyecto de un compañero/a'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "Quin d'aquests guions fa que l'alga es gronxi <b>sense parar mai</b>?|¿Cuál de estos guiones hace que el alga se balancee <b>sin parar nunca</b>?",
        opts: ['Per sempre { vestit següent, espera 0,5 }|Por siempre { disfraz siguiente, espera 0,5 }', 'Repeteix 2 vegades { vestit següent, espera 0,5 }|Repite 2 veces { disfraz siguiente, espera 0,5 }', 'Vestit següent, vestit següent, vestit següent|Disfraz siguiente, disfraz siguiente, disfraz siguiente'], a: 0,
        ex: "«Per sempre» no s'acaba, i l'espera fa que es vegi cada vestit.|«Por siempre» no se acaba, y la espera hace que se vea cada disfraz." },
      { k: 'feel', ph: 'tanca' }
    ] }
] };
