/* Tech 3D · Nivell 2 · unitat 2 «Transformacions» (p2-1 … p2-4)
   Contingut propi de Numi (format: scripts/TECH-3D.md). Fil narratiu: l'estudi d'enginyeria de Bit rep l'encàrrec de la
   cooperativa del Molí Vell (una maqueta del seu molí de vent restaurat per al centre de visitants).
   p2-1 moure: mou(x, y, z) com a vector, a qui afecta (la instrucció o el bloc { }), grups i moviments que se sumen ·
   p2-2 girar: gira(x, y, z) en graus, el sentit positiu i el gir al voltant de l'ORIGEN (no del centre, com al Nivell 1) ·
   p2-3 l'ordre importa: de dins cap a fora, moure i girar no és commutatiu, patrons circulars i escala des de l'origen ·
   p2-4 projecte: el molí (torre, teulada, eix horitzontal i aspes girades al voltant de l'eix).
   Les opcions de m3predict porten sempre una peça de referència (l'eix, una barra grisa…): les miniatures s'enquadren soles
   i, sense referència, dues posicions diferents es veurien iguals. */
Object.assign(TBADGE, {
  p21mou: { id: 'p21mou', ico: '➡️', n: 'Mestre/a del vector|Maestro/a del vector', d: "Col·loques peces i grups al mil·límetre amb mou, i saps sumar moviments.|Colocas piezas y grupos al milímetro con mueve, y sabes sumar movimientos." },
  p22gir: { id: 'p22gir', ico: '🔄', n: 'Pilot/a de girs|Piloto/a de giros', d: "Saps girar en els tres eixos i que gira fa girar al voltant de l'origen.|Sabes girar en los tres ejes y que gira hace girar alrededor del origen." },
  p23ord: { id: 'p23ord', ico: '🧮', n: "Ordre i mètode|Orden y método", d: "Llegeixes les transformacions de dins cap a fora i fas patrons al voltant d'un centre.|Lees las transformaciones de dentro hacia fuera y haces patrones alrededor de un centro." },
  p24moli: { id: 'p24moli', ico: '🌬️', n: 'Constructor/a de molins|Constructor/a de molinos', d: "Projecte acabat: la maqueta del Molí Vell, amb l'eix i les aspes ben girats.|Proyecto terminado: la maqueta del Molino Viejo, con el eje y las aspas bien girados." }
});

COURSE_UNITS[2] = (() => {
  const B = (ca, es) => ca + '|' + es;
  // p2-1: el fanal (base, pal i bombeta soldada 3 mm), en grup; l'entrada del molí; el magatzem; l'escala
  const FAN_IN = '  cilindre(14, 3)\n  mou(0, 0, 3) cilindre(4, 40)\n  mou(0, 0, 46) esfera(12)';
  const FANAL = 'cilindre(14, 3)\nmou(0, 0, 3) cilindre(4, 40)\nmou(0, 0, 46) esfera(12)';
  const grp = (x, y, body = FAN_IN, bang = '') => `mou(${x}, ${y}, 0)${bang} {\n${body}\n}`;
  const CAMI = 'mou(-30, -50, 0) cub(60, 100, 2)';
  const ENTR = `${CAMI}\n${grp(-40, 0)}\n${grp(40, 0)}`;
  const MAG = 'mou(-50, 20, 0) cub(30, 20, 16)', MAGT = 'mou(-50, 20, 0) {\n  cub(30, 20, 16)\n  mou(-2, -2, 16) cub(34, 24, 4)\n}';
  const ESC = 'cub(30, 20, 10)\nmou(10, 0, 10) {\n  cub(20, 20, 10)\n  mou(10, 0, 10) cub(10, 20, 10)\n}';
  // p2-2: el suport de l'eix, la creu i la rosa dels vents
  const SUP = 'mou(0, 0, 10) cub(20, 20, 20, centrat)\nmou(0, 0, 14) gira(-90, 0, 0) cilindre(8, 30)';
  const BAR = 'mou(0, 0, 2) cub(60, 8, 4, centrat)', CREU = BAR + '\nmou(0, 0, 2) gira(0, 0, 90) cub(60, 8, 4, centrat)';
  const ROSA = CREU + '\nmou(0, 0, 3) gira(0, 0, 45) cub(40, 6, 6, centrat)\nmou(0, 0, 3) gira(0, 0, 135) cub(40, 6, 6, centrat)';
  const FLOR = 'cilindre(10, 4)\nmou(0, 0, 2) cub(50, 10, 4, centrat)\nmou(0, 0, 2) gira(0, 0, 60) cub(50, 10, 4, centrat)\nmou(0, 0, 2) gira(0, 0, 120) cub(50, 10, 4, centrat)';
  // p2-3: l'aspa al voltant de l'eix i els patrons; la referència grisa de les prediccions
  const HUB = 'cilindre(14, 10)', ASPA = 'mou(5, -4, 0) cub(25, 8, 6)';
  const pat = angs => HUB + angs.map(a => `\ngira(0, 0, ${a}) ${ASPA}`).join('');
  const PAT1 = pat([0]), PAT4 = pat([0, 90, 180, 270]), PAT3 = pat([0, 120, 240]);
  const PAT4X = HUB + '\ngira(0, 0, 0) ' + ASPA + '\ngira(0, 0, 90) ' + ASPA + '\nmou(5, -4, 0)! gira(0, 0, 180) cub(25, 8, 6)\ngira(0, 0, 270) ' + ASPA;
  const SOL5 = 'cilindre(16, 6)' + [0, 72, 144, 216, 288].map(a => `\ngira(0, 0, ${a}) mou(6, -4, 0) cub(22, 8, 4)`).join('');
  const REF = 'cilindre(8, 20)\ncolor("gris") mou(30, -5, 0) cub(10)';
  const RA = REF + '\ngira(0, 0, 90) mou(30, -5, 0) cub(10)', RB = REF + '\nmou(30, -5, 0) gira(0, 0, 90) cub(10)', RC = REF + '\ngira(0, 0, 180) mou(30, -5, 0) cub(10)';
  // p2-4: el molí (torre, teulada, eix i dues aspes en creu), peça a peça
  const TR = 'con(40, 70, 28)\nmou(0, 0, 70) con(34, 22)', EIX = '\nmou(0, -12, 60) gira(90, 0, 0) cilindre(8, 12)';
  const A1 = '\nmou(0, -22, 60) gira(0, 45, 0) cub(80, 3, 8, centrat)', A2 = '\nmou(0, -22, 60) gira(0, -45, 0) cub(80, 3, 8, centrat)';
  const M2 = TR + EIX, M3 = M2 + A1, MOLI = M3 + A2;
  const MOLI6 = M2 + [30, 90, 150].map(a => `\nmou(0, -22, 60) gira(0, ${a}, 0) cub(80, 3, 8, centrat)`).join('');
  const MOLIC = B('// torre\ncon(40, 70, 28)\n// teulada\nmou(0, 0, 70) con(34, 22)\n// eix\nmou(0, -12, 60) gira(90, 0, 0) cilindre(8, 12)\n// aspes\nmou(0, -22, 60) gira(0, 45, 0) cub(80, 3, 8, centrat)\nmou(0, -22, 60) gira(0, -45, 0) cub(80, 3, 8, centrat)',
    '// torre\ncon(40, 70, 28)\n// tejado\nmou(0, 0, 70) con(34, 22)\n// eje\nmou(0, -12, 60) gira(90, 0, 0) cilindre(8, 12)\n// aspas\nmou(0, -22, 60) gira(0, 45, 0) cub(80, 3, 8, centrat)\nmou(0, -22, 60) gira(0, -45, 0) cub(80, 3, 8, centrat)');
  const REFB = 'cilindre(10, 20)\ncolor("gris") mou(5, -3, 0) cub(30, 6, 4)', bl = a => `\ngira(0, 0, ${a}) mou(5, -3, 0) cub(30, 6, 4)`;
  const BLK1 = ['cub', 'cil', 'esf', 'mou'], BLK2 = ['cub', 'cil', 'esf', 'mou', 'gira'], BLK3 = ['cub', 'cil', 'con', 'mou', 'gira', 'color'];
  return {
  t: 'Transformacions|Transformaciones', d: 'Moure, girar i combinar amb codi|Mover, girar y combinar con código', color: '#D63F8C',
  s: [
    /* ---------- Sessió 1 · Moure ---------- */
    { id: 'p2-1', t: 'Moure|Mover', min: 45, badge: 'p21mou',
      learn: ['mou(x, y, z) desplaça la forma o el bloc { } que el segueix: x cap a la dreta, y cap al fons i z amunt; els números negatius van al revés.|mueve(x, y, z) desplaza la forma o el bloque { } que le sigue: x hacia la derecha, y hacia el fondo y z hacia arriba; los números negativos van al revés.',
        "Un mou davant d'un bloc { } desplaça tot el grup junt: les peces de dins mantenen les distàncies entre elles.|Un mueve delante de un bloque { } desplaza todo el grupo junto: las piezas de dentro mantienen las distancias entre ellas.",
        'Dos mou seguits se sumen: mou(10, 0, 0) mou(0, 20, 0) és el mateix que mou(10, 20, 0).|Dos mueve seguidos se suman: mueve(10, 0, 0) mueve(0, 20, 0) es lo mismo que mueve(10, 20, 0).'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Una base fa <b>8 mm</b> d\'alt. Quina z ha de tenir el mou d\'una peça que va just a sobre?|Una base mide <b>8 mm</b> de alto. ¿Qué z tiene que tener el mueve de una pieza que va justo encima?', opts: ['8|8', '4|4', '16|16'], a: 0,
          ex: 'La peça de sobre comença on acaba la base: a z = 8.|La pieza de encima empieza donde acaba la base: en z = 8.' },
        { k: 'quiz', ph: 'recorda', q: 'On és el centre d\'un <code>cub(20, centrat)</code>?|¿Dónde está el centro de un <code>cubo(20, centrado)</code>?', opts: ["A l'origen (0, 0, 0)|En el origen (0, 0, 0)", 'A (10, 10, 10)|En (10, 10, 10)', 'A (20, 20, 20)|En (20, 20, 20)'], a: 0 },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: 'La maqueta del Molí Vell|La maqueta del Molino Viejo',
          t: "La cooperativa del <b>Molí Vell</b> ha restaurat el seu molí de vent i ens encarrega una <b>maqueta</b> per al centre de visitants: el molí, el camí d'entrada amb fanals i el magatzem. Per fer-la haurem de dominar les <b>transformacions</b>: moure, girar i combinar-les. Avui comencem per <b>moure</b>: col·locar cada peça al mil·límetre i moure grups sencers sense desmuntar-los.|La cooperativa del <b>Molino Viejo</b> ha restaurado su molino de viento y nos encarga una <b>maqueta</b> para el centro de visitantes: el molino, el camino de entrada con farolas y el almacén. Para hacerla tendremos que dominar las <b>transformaciones</b>: mover, girar y combinarlas. Hoy empezamos por <b>mover</b>: colocar cada pieza al milímetro y mover grupos enteros sin desmontarlos." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Translació|Traslación', t: 'mou és una fletxa|mueve es una flecha', anim: 'p21vec',
            x: "A matemàtiques, moure una figura sense girar-la ni canviar-ne la mida és una <b>translació</b>. Tots els punts de la peça es desplacen amb la mateixa fletxa, el <b>vector</b> (x, y, z): <code>mou(30, 20, 0)</code> porta la peça 30 mm cap a la dreta i 20 mm cap al fons.|En matemáticas, mover una figura sin girarla ni cambiar su tamaño es una <b>traslación</b>. Todos los puntos de la pieza se desplazan con la misma flecha, el <b>vector</b> (x, y, z): <code>mueve(30, 20, 0)</code> lleva la pieza 30 mm hacia la derecha y 20 mm hacia el fondo." },
          { k: 'Signes|Signos', t: 'Els números negatius|Los números negativos', media: { k: 'model', prog: 'color("gris") cub(20)\nmou(-40, 0, 0) color("blau") cub(20)\nmou(0, -40, 0) color("taronja") cub(20)\nmou(0, 0, 30) color("verd") cub(20)' },
            x: "Cada número diu cap on i quant: <b>x</b> positiva, a la dreta (negativa, a l'esquerra); <b>y</b> positiva, cap al fons (negativa, cap a tu); <b>z</b> positiva, amunt. El cub gris és a l'origen; el blau s'ha mogut −40 en x, el taronja −40 en y i el verd, 30 amunt.|Cada número dice hacia dónde y cuánto: <b>x</b> positiva, a la derecha (negativa, a la izquierda); <b>y</b> positiva, hacia el fondo (negativa, hacia ti); <b>z</b> positiva, hacia arriba. El cubo gris está en el origen; el azul se ha movido −40 en x, el naranja −40 en y y el verde, 30 hacia arriba.",
            tip: "A la vista 3D, la línia vermella és l'eix x i la verda, l'eix y: es creuen a l'origen.|En la vista 3D, la línea roja es el eje x y la verde, el eje y: se cruzan en el origen." },
          { k: 'Abast|Alcance', t: 'A qui afecta un mou?|¿A quién afecta un mueve?', anim: 'p21scope',
            x: "Un <code>mou</code> només afecta <b>el que té just després</b>: la forma de la mateixa línia o, si hi ha claus, <b>tot el bloc { }</b>. Les instruccions de les línies següents no es mouen. Als blocs ho veus clar: el que es mou és a dins del bloc mou.|Un <code>mueve</code> solo afecta a <b>lo que tiene justo después</b>: la forma de la misma línea o, si hay llaves, <b>todo el bloque { }</b>. Las instrucciones de las líneas siguientes no se mueven. En los bloques lo ves claro: lo que se mueve está dentro del bloque mueve.",
            bad: 'Un mou mou totes les formes que vénen després.|Un mueve mueve todas las formas que vienen después.', good: 'Un mou només mou la forma o el bloc { } que té just després.|Un mueve solo mueve la forma o el bloque { } que tiene justo después.' },
          { k: 'Grups|Grupos', t: 'Fes la peça a l\'origen i després col·loca-la|Haz la pieza en el origen y después colócala', media: { k: 'model', prog: `${grp(-30, 0)}\n${grp(30, 0)}` },
            x: "Aquest fanal té tres peces dins d'un bloc. Els mou de dins són <b>relatius al grup</b>: el pal sempre comença 3 mm sobre la base, sigui on sigui el fanal. El mou de fora el col·loca sencer. Així treballen els enginyers: dissenyen cada peça a l'origen i després la porten al seu lloc.|Esta farola tiene tres piezas dentro de un bloque. Los mueve de dentro son <b>relativos al grupo</b>: el palo siempre empieza 3 mm sobre la base, esté donde esté la farola. El mueve de fuera la coloca entera. Así trabajan los ingenieros: diseñan cada pieza en el origen y después la llevan a su sitio." },
          { k: 'Sumar|Sumar', t: 'Moviments encadenats|Movimientos encadenados', anim: 'p21chain',
            x: "Si una peça té dos <code>mou</code> seguits (o un mou dins d'un bloc que ja té un mou), els desplaçaments <b>se sumen</b>: x amb x, y amb y i z amb z. La bombeta d'un fanal a <code>mou(30, 0, 0)</code> acaba a (30, 0, 46).|Si una pieza tiene dos <code>mueve</code> seguidos (o un mueve dentro de un bloque que ya tiene un mueve), los desplazamientos <b>se suman</b>: x con x, y con y y z con z. La bombilla de una farola en <code>mueve(30, 0, 0)</code> acaba en (30, 0, 46)." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🗺️', title: 'Moure amb fletxes|Mover con flechas', t: 'Per parelles, amb la fitxa de la quadrícula (cada quadre = 10 mm), un quadrat de paper i les targetes «mou»:|Por parejas, con la ficha de la cuadrícula (cada cuadro = 10 mm), un cuadrado de papel y las tarjetas «mueve»:',
          steps: ["Poseu el quadrat amb una cantonada a l'origen de la quadrícula.|Poned el cuadrado con una esquina en el origen de la cuadrícula.", 'Gireu tres targetes i apliqueu-les una darrere l\'altra. Apunteu on acaba la cantonada.|Girad tres tarjetas y aplicadlas una detrás de otra. Apuntad dónde acaba la esquina.', 'Sumeu les tres targetes: quin mou únic fa el mateix? Comproveu-ho tornant a començar.|Sumad las tres tarjetas: ¿qué mueve único hace lo mismo? Comprobadlo volviendo a empezar.', 'Repte: trieu dues targetes que facin tornar el quadrat a l\'origen.|Reto: elegid dos tarjetas que hagan volver el cuadrado al origen.'],
          tip: 'Si dues targetes es compensen (com +20 i −20), la suma és zero.|Si dos tarjetas se compensan (como +20 y −20), la suma es cero.' },
        { k: 'm3predict', ph: 'prova', q: 'El segon cilindre té <b>dos mou</b> seguits. Quin model fa?|El segundo cilindro tiene <b>dos mueve</b> seguidos. ¿Qué modelo hace?', prog: 'cilindre(30, 10)\nmou(0, 0, 10) mou(0, 0, 10) cilindre(20, 10)',
          opts: [{ prog: 'cilindre(30, 10)\nmou(0, 0, 10) mou(0, 0, 10) cilindre(20, 10)' }, { prog: 'cilindre(30, 10)\nmou(0, 0, 10) cilindre(20, 10)' }, { prog: 'cilindre(30, 10)\nmou(0, 0, 30) cilindre(20, 10)' }], a: 0,
          ex: "Els dos mou se sumen: 10 + 10 = 20. El cilindre petit comença a z = 20 i, com que el gran acaba a 10, queda un buit de 10 mm: flota.|Los dos mueve se suman: 10 + 10 = 20. El cilindro pequeño empieza en z = 20 y, como el grande acaba en 10, queda un hueco de 10 mm: flota." },
        { k: 'm3predict', ph: 'investiga', q: 'Fixa\'t bé en les <b>claus</b>. Quin model fa?|Fíjate bien en las <b>llaves</b>. ¿Qué modelo hace?', prog: grp(30, 0, '  cilindre(14, 3)\n  mou(0, 0, 3) cilindre(4, 40)') + '\nmou(0, 0, 46) esfera(12)',
          opts: [{ prog: grp(30, 0, '  cilindre(14, 3)\n  mou(0, 0, 3) cilindre(4, 40)') + '\nmou(0, 0, 46) esfera(12)' }, { prog: grp(30, 0) }, { prog: 'mou(30, 0, 0) cilindre(14, 3)\nmou(0, 0, 3) cilindre(4, 40)\nmou(0, 0, 46) esfera(12)' }], a: 0,
          ex: "La bombeta és fora de les claus: el mou(30, 0, 0) del grup no l'afecta i es queda a x = 0, flotant al costat del fanal.|La bombilla está fuera de las llaves: el mueve(30, 0, 0) del grupo no la afecta y se queda en x = 0, flotando al lado de la farola." },
        { k: 'm3spot', ph: 'investiga', q: "A l'entrada del molí, una bombeta ha caigut a terra. Toca la instrucció que està malament.|En la entrada del molino, una bombilla se ha caído al suelo. Toca la instrucción que está mal.", prog: `${CAMI}\n${grp(-40, 0, '  cilindre(14, 3)\n  mou(0, 0, 3) cilindre(4, 40)\n  mou(0, 46, 0)! esfera(12)')}\n${grp(40, 0)}`, target: ENTR,
          ex: "El 46 és a la posició de la y: la bombeta s'ha desplaçat 46 mm cap al fons en lloc de pujar. Ha de ser mou(0, 0, 46).|El 46 está en la posición de la y: la bombilla se ha desplazado 46 mm hacia el fondo en lugar de subir. Tiene que ser mueve(0, 0, 46)." },
        { k: 'm3spot', ph: 'investiga', q: "Ara només es veu <b>un fanal</b>, però al programa n'hi ha dos. Quina instrucció està malament?|Ahora solo se ve <b>una farola</b>, pero en el programa hay dos. ¿Qué instrucción está mal?", prog: `${CAMI}\n${grp(-40, 0)}\n${grp(-40, 0, FAN_IN, '!')}`, target: ENTR,
          ex: "Els dos grups es mouen a x = −40: el segon fanal és just a sobre del primer. Ha d'anar a l'altra banda del camí, a x = 40 (positiu).|Los dos grupos se mueven a x = −40: la segunda farola está justo encima de la primera. Tiene que ir al otro lado del camino, a x = 40 (positivo)." },
        { k: 'move', ph: 'pausa', title: 'Vectors amb el cos|Vectores con el cuerpo', secs: 40, t: "Dempeus, tu ets la peça. <b>mou(2, 0, 0)</b>: dues passes a la dreta. <b>mou(0, 1, 0)</b>: una passa endavant. <b>mou(0, 0, 1)</b>: de puntetes. Ara <b>mou(−2, −1, 0)</b>: has tornat a l'origen?|De pie, tú eres la pieza. <b>mueve(2, 0, 0)</b>: dos pasos a la derecha. <b>mueve(0, 1, 0)</b>: un paso adelante. <b>mueve(0, 0, 1)</b>: de puntillas. Ahora <b>mueve(−2, −1, 0)</b>: ¿has vuelto al origen?" },
        { k: 'm3code', ph: 'repte', q: "<b>El magatzem:</b> porta la caixa fins al fantasma. Fes servir la vista de dalt per llegir-ne la posició.|<b>El almacén:</b> lleva la caja hasta el fantasma. Usa la vista de arriba para leer su posición.", start: 'cub(30, 20, 16)', blocks: BLK1, target: MAG,
          checks: [{ k: 'match', target: MAG, th: 0.95, t: 'És exactament on és el fantasma|Está exactamente donde está el fantasma' }, { k: 'uses', b: 'mou' }],
          hint: "El fantasma és a l'esquerra de l'origen (x negativa: −50) i cap al fons (y positiva: 20). No cal pujar-lo.|El fantasma está a la izquierda del origen (x negativa: −50) y hacia el fondo (y positiva: 20). No hace falta subirlo.", sol: MAG },
        { k: 'm3code', ph: 'repte', q: "<b>El fanal:</b> porta el fanal sencer fins al fantasma, a (40, −30, 0). El més net és un sol mou davant d'un bloc { } amb les tres peces a dins.|<b>La farola:</b> lleva la farola entera hasta el fantasma, a (40, −30, 0). Lo más limpio es un solo mueve delante de un bloque { } con las tres piezas dentro.", start: FANAL, blocks: BLK1, target: grp(40, -30),
          checks: [{ k: 'match', target: grp(40, -30), th: 0.92, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'one' }],
          hint: "Afegeix un bloc mou a dalt de tot i, amb la fletxa ↑, fica-hi les tres peces una a una. Els mou de dins no s'han de tocar.|Añade un bloque mueve arriba del todo y, con la flecha ↑, mete dentro las tres piezas una a una. Los mueve de dentro no hay que tocarlos.", sol: grp(40, -30) },
        { k: 'm3code', ph: 'repte', q: "<b>Dos fanals:</b> afegeix-ne un segon, igual, a l'altra banda: a (−40, −30, 0).|<b>Dos farolas:</b> añade una segunda, igual, al otro lado: a (−40, −30, 0).", start: grp(40, -30), blocks: BLK1, target: `${grp(40, -30)}\n${grp(-40, -30)}`,
          checks: [{ k: 'match', target: `${grp(40, -30)}\n${grp(-40, -30)}`, th: 0.92, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'count', min: 6 }],
          hint: 'Toca el bloc mou del fanal i prem «Duplica». Al duplicat, canvia només la x per −40.|Toca el bloque mueve de la farola y pulsa «Duplica». En el duplicado, cambia solo la x por −40.', sol: `${grp(40, -30)}\n${grp(-40, -30)}` },
        { k: 'm3code', ph: 'repte', q: "<b>El teulat del magatzem:</b> dins del bloc, afegeix una placa de <b>34 × 24 × 4 mm</b> a sobre de la caixa que sobresurti <b>2 mm</b> per cada costat.|<b>El tejado del almacén:</b> dentro del bloque, añade una placa de <b>34 × 24 × 4 mm</b> encima de la caja que sobresalga <b>2 mm</b> por cada lado.", start: 'mou(-50, 20, 0) {\n  cub(30, 20, 16)\n}', blocks: BLK1, target: MAGT,
          checks: [{ k: 'match', target: MAGT, th: 0.92, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'one' }, { k: 'count', t: 'box', min: 2, txt: 'Hi ha la caixa i el teulat|Están la caja y el tejado' }],
          hint: "Dins del bloc, els números són relatius a la caixa: per sobresortir 2 mm, el teulat comença a x = −2 i y = −2, i a z = 16, on acaba la caixa.|Dentro del bloque, los números son relativos a la caja: para sobresalir 2 mm, el tejado empieza en x = −2 e y = −2, y en z = 16, donde acaba la caja.", sol: MAGT },
        { k: 'm3code', ph: 'repte', extra: true, q: "<b>L'escala del molí:</b> fes els tres graons del fantasma. Cada graó és 10 mm més estret i es mou <b>10 mm a la dreta i 10 amunt</b> respecte de l'anterior: prova de fer-ho amb blocs niats.|<b>La escalera del molino:</b> haz los tres peldaños del fantasma. Cada peldaño es 10 mm más estrecho y se mueve <b>10 mm a la derecha y 10 hacia arriba</b> respecto del anterior: prueba a hacerlo con bloques anidados.", start: 'cub(30, 20, 10)', blocks: BLK1, target: ESC,
          checks: [{ k: 'match', target: ESC, th: 0.92, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'one' }, { k: 'size', ax: 'z', v: 30 }],
          hint: "Dins d'un mou(10, 0, 10) hi va el segon graó i, dins d'aquest mateix bloc, un altre mou(10, 0, 10) amb el tercer: els moviments se sumen i el tercer acaba a (20, 0, 20).|Dentro de un mueve(10, 0, 10) va el segundo peldaño y, dentro de ese mismo bloque, otro mueve(10, 0, 10) con el tercero: los movimientos se suman y el tercero acaba en (20, 0, 20).", sol: ESC },
        { k: 'm3free', ph: 'crea', q: "<b>L'entrada del molí.</b> Dissenya-la al teu gust: un camí o una plaça i almenys <b>dos objectes iguals</b> (fanals, bancs, arbres…), cadascun fet a l'origen dins d'un bloc { } i col·locat amb un sol mou.|<b>La entrada del molino.</b> Diséñala a tu gusto: un camino o una plaza y al menos <b>dos objetos iguales</b> (farolas, bancos, árboles…), cada uno hecho en el origen dentro de un bloque { } y colocado con un solo mueve.",
          name: "L'entrada del molí|La entrada del molino", blocks: ['cub', 'cil', 'esf', 'con', 'mou', 'color'],
          crit: ['Un camí o una plaça com a base|Un camino o una plaza como base', "Almenys dos grups iguals, cadascun amb un mou davant d'un bloc { }|Al menos dos grupos iguales, cada uno con un mueve delante de un bloque { }", 'Tot recolza a la placa o a sobre d\'una altra peça|Todo se apoya en la placa o encima de otra pieza'],
          checks: [{ k: 'count', min: 5 }, { k: 'uses', b: 'mou' }, { k: 'onplate' }], sol: ENTR },
        { k: 'quiz', ph: 'tanca', q: '<code>mou(10, 0, 0) mou(0, 20, 0) cub(5)</code> és el mateix que…|<code>mueve(10, 0, 0) mueve(0, 20, 0) cubo(5)</code> es lo mismo que…', opts: ['<code>mou(10, 20, 0) cub(5)</code>|<code>mueve(10, 20, 0) cubo(5)</code>', '<code>mou(10, 0, 0) cub(5)</code>|<code>mueve(10, 0, 0) cubo(5)</code>', '<code>mou(30, 0, 0) cub(5)</code>|<code>mueve(30, 0, 0) cubo(5)</code>'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'A <code>mou(0, 0, 10) { cub(10) esfera(10) }</code> i després <code>cub(10)</code>, quantes formes puja el mou?|En <code>mueve(0, 0, 10) { cubo(10) esfera(10) }</code> y después <code>cubo(10)</code>, ¿cuántas formas sube el mueve?', opts: ['2: les de dins de les claus|2: las de dentro de las llaves', '3: totes|3: todas', '1: només la primera|1: solo la primera'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* ---------- Sessió 2 · Girar ---------- */
    { id: 'p2-2', t: 'Girar|Girar', min: 45, badge: 'p22gir',
      learn: ["gira(x, y, z) fa girar la forma o el bloc que el segueix tants graus al voltant dels eixos x, y i z; un angle positiu va en sentit contrari a les agulles del rellotge, mirant des de la punta de l'eix.|gira(x, y, z) hace girar la forma o el bloque que le sigue tantos grados alrededor de los ejes x, y y z; un ángulo positivo va en sentido contrario a las agujas del reloj, mirando desde la punta del eje.",
        "gira sempre fa girar al voltant de l'origen: si la peça no hi és, fa un arc al seu voltant, no gira sobre si mateixa.|gira siempre hace girar alrededor del origen: si la pieza no está ahí, hace un arco a su alrededor, no gira sobre sí misma.",
        'Per tombar un cilindre es gira en x o en y; per girar una peça sobre si mateixa, la centro a l\'origen, la giro i després la moc.|Para tumbar un cilindro se gira en x o en y; para girar una pieza sobre sí misma, la centro en el origen, la giro y después la muevo.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Quina fletxa és <code>mou(-20, 0, 10)</code>?|¿Qué flecha es <code>mueve(-20, 0, 10)</code>?', opts: ['20 mm a l\'esquerra i 10 mm amunt|20 mm a la izquierda y 10 mm hacia arriba', '20 mm a la dreta i 10 mm avall|20 mm a la derecha y 10 mm hacia abajo', '20 mm cap al fons i 10 mm amunt|20 mm hacia el fondo y 10 mm hacia arriba'], a: 0 },
        { k: 'm3predict', ph: 'recorda', q: 'Quin model fa aquest programa?|¿Qué modelo hace este programa?', prog: grp(30, 0),
          opts: [{ prog: grp(30, 0) }, { prog: 'mou(30, 0, 0) cilindre(14, 3)\nmou(0, 0, 3) cilindre(4, 40)\nmou(0, 0, 46) esfera(12)' }, { prog: grp(30, 0, '  cilindre(14, 3)\n  mou(0, 0, 3) cilindre(4, 40)\n  mou(0, 0, 66) esfera(12)') }], a: 0,
          ex: 'Les tres peces són dins del bloc: el mou(30, 0, 0) les porta juntes i el fanal queda sencer.|Las tres piezas están dentro del bloque: el mueve(30, 0, 0) las lleva juntas y la farola queda entera.' },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: 'Les peces que giren|Las piezas que giran',
          t: "Al molí hi ha peces que no van rectes: l'<b>eix</b> de les aspes està ajagut i les <b>aspes</b> fan una creu inclinada. Amb el ratolí les giraríem a ull; amb codi les girarem amb angles exactes. Però compte, enginyers: al nostre llenguatge, com a l'OpenSCAD de veritat, <b>gira</b> no fa girar la peça sobre el seu centre… Avui descobrirem al voltant de quin punt gira.|En el molino hay piezas que no van rectas: el <b>eje</b> de las aspas está tumbado y las <b>aspas</b> hacen una cruz inclinada. Con el ratón las giraríamos a ojo; con código las giraremos con ángulos exactos. Pero cuidado, ingenieros: en nuestro lenguaje, como en el OpenSCAD de verdad, <b>gira</b> no hace girar la pieza sobre su centro… Hoy descubriremos alrededor de qué punto gira." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Angles|Ángulos', t: 'gira(x, y, z): graus al voltant de cada eix|gira(x, y, z): grados alrededor de cada eje', anim: 'p22axes',
            x: "Cada número és un angle en <b>graus</b> al voltant d'un eix: 90 és un quart de volta; 180, mitja volta; 360, una volta sencera. Un angle <b>positiu</b> gira en sentit <b>contrari a les agulles del rellotge</b> quan l'eix t'apunta a tu. El més habitual és <code>gira(0, 0, a)</code>: girar sobre la placa, vist des de dalt.|Cada número es un ángulo en <b>grados</b> alrededor de un eje: 90 es un cuarto de vuelta; 180, media vuelta; 360, una vuelta entera. Un ángulo <b>positivo</b> gira en sentido <b>contrario a las agujas del reloj</b> cuando el eje te apunta a ti. Lo más habitual es <code>gira(0, 0, a)</code>: girar sobre la placa, visto desde arriba.",
            tip: "Truc de la mà dreta: el polze apunta cap a l'eix positiu i els altres dits es dobleguen en el sentit dels angles positius.|Truco de la mano derecha: el pulgar apunta hacia el eje positivo y los otros dedos se doblan en el sentido de los ángulos positivos." },
          { k: "L'origen|El origen", t: "S'hi gira al voltant de l'origen|Se gira alrededor del origen", anim: 'p22orbit',
            x: "Al Nivell 1, cada peça girava sobre el seu centre. Aquí, com a OpenSCAD, <code>gira</code> fa girar <b>al voltant de l'origen</b>. Si la peça és lluny, en girar fa un <b>arc</b>, com una cadira de sínia. Si la peça toca l'origen, sembla que giri «per una cantonada».|En el Nivel 1, cada pieza giraba sobre su centro. Aquí, como en OpenSCAD, <code>gira</code> hace girar <b>alrededor del origen</b>. Si la pieza está lejos, al girar hace un <b>arco</b>, como una silla de noria. Si la pieza toca el origen, parece que gire «por una esquina».",
            bad: 'gira fa girar la peça sobre el seu propi centre.|gira hace girar la pieza sobre su propio centro.', good: "gira fa girar la peça al voltant de l'origen (0, 0, 0).|gira hace girar la pieza alrededor del origen (0, 0, 0)." },
          { k: 'Exemple|Ejemplo', t: 'La mateixa barra, tres angles|La misma barra, tres ángulos', media: { k: 'model', prog: 'color("gris") cub(40, 6, 6)\ngira(0, 0, 45) color("taronja") cub(40, 6, 6)\ngira(0, 0, 90) cub(40, 6, 6)' },
            x: "Les tres barres són <code>cub(40, 6, 6)</code>, amb una cantonada a l'origen. La grisa no gira; la taronja gira 45° i la rosa, 90°: ara apunta cap al fons (eix y). Totes giren al voltant de la cantonada que és a l'origen, com un ventall.|Las tres barras son <code>cubo(40, 6, 6)</code>, con una esquina en el origen. La gris no gira; la naranja gira 45° y la rosa, 90°: ahora apunta hacia el fondo (eje y). Todas giran alrededor de la esquina que está en el origen, como un abanico." },
          { k: 'Tombar|Tumbar', t: 'Girs en x i en y: tombar peces|Giros en x y en y: tumbar piezas', media: { k: 'model', prog: 'mou(0, 0, 5) gira(0, 90, 0) cilindre(10, 40)\nmou(0, 20, 5) gira(-90, 0, 0) color("blau") cilindre(10, 40)' },
            x: "Un cilindre neix dret (eix z). Per <b>ajaure'l</b>, cal girar-lo en x o en y: <code>gira(0, 90, 0)</code> el tomba cap a x positiva i <code>gira(-90, 0, 0)</code>, cap a y positiva. Com que gira al voltant de l'origen, mig cilindre queda sota la placa: el pugem amb un mou de la meitat del diàmetre.|Un cilindro nace de pie (eje z). Para <b>tumbarlo</b>, hay que girarlo en x o en y: <code>gira(0, 90, 0)</code> lo tumba hacia x positiva y <code>gira(-90, 0, 0)</code>, hacia y positiva. Como gira alrededor del origen, medio cilindro queda bajo la placa: lo subimos con un mueve de la mitad del diámetro." },
          { k: 'Sobre si mateixa|Sobre sí misma', t: 'La recepta: centra, gira i mou|La receta: centra, gira y mueve', media: { k: 'model', prog: 'mou(-30, 0, 10) cub(20, centrat)\nmou(30, 0, 10) gira(0, 0, 45) cub(20, centrat)' },
            x: "Per girar una peça sobre el seu centre: la fas <b>centrada</b> (el centre a l'origen), la <b>gires</b> i després la <b>mous</b> al seu lloc. S'escriu al revés de com passa: <code>mou(30, 0, 10) gira(0, 0, 45) cub(20, centrat)</code>. Per què? Ho descobrirem a la sessió següent!|Para girar una pieza sobre su centro: la haces <b>centrada</b> (el centro en el origen), la <b>giras</b> y después la <b>mueves</b> a su sitio. Se escribe al revés de como pasa: <code>mueve(30, 0, 10) gira(0, 0, 45) cubo(20, centrado)</code>. ¿Por qué? ¡Lo descubriremos en la sesión siguiente!" }
        ] },
        { k: 'unplug', ph: 'mans', ico: '📌', title: "El paper que gira|El papel que gira", t: 'Per parelles, amb la fitxa de la quadrícula, un full de paper vegetal (o un acetat) i un llapis:|Por parejas, con la ficha de la cuadrícula, una hoja de papel vegetal (o un acetato) y un lápiz:',
          steps: ["Dibuixeu una barra al paper vegetal, a sobre de la quadrícula, de (20, 0) a (40, 10).|Dibujad una barra en el papel vegetal, encima de la cuadrícula, de (20, 0) a (40, 10).", "Clavant la punta del llapis a l'origen, gireu el paper vegetal un quart de volta en sentit contrari a les agulles del rellotge. On ha anat a parar la barra?|Clavando la punta del lápiz en el origen, girad el papel vegetal un cuarto de vuelta en sentido contrario a las agujas del reloj. ¿Dónde ha ido a parar la barra?", "Torneu a començar, però ara clavant el llapis al centre de la barra. Què canvia?|Volved a empezar, pero ahora clavando el lápiz en el centro de la barra. ¿Qué cambia?", 'Apunteu les dues posicions finals a la fitxa i compareu-les.|Apuntad las dos posiciones finales en la ficha y comparadlas.'],
          tip: "El llapis és l'eix de gir: el codi sempre el clava a l'origen.|El lápiz es el eje de giro: el código siempre lo clava en el origen." },
        { k: 'm3predict', ph: 'prova', q: 'La barra grisa no gira. <b>Com queda la rosa?</b>|La barra gris no gira. <b>¿Cómo queda la rosa?</b>', prog: 'color("gris") cub(40, 10, 4)\ngira(0, 0, 90) cub(40, 10, 4)',
          opts: [{ prog: 'color("gris") cub(40, 10, 4)\ngira(0, 0, 90) cub(40, 10, 4)' }, { prog: 'color("gris") cub(40, 10, 4)\nmou(15, -15, 0) cub(10, 40, 4)' }, { prog: 'color("gris") cub(40, 10, 4)\ngira(0, 0, 180) cub(40, 10, 4)' }], a: 0,
          ex: "La rosa gira 90° al voltant de l'origen, que és a la seva cantonada: fa una L amb la grisa. Si girés sobre el seu centre, faria una creu.|La rosa gira 90° alrededor del origen, que está en su esquina: hace una L con la gris. Si girara sobre su centro, haría una cruz." },
        { k: 'm3predict', ph: 'investiga', q: "Una sínia: l'eix al mig, una cabina grisa i una de rosa dins d'un bloc girat. <b>On queda la rosa?</b>|Una noria: el eje en medio, una cabina gris y una rosa dentro de un bloque girado. <b>¿Dónde queda la rosa?</b>", prog: 'cilindre(10, 20)\ncolor("gris") mou(30, -5, 0) cub(10)\ngira(0, 0, 90) {\n  mou(30, -5, 0) cub(10)\n}',
          opts: [{ prog: 'cilindre(10, 20)\ncolor("gris") mou(30, -5, 0) cub(10)\ngira(0, 0, 90) {\n  mou(30, -5, 0) cub(10)\n}' }, { prog: 'cilindre(10, 20)\ncolor("gris") mou(30, -5, 0) cub(10)\ngira(0, 0, 180) {\n  mou(30, -5, 0) cub(10)\n}' }, { prog: 'cilindre(10, 20)\ncolor("gris") mou(30, -5, 0) cub(10)\ngira(0, 0, 45) {\n  mou(30, -5, 0) cub(10)\n}' }], a: 0,
          ex: "El bloc gira 90° al voltant de l'origen, on és l'eix: la cabina rosa fa un quart de volta i queda a la mateixa distància, formant un angle recte amb la grisa.|El bloque gira 90° alrededor del origen, donde está el eje: la cabina rosa da un cuarto de vuelta y queda a la misma distancia, formando un ángulo recto con la gris." },
        { k: 'm3spot', ph: 'investiga', q: "L'eix del molí havia de quedar <b>ajagut</b>, cap al fons, però surt dret. Toca la instrucció que està malament.|El eje del molino tenía que quedar <b>tumbado</b>, hacia el fondo, pero sale de pie. Toca la instrucción que está mal.", prog: 'mou(0, 0, 10) cub(20, 20, 20, centrat)\nmou(0, 0, 14) gira(0, 0, 90)! cilindre(8, 30)', target: SUP,
          ex: "Un cilindre dret girat en z continua dret: gira sobre el seu propi eix i no canvia res. Per tombar-lo cap al fons cal girar en x: gira(-90, 0, 0).|Un cilindro de pie girado en z sigue de pie: gira sobre su propio eje y no cambia nada. Para tumbarlo hacia el fondo hay que girar en x: gira(-90, 0, 0)." },
        { k: 'move', ph: 'pausa', title: "El braç d'aspa|El brazo de aspa", secs: 40, t: "Estira un braç cap a la dreta: és una aspa i la teva espatlla és l'origen. <b>gira(0, 0, 90)</b>: puja el braç fins dalt fent un quart de volta. <b>gira(0, 0, 180)</b>: baixa'l per l'altre costat. Ara gira tot tu sobre tu mateix/a: és el mateix gir?|Estira un brazo hacia la derecha: es un aspa y tu hombro es el origen. <b>gira(0, 0, 90)</b>: sube el brazo hasta arriba dando un cuarto de vuelta. <b>gira(0, 0, 180)</b>: bájalo por el otro lado. Ahora gira todo tú sobre ti mismo/a: ¿es el mismo giro?" },
        { k: 'm3code', ph: 'repte', q: 'Gira la barra perquè apunti <b>cap al fons</b> (eix y), com el fantasma.|Gira la barra para que apunte <b>hacia el fondo</b> (eje y), como el fantasma.', start: 'cub(40, 8, 8)', blocks: BLK2, target: 'gira(0, 0, 90) cub(40, 8, 8)',
          checks: [{ k: 'match', target: 'gira(0, 0, 90) cub(40, 8, 8)', th: 0.9, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'uses', b: 'gira' }],
          hint: "És un gir sobre la placa (eix z). De l'eix x a l'eix y hi ha un quart de volta en sentit contrari a les agulles del rellotge: +90°.|Es un giro sobre la placa (eje z). Del eje x al eje y hay un cuarto de vuelta en sentido contrario a las agujas del reloj: +90°.", sol: 'gira(0, 0, 90) cub(40, 8, 8)' },
        { k: 'm3code', ph: 'repte', q: "<b>Tomba el cilindre:</b> que quedi ajagut sobre la placa, apuntant cap a x positiva, com el fantasma.|<b>Tumba el cilindro:</b> que quede tumbado sobre la placa, apuntando hacia x positiva, como el fantasma.", start: 'cilindre(10, 40)', blocks: BLK2, target: 'mou(0, 0, 5) gira(0, 90, 0) cilindre(10, 40)',
          checks: [{ k: 'match', target: 'mou(0, 0, 5) gira(0, 90, 0) cilindre(10, 40)', th: 0.85, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'size', ax: 'x', v: 40 }, { k: 'onplate' }],
          hint: "Gira'l 90° en y. Queda mig enfonsat: puja'l la meitat del diàmetre amb un mou per fora del gira.|Gíralo 90° en y. Queda medio hundido: súbelo la mitad del diámetro con un mueve por fuera del gira.", sol: 'mou(0, 0, 5) gira(0, 90, 0) cilindre(10, 40)' },
        { k: 'm3code', ph: 'repte', q: "Gira la placa <b>45° sobre si mateixa</b>, sense que el seu centre es mogui de (30, 30).|Gira la placa <b>45° sobre sí misma</b>, sin que su centro se mueva de (30, 30).", start: 'mou(30, 30, 2) cub(30, 30, 4, centrat)', blocks: BLK2, target: 'mou(30, 30, 2) gira(0, 0, 45) cub(30, 30, 4, centrat)',
          checks: [{ k: 'match', target: 'mou(30, 30, 2) gira(0, 0, 45) cub(30, 30, 4, centrat)', th: 0.9, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'uses', b: 'gira' }],
          hint: "Posa el gira just davant del cub, dins del mou: la placa centrada gira a l'origen i després el mou la porta al seu lloc. Si poses el gira per fora, fa un arc!|Pon el gira justo delante del cubo, dentro del mueve: la placa centrada gira en el origen y después el mueve la lleva a su sitio. Si pones el gira por fuera, ¡hace un arco!", sol: 'mou(30, 30, 2) gira(0, 0, 45) cub(30, 30, 4, centrat)' },
        { k: 'm3code', ph: 'repte', q: "<b>La creu de les aspes:</b> afegeix una segona barra igual, girada 90°, perquè facin una creu.|<b>La cruz de las aspas:</b> añade una segunda barra igual, girada 90°, para que hagan una cruz.", start: BAR, blocks: BLK2, target: CREU,
          checks: [{ k: 'match', target: CREU, th: 0.92, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'count', t: 'box', min: 2, txt: 'Hi ha dues barres|Hay dos barras' }, { k: 'one' }],
          hint: 'Duplica el bloc de la barra i, al duplicat, posa un gira(0, 0, 90) just davant del cub.|Duplica el bloque de la barra y, en el duplicado, pon un gira(0, 0, 90) justo delante del cubo.', sol: CREU },
        { k: 'm3code', ph: 'repte', extra: true, q: "<b>La rosa dels vents:</b> afegeix a la creu dues barres més curtes (<b>40 × 6 × 6</b>, centrades i pujades 3 mm) girades 45° i 135°.|<b>La rosa de los vientos:</b> añade a la cruz dos barras más cortas (<b>40 × 6 × 6</b>, centradas y subidas 3 mm) giradas 45° y 135°.", start: CREU, blocks: BLK2, target: ROSA,
          checks: [{ k: 'match', target: ROSA, th: 0.92, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'count', t: 'box', min: 4, txt: 'Hi ha quatre barres|Hay cuatro barras' }, { k: 'one' }],
          hint: 'Cada barra curta: mou(0, 0, 3) gira(0, 0, 45) cub(40, 6, 6, centrat). La segona, igual amb 135.|Cada barra corta: mueve(0, 0, 3) gira(0, 0, 45) cubo(40, 6, 6, centrado). La segunda, igual con 135.', sol: ROSA },
        { k: 'm3free', ph: 'crea', q: "<b>Una peça amb girs.</b> Crea un objecte amb almenys <b>3 peces</b> i <b>dos angles diferents</b>: una hèlix, una flor, un ventilador, un rellotge…|<b>Una pieza con giros.</b> Crea un objeto con al menos <b>3 piezas</b> y <b>dos ángulos distintos</b>: una hélice, una flor, un ventilador, un reloj…",
          name: 'La meva peça amb girs|Mi pieza con giros', blocks: ['cub', 'cil', 'esf', 'con', 'mou', 'gira', 'color'],
          crit: ['Almenys 3 peces|Al menos 3 piezas', 'Almenys dos angles de gir diferents|Al menos dos ángulos de giro distintos', 'Una sola peça que toca la placa|Una sola pieza que toca la placa'],
          checks: [{ k: 'count', min: 3 }, { k: 'uses', b: 'gira' }, { k: 'one' }, { k: 'onplate' }], sol: FLOR },
        { k: 'quiz', ph: 'tanca', q: 'Al voltant de quin punt gira un <code>cub(20)</code> amb <code>gira(0, 0, 90)</code>?|¿Alrededor de qué punto gira un <code>cubo(20)</code> con <code>gira(0, 0, 90)</code>?', opts: ["De l'origen (0, 0, 0), que és a la seva cantonada|Del origen (0, 0, 0), que está en su esquina", 'Del centre del cub|Del centro del cubo', 'Del centre de la cara de dalt|Del centro de la cara de arriba'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Quin gir <b>tomba</b> un cilindre dret perquè quedi ajagut?|¿Qué giro <b>tumba</b> un cilindro de pie para que quede tumbado?', opts: ['<code>gira(0, 90, 0)</code>|<code>gira(0, 90, 0)</code>', '<code>gira(0, 0, 90)</code>|<code>gira(0, 0, 90)</code>', '<code>gira(0, 0, 360)</code>|<code>gira(0, 0, 360)</code>'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* ---------- Sessió 3 · L'ordre importa ---------- */
    { id: 'p2-3', t: "L'ordre importa|El orden importa", min: 45, badge: 'p23ord',
      learn: ["Les transformacions s'apliquen de dins cap a fora: primer la que és més a prop de la forma.|Las transformaciones se aplican de dentro hacia fuera: primero la que está más cerca de la forma.",
        "gira(…) mou(…) forma: primer es mou i després gira al voltant de l'origen (fa un arc). mou(…) gira(…) forma: primer gira a l'origen i després es mou.|gira(…) mueve(…) forma: primero se mueve y después gira alrededor del origen (hace un arco). mueve(…) gira(…) forma: primero gira en el origen y después se mueve.",
        "Per repartir n peces iguals al voltant d'un centre, les mous a la mateixa distància i les gires 360 / n graus cada una.|Para repartir n piezas iguales alrededor de un centro, las mueves a la misma distancia y las giras 360 / n grados cada una."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Un angle de <b>+90°</b> en z, vist des de dalt, gira…|Un ángulo de <b>+90°</b> en z, visto desde arriba, gira…', opts: ['En sentit contrari a les agulles del rellotge|En sentido contrario a las agujas del reloj', 'En el sentit de les agulles del rellotge|En el sentido de las agujas del reloj', 'Depèn de la mida de la peça|Depende del tamaño de la pieza'], a: 0 },
        { k: 'quiz', ph: 'recorda', q: 'Una peça és a 30 mm de l\'origen i li apliques <code>gira(0, 0, 90)</code>. Què passa?|Una pieza está a 30 mm del origen y le aplicas <code>gira(0, 0, 90)</code>. ¿Qué pasa?', opts: ["Fa un quart de volta al voltant de l'origen i queda a 30 mm en una altra direcció|Da un cuarto de vuelta alrededor del origen y queda a 30 mm en otra dirección", 'Gira sobre el seu centre i no es mou de lloc|Gira sobre su centro y no se mueve de sitio', "Torna a l'origen|Vuelve al origen"], a: 0 },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: "El misteri de l'aspa fugitiva|El misterio del aspa fugitiva",
          t: "Avui la Júlia ha muntat les aspes del molí… i una ha aparegut a l'altra punta de la placa! Ha fet servir les mateixes instruccions que nosaltres: un <b>gira</b> i un <b>mou</b>. On és la diferència? Doncs en l'<b>ordre</b>. Com quan et poses els mitjons i les sabates: si canvies l'ordre, el resultat no és el mateix. Avui aprendrem a llegir les transformacions en l'ordre en què passen de debò.|Hoy Júlia ha montado las aspas del molino… ¡y una ha aparecido en la otra punta de la placa! Ha usado las mismas instrucciones que nosotros: un <b>gira</b> y un <b>mueve</b>. ¿Dónde está la diferencia? Pues en el <b>orden</b>. Como cuando te pones los calcetines y los zapatos: si cambias el orden, el resultado no es el mismo. Hoy aprenderemos a leer las transformaciones en el orden en que pasan de verdad." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Ordre de lectura|Orden de lectura', t: 'De dins cap a fora|De dentro hacia fuera', anim: 'p23inout',
            x: "L'ordinador fa primer la <b>forma</b> i després li aplica les transformacions començant per la que té <b>més a prop</b>. A <code>gira(0, 0, 90) mou(30, 0, 0) cub(10)</code>: 1, fa el cub; 2, el mou 30 mm; 3, el gira tot al voltant de l'origen. Als blocs és fàcil de veure: es comença pel bloc de més endins.|El ordenador hace primero la <b>forma</b> y después le aplica las transformaciones empezando por la que tiene <b>más cerca</b>. En <code>gira(0, 0, 90) mueve(30, 0, 0) cubo(10)</code>: 1, hace el cubo; 2, lo mueve 30 mm; 3, lo gira todo alrededor del origen. En los bloques es fácil de ver: se empieza por el bloque más interior." },
          { k: 'Comparar|Comparar', t: 'Mateixes instruccions, llocs diferents|Mismas instrucciones, sitios distintos', media: { k: 'model', prog: 'cilindre(6, 24)\ncolor("blau") gira(0, 0, 90) mou(30, -5, 0) cub(10)\ncolor("taronja") mou(30, -5, 0) gira(0, 0, 90) cub(10)' },
            x: "Els dos cubs fan servir <code>gira(0, 0, 90)</code> i <code>mou(30, −5, 0)</code>. El <b>blau</b> primer es mou i després gira: fa un arc i acaba cap al fons. El <b>taronja</b> primer gira, a l'origen, i després es mou: es queda a la dreta.|Los dos cubos usan <code>gira(0, 0, 90)</code> y <code>mueve(30, −5, 0)</code>. El <b>azul</b> primero se mueve y después gira: hace un arco y acaba hacia el fondo. El <b>naranja</b> primero gira, en el origen, y después se mueve: se queda a la derecha." },
          { k: 'Matemàtiques|Matemáticas', t: 'Compondre no és commutatiu|Componer no es conmutativo', anim: 'p23paths',
            x: "Aplicar una transformació darrere l'altra és <b>compondre-les</b>. Amb nombres, 2 + 3 = 3 + 2; amb transformacions, <b>l'ordre canvia el resultat</b>: girar i moure no és el mateix que moure i girar. Dos moviments seguits, en canvi, sí que es poden canviar d'ordre.|Aplicar una transformación detrás de otra es <b>componerlas</b>. Con números, 2 + 3 = 3 + 2; con transformaciones, <b>el orden cambia el resultado</b>: girar y mover no es lo mismo que mover y girar. Dos movimientos seguidos, en cambio, sí que se pueden cambiar de orden.",
            bad: "L'ordre de gira i mou no importa: el resultat és el mateix.|El orden de gira y mueve no importa: el resultado es el mismo.", good: "Primer s'aplica el que és més a prop de la forma: canviar l'ordre canvia on acaba la peça.|Primero se aplica lo que está más cerca de la forma: cambiar el orden cambia dónde acaba la pieza." },
          { k: 'Patrons|Patrones', t: "Mou lluny i gira: peces al voltant d'un centre|Mueve lejos y gira: piezas alrededor de un centro", media: { k: 'model', prog: PAT4 },
            x: "Quatre aspes iguals: cada una té el <b>mateix mou</b> (la porta a la distància) i un <b>gira</b> diferent per fora (0°, 90°, 180°, 270°). Per repartir <b>n</b> peces, l'angle entre elles és <b>360 / n</b>: 4 peces, 90°; 3 peces, 120°; 6 peces, 60°.|Cuatro aspas iguales: cada una tiene el <b>mismo mueve</b> (la lleva a la distancia) y un <b>gira</b> distinto por fuera (0°, 90°, 180°, 270°). Para repartir <b>n</b> piezas, el ángulo entre ellas es <b>360 / n</b>: 4 piezas, 90°; 3 piezas, 120°; 6 piezas, 60°." },
          { k: 'I escala?|¿Y escala?', t: "escala també treballa des de l'origen|escala también trabaja desde el origen", media: { k: 'model', prog: 'cilindre(4, 30)\ncolor("gris") mou(20, 0, 0) cub(10)\nescala(2) mou(20, 0, 0) cub(10)' },
            x: "<code>escala(2)</code> fa la forma el doble de gran… però també des de l'origen: si la forma ja s'ha mogut, la <b>distància també es duplica</b>. El cub gris és a 20 mm; el rosa, escalat després de moure'l, fa 20 mm i és a 40 mm. A matemàtiques en diem <b>homotècia</b>.|<code>escala(2)</code> hace la forma el doble de grande… pero también desde el origen: si la forma ya se ha movido, la <b>distancia también se duplica</b>. El cubo gris está a 20 mm; el rosa, escalado después de moverlo, mide 20 mm y está a 40 mm. En matemáticas lo llamamos <b>homotecia</b>." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🧦', title: 'Dues ordres, dos llocs|Dos órdenes, dos sitios', t: 'Per parelles, amb la fitxa de la quadrícula, un quadrat de paper i el paper vegetal de la sessió anterior:|Por parejas, con la ficha de la cuadrícula, un cuadrado de papel y el papel vegetal de la sesión anterior:',
          steps: ["Persona A: mou el quadrat 30 mm a la dreta i després gira-ho tot 90° clavant el llapis a l'origen. Marca on acaba.|Persona A: mueve el cuadrado 30 mm a la derecha y después gíralo todo 90° clavando el lápiz en el origen. Marca dónde acaba.", "Persona B: primer gira el quadrat 90° a l'origen i després mou-lo 30 mm a la dreta. Marca on acaba.|Persona B: primero gira el cuadrado 90° en el origen y después muévelo 30 mm a la derecha. Marca dónde acaba.", 'Compareu les dues marques i escriviu el programa de cada una.|Comparad las dos marcas y escribid el programa de cada una.', "Penseu dues accions de cada dia on l'ordre importa i dues on no.|Pensad dos acciones de cada día donde el orden importa y dos donde no."],
          tip: "Mitjons i sabates: l'ordre importa. Barret i bufanda: no.|Calcetines y zapatos: el orden importa. Sombrero y bufanda: no." },
        { k: 'm3predict', ph: 'prova', q: "L'eix i el cub gris no canvien. <b>On queda el cub rosa?</b> Llegeix de dins cap a fora.|El eje y el cubo gris no cambian. <b>¿Dónde queda el cubo rosa?</b> Lee de dentro hacia fuera.", prog: RA,
          opts: [{ prog: RA }, { prog: RB }, { prog: RC }], a: 0,
          ex: "Primer es mou 30 mm (on és el gris) i després gira 90° al voltant de l'origen: fa un quart de volta i queda cap al fons, en angle recte amb el gris.|Primero se mueve 30 mm (donde está el gris) y después gira 90° alrededor del origen: da un cuarto de vuelta y queda hacia el fondo, en ángulo recto con el gris." },
        { k: 'm3predict', ph: 'investiga', q: "Ara, <b>amb l'ordre al revés</b>. On queda el cub rosa?|Ahora, <b>con el orden al revés</b>. ¿Dónde queda el cubo rosa?", prog: RB,
          opts: [{ prog: RA }, { prog: RB }, { prog: RC }], a: 1,
          ex: "Primer gira a l'origen (gira sobre la cantonada i passa a ocupar de x = −10 a 0) i després es mou 30 mm: queda entre l'eix i el cub gris, tocant-lo.|Primero gira en el origen (gira sobre la esquina y pasa a ocupar de x = −10 a 0) y después se mueve 30 mm: queda entre el eje y el cubo gris, tocándolo." },
        { k: 'm3spot', ph: 'investiga', q: "Aquesta és l'aspa fugitiva de la Júlia. Toca la instrucció que té l'ordre canviat.|Esta es el aspa fugitiva de Júlia. Toca la instrucción que tiene el orden cambiado.", prog: PAT4X, target: PAT4,
          ex: "En aquesta línia, primer gira el cub a l'origen i després el mou: l'aspa queda desplaçada. Per fer-la girar al voltant de l'eix, el gira ha d'anar per fora: gira(0, 0, 180) mou(5, −4, 0) cub(25, 8, 6).|En esta línea, primero gira el cubo en el origen y después lo mueve: el aspa queda desplazada. Para hacerla girar alrededor del eje, el gira tiene que ir por fuera: gira(0, 0, 180) mueve(5, −4, 0) cubo(25, 8, 6)." },
        { k: 'move', ph: 'pausa', title: 'Mitjons i sabates|Calcetines y zapatos', secs: 40, t: "Executa amb el cos: <b>pas a la dreta</b> i després <b>gira mig tomb</b>. Ara al revés: <b>gira mig tomb</b> i després <b>pas a la dreta</b>. Mira on has acabat cada vegada: és el mateix lloc?|Ejecuta con el cuerpo: <b>paso a la derecha</b> y después <b>media vuelta</b>. Ahora al revés: <b>media vuelta</b> y después <b>paso a la derecha</b>. Mira dónde has acabado cada vez: ¿es el mismo sitio?" },
        { k: 'm3code', ph: 'repte', q: "Porta el cub al fantasma: <b>gira'l 45° sobre si mateix</b> i <b>mou-lo</b> a (40, 20, 5).|Lleva el cubo al fantasma: <b>gíralo 45° sobre sí mismo</b> y <b>muévelo</b> a (40, 20, 5).", start: 'cub(10, centrat)', blocks: BLK2, target: 'mou(40, 20, 5) gira(0, 0, 45) cub(10, centrat)',
          checks: [{ k: 'match', target: 'mou(40, 20, 5) gira(0, 0, 45) cub(10, centrat)', th: 0.85, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'uses', b: 'gira' }, { k: 'onplate' }],
          hint: "El que ha de passar primer va més a prop del cub: mou(40, 20, 5) gira(0, 0, 45) cub(10, centrat).|Lo que tiene que pasar primero va más cerca del cubo: mueve(40, 20, 5) gira(0, 0, 45) cubo(10, centrado).", sol: 'mou(40, 20, 5) gira(0, 0, 45) cub(10, centrat)' },
        { k: 'm3code', ph: 'repte', q: "Fes que l'aspa giri <b>90° al voltant de l'eix</b> (l'origen), com el fantasma.|Haz que el aspa gire <b>90° alrededor del eje</b> (el origen), como el fantasma.", start: `${HUB}\n${ASPA}`, blocks: BLK2, target: `${HUB}\ngira(0, 0, 90) ${ASPA}`,
          checks: [{ k: 'match', target: `${HUB}\ngira(0, 0, 90) ${ASPA}`, th: 0.9, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'uses', b: 'gira' }, { k: 'one' }],
          hint: "L'aspa ja és a la seva distància: el gira ha d'anar per fora del mou perquè passi després.|El aspa ya está a su distancia: el gira tiene que ir por fuera del mueve para que pase después.", sol: `${HUB}\ngira(0, 0, 90) ${ASPA}` },
        { k: 'm3code', ph: 'repte', q: '<b>Quatre aspes:</b> copia l\'aspa tres vegades i canvia només l\'angle: 0°, 90°, 180° i 270°.|<b>Cuatro aspas:</b> copia el aspa tres veces y cambia solo el ángulo: 0°, 90°, 180° y 270°.', start: PAT1, blocks: BLK2, target: PAT4,
          checks: [{ k: 'match', target: PAT4, th: 0.92, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'count', t: 'box', min: 4, txt: 'Hi ha quatre aspes|Hay cuatro aspas' }, { k: 'one' }],
          hint: "Toca el bloc gira de l'aspa i prem «Duplica» tres vegades. Després canvia l'angle de cada còpia.|Toca el bloque gira del aspa y pulsa «Duplica» tres veces. Después cambia el ángulo de cada copia.", sol: PAT4 },
        { k: 'm3code', ph: 'repte', q: "<b>Tres aspes</b> repartides igual al voltant de l'eix. Quin angle hi ha entre elles?|<b>Tres aspas</b> repartidas igual alrededor del eje. ¿Qué ángulo hay entre ellas?", start: PAT1, blocks: BLK2, target: PAT3,
          checks: [{ k: 'match', target: PAT3, th: 0.92, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'count', t: 'box', min: 3, max: 3, txt: 'Exactament tres aspes|Exactamente tres aspas' }, { k: 'one' }],
          hint: '360 / 3 = 120. Els angles són 0°, 120° i 240°.|360 / 3 = 120. Los ángulos son 0°, 120° y 240°.', sol: PAT3 },
        { k: 'm3code', ph: 'repte', extra: true, q: "Amb <b>una sola instrucció nova</b>, fes que el cub sigui el doble de gran <b>i</b> quedi el doble de lluny de l'origen, com el fantasma.|Con <b>una sola instrucción nueva</b>, haz que el cubo sea el doble de grande <b>y</b> quede el doble de lejos del origen, como el fantasma.", start: 'mou(20, 0, 0) cub(10)', blocks: ['cub', 'mou', 'gira', 'escala'], target: 'escala(2) mou(20, 0, 0) cub(10)',
          checks: [{ k: 'match', target: 'escala(2) mou(20, 0, 0) cub(10)', th: 0.9, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'uses', b: 'escala' }, { k: 'size', ax: 'x', v: 20 }],
          hint: "escala també treballa des de l'origen: si va per fora del mou, escala la mida i la distància alhora.|escala también trabaja desde el origen: si va por fuera del mueve, escala el tamaño y la distancia a la vez.", sol: 'escala(2) mou(20, 0, 0) cub(10)' },
        { k: 'm3free', ph: 'crea', q: "<b>Un patró circular.</b> Crea un objecte amb almenys <b>4 peces iguals</b> repartides al voltant de l'origen amb gira i mou: un sol, una flor, una roda, un rellotge…|<b>Un patrón circular.</b> Crea un objeto con al menos <b>4 piezas iguales</b> repartidas alrededor del origen con gira y mueve: un sol, una flor, una rueda, un reloj…",
          name: 'El meu patró circular|Mi patrón circular', blocks: ['cub', 'cil', 'esf', 'con', 'mou', 'gira', 'color'],
          crit: ["Almenys 4 peces iguals al voltant d'un centre|Al menos 4 piezas iguales alrededor de un centro", 'Angles repartits igual (360 / n)|Ángulos repartidos igual (360 / n)', 'Una sola peça que toca la placa|Una sola pieza que toca la placa'],
          checks: [{ k: 'count', min: 5 }, { k: 'uses', b: 'gira' }, { k: 'one' }, { k: 'onplate' }], sol: SOL5 },
        { k: 'quiz', ph: 'tanca', q: 'A <code>gira(0, 0, 90) mou(30, 0, 0) cub(10)</code>, què passa primer?|En <code>gira(0, 0, 90) mueve(30, 0, 0) cubo(10)</code>, ¿qué pasa primero?', opts: ["El cub es mou 30 mm i després gira al voltant de l'origen|El cubo se mueve 30 mm y después gira alrededor del origen", 'El cub gira i després es mou|El cubo gira y después se mueve', 'Les dues coses alhora: el resultat és el mateix|Las dos cosas a la vez: el resultado es el mismo'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Per repartir <b>6 peces</b> iguals al voltant d\'un centre, de quants graus és cada gir?|Para repartir <b>6 piezas</b> iguales alrededor de un centro, ¿de cuántos grados es cada giro?', opts: ['60° (360 / 6)|60° (360 / 6)', '6°|6°', '90°|90°'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* ---------- Sessió 4 · Projecte: el molí ---------- */
    { id: 'p2-4', t: 'Projecte: el molí|Proyecto: el molino', min: 45, proj: true, badge: 'p24moli',
      learn: ["Un objecte complex es descompon en peces i cada peça es fa amb la forma i les transformacions que necessita.|Un objeto complejo se descompone en piezas y cada pieza se hace con la forma y las transformaciones que necesita.",
        "Les aspes es fan centrades a l'origen, es giren al voltant de l'eix y i després es mouen fins a l'eix del molí.|Las aspas se hacen centradas en el origen, se giran alrededor del eje y y después se mueven hasta el eje del molino.",
        'Abans de fabricar, es comprova la fitxa tècnica: una sola peça, sobre la placa i dins de la caixa màxima.|Antes de fabricar, se comprueba la ficha técnica: una sola pieza, sobre la placa y dentro de la caja máxima.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Per repartir <b>4 aspes</b> iguals al voltant de l\'eix, de quants graus és cada gir?|Para repartir <b>4 aspas</b> iguales alrededor del eje, ¿de cuántos grados es cada giro?', opts: ['90°|90°', '45°|45°', '4°|4°'], a: 0 },
        { k: 'm3predict', ph: 'recorda', q: 'L\'aspa grisa no gira. <b>On queda la rosa?</b>|El aspa gris no gira. <b>¿Dónde queda la rosa?</b>', prog: REFB + bl(45),
          opts: [{ prog: REFB + bl(45) }, { prog: REFB + bl(90) }, { prog: REFB + bl(180) }], a: 0,
          ex: "Primer es mou a la seva distància i després gira 45° al voltant de l'eix: les dues aspes fan una V.|Primero se mueve a su distancia y después gira 45° alrededor del eje: las dos aspas hacen una V." },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: 'El molí, peça a peça|El molino, pieza a pieza',
          t: "Ja tenim la <b>fitxa tècnica</b> de la cooperativa: una torre en forma de tronc de con, una teulada cònica, un eix horitzontal que surt per davant i dues aspes en creu, inclinades 45°. Avui muntarem el <b>Molí Vell</b> peça a peça i, al final, el faràs teu. Recordeu el que hem après: moure, girar i, sobretot, l'ordre!|Ya tenemos la <b>ficha técnica</b> de la cooperativa: una torre en forma de tronco de cono, un tejado cónico, un eje horizontal que sale por delante y dos aspas en cruz, inclinadas 45°. Hoy montaremos el <b>Molino Viejo</b> pieza a pieza y, al final, lo harás tuyo. Recordad lo que hemos aprendido: mover, girar y, sobre todo, ¡el orden!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Descompondre|Descomponer', t: 'El molí desmuntat|El molino desmontado', anim: 'p24parts',
            x: "Els enginyers descomponen un objecte en <b>peces senzilles</b> i, per a cadascuna, decideixen la forma i les transformacions: la torre no necessita cap mou; la teulada, un mou; l'eix, un gira per ajaure'l; i les aspes, un gira i un mou.|Los ingenieros descomponen un objeto en <b>piezas sencillas</b> y, para cada una, deciden la forma y las transformaciones: la torre no necesita ningún mueve; el tejado, un mueve; el eje, un gira para tumbarlo; y las aspas, un gira y un mueve." },
          { k: 'Fitxa tècnica|Ficha técnica', t: 'Les mides del Molí Vell|Las medidas del Molino Viejo', anim: 'p24spec',
            x: "La torre fa 70 mm d'alçada, 40 mm de diàmetre a baix i 28 a dalt. La teulada és un con de 34 × 22 mm. L'eix, un cilindre de 8 mm de diàmetre, surt 12 mm per davant a z = 60. Les aspes són dues plaques de 80 × 3 × 8 mm. Tot ha de cabre en 100 × 100 × 120 mm.|La torre mide 70 mm de altura, 40 mm de diámetro abajo y 28 arriba. El tejado es un cono de 34 × 22 mm. El eje, un cilindro de 8 mm de diámetro, sale 12 mm por delante en z = 60. Las aspas son dos placas de 80 × 3 × 8 mm. Todo tiene que caber en 100 × 100 × 120 mm." },
          { k: "L'eix|El eje", t: "Un cilindre ajagut que surt per davant|Un cilindro tumbado que sale por delante", media: { k: 'model', prog: M2 },
            x: "<code>gira(90, 0, 0)</code> tomba el cilindre cap a y negativa, és a dir, <b>cap a davant</b>. Després el mou el porta a z = 60 i 12 mm endavant, perquè comenci una mica dins de la torre i hi quedi soldat.|<code>gira(90, 0, 0)</code> tumba el cilindro hacia y negativa, es decir, <b>hacia delante</b>. Después el mueve lo lleva a z = 60 y 12 mm adelante, para que empiece un poco dentro de la torre y quede soldado." },
          { k: 'Les aspes|Las aspas', t: "Girar al voltant de l'eix y|Girar alrededor del eje y", media: { k: 'model', prog: 'gira(0, 45, 0) cub(80, 3, 8, centrat)\ngira(0, -45, 0) cub(80, 3, 8, centrat)\ngira(90, 0, 0) cilindre(8, 6, centrat)' },
            x: "Les aspes giren al voltant de l'eix del molí, que va de davant a darrere: l'eix <b>y</b>. Per això es fan <b>centrades</b> a l'origen i es giren amb <code>gira(0, 45, 0)</code> i <code>gira(0, −45, 0)</code>: una creu en forma d'X. Al molí, un <code>mou(0, −22, 60)</code> per fora porta la creu fins a la punta de l'eix.|Las aspas giran alrededor del eje del molino, que va de delante a atrás: el eje <b>y</b>. Por eso se hacen <b>centradas</b> en el origen y se giran con <code>gira(0, 45, 0)</code> y <code>gira(0, −45, 0)</code>: una cruz en forma de X. En el molino, un <code>mueve(0, −22, 60)</code> por fuera lleva la cruz hasta la punta del eje.",
            tip: 'mou per fora i gira per dins: primer gira a l\'origen, després es mou. Al revés, l\'aspa faria un arc i fugiria!|mueve por fuera y gira por dentro: primero gira en el origen, después se mueve. ¡Al revés, el aspa haría un arco y se escaparía!' },
          { k: 'Muntatge|Montaje', t: 'El Molí Vell complet|El Molino Viejo completo', media: { k: 'model', prog: MOLIC },
            x: "Cada peça és una línia (o un grup) i els comentaris <code>//</code> diuen què és cada part. L'ordre de les <b>línies</b> no importa, però l'ordre de les <b>transformacions dins de cada línia</b>, sí.|Cada pieza es una línea (o un grupo) y los comentarios <code>//</code> dicen qué es cada parte. El orden de las <b>líneas</b> no importa, pero el orden de las <b>transformaciones dentro de cada línea</b>, sí." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '✏️', title: "El molí explotat|El molino explosionado", t: 'Individualment, amb la fitxa «El molí, peça a peça»:|Individualmente, con la ficha «El molino, pieza a pieza»:',
          steps: ["Dibuixa el molí desmuntat: la torre, la teulada, l'eix i les aspes separats.|Dibuja el molino desmontado: la torre, el tejado, el eje y las aspas separados.", "Per a cada peça, omple la taula: forma, mides, gira i mou.|Para cada pieza, rellena la tabla: forma, medidas, gira y mueve.", "Pensa com el faràs teu: més aspes, una porta, una base, colors… Apunta-ho.|Piensa cómo lo harás tuyo: más aspas, una puerta, una base, colores… Apúntalo.", 'Comprova amb un company/a que l\'ordre de cada gira i mou és correcte.|Comprueba con un compañero/a que el orden de cada gira y mueve es correcto.'],
          tip: "A la columna del gira, pregunta't: sobre quin eix gira aquesta peça?|En la columna del gira, pregúntate: ¿sobre qué eje gira esta pieza?" },
        { k: 'm3spot', ph: 'investiga', q: "Una aspa ha fugit de l'eix. Toca la instrucció que està malament.|Un aspa se ha escapado del eje. Toca la instrucción que está mal.", prog: M3 + '\ngira(0, -45, 0)! mou(0, -22, 60) cub(80, 3, 8, centrat)', target: MOLI,
          ex: "Aquí el mou va per dins: l'aspa primer es mou fins a l'eix i després gira al voltant de l'origen, que és a terra. Ha de ser al revés: mou(0, −22, 60) gira(0, −45, 0) cub(80, 3, 8, centrat).|Aquí el mueve va por dentro: el aspa primero se mueve hasta el eje y después gira alrededor del origen, que está en el suelo. Tiene que ser al revés: mueve(0, −22, 60) gira(0, −45, 0) cubo(80, 3, 8, centrado)." },
        { k: 'move', ph: 'pausa', title: 'El molí humà|El molino humano', secs: 40, t: "En grups de quatre, d'esquena amb esquena i braços estirats: sou les aspes. L'eix és el centre del grup. Feu <b>gira(0, 45, 0)</b> tots junts, a poc a poc, i després <b>mitja volta</b> sencera sense deixar anar la creu!|En grupos de cuatro, espalda con espalda y brazos estirados: sois las aspas. El eje es el centro del grupo. Haced <b>gira(0, 45, 0)</b> todos juntos, poco a poco, y después <b>media vuelta</b> entera ¡sin soltar la cruz!" },
        { k: 'm3code', ph: 'repte', q: "<b>Pas 1 · La torre i la teulada:</b> un tronc de con de 70 mm d'alçada (40 mm a baix i 28 a dalt) i, a sobre, un con de 34 mm de diàmetre i 22 d'alçada.|<b>Paso 1 · La torre y el tejado:</b> un tronco de cono de 70 mm de altura (40 mm abajo y 28 arriba) y, encima, un cono de 34 mm de diámetro y 22 de altura.", blocks: BLK3, target: TR,
          checks: [{ k: 'match', target: TR, th: 0.92, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'one' }, { k: 'size', ax: 'z', v: 92 }],
          hint: 'con(40, 70, 28) per a la torre i mou(0, 0, 70) con(34, 22) per a la teulada.|cono(40, 70, 28) para la torre y mueve(0, 0, 70) cono(34, 22) para el tejado.', sol: TR },
        { k: 'm3code', ph: 'repte', q: "<b>Pas 2 · L'eix:</b> un cilindre de 8 mm de diàmetre i 12 de llarg, ajagut cap a davant, que comenci a y = −12 i a z = 60.|<b>Paso 2 · El eje:</b> un cilindro de 8 mm de diámetro y 12 de largo, tumbado hacia delante, que empiece en y = −12 y en z = 60.", start: TR, blocks: BLK3, target: M2,
          checks: [{ k: 'match', target: M2, th: 0.92, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'one' }, { k: 'uses', b: 'gira' }],
          hint: "gira(90, 0, 0) el tomba cap a y negativa. Després, per fora, mou(0, −12, 60).|gira(90, 0, 0) lo tumba hacia y negativa. Después, por fuera, mueve(0, −12, 60).", sol: M2 },
        { k: 'm3code', ph: 'repte', q: "<b>Pas 3 · La primera aspa:</b> una placa de 80 × 3 × 8 mm, centrada, girada <b>45° en y</b> i moguda a la punta de l'eix, a (0, −22, 60).|<b>Paso 3 · La primera aspa:</b> una placa de 80 × 3 × 8 mm, centrada, girada <b>45° en y</b> y movida a la punta del eje, en (0, −22, 60).", start: M2, blocks: BLK3, target: M3,
          checks: [{ k: 'match', target: M3, th: 0.92, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'one' }, { k: 'count', t: 'box', min: 1, txt: "Hi ha l'aspa|Está el aspa" }],
          hint: 'mou(0, −22, 60) gira(0, 45, 0) cub(80, 3, 8, centrat): el mou per fora, el gira per dins.|mueve(0, −22, 60) gira(0, 45, 0) cubo(80, 3, 8, centrado): el mueve por fuera, el gira por dentro.', sol: M3 },
        { k: 'm3code', ph: 'repte', q: "<b>Pas 4 · La segona aspa:</b> completa la creu amb una aspa igual, girada <b>−45°</b>.|<b>Paso 4 · La segunda aspa:</b> completa la cruz con un aspa igual, girada <b>−45°</b>.", start: M3, blocks: BLK3, target: MOLI,
          checks: [{ k: 'match', target: MOLI, th: 0.94, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'count', t: 'box', min: 2, txt: 'Hi ha les dues aspes|Están las dos aspas' }, { k: 'one' }, { k: 'fit', box: [100, 100, 120] }],
          hint: "Duplica el bloc de l'aspa i canvia el 45 per −45.|Duplica el bloque del aspa y cambia el 45 por −45.", sol: MOLI },
        { k: 'm3code', ph: 'repte', extra: true, q: "<b>Un molí de sis aspes:</b> fes la creu amb <b>tres</b> plaques repartides igual, a 30°, 90° i 150°.|<b>Un molino de seis aspas:</b> haz la cruz con <b>tres</b> placas repartidas igual, a 30°, 90° y 150°.", start: MOLI, blocks: BLK3, target: MOLI6,
          checks: [{ k: 'match', target: MOLI6, th: 0.92, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'count', t: 'box', min: 3, max: 3, txt: 'Exactament tres plaques|Exactamente tres placas' }, { k: 'one' }],
          hint: "Cada placa fa dues aspes. Sis aspes en 360° són 60° entre aspes: les plaques van a 30°, 90° i 150°.|Cada placa hace dos aspas. Seis aspas en 360° son 60° entre aspas: las placas van a 30°, 90° y 150°.", sol: MOLI6 },
        { k: 'm3free', ph: 'crea', q: "<b>El teu Molí Vell.</b> Parteix del molí de l'estudi i fes-lo teu: més aspes, una porta, finestres, una base, colors, una altra teulada… Ha de continuar sent una sola peça dins de la caixa de 100 × 100 × 120 mm.|<b>Tu Molino Viejo.</b> Parte del molino del estudio y hazlo tuyo: más aspas, una puerta, ventanas, una base, colores, otro tejado… Tiene que seguir siendo una sola pieza dentro de la caja de 100 × 100 × 120 mm.",
          name: 'El meu molí|Mi molino', start: MOLIC, blocks: ['cub', 'cil', 'esf', 'con', 'mou', 'gira', 'color', 'rem'],
          crit: ["Torre, teulada, eix i almenys 4 aspes|Torre, tejado, eje y al menos 4 aspas", "Les aspes estan girades al voltant de l'eix (mou per fora, gira per dins)|Las aspas están giradas alrededor del eje (mueve por fuera, gira por dentro)", "Hi has afegit almenys una millora pròpia|Has añadido al menos una mejora propia", 'Una sola peça sobre la placa, dins de 100 × 100 × 120 mm|Una sola pieza sobre la placa, dentro de 100 × 100 × 120 mm'],
          checks: [{ k: 'count', min: 6 }, { k: 'uses', b: 'gira' }, { k: 'one' }, { k: 'onplate' }, { k: 'fit', box: [100, 100, 120] }], sol: MOLI + '\nmou(-6, -22, 0) cub(12, 6, 18)' },
        { k: 'quiz', ph: 'tanca', q: "Per què les aspes s'escriuen <code>mou(…) gira(…) cub(…, centrat)</code> i no al revés?|¿Por qué las aspas se escriben <code>mueve(…) gira(…) cubo(…, centrado)</code> y no al revés?", opts: ["Perquè han de girar a l'origen, sobre el seu centre, i després anar a l'eix|Porque tienen que girar en el origen, sobre su centro, y después ir al eje", 'Perquè el programa és més curt|Porque el programa es más corto', 'Perquè els blocs gira sempre van al final|Porque los bloques gira siempre van al final'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: "Quin gir fa servir l'eix del molí per quedar <b>ajagut cap a davant</b>?|¿Qué giro usa el eje del molino para quedar <b>tumbado hacia delante</b>?", opts: ['<code>gira(90, 0, 0)</code>|<code>gira(90, 0, 0)</code>', '<code>gira(0, 0, 90)</code>|<code>gira(0, 0, 90)</code>', '<code>gira(0, 0, 0)</code>|<code>gira(0, 0, 0)</code>'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] }
  ] };
})();
