/* Tech Web · unitat 6 «Disposició» (w6-1 … w6-4)
   Contingut propi de Numi. El Club Foto del poble vol una web per ensenyar les fotos de les seves sortides i l'alumne/a
   n'és el dissenyador/a: posa caixes en fila i en columna amb flexbox (display: flex, gap, flex-direction,
   justify-content, align-items), fa galeries amb grid (grid-template-columns, fr, repeat) i fa servir taules només per
   a dades (table, tr, td, th, caption). Projecte: l'àlbum de fotos.
   · Dins del codi (html/css), «{{català|castellano}}» es tria en el moment de mostrar-lo, segons l'idioma de l'alumne/a.
   · Les comprovacions es fan amb petits ajudants (tag, inn, css…); el nom de l'etiqueta hi va com a propietat no
     enumerable perquè no es confongui amb un text per traduir. */
Object.assign(TBADGE, {
  w_fila: { id: 'w_fila', ico: '📏', n: 'Mestre/a del flex|Maestro/a del flex', d: 'Has posat caixes en fila i en columna amb flexbox.|Has puesto cajas en fila y en columna con flexbox.' },
  w_graella: { id: 'w_graella', ico: '🧩', n: 'Arquitecte/a de graelles|Arquitecto/a de rejillas', d: 'Has construït galeries de fotos amb display: grid i columnes fr.|Has construido galerías de fotos con display: grid y columnas fr.' },
  w_taula: { id: 'w_taula', ico: '📅', n: 'Organitzador/a de dades|Organizador/a de datos', d: 'Has fet taules amb capçaleres que tothom pot entendre, també amb un lector de pantalla.|Has hecho tablas con cabeceras que todo el mundo puede entender, también con un lector de pantalla.' },
  w_album: { id: 'w_album', ico: '🏆', n: "Dissenyador/a de l'àlbum|Diseñador/a del álbum", d: "Projecte acabat: el teu àlbum de fotos amb flex, grid i una taula de dades.|Proyecto terminado: tu álbum de fotos con flex, grid y una tabla de datos." }
});

COURSE_UNITS[6] = (() => {
  // «{{ca|es}}» dins del codi: es resol en llegir-lo (getter), així el codi canvia d'idioma amb l'app
  const LG = s => s.replace(/\{\{([^{}|]*)\|([^{}]*)\}\}/g, (_, ca, es) => (typeof LANG !== 'undefined' && LANG === 'es') ? es : ca);
  const BI = o => { if (Array.isArray(o)) { o.forEach(BI); return o; } if (!o || typeof o !== 'object') return o;
    for (const k of Object.keys(o)) { const v = o[k]; if ((k === 'html' || k === 'css') && typeof v === 'string' && v.includes('{{')) Object.defineProperty(o, k, { get: () => LG(v), enumerable: true, configurable: true }); else if (v && typeof v === 'object') BI(v); }
    return o; };
  // comprovacions
  const ne = (o, t) => Object.defineProperty(o, 't', { value: t, enumerable: false, writable: true, configurable: true });
  const tag = (t, o = {}) => ne({ k: 'tag', ...o }, t);
  const inn = (t, p, o = {}) => ne({ k: 'in', p, ...o }, t);
  const alt = (min, o = {}) => ne({ k: 'attr', a: 'alt', min, ...o }, 'img');
  const notag = (t, o = {}) => ne({ k: 'notag', ...o }, t);
  const sty = (t, p, v, o = {}) => ne({ k: 'styled', p, ...(v ? { v } : {}), ...o }, t);
  const css = (s, p, v, o = {}) => ({ k: 'css', s, p, ...(v ? { v } : {}), ...o });
  const prop = (p, v, o = {}) => ({ k: 'prop', p, ...(v ? { v } : {}), ...o });
  const CLEAN = { k: 'clean' }, CSSOK = { k: 'cssclean' };
  const FLEX = '/^flex$/', GRID = '/^grid$/', COL3 = '/^\\s*(repeat\\(\\s*3\\s*,[^)]+\\)|[^\\s,]+\\s+[^\\s,]+\\s+[^\\s,]+)\\s*$/', COL4 = '/^\\s*(repeat\\(\\s*4\\s*,[^)]+\\)|([^\\s,]+\\s+){3}[^\\s,]+)\\s*$/';
  const cs = t => ne({ tab: 'css' }, t);   // fragment per inserir a la pestanya CSS
  // les fotos del club (dibuixos de Numi) amb el seu text alternatiu
  const F = {
    platja: ['platja', 'Platja amb una palmera i el sol|Playa con una palmera y el sol'], muntanya: ['muntanya', 'Dues muntanyes amb neu al cim|Dos montañas con nieve en la cima'],
    bosc: ['bosc', 'Turons verds amb arbres|Colinas verdes con árboles'], pont: ['pont', 'Un pont de pedra sobre el riu|Un puente de piedra sobre el río'],
    castell: ['castell', 'Un castell amb dues torres|Un castillo con dos torres'], ciutat: ['ciutat', 'Edificis de la ciutat al vespre|Edificios de la ciudad al atardecer'],
    espai: ['espai', "Planetes a l'espai|Planetas en el espacio"], seu: ['seu-vella', "Una catedral antiga dalt d'un turó|Una catedral antigua en lo alto de una colina"]
  };
  const img = (n, ind = '  ') => `${ind}<img src="img/tech/web/${F[n][0]}.svg" alt="{{${F[n][1]}}}">`;
  const fig = (n, cap, ind = '  ') => `${ind}<figure>\n${img(n, ind + '  ')}\n${ind}  <figcaption>{{${cap}}}</figcaption>\n${ind}</figure>`;
  const foto = (n, cap) => `  <div class="foto">\n${img(n, '    ')}\n    <p>{{${cap}}}</p>\n  </div>`;

  /* ---------- codi de la sessió 1 ---------- */
  const S1_FOTOS = (n = 3) => `<h1>{{Les sortides del Club Foto|Las salidas del Club Foto}}</h1>\n<div class="fila">\n${[foto('platja', 'La platja|La playa'), foto('bosc', 'El bosc|El bosque'), foto('pont', 'El pont|El puente'), foto('castell', 'El castell|El castillo')].slice(0, n).join('\n')}\n</div>`;
  const S1_CSS = `body {\n  background: #EAF6F8;\n}\n.foto {\n  background: white;\n  padding: 6px;\n  border-radius: 10px;\n  text-align: center;\n}\nimg {\n  width: 64px;\n}`;
  const BOX3 = `<div class="fila">\n  <div class="c">A</div>\n  <div class="c">B</div>\n  <div class="c">C</div>\n</div>`;
  const BOXC = `.c {\n  background: #E0538F;\n  color: white;\n  padding: 8px;\n}`;
  const NAV = `<nav>\n  <a href="#inici">{{Inici|Inicio}}</a>\n  <a href="#fotos">{{Fotos|Fotos}}</a>\n  <a href="#sortides">{{Sortides|Salidas}}</a>\n  <a href="#club">{{El club|El club}}</a>\n</nav>\n<h1>Club Foto</h1>`;
  const NAV_CSS = `nav {\n  background: #14A3B8;\n  padding: 12px;\n}\nnav a {\n  color: white;\n  font-weight: bold;\n  text-decoration: none;\n}`;
  const COLS = `<h2>{{Properes sortides|Próximas salidas}}</h2>\n<div class="columna">\n  <p class="sortida">{{Dissabte: el moll|Sábado: el muelle}}</p>\n  <p class="sortida">{{Diumenge: el bosc|Domingo: el bosque}}</p>\n  <p class="sortida">{{Dimecres: la platja|Miércoles: la playa}}</p>\n</div>`;
  const COLS_CSS = `.sortida {\n  background: #FFE3B3;\n  padding: 10px;\n  border-radius: 8px;\n  margin: 0;\n}`;

  /* ---------- codi de la sessió 2 ---------- */
  const NUM = (n, c = 'c') => Array.from({ length: n }, (_, i) => `  <div class="${c}">${i + 1}</div>`).join('\n');
  const NUMC = `.c {\n  background: #6C5CE7;\n  color: white;\n  padding: 8px;\n  text-align: center;\n}`;
  const HEAD = `<header>\n  <img src="img/ic/star.webp" alt="{{Logo del Club Foto|Logo del Club Foto}}">\n  <h1>Club Foto</h1>\n  <a href="#apunta">{{Apunta't|Apúntate}}</a>\n</header>`;
  const HEAD_CSS = `header {\n  display: flex;\n  background: #14204A;\n  padding: 10px;\n}\nheader img {\n  width: 56px;\n}\nh1 {\n  color: white;\n  font-size: 22px;\n  margin: 0;\n}\nheader a {\n  background: #FFC531;\n  color: #14204A;\n  padding: 6px 10px;\n  border-radius: 8px;\n}`;
  const GAL6 = `<h2>{{Fotos de l'estiu|Fotos del verano}}</h2>\n<div class="galeria">\n${['platja', 'pont', 'castell', 'ciutat', 'muntanya', 'bosc'].map(n => img(n)).join('\n')}\n</div>`;
  const GAL_IMG = `img {\n  width: 100%;\n  border-radius: 8px;\n}`;
  const PETS = [['cat', 'Gat|Gato'], ['dog', 'Gos|Perro'], ['fox', 'Guineu|Zorro'], ['owl', 'Mussol|Búho'], ['turtle', 'Tortuga|Tortuga'], ['rabbit', 'Conill|Conejo'], ['lion', 'Lleó|León'], ['octopus', 'Pop|Pulpo']];
  const ANIM = n => `<h2>{{Les mascotes del club|Las mascotas del club}}</h2>\n<div class="animals">\n${PETS.slice(0, n).map(([f, a]) => `  <img src="img/ic/${f}.webp" alt="{{${a}}}">`).join('\n')}\n</div>`;
  const ANIM_CSS = `.animals img {\n  width: 100%;\n  background: #FFF3D6;\n  border-radius: 12px;\n}`;

  /* ---------- codi de la sessió 3 ---------- */
  const T_CSS = `table {\n  border-collapse: collapse;\n}\nth, td {\n  border: 1px solid #9AA6C8;\n  padding: 6px;\n}\nth {\n  background-color: #14A3B8;\n  color: white;\n}`;
  const R = (...c) => `  <tr>${c.map(x => `<td>${x}</td>`).join('')}</tr>`;
  const RH = (...c) => `  <tr>${c.map(x => `<th>${x}</th>`).join('')}</tr>`;
  const SORT = [['{{Dissabte|Sábado}}', '{{El moll|El muelle}}', '10:00'], ['{{Diumenge|Domingo}}', '{{El bosc|El bosque}}', '9:30'], ['{{Dimecres|Miércoles}}', '{{La platja|La playa}}', '18:00']];
  const SORT_T = n => `<table>\n  <caption>{{Sortides del club|Salidas del club}}</caption>\n${RH('{{Dia|Día}}', '{{Lloc|Lugar}}', '{{Hora|Hora}}')}\n${SORT.slice(0, n).map(r => R(...r)).join('\n')}\n</table>`;
  const VOTS = [['{{El far|El faro}}', 'Laia', '12'], ['{{La gavina|La gaviota}}', 'Pau', '9'], ['{{La tempesta|La tormenta}}', 'Nil', '15']];
  const VOTS_FAKE = `<table>\n  <tr>\n    <td><b>{{Foto|Foto}}</b></td>\n    <td><b>{{Autor/a|Autor/a}}</b></td>\n    <td><b>{{Vots|Votos}}</b></td>\n  </tr>\n${VOTS.map(r => R(...r)).join('\n')}\n</table>`;
  const VOTS_OK = `<table>\n  <caption>{{Concurs de fotos: els vots|Concurso de fotos: los votos}}</caption>\n${RH('{{Foto|Foto}}', '{{Autor/a|Autor/a}}', '{{Vots|Votos}}')}\n${VOTS.map(r => R(...r)).join('\n')}\n</table>`;

  /* ---------- codi de la sessió 4 ---------- */
  const ALB_HEAD = `<header>\n  <h1>{{L'àlbum del Club Foto|El álbum del Club Foto}}</h1>\n  <nav>\n    <a href="#galeria">{{Galeria|Galería}}</a>\n    <a href="#dades">{{Dades|Datos}}</a>\n    <a href="#club">{{El club|El club}}</a>\n  </nav>\n</header>`;
  const ALB_HEAD_CSS = `header {\n  background: #14204A;\n  padding: 10px 14px;\n}\nh1 {\n  color: white;\n  font-size: 20px;\n  margin: 0;\n}\nnav a {\n  color: #FFC531;\n  font-weight: bold;\n}`;
  const FIGS = [['platja', "La platja, a l'estiu|La playa, en verano"], ['muntanya', 'Excursió a la muntanya|Excursión a la montaña'], ['pont', 'El pont vell|El puente viejo'], ['castell', 'Visita al castell|Visita al castillo'], ['bosc', 'Pícnic al bosc|Pícnic en el bosque'], ['espai', "Nit d'estrelles|Noche de estrellas"]];
  const ALB_GAL = n => `<h2 id="galeria">{{Galeria|Galería}}</h2>\n<div class="galeria">\n${FIGS.slice(0, n).map(([f, c]) => fig(f, c)).join('\n')}\n</div>`;
  const FIG_CSS = `body {\n  background: #EAF6F8;\n}\nfigure {\n  margin: 0;\n  background: white;\n  padding: 6px;\n  border-radius: 10px;\n}\nimg {\n  width: 100%;\n}\nfigcaption {\n  font-size: 14px;\n  text-align: center;\n}`;
  const BUG_HTML = `<header>\n  <h1>{{Àlbum|Álbum}}</h1>\n  <nav>\n    <a href="#galeria">{{Galeria|Galería}}</a>\n    <a href="#dades">{{Dades|Datos}}</a>\n  </nav>\n</header>\n<div class="galeria">\n  <figure>\n${img('castell', '    ')}\n    <figcaption>{{El castell|El castillo}}</figcaption>\n  <figure>\n${img('ciutat', '    ')}\n    <figcaption>{{La ciutat|La ciudad}}</figcaption>\n  </figure>\n</div>`;
  const BUG_CSS = `header {\n  display: flex;\n  justify-content: space between;\n  align-items: center;\n  background: #14204A;\n  color: white;\n  padding: 10px;\n}\nnav a {\n  display: flex;\n  color: #FFC531;\n}\n.galeria {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n  gap: 8px;\n}\nfigure {\n  margin: 0;\n}\nimg {\n  width: 100%;\n}`;
  const ALBUM_CSS = `body {\n  background: #F5F8FF;\n}\nfigure {\n  margin: 0;\n}\nimg {\n  width: 100%;\n  border-radius: 8px;\n}`;

  return BI({ t: 'Disposició|Disposición', d: 'Files, columnes i graelles|Filas, columnas y rejillas', color: '#6C5CE7', s: [
  /* ---------- Sessió 1 · Una al costat de l'altra ---------- */
  { id: 'w6-1', t: "Una al costat de l'altra|Una al lado de la otra", min: 40, badge: 'w_fila',
    learn: ["Amb display: flex al contenidor, els elements de dins es posen en fila, l'un al costat de l'altre.|Con display: flex en el contenedor, los elementos de dentro se ponen en fila, uno al lado del otro.",
      'gap separa els elements, i flex-direction: column els posa en columna.|gap separa los elementos, y flex-direction: column los pone en columna.',
      "justify-content decideix on van dins la fila: a l'inici, al centre, al final o repartits.|justify-content decide dónde van dentro de la fila: al inicio, en el centro, al final o repartidos."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "Recordes les caixes? Quina propietat posa espai <b>a dins</b> de la caixa, entre el contingut i la vora?|¿Recuerdas las cajas? ¿Qué propiedad pone espacio <b>dentro</b> de la caja, entre el contenido y el borde?",
        opts: ['<code>padding</code>|<code>padding</code>', '<code>margin</code>|<code>margin</code>', '<code>border</code>|<code>border</code>'], a: 0,
        ex: "El <code>padding</code> és el farciment de dins. El <code>margin</code> és l'espai de fora, entre una caixa i les altres.|El <code>padding</code> es el relleno de dentro. El <code>margin</code> es el espacio de fuera, entre una caja y las demás." },
      { k: 'wquiz', ph: 'recorda', q: "Tres <code>&lt;div&gt;</code> seguits, sense res més de CSS que el color. <b>Com es veuen?</b>|Tres <code>&lt;div&gt;</code> seguidos, sin nada más de CSS que el color. <b>¿Cómo se ven?</b>",
        code: { html: NUM(3).replace(/^  /gm, ''), css: NUMC },
        opts: [{ html: NUM(3), css: NUMC }, { html: `<div style="display:flex;gap:4px">${NUM(3)}</div>`, css: NUMC }, { html: NUM(3), css: NUMC + '\n.c { width: 30px; margin: 4px auto; }' }], a: 0,
        ex: "Un <code>&lt;div&gt;</code> és una caixa de <b>bloc</b>: ocupa tota l'amplada i la següent comença a sota. Les caixes fan <b>pila</b>.|Un <code>&lt;div&gt;</code> es una caja de <b>bloque</b>: ocupa todo el ancho y la siguiente empieza debajo. Las cajas hacen <b>pila</b>." },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'poble', title: 'El Club Foto|El Club Foto',
        t: "El <b>Club Foto</b> del poble surt cada setmana a fer fotos: a la platja, al bosc, al pont vell… Volen una web per ensenyar-les, però tenen un problema: tot surt <b>una cosa sota l'altra</b>, com una torre llarguíssima. Ens han demanat ajuda!|El <b>Club Foto</b> del pueblo sale cada semana a hacer fotos: a la playa, al bosque, al puente viejo… Quieren una web para enseñarlas, pero tienen un problema: todo sale <b>una cosa debajo de la otra</b>, como una torre larguísima. ¡Nos han pedido ayuda!" },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy',
        t: "BIP! En aquesta unitat seràs el dissenyador/a de la web del club. Avui aprendràs a dir-li al navegador <b>on va cada caixa</b>: en fila, en columna, al centre… Això es diu la <b>disposició</b> d'una pàgina (en anglès, <i>layout</i>).|¡BIP! En esta unidad serás el diseñador/a de la web del club. Hoy aprenderás a decirle al navegador <b>dónde va cada caja</b>: en fila, en columna, en el centro… Esto se llama la <b>disposición</b> de una página (en inglés, <i>layout</i>)." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Caixes en pila|Cajas en pila', t: "Per defecte, una sota l'altra|Por defecto, una debajo de la otra", anim: 'w6stack',
          x: "Ja saps que tot és una caixa. Les caixes de bloc com <code>&lt;div&gt;</code>, <code>&lt;p&gt;</code> o <code>&lt;h1&gt;</code> ocupen tota l'amplada i fan <b>pila</b>. Per posar-les l'una al costat de l'altra, el CSS té una eina: <span class='hl'>flexbox</span>.|Ya sabes que todo es una caja. Las cajas de bloque como <code>&lt;div&gt;</code>, <code>&lt;p&gt;</code> o <code>&lt;h1&gt;</code> ocupan todo el ancho y hacen <b>pila</b>. Para ponerlas una al lado de la otra, el CSS tiene una herramienta: <span class='hl'>flexbox</span>." },
        { k: 'Flexbox|Flexbox', t: 'display: flex|display: flex',
          media: { k: 'web', html: `<div class="fila">\n  <div class="foto">{{Platja|Playa}}</div>\n  <div class="foto">{{Bosc|Bosque}}</div>\n  <div class="foto">{{Pont|Puente}}</div>\n</div>`, css: `.fila {\n  display: flex;\n}\n.foto {\n  background: #FFC531;\n  padding: 10px;\n}` },
          x: "Posa les caixes dins d'una caixa més gran, el <span class='hl'>contenidor</span>, i escriu-hi <code>display: flex;</code>. Les caixes de dins, els <span class='hl'>elements</span>, es posen en fila. Mira-ho a la dreta: tres <code>&lt;div&gt;</code> en fila!|Pon las cajas dentro de una caja más grande, el <span class='hl'>contenedor</span>, y escribe en ella <code>display: flex;</code>. Las cajas de dentro, los <span class='hl'>elementos</span>, se ponen en fila. Míralo: ¡tres <code>&lt;div&gt;</code> en fila!" },
        { k: 'Espai|Espacio', t: "gap: l'espai entre elements|gap: el espacio entre elementos",
          media: { k: 'web', html: `<div class="fila">\n  <div class="foto">{{Platja|Playa}}</div>\n  <div class="foto">{{Bosc|Bosque}}</div>\n  <div class="foto">{{Pont|Puente}}</div>\n</div>`, css: `.fila {\n  display: flex;\n  gap: 16px;\n}\n.foto {\n  background: #FFC531;\n  padding: 10px;\n}` },
          x: "<code>gap</code> (que vol dir «forat») posa el mateix espai <b>entre</b> tots els elements, i no en deixa als extrems. És més fàcil que posar un marge a cada caixa.|<code>gap</code> (que quiere decir «hueco») pone el mismo espacio <b>entre</b> todos los elementos, y no deja en los extremos. Es más fácil que poner un margen a cada caja.",
          tip: "<code>gap</code> també funciona amb la graella que veurem a la sessió següent.|<code>gap</code> también funciona con la rejilla que veremos en la sesión siguiente." },
        { k: 'Compte!|¡Cuidado!', t: 'Al pare, no als fills|Al padre, no a los hijos', anim: 'w6parent',
          x: "Flexbox es posa al <b>contenidor</b>: és el pare qui col·loca els seus fills. Si poses <code>display: flex</code> a cada foto, les fotos no es mouen de lloc.|Flexbox se pone en el <b>contenedor</b>: es el padre quien coloca a sus hijos. Si pones <code>display: flex</code> en cada foto, las fotos no se mueven de sitio.",
          bad: '<code>.foto { display: flex; }</code>: ho poso a cada element.|<code>.foto { display: flex; }</code>: lo pongo en cada elemento.', good: '<code>.fila { display: flex; }</code>: ho poso a la caixa que els conté.|<code>.fila { display: flex; }</code>: lo pongo en la caja que los contiene.' }
      ] },
      { k: 'seq', ph: 'mans', q: "<b>Ordena els passos</b> per posar tres fotos en fila.|<b>Ordena los pasos</b> para poner tres fotos en fila.",
        items: [`A l'HTML, posa les fotos dins d'un contenidor: <code>&lt;div class="fila"&gt;</code>|En el HTML, pon las fotos dentro de un contenedor: <code>&lt;div class="fila"&gt;</code>`,
          'Al CSS, escriu una regla per al contenidor: <code>.fila { }</code>|En el CSS, escribe una regla para el contenedor: <code>.fila { }</code>',
          'A dins de la regla, escriu <code>display: flex;</code>|Dentro de la regla, escribe <code>display: flex;</code>',
          'Afegeix <code>gap: 10px;</code> perquè no quedin enganxades|Añade <code>gap: 10px;</code> para que no queden pegadas'],
        ex: "Primer l'estructura (HTML) i després la disposició (CSS). Sense contenidor, no hi ha ningú que posi les fotos en fila!|Primero la estructura (HTML) y después la disposición (CSS). Sin contenedor, ¡no hay nadie que ponga las fotos en fila!" },
      { k: 'unplug', ph: 'mans', ico: '📦', title: 'Caixes de veritat|Cajas de verdad',
        t: "Amb algú de casa i una safata (o una tapa de capsa) i 4 objectes petits: gots, llibres, fruites…|Con alguien de casa y una bandeja (o una tapa de caja) y 4 objetos pequeños: vasos, libros, frutas…",
        steps: ["La safata és el <b>contenidor</b> i els objectes, els <b>elements</b>. Al principi, posa'ls en pila, l'un darrere l'altre.|La bandeja es el <b>contenedor</b> y los objetos, los <b>elementos</b>. Al principio, ponlos en pila, uno detrás del otro.",
          "L'altra persona diu regles de CSS: <code>display: flex</code>, <code>gap: dos dits</code>, <code>justify-content: center</code>…|La otra persona dice reglas de CSS: <code>display: flex</code>, <code>gap: dos dedos</code>, <code>justify-content: center</code>…",
          'Tu col·loques els objectes com ho faria el navegador. Recorda: la regla és per a la safata, i la safata mou tots els objectes alhora.|Tú colocas los objetos como lo haría el navegador. Recuerda: la regla es para la bandeja, y la bandeja mueve todos los objetos a la vez.',
          "Canvieu els papers i inventeu una regla nova: qui l'endevina?|Cambiad los papeles e inventad una regla nueva: ¿quién la adivina?"],
        tip: "Truc: abans de moure res, digues en veu alta què creus que passarà.|Truco: antes de mover nada, di en voz alta qué crees que pasará." },
      { k: 'wquiz', ph: 'prova', q: "Prediu: <b>quina vista prèvia</b> fa aquest codi?|Predice: <b>¿qué vista previa</b> hace este código?",
        code: { html: BOX3, css: `.fila {\n  display: flex;\n  gap: 20px;\n}\n${BOXC}` },
        opts: [{ html: BOX3, css: `.fila { display: flex; gap: 20px; }\n${BOXC}` }, { html: BOX3, css: `.fila { display: flex; }\n${BOXC}` }, { html: BOX3, css: `.fila { display: flex; flex-direction: column; gap: 20px; }\n${BOXC}` }], a: 0,
        ex: "<code>display: flex</code> les posa en fila i <code>gap: 20px</code> deixa 20 píxels entre l'una i l'altra.|<code>display: flex</code> las pone en fila y <code>gap: 20px</code> deja 20 píxeles entre una y otra." },
      { k: 'wspot', ph: 'investiga', q: "Aquest codi hauria de posar les fotos en fila, però surten en pila. <b>Toca la línia amb l'error.</b>|Este código debería poner las fotos en fila, pero salen en pila. <b>Toca la línea con el error.</b>",
        html: `<div class="fila"></div>\n  <div class="foto">{{Platja|Playa}}</div>\n  <div class="foto">{{Bosc|Bosque}}</div>\n  <div class="foto">{{Pont|Puente}}</div>`,
        css: `.fila { display: flex; gap: 10px; }\n.foto { background: #FFC531; padding: 10px; }`, bad: 1,
        ex: "El contenidor es tanca a la línia 1, abans de les fotos: queda buit i les fotos són fora. El <code>&lt;/div&gt;</code> ha d'anar al final, després de l'última foto.|El contenedor se cierra en la línea 1, antes de las fotos: queda vacío y las fotos están fuera. El <code>&lt;/div&gt;</code> tiene que ir al final, después de la última foto." },
      { k: 'move', ph: 'pausa', secs: 25, t: "Dempeus! Fes de caixa flex: quan diguis <b>row</b>, estira els braços als costats; quan diguis <b>column</b>, aixeca'ls ben amunt; quan diguis <b>center</b>, fes un pas cap al centre. Tres vegades, cada cop més de pressa!|¡De pie! Haz de caja flex: cuando digas <b>row</b>, estira los brazos a los lados; cuando digas <b>column</b>, levántalos bien arriba; cuando digas <b>center</b>, da un paso hacia el centro. ¡Tres veces, cada vez más deprisa!" },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/sortides', tab: 'css', q: "El Club Foto té tres fotos, però surten en pila. Al CSS, escriu una regla perquè el contenidor <code>.fila</code> les posi <b>en fila</b>.|El Club Foto tiene tres fotos, pero salen en pila. En el CSS, escribe una regla para que el contenedor <code>.fila</code> las ponga <b>en fila</b>.",
        html: S1_FOTOS(3), css: S1_CSS, checks: [css('.fila', 'display', FLEX, { txt: 'Una regla <code>.fila { display: flex; }</code>|Una regla <code>.fila { display: flex; }</code>' }), CSSOK],
        snips: [cs('.fila {\n  |\n}'), cs('display: flex;')],
        sol: { css: S1_CSS + '\n.fila {\n  display: flex;\n}' }, hint: "Afegeix al final del CSS una regla nova amb el selector <code>.fila</code> i, a dins, <code>display: flex;</code>|Añade al final del CSS una regla nueva con el selector <code>.fila</code> y, dentro, <code>display: flex;</code>" },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/sortides', q: "Les fotos estan massa enganxades. Afegeix un <code>gap</code> al contenidor i, a l'HTML, posa una <b>quarta foto</b> dins de la fila (per exemple, <code>castell.svg</code>), amb el seu <code>alt</code>.|Las fotos están demasiado pegadas. Añade un <code>gap</code> al contenedor y, en el HTML, pon una <b>cuarta foto</b> dentro de la fila (por ejemplo, <code>castell.svg</code>), con su <code>alt</code>.",
        html: S1_FOTOS(3), css: S1_CSS + '\n.fila {\n  display: flex;\n}',
        checks: [css('.fila', 'gap', null, { txt: 'El contenidor <code>.fila</code> té <code>gap</code>|El contenedor <code>.fila</code> tiene <code>gap</code>' }), { k: 'class', c: 'foto', min: 4, txt: 'Hi ha 4 fotos <code>.foto</code>|Hay 4 fotos <code>.foto</code>' }, alt(4, { txt: 'Les 4 imatges tenen <code>alt</code>|Las 4 imágenes tienen <code>alt</code>' }), CLEAN],
        snips: [`<div class="foto">\n    <img src="img/tech/web/castell.svg" alt="|">\n    <p></p>\n  </div>`, cs('gap: 10px;')],
        sol: { html: S1_FOTOS(4), css: S1_CSS + '\n.fila {\n  display: flex;\n  gap: 10px;\n}' }, hint: "Copia un dels blocs <code>&lt;div class=\"foto\"&gt;…&lt;/div&gt;</code> i enganxa'l just abans del <code>&lt;/div&gt;</code> que tanca la fila. Canvia-hi la imatge, l'<code>alt</code> i el text.|Copia uno de los bloques <code>&lt;div class=\"foto\"&gt;…&lt;/div&gt;</code> y pégalo justo antes del <code>&lt;/div&gt;</code> que cierra la fila. Cambia la imagen, el <code>alt</code> y el texto." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Direcció|Dirección', t: 'flex-direction: row o column|flex-direction: row o column',
          media: { k: 'web', html: `<div class="columna">\n  <div class="c">{{Inici|Inicio}}</div>\n  <div class="c">{{Fotos|Fotos}}</div>\n  <div class="c">{{Sortides|Salidas}}</div>\n</div>`, css: `.columna {\n  display: flex;\n  flex-direction: column;\n  gap: 8px;\n}\n.c {\n  background: #14A3B8;\n  color: white;\n  padding: 8px;\n}` },
          x: "Flex fa una fila (<code>row</code>) si no li dius res. Amb <code>flex-direction: column</code>, els elements van en <b>columna</b>, de dalt a baix. És molt útil per a menús laterals i per a pantalles de mòbil.|Flex hace una fila (<code>row</code>) si no le dices nada. Con <code>flex-direction: column</code>, los elementos van en <b>columna</b>, de arriba abajo. Es muy útil para menús laterales y para pantallas de móvil.",
          tip: "Sembla com al principi? No ben bé: ara hi ha <code>gap</code> i les pots alinear com vulguis.|¿Parece como al principio? No del todo: ahora hay <code>gap</code> y las puedes alinear como quieras." },
        { k: 'On van?|¿Dónde van?', t: 'justify-content|justify-content', anim: 'w6justify',
          x: "<code>justify-content</code> diu on es col·loquen els elements al llarg de la fila: <code>flex-start</code> (a l'inici), <code>center</code> (al centre), <code>flex-end</code> (al final) o <code>space-between</code> (repartits: el primer i l'últim toquen les vores).|<code>justify-content</code> dice dónde se colocan los elementos a lo largo de la fila: <code>flex-start</code> (al inicio), <code>center</code> (en el centro), <code>flex-end</code> (al final) o <code>space-between</code> (repartidos: el primero y el último tocan los bordes)." },
        { k: 'Un menú|Un menú', t: 'Un menú en fila|Un menú en fila',
          media: { k: 'web', html: `<nav>\n  <a href="#">{{Inici|Inicio}}</a>\n  <a href="#">{{Fotos|Fotos}}</a>\n  <a href="#">{{Club|Club}}</a>\n</nav>`, css: `nav {\n  display: flex;\n  justify-content: space-between;\n  background: #14204A;\n  padding: 10px;\n}\nnav a {\n  color: #FFC531;\n}` },
          x: "Molts menús de navegació són això: un <code>&lt;nav&gt;</code> amb enllaços i una regla flex. Amb <code>space-between</code>, els enllaços es reparteixen per tota la barra, sigui ampla o estreta.|Muchos menús de navegación son esto: un <code>&lt;nav&gt;</code> con enlaces y una regla flex. Con <code>space-between</code>, los enlaces se reparten por toda la barra, sea ancha o estrecha." }
      ] },
      { k: 'wquiz', ph: 'prova', q: "I aquest? Fixa't en <code>justify-content</code>.|¿Y este? Fíjate en <code>justify-content</code>.",
        code: { html: BOX3, css: `.fila {\n  display: flex;\n  justify-content: space-between;\n}\n${BOXC}` },
        opts: [{ html: BOX3, css: `.fila { display: flex; }\n${BOXC}` }, { html: BOX3, css: `.fila { display: flex; justify-content: center; }\n${BOXC}` }, { html: BOX3, css: `.fila { display: flex; justify-content: space-between; }\n${BOXC}` }], a: 2,
        ex: "Amb <code>space-between</code>, el primer element toca l'esquerra, l'últim toca la dreta i l'espai que sobra es reparteix entre ells.|Con <code>space-between</code>, el primer elemento toca la izquierda, el último toca la derecha y el espacio que sobra se reparte entre ellos." },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi', q: "Ara tu sol/a: fes el <b>menú del club</b>. Al CSS, fes que el <code>nav</code> sigui flex, que els enllaços es <b>reparteixin</b> per tota la barra (<code>space-between</code>) i que tinguin un <code>gap</code> de 10px.|Ahora tú solo/a: haz el <b>menú del club</b>. En el CSS, haz que el <code>nav</code> sea flex, que los enlaces se <b>repartan</b> por toda la barra (<code>space-between</code>) y que tengan un <code>gap</code> de 10px.",
        html: NAV, css: NAV_CSS, tab: 'css',
        checks: [css('nav', 'display', FLEX), css('nav', 'justify-content', '/^space-between$/', { txt: '<code>nav</code> té <code>justify-content: space-between</code>|<code>nav</code> tiene <code>justify-content: space-between</code>' }), css('nav', 'gap'), CSSOK],
        snips: [cs('display: flex;'), cs('justify-content: |;'), cs('gap: 10px;')],
        sol: { css: `nav {\n  display: flex;\n  justify-content: space-between;\n  gap: 10px;\n  background: #14A3B8;\n  padding: 12px;\n}\nnav a {\n  color: white;\n  font-weight: bold;\n  text-decoration: none;\n}` },
        hint: "Escriu les tres propietats dins de la regla <code>nav { … }</code> que ja hi ha, cadascuna amb els seus dos punts i el seu punt i coma.|Escribe las tres propiedades dentro de la regla <code>nav { … }</code> que ya hay, cada una con sus dos puntos y su punto y coma." },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/sortides', tab: 'css', q: "Caça els errors! Aquesta llista de sortides havia d'anar <b>en columna</b> amb 12px d'espai, però el CSS té <b>tres errors</b>. Troba'ls i arregla'ls.|¡Caza los errores! Esta lista de salidas tenía que ir <b>en columna</b> con 12px de espacio, pero el CSS tiene <b>tres errores</b>. Encuéntralos y arréglalos.",
        html: COLS, css: `.columna {\n  display: flexbox;\n  flex-direction: colum;\n  gap 12px;\n}\n${COLS_CSS}`,
        checks: [css('.columna', 'display', FLEX), css('.columna', 'flex-direction', '/^column$/', { txt: '<code>.columna</code> té <code>flex-direction: column</code>|<code>.columna</code> tiene <code>flex-direction: column</code>' }), css('.columna', 'gap'), CSSOK],
        sol: { css: `.columna {\n  display: flex;\n  flex-direction: column;\n  gap: 12px;\n}\n${COLS_CSS}` },
        hint: "Mira bé cada paraula: el valor és <code>flex</code> (no <code>flexbox</code>), <code>column</code> s'escriu amb una <b>n</b> al final, i entre la propietat i el valor sempre hi ha <b>dos punts</b>.|Mira bien cada palabra: el valor es <code>flex</code> (no <code>flexbox</code>), <code>column</code> se escribe con una <b>n</b> al final, y entre la propiedad y el valor siempre hay <b>dos puntos</b>." },
      { k: 'wcreate', ph: 'crea', url: 'clubfoto.numi', name: 'La capçalera del Club Foto|La cabecera del Club Foto',
        q: "Ara decideixes tu! Fes la part de dalt de la web del club: un títol, un <b>menú en fila</b> i una fila de <b>3 fotos</b> o més, amb el seu nom. Tria els colors, les fotos i on van.|¡Ahora decides tú! Haz la parte de arriba de la web del club: un título, un <b>menú en fila</b> y una fila de <b>3 fotos</b> o más, con su nombre. Elige los colores, las fotos y dónde van.",
        crit: ['El menú és una fila flex amb gap|El menú es una fila flex con gap', 'Una fila flex amb almenys 3 fotos, totes amb alt|Una fila flex con al menos 3 fotos, todas con alt', 'Fas servir justify-content|Usas justify-content'],
        html: `<h1>Club Foto</h1>\n<nav>\n  <a href="#fotos">{{Fotos|Fotos}}</a>\n  <a href="#sortides">{{Sortides|Salidas}}</a>\n</nav>\n<h2>{{Les millors fotos|Las mejores fotos}}</h2>\n<div class="fila">\n${foto('muntanya', 'La muntanya|La montaña')}\n</div>`,
        css: S1_CSS,
        checks: [tag('h1'), css('nav', 'display', FLEX), css('.fila', 'display', FLEX), prop('gap', null, { txt: 'Fas servir <code>gap</code>|Usas <code>gap</code>' }), prop('justify-content', null, { txt: 'Fas servir <code>justify-content</code>|Usas <code>justify-content</code>' }), alt(3, { txt: 'Almenys 3 imatges amb <code>alt</code>|Al menos 3 imágenes con <code>alt</code>' }), CLEAN],
        snips: [`<div class="foto">\n    <img src="img/tech/web/|.svg" alt="">\n    <p></p>\n  </div>`, '<a href="#">|</a>', cs('display: flex;'), cs('justify-content: |;'), cs('gap: 10px;')],
        sol: { html: `<h1>Club Foto</h1>\n<nav>\n  <a href="#fotos">{{Fotos|Fotos}}</a>\n  <a href="#sortides">{{Sortides|Salidas}}</a>\n  <a href="#club">{{El club|El club}}</a>\n</nav>\n<h2>{{Les millors fotos|Las mejores fotos}}</h2>\n<div class="fila">\n${foto('muntanya', 'La muntanya|La montaña')}\n${foto('platja', 'La platja|La playa')}\n${foto('ciutat', 'La ciutat|La ciudad')}\n</div>`,
          css: S1_CSS + `\nnav {\n  display: flex;\n  justify-content: center;\n  gap: 16px;\n  background: #14204A;\n  padding: 10px;\n}\nnav a {\n  color: #FFC531;\n}\n.fila {\n  display: flex;\n  justify-content: center;\n  gap: 10px;\n}` } },
      { k: 'quiz', ph: 'tanca', q: "On s'escriu <code>display: flex</code> per posar unes fotos en fila?|¿Dónde se escribe <code>display: flex</code> para poner unas fotos en fila?",
        opts: ['A la caixa que conté les fotos (el contenidor)|En la caja que contiene las fotos (el contenedor)', 'A cada foto|En cada foto', 'Al títol <code>&lt;h1&gt;</code>|En el título <code>&lt;h1&gt;</code>'], a: 0,
        ex: 'El pare (el contenidor) és qui col·loca els fills.|El padre (el contenedor) es quien coloca a los hijos.' },
      { k: 'quiz', ph: 'tanca', q: "Quina propietat posa <b>el mateix espai</b> entre tots els elements d'una fila flex?|¿Qué propiedad pone <b>el mismo espacio</b> entre todos los elementos de una fila flex?",
        opts: ['<code>gap</code>|<code>gap</code>', '<code>padding</code>|<code>padding</code>', '<code>flex-direction</code>|<code>flex-direction</code>'], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 2 · Graelles ---------- */
  { id: 'w6-2', t: 'Graelles|Rejillas', min: 40, badge: 'w_graella',
    learn: ["align-items col·loca els elements de dalt a baix: amb center, queden centrats.|align-items coloca los elementos de arriba abajo: con center, quedan centrados.",
      'Amb display: grid i grid-template-columns, tu dius les columnes i la graella fa les files sola.|Con display: grid y grid-template-columns, tú dices las columnas y la rejilla hace las filas sola.',
      "1fr és un tros de l'espai que queda: repeat(3, 1fr) fa tres columnes iguals.|1fr es un trozo del espacio que queda: repeat(3, 1fr) hace tres columnas iguales."],
    steps: [
      { k: 'wquiz', ph: 'recorda', q: "Recordes <code>justify-content</code>? Quina vista prèvia fa <code>justify-content: center</code>?|¿Recuerdas <code>justify-content</code>? ¿Qué vista previa hace <code>justify-content: center</code>?",
        code: { html: BOX3, css: `.fila {\n  display: flex;\n  justify-content: center;\n}\n${BOXC}` },
        opts: [{ html: BOX3, css: `.fila { display: flex; justify-content: flex-end; }\n${BOXC}` }, { html: BOX3, css: `.fila { display: flex; justify-content: center; }\n${BOXC}` }, { html: BOX3, css: `.fila { display: flex; justify-content: space-between; }\n${BOXC}` }], a: 1,
        ex: "<code>center</code> ajunta els elements al mig de la fila.|<code>center</code> junta los elementos en el medio de la fila." },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'moll', title: '9 fotos del moll|9 fotos del muelle',
        t: "El Club Foto ha tornat de la sortida al moll amb <b>9 fotos</b> i les vol penjar totes. En una sola fila no hi caben, i en columna la pàgina fa quilòmetres! Necessiten una <b>graella</b>: files i columnes, com una capsa d'ous.|El Club Foto ha vuelto de la salida al muelle con <b>9 fotos</b> y las quiere colgar todas. En una sola fila no caben, ¡y en columna la página mide kilómetros! Necesitan una <b>rejilla</b>: filas y columnas, como una caja de huevos." },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy',
        t: "BIP! Primer arreglarem la capçalera del club, que té el logo i el títol desquadrats. Després, la gran eina d'avui: <b>grid</b>, la graella del CSS.|¡BIP! Primero arreglaremos la cabecera del club, que tiene el logo y el título descuadrados. Después, la gran herramienta de hoy: <b>grid</b>, la rejilla del CSS." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Alinear|Alinear', t: 'align-items: de dalt a baix|align-items: de arriba abajo', anim: 'w6align',
          x: "<code>justify-content</code> mou els elements <b>al llarg de la fila</b> (↔). <code>align-items</code> els mou en l'<b>altra direcció</b> (↕): a dalt (<code>flex-start</code>), al mig (<code>center</code>) o a baix (<code>flex-end</code>). Amb <code>center</code>, un logo gran i un títol petit queden ben alineats.|<code>justify-content</code> mueve los elementos <b>a lo largo de la fila</b> (↔). <code>align-items</code> los mueve en la <b>otra dirección</b> (↕): arriba (<code>flex-start</code>), en medio (<code>center</code>) o abajo (<code>flex-end</code>). Con <code>center</code>, un logo grande y un título pequeño quedan bien alineados." },
        { k: 'Graella|Rejilla', t: 'display: grid|display: grid',
          media: { k: 'web', html: `<div class="galeria">\n${NUM(6)}\n</div>`, css: `.galeria {\n  display: grid;\n  grid-template-columns: 80px 80px 80px;\n  gap: 6px;\n}\n${NUMC}` },
          x: "Amb <code>display: grid</code>, el contenidor es converteix en una <span class='hl'>graella</span>. A <code>grid-template-columns</code> escrius una mida per a cada columna: aquí, 3 columnes de 80px. Tu només dius les columnes: les <b>files es fan soles</b>.|Con <code>display: grid</code>, el contenedor se convierte en una <span class='hl'>rejilla</span>. En <code>grid-template-columns</code> escribes un tamaño para cada columna: aquí, 3 columnas de 80px. Tú solo dices las columnas: las <b>filas se hacen solas</b>." },
        { k: 'La unitat fr|La unidad fr', t: "fr: un tros de l'espai|fr: un trozo del espacio", anim: 'w6fr',
          x: "<code>fr</code> vol dir «fracció»: un tros de l'espai que queda. <code>1fr 2fr 1fr</code> parteix l'amplada en 4 trossos i la columna del mig se n'emporta 2. Com que són trossos i no píxels, la graella s'adapta a qualsevol pantalla.|<code>fr</code> quiere decir «fracción»: un trozo del espacio que queda. <code>1fr 2fr 1fr</code> parte el ancho en 4 trozos y la columna del medio se lleva 2. Como son trozos y no píxeles, la rejilla se adapta a cualquier pantalla." },
        { k: 'repeat()|repeat()', t: 'repeat(): sense repetir-te|repeat(): sin repetirte',
          media: { k: 'web', html: `<div class="galeria">\n${NUM(7)}\n</div>`, css: `.galeria {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 8px;\n}\n${NUMC}` },
          x: "<code>repeat(3, 1fr)</code> és el mateix que <code>1fr 1fr 1fr</code>: tres columnes iguals. Fixa't: hi ha 7 caixes i 3 columnes, i la graella fa <b>3 files</b> ella sola (l'última, amb una caixa).|<code>repeat(3, 1fr)</code> es lo mismo que <code>1fr 1fr 1fr</code>: tres columnas iguales. Fíjate: hay 7 cajas y 3 columnas, y la rejilla hace <b>3 filas</b> ella sola (la última, con una caja)." },
        { k: 'Flex o grid?|¿Flex o grid?', t: 'Una direcció o dues|Una dirección o dos', anim: 'w6grid',
          x: "<b>Flex</b> és per a una sola direcció: una fila (un menú, una capçalera) o una columna. <b>Grid</b> és per a dues direccions alhora: files i columnes, com una galeria de fotos.|<b>Flex</b> es para una sola dirección: una fila (un menú, una cabecera) o una columna. <b>Grid</b> es para dos direcciones a la vez: filas y columnas, como una galería de fotos.",
          bad: 'Per fer una graella de 3 × 3, faig 3 contenidors flex, un per fila.|Para hacer una rejilla de 3 × 3, hago 3 contenedores flex, uno por fila.', good: 'Poso les 9 fotos dins d\'un sol contenidor grid i ell les reparteix en files.|Pongo las 9 fotos dentro de un solo contenedor grid y él las reparte en filas.' }
      ] },
      { k: 'quiz', ph: 'mans', q: "Una galeria té <code>grid-template-columns: repeat(4, 1fr)</code> i <b>10 fotos</b>. Quantes files tindrà?|Una galería tiene <code>grid-template-columns: repeat(4, 1fr)</code> y <b>10 fotos</b>. ¿Cuántas filas tendrá?",
        opts: ['3 files: 4, 4 i 2 fotos|3 filas: 4, 4 y 2 fotos', '4 files de 4 fotos|4 filas de 4 fotos', '10 files, una foto a cada fila|10 filas, una foto en cada fila'], a: 0,
        ex: "La graella omple les files d'esquerra a dreta, i quan una s'acaba en comença una altra. 4 + 4 + 2 = 10.|La rejilla llena las filas de izquierda a derecha, y cuando una se acaba empieza otra. 4 + 4 + 2 = 10." },
      { k: 'unplug', ph: 'mans', ico: '🔍', title: 'Caçadors de graelles|Cazadores de rejillas',
        t: "Les graelles són a tot arreu! Busca'n a casa amb algú de la família.|¡Las rejillas están por todas partes! Busca en casa con alguien de la familia.",
        steps: ["Troba 3 coses que siguin una graella: una capsa d'ous, un calendari, les rajoles de la paret, un teclat, una prestatgeria…|Encuentra 3 cosas que sean una rejilla: una caja de huevos, un calendario, los azulejos de la pared, un teclado, una estantería…",
          "Per a cadascuna, compta quantes <b>columnes</b> i quantes <b>files</b> té.|Para cada una, cuenta cuántas <b>columnas</b> y cuántas <b>filas</b> tiene.",
          "Escriu la regla de CSS que la faria: per exemple, un calendari és <code>repeat(7, 1fr)</code>.|Escribe la regla de CSS que la haría: por ejemplo, un calendario es <code>repeat(7, 1fr)</code>.",
          "Hi ha alguna columna més ampla que les altres? Com ho escriuries amb <code>fr</code>?|¿Hay alguna columna más ancha que las demás? ¿Cómo lo escribirías con <code>fr</code>?"],
        tip: "Una capsa de 12 ous en 2 files de 6 seria grid-template-columns: repeat(6, 1fr).|Una caja de 12 huevos en 2 filas de 6 sería grid-template-columns: repeat(6, 1fr)." },
      { k: 'wquiz', ph: 'prova', q: "Prediu: <b>quina vista prèvia</b> fa aquest codi?|Predice: <b>¿qué vista previa</b> hace este código?",
        code: { html: `<div class="galeria">\n${NUM(4)}\n</div>`, css: `.galeria {\n  display: grid;\n  grid-template-columns: 1fr 2fr;\n  gap: 6px;\n}\n${NUMC}` },
        opts: [{ html: `<div class="galeria">\n${NUM(4)}\n</div>`, css: `.galeria { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; }\n${NUMC}` }, { html: `<div class="galeria">\n${NUM(4)}\n</div>`, css: `.galeria { display: grid; grid-template-columns: 1fr 2fr; gap: 6px; }\n${NUMC}` }, { html: `<div class="galeria">\n${NUM(4)}\n</div>`, css: `.galeria { display: grid; grid-template-columns: 2fr 1fr; gap: 6px; }\n${NUMC}` }], a: 1,
        ex: "Dues columnes: la primera s'emporta 1 tros i la segona, 2. Per això la de la dreta és el doble d'ampla.|Dos columnas: la primera se lleva 1 trozo y la segunda, 2. Por eso la de la derecha es el doble de ancha." },
      { k: 'wspot', ph: 'investiga', preview: false, q: "Aquesta galeria hauria de tenir 3 columnes, però totes les fotos surten en una sola columna. <b>Toca la línia amb l'error.</b>|Esta galería debería tener 3 columnas, pero todas las fotos salen en una sola columna. <b>Toca la línea con el error.</b>",
        css: `.galeria {\n  display: grid;\n  grid-template-columns: 1fr, 1fr, 1fr;\n  gap: 8px;\n}\nimg {\n  width: 100%;\n}`, bad: 3,
        ex: "A <code>grid-template-columns</code>, les columnes se separen amb <b>espais</b>, no amb comes. Amb comes, el navegador no entén la línia i se la salta.|En <code>grid-template-columns</code>, las columnas se separan con <b>espacios</b>, no con comas. Con comas, el navegador no entiende la línea y se la salta." },
      { k: 'move', ph: 'pausa', secs: 25, t: "Fes de graella amb el cos: 3 columnes! Toca l'espatlla esquerra, el pit i l'espatlla dreta (fila 1); després els genolls, la panxa i el cap (fila 2). Ara més de pressa!|Haz de rejilla con el cuerpo: ¡3 columnas! Toca el hombro izquierdo, el pecho y el hombro derecho (fila 1); después las rodillas, la barriga y la cabeza (fila 2). ¡Ahora más deprisa!" },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi', tab: 'css', q: "La capçalera ja és flex, però el logo, el títol i el botó estan desquadrats. Centra'ls <b>de dalt a baix</b> amb <code>align-items</code> i reparteix-los per la barra amb <code>justify-content</code>.|La cabecera ya es flex, pero el logo, el título y el botón están descuadrados. Céntralos <b>de arriba abajo</b> con <code>align-items</code> y repártelos por la barra con <code>justify-content</code>.",
        html: HEAD, css: HEAD_CSS,
        checks: [css('header', 'align-items', '/^center$/', { txt: '<code>header</code> té <code>align-items: center</code>|<code>header</code> tiene <code>align-items: center</code>' }), css('header', 'justify-content', '/^space-between$/', { txt: '<code>header</code> té <code>justify-content: space-between</code>|<code>header</code> tiene <code>justify-content: space-between</code>' }), CSSOK],
        snips: [cs('align-items: center;'), cs('justify-content: space-between;')],
        sol: { css: HEAD_CSS.replace('  display: flex;\n', '  display: flex;\n  justify-content: space-between;\n  align-items: center;\n') },
        hint: "Les dues propietats van dins de la regla <code>header { … }</code>, perquè la capçalera és el contenidor.|Las dos propiedades van dentro de la regla <code>header { … }</code>, porque la cabecera es el contenedor." },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/galeria', tab: 'css', q: "Sis fotos de l'estiu, enormes i en pila. Converteix <code>.galeria</code> en una <b>graella de 3 columnes iguals</b>.|Seis fotos del verano, enormes y en pila. Convierte <code>.galeria</code> en una <b>rejilla de 3 columnas iguales</b>.",
        html: GAL6, css: `.galeria {\n  gap: 8px;\n}\n${GAL_IMG}`,
        checks: [css('.galeria', 'display', GRID), css('.galeria', 'grid-template-columns', COL3, { txt: '<code>.galeria</code> té <code>grid-template-columns</code> amb 3 columnes|<code>.galeria</code> tiene <code>grid-template-columns</code> con 3 columnas' }), CSSOK],
        snips: [cs('display: grid;'), cs('grid-template-columns: |;'), cs('repeat(3, 1fr)')],
        sol: { css: `.galeria {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 8px;\n}\n${GAL_IMG}` },
        hint: "Dins de <code>.galeria</code> escriu <code>display: grid;</code> i, a sota, <code>grid-template-columns: repeat(3, 1fr);</code>|Dentro de <code>.galeria</code> escribe <code>display: grid;</code> y, debajo, <code>grid-template-columns: repeat(3, 1fr);</code>" },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/mascotes', q: "Les mascotes del club! Afegeix-ne <b>2 més</b> a l'HTML (en tens a <code>img/ic/</code>: <code>lion</code>, <code>octopus</code>, <code>eagle</code>, <code>chick</code>…) i escriu tu sol/a la graella: <b>4 columnes iguals</b> i un <code>gap</code>.|¡Las mascotas del club! Añade <b>2 más</b> en el HTML (tienes en <code>img/ic/</code>: <code>lion</code>, <code>octopus</code>, <code>eagle</code>, <code>chick</code>…) y escribe tú solo/a la rejilla: <b>4 columnas iguales</b> y un <code>gap</code>.",
        html: ANIM(6), css: ANIM_CSS,
        checks: [inn('img', 'div', { min: 8, txt: 'Hi ha 8 mascotes a la graella|Hay 8 mascotas en la rejilla' }), alt(8, { txt: 'Les 8 imatges tenen <code>alt</code>|Las 8 imágenes tienen <code>alt</code>' }), css('.animals', 'display', GRID), css('.animals', 'grid-template-columns', COL4, { txt: '<code>.animals</code> té 4 columnes|<code>.animals</code> tiene 4 columnas' }), css('.animals', 'gap'), CLEAN],
        snips: ['<img src="img/ic/|.webp" alt="">', cs('.animals {\n  |\n}'), cs('display: grid;'), cs('grid-template-columns: |;'), cs('gap: 10px;')],
        sol: { html: ANIM(8), css: `.animals {\n  display: grid;\n  grid-template-columns: repeat(4, 1fr);\n  gap: 10px;\n}\n${ANIM_CSS}` },
        hint: "Fes una regla nova <code>.animals { … }</code> (sense <code>img</code>: és el contenidor) amb <code>display</code>, <code>grid-template-columns</code> i <code>gap</code>.|Haz una regla nueva <code>.animals { … }</code> (sin <code>img</code>: es el contenedor) con <code>display</code>, <code>grid-template-columns</code> y <code>gap</code>." },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/galeria', tab: 'css', q: "Caça els errors! Aquesta graella té <b>tres errors</b> al CSS i no funciona. Arregla'ls perquè surtin 3 columnes amb espai entre les fotos.|¡Caza los errores! Esta rejilla tiene <b>tres errores</b> en el CSS y no funciona. Arréglalos para que salgan 3 columnas con espacio entre las fotos.",
        html: GAL6, css: `.galeria {\n  display: grip;\n  grid-template-columns: 1fr, 1fr, 1fr;\n  gap: 10;\n}\n${GAL_IMG}`,
        checks: [css('.galeria', 'display', GRID), css('.galeria', 'grid-template-columns', '/^[^,]*fr[^,]*$/', { txt: 'Les columnes amb <code>fr</code> i separades amb espais (sense comes)|Las columnas con <code>fr</code> y separadas con espacios (sin comas)' }), css('.galeria', 'gap', '/^\\d+(\\.\\d+)?[a-z%]+$/', { txt: 'El <code>gap</code> té unitat (per exemple, <code>10px</code>)|El <code>gap</code> tiene unidad (por ejemplo, <code>10px</code>)' })],
        sol: { css: `.galeria {\n  display: grid;\n  grid-template-columns: 1fr 1fr 1fr;\n  gap: 10px;\n}\n${GAL_IMG}` },
        hint: "Un error és una lletra, un altre són unes comes que sobren i l'últim és una unitat que falta. Els números de mida, si no són 0, sempre porten unitat: <code>px</code>.|Un error es una letra, otro son unas comas que sobran y el último es una unidad que falta. Los números de tamaño, si no son 0, siempre llevan unidad: <code>px</code>." },
      { k: 'wcreate', ph: 'crea', url: 'clubfoto.numi/la-meva-sortida', name: 'La meva galeria|Mi galería',
        q: "Inventa't una sortida del club i fes-ne la <b>galeria</b>: un títol, unes línies explicant-la i una graella amb <b>almenys 6 fotos</b>. Tu tries quantes columnes i com d'amples (amb <code>fr</code>).|Invéntate una salida del club y haz su <b>galería</b>: un título, unas líneas explicándola y una rejilla con <b>al menos 6 fotos</b>. Tú eliges cuántas columnas y cómo de anchas (con <code>fr</code>).",
        crit: ['Una graella amb display: grid|Una rejilla con display: grid', 'Columnes amb fr i un gap|Columnas con fr y un gap', 'Almenys 6 fotos, totes amb alt|Al menos 6 fotos, todas con alt'],
        html: `<h1>{{La meva sortida|Mi salida}}</h1>\n<p>{{Explica on vau anar i què vau veure.|Explica adónde fuisteis y qué visteis.}}</p>\n<div class="galeria">\n${img('platja')}\n</div>`,
        css: `body {\n  background: #F5F8FF;\n}\nimg {\n  width: 100%;\n  border-radius: 10px;\n}`,
        checks: [tag('h1'), prop('display', GRID, { txt: 'Hi ha un contenidor amb <code>display: grid</code>|Hay un contenedor con <code>display: grid</code>' }), prop('grid-template-columns', '/fr/', { txt: 'Les columnes fan servir <code>fr</code>|Las columnas usan <code>fr</code>' }), prop('gap', null, { txt: 'Fas servir <code>gap</code>|Usas <code>gap</code>' }), alt(6, { txt: 'Almenys 6 fotos amb <code>alt</code>|Al menos 6 fotos con <code>alt</code>' }), CLEAN],
        snips: ['<img src="img/tech/web/|.svg" alt="">', cs('display: grid;'), cs('grid-template-columns: |;'), cs('gap: 8px;')],
        sol: { html: `<h1>{{Excursió a la muntanya|Excursión a la montaña}}</h1>\n<p>{{Vam pujar fins al castell i vam tornar pel pont.|Subimos hasta el castillo y volvimos por el puente.}}</p>\n<div class="galeria">\n${['platja', 'muntanya', 'bosc', 'castell', 'pont', 'seu'].map(n => img(n)).join('\n')}\n</div>`,
          css: `body {\n  background: #F5F8FF;\n}\nimg {\n  width: 100%;\n  border-radius: 10px;\n}\n.galeria {\n  display: grid;\n  grid-template-columns: 2fr 1fr 1fr;\n  gap: 8px;\n}` } },
      { k: 'quiz', ph: 'tanca', q: "Què fa <code>grid-template-columns: repeat(3, 1fr)</code>?|¿Qué hace <code>grid-template-columns: repeat(3, 1fr)</code>?",
        opts: ['Tres columnes iguals que es reparteixen l\'amplada|Tres columnas iguales que se reparten el ancho', 'Tres files d\'un píxel|Tres filas de un píxel', 'Repeteix tres vegades cada foto|Repite tres veces cada foto'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "Vols centrar el logo i el títol d'una capçalera flex <b>de dalt a baix</b>. Quina propietat fas servir?|Quieres centrar el logo y el título de una cabecera flex <b>de arriba abajo</b>. ¿Qué propiedad usas?",
        opts: ['<code>align-items: center</code>|<code>align-items: center</code>', '<code>justify-content: center</code>|<code>justify-content: center</code>', '<code>text-align: center</code>|<code>text-align: center</code>'], a: 0,
        ex: "<code>justify-content</code> va al llarg de la fila (↔) i <code>align-items</code>, de dalt a baix (↕).|<code>justify-content</code> va a lo largo de la fila (↔) y <code>align-items</code>, de arriba abajo (↕)." },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 3 · Taules ---------- */
  { id: 'w6-3', t: 'Taules|Tablas', min: 40, badge: 'w_taula',
    learn: ['Una taula és per a dades en files i columnes, com un horari o uns resultats; no per col·locar fotos.|Una tabla es para datos en filas y columnas, como un horario o unos resultados; no para colocar fotos.',
      '<code>&lt;table&gt;</code> té files <code>&lt;tr&gt;</code>; cada fila té cel·les <code>&lt;td&gt;</code>, i les capçaleres són <code>&lt;th&gt;</code>.|<code>&lt;table&gt;</code> tiene filas <code>&lt;tr&gt;</code>; cada fila tiene celdas <code>&lt;td&gt;</code>, y las cabeceras son <code>&lt;th&gt;</code>.',
      'Amb <code>&lt;caption&gt;</code> i <code>&lt;th&gt;</code>, un lector de pantalla pot explicar la taula a qui no la veu.|Con <code>&lt;caption&gt;</code> y <code>&lt;th&gt;</code>, un lector de pantalla puede explicar la tabla a quien no la ve.'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "Tens 8 fotos en una graella amb <code>grid-template-columns: repeat(4, 1fr)</code>. Quantes files surten?|Tienes 8 fotos en una rejilla con <code>grid-template-columns: repeat(4, 1fr)</code>. ¿Cuántas filas salen?",
        opts: ['2 files de 4|2 filas de 4', '4 files de 2|4 filas de 2', '1 fila de 8|1 fila de 8'], a: 0, ex: 'Tu dius les columnes (4) i la graella fa les files que calguin: 8 ÷ 4 = 2.|Tú dices las columnas (4) y la rejilla hace las filas que hagan falta: 8 ÷ 4 = 2.' },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'taller', title: 'La llibreta del club|La libreta del club',
        t: "El Club Foto apunta les sortides en una llibreta: «dissabte al moll a les 10, diumenge al bosc a les 9 i mitja, dimecres a la platja…». Tot seguit, sense ordre. Ningú no ho troba! Cada sortida té tres dades: el <b>dia</b>, el <b>lloc</b> i l'<b>hora</b>.|El Club Foto apunta las salidas en una libreta: «sábado en el muelle a las 10, domingo en el bosque a las 9 y media, miércoles en la playa…». Todo seguido, sin orden. ¡Nadie lo encuentra! Cada salida tiene tres datos: el <b>día</b>, el <b>lugar</b> y la <b>hora</b>." },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy',
        t: "BIP! Quan la informació té <b>files i columnes</b> (cada fila és una sortida i cada columna, un tipus de dada), no és una galeria: és una <b>taula</b>. L'HTML té etiquetes especials per fer-ne.|¡BIP! Cuando la información tiene <b>filas y columnas</b> (cada fila es una salida y cada columna, un tipo de dato), no es una galería: es una <b>tabla</b>. El HTML tiene etiquetas especiales para hacerlas." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Dades en taula|Datos en tabla', t: 'Quan cal una taula?|¿Cuándo hace falta una tabla?', pic: 'img/ment/com.webp',
          x: "El tiquet de la compra, l'horari de classe o la classificació d'una lliga són <span class='hl'>taules</span>: cada <b>fila</b> és una cosa (un producte, un dia, un equip) i cada <b>columna</b> és un tipus de dada (el nom, el preu, els punts).|El tique de la compra, el horario de clase o la clasificación de una liga son <span class='hl'>tablas</span>: cada <b>fila</b> es una cosa (un producto, un día, un equipo) y cada <b>columna</b> es un tipo de dato (el nombre, el precio, los puntos).",
          bad: "Faig servir una taula per col·locar les fotos d'una galeria.|Uso una tabla para colocar las fotos de una galería.", good: 'Taula per a dades; grid o flex per col·locar fotos i caixes.|Tabla para datos; grid o flex para colocar fotos y cajas.' },
        { k: 'Etiquetes|Etiquetas', t: 'table, tr i td|table, tr y td', anim: 'w6table',
          x: "<code>&lt;table&gt;</code> és la taula sencera. A dins, cada <code>&lt;tr&gt;</code> (<i>table row</i>) és una <b>fila</b>, i cada <code>&lt;td&gt;</code> (<i>table data</i>) és una <b>cel·la</b> d'aquella fila. Totes les files han de tenir el mateix nombre de cel·les.|<code>&lt;table&gt;</code> es la tabla entera. Dentro, cada <code>&lt;tr&gt;</code> (<i>table row</i>) es una <b>fila</b>, y cada <code>&lt;td&gt;</code> (<i>table data</i>) es una <b>celda</b> de esa fila. Todas las filas tienen que tener el mismo número de celdas." },
        { k: 'Capçaleres|Cabeceras', t: 'th i caption|th y caption',
          media: { k: 'web', html: SORT_T(2), css: T_CSS },
          x: "La primera fila diu què hi ha a cada columna: les seves cel·les són <code>&lt;th&gt;</code> (<i>table header</i>), i el navegador les posa en negreta. <code>&lt;caption&gt;</code> és el títol de la taula i va just després de <code>&lt;table&gt;</code>.|La primera fila dice qué hay en cada columna: sus celdas son <code>&lt;th&gt;</code> (<i>table header</i>), y el navegador las pone en negrita. <code>&lt;caption&gt;</code> es el título de la tabla y va justo después de <code>&lt;table&gt;</code>." },
        { k: 'Accessibilitat|Accesibilidad', t: "Taules que s'entenen sense veure-les|Tablas que se entienden sin verlas", anim: 'w6reader',
          x: "Algunes persones naveguen amb un <span class='hl'>lector de pantalla</span>, un programa que llegeix la web en veu alta. Gràcies als <code>&lt;th&gt;</code>, pot dir «Lloc: el bosc» i no només «el bosc». Per això les capçaleres han de ser <code>th</code>, i no <code>td</code> amb negreta.|Algunas personas navegan con un <span class='hl'>lector de pantalla</span>, un programa que lee la web en voz alta. Gracias a los <code>&lt;th&gt;</code>, puede decir «Lugar: el bosque» y no solo «el bosque». Por eso las cabeceras tienen que ser <code>th</code>, y no <code>td</code> con negrita." },
        { k: 'Estil|Estilo', t: 'Vores i espais a la taula|Bordes y espacios en la tabla',
          media: { k: 'web', html: SORT_T(2), css: T_CSS },
          x: "Les taules no tenen vores per defecte. Fes servir el que ja saps de les caixes: <code>border</code> i <code>padding</code> a <code>th, td</code>. I <code>border-collapse: collapse</code> ajunta les vores dobles de les cel·les en una de sola.|Las tablas no tienen bordes por defecto. Usa lo que ya sabes de las cajas: <code>border</code> y <code>padding</code> en <code>th, td</code>. Y <code>border-collapse: collapse</code> junta los bordes dobles de las celdas en uno solo.",
          tip: "<code>th, td { … }</code> és una regla per a dos selectors alhora: la coma vol dir «i també».|<code>th, td { … }</code> es una regla para dos selectores a la vez: la coma quiere decir «y también»." }
      ] },
      { k: 'seq', ph: 'mans', q: "<b>Ordena les línies</b> d'aquesta taula, de dalt a baix.|<b>Ordena las líneas</b> de esta tabla, de arriba abajo.",
        items: ['<code>&lt;table&gt;</code>|<code>&lt;table&gt;</code>', '<code>&lt;caption&gt;Sortides&lt;/caption&gt;</code>|<code>&lt;caption&gt;Salidas&lt;/caption&gt;</code>',
          '<code>&lt;tr&gt;&lt;th&gt;Dia&lt;/th&gt;&lt;th&gt;Lloc&lt;/th&gt;&lt;/tr&gt;</code>|<code>&lt;tr&gt;&lt;th&gt;Día&lt;/th&gt;&lt;th&gt;Lugar&lt;/th&gt;&lt;/tr&gt;</code>',
          '<code>&lt;tr&gt;&lt;td&gt;Dissabte&lt;/td&gt;&lt;td&gt;El moll&lt;/td&gt;&lt;/tr&gt;</code>|<code>&lt;tr&gt;&lt;td&gt;Sábado&lt;/td&gt;&lt;td&gt;El muelle&lt;/td&gt;&lt;/tr&gt;</code>', '<code>&lt;/table&gt;</code>|<code>&lt;/table&gt;</code>'],
        ex: "Primer s'obre la taula, després el títol, la fila de capçaleres, les files de dades i, al final, es tanca.|Primero se abre la tabla, después el título, la fila de cabeceras, las filas de datos y, al final, se cierra." },
      { k: 'quiz', ph: 'investiga', q: "Quina d'aquestes coses <b>sí</b> que hauria de ser una taula?|¿Cuál de estas cosas <b>sí</b> debería ser una tabla?",
        opts: ['Els resultats del concurs: foto, autor/a i vots de cada foto|Los resultados del concurso: foto, autor/a y votos de cada foto', 'La galeria de fotos de la sortida|La galería de fotos de la salida', 'El menú de navegació de la web|El menú de navegación de la web'], a: 0,
        ex: "Els resultats es llegeixen per files (cada foto) i per columnes (cada dada): són dades de taula. La galeria es fa amb grid i el menú, amb flex.|Los resultados se leen por filas (cada foto) y por columnas (cada dato): son datos de tabla. La galería se hace con grid y el menú, con flex." },
      { k: 'unplug', ph: 'mans', ico: '📅', title: 'Taules amagades|Tablas escondidas',
        t: "A casa hi ha moltes taules que no semblen taules. Busca-les amb algú de la família.|En casa hay muchas tablas que no parecen tablas. Búscalas con alguien de la familia.",
        steps: ["Troba 3 taules de veritat: un tiquet de la compra, un horari, un calendari, la informació nutricional d'un paquet de galetes…|Encuentra 3 tablas de verdad: un tique de la compra, un horario, un calendario, la información nutricional de un paquete de galletas…",
          'Per a cadascuna, digues què és cada <b>fila</b> i què és cada <b>columna</b>.|Para cada una, di qué es cada <b>fila</b> y qué es cada <b>columna</b>.',
          'Quines són les capçaleres (els <code>th</code>)? Té títol (<code>caption</code>)?|¿Cuáles son las cabeceras (los <code>th</code>)? ¿Tiene título (<code>caption</code>)?',
          "Llegeix-ne una fila en veu alta com un lector de pantalla: «Producte: pomes. Preu: 2 euros».|Lee una fila en voz alta como un lector de pantalla: «Producto: manzanas. Precio: 2 euros»."] },
      { k: 'wquiz', ph: 'prova', q: "Prediu: <b>quina vista prèvia</b> fa aquesta taula?|Predice: <b>¿qué vista previa</b> hace esta tabla?",
        code: { html: `<table>\n${RH('{{Foto|Foto}}', '{{Vots|Votos}}')}\n${R('{{El far|El faro}}', '12')}\n${R('{{La gavina|La gaviota}}', '9')}\n</table>`, css: T_CSS },
        opts: [{ html: `<table>\n${RH('{{Foto|Foto}}', '{{Vots|Votos}}')}\n${R('{{El far|El faro}}', '12')}\n${R('{{La gavina|La gaviota}}', '9')}\n</table>`, css: T_CSS },
          { html: `<table>\n  <tr><th>{{Foto|Foto}}</th><td>{{El far|El faro}}</td><td>{{La gavina|La gaviota}}</td></tr>\n  <tr><th>{{Vots|Votos}}</th><td>12</td><td>9</td></tr>\n</table>`, css: T_CSS },
          { html: `<table>\n  <tr><th>{{Foto|Foto}}</th><th>{{Vots|Votos}}</th><td>{{El far|El faro}}</td><td>12</td><td>{{La gavina|La gaviota}}</td><td>9</td></tr>\n</table>`, css: T_CSS }], a: 0,
        ex: "Cada <code>&lt;tr&gt;</code> és una fila, de dalt a baix: primer la de capçaleres i després una fila per a cada foto.|Cada <code>&lt;tr&gt;</code> es una fila, de arriba abajo: primero la de cabeceras y después una fila para cada foto." },
      { k: 'wspot', ph: 'investiga', q: "A la vista prèvia, «9:30» surt a la columna del lloc! <b>Toca la línia amb l'error.</b>|En la vista previa, ¡«9:30» sale en la columna del lugar! <b>Toca la línea con el error.</b>",
        html: `<table>\n${RH('{{Dia|Día}}', '{{Lloc|Lugar}}', '{{Hora|Hora}}')}\n${R(...SORT[0])}\n${R(SORT[1][0], SORT[1][2])}\n${R(...SORT[2])}\n</table>`, css: T_CSS, bad: 4,
        ex: "A la fila de la línia 4 falta la cel·la del lloc: només té dues <code>&lt;td&gt;</code>, i les cel·les s'omplen per ordre. Cada fila ha de tenir una cel·la per a cada columna.|En la fila de la línea 4 falta la celda del lugar: solo tiene dos <code>&lt;td&gt;</code>, y las celdas se llenan por orden. Cada fila tiene que tener una celda para cada columna." },
      { k: 'move', ph: 'pausa', secs: 25, t: "Taula humana! Imagina que ets una cel·la: aixeca el braç dret si ets de la fila de capçaleres, el braç esquerre si ets d'una fila de dades, i salta si ets el <code>caption</code>. Fes-ho 3 vegades canviant de paper.|¡Tabla humana! Imagina que eres una celda: levanta el brazo derecho si eres de la fila de cabeceras, el brazo izquierdo si eres de una fila de datos, y salta si eres el <code>caption</code>. Hazlo 3 veces cambiando de papel." },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/sortides', q: "Falta una sortida a la taula! Afegeix una <b>fila nova</b> al final: <b>dimecres, a la platja, a les 18:00</b>.|¡Falta una salida en la tabla! Añade una <b>fila nueva</b> al final: <b>miércoles, en la playa, a las 18:00</b>.",
        html: SORT_T(2), css: T_CSS,
        checks: [tag('tr', { min: 4, txt: 'Hi ha 4 files <code>&lt;tr&gt;</code>|Hay 4 filas <code>&lt;tr&gt;</code>' }), inn('td', 'tr', { min: 9, txt: 'Hi ha 9 cel·les <code>&lt;td&gt;</code> dins de files|Hay 9 celdas <code>&lt;td&gt;</code> dentro de filas' }), CLEAN],
        snips: ['<tr><td>|</td><td></td><td></td></tr>', '<td>|</td>'],
        sol: { html: SORT_T(3) },
        hint: "Copia l'última fila <code>&lt;tr&gt;…&lt;/tr&gt;</code>, enganxa-la just abans de <code>&lt;/table&gt;</code> i canvia'n les tres dades.|Copia la última fila <code>&lt;tr&gt;…&lt;/tr&gt;</code>, pégala justo antes de <code>&lt;/table&gt;</code> y cambia sus tres datos." },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/concurs', q: "Aquesta taula fa trampa: les capçaleres són <code>&lt;td&gt;</code> amb <code>&lt;b&gt;</code>, i un lector de pantalla no les reconeix. Canvia-les per <code>&lt;th&gt;</code> (sense <code>&lt;b&gt;</code>) i posa-hi un títol amb <code>&lt;caption&gt;</code>.|Esta tabla hace trampa: las cabeceras son <code>&lt;td&gt;</code> con <code>&lt;b&gt;</code>, y un lector de pantalla no las reconoce. Cámbialas por <code>&lt;th&gt;</code> (sin <code>&lt;b&gt;</code>) y ponle un título con <code>&lt;caption&gt;</code>.",
        html: VOTS_FAKE, css: T_CSS,
        checks: [tag('th', { min: 3, txt: 'Hi ha 3 capçaleres <code>&lt;th&gt;</code>|Hay 3 cabeceras <code>&lt;th&gt;</code>' }), notag('b', { txt: 'Ja no hi ha cap <code>&lt;b&gt;</code>|Ya no hay ningún <code>&lt;b&gt;</code>' }), tag('caption', { txt: 'La taula té <code>&lt;caption&gt;</code>|La tabla tiene <code>&lt;caption&gt;</code>' }), { k: 'order', a: 'caption', b: 'tr', txt: 'El <code>&lt;caption&gt;</code> va abans de les files|El <code>&lt;caption&gt;</code> va antes de las filas' }, CLEAN],
        snips: ['<th>|</th>', '<caption>|</caption>'],
        sol: { html: VOTS_OK },
        hint: "Canvia <code>&lt;td&gt;&lt;b&gt;Foto&lt;/b&gt;&lt;/td&gt;</code> per <code>&lt;th&gt;Foto&lt;/th&gt;</code>, i el mateix amb les altres dues. El <code>&lt;caption&gt;</code> va just després de <code>&lt;table&gt;</code>.|Cambia <code>&lt;td&gt;&lt;b&gt;Foto&lt;/b&gt;&lt;/td&gt;</code> por <code>&lt;th&gt;Foto&lt;/th&gt;</code>, y lo mismo con las otras dos. El <code>&lt;caption&gt;</code> va justo después de <code>&lt;table&gt;</code>." },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/concurs', tab: 'css', q: "Ara, l'estil, tu sol/a: ajunta les vores de la taula (<code>border-collapse</code>), posa vora i <code>padding</code> a les cel·les (<code>th, td</code>) i un color de fons a les capçaleres amb <code>background-color</code>.|Ahora, el estilo, tú solo/a: junta los bordes de la tabla (<code>border-collapse</code>), pon borde y <code>padding</code> a las celdas (<code>th, td</code>) y un color de fondo a las cabeceras con <code>background-color</code>.",
        html: VOTS_OK, css: `body {\n  font-family: sans-serif;\n}`,
        checks: [css('table', 'border-collapse', '/^collapse$/', { txt: '<code>table</code> té <code>border-collapse: collapse</code>|<code>table</code> tiene <code>border-collapse: collapse</code>' }), sty('td', 'border', null, { txt: 'Les cel·les <code>td</code> tenen <code>border</code>|Las celdas <code>td</code> tienen <code>border</code>' }), sty('td', 'padding', null, { txt: 'Les cel·les <code>td</code> tenen <code>padding</code>|Las celdas <code>td</code> tienen <code>padding</code>' }), sty('th', 'background-color', null, { txt: 'Les capçaleres <code>th</code> tenen <code>background-color</code>|Las cabeceras <code>th</code> tienen <code>background-color</code>' }), CSSOK],
        snips: [cs('table {\n  |\n}'), cs('th, td {\n  |\n}'), cs('border: 1px solid |;'), cs('padding: 6px;'), cs('background-color: |;')],
        sol: { css: `body {\n  font-family: sans-serif;\n}\n${T_CSS}` },
        hint: "Tres regles: <code>table { … }</code> per a <code>border-collapse</code>, <code>th, td { … }</code> per a la vora i el farciment, i <code>th { … }</code> per al color de fons.|Tres reglas: <code>table { … }</code> para <code>border-collapse</code>, <code>th, td { … }</code> para el borde y el relleno, y <code>th { … }</code> para el color de fondo." },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/concurs', q: "Caça els errors! Aquesta taula té <b>dues etiquetes mal tancades</b>. Llegeix el missatge d'avís, troba-les i arregla-les.|¡Caza los errores! Esta tabla tiene <b>dos etiquetas mal cerradas</b>. Lee el mensaje de aviso, encuéntralas y arréglalas.",
        html: `<table>\n  <caption>{{Punts del concurs de fotos|Puntos del concurso de fotos}}</caption>\n  <tr>\n    <th>{{Foto|Foto}}</th>\n    <th>{{Autor/a|Autor/a}}</th>\n    <th>{{Punts|Puntos}}</td>\n  </tr>\n  <tr>\n    <td>{{El far|El faro}}</td>\n    <td>Laia</td>\n    <td>8</td>\n  <tr>\n    <td>{{La gavina|La gaviota}}</td>\n    <td>Pau</td>\n    <td>9</td>\n  </tr>\n</table>`, css: T_CSS,
        checks: [CLEAN, tag('th', { min: 3 }), inn('td', 'tr', { min: 6 }), tag('tr', { min: 3 })],
        sol: { html: `<table>\n  <caption>{{Punts del concurs de fotos|Puntos del concurso de fotos}}</caption>\n  <tr>\n    <th>{{Foto|Foto}}</th>\n    <th>{{Autor/a|Autor/a}}</th>\n    <th>{{Punts|Puntos}}</th>\n  </tr>\n  <tr>\n    <td>{{El far|El faro}}</td>\n    <td>Laia</td>\n    <td>8</td>\n  </tr>\n  <tr>\n    <td>{{La gavina|La gaviota}}</td>\n    <td>Pau</td>\n    <td>9</td>\n  </tr>\n</table>` },
        hint: "Una cel·la <code>&lt;th&gt;</code> es tanca amb <code>&lt;/th&gt;</code>, no amb <code>&lt;/td&gt;</code>. I cada <code>&lt;tr&gt;</code> s'ha de tancar amb <code>&lt;/tr&gt;</code> abans d'obrir la fila següent.|Una celda <code>&lt;th&gt;</code> se cierra con <code>&lt;/th&gt;</code>, no con <code>&lt;/td&gt;</code>. Y cada <code>&lt;tr&gt;</code> se tiene que cerrar con <code>&lt;/tr&gt;</code> antes de abrir la fila siguiente." },
      { k: 'wcreate', ph: 'crea', url: 'clubfoto.numi/la-meva-taula', name: 'La meva taula|Mi tabla',
        q: "Fes una taula amb dades de veritat: el teu horari de la setmana, els resultats d'un concurs de la classe, les fotos que faries en una sortida… Ha de tenir títol (<code>caption</code>), capçaleres (<code>th</code>), <b>almenys 3 files de dades</b> i estil.|Haz una tabla con datos de verdad: tu horario de la semana, los resultados de un concurso de la clase, las fotos que harías en una salida… Tiene que tener título (<code>caption</code>), cabeceras (<code>th</code>), <b>al menos 3 filas de datos</b> y estilo.",
        crit: ['Un caption amb el títol de la taula|Un caption con el título de la tabla', 'Una fila de capçaleres th i almenys 3 files de dades|Una fila de cabeceras th y al menos 3 filas de datos', 'Estil: vores juntes i padding a les cel·les|Estilo: bordes juntos y padding en las celdas'],
        html: `<h2>{{La meva taula|Mi tabla}}</h2>\n<table>\n  <caption>{{Escriu aquí el títol|Escribe aquí el título}}</caption>\n  <tr><th></th><th></th><th></th></tr>\n</table>`, css: `body {\n  font-family: sans-serif;\n}`,
        checks: [ne({ k: 'text', min: 3, txt: 'El <code>&lt;caption&gt;</code> té un títol|El <code>&lt;caption&gt;</code> tiene un título' }, 'caption'), tag('th', { min: 3 }), tag('tr', { min: 4, txt: 'Almenys 4 files (capçaleres + 3 de dades)|Al menos 4 filas (cabeceras + 3 de datos)' }), inn('td', 'tr', { min: 9, txt: 'Almenys 9 cel·les de dades|Al menos 9 celdas de datos' }), prop('border-collapse', '/^collapse$/', { txt: 'Fas servir <code>border-collapse: collapse</code>|Usas <code>border-collapse: collapse</code>' }), sty('td', 'padding', null, { txt: 'Les cel·les tenen <code>padding</code>|Las celdas tienen <code>padding</code>' }), CLEAN],
        snips: ['<tr><td>|</td><td></td><td></td></tr>', '<th>|</th>', cs('table {\n  border-collapse: collapse;|\n}'), cs('th, td {\n  border: 1px solid #9AA6C8;\n  padding: 6px;|\n}')],
        sol: { html: `<h2>{{La meva setmana|Mi semana}}</h2>\n<table>\n  <caption>{{Les meves activitats|Mis actividades}}</caption>\n${RH('{{Dia|Día}}', '{{Activitat|Actividad}}', '{{Hora|Hora}}')}\n${R('{{Dilluns|Lunes}}', '{{Bàsquet|Baloncesto}}', '17:30')}\n${R('{{Dimecres|Miércoles}}', '{{Música|Música}}', '18:00')}\n${R('{{Dijous|Jueves}}', '{{Club Foto|Club Foto}}', '17:00')}\n</table>`,
          css: `body {\n  font-family: sans-serif;\n}\n${T_CSS}` } },
      { k: 'quiz', ph: 'tanca', q: 'Quina etiqueta fa una <b>fila</b> en una taula?|¿Qué etiqueta hace una <b>fila</b> en una tabla?',
        opts: ['<code>&lt;tr&gt;</code>|<code>&lt;tr&gt;</code>', '<code>&lt;td&gt;</code>|<code>&lt;td&gt;</code>', '<code>&lt;th&gt;</code>|<code>&lt;th&gt;</code>'], a: 0,
        ex: '<code>tr</code> és la fila (<i>row</i>); <code>td</code> i <code>th</code> són les cel·les de dins.|<code>tr</code> es la fila (<i>row</i>); <code>td</code> y <code>th</code> son las celdas de dentro.' },
      { k: 'quiz', ph: 'tanca', q: "Per què les capçaleres han de ser <code>&lt;th&gt;</code> i no <code>&lt;td&gt;</code> amb negreta?|¿Por qué las cabeceras tienen que ser <code>&lt;th&gt;</code> y no <code>&lt;td&gt;</code> con negrita?",
        opts: ['Perquè així un lector de pantalla sap què vol dir cada dada|Porque así un lector de pantalla sabe qué quiere decir cada dato', 'Perquè els th són més grans|Porque los th son más grandes', 'Perquè sense th la taula no té vores|Porque sin th la tabla no tiene bordes'], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 4 · Projecte: l'àlbum de fotos ---------- */
  { id: 'w6-4', t: "Projecte: l'àlbum de fotos|Proyecto: el álbum de fotos", min: 45, proj: true, badge: 'w_album',
    learn: ["Abans de programar una pàgina, un esbós en paper t'ajuda a decidir les caixes i com es col·loquen.|Antes de programar una página, un boceto en papel te ayuda a decidir las cajas y cómo se colocan.",
      'Cada eina per a la seva feina: flex per a files (capçalera, menú), grid per a la galeria i taula per a les dades.|Cada herramienta para su trabajo: flex para filas (cabecera, menú), grid para la galería y tabla para los datos.',
      "Has fet el teu àlbum de fotos amb una disposició de veritat i l'has revisat al mòbil i a l'ordinador.|Has hecho tu álbum de fotos con una disposición de verdad y lo has revisado en el móvil y en el ordenador."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Quina etiqueta posa el <b>títol</b> d\'una taula?|¿Qué etiqueta pone el <b>título</b> de una tabla?',
        opts: ['<code>&lt;caption&gt;</code>|<code>&lt;caption&gt;</code>', '<code>&lt;th&gt;</code>|<code>&lt;th&gt;</code>', '<code>&lt;title&gt;</code>|<code>&lt;title&gt;</code>'], a: 0,
        ex: "<code>caption</code> és el títol de la taula. <code>th</code> són les capçaleres de les columnes i <code>title</code>, el nom de la pestanya.|<code>caption</code> es el título de la tabla. <code>th</code> son las cabeceras de las columnas y <code>title</code>, el nombre de la pestaña." },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'illa', title: "L'exposició del club|La exposición del club",
        t: "Gran dia! El Club Foto prepara l'<b>exposició de final de curs</b> i vol un <b>àlbum web</b> perquè les famílies puguin veure les fotos des de casa. Tu en seràs el dissenyador/a: hauràs de fer servir tot el que has après en aquesta unitat.|¡Gran día! El Club Foto prepara la <b>exposición de final de curso</b> y quiere un <b>álbum web</b> para que las familias puedan ver las fotos desde casa. Tú serás el diseñador/a: tendrás que usar todo lo que has aprendido en esta unidad." },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy', t: "BIP! Això és el que demana el club:|¡BIP! Esto es lo que pide el club:",
        box: "<ol><li>Una <b>capçalera</b> amb el títol i un menú (flex).</li><li>Una <b>galeria</b> de 6 fotos o més, cada una amb el seu peu de foto (grid, <code>figure</code> i <code>figcaption</code>).</li><li>Una <b>taula</b> amb les dades de les fotos (<code>caption</code> i <code>th</code>).</li><li>Un <b>peu de pàgina</b> amb qui l'ha fet.</li></ol>|<ol><li>Una <b>cabecera</b> con el título y un menú (flex).</li><li>Una <b>galería</b> de 6 fotos o más, cada una con su pie de foto (grid, <code>figure</code> y <code>figcaption</code>).</li><li>Una <b>tabla</b> con los datos de las fotos (<code>caption</code> y <code>th</code>).</li><li>Un <b>pie de página</b> con quién la ha hecho.</li></ol>" },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Planificar|Planificar', t: "Primer, l'esbós|Primero, el boceto", pic: 'img/ment/lli.webp',
          x: "Els dissenyadors web fan un <span class='hl'>esbós</span> (en anglès, <i>wireframe</i>): un dibuix amb caixes i fletxes, sense colors ni detalls. Així decideixen on va cada cosa abans d'escriure codi, i és molt més fàcil canviar un dibuix que cent línies de CSS.|Los diseñadores web hacen un <span class='hl'>boceto</span> (en inglés, <i>wireframe</i>): un dibujo con cajas y flechas, sin colores ni detalles. Así deciden dónde va cada cosa antes de escribir código, y es mucho más fácil cambiar un dibujo que cien líneas de CSS." },
        { k: 'Cada eina…|Cada herramienta…', t: 'Flex, grid o taula?|¿Flex, grid o tabla?',
          media: { k: 'web', html: `<header>\n  <b>Club Foto</b>\n  <nav><a href="#">{{Fotos|Fotos}}</a> <a href="#">{{Dades|Datos}}</a></nav>\n</header>\n<div class="galeria">\n${img('platja')}\n${img('bosc')}\n${img('pont')}\n</div>\n<table>\n${RH('{{Foto|Foto}}', '{{Lloc|Lugar}}')}\n${R('1', '{{La platja|La playa}}')}\n</table>`,
            css: `header {\n  display: flex;\n  justify-content: space-between;\n}\n.galeria {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 6px;\n}\nimg {\n  width: 100%;\n}\nth, td {\n  border: 1px solid #9AA6C8;\n}` },
          x: "Una sola pàgina, tres eines: <b>flex</b> per a la capçalera (una fila), <b>grid</b> per a la galeria (files i columnes) i <b>taula</b> per a les dades (informació que es llegeix per files i per columnes).|Una sola página, tres herramientas: <b>flex</b> para la cabecera (una fila), <b>grid</b> para la galería (filas y columnas) y <b>tabla</b> para los datos (información que se lee por filas y por columnas)." },
        { k: 'Peus de foto|Pies de foto', t: 'figure dins de la graella|figure dentro de la rejilla',
          media: { k: 'web', html: `<div class="galeria">\n${fig('platja', "La platja, a l'estiu|La playa, en verano")}\n${fig('castell', 'Visita al castell|Visita al castillo')}\n</div>`,
            css: `.galeria {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n  gap: 8px;\n}\nfigure {\n  margin: 0;\n  background: #FFF3D6;\n  padding: 6px;\n  border-radius: 8px;\n}\nimg {\n  width: 100%;\n}` },
          x: "Recordes <code>&lt;figure&gt;</code> i <code>&lt;figcaption&gt;</code>? Són perfectes per a l'àlbum: cada <code>figure</code> és una cel·la de la graella, amb la foto i el seu peu. Compte: <code>figure</code> porta marge per defecte; amb <code>margin: 0</code> queda ben encaixada.|¿Recuerdas <code>&lt;figure&gt;</code> y <code>&lt;figcaption&gt;</code>? Son perfectas para el álbum: cada <code>figure</code> es una celda de la rejilla, con la foto y su pie. Cuidado: <code>figure</code> lleva margen por defecto; con <code>margin: 0</code> queda bien encajada." },
        { k: 'Revisar|Revisar', t: 'Mira-ho amb ulls de visitant|Míralo con ojos de visitante', pic: 'img/ment/vel.webp',
          x: "Abans de donar l'àlbum per acabat, revisa'l: totes les fotos tenen <code>alt</code>? Els títols van en ordre (<code>h1</code>, <code>h2</code>)? El text es llegeix bé sobre el fons? I prova'l amb el botó del mòbil 📱 i el de l'ordinador 💻.|Antes de dar el álbum por terminado, revísalo: ¿todas las fotos tienen <code>alt</code>? ¿Los títulos van en orden (<code>h1</code>, <code>h2</code>)? ¿El texto se lee bien sobre el fondo? Y pruébalo con el botón del móvil 📱 y el del ordenador 💻.",
          tip: "Amb <code>fr</code> i <code>gap</code>, la graella ja s'adapta sola a pantalles petites. A la unitat següent aprendràs a canviar la disposició per al mòbil.|Con <code>fr</code> y <code>gap</code>, la rejilla ya se adapta sola a pantallas pequeñas. En la unidad siguiente aprenderás a cambiar la disposición para el móvil." }
      ] },
      { k: 'seq', ph: 'mans', q: "<b>Ordena el pla de treball</b> de l'àlbum.|<b>Ordena el plan de trabajo</b> del álbum.",
        items: ["Fer l'esbós en paper: on va cada caixa|Hacer el boceto en papel: dónde va cada caja", "Escriure l'HTML: capçalera, galeria, taula i peu|Escribir el HTML: cabecera, galería, tabla y pie", 'Escriure el CSS de la disposició: flex i grid|Escribir el CSS de la disposición: flex y grid', 'Afegir colors, vores i espais|Añadir colores, bordes y espacios', "Revisar-ho al mòbil i a l'ordinador|Revisarlo en el móvil y en el ordenador"],
        ex: 'De les grans decisions als detalls: primer on va cada cosa, després com es veu i, al final, comprovar-ho.|De las grandes decisiones a los detalles: primero dónde va cada cosa, después cómo se ve y, al final, comprobarlo.' },
      { k: 'quiz', ph: 'investiga', q: "Per a cada part de l'àlbum, quina eina és la bona?|Para cada parte del álbum, ¿qué herramienta es la buena?",
        opts: ['Capçalera: flex · Galeria: grid · Dades: taula|Cabecera: flex · Galería: grid · Datos: tabla', 'Capçalera: taula · Galeria: taula · Dades: taula|Cabecera: tabla · Galería: tabla · Datos: tabla', 'Capçalera: grid · Galeria: flex en columna · Dades: paràgrafs|Cabecera: grid · Galería: flex en columna · Datos: párrafos'], a: 0,
        ex: "Una fila → flex. Files i columnes de fotos → grid. Dades que es llegeixen per files i columnes → taula.|Una fila → flex. Filas y columnas de fotos → grid. Datos que se leen por filas y columnas → tabla." },
      { k: 'wquiz', ph: 'prova', q: "Prediu: quina vista prèvia fa aquest esquelet d'àlbum?|Predice: ¿qué vista previa hace este esqueleto de álbum?",
        code: { html: `<header>\n  <b>{{Àlbum|Álbum}}</b>\n  <b>{{Menú|Menú}}</b>\n</header>\n<div class="galeria">\n${NUM(4)}\n</div>`, css: `header {\n  display: flex;\n  justify-content: space-between;\n}\n.galeria {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n  gap: 6px;\n}\n${NUMC}` },
        opts: [{ html: `<header>\n  <b>{{Àlbum|Álbum}}</b>\n  <b>{{Menú|Menú}}</b>\n</header>\n<div class="galeria">\n${NUM(4)}\n</div>`, css: `header { display: flex; justify-content: space-between; }\n.galeria { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; }\n${NUMC}` },
          { html: `<header>\n  <b>{{Àlbum|Álbum}}</b>\n  <b>{{Menú|Menú}}</b>\n</header>\n<div class="galeria">\n${NUM(4)}\n</div>`, css: `header { display: flex; flex-direction: column; }\n.galeria { display: flex; gap: 6px; }\n${NUMC}` },
          { html: `<header>\n  <b>{{Àlbum|Álbum}}</b>\n  <b>{{Menú|Menú}}</b>\n</header>\n<div class="galeria">\n${NUM(4)}\n</div>`, css: `header { display: flex; justify-content: center; gap: 6px; }\n.galeria { display: grid; grid-template-columns: 1fr 1fr 1fr 1fr; gap: 6px; }\n${NUMC}` }], a: 0,
        ex: "La capçalera reparteix les dues paraules als extrems (<code>space-between</code>) i la galeria fa 2 columnes iguals: 4 caixes, 2 files.|La cabecera reparte las dos palabras a los extremos (<code>space-between</code>) y la galería hace 2 columnas iguales: 4 cajas, 2 filas." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Estira't com una foto panoràmica: braços ben oberts (fila!). Ara com una foto vertical: braços amunt (columna!). Ara fes un marc amb els dits i «fotografia» tres coses de l'aula.|Estírate como una foto panorámica: brazos bien abiertos (¡fila!). Ahora como una foto vertical: brazos arriba (¡columna!). Ahora haz un marco con los dedos y «fotografía» tres cosas del aula." },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/album', tab: 'css', q: "Peça 1: la <b>capçalera</b>. Fes que <code>header</code> posi el títol i el menú als extrems i centrats de dalt a baix, i que el <code>nav</code> posi els enllaços en fila amb un <code>gap</code>.|Pieza 1: la <b>cabecera</b>. Haz que <code>header</code> ponga el título y el menú en los extremos y centrados de arriba abajo, y que el <code>nav</code> ponga los enlaces en fila con un <code>gap</code>.",
        html: ALB_HEAD, css: ALB_HEAD_CSS,
        checks: [css('header', 'display', FLEX), css('header', 'justify-content', '/^space-between$/', { txt: '<code>header</code> té <code>justify-content: space-between</code>|<code>header</code> tiene <code>justify-content: space-between</code>' }), css('header', 'align-items', '/^center$/', { txt: '<code>header</code> té <code>align-items: center</code>|<code>header</code> tiene <code>align-items: center</code>' }), css('nav', 'display', FLEX), css('nav', 'gap'), CSSOK],
        snips: [cs('nav {\n  |\n}'), cs('display: flex;'), cs('justify-content: space-between;'), cs('align-items: center;'), cs('gap: 12px;')],
        sol: { css: `header {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  background: #14204A;\n  padding: 10px 14px;\n}\nh1 {\n  color: white;\n  font-size: 20px;\n  margin: 0;\n}\nnav {\n  display: flex;\n  gap: 12px;\n}\nnav a {\n  color: #FFC531;\n  font-weight: bold;\n}` },
        hint: "Són dos contenidors: <code>header</code> (conté el títol i el menú) i <code>nav</code> (conté els enllaços). Cada un necessita el seu <code>display: flex</code>.|Son dos contenedores: <code>header</code> (contiene el título y el menú) y <code>nav</code> (contiene los enlaces). Cada uno necesita su <code>display: flex</code>." },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/album', q: "Peça 2: la <b>galeria</b>. Afegeix <b>2 fotos més</b> amb el seu peu de foto (<code>figure</code> amb <code>img</code> i <code>figcaption</code>) i fes una graella de <b>2 columnes</b> amb <code>fr</code> i <code>gap</code>.|Pieza 2: la <b>galería</b>. Añade <b>2 fotos más</b> con su pie de foto (<code>figure</code> con <code>img</code> y <code>figcaption</code>) y haz una rejilla de <b>2 columnas</b> con <code>fr</code> y <code>gap</code>.",
        html: ALB_GAL(2), css: FIG_CSS,
        checks: [tag('figure', { min: 4, txt: 'Hi ha 4 <code>&lt;figure&gt;</code>|Hay 4 <code>&lt;figure&gt;</code>' }), inn('figcaption', 'figure', { min: 4, txt: 'Cada figura té el seu <code>&lt;figcaption&gt;</code>|Cada figura tiene su <code>&lt;figcaption&gt;</code>' }), alt(4, { txt: 'Les 4 fotos tenen <code>alt</code>|Las 4 fotos tienen <code>alt</code>' }), css('.galeria', 'display', GRID), css('.galeria', 'grid-template-columns', '/fr/', { txt: '<code>.galeria</code> té columnes amb <code>fr</code>|<code>.galeria</code> tiene columnas con <code>fr</code>' }), css('.galeria', 'gap'), CLEAN],
        snips: [`<figure>\n    <img src="img/tech/web/|.svg" alt="">\n    <figcaption></figcaption>\n  </figure>`, cs('.galeria {\n  |\n}'), cs('display: grid;'), cs('grid-template-columns: 1fr 1fr;'), cs('gap: 8px;')],
        sol: { html: ALB_GAL(4), css: FIG_CSS + `\n.galeria {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n  gap: 8px;\n}` },
        hint: "Copia una <code>&lt;figure&gt;…&lt;/figure&gt;</code> sencera i enganxa-la abans del <code>&lt;/div&gt;</code>. Després fes la regla <code>.galeria { … }</code> amb <code>display</code>, <code>grid-template-columns</code> i <code>gap</code>.|Copia una <code>&lt;figure&gt;…&lt;/figure&gt;</code> entera y pégala antes del <code>&lt;/div&gt;</code>. Después haz la regla <code>.galeria { … }</code> con <code>display</code>, <code>grid-template-columns</code> y <code>gap</code>." },
      { k: 'web', ph: 'repte', url: 'clubfoto.numi/album', q: "Peça 3: una companya del club ha fet aquest tros de l'àlbum, però no queda bé. Hi ha <b>tres errors</b>: un a l'HTML i dos al CSS. Troba'ls i arregla'ls (mira els dos fitxers!).|Pieza 3: una compañera del club ha hecho este trozo del álbum, pero no queda bien. Hay <b>tres errores</b>: uno en el HTML y dos en el CSS. Encuéntralos y arréglalos (¡mira los dos archivos!).",
        html: BUG_HTML, css: BUG_CSS,
        checks: [CLEAN, tag('figure', { min: 2 }), css('header', 'justify-content', '/^space-between$/', { txt: '<code>justify-content</code> de <code>header</code> ben escrit|<code>justify-content</code> de <code>header</code> bien escrito' }), css('nav', 'display', FLEX, { txt: 'El <code>display: flex</code> és al contenidor <code>nav</code>|El <code>display: flex</code> está en el contenedor <code>nav</code>' })],
        sol: { html: BUG_HTML.replace(`    <figcaption>{{El castell|El castillo}}</figcaption>\n`, `    <figcaption>{{El castell|El castillo}}</figcaption>\n  </figure>\n`), css: BUG_CSS.replace('space between', 'space-between').replace('nav a {\n  display: flex;\n', 'nav {\n  display: flex;\n  gap: 10px;\n}\nnav a {\n') },
        hint: "A l'HTML, compta les <code>&lt;figure&gt;</code> que s'obren i les que es tanquen. Al CSS, mira bé el guionet de <code>space-between</code> i a qui està posat el <code>display: flex</code> del menú: al pare o als fills?|En el HTML, cuenta las <code>&lt;figure&gt;</code> que se abren y las que se cierran. En el CSS, mira bien el guion de <code>space-between</code> y a quién está puesto el <code>display: flex</code> del menú: ¿al padre o a los hijos?" },
      { k: 'wcreate', ph: 'crea', url: 'clubfoto.numi/el-meu-album', name: "El meu àlbum de fotos|Mi álbum de fotos",
        q: "<b>Projecte final de la unitat!</b> Construeix el teu àlbum seguint el teu esbós: capçalera amb menú (flex), galeria d'almenys <b>6 fotos amb peu</b> (grid), una <b>taula</b> amb les dades de les fotos i un peu de pàgina. Fes-lo teu: colors, fotos i textos.|<b>¡Proyecto final de la unidad!</b> Construye tu álbum siguiendo tu boceto: cabecera con menú (flex), galería de al menos <b>6 fotos con pie</b> (grid), una <b>tabla</b> con los datos de las fotos y un pie de página. Hazlo tuyo: colores, fotos y textos.",
        crit: ['Capçalera i menú amb flex|Cabecera y menú con flex', 'Galeria amb grid: almenys 6 fotos amb alt i peu de foto|Galería con grid: al menos 6 fotos con alt y pie de foto', 'Una taula de dades amb caption i th|Una tabla de datos con caption y th', 'Peu de pàgina, i revisat al mòbil i a l\'ordinador|Pie de página, y revisado en el móvil y en el ordenador'],
        html: `<header>\n  <h1>{{El meu àlbum|Mi álbum}}</h1>\n  <nav>\n    <a href="#galeria">{{Galeria|Galería}}</a>\n  </nav>\n</header>\n<main>\n  <h2 id="galeria">{{Galeria|Galería}}</h2>\n  <div class="galeria">\n${fig('espai', "Un viatge a l'espai|Un viaje al espacio", '    ')}\n  </div>\n  <h2 id="dades">{{Les dades de les fotos|Los datos de las fotos}}</h2>\n  <table>\n    <caption>{{Fitxa de cada foto|Ficha de cada foto}}</caption>\n  </table>\n</main>\n<footer>\n  <p>{{Fet per…|Hecho por…}}</p>\n</footer>`,
        css: ALBUM_CSS,
        checks: [sty('header', 'display', FLEX, { txt: 'La capçalera <code>header</code> és flex|La cabecera <code>header</code> es flex' }), sty('nav', 'display', FLEX, { txt: 'El menú <code>nav</code> és flex|El menú <code>nav</code> es flex' }), prop('display', GRID, { txt: 'La galeria és una graella (<code>display: grid</code>)|La galería es una rejilla (<code>display: grid</code>)' }), prop('grid-template-columns', null, { txt: 'La graella té <code>grid-template-columns</code>|La rejilla tiene <code>grid-template-columns</code>' }),
          tag('figure', { min: 6, txt: 'Almenys 6 <code>&lt;figure&gt;</code>|Al menos 6 <code>&lt;figure&gt;</code>' }), inn('figcaption', 'figure', { min: 6, txt: 'Cada foto té el seu <code>&lt;figcaption&gt;</code>|Cada foto tiene su <code>&lt;figcaption&gt;</code>' }), alt(6, { txt: 'Totes les fotos tenen <code>alt</code>|Todas las fotos tienen <code>alt</code>' }),
          tag('th', { min: 2, txt: 'La taula té capçaleres <code>&lt;th&gt;</code>|La tabla tiene cabeceras <code>&lt;th&gt;</code>' }), inn('td', 'tr', { min: 4, txt: 'La taula té dades: almenys 4 <code>&lt;td&gt;</code>|La tabla tiene datos: al menos 4 <code>&lt;td&gt;</code>' }), tag('footer'), CLEAN],
        snips: [`<figure>\n      <img src="img/tech/web/|.svg" alt="">\n      <figcaption></figcaption>\n    </figure>`, '<tr><td>|</td><td></td></tr>', '<th>|</th>', '<a href="#">|</a>', cs('display: flex;'), cs('display: grid;'), cs('grid-template-columns: |;'), cs('gap: 10px;')],
        sol: { html: `<header>\n  <h1>{{El meu àlbum|Mi álbum}}</h1>\n  <nav>\n    <a href="#galeria">{{Galeria|Galería}}</a>\n    <a href="#dades">{{Dades|Datos}}</a>\n  </nav>\n</header>\n<main>\n  <h2 id="galeria">{{Galeria|Galería}}</h2>\n  <div class="galeria">\n${FIGS.map(([f, c]) => fig(f, c, '    ')).join('\n')}\n  </div>\n  <h2 id="dades">{{Les dades de les fotos|Los datos de las fotos}}</h2>\n  <table>\n    <caption>{{Fitxa de cada foto|Ficha de cada foto}}</caption>\n  ${RH('{{Foto|Foto}}', '{{Lloc|Lugar}}', '{{Mes|Mes}}')}\n  ${R('{{La platja|La playa}}', '{{El moll|El muelle}}', '{{Juliol|Julio}}')}\n  ${R('{{La muntanya|La montaña}}', '{{El cim|La cima}}', '{{Octubre|Octubre}}')}\n  ${R('{{El pont|El puente}}', '{{El riu|El río}}', '{{Març|Marzo}}')}\n  </table>\n</main>\n<footer>\n  <p>{{Fet per l'equip del Club Foto|Hecho por el equipo del Club Foto}}</p>\n</footer>`,
          css: ALBUM_CSS + `\nheader {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  background: #14204A;\n  color: white;\n  padding: 10px;\n}\nnav {\n  display: flex;\n  gap: 12px;\n}\nnav a {\n  color: #FFC531;\n}\n.galeria {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 10px;\n}\nfigcaption {\n  text-align: center;\n  font-size: 14px;\n}\ntable {\n  border-collapse: collapse;\n}\nth, td {\n  border: 1px solid #9AA6C8;\n  padding: 6px;\n}\nth {\n  background-color: #FFC531;\n}\nfooter {\n  text-align: center;\n  color: #555;\n}` } },
      { k: 'story', ph: 'crea', who: 'numi', t: "Abans de dir que està acabat, fes la <b>revisió</b> del teu àlbum, com un dissenyador/a de veritat:|Antes de decir que está terminado, haz la <b>revisión</b> de tu álbum, como un diseñador/a de verdad:",
        box: "<ol><li>Totes les fotos tenen un <code>alt</code> que les descriu?</li><li>Els títols van en ordre: un <code>h1</code> i després <code>h2</code>?</li><li>El text es llegeix bé sobre el color de fons?</li><li>Prova el botó 📱 i el 💻: es veu bé en totes dues pantalles?</li></ol>|<ol><li>¿Todas las fotos tienen un <code>alt</code> que las describe?</li><li>¿Los títulos van en orden: un <code>h1</code> y después <code>h2</code>?</li><li>¿El texto se lee bien sobre el color de fondo?</li><li>Prueba el botón 📱 y el 💻: ¿se ve bien en las dos pantallas?</li></ol>" },
      { k: 'quiz', ph: 'tanca', q: "Què és un <b>esbós</b> (<i>wireframe</i>) d'una web?|¿Qué es un <b>boceto</b> (<i>wireframe</i>) de una web?",
        opts: ['Un dibuix amb caixes que diu on va cada cosa, abans de programar|Un dibujo con cajas que dice dónde va cada cosa, antes de programar', 'La web acabada amb tots els colors|La web terminada con todos los colores', 'Un error del CSS|Un error del CSS'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "Vols ensenyar el <b>rànquing</b> del concurs de fotos (posició, foto i punts). Què fas servir?|Quieres enseñar el <b>ranking</b> del concurso de fotos (posición, foto y puntos). ¿Qué usas?",
        opts: ['Una taula amb th i td|Una tabla con th y td', 'Una graella grid de fotos|Una rejilla grid de fotos', 'Un menú flex|Un menú flex'], a: 0,
        ex: 'Són dades que es llegeixen per files i per columnes: és feina d\'una taula.|Son datos que se leen por filas y por columnas: es trabajo de una tabla.' },
      { k: 'feel', ph: 'tanca' }
    ] }
  ] });
})();
