/* Tech Robòtica · unitat 4 «Seguir la línia» (sessions k4-1…k4-4): sensors de línia L/M/R, valor ADC, seguir la vora
   amb un sensor, seguir amb dos i tres sensors, cruïlles i estacions, el seguiment del xip i el projecte del tren de
   mercaderies del port. Contingut propi de Numi. */
Object.assign(TBADGE, {
  k_linia: { id: 'k_linia', ico: '🔦', n: 'Ulls de línia|Ojos de línea', d: 'Has fet que el Maqueen distingeixi el negre, el blanc i els colors amb els sensors de línia.|Has hecho que el Maqueen distinga el negro, el blanco y los colores con los sensores de línea.' },
  k_vora: { id: 'k_vora', ico: '〰️', n: 'Seguidor/a de vores|Seguidor/a de bordes', d: 'Has programat un robot que segueix una línia amb un sol sensor.|Has programado un robot que sigue una línea con un solo sensor.' },
  k_cruilla: { id: 'k_cruilla', ico: '➕', n: 'Mestre/a de cruïlles|Maestro/a de cruces', d: 'El teu robot segueix la línia amb dos i tres sensors i sap què fer a les cruïlles.|Tu robot sigue la línea con dos y tres sensores y sabe qué hacer en los cruces.' },
  k_tren: { id: 'k_tren', ico: '🚂', n: 'Enginyer/a del tren|Ingeniero/a del tren', d: 'Has planificat, programat i provat el tren de mercaderies del port.|Has planificado, programado y probado el tren de mercancías del puerto.' }
});
ROBOTICA_UNITS[4] = (() => {
  // ---------- pistes (cm) ----------
  const ln = (x, y0 = 12, y1 = 68) => ({ p: [[x, y0], [x, y1]] });
  const OVAL = [[92, 14], [95.8, 14.8], [99.1, 16.9], [101.2, 20.2], [102, 24], [102, 56], [101.2, 59.8], [99.1, 63.1], [95.8, 65.2], [92, 66], [28, 66], [24.2, 65.2], [20.9, 63.1], [18.8, 59.8], [18, 56], [18, 24], [18.8, 20.2], [20.9, 16.9], [24.2, 14.8], [28, 14]];
  const OVAL6 = [[96, 14], [99, 14.8], [101.2, 17], [102, 20], [102, 60], [101.2, 63], [99, 65.2], [96, 66], [24, 66], [21, 65.2], [18.8, 63], [18, 60], [18, 20], [18.8, 17], [21, 14.8], [24, 14]];
  const SQ = [[82, 10], [86, 11.1], [88.9, 14], [90, 18], [90, 62], [88.9, 66], [86, 68.9], [82, 70], [38, 70], [34, 68.9], [31.1, 66], [30, 62], [30, 18], [31.1, 14], [34, 11.1], [38, 10]];
  const PILL = [[83, 18], [88.4, 18.7], [93.5, 20.8], [97.8, 24.2], [101.2, 28.5], [103.3, 33.6], [104, 39], [104, 41], [103.3, 46.4], [101.2, 51.5], [97.8, 55.8], [93.5, 59.2], [88.4, 61.3], [83, 62], [37, 62], [31.6, 61.3], [26.5, 59.2], [22.2, 55.8], [18.8, 51.5], [16.7, 46.4], [16, 41], [16, 39], [16.7, 33.6], [18.8, 28.5], [22.2, 24.2], [26.5, 20.8], [31.6, 18.7], [37, 18]];
  const LONG1 = [[98, 18], [102.6, 18.9], [106.5, 21.5], [109.1, 25.4], [110, 30], [110, 50], [109.1, 54.6], [106.5, 58.5], [102.6, 61.1], [98, 62], [22, 62], [17.4, 61.1], [13.5, 58.5], [10.9, 54.6], [10, 50], [10, 30], [10.9, 25.4], [13.5, 21.5], [17.4, 18.9], [22, 18]];
  const LONG2 = [[94, 12], [100.1, 13.2], [105.3, 16.7], [108.8, 21.9], [110, 28], [110, 52], [108.8, 58.1], [105.3, 63.3], [100.1, 66.8], [94, 68], [26, 68], [19.9, 66.8], [14.7, 63.3], [11.2, 58.1], [10, 52], [10, 28], [11.2, 21.9], [14.7, 16.7], [19.9, 13.2], [26, 12]];
  const S1 = [[12, 44], [18, 51.7], [24, 58.1], [30, 62.5], [36, 64], [42, 62.5], [48, 58.1], [54, 51.7], [60, 44], [66, 36.3], [72, 29.9], [78, 25.5], [84, 24], [90, 25.5], [96, 29.9], [102, 36.3], [108, 44]];
  const S2 = [[12, 36], [18, 28.3], [24, 21.9], [30, 17.5], [36, 16], [42, 17.5], [48, 21.9], [54, 28.3], [60, 36], [66, 43.7], [72, 50.1], [78, 54.5], [84, 56], [90, 54.5], [96, 50.1], [102, 43.7], [108, 36]];
  const S3 = [[12, 40], [18, 44.3], [24, 48.4], [30, 52.2], [36, 55.6], [42, 58.3], [48, 60.3], [54, 61.6], [60, 62], [66, 61.6], [72, 60.3], [78, 58.3], [84, 55.6], [90, 52.2], [96, 48.4], [102, 44.3], [108, 40]];
  const E1 = [[12, 44], [18, 52.7], [24, 59.6], [30, 63.5], [36, 63.5], [42, 59.6], [48, 52.7], [54, 44], [60, 35.3], [66, 28.4], [72, 24.5], [78, 24.5], [84, 28.4], [90, 35.3], [96, 44]];
  const E2 = [[12, 30], [18, 32.1], [24, 34.3], [30, 36.4], [36, 38.6], [42, 40.7], [48, 42.9], [54, 45], [60, 47.1], [66, 49.3], [72, 51.4], [78, 53.6], [84, 55.7], [90, 57.9], [96, 60]];
  const E3 = [[12, 56], [18, 52], [24, 48.2], [30, 44.8], [36, 41.9], [42, 39.8], [48, 38.5], [54, 38], [60, 38.5], [66, 39.8], [72, 41.9], [78, 44.8], [84, 48.2], [90, 52], [96, 56]];
  const ST1 = [[12, 40], [17.5, 48.4], [23, 55.6], [28.5, 60.3], [34, 62], [39.5, 60.3], [45, 55.6], [50.5, 48.4], [56, 40], [61.5, 31.6], [67, 24.4], [72.5, 19.7], [78, 18], [83.5, 19.7], [89, 24.4], [94.5, 31.6], [100, 40]];
  const ST2 = [[12, 60], [17.5, 57.5], [23, 55], [28.5, 52.5], [34, 50], [39.5, 47.5], [45, 45], [50.5, 42.5], [56, 40], [61.5, 37.5], [67, 35], [72.5, 32.5], [78, 30], [83.5, 27.5], [89, 25], [94.5, 22.5], [100, 20]];
  const ST3 = [[12, 28], [16.9, 33.2], [21.8, 38.2], [26.6, 43], [31.5, 47.2], [36.4, 50.9], [41.3, 53.9], [46.1, 56.2], [51, 57.5], [55.9, 58], [60.8, 57.6], [65.6, 56.2], [70.5, 54.1], [75.4, 51.1], [80.3, 47.4], [85.1, 43.2], [90, 38.5]];
  const STEP_A = [[8, 60], [40, 60], [40, 25], [80, 25], [80, 55], [112, 55]], STEP_B = [[8, 22], [36, 22], [36, 58], [70, 58], [70, 28], [112, 28]], STEP_C = [[8, 40], [30, 40], [30, 14], [60, 14], [60, 66], [92, 66], [92, 40], [112, 40]];
  // les rutes del tren de mercaderies del port (ratlla travessera = estació; zona blava = terminal)
  const RA = [[8, 62], [50, 62], [58, 60], [64, 55], [68, 48], [70, 40], [72, 32], [77, 25], [84, 21], [92, 20], [104, 20]];
  const RB = [[8, 18], [40, 18], [48, 20], [54, 25], [58, 32], [60, 40], [62, 48], [66, 55], [72, 60], [80, 62], [104, 62]];
  const RC = [[8, 66], [60, 66], [70, 64], [76, 58], [78, 50], [76, 43], [70, 38], [60, 36], [40, 36], [30, 34], [25, 28], [24, 22], [28, 16], [36, 13], [50, 12], [104, 12]];
  const TERM = r => ({ id: 'tz', r, col: 'blue', label: 'TERMINAL|TERMINAL' });
  const ROUTE_A = { bot: [10, 62, 90], lines: [{ p: RA }, ln(34, 54, 70)], zones: [TERM([92, 9, 26, 22])], goal: [{ k: 'cps', pts: [[44, 62], [70, 40], [92, 20]], r: 7 }, { k: 'notes', n: ['C5'] }, { k: 'zone', id: 'tz', stop: true }] };
  const ROUTE_B = { bot: [10, 18, 90], lines: [{ p: RB }, ln(26, 10, 26), { p: [[52.2, 41.9], [67.8, 38.1]] }], zones: [TERM([92, 51, 26, 22])], goal: [{ k: 'cps', pts: [[36, 18], [62, 48], [92, 62]], r: 7 }, { k: 'notes', n: ['C5', 'C5'] }, { k: 'zone', id: 'tz', stop: true }] };
  const nonote = R => ({ ...R, goal: R.goal.filter(g => g.k !== 'notes') });
  // ---------- programes ----------
  const STOP_M = 'forever{ if:M=1{ stop:all } else{ run:all,fwd,120 } }';
  const ONE = (a, b) => `forever{ if:M=1{ run:L,fwd,${a} run:R,fwd,${b} } else{ run:L,fwd,${b} run:R,fwd,${a} } }`;
  const TWO = (a, b) => `forever{ if:L=1{ run:L,fwd,${b} run:R,fwd,${a} } else{ if:R=1{ run:L,fwd,${a} run:R,fwd,${b} } else{ run:all,fwd,${a} } } }`;
  const TWOX = (a, b, x) => `forever{ if:L=1&&R=1{ ${x} } else{ if:L=1{ run:L,fwd,${b} run:R,fwd,${a} } else{ if:R=1{ run:L,fwd,${a} run:R,fwd,${b} } else{ run:all,fwd,${a} } } } }`;
  const THREE = (a, b) => `forever{ if:L=1{ run:L,fwd,${b} run:R,fwd,${a} } else{ if:R=1{ run:L,fwd,${a} run:R,fwd,${b} } else{ if:M=1{ run:all,fwd,${a} } } } }`;
  const PATROL_T = 'start{ patrol:on } forever{ if:aM>200&&aM<600{ patrol:off stop:all } }';
  const PATROL_ST = 'start{ patrol:on } forever{ if:L=1&&R=1{ patrol:off stop:all note:C5,1 wait:1500 run:all,fwd,120 wait:500 patrol:on } if:aM>200&&aM<600{ patrol:off stop:all } }';
  const OVAL_CPS = [[102, 40], [60, 14], [18, 40], [60, 66]];
  const PAL = ['run', 'stop', 'wait', 'if', 'else'];
  return { t: 'Seguir la línia|Seguir la línea', d: 'Sensors de llum reflectida|Sensores de luz reflejada', color: '#E2574C', s: [
    /* ===================================== k4-1 · Blanc o negre? ===================================== */
    { id: 'k4-1', t: 'Blanc o negre?|¿Blanco o negro?', min: 45, badge: 'k_linia',
      learn: ['Els sensors de línia envien llum cap a terra: el blanc en torna molta (0) i el negre, gairebé gens (1).|Los sensores de línea envían luz hacia el suelo: el blanco devuelve mucha (0) y el negro, casi nada (1).',
        'El valor ADC (de 0 a 1023) distingeix el blanc (≈90), els colors (≈360) i el negre (≈900).|El valor ADC (de 0 a 1023) distingue el blanco (≈90), los colores (≈360) y el negro (≈900).',
        'Si el robot va massa de pressa, passa la cinta abans de frenar: per aturar-se a la línia cal anar a poc a poc.|Si el robot va demasiado deprisa, pasa la cinta antes de frenar: para pararse en la línea hay que ir despacio.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "A la unitat 3: què et diu el sensor d'ultrasons quan <b>no veu cap obstacle</b>?|En la unidad 3: ¿qué te dice el sensor de ultrasonidos cuando <b>no ve ningún obstáculo</b>?",
          opts: ['500|500', '0|0', '1|1'], a: 0, ex: "Torna 500, que vol dir «no he rebut cap eco». Avui coneixeràs uns altres sensors: els que miren a terra.|Devuelve 500, que quiere decir «no he recibido ningún eco». Hoy conocerás otros sensores: los que miran al suelo." },
        { k: 'quiz', ph: 'recorda', q: 'Quin guió fa que el robot torni a mirar els sensors <b>una vegada i una altra</b>?|¿Qué guion hace que el robot vuelva a mirar los sensores <b>una y otra vez</b>?',
          opts: ['«per sempre»|«para siempre»', '«en iniciar»|«al iniciar»', '«en prémer el botó A»|«al pulsar el botón A»'], a: 0, ex: "«Per sempre» repeteix els blocs sense parar: perfecte per vigilar un sensor.|«Para siempre» repite los bloques sin parar: perfecto para vigilar un sensor." },
        { k: 'story', ph: 'missio', who: 'both', scene: 'moll', t: "Benvinguts al <b>moll de mercaderies</b> del port! Al magatzem nou, els robots porten caixes per camins de <b>cinta negra</b> enganxada a terra. Per saber on és la cinta, el Maqueen té tres «ulls» petits sota el morro, mirant a terra: els <b>sensors de línia</b>.|¡Bienvenidos al <b>muelle de mercancías</b> del puerto! En el almacén nuevo, los robots llevan cajas por caminos de <b>cinta negra</b> pegada al suelo. Para saber dónde está la cinta, el Maqueen tiene tres «ojos» pequeños bajo el morro, mirando al suelo: los <b>sensores de línea</b>." },
        { k: 'story', ph: 'missio', who: 'bit', mood: 'happy', t: "BIP! A moltes fàbriques i magatzems de veritat hi ha vehicles que segueixen línies pintades o enganxades a terra. Avui aprendràs com distingeixen el <b>negre</b> del <b>blanc</b>… i fins i tot els <b>colors</b>!|¡BIP! En muchas fábricas y almacenes de verdad hay vehículos que siguen líneas pintadas o pegadas en el suelo. Hoy aprenderás cómo distinguen el <b>negro</b> del <b>blanco</b>… ¡e incluso los <b>colores</b>!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'El sensor de línia|El sensor de línea', t: 'Llum que rebota|Luz que rebota', anim: 'k4ir',
            x: "Cada sensor té un <b>emissor</b> que envia llum infraroja (no la veiem) cap a terra i un <b>receptor</b> que mesura quanta en torna. El <b>blanc</b> la fa rebotar molt: el sensor diu <span class='hl'>0</span>. El <b>negre</b> se la «menja» i gairebé no en torna: el sensor diu <span class='hl'>1</span>.|Cada sensor tiene un <b>emisor</b> que envía luz infrarroja (no la vemos) hacia el suelo y un <b>receptor</b> que mide cuánta vuelve. El <b>blanco</b> la hace rebotar mucho: el sensor dice <span class='hl'>0</span>. El <b>negro</b> se la «come» y casi no devuelve: el sensor dice <span class='hl'>1</span>.",
            tip: "Per això la unitat es diu «sensors de llum reflectida»: mesuren la llum que torna després de rebotar.|Por eso la unidad se llama «sensores de luz reflejada»: miden la luz que vuelve después de rebotar." },
          { k: 'L, M i R|L, M y R', t: 'Tres sensors en fila|Tres sensores en fila', anim: 'k4lmr',
            x: "El Maqueen en té tres, en fila, uns 3,6 cm per davant del centre: <b>L</b> (esquerre), <b>M</b> (mig) i <b>R</b> (dret), separats poc més d'1 cm. La cinta fa 2 cm: quan el robot hi és ben centrat, només el <b>M</b> veu negre (0 1 0).|El Maqueen tiene tres, en fila, unos 3,6 cm por delante del centro: <b>L</b> (izquierdo), <b>M</b> (medio) y <b>R</b> (derecho), separados poco más de 1 cm. La cinta mide 2 cm: cuando el robot está bien centrado, solo el <b>M</b> ve negro (0 1 0)." },
          { k: 'Prova-ho|Pruébalo', t: 'Para quan vegis negre|Para cuando veas negro',
            robo: { w: { w: 120, h: 80, bot: [14, 40, 90], lines: [ln(80)], time: 9 }, prog: STOP_M },
            x: "«Per sempre», <b>si</b> el sensor M veu negre (M = 1), para els motors; <b>si no</b>, endavant. Fixa't en els sensors del robot: quan toquen la cinta s'encenen.|«Para siempre», <b>si</b> el sensor M ve negro (M = 1), para los motores; <b>si no</b>, adelante. Fíjate en los sensores del robot: cuando tocan la cinta se encienden." },
          { k: 'Valor ADC|Valor ADC', t: 'Un número de 0 a 1023|Un número de 0 a 1023', anim: 'k4adc',
            x: "A més del 0/1, cada sensor dona un número, el <b>valor analògic</b> o <b>ADC</b>: el blanc dona uns <b>90</b>, un color (blau, verd…) uns <b>360</b> i el negre uns <b>900</b>. Amb el bloc «línia M (ADC)» el robot pot reconèixer una <b>zona de color</b>, que amb el 0/1 semblaria blanca.|Además del 0/1, cada sensor da un número, el <b>valor analógico</b> o <b>ADC</b>: el blanco da unos <b>90</b>, un color (azul, verde…) unos <b>360</b> y el negro unos <b>900</b>. Con el bloque «línea M (ADC)» el robot puede reconocer una <b>zona de color</b>, que con el 0/1 parecería blanca." },
          { k: 'Compte!|¡Cuidado!', t: "L'aire també és «negre»|El aire también es «negro»", anim: 'k4air',
            x: "Si el sensor queda a sobre del buit (a la vora d'una taula), la llum no rebota enlloc i no en torna gens: el sensor diu <b>1</b>, com si veiés negre. Això serveix per fer robots que <b>no cauen</b> de la taula!|Si el sensor queda sobre el vacío (en el borde de una mesa), la luz no rebota en ningún sitio y no vuelve nada: el sensor dice <b>1</b>, como si viera negro. ¡Esto sirve para hacer robots que <b>no se caen</b> de la mesa!",
            bad: 'Si el sensor diu 1, segur que hi ha cinta negra.|Si el sensor dice 1, seguro que hay cinta negra.', good: 'Un 1 vol dir «no torna llum»: cinta negra… o el buit de la vora.|Un 1 quiere decir «no vuelve luz»: cinta negra… o el vacío del borde.' }
        ] },
        { k: 'quiz', ph: 'prova', q: 'El sensor <b>M</b> és damunt la cinta negra i <b>L</b> i <b>R</b>, damunt el blanc. Què mostra el tauler «Línia L·M·R»?|El sensor <b>M</b> está sobre la cinta negra y <b>L</b> y <b>R</b>, sobre el blanco. ¿Qué muestra el panel «Línea L·M·R»?',
          opts: ['0 1 0|0 1 0', '1 0 1|1 0 1', '1 1 1|1 1 1'], a: 0, ex: "Negre = 1 i blanc = 0. Només el del mig veu la cinta.|Negro = 1 y blanco = 0. Solo el del medio ve la cinta." },
        { k: 'quiz', ph: 'prova', q: 'El robot passa per sobre una <b>zona blava</b>. Quin valor ADC llegeix el sensor M, més o menys?|El robot pasa por encima de una <b>zona azul</b>. ¿Qué valor ADC lee el sensor M, más o menos?',
          opts: ['≈ 360|≈ 360', '≈ 900|≈ 900', '≈ 90|≈ 90'], a: 0, art: () => TANI.k4adc(), ex: "Els colors queden entre el blanc (≈90) i el negre (≈900). Però compte: amb el 0/1, la zona blava diu 0, com el blanc.|Los colores quedan entre el blanco (≈90) y el negro (≈900). Pero cuidado: con el 0/1, la zona azul dice 0, como el blanco." },
        { k: 'unplug', ph: 'mans', ico: '🔦', title: 'La prova de la llanterna|La prueba de la linterna', t: 'Comprova tu mateix/a què veu un sensor de línia. Necessites un adult i el llum del mòbil.|Comprueba tú mismo/a qué ve un sensor de línea. Necesitas a un adulto y la luz del móvil.',
          steps: ["Busca un full blanc i una cosa ben negra: una cartolina, un jersei, una bossa…|Busca una hoja blanca y algo bien negro: una cartulina, un jersey, una bolsa…",
            "En una habitació amb poca llum, enceneu la llanterna del mòbil i apunteu-la al full blanc des d'uns 10 cm, una mica inclinada.|En una habitación con poca luz, encended la linterna del móvil y apuntadla a la hoja blanca desde unos 10 cm, un poco inclinada.",
            "Posa la mà al costat: hi veuràs la llum que rebota. Ara feu el mateix amb el negre: en torna molta menys!|Pon la mano al lado: verás la luz que rebota. Ahora haced lo mismo con el negro: ¡vuelve mucha menos!",
            "Prova també un full de color. Rebota més que el negre, però menys que el blanc: és el «≈360» del sensor!|Prueba también una hoja de color. Rebota más que el negro, pero menos que el blanco: ¡es el «≈360» del sensor!"],
          tip: "No miris mai directament la llum de la llanterna.|No mires nunca directamente la luz de la linterna." },
        { k: 'rpredict', ph: 'prova', q: "El robot repeteix: <b>si M = 1, para; si no, endavant</b>. Primer trobarà una zona blava i després dues cintes negres. <b>On s'aturarà?</b>|El robot repite: <b>si M = 1, para; si no, adelante</b>. Primero encontrará una zona azul y después dos cintas negras. <b>¿Dónde se parará?</b>",
          w: { w: 120, h: 80, bot: [12, 40, 90], zones: [{ id: 'z', r: [30, 24, 16, 32], col: 'blue' }], lines: [ln(66, 14, 66), ln(96, 14, 66)], marks: { A: [38, 40], B: [62, 40], C: [92, 40] }, time: 12 },
          prog: STOP_M, a: 'B', ex: "La zona blava no és negra: el 0/1 hi diu 0 i el robot continua. S'atura a la primera cinta negra.|La zona azul no es negra: el 0/1 dice 0 y el robot sigue. Se para en la primera cinta negra." },
        { k: 'rspot', ph: 'investiga', q: "Aquest robot arriba a la cinta, frena un instant… i continua! <b>Toca el bloc que en té la culpa.</b>|Este robot llega a la cinta, frena un instante… ¡y sigue! <b>Toca el bloque que tiene la culpa.</b>",
          w: { w: 120, h: 80, bot: [14, 40, 90], lines: [ln(70)], time: 8 }, prog: 'forever{ if:M=1{ stop:all } else{ run:all,fwd,255! } }',
          yes: "Exacte! A 255 va tan de pressa que, quan frena, el sensor ja ha passat la cinta, torna a veure blanc i torna a arrencar.|¡Exacto! A 255 va tan deprisa que, cuando frena, el sensor ya ha pasado la cinta, vuelve a ver blanco y vuelve a arrancar.",
          ex: "És la velocitat 255: el robot no frena en sec (té inèrcia) i la cinta només fa 2 cm. Quan el sensor torna a veure blanc, el «si no» el torna a engegar.|Es la velocidad 255: el robot no frena en seco (tiene inercia) y la cinta solo mide 2 cm. Cuando el sensor vuelve a ver blanco, el «si no» lo vuelve a poner en marcha." },
        { k: 'move', ph: 'pausa', secs: 30, t: "Fes de sensor de línia! Dret/a, mira el terra: quan imaginis una cinta <b>negra</b>, aixeca els braços (1); quan vegis <b>blanc</b>, abaixa'ls (0). Fes la seqüència: 0, 0, 1, 0, 1, 1, 0. Ara més de pressa!|¡Haz de sensor de línea! De pie, mira el suelo: cuando imagines una cinta <b>negra</b>, levanta los brazos (1); cuando veas <b>blanco</b>, bájalos (0). Haz la secuencia: 0, 0, 1, 0, 1, 1, 0. ¡Ahora más deprisa!" },
        { k: 'robo', ph: 'repte', q: "Les caixes es carreguen a la <b>línia de càrrega</b>. Fes que el robot avanci i <b>s'aturi a la cinta negra</b>. Compte: hi ha 3 pistes amb la cinta en llocs diferents.|Las cajas se cargan en la <b>línea de carga</b>. Haz que el robot avance y <b>se pare en la cinta negra</b>. Cuidado: hay 3 pistas con la cinta en sitios diferentes.",
          w: { w: 120, h: 80, bot: [14, 40, 90], lines: [ln(85)], zones: [{ id: 'm', r: [71, 26, 18, 28], col: 'yellow', label: 'CÀRREGA|CARGA' }], goal: [{ k: 'zone', id: 'm', stop: true }], time: 15,
            alts: [{ lines: [ln(60)], zones: [{ id: 'm', r: [46, 26, 18, 28], col: 'yellow', label: 'CÀRREGA|CARGA' }] }, { lines: [ln(104)], zones: [{ id: 'm', r: [90, 26, 18, 28], col: 'yellow', label: 'CÀRREGA|CARGA' }] }] },
          pal: PAL, ops: ['L', 'M', 'R', 'dist'], scripts: ['start', 'forever'], sol: STOP_M,
          hint: "A «per sempre»: si línia M = 1, atura els motors; si no, endavant a velocitat 120.|En «para siempre»: si línea M = 1, para los motores; si no, adelante a velocidad 120." },
        { k: 'robo', ph: 'repte', q: "Aquest robot de càrrega va <b>massa de pressa</b> i es passa la línia de descàrrega. Arregla'l perquè s'aturi a la cinta a les 3 pistes.|Este robot de carga va <b>demasiado deprisa</b> y se pasa la línea de descarga. Arréglalo para que se pare en la cinta en las 3 pistas.",
          w: { w: 120, h: 80, bot: [60, 72, 0], lines: [{ p: [[14, 30], [106, 30]] }], zones: [{ id: 'm', r: [46, 26, 28, 16], col: 'yellow', label: 'DESCÀRREGA|DESCARGA' }], goal: [{ k: 'zone', id: 'm', stop: true }], time: 15,
            alts: [{ lines: [{ p: [[14, 18], [106, 18]] }], zones: [{ id: 'm', r: [46, 14, 28, 16], col: 'yellow', label: 'DESCÀRREGA|DESCARGA' }] }, { lines: [{ p: [[14, 46], [106, 46]] }], zones: [{ id: 'm', r: [46, 42, 28, 16], col: 'yellow', label: 'DESCÀRREGA|DESCARGA' }] }] },
          pal: PAL, ops: ['L', 'M', 'R'], scripts: ['start', 'forever'], prog: 'forever{ if:M=1{ stop:all } else{ run:all,fwd,255 } }', sol: STOP_M,
          hint: "Toca el número 255 i posa-hi una velocitat més baixa, com 120. Com més lent, menys s'escapa quan frena.|Toca el número 255 y pon una velocidad más baja, como 120. Cuanto más lento, menos se escapa cuando frena." },
        { k: 'robo', ph: 'repte', q: "Ara el robot treballa damunt d'una <b>taula sense vora</b>. Ha d'avançar, <b>aturar-se abans de caure</b> i encendre els <b>llums vermells</b> d'avís. Les 3 taules fan llargades diferents.|Ahora el robot trabaja sobre una <b>mesa sin borde</b>. Tiene que avanzar, <b>pararse antes de caer</b> y encender las <b>luces rojas</b> de aviso. Las 3 mesas tienen longitudes diferentes.",
          w: { w: 110, h: 80, border: false, bot: [14, 40, 90], zones: [{ id: 'v', r: [92, 0, 18, 80], col: 'red', label: 'VORA|BORDE' }], goal: [{ k: 'zone', id: 'v', stop: true }, { k: 'car', c: 'red' }], time: 15,
            alts: [{ w: 80, zones: [{ id: 'v', r: [62, 0, 18, 80], col: 'red', label: 'VORA|BORDE' }] }, { w: 130, zones: [{ id: 'v', r: [112, 0, 18, 80], col: 'red', label: 'VORA|BORDE' }] }] },
          pal: [...PAL, 'car'], ops: ['L', 'M', 'R', 'dist'], scripts: ['start', 'forever'], sol: 'forever{ if:M=1{ stop:all car:all,red } else{ run:all,fwd,120 } }',
          hint: "Fora de la taula no torna llum: el sensor M diu 1, com amb la cinta negra. Dins del «si», atura el robot i encén els llums vermells.|Fuera de la mesa no vuelve luz: el sensor M dice 1, como con la cinta negra. Dentro del «si», para el robot y enciende las luces rojas." },
        { k: 'robo', ph: 'repte', q: "Les caixes es deixen a la <b>zona blava de descàrrega</b>. El robot s'hi ha d'aturar <b>ben a dins</b>. Pista: amb el 0/1, el blau sembla blanc… fes servir el valor <b>ADC</b>.|Las cajas se dejan en la <b>zona azul de descarga</b>. El robot tiene que pararse <b>bien dentro</b>. Pista: con el 0/1, el azul parece blanco… usa el valor <b>ADC</b>.",
          w: { w: 120, h: 80, bot: [14, 40, 90], zones: [{ id: 'b', r: [70, 22, 24, 36], col: 'blue', label: 'DESCÀRREGA|DESCARGA' }], goal: [{ k: 'zone', id: 'b', stop: true }], time: 15,
            alts: [{ zones: [{ id: 'b', r: [44, 22, 24, 36], col: 'blue', label: 'DESCÀRREGA|DESCARGA' }] }, { zones: [{ id: 'b', r: [92, 22, 24, 36], col: 'blue', label: 'DESCÀRREGA|DESCARGA' }] }] },
          pal: PAL, ops: ['M', 'aM', 'dist'], scripts: ['start', 'forever'], sol: 'forever{ if:aM>200{ wait:500 stop:all } else{ run:all,fwd,120 } }',
          hint: "Si línia M (ADC) > 200, ja és a sobre del blau. Però el sensor va davant del robot: espera 500 ms abans d'aturar-lo, perquè hi entri del tot.|Si línea M (ADC) > 200, ya está sobre el azul. Pero el sensor va delante del robot: espera 500 ms antes de pararlo, para que entre del todo." },
        { k: 'rcreate', ph: 'crea', name: 'El robot del moll|El robot del muelle', q: "Programa el teu robot del moll: ha d'anar fins a la <b>línia de càrrega</b>, aturar-s'hi i <b>avisar</b> que ha arribat, com tu vulguis: llums, una icona a la micro:bit…|Programa tu robot del muelle: tiene que ir hasta la <b>línea de carga</b>, pararse y <b>avisar</b> de que ha llegado, como tú quieras: luces, un icono en la micro:bit…",
          crit: ["S'atura a la cinta negra|Se para en la cinta negra", "Avisa amb els llums del cotxe o amb una icona|Avisa con las luces del coche o con un icono", "Fa servir el sensor de línia (no el temps)|Usa el sensor de línea (no el tiempo)"],
          w: { w: 120, h: 80, bot: [14, 40, 90], lines: [ln(90)], zones: [{ id: 'm', r: [76, 26, 18, 28], col: 'yellow', label: 'CÀRREGA|CARGA' }], goal: [{ k: 'zone', id: 'm', stop: true }], time: 15 },
          pal: [...PAL, 'car', 'under', 'icon', 'note'], ops: ['L', 'M', 'R', 'aM'], scripts: ['start', 'forever'], sol: 'forever{ if:M=1{ stop:all car:all,green icon:yes } else{ run:all,fwd,120 car:all,yellow } }',
          check: P => { const ks = []; const w = l => (l || []).forEach(b => { ks.push(b.k); w(b.b); w(b.e); }); Object.values(P).forEach(w); return ks.includes('car') || ks.includes('icon') || ks.includes('under') ? null : "Falta l'avís: afegeix llums o una icona quan arribi a la cinta.|Falta el aviso: añade luces o un icono cuando llegue a la cinta."; } },
        { k: 'quiz', ph: 'tanca', q: 'Què vol dir que el sensor M llegeixi <b>1</b>?|¿Qué quiere decir que el sensor M lea <b>1</b>?',
          opts: ["Que gairebé no torna llum: hi ha negre (o el buit)|Que casi no vuelve luz: hay negro (o el vacío)", 'Que hi ha un obstacle al davant|Que hay un obstáculo delante', 'Que el robot va a velocitat 1|Que el robot va a velocidad 1'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Per distingir una zona de color del blanc, quin valor fas servir?|Para distinguir una zona de color del blanco, ¿qué valor usas?',
          opts: ['El valor ADC, de 0 a 1023|El valor ADC, de 0 a 1023', 'El 0/1 del sensor de línia|El 0/1 del sensor de línea', 'La distància dels ultrasons|La distancia de los ultrasonidos'], a: 0, ex: "Amb el 0/1, el color i el blanc donen 0. L'ADC dona ≈90 al blanc i ≈360 als colors.|Con el 0/1, el color y el blanco dan 0. El ADC da ≈90 al blanco y ≈360 a los colores." },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* ===================================== k4-2 · La vora de la línia ===================================== */
    { id: 'k4-2', t: 'La vora de la línia|El borde de la línea', min: 45, badge: 'k_vora',
      learn: ['Amb un sol sensor, el robot segueix la vora de la línia: si veu negre gira cap a un costat i si veu blanc, cap a l\'altre.|Con un solo sensor, el robot sigue el borde de la línea: si ve negro gira hacia un lado y si ve blanco, hacia el otro.',
        'Per girar seguint la línia, un motor va més ràpid que l\'altre; com més diferència, més tancat és el gir.|Para girar siguiendo la línea, un motor va más rápido que el otro; cuanta más diferencia, más cerrado es el giro.',
        'A les corbes tancades cal anar més a poc a poc o girar més: si no, el robot perd la línia.|En las curvas cerradas hay que ir más despacio o girar más: si no, el robot pierde la línea.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Sobre la cinta negra, quin valor dona el sensor de línia M?|Sobre la cinta negra, ¿qué valor da el sensor de línea M?', opts: ['1|1', '0|0', '500|500'], a: 0, ex: "Negre = 1 (torna poca llum) i blanc = 0 (en torna molta).|Negro = 1 (vuelve poca luz) y blanco = 0 (vuelve mucha)." },
        { k: 'story', ph: 'missio', who: 'numi', scene: 'moll', t: "Ara les caixes han d'anar del moll fins al magatzem per un camí de cinta <b>ple de corbes</b>. Aturar-se a la cinta ja no n'hi ha prou: el robot l'ha de <b>seguir</b>. I sabies que ho pot fer amb un <b>sol sensor</b>? El truc és seguir la <b>vora</b>.|Ahora las cajas tienen que ir del muelle hasta el almacén por un camino de cinta <b>lleno de curvas</b>. Pararse en la cinta ya no basta: el robot tiene que <b>seguirla</b>. ¿Y sabías que puede hacerlo con un <b>solo sensor</b>? El truco es seguir el <b>borde</b>." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'La idea|La idea', t: 'Seguir la vora|Seguir el borde', anim: 'k4edge',
            x: "Amb el sensor <b>M</b>: si veu <b>negre</b>, el robot gira a la dreta i surt de la cinta; si veu <b>blanc</b>, gira a l'esquerra i hi torna. Així avança fent una petita ziga-zaga per la <b>vora</b>, la ratlla on s'acaba el negre i comença el blanc.|Con el sensor <b>M</b>: si ve <b>negro</b>, el robot gira a la derecha y sale de la cinta; si ve <b>blanco</b>, gira a la izquierda y vuelve. Así avanza haciendo un pequeño zigzag por el <b>borde</b>, la raya donde acaba el negro y empieza el blanco.",
            bad: 'El robot segueix el mig de la cinta.|El robot sigue el medio de la cinta.', good: 'Amb un sensor, el robot segueix la vora entre el negre i el blanc.|Con un sensor, el robot sigue el borde entre el negro y el blanco.' },
          { k: 'Programa|Programa', t: 'Un «si» amb dos girs|Un «si» con dos giros',
            robo: { w: { w: 120, h: 80, bot: [40, 66, 90], lines: [{ p: OVAL, closed: true }], time: 24 }, prog: ONE(180, 50) },
            x: "A cada branca hi ha dues ordres de motor: un motor <b>ràpid</b> (180) i l'altre <b>lent</b> (50). Com a la unitat 2, quan un motor va més ràpid que l'altre, el robot fa una corba cap al costat del motor lent.|En cada rama hay dos órdenes de motor: un motor <b>rápido</b> (180) y el otro <b>lento</b> (50). Como en la unidad 2, cuando un motor va más rápido que el otro, el robot hace una curva hacia el lado del motor lento." },
          { k: "L'altra vora|El otro borde", t: 'Canvia els girs de lloc|Cambia los giros de sitio',
            robo: { w: { w: 120, h: 80, bot: [40, 66, 90], lines: [{ p: OVAL, closed: true }], time: 24 }, prog: 'forever{ if:M=1{ run:L,fwd,50 run:R,fwd,180 } else{ run:L,fwd,180 run:R,fwd,50 } }' },
            x: "Si canvies els girs (negre → esquerra, blanc → dreta), el robot segueix <b>l'altra vora</b> de la cinta. Les dues maneres funcionen: tria'n una i no les barregis!|Si cambias los giros (negro → izquierda, blanco → derecha), el robot sigue <b>el otro borde</b> de la cinta. Las dos maneras funcionan: ¡elige una y no las mezcles!" },
          { k: 'Velocitat|Velocidad', t: 'A les corbes, compte!|¡En las curvas, cuidado!',
            robo: { w: { w: 120, h: 80, bot: [40, 66, 90], lines: [{ p: OVAL6, closed: true }], time: 12 }, prog: ONE(200, 150) },
            x: "Aquí els motors van a 200 i 150: gairebé igual. El robot gira massa poc i, a la primera corba tancada, <b>perd la línia</b>. Solució: més diferència entre els motors (180 i 50) o menys velocitat.|Aquí los motores van a 200 y 150: casi igual. El robot gira demasiado poco y, en la primera curva cerrada, <b>pierde la línea</b>. Solución: más diferencia entre los motores (180 y 50) o menos velocidad." }
        ] },
        { k: 'seq', ph: 'mans', q: 'Ordena el que passa quan el robot segueix la vora amb un sensor (comença a sobre de la cinta).|Ordena lo que pasa cuando el robot sigue el borde con un sensor (empieza encima de la cinta).',
          items: ['El sensor M veu negre (1)|El sensor M ve negro (1)', 'El robot gira a la dreta i surt de la cinta|El robot gira a la derecha y sale de la cinta', 'El sensor M veu blanc (0)|El sensor M ve blanco (0)', "El robot gira a l'esquerra i torna a la cinta|El robot gira a la izquierda y vuelve a la cinta"],
          ex: "I torna a començar, sense parar: per això el programa va dins de «per sempre».|Y vuelve a empezar, sin parar: por eso el programa va dentro de «para siempre»." },
        { k: 'quiz', ph: 'prova', q: "Amb el programa de la vora, el robot comença en un lloc <b>tot blanc</b>, lluny de la cinta. Què farà?|Con el programa del borde, el robot empieza en un sitio <b>todo blanco</b>, lejos de la cinta. ¿Qué hará?",
          opts: ["Girarà a l'esquerra sense parar, fent cercles|Girará a la izquierda sin parar, haciendo círculos", 'Anirà recte fins a trobar la cinta|Irá recto hasta encontrar la cinta', 'Es quedarà quiet|Se quedará quieto'], a: 0,
          ex: "Sempre veu blanc, i amb blanc la regla diu «gira a l'esquerra». Per això el robot ha de començar a la vora de la cinta.|Siempre ve blanco, y con blanco la regla dice «gira a la izquierda». Por eso el robot tiene que empezar en el borde de la cinta." },
        { k: 'rspot', ph: 'investiga', q: "Aquest robot surt de la cinta i ja no hi torna mai més. <b>Toca el bloc que s'ha d'arreglar.</b>|Este robot sale de la cinta y ya no vuelve nunca más. <b>Toca el bloque que hay que arreglar.</b>",
          w: { w: 120, h: 80, bot: [40, 66, 90], lines: [{ p: OVAL, closed: true }], time: 8 }, prog: 'forever{ if:M=1{ run:L,fwd,180 run:R,fwd,50 } else{ run:all,fwd,180! } }',
          yes: "Molt bé! Quan veu blanc va recte i s'allunya. Hauria de girar cap a la cinta: motor esquerre lent i dret ràpid.|¡Muy bien! Cuando ve blanco va recto y se aleja. Debería girar hacia la cinta: motor izquierdo lento y derecho rápido.",
          ex: "És el «si no»: amb blanc, el robot va recte i s'allunya de la cinta. Hauria de girar cap a l'esquerra per tornar-hi.|Es el «si no»: con blanco, el robot va recto y se aleja de la cinta. Debería girar hacia la izquierda para volver." },
        { k: 'quiz', ph: 'investiga', q: "Si canvies els dos girs de lloc (negre → esquerra, blanc → dreta), què passa?|Si cambias los dos giros de sitio (negro → izquierda, blanco → derecha), ¿qué pasa?",
          opts: ["Segueix l'altra vora de la cinta|Sigue el otro borde de la cinta", 'Ja no funciona mai|Ya no funciona nunca', 'Va el doble de ràpid|Va el doble de rápido'], a: 0, art: () => TANI.k4edge() },
        { k: 'move', ph: 'pausa', secs: 30, t: "Fes de robot seguidor de vores! Imagina una ratlla a terra: fes un pas en diagonal cap a la dreta («negre!») i un cap a l'esquerra («blanc!»). Avança 10 passos en ziga-zaga sense perdre la ratlla.|¡Haz de robot seguidor de bordes! Imagina una raya en el suelo: da un paso en diagonal hacia la derecha («¡negro!») y uno hacia la izquierda («¡blanco!»). Avanza 10 pasos en zigzag sin perder la raya." },
        { k: 'robo', ph: 'repte', q: "El primer camí del magatzem té <b>corbes suaus</b>. Programa el robot perquè segueixi la cinta fins al final, passant pels punts 1, 2, 3 i 4. Hi ha 3 camins diferents!|El primer camino del almacén tiene <b>curvas suaves</b>. Programa el robot para que siga la cinta hasta el final, pasando por los puntos 1, 2, 3 y 4. ¡Hay 3 caminos diferentes!",
          w: { w: 120, h: 80, bot: [12, 44, 142], lines: [{ p: S1 }], goal: [{ k: 'cps', pts: [S1[4], S1[8], S1[12], S1[16]], r: 7 }], time: 30,
            alts: [{ bot: [12, 36, 38], lines: [{ p: S2 }], goal: [{ k: 'cps', pts: [S2[4], S2[8], S2[12], S2[16]], r: 7 }] }, { bot: [12, 40, 126], lines: [{ p: S3 }], goal: [{ k: 'cps', pts: [S3[4], S3[8], S3[12], S3[16]], r: 7 }] }] },
          pal: PAL, ops: ['L', 'M', 'R'], scripts: ['start', 'forever'], sol: ONE(150, 50),
          hint: "Si M = 1: motor esquerre 150 i dret 50 (gira a la dreta). Si no: esquerre 50 i dret 150 (gira a l'esquerra).|Si M = 1: motor izquierdo 150 y derecho 50 (gira a la derecha). Si no: izquierdo 50 y derecho 150 (gira a la izquierda)." },
        { k: 'robo', ph: 'repte', q: "En aquest circuit hi ha <b>corbes tancades</b> i el robot es perd. Canvia les velocitats perquè faci la volta sencera (punts 1 a 4).|En este circuito hay <b>curvas cerradas</b> y el robot se pierde. Cambia las velocidades para que dé la vuelta entera (puntos 1 a 4).",
          w: { w: 120, h: 80, bot: [40, 66, 90], lines: [{ p: OVAL6, closed: true }], goal: [{ k: 'cps', pts: OVAL_CPS, r: 7 }], time: 40 },
          pal: PAL, ops: ['L', 'M', 'R'], scripts: ['start', 'forever'], prog: ONE(200, 150), sol: ONE(180, 50),
          hint: "Amb 200 i 150 gira massa poc. Fes que el motor lent vagi molt més lent: per exemple 180 i 50.|Con 200 y 150 gira demasiado poco. Haz que el motor lento vaya mucho más lento: por ejemplo 180 y 50." },
        { k: 'robo', ph: 'repte', q: "<b>La volta al magatzem.</b> Fes que el robot doni una volta sencera al circuit (punts 1 a 4). El mateix programa ha de funcionar als 3 circuits, i n'hi ha un que va en sentit contrari!|<b>La vuelta al almacén.</b> Haz que el robot dé una vuelta entera al circuito (puntos 1 a 4). El mismo programa tiene que funcionar en los 3 circuitos, ¡y hay uno que va en sentido contrario!",
          w: { w: 120, h: 80, bot: [40, 66, 90], lines: [{ p: OVAL, closed: true }], goal: [{ k: 'cps', pts: OVAL_CPS, r: 7 }], time: 40,
            alts: [{ bot: [70, 70, 270], lines: [{ p: SQ, closed: true }], goal: [{ k: 'cps', pts: [[30, 40], [60, 10], [90, 40], [60, 70]], r: 7 }] }, { bot: [50, 18, 90], lines: [{ p: PILL, closed: true }], goal: [{ k: 'cps', pts: [[104, 40], [60, 62], [16, 40], [60, 18]], r: 7 }] }] },
          pal: PAL, ops: ['L', 'M', 'R'], scripts: ['start', 'forever'], sol: ONE(180, 50),
          hint: "El programa de la vora no depèn de la forma del circuit: el sensor el guia. Prova amb 180 i 50.|El programa del borde no depende de la forma del circuito: el sensor lo guía. Prueba con 180 y 50." },
        { k: 'robo', ph: 'repte', q: "Repte difícil: el camí acaba a l'<b>estació blava</b>. El robot ha de seguir la cinta i <b>aturar-se</b> quan arribi al blau. Pista: el valor ADC distingeix tres coses: negre (≈900), blau (≈360) i blanc (≈90).|Reto difícil: el camino termina en la <b>estación azul</b>. El robot tiene que seguir la cinta y <b>pararse</b> cuando llegue al azul. Pista: el valor ADC distingue tres cosas: negro (≈900), azul (≈360) y blanco (≈90).",
          w: { w: 120, h: 80, bot: [12, 44, 145], lines: [{ p: E1 }], zones: [{ id: 'e', r: [96, 32, 20, 24], col: 'blue', label: 'ESTACIÓ|ESTACIÓN' }], goal: [{ k: 'cps', pts: [E1[5], E1[10], E1[14]], r: 7 }, { k: 'stopped' }], time: 30,
            alts: [{ bot: [12, 30, 109], lines: [{ p: E2 }], zones: [{ id: 'e', r: [96, 48, 20, 24], col: 'blue', label: 'ESTACIÓ|ESTACIÓN' }], goal: [{ k: 'cps', pts: [E2[5], E2[10], E2[14]], r: 7 }, { k: 'stopped' }] },
              { bot: [12, 56, 56], lines: [{ p: E3 }], zones: [{ id: 'e', r: [96, 44, 20, 24], col: 'blue', label: 'ESTACIÓ|ESTACIÓN' }], goal: [{ k: 'cps', pts: [E3[5], E3[10], E3[14]], r: 7 }, { k: 'stopped' }] }] },
          pal: PAL, ops: ['M', 'aM'], scripts: ['start', 'forever'], sol: 'forever{ if:aM>600{ run:L,fwd,150 run:R,fwd,40 } else{ if:aM>200{ stop:all } else{ run:L,fwd,40 run:R,fwd,150 } } }',
          hint: "Fes tres casos amb «si… si no»: si ADC > 600 (negre), gira a la dreta; si no, si ADC > 200 (blau), atura't; si no (blanc), gira a l'esquerra.|Haz tres casos con «si… si no»: si ADC > 600 (negro), gira a la derecha; si no, si ADC > 200 (azul), párate; si no (blanco), gira a la izquierda." },
        { k: 'rcreate', ph: 'crea', name: 'La ruta de les caixes|La ruta de las cajas', q: "Projecte: el robot de les caixes fa la volta llarga al magatzem amb <b>llums que avisen</b>: un color quan el sensor veu negre i un altre quan veu blanc. Tria tu els colors i les velocitats!|Proyecto: el robot de las cajas da la vuelta larga al almacén con <b>luces que avisan</b>: un color cuando el sensor ve negro y otro cuando ve blanco. ¡Elige tú los colores y las velocidades!",
          crit: ['Fa la volta sencera seguint la vora (punts 1 a 4)|Da la vuelta entera siguiendo el borde (puntos 1 a 4)', "Els llums canvien de color segons el que veu el sensor|Las luces cambian de color según lo que ve el sensor"],
          w: { w: 120, h: 80, bot: [50, 68, 90], lines: [{ p: LONG2, closed: true }], goal: [{ k: 'cps', pts: [[110, 40], [60, 12], [10, 40], [60, 68]], r: 7 }], time: 45 },
          pal: [...PAL, 'car', 'under'], ops: ['L', 'M', 'R', 'aM'], scripts: ['start', 'forever'], sol: 'forever{ if:M=1{ run:L,fwd,180 run:R,fwd,50 car:all,yellow } else{ run:L,fwd,50 run:R,fwd,180 car:all,blue } }',
          check: P => { let n = 0; const w = l => (l || []).forEach(b => { if (b.k === 'car' || b.k === 'under') n++; w(b.b); w(b.e); }); Object.values(P).forEach(w); return n >= 2 ? null : 'Posa un bloc de llums a cada branca del «si»: un color per al negre i un altre per al blanc.|Pon un bloque de luces en cada rama del «si»: un color para el negro y otro para el blanco.'; } },
        { k: 'quiz', ph: 'tanca', q: 'Amb un sol sensor, què segueix el robot?|Con un solo sensor, ¿qué sigue el robot?', opts: ['La vora entre el negre i el blanc|El borde entre el negro y el blanco', 'El mig exacte de la cinta|El centro exacto de la cinta', 'La paret del magatzem|La pared del almacén'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'A una corba tancada, el robot perd la línia. Què pots provar?|En una curva cerrada, el robot pierde la línea. ¿Qué puedes probar?',
          opts: ['Més diferència entre els motors o menys velocitat|Más diferencia entre los motores o menos velocidad', 'Posar els dos motors a la mateixa velocitat|Poner los dos motores a la misma velocidad', 'Posar els dos motors a 255|Poner los dos motores a 255'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* ===================================== k4-3 · Dos sensors i cruïlles ===================================== */
    { id: 'k4-3', t: 'Dos sensors i cruïlles|Dos sensores y cruces', min: 45, badge: 'k_cruilla',
      learn: ['Amb dos sensors (L i R) la cinta queda al mig: el robot va recte i només gira quan un dels dos veu negre.|Con dos sensores (L y R) la cinta queda en medio: el robot va recto y solo gira cuando uno de los dos ve negro.',
        'Quan L i R veuen negre alhora és una cruïlla o una estació: aquesta condició s\'ha de mirar primer.|Cuando L y R ven negro a la vez es un cruce o una estación: esta condición hay que mirarla primero.',
        'Amb tres sensors, si no en veu cap (0 0 0), el robot continua fent el mateix i així no es perd als revolts de 90°.|Con tres sensores, si no ve ninguno (0 0 0), el robot sigue haciendo lo mismo y así no se pierde en las curvas de 90°.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Amb un sol sensor, el robot segueix…|Con un solo sensor, el robot sigue…', opts: ['la vora de la cinta|el borde de la cinta', 'el mig de la cinta|el centro de la cinta', 'el robot del davant|el robot de delante'], a: 0, ex: "I fa ziga-zaga: si veu negre gira cap a un costat i si veu blanc, cap a l'altre.|Y hace zigzag: si ve negro gira hacia un lado y si ve blanco, hacia el otro." },
        { k: 'story', ph: 'missio', who: 'both', scene: 'moll', t: "El magatzem del port ha crescut: ara hi ha <b>cruïlles</b> i <b>estacions</b> marcades amb una ratlla travessera. Amb un sol sensor el robot fa ziga-zaga i no sap quan arriba a una estació. Avui farem servir <b>dos</b> i <b>tres</b> sensors alhora!|El almacén del puerto ha crecido: ahora hay <b>cruces</b> y <b>estaciones</b> marcadas con una raya transversal. Con un solo sensor el robot hace zigzag y no sabe cuándo llega a una estación. ¡Hoy usaremos <b>dos</b> y <b>tres</b> sensores a la vez!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Dos sensors|Dos sensores', t: 'La cinta al mig|La cinta en medio', anim: 'k4two',
            x: "<b>L</b> i <b>R</b> queden a banda i banda de la cinta. Si tots dos veuen blanc (0 0), la cinta és al mig: <b>recte</b>. Si <b>L</b> veu negre, la cinta s'ha mogut cap a l'esquerra: <b>gira a l'esquerra</b>. Si <b>R</b> veu negre: <b>gira a la dreta</b>.|<b>L</b> y <b>R</b> quedan a ambos lados de la cinta. Si los dos ven blanco (0 0), la cinta está en medio: <b>recto</b>. Si <b>L</b> ve negro, la cinta se ha movido hacia la izquierda: <b>gira a la izquierda</b>. Si <b>R</b> ve negro: <b>gira a la derecha</b>." },
          { k: 'Programa|Programa', t: 'Recte quan pot, gira quan cal|Recto cuando puede, gira cuando hace falta',
            robo: { w: { w: 120, h: 80, bot: [40, 62, 90], lines: [{ p: LONG1, closed: true }], time: 16 }, prog: TWO(200, 30) },
            x: "Tres casos amb «si… si no» un dins de l'altre: si L, a l'esquerra; si no, si R, a la dreta; si no, recte. A les rectes no fa ziga-zaga: va més de pressa que amb un sensor.|Tres casos con «si… si no» uno dentro del otro: si L, a la izquierda; si no, si R, a la derecha; si no, recto. En las rectas no hace zigzag: va más deprisa que con un sensor." },
          { k: 'Tres sensors|Tres sensores', t: 'Què diuen L, M i R junts|Qué dicen L, M y R juntos', anim: 'k4cross',
            x: "Amb els tres sensors el robot sap més coses. <b>1 1 1</b>: tots veuen negre, és una <b>cruïlla</b> o la ratlla d'una <b>estació</b>. <b>0 0 0</b>: no veu la cinta; el millor és <b>no canviar res</b> i continuar girant com abans, fins que la torni a trobar.|Con los tres sensores el robot sabe más cosas. <b>1 1 1</b>: todos ven negro, es un <b>cruce</b> o la raya de una <b>estación</b>. <b>0 0 0</b>: no ve la cinta; lo mejor es <b>no cambiar nada</b> y seguir girando como antes, hasta que la vuelva a encontrar." },
          { k: "L'estació|La estación", t: 'Una condició amb «i»|Una condición con «y»',
            robo: { w: { w: 120, h: 80, bot: [12, 40, 147], lines: [{ p: ST1 }, { p: [[93.3, 44.4], [106.7, 35.6]] }], time: 12 }, prog: TWOX(150, 30, 'stop:all') },
            x: "La condició <b>L = 1 i R = 1</b> només és certa quan els dos sensors veuen negre <b>alhora</b>: a la ratlla de l'estació. Ha d'anar <b>primer</b>: si no, el robot veuria L = 1 i giraria.|La condición <b>L = 1 y R = 1</b> solo es cierta cuando los dos sensores ven negro <b>a la vez</b>: en la raya de la estación. Tiene que ir <b>primero</b>: si no, el robot vería L = 1 y giraría.",
            bad: "Primer «si L = 1» i després «si L = 1 i R = 1».|Primero «si L = 1» y después «si L = 1 y R = 1».", good: "El cas més especial primer: «si L = 1 i R = 1».|El caso más especial primero: «si L = 1 y R = 1»." }
        ] },
        { k: 'quiz', ph: 'prova', q: 'Els sensors diuen <b>L 0 · M 1 · R 0</b>. Què ha de fer el robot?|Los sensores dicen <b>L 0 · M 1 · R 0</b>. ¿Qué tiene que hacer el robot?', opts: ['Anar recte|Ir recto', "Girar a l'esquerra|Girar a la izquierda", 'Aturar-se|Pararse'], a: 0, ex: "La cinta és just al mig: tot va bé!|La cinta está justo en medio: ¡todo va bien!" },
        { k: 'quiz', ph: 'prova', q: 'Els sensors diuen <b>L 1 · M 1 · R 1</b>. On és el robot?|Los sensores dicen <b>L 1 · M 1 · R 1</b>. ¿Dónde está el robot?', opts: ['A una cruïlla o a la ratlla d\'una estació|En un cruce o en la raya de una estación', 'Fora de la cinta|Fuera de la cinta', 'Davant d\'una paret|Delante de una pared'], a: 0, art: () => TANI.k4cross() },
        { k: 'rpredict', ph: 'prova', q: "Aquest robot segueix la cinta amb dos sensors (primer mira L, després R) i arriba a una <b>cruïlla</b>. Cap on anirà?|Este robot sigue la cinta con dos sensores (primero mira L, después R) y llega a un <b>cruce</b>. ¿Hacia dónde irá?",
          w: { w: 120, h: 80, bot: [12, 40, 90], lines: [{ p: [[10, 40], [110, 40]] }, { p: [[60, 14], [60, 66]] }], marks: { A: [60, 12], B: [104, 40], C: [60, 68] }, time: 7 }, prog: TWO(150, 30), a: 'A',
          ex: "A la cruïlla L i R veuen negre, però el programa mira primer L: «gira a l'esquerra»! El robot gira i se'n va amunt. Per anar recte, cal mirar primer «L = 1 i R = 1».|En el cruce L y R ven negro, pero el programa mira primero L: «¡gira a la izquierda!». El robot gira y se va arriba. Para ir recto, hay que mirar primero «L = 1 y R = 1»." },
        { k: 'unplug', ph: 'mans', ico: '👣', title: 'El robot de dos peus|El robot de dos pies', t: 'Fes de robot de dos sensors amb algú de casa.|Haz de robot de dos sensores con alguien de casa.',
          steps: ["Poseu una corda o una tira de paper llarga a terra, fent una corba suau, i una tira travessera al final: l'estació.|Poned una cuerda o una tira de papel larga en el suelo, haciendo una curva suave, y una tira transversal al final: la estación.",
            "Camina a poc a poc amb un peu a cada costat de la corda, sense trepitjar-la: els teus peus són els sensors L i R.|Camina despacio con un pie a cada lado de la cuerda, sin pisarla: tus pies son los sensores L y R.",
            "Si el peu esquerre toca la corda, gira una mica a l'esquerra; si la toca el dret, una mica a la dreta.|Si el pie izquierdo toca la cuerda, gira un poco a la izquierda; si la toca el derecho, un poco a la derecha.",
            "Quan els dos peus toquin la tira travessera alhora, atura't: has arribat a l'estació! Després, canvieu els papers.|Cuando los dos pies toquen la tira transversal a la vez, párate: ¡has llegado a la estación! Después, cambiad los papeles."],
          tip: "Feu-ho en un lloc sense obstacles i sense córrer.|Hacedlo en un sitio sin obstáculos y sin correr." },
        { k: 'move', ph: 'pausa', secs: 25, t: "Fes de semàfor de sensors! Braç esquerre amunt = L veu negre, braç dret amunt = R veu negre. Fes: «recte» (cap braç), «esquerra» (l'esquerre), «dreta» (el dret) i «estació!» (els dos). Més de pressa!|¡Haz de semáforo de sensores! Brazo izquierdo arriba = L ve negro, brazo derecho arriba = R ve negro. Haz: «recto» (ningún brazo), «izquierda» (el izquierdo), «derecha» (el derecho) y «¡estación!» (los dos). ¡Más deprisa!" },
        { k: 'robo', ph: 'repte', q: "<b>Dos ulls, més recte.</b> Programa el robot perquè segueixi el circuit amb els sensors <b>L i R</b> (aquí no hi ha el M!) i faci la volta sencera als 2 circuits.|<b>Dos ojos, más recto.</b> Programa el robot para que siga el circuito con los sensores <b>L y R</b> (¡aquí no está el M!) y dé la vuelta entera en los 2 circuitos.",
          w: { w: 120, h: 80, bot: [40, 62, 90], lines: [{ p: LONG1, closed: true }], goal: [{ k: 'cps', pts: [[110, 40], [60, 18], [10, 40], [60, 62]], r: 7 }], time: 40,
            alts: [{ bot: [80, 68, 270], lines: [{ p: LONG2, closed: true }], goal: [{ k: 'cps', pts: [[10, 40], [60, 12], [110, 40], [60, 68]], r: 7 }] }] },
          pal: PAL, ops: ['L', 'R'], scripts: ['start', 'forever'], sol: TWO(200, 30),
          hint: "Si L = 1: esquerre 30 i dret 200. Si no, si R = 1: esquerre 200 i dret 30. Si no: tots dos a 200.|Si L = 1: izquierdo 30 y derecho 200. Si no, si R = 1: izquierdo 200 y derecho 30. Si no: los dos a 200." },
        { k: 'robo', ph: 'repte', q: "Cada camí acaba en una <b>estació</b> (la ratlla travessera). Fes que el robot segueixi la cinta i <b>s'aturi a l'estació</b>, a les 3 pistes.|Cada camino termina en una <b>estación</b> (la raya transversal). Haz que el robot siga la cinta y <b>se pare en la estación</b>, en las 3 pistas.",
          w: { w: 120, h: 80, bot: [12, 40, 147], lines: [{ p: ST1 }, { p: [[93.3, 44.4], [106.7, 35.6]] }], zones: [{ id: 'e', r: [84, 29, 18, 22], col: 'green', label: 'ESTACIÓ|ESTACIÓN' }], goal: [{ k: 'cps', pts: [ST1[8]], r: 7 }, { k: 'zone', id: 'e', stop: true }], time: 30,
            alts: [{ bot: [12, 60, 66], lines: [{ p: ST2 }, { p: [[103.3, 27.3], [96.7, 12.7]] }], zones: [{ id: 'e', r: [84, 9, 18, 22], col: 'green', label: 'ESTACIÓ|ESTACIÓN' }], goal: [{ k: 'cps', pts: [ST2[8]], r: 7 }, { k: 'zone', id: 'e', stop: true }] },
              { bot: [12, 28, 137], lines: [{ p: ST3 }, { p: [[95.5, 44.3], [84.5, 32.7]] }], zones: [{ id: 'e', r: [74, 28, 18, 22], col: 'green', label: 'ESTACIÓ|ESTACIÓN' }], goal: [{ k: 'cps', pts: [ST3[8]], r: 7 }, { k: 'zone', id: 'e', stop: true }] }] },
          pal: [...PAL, 'and'], ops: ['L', 'M', 'R'], scripts: ['start', 'forever'], sol: TWOX(150, 30, 'stop:all'),
          hint: "Primer de tot: si L = 1 i R = 1, atura't. Si no, el seguidor de dos sensors. I no hi vagis massa de pressa (150 va bé)!|Lo primero: si L = 1 y R = 1, párate. Si no, el seguidor de dos sensores. ¡Y no vayas demasiado deprisa (150 va bien)!" },
        { k: 'robo', ph: 'repte', q: "En aquests camins hi ha <b>cruïlles</b>. El robot hauria d'anar recte, però gira! Arregla el programa perquè <b>creui recte</b> i arribi al final (punts 1, 2 i 3) a les 3 pistes.|En estos caminos hay <b>cruces</b>. El robot debería ir recto, ¡pero gira! Arregla el programa para que <b>cruce recto</b> y llegue al final (puntos 1, 2 y 3) en las 3 pistas.",
          w: { w: 120, h: 80, bot: [12, 40, 90], lines: [{ p: [[10, 40], [110, 40]] }, { p: [[60, 8], [60, 72]] }], goal: [{ k: 'cps', pts: [[40, 40], [80, 40], [104, 40]], r: 7 }], time: 20,
            alts: [{ lines: [{ p: [[10, 40], [45, 40], [75, 25], [110, 25]] }, { p: [[60, 6], [60, 74]] }], goal: [{ k: 'cps', pts: [[40, 40], [75, 25], [104, 25]], r: 7 }] },
              { lines: [{ p: [[10, 40], [110, 40]] }, { p: [[35, 10], [35, 70]] }, { p: [[80, 10], [80, 70]] }], goal: [{ k: 'cps', pts: [[50, 40], [90, 40], [104, 40]], r: 7 }] }] },
          pal: [...PAL, 'and'], ops: ['L', 'R'], scripts: ['start', 'forever'], prog: TWO(150, 30), sol: TWOX(150, 30, 'run:all,fwd,150'),
          hint: "Afegeix al principi un «si L = 1 i R = 1»: endavant recte. Posa el seguidor d'abans dins del seu «si no».|Añade al principio un «si L = 1 y R = 1»: adelante recto. Pon el seguidor de antes dentro de su «si no»." },
        { k: 'robo', ph: 'repte', q: "Repte difícil: <b>revolts de 90°</b>! Amb dos sensors, el robot es passa el revolt i es perd. Fes servir també el <b>M</b>: si cap sensor veu la cinta (0 0 0), que <b>no canviï res</b> i continuï girant.|Reto difícil: ¡<b>curvas de 90°</b>! Con dos sensores, el robot se pasa la curva y se pierde. Usa también el <b>M</b>: si ningún sensor ve la cinta (0 0 0), que <b>no cambie nada</b> y siga girando.",
          w: { w: 120, h: 80, bot: [10, 60, 90], lines: [{ p: STEP_A }], goal: [{ k: 'cps', pts: [[40, 60], [40, 25], [80, 25], [80, 55], [108, 55]], r: 7 }], time: 30,
            alts: [{ bot: [10, 22, 90], lines: [{ p: STEP_B }], goal: [{ k: 'cps', pts: [[36, 22], [36, 58], [70, 58], [70, 28], [108, 28]], r: 7 }] },
              { bot: [10, 40, 90], lines: [{ p: STEP_C }], goal: [{ k: 'cps', pts: [[30, 40], [30, 14], [60, 14], [60, 66], [92, 66], [92, 40], [108, 40]], r: 7 }] }] },
          pal: PAL, ops: ['L', 'M', 'R'], scripts: ['start', 'forever'], prog: TWO(150, 0), sol: THREE(150, 0),
          hint: "L'últim «si no» (recte) fa que es perdi. Canvia'l per «si M = 1: recte», sense cap «si no». Quan no veu res, els motors continuen fent el que feien: girar!|El último «si no» (recto) hace que se pierda. Cámbialo por «si M = 1: recto», sin ningún «si no». Cuando no ve nada, los motores siguen haciendo lo que hacían: ¡girar!" },
        { k: 'rcreate', ph: 'crea', name: 'El robot amb intermitents|El robot con intermitentes', q: "Projecte: posa <b>intermitents</b> al teu robot de dos sensors, com un cotxe: quan gira a l'esquerra, s'encén el llum esquerre; quan gira a la dreta, el dret; i quan va recte, els dos d'un altre color.|Proyecto: pon <b>intermitentes</b> a tu robot de dos sensores, como un coche: cuando gira a la izquierda, se enciende la luz izquierda; cuando gira a la derecha, la derecha; y cuando va recto, las dos de otro color.",
          crit: ['Fa la volta sencera al circuit|Da la vuelta entera al circuito', "Els llums del costat del gir s'encenen|Las luces del lado del giro se encienden", 'Fa servir els sensors L i R|Usa los sensores L y R'],
          w: { w: 120, h: 80, bot: [40, 62, 90], lines: [{ p: LONG1, closed: true }], goal: [{ k: 'cps', pts: [[110, 40], [60, 18], [10, 40], [60, 62]], r: 7 }], time: 40 },
          pal: [...PAL, 'and', 'car', 'under'], ops: ['L', 'M', 'R'], scripts: ['start', 'forever'],
          sol: 'forever{ if:L=1{ run:L,fwd,30 run:R,fwd,180 car:L,yellow car:R,black } else{ if:R=1{ run:L,fwd,180 run:R,fwd,30 car:R,yellow car:L,black } else{ run:all,fwd,180 car:all,white } } }',
          check: P => { let n = 0; const w = l => (l || []).forEach(b => { if (b.k === 'car' && b.side !== 'all') n++; w(b.b); w(b.e); }); Object.values(P).forEach(w); return n >= 2 ? null : "Fes servir els llums d'un sol costat (l'esquerre o el dret) quan el robot gira.|Usa las luces de un solo lado (la izquierda o la derecha) cuando el robot gira."; } },
        { k: 'quiz', ph: 'tanca', q: 'Per què la condició «L = 1 i R = 1» ha d\'anar la primera?|¿Por qué la condición «L = 1 y R = 1» tiene que ir la primera?',
          opts: ["Perquè, si no, a la cruïlla el robot veuria L = 1 i giraria|Porque, si no, en el cruce el robot vería L = 1 y giraría", 'Perquè és la més curta|Porque es la más corta', "No importa l'ordre dels «si»|No importa el orden de los «si»"], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Què fa el robot de tres sensors quan no veu la cinta (0 0 0)?|¿Qué hace el robot de tres sensores cuando no ve la cinta (0 0 0)?',
          opts: ['Continua fent el mateix que abans fins que la torna a trobar|Sigue haciendo lo mismo que antes hasta que la vuelve a encontrar', 'Para de cop|Para de golpe', 'Va recte cap a la paret|Va recto hacia la pared'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* ===================================== k4-4 · Projecte: el tren de mercaderies ===================================== */
    { id: 'k4-4', t: 'Projecte: el tren de mercaderies|Proyecto: el tren de mercancías', min: 45, proj: true, badge: 'k_tren',
      learn: ['El xip del Maqueen pot seguir la línia sol (seguiment de línia activat), però no sap on s\'ha d\'aturar: això ho decideix el teu programa.|El chip del Maqueen puede seguir la línea solo (seguimiento de línea activado), pero no sabe dónde tiene que pararse: eso lo decide tu programa.',
        'Per tornar a arrencar després d\'una estació, cal avançar una mica per sortir de la ratlla.|Para volver a arrancar después de una estación, hay que avanzar un poco para salir de la raya.',
        'Un projecte gran es fa a trossos: programar una part, provar-la a totes les pistes i després afegir la següent.|Un proyecto grande se hace a trozos: programar una parte, probarla en todas las pistas y después añadir la siguiente.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Què vol dir que els sensors diguin <b>L 1 · M 1 · R 1</b>?|¿Qué quiere decir que los sensores digan <b>L 1 · M 1 · R 1</b>?', opts: ["Que el robot és a una cruïlla o a la ratlla d'una estació|Que el robot está en un cruce o en la raya de una estación", 'Que el robot ha perdut la línia|Que el robot ha perdido la línea', 'Que hi ha una zona blava|Que hay una zona azul'], a: 0 },
        { k: 'story', ph: 'missio', who: 'both', scene: 'moll', t: "Gran dia al port! Ha arribat un vaixell ple de caixes i el <b>tren de mercaderies</b> les ha de portar del moll fins a la <b>terminal blava</b>, aturant-se a cada <b>estació</b> per avisar amb un xiulet. Avui en seràs l'enginyer/a: ho planificaràs, ho programaràs i ho provaràs.|¡Gran día en el puerto! Ha llegado un barco lleno de cajas y el <b>tren de mercancías</b> las tiene que llevar del muelle hasta la <b>terminal azul</b>, parándose en cada <b>estación</b> para avisar con un silbido. Hoy serás su ingeniero/a: lo planificarás, lo programarás y lo probarás." },
        { k: 'story', ph: 'missio', who: 'bit', mood: 'think', t: "BIP! El projecte té tres parts: <b>1)</b> que el tren segueixi la via fins a la terminal i s'hi aturi; <b>2)</b> que pari i xiuli a les estacions; <b>3)</b> el teu tren, amb llums i el teu estil. Anem a trossos!|¡BIP! El proyecto tiene tres partes: <b>1)</b> que el tren siga la vía hasta la terminal y se pare; <b>2)</b> que pare y silbe en las estaciones; <b>3)</b> tu tren, con luces y tu estilo. ¡Vamos a trozos!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'El xip|El chip', t: 'El seguiment de línia automàtic|El seguimiento de línea automático',
            robo: { w: { w: 120, h: 80, bot: [40, 66, 90], lines: [{ p: OVAL, closed: true }], time: 20 }, prog: 'start{ patrol:on }' },
            x: "El Maqueen porta un xip que sap seguir la línia <b>sol</b>, amb els tres sensors: el bloc <b>«seguiment de línia activat»</b>. Va a una velocitat fixa, més aviat lenta, i al simulador, a les cruïlles, continua recte. Per parar-lo: <b>«seguiment de línia desactivat»</b> i, per si de cas, «atura el motor».|El Maqueen lleva un chip que sabe seguir la línea <b>solo</b>, con los tres sensores: el bloque <b>«seguimiento de línea activado»</b>. Va a una velocidad fija, más bien lenta, y en el simulador, en los cruces, sigue recto. Para pararlo: <b>«seguimiento de línea desactivado»</b> y, por si acaso, «para el motor»." },
          { k: 'Compte!|¡Cuidado!', t: 'El xip no sap on parar|El chip no sabe dónde parar',
            robo: { w: { w: 120, h: 80, bot: [12, 40, 90], lines: [{ p: [[10, 40], [60, 40]] }], time: 12 }, prog: 'start{ patrol:on }' },
            x: "Quan s'acaba la cinta, el xip no s'atura: continua endavant! On i quan s'ha de parar ho decideix <b>el teu programa</b>, vigilant els sensors dins de «per sempre».|Cuando se acaba la cinta, el chip no se para: ¡sigue adelante! Dónde y cuándo tiene que pararse lo decide <b>tu programa</b>, vigilando los sensores dentro de «para siempre».",
            bad: "Amb el seguiment del xip, el robot ja sap on ha d'anar.|Con el seguimiento del chip, el robot ya sabe adónde tiene que ir.", good: "El xip segueix la cinta; el meu programa decideix on s'atura.|El chip sigue la cinta; mi programa decide dónde se para." },
          { k: 'Estacions|Estaciones', t: 'Parar, xiular i tornar a arrencar|Parar, silbar y volver a arrancar',
            robo: { w: { w: 120, h: 80, ...nonote(ROUTE_A), time: 26 }, prog: PATROL_ST },
            x: "A la ratlla (L = 1 i R = 1): desactiva el seguiment, atura els motors, toca una nota i espera. Després, <b>avança mig segon</b> per sortir de la ratlla i torna a activar el seguiment. A la terminal blava (ADC entre 200 i 600) s'atura del tot.|En la raya (L = 1 y R = 1): desactiva el seguimiento, para los motores, toca una nota y espera. Después, <b>avanza medio segundo</b> para salir de la raya y vuelve a activar el seguimiento. En la terminal azul (ADC entre 200 y 600) se para del todo." },
          { k: 'Projecte|Proyecto', t: 'Com es fa un projecte|Cómo se hace un proyecto', anim: 'k4plan',
            x: "Els enginyers no ho programen tot de cop. Primer entenen la missió i miren la pista; després programen <b>una part</b>, la proven, i només llavors n'afegeixen una altra. Quan falla, no ho esborren tot: busquen què ha canviat.|Los ingenieros no lo programan todo de golpe. Primero entienden la misión y miran la pista; después programan <b>una parte</b>, la prueban, y solo entonces añaden otra. Cuando falla, no lo borran todo: buscan qué ha cambiado." }
        ] },
        { k: 'rpredict', ph: 'prova', q: "El robot activa el <b>seguiment de línia</b> del xip i res més. Què passarà quan s'acabi la cinta?|El robot activa el <b>seguimiento de línea</b> del chip y nada más. ¿Qué pasará cuando se acabe la cinta?",
          w: { w: 120, h: 80, bot: [12, 40, 90], lines: [{ p: [[10, 40], [60, 40]] }], marks: { A: [56, 40], B: [80, 22], C: [110, 40] }, time: 22 }, prog: 'start{ patrol:on }', a: 'C',
          ex: "El xip no s'atura sol: sense cinta, continua recte fins a la paret. Per això el programa ha de dir on parar.|El chip no se para solo: sin cinta, sigue recto hasta la pared. Por eso el programa tiene que decir dónde parar." },
        { k: 'quiz', ph: 'prova', q: "Per què, després d'esperar a l'estació, el tren avança mig segon <b>abans</b> de tornar a activar el seguiment?|¿Por qué, después de esperar en la estación, el tren avanza medio segundo <b>antes</b> de volver a activar el seguimiento?",
          opts: ["Per sortir de la ratlla: si no, tornaria a veure 1 1 1 i pararia una altra vegada|Para salir de la raya: si no, volvería a ver 1 1 1 y pararía otra vez", 'Per anar més de pressa|Para ir más deprisa', 'Perquè el xip necessita escalfar-se|Porque el chip necesita calentarse'], a: 0 },
        { k: 'seq', ph: 'mans', q: "Ordena com faràs el projecte del tren, com un/a enginyer/a.|Ordena cómo harás el proyecto del tren, como un/a ingeniero/a.",
          items: ['Entén la missió i mira bé les pistes|Entiende la misión y mira bien las pistas', 'Programa que el tren segueixi la via fins a la terminal|Programa que el tren siga la vía hasta la terminal', 'Prova-ho a totes les pistes|Pruébalo en todas las pistas', 'Afegeix les parades a les estacions i torna a provar|Añade las paradas en las estaciones y vuelve a probar', 'Millora-ho: llums, sons i el teu estil|Mejóralo: luces, sonidos y tu estilo'],
          ex: "A trossos i provant cada part: així, si alguna cosa falla, saps on buscar.|A trozos y probando cada parte: así, si algo falla, sabes dónde buscar." },
        { k: 'move', ph: 'pausa', secs: 30, t: "Feu el tren! Camina com un tren de mercaderies fent «txuc-txuc» amb els braços. Quan diguis «estació!», atura't, fes un xiulet (uuu-uuu!), compta fins a 3 i torna a arrencar.|¡Haced el tren! Camina como un tren de mercancías haciendo «chu-chu» con los brazos. Cuando digas «¡estación!», párate, haz un silbido (¡uuu-uuu!), cuenta hasta 3 y vuelve a arrancar." },
        { k: 'robo', ph: 'repte', q: "<b>Part 1.</b> El tren ha de seguir la via des del moll fins a la <b>terminal blava</b> i aturar-s'hi. Pots fer servir el seguiment del xip o el teu propi seguidor. Les 2 vies són diferents!|<b>Parte 1.</b> El tren tiene que seguir la vía desde el muelle hasta la <b>terminal azul</b> y pararse allí. Puedes usar el seguimiento del chip o tu propio seguidor. ¡Las 2 vías son diferentes!",
          w: { w: 120, h: 80, ...nonote(ROUTE_A), time: 40, alts: [nonote(ROUTE_B)] },
          pal: [...PAL, 'and', 'patrol'], ops: ['L', 'M', 'R', 'aM'], scripts: ['start', 'forever'], sol: PATROL_T,
          hint: "A «en iniciar»: seguiment de línia activat. A «per sempre»: si línia M (ADC) > 200 i < 600 (és el blau), seguiment desactivat i atura el motor (al robot de veritat, així segur que s'atura).|En «al iniciar»: seguimiento de línea activado. En «para siempre»: si línea M (ADC) > 200 y < 600 (es el azul), seguimiento desactivado y para el motor (en el robot de verdad, así seguro que se para)." },
        { k: 'robo', ph: 'repte', q: "<b>Part 2.</b> Ara el tren s'ha d'aturar a cada <b>estació</b> (la ratlla travessera), tocar la nota <b>do′</b> com a xiulet, esperar i continuar fins a la terminal. A la via 2 hi ha <b>dues</b> estacions!|<b>Parte 2.</b> Ahora el tren tiene que pararse en cada <b>estación</b> (la raya transversal), tocar la nota <b>do′</b> como silbido, esperar y seguir hasta la terminal. ¡En la vía 2 hay <b>dos</b> estaciones!",
          w: { w: 120, h: 80, ...ROUTE_A, time: 36, alts: [ROUTE_B] },
          pal: [...PAL, 'and', 'patrol', 'note'], ops: ['L', 'M', 'R', 'aM'], scripts: ['start', 'forever'], prog: PATROL_T, sol: PATROL_ST,
          hint: "Afegeix a «per sempre»: si L = 1 i R = 1 → seguiment desactivat, atura, nota do′, espera 1500, endavant 120, espera 500, seguiment activat.|Añade en «para siempre»: si L = 1 y R = 1 → seguimiento desactivado, para, nota do′, espera 1500, adelante 120, espera 500, seguimiento activado." },
        { k: 'rcreate', ph: 'crea', name: 'El meu tren de mercaderies|Mi tren de mercancías', q: "<b>Part 3: el teu tren!</b> Aquesta via és la més llarga, amb dues estacions. El tren ha de fer tot el recorregut fins a la terminal. A les estacions, <b>para, xiula i encén els llums</b>; a la terminal, mostra una icona a la micro:bit. Afegeix-hi el teu estil!|<b>Parte 3: ¡tu tren!</b> Esta vía es la más larga, con dos estaciones. El tren tiene que hacer todo el recorrido hasta la terminal. En las estaciones, <b>para, silba y enciende las luces</b>; en la terminal, muestra un icono en la micro:bit. ¡Añádele tu estilo!",
          crit: ['Fa tot el recorregut i para a la terminal blava|Hace todo el recorrido y para en la terminal azul', 'A cada estació para, toca una nota i encén els llums|En cada estación para, toca una nota y enciende las luces', 'A la terminal mostra una icona|En la terminal muestra un icono'],
          w: { w: 120, h: 80, bot: [10, 66, 90], lines: [{ p: RC }, ln(36, 58, 74), ln(50, 28, 44)], zones: [TERM([92, 1, 26, 22])], goal: [{ k: 'cps', pts: [[60, 66], [78, 50], [40, 36], [25, 28], [70, 12]], r: 7 }, { k: 'zone', id: 'tz', stop: true }], time: 60 },
          pal: [...PAL, 'and', 'patrol', 'note', 'car', 'under', 'icon'], ops: ['L', 'M', 'R', 'aM'], scripts: ['start', 'forever'],
          sol: 'start{ patrol:on } forever{ if:L=1&&R=1{ patrol:off stop:all car:all,yellow note:C5,1 wait:1500 car:all,black run:all,fwd,120 wait:500 patrol:on } if:aM>200&&aM<600{ patrol:off stop:all car:all,green icon:happy } }',
          check: P => { const ks = []; const w = l => (l || []).forEach(b => { ks.push(b.k); w(b.b); w(b.e); }); Object.values(P).forEach(w); return !ks.includes('note') ? 'El tren ha de xiular a les estacions: afegeix-hi una nota.|El tren tiene que silbar en las estaciones: añade una nota.' : !ks.includes('car') && !ks.includes('under') ? 'Encén els llums a les estacions.|Enciende las luces en las estaciones.' : !ks.includes('icon') ? 'A la terminal, mostra una icona a la micro:bit.|En la terminal, muestra un icono en la micro:bit.' : null; } },
        { k: 'quiz', ph: 'tanca', q: 'Quina és la millor manera de programar un projecte gran?|¿Cuál es la mejor manera de programar un proyecto grande?',
          opts: ['A trossos, provant cada part abans d\'afegir-ne una altra|A trozos, probando cada parte antes de añadir otra', 'Tot de cop i provar-ho al final|Todo de golpe y probarlo al final', "Copiar-lo d'un company/a|Copiarlo de un compañero/a"], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Amb el teu programa, el tren passa per una via amb <b>tres</b> estacions. Quantes vegades xiularà?|Con tu programa, el tren pasa por una vía con <b>tres</b> estaciones. ¿Cuántas veces silbará?',
          opts: ['3, una a cada estació|3, una en cada estación', '1, només a la primera|1, solo en la primera', 'Cap|Ninguna'], a: 0, ex: "El «si L = 1 i R = 1» és dins de «per sempre»: funciona a cada estació que trobi, siguin les que siguin.|El «si L = 1 y R = 1» está dentro de «para siempre»: funciona en cada estación que encuentre, sean las que sean." },
        { k: 'feel', ph: 'tanca' }
      ] }
  ] };
})();
