/* Tech Creadors · unitat 5 «Condicions»: si… toca, si… si no, colors que avisen, «i», «o», «no»; projecte «Atrapa la fruita» */
Object.assign(TBADGE, {
  g_xocs: { id: 'g_xocs', ico: '💥', n: 'Detector/a de xocs|Detector/a de choques', d: 'Has fet que els teus personatges reaccionin quan toquen alguna cosa.|Has hecho que tus personajes reaccionen cuando tocan algo.' },
  g_colors: { id: 'g_colors', ico: '🚦', n: 'Semàfor de colors|Semáforo de colores', d: 'Has fet servir els colors del fons per avisar i has programat decisions amb «si… si no».|Has usado los colores del fondo para avisar y has programado decisiones con «si… si no».' },
  g_logica: { id: 'g_logica', ico: '🧠', n: 'Mestre/a de la lògica|Maestro/a de la lógica', d: 'Has ajuntat i girat condicions amb «i», «o» i «no».|Has juntado y girado condiciones con «y», «o» y «no».' },
  g_fruita: { id: 'g_fruita', ico: '🍎', n: 'Caçador/a de fruita|Cazador/a de fruta', d: 'Projecte acabat: el teu videojoc «Atrapa la fruita», ple de regles amb «si».|Proyecto terminado: tu videojuego «Atrapa la fruta», lleno de reglas con «si».' }
});
COURSE_UNITS[5] = { t: 'Condicions|Condiciones', d: 'Xocs, colors i decisions|Choques, colores y decisiones', color: '#2FA35A', s: [
  /* ---------------------------------------------------------------- Sessió 1 · Si toca… */
  { id: 'g5-1', t: 'Si toca…|Si toca…', min: 45, badge: 'g_xocs',
    learn: ['Una condició és una pregunta que només es respon amb sí o no, com «Toca la cistella?».|Una condición es una pregunta que solo se responde con sí o no, como «¿Toca la cesta?».',
      'El bloc «si» fa els blocs de dins només quan la resposta és sí; si és no, se\'ls salta.|El bloque «si» hace los bloques de dentro solo cuando la respuesta es sí; si es no, se los salta.',
      'Perquè un personatge vigili tota l\'estona, el «si» ha d\'anar dins d\'un «per sempre».|Para que un personaje vigile todo el rato, el «si» tiene que ir dentro de un «por siempre».'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Recordes les coordenades? La poma és a dalt de tot, a <b>y = 150</b>. Quin bloc la fa <b>baixar</b> una mica?|¿Recuerdas las coordenadas? La manzana está arriba del todo, en <b>y = 150</b>. ¿Qué bloque la hace <b>bajar</b> un poco?',
        opts: ['canvia y en -5|cambia y en -5', 'canvia y en 5|cambia y en 5', 'canvia x en -5|cambia x en -5'], a: 0,
        ex: 'Quan la y es fa més petita, el personatge baixa. Avui farem caure moltes fruites!|Cuando la y se hace más pequeña, el personaje baja. ¡Hoy haremos caer muchas frutas!' },
      { k: 'quiz', ph: 'recorda', q: 'Quan es fan els blocs que hi ha sota <b>Quan premo la tecla espai</b>?|¿Cuándo se hacen los bloques que hay debajo de <b>Al pulsar la tecla espacio</b>?',
        opts: ['Només quan algú prem l\'espai|Solo cuando alguien pulsa el espacio', 'Sempre, des del principi|Siempre, desde el principio', 'Quan toques la bandera verda|Cuando tocas la bandera verde'], a: 0,
        ex: 'Exacte: els blocs esperen que passi alguna cosa. Avui aprendràs un bloc que també decideix <b>quan</b> es fan els blocs.|Exacto: los bloques esperan a que pase algo. Hoy aprenderás un bloque que también decide <b>cuándo</b> se hacen los bloques.' },
      { k: 'story', ph: 'missio', who: 'both', scene: 'poble', title: 'La Festa de la Fruita|La Fiesta de la Fruta',
        t: "Al poble de l'illa arriba la <b>Festa de la Fruita</b>! L'alcaldessa ens ha demanat un videojoc per a la fira: <b>Atrapa la fruita</b>. Les pomes i els plàtans cauen dels arbres i una cistella les ha d'atrapar.|¡Al pueblo de la isla llega la <b>Fiesta de la Fruta</b>! La alcaldesa nos ha pedido un videojuego para la feria: <b>Atrapa la fruta</b>. Las manzanas y los plátanos caen de los árboles y una cesta las tiene que atrapar." },
      { k: 'story', ph: 'missio', who: 'bit', scene: 'poble', mood: 'think',
        t: "BIP! Hi ha un problema: com sabrà la cistella que una poma l'ha tocada? Els personatges han de <b>fer preguntes</b>: «Toco la poma?». Avui aprendràs el bloc que pregunta: el bloc <b>si</b>.|¡BIP! Hay un problema: ¿cómo sabrá la cesta que una manzana la ha tocado? Los personajes tienen que <b>hacer preguntas</b>: «¿Toco la manzana?». Hoy aprenderás el bloque que pregunta: el bloque <b>si</b>." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Condició|Condición', t: 'Una pregunta de sí o no|Una pregunta de sí o no', anim: 'g5cond',
          x: "Una <span class='hl'>condició</span> és una pregunta que només es pot respondre <b>sí</b> o <b>no</b>: «Plou?», «Toco la poma?», «Soc a la vora?». Els programes en fan servir per decidir què fan.|Una <span class='hl'>condición</span> es una pregunta que solo se puede responder <b>sí</b> o <b>no</b>: «¿Llueve?», «¿Toco la manzana?», «¿Estoy en el borde?». Los programas las usan para decidir qué hacen.",
          tip: 'Tu també en fas cada dia: «Fa fred? Si la resposta és sí, em poso la jaqueta.»|Tú también las haces cada día: «¿Hace frío? Si la respuesta es sí, me pongo la chaqueta.»' },
        { k: 'El bloc «si»|El bloque «si»', t: 'Si la resposta és sí, fa els blocs de dins|Si la respuesta es sí, hace los bloques de dentro', anim: 'g5if',
          x: "El bloc <b>si …</b> té una condició i un forat. Quan la resposta és <b>sí</b>, fa els blocs que hi ha dins. Quan és <b>no</b>, se'ls salta i continua amb el que ve després.|El bloque <b>si …</b> tiene una condición y un hueco. Cuando la respuesta es <b>sí</b>, hace los bloques que hay dentro. Cuando es <b>no</b>, se los salta y sigue con lo que viene después." },
        { k: 'Toca…|Toca…', t: '«Toca …?»: la pregunta dels xocs|«¿Toca …?»: la pregunta de los choques',
          media: { k: 'stage', w: { bg: 'parc', sprites: [{ id: 'gat', art: 'gat', x: -150, y: -110, dir: 90 }, { id: 'roca', art: 'roca', x: 120, y: -110 }] }, prog: '@gat flag{ forever{ move:4 bounce if:touch:roca{ say:"Ai, una roca!|¡Ay, una roca!",1 turn:180 } } }', time: 7 },
          x: "La condició <b>toca …</b> pregunta si el personatge xoca amb un altre personatge, amb <b>la vora</b> de l'escenari o amb <b>el ratolí</b> (o el dit). El gat de la demo pregunta tota l'estona: «Toco la roca?». Quan la resposta és sí, diu «Ai!» i fa mitja volta.|La condición <b>toca …</b> pregunta si el personaje choca con otro personaje, con <b>el borde</b> del escenario o con <b>el ratón</b> (o el dedo). El gato de la demo pregunta todo el rato: «¿Toco la roca?». Cuando la respuesta es sí, dice «¡Ay!» y da media vuelta." },
        { k: 'Compte!|¡Cuidado!', t: 'Preguntar tota l\'estona|Preguntar todo el rato', anim: 'g5loop',
          x: "Un <b>si</b> només pregunta una vegada: quan li arriba el torn. Si el poses dins d'un <b>per sempre</b>, el personatge torna a preguntar a cada volta del bucle, <b>30 vegades cada segon</b>. Així no se li escapa cap xoc.|Un <b>si</b> solo pregunta una vez: cuando le llega el turno. Si lo pones dentro de un <b>por siempre</b>, el personaje vuelve a preguntar en cada vuelta del bucle, <b>30 veces cada segundo</b>. Así no se le escapa ningún choque.",
          bad: 'Poso el «si» al principi, fora del bucle: ja vigilarà tota l\'estona.|Pongo el «si» al principio, fuera del bucle: ya vigilará todo el rato.', good: 'Poso el «si» dins del «per sempre»: així pregunta a cada volta.|Pongo el «si» dentro del «por siempre»: así pregunta en cada vuelta.' },
        { k: 'Ja el coneixies!|¡Ya lo conocías!', t: '«Si toques la vora…»|«Si tocas el borde…»',
          media: { k: 'stage', w: { bg: 'cel', sprites: [{ id: 'pilota', art: 'pilota', x: -100, y: 20, dir: 90 }] }, prog: '@pilota flag{ forever{ move:7 if:touch:edge{ turn:180 sound:boing } } }', time: 6 },
          x: "El bloc <b>si toques la vora, rebota</b> que ja coneixes té una condició amagada a dins! Ara pots fer la teva: <b>si toca la vora</b>, gira, fa un so… o el que vulguis.|¡El bloque <b>si tocas el borde, rebota</b> que ya conoces tiene una condición escondida dentro! Ahora puedes hacer la tuya: <b>si toca el borde</b>, gira, hace un sonido… o lo que quieras." }
      ] },
      { k: 'seq', ph: 'mans', q: 'La poma cau dins d\'un <b>per sempre</b>. <b>Ordena</b> el que fa a cada volta del bucle.|La manzana cae dentro de un <b>por siempre</b>. <b>Ordena</b> lo que hace en cada vuelta del bucle.',
        items: ['Baixa una mica|Baja un poco', 'Pregunta: «Toco la cistella?»|Pregunta: «¿Toco la cesta?»', "Si la resposta és sí, s'amaga|Si la respuesta es sí, se esconde", 'Torna a començar la volta|Vuelve a empezar la vuelta'],
        ex: 'Baixa, pregunta, decideix… i torna a començar. Tan de pressa que sembla que ho fa tot alhora!|Baja, pregunta, decide… y vuelve a empezar. ¡Tan rápido que parece que lo hace todo a la vez!' },
      { k: 'unplug', ph: 'mans', ico: '🔎', title: 'Caçadors de condicions|Cazadores de condiciones',
        t: 'A casa hi ha moltes màquines que fan preguntes de sí o no. Busca\'n tres amb algú de casa.|En casa hay muchas máquinas que hacen preguntas de sí o no. Busca tres con alguien de casa.',
        steps: ["Obre la nevera: s'encén el llum? La nevera pregunta: «La porta és oberta?»|Abre la nevera: ¿se enciende la luz? La nevera pregunta: «¿La puerta está abierta?»",
          'Busca dues màquines més que decideixin soles: la rentadora, el microones, l\'ascensor, el llum de l\'escala…|Busca dos máquinas más que decidan solas: la lavadora, el microondas, el ascensor, la luz de la escalera…',
          'Escriu cada una com una regla: «<b>Si</b> … , llavors …».|Escribe cada una como una regla: «<b>Si</b> … , entonces …».',
          'Llegiu les regles en veu alta i digueu quina és la pregunta de sí o no.|Leed las reglas en voz alta y decid cuál es la pregunta de sí o no.'],
        tip: 'Exemple: «Si la porta de la nevera és oberta, el llum s\'encén.» La condició és «la porta és oberta?».|Ejemplo: «Si la puerta de la nevera está abierta, la luz se enciende.» La condición es «¿la puerta está abierta?».' },
      { k: 'quiz', ph: 'prova', q: 'Llegeix el programa del cranc. <b>Què creus que farà?</b>|Lee el programa del cangrejo. <b>¿Qué crees que hará?</b>',
        art: () => `<div class="sdcode">${sgDemoChips(SQ('@cranc flag{ forever{ move:3 if:touch:peix{ say:"Hola, peix!|¡Hola, pez!" } } }'), { w: { bg: 'aquari', sprites: [{ id: 'cranc', art: 'cranc', x: -150, y: -130 }, { id: 'peix', art: 'peix', x: 60, y: -120 }] } })}</div>`,
        opts: ['Caminarà i dirà «Hola, peix!» quan toqui el peix|Caminará y dirá «¡Hola, pez!» cuando toque el pez', 'Dirà «Hola, peix!» des del principi|Dirá «¡Hola, pez!» desde el principio', 'No es mourà fins que toqui el peix|No se moverá hasta que toque el pez'], a: 0,
        ex: 'El cranc camina sempre i, a cada volta, pregunta si toca el peix. Només el saluda quan la resposta és sí. Comprova-ho al pas següent!|El cangrejo camina siempre y, en cada vuelta, pregunta si toca el pez. Solo lo saluda cuando la respuesta es sí. ¡Compruébalo en el paso siguiente!' },
      { k: 'sfree', ph: 'prova', q: 'Toca <b>Comença</b> i mira el cranc. Ho havies endevinat?|Toca <b>Empieza</b> y mira el cangrejo. ¿Lo habías adivinado?',
        w: { bg: 'aquari', sprites: [{ id: 'cranc', art: 'cranc', x: -150, y: -130 }, { id: 'peix', art: 'peix', x: 60, y: -120 }], time: 6 },
        prog: '@cranc flag{ forever{ move:3 if:touch:peix{ say:"Hola, peix!|¡Hola, pez!" } } }' },
      { k: 'sspot', ph: 'investiga', q: 'La pilota rebota sola. <b>Toca el bloc que fa la pregunta</b>.|La pelota rebota sola. <b>Toca el bloque que hace la pregunta</b>.',
        w: { bg: 'parc', sprites: [{ id: 'pilota', art: 'pilota', x: -60, y: -100, dir: 90 }], time: 5 },
        prog: '@pilota flag{ forever{ move:6 if:touch:edge!{ turn:180 sound:boing } } }',
        ex: 'El bloc «si toca la vora» pregunta a cada volta. Els blocs de dins (girar i fer el so) només es fan quan la resposta és sí.|El bloque «si toca el borde» pregunta en cada vuelta. Los bloques de dentro (girar y hacer el sonido) solo se hacen cuando la respuesta es sí.' },
      { k: 'move', ph: 'pausa', secs: 30, t: 'Fes de bloc «si»! Quan algú digui <b>«poma»</b>, ajup-te. Quan digui <b>«plàtan»</b>, fes un salt. I si diu una altra fruita… queda\'t quiet/a!|¡Haz de bloque «si»! Cuando alguien diga <b>«manzana»</b>, agáchate. Cuando diga <b>«plátano»</b>, da un salto. Y si dice otra fruta… ¡quédate quieto/a!' },
      { k: 'stage', ph: 'repte', q: "La poma ja cau. Fes que <b>s'amagui quan toqui la cistella</b>: l'has atrapada! Compte: a la prova 2 la cistella és en un altre lloc.|La manzana ya cae. Haz que <b>se esconda cuando toque la cesta</b>: ¡la has atrapado! Cuidado: en la prueba 2 la cesta está en otro sitio.",
        w: { bg: 'bosc', sprites: [{ id: 'poma', art: 'poma', x: -60, y: 150 }, { id: 'cistella', art: 'cistella', x: -60, y: -120 }], time: 4, goal: [{ k: 'hidden', s: 'poma' }],
          alts: [{ sprites: [{ id: 'poma', art: 'poma', x: 80, y: 150 }, { id: 'cistella', art: 'cistella', x: -110, y: -120 }], goal: [{ k: 'shown', s: 'poma' }, { k: 'dy', s: 'poma', min: -250 }] }] },
        edit: ['poma'], hats: ['flag'], pal: ['chy', 'forever', 'if', 'hide', 'sound'], prog: '@poma flag{ forever{ chy:-5 } }',
        sol: '@poma flag{ forever{ chy:-5 if:touch:cistella{ hide } } }',
        hint: "Toca el forat de dins del «per sempre», posa-hi un bloc «si» (ja pregunta «toca la cistella?») i, a dins del «si», posa «amaga't».|Toca el hueco de dentro del «por siempre», pon un bloque «si» (ya pregunta «¿toca la cesta?») y, dentro del «si», pon «escóndete»." },
      { k: 'stage', ph: 'repte', q: "L'ocell vola cap a la dreta i s'escapa de l'escenari. Fes que, <b>si toca la vora, giri 180 graus</b>. Així anirà d'una banda a l'altra sense sortir mai.|El pájaro vuela hacia la derecha y se escapa del escenario. Haz que, <b>si toca el borde, gire 180 grados</b>. Así irá de un lado al otro sin salir nunca.",
        w: { bg: 'cel', sprites: [{ id: 'ocell', art: 'ocell', x: -100, y: 40, dir: 90 }], time: 5, goal: [{ k: 'reach', s: 'ocell', r: [160, -180, 240, 180] }, { k: 'reach', s: 'ocell', r: [-240, -180, -160, 180] }, { k: 'at', s: 'ocell', r: [-240, -180, 240, 180] }],
          alts: [{ sprites: [{ id: 'ocell', art: 'ocell', x: 60, y: -60, dir: 90 }] }] },
        edit: ['ocell'], hats: ['flag'], pal: ['move', 'turn', 'forever', 'if'],
        sol: '@ocell flag{ forever{ move:6 if:touch:edge{ turn:180 } } }',
        hint: 'Dins del «per sempre»: primer «mou-te», després «si toca la vora» amb «gira 180 graus» a dins.|Dentro del «por siempre»: primero «muévete», después «si toca el borde» con «gira 180 grados» dentro.' },
      { k: 'stage', ph: 'repte', q: "Ara la poma té <b>dues preguntes</b>: si toca la cistella, s'amaga; i si toca la vora de baix, <b>torna a dalt</b> (posa y a 150) per tornar a caure.|Ahora la manzana tiene <b>dos preguntas</b>: si toca la cesta, se esconde; y si toca el borde de abajo, <b>vuelve arriba</b> (pon y a 150) para volver a caer.",
        w: { bg: 'bosc', sprites: [{ id: 'poma', art: 'poma', x: 100, y: 150 }, { id: 'cistella', art: 'cistella', x: 100, y: -120 }], time: 5, goal: [{ k: 'hidden', s: 'poma' }],
          alts: [{ sprites: [{ id: 'poma', art: 'poma', x: -120, y: 150 }, { id: 'cistella', art: 'cistella', x: 90, y: -120 }], goal: [{ k: 'shown', s: 'poma' }, { k: 'at', s: 'poma', r: [-240, -180, 240, 180] }, { k: 'moved', s: 'poma', min: 500 }] }] },
        edit: ['poma'], hats: ['flag'], pal: ['chy', 'sety', 'forever', 'if', 'hide', 'sound'], prog: '@poma flag{ forever{ chy:-5 } }',
        sol: '@poma flag{ forever{ chy:-5 if:touch:cistella{ hide } if:touch:edge{ sety:150 } } }',
        hint: 'Calen dos blocs «si» dins del «per sempre». Al segon, toca «la cistella» i tria «la vora». A dins, «posa y a 150».|Hacen falta dos bloques «si» dentro del «por siempre». En el segundo, toca «la cesta» y elige «el borde». Dentro, «pon y a 150».' },
      { k: 'stage', ph: 'repte', q: "Ui! Aquest programa té un error: la poma <b>no s'amaga mai</b>, encara que toqui la cistella. Per què? <b>Arregla'l.</b>|¡Uy! Este programa tiene un error: la manzana <b>no se esconde nunca</b>, aunque toque la cesta. ¿Por qué? <b>Arréglalo.</b>",
        w: { bg: 'bosc', sprites: [{ id: 'poma', art: 'poma', x: 130, y: 150 }, { id: 'cistella', art: 'cistella', x: 130, y: -120 }], time: 4, goal: [{ k: 'hidden', s: 'poma' }],
          alts: [{ sprites: [{ id: 'poma', art: 'poma', x: -140, y: 150 }, { id: 'cistella', art: 'cistella', x: 20, y: -120 }], goal: [{ k: 'shown', s: 'poma' }, { k: 'dy', s: 'poma', min: -250 }] }] },
        edit: ['poma'], hats: ['flag'], pal: ['chy', 'forever', 'if', 'hide'], prog: '@poma flag{ if:touch:cistella{ hide } forever{ chy:-5 } }',
        sol: '@poma flag{ forever{ chy:-5 if:touch:cistella{ hide } } }',
        hint: "El «si» és fora del bucle: només pregunta una vegada, al principi, quan la poma encara és a dalt. Esborra'l i torna'l a posar dins del «per sempre».|El «si» está fuera del bucle: solo pregunta una vez, al principio, cuando la manzana aún está arriba. Bórralo y vuelve a ponerlo dentro del «por siempre»." },
      { k: 'screate', ph: 'crea', name: 'La meva primera condició|Mi primera condición',
        q: "Ara inventes tu! En Numi passeja pel parc fins al regal. Quan el toqui, ha de <b>reaccionar com tu vulguis</b>: dir alguna cosa, fer un so, posar-se content, fer-se gran…|¡Ahora inventas tú! Numi pasea por el parque hasta el regalo. Cuando lo toque, tiene que <b>reaccionar como tú quieras</b>: decir algo, hacer un sonido, ponerse contento, hacerse grande…",
        crit: ['En Numi es mou dins d\'un «per sempre»|Numi se mueve dentro de un «por siempre»', 'Fa servir «si toca el regal» dins del bucle|Usa «si toca el regalo» dentro del bucle', 'Quan toca el regal, diu alguna cosa i fa una altra reacció|Cuando toca el regalo, dice algo y hace otra reacción'],
        w: { bg: 'parc', sprites: [{ id: 'numi', art: 'numi', x: -170, y: -90, dir: 90, size: 80 }, { id: 'regal', art: 'regal', x: 110, y: -100 }], time: 6, goal: [{ k: 'touched', a: 'numi', b: 'regal' }, { k: 'said', s: 'numi' }] },
        edit: ['numi'], hats: ['flag'], pal: ['move', 'turn', 'bounce', 'forever', 'if', 'say', 'costume', 'next', 'size', 'chsize', 'sound', 'wait'],
        texts: ['Un regal!|¡Un regalo!', 'Què hi deu haver?|¿Qué habrá dentro?', 'Gràcies!|¡Gracias!'],
        sol: '@numi flag{ forever{ move:3 bounce if:touch:regal{ say:"Un regal!|¡Un regalo!",1 costume:2 sound:victoria } } }',
        check: P => { const f = (l, loop) => (l || []).some(b => (b.k === 'if' && loop && JSON.stringify(b.c || {}).includes('"touch"') && (b.b || []).length) || f(b.b, loop || b.k === 'forever') || f(b.e, loop)); return Object.values(P.numi || {}).some(sc => sc.some(l => f(l, false))) ? null : 'Falta un «si toca…» amb blocs a dins, posat dins del «per sempre».|Falta un «si toca…» con bloques dentro, puesto dentro del «por siempre».'; } },
      { k: 'quiz', ph: 'tanca', q: 'Per acabar: què és una <b>condició</b>?|Para terminar: ¿qué es una <b>condición</b>?',
        opts: ['Una pregunta que es respon amb sí o no|Una pregunta que se responde con sí o no', 'Un bloc que mou el personatge|Un bloque que mueve el personaje', 'Un fons de l\'escenari|Un fondo del escenario'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: 'On has de posar el <b>si toca…</b> perquè el personatge vigili tota l\'estona?|¿Dónde tienes que poner el <b>si toca…</b> para que el personaje vigile todo el rato?',
        opts: ['Dins del «per sempre»|Dentro del «por siempre»', 'Abans del «per sempre»|Antes del «por siempre»', 'En un altre personatge|En otro personaje'], a: 0,
        ex: 'Dins del bucle, la pregunta es repeteix a cada volta.|Dentro del bucle, la pregunta se repite en cada vuelta.' },
      { k: 'feel', ph: 'tanca' }
    ] },
  /* ---------------------------------------------------------------- Sessió 2 · Colors que avisen */
  { id: 'g5-2', t: 'Colors que avisen|Colores que avisan', min: 45, badge: 'g_colors',
    learn: ['La condició «toca el color» pregunta si el personatge trepitja un color del fons, com el blau del mar.|La condición «toca el color» pregunta si el personaje pisa un color del fondo, como el azul del mar.',
      'El bloc «si… si no» té dues parts: una per quan la resposta és sí i una altra per quan és no.|El bloque «si… si no» tiene dos partes: una para cuando la respuesta es sí y otra para cuando es no.',
      'Cada vegada, el «si… si no» fa una de les dues parts, mai les dues alhora.|Cada vez, el «si… si no» hace una de las dos partes, nunca las dos a la vez.'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'On has de posar el <b>si toca…</b> perquè el personatge vigili tota l\'estona?|¿Dónde tienes que poner el <b>si toca…</b> para que el personaje vigile todo el rato?',
        opts: ['Dins del «per sempre»|Dentro del «por siempre»', 'Abans del «per sempre»|Antes del «por siempre»', 'Al final de tot|Al final de todo'], a: 0,
        ex: 'Dins del bucle, el personatge torna a preguntar a cada volta.|Dentro del bucle, el personaje vuelve a preguntar en cada vuelta.' },
      { k: 'quiz', ph: 'recorda', q: 'Al laberint de l\'última unitat, què volia dir el color <b>blau</b>?|En el laberinto de la última unidad, ¿qué quería decir el color <b>azul</b>?',
        opts: ['Les parets|Las paredes', 'La sortida|La salida', 'El camí lliure|El camino libre'], a: 0,
        ex: 'Els colors del fons poden donar informació. Avui en farem servir molts!|Los colores del fondo pueden dar información. ¡Hoy usaremos muchos!' },
      { k: 'story', ph: 'missio', who: 'both', scene: 'moll', title: 'Ningú no vol mullar-se|Nadie quiere mojarse',
        t: "La Festa de la Fruita continua a la platja! En Pinces, el cranc, porta cocos a la fira, però <b>no sap nedar</b>. Necessita que el fons l'avisi: el blau del mar vol dir «compte!».|¡La Fiesta de la Fruta continúa en la playa! Pinzas, el cangrejo, lleva cocos a la feria, pero <b>no sabe nadar</b>. Necesita que el fondo le avise: el azul del mar quiere decir «¡cuidado!»." },
      { k: 'story', ph: 'missio', who: 'bit', scene: 'moll', mood: 'happy',
        t: "BIP! Els colors avisen, com al semàfor: vermell vol dir «para» i verd, «passa». Avui els personatges miraran de quin color és el que trepitgen… i aprendràs a dir què han de fer <b>si no</b>.|¡BIP! Los colores avisan, como en el semáforo: rojo quiere decir «para» y verde, «pasa». Hoy los personajes mirarán de qué color es lo que pisan… y aprenderás a decir qué tienen que hacer <b>si no</b>." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Toca el color|Toca el color', t: '«Toca el color …?»|«¿Toca el color …?»', anim: 'g5color',
          x: "La condició <b>toca el color</b> pregunta si el personatge trepitja una zona d'un color del fons: el <b>blau</b> del mar, el <b>groc</b> de la sorra, el <b>verd</b> de l'herba… Així el fons pot avisar.|La condición <b>toca el color</b> pregunta si el personaje pisa una zona de un color del fondo: el <b>azul</b> del mar, el <b>amarillo</b> de la arena, el <b>verde</b> de la hierba… Así el fondo puede avisar.",
          tip: 'A molts videojocs, el vermell vol dir perill i el verd, sortida o meta.|En muchos videojuegos, el rojo quiere decir peligro y el verde, salida o meta.' },
        { k: 'Demo|Demo', t: 'En Pinces no es mulla|Pinzas no se moja',
          media: { k: 'stage', w: { bg: 'platja', sprites: [{ id: 'cranc', art: 'cranc', x: -60, y: -150 }] }, prog: '@cranc flag{ forever{ chy:2 if:color:blue{ think:"Aigua!|¡Agua!",1 sety:-150 } } }', time: 7 },
          x: 'El cranc puja per la sorra. A cada volta pregunta: «Toco el blau?». Quan la resposta és sí, pensa «Aigua!» i torna a baix.|El cangrejo sube por la arena. En cada vuelta pregunta: «¿Toco el azul?». Cuando la respuesta es sí, piensa «¡Agua!» y vuelve abajo.' },
        { k: 'Si… si no|Si… si no', t: 'Dues respostes, dos camins|Dos respuestas, dos caminos', anim: 'g5else',
          x: "El bloc <b>si … si no</b> té dos forats: el de dalt es fa quan la resposta és <b>sí</b> i el de baix (<b>si no</b>) quan és <b>no</b>. Cada vegada en fa <b>un dels dos</b>, mai tots dos. Per afegir-lo, toca un bloc «si» i després <b>Afegeix «si no»</b>.|El bloque <b>si … si no</b> tiene dos huecos: el de arriba se hace cuando la respuesta es <b>sí</b> y el de abajo (<b>si no</b>) cuando es <b>no</b>. Cada vez hace <b>uno de los dos</b>, nunca los dos. Para añadirlo, toca un bloque «si» y después <b>Añade «si no»</b>.",
          bad: 'Per fer una cosa quan toca i una altra quan no toca, necessito dos «si».|Para hacer una cosa cuando toca y otra cuando no toca, necesito dos «si».', good: 'Amb un sol «si… si no» n\'hi ha prou: dalt el sí, baix el no.|Con un solo «si… si no» basta: arriba el sí, abajo el no.' },
        { k: 'Demo|Demo', t: 'Caure o caminar|Caer o caminar',
          media: { k: 'stage', w: { bg: 'bosc', sprites: [{ id: 'numi', art: 'numi', x: -170, y: 130, dir: 90, size: 80 }] }, prog: '@numi flag{ forever{ if:color:green{ move:3 } else{ chy:-5 } } }', time: 6 },
          x: 'En Numi pregunta: «Toco el verd de l\'herba?». <b>Si no</b>, cau. Quan arriba a l\'herba, la resposta és sí i camina. Una sola pregunta, dues respostes.|Numi pregunta: «¿Toco el verde de la hierba?». <b>Si no</b>, cae. Cuando llega a la hierba, la respuesta es sí y camina. Una sola pregunta, dos respuestas.' },
        { k: 'Laberint|Laberinto', t: 'Cada color, una regla|Cada color, una regla',
          media: { k: 'stage', w: { bg: 'laberint', sprites: [{ id: 'estel', art: 'estel', x: -175, y: 100, size: 60 }] }, prog: '@estel flag{ glide:1,-175,-80 glide:0.8,-75,-80 glide:1,-75,80 glide:0.8,25,80 glide:1,25,-80 glide:0.8,125,-80 } flag{ forever{ if:color:green{ say:"He sortit!|¡He salido!" stop:all } } }', time: 7 },
          x: 'Al laberint, cada color té el seu significat: el <b>blau</b> són parets, el <b>vermell</b> és una trampa i el <b>verd</b> és la sortida. Un «si» per a cada color, i el personatge sap què ha de fer.|En el laberinto, cada color tiene su significado: el <b>azul</b> son paredes, el <b>rojo</b> es una trampa y el <b>verde</b> es la salida. Un «si» para cada color, y el personaje sabe qué tiene que hacer.' }
      ] },
      { k: 'quiz', ph: 'mans', q: 'Regla del semàfor: «<b>Si</b> el llum és verd, passo; <b>si no</b>, m\'espero.» Ara el llum és <b>vermell</b>. Què faig?|Regla del semáforo: «<b>Si</b> la luz es verde, paso; <b>si no</b>, espero.» Ahora la luz es <b>roja</b>. ¿Qué hago?',
        opts: ["M'espero|Espero", 'Passo|Paso', 'Passo i m\'espero alhora|Paso y espero a la vez'], a: 0,
        ex: 'El llum no és verd, així que es fa la part del «si no»: esperar. Mai es fan les dues parts.|La luz no es verde, así que se hace la parte del «si no»: esperar. Nunca se hacen las dos partes.' },
      { k: 'unplug', ph: 'mans', ico: '🚦', title: 'El semàfor de casa|El semáforo de casa',
        t: 'Necessites algú de casa i dos papers: un de <b>verd</b> i un de <b>vermell</b>.|Necesitas a alguien de casa y dos papeles: uno <b>verde</b> y uno <b>rojo</b>.',
        steps: ["Una persona fa de semàfor i aixeca un paper. L'altra segueix la regla: <b>si</b> és verd, camina a poc a poc; <b>si no</b>, s'atura com una estàtua.|Una persona hace de semáforo y levanta un papel. La otra sigue la regla: <b>si</b> es verde, camina despacio; <b>si no</b>, se para como una estatua.",
          'Feu-ho deu vegades, cada cop més de pressa.|Hacedlo diez veces, cada vez más deprisa.',
          'Canvieu els papers.|Cambiad los papeles.',
          'Inventeu una regla nova amb un tercer color: per exemple, groc vol dir «camina de puntetes».|Inventad una regla nueva con un tercer color: por ejemplo, amarillo quiere decir «camina de puntillas».'],
        tip: 'Fixeu-vos que amb dos colors n\'hi ha prou amb un «si… si no». Amb tres, cal una pregunta més!|Fijaos en que con dos colores basta con un «si… si no». ¡Con tres, hace falta una pregunta más!' },
      { k: 'quiz', ph: 'prova', q: 'En Pinces és a la sorra (groc). Llegeix el programa: <b>què fa ara?</b>|Pinzas está en la arena (amarillo). Lee el programa: <b>¿qué hace ahora?</b>',
        art: () => `<div class="sdcode">${sgDemoChips(SQ('@cranc flag{ forever{ if:color:yellow{ move:3 bounce } else{ think:"Aigua!|¡Agua!" } } }'), { w: { bg: 'platja', sprites: [{ id: 'cranc', art: 'cranc', x: 0, y: -140 }] } })}</div>`,
        opts: ['Camina, perquè toca el groc|Camina, porque toca el amarillo', 'Pensa «Aigua!»|Piensa «¡Agua!»', 'Camina i pensa «Aigua!» alhora|Camina y piensa «¡Agua!» a la vez'], a: 0,
        ex: 'La resposta a «toca el groc?» és sí: es fa la part de dalt. La part del «si no» espera el seu torn.|La respuesta a «¿toca el amarillo?» es sí: se hace la parte de arriba. La parte del «si no» espera su turno.' },
      { k: 'sspot', ph: 'investiga', q: 'Toca el bloc que es fa quan el cranc <b>NO</b> toca el blau.|Toca el bloque que se hace cuando el cangrejo <b>NO</b> toca el azul.',
        w: { bg: 'platja', sprites: [{ id: 'cranc', art: 'cranc', x: -60, y: -150 }], time: 6 },
        prog: '@cranc flag{ forever{ if:color:blue{ think:"Aigua!|¡Agua!",1 sety:-150 } else{ chy:3! } } }',
        ex: 'El bloc de la part «si no» (canvia y en 3) es fa quan la resposta és no: mentre no toca el mar, el cranc puja.|El bloque de la parte «si no» (cambia y en 3) se hace cuando la respuesta es no: mientras no toca el mar, el cangrejo sube.' },
      { k: 'move', ph: 'pausa', secs: 30, t: 'Semàfor humà! Quan algú digui <b>«verd»</b>, camina sense moure\'t del lloc; <b>«vermell»</b>, queda\'t quiet/a com una estàtua; <b>«blau»</b>, fes veure que neds!|¡Semáforo humano! Cuando alguien diga <b>«verde»</b>, camina sin moverte del sitio; <b>«rojo»</b>, quédate quieto/a como una estatua; <b>«azul»</b>, ¡haz ver que nadas!' },
      { k: 'stage', ph: 'repte', q: "En Pinces puja cap al mar. Ja té la pregunta «<b>si toca el color blau</b>». Posa-hi a dins el que ha de fer: <b>tornar a la sorra</b> (posa y a -150).|Pinzas sube hacia el mar. Ya tiene la pregunta «<b>si toca el color azul</b>». Pon dentro lo que tiene que hacer: <b>volver a la arena</b> (pon y a -150).",
        w: { bg: 'platja', sprites: [{ id: 'cranc', art: 'cranc', x: -120, y: -150 }], time: 4, goal: [{ k: 'moved', s: 'cranc', min: 200 }, { k: 'at', s: 'cranc', r: [-240, -180, 240, -70] }],
          alts: [{ sprites: [{ id: 'cranc', art: 'cranc', x: 110, y: -120 }] }] },
        edit: ['cranc'], hats: ['flag'], pal: ['chy', 'sety', 'think', 'forever', 'if', 'cond+'], prog: '@cranc flag{ forever{ chy:3 if:color:blue{ } } }', texts: ['Aigua!|¡Agua!'],
        sol: '@cranc flag{ forever{ chy:3 if:color:blue{ sety:-150 } } }',
        hint: 'Toca el forat de dins del «si toca el color blau» i afegeix «posa y a», amb el número -150.|Toca el hueco de dentro del «si toca el color azul» y añade «pon y a», con el número -150.' },
      { k: 'stage', ph: 'repte', q: "En Numi cau del cel. Fes que <b>si toca el verd, camini</b> (mou-te 3 passos) i, <b>si no, caigui</b> (canvia y en -5). Toca el bloc «si» i després <b>Afegeix «si no»</b>.|Numi cae del cielo. Haz que <b>si toca el verde, camine</b> (muévete 3 pasos) y, <b>si no, caiga</b> (cambia y en -5). Toca el bloque «si» y después <b>Añade «si no»</b>.",
        w: { bg: 'bosc', sprites: [{ id: 'numi', art: 'numi', x: -180, y: 120, dir: 90, size: 80 }], time: 5, goal: [{ k: 'reach', s: 'numi', r: [100, -110, 240, -40] }, { k: 'at', s: 'numi', r: [-240, -110, 260, -40] }],
          alts: [{ sprites: [{ id: 'numi', art: 'numi', x: -150, y: 40, dir: 90, size: 80 }] }] },
        edit: ['numi'], hats: ['flag'], pal: ['move', 'chy', 'forever', 'if', 'else', 'cond+'], prog: '@numi flag{ forever{ if:color:green{ } } }',
        sol: '@numi flag{ forever{ if:color:green{ move:3 } else{ chy:-5 } } }',
        hint: "A dalt del «si» va «mou-te 3 passos». Després toca el «si», tria «Afegeix «si no»» i, a la part de baix, posa «canvia y en -5».|Arriba del «si» va «muévete 3 pasos». Después toca el «si», elige «Añade «si no»» y, en la parte de abajo, pon «cambia y en -5»." },
      { k: 'stage', ph: 'repte', q: "Ui! En Numi camina pel cel i s'enfonsa a l'herba. <b>Les dues respostes estan canviades.</b> Arregla-ho perquè caigui fins a l'herba i després camini.|¡Uy! Numi camina por el cielo y se hunde en la hierba. <b>Las dos respuestas están cambiadas.</b> Arréglalo para que caiga hasta la hierba y después camine.",
        w: { bg: 'bosc', sprites: [{ id: 'numi', art: 'numi', x: -120, y: 80, dir: 90, size: 80 }], time: 5, goal: [{ k: 'reach', s: 'numi', r: [100, -110, 240, -40] }, { k: 'at', s: 'numi', r: [-240, -110, 260, -40] }],
          alts: [{ sprites: [{ id: 'numi', art: 'numi', x: -200, y: 0, dir: 90, size: 80 }] }] },
        edit: ['numi'], hats: ['flag'], pal: ['move', 'chy', 'forever', 'if', 'else', 'cond+'], prog: '@numi flag{ forever{ if:color:green{ chy:-5 } else{ move:3 } } }',
        sol: '@numi flag{ forever{ if:color:green{ move:3 } else{ chy:-5 } } }',
        hint: "Quan toca el verd (part de dalt) ha de caminar; quan no el toca (part «si no») ha de caure. Esborra els dos blocs i torna'ls a posar al seu lloc.|Cuando toca el verde (parte de arriba) tiene que caminar; cuando no lo toca (parte «si no») tiene que caer. Borra los dos bloques y vuelve a ponerlos en su sitio." },
      { k: 'stage', ph: 'repte', q: "El laberint! L'Estel es mou amb les fletxes. Completa les regles dels colors: <b>si toca el blau</b> (paret), torna a l'inici (ves a x: -175, y: 100); <b>si toca el verd</b>, diu «He sortit!» i atura-ho tot. Prova-ho amb <b>Comença</b> i les fletxes, i després toca <b>Comprova</b>.|¡El laberinto! Estel se mueve con las flechas. Completa las reglas de los colores: <b>si toca el azul</b> (pared), vuelve al inicio (ve a x: -175, y: 100); <b>si toca el verde</b>, dice «¡He salido!» y lo para todo. Pruébalo con <b>Empieza</b> y las flechas, y después toca <b>Comprueba</b>.",
        w: { bg: 'laberint', keys: ['left', 'right', 'up', 'down'], time: 1.6,
          sprites: [{ id: 'estel', art: 'estel', x: -175, y: 100, size: 60, prog: '@estel key:right{ chx:20 } key:left{ chx:-20 } key:up{ chy:20 } key:down{ chy:-20 }' }],
          input: [...'DDDRRR'].map((c, i) => ({ t: +(.3 + i * .16).toFixed(2), key: { R: 'right', L: 'left', U: 'up', D: 'down' }[c], dur: .07 })),
          goal: [{ k: 'at', s: 'estel', r: [-190, 85, -145, 115] }, { k: 'running', t: 1.4 }],
          alts: [{ time: 7, input: [...'DDDDDDDDDRRRRRUUUUUUUURRRRRDDDDDDDDRRRRR'].map((c, i) => ({ t: +(.3 + i * .16).toFixed(2), key: { R: 'right', L: 'left', U: 'up', D: 'down' }[c], dur: .07 })),
            goal: [{ k: 'at', s: 'estel', r: [100, -140, 210, -60] }, { k: 'said', s: 'estel', t: 'He sortit' }, { k: 'stopped' }] }] },
        edit: ['estel'], hats: ['flag'], pal: ['goto', 'say', 'stop', 'forever', 'if', 'cond+'], texts: ['He sortit!|¡He salido!'],
        prog: '@estel flag{ forever{ if:color:blue{ } if:color:green{ } } }',
        sol: '@estel flag{ forever{ if:color:blue{ goto:-175,100 } if:color:green{ say:"He sortit!|¡He salido!" stop:all } } }',
        hint: 'Dins del primer «si» posa «ves a x: -175 y: 100». Dins del segon, «digues He sortit!» i «atura tot».|Dentro del primer «si» pon «ve a x: -175 y: 100». Dentro del segundo, «di ¡He salido!» y «para todo».' },
      { k: 'screate', ph: 'crea', name: 'El meu avís de colors|Mi aviso de colores',
        q: "La Tuga passeja per la platja amb les fletxes. Inventa què fa <b>si toca el blau</b> del mar i què fa <b>si no</b>: pot dir coses, canviar de vestit, fer sons… Prova-ho amb les fletxes i, quan t'agradi, toca <b>Comprova</b>.|Tuga pasea por la playa con las flechas. Inventa qué hace <b>si toca el azul</b> del mar y qué hace <b>si no</b>: puede decir cosas, cambiar de disfraz, hacer sonidos… Pruébalo con las flechas y, cuando te guste, toca <b>Comprueba</b>.",
        crit: ['Fa servir «si toca el color… si no…»|Usa «si toca el color… si no…»', 'Fa una cosa diferent a cada part|Hace una cosa diferente en cada parte', 'La Tuga diu alguna cosa|Tuga dice algo'],
        w: { bg: 'platja', keys: ['left', 'right', 'up', 'down'], time: 3,
          sprites: [{ id: 'tuga', art: 'tuga', x: 0, y: -140, size: 90, prog: '@tuga key:right{ chx:10 } key:left{ chx:-10 } key:up{ chy:10 } key:down{ chy:-10 }' }],
          input: Array.from({ length: 8 }, (_, i) => ({ t: +(.3 + i * .2).toFixed(2), key: 'up', dur: .07 })),
          goal: [{ k: 'said', s: 'tuga' }, { k: 'dy', s: 'tuga', min: 40 }] },
        edit: ['tuga'], hats: ['flag'], pal: ['say', 'think', 'costume', 'next', 'size', 'sound', 'wait', 'forever', 'if', 'else', 'cond+'],
        texts: ['Glub, glub!|¡Glub, glub!', 'Quina calor!|¡Qué calor!', "L'aigua és fresca!|¡El agua está fresca!"],
        prog: '@tuga flag{ forever{ if:color:blue{ } else{ } } }',
        sol: '@tuga flag{ forever{ if:color:blue{ say:"Glub, glub!|¡Glub, glub!" costume:2 } else{ say:"Quina calor!|¡Qué calor!" costume:1 } } }',
        check: P => { const f = l => (l || []).some(b => (b.k === 'if' && JSON.stringify(b.c || {}).includes('"color"') && (b.b || []).length && (b.e || []).length) || f(b.b) || f(b.e)); return Object.values(P.tuga || {}).some(sc => sc.some(f)) ? null : 'Posa algun bloc a les dues parts del «si toca el color… si no».|Pon algún bloque en las dos partes del «si toca el color… si no».'; } },
      { k: 'quiz', ph: 'tanca', q: 'Cada vegada que pregunta, quantes parts fa un <b>si… si no</b>?|Cada vez que pregunta, ¿cuántas partes hace un <b>si… si no</b>?',
        opts: ['Una de les dues|Una de las dos', 'Totes dues|Las dos', 'Cap|Ninguna'], a: 0,
        ex: 'Si la resposta és sí, la de dalt; si és no, la de baix.|Si la respuesta es sí, la de arriba; si es no, la de abajo.' },
      { k: 'quiz', ph: 'tanca', q: 'Al laberint, quina regla fa que funcioni la <b>sortida verda</b>?|En el laberinto, ¿qué regla hace que funcione la <b>salida verde</b>?',
        opts: ['Si toca el verd, digues «He sortit!» i atura-ho tot|Si toca el verde, di «¡He salido!» y páralo todo', 'Si toca el blau, ves a l\'inici|Si toca el azul, ve al inicio', 'Digues «He sortit!» al principi|Di «¡He salido!» al principio'], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] },
  /* ---------------------------------------------------------------- Sessió 3 · I, o, no */
  { id: 'g5-3', t: 'I, o, no|Y, o, no', min: 45, badge: 'g_logica',
    learn: ['Amb «i», la resposta és sí només si les dues preguntes són sí.|Con «y», la respuesta es sí solo si las dos preguntas son sí.',
      'Amb «o», n\'hi ha prou que una de les dues preguntes sigui sí.|Con «o», basta con que una de las dos preguntas sea sí.',
      '«No» gira la resposta: el sí es torna no i el no es torna sí.|«No» gira la respuesta: el sí se vuelve no y el no se vuelve sí.'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: '«<b>Si</b> toca el verd, camina; <b>si no</b>, cau.» En Numi és a l\'aire, lluny de l\'herba. Què fa?|«<b>Si</b> toca el verde, camina; <b>si no</b>, cae.» Numi está en el aire, lejos de la hierba. ¿Qué hace?',
        opts: ['Cau|Cae', 'Camina|Camina', 'Camina i cau alhora|Camina y cae a la vez'], a: 0,
        ex: 'No toca el verd: es fa la part del «si no».|No toca el verde: se hace la parte del «si no».' },
      { k: 'quiz', ph: 'recorda', q: 'Quina condició fa servir en Pinces, el cranc, per saber que ha arribat al mar?|¿Qué condición usa Pinzas, el cangrejo, para saber que ha llegado al mar?',
        opts: ['Toca el color blau|Toca el color azul', 'Toca la vora|Toca el borde', 'Toca el ratolí|Toca el ratón'], a: 0 },
      { k: 'story', ph: 'missio', who: 'both', scene: 'lab', title: 'Regles més llestes|Reglas más listas',
        t: "Al laboratori preparem les sorpreses del videojoc. Hi ha un regal que <b>només s'obre si hi arriben en Numi i en Bit alhora</b>, i un gat que ha de girar si troba una roca <b>o</b> la vora.|En el laboratorio preparamos las sorpresas del videojuego. Hay un regalo que <b>solo se abre si llegan Numi y Bit a la vez</b>, y un gato que tiene que girar si encuentra una roca <b>o</b> el borde." },
      { k: 'story', ph: 'missio', who: 'bit', scene: 'lab', mood: 'happy',
        t: 'BIP! Per a regles així necessitem tres paraules màgiques: <b>i</b>, <b>o</b> i <b>no</b>. Les dues primeres ajunten preguntes. La tercera, les gira del revés!|¡BIP! Para reglas así necesitamos tres palabras mágicas: <b>y</b>, <b>o</b> y <b>no</b>. Las dos primeras juntan preguntas. ¡La tercera las gira del revés!' },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'i|y', t: 'Amb «i», calen les dues|Con «y», hacen falta las dos', anim: 'g5andor',
          x: "Amb <b>i</b> ajuntes dues preguntes, i la resposta és sí <b>només si totes dues són sí</b>. «Si toca en Numi <b>i</b> toca en Bit» vol dir que hi han de ser els dos. Amb <b>o</b>, en canvi, n'hi ha prou amb un.|Con <b>y</b> juntas dos preguntas, y la respuesta es sí <b>solo si las dos son sí</b>. «Si toca a Numi <b>y</b> toca a Bit» quiere decir que tienen que estar los dos. Con <b>o</b>, en cambio, basta con uno.",
          tip: 'Per afegir «i / o», toca el bloc «si» i després <b>Afegeix «i / o»</b>. Tocant la paraula del mig, tries «i» o «o».|Para añadir «y / o», toca el bloque «si» y después <b>Añade «y / o»</b>. Tocando la palabra del medio, eliges «y» u «o».' },
        { k: 'Demo|Demo', t: 'El regal dels dos amics|El regalo de los dos amigos',
          media: { k: 'stage', w: { bg: 'parc', sprites: [{ id: 'regal', art: 'regal', x: 0, y: -60 }, { id: 'numi', art: 'numi', x: -190, y: -60, size: 80 }, { id: 'bit', art: 'bit', x: 190, y: -60, size: 80, dir: -90 }] },
            prog: '@numi flag{ glide:1.5,-32,-60 } @bit flag{ wait:1 glide:1.5,32,-60 } @regal flag{ forever{ if:touch:numi&&touch:bit{ sound:victoria hide } } }', time: 4 },
          x: "Quan arriba en Numi, el regal encara no s'obre: falta en Bit. Quan hi són <b>tots dos</b>, la resposta és sí i el regal s'obre.|Cuando llega Numi, el regalo todavía no se abre: falta Bit. Cuando están <b>los dos</b>, la respuesta es sí y el regalo se abre." },
        { k: 'o|o', t: 'Amb «o», n\'hi ha prou amb una|Con «o», basta con una',
          media: { k: 'stage', w: { bg: 'parc', sprites: [{ id: 'gat', art: 'gat', x: -150, y: -110, dir: 90 }, { id: 'roca', art: 'roca', x: 90, y: -110 }] }, prog: '@gat flag{ forever{ move:5 if:touch:roca||touch:edge{ turn:180 } } }', time: 7 },
          x: "El gat gira <b>si toca la roca o la vora</b>. Quan toca la roca, gira. Quan toca la vora, també. Amb un sol «si» vigila les dues coses.|El gato gira <b>si toca la roca o el borde</b>. Cuando toca la roca, gira. Cuando toca el borde, también. Con un solo «si» vigila las dos cosas.",
          bad: '«o» vol dir que han de passar les dues coses alhora.|«o» quiere decir que tienen que pasar las dos cosas a la vez.', good: 'Amb «o» n\'hi ha prou amb una; amb «i» calen les dues.|Con «o» basta con una; con «y» hacen falta las dos.' },
        { k: 'no|no', t: '«No» gira la resposta|«No» gira la respuesta', anim: 'g5not',
          x: "<b>No</b> gira la resposta del revés: el sí es torna no i el no es torna sí. «Si <b>no</b> toca la roca, camina» vol dir: camina mentre la roca és lluny i para quan la toca.|<b>No</b> gira la respuesta del revés: el sí se vuelve no y el no se vuelve sí. «Si <b>no</b> toca la roca, camina» quiere decir: camina mientras la roca está lejos y para cuando la toca.",
          tip: 'Al repte d\'en Bit, el «no» ja ve posat davant de la condició: llegeix-la en veu alta, «si <b>no</b> toca la roca».|En el reto de Bit, el «no» ya viene puesto delante de la condición: léela en voz alta, «si <b>no</b> toca la roca».' },
        { k: 'Demo|Demo', t: 'En Bit para a temps|Bit para a tiempo',
          media: { k: 'stage', w: { bg: 'parc', sprites: [{ id: 'bit', art: 'bit', x: -180, y: -100, size: 90 }, { id: 'roca', art: 'roca', x: 80, y: -110 }] }, prog: '@bit flag{ forever{ if:!touch:roca{ move:3 } else{ say:"Una roca!|¡Una roca!" } } }', time: 6 },
          x: "Mentre la resposta a «toca la roca?» és no, el «no» la gira en sí i en Bit camina. Quan toca la roca, s'atura i ho diu.|Mientras la respuesta a «¿toca la roca?» es no, el «no» la gira en sí y Bit camina. Cuando toca la roca, se para y lo dice." }
      ] },
      { k: 'quiz', ph: 'mans', q: 'Regla de la fira: «Pots entrar a la pista de ball si portes entrada <b>i</b> barret.» La Guida porta entrada però <b>no</b> porta barret. Pot entrar?|Regla de la feria: «Puedes entrar en la pista de baile si llevas entrada <b>y</b> sombrero.» Guida lleva entrada pero <b>no</b> lleva sombrero. ¿Puede entrar?',
        opts: ['No: amb «i» calen les dues coses|No: con «y» hacen falta las dos cosas', 'Sí: ja porta entrada|Sí: ya lleva entrada', 'Només mitja estona|Solo un rato'], a: 0 },
      { k: 'quiz', ph: 'mans', q: 'Ara la regla canvia: «Pots entrar si portes entrada <b>o</b> barret.» La Guida porta entrada però no barret. Pot entrar?|Ahora la regla cambia: «Puedes entrar si llevas entrada <b>o</b> sombrero.» Guida lleva entrada pero no sombrero. ¿Puede entrar?',
        opts: ['Sí: amb «o» n\'hi ha prou amb una|Sí: con «o» basta con una', 'No: li falta el barret|No: le falta el sombrero', 'No: amb «o» calen les dues|No: con «o» hacen falta las dos'], a: 0,
        ex: 'Una sola paraula canvia tota la regla. Per això cal triar bé entre «i» i «o».|Una sola palabra cambia toda la regla. Por eso hay que elegir bien entre «y» y «o».' },
      { k: 'unplug', ph: 'mans', ico: '🕵️', title: 'Endevina la meva regla|Adivina mi regla',
        t: 'Amb algú de casa i uns quants objectes: peluixos, fruita, roba, llapis…|Con alguien de casa y unos cuantos objetos: peluches, fruta, ropa, lápices…',
        steps: ['Una persona pensa una regla secreta amb «i» o «o». Per exemple: «M\'agrada si és vermell <b>o</b> és rodó.»|Una persona piensa una regla secreta con «y» u «o». Por ejemplo: «Me gusta si es rojo <b>o</b> es redondo.»',
          "L'altra ensenya objectes un a un i la primera només respon «sí» o «no».|La otra enseña objetos uno a uno y la primera solo responde «sí» o «no».",
          'Quan creguis que la saps, digues la regla. És «i» o és «o»?|Cuando creas que la sabes, di la regla. ¿Es «y» o es «o»?',
          'Canvieu els papers i proveu una regla amb «no»: «M\'agrada si <b>no</b> és de plàstic.»|Cambiad los papeles y probad una regla con «no»: «Me gusta si <b>no</b> es de plástico.»'] },
      { k: 'sspot', ph: 'investiga', q: 'La papallona hauria de girar quan toca la vora <b>o</b> la roca, però travessa la roca. <b>Toca el bloc que s\'equivoca.</b>|La mariposa debería girar cuando toca el borde <b>o</b> la roca, pero atraviesa la roca. <b>Toca el bloque que se equivoca.</b>',
        w: { bg: 'cel', sprites: [{ id: 'papallona', art: 'papallona', x: -120, y: 20, dir: 90 }, { id: 'roca', art: 'roca', x: 110, y: 20 }], time: 6 },
        prog: '@papallona flag{ forever{ move:4 next if:touch:edge&&touch:roca!{ turn:180 } } }',
        ex: 'El «si» diu <b>i</b>: només gira si toca la vora i la roca alhora, cosa que gairebé mai no passa. Hauria de dir <b>o</b>.|El «si» dice <b>y</b>: solo gira si toca el borde y la roca a la vez, algo que casi nunca pasa. Debería decir <b>o</b>.' },
      { k: 'quiz', ph: 'prova', q: 'Llegeix el programa d\'en Bit. <b>Què farà?</b>|Lee el programa de Bit. <b>¿Qué hará?</b>',
        art: () => `<div class="sdcode">${sgDemoChips(SQ('@bit flag{ forever{ if:!touch:roca{ move:3 } } }'), { w: { bg: 'parc', sprites: [{ id: 'bit', art: 'bit', x: -180, y: -100 }, { id: 'roca', art: 'roca', x: 80, y: -110 }] } })}</div>`,
        opts: ['Caminarà fins que toqui la roca i s\'aturarà|Caminará hasta que toque la roca y se parará', 'No es mourà mai|No se moverá nunca', 'Travessarà la roca|Atravesará la roca'], a: 0,
        ex: 'Mentre no toca la roca, el «no» fa que la resposta sigui sí i camina. Quan la toca, la resposta és no i s\'atura.|Mientras no toca la roca, el «no» hace que la respuesta sea sí y camina. Cuando la toca, la respuesta es no y se para.' },
      { k: 'move', ph: 'pausa', secs: 30, t: 'Portes lògiques! Aixeca\'t si portes alguna cosa blava <b>i</b> t\'agrada la fruita. Ara, si portes alguna cosa blava <b>o</b> t\'agrada la fruita. I ara… si <b>no</b> portes res blau!|¡Puertas lógicas! Levántate si llevas algo azul <b>y</b> te gusta la fruta. Ahora, si llevas algo azul <b>o</b> te gusta la fruta. Y ahora… ¡si <b>no</b> llevas nada azul!' },
      { k: 'stage', ph: 'repte', q: "El gat passeja pel parc. Fes que <b>giri 180 graus si toca la roca o la vora</b>. Darrere la roca dorm una papallona: no la despertis! Només pots fer servir 4 blocs.|El gato pasea por el parque. Haz que <b>gire 180 grados si toca la roca o el borde</b>. Detrás de la roca duerme una mariposa: ¡no la despiertes! Solo puedes usar 4 bloques.",
        w: { bg: 'parc', sprites: [{ id: 'gat', art: 'gat', x: -150, y: -110, dir: 90 }, { id: 'roca', art: 'roca', x: 90, y: -110 }, { id: 'papallona', art: 'papallona', x: 165, y: -100, size: 80 }], time: 6,
          goal: [{ k: 'notouch', a: 'gat', b: 'papallona' }, { k: 'reach', s: 'gat', r: [-240, -180, -170, 180] }, { k: 'at', s: 'gat', r: [-240, -180, 240, 180] }, { k: 'moved', s: 'gat', min: 500 }],
          alts: [{ sprites: [{ id: 'gat', art: 'gat', x: -150, y: -110, dir: 90 }, { id: 'roca', art: 'roca', x: -10, y: -110 }, { id: 'papallona', art: 'papallona', x: 65, y: -100, size: 80 }] }] },
        edit: ['gat'], hats: ['flag'], pal: ['move', 'turn', 'forever', 'if', 'and'], max: 4,
        sol: '@gat flag{ forever{ move:5 if:touch:roca||touch:edge{ turn:180 } } }',
        hint: "Posa un «si» dins del «per sempre», toca'l i tria «Afegeix «i / o»». Després toca la paraula «i» i canvia-la per «o».|Pon un «si» dentro del «por siempre», tócalo y elige «Añade «y / o»». Después toca la palabra «y» y cámbiala por «o»." },
      { k: 'stage', ph: 'repte', q: "Programa el regal: s'ha d'amagar (obrir-se) <b>només si toca en Numi i toca en Bit</b>. A les proves 2 i 3, només n'hi arriba un: llavors no s'ha d'obrir!|Programa el regalo: se tiene que esconder (abrirse) <b>solo si toca a Numi y toca a Bit</b>. En las pruebas 2 y 3, solo llega uno: ¡entonces no se tiene que abrir!",
        w: { bg: 'parc', time: 3,
          sprites: [{ id: 'regal', art: 'regal', x: 0, y: -60 }, { id: 'numi', art: 'numi', x: -190, y: -60, size: 80, prog: '@numi flag{ glide:1.5,-32,-60 }' }, { id: 'bit', art: 'bit', x: 190, y: -60, size: 80, dir: -90, prog: '@bit flag{ glide:1.5,32,-60 }' }],
          goal: [{ k: 'hidden', s: 'regal' }],
          alts: [{ sprites: [{ id: 'regal', art: 'regal', x: 0, y: -60 }, { id: 'numi', art: 'numi', x: -190, y: -60, size: 80, prog: '@numi flag{ glide:1.5,-32,-60 }' }, { id: 'bit', art: 'bit', x: 190, y: -60, size: 80, dir: -90, prog: '@bit flag{ glide:1.5,120,-60 }' }], goal: [{ k: 'shown', s: 'regal' }] },
            { sprites: [{ id: 'regal', art: 'regal', x: 0, y: -60 }, { id: 'numi', art: 'numi', x: -190, y: -60, size: 80, prog: '@numi flag{ glide:1.5,-120,-60 }' }, { id: 'bit', art: 'bit', x: 190, y: -60, size: 80, dir: -90, prog: '@bit flag{ glide:1.5,32,-60 }' }], goal: [{ k: 'shown', s: 'regal' }] }] },
        edit: ['regal'], hats: ['flag'], pal: ['hide', 'sound', 'forever', 'if', 'and'],
        sol: '@regal flag{ forever{ if:touch:numi&&touch:bit{ sound:victoria hide } } }',
        hint: "El «si» ja pregunta «toca en Numi». Toca'l, tria «Afegeix «i / o»» i canvia «la vora» per «Bit». A dins, «amaga't».|El «si» ya pregunta «toca a Numi». Tócalo, elige «Añade «y / o»» y cambia «el borde» por «Bit». Dentro, «escóndete»." },
      { k: 'stage', ph: 'repte', q: "En Bit té la pregunta «<b>si no toca la roca</b>». Completa-la: si no toca la roca, <b>camina</b> (mou-te 3 passos); si no (quan la toca), <b>diu «Una roca!»</b>.|Bit tiene la pregunta «<b>si no toca la roca</b>». Complétala: si no toca la roca, <b>camina</b> (muévete 3 pasos); si no (cuando la toca), <b>dice «¡Una roca!»</b>.",
        w: { bg: 'parc', time: 5, sprites: [{ id: 'bit', art: 'bit', x: -180, y: -100, size: 90 }, { id: 'roca', art: 'roca', x: 60, y: -110 }],
          goal: [{ k: 'at', s: 'bit', r: [-20, -180, 30, 180] }, { k: 'said', s: 'bit' }],
          alts: [{ sprites: [{ id: 'bit', art: 'bit', x: -180, y: -100, size: 90 }, { id: 'roca', art: 'roca', x: -30, y: -110 }], goal: [{ k: 'at', s: 'bit', r: [-110, -180, -60, 180] }, { k: 'said', s: 'bit' }] }] },
        edit: ['bit'], hats: ['flag'], pal: ['move', 'say', 'forever', 'if', 'else'], texts: ['Una roca!|¡Una roca!'],
        prog: '@bit flag{ forever{ if:!touch:roca{ } else{ } } }',
        sol: '@bit flag{ forever{ if:!touch:roca{ move:3 } else{ say:"Una roca!|¡Una roca!" } } }',
        hint: 'A la part de dalt (no toca la roca) posa «mou-te 3 passos». A la part «si no», «digues Una roca!».|En la parte de arriba (no toca la roca) pon «muévete 3 pasos». En la parte «si no», «di ¡Una roca!».' },
      { k: 'screate', ph: 'crea', name: 'La regla del tresor|La regla del tesoro',
        q: "En Numi busca tresors pel parc. Inventa una regla amb <b>i</b> o amb <b>o</b>: per exemple, «si toca l'estrella o el cor, digues «Tresor!» i fes un so». Tu decideixes com es mou i què fa!|Numi busca tesoros por el parque. Inventa una regla con <b>y</b> o con <b>o</b>: por ejemplo, «si toca la estrella o el corazón, di «¡Tesoro!» y haz un sonido». ¡Tú decides cómo se mueve y qué hace!",
        crit: ['En Numi es mou pel parc|Numi se mueve por el parque', 'Fa servir una condició amb «i» o amb «o»|Usa una condición con «y» o con «o»', 'Quan troba un tresor, diu alguna cosa|Cuando encuentra un tesoro, dice algo'],
        w: { bg: 'parc', time: 6, sprites: [{ id: 'numi', art: 'numi', x: -180, y: -100, dir: 90, size: 80 }, { id: 'estrella', art: 'estrella', x: 40, y: -100 }, { id: 'cor', art: 'cor', x: 140, y: 60 }, { id: 'roca', art: 'roca', x: -60, y: 60 }],
          goal: [{ k: 'said', s: 'numi' }] },
        edit: ['numi'], hats: ['flag'], pal: ['move', 'turn', 'bounce', 'say', 'costume', 'next', 'chsize', 'sound', 'wait', 'forever', 'if', 'else', 'and', 'cond+'],
        texts: ['Tresor!|¡Tesoro!', 'Una roca!|¡Una roca!', 'Què bonic!|¡Qué bonito!'],
        sol: '@numi flag{ forever{ move:3 bounce if:touch:estrella||touch:cor{ say:"Tresor!|¡Tesoro!",1 sound:moneda } } }',
        check: P => { const f = l => (l || []).some(b => (b.c && (b.c.and || b.c.or)) || f(b.b) || f(b.e)); return Object.values(P.numi || {}).some(sc => sc.some(f)) ? null : 'Falta una condició amb «i» o amb «o». Toca el bloc «si» i tria «Afegeix «i / o»».|Falta una condición con «y» o con «o». Toca el bloque «si» y elige «Añade «y / o»».'; } },
      { k: 'quiz', ph: 'tanca', q: '«Si toca la roca <b>o</b> la vora, gira.» El gat toca la vora, però no la roca. Gira?|«Si toca la roca <b>o</b> el borde, gira.» El gato toca el borde, pero no la roca. ¿Gira?',
        opts: ['Sí|Sí', 'No|No', 'Només si també toca la roca|Solo si también toca la roca'], a: 0,
        ex: 'Amb «o», n\'hi ha prou que una de les dues sigui sí.|Con «o», basta con que una de las dos sea sí.' },
      { k: 'quiz', ph: 'tanca', q: 'Què fa el <b>no</b> en una condició?|¿Qué hace el <b>no</b> en una condición?',
        opts: ['Gira la resposta: el sí es torna no i el no, sí|Gira la respuesta: el sí se vuelve no y el no, sí', 'Atura el programa|Para el programa', 'Esborra el bloc «si»|Borra el bloque «si»'], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] },
  /* ---------------------------------------------------------------- Sessió 4 · Projecte: atrapa la fruita */
  { id: 'g5-4', t: 'Projecte: atrapa la fruita|Proyecto: atrapa la fruta', min: 45, proj: true, badge: 'g_fruita',
    learn: ['Abans de programar un videojoc, fem el pla: qui hi ha, com es mou cadascú i quines regles té.|Antes de programar un videojuego, hacemos el plan: quién hay, cómo se mueve cada uno y qué reglas tiene.',
      'Cada regla del videojoc és un «si»: si la fruita toca la cistella, si toca la vora, si la roca toca la cistella…|Cada regla del videojuego es un «si»: si la fruta toca la cesta, si toca el borde, si la roca toca la cesta…',
      'Un videojoc es construeix a trossos: es prova cada tros, es busquen els errors i es millora.|Un videojuego se construye a trozos: se prueba cada trozo, se buscan los errores y se mejora.'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'El regal s\'obre «si toca en Numi <b>i</b> toca en Bit». Només hi ha arribat en Numi. S\'obre?|El regalo se abre «si toca a Numi <b>y</b> toca a Bit». Solo ha llegado Numi. ¿Se abre?',
        opts: ['No, calen els dos|No, hacen falta los dos', 'Sí, n\'hi ha prou amb un|Sí, basta con uno', 'Només una mica|Solo un poco'], a: 0 },
      { k: 'quiz', ph: 'recorda', q: '«Si <b>no</b> toca la roca, camina.» Què fa en Bit quan toca la roca?|«Si <b>no</b> toca la roca, camina.» ¿Qué hace Bit cuando toca la roca?',
        opts: ["S'atura|Se para", 'Continua caminant|Sigue caminando', 'Salta la roca|Salta la roca'], a: 0 },
      { k: 'story', ph: 'missio', who: 'both', scene: 'poble', title: 'El gran dia|El gran día',
        t: "Avui és el gran dia: la fira de la Festa de la Fruita obre les portes! Muntarem el videojoc <b>Atrapa la fruita</b> peça a peça: la cistella, les fruites que cauen i… una roca que ho pot espatllar tot!|¡Hoy es el gran día: la feria de la Fiesta de la Fruta abre sus puertas! Montaremos el videojuego <b>Atrapa la fruta</b> pieza a pieza: la cesta, las frutas que caen y… ¡una roca que lo puede estropear todo!" },
      { k: 'story', ph: 'missio', who: 'bit', scene: 'poble', mood: 'think',
        t: 'BIP! Un bon videojoc té <b>regles clares</b>. I ja saps una cosa: cada regla és un <b>si</b>. Si la poma toca la cistella… Si toca la vora de baix… Si la roca toca la cistella…|¡BIP! Un buen videojuego tiene <b>reglas claras</b>. Y ya sabes una cosa: cada regla es un <b>si</b>. Si la manzana toca la cesta… Si toca el borde de abajo… Si la roca toca la cesta…' },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'El pla|El plan', t: 'Primer, el pla en paper|Primero, el plan en papel', anim: 'g5plan',
          x: 'Abans de programar, fes el <b>pla</b>: quins personatges hi ha, com es mou cadascú i quines <b>regles</b> té. Cada regla és un «si». Amb el pla fet, programar és molt més fàcil.|Antes de programar, haz el <b>plan</b>: qué personajes hay, cómo se mueve cada uno y qué <b>reglas</b> tiene. Cada regla es un «si». Con el plan hecho, programar es mucho más fácil.' },
        { k: 'Guions|Guiones', t: 'Cada personatge, els seus guions|Cada personaje, sus guiones',
          media: { k: 'stage', w: { bg: 'bosc', sprites: [{ id: 'cistella', art: 'cistella', x: -120, y: -130 }, { id: 'poma', art: 'poma', x: -120, y: 150 }, { id: 'platan', art: 'platan', x: 100, y: 150 }] },
            prog: '@cistella flag{ forever{ glide:1.2,-120,-130 wait:0.4 glide:1.2,100,-130 wait:0.4 } } @poma flag{ forever{ chy:-4 if:touch:cistella{ sound:pop sety:150 } if:touch:edge{ sety:150 } } } @platan flag{ forever{ chy:-3 if:touch:cistella{ sound:moneda sety:150 } if:touch:edge{ sety:150 } } }', time: 8 },
          x: 'La cistella té els guions per moure\'s. Cada fruita té el seu: cau i pregunta tota l\'estona «toco la cistella?» i «toco la vora?». Tots els guions funcionen alhora.|La cesta tiene los guiones para moverse. Cada fruta tiene el suyo: cae y pregunta todo el rato «¿toco la cesta?» y «¿toco el borde?». Todos los guiones funcionan a la vez.' },
        { k: 'Fi|Fin', t: 'Una regla que ho acaba tot|Una regla que lo acaba todo',
          media: { k: 'stage', w: { bg: 'bosc', sprites: [{ id: 'cistella', art: 'cistella', x: 40, y: -130 }, { id: 'roca', art: 'roca', x: 40, y: 150, size: 80 }] },
            prog: '@roca flag{ forever{ chy:-4 if:touch:cistella{ say:"Pam! S\'ha acabat!|¡Pam! ¡Se acabó!" stop:all } if:touch:edge{ sety:150 } } }', time: 5 },
          x: 'Una regla pot acabar el videojoc: <b>si la roca toca la cistella</b>, diu «Pam!» i <b>atura-ho tot</b>. Així qui el prova ha d\'anar amb compte!|Una regla puede acabar el videojuego: <b>si la roca toca la cesta</b>, dice «¡Pam!» y <b>lo para todo</b>. Así quien lo prueba ¡tiene que ir con cuidado!',
          tip: 'Prova cada tros abans de passar al següent: és molt més fàcil trobar els errors.|Prueba cada trozo antes de pasar al siguiente: es mucho más fácil encontrar los errores.',
          bad: 'Ho programo tot de cop i ho provo al final.|Lo programo todo de golpe y lo pruebo al final.', good: 'Programo un tros, el provo, l\'arreglo i després en faig un altre.|Programo un trozo, lo pruebo, lo arreglo y después hago otro.' }
      ] },
      { k: 'sfree', ph: 'prova', q: 'Així serà el videojoc acabat. Toca <b>Comença</b> i mou la cistella amb les fletxes (o els botons ← →). Quantes fruites atrapes?|Así será el videojuego terminado. Toca <b>Empieza</b> y mueve la cesta con las flechas (o los botones ← →). ¿Cuántas frutas atrapas?',
        w: { bg: 'bosc', keys: ['left', 'right'], time: 30, sprites: [{ id: 'cistella', art: 'cistella', x: 0, y: -130 }, { id: 'poma', art: 'poma', x: -120, y: 150 }, { id: 'platan', art: 'platan', x: 100, y: 150 }, { id: 'roca', art: 'roca', x: 0, y: 170, size: 70 }] },
        prog: '@cistella key:right{ chx:20 if:touch:edge{ chx:-20 } } key:left{ chx:-20 if:touch:edge{ chx:20 } } @poma flag{ forever{ chy:-4 if:touch:cistella{ sound:pop sety:150 } if:touch:edge{ sety:150 } } } @platan flag{ forever{ chy:-5 if:touch:cistella{ sound:moneda sety:150 } if:touch:edge{ sety:150 } } } @roca flag{ wait:3 forever{ chy:-3 if:touch:cistella{ say:"Pam! S\'ha acabat!|¡Pam! ¡Se acabó!" stop:all } if:touch:edge{ sety:170 } } }' },
      { k: 'seq', ph: 'mans', q: '<b>Ordena el pla</b> per construir el videojoc a trossos.|<b>Ordena el plan</b> para construir el videojuego a trozos.',
        items: ['Fer que la cistella es mogui amb les fletxes|Hacer que la cesta se mueva con las flechas', 'Fer caure la poma|Hacer caer la manzana', 'Afegir la regla «si toca la cistella…»|Añadir la regla «si toca la cesta…»', 'Afegir la regla «si toca la vora…»|Añadir la regla «si toca el borde…»', 'Provar-ho i millorar-ho|Probarlo y mejorarlo'],
        ex: 'Primer el que es mou, després les regles i, al final, provar i millorar.|Primero lo que se mueve, después las reglas y, al final, probar y mejorar.' },
      { k: 'unplug', ph: 'mans', ico: '👨‍👩‍👧', title: 'El tester de casa|El tester de casa',
        t: 'Quan acabis el projecte, ensenya\'l a algú de casa. Ell o ella serà el teu <b>tester</b>: la persona que prova un videojoc per trobar-hi errors i idees.|Cuando acabes el proyecto, enséñalo a alguien de casa. Él o ella será tu <b>tester</b>: la persona que prueba un videojuego para encontrarle errores e ideas.',
        steps: ['Explica-li les regles sense tocar res: què es mou, què cau i què passa si…|Explícale las reglas sin tocar nada: qué se mueve, qué cae y qué pasa si…',
          "Deixa'l provar sense ajudar-lo. Mira on s'encalla.|Déjale probar sin ayudarle. Mira dónde se atasca.",
          'Pregunta-li: què t\'ha agradat? Què canviaries?|Pregúntale: ¿qué te ha gustado? ¿Qué cambiarías?',
          "Apunta una millora i, el pròxim dia, programa-la.|Apunta una mejora y, el próximo día, prográmala."] },
      { k: 'sspot', ph: 'investiga', q: 'Aquest videojoc té un error: la poma cau, però <b>no torna mai a dalt</b>. Toca el bloc que falla.|Este videojuego tiene un error: la manzana cae, pero <b>no vuelve nunca arriba</b>. Toca el bloque que falla.',
        w: { bg: 'bosc', sprites: [{ id: 'poma', art: 'poma', x: -60, y: 150 }, { id: 'cistella', art: 'cistella', x: 100, y: -130 }], time: 5 },
        prog: '@poma flag{ forever{ chy:-4 if:touch:cistella{ sound:pop sety:150 } if:touch:edge{ sety:-150! } } }',
        ex: 'Quan toca la vora de baix, la poma va a y = -150, que també és a baix. Ha d\'anar a y = 150, a dalt de tot.|Cuando toca el borde de abajo, la manzana va a y = -150, que también está abajo. Tiene que ir a y = 150, arriba del todo.' },
      { k: 'move', ph: 'pausa', secs: 30, t: 'Fes de cistella! Algú llança fruites imaginàries a la dreta o a l\'esquerra: mou-te d\'una banda a l\'altra i atrapa-les. Compte amb les roques: si diuen «roca», ajup-te!|¡Haz de cesta! Alguien lanza frutas imaginarias a la derecha o a la izquierda: muévete de un lado al otro y atrápalas. Cuidado con las rocas: si dicen «roca», ¡agáchate!' },
      { k: 'stage', ph: 'repte', q: "Tros 1: la cistella. Fes que es mogui amb les fletxes (canvia x en 20 o en -20) i que, <b>si toca la vora, torni enrere</b> perquè no s'escapi. Prova-ho amb les fletxes i toca <b>Comprova</b>.|Trozo 1: la cesta. Haz que se mueva con las flechas (cambia x en 20 o en -20) y que, <b>si toca el borde, vuelva atrás</b> para que no se escape. Pruébalo con las flechas y toca <b>Comprueba</b>.",
        w: { bg: 'bosc', keys: ['left', 'right'], time: 3,
          sprites: [{ id: 'cistella', art: 'cistella', x: 0, y: -130 }, { id: 'papallona', art: 'papallona', x: -170, y: 110, size: 70, prog: '@papallona flag{ forever{ next wait:0.3 } }' }],
          input: Array.from({ length: 16 }, (_, i) => ({ t: +(.3 + i * .15).toFixed(2), key: 'right', dur: .07 })),
          goal: [{ k: 'dx', s: 'cistella', min: 150 }, { k: 'at', s: 'cistella', r: [-240, -180, 240, 0] }, { k: 'running', t: 2.9 }],
          alts: [{ input: Array.from({ length: 16 }, (_, i) => ({ t: +(.3 + i * .15).toFixed(2), key: 'left', dur: .07 })), goal: [{ k: 'dx', s: 'cistella', min: -150 }, { k: 'at', s: 'cistella', r: [-240, -180, 240, 0] }, { k: 'running', t: 2.9 }] }] },
        edit: ['cistella'], hats: ['key:left', 'key:right'], pal: ['chx', 'if'],
        sol: '@cistella key:right{ chx:20 if:touch:edge{ chx:-20 } } key:left{ chx:-20 if:touch:edge{ chx:20 } }',
        hint: 'A «Quan premo la fletxa dreta»: «canvia x en 20» i, després, «si toca la vora» amb «canvia x en -20» a dins. A l\'esquerra, al revés.|En «Al pulsar la flecha derecha»: «cambia x en 20» y, después, «si toca el borde» con «cambia x en -20» dentro. En la izquierda, al revés.' },
      { k: 'stage', ph: 'repte', q: "Tros 2: la poma. Ha de caure i tenir dues regles: <b>si toca la cistella</b>, fa el so pop i va a x: 100, y: 150 (la pròxima cau per un altre lloc); <b>si toca la vora</b>, torna a dalt (posa y a 150).|Trozo 2: la manzana. Tiene que caer y tener dos reglas: <b>si toca la cesta</b>, hace el sonido pop y va a x: 100, y: 150 (la próxima cae por otro sitio); <b>si toca el borde</b>, vuelve arriba (pon y a 150).",
        w: { bg: 'bosc', time: 5, sprites: [{ id: 'poma', art: 'poma', x: -100, y: 150 }, { id: 'cistella', art: 'cistella', x: -100, y: -130 }],
          goal: [{ k: 'sound', n: 'pop' }, { k: 'at', s: 'poma', r: [80, -180, 120, 180] }],
          alts: [{ sprites: [{ id: 'poma', art: 'poma', x: -100, y: 150 }, { id: 'cistella', art: 'cistella', x: 120, y: -130 }], goal: [{ k: 'at', s: 'poma', r: [-120, -180, -80, 180] }, { k: 'moved', s: 'poma', min: 400 }, { k: 'running', t: 4.8 }] }] },
        edit: ['poma'], hats: ['flag'], pal: ['chy', 'goto', 'sety', 'sound', 'forever', 'if'], prog: '@poma flag{ forever{ chy:-4 } }',
        sol: '@poma flag{ forever{ chy:-4 if:touch:cistella{ sound:pop goto:100,150 } if:touch:edge{ sety:150 } } }',
        hint: 'Dins del «per sempre», després de «canvia y en -4», posa dos «si»: «si toca la cistella» (so pop i «ves a x: 100 y: 150») i «si toca la vora» («posa y a 150»).|Dentro del «por siempre», después de «cambia y en -4», pon dos «si»: «si toca la cesta» (sonido pop y «ve a x: 100 y: 150») y «si toca el borde» («pon y a 150»).' },
      { k: 'stage', ph: 'repte', q: "Tros 3: la roca! Cau com la poma, però <b>si toca la cistella</b>, diu «Pam! S'ha acabat!» i <b>atura-ho tot</b>. I si toca la vora, torna a dalt (posa y a 150).|Trozo 3: ¡la roca! Cae como la manzana, pero <b>si toca la cesta</b>, dice «¡Pam! ¡Se acabó!» y <b>lo para todo</b>. Y si toca el borde, vuelve arriba (pon y a 150).",
        w: { bg: 'bosc', time: 4, sprites: [{ id: 'roca', art: 'roca', x: 40, y: 150, size: 80 }, { id: 'cistella', art: 'cistella', x: 40, y: -130 }],
          goal: [{ k: 'stopped' }, { k: 'said', s: 'roca' }],
          alts: [{ sprites: [{ id: 'roca', art: 'roca', x: 40, y: 150, size: 80 }, { id: 'cistella', art: 'cistella', x: -150, y: -130 }], goal: [{ k: 'running', t: 3.8 }, { k: 'moved', s: 'roca', min: 350 }, { k: 'at', s: 'roca', r: [-240, -180, 240, 180] }] }] },
        edit: ['roca'], hats: ['flag'], pal: ['chy', 'sety', 'say', 'stop', 'forever', 'if'], texts: ["Pam! S'ha acabat!|¡Pam! ¡Se acabó!"], prog: '@roca flag{ forever{ chy:-5 } }',
        sol: '@roca flag{ forever{ chy:-5 if:touch:cistella{ say:"Pam! S\'ha acabat!|¡Pam! ¡Se acabó!" stop:all } if:touch:edge{ sety:150 } } }',
        hint: 'Com la poma: dos «si». Al de la cistella, «digues…» i «atura tot». Al de la vora, «posa y a 150».|Como la manzana: dos «si». En el de la cesta, «di…» y «para todo». En el del borde, «pon y a 150».' },
      { k: 'screate', ph: 'crea', name: 'Atrapa la fruita|Atrapa la fruta',
        q: "Ara, el videojoc sencer! La cistella ja es mou amb les fletxes i la poma ja cau. Afegeix les <b>regles de la poma</b> i programa el <b>plàtan</b>. Després millora'l com vulguis: sons, frases, velocitats… Prova'l amb les fletxes i, quan estigui a punt, toca <b>Comprova</b>.|¡Ahora, el videojuego entero! La cesta ya se mueve con las flechas y la manzana ya cae. Añade las <b>reglas de la manzana</b> y programa el <b>plátano</b>. Después mejóralo como quieras: sonidos, frases, velocidades… Pruébalo con las flechas y, cuando esté listo, toca <b>Comprueba</b>.",
        crit: ['La poma i el plàtan cauen i tornen a dalt si toquen la vora|La manzana y el plátano caen y vuelven arriba si tocan el borde', 'Si una fruita toca la cistella, passa alguna cosa (so, frase…)|Si una fruta toca la cesta, pasa algo (sonido, frase…)', 'Has afegit una millora teva|Has añadido una mejora tuya'],
        w: { bg: 'bosc', keys: ['left', 'right'], time: 7,
          sprites: [{ id: 'cistella', art: 'cistella', x: 0, y: -130 }, { id: 'poma', art: 'poma', x: -120, y: 150 }, { id: 'platan', art: 'platan', x: 100, y: 150 }, { id: 'papallona', art: 'papallona', x: -200, y: 120, size: 70, prog: '@papallona flag{ forever{ next wait:0.3 } }' }],
          input: [...Array.from({ length: 6 }, (_, i) => ({ t: +(.3 + i * .15).toFixed(2), key: 'left', dur: .07 })), ...Array.from({ length: 11 }, (_, i) => ({ t: +(2.3 + i * .15).toFixed(2), key: 'right', dur: .07 }))],
          goal: [{ k: 'touched', a: 'cistella', b: 'poma' }, { k: 'touched', a: 'cistella', b: 'platan' }, { k: 'sound' }, { k: 'moved', s: 'platan', min: 300 }] },
        edit: ['cistella', 'poma', 'platan'], hats: ['flag', 'key:left', 'key:right'], hatsBy: { cistella: ['key:left', 'key:right', 'flag'], poma: ['flag'], platan: ['flag'] }, pal: ['chx', 'chy', 'goto', 'sety', 'say', 'next', 'size', 'sound', 'wait', 'stop', 'forever', 'if', 'else', 'and', 'cond+'],
        texts: ['Ñam!|¡Ñam!', 'Una altra!|¡Otra!', 'Quina fruita més bona!|¡Qué fruta tan buena!'],
        prog: '@cistella key:right{ chx:20 if:touch:edge{ chx:-20 } } key:left{ chx:-20 if:touch:edge{ chx:20 } } @poma flag{ forever{ chy:-4 } }',
        sol: '@cistella key:right{ chx:20 if:touch:edge{ chx:-20 } } key:left{ chx:-20 if:touch:edge{ chx:20 } } @poma flag{ forever{ chy:-4 if:touch:cistella{ sound:pop sety:150 } if:touch:edge{ sety:150 } } } @platan flag{ forever{ chy:-5 if:touch:cistella{ sound:moneda sety:150 } if:touch:edge{ sety:150 } } }',
        check: P => { const f = l => (l || []).some(b => (b.k === 'if' && JSON.stringify(b.c || {}).includes('"cistella"') && (b.b || []).length) || f(b.b) || f(b.e)); const ok = id => Object.values(P[id] || {}).some(sc => sc.some(f)); return ok('poma') && ok('platan') ? null : 'La poma i el plàtan necessiten la regla «si toca la cistella» amb algun bloc a dins.|La manzana y el plátano necesitan la regla «si toca la cesta» con algún bloque dentro.'; } },
      { k: 'quiz', ph: 'tanca', q: 'Quina regla fa que el videojoc s\'acabi quan cau la roca?|¿Qué regla hace que el videojuego se acabe cuando cae la roca?',
        opts: ['Si la roca toca la cistella, atura-ho tot|Si la roca toca la cesta, páralo todo', 'Si la roca toca la vora, posa y a 150|Si la roca toca el borde, pon y a 150', 'Canvia y en -5|Cambia y en -5'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: 'El teu tester diu: «El plàtan surt per baix i no torna mai.» Què li falta al plàtan?|Tu tester dice: «El plátano sale por abajo y no vuelve nunca.» ¿Qué le falta al plátano?',
        opts: ['La regla «si toca la vora, posa y a 150»|La regla «si toca el borde, pon y a 150»', 'Un fons nou|Un fondo nuevo', 'Més velocitat|Más velocidad'], a: 0,
        ex: 'Escoltar el tester ajuda a trobar errors que tu no havies vist.|Escuchar al tester ayuda a encontrar errores que tú no habías visto.' },
      { k: 'feel', ph: 'tanca' }
    ] }
] };
