/* Tech 3D · Nivell 2 · unitat 7 «Enginyeria i fabricació» (p7-1 … p7-4)
   Contingut propi de Numi. Fil narratiu: l'estudi d'enginyeria del Taller de Bit rep els primers encàrrecs reals (la
   fusteria d'en Ramon, la Marta i el seu penjador, el museu del barri) i aprèn a dissenyar per fabricar:
   p7-1 peces que encaixen (eix i forat, pestanya i ranura, tapa amb llavi) · p7-2 toleràncies (forat = d + 2 × tol) ·
   p7-3 voladissos, la regla dels 45°, ponts i orientació a la placa · p7-4 projecte: una frontissa desmuntable en dues
   peces amb tolerància paramètrica.
   Notes tècniques: les comprovacions que han de distingir dècimes de mil·límetre fan servir «part» (mides exactes de la
   peça, tol 0,05) i no la semblança de volum; quan hi ha dues peces separades a la placa no es demana «one». Les
   variables que surten a les comprovacions tenen el mateix nom en les dues llengües (d, tol, diam, h); la resta de
   programes porten versió «ca|es» quan hi ha comentaris o noms propis de cada llengua. */
Object.assign(TBADGE, {
  p74_frontissa: { id: 'p74_frontissa', ico: '🔩', n: 'Enginyer/a de frontisses|Ingeniero/a de bisagras', d: "Has dissenyat una frontissa de dues peces amb tolerància paramètrica, sense suports i a punt per imprimir.|Has diseñado una bisagra de dos piezas con tolerancia paramétrica, sin soportes y lista para imprimir." }
});
COURSE_UNITS[7] = (() => {
  /* ---------- p7-1 · peces que encaixen ---------- */
  const PEG = 'resta {\n  cub(30, 30, 12)\n  mou(15, 15, -1) cilindre(10, 14)\n}\nmou(50, 15, 0) cilindre(10, 20)';
  const PEGD = 'd = 10\nresta {\n  cub(30, 30, 12)\n  mou(15, 15, -1) cilindre(d, 14)\n}\nmou(50, 15, 0) cilindre(d, 20)';
  const SLOT = 'resta {\n  cub(40, 20, 10)\n  mou(10, 8, 3) cub(20, 4, 8)\n}\nmou(0, 30, 0) {\n  cub(40, 20, 4)\n  mou(10, 8, 4) cub(20, 4, 6)\n}';
  const LID0 = "d = 40\nparet = 2\n// el pot\ncilindre(d, 2)\ntub(d, 30, paret)\n// la tapa (s'imprimeix del revés)\nmou(55, 0, 0) cilindre(d, 3)|d = 40\npared = 2\n// el bote\ncilindro(d, 2)\ntubo(d, 30, pared)\n// la tapa (se imprime del revés)\nmueve(55, 0, 0) cilindro(d, 3)";
  const LID = "d = 40\nparet = 2\n// el pot\ncilindre(d, 2)\ntub(d, 30, paret)\n// la tapa (s'imprimeix del revés)\nmou(55, 0, 0) cilindre(d, 3)\nmou(55, 0, 3) tub(d - 2 * paret, 5, 1.5)|d = 40\npared = 2\n// el bote\ncilindro(d, 2)\ntubo(d, 30, pared)\n// la tapa (se imprime del revés)\nmueve(55, 0, 0) cilindro(d, 3)\nmueve(55, 0, 3) tubo(d - 2 * pared, 5, 1.5)";
  /* ---------- p7-2 · toleràncies ---------- */
  const TOL0 = 'd = 10\ntol = 0.3\nresta {\n  cub(30, 30, 12)\n  mou(15, 15, -1) cilindre(d, 14)\n}\nmou(50, 15, 0) cilindre(d, 20)';
  const TOLD = 'd = 10\ntol = 0.3\nresta {\n  cub(30, 30, 12)\n  mou(15, 15, -1) cilindre(d + 2 * tol, 14)\n}\nmou(50, 15, 0) cilindre(d, 20)';
  const TEST = 'resta {\n  cub(64, 16, 5)\n  repeteix i de 1 a 4 {\n    mou(15 * i - 5, 8, -1) cilindre(6 + 2 * i * 0.1, 7)\n  }\n}\nmou(5, 30, 0) cilindre(6, 12)';
  const CAP = 'd = 22\ntol = 0.2\nresta {\n  cilindre(d + 2 * tol + 4, 15)\n  mou(0, 0, 2) cilindre(d + 2 * tol, 15)\n}';
  const WHEEL0 = "lliure = 0.4\npressio = 0.1\neix = 5\n// la roda: ha de girar\nresta {\n  cilindre(30, 6)\n  mou(0, 0, -1) cilindre(eix, 8)\n}\n// el tap: s'ha de quedar fix\nmou(30, 0, 0) resta {\n  cilindre(10, 5)\n  mou(0, 0, -1) cilindre(eix, 7)\n}|libre = 0.4\npresion = 0.1\neje = 5\n// la rueda: tiene que girar\nresta {\n  cilindro(30, 6)\n  mueve(0, 0, -1) cilindro(eje, 8)\n}\n// el tapón: tiene que quedarse fijo\nmueve(30, 0, 0) resta {\n  cilindro(10, 5)\n  mueve(0, 0, -1) cilindro(eje, 7)\n}";
  const WHEEL = "lliure = 0.4\npressio = 0.1\neix = 5\n// la roda: ha de girar\nresta {\n  cilindre(30, 6)\n  mou(0, 0, -1) cilindre(eix + 2 * lliure, 8)\n}\n// el tap: s'ha de quedar fix\nmou(30, 0, 0) resta {\n  cilindre(10, 5)\n  mou(0, 0, -1) cilindre(eix + 2 * pressio, 7)\n}|libre = 0.4\npresion = 0.1\neje = 5\n// la rueda: tiene que girar\nresta {\n  cilindro(30, 6)\n  mueve(0, 0, -1) cilindro(eje + 2 * libre, 8)\n}\n// el tapón: tiene que quedarse fijo\nmueve(30, 0, 0) resta {\n  cilindro(10, 5)\n  mueve(0, 0, -1) cilindro(eje + 2 * presion, 7)\n}";
  /* ---------- p7-3 · voladissos i suports ---------- */
  const MUSH90 = 'cilindre(10, 20)\nmou(0, 0, 20) cilindre(30, 5)';
  const MUSH = 'cilindre(10, 20)\nmou(0, 0, 10) con(10, 10, 30)\nmou(0, 0, 20) cilindre(30, 5)';
  const MUSH2 = 'cilindre(10, 20)\nmou(0, 0, 20) cilindre(30, 5)\nmou(45, 0, 0) {\n  cilindre(10, 20)\n  mou(0, 0, 10) con(10, 10, 30)\n  mou(0, 0, 20) cilindre(30, 5)\n}';
  const BRIDGE = 'cub(10, 20, 30)\nmou(40, 0, 0) cub(10, 20, 30)\nmou(0, 0, 30) cub(50, 20, 5)';
  const STAMP0 = 'cilindre(12, 25)\nmou(-20, -20, 25) cub(40, 40, 4)';
  const STAMP = 'mou(0, 0, 29) gira(180, 0, 0) {\n  cilindre(12, 25)\n  mou(-20, -20, 25) cub(40, 40, 4)\n}';
  const STAMP2 = 'cilindre(12, 25)\nmou(-20, -20, 25) cub(40, 40, 4)\nmou(55, 0, 29) gira(180, 0, 0) {\n  cilindre(12, 25)\n  mou(-20, -20, 25) cub(40, 40, 4)\n}';
  const HOOK0 = 'cub(5, 20, 50)\nmou(0, 0, 45) cub(30, 20, 5)\nmou(25, 0, 35) cub(5, 20, 15)';
  const HOOK = 'gira(90, 0, 0) {\n  cub(5, 20, 50)\n  mou(0, 0, 45) cub(30, 20, 5)\n  mou(25, 0, 35) cub(5, 20, 15)\n}';
  const ROUND = 'resta {\n  cub(40, 20, 20)\n  mou(20, -1, 10) gira(-90, 0, 0) cilindre(8, 22)\n}';
  const DIAM = 'resta {\n  cub(40, 20, 20)\n  mou(20, 10, 10) gira(0, 45, 0) cub(8, 22, 8, centrat)\n}';
  /* ---------- p7-4 · la frontissa (variables: tol, passador/pasador, diam, h) ---------- */
  const HV = (pin) => `tol = 0.3\n${pin} = 5\ndiam = 10\nh = 20`;
  const A0 = `${HV('passador')}\n// peça A: l'ala i el cilindre\nmou(-30, -1.5, 0) cub(30, 3, h)\ncilindre(diam, h)|${HV('pasador')}\n// pieza A: el ala y el cilindro\nmueve(-30, -1.5, 0) cubo(30, 3, h)\ncilindro(diam, h)`;
  const A1 = `${HV('passador')}\n// peça A: l'ala, el cilindre i el passador\nmou(-30, -1.5, 0) cub(30, 3, h)\ncilindre(diam, h)\nmou(0, 0, h) cilindre(passador, 10)|${HV('pasador')}\n// pieza A: el ala, el cilindro y el pasador\nmueve(-30, -1.5, 0) cubo(30, 3, h)\ncilindro(diam, h)\nmueve(0, 0, h) cilindro(pasador, 10)`;
  const B0 = `${HV('passador')}\n// peça B: l'ala i el cilindre (el forat anirà a sota)\nuneix {\n  mou(0, -1.5, 0) cub(30, 3, h)\n  cilindre(diam, h)\n}|${HV('pasador')}\n// pieza B: el ala y el cilindro (el agujero irá debajo)\nune {\n  mueve(0, -1.5, 0) cubo(30, 3, h)\n  cilindro(diam, h)\n}`;
  const Bx = (diam, tol, hole, cmt) => [['passador', 'cub', 'cilindre', 'mou', 'uneix', cmt[0]], ['pasador', 'cubo', 'cilindro', 'mueve', 'une', cmt[1]]].map(([pin, cu, ci, mo, un, c]) =>
    `tol = ${tol}\n${pin} = 5\ndiam = ${diam}\nh = 20\n// ${c}\nresta {\n  ${un} {\n    ${mo}(0, -1.5, 0) ${cu}(30, 3, h)\n    ${ci}(diam, h)\n  }\n  ${hole(pin, mo, ci)}\n}`).join('|');
  const CB = ["peça B: el forat a sota, amb tolerància", 'pieza B: el agujero debajo, con tolerancia'];
  const B1 = Bx(10, 0.3, (p, m, c) => `${m}(0, 0, -1) ${c}(${p} + 2 * tol, 12)`, CB);
  const BTHRU = Bx(10, 0.3, (p, m, c) => `${m}(0, 0, -1) ${c}(${p} + 2 * tol, 22)`, CB);
  const BTOP = Bx(10, 0.3, (p, m, c) => `${m}(0, 0, 9) ${c}(${p} + 2 * tol, 12)`, CB);
  const BBAD = Bx(10, 0.3, (p, m, c) => `${m}(0, 0, -1) ${c}(${p}, 12)!`, CB);
  const B7 = Bx(7, 0.4, (p, m, c) => `${m}(0, 0, -1) ${c}(${p} + 2 * tol, 12)`, ['el client la vol més prima: com a molt 9 mm', 'el cliente la quiere más fina: como mucho 9 mm']);
  const B9 = Bx(9, 0.4, (p, m, c) => `${m}(0, 0, -1) ${c}(${p} + 2 * tol, 12)`, ['el client la vol més prima: com a molt 9 mm', 'el cliente la quiere más fina: como mucho 9 mm']);
  const MODS = [['passador', 'cub', 'cilindre', 'mou', 'uneix', 'defineix', 'pecaA', 'pecaB', 'les dues peces de la frontissa', 'gira'], ['pasador', 'cubo', 'cilindro', 'mueve', 'une', 'define', 'piezaA', 'piezaB', 'las dos piezas de la bisagra', 'gira']];
  const HMOD = (tail) => MODS.map(([pin, cu, ci, mo, un, de, A, B, c, gi], k) =>
    `tol = 0.3\n${pin} = 5\ndiam = 10\nh = 20\n// ${c}\n${de} ${A}() {\n  ${mo}(-30, -1.5, 0) ${cu}(30, 3, h)\n  ${ci}(diam, h)\n  ${mo}(0, 0, h) ${ci}(${pin}, 10)\n}\n${de} ${B}() {\n  resta {\n    ${un} {\n      ${mo}(0, -1.5, 0) ${cu}(30, 3, h)\n      ${ci}(diam, h)\n    }\n    ${mo}(0, 0, -1) ${ci}(${pin} + 2 * tol, 12)\n  }\n}\n${tail(A, B, mo, gi, k)}`).join('|');
  const HONE = HMOD(A => `${A}()`);
  const HTWO = HMOD((A, B, mo) => `${A}()\n${mo}(40, 0, 0) ${B}()`);
  const HMNT = HMOD((A, B, mo, gi) => `${A}()\n${mo}(0, 0, h) ${gi}(0, 0, 120) ${B}()`);
  const BL1 = ['cub', 'cil', 'tub', 'mou', 'resta', 'uneix', 'var'];
  return {
  t: 'Enginyeria i fabricació|Ingeniería y fabricación', d: 'Encaixos i toleràncies|Encajes y tolerancias', color: '#14A3B8',
  s: [
    /* =================================== Sessió 1 · Peces que encaixen =================================== */
    { id: 'p7-1', t: 'Peces que encaixen|Piezas que encajan', min: 45,
      learn: ["Un muntatge són peces pensades per encaixar: eix i forat, pestanya i ranura o tapa amb llavi.|Un montaje son piezas pensadas para encajar: eje y agujero, pestaña y ranura o tapa con labio.",
        "Les mides que s'han de correspondre (el forat i l'eix) es lliguen amb la mateixa variable.|Las medidas que tienen que corresponderse (el agujero y el eje) se ligan con la misma variable.",
        "Les peces d'un muntatge s'imprimeixen per separat, una al costat de l'altra a la placa, i després es munten.|Las piezas de un montaje se imprimen por separado, una al lado de la otra en la placa, y después se montan."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Què fa <code>resta { A  B }</code>?|¿Qué hace <code>resta { A  B }</code>?', opts: ['Es queda amb A i li treu B|Se queda con A y le quita B', 'Uneix A i B en una sola peça|Une A y B en una sola pieza', 'Es queda només amb la part que tenen en comú|Se queda solo con la parte que tienen en común'], a: 0,
          ex: 'El primer element de la resta és el que queda; tots els altres es treuen. Així es fan els forats.|El primer elemento de la resta es el que queda; todos los demás se quitan. Así se hacen los agujeros.' },
        { k: 'quiz', ph: 'recorda', q: 'Si <code>d = 10</code>, quina mida té <code>cilindre(d + 4, 5)</code>?|Si <code>d = 10</code>, ¿qué medida tiene <code>cilindro(d + 4, 5)</code>?', opts: ['14 mm de diàmetre i 5 d\'alçada|14 mm de diámetro y 5 de altura', '10 mm de diàmetre i 9 d\'alçada|10 mm de diámetro y 9 de altura', '4 mm de diàmetre i 5 d\'alçada|4 mm de diámetro y 5 de altura'], a: 0 },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: 'El primer encàrrec de veritat|El primer encargo de verdad',
          t: "Ha sonat el telèfon de l'estudi: és en <b>Ramon</b>, de la fusteria del barri. Fa cadires, taules i calaixos de fusta, i ens demana peces de plàstic que <b>encaixin</b> amb les seves: taps per a les potes, tapes per als pots de cargols, ranures i pestanyes… Fins ara hem fet objectes d'una sola peça. Ara toca dissenyar <b>peces que es munten</b>. Benvinguts a la unitat d'enginyeria!|Ha sonado el teléfono del estudio: es <b>Ramon</b>, de la carpintería del barrio. Hace sillas, mesas y cajones de madera, y nos pide piezas de plástico que <b>encajen</b> con las suyas: tapones para las patas, tapas para los botes de tornillos, ranuras y pestañas… Hasta ahora hemos hecho objetos de una sola pieza. Ahora toca diseñar <b>piezas que se montan</b>. ¡Bienvenidos a la unidad de ingeniería!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Muntatges|Montajes', t: 'Peces que es troben|Piezas que se encuentran', anim: 'p71fit',
            x: "Moltes coses de cada dia són <b>muntatges</b>: el tap d'un bolígraf, la tapa d'un pot, les potes d'una cadira. Els encaixos més habituals són tres: l'<b>eix i forat</b> (un cilindre que entra en un forat), la <b>pestanya i ranura</b> (una llengüeta que entra en un tall) i la <b>tapa amb llavi</b> (una vora que entra dins del pot).|Muchas cosas de cada día son <b>montajes</b>: el capuchón de un bolígrafo, la tapa de un bote, las patas de una silla. Los encajes más habituales son tres: el <b>eje y agujero</b> (un cilindro que entra en un agujero), la <b>pestaña y ranura</b> (una lengüeta que entra en un corte) y la <b>tapa con labio</b> (un borde que entra dentro del bote)." },
          { k: 'Eix i forat|Eje y agujero', t: 'El forat es fa amb resta|El agujero se hace con resta', media: { k: 'model', prog: PEG },
            x: "El bloc de l'esquerra és un <code>cub</code> menys un <code>cilindre</code>: un forat de 10 mm. El cilindre del forat comença a <b>z = −1</b> i fa 14 mm, una mica més que el bloc (12 mm): així travessa del tot. L'eix de la dreta és una <b>altra peça</b>, fora de la resta.|El bloque de la izquierda es un <code>cubo</code> menos un <code>cilindro</code>: un agujero de 10 mm. El cilindro del agujero empieza en <b>z = −1</b> y mide 14 mm, un poco más que el bloque (12 mm): así lo atraviesa del todo. El eje de la derecha es <b>otra pieza</b>, fuera de la resta.",
            tip: "Un forat que travessa ha de sobresortir una mica per dalt i per baix. Si acaba just a la cara, hi pot quedar una làmina finíssima.|Un agujero que atraviesa tiene que sobresalir un poco por arriba y por abajo. Si acaba justo en la cara, puede quedar una lámina finísima." },
          { k: 'Mides lligades|Medidas ligadas', t: 'Una variable per a les dues peces|Una variable para las dos piezas', media: { k: 'model', prog: PEGD },
            x: "L'eix i el forat han de fer la mateixa mida. Si escrius el número dues vegades, el dia que el canviïs en un lloc i no en l'altre, ja no encaixaran. Per això els enginyers fan servir <b>una sola variable</b> per a totes dues peces: <code>d = 10</code>. Canvia d, i canvien l'eix i el forat alhora.|El eje y el agujero tienen que medir lo mismo. Si escribes el número dos veces, el día que lo cambies en un sitio y no en el otro, ya no encajarán. Por eso los ingenieros usan <b>una sola variable</b> para las dos piezas: <code>d = 10</code>. Cambia d, y cambian el eje y el agujero a la vez." },
          { k: 'Pestanya i ranura|Pestaña y ranura', t: 'Un forat que no travessa|Un agujero que no atraviesa', media: { k: 'model', prog: SLOT },
            x: "La <b>ranura</b> és un <code>cub</code> restat que no arriba a baix de tot. Ha de ser <b>una mica més fonda</b> que la pestanya (aquí, 7 mm per a una pestanya de 6): si no, la pestanya toparia amb el fons i les dues peces no quedarien juntes.|La <b>ranura</b> es un <code>cubo</code> restado que no llega abajo del todo. Tiene que ser <b>un poco más honda</b> que la pestaña (aquí, 7 mm para una pestaña de 6): si no, la pestaña toparía con el fondo y las dos piezas no quedarían juntas." },
          { k: 'Tapa amb llavi|Tapa con labio', t: 'La vora que entra dins del pot|El borde que entra dentro del bote', media: { k: 'model', prog: LID },
            x: "El pot és un <code>tub</code> amb paret de gruix <code>paret</code>: per dins fa <code>d − 2 × paret</code>. El <b>llavi</b> de la tapa ha de fer just aquesta mida per fora. La tapa s'imprimeix <b>del revés</b>, amb el llavi cap amunt, perquè la cara plana quedi a la placa.|El bote es un <code>tubo</code> con pared de grosor <code>pared</code>: por dentro mide <code>d − 2 × pared</code>. El <b>labio</b> de la tapa tiene que medir justo eso por fuera. La tapa se imprime <b>del revés</b>, con el labio hacia arriba, para que la cara plana quede en la placa." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🔍', title: "Caça d'encaixos|Caza de encajes", t: 'Per parelles, amb un regle (o un peu de rei, si n\'hi ha):|Por parejas, con una regla (o un pie de rey, si hay):',
          steps: ["Busqueu a la classe o a la motxilla 4 objectes amb peces que encaixen: un bolígraf amb tap, un pot, una carpeta, un estoig…|Buscad en la clase o en la mochila 4 objetos con piezas que encajan: un bolígrafo con capuchón, un bote, una carpeta, un estuche…",
            "Per a cada objecte, digueu quin encaix és: eix i forat, pestanya i ranura, tapa amb llavi o un altre (rosca, imant, pressió…).|Para cada objeto, decid qué encaje es: eje y agujero, pestaña y ranura, tapa con labio u otro (rosca, imán, presión…).",
            "Mesureu les dues mides que es corresponen: el gruix del bolígraf i el forat del tap, per exemple. Són exactament iguals?|Medid las dos medidas que se corresponden: el grosor del bolígrafo y el agujero del capuchón, por ejemplo. ¿Son exactamente iguales?"],
          tip: 'Fixeu-vos-hi bé: la peça de fora sempre és una mica més gran. La setmana que ve descobrirem per què.|Fijaos bien: la pieza de fuera siempre es un poco más grande. La semana que viene descubriremos por qué.' },
        { k: 'm3predict', ph: 'prova', q: 'Llegeix el programa. <b>Quin muntatge fa?</b>|Lee el programa. <b>¿Qué montaje hace?</b>', prog: PEG,
          opts: [{ prog: PEG }, { prog: 'cub(30, 30, 12)\nmou(15, 15, -1) cilindre(10, 14)\nmou(50, 15, 0) cilindre(10, 20)' }, { prog: 'resta {\n  cub(30, 30, 12)\n  mou(15, 15, -1) cilindre(10, 14)\n}\nmou(15, 15, 0) cilindre(10, 20)' }, { prog: 'resta {\n  cub(30, 30, 12)\n  mou(0, 0, -1) cilindre(10, 14)\n}\nmou(50, 15, 0) cilindre(10, 20)' }], a: 0,
          ex: "La resta treu el cilindre del centre del bloc (15, 15): queda un forat de 10 mm que travessa. El segon cilindre és fora de la resta: és l'eix, una peça a part que s'imprimeix al costat.|La resta quita el cilindro del centro del bloque (15, 15): queda un agujero de 10 mm que lo atraviesa. El segundo cilindro está fuera de la resta: es el eje, una pieza aparte que se imprime al lado." },
        { k: 'm3spot', ph: 'investiga', q: "En Ramon diu que l'eix <b>no entra</b> al forat. Toca la instrucció que fa la mida equivocada.|Ramon dice que el eje <b>no entra</b> en el agujero. Toca la instrucción que hace la medida equivocada.",
          prog: 'd = 10\nresta {\n  cub(30, 30, 12)\n  mou(15, 15, -1) cilindre(8, 14)!\n}\nmou(50, 15, 0) cilindre(d, 20)', target: PEGD,
          ex: "El forat fa 8 mm i l'eix, 10: no hi cap. Si el forat també fes servir la variable d, sempre farien el mateix.|El agujero mide 8 mm y el eje, 10: no cabe. Si el agujero también usara la variable d, siempre medirían lo mismo." },
        { k: 'move', ph: 'pausa', title: 'Encaixa amb el cos|Encaja con el cuerpo', secs: 30, t: "Fes un <b>forat</b> amb una mà (un cercle amb el polze i l'índex) i un <b>eix</b> amb un dit de l'altra: fes-lo entrar i sortir 5 vegades. Ara fes una <b>ranura</b> amb les dues mans juntes i fes-hi entrar l'altra mà plana com una pestanya!|Haz un <b>agujero</b> con una mano (un círculo con el pulgar y el índice) y un <b>eje</b> con un dedo de la otra: hazlo entrar y salir 5 veces. ¡Ahora haz una <b>ranura</b> con las dos manos juntas y haz entrar en ella la otra mano plana como una pestaña!" },
        { k: 'm3code', ph: 'repte', text: true, q: "Ara el cilindre del centre <b>s'afegeix</b> al bloc. Converteix-lo en un <b>forat</b>: posa el bloc i aquest cilindre dins d'una <code>resta</code>. L'eix de la dreta s'ha de quedar com està.|Ahora el cilindro del centro <b>se añade</b> al bloque. Conviértelo en un <b>agujero</b>: pon el bloque y ese cilindro dentro de una <code>resta</code>. El eje de la derecha tiene que quedarse como está.",
          start: 'cub(30, 30, 12)\nmou(15, 15, -1) cilindre(10, 14)\nmou(50, 15, 0) cilindre(10, 20)', blocks: BL1, target: PEG,
          checks: [{ k: 'hole', t: 'El bloc té un forat|El bloque tiene un agujero' }, { k: 'part', t: 'cyl', hole: true, s: [10, 10, 14], at: [15, 15, null], tol: 0.05, txt: "El forat fa 10 mm, com l'eix|El agujero mide 10 mm, como el eje" },
            { k: 'part', t: 'cyl', hole: false, s: [10, 10, 20], at: [50, 15, null], tol: 0.05, txt: "L'eix continua sent una peça a part|El eje sigue siendo una pieza aparte" }, { k: 'uses', b: 'diff' }],
          hint: "Afegeix un bloc «resta» i posa-hi a dins, en aquest ordre, el cub i el cilindre del forat (amb el seu mou). El primer de la resta és el que queda; el segon és el que es treu.|Añade un bloque «resta» y pon dentro, en este orden, el cubo y el cilindro del agujero (con su mueve). El primero de la resta es el que queda; el segundo es el que se quita.",
          sol: PEG },
        { k: 'm3code', ph: 'repte', text: true, q: "Fes la <b>ranura</b> on entrarà la pestanya de la placa: 20 mm de llarg, 4 mm d'ample i <b>7 mm de fons</b> (1 mm més que la pestanya), centrada al bloc de 40 × 20 × 10.|Haz la <b>ranura</b> donde entrará la pestaña de la placa: 20 mm de largo, 4 mm de ancho y <b>7 mm de fondo</b> (1 mm más que la pestaña), centrada en el bloque de 40 × 20 × 10.",
          start: 'cub(40, 20, 10)\nmou(0, 30, 0) {\n  cub(40, 20, 4)\n  mou(10, 8, 4) cub(20, 4, 6)\n}', blocks: ['cub', 'mou', 'resta', 'uneix'], target: SLOT,
          checks: [{ k: 'part', t: 'box', hole: true, s: [20, 4, 8], at: [20, 10, 7], tol: 0.05, txt: 'La ranura fa 20 × 4 mm i 7 de fons, al centre|La ranura mide 20 × 4 mm y 7 de fondo, en el centro' }, { k: 'hole', t: 'El bloc té la ranura buidada|El bloque tiene la ranura vaciada' }, { k: 'wall', min: 1.2, t: 'Cap paret de menys de 1,2 mm|Ninguna pared de menos de 1,2 mm' }, { k: 'onplate' }],
          hint: "Per centrar 20 × 4 en un bloc de 40 × 20: x = (40 − 20) ÷ 2 = 10 i y = (20 − 4) ÷ 2 = 8. El bloc acaba a z = 10: per fer 7 de fons comença a z = 3, i fes-la de 8 d'alçada perquè sobresurti 1 mm per dalt: mou(10, 8, 3) cub(20, 4, 8).|Para centrar 20 × 4 en un bloque de 40 × 20: x = (40 − 20) ÷ 2 = 10 e y = (20 − 4) ÷ 2 = 8. El bloque acaba en z = 10: para 7 de fondo empieza en z = 3, y hazla de 8 de altura para que sobresalga 1 mm por arriba: mueve(10, 8, 3) cubo(20, 4, 8).",
          sol: SLOT },
        { k: 'm3code', ph: 'repte', text: true, q: "En Ramon vol eixos de gruixos diferents. Fes que el forat faci servir la variable <code>d</code>, com l'eix: així, si canvies d, canvien totes dues peces.|Ramon quiere ejes de grosores distintos. Haz que el agujero use la variable <code>d</code>, como el eje: así, si cambias d, cambian las dos piezas.",
          start: 'd = 10\nresta {\n  cub(30, 30, 12)\n  mou(15, 15, -1) cilindre(10, 14)\n}\nmou(50, 15, 0) cilindre(d, 20)', blocks: BL1, vars: ['d'],
          checks: [{ k: 'part', t: 'cyl', hole: true, s: ['d', 'd', 14], at: [15, 15, null], tol: 0.05, txt: 'El forat fa d mm|El agujero mide d mm' }, { k: 'part', t: 'cyl', hole: false, s: ['d', 'd', 20], tol: 0.05, txt: "L'eix fa d mm|El eje mide d mm" },
            { k: 'param', v: 'd', vals: [6, 12], t: 'Encaixen amb d = 6 i amb d = 12|Encajan con d = 6 y con d = 12' }],
          hint: 'Toca el 10 del cilindre del forat i escriu-hi d.|Toca el 10 del cilindro del agujero y escribe d.', sol: PEGD },
        { k: 'm3code', ph: 'repte', text: true, q: "La tapa del pot de cargols: afegeix-hi un <b>llavi</b> que entri dins del pot. És un <code>tub</code> de 5 mm d'alt i 1,5 mm de paret que per fora fa el diàmetre de dins del pot, <code>d − 2 × paret</code>, i va a sobre de la tapa (s'imprimeix del revés).|La tapa del bote de tornillos: añádele un <b>labio</b> que entre dentro del bote. Es un <code>tubo</code> de 5 mm de alto y 1,5 mm de pared que por fuera mide el diámetro de dentro del bote, <code>d − 2 × pared</code>, y va encima de la tapa (se imprime del revés).",
          start: LID0, blocks: ['var', 'cil', 'tub', 'mou', 'uneix'],
          checks: [{ k: 'part', t: 'tube', s: ['d - 4', 'd - 4', 5], at: [55, 0, 5.5], tol: 0.05, txt: 'El llavi fa per fora el que el pot per dins|El labio mide por fuera lo que el bote por dentro' }, { k: 'param', v: 'd', vals: [36, 44], t: 'Encaixa amb pots de 36 i de 44 mm|Encaja con botes de 36 y de 44 mm' }, { k: 'wall', min: 1.2, t: 'Cap paret de menys de 1,2 mm|Ninguna pared de menos de 1,2 mm' }, { k: 'onplate' }],
          hint: "La tapa acaba a z = 3: el llavi hi va a sobre, amb mou(55, 0, 3) tub(d - 2 * paret, 5, 1.5).|La tapa acaba en z = 3: el labio va encima, con mueve(55, 0, 3) tubo(d - 2 * pared, 5, 1.5).",
          sol: LID },
        { k: 'm3free', ph: 'crea', text: true, q: "<b>El teu encaix.</b> Dissenya dues peces que encaixin: un eix i el seu forat, una pestanya i la seva ranura o una tapa amb llavi. Posa-les una al costat de l'altra i fes servir una variable per a la mida que comparteixen.|<b>Tu encaje.</b> Diseña dos piezas que encajen: un eje y su agujero, una pestaña y su ranura o una tapa con labio. Ponlas una al lado de la otra y usa una variable para la medida que comparten.",
          name: 'Les meves peces que encaixen|Mis piezas que encajan', blocks: ['var', 'cub', 'cil', 'tub', 'con', 'esf', 'mou', 'resta', 'uneix', 'color'],
          crit: ["Dues peces que encaixen, una al costat de l'altra a la placa|Dos piezas que encajan, una al lado de la otra en la placa", 'La mida que comparteixen és una variable (per exemple, d)|La medida que comparten es una variable (por ejemplo, d)', 'El forat o la ranura es fa amb resta|El agujero o la ranura se hace con resta'],
          checks: [{ k: 'uses', b: 'var' }, { k: 'uses', b: 'diff' }, { k: 'hole', t: 'Té un forat o una ranura|Tiene un agujero o una ranura' }, { k: 'onplate' }],
          sol: 'd = 8\nresta {\n  cilindre(30, 10)\n  mou(0, 0, -1) cilindre(d, 12)\n}\nmou(35, 0, 0) cilindre(d, 18)' },
        { k: 'quiz', ph: 'tanca', q: "Per què el forat i l'eix fan servir la mateixa variable?|¿Por qué el agujero y el eje usan la misma variable?", opts: ['Perquè si en canvio la mida, canvien tots dos i continuen encaixant|Porque si cambio la medida, cambian los dos y siguen encajando', 'Perquè el programa va més de pressa|Porque el programa va más rápido', 'Perquè una variable no es pot fer servir una sola vegada|Porque una variable no se puede usar una sola vez'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Un forat ha de travessar un bloc de 12 mm d\'alçada. Quin cilindre restes?|Un agujero tiene que atravesar un bloque de 12 mm de altura. ¿Qué cilindro restas?', opts: ['Un que comenci a z = −1 i faci 14 mm|Uno que empiece en z = −1 y mida 14 mm', 'Un que comenci a z = 0 i faci 12 mm justos|Uno que empiece en z = 0 y mida 12 mm justos', 'Un de 6 mm d\'alçada|Uno de 6 mm de altura'], a: 0,
          ex: 'Si sobresurt per dalt i per baix, segur que no queda cap làmina.|Si sobresale por arriba y por abajo, seguro que no queda ninguna lámina.' },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* =================================== Sessió 2 · Toleràncies =================================== */
    { id: 'p7-2', t: 'Toleràncies|Tolerancias', min: 45,
      learn: ["Les impressores 3D no són exactes: el plàstic s'aixafa i s'encongeix, i els forats surten una mica més petits.|Las impresoras 3D no son exactas: el plástico se aplasta y encoge, y los agujeros salen un poco más pequeños.",
        "La tolerància és l'espai que es deixa a cada costat: forat = d + 2 × tol, sovint amb tol entre 0,2 i 0,4 mm.|La tolerancia es el espacio que se deja a cada lado: agujero = d + 2 × tol, a menudo con tol entre 0,2 y 0,4 mm.",
        "Amb una variable tol i una peça de prova, cada impressora troba la seva tolerància.|Con una variable tol y una pieza de prueba, cada impresora encuentra su tolerancia."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Què fa aquest programa dins d\'una resta, en un bloc de 12 mm? <code>mou(15, 15, -1) cilindre(10, 14)</code>|¿Qué hace este programa dentro de una resta, en un bloque de 12 mm? <code>mueve(15, 15, -1) cilindro(10, 14)</code>',
          opts: ['Un forat de 10 mm que travessa el bloc|Un agujero de 10 mm que atraviesa el bloque', 'Un eix de 10 mm a sobre del bloc|Un eje de 10 mm encima del bloque', 'Un forat de 14 mm|Un agujero de 14 mm'], a: 0 },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: "L'eix no entra!|¡El eje no entra!",
          t: "La Nuvi ha imprès les peces de la setmana passada i en Ramon ha vingut a provar-les… «<b>L'eix no entra al forat!</b>». Però si el forat i l'eix fan exactament 10 mm! Què ha passat? Avui descobrirem el secret que fa servir qualsevol enginyer abans de fabricar: la <b>tolerància</b>.|Nuvi ha impreso las piezas de la semana pasada y Ramon ha venido a probarlas… «<b>¡El eje no entra en el agujero!</b>». ¡Pero si el agujero y el eje miden exactamente 10 mm! ¿Qué ha pasado? Hoy descubriremos el secreto que usa cualquier ingeniero antes de fabricar: la <b>tolerancia</b>." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Fabricar no és exacte|Fabricar no es exacto', t: 'Per què el forat surt més petit|Por qué el agujero sale más pequeño', anim: 'p72why',
            x: "La impressora fa les peces amb un fil de plàstic fos que surt d'un broquet (sovint de 0,4 mm). En sortir, el plàstic <b>s'aixafa i s'eixampla</b> una mica; en refredar-se, <b>s'encongeix</b>; i els cercles es fan amb <b>trossos rectes</b>, com un polígon. Resultat: els forats surten una mica <b>més petits</b> que al disseny i les peces de fora, una mica <b>més grosses</b>.|La impresora hace las piezas con un hilo de plástico fundido que sale de una boquilla (a menudo de 0,4 mm). Al salir, el plástico <b>se aplasta y se ensancha</b> un poco; al enfriarse, <b>encoge</b>; y los círculos se hacen con <b>trozos rectos</b>, como un polígono. Resultado: los agujeros salen un poco <b>más pequeños</b> que en el diseño y las piezas de fuera, un poco <b>más gruesas</b>." },
          { k: 'La tolerància|La tolerancia', t: "L'espai que deixem a propòsit|El espacio que dejamos a propósito", anim: 'p72tol',
            x: "La <b>tolerància</b> (o folgança) és l'espai que deixem a propòsit entre dues peces que encaixen. Va <b>a cada costat</b>: si l'eix fa d, el forat fa <code>d + 2 × tol</code>. Amb les impressores de filament se sol fer servir una tolerància d'entre <b>0,2 i 0,4 mm</b>.|La <b>tolerancia</b> (u holgura) es el espacio que dejamos a propósito entre dos piezas que encajan. Va <b>a cada lado</b>: si el eje mide d, el agujero mide <code>d + 2 × tol</code>. Con las impresoras de filamento se suele usar una tolerancia de entre <b>0,2 y 0,4 mm</b>.",
            tip: "Un full de paper fa més o menys 0,1 mm de gruix: una tolerància de 0,2 mm és com dos fulls a cada costat.|Una hoja de papel mide más o menos 0,1 mm de grosor: una tolerancia de 0,2 mm es como dos hojas a cada lado." },
          { k: "Tipus d'ajust|Tipos de ajuste", t: 'A pressió, lliscant o lliure|A presión, deslizante o libre', anim: 'p72fits',
            x: "Segons la tolerància, l'encaix es comporta diferent: amb molt poca (uns 0,1 mm) entra <b>a pressió</b> i es queda fix; amb una mica més (0,2–0,3 mm) <b>llisca</b>; amb més (uns 0,4 mm) <b>gira lliure</b>, com una roda al seu eix. Són valors orientatius: cada impressora i cada plàstic són una mica diferents.|Según la tolerancia, el encaje se comporta distinto: con muy poca (unos 0,1 mm) entra <b>a presión</b> y se queda fijo; con un poco más (0,2–0,3 mm) <b>desliza</b>; con más (unos 0,4 mm) <b>gira libre</b>, como una rueda en su eje. Son valores orientativos: cada impresora y cada plástico son un poco distintos." },
          { k: 'Tolerància paramètrica|Tolerancia paramétrica', t: 'tol és una variable|tol es una variable', media: { k: 'model', prog: TOLD },
            x: "Si la tolerància és una variable, <code>tol = 0.3</code>, la pots canviar en un segon quan provis les peces. Fixa't que <b>només el forat</b> la fa servir: l'eix continua fent d. Si posessis la tolerància a totes dues peces, tornarien a fer el mateix!|Si la tolerancia es una variable, <code>tol = 0.3</code>, puedes cambiarla en un segundo cuando pruebes las piezas. Fíjate en que <b>solo el agujero</b> la usa: el eje sigue midiendo d. ¡Si pusieras la tolerancia en las dos piezas, volverían a medir lo mismo!",
            tip: 'Al codi, els decimals s\'escriuen amb punt: 0.3 vol dir 0,3 mm.|En el código, los decimales se escriben con punto: 0.3 quiere decir 0,3 mm.' },
          { k: 'La peça de prova|La pieza de prueba', t: 'Cada impressora té la seva tolerància|Cada impresora tiene su tolerancia', media: { k: 'model', prog: TEST },
            x: "Abans d'un encàrrec gran, els enginyers imprimeixen una <b>peça de prova</b>: una tira amb forats de tolerància creixent (0,1 · 0,2 · 0,3 · 0,4 mm) i l'eix. El forat on l'eix entra com vols et diu la tolerància de <b>la teva</b> impressora. Amb un bucle, la tira es fa en quatre línies.|Antes de un encargo grande, los ingenieros imprimen una <b>pieza de prueba</b>: una tira con agujeros de tolerancia creciente (0,1 · 0,2 · 0,3 · 0,4 mm) y el eje. El agujero en el que el eje entra como quieres te dice la tolerancia de <b>tu</b> impresora. Con un bucle, la tira se hace en cuatro líneas." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '📄', title: 'Fundes de paper|Fundas de papel', t: 'Per parelles, amb un retolador gruixut, fulls de paper i cinta adhesiva:|Por parejas, con un rotulador grueso, hojas de papel y cinta adhesiva:',
          steps: ["Enrotlleu una tira de paper ben estreta al voltant del retolador i tanqueu-la amb cinta: és una funda sense tolerància.|Enrollad una tira de papel bien apretada alrededor del rotulador y cerradla con cinta: es una funda sin tolerancia.",
            "Feu-ne una altra, però abans emboliqueu el retolador amb un full de més, que després traureu: és una funda amb una folgança d'uns 0,1 mm a cada costat. Feu-ne una tercera amb tres fulls de més.|Haced otra, pero antes envolved el rotulador con una hoja de más, que después quitaréis: es una funda con una holgura de unos 0,1 mm a cada lado. Haced una tercera con tres hojas de más.",
            "Traieu els fulls de més i proveu les tres fundes: quina entra a pressió, quina llisca i quina balla?|Quitad las hojas de más y probad las tres fundas: ¿cuál entra a presión, cuál desliza y cuál baila?"],
          tip: "Heu fet el mateix que els enginyers: deixar espai a propòsit perquè les peces encaixin com volem.|Habéis hecho lo mismo que los ingenieros: dejar espacio a propósito para que las piezas encajen como queremos." },
        { k: 'quiz', ph: 'prova', q: "L'eix fa 8 mm i <code>tol = 0.3</code>. Quant ha de fer el forat?|El eje mide 8 mm y <code>tol = 0.3</code>. ¿Cuánto tiene que medir el agujero?", opts: ['8,6 mm|8,6 mm', '8,3 mm|8,3 mm', '7,4 mm|7,4 mm'], a: 0,
          ex: 'La tolerància va a cada costat: 8 + 2 × 0,3 = 8,6 mm.|La tolerancia va a cada lado: 8 + 2 × 0,3 = 8,6 mm.' },
        { k: 'm3spot', ph: 'investiga', q: "Aquest forat té tolerància, però l'eix encara hi entra massa just. Toca la instrucció que no la posa bé.|Este agujero tiene tolerancia, pero el eje todavía entra demasiado justo. Toca la instrucción que no la pone bien.",
          prog: 'd = 10\ntol = 0.3\nresta {\n  cub(30, 30, 12)\n  mou(15, 15, -1) cilindre(d + tol, 14)!\n}\nmou(50, 15, 0) cilindre(d, 20)', target: TOLD,
          ex: "Amb d + tol només queden 0,15 mm a cada costat. La tolerància s'ha de sumar dues vegades, una per costat: d + 2 * tol.|Con d + tol solo quedan 0,15 mm a cada lado. La tolerancia tiene que sumarse dos veces, una por lado: d + 2 * tol." },
        { k: 'm3predict', ph: 'investiga', q: 'Quina peça de prova fa aquest programa?|¿Qué pieza de prueba hace este programa?', prog: TEST,
          opts: [{ prog: TEST }, { prog: 'resta {\n  cub(64, 16, 5)\n  repeteix i de 1 a 2 {\n    mou(15 * i - 5, 8, -1) cilindre(6 + 2 * i * 0.1, 7)\n  }\n}\nmou(5, 30, 0) cilindre(6, 12)' },
            { prog: 'resta {\n  cub(16, 64, 5)\n  repeteix i de 1 a 4 {\n    mou(8, 15 * i - 5, -1) cilindre(6 + 2 * i * 0.1, 7)\n  }\n}\nmou(30, 5, 0) cilindre(6, 12)' }, { prog: 'resta {\n  cub(64, 16, 5)\n  repeteix i de 1 a 4 {\n    mou(15 * i - 5, 8, -1) cilindre(6 + 2 * i * 0.1, 7)\n  }\n}' }], a: 0,
          ex: "El bucle fa 4 voltes (i = 1, 2, 3, 4): cada forat és 15 mm més a la dreta i 0,2 mm més ample que l'anterior (6,2 · 6,4 · 6,6 · 6,8 mm). L'eix de 6 mm és fora de la resta.|El bucle da 4 vueltas (i = 1, 2, 3, 4): cada agujero está 15 mm más a la derecha y es 0,2 mm más ancho que el anterior (6,2 · 6,4 · 6,6 · 6,8 mm). El eje de 6 mm está fuera de la resta." },
        { k: 'move', ph: 'pausa', title: 'A pressió, lliscant o lliure?|¿A presión, deslizante o libre?', secs: 30, t: "Posa't dret/a. Quan el professor/a digui «<b>a pressió</b>», abraça't fort (no et pots moure!). Quan digui «<b>llisca</b>», frega't les mans amunt i avall. Quan digui «<b>lliure</b>», gira els braços com una roda. Tres rondes, cada vegada més de pressa!|Ponte de pie. Cuando el profesor/a diga «<b>a presión</b>», abrázate fuerte (¡no te puedes mover!). Cuando diga «<b>desliza</b>», frótate las manos arriba y abajo. Cuando diga «<b>libre</b>», gira los brazos como una rueda. ¡Tres rondas, cada vez más deprisa!" },
        { k: 'm3code', ph: 'repte', text: true, q: "Posa la <b>tolerància</b> al forat: ha de fer <code>d + 2 × tol</code>. L'eix no el toquis: ha de continuar fent d.|Pon la <b>tolerancia</b> en el agujero: tiene que medir <code>d + 2 × tol</code>. El eje no lo toques: tiene que seguir midiendo d.",
          start: TOL0, blocks: BL1, vars: ['d', 'tol'],
          checks: [{ k: 'part', t: 'cyl', hole: true, s: ['d + 2*tol', 'd + 2*tol', 14], at: [15, 15, null], tol: 0.05, txt: 'El forat fa d + 2 × tol|El agujero mide d + 2 × tol' }, { k: 'part', t: 'cyl', hole: false, s: ['d', 'd', 20], tol: 0.05, txt: "L'eix continua fent d|El eje sigue midiendo d" },
            { k: 'param', v: 'tol', vals: [0.2, 0.4], t: 'Funciona amb tol = 0,2 i amb tol = 0,4|Funciona con tol = 0,2 y con tol = 0,4' }],
          hint: 'Al cilindre del forat, canvia d per d + 2 * tol.|En el cilindro del agujero, cambia d por d + 2 * tol.', sol: TOLD },
        { k: 'm3code', ph: 'repte', text: true, q: "El <b>tap per a les potes</b> d'en Ramon: les potes fan 22 mm. El tap és un got petit amb paret i fons de 2 mm que ha d'entrar ajustat (<code>tol = 0.2</code>). Arregla el forat i la mida de fora.|El <b>tapón para las patas</b> de Ramon: las patas miden 22 mm. El tapón es un vaso pequeño con pared y fondo de 2 mm que tiene que entrar ajustado (<code>tol = 0.2</code>). Arregla el agujero y la medida de fuera.",
          start: 'd = 22\ntol = 0.2\nresta {\n  cilindre(d + 4, 15)\n  mou(0, 0, 2) cilindre(d, 15)\n}', blocks: BL1, vars: ['d', 'tol'],
          checks: [{ k: 'part', t: 'cyl', hole: true, s: ['d + 2*tol', 'd + 2*tol', 15], tol: 0.05, txt: 'El forat fa d + 2 × tol|El agujero mide d + 2 × tol' }, { k: 'size', ax: 'x', v: 'd + 2*tol + 4', tol: 0.1, t: 'Per fora fa el forat + 4 mm (paret de 2 mm)|Por fuera mide el agujero + 4 mm (pared de 2 mm)' },
            { k: 'wall', min: 1.8, t: 'Parets i fons d\'uns 2 mm|Paredes y fondo de unos 2 mm' }, { k: 'one' }, { k: 'param', v: 'tol', vals: [0.2, 0.3], t: 'Funciona amb tol = 0,2 i 0,3|Funciona con tol = 0,2 y 0,3' }],
          hint: 'El forat: cilindre(d + 2 * tol, 15). Per fora: el forat més 2 mm de paret a cada costat, cilindre(d + 2 * tol + 4, 15).|El agujero: cilindro(d + 2 * tol, 15). Por fuera: el agujero más 2 mm de pared a cada lado, cilindro(d + 2 * tol + 4, 15).',
          sol: CAP },
        { k: 'm3code', ph: 'repte', text: true, q: "Fes la <b>peça de prova</b>: una tira amb 4 forats per a un eix de 6 mm, de tolerància 0,1 · 0,2 · 0,3 · 0,4 mm, cada 15 mm (el primer a x = 10). Fes servir un <code>repeteix</code>.|Haz la <b>pieza de prueba</b>: una tira con 4 agujeros para un eje de 6 mm, de tolerancia 0,1 · 0,2 · 0,3 · 0,4 mm, cada 15 mm (el primero en x = 10). Usa un <code>repite</code>.",
          start: 'resta {\n  cub(64, 16, 5)\n  mou(10, 8, -1) cilindre(6.2, 7)\n}\nmou(5, 30, 0) cilindre(6, 12)', blocks: ['cub', 'cil', 'mou', 'resta', 'rep', 'var'],
          checks: [{ k: 'count', t: 'cyl', hole: true, min: 4, txt: '4 forats a la tira|4 agujeros en la tira' }, { k: 'part', t: 'cyl', hole: true, s: [6.2, 6.2, 7], at: [10, 8, null], tol: 0.05, txt: 'El primer, de 6,2 mm a x = 10|El primero, de 6,2 mm en x = 10' },
            { k: 'part', t: 'cyl', hole: true, s: [6.8, 6.8, 7], at: [55, 8, null], tol: 0.05, txt: "L'últim, de 6,8 mm a x = 55|El último, de 6,8 mm en x = 55" }, { k: 'uses', b: 'rep' }, { k: 'wall', min: 1.2, t: 'Cap paret de menys de 1,2 mm|Ninguna pared de menos de 1,2 mm' }],
          hint: "Dins de la resta, en lloc del forat: repeteix i de 1 a 4 { mou(15 * i - 5, 8, -1) cilindre(6 + 2 * i * 0.1, 7) }. Amb i = 1 surt x = 10 i 6,2 mm; amb i = 4, x = 55 i 6,8 mm.|Dentro de la resta, en lugar del agujero: repite i de 1 a 4 { mueve(15 * i - 5, 8, -1) cilindro(6 + 2 * i * 0.1, 7) }. Con i = 1 sale x = 10 y 6,2 mm; con i = 4, x = 55 y 6,8 mm.",
          sol: TEST },
        { k: 'm3code', ph: 'repte', text: true, extra: true, q: "Una <b>roda</b> que ha de girar lliure al seu eix de 5 mm (tolerància 0,4) i un <b>tap</b> que s'hi ha de quedar fix, a pressió (0,1). Posa a cada forat la tolerància que li toca.|Una <b>rueda</b> que tiene que girar libre en su eje de 5 mm (tolerancia 0,4) y un <b>tapón</b> que tiene que quedarse fijo, a presión (0,1). Pon en cada agujero la tolerancia que le toca.",
          start: WHEEL0, blocks: BL1,
          checks: [{ k: 'part', t: 'cyl', hole: true, s: [5.8, 5.8, 8], at: [0, 0, null], tol: 0.05, txt: 'La roda: forat de 5,8 mm (gira lliure)|La rueda: agujero de 5,8 mm (gira libre)' }, { k: 'part', t: 'cyl', hole: true, s: [5.2, 5.2, 7], at: [30, 0, null], tol: 0.05, txt: 'El tap: forat de 5,2 mm (a pressió)|El tapón: agujero de 5,2 mm (a presión)' }, { k: 'wall', min: 1.2, t: 'Cap paret de menys de 1,2 mm|Ninguna pared de menos de 1,2 mm' }, { k: 'onplate' }],
          hint: 'Roda: cilindre(eix + 2 * lliure, 8). Tap: cilindre(eix + 2 * pressio, 7).|Rueda: cilindro(eje + 2 * libre, 8). Tapón: cilindro(eje + 2 * presion, 7).', sol: WHEEL },
        { k: 'm3free', ph: 'crea', text: true, q: "<b>A mida d'un objecte real.</b> Tria un objecte de la classe (un llapis, un retolador, una moneda…), mesura'l i dissenya una peça que hi encaixi: un capuçó, un suport, una funda… Posa la mida en una variable i afegeix-hi la tolerància.|<b>A medida de un objeto real.</b> Elige un objeto de la clase (un lápiz, un rotulador, una moneda…), mídelo y diseña una pieza que encaje en él: un capuchón, un soporte, una funda… Pon la medida en una variable y añádele la tolerancia.",
          name: 'La meva peça a mida|Mi pieza a medida', blocks: ['var', 'cub', 'cil', 'tub', 'con', 'esf', 'mou', 'resta', 'uneix', 'color'],
          crit: ["La mida de l'objecte és una variable (mesurada amb el regle)|La medida del objeto es una variable (medida con la regla)", 'El forat fa la mida + 2 × tol|El agujero mide la medida + 2 × tol', 'Cap paret de menys de 1,2 mm|Ninguna pared de menos de 1,2 mm'],
          checks: [{ k: 'uses', b: 'var' }, { k: 'hole', t: 'Té el forat per a l\'objecte|Tiene el agujero para el objeto' }, { k: 'wall', min: 1.2, t: 'Cap paret de menys de 1,2 mm|Ninguna pared de menos de 1,2 mm' }, { k: 'onplate' }],
          sol: 'd = 7.5\ntol = 0.2\nresta {\n  cilindre(d + 2 * tol + 4, 20)\n  mou(0, 0, 3) cilindre(d + 2 * tol, 20)\n}' },
        { k: 'quiz', ph: 'tanca', q: 'Per què un forat imprès surt una mica més petit que al disseny?|¿Por qué un agujero impreso sale un poco más pequeño que en el diseño?', opts: ["Perquè el plàstic s'aixafa en sortir i s'encongeix en refredar-se|Porque el plástico se aplasta al salir y encoge al enfriarse", "Perquè la impressora s'equivoca de números|Porque la impresora se equivoca de números", 'Perquè el programa arrodoneix les mides|Porque el programa redondea las medidas'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Vols que una roda giri lliure al seu eix. Quina tolerància hi poses?|Quieres que una rueda gire libre en su eje. ¿Qué tolerancia le pones?', opts: ['Uns 0,4 mm|Unos 0,4 mm', '0 mm|0 mm', '5 mm|5 mm'], a: 0,
          ex: "Amb 0 no hi entraria; amb 5 mm ballaria tant que no seria una roda!|¡Con 0 no entraría; con 5 mm bailaría tanto que no sería una rueda!" },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* =================================== Sessió 3 · Voladissos i suports =================================== */
    { id: 'p7-3', t: 'Voladissos i suports|Voladizos y soportes', min: 45,
      learn: ["La impressora fa capes i cada capa necessita la de sota: fins a uns 45° respecte de la vertical, la capa nova es recolza prou en l'anterior.|La impresora hace capas y cada capa necesita la de debajo: hasta unos 45° respecto de la vertical, la capa nueva se apoya lo suficiente en la anterior.",
        "Els voladissos més inclinats necessiten suports: és millor evitar-los amb xamfrans a 45°, forats en rombe o ponts curts.|Los voladizos más inclinados necesitan soportes: es mejor evitarlos con chaflanes a 45°, agujeros en rombo o puentes cortos.",
        "Orientar bé la peça a la placa, amb la cara plana més gran a baix, estalvia suports i dona una base estable.|Orientar bien la pieza en la placa, con la cara plana más grande abajo, ahorra soportes y da una base estable."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Un eix fa 6 mm i <code>tol = 0.3</code>. Quant fa el forat?|Un eje mide 6 mm y <code>tol = 0.3</code>. ¿Cuánto mide el agujero?', opts: ['6,6 mm|6,6 mm', '6,3 mm|6,3 mm', '5,4 mm|5,4 mm'], a: 0 },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: 'Un niu de fils|Un nido de hilos',
          t: "La Marta, una veïna, ens va encarregar un <b>penjador de claus</b>. La Nuvi l'ha imprès dret… i el braç ha sortit com un <b>niu de fils de plàstic</b>! El braç quedava a l'aire: la impressora posava plàstic on no hi havia res a sota. Avui aprendrem a dissenyar peces que la Nuvi pugui imprimir <b>sense ajuda</b>: els enginyers en diuen <b>dissenyar per fabricar</b>.|Marta, una vecina, nos encargó un <b>colgador de llaves</b>. Nuvi lo ha impreso de pie… ¡y el brazo ha salido como un <b>nido de hilos de plástico</b>! El brazo quedaba en el aire: la impresora ponía plástico donde no había nada debajo. Hoy aprenderemos a diseñar piezas que Nuvi pueda imprimir <b>sin ayuda</b>: los ingenieros lo llaman <b>diseñar para fabricar</b>." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Capa a capa|Capa a capa', t: 'Cada capa necessita la de sota|Cada capa necesita la de debajo', anim: 'p73layers',
            x: "La impressora fa la peça de baix a dalt, una <b>capa</b> fina rere l'altra (sovint de 0,2 mm). Cada capa s'enganxa a la de sota. Si una paret s'inclina una mica, cada capa sobresurt poc i encara es recolza en l'anterior. Si s'inclina massa, la capa nova queda a l'aire i cau: és un <b>voladís</b>.|La impresora hace la pieza de abajo arriba, una <b>capa</b> fina tras otra (a menudo de 0,2 mm). Cada capa se pega a la de debajo. Si una pared se inclina un poco, cada capa sobresale poco y todavía se apoya en la anterior. Si se inclina demasiado, la capa nueva queda en el aire y cae: es un <b>voladizo</b>." },
          { k: 'La regla dels 45°|La regla de los 45°', t: 'Fins on es pot inclinar una paret|Hasta dónde se puede inclinar una pared', anim: 'p73rule',
            x: "Com a regla pràctica, una paret s'imprimeix bé sense ajuda si no s'inclina més de <b>45°</b> respecte de la vertical. Per això una lletra <b>Y</b>, amb els braços inclinats, s'imprimeix dreta sense problemes, i una <b>T</b>, amb els braços horitzontals, no.|Como regla práctica, una pared se imprime bien sin ayuda si no se inclina más de <b>45°</b> respecto de la vertical. Por eso una letra <b>Y</b>, con los brazos inclinados, se imprime de pie sin problemas, y una <b>T</b>, con los brazos horizontales, no.",
            tip: "Depèn de la impressora, del plàstic i del ventilador: algunes van una mica més enllà, però 45° és un límit segur.|Depende de la impresora, del plástico y del ventilador: algunas llegan un poco más allá, pero 45° es un límite seguro." },
          { k: 'El xamfrà|El chaflán', t: 'Un tall a 45° en lloc d\'un voladís|Un corte a 45° en lugar de un voladizo', media: { k: 'model', prog: MUSH2 },
            x: "Al bolet de l'esquerra, el barret penja a l'aire a 90°. Al de la dreta, un <code>con(10, 10, 30)</code> fa de <b>xamfrà</b>: s'eixampla 10 mm de radi en 10 mm d'alçada, és a dir, a 45°. Sota el barret ja no hi ha res a l'aire.|En la seta de la izquierda, el sombrero cuelga en el aire a 90°. En la de la derecha, un <code>cono(10, 10, 30)</code> hace de <b>chaflán</b>: se ensancha 10 mm de radio en 10 mm de altura, es decir, a 45°. Bajo el sombrero ya no hay nada en el aire.",
            bad: 'Voladís a 90°: la impressora fa fils al buit.|Voladizo a 90°: la impresora hace hilos en el vacío.', good: 'Xamfrà a 45°: cada capa es recolza en la de sota.|Chaflán a 45°: cada capa se apoya en la de debajo.' },
          { k: 'Ponts|Puentes', t: "D'un suport a l'altre|De un soporte al otro", media: { k: 'model', prog: BRIDGE },
            x: "Un tram horitzontal que va d'un suport a un altre és un <b>pont</b>. La impressora estira el fil d'una columna a l'altra, com una corda, i el ventilador el refreda de seguida. Els <b>ponts curts</b> surten bé; si són molt llargs, el fil es despenja pel mig.|Un tramo horizontal que va de un soporte a otro es un <b>puente</b>. La impresora estira el hilo de una columna a la otra, como una cuerda, y el ventilador lo enfría enseguida. Los <b>puentes cortos</b> salen bien; si son muy largos, el hilo se descuelga por el medio." },
          { k: 'Orientació i suports|Orientación y soportes', t: 'Com poses la peça a la placa|Cómo pones la pieza en la placa', media: { k: 'model', prog: STAMP2 },
            x: "El mateix segell, de dues maneres: a l'esquerra, la placa queda a dalt i tota la vora és un voladís; a la dreta, amb <code>gira(180, 0, 0)</code>, la <b>cara plana més gran</b> és a baix i no cal res més. Si un voladís no es pot evitar, el programa de laminar pot afegir <b>suports</b>: bastides que després s'arrenquen, però gasten plàstic i temps i deixen marques.|El mismo sello, de dos maneras: a la izquierda, la placa queda arriba y todo el borde es un voladizo; a la derecha, con <code>gira(180, 0, 0)</code>, la <b>cara plana más grande</b> está abajo y no hace falta nada más. Si un voladizo no se puede evitar, el programa de laminar puede añadir <b>soportes</b>: andamios que después se arrancan, pero gastan plástico y tiempo y dejan marcas.",
            tip: "Les peces impreses són més fluixes entre capes, com un full de pasta de full: si una peça ha d'aguantar força, pensa també cap a on van les capes.|Las piezas impresas son más flojas entre capas, como una hoja de hojaldre: si una pieza tiene que aguantar fuerza, piensa también hacia dónde van las capas." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🧱', title: 'Capes de plastilina|Capas de plastilina', t: 'Per grups de tres, amb plastilina:|Por grupos de tres, con plastilina:',
          steps: ['Feu 14 xurros de plastilina del mateix gruix, com si fossin el fil de la impressora.|Haced 14 churros de plastilina del mismo grosor, como si fueran el hilo de la impresora.',
            "Construïu tres parets de 4 xurros: una de dreta, una que s'inclini una mica a cada capa (uns 45°) i una altra en què cada xurro surti molt més enfora que el de sota.|Construid tres paredes de 4 churros: una recta, una que se incline un poco en cada capa (unos 45°) y otra en la que cada churro salga mucho más afuera que el de debajo.",
            'Feu dues torres separades un pam i poseu-hi un xurro a sobre que vagi d\'una a l\'altra: és un pont! Què passa si les torres són més lluny?|Haced dos torres separadas un palmo y poned encima un churro que vaya de una a otra: ¡es un puente! ¿Qué pasa si las torres están más lejos?'],
          tip: 'Quina paret ha caigut? A quina capa? Això és un voladís.|¿Qué pared se ha caído? ¿En qué capa? Eso es un voladizo.' },
        { k: 'm3predict', ph: 'prova', q: 'Què fa <code>gira(180, 0, 0)</code> al segell? <b>Quin model surt?</b>|¿Qué hace <code>gira(180, 0, 0)</code> al sello? <b>¿Qué modelo sale?</b>', prog: STAMP,
          opts: [{ prog: STAMP }, { prog: STAMP0 }, { prog: 'gira(180, 0, 0) {\n  cilindre(12, 25)\n  mou(-20, -20, 25) cub(40, 40, 4)\n}' }, { prog: 'mou(0, 0, 20) gira(90, 0, 0) {\n  cilindre(12, 25)\n  mou(-20, -20, 25) cub(40, 40, 4)\n}' }], a: 0,
          ex: "gira(180, 0, 0) posa la peça de cap per avall (sota la placa) i mou(0, 0, 29) la torna a pujar: ara la placa del segell és a baix, ben recolzada, i el mànec queda a dalt.|gira(180, 0, 0) pone la pieza boca abajo (bajo la placa) y mueve(0, 0, 29) la vuelve a subir: ahora la placa del sello está abajo, bien apoyada, y el mango queda arriba." },
        { k: 'm3spot', ph: 'investiga', q: "En Bit ha posat un xamfrà sota el barret del bolet, però la peça encara té un voladís. Toca la instrucció equivocada.|Bit ha puesto un chaflán bajo el sombrero de la seta, pero la pieza todavía tiene un voladizo. Toca la instrucción equivocada.",
          prog: 'cilindre(10, 20)\nmou(0, 0, 10) con(30, 10, 10)!\nmou(0, 0, 20) cilindre(30, 5)', target: MUSH,
          ex: 'Aquest con és ample a baix i estret a dalt: el barret continua a l\'aire. Ha de ser al revés, con(10, 10, 30): estret a baix i ample a dalt.|Este cono es ancho abajo y estrecho arriba: el sombrero sigue en el aire. Tiene que ser al revés, cono(10, 10, 30): estrecho abajo y ancho arriba.' },
        { k: 'quiz', ph: 'investiga', q: "Quina d'aquestes lletres es pot imprimir <b>dreta</b> sense suports?|¿Cuál de estas letras se puede imprimir <b>de pie</b> sin soportes?", opts: ['La Y, amb els braços que pugen a 45°|La Y, con los brazos que suben a 45°', 'La T|La T', 'La F|La F'], a: 0,
          ex: "La T i la F tenen trams horitzontals que surten a l'aire. Els braços de la Y s'inclinen 45° i cada capa es recolza en l'anterior.|La T y la F tienen tramos horizontales que salen al aire. Los brazos de la Y se inclinan 45° y cada capa se apoya en la anterior." },
        { k: 'move', ph: 'pausa', title: 'Ets una impressora|Eres una impresora', secs: 30, t: "Ajup-te i ves pujant a poc a poc, <b>capa a capa</b>, amb els braços enganxats al cos. Ara obre un braç inclinat cap amunt, a 45°: aguanta! Ara posa'l horitzontal… i deixa'l caure, com un fil sense suport!|Agáchate y ve subiendo poco a poco, <b>capa a capa</b>, con los brazos pegados al cuerpo. Ahora abre un brazo inclinado hacia arriba, a 45°: ¡aguanta! Ahora ponlo horizontal… ¡y déjalo caer, como un hilo sin soporte!" },
        { k: 'm3code', ph: 'repte', text: true, q: "Treu el voladís del bolet: posa un <b>xamfrà a 45°</b> sota el barret. És un <code>con(10, 10, 30)</code> que va de z = 10 a z = 20: estret a baix i ample a dalt.|Quita el voladizo de la seta: pon un <b>chaflán a 45°</b> bajo el sombrero. Es un <code>cono(10, 10, 30)</code> que va de z = 10 a z = 20: estrecho abajo y ancho arriba.",
          start: MUSH90, blocks: ['cil', 'con', 'mou', 'uneix'], target: MUSH,
          checks: [{ k: 'match', target: MUSH, th: 0.9, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'part', t: 'cone', s: [30, 30, 10], at: [0, 0, 15], tol: 0.3, txt: 'Hi ha el xamfrà de 30 mm, de z = 10 a z = 20|Está el chaflán de 30 mm, de z = 10 a z = 20' }, { k: 'one' }, { k: 'onplate' }],
          hint: 'Afegeix mou(0, 0, 10) con(10, 10, 30): el primer número és el diàmetre de baix (com el peu) i l\'últim, el de dalt (com el barret).|Añade mueve(0, 0, 10) cono(10, 10, 30): el primer número es el diámetro de abajo (como el pie) y el último, el de arriba (como el sombrero).',
          sol: MUSH },
        { k: 'm3code', ph: 'repte', text: true, q: "El <b>segell</b> està de cap per amunt: la placa queda a dalt i tota la vora és un voladís. Gira'l perquè la cara plana del segell quedi <b>a baix</b>, sobre la placa d'impressió.|El <b>sello</b> está boca arriba: la placa queda arriba y todo el borde es un voladizo. Gíralo para que la cara plana del sello quede <b>abajo</b>, sobre la placa de impresión.",
          start: STAMP0, blocks: ['cil', 'cub', 'mou', 'gira', 'uneix'],
          checks: [{ k: 'flatbase', min: 1500, t: 'La cara plana del segell és a baix (1.600 mm²)|La cara plana del sello está abajo (1.600 mm²)' }, { k: 'onplate' }, { k: 'one' }, { k: 'size', ax: 'z', v: 29, t: "Continua fent 29 mm d'alçada|Sigue midiendo 29 mm de altura" }],
          hint: "Posa-ho tot dins de gira(180, 0, 0) { … } (queda sota la placa) i, davant, mou(0, 0, 29) per tornar-lo a pujar. També pots reescriure'l: primer la placa a z = 0 i el mànec a sobre.|Ponlo todo dentro de gira(180, 0, 0) { … } (queda bajo la placa) y, delante, mueve(0, 0, 29) para volver a subirlo. También puedes reescribirlo: primero la placa en z = 0 y el mango encima.",
          sol: STAMP },
        { k: 'm3code', ph: 'repte', text: true, q: "El <b>penjador de la Marta</b>: dret, el braç i la punta queden a l'aire. Si l'imprimeixes <b>estirat de costat</b>, el perfil en forma de J queda sobre la placa i no hi ha cap voladís. Gira'l perquè faci com a molt 20 mm d'alçada.|El <b>colgador de Marta</b>: de pie, el brazo y la punta quedan en el aire. Si lo imprimes <b>tumbado de lado</b>, el perfil en forma de J queda sobre la placa y no hay ningún voladizo. Gíralo para que mida como mucho 20 mm de altura.",
          start: HOOK0, blocks: ['cub', 'mou', 'gira', 'uneix'],
          checks: [{ k: 'zmax', v: 20, t: 'Estirat: com a molt 20 mm d\'alçada|Tumbado: como mucho 20 mm de altura' }, { k: 'onplate' }, { k: 'one' }, { k: 'flatbase', min: 400, t: 'Tot el perfil recolzat a la placa|Todo el perfil apoyado en la placa' }],
          hint: "Posa les tres peces dins de gira(90, 0, 0) { … }: el gir al voltant de l'eix x tomba la peça i la fondària (y, 20 mm) passa a ser l'alçada.|Pon las tres piezas dentro de gira(90, 0, 0) { … }: el giro alrededor del eje x tumba la pieza y el fondo (y, 20 mm) pasa a ser la altura.",
          sol: HOOK },
        { k: 'm3code', ph: 'repte', text: true, q: "Aquest suport té un <b>forat horitzontal rodó</b> per passar-hi un cable: el seu sostre és pla i es despenja. Canvia'l per un <b>forat en rombe</b>, un <code>cub(8, 22, 8, centrat)</code> girat 45°: el sostre queda a 45° i s'imprimeix sol.|Este soporte tiene un <b>agujero horizontal redondo</b> para pasar un cable: su techo es plano y se descuelga. Cámbialo por un <b>agujero en rombo</b>, un <code>cubo(8, 22, 8, centrado)</code> girado 45°: el techo queda a 45° y se imprime solo.",
          start: ROUND, blocks: ['cub', 'cil', 'mou', 'gira', 'resta'],
          checks: [{ k: 'part', t: 'box', hole: true, s: [11.31, 22, 11.31], tol: 0.2, txt: 'Hi ha el forat en rombe (8 × 8 girat 45°)|Está el agujero en rombo (8 × 8 girado 45°)' }, { k: 'count', t: 'cyl', hole: true, max: 0, txt: 'Ja no hi ha el forat rodó|Ya no está el agujero redondo' }, { k: 'hole' }, { k: 'one' }],
          hint: "Dins de la resta, canvia la línia del cilindre per mou(20, 10, 10) gira(0, 45, 0) cub(8, 22, 8, centrat): centrat perquè giri al voltant del seu centre; després el mou el porta al mig del bloc.|Dentro de la resta, cambia la línea del cilindro por mueve(20, 10, 10) gira(0, 45, 0) cubo(8, 22, 8, centrado): centrado para que gire alrededor de su centro; después el mueve lo lleva al centro del bloque.",
          sol: DIAM },
        { k: 'm3free', ph: 'crea', text: true, q: "<b>Una peça que la Nuvi pot imprimir sola.</b> Dissenya un objecte útil (un penjador, un suport d'auriculars, un ganxo per a la motxilla…) que <b>no necessiti suports</b>: xamfrans a 45°, forats en rombe, ponts curts i la cara plana més gran a baix.|<b>Una pieza que Nuvi puede imprimir sola.</b> Diseña un objeto útil (un colgador, un soporte de auriculares, un gancho para la mochila…) que <b>no necesite soportes</b>: chaflanes a 45°, agujeros en rombo, puentes cortos y la cara plana más grande abajo.",
          name: 'La meva peça sense suports|Mi pieza sin soportes', blocks: ['cub', 'cil', 'con', 'falca', 'mou', 'gira', 'resta', 'uneix', 'var', 'color'],
          crit: ['Cap voladís de més de 45° (fes servir xamfrans, rombes o ponts curts)|Ningún voladizo de más de 45° (usa chaflanes, rombos o puentes cortos)', 'La cara plana més gran és a baix, sobre la placa|La cara plana más grande está abajo, sobre la placa', 'És una sola peça, amb parets d\'almenys 1,2 mm|Es una sola pieza, con paredes de al menos 1,2 mm'],
          checks: [{ k: 'onplate' }, { k: 'one' }, { k: 'flatbase', min: 300, t: 'Té una base plana d\'almenys 300 mm²|Tiene una base plana de al menos 300 mm²' }, { k: 'wall', min: 1.2, t: 'Cap paret de menys de 1,2 mm|Ninguna pared de menos de 1,2 mm' }],
          sol: HOOK },
        { k: 'quiz', ph: 'tanca', q: 'Fins a quin angle, respecte de la vertical, se sol poder imprimir una paret sense suports?|¿Hasta qué ángulo, respecto de la vertical, se suele poder imprimir una pared sin soportes?', opts: ['Uns 45°|Unos 45°', '90°: horitzontal del tot|90°: horizontal del todo', 'Només 5°|Solo 5°'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Com poses a la placa un segell que té el mànec a sobre de la placa?|¿Cómo pones en la placa un sello que tiene el mango encima de la placa?', opts: ['Amb la cara plana del segell a baix i el mànec cap amunt|Con la cara plana del sello abajo y el mango hacia arriba', 'Amb el mànec a baix i la placa a dalt|Con el mango abajo y la placa arriba', 'Igual, la impressora ja ho arreglarà|Igual, la impresora ya lo arreglará'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* =================================== Sessió 4 · Projecte: la frontissa =================================== */
    { id: 'p7-4', t: 'Projecte: la frontissa|Proyecto: la bisagra', min: 45, proj: true, badge: 'p74_frontissa',
      learn: ["Una frontissa desmuntable té dues peces: la A, amb el passador, i la B, amb un forat que gira al voltant del passador.|Una bisagra desmontable tiene dos piezas: la A, con el pasador, y la B, con un agujero que gira alrededor del pasador.",
        "El forat fa passador + 2 × tol, i la paret del voltant ha de fer almenys 1,2 mm amb qualsevol tolerància.|El agujero mide pasador + 2 × tol, y la pared de alrededor tiene que medir al menos 1,2 mm con cualquier tolerancia.",
        "Les dues peces s'imprimeixen dretes, sense suports, i un sol programa amb variables i mòduls les fa a mida.|Las dos piezas se imprimen de pie, sin soportes, y un solo programa con variables y módulos las hace a medida."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "Un forat horitzontal rodó i molt gran té el sostre pla a dalt. Quin problema pot tenir en imprimir-lo?|Un agujero horizontal redondo y muy grande tiene el techo plano arriba. ¿Qué problema puede tener al imprimirlo?", opts: ["El sostre es pot despenjar: és un voladís|El techo se puede descolgar: es un voladizo", 'Cap: els forats sempre surten perfectes|Ninguno: los agujeros siempre salen perfectos', 'Que el forat surt quadrat|Que el agujero sale cuadrado'], a: 0 },
        { k: 'quiz', ph: 'recorda', q: 'Per a un eix de 5 mm amb <code>tol = 0.3</code>, quin forat fas?|Para un eje de 5 mm con <code>tol = 0.3</code>, ¿qué agujero haces?', opts: ['5,6 mm|5,6 mm', '5,3 mm|5,3 mm', '5 mm justos|5 mm justos'], a: 0 },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: "L'encàrrec del museu|El encargo del museo",
          t: "El <b>museu del barri</b> prepara unes vitrines petites amb una tapa que s'obre per ensenyar minerals. Necessiten <b>frontisses de plàstic</b>… i les volen a mida: unes per a tapes primes i unes altres per a tapes gruixudes. Projecte de la unitat: una <b>frontissa de dues peces</b>, amb <b>tolerància paramètrica</b>, que la Nuvi pugui imprimir <b>sense suports</b>. Tot el que hem après, en una sola peça d'enginyeria!|El <b>museo del barrio</b> prepara unas vitrinas pequeñas con una tapa que se abre para enseñar minerales. Necesitan <b>bisagras de plástico</b>… y las quieren a medida: unas para tapas finas y otras para tapas gruesas. Proyecto de la unidad: una <b>bisagra de dos piezas</b>, con <b>tolerancia paramétrica</b>, que Nuvi pueda imprimir <b>sin soportes</b>. ¡Todo lo que hemos aprendido, en una sola pieza de ingeniería!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'La frontissa|La bisagra', t: 'Dues peces i un passador|Dos piezas y un pasador', anim: 'p74hinge',
            x: "Una frontissa té dues <b>ales</b> (les plaques que es cargolen a la tapa i a la caixa) i un <b>cilindre</b> on gira. La nostra és <b>desmuntable</b>, com les de moltes portes: la peça <b>A</b> té un <b>passador</b> (un eix) a dalt i la peça <b>B</b> té un forat a baix. B es posa a sobre d'A i gira al voltant del passador.|Una bisagra tiene dos <b>alas</b> (las placas que se atornillan a la tapa y a la caja) y un <b>cilindro</b> donde gira. La nuestra es <b>desmontable</b>, como las de muchas puertas: la pieza <b>A</b> tiene un <b>pasador</b> (un eje) arriba y la pieza <b>B</b> tiene un agujero abajo. B se pone encima de A y gira alrededor del pasador." },
          { k: 'Peça A|Pieza A', t: "L'ala, el cilindre i el passador|El ala, el cilindro y el pasador", media: { k: 'model', prog: A1 },
            x: "La peça A és una ala (<code>cub</code> de 30 × 3 × h), un cilindre de diàmetre <code>diam</code> i, a sobre, el <b>passador</b> de 5 mm i 10 d'alçada. Totes les mides surten de quatre variables al principi del programa.|La pieza A es un ala (<code>cubo</code> de 30 × 3 × h), un cilindro de diámetro <code>diam</code> y, encima, el <b>pasador</b> de 5 mm y 10 de altura. Todas las medidas salen de cuatro variables al principio del programa." },
          { k: 'Peça B|Pieza B', t: 'El forat, a sota|El agujero, debajo', media: { k: 'model', prog: B1 },
            x: "La peça B té l'ala cap a l'altre costat i un forat que comença per sota (z = −1). El forat fa <code>passador + 2 * tol</code> i és <b>més fondo que el passador</b> (12 mm per a un passador de 10): així B es recolza sobre el cilindre d'A i no sobre la punta del passador.|La pieza B tiene el ala hacia el otro lado y un agujero que empieza por debajo (z = −1). El agujero mide <code>pasador + 2 * tol</code> y es <b>más hondo que el pasador</b> (12 mm para un pasador de 10): así B se apoya sobre el cilindro de A y no sobre la punta del pasador." },
          { k: 'Muntada|Montada', t: 'B a sobre d\'A, oberta 120°|B encima de A, abierta 120°', media: { k: 'model', prog: HMNT },
            x: "Muntada, la peça B queda a sobre de la A i gira al voltant del passador. Aquí la mostrem girada 120° amb <code>gira(0, 0, 120)</code>: així s'obriria la tapa de la vitrina. Les dues peces són <b>mòduls</b>, i per això les podem fer servir per imprimir-les i també per veure-les muntades.|Montada, la pieza B queda encima de la A y gira alrededor del pasador. Aquí la mostramos girada 120° con <code>gira(0, 0, 120)</code>: así se abriría la tapa de la vitrina. Las dos piezas son <b>módulos</b>, y por eso podemos usarlas para imprimirlas y también para verlas montadas." },
          { k: 'Fabricar-la bé|Fabricarla bien', t: 'Dretes, sense suports i amb parets segures|De pie, sin soportes y con paredes seguras', media: { k: 'model', prog: HTWO },
            x: "Les dues peces s'imprimeixen <b>dretes</b>, una al costat de l'altra: no hi ha voladissos i el forat de B comença a la placa (el seu sostre és un pont curtíssim). El passador, imprès dret, és més fluix entre capes: per això no el fem més prim de 5 mm. I la paret del cilindre al voltant del forat ha de fer almenys <b>1,2 mm</b>.|Las dos piezas se imprimen <b>de pie</b>, una al lado de la otra: no hay voladizos y el agujero de B empieza en la placa (su techo es un puente cortísimo). El pasador, impreso de pie, es más flojo entre capas: por eso no lo hacemos más fino de 5 mm. Y la pared del cilindro alrededor del agujero tiene que medir al menos <b>1,2 mm</b>.",
            tip: "Amb tol = 0.4, un passador de 5 mm i un cilindre de 10, la paret fa (10 − 5,8) ÷ 2 = 2,1 mm. Bé!|Con tol = 0.4, un pasador de 5 mm y un cilindro de 10, la pared mide (10 − 5,8) ÷ 2 = 2,1 mm. ¡Bien!" }
        ] },
        { k: 'unplug', ph: 'mans', ico: '✂️', title: 'La frontissa de cartolina|La bisagra de cartulina', t: 'Per parelles, amb cartolina, cinta adhesiva, un llapis i dos bastonets (un de prim i un de gruixut):|Por parejas, con cartulina, cinta adhesiva, un lápiz y dos palitos (uno fino y uno grueso):',
          steps: ["Retalleu dues tires de cartolina de 8 × 4 cm: seran les ales A i B.|Recortad dos tiras de cartulina de 8 × 4 cm: serán las alas A y B.",
            "Enrotlleu un extrem de cada tira al voltant del llapis i tanqueu-lo amb cinta. Poseu el rotllo de B a sobre del d'A, amb el llapis passant pels dos.|Enrollad un extremo de cada tira alrededor del lápiz y cerradlo con cinta. Poned el rollo de B encima del de A, con el lápiz pasando por los dos.",
            "Canvieu el llapis pel bastonet prim i després pel gruixut: amb quin gira millor? Amb quin queda massa fluix o massa just?|Cambiad el lápiz por el palito fino y después por el grueso: ¿con cuál gira mejor? ¿Con cuál queda demasiado flojo o demasiado justo?"],
          tip: 'El rotllo és el cilindre, el bastonet és el passador i la diferència de gruix és la tolerància.|El rollo es el cilindro, el palito es el pasador y la diferencia de grosor es la tolerancia.' },
        { k: 'm3predict', ph: 'prova', q: 'Llegeix la peça B. <b>On queda el forat?</b>|Lee la pieza B. <b>¿Dónde queda el agujero?</b>', prog: B1,
          opts: [{ prog: B1 }, { prog: BTHRU }, { prog: BTOP }, { prog: B0 }], a: 0,
          ex: "El forat comença a z = −1 i fa 12 mm: obre la cara de baix i arriba fins a z = 11. Per aquí entrarà el passador de la peça A.|El agujero empieza en z = −1 y mide 12 mm: abre la cara de abajo y llega hasta z = 11. Por aquí entrará el pasador de la pieza A." },
        { k: 'm3spot', ph: 'investiga', q: "Aquesta peça B s'ha imprès i <b>no entra</b> al passador. Toca la instrucció equivocada.|Esta pieza B se ha impreso y <b>no entra</b> en el pasador. Toca la instrucción equivocada.", prog: BBAD, target: B1,
          ex: "El forat fa exactament el que el passador: sense tolerància, en imprimir-lo sortirà més petit i no hi entrarà. Ha de ser passador + 2 * tol.|El agujero mide exactamente lo que el pasador: sin tolerancia, al imprimirlo saldrá más pequeño y no entrará. Tiene que ser pasador + 2 * tol." },
        { k: 'move', ph: 'pausa', title: 'La frontissa humana|La bisagra humana', secs: 30, t: "Per parelles, doneu-vos la mà: és el passador. Un és la peça <b>A</b> i es queda quiet; l'altre és la peça <b>B</b> i gira al seu voltant, a poc a poc, sense deixar anar la mà. Ara canvieu!|Por parejas, daos la mano: es el pasador. Uno es la pieza <b>A</b> y se queda quieto; el otro es la pieza <b>B</b> y gira a su alrededor, despacio, sin soltar la mano. ¡Ahora cambiad!" },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Peça A.</b> Ja tens l'ala i el cilindre. Posa-hi a sobre el <b>passador</b>: un cilindre de diàmetre <code>passador</code> i 10 mm d'alçada que comença on acaba el cilindre (z = h).|<b>Pieza A.</b> Ya tienes el ala y el cilindro. Ponle encima el <b>pasador</b>: un cilindro de diámetro <code>pasador</code> y 10 mm de altura que empieza donde acaba el cilindro (z = h).",
          start: A0, blocks: ['var', 'cub', 'cil', 'mou', 'uneix', 'rem'], target: A1,
          checks: [{ k: 'part', t: 'cyl', hole: false, s: [5, 5, 10], at: [0, 0, 25], tol: 0.05, txt: 'El passador fa 5 × 10 mm, a sobre del cilindre|El pasador mide 5 × 10 mm, encima del cilindro' }, { k: 'one' }, { k: 'onplate' }, { k: 'size', ax: 'z', v: 30, t: 'Fa 30 mm d\'alçada en total|Mide 30 mm de altura en total' }],
          hint: 'Afegeix mou(0, 0, h) cilindre(passador, 10).|Añade mueve(0, 0, h) cilindro(pasador, 10).', sol: A1 },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Peça B.</b> Fes-li el forat per al passador, des de sota: un cilindre de <code>passador + 2 * tol</code> que comença a z = −1 i fa 12 mm. Ha de funcionar amb qualsevol tolerància entre 0,2 i 0,4.|<b>Pieza B.</b> Hazle el agujero para el pasador, desde abajo: un cilindro de <code>pasador + 2 * tol</code> que empieza en z = −1 y mide 12 mm. Tiene que funcionar con cualquier tolerancia entre 0,2 y 0,4.",
          start: B0, blocks: ['var', 'cub', 'cil', 'mou', 'uneix', 'resta', 'rem'], target: B1,
          checks: [{ k: 'part', t: 'cyl', hole: true, s: ['5 + 2*tol', '5 + 2*tol', 12], at: [0, 0, 5], tol: 0.05, txt: 'Forat de passador + 2 × tol, des de sota|Agujero de pasador + 2 × tol, desde abajo' }, { k: 'one' }, { k: 'wall', min: 1.2, t: 'Paret de 1,2 mm com a mínim|Pared de 1,2 mm como mínimo' }, { k: 'param', v: 'tol', vals: [0.2, 0.4], t: 'Funciona amb tol = 0,2 i 0,4|Funciona con tol = 0,2 y 0,4' }],
          hint: "Canvia uneix { … } per resta { uneix { … } mou(0, 0, -1) cilindre(passador + 2 * tol, 12) }: el primer de la resta és la peça; el segon, el forat.|Cambia une { … } por resta { une { … } mueve(0, 0, -1) cilindro(pasador + 2 * tol, 12) }: el primero de la resta es la pieza; el segundo, el agujero.",
          sol: B1 },
        { k: 'm3code', ph: 'repte', text: true, q: "El museu vol la frontissa <b>més prima</b>: com a molt <b>9 mm</b> de gruix. Algú ha posat <code>diam = 7</code>, però amb <code>tol = 0.4</code> la paret al voltant del forat queda massa fina. Tria el diàmetre més prim que respecti els 9 mm i deixi almenys 1,2 mm de paret.|El museo quiere la bisagra <b>más fina</b>: como mucho <b>9 mm</b> de grosor. Alguien ha puesto <code>diam = 7</code>, pero con <code>tol = 0.4</code> la pared alrededor del agujero queda demasiado fina. Elige el diámetro más fino que respete los 9 mm y deje al menos 1,2 mm de pared.",
          start: B7, blocks: ['var', 'cub', 'cil', 'mou', 'uneix', 'resta', 'rem'],
          checks: [{ k: 'fit', box: [36, 9, 20], t: 'Com a molt 9 mm de gruix|Como mucho 9 mm de grosor' }, { k: 'wall', min: 1.2, t: 'Paret de 1,2 mm com a mínim|Pared de 1,2 mm como mínimo' }, { k: 'param', v: 'tol', vals: [0.2, 0.4], t: 'Funciona amb tol = 0,2 i 0,4|Funciona con tol = 0,2 y 0,4' }, { k: 'one' }],
          hint: "El forat més gran fa 5 + 2 × 0,4 = 5,8 mm. Amb 1,2 mm de paret a cada costat: 5,8 + 2,4 = 8,2 mm. Qualsevol diam entre 8,4 i 9 compleix les dues coses.|El agujero más grande mide 5 + 2 × 0,4 = 5,8 mm. Con 1,2 mm de pared a cada lado: 5,8 + 2,4 = 8,2 mm. Cualquier diam entre 8,4 y 9 cumple las dos cosas.",
          sol: B9 },
        { k: 'm3code', ph: 'repte', text: true, q: "Les dues peces ja són <b>mòduls</b>, però el programa només fa la A. Afegeix la <b>B</b> 40 mm a la dreta, perquè les dues s'imprimeixin juntes sense tocar-se.|Las dos piezas ya son <b>módulos</b>, pero el programa solo hace la A. Añade la <b>B</b> 40 mm a la derecha, para que las dos se impriman juntas sin tocarse.",
          start: HONE, blocks: ['var', 'cub', 'cil', 'mou', 'gira', 'uneix', 'resta', 'def', 'call', 'rem'],
          checks: [{ k: 'size', ax: 'x', v: 100, tol: 1, t: 'Les dues peces a la placa: 100 mm en total|Las dos piezas en la placa: 100 mm en total' }, { k: 'count', t: 'cyl', hole: false, min: 3, txt: 'Cilindre d\'A, passador i cilindre de B|Cilindro de A, pasador y cilindro de B' }, { k: 'count', t: 'cyl', hole: true, min: 1, txt: 'El forat de la peça B|El agujero de la pieza B' }, { k: 'uses', b: 'call' }, { k: 'onplate' }],
          hint: 'Afegeix al final mou(40, 0, 0) pecaB().|Añade al final mueve(40, 0, 0) piezaB().', sol: HTWO },
        { k: 'm3free', ph: 'crea', text: true, q: "<b>La teva frontissa per al museu.</b> Parteix del programa de les dues peces i fes-la teva: canvia les mides de les ales, afegeix-hi forats per als cargols (millor en rombe, si són horitzontals!), dona-li una forma especial… Que continuï sent paramètrica i que s'imprimeixi sense suports.|<b>Tu bisagra para el museo.</b> Parte del programa de las dos piezas y hazla tuya: cambia las medidas de las alas, añádele agujeros para los tornillos (¡mejor en rombo, si son horizontales!), dale una forma especial… Que siga siendo paramétrica y que se imprima sin soportes.",
          name: 'La meva frontissa|Mi bisagra', start: HTWO, blocks: ['var', 'cub', 'cil', 'con', 'falca', 'mou', 'gira', 'uneix', 'resta', 'def', 'call', 'color', 'rem'],
          crit: ["Les peces A i B, una al costat de l'altra a la placa|Las piezas A y B, una al lado de la otra en la placa", 'El forat fa passador + 2 × tol i tol és una variable|El agujero mide pasador + 2 × tol y tol es una variable', 'Cap paret de menys de 1,2 mm i cap voladís de més de 45°|Ninguna pared de menos de 1,2 mm y ningún voladizo de más de 45°', 'Un toc teu: forats per als cargols, una forma especial a les ales…|Un toque tuyo: agujeros para los tornillos, una forma especial en las alas…'],
          checks: [{ k: 'uses', b: 'var' }, { k: 'hole', t: 'La peça B té el forat|La pieza B tiene el agujero' }, { k: 'count', t: 'cyl', hole: false, min: 3, txt: 'Cilindres i passador|Cilindros y pasador' }, { k: 'wall', min: 1.2, t: 'Cap paret de menys de 1,2 mm|Ninguna pared de menos de 1,2 mm' }, { k: 'onplate' }, { k: 'param', v: 'tol', vals: [0.2, 0.4], t: 'Funciona amb tol = 0,2 i 0,4|Funciona con tol = 0,2 y 0,4' }],
          sol: HTWO },
        { k: 'quiz', ph: 'tanca', q: 'Per què el forat de la peça B és més fondo que el passador?|¿Por qué el agujero de la pieza B es más hondo que el pasador?', opts: ["Perquè B es recolzi sobre el cilindre d'A i no sobre la punta del passador|Para que B se apoye sobre el cilindro de A y no sobre la punta del pasador", 'Per gastar menys plàstic|Para gastar menos plástico', 'Perquè el passador creix en imprimir-lo|Porque el pasador crece al imprimirlo'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Vols fer el cilindre de la frontissa més prim. Què has de vigilar?|Quieres hacer el cilindro de la bisagra más fino. ¿Qué tienes que vigilar?', opts: ['Que la paret al voltant del forat no faci menys de 1,2 mm amb la tolerància més gran|Que la pared alrededor del agujero no mida menos de 1,2 mm con la tolerancia más grande', 'Res: com més prim, millor|Nada: cuanto más fino, mejor', 'Que tingui un color diferent|Que tenga un color distinto'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] }
  ] };
})();
