/* Tech Creadors · unitat 6 «Variables»: el marcador (punts), les vides i la fi de la partida, el compte enrere i el
   cronòmetre, i el projecte de la mascota virtual. Tot passa a la Fira de Tardor del poble, a la caseta dels videojocs.
   Nota: les comparacions principals (vides = 0, gana > 5…) arriben ja posades als programes de partida, perquè
   l'alumne/a les completi; amb «cond+» a la paleta també en pot crear de noves. */
Object.assign(TBADGE, {
  g_marcador: { id: 'g_marcador', ico: '🔢', n: 'Marcador a punt|Marcador a punto', d: 'Has creat la teva primera variable: un marcador que suma i resta punts.|Has creado tu primera variable: un marcador que suma y resta puntos.' },
  g_vides: { id: 'g_vides', ico: '❤️', n: 'Tres vides|Tres vidas', d: 'Has programat vides que baixen a cada xoc i una fi de partida que ho atura tot.|Has programado vidas que bajan en cada choque y un fin de partida que lo para todo.' },
  g_rellotge: { id: 'g_rellotge', ico: '⏱️', n: 'Contrarellotge|Contrarreloj', d: 'Has fet un compte enrere i has mesurat el temps amb el cronòmetre.|Has hecho una cuenta atrás y has medido el tiempo con el cronómetro.' },
  g_mascota: { id: 'g_mascota', ico: '🐾', n: 'Cuidador/a de mascotes|Cuidador/a de mascotas', d: 'Projecte acabat: una mascota virtual que té gana, menja i canvia de cara.|Proyecto terminado: una mascota virtual que tiene hambre, come y cambia de cara.' }
});
COURSE_UNITS[6] = (() => {
  // noms de les variables tal com es veuen a l'escenari i als blocs
  const VN = { punts: 'punts|puntos', vides: 'vides|vidas', temps: 'temps|tiempo', segons: 'segons|segundos', salts: 'salts|saltos', gana: 'gana|hambre', alegria: 'alegria|alegría' };
  // blocs dibuixats dins d'una pregunta (com a l'editor)
  const CH = (sq, sprites) => () => `<div class="sdcode">${sgDemoChips(SQ(sq), { w: { bg: 'parc', sprites }, varNames: VN })}</div>`;
  const clicks = (id, ts) => ts.map(t => ({ t, click: id }));
  const FI = 'Fi de la partida!|¡Fin de la partida!', TEMPS = "S'ha acabat el temps!|¡Se acabó el tiempo!";
  // el gat que passeja i la poma que cau (unitat 5): ara amb punts
  const GAT = { id: 'gat', art: 'gat', x: -200, y: -120, prog: '@gat flag{ forever{ move:6 bounce } }' };
  const POMA_OK = '@poma flag{ setv:punts,0 forever{ chy:-8 if:touch:gat{ chv:punts,1 sound:moneda sety:150 } if:touch:edge{ sety:150 } } }';
  const METEOR = '@meteorit flag{ forever{ chy:-6 if:touch:edge{ sety:150 } } }';
  const NAU_OK = `@nau flag{ setv:vides,3 forever{ if:touch:meteorit{ chv:vides,-1 sound:xoc wait:1 } if:$vides=0{ say:"${FI}" stop:all } } }`;
  const W_NAU = (time, extra = {}) => ({ bg: 'espai', sprites: [{ id: 'nau', art: 'nau', x: 0, y: -120 }, { id: 'meteorit', art: 'meteorit', x: 0, y: 150, prog: METEOR }], vars: ['vides'], time, ...extra });
  const GANA = '@mascota flag{ setv:gana,0 forever{ wait:1 chv:gana,1 } }';
  const PET = (prog) => [{ id: 'mascota', art: 'mascota', x: 0, y: -30, size: 130, prog }, { id: 'poma', art: 'poma', x: -170, y: -120, size: 120, name: 'Poma (menjar)|Manzana (comida)' }, { id: 'pilota', art: 'pilota', x: 170, y: -120, size: 120 }];
  const PET_FULL = '@mascota flag{ setv:gana,0 forever{ wait:1 chv:gana,1 } } flag{ setv:alegria,5 forever{ wait:1.5 chv:alegria,-1 } } flag{ forever{ if:$gana>5{ costume:2 } else{ if:$alegria<3{ costume:4 } else{ costume:1 } } } } click{ say:$gana,1 } @poma click{ chv:gana,-3 sound:pop } @pilota click{ chv:alegria,2 sound:boing }';
  return { t: 'Variables|Variables', d: 'Punts, vides i temps|Puntos, vidas y tiempo', color: '#D9468F', s: [

  /* ---------- Sessió 1 · El marcador ---------- */
  { id: 'g6-1', t: 'El marcador|El marcador', min: 45, badge: 'g_marcador',
    learn: ["Una variable és una capsa amb nom que guarda un número; el número pot canviar mentre el programa funciona.|Una variable es una caja con nombre que guarda un número; el número puede cambiar mientras el programa funciona.",
      "«Posa punts a 0» canvia el número per un de nou; «suma a punts 1» n'hi afegeix 1 (i amb -1, en resta).|«Pon puntos a 0» cambia el número por uno nuevo; «suma a puntos 1» le añade 1 (y con -1, le resta).",
      "Si un personatge diu la variable, diu el número que hi ha a dins: així es mostra el marcador.|Si un personaje dice la variable, dice el número que hay dentro: así se muestra el marcador."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "Recordes la unitat 5? La poma cau amb aquest guió. <b>Què passa quan toca la cistella?</b>|¿Recuerdas la unidad 5? La manzana cae con este guion. <b>¿Qué pasa cuando toca la cesta?</b>",
        art: CH('@poma flag{ forever{ chy:-5 if:touch:cistella{ say:"Atrapada!|¡Atrapada!",1 sety:150 } } }', [{ id: 'poma', art: 'poma' }, { id: 'cistella', art: 'cistella' }]),
        opts: ["Diu «Atrapada!» i torna a dalt|Dice «¡Atrapada!» y vuelve arriba", "S'atura per sempre|Se para para siempre", "No passa res: el «si» només mira una vegada|No pasa nada: el «si» solo mira una vez"], a: 0,
        ex: "El «si» és dins del «per sempre»: a cada volta mira si toca la cistella.|El «si» está dentro del «por siempre»: en cada vuelta mira si toca la cesta." },
      { k: 'story', ph: 'missio', who: 'both', scene: 'poble', title: 'La Fira de Tardor|La Feria de Otoño',
        t: "Arriba la <b>Fira de Tardor</b> del poble! En Numi i en Bit hi muntaran una caseta amb <b>videojocs fets per vosaltres</b>. Però els videojocs que tenim tenen un problema: ningú no sap <b>quants punts ha fet</b>.|¡Llega la <b>Feria de Otoño</b> del pueblo! Numi y Bit montarán una caseta con <b>videojuegos hechos por vosotros</b>. Pero los videojuegos que tenemos tienen un problema: nadie sabe <b>cuántos puntos ha hecho</b>." },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy',
        t: "BIP! Per comptar punts, el programa ha de <b>recordar un número que va canviant</b>: 0, 1, 2, 3… Els programadors guarden aquests números en <b>variables</b>. Avui en farem la primera: el <b>marcador</b>.|¡BIP! Para contar puntos, el programa tiene que <b>recordar un número que va cambiando</b>: 0, 1, 2, 3… Los programadores guardan estos números en <b>variables</b>. Hoy haremos la primera: el <b>marcador</b>." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Variable|Variable', t: 'Una capsa amb nom|Una caja con nombre', anim: 'g6box',
          x: "Una <span class='hl'>variable</span> és com una capsa amb una etiqueta. L'etiqueta és el <b>nom</b> (per exemple, <b>punts</b>) i a dins hi ha <b>un número</b>. El número pot canviar mentre el programa funciona; el nom no canvia.|Una <span class='hl'>variable</span> es como una caja con una etiqueta. La etiqueta es el <b>nombre</b> (por ejemplo, <b>puntos</b>) y dentro hay <b>un número</b>. El número puede cambiar mientras el programa funciona; el nombre no cambia.",
          tip: "A l'escenari, a dalt a l'esquerra, hi ha el marcador: el nom de cada variable i el seu número.|En el escenario, arriba a la izquierda, está el marcador: el nombre de cada variable y su número." },
        { k: 'Posa i suma|Pon y suma', t: 'Dos blocs per canviar-la|Dos bloques para cambiarla', anim: 'g6setch',
          x: "<b>Posa punts a 0</b> hi posa un número nou, i el que hi havia s'esborra. <b>Suma a punts 1</b> afegeix 1 al que ja hi havia: el 3 passa a ser un 4. Si sumes un número negatiu, <b>restes</b>: «suma a punts -2» fa que el 5 passi a ser un 3.|<b>Pon puntos a 0</b> pone un número nuevo, y el que había se borra. <b>Suma a puntos 1</b> añade 1 al que ya había: el 3 pasa a ser un 4. Si sumas un número negativo, <b>restas</b>: «suma a puntos -2» hace que el 5 pase a ser un 3." },
        { k: "A l'escenari|En el escenario", t: 'Cada toc, un punt|Cada toque, un punto',
          media: { k: 'stage', w: { bg: 'parc', sprites: [{ id: 'moneda', art: 'moneda', x: 0, y: -10, size: 160 }], vars: ['punts'], input: clicks('moneda', [1, 2, 3, 4]) }, prog: '@moneda flag{ setv:punts,0 forever{ next wait:0.12 } } click{ chv:punts,1 sound:moneda }', varNames: VN, time: 5.5 },
          x: "Mira la demo: quan comença, posa <b>punts</b> a 0. Després, cada vegada que algú toca la moneda, el guió «Quan toco aquest personatge» hi suma 1, i el marcador de dalt s'actualitza sol.|Mira la demo: al empezar, pone <b>puntos</b> a 0. Después, cada vez que alguien toca la moneda, el guion «Al tocar este personaje» le suma 1, y el marcador de arriba se actualiza solo." },
        { k: 'Digues el número|Di el número', t: 'Un personatge que diu els punts|Un personaje que dice los puntos',
          media: { k: 'stage', w: { bg: 'nit', sprites: [{ id: 'estrella', art: 'estrella', x: 0, y: 0, size: 160 }], vars: ['punts'], input: clicks('estrella', [1, 2, 3]) }, prog: '@estrella click{ chv:punts,1 say:$punts,0.6 }', varNames: VN, time: 4.5 },
          x: "Al bloc <b>digues</b>, en lloc d'escriure un text, pots triar una variable. Llavors el personatge diu <b>el número que hi ha a dins</b> (1, 2, 3…), no la paraula «punts».|En el bloque <b>di</b>, en lugar de escribir un texto, puedes elegir una variable. Entonces el personaje dice <b>el número que hay dentro</b> (1, 2, 3…), no la palabra «puntos»." },
        { k: 'Compte!|¡Cuidado!', t: '«Posa» no és «suma»|«Pon» no es «suma»', anim: 'g6bug',
          x: "És l'error més típic: si quan toques la moneda poses «posa punts a 1», el marcador sempre dirà 1, per moltes vegades que la toquis.|Es el error más típico: si al tocar la moneda pones «pon puntos a 1», el marcador siempre dirá 1, por muchas veces que la toques.",
          bad: "Quan toco la moneda: posa punts a 1 → 1, 1, 1…|Al tocar la moneda: pon puntos a 1 → 1, 1, 1…", good: "Quan toco la moneda: suma a punts 1 → 1, 2, 3…|Al tocar la moneda: suma a puntos 1 → 1, 2, 3…" }
      ] },
      { k: 'unplug', ph: 'mans', ico: '📦', title: 'La capsa dels punts|La caja de los puntos',
        t: "Necessites algú de casa, un paper i una paperera (o una capsa). El paper serà la <b>variable</b>.|Necesitas a alguien de casa, un papel y una papelera (o una caja). El papel será la <b>variable</b>.",
        steps: ["Escriviu a dalt del paper el nom de la variable: <b>punts</b>. A sota, el número: <b>0</b>.|Escribid arriba del papel el nombre de la variable: <b>puntos</b>. Debajo, el número: <b>0</b>.",
          "Feu boles de paper i llanceu-les a la paperera. Cada vegada que una hi entra: <b>suma a punts 1</b> (ratlleu el número i escriviu el nou).|Haced bolas de papel y lanzadlas a la papelera. Cada vez que una entra: <b>suma a puntos 1</b> (tachad el número y escribid el nuevo).",
          "Si una bola cau fora, <b>suma a punts -1</b>.|Si una bola cae fuera, <b>suma a puntos -1</b>.",
          "Per començar una partida nova: <b>posa punts a 0</b>. Canvieu els papers!|Para empezar una partida nueva: <b>pon puntos a 0</b>. ¡Cambiad los papeles!"],
        tip: "Fixeu-vos que el nom «punts» no canvia mai: només canvia el número de sota.|Fijaos en que el nombre «puntos» no cambia nunca: solo cambia el número de debajo." },
      { k: 'seq', ph: 'mans', q: "Una partida a la moneda de la sort. <b>Ordena què passa</b>, del primer al darrer.|Una partida a la moneda de la suerte. <b>Ordena qué pasa</b>, del primero al último.",
        items: ["Toques la bandera verda: posa punts a 0|Tocas la bandera verde: pon puntos a 0", "Toques la moneda: suma a punts 1 → el marcador diu 1|Tocas la moneda: suma a puntos 1 → el marcador dice 1", "Toques la moneda: suma a punts 1 → el marcador diu 2|Tocas la moneda: suma a puntos 1 → el marcador dice 2", "Toques la bandera un altre cop: el marcador torna a 0|Tocas la bandera otra vez: el marcador vuelve a 0"],
        ex: "Primer es posa a 0 i després cada toc hi suma 1. En tornar a començar, el «posa a 0» esborra la partida d'abans.|Primero se pone a 0 y después cada toque le suma 1. Al volver a empezar, el «pon a 0» borra la partida de antes." },
      { k: 'quiz', ph: 'prova', q: "Pensa abans de respondre: <b>quant valdrà punts</b> quan s'acabi aquest guió?|Piensa antes de responder: <b>¿cuánto valdrá puntos</b> cuando termine este guion?",
        art: CH('@numi flag{ setv:punts,0 chv:punts,2 chv:punts,2 setv:punts,10 chv:punts,-1 }', [{ id: 'numi', art: 'numi' }]),
        opts: ['9|9', '3|3', '13|13'], a: 0, keep: true,
        ex: "0 + 2 + 2 = 4, però «posa punts a 10» esborra el 4 i hi posa un 10. Després, suma -1: 10 - 1 = 9.|0 + 2 + 2 = 4, pero «pon puntos a 10» borra el 4 y pone un 10. Después, suma -1: 10 - 1 = 9." },
      { k: 'quiz', ph: 'prova', q: "Vols que en Numi digui quants punts portes. <b>Quin bloc hi poses?</b>|Quieres que Numi diga cuántos puntos llevas. <b>¿Qué bloque pones?</b>",
        opts: ["«digues» i hi tries la variable <b>punts</b>|«di» y eliges la variable <b>puntos</b>", "«digues» i hi escrius la paraula «punts»|«di» y escribes la palabra «puntos»", "«posa punts a 0»|«pon puntos a 0»"], a: 0,
        ex: "Si escrius la paraula, en Numi diu «punts». Si tries la variable, diu el número que hi ha a dins.|Si escribes la palabra, Numi dice «puntos». Si eliges la variable, dice el número que hay dentro." },
      { k: 'sspot', ph: 'investiga', q: "Aquest marcador sempre diu 1, per moltes vegades que toquis la moneda. <b>Toca el bloc que s'equivoca.</b>|Este marcador siempre dice 1, por muchas veces que toques la moneda. <b>Toca el bloque que se equivoca.</b>",
        w: { bg: 'parc', sprites: [{ id: 'moneda', art: 'moneda', x: 0, y: -10, size: 160 }], vars: ['punts'] }, varNames: VN,
        prog: '@moneda flag{ setv:punts,0 forever{ next wait:0.12 } } click{ setv:punts,1! sound:moneda }',
        ex: "«Posa punts a 1» hi posa un 1 cada vegada. Per sumar, cal «suma a punts 1».|«Pon puntos a 1» pone un 1 cada vez. Para sumar, hace falta «suma a puntos 1»." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de marcador! Aixeca't i fes <b>5 salts</b>: a cada salt, digues el número en veu alta (1, 2, 3, 4, 5). Ara <b>posa a 0</b>: ajup-te i torna a començar amb <b>3 salts</b>.|¡Haz de marcador! Levántate y da <b>5 saltos</b>: en cada salto, di el número en voz alta (1, 2, 3, 4, 5). Ahora <b>pon a 0</b>: agáchate y vuelve a empezar con <b>3 saltos</b>." },
      { k: 'stage', ph: 'repte', q: "La moneda de la sort! Fes que, <b>cada vegada que toques la moneda</b>, sumi <b>1</b> a punts i faci el so «moneda». Prova-ho amb <b>Comença</b> i, quan funcioni, toca <b>Comprova</b>.|¡La moneda de la suerte! Haz que, <b>cada vez que toques la moneda</b>, sume <b>1</b> a puntos y haga el sonido «moneda». Pruébalo con <b>Empieza</b> y, cuando funcione, toca <b>Comprueba</b>.",
        w: { bg: 'parc', sprites: [{ id: 'moneda', art: 'moneda', x: 0, y: -10, size: 160, prog: '@moneda flag{ forever{ next wait:0.12 } }' }], vars: ['punts'], input: clicks('moneda', [.6, 1.2, 1.8, 2.4, 3]), time: 4, goal: [{ k: 'var', v: 'punts', eq: 5 }, { k: 'running', t: 3.4 }] },
        edit: ['moneda'], hats: ['click'], pal: ['chv', 'setv', 'sound', 'say', 'next', 'wait'], varNames: VN,
        sol: '@moneda click{ chv:punts,1 sound:moneda }', hint: "Al guió «Quan toco aquest personatge», posa «suma a punts 1».|En el guion «Al tocar este personaje», pon «suma a puntos 1»." },
      { k: 'stage', ph: 'repte', q: "Ara els punts es guanyen atrapant. La poma ja cau sola. Fes que, <b>si toca el gat</b>, sumi 1 a punts i <b>torni a dalt</b> (posa y a 150).|Ahora los puntos se ganan atrapando. La manzana ya cae sola. Haz que, <b>si toca el gato</b>, sume 1 a puntos y <b>vuelva arriba</b> (pon y a 150).",
        w: { bg: 'parc', sprites: [GAT, { id: 'poma', art: 'poma', x: 0, y: 150 }], vars: ['punts'], time: 8, goal: [{ k: 'var', v: 'punts', min: 2, max: 5 }, { k: 'running', t: 7.8 }] },
        edit: ['poma'], hats: ['flag'], pal: ['chv', 'setv', 'if', 'sety', 'chy', 'sound', 'forever'], varNames: VN,
        prog: '@poma flag{ forever{ chy:-8 if:touch:edge{ sety:150 } } }', sol: POMA_OK,
        hint: "Dins del «per sempre», afegeix «si toca el gat» i, a dins, «suma a punts 1» i «posa y a 150». Si no la tornes a dalt, mentre toca el gat suma molts punts de cop!|Dentro del «por siempre», añade «si toca el gato» y, dentro, «suma a puntos 1» y «pon y a 150». Si no la devuelves arriba, mientras toca el gato ¡suma muchos puntos de golpe!" },
      { k: 'stage', ph: 'repte', q: "El comptador de salts. Quan prems <b>espai</b>, el gat salta. Fes que cada salt sumi 1 a <b>salts</b> i que el gat <b>digui quants salts porta</b>.|El contador de saltos. Al pulsar <b>espacio</b>, el gato salta. Haz que cada salto sume 1 a <b>saltos</b> y que el gato <b>diga cuántos saltos lleva</b>.",
        w: { bg: 'parc', sprites: [{ id: 'gat', art: 'gat', x: 0, y: -110 }, { id: 'ocell', art: 'ocell', x: -150, y: 120, prog: '@ocell flag{ forever{ move:3 bounce next } }' }], vars: ['salts'], keys: ['space'],
          input: [{ t: .5, key: 'space', dur: .1 }, { t: 1.5, key: 'space', dur: .1 }, { t: 2.5, key: 'space', dur: .1 }], time: 4, goal: [{ k: 'var', v: 'salts', eq: 3 }, { k: 'said', s: 'gat', t: '3' }, { k: 'running', t: 3.6 }] },
        edit: ['gat'], hats: ['key:space'], pal: ['chv', 'setv', 'chy', 'wait', 'say', 'sound'], varNames: VN, texts: ['Hop!|¡Hop!'],
        prog: '@gat key:space{ chy:60 wait:0.3 chy:-60 }', sol: '@gat key:space{ chy:60 wait:0.3 chy:-60 chv:salts,1 say:$salts }',
        hint: "Afegeix «suma a salts 1» i un «digues». Toca el text del «digues» i tria la variable <b>salts</b>.|Añade «suma a saltos 1» y un «di». Toca el texto del «di» y elige la variable <b>saltos</b>." },
      { k: 'stage', ph: 'repte', q: "Sumar i restar! Programa els dos personatges: <b>tocar l'estrella suma 1 punt</b> i <b>tocar el meteorit en resta 1</b> (suma -1).|¡Sumar y restar! Programa los dos personajes: <b>tocar la estrella suma 1 punto</b> y <b>tocar el meteorito resta 1</b> (suma -1).",
        w: { bg: 'nit', sprites: [{ id: 'estrella', art: 'estrella', x: -110, y: 10, size: 150 }, { id: 'meteorit', art: 'meteorit', x: 110, y: 10, size: 150, prog: '@meteorit flag{ forever{ turn:3 } }' }], vars: ['punts'],
          input: [...clicks('estrella', [.5, 1, 1.5]), { t: 2, click: 'meteorit' }, { t: 2.5, click: 'estrella' }], time: 3.2, goal: [{ k: 'var', v: 'punts', eq: 3 }, { k: 'running', t: 3 }] },
        edit: ['estrella', 'meteorit'], hats: ['click'], pal: ['chv', 'setv', 'sound', 'say'], varNames: VN,
        sol: '@estrella click{ chv:punts,1 sound:moneda } @meteorit click{ chv:punts,-1 sound:xoc }',
        hint: "Tria cada personatge a dalt. Al meteorit, posa «suma a punts» i canvia el 1 per <b>-1</b>.|Elige cada personaje arriba. En el meteorito, pon «suma a puntos» y cambia el 1 por <b>-1</b>." },
      { k: 'screate', ph: 'crea', name: 'La caseta dels globus|La caseta de los globos',
        q: "<b>La teva caseta de la fira!</b> Cada globus que toques és un punt. Fes-la com vulguis (sons, mides, llocs…), però ha de complir els criteris.|<b>¡Tu caseta de la feria!</b> Cada globo que toques es un punto. Hazla como quieras (sonidos, tamaños, sitios…), pero tiene que cumplir los criterios.",
        crit: ["Quan comença, posa punts a 0|Al empezar, pon puntos a 0", "Cada vegada que toques el globus, suma punts|Cada vez que tocas el globo, suma puntos", "Quan toques en Numi, diu quants punts portes|Al tocar a Numi, dice cuántos puntos llevas"],
        w: { bg: 'parc', sprites: [{ id: 'globus', art: 'globus', x: 70, y: 20, size: 130 }, { id: 'numi', art: 'numi', x: -150, y: -70 }, { id: 'ocell', art: 'ocell', x: -160, y: 130, prog: '@ocell flag{ forever{ move:3 bounce next } }' }], vars: ['punts'],
          input: [...clicks('globus', [.6, 1.2, 1.8]), { t: 2.4, click: 'numi' }], time: 3.6, goal: [{ k: 'var', v: 'punts', min: 3 }, { k: 'said', s: 'numi' }] },
        edit: ['globus', 'numi'], hats: ['flag', 'click'], pal: ['setv', 'chv', 'say', 'sound', 'next', 'wait', 'goto', 'glide', 'size', 'chsize', 'hide', 'show'], varNames: VN, texts: ['Molt bé!|¡Muy bien!'],
        sol: '@globus flag{ setv:punts,0 } click{ chv:punts,1 sound:pop } @numi click{ say:$punts,2 }',
        check: P => { const f = (id, h, pred) => ((P[id] || {})[h] || []).some(function w(l) { return (l || []).some(b => pred(b) || w(b.b) || w(b.e)); });
          if (!['globus', 'numi'].some(id => f(id, 'flag', b => b.k === 'setv'))) return "Falta «posa punts a 0» en un guió «Quan comença».|Falta «pon puntos a 0» en un guion «Al empezar».";
          if (!f('globus', 'click', b => b.k === 'chv')) return "Quan toques el globus, ha de sumar punts.|Al tocar el globo, tiene que sumar puntos.";
          if (!f('numi', 'click', b => b.k === 'say' && typeof b.t === 'object')) return "En Numi ha de dir la variable punts (toca el text del «digues» i tria-la).|Numi tiene que decir la variable puntos (toca el texto del «di» y elígela).";
          return null; } },
      { k: 'quiz', ph: 'tanca', q: "Per acabar: què és una <b>variable</b>?|Para terminar: ¿qué es una <b>variable</b>?",
        opts: ["Una capsa amb nom que guarda un número que pot canviar|Una caja con nombre que guarda un número que puede cambiar", "Un personatge que es mou per l'escenari|Un personaje que se mueve por el escenario", "Un so que fa la moneda|Un sonido que hace la moneda"], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "<b>punts</b> val 7. Què val després de «suma a punts -2»?|<b>puntos</b> vale 7. ¿Qué vale después de «suma a puntos -2»?", opts: ['5|5', '9|9', '-2|-2'], a: 0, keep: true,
        ex: "Sumar un número negatiu és restar: 7 - 2 = 5.|Sumar un número negativo es restar: 7 - 2 = 5." },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 2 · Vides i fi de partida ---------- */
  { id: 'g6-2', t: 'Vides i fi de partida|Vidas y fin de partida', min: 45, badge: 'g_vides',
    learn: ["Les vides són una variable que comença a 3 i baixa 1 a cada xoc; després del xoc cal esperar una mica perquè no en baixi més d'una.|Las vidas son una variable que empieza en 3 y baja 1 en cada choque; después del choque hay que esperar un poco para que no baje más de una.",
      "Una condició pot comparar una variable amb un número: vides = 0, punts > 9, temps < 5. La resposta és sí o no.|Una condición puede comparar una variable con un número: vidas = 0, puntos > 9, tiempo < 5. La respuesta es sí o no.",
      "«Posa vides a 3» va una sola vegada, al començament; «atura tot» acaba la partida.|«Pon vidas a 3» va una sola vez, al principio; «para todo» termina la partida."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "De la sessió anterior: quin bloc fa que el marcador <b>baixi</b> 1 punt?|De la sesión anterior: ¿qué bloque hace que el marcador <b>baje</b> 1 punto?",
        opts: ["«suma a punts -1»|«suma a puntos -1»", "«posa punts a -1»|«pon puntos a -1»", "«suma a punts 1»|«suma a puntos 1»"], a: 0,
        ex: "Sumar -1 és restar 1. «Posa punts a -1» esborraria tots els punts i hi posaria un -1.|Sumar -1 es restar 1. «Pon puntos a -1» borraría todos los puntos y pondría un -1." },
      { k: 'quiz', ph: 'recorda', q: "Quan el gat atrapava la poma, per què la tornàvem a dalt?|Cuando el gato atrapaba la manzana, ¿por qué la devolvíamos arriba?",
        opts: ["Perquè, mentre la toca, sumaria punts a cada volta del bucle|Porque, mientras la toca, sumaría puntos en cada vuelta del bucle", "Perquè la poma no pot estar a baix|Porque la manzana no puede estar abajo", "Perquè el gat no la vegi|Para que el gato no la vea"], a: 0 },
      { k: 'story', ph: 'missio', who: 'both', scene: 'poble', title: 'La nau que no es trenca mai|La nave que no se rompe nunca',
        t: "A la caseta de la fira, en Bit ha provat el videojoc de l'espai: la nau xoca amb el meteorit i… <b>no passa res!</b> Ni s'acaba la partida ni res. Així no té gràcia. Necessitem <b>vides</b>.|En la caseta de la feria, Bit ha probado el videojuego del espacio: la nave choca con el meteorito y… <b>¡no pasa nada!</b> Ni se acaba la partida ni nada. Así no tiene gracia. Necesitamos <b>vidas</b>." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Vides|Vidas', t: 'Una variable que baixa|Una variable que baja', anim: 'g6lives',
          x: "Les <b>vides</b> també són una variable. Al començament, <b>posa vides a 3</b>. A cada xoc, <b>suma a vides -1</b>: 3, 2, 1… i quan arriben a 0, s'ha acabat la partida.|Las <b>vidas</b> también son una variable. Al principio, <b>pon vidas a 3</b>. En cada choque, <b>suma a vidas -1</b>: 3, 2, 1… y cuando llegan a 0, se ha acabado la partida." },
        { k: 'Un xoc, una vida|Un choque, una vida', t: 'Espera després del xoc|Espera después del choque',
          media: { k: 'stage', w: W_NAU(6), prog: `${METEOR} @nau flag{ setv:vides,3 forever{ if:touch:meteorit{ chv:vides,-1 sound:xoc wait:1 } } }`, varNames: VN, time: 6 },
          x: "Mentre el meteorit travessa la nau, la toca durant molts fotogrames. Per això, després de restar una vida, la nau <b>espera 1 segon</b>: així cada xoc només en resta una.|Mientras el meteorito atraviesa la nave, la toca durante muchos fotogramas. Por eso, después de restar una vida, la nave <b>espera 1 segundo</b>: así cada choque solo resta una." },
        { k: 'Comparar|Comparar', t: 'vides = 0?|¿vidas = 0?', anim: 'g6cmp',
          x: "Una condició pot <b>comparar</b> una variable amb un número: <b>vides = 0</b> (és igual a 0?), <b>punts > 9</b> (és més gran que 9?), <b>temps < 5</b> (és més petit que 5?). La resposta sempre és <b>sí</b> o <b>no</b>.|Una condición puede <b>comparar</b> una variable con un número: <b>vidas = 0</b> (¿es igual a 0?), <b>puntos > 9</b> (¿es mayor que 9?), <b>tiempo < 5</b> (¿es menor que 5?). La respuesta siempre es <b>sí</b> o <b>no</b>.",
          tip: "Truc per al > i el <: la boca oberta sempre mira el número més gran. Al menú també hi ha ≠ (diferent de), ≤ (més petit o igual) i ≥ (més gran o igual).|Truco para el > y el <: la boca abierta siempre mira al número más grande. En el menú también están ≠ (distinto de), ≤ (menor o igual) y ≥ (mayor o igual)." },
        { k: 'Fi de la partida|Fin de la partida', t: 'Quan no queden vides|Cuando no quedan vidas',
          media: { k: 'stage', w: W_NAU(9), prog: `${METEOR} ${NAU_OK}`, varNames: VN, time: 9 },
          x: "Dins del «per sempre», un «si vides = 0» vigila les vides a cada volta. Quan la resposta és sí, la nau diu «Fi de la partida!» i <b>atura tot</b>: s'aturen tots els guions de tots els personatges.|Dentro del «por siempre», un «si vidas = 0» vigila las vidas en cada vuelta. Cuando la respuesta es sí, la nave dice «¡Fin de la partida!» y <b>para todo</b>: se paran todos los guiones de todos los personajes." },
        { k: 'Compte!|¡Cuidado!', t: '«Posa vides a 3», fora del bucle|«Pon vidas a 3», fuera del bucle',
          media: { k: 'stage', w: W_NAU(6), prog: `${METEOR} @nau flag{ forever{ setv:vides,3 if:touch:meteorit{ chv:vides,-1 sound:xoc wait:1 } if:$vides=0{ say:"${FI}" stop:all } } }`, varNames: VN, time: 6 },
          x: "En aquesta demo, «posa vides a 3» és dins del «per sempre»: a cada volta les vides tornen a 3, i la partida no s'acaba mai.|En esta demo, «pon vidas a 3» está dentro del «por siempre»: en cada vuelta las vidas vuelven a 3, y la partida no se acaba nunca.",
          bad: "Per sempre: posa vides a 3… → sempre 3 vides|Por siempre: pon vidas a 3… → siempre 3 vidas", good: "Posa vides a 3 i, després, per sempre…|Pon vidas a 3 y, después, por siempre…" }
      ] },
      { k: 'unplug', ph: 'mans', ico: '❤️', title: 'Les tres vides|Las tres vidas',
        t: "Necessites algú de casa, un mitjó enrotllat (que no faci mal) i tres cors de paper.|Necesitas a alguien de casa, un calcetín enrollado (que no haga daño) y tres corazones de papel.",
        steps: ["Una persona és la <b>nau</b> i té <b>3 cors</b> a la mà: posa vides a 3.|Una persona es la <b>nave</b> y tiene <b>3 corazones</b> en la mano: pon vidas a 3.",
          "L'altra llança el mitjó a poc a poc, de lluny. Si toca la nau: <b>suma a vides -1</b> (deixa un cor a terra).|La otra lanza el calcetín despacio, desde lejos. Si toca a la nave: <b>suma a vidas -1</b> (deja un corazón en el suelo).",
          "Després de cada xoc, compteu fins a 3 abans del llançament següent: és l'«espera» del programa.|Después de cada choque, contad hasta 3 antes del siguiente lanzamiento: es la «espera» del programa.",
          "Quan vides = 0, digueu junts: «Fi de la partida!». Canvieu els papers.|Cuando vidas = 0, decid juntos: «¡Fin de la partida!». Cambiad los papeles."],
        tip: "Abans de cada llançament, digueu en veu alta quantes vides queden: és el marcador.|Antes de cada lanzamiento, decid en voz alta cuántas vidas quedan: es el marcador." },
      { k: 'seq', ph: 'mans', q: "Ordena el guió de la nau perquè funcioni. <b>Toca els blocs de dalt a baix.</b>|Ordena el guion de la nave para que funcione. <b>Toca los bloques de arriba abajo.</b>",
        items: ["Quan comença|Al empezar", "Posa vides a 3|Pon vidas a 3", "Per sempre:|Por siempre:", "↳ Si toca el meteorit → suma a vides -1 i espera 1 segon|↳ Si toca el meteorito → suma a vidas -1 y espera 1 segundo", "↳ Si vides = 0 → digues «Fi de la partida!» i atura tot|↳ Si vidas = 0 → di «¡Fin de la partida!» y para todo"],
        ex: "«Posa vides a 3» va abans del bucle, una sola vegada. Dins del bucle, la nau vigila els xocs i les vides.|«Pon vidas a 3» va antes del bucle, una sola vez. Dentro del bucle, la nave vigila los choques y las vidas." },
      { k: 'quiz', ph: 'prova', q: "La nau comença amb <b>3 vides</b>. Xoca, agafa un cor (+1), xoca i torna a xocar. <b>Quantes vides li queden?</b>|La nave empieza con <b>3 vidas</b>. Choca, coge un corazón (+1), choca y vuelve a chocar. <b>¿Cuántas vidas le quedan?</b>",
        opts: ['1|1', '0|0', '2|2'], a: 0, keep: true, ex: "3 - 1 = 2, 2 + 1 = 3, 3 - 1 = 2, 2 - 1 = 1. Encara li queda una vida!|3 - 1 = 2, 2 + 1 = 3, 3 - 1 = 2, 2 - 1 = 1. ¡Aún le queda una vida!" },
      { k: 'quiz', ph: 'prova', q: "Quina condició vol dir «ja no queden vides»?|¿Qué condición quiere decir «ya no quedan vidas»?",
        opts: ["vides = 0|vidas = 0", "vides = 3|vidas = 3", "vides > 0|vidas > 0"], a: 0,
        ex: "vides > 0 vol dir que encara en queden. vides = 3 només és certa al començament.|vidas > 0 quiere decir que aún quedan. vidas = 3 solo es cierta al principio." },
      { k: 'sspot', ph: 'investiga', q: "Ui! Aquesta partida s'acaba <b>abans de començar</b>. <b>Toca el bloc que s'equivoca.</b>|¡Uy! Esta partida se acaba <b>antes de empezar</b>. <b>Toca el bloque que se equivoca.</b>",
        w: W_NAU(4), varNames: VN,
        prog: `@nau flag{ setv:vides,3 forever{ if:touch:meteorit{ chv:vides,-1 sound:xoc wait:1 } if:$vides=3!{ say:"${FI}" stop:all } } }`,
        ex: "Al començament vides = 3, i la condició ja diu que sí: la partida s'acaba de seguida. Ha de ser vides = 0.|Al principio vidas = 3, y la condición ya dice que sí: la partida se acaba enseguida. Tiene que ser vidas = 0." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Ets la nau! Dret/a, amb <b>3 vides</b> (aixeca 3 dits). Quan diguin «meteorit!», ajup-te ràpid. Si t'hi encantes, abaixa un dit. Quan no et quedin dits: «Fi de la partida!» i seu.|¡Eres la nave! De pie, con <b>3 vidas</b> (levanta 3 dedos). Cuando digan «¡meteorito!», agáchate rápido. Si te despistas, baja un dedo. Cuando no te queden dedos: «¡Fin de la partida!» y siéntate." },
      { k: 'stage', ph: 'repte', q: "Dona <b>3 vides</b> a la nau i fes que, <b>cada vegada que el meteorit la toca</b>, en perdi una (suma -1) i <b>esperi 1 segon</b>.|Dale <b>3 vidas</b> a la nave y haz que, <b>cada vez que el meteorito la toca</b>, pierda una (suma -1) y <b>espere 1 segundo</b>.",
        w: W_NAU(2.6, { goal: [{ k: 'var', v: 'vides', eq: 2 }, { k: 'running', t: 2.5 }], alts: [{ time: 4.4, goal: [{ k: 'var', v: 'vides', eq: 1 }, { k: 'running', t: 4.3 }] }] }),
        edit: ['nau'], hats: ['flag'], pal: ['setv', 'chv', 'if', 'forever', 'wait', 'sound', 'say'], varNames: VN,
        sol: '@nau flag{ setv:vides,3 forever{ if:touch:meteorit{ chv:vides,-1 sound:xoc wait:1 } } }',
        hint: "Primer «posa vides a 3». Després un «per sempre» amb «si toca el meteorit» i, a dins, «suma a vides -1» i «espera 1».|Primero «pon vidas a 3». Después un «por siempre» con «si toca el meteorito» y, dentro, «suma a vidas -1» y «espera 1»." },
      { k: 'stage', ph: 'repte', q: "Ara, la fi de la partida. El «si vides = 0» ja hi és: posa-hi a dins que la nau digui <b>«Fi de la partida!»</b> i <b>atura tot</b>.|Ahora, el fin de la partida. El «si vidas = 0» ya está: pon dentro que la nave diga <b>«¡Fin de la partida!»</b> y <b>para todo</b>.",
        w: W_NAU(10, { goal: [{ k: 'said', s: 'nau', t: 'partida' }, { k: 'stopped' }, { k: 'var', v: 'vides', eq: 0 }] }),
        edit: ['nau'], hats: ['flag'], pal: ['setv', 'chv', 'if', 'cond+', 'forever', 'wait', 'sound', 'say', 'stop'], varNames: VN, texts: [FI, 'Uf!|¡Uf!'],
        prog: '@nau flag{ setv:vides,3 forever{ if:touch:meteorit{ chv:vides,-1 sound:xoc wait:1 } if:$vides=0{ } } }', sol: NAU_OK,
        hint: "Toca l'espai de dins del «si vides = 0» i afegeix «digues» (tria «Fi de la partida!») i «atura tot».|Toca el espacio de dentro del «si vidas = 0» y añade «di» (elige «¡Fin de la partida!») y «para todo»." },
      { k: 'stage', ph: 'repte', q: "Una vida extra! La nau ja té 3 vides i es mou amb la fletxa →. Programa el <b>cor</b>: quan el toqui la nau, suma <b>1</b> a vides i <b>amaga't</b>.|¡Una vida extra! La nave ya tiene 3 vidas y se mueve con la flecha →. Programa el <b>corazón</b>: cuando lo toque la nave, suma <b>1</b> a vidas y <b>escóndete</b>.",
        w: { bg: 'espai', sprites: [{ id: 'nau', art: 'nau', x: -150, y: -100, prog: '@nau flag{ setv:vides,3 } key:right{ chx:15 } key:left{ chx:-15 }' }, { id: 'cor', art: 'cor', x: 60, y: -100, size: 120 }], vars: ['vides'], keys: ['left', 'right'],
          input: [{ t: .5, key: 'right', dur: 1.6 }], time: 4, goal: [{ k: 'var', v: 'vides', eq: 4 }, { k: 'hidden', s: 'cor' }, { k: 'touched', a: 'cor', b: 'nau' }] },
        edit: ['cor'], hats: ['flag'], pal: ['chv', 'setv', 'waitu', 'if', 'forever', 'hide', 'show', 'sound'], varNames: VN,
        sol: '@cor flag{ waitu:touch:nau chv:vides,1 sound:pop hide }',
        hint: "«Espera fins que toca la nau» i després «suma a vides 1» i «amaga't». Amagat, ja no el pot tocar més.|«Espera hasta que toca la nave» y después «suma a vidas 1» y «escóndete». Escondido, ya no lo puede tocar más." },
      { k: 'stage', ph: 'repte', q: "Aquesta partida no s'acaba mai: les vides no baixen de 3! <b>Troba l'error i arregla'l.</b>|Esta partida no se acaba nunca: ¡las vidas no bajan de 3! <b>Encuentra el error y arréglalo.</b>",
        w: W_NAU(10, { goal: [{ k: 'said', s: 'nau', t: 'partida' }, { k: 'stopped' }, { k: 'var', v: 'vides', eq: 0 }] }),
        edit: ['nau'], hats: ['flag'], pal: ['setv', 'chv', 'if', 'cond+', 'forever', 'wait', 'sound', 'say', 'stop'], varNames: VN, texts: [FI],
        prog: `@nau flag{ forever{ setv:vides,3 if:touch:meteorit{ chv:vides,-1 sound:xoc wait:1 } if:$vides=0{ say:"${FI}" stop:all } } }`, sol: NAU_OK,
        hint: "On és «posa vides a 3»? Si és dins del «per sempre», es repeteix a cada volta. Esborra'l i posa'n un de nou abans del bucle.|¿Dónde está «pon vidas a 3»? Si está dentro del «por siempre», se repite en cada vuelta. Bórralo y pon uno nuevo antes del bucle." },
      { k: 'screate', ph: 'crea', name: 'El peix i les meduses|El pez y las medusas',
        q: "<b>El teu videojoc de vides!</b> El peix ha d'esquivar la medusa amb les fletxes ↑ i ↓. El «si vides = 0» ja hi és; la resta, la fas tu.|<b>¡Tu videojuego de vidas!</b> El pez tiene que esquivar la medusa con las flechas ↑ y ↓. El «si vidas = 0» ya está; el resto, lo haces tú.",
        crit: ["El peix comença amb 3 vides|El pez empieza con 3 vidas", "Cada xoc amb la medusa resta una sola vida|Cada choque con la medusa resta una sola vida", "Quan vides = 0, diu alguna cosa i atura tot|Cuando vidas = 0, dice algo y para todo", "Extra: el peix es mou amb ↑ i ↓|Extra: el pez se mueve con ↑ y ↓"],
        w: { bg: 'aquari', sprites: [{ id: 'peix', art: 'peix', x: 0, y: -30 }, { id: 'medusa', art: 'medusa', x: -200, y: -30, prog: '@medusa flag{ forever{ chx:6 next if:touch:edge{ setx:-200 } } }' }], vars: ['vides'], keys: ['up', 'down'],
          time: 12, goal: [{ k: 'stopped' }, { k: 'var', v: 'vides', eq: 0 }, { k: 'said', s: 'peix' }] },
        edit: ['peix'], hats: ['flag', 'key:up', 'key:down'], pal: ['setv', 'chv', 'if', 'cond+', 'forever', 'wait', 'sound', 'say', 'stop', 'chy', 'next', 'costume'], varNames: VN, texts: [FI, 'Ai!|¡Ay!'],
        prog: '@peix flag{ forever{ if:$vides=0{ } } }',
        sol: `@peix flag{ setv:vides,3 forever{ if:touch:medusa{ chv:vides,-1 sound:xoc wait:1 } if:$vides=0{ say:"${FI}" stop:all } } } key:up{ chy:20 } key:down{ chy:-20 }`,
        check: P => { const l = ((P.peix || {}).flag || [])[0] || [], i = l.findIndex(b => b.k === 'setv' && b.v === 'vides'), j = l.findIndex(b => b.k === 'forever');
          if (i < 0 || (j >= 0 && i > j) || !(typeof l[i].n === 'number' && l[i].n > 0)) return "Posa «posa vides a 3» al començament, abans del «per sempre».|Pon «pon vidas a 3» al principio, antes del «por siempre».";
          const hit = JSON.stringify(l).match(/"k":"if","c":\{"touch":"medusa"\},"b":(\[.*?\]),"e"/);
          if (!hit || !/"k":"chv"/.test(hit[1])) return "Quan el peix toca la medusa, ha de perdre una vida (suma a vides -1).|Cuando el pez toca la medusa, tiene que perder una vida (suma a vidas -1).";
          if (!/"k":"wait"/.test(hit[1])) return "Després de perdre una vida, el peix ha d'esperar una mica: si no, en perd moltes de cop.|Después de perder una vida, el pez tiene que esperar un poco: si no, pierde muchas de golpe.";
          return null; } },
      { k: 'quiz', ph: 'tanca', q: "Per què la nau espera 1 segon després de perdre una vida?|¿Por qué la nave espera 1 segundo después de perder una vida?",
        opts: ["Perquè el meteorit la toca durant molts fotogrames i li trauria més vides|Porque el meteorito la toca durante muchos fotogramas y le quitaría más vidas", "Perquè la nau està cansada|Porque la nave está cansada", "Perquè el programa vagi més de pressa|Para que el programa vaya más deprisa"], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "On ha d'anar «posa vides a 3»?|¿Dónde tiene que ir «pon vidas a 3»?",
        opts: ["Al començament, abans del «per sempre»|Al principio, antes del «por siempre»", "Dins del «per sempre»|Dentro del «por siempre»", "Dins del «si vides = 0»|Dentro del «si vidas = 0»"], a: 0,
        ex: "Si és dins del bucle, les vides tornen a 3 a cada volta.|Si está dentro del bucle, las vidas vuelven a 3 en cada vuelta." },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 3 · Compte enrere ---------- */
  { id: 'g6-3', t: 'Compte enrere|Cuenta atrás', min: 45, badge: 'g_rellotge',
    learn: ["Un compte enrere és una variable que comença en un número i baixa 1 cada segon (repeteix: espera 1 segon, suma -1).|Una cuenta atrás es una variable que empieza en un número y baja 1 cada segundo (repite: espera 1 segundo, suma -1).",
      "El rellotge pot tenir el seu propi guió: funciona alhora que la resta del videojoc, i «atura tot» l'acaba.|El reloj puede tener su propio guion: funciona a la vez que el resto del videojuego, y «para todo» lo termina.",
      "El cronòmetre compta cap amunt tot sol; «posa el cronòmetre a zero» el fa començar de nou per saber quant has trigat.|El cronómetro cuenta hacia arriba solo; «pon el cronómetro a cero» lo hace empezar de nuevo para saber cuánto has tardado."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "Recordes la nau? <b>Quan</b> diu «Fi de la partida!»?|¿Recuerdas la nave? <b>¿Cuándo</b> dice «¡Fin de la partida!»?",
        art: CH(NAU_OK, [{ id: 'nau', art: 'nau' }, { id: 'meteorit', art: 'meteorit' }]),
        opts: ["Quan vides = 0|Cuando vidas = 0", "Al primer xoc|En el primer choque", "Quan vides = 3|Cuando vidas = 3"], a: 0 },
      { k: 'quiz', ph: 'recorda', q: "Què fa el bloc «atura tot»?|¿Qué hace el bloque «para todo»?",
        opts: ["Atura tots els guions de tots els personatges|Para todos los guiones de todos los personajes", "Només atura el guió on és|Solo para el guion donde está", "Torna a començar la partida|Vuelve a empezar la partida"], a: 0 },
      { k: 'story', ph: 'missio', who: 'both', scene: 'poble', title: 'Hi ha cua a la caseta!|¡Hay cola en la caseta!',
        t: "La caseta de la fira té tant d'èxit que hi ha una cua llarguíssima! Perquè tothom pugui provar els videojocs, cada persona tindrà <b>10 segons</b>. Necessitem un rellotge que compti enrere: 10, 9, 8…|¡La caseta de la feria tiene tanto éxito que hay una cola larguísima! Para que todo el mundo pueda probar los videojuegos, cada persona tendrá <b>10 segundos</b>. Necesitamos un reloj que cuente hacia atrás: 10, 9, 8…" },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy',
        t: "BIP! Un compte enrere és una <b>variable</b> que baixa sola, 1 cada segon. I l'escenari també té un rellotge que compta <b>cap amunt</b>: el <b>cronòmetre</b>. Avui els farem servir tots dos!|¡BIP! Una cuenta atrás es una <b>variable</b> que baja sola, 1 cada segundo. Y el escenario también tiene un reloj que cuenta <b>hacia arriba</b>: el <b>cronómetro</b>. ¡Hoy usaremos los dos!" },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Compte enrere|Cuenta atrás', t: 'Una variable que baixa cada segon|Una variable que baja cada segundo', anim: 'g6count',
          x: "Un compte enrere és una variable, <b>temps</b>, que comença, per exemple, a 5. Un bucle la fa baixar: <b>repeteix 5 vegades: espera 1 segon i suma a temps -1</b>. Quan el bucle acaba, el temps val 0.|Una cuenta atrás es una variable, <b>tiempo</b>, que empieza, por ejemplo, en 5. Un bucle la hace bajar: <b>repite 5 veces: espera 1 segundo y suma a tiempo -1</b>. Cuando el bucle termina, el tiempo vale 0." },
        { k: 'Mira-ho|Míralo', t: '5, 4, 3, 2, 1… Ja!|5, 4, 3, 2, 1… ¡Ya!',
          media: { k: 'stage', w: { bg: 'escenari', sprites: [{ id: 'numi', art: 'numi', x: 0, y: -40, size: 130 }], vars: ['temps'] }, prog: '@numi flag{ setv:temps,5 rep:5{ say:$temps wait:1 chv:temps,-1 } say:"Ja!|¡Ya!",1.5 }', varNames: VN, time: 7 },
          x: "Fixa't en l'ordre de dins del bucle: primer en Numi <b>diu</b> el número, després <b>espera</b> 1 segon i, al final, en <b>resta</b> 1. Quan el bucle s'acaba, diu «Ja!».|Fíjate en el orden de dentro del bucle: primero Numi <b>dice</b> el número, después <b>espera</b> 1 segundo y, al final, <b>resta</b> 1. Cuando el bucle termina, dice «¡Ya!»." },
        { k: 'Dos guions alhora|Dos guiones a la vez', t: 'El rellotge i el videojoc|El reloj y el videojuego',
          media: { k: 'stage', w: { bg: 'parc', sprites: [GAT, { id: 'poma', art: 'poma', x: 0, y: 150 }, { id: 'numi', art: 'numi', x: 170, y: 40, size: 80 }], vars: ['punts', 'temps'] }, prog: `${GAT.prog} ${POMA_OK} @numi flag{ setv:temps,6 rep:6{ wait:1 chv:temps,-1 } say:"${TEMPS}" stop:all }`, varNames: VN, time: 8 },
          x: "En Numi fa de rellotge amb el seu propi guió, i el gat i la poma continuen amb els seus: tots els guions funcionen <b>alhora</b>. Quan el temps arriba a 0, «atura tot» ho para tot.|Numi hace de reloj con su propio guion, y el gato y la manzana siguen con los suyos: todos los guiones funcionan <b>a la vez</b>. Cuando el tiempo llega a 0, «para todo» lo para todo." },
        { k: 'El cronòmetre|El cronómetro', t: 'Quant has trigat?|¿Cuánto has tardado?', anim: 'g6timer',
          x: "L'escenari té un rellotge que compta <b>cap amunt</b> tot sol, en segons: el <b>cronòmetre</b>. El bloc «posa el cronòmetre a zero» el fa començar de nou. Al final, pots guardar-ne el valor en una variable: <b>posa segons a cronòmetre</b>.|El escenario tiene un reloj que cuenta <b>hacia arriba</b> solo, en segundos: el <b>cronómetro</b>. El bloque «pon el cronómetro a cero» lo hace empezar de nuevo. Al final, puedes guardar su valor en una variable: <b>pon segundos a cronómetro</b>.",
          tip: "Compte enrere: de 10 a 0. Cronòmetre: de 0 cap amunt.|Cuenta atrás: de 10 a 0. Cronómetro: de 0 hacia arriba." },
        { k: 'Compte!|¡Cuidado!', t: "No t'oblidis d'esperar|No te olvides de esperar",
          media: { k: 'stage', w: { bg: 'escenari', sprites: [{ id: 'numi', art: 'numi', x: 0, y: -40, size: 130 }], vars: ['temps'] }, prog: '@numi flag{ setv:temps,10 wait:1 rep:10{ chv:temps,-1 } say:"Ja?|¿Ya?",2 }', varNames: VN, time: 4 },
          x: "En aquesta demo falta «espera 1 segon» dins del bucle. Cada volta dura només un fotograma, i el compte enrere de 10 segons s'acaba en un moment!|En esta demo falta «espera 1 segundo» dentro del bucle. Cada vuelta dura solo un fotograma, ¡y la cuenta atrás de 10 segundos se acaba en un momento!",
          bad: "Repeteix 10: suma a temps -1 → s'acaba de seguida|Repite 10: suma a tiempo -1 → se acaba enseguida", good: "Repeteix 10: espera 1 segon, suma a temps -1|Repite 10: espera 1 segundo, suma a tiempo -1" }
      ] },
      { k: 'unplug', ph: 'mans', ico: '⏳', title: 'El repte dels 10 segons|El reto de los 10 segundos',
        t: "Necessites algú de casa i uns quants objectes petits (pinces, taps, peces de construcció).|Necesitas a alguien de casa y unos cuantos objetos pequeños (pinzas, tapones, piezas de construcción).",
        steps: ["Una persona fa de <b>rellotge</b>: diu en veu alta 10, 9, 8… fins a 0, un número cada segon.|Una persona hace de <b>reloj</b>: dice en voz alta 10, 9, 8… hasta 0, un número cada segundo.",
          "Alhora, l'altra posa objectes dins d'un got, d'un en un, tan de pressa com pugui.|A la vez, la otra mete objetos dentro de un vaso, de uno en uno, tan rápido como pueda.",
          "Quan el rellotge diu 0: «S'ha acabat el temps!». Compteu els punts (objectes del got).|Cuando el reloj dice 0: «¡Se acabó el tiempo!». Contad los puntos (objetos del vaso).",
          "Canvieu els papers. Qui ha fet més punts?|Cambiad los papeles. ¿Quién ha hecho más puntos?"],
        tip: "Mentre una persona compta i l'altra recull, passen dues coses alhora: com dos guions!|Mientras una persona cuenta y la otra recoge, pasan dos cosas a la vez: ¡como dos guiones!" },
      { k: 'seq', ph: 'mans', q: "Ordena el guió del rellotge. <b>Toca els blocs de dalt a baix.</b>|Ordena el guion del reloj. <b>Toca los bloques de arriba abajo.</b>",
        items: ["Posa temps a 10|Pon tiempo a 10", "Repeteix 10 vegades:|Repite 10 veces:", "↳ Espera 1 segon|↳ Espera 1 segundo", "↳ Suma a temps -1|↳ Suma a tiempo -1", "Digues «S'ha acabat el temps!» i atura tot|Di «¡Se acabó el tiempo!» y para todo"],
        ex: "El temps comença a 10 i el bucle li resta 1 cada segon. Quan el bucle acaba, el temps ja val 0.|El tiempo empieza en 10 y el bucle le resta 1 cada segundo. Cuando el bucle termina, el tiempo ya vale 0." },
      { k: 'quiz', ph: 'prova', q: "<b>Quant de temps</b> passa fins que en Numi diu «Ja!»?|<b>¿Cuánto tiempo</b> pasa hasta que Numi dice «¡Ya!»?",
        art: CH('@numi flag{ setv:temps,3 rep:3{ wait:1 chv:temps,-1 } say:"Ja!|¡Ya!" }', [{ id: 'numi', art: 'numi' }]),
        opts: ['3 segons|3 segundos', '1 segon|1 segundo', 'Ho diu de seguida|Lo dice enseguida'], a: 0,
        ex: "El bucle es repeteix 3 vegades i cada volta espera 1 segon: 3 segons.|El bucle se repite 3 veces y cada vuelta espera 1 segundo: 3 segundos." },
      { k: 'quiz', ph: 'prova', q: "Has posat el cronòmetre a zero en sortir i, en arribar a la meta, marca <b>4,5</b>. Què vol dir?|Has puesto el cronómetro a cero al salir y, al llegar a la meta, marca <b>4,5</b>. ¿Qué quiere decir?",
        opts: ["Que has trigat 4 segons i mig|Que has tardado 4 segundos y medio", "Que queden 4 segons i mig|Que quedan 4 segundos y medio", "Que has fet 4 punts i mig|Que has hecho 4 puntos y medio"], a: 0,
        ex: "El cronòmetre compta cap amunt: diu quant de temps ha passat des que l'has posat a zero.|El cronómetro cuenta hacia arriba: dice cuánto tiempo ha pasado desde que lo has puesto a cero." },
      { k: 'sspot', ph: 'investiga', q: "Aquest compte enrere va cap amunt: 5, 6, 7… <b>Toca el bloc que s'equivoca.</b>|Esta cuenta atrás va hacia arriba: 5, 6, 7… <b>Toca el bloque que se equivoca.</b>",
        w: { bg: 'escenari', sprites: [{ id: 'numi', art: 'numi', x: 0, y: -40, size: 130 }], vars: ['temps'] }, varNames: VN,
        prog: '@numi flag{ setv:temps,5 rep:5{ say:$temps wait:1 chv:temps,1! } say:"Ja!|¡Ya!" }',
        ex: "«Suma a temps 1» fa pujar el temps. Per baixar, ha de ser -1.|«Suma a tiempo 1» hace subir el tiempo. Para bajar, tiene que ser -1." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Compte enrere amb el cos! Comença dret/a amb els braços amunt: <b>10</b>. A cada número, baixa una mica: 9, 8, 7… A <b>0</b> has d'estar ajupit/ida. I ara, cronòmetre: puja a poc a poc comptant 1, 2, 3… fins a 10!|¡Cuenta atrás con el cuerpo! Empieza de pie con los brazos arriba: <b>10</b>. En cada número, baja un poco: 9, 8, 7… En <b>0</b> tienes que estar agachado/a. Y ahora, cronómetro: sube despacio contando 1, 2, 3… ¡hasta 10!" },
      { k: 'stage', ph: 'repte', q: "En Numi presenta la cursa. Fes que digui <b>5, 4, 3, 2, 1</b> (un número cada segon, amb la variable <b>temps</b>) i després <b>«Ja!»</b>: llavors el cotxe surt. Com a màxim, 6 blocs!|Numi presenta la carrera. Haz que diga <b>5, 4, 3, 2, 1</b> (un número cada segundo, con la variable <b>tiempo</b>) y después <b>«¡Ya!»</b>: entonces el coche sale. ¡Como máximo, 6 bloques!",
        w: { bg: 'ciutat', sprites: [{ id: 'numi', art: 'numi', x: 60, y: -20, size: 120 }, { id: 'cotxe', art: 'cotxe', x: -150, y: -140, size: 90, prog: '@cotxe flag{ wait:2.5 if:$temps=0{ say:"Massa ràpid!|¡Demasiado rápido!" stop:all } } flag{ wait:0.5 waitu:$temps=0 glide:1.5,190,-140 }' }], vars: ['temps'], time: 7,
          goal: [{ k: 'var', v: 'temps', eq: 0 }, { k: 'said', s: 'numi', t: '5' }, { k: 'said', s: 'numi', t: '1' }, { k: 'said', s: 'numi', t: 'Ja' }, { k: 'running', t: 4.8 }] },
        edit: ['numi'], hats: ['flag'], pal: ['setv', 'chv', 'rep', 'wait', 'say', 'sound'], varNames: VN, texts: ['Ja!|¡Ya!'], max: 6,
        sol: '@numi flag{ setv:temps,5 rep:5{ say:$temps wait:1 chv:temps,-1 } say:"Ja!|¡Ya!" }',
        hint: "Posa temps a 5. Dins d'un «repeteix 5»: «digues temps», «espera 1» i «suma a temps -1». Al final, «digues Ja!».|Pon tiempo a 5. Dentro de un «repite 5»: «di tiempo», «espera 1» y «suma a tiempo -1». Al final, «di ¡Ya!»." },
      { k: 'stage', ph: 'repte', q: "El videojoc de la poma ja funciona. Fes que en Numi sigui el <b>rellotge</b>: temps a 6, que baixi 1 cada segon i, a 0, que digui que s'ha acabat el temps i <b>aturi tot</b>.|El videojuego de la manzana ya funciona. Haz que Numi sea el <b>reloj</b>: tiempo a 6, que baje 1 cada segundo y, en 0, que diga que se acabó el tiempo y <b>pare todo</b>.",
        w: { bg: 'parc', sprites: [GAT, { id: 'poma', art: 'poma', x: 0, y: 150, prog: POMA_OK }, { id: 'numi', art: 'numi', x: 170, y: 40, size: 80 }], vars: ['punts', 'temps'], time: 9, goal: [{ k: 'stopped' }, { k: 'var', v: 'temps', eq: 0 }, { k: 'var', v: 'punts', min: 2 }, { k: 'said', s: 'numi' }] },
        edit: ['numi'], hats: ['flag'], pal: ['setv', 'chv', 'rep', 'wait', 'say', 'stop', 'sound'], varNames: VN, texts: [TEMPS],
        sol: `@numi flag{ setv:temps,6 rep:6{ wait:1 chv:temps,-1 } say:"${TEMPS}" stop:all }`,
        hint: "És com el compte enrere d'abans, però al final, després del «digues», cal «atura tot».|Es como la cuenta atrás de antes, pero al final, después del «di», hace falta «para todo»." },
      { k: 'stage', ph: 'repte', q: "Quant triga el cotxe? Ara surt quan acaba de dir «3, 2, 1…». <b>Posa el cronòmetre a zero</b> just quan surt i, en arribar a la bandera, guarda'l a <b>segons</b> i fes que el cotxe ho digui.|¿Cuánto tarda el coche? Ahora sale cuando acaba de decir «3, 2, 1…». <b>Pon el cronómetro a cero</b> justo al salir y, al llegar a la bandera, guárdalo en <b>segundos</b> y haz que el coche lo diga.",
        w: { bg: 'ciutat', sprites: [{ id: 'cotxe', art: 'cotxe', x: -190, y: -150 }, { id: 'bandera', art: 'bandera', x: 190, y: -135, prog: '@bandera flag{ forever{ next wait:0.3 } }' }], vars: ['segons'], time: 8, goal: [{ k: 'var', v: 'segons', min: 2, max: 3.5 }, { k: 'said', s: 'cotxe', t: '2.8' }] },
        edit: ['cotxe'], hats: ['flag'], pal: ['timer0', 'setv', 'chv', 'say', 'move', 'wait', 'until', 'sound'], ops: ['timer'], varNames: VN,
        prog: '@cotxe flag{ say:"3, 2, 1…|3, 2, 1…",2 until:touch:bandera{ move:4 } }',
        sol: '@cotxe flag{ say:"3, 2, 1…|3, 2, 1…",2 timer0 until:touch:bandera{ move:4 } setv:segons,timer say:$segons }',
        hint: "«Posa el cronòmetre a zero» va just abans del «repeteix fins que». Al final: «posa segons a…» (toca el número i tria <b>cronòmetre</b>) i «digues segons».|«Pon el cronómetro a cero» va justo antes del «repite hasta que». Al final: «pon segundos a…» (toca el número y elige <b>cronómetro</b>) y «di segundos»." },
      { k: 'stage', ph: 'repte', q: "Aquest rellotge diu «S'ha acabat el temps!» quan encara queden <b>5 segons</b>. <b>Troba l'error i arregla'l.</b>|Este reloj dice «¡Se acabó el tiempo!» cuando aún quedan <b>5 segundos</b>. <b>Encuentra el error y arréglalo.</b>",
        w: { bg: 'escenari', sprites: [{ id: 'numi', art: 'numi', x: 0, y: -40, size: 130 }], vars: ['temps'], time: 12, goal: [{ k: 'var', v: 'temps', eq: 0 }, { k: 'said', s: 'numi', t: 'temps' }, { k: 'running', t: 9.8 }] },
        edit: ['numi'], hats: ['flag'], pal: ['setv', 'chv', 'rep', 'wait', 'say', 'sound'], varNames: VN, texts: [TEMPS],
        prog: `@numi flag{ setv:temps,10 rep:5{ say:$temps wait:1 chv:temps,-1 } say:"${TEMPS}" }`,
        sol: `@numi flag{ setv:temps,10 rep:10{ say:$temps wait:1 chv:temps,-1 } say:"${TEMPS}" }`,
        hint: "Si el temps comença a 10 i cada volta en resta 1, quantes voltes calen per arribar a 0?|Si el tiempo empieza en 10 y cada vuelta resta 1, ¿cuántas vueltas hacen falta para llegar a 0?" },
      { k: 'screate', ph: 'crea', name: 'Contrarellotge al bosc|Contrarreloj en el bosque',
        q: "<b>El teu videojoc contrarellotge!</b> Toca la papallona tantes vegades com puguis abans que s'acabi el temps. Tu decideixes quant de temps hi ha i com vola.|<b>¡Tu videojuego contrarreloj!</b> Toca la mariposa tantas veces como puedas antes de que se acabe el tiempo. Tú decides cuánto tiempo hay y cómo vuela.",
        crit: ["La papallona vola i, si la toques, suma punts|La mariposa vuela y, si la tocas, suma puntos", "En Numi fa un compte enrere que baixa cada segon|Numi hace una cuenta atrás que baja cada segundo", "Quan el temps arriba a 0, diu alguna cosa i atura tot|Cuando el tiempo llega a 0, dice algo y para todo"],
        w: { bg: 'bosc', sprites: [{ id: 'papallona', art: 'papallona', x: -100, y: 40, dir: 60 }, { id: 'numi', art: 'numi', x: 170, y: -100, size: 80 }], vars: ['punts', 'temps'],
          input: clicks('papallona', [1, 2, 3, 4]), time: 9, goal: [{ k: 'stopped' }, { k: 'var', v: 'temps', eq: 0 }, { k: 'var', v: 'punts', min: 2 }, { k: 'said', s: 'numi' }] },
        edit: ['papallona', 'numi'], hats: ['flag', 'click'], pal: ['setv', 'chv', 'rep', 'forever', 'wait', 'say', 'stop', 'sound', 'move', 'turn', 'bounce', 'next', 'glide', 'goto'], varNames: VN, texts: [TEMPS, 'Atrapada!|¡Atrapada!'],
        sol: `@papallona flag{ setv:punts,0 forever{ move:4 bounce next } } click{ chv:punts,1 sound:pop } @numi flag{ setv:temps,6 rep:6{ wait:1 chv:temps,-1 } say:"${TEMPS}" stop:all }`,
        check: P => { const has = (id, h, k) => ((P[id] || {})[h] || []).some(function w(l) { return (l || []).some(b => b.k === k || w(b.b) || w(b.e)); });
          if (!has('papallona', 'click', 'chv')) return "Quan toques la papallona, ha de sumar punts.|Al tocar la mariposa, tiene que sumar puntos.";
          if (!has('numi', 'flag', 'wait') || !has('numi', 'flag', 'chv')) return "El compte enrere d'en Numi ha d'esperar 1 segon i restar 1 a temps a cada volta.|La cuenta atrás de Numi tiene que esperar 1 segundo y restar 1 a tiempo en cada vuelta.";
          return null; } },
      { k: 'quiz', ph: 'tanca', q: "Què hi ha dins del bucle d'un compte enrere?|¿Qué hay dentro del bucle de una cuenta atrás?",
        opts: ["Espera 1 segon i suma a temps -1|Espera 1 segundo y suma a tiempo -1", "Posa temps a 10|Pon tiempo a 10", "Atura tot|Para todo"], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "Vols saber <b>quant has trigat</b> a fer una cursa. Què fas servir?|Quieres saber <b>cuánto has tardado</b> en hacer una carrera. ¿Qué usas?",
        opts: ["El cronòmetre, posat a zero en sortir|El cronómetro, puesto a cero al salir", "Un compte enrere que comença a 0|Una cuenta atrás que empieza en 0", "La variable vides|La variable vidas"], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 4 · Projecte: la mascota virtual ---------- */
  { id: 'g6-4', t: 'Projecte: la mascota virtual|Proyecto: la mascota virtual', min: 45, proj: true, badge: 'g_mascota',
    learn: ["Una mascota virtual està feta de variables: la gana puja sola amb el temps i els botons la fan baixar.|Una mascota virtual está hecha de variables: el hambre sube sola con el tiempo y los botones la hacen bajar.",
      "Amb «si gana > 5… si no…», la mascota canvia de vestit segons el valor de la variable.|Con «si hambre > 5… si no…», la mascota cambia de disfraz según el valor de la variable.",
      "Un projecte gran es fa a trossos: primer el pla, després cada part, i provar-la abans de passar a la següent.|Un proyecto grande se hace a trozos: primero el plan, después cada parte, y probarla antes de pasar a la siguiente."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "Quin guió fa que una variable <b>pugi 1 cada segon</b>, tota sola, sense parar?|¿Qué guion hace que una variable <b>suba 1 cada segundo</b>, ella sola, sin parar?",
        opts: ["Per sempre: espera 1 segon, suma 1|Por siempre: espera 1 segundo, suma 1", "Per sempre: suma 1|Por siempre: suma 1", "Espera 1 segon, posa a 1|Espera 1 segundo, pon a 1"], a: 0,
        ex: "Sense l'espera, sumaria 1 a cada fotograma: 30 cada segon!|Sin la espera, sumaría 1 en cada fotograma: ¡30 cada segundo!" },
      { k: 'story', ph: 'missio', who: 'both', scene: 'poble', title: 'El racó dels petits|El rincón de los pequeños',
        t: "L'últim dia de la fira, la caseta tindrà un racó per als més petits: una <b>mascota virtual</b>! Té gana, s'avorreix i canvia de cara. Els petits la cuidaran tocant la pantalla. I la programareu vosaltres!|El último día de la feria, la caseta tendrá un rincón para los más pequeños: ¡una <b>mascota virtual</b>! Tiene hambre, se aburre y cambia de cara. Los pequeños la cuidarán tocando la pantalla. ¡Y la programaréis vosotros!" },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy', scene: 'taller',
        t: "BIP! He mirat per dins una mascota virtual: està feta de <b>variables</b>! La <b>gana</b> puja sola amb el temps, la <b>poma</b> la fa baixar i la mascota posa una cara o una altra segons el número. Ho farem a trossos.|¡BIP! He mirado por dentro una mascota virtual: ¡está hecha de <b>variables</b>! El <b>hambre</b> sube sola con el tiempo, la <b>manzana</b> la hace bajar y la mascota pone una cara u otra según el número. Lo haremos a trozos." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'La mascota|La mascota', t: 'Feta de variables|Hecha de variables', anim: 'g6pet',
          x: "La mascota té una variable, <b>gana</b>. Cada segon puja 1. Quan toques la poma, baixa. I la cara depèn del número: amb poca gana està contenta; amb molta, té gana.|La mascota tiene una variable, <b>hambre</b>. Cada segundo sube 1. Cuando tocas la manzana, baja. Y la cara depende del número: con poca hambre está contenta; con mucha, tiene hambre." },
        { k: 'Tros 1|Trozo 1', t: 'La gana puja sola|El hambre sube sola',
          media: { k: 'stage', w: { bg: 'parc', sprites: PET(), vars: ['gana'] }, prog: GANA, varNames: VN, time: 6 },
          x: "Un guió amb <b>per sempre</b> i <b>espera 1 segon</b> fa pujar la gana tota sola: 1, 2, 3… Mira el marcador de dalt.|Un guion con <b>por siempre</b> y <b>espera 1 segundo</b> hace subir el hambre sola: 1, 2, 3… Mira el marcador de arriba." },
        { k: 'Tros 2 i 3|Trozo 2 y 3', t: 'La poma i la cara|La manzana y la cara',
          media: { k: 'stage', w: { bg: 'parc', sprites: PET(), vars: ['gana'], input: [{ t: 5.5, click: 'poma' }] }, prog: `${GANA} flag{ forever{ if:$gana>3{ costume:2 } else{ costume:1 } } } @poma click{ chv:gana,-3 sound:pop }`, varNames: VN, time: 8 },
          x: "<b>Si gana > 3</b>, posa el vestit 2 (té gana); <b>si no</b>, el vestit 1 (contenta). Quan algú toca la poma, la gana baixa 3 i la cara canvia. Els vestits de la mascota: <b>1</b> contenta, <b>2</b> té gana, <b>3</b> dorm, <b>4</b> trista.|<b>Si hambre > 3</b>, pon el disfraz 2 (tiene hambre); <b>si no</b>, el disfraz 1 (contenta). Cuando alguien toca la manzana, el hambre baja 3 y la cara cambia. Los disfraces de la mascota: <b>1</b> contenta, <b>2</b> tiene hambre, <b>3</b> duerme, <b>4</b> triste." },
        { k: 'Compte!|¡Cuidado!', t: 'Una gana negativa?|¿Un hambre negativa?',
          media: { k: 'stage', w: { bg: 'parc', sprites: PET(), vars: ['gana'], input: clicks('poma', [1.5, 2, 2.5, 3]) }, prog: `${GANA} @poma click{ chv:gana,-3 sound:pop }`, varNames: VN, time: 5 },
          x: "Si els petits toquen la poma moltes vegades, la gana baixa de 0: -3, -6… Una gana negativa no té sentit! Un «si gana < 0: posa gana a 0» ho arregla.|Si los pequeños tocan la manzana muchas veces, el hambre baja de 0: -3, -6… ¡Un hambre negativa no tiene sentido! Un «si hambre < 0: pon hambre a 0» lo arregla.",
          bad: "Toques la poma 4 vegades → gana = -10|Tocas la manzana 4 veces → hambre = -10", good: "Si gana < 0 → posa gana a 0|Si hambre < 0 → pon hambre a 0" }
      ] },
      { k: 'unplug', ph: 'mans', ico: '📝', title: 'El pla de la mascota|El plan de la mascota',
        t: "Abans de programar, fes el pla en un paper (si vols, amb algú de casa).|Antes de programar, haz el plan en un papel (si quieres, con alguien de casa).",
        steps: ["Dibuixa la teva mascota i posa-li un nom.|Dibuja tu mascota y ponle un nombre.",
          "Tria les seves variables: <b>gana</b> i una altra (alegria, son, set…).|Elige sus variables: <b>hambre</b> y otra (alegría, sueño, sed…).",
          "Per a cada variable: com puja sola? Quin botó la fa baixar?|Para cada variable: ¿cómo sube sola? ¿Qué botón la hace bajar?",
          "Quina cara posa i quan? Per exemple: si gana > 5, cara de gana.|¿Qué cara pone y cuándo? Por ejemplo: si hambre > 5, cara de hambre."],
        tip: "Un bon pla t'estalvia molts errors: després només has de passar-lo a blocs, tros a tros.|Un buen plan te ahorra muchos errores: después solo tienes que pasarlo a bloques, trozo a trozo." },
      { k: 'seq', ph: 'mans', q: "Un projecte gran es fa a trossos. <b>Ordena els trossos</b> de la mascota virtual.|Un proyecto grande se hace a trozos. <b>Ordena los trozos</b> de la mascota virtual.",
        items: ["Fer el pla en un paper|Hacer el plan en un papel", "La gana puja sola cada segon|El hambre sube sola cada segundo", "La poma fa baixar la gana|La manzana hace bajar el hambre", "La cara canvia segons la gana|La cara cambia según el hambre", "Provar-la amb un company/a i millorar-la|Probarla con un compañero/a y mejorarla"],
        ex: "Primer el pla. Després cada tros, i el proves abans de passar al següent. Al final, la prova de veritat: amb una altra persona.|Primero el plan. Después cada trozo, y lo pruebas antes de pasar al siguiente. Al final, la prueba de verdad: con otra persona." },
      { k: 'sfree', ph: 'prova', q: "Aquesta és la mascota de la caseta. Toca <b>Comença</b> i cuida-la: toca la poma i la pilota, i toca la mascota perquè digui quanta gana té. Fixa't en el marcador!|Esta es la mascota de la caseta. Toca <b>Empieza</b> y cuídala: toca la manzana y la pelota, y toca la mascota para que diga cuánta hambre tiene. ¡Fíjate en el marcador!",
        w: { bg: 'parc', sprites: PET(), vars: ['gana', 'alegria'], time: 60 }, varNames: VN, prog: PET_FULL },
      { k: 'quiz', ph: 'prova', q: "La gana val <b>6</b>. Quin vestit porta la mascota amb aquest guió?|El hambre vale <b>6</b>. ¿Qué disfraz lleva la mascota con este guion?",
        art: CH('@mascota flag{ forever{ if:$gana>5{ costume:2 } else{ costume:1 } } }', [{ id: 'mascota', art: 'mascota' }]),
        opts: ["El 2: té gana|El 2: tiene hambre", "L'1: contenta|El 1: contenta", "Cap: el guió no fa res|Ninguno: el guion no hace nada"], a: 0,
        ex: "6 és més gran que 5: la condició diu que sí i es posa el vestit 2.|6 es mayor que 5: la condición dice que sí y se pone el disfraz 2." },
      { k: 'sspot', ph: 'investiga', q: "La gana arriba a 10, però la mascota <b>mai no posa cara de gana</b>. <b>Toca el bloc que s'equivoca.</b>|El hambre llega a 10, pero la mascota <b>nunca pone cara de hambre</b>. <b>Toca el bloque que se equivoca.</b>",
        w: { bg: 'parc', sprites: PET(), vars: ['gana'] }, varNames: VN,
        prog: `${GANA} flag{ forever{ if:$gana>50!{ costume:2 } else{ costume:1 } } }`,
        ex: "La gana no arriba mai a 50, i la condició sempre diu que no. Amb un número més petit (gana > 5) sí que funciona.|El hambre nunca llega a 50, y la condición siempre dice que no. Con un número más pequeño (hambre > 5) sí que funciona." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de mascota! Quan diguem un número de gana, posa la cara: de 0 a 5, <b>somriu</b>; més de 5, <b>frega't la panxa</b> amb cara de gana. 2… 7… 4… 9… I ara, una poma: «gana menys 3»!|¡Haz de mascota! Cuando digamos un número de hambre, pon la cara: de 0 a 5, <b>sonríe</b>; más de 5, <b>frótate la barriga</b> con cara de hambre. 2… 7… 4… 9… Y ahora, una manzana: «¡hambre menos 3!»" },
      { k: 'stage', ph: 'repte', q: "Tros 1: la gana. Quan comença, posa <b>gana a 0</b> i, després, <b>per sempre</b>: espera 1 segon i suma 1 a gana.|Trozo 1: el hambre. Al empezar, pon <b>hambre a 0</b> y, después, <b>por siempre</b>: espera 1 segundo y suma 1 a hambre.",
        w: { bg: 'parc', sprites: PET(), vars: ['gana'], time: 5.5, goal: [{ k: 'var', v: 'gana', min: 4, max: 6 }, { k: 'running', t: 5.4 }] },
        edit: ['mascota'], hats: ['flag'], pal: ['setv', 'chv', 'forever', 'wait', 'rep', 'costume', 'say'], varNames: VN, sol: GANA,
        hint: "Sense «espera 1», la gana puja 30 cada segon! L'espera va dins del «per sempre».|Sin «espera 1», ¡el hambre sube 30 cada segundo! La espera va dentro del «por siempre»." },
      { k: 'stage', ph: 'repte', q: "Tros 2: el menjar. La gana ja puja sola. Programa la <b>poma</b>: quan la toquis, ha de <b>restar 3</b> a gana (suma -3) i fer un so.|Trozo 2: la comida. El hambre ya sube sola. Programa la <b>manzana</b>: cuando la toques, tiene que <b>restar 3</b> al hambre (suma -3) y hacer un sonido.",
        w: { bg: 'parc', sprites: PET(GANA), vars: ['gana'], input: [{ t: 4.2, click: 'poma' }], time: 5.5, goal: [{ k: 'var', v: 'gana', eq: 2 }, { k: 'running', t: 5.4 }] },
        edit: ['poma'], hats: ['click'], pal: ['chv', 'setv', 'sound', 'say', 'size', 'chsize'], varNames: VN,
        sol: '@poma click{ chv:gana,-3 sound:pop }', hint: "Al guió «Quan toco aquest personatge» de la poma, posa «suma a gana» i canvia el 1 per <b>-3</b>.|En el guion «Al tocar este personaje» de la manzana, pon «suma a hambre» y cambia el 1 por <b>-3</b>." },
      { k: 'stage', ph: 'repte', q: "Tros 3: la cara. El segon guió ja té «si gana > 3… si no…». Posa-hi a dins els vestits: <b>vestit 2</b> (té gana) si gana > 3 i, si no, <b>vestit 1</b> (contenta).|Trozo 3: la cara. El segundo guion ya tiene «si hambre > 3… si no…». Pon dentro los disfraces: <b>disfraz 2</b> (tiene hambre) si hambre > 3 y, si no, <b>disfraz 1</b> (contenta).",
        w: { bg: 'parc', sprites: [{ ...PET()[0] }, { ...PET()[1], prog: '@poma click{ chv:gana,-3 sound:pop }' }, PET()[2]], vars: ['gana'], input: [{ t: 4.5, click: 'poma' }], time: 6, goal: [{ k: 'costumes', s: 'mascota', min: 2 }] },
        edit: ['mascota'], hats: ['flag'], pal: ['costume', 'next', 'setv', 'chv', 'forever', 'wait', 'if', 'else', 'cond+', 'say'], varNames: VN,
        prog: `${GANA} flag{ forever{ if:$gana>3{ } else{ } } }`, sol: `${GANA} flag{ forever{ if:$gana>3{ costume:2 } else{ costume:1 } } }`,
        hint: "A la part del «si», «posa el vestit 2»; a la part del «si no», «posa el vestit 1». Toca el número del vestit per canviar-lo.|En la parte del «si», «pon el disfraz 2»; en la parte del «si no», «pon el disfraz 1». Toca el número del disfraz para cambiarlo." },
      { k: 'stage', ph: 'repte', q: "Tros 4: una segona variable, l'<b>alegria</b>. Baixa sola i, quan està per sota de 3, la mascota es posa trista. Programa la <b>pilota</b>: quan la toquis, suma <b>2</b> a alegria i fa el so «boing».|Trozo 4: una segunda variable, la <b>alegría</b>. Baja sola y, cuando está por debajo de 3, la mascota se pone triste. Programa la <b>pelota</b>: cuando la toques, suma <b>2</b> a alegría y hace el sonido «boing».",
        w: { bg: 'parc', sprites: [{ ...PET()[0], prog: '@mascota flag{ setv:alegria,5 forever{ wait:1.5 chv:alegria,-1 } } flag{ forever{ if:$alegria<3{ costume:4 } else{ costume:1 } } }' }, PET()[1], PET()[2]], vars: ['alegria'],
          input: clicks('pilota', [2, 3]), time: 5, goal: [{ k: 'var', v: 'alegria', eq: 6 }, { k: 'running', t: 4.8 }] },
        edit: ['pilota'], hats: ['click'], pal: ['chv', 'setv', 'sound', 'say', 'turn', 'chy', 'wait'], varNames: VN,
        sol: '@pilota click{ chv:alegria,2 sound:boing }', hint: "És com la poma, però amb la variable <b>alegria</b> i +2.|Es como la manzana, pero con la variable <b>alegría</b> y +2." },
      { k: 'screate', ph: 'crea', name: 'La meva mascota virtual|Mi mascota virtual',
        q: "<b>Projecte final de la unitat!</b> Construeix la teva mascota virtual a partir del teu pla. El guió «si gana > 5… si no…» ja hi és: la resta la fas tu. Després, fes-la provar a un company/a.|<b>¡Proyecto final de la unidad!</b> Construye tu mascota virtual a partir de tu plan. El guion «si hambre > 5… si no…» ya está: el resto lo haces tú. Después, haz que la pruebe un compañero/a.",
        crit: ["La gana puja sola cada segon|El hambre sube sola cada segundo", "Quan toques la poma, la gana baixa|Al tocar la manzana, el hambre baja", "La mascota posa cara de gana quan gana > 5|La mascota pone cara de hambre cuando hambre > 5", "Extra: la pilota, l'alegria o un altre vestit (dorm, trista)|Extra: la pelota, la alegría u otro disfraz (duerme, triste)"],
        w: { bg: 'parc', sprites: PET(), vars: ['gana', 'alegria'], input: [{ t: 6.5, click: 'poma' }], time: 7.8, goal: [{ k: 'costumes', s: 'mascota', min: 2 }, { k: 'var', v: 'gana', max: 5 }] },
        edit: ['mascota', 'poma', 'pilota'], hats: ['flag', 'click'], pal: ['setv', 'chv', 'forever', 'wait', 'if', 'else', 'cond+', 'costume', 'next', 'say', 'think', 'sound', 'chsize', 'size', 'turn', 'chy', 'rep'], varNames: VN,
        texts: ['Ñam!|¡Ñam!', 'Tinc gana!|¡Tengo hambre!', 'Quina alegria!|¡Qué alegría!'],
        prog: '@mascota flag{ } flag{ forever{ if:$gana>5{ } else{ } } }',
        sol: `${GANA} flag{ forever{ if:$gana>5{ costume:2 } else{ costume:1 } } } @poma click{ chv:gana,-3 sound:pop say:"Ñam!|¡Ñam!",1 } @pilota click{ chv:alegria,2 sound:boing }`,
        check: P => { const has = (id, h, pred) => ((P[id] || {})[h] || []).some(function w(l) { return (l || []).some(b => pred(b) || w(b.b) || w(b.e)); });
          const up = b => b.k === 'chv' && b.v === 'gana' && !(typeof b.n === 'number' && b.n <= 0), down = b => b.k === 'chv' && b.v === 'gana' && typeof b.n === 'number' && b.n < 0;
          if (!has('mascota', 'flag', b => b.k === 'forever' && (b.b || []).some(x => x.k === 'wait') && JSON.stringify(b.b).includes('"v":"gana"'))) return "La gana ha de pujar sola: per sempre, espera 1 segon i suma 1 a gana.|El hambre tiene que subir sola: por siempre, espera 1 segundo y suma 1 a hambre.";
          if (!has('mascota', 'flag', up)) return "Falta el bloc que suma gana.|Falta el bloque que suma hambre.";
          if (!has('poma', 'click', down)) return "Quan toques la poma, la gana ha de baixar (suma un número negatiu).|Al tocar la manzana, el hambre tiene que bajar (suma un número negativo).";
          return null; } },
      { k: 'quiz', ph: 'tanca', q: "Per què la gana de la mascota puja sola?|¿Por qué el hambre de la mascota sube sola?",
        opts: ["Perquè un guió amb «per sempre» i «espera» hi suma 1 cada segon|Porque un guion con «por siempre» y «espera» le suma 1 cada segundo", "Perquè les variables sempre pugen|Porque las variables siempre suben", "Perquè la mascota menja massa|Porque la mascota come demasiado"], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "Al teu proper videojoc vols saber <b>quant falta per acabar</b>. Quina variable faràs servir?|En tu próximo videojuego quieres saber <b>cuánto falta para terminar</b>. ¿Qué variable usarás?",
        opts: ["temps, amb un compte enrere|tiempo, con una cuenta atrás", "punts|puntos", "vides|vidas"], a: 0,
        ex: "Punts, vides i temps: ja coneixes les tres variables de gairebé tots els videojocs!|Puntos, vidas y tiempo: ¡ya conoces las tres variables de casi todos los videojuegos!" },
      { k: 'feel', ph: 'tanca' }
    ] }
  ] };
})();
