/* Tech 3D · Nivell 1 · unitat 7 «Dissenyar per a persones» (m7-1 … m7-4)
   Contingut propi de Numi. Fil narratiu: el Taller de Bit rep encàrrecs de persones concretes (l'àvia Rosa, en Pol, la Nur,
   la Nil, la mestra Txell i l'escola). Disseny centrat en les persones a nivell d'infant: entrevistar, necessitats,
   accessibilitat (m7-1), esbós i mesures amb marge (m7-2), provar, retroacció i menys plàstic (m7-3) i el projecte
   «un invent per a l'escola» amb especificacions pròpies (m7-4). A m7-3 la versió 2 continua des del porta-coses desat
   a m7-2 (portafoli), si n'hi ha. Models: peces { id, t, s: [x, y, z] mm, p: centre, r: graus, c, hole }, placa 200 × 200. */
Object.assign(TBADGE, {
  m7inventor: { id: 'm7inventor', ico: '🛠️', n: "Inventor/a de l'escola|Inventor/a de la escuela", d: "Has escrit les especificacions d'un invent per a l'escola i l'has modelat pensant en qui el farà servir.|Has escrito las especificaciones de un invento para la escuela y lo has modelado pensando en quién lo usará." }
});
COURSE_UNITS[7] = (() => {
  const P = (id, t, s, p, c, o = {}) => ({ id, t, s, p, r: o.r || [0, 0, 0], c, ...o });
  const H = (id, t, s, p, o = {}) => P(id, t, s, p, '#9AA3B5', { hole: true, ...o });
  const ts = () => { try { return typeof TS_ === 'function' ? TS_() : null; } catch (e) { return null; } };
  const cl = m => JSON.parse(JSON.stringify(m));
  // l'últim model desat al portafoli des d'alguna d'aquestes sessions (per continuar-lo a la versió següent)
  const lastOf = sids => { const t = ts(); if (!t || !Array.isArray(t.port)) return null; for (let i = t.port.length - 1; i >= 0; i--) { const p = t.port[i]; if (p && p.kind === 'model' && sids.includes(p.sid) && p.model && Array.isArray(p.model.parts) && p.model.parts.length) return p; } return null; };

  /* ---------- m7-1 · persones, necessitats i accessibilitat ---------- */
  const MANEC = d => [P('manec', 'cyl', [d, d, 80], [0, 0, 40], '#3D7BF4'), H('ranura', 'box', [3, 8, 50], [0, 0, 56])];
  const RINGS = (x, d) => [20, 40, 60].map((z, i) => P('anella' + (i + 1), 'torus', [d + 4, d + 4, 4], [x, 0, z], '#5B3FD6'));
  const ACCESS = [P('prim', 'cyl', [12, 12, 80], [-30, 0, 40], '#9AA3B5'), P('gruixut', 'cyl', [30, 30, 80], [16, 0, 40], '#7C5CFF'), ...RINGS(16, 30)];
  const knob = (x, i, top) => [P('porta' + i, 'box', [26, 6, 64], [x, 6, 32], '#F3F3EE'), P('eix' + i, 'cyl', [8, 8, 14], [x, -3, 40], '#9AA3B5', { r: [90, 0, 0] }), ...top];
  const KNOBS = [...knob(-55, 1, [P('pom', 'sph', [22, 22, 22], [-55, -18, 40], '#FF8A3D')]), ...knob(0, 2, [P('maneta', 'box', [46, 12, 10], [17, -14, 40], '#7C5CFF')]), ...knob(55, 3, [P('pomet', 'sph', [12, 12, 12], [55, -14, 40], '#2FB36D')])];
  const TOYB = [P('cos', 'box', [50, 26, 16], [0, 0, 14], '#3D7BF4'), P('cabina', 'box', [24, 22, 12], [-4, 0, 28], '#5BC0EB'),
    ...[[-15, -15], [15, -15], [-15, 15], [15, 15]].map(([x, y], i) => P('roda' + (i + 1), 'cyl', [14, 14, 6], [x, y, 7], '#2A2F3A', { r: [90, 0, 0] }))];
  const TOY = [...TOYB, P('punxa', 'cone', [8, 8, 18], [0, 0, 42], '#E8453C')];
  const TOYOK = [...TOYB, P('bola', 'sph', [12, 12, 12], [0, 0, 39], '#E8453C')];
  const GRIP = [P('prisma', 'hex', [24, 20.8, 40], [0, 0, 20], '#2FB36D'), H('forat', 'cyl', [8, 8, 44], [0, 0, 20])];
  const TAG = [P('placa', 'box', [40, 40, 3], [0, 0, 1.5], '#F7C531'), P('cor', 'heart', [24, 24, 3], [0, -3, 4.5], '#E8453C'), H('forat', 'cyl', [6, 6, 5], [0, 14, 1.5])];

  /* ---------- m7-2 · esbós, mesures i marge ---------- */
  const GOMA = [P('goma', 'box', [40, 20, 10], [0, 0, 5], '#F3F3EE'), P('funda', 'box', [22, 21, 11], [9, 0, 5.5], '#3D7BF4')];
  const PINZ = [P('base', 'box', [96, 32, 4], [0, 0, 2], '#A0683A'), P('tub1', 'tube', [26, 26, 50], [-32, 0, 29], '#3D7BF4', { w: 2 }), P('tub2', 'tube', [26, 26, 40], [0, 0, 24], '#EC5FA8', { w: 2 }), P('tub3', 'tube', [26, 26, 50], [32, 0, 29], '#2FB36D', { w: 2 })];
  const XS = [-22, 0, 22];
  const BLOC = d => [P('bloc', 'box', [70, 30, 40], [0, 0, 20], '#EC5FA8'), ...XS.map((x, i) => H('f' + (i + 1), 'cyl', [d, d, 32], [x, 0, 26]))];
  // el porta-retoladors amb tres retoladors posats (el porta-retoladors i els seus forats en un grup: els retoladors no es tallen)
  const MARK = [...BLOC(16).map(p => ({ ...p, g: 'pr' })), ...XS.flatMap((x, i) => [P('r' + (i + 1), 'cyl', [14, 14, 60], [x, 0, 40], '#F3F3EE'), P('t' + (i + 1), 'cyl', [15, 15, 20], [x, 0, 76], ['#E8453C', '#3D7BF4', '#2FB36D'][i])])];
  const STAND = y => [P('base', 'box', [80, 60, 6], [0, 0, 3], '#14A3B8'), P('topall', 'box', [80, 6, 12], [0, -27, 12], '#E8453C'), P('respatller', 'box', [80, 24, 30], [0, y, 21], '#3D7BF4')];

  /* ---------- m7-3 · provar, millorar i menys plàstic ---------- */
  const TALL = w => [P('peu', 'cyl', [w, w, 6], [0, 0, 3], '#F7C531'), P('tub', 'tube', [22, 22, 84], [0, 0, 48], '#5BC0EB', { w: 2 })];
  const CLIPS = (h, s) => [P('caixa', 'box', [50, 50, 40], [0, 0, 20], '#FF8A3D'), H('forat', 'box', [s, s, h], [0, 0, 41 - h / 2])];
  const SOLID = x => [P('massis', 'cyl', [50, 50, 80], [x, 0, 40], '#FF8A3D'), H('buit', 'cyl', [30, 30, 76], [x, 0, 43])];
  const TUBE = x => [P('tub', 'tube', [50, 50, 77], [x, 0, 41.5], '#2FB36D', { w: 2 }), P('fons', 'cyl', [50, 50, 3], [x, 0, 1.5], '#2FB36D')];
  const ECO = [...SOLID(-35).map(p => ({ ...p, id: p.id + 'A', g: 'a' })), ...TUBE(35)];

  /* ---------- m7-4 · invents per a l'escola ---------- */
  const HOOK = py => [P('esquena', 'box', [12, 90, 12], [-24, 0, 6], '#7C5CFF'), P('bras', 'box', [44, 12, 12], [-2, -39, 6], '#7C5CFF'), P('punta', 'box', [12, 30, 12], [14, py, 6], '#7C5CFF'),
    H('c1', 'cyl', [5, 5, 14], [-24, 32, 6]), H('c2', 'cyl', [5, 5, 14], [-24, 8, 6])];
  const BOOK = [P('base', 'box', [70, 80, 5], [0, 0, 2.5], '#FF8A3D'), P('paret', 'box', [70, 5, 80], [0, -37.5, 40], '#FF8A3D'),
    P('reforc1', 'wedge', [30, 6, 40], [-24, -20, 25], '#E8453C', { r: [0, 0, 90] }), P('reforc2', 'wedge', [30, 6, 40], [24, -20, 25], '#E8453C', { r: [0, 0, 90] })];
  const ORG = [P('caixa', 'box', [90, 60, 40], [0, 0, 20], '#14A3B8'), H('gran', 'box', [52, 54, 38], [-16, 0, 22]), H('petit1', 'box', [26, 25, 38], [27, -14.5, 22]), H('petit2', 'box', [26, 25, 38], [27, 14.5, 22])];
  // els tres invents junts (l'organitzador, girat 90° perquè hi càpiguen; cada invent en un grup perquè els forats no tallin els altres)
  const ORG2 = [P('caixa', 'box', [60, 90, 40], [0, 0, 20], '#14A3B8'), H('gran', 'box', [54, 52, 38], [0, -16, 22]), H('petit1', 'box', [25, 26, 38], [-14.5, 27, 22]), H('petit2', 'box', [25, 26, 38], [14.5, 27, 22])];
  const mv = (l, dx, dy, g, pre) => l.map(p => ({ ...p, id: pre + p.id, p: [p.p[0] + dx, p.p[1] + dy, p.p[2]], g }));
  const INVENTS = [...mv(HOOK(-19), -66, 0, 'h', 'pj'), ...mv(BOOK, -2, 0, 'b', 'al'), ...mv(ORG2, 64, 0, 'o', 'or')];

  return {
  t: 'Dissenyar per a persones|Diseñar para personas', d: 'Objectes útils|Objetos útiles', color: '#EC5FA8',
  s: [
    /* ============ Sessió 1 · Qui ho farà servir? ============ */
    { id: 'm7-1', t: 'Qui ho farà servir?|¿Quién lo usará?', min: 42,
      learn: ["Un bon disseny comença per la persona: primer l'escoltes amb una entrevista i després imagines l'objecte.|Un buen diseño empieza por la persona: primero la escuchas con una entrevista y después imaginas el objeto.",
        "Les necessitats són el que l'objecte ha de fer sí o sí; els desitjos, el que estaria bé que fes.|Las necesidades son lo que el objeto tiene que hacer sí o sí; los deseos, lo que estaría bien que hiciera.",
        "Un objecte accessible el pot fer servir tothom: mànecs gruixuts, formes que es noten tocant, colors que contrasten i cap punxa.|Un objeto accesible lo puede usar todo el mundo: mangos gruesos, formas que se notan al tocar, colores que contrastan y ninguna punta."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "A la unitat passada vas preparar models per a la Nuvi. Per què una paret de <b>0,5 mm</b> no és bona idea?|En la unidad pasada preparaste modelos para Nuvi. ¿Por qué una pared de <b>0,5 mm</b> no es buena idea?",
          opts: ["És tan prima que la impressora no la pot fer bé i es trencaria|Es tan fina que la impresora no la puede hacer bien y se rompería", 'Gasta massa plàstic|Gasta demasiado plástico', 'No es pot pintar de colors|No se puede pintar de colores'], a: 0,
          ex: "Les parets han de fer almenys 2 mm perquè la Nuvi hi pugui posar prou plàstic i la peça sigui forta.|Las paredes tienen que medir al menos 2 mm para que Nuvi pueda poner suficiente plástico y la pieza sea fuerte." },
        { k: 'quiz', ph: 'recorda', q: 'Quin fitxer necessita la Nuvi per imprimir el teu model?|¿Qué archivo necesita Nuvi para imprimir tu modelo?',
          opts: ['Un fitxer STL|Un archivo STL', 'Una foto del model|Una foto del modelo', 'Un document de text|Un documento de texto'], a: 0,
          ex: "L'STL descriu la superfície del model amb triangles i guarda les mides en mil·límetres.|El STL describe la superficie del modelo con triángulos y guarda las medidas en milímetros." },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'fab', title: 'Encàrrecs amb nom i cognom|Encargos con nombre y apellido',
          t: "Han arribat cartes al taller! L'<b>àvia Rosa</b> té les mans rígides i li costa agafar la cullera. En <b>Pol</b> es cansa amb els llapis prims. La <b>Nur</b>, que hi veu molt poc, vol trobar el seu penjador de l'escola. A partir d'ara no dissenyarem per a «algú»: dissenyarem <b>per a persones de veritat</b>. I el primer pas no és modelar… és <b>escoltar</b>!|¡Han llegado cartas al taller! La <b>abuela Rosa</b> tiene las manos rígidas y le cuesta coger la cuchara. <b>Pol</b> se cansa con los lápices finos. <b>Nur</b>, que ve muy poco, quiere encontrar su percha de la escuela. A partir de ahora no diseñaremos para «alguien»: diseñaremos <b>para personas de verdad</b>. Y el primer paso no es modelar… ¡es <b>escuchar</b>!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Disseny per a persones|Diseño para personas', t: "Primer la persona, després l'objecte|Primero la persona, después el objeto", anim: 'm7pers',
            x: "Els bons dissenyadors no comencen pel que els agrada a ells: comencen per la <b>persona</b> que farà servir l'objecte. El camí té quatre passos que es repeteixen: <b>escoltar</b> (què li passa?), <b>imaginar</b> idees, <b>construir</b> un model i <b>provar-lo</b> amb ella. Si alguna cosa no va bé, tornem a escoltar.|Los buenos diseñadores no empiezan por lo que les gusta a ellos: empiezan por la <b>persona</b> que usará el objeto. El camino tiene cuatro pasos que se repiten: <b>escuchar</b> (¿qué le pasa?), <b>imaginar</b> ideas, <b>construir</b> un modelo y <b>probarlo</b> con ella. Si algo no va bien, volvemos a escuchar.",
            tip: "Això es diu <b>disseny centrat en les persones</b>.|Esto se llama <b>diseño centrado en las personas</b>." },
          { k: "L'entrevista|La entrevista", t: 'Preguntes que fan parlar|Preguntas que hacen hablar', anim: 'm7ask',
            x: "Per saber què necessita algú, li fem una <b>entrevista</b>. Les millors preguntes són <b>obertes</b>: no es contesten amb un sí o un no. «Com ho fas ara?», «Què és el que més et costa?», «On ho faràs servir?». Després cal <b>escoltar</b> sense interrompre i <b>apuntar</b> les respostes.|Para saber qué necesita alguien, le hacemos una <b>entrevista</b>. Las mejores preguntas son <b>abiertas</b>: no se contestan con un sí o un no. «¿Cómo lo haces ahora?», «¿Qué es lo que más te cuesta?», «¿Dónde lo usarás?». Después hay que <b>escuchar</b> sin interrumpir y <b>apuntar</b> las respuestas.",
            bad: "«Oi que t'agradaria una cullera blava?»|«¿A que te gustaría una cuchara azul?»", good: "«Explica'm com agafes la cullera ara.»|«Explícame cómo coges la cuchara ahora.»" },
          { k: 'Necessitats|Necesidades', t: 'El que cal i el que agradaria|Lo que hace falta y lo que gustaría', anim: 'm7need',
            x: "De l'entrevista en surten dues llistes. Les <b>necessitats</b> són el que l'objecte <b>ha de</b> fer sí o sí: «el mànec ha de ser gruixut perquè l'àvia el pugui agafar». Els <b>desitjos</b> són el que estaria bé: «m'agradaria que fos lila». Primer es resolen les necessitats; després, si es pot, els desitjos.|De la entrevista salen dos listas. Las <b>necesidades</b> son lo que el objeto <b>tiene que</b> hacer sí o sí: «el mango tiene que ser grueso para que la abuela lo pueda coger». Los <b>deseos</b> son lo que estaría bien: «me gustaría que fuera lila». Primero se resuelven las necesidades; después, si se puede, los deseos.",
            tip: "Una necessitat que no es compleix fa que l'objecte no serveixi. Un desig que no es compleix només fa que agradi una mica menys.|Una necesidad que no se cumple hace que el objeto no sirva. Un deseo que no se cumple solo hace que guste un poco menos." },
          { k: 'Accessibilitat|Accesibilidad', t: 'Objectes que tothom pot fer servir|Objetos que todo el mundo puede usar', media: { k: 'model', model: { parts: ACCESS } },
            x: "Un objecte és <b>accessible</b> quan el pot fer servir tothom, també qui té poca força, poca vista o és molt petit. Algunes idees: mànecs <b>gruixuts</b> i amb relleu per agafar-los bé, formes que es poden <b>reconèixer tocant</b>, colors que <b>contrasten</b> (groc i negre, blanc i vermell…) i <b>cap punxa</b> ni vora tallant.|Un objeto es <b>accesible</b> cuando lo puede usar todo el mundo, también quien tiene poca fuerza, poca vista o es muy pequeño. Algunas ideas: mangos <b>gruesos</b> y con relieve para cogerlos bien, formas que se pueden <b>reconocer al tocar</b>, colores que <b>contrastan</b> (amarillo y negro, blanco y rojo…) y <b>ninguna punta</b> ni borde cortante.",
            tip: "Tots dos mànecs són per a la mateixa cullera. Amb quin creus que l'àvia Rosa farà menys força?|Los dos mangos son para la misma cuchara. ¿Con cuál crees que la abuela Rosa hará menos fuerza?" }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🎤', title: "L'entrevista|La entrevista", t: "Per parelles: una persona fa l'entrevista i l'altra respon; després us canvieu. Qui respon pensa en algú que conegui (un avi, un germà petit, un veí) que tingui dificultats amb una cosa de cada dia.|Por parejas: una persona hace la entrevista y la otra responde; después os cambiáis. Quien responde piensa en alguien que conozca (un abuelo, un hermano pequeño, un vecino) que tenga dificultades con algo de cada día.",
          steps: ["Pregunta: «Quina cosa de cada dia li costa fer o li fa nosa?»|Pregunta: «¿Qué cosa de cada día le cuesta hacer o le molesta?»", "Pregunta: «Com ho fa ara? Ensenya-m'ho amb les mans.»|Pregunta: «¿Cómo lo hace ahora? Enséñamelo con las manos.»",
            "Pregunta: «On i quan ho fa servir?»|Pregunta: «¿Dónde y cuándo lo usa?»", "Apunta dues necessitats (ha de…) i un desig (m'agradaria…).|Apunta dos necesidades (tiene que…) y un deseo (me gustaría…)."],
          tip: "Una bona entrevistadora escolta més que no parla. Si no entens alguna cosa, pregunta: «Què vols dir?»|Una buena entrevistadora escucha más que habla. Si no entiendes algo, pregunta: «¿Qué quieres decir?»" },
        { k: 'm3look', ph: 'prova', q: "Tres poms per a la porta de l'àvia Rosa, que té les mans rígides. <b>Quin li costarà menys d'obrir?</b> Gira la vista per mirar-los bé.|Tres pomos para la puerta de la abuela Rosa, que tiene las manos rígidas. <b>¿Cuál le costará menos abrir?</b> Gira la vista para mirarlos bien.",
          model: { parts: KNOBS }, opts: ['La maneta llarga (al mig)|La manilla larga (en el medio)', "El pom rodó gran (a l'esquerra)|El pomo redondo grande (a la izquierda)", 'El pom petit (a la dreta)|El pomo pequeño (a la derecha)'], a: 0,
          ex: "Una maneta s'abaixa empenyent amb la mà oberta o fins i tot amb el colze: no cal tancar els dits ni girar el canell. Els poms rodons s'han d'agafar fort i girar.|Una manilla se baja empujando con la mano abierta o incluso con el codo: no hace falta cerrar los dedos ni girar la muñeca. Los pomos redondos hay que cogerlos fuerte y girarlos." },
        { k: 'm3look', ph: 'investiga', q: "La <b>Nil</b> té 3 anys i tot ho toca i s'ho posa a la boca. <b>Toca la peça d'aquesta joguina que li podria fer mal.</b>|<b>Nil</b> tiene 3 años y todo lo toca y se lo lleva a la boca. <b>Toca la pieza de este juguete que le podría hacer daño.</b>",
          model: { parts: TOY }, pick: 'punxa', yes: "Exacte: l'antena acaba en punxa.|Exacto: la antena acaba en punta.", no: "Aquesta peça és arrodonida. Busca'n una que acabi en punta.|Esta pieza es redondeada. Busca una que acabe en punta.",
          ex: "Per als infants petits, millor formes arrodonides i peces grans que no es puguin desenganxar.|Para los niños pequeños, mejor formas redondeadas y piezas grandes que no se puedan despegar." },
        { k: 'move', ph: 'pausa', title: 'Mans que treballen|Manos que trabajan', secs: 30, t: "Obre i tanca les mans cinc vegades, ben fort. Fes girar els canells. Ara imagina que tens les mans rígides com l'àvia Rosa: com obriries una porta? Fes veure que abaixes una maneta <b>amb el colze</b>!|Abre y cierra las manos cinco veces, bien fuerte. Haz girar las muñecas. Ahora imagina que tienes las manos rígidas como la abuela Rosa: ¿cómo abrirías una puerta? ¡Haz como si bajaras una manilla <b>con el codo</b>!" },
        { k: 'm3fix', ph: 'repte', q: "Primer encàrrec: el <b>mànec de la cullera</b> de l'àvia Rosa. Ara fa 12 mm de gruix i no el pot agafar. A l'entrevista va dir que el que millor agafa és un got petit: fes el mànec de <b>30 mm</b> de diàmetre (x i y) i deixa'l de 80 mm de llarg.|Primer encargo: el <b>mango de la cuchara</b> de la abuela Rosa. Ahora mide 12 mm de grosor y no lo puede coger. En la entrevista dijo que lo que mejor coge es un vaso pequeño: haz el mango de <b>30 mm</b> de diámetro (x e y) y déjalo de 80 mm de largo.",
          start: { parts: MANEC(12) }, fix: ['manec'], palette: ['cyl', 'hbox'],
          checks: [{ k: 'size', ax: 'x', v: 30, t: 'Fa 30 mm de gruix en x|Mide 30 mm de grosor en x' }, { k: 'size', ax: 'y', v: 30, t: 'Fa 30 mm de gruix en y|Mide 30 mm de grosor en y' }, { k: 'size', ax: 'z', v: 80, t: 'Continua fent 80 mm de llarg|Sigue midiendo 80 mm de largo' }, { k: 'hole', t: 'Conserva la ranura per a la cullera|Conserva la ranura para la cuchara' }],
          hint: "Toca el mànec i, a la pestanya Mida, escriu 30 a la X i 30 a la Y. No toquis la Z.|Toca el mango y, en la pestaña Medida, escribe 30 en la X y 30 en la Y. No toques la Z.", sol: { parts: MANEC(30) } },
        { k: 'm3build', ph: 'repte', q: "En <b>Pol</b> es cansa amb els llapis prims. Fes-li un <b>engruixidor</b>: un prisma hexagonal de <b>24 mm</b> d'ample i 40 mm d'alt amb un <b>forat rodó de 8 mm</b> que el travessi de dalt a baix, perquè hi passi el llapis. Segueix el fantasma.|<b>Pol</b> se cansa con los lápices finos. Hazle un <b>engrosador</b>: un prisma hexagonal de <b>24 mm</b> de ancho y 40 mm de alto con un <b>agujero redondo de 8 mm</b> que lo atraviese de arriba abajo, para que pase el lápiz. Sigue el fantasma.",
          palette: ['hex', 'hcyl'], target: { parts: GRIP },
          checks: [{ k: 'match', target: { parts: GRIP }, th: 0.85, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'hole', t: 'El llapis hi pot passar (té un forat)|El lápiz puede pasar (tiene un agujero)' }, { k: 'onplate' }],
          hint: "Afegeix el prisma i, a Mida, posa 24 a la X, 20,8 a la Y i 40 a la Z. El forat rodó: 8 × 8 mm i més alt que el prisma (44 mm), al centre.|Añade el prisma y, en Medida, pon 24 en la X, 20,8 en la Y y 40 en la Z. El agujero redondo: 8 × 8 mm y más alto que el prisma (44 mm), en el centro.",
          sol: { parts: GRIP } },
        { k: 'm3build', ph: 'repte', q: "La <b>Nur</b> hi veu molt poc, però amb els dits ho nota tot. Fes-li una <b>etiqueta tàctil</b> per al penjador: a sobre de la placa groga, un <b>cor en relleu</b> de 3 mm i un <b>forat</b> per penjar-la. Groc i vermell: colors que contrasten!|<b>Nur</b> ve muy poco, pero con los dedos lo nota todo. Hazle una <b>etiqueta táctil</b> para la percha: encima de la placa amarilla, un <b>corazón en relieve</b> de 3 mm y un <b>agujero</b> para colgarla. Amarillo y rojo: ¡colores que contrastan!",
          start: { parts: [TAG[0]] }, palette: ['heart', 'star', 'hcyl'], target: { parts: TAG },
          checks: [{ k: 'match', target: { parts: TAG }, th: 0.9, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'hole', t: 'Té un forat per penjar-la|Tiene un agujero para colgarla' }, { k: 'colors', min: 2, t: 'Dos colors que contrasten|Dos colores que contrastan' }, { k: 'one' }],
          hint: "El cor: 24 × 24 × 3 mm, a y = −3 i z = 3 (just a sobre de la placa). El forat rodó: 6 mm, a y = 14.|El corazón: 24 × 24 × 3 mm, en y = −3 y z = 3 (justo encima de la placa). El agujero redondo: 6 mm, en y = 14.",
          sol: { parts: TAG } },
        { k: 'm3fix', ph: 'repte', extra: true, q: "Ara arregla la joguina de la Nil: canvia la <b>punxa</b> de l'antena per una <b>bola</b> rodona que toqui la cabina.|Ahora arregla el juguete de Nil: cambia la <b>punta</b> de la antena por una <b>bola</b> redonda que toque la cabina.",
          start: { parts: TOY }, fix: ['punxa'], palette: ['sph'],
          checks: [{ k: 'count', t: 'cone', max: 0, txt: 'No queda cap punxa (cap con)|No queda ninguna punta (ningún cono)' }, { k: 'count', t: 'sph', min: 1, txt: 'Hi ha una bola a dalt|Hay una bola arriba' }, { k: 'one' }, { k: 'onplate' }],
          hint: "Esborra el con (la paperera) i afegeix una esfera de 12 × 12 × 12 mm. A Posició: x = 0, y = 0, z = 33, perquè toqui la cabina.|Borra el cono (la papelera) y añade una esfera de 12 × 12 × 12 mm. En Posición: x = 0, y = 0, z = 33, para que toque la cabina.",
          sol: { parts: TOYOK } },
        { k: 'm3free', ph: 'crea', q: "<b>El teu primer encàrrec.</b> Pensa en la persona de la teva entrevista i dissenya-li un objecte senzill que l'ajudi: un mànec gruixut, una etiqueta tàctil, un agafador… Fes-lo a la mida de les seves mans.|<b>Tu primer encargo.</b> Piensa en la persona de tu entrevista y diséñale un objeto sencillo que la ayude: un mango grueso, una etiqueta táctil, un agarrador… Hazlo a la medida de sus manos.",
          name: 'El meu primer encàrrec|Mi primer encargo',
          crit: ['Saps per a qui és i quina necessitat resol|Sabes para quién es y qué necesidad resuelve', 'La mida està pensada per a les seves mans|El tamaño está pensado para sus manos', 'No té punxes ni vores tallants|No tiene puntas ni bordes cortantes'],
          checks: [{ k: 'onplate' }, { k: 'one' }], sol: { parts: [...MANEC(30), ...RINGS(0, 30)] } },
        { k: 'quiz', ph: 'tanca', q: 'Quina és una bona pregunta per a una entrevista?|¿Cuál es una buena pregunta para una entrevista?', opts: ["«Com ho fas ara, això?»|«¿Cómo lo haces ahora?»", "«Oi que t'agrada el meu invent?»|«¿A que te gusta mi invento?»", "«Vols que sigui blau, sí o no?»|«¿Quieres que sea azul, sí o no?»"], a: 0,
          ex: "És una pregunta oberta: fa que la persona expliqui com ho fa i on li costa.|Es una pregunta abierta: hace que la persona explique cómo lo hace y dónde le cuesta." },
        { k: 'quiz', ph: 'tanca', q: 'Un objecte és <b>accessible</b> quan…|Un objeto es <b>accesible</b> cuando…', opts: ['El pot fer servir tothom, també qui té poca força o poca vista|Lo puede usar todo el mundo, también quien tiene poca fuerza o poca vista', 'És molt car|Es muy caro', "Només el pot fer servir qui l'ha dissenyat|Solo lo puede usar quien lo ha diseñado"], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },

    /* ============ Sessió 2 · Esbós i mesures ============ */
    { id: 'm7-2', t: 'Esbós i mesures|Boceto y medidas', min: 43,
      learn: ["Un esbós és un dibuix ràpid de davant i de dalt amb les cotes: les mides importants en mil·límetres.|Un boceto es un dibujo rápido de delante y de arriba con las cotas: las medidas importantes en milímetros.",
        "Per mesurar amb el regle, l'objecte toca el 0 i es mira de cara: cada ratlleta és 1 mm.|Para medir con la regla, el objeto toca el 0 y se mira de frente: cada rayita es 1 mm.",
        "Un forat ha de ser una mica més gran que el que hi entra: al taller deixem 2 mm de marge.|Un agujero tiene que ser un poco más grande que lo que entra: en el taller dejamos 2 mm de margen."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "La setmana passada vas fer una entrevista. Què és una <b>necessitat</b>?|La semana pasada hiciste una entrevista. ¿Qué es una <b>necesidad</b>?",
          opts: ["El que l'objecte ha de fer sí o sí|Lo que el objeto tiene que hacer sí o sí", 'El color preferit de la persona|El color preferido de la persona', 'Una cosa que estaria bé però no cal|Algo que estaría bien pero no hace falta'], a: 0,
          ex: "Les necessitats van primer; els desitjos (com el color preferit), si es pot.|Las necesidades van primero; los deseos (como el color preferido), si se puede." },
        { k: 'm3look', ph: 'recorda', q: "Tots dos mànecs són per a la mateixa cullera. <b>Quin agafarà millor algú amb poca força?</b>|Los dos mangos son para la misma cuchara. <b>¿Cuál cogerá mejor alguien con poca fuerza?</b>",
          model: { parts: ACCESS }, opts: ['El gruixut, amb anelles|El grueso, con anillos', 'El prim|El fino'], a: 0,
          ex: "El mànec gruixut s'agafa amb tota la mà i les anelles fan que no rellisqui.|El mango grueso se coge con toda la mano y los anillos hacen que no resbale." },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'fab', title: "L'encàrrec de la Txell|El encargo de Txell",
          t: "La mestra de plàstica, la <b>Txell</b>, té un problema: els retoladors rodolen per les taules i acaben a terra. Ens demana un <b>porta-retoladors</b>. Ja ha mesurat un retolador: fa <b>14 mm</b> de gruix. Avui treballarem com els dissenyadors de veritat: primer un <b>esbós amb mides</b> en paper i després el model. Si les mides són bones, la Nuvi l'encertarà a la primera!|La maestra de plástica, <b>Txell</b>, tiene un problema: los rotuladores ruedan por las mesas y acaban en el suelo. Nos pide un <b>portarrotuladores</b>. Ya ha medido un rotulador: mide <b>14 mm</b> de grosor. Hoy trabajaremos como los diseñadores de verdad: primero un <b>boceto con medidas</b> en papel y después el modelo. ¡Si las medidas son buenas, Nuvi lo acertará a la primera!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: "L'esbós|El boceto", t: 'Un dibuix ràpid amb les mides|Un dibujo rápido con las medidas', anim: 'm7sketch',
            x: "Un <b>esbós</b> és un dibuix ràpid, en paper i a llapis, per pensar com serà l'objecte. No cal que sigui bonic: cal que s'entengui. Normalment es dibuixa <b>de davant</b> i <b>de dalt</b>, i s'hi escriuen les mides importants.|Un <b>boceto</b> es un dibujo rápido, en papel y a lápiz, para pensar cómo será el objeto. No hace falta que sea bonito: hace falta que se entienda. Normalmente se dibuja <b>de delante</b> y <b>de arriba</b>, y se escriben las medidas importantes.",
            tip: "Esborrar està permès: l'esbós serveix per equivocar-se sense gastar plàstic.|Borrar está permitido: el boceto sirve para equivocarse sin gastar plástico." },
          { k: 'Mesurar|Medir', t: 'El regle, en mil·límetres|La regla, en milímetros', anim: 'm7ruler',
            x: "Per mesurar, l'objecte ha de tocar el <b>0</b> del regle (no la vora!) i s'ha de mirar on acaba, de cara i no de costat. Cada ratlleta és <b>1 mm</b> i cada número és 1 cm, que són <b>10 mm</b>. El retolador arriba a l'1 i quatre ratlletes més: <b>14 mm</b>.|Para medir, el objeto tiene que tocar el <b>0</b> de la regla (¡no el borde!) y hay que mirar dónde acaba, de frente y no de lado. Cada rayita es <b>1 mm</b> y cada número es 1 cm, que son <b>10 mm</b>. El rotulador llega al 1 y cuatro rayitas más: <b>14 mm</b>." },
          { k: 'Les cotes|Las cotas', t: "Cada mida, un número de l'editor|Cada medida, un número del editor", media: { k: 'model', model: { parts: MARK } },
            x: "Les mides de l'esbós es diuen <b>cotes</b>: una fletxa amb un número. Al taller, cada cota es converteix en un número de la pestanya <b>Mida</b>: l'<b>amplada</b> va a la X, la <b>fondària</b> a la Y i l'<b>alçada</b> a la Z. Aquest és el porta-retoladors de l'esbós: 70 × 30 × 40 mm, amb tres forats.|Las medidas del boceto se llaman <b>cotas</b>: una flecha con un número. En el taller, cada cota se convierte en un número de la pestaña <b>Medida</b>: la <b>anchura</b> va a la X, el <b>fondo</b> a la Y y la <b>altura</b> a la Z. Este es el portarrotuladores del boceto: 70 × 30 × 40 mm, con tres agujeros.",
            tip: "Amb el botó del regle (a sota de la vista) veuràs les cotes de la peça que toquis.|Con el botón de la regla (debajo de la vista) verás las cotas de la pieza que toques." },
          { k: 'El marge|El margen', t: 'Una mica més gran perquè hi càpiga|Un poco más grande para que quepa', anim: 'm7marge',
            x: "Si fas un forat de 14 mm per a un retolador de 14 mm, <b>no hi entrarà</b>: els forats impresos sempre surten una mica més petits del que has dibuixat. Per això deixem <b>marge</b>: el forat ha de ser una mica més gran que l'objecte. Al taller farem servir <b>2 mm</b>: 14 + 2 = <b>16 mm</b>.|Si haces un agujero de 14 mm para un rotulador de 14 mm, <b>no entrará</b>: los agujeros impresos siempre salen un poco más pequeños de lo que has dibujado. Por eso dejamos <b>margen</b>: el agujero tiene que ser un poco más grande que el objeto. En el taller usaremos <b>2 mm</b>: 14 + 2 = <b>16 mm</b>.",
            bad: "Forat = mida de l'objecte|Agujero = medida del objeto", good: "Forat = mida de l'objecte + 2 mm|Agujero = medida del objeto + 2 mm" }
        ] },
        { k: 'unplug', ph: 'mans', ico: '📏', title: 'Mesura i esbossa|Mide y esboza', t: 'Amb un regle i la fitxa (o un full):|Con una regla y la ficha (o una hoja):',
          steps: ['Tria tres objectes petits: un llapis, una goma i un retolador.|Elige tres objetos pequeños: un lápiz, una goma y un rotulador.', 'Mesura el gruix i la llargada de cada un en mil·límetres i apunta-ho.|Mide el grosor y el largo de cada uno en milímetros y apúntalo.',
            "Dibuixa l'esbós d'un porta-coses per a aquests objectes, de davant i de dalt.|Dibuja el boceto de un portacosas para estos objetos, de delante y de arriba.", "Escriu les cotes: les mides de la peça i dels forats (amb 2 mm de marge!).|Escribe las cotas: las medidas de la pieza y de los agujeros (¡con 2 mm de margen!)."],
          tip: "Per mesurar el gruix d'un objecte rodó, posa'l dret sobre el regle i mira'l des de dalt.|Para medir el grosor de un objeto redondo, ponlo de pie sobre la regla y míralo desde arriba." },
        { k: 'm3look', ph: 'prova', q: "Aquesta goma és a la placa i la mirem des de dalt. Cada quadret fa 10 mm. <b>Quant fa d'amplada (x) i de fondària (y)?</b>|Esta goma está en la placa y la miramos desde arriba. Cada cuadrito mide 10 mm. <b>¿Cuánto mide de anchura (x) y de fondo (y)?</b>",
          model: { parts: GOMA }, view: 'top', lock: true, opts: ['40 × 20 mm|40 × 20 mm', '20 × 40 mm|20 × 40 mm', '4 × 2 mm|4 × 2 mm'], a: 0,
          ex: "D'esquerra a dreta ocupa 4 quadrets (40 mm) i de davant a darrere, 2 quadrets (20 mm). L'amplada sempre va primer.|De izquierda a derecha ocupa 4 cuadritos (40 mm) y de delante a detrás, 2 cuadritos (20 mm). La anchura siempre va primero." },
        { k: 'm3look', ph: 'investiga', q: "L'esbós del porta-pinzells diu que els tres tubs fan <b>50 mm</b> d'alt. Un està mal fet. <b>Toca el tub mal mesurat.</b> Mira'ls de davant per comparar-los.|El boceto del portapinceles dice que los tres tubos miden <b>50 mm</b> de alto. Uno está mal hecho. <b>Toca el tubo mal medido.</b> Míralos de delante para compararlos.",
          model: { parts: PINZ }, pick: 'tub2', no: "Aquest fa els 50 mm de l'esbós. Compara'ls des de davant.|Este mide los 50 mm del boceto. Compáralos desde delante.",
          ex: "El del mig només fa 40 mm: algú va escriure 40 en lloc de 50. Per això cal tornar a mirar l'esbós abans d'imprimir.|El del medio solo mide 40 mm: alguien escribió 40 en lugar de 50. Por eso hay que volver a mirar el boceto antes de imprimir." },
        { k: 'move', ph: 'pausa', title: 'El regle humà|La regla humana', secs: 30, t: "Fes amb els dits un espai d'<b>1 cm</b>… ara de <b>5 cm</b>… ara, amb les mans, de <b>30 cm</b>, com un regle llarg. Tanca els ulls i torna-ho a provar. Obre'ls: t'has acostat a la mida?|Haz con los dedos un espacio de <b>1 cm</b>… ahora de <b>5 cm</b>… ahora, con las manos, de <b>30 cm</b>, como una regla larga. Cierra los ojos y vuelve a probar. Ábrelos: ¿te has acercado a la medida?" },
        { k: 'm3build', ph: 'repte', q: "<b>Del paper a la pantalla.</b> L'esbós de la Txell diu: bloc de <b>70 mm</b> d'amplada, <b>30 mm</b> de fondària i <b>40 mm</b> d'alçada. Aquí no hi ha fantasma: canvia les mides del cub perquè siguin aquestes.|<b>Del papel a la pantalla.</b> El boceto de Txell dice: bloque de <b>70 mm</b> de anchura, <b>30 mm</b> de fondo y <b>40 mm</b> de altura. Aquí no hay fantasma: cambia las medidas del cubo para que sean estas.",
          start: { parts: [P('a1', 'box', [20, 20, 20], [0, 0, 10], '#EC5FA8')] }, palette: ['box'],
          checks: [{ k: 'size', ax: 'x', v: 70, t: 'Amplada (x): 70 mm|Anchura (x): 70 mm' }, { k: 'size', ax: 'y', v: 30, t: 'Fondària (y): 30 mm|Fondo (y): 30 mm' }, { k: 'size', ax: 'z', v: 40, t: 'Alçada (z): 40 mm|Altura (z): 40 mm' }, { k: 'onplate' }],
          hint: "Toca el cub i, a la pestanya Mida, escriu 70 a la X, 30 a la Y i 40 a la Z.|Toca el cubo y, en la pestaña Medida, escribe 70 en la X, 30 en la Y y 40 en la Z.", sol: { parts: [P('a1', 'box', [70, 30, 40], [0, 0, 20], '#EC5FA8')] } },
        { k: 'm3build', ph: 'repte', q: "<b>Forats amb marge.</b> El retolador fa 14 mm. Fes tres forats rodons de <b>16 mm</b> (14 + 2 de marge) i 32 mm d'alt, que comencin a <b>z = 10</b> (així queda fons per sota). Van a x = −22, x = 0 i x = 22.|<b>Agujeros con margen.</b> El rotulador mide 14 mm. Haz tres agujeros redondos de <b>16 mm</b> (14 + 2 de margen) y 32 mm de alto, que empiecen en <b>z = 10</b> (así queda fondo por debajo). Van en x = −22, x = 0 y x = 22.",
          start: { parts: [BLOC(16)[0]] }, palette: ['hcyl'], target: { parts: BLOC(16) },
          checks: [{ k: 'part', t: 'cyl', hole: true, s: [16, 16, 32], at: [-22, 0, null], txt: "Forat de 16 mm a x = −22|Agujero de 16 mm en x = −22" }, { k: 'part', t: 'cyl', hole: true, s: [16, 16, 32], at: [0, 0, null], txt: 'Forat de 16 mm a x = 0|Agujero de 16 mm en x = 0' },
            { k: 'part', t: 'cyl', hole: true, s: [16, 16, 32], at: [22, 0, null], txt: 'Forat de 16 mm a x = 22|Agujero de 16 mm en x = 22' }, { k: 'onplate' }],
          hint: "Afegeix un forat rodó i posa-li 16 × 16 × 32 mm. A Posició: x = −22, y = 0, z = 10. Després duplica'l i canvia la x de la còpia (0 i 22).|Añade un agujero redondo y ponle 16 × 16 × 32 mm. En Posición: x = −22, y = 0, z = 10. Después duplícalo y cambia la x de la copia (0 y 22).",
          sol: { parts: BLOC(16) } },
        { k: 'm3build', ph: 'repte', q: "La tauleta de la biblioteca fa 9 mm de gruix. Al suport, la <b>ranura</b> entre el topall vermell i el respatller blau ha de fer <b>12 mm</b> (9 + 3 de marge). Ara fa massa. <b>Mou el respatller</b> fins que la ranura faci 12 mm.|La tableta de la biblioteca mide 9 mm de grosor. En el soporte, la <b>ranura</b> entre el tope rojo y el respaldo azul tiene que medir <b>12 mm</b> (9 + 3 de margen). Ahora mide demasiado. <b>Mueve el respaldo</b> hasta que la ranura mida 12 mm.",
          start: { parts: STAND(20) }, palette: ['box'],
          checks: [{ k: 'part', t: 'box', s: [80, 24, 30], at: [0, 0, null], txt: 'Ranura de 12 mm entre el topall i el respatller|Ranura de 12 mm entre el tope y el respaldo' }, { k: 'one' }, { k: 'onplate' }],
          hint: "El topall acaba a y = −24. Si la ranura fa 12 mm, el respatller comença a y = −12. Com que fa 24 mm de fondària, el seu centre (la y de Posició) és a y = 0.|El tope acaba en y = −24. Si la ranura mide 12 mm, el respaldo empieza en y = −12. Como mide 24 mm de fondo, su centro (la y de Posición) está en y = 0.",
          sol: { parts: STAND(0) } },
        { k: 'm3build', ph: 'repte', extra: true, q: "<b>⭐ El porta-gomes.</b> La goma fa 40 × 20 mm. Fes-li un forat (una caixa forat) de <b>42 × 22 mm</b>, amb 12 mm d'alt i començant a <b>z = 3</b>: així queda un fons de 3 mm i el forat sobresurt una mica per dalt.|<b>⭐ El portagomas.</b> La goma mide 40 × 20 mm. Hazle un agujero (una caja agujero) de <b>42 × 22 mm</b>, con 12 mm de alto y empezando en <b>z = 3</b>: así queda un fondo de 3 mm y el agujero sobresale un poco por arriba.",
          start: { parts: [P('caixa', 'box', [50, 30, 13], [0, 0, 6.5], '#2FB36D')] }, palette: ['hbox'],
          checks: [{ k: 'part', t: 'box', hole: true, s: [42, 22, 12], txt: 'Forat de 42 × 22 mm (la goma + el marge)|Agujero de 42 × 22 mm (la goma + el margen)' }, { k: 'hole' }, { k: 'flatbase', min: 1000, t: 'Té fons: la base continua plana|Tiene fondo: la base sigue plana' }],
          hint: "Afegeix una caixa forat i posa-li 42 × 22 × 12 mm. A Posició: x = 0, y = 0, z = 3.|Añade una caja agujero y ponle 42 × 22 × 12 mm. En Posición: x = 0, y = 0, z = 3.",
          sol: { parts: [P('caixa', 'box', [50, 30, 13], [0, 0, 6.5], '#2FB36D'), H('forat', 'box', [42, 22, 12], [0, 0, 9])] } },
        { k: 'm3free', ph: 'crea', q: "<b>El teu porta-coses a mida.</b> Tria un objecte que hagis mesurat (un llapis, una goma, unes tisores…) i dissenya-li un suport a partir del teu esbós. Els forats: la mida de l'objecte + 2 mm.|<b>Tu portacosas a medida.</b> Elige un objeto que hayas medido (un lápiz, una goma, unas tijeras…) y diséñale un soporte a partir de tu boceto. Los agujeros: la medida del objeto + 2 mm.",
          name: 'El meu porta-coses|Mi portacosas',
          crit: ["L'has dibuixat abans en un esbós amb les cotes|Lo has dibujado antes en un boceto con las cotas", "Els forats fan la mida de l'objecte + 2 mm|Los agujeros miden la medida del objeto + 2 mm", 'Té una base plana i no es tomba|Tiene una base plana y no se vuelca'],
          checks: [{ k: 'hole' }, { k: 'flatbase', min: 400, t: 'Té una base plana per recolzar-se|Tiene una base plana para apoyarse' }, { k: 'one' }, { k: 'onplate' }],
          sol: { parts: [P('a1', 'box', [60, 30, 30], [0, 0, 15], '#7C5CFF'), H('a2', 'cyl', [10, 10, 26], [-15, 0, 18]), H('a3', 'cyl', [16, 16, 26], [12, 0, 18])] } },
        { k: 'quiz', ph: 'tanca', q: 'Un llapis fa <b>8 mm</b> de gruix. De quina mida faràs el forat?|Un lápiz mide <b>8 mm</b> de grosor. ¿De qué medida harás el agujero?', opts: ['10 mm|10 mm', '8 mm|8 mm', '6 mm|6 mm'], a: 0,
          ex: '8 mm del llapis + 2 mm de marge = 10 mm.|8 mm del lápiz + 2 mm de margen = 10 mm.' },
        { k: 'quiz', ph: 'tanca', q: 'Què és una <b>cota</b>?|¿Qué es una <b>cota</b>?', opts: ["Una mida escrita a l'esbós, amb una fletxa i un número|Una medida escrita en el boceto, con una flecha y un número", 'Un color del taller|Un color del taller', 'Una peça forat|Una pieza agujero'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },

    /* ============ Sessió 3 · Provar i millorar ============ */
    { id: 'm7-3', t: 'Provar i millorar|Probar y mejorar', min: 44,
      learn: ["Iterar és fer versions: es prova cada versió amb les persones i se'n fa una de millor.|Iterar es hacer versiones: se prueba cada versión con las personas y se hace una mejor.",
        "Una bona retroacció és amable i concreta: dues estrelles (el que funciona) i un desig (com millorar-ho).|Una buena retroalimentación es amable y concreta: dos estrellas (lo que funciona) y un deseo (cómo mejorarlo).",
        "Per gastar menys plàstic, buidem les peces deixant parets de 2-3 mm i les fem tan grans com calgui, ni més ni menys.|Para gastar menos plástico, vaciamos las piezas dejando paredes de 2-3 mm y las hacemos tan grandes como haga falta, ni más ni menos."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Un retolador fa 14 mm. De quina mida faràs el forat?|Un rotulador mide 14 mm. ¿De qué medida harás el agujero?', opts: ['16 mm|16 mm', '14 mm|14 mm', '12 mm|12 mm'], a: 0,
          ex: '14 mm + 2 mm de marge = 16 mm.|14 mm + 2 mm de margen = 16 mm.' },
        { k: 'quiz', ph: 'recorda', q: "On escrius les mides de l'esbós a l'editor?|¿Dónde escribes las medidas del boceto en el editor?", opts: ['A la pestanya Mida: amplada a la X, fondària a la Y i alçada a la Z|En la pestaña Medida: anchura en la X, fondo en la Y y altura en la Z', 'A la pestanya Color|En la pestaña Color', 'Enlloc: es fa a ull|En ningún sitio: se hace a ojo'], a: 0 },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'fab', title: 'Tres notes a la bústia|Tres notas en el buzón',
          t: "La Nuvi va imprimir la <b>versió 1</b> del porta-retoladors (la que vam fer abans d'aprendre el marge) i la classe de la Txell l'ha provat tota la setmana. Ens han deixat tres notes: «Els retoladors hi entren massa justos», «El porta-raspalls del lavabo es tomba» i «Quina estona per imprimir-ho, i quant de plàstic!». No són males notícies: són <b>pistes</b>. Avui farem les <b>versions 2</b>!|Nuvi imprimió la <b>versión 1</b> del portarrotuladores (la que hicimos antes de aprender el margen) y la clase de Txell la ha probado toda la semana. Nos han dejado tres notas: «Los rotuladores entran demasiado justos», «El portacepillos del lavabo se vuelca» y «¡Cuánto rato para imprimirlo, y cuánto plástico!». No son malas noticias: son <b>pistas</b>. ¡Hoy haremos las <b>versiones 2</b>!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Iterar|Iterar', t: 'Versió 1, versió 2, versió 3…|Versión 1, versión 2, versión 3…', anim: 'm7iter',
            x: "Cap dissenyador l'encerta a la primera. Es fa una <b>versió</b>, es <b>prova</b> amb les persones que la faran servir, s'apunta què falla i es fa una versió millor. Repetir aquest cercle es diu <b>iterar</b>. A cada volta, l'objecte és una mica millor.|Ningún diseñador lo acierta a la primera. Se hace una <b>versión</b>, se <b>prueba</b> con las personas que la usarán, se apunta qué falla y se hace una versión mejor. Repetir este círculo se llama <b>iterar</b>. En cada vuelta, el objeto es un poco mejor.",
            tip: "Desa cada versió amb un número (v1, v2…): així les pots comparar.|Guarda cada versión con un número (v1, v2…): así las puedes comparar." },
          { k: 'La retroacció|La retroalimentación', t: 'Dir-ho perquè ajudi|Decirlo para que ayude', anim: 'm7feed',
            x: "Quan proves l'objecte d'un company/a, li dones <b>retroacció</b>: què funciona i què milloraries. Una bona retroacció és <b>amable</b>, <b>concreta</b> i diu <b>com</b> millorar. Una manera fàcil: <b>dues estrelles i un desig</b>, dues coses que funcionen i una proposta.|Cuando pruebas el objeto de un compañero/a, le das <b>retroalimentación</b>: qué funciona y qué mejorarías. Una buena retroalimentación es <b>amable</b>, <b>concreta</b> y dice <b>cómo</b> mejorar. Una manera fácil: <b>dos estrellas y un deseo</b>, dos cosas que funcionan y una propuesta.",
            bad: "«És lleig.»|«Es feo.»", good: "«La base és molt estable. Els forats són justos: fes-los 2 mm més grans.»|«La base es muy estable. Los agujeros son justos: hazlos 2 mm más grandes.»" },
          { k: 'Menys plàstic|Menos plástico', t: 'La mateixa feina amb menys material|El mismo trabajo con menos material', media: { k: 'model', model: { parts: ECO } },
            x: "Tot el que imprimim gasta <b>plàstic</b>, <b>temps</b> i <b>energia</b>. Un dissenyador responsable fa que l'objecte faci la seva feina amb el mínim de material: el <b>buida</b> per dins (deixant parets de 2-3 mm), el fa només <b>tan gran com cal</b> i no imprimeix proves que no calen.|Todo lo que imprimimos gasta <b>plástico</b>, <b>tiempo</b> y <b>energía</b>. Un diseñador responsable hace que el objeto haga su trabajo con el mínimo de material: lo <b>vacía</b> por dentro (dejando paredes de 2-3 mm), lo hace solo <b>tan grande como hace falta</b> y no imprime pruebas que no hacen falta.",
            tip: "Tots dos porta-llapis aguanten els mateixos llapis. El massís (esquerra) gasta uns 103 cm³ de plàstic; el tub amb fons (dreta), uns 29 cm³.|Los dos portalápices aguantan los mismos lápices. El macizo (izquierda) gasta unos 103 cm³ de plástico; el tubo con fondo (derecha), unos 29 cm³." },
          { k: 'Estable|Estable', t: 'Que no es tombi|Que no se vuelque', anim: 'm7stable',
            x: "Un objecte alt amb la base petita es tomba amb un copet. Si fas la <b>base més ampla</b> que la part de dalt, o el fas més baix, queda <b>estable</b>. Pensa com t'aguantes tu: amb els peus junts et desequilibres; amb els peus oberts, no.|Un objeto alto con la base pequeña se vuelca con un golpecito. Si haces la <b>base más ancha</b> que la parte de arriba, o lo haces más bajo, queda <b>estable</b>. Piensa cómo te aguantas tú: con los pies juntos te desequilibras; con los pies abiertos, no." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '⭐', title: 'Dues estrelles i un desig|Dos estrellas y un deseo', t: "Per parelles, intercanvieu l'esbós (o el porta-coses que vau desar la sessió passada) i feu-vos de provadors:|Por parejas, intercambiad el boceto (o el portacosas que guardasteis la sesión pasada) y haced de probadores:",
          steps: ["Mira'l bé i pensa per a qui és i què ha de fer.|Míralo bien y piensa para quién es y qué tiene que hacer.", 'Escriu dues estrelles: dues coses que funcionen bé.|Escribe dos estrellas: dos cosas que funcionan bien.',
            'Escriu un desig: una millora concreta, amb números si pots.|Escribe un deseo: una mejora concreta, con números si puedes.', 'Torneu-vos els papers i llegiu-los en silenci. Quina millora faràs?|Devolveos los papeles y leedlos en silencio. ¿Qué mejora harás?'],
          tip: "Parla del disseny, no de la persona: «el forat és petit», no «ho has fet malament».|Habla del diseño, no de la persona: «el agujero es pequeño», no «lo has hecho mal»." },
        { k: 'm3look', ph: 'prova', q: "Tots dos porta-llapis aguanten els mateixos llapis. <b>Quin gasta menys plàstic?</b>|Los dos portalápices aguantan los mismos lápices. <b>¿Cuál gasta menos plástico?</b>",
          model: { parts: ECO }, opts: [{ model: { parts: SOLID(0) }, t: 'El massís|El macizo' }, { model: { parts: TUBE(0) }, t: 'El tub amb fons|El tubo con fondo' }], a: 1,
          ex: "El tub té parets de 2 mm i un fons de 3 mm: gasta menys d'un terç del plàstic del massís i fa la mateixa feina.|El tubo tiene paredes de 2 mm y un fondo de 3 mm: gasta menos de un tercio del plástico del macizo y hace el mismo trabajo." },
        { k: 'm3look', ph: 'investiga', q: "El porta-raspalls del lavabo cau cada dos per tres. <b>Per què?</b> Mira'l de costat.|El portacepillos del lavabo se cae cada dos por tres. <b>¿Por qué?</b> Míralo de lado.",
          model: { parts: TALL(24) }, view: 'front', opts: ['La base és tan estreta com el tub, i el tub és molt alt|La base es tan estrecha como el tubo, y el tubo es muy alto', 'És massa baix|Es demasiado bajo', 'Té massa forats|Tiene demasiados agujeros'], a: 0,
          ex: "Un objecte alt amb una base petita es tomba de seguida. Amb una base més ampla, el problema s'acaba.|Un objeto alto con una base pequeña se vuelca enseguida. Con una base más ancha, el problema se acaba." },
        { k: 'move', ph: 'pausa', title: 'Estàtues estables|Estatuas estables', secs: 30, t: "Posa't dret amb els peus <b>junts</b> i tanca els ulls: notes com et balanceges? Ara obre els peus a l'amplada de les espatlles: molt més estable! Prova-ho també a peu coix… <b>Base ampla, estàtua estable!</b>|Ponte de pie con los pies <b>juntos</b> y cierra los ojos: ¿notas cómo te balanceas? Ahora abre los pies a la anchura de los hombros: ¡mucho más estable! Pruébalo también a la pata coja… <b>¡Base ancha, estatua estable!</b>" },
        { k: 'm3fix', ph: 'repte', q: "Primera nota: <b>els retoladors hi entren massa justos</b>. A la versió 1, els forats fan 14 mm. Fes la versió 2: els tres forats, de <b>16 mm</b>.|Primera nota: <b>los rotuladores entran demasiado justos</b>. En la versión 1, los agujeros miden 14 mm. Haz la versión 2: los tres agujeros, de <b>16 mm</b>.",
          start: { parts: BLOC(14) }, fix: ['f1'], palette: ['hcyl'],
          checks: [{ k: 'part', t: 'cyl', hole: true, s: [16, 16, 32], at: [-22, 0, null], txt: "Forat de l'esquerra: 16 mm|Agujero de la izquierda: 16 mm" }, { k: 'part', t: 'cyl', hole: true, s: [16, 16, 32], at: [0, 0, null], txt: 'Forat del mig: 16 mm|Agujero del medio: 16 mm' },
            { k: 'part', t: 'cyl', hole: true, s: [16, 16, 32], at: [22, 0, null], txt: 'Forat de la dreta: 16 mm|Agujero de la derecha: 16 mm' }, { k: 'onplate' }],
          hint: "Toca cada forat i, a Mida, canvia el 14 per 16 a la X i a la Y. No toquis la Z.|Toca cada agujero y, en Medida, cambia el 14 por 16 en la X y en la Y. No toques la Z.", sol: { parts: BLOC(16) } },
        { k: 'm3fix', ph: 'repte', q: "Segona nota: <b>el porta-raspalls es tomba</b>. El peu fa només 24 mm, igual que el tub. Fes-lo de <b>60 mm</b> de diàmetre perquè quedi estable.|Segunda nota: <b>el portacepillos se vuelca</b>. El pie mide solo 24 mm, igual que el tubo. Hazlo de <b>60 mm</b> de diámetro para que quede estable.",
          start: { parts: TALL(24) }, fix: ['peu'], palette: ['cyl'],
          checks: [{ k: 'flatbase', min: 2500, t: 'La base és prou ampla per no tombar-se (uns 60 mm)|La base es bastante ancha para no volcarse (unos 60 mm)' }, { k: 'size', ax: 'z', v: 90, t: "Continua fent 90 mm d'alt|Sigue midiendo 90 mm de alto" }, { k: 'one' }, { k: 'onplate' }],
          hint: "Toca el peu groc i, a Mida, escriu 60 a la X i 60 a la Y. L'alçada (6 mm) no cal canviar-la.|Toca el pie amarillo y, en Medida, escribe 60 en la X y 60 en la Y. La altura (6 mm) no hace falta cambiarla.", sol: { parts: TALL(60) } },
        { k: 'm3build', ph: 'repte', q: "Tercera nota: <b>massa plàstic!</b> La caixa de clips és gairebé massissa: només té un forat de 10 mm a dalt. Buida-la: fes el forat de <b>44 × 44 mm</b> i 38 mm d'alt, començant a <b>z = 3</b>. Quedaran parets i fons de 3 mm.|Tercera nota: <b>¡demasiado plástico!</b> La caja de clips es casi maciza: solo tiene un agujero de 10 mm arriba. Vacíala: haz el agujero de <b>44 × 44 mm</b> y 38 mm de alto, empezando en <b>z = 3</b>. Quedarán paredes y fondo de 3 mm.",
          start: { parts: CLIPS(11, 40) }, palette: ['hbox'],
          checks: [{ k: 'vol', max: 35, t: 'Gasta com a molt 35 cm³ de plàstic (ara en gasta uns 82)|Gasta como mucho 35 cm³ de plástico (ahora gasta unos 82)' }, { k: 'wall', min: 2 }, { k: 'hole', t: 'Continua sent una caixa buida per dins|Sigue siendo una caja hueca por dentro' }, { k: 'size', ax: 'z', v: 40, t: "Continua fent 40 mm d'alt|Sigue midiendo 40 mm de alto" }],
          hint: "Toca el forat. A Mida: 44 × 44 × 38 mm. A Posició: x = 0, y = 0, z = 3.|Toca el agujero. En Medida: 44 × 44 × 38 mm. En Posición: x = 0, y = 0, z = 3.", sol: { parts: CLIPS(38, 44) } },
        { k: 'm3build', ph: 'repte', extra: true, q: "<b>⭐ El porta-llapis lleuger.</b> Aquest porta-llapis massís gasta uns 103 cm³. Fes la versió 2 amb un <b>tub</b> de 50 mm de diàmetre i un <b>fons</b> de 3 mm: menys de 40 cm³ i 80 mm d'alt.|<b>⭐ El portalápices ligero.</b> Este portalápices macizo gasta unos 103 cm³. Haz la versión 2 con un <b>tubo</b> de 50 mm de diámetro y un <b>fondo</b> de 3 mm: menos de 40 cm³ y 80 mm de alto.",
          start: { parts: SOLID(0) }, palette: ['tube', 'cyl'],
          checks: [{ k: 'vol', max: 40, t: 'Gasta menys de 40 cm³ de plàstic|Gasta menos de 40 cm³ de plástico' }, { k: 'count', t: 'tube', min: 1, txt: 'Fa servir un tub|Usa un tubo' }, { k: 'flatbase', min: 1500, t: 'Té un fons pla perquè no caiguin els llapis|Tiene un fondo plano para que no caigan los lápices' }, { k: 'size', ax: 'z', v: 80, t: "Fa 80 mm d'alt|Mide 80 mm de alto" }, { k: 'one' }],
          hint: "Esborra les dues peces. Afegeix un cilindre de 50 × 50 × 3 mm (el fons) i un tub de 50 × 50 × 77 mm, amb la z a 3, just a sobre del fons.|Borra las dos piezas. Añade un cilindro de 50 × 50 × 3 mm (el fondo) y un tubo de 50 × 50 × 77 mm, con la z en 3, justo encima del fondo.",
          sol: { parts: TUBE(0) } },
        { k: 'm3free', ph: 'crea', q: "<b>La versió 2.</b> Aquí tens el teu porta-coses de la sessió passada (o el de la Txell, si no en vas desar cap). Fes-hi <b>almenys una millora</b> de les que t'han proposat: més marge, una base més ampla, menys plàstic…|<b>La versión 2.</b> Aquí tienes tu portacosas de la sesión pasada (o el de Txell, si no guardaste ninguno). Hazle <b>al menos una mejora</b> de las que te han propuesto: más margen, una base más ancha, menos plástico…",
          name: 'El meu porta-coses (versió 2)|Mi portacosas (versión 2)', get start() { const l = lastOf(['m7-3', 'm7-2']); return l ? { parts: cl(l.model.parts) } : { parts: BLOC(14) }; },
          crit: ["Has fet almenys una millora de la retroacció|Has hecho al menos una mejora de la retroalimentación", 'Gasta menys plàstic o funciona millor que la versió 1|Gasta menos plástico o funciona mejor que la versión 1', 'Continua tocant la placa, amb base plana|Sigue tocando la placa, con base plana'],
          checks: [{ k: 'onplate' }, { k: 'flatbase', min: 400, t: 'Té una base plana per recolzar-se|Tiene una base plana para apoyarse' }, { k: 'one' }], sol: { parts: BLOC(16) } },
        { k: 'quiz', ph: 'tanca', q: 'Què vol dir <b>iterar</b>?|¿Qué quiere decir <b>iterar</b>?', opts: ['Millorar un disseny fent versions i provant-les|Mejorar un diseño haciendo versiones y probándolas', 'Fer-lo una sola vegada, perfecte|Hacerlo una sola vez, perfecto', "Copiar el disseny d'un altre|Copiar el diseño de otro"], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Com gastes menys plàstic sense que la peça es trenqui?|¿Cómo gastas menos plástico sin que la pieza se rompa?', opts: ['La buido per dins però deixo parets de 2-3 mm|La vacío por dentro pero dejo paredes de 2-3 mm', "Faig les parets d'1 mm|Hago las paredes de 1 mm", 'La faig el doble de gran|La hago el doble de grande'], a: 0,
          ex: "Buida, però amb parets prou gruixudes: si no, la Nuvi no les pot fer fortes.|Vacía, pero con paredes bastante gruesas: si no, Nuvi no las puede hacer fuertes." },
        { k: 'feel', ph: 'tanca' }
      ] },

    /* ============ Sessió 4 · Projecte: un invent per a l'escola ============ */
    { id: 'm7-4', t: "Projecte: un invent per a l'escola|Proyecto: un invento para la escuela", min: 45, proj: true, badge: 'm7inventor',
      learn: ["Les especificacions diuen què ha de complir el disseny: per a qui és, què fa, les mides i com s'imprimirà.|Las especificaciones dicen qué tiene que cumplir el diseño: para quién es, qué hace, las medidas y cómo se imprimirá.",
        "Cada especificació s'ha de poder comprovar, amb un regle o amb les comprovacions del taller.|Cada especificación se tiene que poder comprobar, con una regla o con las comprobaciones del taller.",
        "Pensar com es posarà l'objecte a la placa també és dissenyar: estirat, sense parts a l'aire, és més fort.|Pensar cómo se pondrá el objeto en la placa también es diseñar: tumbado, sin partes en el aire, es más fuerte."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "Un company/a et diu: «La base és molt estable; els forats són justos, fes-los més grans». Quina mena de retroacció és?|Un compañero/a te dice: «La base es muy estable; los agujeros son justos, hazlos más grandes». ¿Qué tipo de retroalimentación es?",
          opts: ['Amable i concreta: diu què funciona i com millorar|Amable y concreta: dice qué funciona y cómo mejorar', 'No serveix: no és un elogi|No sirve: no es un elogio', 'És una crítica a la persona|Es una crítica a la persona'], a: 0 },
        { k: 'quiz', ph: 'recorda', q: 'Un objecte alt es tomba. Quina millora el fa més estable?|Un objeto alto se vuelca. ¿Qué mejora lo hace más estable?', opts: ['Fer la base més ampla|Hacer la base más ancha', 'Fer-lo més alt|Hacerlo más alto', "Pintar-lo d'un altre color|Pintarlo de otro color"], a: 0 },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'poble', title: "El concurs d'invents|El concurso de inventos",
          t: "La directora de l'escola, la <b>Montse</b>, ha obert el <b>Concurs d'invents</b>! L'escola necessita objectes útils: un <b>penjador</b> per a les motxilles del passadís, un <b>aguantallibres</b> per a la biblioteca i un <b>organitzador</b> per a la taula de la mestra. Tu seràs l'inventor/a: triaràs què fer, n'escriuràs les <b>especificacions</b> i el modelaràs. La Nuvi ja s'escalfa per imprimir-los!|La directora de la escuela, <b>Montse</b>, ¡ha abierto el <b>Concurso de inventos</b>! La escuela necesita objetos útiles: un <b>colgador</b> para las mochilas del pasillo, un <b>sujetalibros</b> para la biblioteca y un <b>organizador</b> para la mesa de la maestra. Tú serás el inventor/a: elegirás qué hacer, escribirás sus <b>especificaciones</b> y lo modelarás. ¡Nuvi ya se calienta para imprimirlos!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Especificacions|Especificaciones', t: 'Què ha de complir el teu invent|Qué tiene que cumplir tu invento', anim: 'm7spec',
            x: "Les <b>especificacions</b> són la llista del que ha de complir el disseny, escrita <b>abans</b> de començar: <b>per a qui</b> és, <b>què ha de fer</b>, les <b>mides</b> (màximes o exactes) i què cal perquè es pugui <b>imprimir</b>. Cada especificació s'ha de poder comprovar: «aguanta una motxilla», «fa com a molt 100 mm», «parets de 3 mm».|Las <b>especificaciones</b> son la lista de lo que tiene que cumplir el diseño, escrita <b>antes</b> de empezar: <b>para quién</b> es, <b>qué tiene que hacer</b>, las <b>medidas</b> (máximas o exactas) y qué hace falta para que se pueda <b>imprimir</b>. Cada especificación se tiene que poder comprobar: «aguanta una mochila», «mide como mucho 100 mm», «paredes de 3 mm».",
            tip: "Les comprovacions de cada repte del taller són especificacions que l'app revisa sola.|Las comprobaciones de cada reto del taller son especificaciones que la app revisa sola." },
          { k: 'Tres invents|Tres inventos', t: 'Penjador, aguantallibres i organitzador|Colgador, sujetalibros y organizador', media: { k: 'model', model: { parts: INVENTS } },
            x: "El <b>penjador</b> (esquerra) es cargola a la paret pels dos forats i té un ganxo per a la nansa. L'<b>aguantallibres</b> (centre) és una L amb dos reforços triangulars perquè no es dobli. L'<b>organitzador</b> (dreta) és una caixa buidada amb compartiments de mides diferents.|El <b>colgador</b> (izquierda) se atornilla a la pared por los dos agujeros y tiene un gancho para el asa. El <b>sujetalibros</b> (centro) es una L con dos refuerzos triangulares para que no se doble. El <b>organizador</b> (derecha) es una caja vaciada con compartimentos de medidas distintas.",
            tip: "Gira la vista: cada invent està fet només amb caixes, falques i forats.|Gira la vista: cada invento está hecho solo con cajas, cuñas y agujeros." },
          { k: 'Pensat per imprimir|Pensado para imprimir', t: 'Com el posaràs a la placa?|¿Cómo lo pondrás en la placa?', media: { k: 'model', model: { parts: HOOK(-19) } },
            x: "El penjador es dissenya <b>estirat</b> a la placa, com una lletra J. Així no té cap part a l'aire (la Nuvi no necessita suports) i les capes van d'una punta a l'altra del ganxo: és molt més <b>fort</b> que si l'imprimissis dret. Pensar com es col·locarà a la placa forma part del disseny.|El colgador se diseña <b>tumbado</b> en la placa, como una letra J. Así no tiene ninguna parte en el aire (Nuvi no necesita soportes) y las capas van de una punta a la otra del gancho: es mucho más <b>fuerte</b> que si lo imprimieras de pie. Pensar cómo se colocará en la placa forma parte del diseño." },
          { k: 'El camí del disseny|El camino del diseño', t: "De l'entrevista a l'invent|De la entrevista al invento", anim: 'm7road',
            x: "Ja coneixes tot el camí: <b>escoltar</b> la persona, fer l'<b>esbós amb mides</b>, <b>modelar</b> al taller, <b>provar</b> i <b>millorar</b>. Avui el recorreràs sencer amb el teu invent.|Ya conoces todo el camino: <b>escuchar</b> a la persona, hacer el <b>boceto con medidas</b>, <b>modelar</b> en el taller, <b>probar</b> y <b>mejorar</b>. Hoy lo recorrerás entero con tu invento." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '📋', title: "La fitxa d'especificacions|La ficha de especificaciones", t: "Tria el teu invent (o un altre que necessiti l'escola) i omple la fitxa:|Elige tu invento (u otro que necesite la escuela) y rellena la ficha:",
          steps: ['Per a qui és? On es farà servir?|¿Para quién es? ¿Dónde se usará?', 'Què ha de fer? Escriu-ho amb verbs: aguantar, guardar, penjar…|¿Qué tiene que hacer? Escríbelo con verbos: aguantar, guardar, colgar…',
            'Quines mides ha de tenir? Mesura el que hi anirà (una nansa, un llibre, uns llapis).|¿Qué medidas tiene que tener? Mide lo que irá en él (un asa, un libro, unos lápices).', "Fes l'esbós de davant i de dalt amb les cotes.|Haz el boceto de delante y de arriba con las cotas."],
          tip: "Si pots, ensenya la fitxa a qui farà servir l'invent: és la millor manera de saber si està bé.|Si puedes, enseña la ficha a quien usará el invento: es la mejor manera de saber si está bien." },
        { k: 'm3look', ph: 'prova', q: "Mira els tres invents. <b>Quants compartiments té l'organitzador?</b> Des de dalt es veu molt bé.|Mira los tres inventos. <b>¿Cuántos compartimentos tiene el organizador?</b> Desde arriba se ve muy bien.",
          model: { parts: INVENTS }, opts: ['3|3', '2|2', '4|4'], a: 0,
          ex: "Té un compartiment gran i dos de petits: tres forats caixa dins d'una sola caixa.|Tiene un compartimento grande y dos pequeños: tres agujeros caja dentro de una sola caja." },
        { k: 'm3fix', ph: 'investiga', q: "Ui! A aquest penjador, la punta del ganxo no toca el braç: hi ha 2 mm d'aire i la Nuvi l'imprimiria en dues peces. <b>Arregla'l</b> perquè sigui una sola peça.|¡Uy! En este colgador, la punta del gancho no toca el brazo: hay 2 mm de aire y Nuvi lo imprimiría en dos piezas. <b>Arréglalo</b> para que sea una sola pieza.",
          start: { parts: HOOK(-16) }, fix: ['punta'], palette: ['box', 'hcyl'], checks: [{ k: 'one' }, { k: 'onplate' }],
          hint: "Toca la punta i baixa-la: a Posició, la seva y ha de ser −19 (així es fica 1 mm dins del braç).|Toca la punta y bájala: en Posición, su y tiene que ser −19 (así se mete 1 mm dentro del brazo).", sol: { parts: HOOK(-19) } },
        { k: 'move', ph: 'pausa', title: 'Invents amb el cos|Inventos con el cuerpo', secs: 30, t: "Fes de <b>penjador</b>: un braç enganxat al cos (la part que va a la paret) i l'altre doblegat endavant com un ganxo. Ara fes d'<b>aguantallibres</b>: una L amb el cos, ben ferma! I ara d'<b>organitzador</b>: obre els braços com si guardessis coses a cada costat.|Haz de <b>colgador</b>: un brazo pegado al cuerpo (la parte que va a la pared) y el otro doblado hacia delante como un gancho. Ahora haz de <b>sujetalibros</b>: ¡una L con el cuerpo, bien firme! Y ahora de <b>organizador</b>: abre los brazos como si guardaras cosas a cada lado." },
        { k: 'm3build', ph: 'repte', q: "<b>Invent 1: el penjador de motxilles.</b> Ja tens l'esquena (la part que va a la paret). Afegeix-hi el <b>braç</b> i la <b>punta</b> del ganxo i <b>dos forats</b> de 5 mm per als cargols. Tot estirat, com el fantasma.|<b>Invento 1: el colgador de mochilas.</b> Ya tienes la espalda (la parte que va a la pared). Añádele el <b>brazo</b> y la <b>punta</b> del gancho y <b>dos agujeros</b> de 5 mm para los tornillos. Todo tumbado, como el fantasma.",
          start: { parts: [HOOK(-19)[0]] }, palette: ['box', 'hcyl'], target: { parts: HOOK(-19) },
          checks: [{ k: 'match', target: { parts: HOOK(-19) }, th: 0.85, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'count', t: 'cyl', hole: true, min: 2, txt: '2 forats per als cargols|2 agujeros para los tornillos' }, { k: 'one' }, { k: 'onplate' }],
          hint: "Braç: caixa de 44 × 12 × 12 mm a x = −2, y = −39. Punta: 12 × 30 × 12 mm a x = 14, y = −19. Forats: 5 × 5 × 14 mm a x = −24, y = 32 i y = 8.|Brazo: caja de 44 × 12 × 12 mm en x = −2, y = −39. Punta: 12 × 30 × 12 mm en x = 14, y = −19. Agujeros: 5 × 5 × 14 mm en x = −24, y = 32 e y = 8.",
          sol: { parts: HOOK(-19) } },
        { k: 'm3build', ph: 'repte', q: "<b>Invent 2: l'aguantallibres.</b> Ja tens la base. Afegeix la <b>paret</b> de 5 mm de gruix i 80 mm d'alt i dos <b>reforços</b> triangulars (falques) que la subjectin per darrere. Segueix el fantasma.|<b>Invento 2: el sujetalibros.</b> Ya tienes la base. Añade la <b>pared</b> de 5 mm de grosor y 80 mm de alto y dos <b>refuerzos</b> triangulares (cuñas) que la sujeten por detrás. Sigue el fantasma.",
          start: { parts: [BOOK[0]] }, palette: ['box', 'wedge'], target: { parts: BOOK },
          checks: [{ k: 'match', target: { parts: BOOK }, th: 0.85, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'size', ax: 'z', v: 80, t: "Fa 80 mm d'alt per aguantar els llibres|Mide 80 mm de alto para aguantar los libros" }, { k: 'flatbase', min: 3000, t: 'Té una base plana i ampla|Tiene una base plana y ancha' }, { k: 'one' }],
          hint: "Paret: 70 × 5 × 80 mm a y = −37,5. Cada falca: 30 × 6 × 40 mm, girada 90° en z, a y = −20 i z = 5; una a x = −24 i l'altra a x = 24.|Pared: 70 × 5 × 80 mm en y = −37,5. Cada cuña: 30 × 6 × 40 mm, girada 90° en z, en y = −20 y z = 5; una en x = −24 y la otra en x = 24.",
          sol: { parts: BOOK } },
        { k: 'm3build', ph: 'repte', q: "<b>Invent 3: l'organitzador de la mestra.</b> Buida la caixa amb <b>tres forats</b>: un compartiment gran per a les llibretes i dos de petits per als clips i les gomes. Deixa parets de 3 mm o més, com el fantasma.|<b>Invento 3: el organizador de la maestra.</b> Vacía la caja con <b>tres agujeros</b>: un compartimento grande para las libretas y dos pequeños para los clips y las gomas. Deja paredes de 3 mm o más, como el fantasma.",
          start: { parts: [ORG[0]] }, palette: ['hbox'], target: { parts: ORG },
          checks: [{ k: 'match', target: { parts: ORG }, th: 0.85, t: "S'assembla al fantasma|Se parece al fantasma" }, { k: 'count', t: 'box', hole: true, min: 3, txt: '3 compartiments (3 forats caixa)|3 compartimentos (3 agujeros caja)' }, { k: 'wall', min: 2 }, { k: 'flatbase', min: 3000, t: 'El fons és pla|El fondo es plano' }],
          hint: "Tots els forats tenen 38 mm d'alt i z = 3. Gran: 52 × 54 mm a x = −16. Petits: 26 × 25 mm a x = 27, un a y = −14,5 i l'altre a y = 14,5.|Todos los agujeros tienen 38 mm de alto y z = 3. Grande: 52 × 54 mm en x = −16. Pequeños: 26 × 25 mm en x = 27, uno en y = −14,5 y el otro en y = 14,5.",
          sol: { parts: ORG } },
        { k: 'm3free', ph: 'crea', q: "<b>El teu invent per a l'escola.</b> Fes l'invent de la teva fitxa d'especificacions: un dels tres o un de teu. Abans d'acabar, comprova cada especificació.|<b>Tu invento para la escuela.</b> Haz el invento de tu ficha de especificaciones: uno de los tres o uno tuyo. Antes de terminar, comprueba cada especificación.",
          name: "El meu invent per a l'escola|Mi invento para la escuela",
          crit: ['Compleix les especificacions de la teva fitxa|Cumple las especificaciones de tu ficha', 'Té la mida pensada per a qui el farà servir|Tiene el tamaño pensado para quien lo usará', "Està pensat per imprimir-se bé (estirat, sense parts a l'aire)|Está pensado para imprimirse bien (tumbado, sin partes en el aire)"],
          checks: [{ k: 'onplate' }, { k: 'one' }, { k: 'count', min: 2, txt: 'Té almenys 2 peces|Tiene al menos 2 piezas' }, { k: 'fit', box: [180, 180, 150], t: 'Cap a la placa de la Nuvi|Cabe en la placa de Nuvi' }],
          sol: { parts: HOOK(-19) } },
        { k: 'quiz', ph: 'tanca', q: 'Quina especificació es pot comprovar?|¿Qué especificación se puede comprobar?', opts: ["«Fa com a molt 100 mm d'alt»|«Mide como mucho 100 mm de alto»", '«Ha de ser bonic»|«Tiene que ser bonito»', "«Ha d'agradar a tothom»|«Tiene que gustar a todo el mundo»"], a: 0,
          ex: "Amb un regle (o amb les comprovacions del taller) se sap si fa 100 mm o no. «Bonic» depèn de qui ho mira.|Con una regla (o con las comprobaciones del taller) se sabe si mide 100 mm o no. «Bonito» depende de quien lo mira." },
        { k: 'quiz', ph: 'tanca', q: 'Per què el penjador es dissenya estirat a la placa?|¿Por qué el colgador se diseña tumbado en la placa?', opts: ['Perquè no necessita suports i queda més fort|Porque no necesita soportes y queda más fuerte', 'Perquè així és més bonic|Porque así es más bonito', 'Perquè la Nuvi només imprimeix coses planes|Porque Nuvi solo imprime cosas planas'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] }
  ] };
})();
