/* Tech Creadors · unitat 1 «Primers passos a l'escenari» (g1-1 … g1-4)
   Contingut propi de Numi. Les històries passen al Teatre de l'illa: els actors són personatges de l'ordinador i
   l'alumne/a n'escriu els guions. Conceptes: escenari i personatges, «Quan comença», moure (endavant i enrere),
   la direcció i girar, dir i pensar frases amb temps, fons i escenes, amagar-se; projecte «Presenta't». */
Object.assign(TBADGE, {
  g_actor: { id: 'g_actor', ico: '🎭', n: 'Primer personatge|Primer personaje', d: "Has fet moure i parlar el teu primer personatge a l'escenari.|Has hecho mover y hablar a tu primer personaje en el escenario." },
  g_assaig: { id: 'g_assaig', ico: '🧭', n: "Director/a d'assaig|Director/a de ensayo", d: 'Fas girar els personatges cap on toca i els fas dir el seu paper, frase a frase.|Haces girar a los personajes hacia donde toca y les haces decir su papel, frase a frase.' },
  g_decorat: { id: 'g_decorat', ico: '🏰', n: 'Decorador/a|Decorador/a', d: 'Has creat històries amb escenes: fons que canvien i personatges que surten de l\'escena.|Has creado historias con escenas: fondos que cambian y personajes que salen de la escena.' },
  g_presenta: { id: 'g_presenta', ico: '🌟', n: "Estrella de l'estrena|Estrella del estreno", d: "Projecte acabat: has presentat el teu personatge al Teatre de l'illa.|Proyecto terminado: has presentado a tu personaje en el Teatro de la isla." }
});

COURSE_UNITS[1] = (() => {
  // el Teatre de l'illa (fons «escenari»): els actors es posen a terra, a y = -95
  const G1_T = (sprites, o = {}) => ({ bg: 'escenari', sprites, ...o });
  const G1_SAYS = P => Object.values(P || {}).reduce((n, scr) => n + scr.reduce((a, l) => a + (function c(x) { return (x || []).reduce((k, b) => k + (['say', 'think'].includes(b.k) ? 1 : 0) + c(b.b) + c(b.e), 0); })(l), 0), 0);
  // un bloc dibuixat com a l'editor, per a les opcions de les preguntes («quin bloc s'equivoca?»)
  const G1_CHIP = src => () => { const b = SQ('@x flag{ ' + src + ' }').x.flag[0][0]; return `<span class="rdb c-${SG_CAT[b.k]}"><span class="tbi">${sgIco(b.k)}</span><span>${sgLabel(b)}</span></span>`; };
  const G1_HAS = (P, ks) => Object.values(P || {}).some(scr => scr.some(function c(l) { return (l || []).some(b => ks.includes(b.k) || c(b.b) || c(b.e)); }));
  return { t: "Primers passos a l'escenari|Primeros pasos en el escenario", d: 'Personatges, moviment i escenes|Personajes, movimiento y escenas', color: '#F08A24', s: [
  /* ---------- Sessió 1 · El meu primer personatge ---------- */
  { id: 'g1-1', t: 'El meu primer personatge|Mi primer personaje', min: 40, badge: 'g_actor',
    learn: ["L'escenari és on passa tot i els personatges són els actors: cadascun fa el que diu el seu guió.|El escenario es donde pasa todo y los personajes son los actores: cada uno hace lo que dice su guion.",
      'Quan toques la bandera verda, el guió de «Quan comença» es fa bloc a bloc, de dalt a baix.|Cuando tocas la bandera verde, el guion de «Al empezar» se hace bloque a bloque, de arriba abajo.',
      '«Mou-te» amb un número positiu fa avançar el personatge; amb un de negatiu, el fa anar enrere.|«Muévete» con un número positivo hace avanzar al personaje; con uno negativo, lo hace ir hacia atrás.'],
    steps: [
      { k: 'story', ph: 'missio', who: 'both', scene: 'poble', title: "El Teatre de l'illa|El Teatro de la isla", art: () => TANI.g1stage(true),
        t: "Hola! Benvingut/da al <b>Teatre de l'illa</b>. Aquí preparem una funció molt especial: els actors són <b>personatges de l'ordinador</b>… i qui els diu què han de fer ets tu!|¡Hola! Bienvenido/a al <b>Teatro de la isla</b>. Aquí preparamos una función muy especial: los actores son <b>personajes del ordenador</b>… ¡y quien les dice lo que tienen que hacer eres tú!" },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy',
        t: "BIP! En aquest curs crearàs <b>animacions</b>, <b>històries</b> i, al final, el teu propi <b>videojoc</b>. Però tot comença amb un primer pas: fer que un personatge <b>es mogui i parli</b> a l'escenari.|¡BIP! En este curso crearás <b>animaciones</b>, <b>historias</b> y, al final, tu propio <b>videojuego</b>. Pero todo empieza con un primer paso: hacer que un personaje <b>se mueva y hable</b> en el escenario." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Escenari|Escenario', t: "L'escenari i els personatges|El escenario y los personajes",
          media: { k: 'stage', w: G1_T([{ id: 'vuit', art: 'vuit', x: -160, y: -95 }, { id: 'numi', art: 'numi', x: -20, y: -95, costume: 1 }, { id: 'guida', art: 'guida', x: 130, y: -95 }]),
            prog: '@guida flag{ point:-90 } @vuit flag{ think:"Quins nervis!|¡Qué nervios!",3 } @numi flag{ move:20 say:"Benvinguts!|¡Bienvenidos!",3 }', time: 4 },
          x: "L'<span class='hl'>escenari</span> és el rectangle on passa tot. Els <span class='hl'>personatges</span> són els actors: cadascun té el seu dibuix i fa el que diuen <b>els seus blocs</b>. Aquí en Numi dona la benvinguda, la Guida es gira per mirar-lo i en Vuit… està nerviós!|El <span class='hl'>escenario</span> es el rectángulo donde pasa todo. Los <span class='hl'>personajes</span> son los actores: cada uno tiene su dibujo y hace lo que dicen <b>sus bloques</b>. Aquí Numi da la bienvenida, Guida se gira para mirarlo y Vuit… ¡está nervioso!",
          tip: "Com en un teatre de debò: hi ha escenari, actors i un guió que diu què fa cadascú.|Como en un teatro de verdad: hay escenario, actores y un guion que dice qué hace cada uno." },
        { k: 'Guió|Guion', t: 'Quan comença: la bandera verda|Al empezar: la bandera verde', anim: 'g1flag',
          x: "Els blocs d'un personatge formen un <span class='hl'>guió</span>. El guió comença amb una capçalera: <b>Quan comença</b> vol dir «quan toquis la bandera verda». Després, els blocs es fan <b>un a un, de dalt a baix</b>.|Los bloques de un personaje forman un <span class='hl'>guion</span>. El guion empieza con una cabecera: <b>Al empezar</b> quiere decir «cuando toques la bandera verde». Después, los bloques se hacen <b>uno a uno, de arriba abajo</b>." },
        { k: 'Moure|Mover', t: 'Mou-te: endavant i enrere|Muévete: adelante y atrás', anim: 'g1move',
          x: "El bloc <b>mou-te 100 passos</b> fa avançar el personatge cap on mira (al principi, cap a la dreta). Amb un número <b>negatiu</b>, com <b>-100</b>, va enrere. Els passos són petits: l'escenari fa <b>480 passos</b> d'ample.|El bloque <b>muévete 100 pasos</b> hace avanzar al personaje hacia donde mira (al principio, hacia la derecha). Con un número <b>negativo</b>, como <b>-100</b>, va hacia atrás. Los pasos son pequeños: el escenario mide <b>480 pasos</b> de ancho.",
          bad: '«Mou-te 10 passos» el porta a l\'altra punta de l\'escenari.|«Muévete 10 pasos» lo lleva a la otra punta del escenario.', good: "10 passos és un trosset: per creuar tot l'escenari en calen més de 400.|10 pasos es un trocito: para cruzar todo el escenario hacen falta más de 400." },
        { k: 'On és?|¿Dónde está?', t: 'El centre és el (0, 0)|El centro es el (0, 0)', anim: 'g1stage',
          x: "Cada punt de l'escenari té dos números. La <b>x</b> diu si és a la dreta (positiu) o a l'esquerra (negatiu) del centre; la <b>y</b>, si és a dalt (positiu) o a baix (negatiu). Al centre, tots dos valen <b>0</b>. Ho estudiarem a fons més endavant: de moment, recorda que <b>la dreta és x positiva</b>.|Cada punto del escenario tiene dos números. La <b>x</b> dice si está a la derecha (positivo) o a la izquierda (negativo) del centro; la <b>y</b>, si está arriba (positivo) o abajo (negativo). En el centro, los dos valen <b>0</b>. Lo estudiaremos a fondo más adelante: de momento, recuerda que <b>la derecha es x positiva</b>." },
        { k: 'Digues|Di', t: 'Fer parlar un personatge|Hacer hablar a un personaje',
          media: { k: 'stage', w: G1_T([{ id: 'numi', art: 'numi', x: -150, y: -95, costume: 1 }]), prog: '@numi flag{ say:"Vinc!|¡Voy!",1 move:150 say:"Bon dia, públic!|¡Buenos días, público!",3 }', time: 5 },
          x: "El bloc <b>digues</b> fa sortir una bafarada amb el text que triïs. Amb <b>2 s</b>, la frase es veu 2 segons i, després, el personatge continua amb el bloc següent.|El bloque <b>di</b> hace salir un bocadillo con el texto que elijas. Con <b>2 s</b>, la frase se ve 2 segundos y, después, el personaje sigue con el bloque siguiente." }
      ] },
      { k: 'quiz', ph: 'prova', q: "Què fa començar el guió <b>Quan comença</b> d'un personatge?|¿Qué hace empezar el guion <b>Al empezar</b> de un personaje?",
        opts: ['Tocar la bandera verda|Tocar la bandera verde', 'Tocar el bloc «mou-te»|Tocar el bloque «muévete»', "Esperar que l'ordinador ho decideixi|Esperar a que el ordenador lo decida"], a: 0,
        ex: 'La bandera verda és el senyal de començar, com quan s\'aixeca el teló.|La bandera verde es la señal de empezar, como cuando se levanta el telón.' },
      { k: 'seq', ph: 'mans', q: "<b>Ordena els passos</b> per preparar la primera funció del teatre.|<b>Ordena los pasos</b> para preparar la primera función del teatro.",
        items: ['Tria el personatge|Elige el personaje', 'Posa-li un guió que comenci amb «Quan comença»|Ponle un guion que empiece con «Al empezar»', 'Afegeix els blocs en ordre, de dalt a baix|Añade los bloques en orden, de arriba abajo', 'Toca la bandera verda i mira què fa|Toca la bandera verde y mira qué hace'],
        ex: 'Primer el personatge, després el guió i, al final, la bandera per provar-ho.|Primero el personaje, después el guion y, al final, la bandera para probarlo.' },
      { k: 'unplug', ph: 'mans', ico: '🎭', title: 'Director/a i actor/actriu|Director/a y actor/actriz',
        t: "Amb algú de casa. Una persona fa de <b>director/a</b> (escriu el guió) i l'altra, d'<b>actor/actriu</b> (el fa).|Con alguien de casa. Una persona hace de <b>director/a</b> (escribe el guion) y la otra, de <b>actor/actriz</b> (lo hace).",
        steps: ["El director/a escriu en un paper 3 ordres, una sota l'altra: per exemple <b>mou-te 3 passos</b>, <b>digues «Bon dia!»</b>, <b>mou-te -2 passos</b>.|El director/a escribe en un papel 3 órdenes, una debajo de otra: por ejemplo <b>muévete 3 pasos</b>, <b>di «¡Buenos días!»</b>, <b>muévete -2 pasos</b>.",
          "Quan aixeca la «bandera verda» (un full verd o un mocador), l'actor/actriu fa les ordres de dalt a baix.|Cuando levanta la «bandera verde» (una hoja verde o un pañuelo), el actor/actriz hace las órdenes de arriba abajo.",
          "Els passos negatius es fan enrere, sense girar-se!|¡Los pasos negativos se hacen hacia atrás, sin girarse!",
          'Canvieu els papers i inventeu un guió nou.|Cambiad los papeles e inventad un guion nuevo.'],
        tip: "L'actor/actriu només pot fer el que diu el paper, encara que sigui estrany. Així funcionen els personatges de l'ordinador.|El actor/actriz solo puede hacer lo que dice el papel, aunque sea raro. Así funcionan los personajes del ordenador." },
      { k: 'sfree', ph: 'prova', q: "Mira l'assaig: toca la <b>bandera verda</b> i fixa't en què fa cada actor. Després toca cada personatge a la llista per veure el seu guió.|Mira el ensayo: toca la <b>bandera verde</b> y fíjate en lo que hace cada actor. Después toca cada personaje en la lista para ver su guion.",
        w: G1_T([{ id: 'guida', art: 'guida', x: -170, y: -95 }, { id: 'tuga', art: 'tuga', x: 0, y: -95 }, { id: 'vuit', art: 'vuit', x: 170, y: -95 }]),
        prog: '@guida flag{ move:100 say:"Ja hi soc!|¡Ya estoy!",2 } @tuga flag{ say:"Bon dia a tothom!|¡Buenos días a todos!",3 } @vuit flag{ move:-90 say:"Jo vaig enrere!|¡Yo voy hacia atrás!",2 }' },
      { k: 'quiz', ph: 'prova', q: 'La Tuga és al centre (x = 0) i mira a la dreta. Fa <b>mou-te -100 passos</b>. On acaba?|Tuga está en el centro (x = 0) y mira a la derecha. Hace <b>muévete -100 pasos</b>. ¿Dónde termina?',
        opts: ["A l'esquerra, a x = -100|A la izquierda, en x = -100", 'A la dreta, a x = 100|A la derecha, en x = 100', 'Al mateix lloc, a x = 0|En el mismo sitio, en x = 0'], a: 0,
        ex: 'El número negatiu la fa anar enrere: 100 passos cap a l\'esquerra.|El número negativo la hace ir hacia atrás: 100 pasos hacia la izquierda.' },
      { k: 'sfree', ph: 'investiga', q: "La Guida havia d'anar cap a la dreta, fins al regal, però alguna cosa falla. Toca la bandera verda i <b>mira què passa</b>.|Guida tenía que ir hacia la derecha, hasta el regalo, pero algo falla. Toca la bandera verde y <b>mira qué pasa</b>.",
        w: G1_T([{ id: 'guida', art: 'guida', x: -120, y: -95 }, { id: 'regal', art: 'regal', x: 120, y: -110, name: 'Regal|Regalo' }]),
        prog: '@guida flag{ say:"Vaig a buscar el regal!|¡Voy a buscar el regalo!",2 move:-240 say:"On és el regal?|¿Dónde está el regalo?",2 }' },
      { k: 'quiz', ph: 'investiga', keep: true, q: "Aquest és el guió de la Guida. <b>Quin bloc s'equivoca?</b>|Este es el guion de Guida. <b>¿Qué bloque se equivoca?</b>",
        opts: [G1_CHIP('say:"Vaig a buscar el regal!|¡Voy a buscar el regalo!",2'), G1_CHIP('move:-240'), G1_CHIP('say:"On és el regal?|¿Dónde está el regalo?",2')], a: 1,
        ex: 'El número és negatiu: -240 la fa anar enrere. Havia de ser 240.|El número es negativo: -240 la hace ir hacia atrás. Tenía que ser 240.' },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de personatge! Dret/a: <b>mou-te 3 passos</b> endavant, <b>mou-te -3 passos</b> (enrere, sense girar-te!) i digues «Hola!» saludant amb la mà. Ara: 2 passos endavant, 1 enrere i una reverència.|¡Haz de personaje! De pie: <b>muévete 3 pasos</b> adelante, <b>muévete -3 pasos</b> (hacia atrás, ¡sin girarte!) y di «¡Hola!» saludando con la mano. Ahora: 2 pasos adelante, 1 atrás y una reverencia." },
      { k: 'stage', ph: 'repte', q: "El teu primer guió! Els actors es posen damunt d'una <b>marca</b> (l'estrella). Fes que en Numi arribi a la seva marca.|¡Tu primer guion! Los actores se colocan encima de una <b>marca</b> (la estrella). Haz que Numi llegue a su marca.",
        w: G1_T([{ id: 'numi', art: 'numi', x: -160, y: -95 }, { id: 'marca', art: 'estrella', x: 60, y: -150, size: 60, name: 'Marca|Marca' }], { goal: [{ k: 'at', s: 'numi', r: [30, -200, 90, 200] }], time: 3 }),
        edit: ['numi'], hats: ['flag'], pal: ['move'], sol: '@numi flag{ move:220 }',
        hint: "Toca el número del bloc per canviar-lo. La marca és a uns 200 passos: prova-ho i, si no hi arriba, ajusta el número.|Toca el número del bloque para cambiarlo. La marca está a unos 200 pasos: pruébalo y, si no llega, ajusta el número." },
      { k: 'stage', ph: 'repte', q: "En Vuit ha d'anar a la seva marca, que és a l'<b>esquerra</b>, però el guió el porta a la dreta. <b>Arregla'l.</b>|Vuit tiene que ir a su marca, que está a la <b>izquierda</b>, pero el guion lo lleva a la derecha. <b>Arréglalo.</b>",
        w: G1_T([{ id: 'vuit', art: 'vuit', x: 100, y: -95 }, { id: 'marca', art: 'estrella', x: -120, y: -150, size: 60, name: 'Marca|Marca' }], { goal: [{ k: 'at', s: 'vuit', r: [-150, -200, -90, 200] }], time: 3 }),
        edit: ['vuit'], hats: ['flag'], pal: ['move'], prog: '@vuit flag{ move:220 }', sol: '@vuit flag{ move:-220 }',
        hint: "Per anar enrere, el número ha de ser negatiu: posa-hi un «-» davant.|Para ir hacia atrás, el número tiene que ser negativo: ponle un «-» delante." },
      { k: 'stage', ph: 'repte', q: "La Flama surt a escena: ha d'arribar a la seva marca i <b>dir alguna cosa al públic</b>.|Flama sale a escena: tiene que llegar a su marca y <b>decir algo al público</b>.",
        w: G1_T([{ id: 'flama', art: 'flama', x: -200, y: -95 }, { id: 'marca', art: 'estrella', x: -20, y: -150, size: 60, name: 'Marca|Marca' }], { goal: [{ k: 'at', s: 'flama', r: [-50, -200, 10, 200] }, { k: 'said', s: 'flama' }], time: 4 }),
        edit: ['flama'], hats: ['flag'], pal: ['move', 'say'], texts: ['Bon dia!|¡Buenos días!', 'Visca el teatre!|¡Viva el teatro!', 'Hola, públic!|¡Hola, público!'],
        sol: '@flama flag{ move:180 say:"Bon dia!|¡Buenos días!",2 }',
        hint: 'Dos blocs: primer «mou-te» fins a la marca i després «digues». Toca el text del bloc «digues» per triar la frase.|Dos bloques: primero «muévete» hasta la marca y después «di». Toca el texto del bloque «di» para elegir la frase.' },
      { k: 'stage', ph: 'repte', q: "La Guida ha d'anar fins al <b>regal</b>, dir-hi alguna cosa i <b>tornar</b> al seu lloc, a l'esquerra.|Guida tiene que ir hasta el <b>regalo</b>, decir algo allí y <b>volver</b> a su sitio, a la izquierda.",
        w: G1_T([{ id: 'guida', art: 'guida', x: -140, y: -95 }, { id: 'regal', art: 'regal', x: 60, y: -110, name: 'Regal|Regalo' }], { goal: [{ k: 'reach', s: 'guida', r: [20, -200, 100, 200] }, { k: 'said', s: 'guida' }, { k: 'at', s: 'guida', r: [-170, -200, -110, 200] }], time: 5 }),
        edit: ['guida'], hats: ['flag'], pal: ['move', 'say'], texts: ['Un regal!|¡Un regalo!', 'Què hi deu haver?|¿Qué habrá dentro?'],
        sol: '@guida flag{ move:200 say:"Un regal!|¡Un regalo!",2 move:-200 }',
        hint: "Tres blocs: anar al regal, dir-hi una frase (amb segons, perquè es vegi que hi és) i tornar amb un número negatiu.|Tres bloques: ir al regalo, decir allí una frase (con segundos, para que se vea que está) y volver con un número negativo." },
      { k: 'screate', ph: 'crea', name: 'El meu primer personatge|Mi primer personaje',
        q: "Ara decideixes tu! En <b>Cavaller</b> surt a escena per primera vegada. Fes que <b>es mogui</b> i que <b>digui alguna cosa</b> al públic. Pots posar-hi tants blocs com vulguis.|¡Ahora decides tú! El <b>Caballero</b> sale a escena por primera vez. Haz que <b>se mueva</b> y que <b>diga algo</b> al público. Puedes poner tantos bloques como quieras.",
        crit: ['Es mou (mou-te)|Se mueve (muévete)', 'Diu alguna cosa al públic (digues)|Dice algo al público (di)'],
        w: G1_T([{ id: 'cavaller', art: 'cavaller', x: -180, y: -95 }], { goal: [{ k: 'moved', s: 'cavaller', min: 40 }, { k: 'said', s: 'cavaller' }], noEarly: true, time: 8 }),
        edit: ['cavaller'], hats: ['flag'], pal: ['move', 'say'], texts: ["Soc el cavaller de l'illa!|¡Soy el caballero de la isla!", 'Bon dia, públic!|¡Buenos días, público!', 'Adéu!|¡Adiós!'],
        sol: `@cavaller flag{ move:150 say:"Soc el cavaller de l'illa!|¡Soy el caballero de la isla!",2 move:-60 say:"Adéu!|¡Adiós!",2 }` },
      { k: 'quiz', ph: 'tanca', q: 'Quin número fa que un personatge vagi <b>enrere</b>?|¿Qué número hace que un personaje vaya hacia <b>atrás</b>?', opts: ['-50|-50', '50|50', '0|0'], a: 0, ex: 'Els números negatius fan anar enrere.|Los números negativos hacen ir hacia atrás.' },
      { k: 'quiz', ph: 'tanca', q: "En quin ordre es fan els blocs d'un guió?|¿En qué orden se hacen los bloques de un guion?", opts: ['Un a un, de dalt a baix|Uno a uno, de arriba abajo', 'Tots alhora|Todos a la vez', 'De baix a dalt|De abajo arriba'], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 2 · Moure i parlar ---------- */
  { id: 'g1-2', t: 'Moure i parlar|Mover y hablar', min: 40, badge: 'g_assaig',
    learn: ['La direcció diu cap on mira el personatge: 90 a la dreta, 180 avall, -90 a l\'esquerra i 0 amunt.|La dirección dice hacia dónde mira el personaje: 90 a la derecha, 180 abajo, -90 a la izquierda y 0 arriba.',
      '«Gira 90 graus» és un quart de volta i no mou el personatge: després cal un «mou-te».|«Gira 90 grados» es un cuarto de vuelta y no mueve al personaje: después hace falta un «muévete».',
      '«Digues» i «pensa» amb segons fan que les frases es llegeixin una darrere l\'altra.|«Di» y «piensa» con segundos hacen que las frases se lean una detrás de otra.'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Recordes què fa <b>mou-te -100 passos</b>?|¿Recuerdas qué hace <b>muévete -100 pasos</b>?',
        opts: ['Fa anar el personatge 100 passos enrere|Hace ir al personaje 100 pasos hacia atrás', 'Fa girar el personatge|Hace girar al personaje', 'Fa anar el personatge 100 passos endavant|Hace ir al personaje 100 pasos hacia adelante'], a: 0 },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'poble', title: "L'assaig general|El ensayo general",
        t: "Demà s'estrena l'obra del Teatre de l'illa i avui fem l'<b>assaig</b>. Els actors han d'aprendre dues coses: <b>girar</b> cap on toca i <b>dir el seu paper</b>, frase a frase, sense que les frases es trepitgin.|Mañana se estrena la obra del Teatro de la isla y hoy hacemos el <b>ensayo</b>. Los actores tienen que aprender dos cosas: <b>girar</b> hacia donde toca y <b>decir su papel</b>, frase a frase, sin que las frases se pisen." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Direcció|Dirección', t: 'Cap on mira?|¿Hacia dónde mira?', anim: 'g1dir',
          x: "Cada personatge té una <span class='hl'>direcció</span>: <b>90</b> és mirar a la dreta, <b>180</b> avall, <b>-90</b> a l'esquerra i <b>0</b> amunt. El bloc <b>apunta en direcció</b> el fa mirar cap on diguis, i <b>mou-te</b> sempre avança cap on mira.|Cada personaje tiene una <span class='hl'>dirección</span>: <b>90</b> es mirar a la derecha, <b>180</b> abajo, <b>-90</b> a la izquierda y <b>0</b> arriba. El bloque <b>apunta en dirección</b> lo hace mirar hacia donde digas, y <b>muévete</b> siempre avanza hacia donde mira.",
          tip: "Pensa en una brúixola: el 0 és a dalt i, si gires cap a la dreta, els números creixen: 90, 180…|Piensa en una brújula: el 0 está arriba y, si giras hacia la derecha, los números crecen: 90, 180…" },
        { k: 'Girar|Girar', t: 'Gira: un quart de volta són 90 graus|Gira: un cuarto de vuelta son 90 grados',
          media: { k: 'stage', w: { bg: 'parc', sprites: [{ id: 'cotxe', art: 'cotxe', x: -150, y: 70 }] }, prog: '@cotxe flag{ say:"Recte!|¡Recto!",1 move:140 say:"Giro!|¡Giro!",1 turn:90 say:"Ara miro avall.|Ahora miro abajo.",2 move:110 say:"Arribat!|¡Llegué!",2 }', time: 7 },
          x: "<b>Gira 90 graus</b> fa un quart de volta cap a la dreta i <b>gira -90 graus</b>, cap a l'esquerra. Girar <b>no mou</b> el personatge de lloc: només canvia cap on mira. Per això, després de girar, gairebé sempre cal un <b>mou-te</b>.|<b>Gira 90 grados</b> da un cuarto de vuelta hacia la derecha y <b>gira -90 grados</b>, hacia la izquierda. Girar <b>no mueve</b> al personaje de sitio: solo cambia hacia dónde mira. Por eso, después de girar, casi siempre hace falta un <b>muévete</b>.",
          bad: '«Gira 90 graus» fa baixar el cotxe.|«Gira 90 grados» hace bajar el coche.', good: "«Gira 90 graus» el fa mirar avall; és el «mou-te» el que el fa baixar.|«Gira 90 grados» lo hace mirar abajo; es el «muévete» lo que lo hace bajar." },
        { k: 'Parlar|Hablar', t: 'Digues i pensa|Di y piensa', anim: 'g1say',
          x: "<b>Digues</b> mostra una bafarada, com en un còmic: és el que el personatge diu en veu alta. <b>Pensa</b> mostra un núvol: és el que pensa però no diu.|<b>Di</b> muestra un bocadillo, como en un cómic: es lo que el personaje dice en voz alta. <b>Piensa</b> muestra una nube: es lo que piensa pero no dice." },
        { k: 'Temps|Tiempo', t: "Una frase darrere l'altra|Una frase detrás de otra",
          media: { k: 'stage', w: G1_T([{ id: 'tuga', art: 'tuga', x: 0, y: -95 }]), prog: '@tuga flag{ say:"Hola!|¡Hola!",2 say:"Soc la Tuga.|Soy Tuga.",2 think:"Ho he dit bé?|¿Lo he dicho bien?",2 }', time: 7 },
          x: "Amb <b>durant 2 s</b>, la frase es queda 2 segons a la pantalla i, quan s'acaba, el personatge passa al bloc següent. Així pots fer un paper sencer, frase a frase.|Con <b>durante 2 s</b>, la frase se queda 2 segundos en la pantalla y, cuando se acaba, el personaje pasa al bloque siguiente. Así puedes hacer un papel entero, frase a frase.",
          bad: 'Dues frases sense segons: la primera desapareix de seguida i només es veu la segona.|Dos frases sin segundos: la primera desaparece enseguida y solo se ve la segunda.', good: 'Posar segons a cada frase perquè el públic les pugui llegir totes.|Poner segundos en cada frase para que el público las pueda leer todas.' }
      ] },
      { k: 'quiz', ph: 'prova', q: 'El cotxe mira a la dreta (direcció 90) i fa <b>gira 90 graus</b>. Cap on mira ara?|El coche mira a la derecha (dirección 90) y hace <b>gira 90 grados</b>. ¿Hacia dónde mira ahora?',
        opts: ['Avall (180)|Abajo (180)', 'Amunt (0)|Arriba (0)', "A l'esquerra (-90)|A la izquierda (-90)"], a: 0,
        ex: 'Un quart de volta cap a la dreta: de mirar a la dreta passa a mirar avall.|Un cuarto de vuelta hacia la derecha: de mirar a la derecha pasa a mirar abajo.' },
      { k: 'seq', ph: 'mans', q: "<b>Ordena el guió</b> de la Flama: entra, saluda, es gira cap a la porta (a l'esquerra) i se'n va.|<b>Ordena el guion</b> de Flama: entra, saluda, se gira hacia la puerta (a la izquierda) y se va.",
        items: ['Quan comença|Al empezar', 'mou-te 150 passos|muévete 150 pasos', 'digues «Hola, públic!» durant 2 s|di «¡Hola, público!» durante 2 s', 'apunta en direcció -90|apunta en dirección -90', 'mou-te 150 passos|muévete 150 pasos'],
        ex: 'Per marxar, primer es gira i després es mou: així camina mirant cap a la porta.|Para irse, primero se gira y después se mueve: así camina mirando hacia la puerta.' },
      { k: 'unplug', ph: 'mans', ico: '🧭', title: 'La brúixola del teatre|La brújula del teatro',
        t: "Amb algú de casa, a un lloc amb espai. Tria una paret que sigui la direcció <b>0</b> (amunt).|Con alguien de casa, en un sitio con espacio. Elige una pared que sea la dirección <b>0</b> (arriba).",
        steps: ["Una persona diu ordres i l'altra les fa: <b>apunta en direcció 90</b>, <b>apunta en direcció 180</b>…|Una persona dice órdenes y la otra las hace: <b>apunta en dirección 90</b>, <b>apunta en dirección 180</b>…",
          'Ara amb girs: <b>gira 90 graus</b> (un quart de volta a la dreta), <b>gira -90 graus</b> (a l\'esquerra).|Ahora con giros: <b>gira 90 grados</b> (un cuarto de vuelta a la derecha), <b>gira -90 grados</b> (a la izquierda).',
          "Afegiu-hi frases: <b>digues «Bon dia!» durant 2 segons</b> (compteu fins a 2 abans de la següent ordre).|Añadid frases: <b>di «¡Buenos días!» durante 2 segundos</b> (contad hasta 2 antes de la siguiente orden).",
          'Canvieu els papers.|Cambiad los papeles.'],
        tip: 'Quatre girs de 90 graus fan una volta sencera: tornes a mirar on miraves.|Cuatro giros de 90 grados dan una vuelta entera: vuelves a mirar donde mirabas.' },
      { k: 'sfree', ph: 'prova', q: "Mira l'assaig: en Vuit i la Guida parlen per torns. Toca la bandera verda i després mira el guió de cadascun. Qui parla primer?|Mira el ensayo: Vuit y Guida hablan por turnos. Toca la bandera verde y después mira el guion de cada uno. ¿Quién habla primero?",
        w: G1_T([{ id: 'vuit', art: 'vuit', x: -110, y: -95 }, { id: 'guida', art: 'guida', x: 110, y: -95, dir: -90 }]),
        prog: '@vuit flag{ say:"Bon dia, Guida!|¡Buenos días, Guida!",2 think:"Què em dirà?|¿Qué me dirá?",2 } @guida flag{ think:"Mmm…|Mmm…",2 say:"Bon dia, Vuit!|¡Buenos días, Vuit!",2 }' },
      { k: 'quiz', ph: 'prova', q: 'Quin d\'aquests blocs fa que el personatge <b>canviï de lloc</b>?|¿Cuál de estos bloques hace que el personaje <b>cambie de sitio</b>?',
        opts: ['mou-te 50 passos|muévete 50 pasos', 'gira 90 graus|gira 90 grados', 'apunta en direcció 0|apunta en dirección 0'], a: 0, ex: 'Girar i apuntar només canvien cap on mira.|Girar y apuntar solo cambian hacia dónde mira.' },
      { k: 'sfree', ph: 'investiga', q: 'El cotxe havia de pujar fins a la bandera, però alguna cosa falla. Toca la bandera verda i <b>mira cap on va</b>.|El coche tenía que subir hasta la bandera, pero algo falla. Toca la bandera verde y <b>mira hacia dónde va</b>.',
        w: { bg: 'parc', sprites: [{ id: 'cotxe', art: 'cotxe', x: -60, y: 20 }, { id: 'bandera', art: 'bandera', x: -60, y: 130, size: 70 }] },
        prog: '@cotxe flag{ turn:90 say:"Cap a la bandera!|¡Hacia la bandera!",2 move:130 }' },
      { k: 'quiz', ph: 'investiga', keep: true, q: "Aquest és el guió del cotxe. <b>Quin bloc s'equivoca?</b>|Este es el guion del coche. <b>¿Qué bloque se equivoca?</b>",
        opts: [G1_CHIP('turn:90'), G1_CHIP('say:"Cap a la bandera!|¡Hacia la bandera!",2'), G1_CHIP('move:130')], a: 0,
        ex: 'Gira 90 graus el fa mirar avall. Per mirar amunt havia de girar -90 graus (o apuntar en direcció 0).|Gira 90 grados lo hace mirar abajo. Para mirar arriba tenía que girar -90 grados (o apuntar en dirección 0).' },
      { k: 'move', ph: 'pausa', secs: 30, t: "Brúixola! Dret/a, mira la pissarra: és la direcció 0. Fes <b>gira 90 graus</b> (un quart de volta a la dreta)… un altre… un altre… i un altre. On mires? Exacte, on miraves! Ara, <b>gira -90 graus</b> dues vegades.|¡Brújula! De pie, mira la pizarra: es la dirección 0. Haz <b>gira 90 grados</b> (un cuarto de vuelta a la derecha)… otro… otro… y otro. ¿Dónde miras? ¡Exacto, donde mirabas! Ahora, <b>gira -90 grados</b> dos veces." },
      { k: 'stage', ph: 'repte', q: 'El cotxe ha d\'arribar a la <b>bandera</b>, que és a dalt. Fes-lo girar i després mou-lo.|El coche tiene que llegar a la <b>bandera</b>, que está arriba. Hazlo girar y después muévelo.',
        w: { bg: 'parc', sprites: [{ id: 'cotxe', art: 'cotxe', x: -100, y: -120 }, { id: 'bandera', art: 'bandera', x: -100, y: 120, size: 70 }], goal: [{ k: 'at', s: 'cotxe', r: [-140, 70, -60, 165] }], time: 3 },
        edit: ['cotxe'], hats: ['flag'], pal: ['move', 'turn', 'point'], sol: '@cotxe flag{ turn:-90 move:220 }',
        hint: 'El cotxe mira a la dreta. Primer fes-lo mirar amunt (direcció 0, o gira -90 graus) i després mou-lo uns 220 passos.|El coche mira a la derecha. Primero hazlo mirar arriba (dirección 0, o gira -90 grados) y después muévelo unos 220 pasos.' },
      { k: 'stage', ph: 'repte', q: "Ara la bandera és a l'altra punta: el cotxe ha d'anar <b>primer cap a la dreta</b> i <b>després amunt</b>.|Ahora la bandera está en la otra punta: el coche tiene que ir <b>primero hacia la derecha</b> y <b>después arriba</b>.",
        w: { bg: 'parc', sprites: [{ id: 'cotxe', art: 'cotxe', x: -180, y: -120 }, { id: 'bandera', art: 'bandera', x: 130, y: 120, size: 70 }], goal: [{ k: 'at', s: 'cotxe', r: [90, 70, 170, 165] }], time: 3 },
        edit: ['cotxe'], hats: ['flag'], pal: ['move', 'turn', 'point'], sol: '@cotxe flag{ move:310 turn:-90 move:220 }',
        hint: 'Fes-ho a trossos: quants passos fins a sota la bandera? Després gira cap amunt i puja.|Hazlo a trozos: ¿cuántos pasos hasta debajo de la bandera? Después gira hacia arriba y sube.' },
      { k: 'stage', ph: 'repte', q: 'El paper de la Flama: primer <b>diu</b> «Bon dia!» i després <b>pensa</b> «Quins nervis!».|El papel de Flama: primero <b>dice</b> «¡Buenos días!» y después <b>piensa</b> «¡Qué nervios!».',
        w: G1_T([{ id: 'flama', art: 'flama', x: 0, y: -95 }], { goal: [{ k: 'said', s: 'flama', t: 'Bon dia!|¡Buenos días!' }, { k: 'said', s: 'flama', t: 'Quins nervis!|¡Qué nervios!' }], time: 6 }),
        edit: ['flama'], hats: ['flag'], pal: ['say', 'think'], texts: ['Bon dia!|¡Buenos días!', 'Quins nervis!|¡Qué nervios!', 'Visca el teatre!|¡Viva el teatro!'],
        sol: '@flama flag{ say:"Bon dia!|¡Buenos días!",2 think:"Quins nervis!|¡Qué nervios!",2 }',
        hint: "Un bloc «digues» i un bloc «pensa», cadascun amb la seva frase. Toca el text per triar-la.|Un bloque «di» y un bloque «piensa», cada uno con su frase. Toca el texto para elegirla." },
      { k: 'stage', ph: 'repte', q: "En Vuit entra fins al <b>centre</b>, saluda el públic i se'n torna <b>mirant cap a l'esquerra</b>, cap a la porta.|Vuit entra hasta el <b>centro</b>, saluda al público y se vuelve <b>mirando hacia la izquierda</b>, hacia la puerta.",
        w: G1_T([{ id: 'vuit', art: 'vuit', x: -160, y: -95 }], { goal: [{ k: 'reach', s: 'vuit', r: [-40, -200, 40, 200] }, { k: 'said', s: 'vuit' }, { k: 'at', s: 'vuit', r: [-200, -200, -120, 200] }, { k: 'dir', s: 'vuit', d: -90 }], time: 6 }),
        edit: ['vuit'], hats: ['flag'], pal: ['move', 'turn', 'point', 'say'], texts: ['Hola, públic!|¡Hola, público!', 'Gràcies per venir!|¡Gracias por venir!'],
        sol: '@vuit flag{ move:160 say:"Hola, públic!|¡Hola, público!",2 point:-90 move:160 }',
        hint: "Per tornar mirant cap a l'esquerra, primer apunta en direcció -90 i després mou-te amb un número positiu.|Para volver mirando hacia la izquierda, primero apunta en dirección -90 y después muévete con un número positivo." },
      { k: 'screate', ph: 'crea', name: "L'assaig del Cavaller|El ensayo del Caballero",
        q: "Fes l'assaig d'en <b>Cavaller</b>: que <b>es mogui</b>, que <b>giri</b> almenys una vegada i que <b>digui dues frases</b>, una darrere l'altra. La resta, com vulguis!|Haz el ensayo del <b>Caballero</b>: que <b>se mueva</b>, que <b>gire</b> al menos una vez y que <b>diga dos frases</b>, una detrás de otra. ¡El resto, como quieras!",
        crit: ['Es mou|Se mueve', 'Gira o apunta cap a un altre costat|Gira o apunta hacia otro lado', 'Diu dues frases amb segons|Dice dos frases con segundos'],
        w: G1_T([{ id: 'cavaller', art: 'cavaller', x: -150, y: -95 }], { goal: [{ k: 'moved', s: 'cavaller', min: 30 }, { k: 'turned', s: 'cavaller' }, { k: 'said', s: 'cavaller' }], noEarly: true, time: 10 }),
        edit: ['cavaller'], hats: ['flag'], pal: ['move', 'turn', 'point', 'say', 'think'], texts: ['Soc el cavaller!|¡Soy el caballero!', "I ara me'n vaig.|Y ahora me voy.", 'On és el drac?|¿Dónde está el dragón?'],
        check: P => G1_SAYS(P.cavaller) >= 2 ? null : "Funciona, però en Cavaller només diu una frase. Afegeix-ne una altra!|Funciona, pero el Caballero solo dice una frase. ¡Añade otra!",
        sol: `@cavaller flag{ move:120 say:"Soc el cavaller!|¡Soy el caballero!",2 point:-90 say:"I ara me'n vaig.|Y ahora me voy.",2 move:100 }` },
      { k: 'quiz', ph: 'tanca', q: "Quina direcció vol dir mirar a l'<b>esquerra</b>?|¿Qué dirección quiere decir mirar a la <b>izquierda</b>?", opts: ['-90|-90', '90|90', '0|0'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: 'Per què posem <b>durant 2 s</b> a les frases?|¿Por qué ponemos <b>durante 2 s</b> en las frases?',
        opts: ['Perquè la frase es vegi i després vingui la següent|Para que la frase se vea y después venga la siguiente', 'Perquè el personatge camini més de pressa|Para que el personaje camine más deprisa', 'Perquè la frase surti més gran|Para que la frase salga más grande'], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 3 · Fons i escenes ---------- */
  { id: 'g1-3', t: 'Fons i escenes|Fondos y escenas', min: 40, badge: 'g_decorat',
    learn: ["El fons és el decorat de l'escenari: es pot canviar a un fons concret o al fons següent de la llista.|El fondo es el decorado del escenario: se puede cambiar a un fondo concreto o al fondo siguiente de la lista.",
      "Una escena és un tros de la història en un lloc: un fons, uns personatges i el que fan i diuen.|Una escena es un trozo de la historia en un lugar: un fondo, unos personajes y lo que hacen y dicen.",
      "«Amaga't» fa sortir un personatge de l'escena i «mostra't» el torna a fer veure.|«Escóndete» hace salir a un personaje de la escena y «muéstrate» lo vuelve a hacer visible."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Un personatge mira a la dreta i fa <b>gira -90 graus</b>. Cap on mira ara?|Un personaje mira a la derecha y hace <b>gira -90 grados</b>. ¿Hacia dónde mira ahora?',
        opts: ['Amunt (0)|Arriba (0)', 'Avall (180)|Abajo (180)', "A l'esquerra (-90)|A la izquierda (-90)"], a: 0, ex: "-90 és un quart de volta cap a l'esquerra: de la dreta passa a mirar amunt.|-90 es un cuarto de vuelta hacia la izquierda: de la derecha pasa a mirar arriba." },
      { k: 'story', ph: 'missio', who: 'both', scene: 'taller', title: 'Els decorats|Los decorados',
        t: "Al taller del teatre pinten <b>decorats</b>: un bosc, una platja, una nit plena d'estrelles… A l'ordinador, el decorat és el <b>fons</b> de l'escenari, i el pots canviar amb un sol bloc. Avui farem històries que viatgen d'un lloc a un altre!|En el taller del teatro pintan <b>decorados</b>: un bosque, una playa, una noche llena de estrellas… En el ordenador, el decorado es el <b>fondo</b> del escenario, y lo puedes cambiar con un solo bloque. ¡Hoy haremos historias que viajan de un sitio a otro!" },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Fons|Fondo', t: "El fons de l'escenari|El fondo del escenario", anim: 'g1bg',
          x: "El <span class='hl'>fons</span> és el dibuix de darrere de tot. Quan canvia el fons, els personatges <b>es queden on són</b>: és com canviar el decorat del teatre mentre els actors esperen.|El <span class='hl'>fondo</span> es el dibujo de detrás de todo. Cuando cambia el fondo, los personajes <b>se quedan donde están</b>: es como cambiar el decorado del teatro mientras los actores esperan." },
        { k: 'Canvia el fons|Cambia el fondo', t: 'Canvia el fons a…|Cambia el fondo a…',
          media: { k: 'stage', w: { bg: 'bosc', bgs: ['bosc', 'platja', 'espai'], sprites: [{ id: 'numi', art: 'numi', x: 0, y: -60, costume: 1 }] }, prog: `@numi flag{ say:"Som al bosc.|Estamos en el bosque.",2 bg:platja say:"Ara, a la platja!|¡Ahora, a la playa!",2 bg:espai say:"I ara, a l'espai!|¡Y ahora, al espacio!",2 }`, time: 7 },
          x: "El bloc <b>canvia el fons a</b> posa el fons que triïs. Si el poses entre dues frases, la història canvia de lloc: primer al bosc, després a la platja…|El bloque <b>cambia el fondo a</b> pone el fondo que elijas. Si lo pones entre dos frases, la historia cambia de sitio: primero en el bosque, después en la playa…" },
        { k: 'Fons següent|Fondo siguiente', t: "Un fons darrere l'altre|Un fondo detrás de otro",
          media: { k: 'stage', w: { bg: 'bosc', bgs: ['bosc', 'platja', 'espai'], sprites: [{ id: 'guida', art: 'guida', x: 0, y: -60 }] }, prog: '@guida flag{ say:"1|1",1 nextbg say:"2|2",1 nextbg say:"3|3",1 nextbg say:"I tornem al primer!|¡Y volvemos al primero!",2 }', time: 6 },
          x: "<b>Fons següent</b> passa al fons que ve després a la llista. Quan arriba a l'últim, <b>torna al primer</b>, com quan passes les pàgines d'un calendari i tornes a gener.|<b>Fondo siguiente</b> pasa al fondo que viene después en la lista. Cuando llega al último, <b>vuelve al primero</b>, como cuando pasas las páginas de un calendario y vuelves a enero." },
        { k: 'Sortir de l\'escena|Salir de la escena', t: "Amaga't i mostra't|Escóndete y muéstrate",
          media: { k: 'stage', w: { bg: 'nit', sprites: [{ id: 'estel', art: 'estel', x: 90, y: -40 }, { id: 'numi', art: 'numi', x: -100, y: -60, costume: 2 }] }, prog: '@estel flag{ say:"Adéu, me\'n vaig!|¡Adiós, me voy!",2 hide } @numi flag{ think:"…|…",2 say:"On és l\'Estel?|¿Dónde está Estel?",3 }', time: 6 },
          x: "<b>Amaga't</b> fa desaparèixer el personatge de l'escenari: continua existint, però no es veu. <b>Mostra't</b> el torna a fer veure. Serveixen per fer que un personatge entri o surti de l'escena.|<b>Escóndete</b> hace desaparecer al personaje del escenario: sigue existiendo, pero no se ve. <b>Muéstrate</b> lo vuelve a hacer visible. Sirven para que un personaje entre o salga de la escena.",
          tip: 'Quan tornes a tocar la bandera, tot torna a començar com al principi: també els personatges amagats.|Cuando vuelves a tocar la bandera, todo vuelve a empezar como al principio: también los personajes escondidos.' },
        { k: 'Escena|Escena', t: "Una història feta d'escenes|Una historia hecha de escenas", anim: 'g1scene',
          x: "Una <span class='hl'>escena</span> és un tros de la història que passa en un lloc: té un fons, uns personatges i el que fan i diuen. Abans de programar, dibuixa les escenes com les vinyetes d'un còmic: és el <b>guió gràfic</b>.|Una <span class='hl'>escena</span> es un trozo de la historia que pasa en un lugar: tiene un fondo, unos personajes y lo que hacen y dicen. Antes de programar, dibuja las escenas como las viñetas de un cómic: es el <b>guion gráfico</b>." }
      ] },
      { k: 'quiz', ph: 'prova', q: "Els fons són <b>bosc, platja i espai</b>, en aquest ordre. Ara es veu l'<b>espai</b>. Què fa <b>fons següent</b>?|Los fondos son <b>bosque, playa y espacio</b>, en este orden. Ahora se ve el <b>espacio</b>. ¿Qué hace <b>fondo siguiente</b>?",
        opts: ['Torna al bosc, el primer|Vuelve al bosque, el primero', "Es queda a l'espai|Se queda en el espacio", 'La pantalla es posa negra|La pantalla se pone negra'], a: 0,
        ex: 'Després de l\'últim fons, torna a començar pel primer.|Después del último fondo, vuelve a empezar por el primero.' },
      { k: 'seq', ph: 'mans', q: "<b>Ordena el guió</b> de la Guida: comença al bosc, viatja a la platja i, al final, surt de l'escena.|<b>Ordena el guion</b> de Guida: empieza en el bosque, viaja a la playa y, al final, sale de la escena.",
        items: ['canvia el fons a bosc|cambia el fondo a bosque', 'digues «Quin bosc tan verd!» durant 2 s|di «¡Qué bosque tan verde!» durante 2 s', 'canvia el fons a platja|cambia el fondo a playa', 'digues «Quina calor!» durant 2 s|di «¡Qué calor!» durante 2 s', "amaga't|escóndete"],
        ex: 'Cada escena comença amb el seu fons i després ve el que diu el personatge.|Cada escena empieza con su fondo y después viene lo que dice el personaje.' },
      { k: 'unplug', ph: 'mans', ico: '🎴', title: 'El guió gràfic|El guion gráfico',
        t: "Amb algú de casa, inventeu una història molt curta de <b>3 escenes</b> i dibuixeu-la en un paper, com un còmic.|Con alguien de casa, inventad una historia muy corta de <b>3 escenas</b> y dibujadla en un papel, como un cómic.",
        steps: ['Dibuixeu 3 requadres: cada un és una escena.|Dibujad 3 recuadros: cada uno es una escena.', 'A cada requadre: on passa (el fons), qui hi surt (els personatges) i què diuen.|En cada recuadro: dónde pasa (el fondo), quién sale (los personajes) y qué dicen.',
          "Expliqueu la història en veu alta, escena a escena.|Explicad la historia en voz alta, escena a escena.", 'Penseu quins blocs caldrien: «canvia el fons a…», «digues…», «amaga\'t»…|Pensad qué bloques harían falta: «cambia el fondo a…», «di…», «escóndete»…'],
        tip: 'Els creadors de dibuixos animats també fan guions gràfics abans de començar.|Los creadores de dibujos animados también hacen guiones gráficos antes de empezar.' },
      { k: 'sfree', ph: 'prova', q: 'La Tuga se\'n va de viatge. Toca la bandera verda i <b>compta quants fons</b> veus. Després mira el seu guió.|Tuga se va de viaje. Toca la bandera verde y <b>cuenta cuántos fondos</b> ves. Después mira su guion.',
        w: G1_T([{ id: 'tuga', art: 'tuga', x: 0, y: -80 }], { bgs: ['escenari', 'bosc', 'platja', 'nit'] }),
        prog: '@tuga flag{ say:"Comença el viatge!|¡Empieza el viaje!",2 bg:bosc say:"Primer, el bosc.|Primero, el bosque.",2 bg:platja say:"Després, la platja.|Después, la playa.",2 bg:nit say:"I bona nit!|¡Y buenas noches!",2 hide }' },
      { k: 'quiz', ph: 'investiga', q: 'Mira aquest guió: <b>canvia el fons a platja</b> → <b>digues «Hola!» 2 s</b> → <b>canvia el fons a nit</b>. Quin fons es veu al final?|Mira este guion: <b>cambia el fondo a playa</b> → <b>di «¡Hola!» 2 s</b> → <b>cambia el fondo a noche</b>. ¿Qué fondo se ve al final?',
        opts: ['La nit|La noche', 'La platja|La playa', 'El fons del principi|El fondo del principio'], a: 0, ex: "Els blocs es fan de dalt a baix: l'últim fons que es posa és la nit.|Los bloques se hacen de arriba abajo: el último fondo que se pone es la noche." },
      { k: 'sfree', ph: 'investiga', q: "La història d'en Numi havia d'acabar a la <b>platja</b>, però alguna cosa falla. Toca la bandera verda i <b>mira on acaba</b>.|La historia de Numi tenía que terminar en la <b>playa</b>, pero algo falla. Toca la bandera verde y <b>mira dónde termina</b>.",
        w: { bg: 'bosc', bgs: ['bosc', 'platja', 'espai'], sprites: [{ id: 'numi', art: 'numi', x: 0, y: -60 }] },
        prog: '@numi flag{ say:"Som al bosc.|Estamos en el bosque.",2 say:"Ara anem a la platja!|¡Ahora vamos a la playa!",2 bg:espai say:"Quina platja tan fosca…|Qué playa tan oscura…",2 }' },
      { k: 'quiz', ph: 'investiga', keep: true, q: "Aquest és el guió d'en Numi. <b>Quin bloc cal arreglar?</b>|Este es el guion de Numi. <b>¿Qué bloque hay que arreglar?</b>",
        opts: [G1_CHIP('say:"Som al bosc.|Estamos en el bosque.",2'), G1_CHIP('say:"Ara anem a la platja!|¡Ahora vamos a la playa!",2'), G1_CHIP('bg:espai'), G1_CHIP('say:"Quina platja tan fosca…|Qué playa tan oscura…",2')], a: 2,
        ex: 'Aquest bloc posa l\'espai. Havia de dir «canvia el fons a platja».|Este bloque pone el espacio. Tenía que decir «cambia el fondo a playa».' },
      { k: 'move', ph: 'pausa', secs: 30, t: "Canvi de decorat! Quan sentis <b>bosc</b>, fes d'arbre amb els braços amunt. <b>Platja</b>: fes que nedes. <b>Espai</b>: fes d'astronauta que flota. <b>Amaga't</b>: ajup-te! (Algú de casa o el professor/a diu els fons cada vegada més de pressa.)|¡Cambio de decorado! Cuando oigas <b>bosque</b>, haz de árbol con los brazos arriba. <b>Playa</b>: haz que nadas. <b>Espacio</b>: haz de astronauta que flota. <b>Escóndete</b>: ¡agáchate! (Alguien de casa o el profesor/a dice los fondos cada vez más deprisa.)" },
      { k: 'stage', ph: 'repte', q: 'En Numi vol anar a la platja. Fes que digui <b>«Anem a la platja!»</b> i després <b>canviï el fons</b> a la platja.|Numi quiere ir a la playa. Haz que diga <b>«¡Vamos a la playa!»</b> y después <b>cambie el fondo</b> a la playa.',
        w: { bg: 'bosc', bgs: ['bosc', 'platja', 'espai'], sprites: [{ id: 'numi', art: 'numi', x: 0, y: -60 }], goal: [{ k: 'said', s: 'numi', t: 'Anem a la platja!|¡Vamos a la playa!' }, { k: 'bg', n: 'platja' }], time: 4 },
        edit: ['numi'], hats: ['flag'], pal: ['say', 'bg'], texts: ['Anem a la platja!|¡Vamos a la playa!', 'Quin bosc!|¡Qué bosque!'],
        sol: '@numi flag{ say:"Anem a la platja!|¡Vamos a la playa!",2 bg:platja }',
        hint: 'Primer el bloc «digues» i després «canvia el fons a». Toca el nom del fons per triar la platja.|Primero el bloque «di» y después «cambia el fondo a». Toca el nombre del fondo para elegir la playa.' },
      { k: 'stage', ph: 'repte', q: "El viatge de la Guida: ha d'anar del bosc a l'<b>espai</b>, passant per la platja, i dir alguna cosa a cada lloc. Aquí només tens el bloc <b>fons següent</b>.|El viaje de Guida: tiene que ir del bosque al <b>espacio</b>, pasando por la playa, y decir algo en cada sitio. Aquí solo tienes el bloque <b>fondo siguiente</b>.",
        w: { bg: 'bosc', bgs: ['bosc', 'platja', 'espai'], sprites: [{ id: 'guida', art: 'guida', x: 0, y: -60 }], goal: [{ k: 'bg', n: 'espai' }, { k: 'bgs', min: 2 }, { k: 'said', s: 'guida' }], time: 6 },
        edit: ['guida'], hats: ['flag'], pal: ['say', 'nextbg'], texts: ['Al bosc!|¡Al bosque!', 'A la platja!|¡A la playa!', "A l'espai!|¡Al espacio!"],
        sol: `@guida flag{ say:"Al bosc!|¡Al bosque!",1 nextbg say:"A la platja!|¡A la playa!",1 nextbg say:"A l'espai!|¡Al espacio!",2 }`,
        hint: "Cada «fons següent» avança un fons de la llista. Quants en calen per anar del bosc a l'espai?|Cada «fondo siguiente» avanza un fondo de la lista. ¿Cuántos hacen falta para ir del bosque al espacio?" },
      { k: 'stage', ph: 'repte', q: "Final de l'obra: l'Estel s'acomiada del públic dient <b>«Adéu!»</b> i després <b>s'amaga</b>.|Final de la obra: Estel se despide del público diciendo <b>«¡Adiós!»</b> y después <b>se esconde</b>.",
        w: { bg: 'nit', sprites: [{ id: 'estel', art: 'estel', x: 0, y: -40 }], goal: [{ k: 'said', s: 'estel', t: 'Adéu!|¡Adiós!' }, { k: 'hidden', s: 'estel' }], time: 4 },
        edit: ['estel'], hats: ['flag'], pal: ['say', 'move', 'hide', 'show'], texts: ['Adéu!|¡Adiós!', 'Bona nit!|¡Buenas noches!'],
        sol: '@estel flag{ say:"Adéu!|¡Adiós!",2 hide }',
        hint: "Primer «digues Adéu!» amb segons, perquè es pugui llegir, i després «amaga't».|Primero «di ¡Adiós!» con segundos, para que se pueda leer, y después «escóndete»." },
      { k: 'stage', ph: 'repte', q: "Aquesta història té les escenes en <b>mal ordre</b>: havia de passar primer al <b>bosc</b> i acabar de <b>nit</b>, però acaba al bosc. <b>Arregla-la.</b>|Esta historia tiene las escenas en <b>mal orden</b>: tenía que pasar primero en el <b>bosque</b> y terminar de <b>noche</b>, pero termina en el bosque. <b>Arréglala.</b>",
        w: G1_T([{ id: 'guida', art: 'guida', x: 0, y: -80 }], { bgs: ['escenari', 'bosc', 'nit'], goal: [{ k: 'bg', n: 'nit' }, { k: 'bgs', min: 2 }, { k: 'said', s: 'guida' }], time: 8 }),
        edit: ['guida'], hats: ['flag'], pal: ['say', 'bg'],
        prog: '@guida flag{ say:"Comença la funció!|¡Empieza la función!",2 bg:nit say:"Bon dia, bosc!|¡Buenos días, bosque!",2 bg:bosc say:"Bona nit a tothom!|¡Buenas noches a todos!",2 }',
        sol: '@guida flag{ say:"Comença la funció!|¡Empieza la función!",2 bg:bosc say:"Bon dia, bosc!|¡Buenos días, bosque!",2 bg:nit say:"Bona nit a tothom!|¡Buenas noches a todos!",2 }',
        hint: 'Mira els dos blocs de fons: estan intercanviats. Toca el nom de cada fons per canviar-lo.|Mira los dos bloques de fondo: están intercambiados. Toca el nombre de cada fondo para cambiarlo.' },
      { k: 'screate', ph: 'crea', name: 'La meva escena|Mi escena',
        q: "Crea una història de <b>dues escenes o més</b>: la Flama diu coses en un lloc i després en un altre. Tria els fons que vulguis i, si vols, fes que surti de l'escena al final.|Crea una historia de <b>dos escenas o más</b>: Flama dice cosas en un sitio y después en otro. Elige los fondos que quieras y, si quieres, haz que salga de la escena al final.",
        crit: ['Hi ha almenys 2 fons diferents|Hay al menos 2 fondos diferentes', 'La Flama diu alguna cosa a cada escena|Flama dice algo en cada escena'],
        w: G1_T([{ id: 'flama', art: 'flama', x: 0, y: -80 }], { bgs: ['escenari', 'bosc', 'platja', 'espai', 'ciutat', 'parc', 'nit'], goal: [{ k: 'bgs', min: 1 }, { k: 'said', s: 'flama' }], noEarly: true, time: 12 }),
        edit: ['flama'], hats: ['flag'], pal: ['say', 'think', 'bg', 'nextbg', 'move', 'turn', 'point', 'hide', 'show'], texts: ['Hola! Soc la Flama.|¡Hola! Soy Flama.', "M'agrada el bosc.|Me gusta el bosque.", "I també l'espai!|¡Y también el espacio!", 'Adéu!|¡Adiós!'],
        check: P => G1_SAYS(P.flama) >= 2 ? null : 'Funciona, però la Flama només diu una frase. Fes que digui alguna cosa a cada escena!|Funciona, pero Flama solo dice una frase. ¡Haz que diga algo en cada escena!',
        sol: `@flama flag{ say:"Hola! Soc la Flama.|¡Hola! Soy Flama.",2 bg:bosc say:"M'agrada el bosc.|Me gusta el bosque.",2 bg:espai say:"I també l'espai!|¡Y también el espacio!",2 hide }` },
      { k: 'quiz', ph: 'tanca', q: 'Quan canvia el fons, què passa amb els personatges?|Cuando cambia el fondo, ¿qué pasa con los personajes?', opts: ['Es queden on són|Se quedan donde están', 'Desapareixen|Desaparecen', 'Tornen al centre|Vuelven al centro'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "Quin bloc fa que un personatge <b>surti de l'escena</b> sense moure'l?|¿Qué bloque hace que un personaje <b>salga de la escena</b> sin moverlo?", opts: ["amaga't|escóndete", 'canvia el fons a nit|cambia el fondo a noche', 'pensa «Adéu»|piensa «Adiós»'], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] },

  /* ---------- Sessió 4 · Projecte: presenta't ---------- */
  { id: 'g1-4', t: "Projecte: presenta't|Proyecto: preséntate", min: 45, proj: true, badge: 'g_presenta',
    learn: ['Un projecte es fa en quatre passos: pensar el pla, programar-lo, provar-lo i millorar-lo.|Un proyecto se hace en cuatro pasos: pensar el plan, programarlo, probarlo y mejorarlo.',
      'Es pot construir un programa a trossos: primer una part, es prova, i després la següent.|Se puede construir un programa a trozos: primero una parte, se prueba, y después la siguiente.',
      "En un projecte que veuran altres persones, mai no hi posem l'adreça, el telèfon ni altres dades privades.|En un proyecto que verán otras personas, nunca ponemos la dirección, el teléfono ni otros datos privados."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Quin bloc passa al fons que ve <b>després</b> a la llista?|¿Qué bloque pasa al fondo que viene <b>después</b> en la lista?', opts: ['fons següent|fondo siguiente', 'canvia el fons a bosc|cambia el fondo a bosque', "mostra't|muéstrate"], a: 0 },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'poble', title: 'La gran estrena|El gran estreno', art: () => TANI.g1stage(true),
        t: "Avui és l'<b>estrena</b> al Teatre de l'illa! Cada programador/a presenta un personatge que <b>parla de tu</b>: com et dius, què t'agrada fer i quin és el teu lloc preferit. És el teu primer <b>projecte</b>!|¡Hoy es el <b>estreno</b> en el Teatro de la isla! Cada programador/a presenta a un personaje que <b>habla de ti</b>: cómo te llamas, qué te gusta hacer y cuál es tu sitio favorito. ¡Es tu primer <b>proyecto</b>!" },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy',
        t: "BIP! Un projecte de debò es fa en quatre passos: <b>pensar el pla</b>, <b>programar-lo</b>, <b>provar-lo</b> i <b>millorar-lo</b>. I es construeix a trossos, com un trencaclosques. Som-hi!|¡BIP! Un proyecto de verdad se hace en cuatro pasos: <b>pensar el plan</b>, <b>programarlo</b>, <b>probarlo</b> y <b>mejorarlo</b>. Y se construye a trozos, como un rompecabezas. ¡Vamos!" },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'El projecte|El proyecto', t: 'Una presentació amb blocs|Una presentación con bloques',
          media: { k: 'stage', w: G1_T([{ id: 'tuga', art: 'tuga', x: -170, y: -95 }], { bgs: ['escenari', 'platja'] }), prog: `@tuga flag{ move:170 say:"Hola! Em dic Tuga.|¡Hola! Me llamo Tuga.",2 say:"M'agrada nedar a poc a poc.|Me gusta nadar despacito.",2 bg:platja say:"El meu lloc preferit és la platja!|¡Mi sitio favorito es la playa!",2 point:-90 move:170 hide }`, time: 9 },
          x: "Mira com es presenta la Tuga: <b>entra</b>, diu <b>el seu nom</b> i <b>què li agrada</b>, canvia el fons al seu <b>lloc preferit</b> i <b>se'n va</b>. Tu faràs el mateix amb el teu personatge, però parlant de tu.|Mira cómo se presenta Tuga: <b>entra</b>, dice <b>su nombre</b> y <b>lo que le gusta</b>, cambia el fondo a su <b>sitio favorito</b> y <b>se va</b>. Tú harás lo mismo con tu personaje, pero hablando de ti." },
        { k: 'El pla|El plan', t: 'Primer, el pla|Primero, el plan', anim: 'g1plan',
          x: "Abans de posar blocs, pensa el pla: <b>com et dius</b>, <b>què t'agrada fer</b> i <b>quin és el teu lloc preferit</b> (serà el fons). Amb el pla clar, programar és molt més fàcil.|Antes de poner bloques, piensa el plan: <b>cómo te llamas</b>, <b>qué te gusta hacer</b> y <b>cuál es tu sitio favorito</b> (será el fondo). Con el plan claro, programar es mucho más fácil.",
          bad: '«Em dic Laia Puig i visc al carrer de les Roses, 5.»|«Me llamo Laia Puig y vivo en la calle de las Rosas, 5.»', good: "«Em dic Laia i m'agrada dibuixar.» Només el nom de pila: res d'adreces, telèfons ni escola.|«Me llamo Laia y me gusta dibujar.» Solo el nombre de pila: nada de direcciones, teléfonos ni colegio." },
        { k: 'Provar|Probar', t: 'Prova-ho com si fossis el públic|Pruébalo como si fueras el público',
          media: { k: 'stage', w: G1_T([{ id: 'guida', art: 'guida', x: 0, y: -95 }]), prog: '@guida flag{ say:"Hola!|¡Hola!" say:"Em dic Guida.|Me llamo Guida.",2 say:"M\'agrada córrer.|Me gusta correr.",2 }', time: 5 },
          x: "Quan acabis, toca la bandera i mira-ho com si fossis el públic. Es llegeixen bé totes les frases? Aquí, el primer <b>digues</b> no té segons i desapareix tan de pressa que no es veu: és un error fàcil d'arreglar. <b>Provar i millorar</b> és part de la feina!|Cuando termines, toca la bandera y míralo como si fueras el público. ¿Se leen bien todas las frases? Aquí, el primer <b>di</b> no tiene segundos y desaparece tan deprisa que no se ve: es un error fácil de arreglar. ¡<b>Probar y mejorar</b> es parte del trabajo!" }
      ] },
      { k: 'seq', ph: 'mans', q: '<b>Ordena el pla</b> de la presentació de la Tuga.|<b>Ordena el plan</b> de la presentación de Tuga.',
        items: ["Entra a l'escenari (mou-te)|Entra en el escenario (muévete)", 'Diu el seu nom|Dice su nombre', "Diu què li agrada fer|Dice qué le gusta hacer", 'Canvia el fons al seu lloc preferit|Cambia el fondo a su sitio favorito', "S'acomiada i se'n va|Se despide y se va"],
        ex: "Aquest ordre és el pla: després només cal passar cada pas a blocs.|Este orden es el plan: después solo hay que pasar cada paso a bloques." },
      { k: 'unplug', ph: 'mans', ico: '📝', title: 'El meu pla|Mi plan',
        t: "Abans de programar, escriu el pla en un paper (o explica'l en veu alta a algú de casa).|Antes de programar, escribe el plan en un papel (o explícalo en voz alta a alguien de casa).",
        steps: ['Com em dic? (només el nom de pila)|¿Cómo me llamo? (solo el nombre de pila)', "Què m'agrada fer?|¿Qué me gusta hacer?", 'Quin és el meu lloc preferit? (bosc, platja, espai, ciutat, parc o nit)|¿Cuál es mi sitio favorito? (bosque, playa, espacio, ciudad, parque o noche)',
          'Com entrarà el meu personatge i com se n\'anirà?|¿Cómo entrará mi personaje y cómo se irá?'],
        tip: "Recorda: ni l'adreça, ni el telèfon, ni el nom de l'escola. Una presentació bonica no ho necessita!|Recuerda: ni la dirección, ni el teléfono, ni el nombre del colegio. ¡Una presentación bonita no lo necesita!" },
      { k: 'quiz', ph: 'prova', q: 'Quina d\'aquestes frases <b>no</b> hauria de dir la teva presentació?|¿Cuál de estas frases <b>no</b> debería decir tu presentación?',
        opts: ['«Visc al carrer de les Roses, número 5.»|«Vivo en la calle de las Rosas, número 5.»', "«M'agrada molt dibuixar.»|«Me gusta mucho dibujar.»", '«Em dic Laia.»|«Me llamo Laia.»'], a: 0,
        ex: "L'adreça és una dada privada: no la posem mai en un projecte que veuran altres persones.|La dirección es un dato privado: no la ponemos nunca en un proyecto que verán otras personas." },
      { k: 'sfree', ph: 'investiga', q: "Mira la presentació d'en Vuit: toca la bandera verda. Pots llegir totes les frases?|Mira la presentación de Vuit: toca la bandera verde. ¿Puedes leer todas las frases?",
        w: G1_T([{ id: 'vuit', art: 'vuit', x: -100, y: -95 }]),
        prog: `@vuit flag{ move:100 say:"Hola! Em dic Vuit.|¡Hola! Me llamo Vuit." say:"M'agraden els pops.|Me gustan los pulpos.",2 }` },
      { k: 'quiz', ph: 'investiga', keep: true, q: "La primera frase d'en Vuit desapareix tan de pressa que no es pot llegir. <b>Quin bloc cal arreglar?</b>|La primera frase de Vuit desaparece tan deprisa que no se puede leer. <b>¿Qué bloque hay que arreglar?</b>",
        opts: [G1_CHIP('move:100'), G1_CHIP('say:"Hola! Em dic Vuit.|¡Hola! Me llamo Vuit."'), G1_CHIP(`say:"M'agraden els pops.|Me gustan los pulpos.",2`)], a: 1,
        ex: "A aquest «digues» li falten els segons: amb «durant 2 s» es podria llegir.|A este «di» le faltan los segundos: con «durante 2 s» se podría leer." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Presenta't en moviment! Fes un pas endavant i digues el teu nom. Fes un gest del que t'agrada fer (dibuixar, córrer, cantar…). Fes una pose del teu lloc preferit. I, per acabar, una gran reverència!|¡Preséntate en movimiento! Da un paso adelante y di tu nombre. Haz un gesto de lo que te gusta hacer (dibujar, correr, cantar…). Haz una pose de tu sitio favorito. Y, para terminar, ¡una gran reverencia!" },
      { k: 'stage', ph: 'repte', q: "Tros 1 del projecte: la Guida <b>entra</b> a l'escenari i <b>diu el seu nom</b>.|Trozo 1 del proyecto: Guida <b>entra</b> en el escenario y <b>dice su nombre</b>.",
        w: G1_T([{ id: 'guida', art: 'guida', x: -180, y: -95 }], { goal: [{ k: 'dx', s: 'guida', min: 80 }, { k: 'said', s: 'guida', t: 'Hola! Em dic Guida.|¡Hola! Me llamo Guida.' }], time: 4 }),
        edit: ['guida'], hats: ['flag'], pal: ['move', 'say'], texts: ['Hola! Em dic Guida.|¡Hola! Me llamo Guida.', "M'agrada córrer pel bosc.|Me gusta correr por el bosque."],
        sol: '@guida flag{ move:180 say:"Hola! Em dic Guida.|¡Hola! Me llamo Guida.",2 }',
        hint: "Un «mou-te» cap a la dreta i un «digues» amb la frase del nom.|Un «muévete» hacia la derecha y un «di» con la frase del nombre." },
      { k: 'stage', ph: 'repte', q: "Tros 2: continua el guió. Ara la Guida diu <b>què li agrada</b> i després <b>canvia el fons</b> al seu lloc preferit, el <b>bosc</b>.|Trozo 2: continúa el guion. Ahora Guida dice <b>lo que le gusta</b> y después <b>cambia el fondo</b> a su sitio favorito, el <b>bosque</b>.",
        w: G1_T([{ id: 'guida', art: 'guida', x: -180, y: -95 }], { bgs: ['escenari', 'bosc', 'platja'], goal: [{ k: 'said', s: 'guida', t: 'Hola! Em dic Guida.|¡Hola! Me llamo Guida.' }, { k: 'said', s: 'guida', t: "M'agrada córrer pel bosc.|Me gusta correr por el bosque." }, { k: 'bg', n: 'bosc' }], time: 6 }),
        edit: ['guida'], hats: ['flag'], pal: ['move', 'say', 'bg'], texts: ['Hola! Em dic Guida.|¡Hola! Me llamo Guida.', "M'agrada córrer pel bosc.|Me gusta correr por el bosque."],
        prog: '@guida flag{ move:180 say:"Hola! Em dic Guida.|¡Hola! Me llamo Guida.",2 }',
        sol: `@guida flag{ move:180 say:"Hola! Em dic Guida.|¡Hola! Me llamo Guida.",2 say:"M'agrada córrer pel bosc.|Me gusta correr por el bosque.",2 bg:bosc }`,
        hint: "Afegeix els blocs nous a sota dels que ja hi ha: un «digues» amb la segona frase i un «canvia el fons a bosc».|Añade los bloques nuevos debajo de los que ya hay: un «di» con la segunda frase y un «cambia el fondo a bosque»." },
      { k: 'stage', ph: 'repte', q: "Tros 3: el comiat. Al final, la Guida <b>es gira cap a l'esquerra</b>, se'n va i <b>s'amaga</b>.|Trozo 3: la despedida. Al final, Guida <b>se gira hacia la izquierda</b>, se va y <b>se esconde</b>.",
        w: G1_T([{ id: 'guida', art: 'guida', x: -180, y: -95 }], { bgs: ['escenari', 'bosc', 'platja'], goal: [{ k: 'bg', n: 'bosc' }, { k: 'dir', s: 'guida', d: -90 }, { k: 'hidden', s: 'guida' }], time: 8 }),
        edit: ['guida'], hats: ['flag'], pal: ['move', 'turn', 'point', 'say', 'bg', 'hide'], texts: ['Hola! Em dic Guida.|¡Hola! Me llamo Guida.', "M'agrada córrer pel bosc.|Me gusta correr por el bosque.", 'Adéu!|¡Adiós!'],
        prog: `@guida flag{ move:180 say:"Hola! Em dic Guida.|¡Hola! Me llamo Guida.",2 say:"M'agrada córrer pel bosc.|Me gusta correr por el bosque.",2 bg:bosc }`,
        sol: `@guida flag{ move:180 say:"Hola! Em dic Guida.|¡Hola! Me llamo Guida.",2 say:"M'agrada córrer pel bosc.|Me gusta correr por el bosque.",2 bg:bosc point:-90 move:150 hide }`,
        hint: "A sota de tot: apunta en direcció -90, mou-te i amaga't.|Debajo de todo: apunta en dirección -90, muévete y escóndete." },
      { k: 'screate', ph: 'crea', name: "Presenta't|Preséntate",
        q: "<b>Projecte: presenta't!</b> Tria un dels tres personatges (a dalt) i programa'l perquè parli de tu. Segueix el teu pla i prova-ho tantes vegades com calgui.|<b>¡Proyecto: preséntate!</b> Elige uno de los tres personajes (arriba) y prográmalo para que hable de ti. Sigue tu plan y pruébalo tantas veces como haga falta.",
        crit: ['Diu el teu nom (només el nom de pila)|Dice tu nombre (solo el nombre de pila)', "Diu què t'agrada fer|Dice lo que te gusta hacer", 'Canvia el fons al teu lloc preferit|Cambia el fondo a tu sitio favorito', 'Es mou o gira almenys una vegada|Se mueve o gira al menos una vez'],
        w: G1_T([{ id: 'guida', art: 'guida', x: -165, y: -95 }, { id: 'flama', art: 'flama', x: 0, y: -95 }, { id: 'cavaller', art: 'cavaller', x: 165, y: -95 }], { bgs: ['escenari', 'bosc', 'platja', 'espai', 'ciutat', 'parc', 'nit'], goal: [{ k: 'said' }, { k: 'bgs', min: 1 }], noEarly: true, time: 16 }),
        edit: ['guida', 'flama', 'cavaller'], hats: ['flag'], pal: ['move', 'turn', 'point', 'say', 'think', 'bg', 'nextbg', 'hide', 'show'],
        texts: ['Hola! Em dic…|¡Hola! Me llamo…', "M'agrada…|Me gusta…", 'El meu lloc preferit és…|Mi sitio favorito es…', 'Gràcies per mirar!|¡Gracias por mirar!'],
        check: P => ['guida', 'flama', 'cavaller'].some(id => G1_SAYS(P[id]) >= 3 && G1_HAS(P[id], ['move', 'turn', 'point'])) ? null : "Funciona, però encara falta alguna cosa: el teu personatge ha de dir almenys 3 frases (nom, què t'agrada i lloc preferit) i moure's o girar.|Funciona, pero aún falta algo: tu personaje tiene que decir al menos 3 frases (nombre, lo que te gusta y sitio favorito) y moverse o girar.",
        sol: `@flama flag{ move:40 say:"Hola! Em dic Flama.|¡Hola! Me llamo Flama.",2 say:"M'agrada cantar i ballar.|Me gusta cantar y bailar.",2 bg:espai say:"El meu lloc preferit és l'espai!|¡Mi sitio favorito es el espacio!",2 turn:-90 say:"Gràcies per mirar!|¡Gracias por mirar!",2 }` },
      { k: 'story', ph: 'crea', who: 'numi', mood: 'happy',
        t: "Ensenya la teva presentació a un company/a (o a algú de casa). Pregunta-li: <b>què t'ha agradat més?</b> I <b>hi ha alguna frase que no s'hagi pogut llegir bé?</b> Si cal, torna enrere i millora-la: així treballen els creadors de debò.|Enseña tu presentación a un compañero/a (o a alguien de casa). Pregúntale: <b>¿qué te ha gustado más?</b> Y <b>¿hay alguna frase que no se haya podido leer bien?</b> Si hace falta, vuelve atrás y mejórala: así trabajan los creadores de verdad." },
      { k: 'quiz', ph: 'tanca', q: 'Quins són els passos d\'un projecte, en ordre?|¿Cuáles son los pasos de un proyecto, en orden?',
        opts: ['Pla → programar → provar → millorar|Plan → programar → probar → mejorar', 'Programar → acabar → esborrar|Programar → terminar → borrar', 'Provar → pla → acabar|Probar → plan → terminar'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "Amb quin bloc un personatge pot anar a l'esquerra <b>sense girar-se</b>?|¿Con qué bloque un personaje puede ir a la izquierda <b>sin girarse</b>?",
        opts: ['mou-te amb un número negatiu|muévete con un número negativo', 'canvia el fons|cambia el fondo', 'pensa|piensa'], a: 0, ex: 'Un número negatiu el fa anar enrere, mirant encara cap a la dreta.|Un número negativo lo hace ir hacia atrás, mirando todavía hacia la derecha.' },
      { k: 'feel', ph: 'tanca' }
    ] }
] };
})();
