/* Tech Creadors · unitat 7 «Atzar i dificultat»
   Nombres a l'atzar i llocs a l'atzar, clons (la fàbrica de meteorits), dificultat que creix (la velocitat és una
   variable que puja, amb un límit) i el projecte: el videojoc «Esquiva els meteorits» per a la Nit de les Estrelles de
   l'observatori de l'illa. Material propi de Numi. */
Object.assign(TBADGE, {
  g_atzar: { id: 'g_atzar', ico: '🎲', n: "Mestre/a de l'atzar|Maestro/a del azar", d: "Has fet que els teus personatges sorprenguin amb llocs i números a l'atzar.|Has hecho que tus personajes sorprendan con lugares y números al azar." },
  g_clons: { id: 'g_clons', ico: '👯', n: 'Fàbrica de clons|Fábrica de clones', d: "Has programat un sol personatge que en crea molts: els clons, que neixen, es mouen i s'esborren.|Has programado un solo personaje que crea muchos: los clones, que nacen, se mueven y se borran." },
  g_dificultat: { id: 'g_dificultat', ico: '📈', n: 'Dissenyador/a de nivells|Diseñador/a de niveles', d: "Has fet un repte que comença fàcil i es fa difícil a poc a poc, amb un límit.|Has hecho un reto que empieza fácil y se hace difícil poco a poco, con un límite." },
  g_esquiva: { id: 'g_esquiva', ico: '☄️', n: 'Pilot/a de meteorits|Piloto de meteoritos', d: "Has construït el teu videojoc «Esquiva els meteorits»: nau, clons a l'atzar, vides, punts i dificultat.|Has construido tu videojuego «Esquiva los meteoritos»: nave, clones al azar, vidas, puntos y dificultad." }
});
COURSE_UNITS[7] = (() => {
  /* ---------- personatges i mons que es fan servir en diversos passos ---------- */
  const MET = (x = 0, y = 170, more = {}) => ({ id: 'meteorit', art: 'meteorit', x, y, rot: 'none', ...more });
  const NAU = (x = 0, y = -140, more = {}) => ({ id: 'nau', art: 'nau', x, y, rot: 'none', ...more });
  const EST = (x = 0, y = 0, more = {}) => ({ id: 'estrella', art: 'estrella', x, y, ...more });
  // la caiguda d'un meteorit: surt per dalt en una x a l'atzar i baixa fins a baix de tot
  const FALL = n => `gotorand sety:170 until:y<-160{ move:${n} }`;
  // clics automàtics de la prova («Comprova»)
  const CLICKS = (id, t0, dt, n) => Array.from({ length: n }, (_, i) => ({ t: +(t0 + i * dt).toFixed(2), click: id }));
  const VN = { numero: 'número|número', tirada: 'tirada|tirada', caiguts: 'caiguts|caídos', punts: 'punts|puntos', vides: 'vides|vidas', velocitat: 'velocitat|velocidad' };
  // per als projectes: buscar blocs dins els guions (SG.progs: { id: { capçalera: [llista de blocs, …] } })
  const blocks = P => { const out = []; const w = l => (l || []).forEach(b => { out.push(b); if (Array.isArray(b.b)) w(b.b); if (b.e) w(b.e); }); Object.values(P || {}).forEach(H => Object.values(H || {}).forEach(scr => (scr || []).forEach(w))); return out; };
  const isRnd = v => v && typeof v === 'object' && v.r === 'rnd';
  const usesRnd = b => b.k === 'gotorand' || ['n', 'x', 'y', 's'].some(k => isRnd(b[k]));
  const inLoop = P => { let ok = false; const w = (l, loop) => (l || []).forEach(b => { if (loop && usesRnd(b)) ok = true; const L2 = loop || ['forever', 'rep', 'until'].includes(b.k); if (Array.isArray(b.b)) w(b.b, L2); if (b.e) w(b.e, L2); }); Object.values(P || {}).forEach(H => Object.entries(H || {}).forEach(([h, scr]) => (scr || []).forEach(l => w(l, h === 'clone' || h === 'click' || h.startsWith('key'))))); return ok; };
  const isVar = (v, n) => v && typeof v === 'object' && v.r === 'var' && v.v === n;
  const condVar = (c, n) => !!c && (isVar(c.a, n) || isVar(c.b, n) || [...(c.and || []), ...(c.or || [])].some(x => condVar(x, n)) || condVar(c.not, n));

  /* ---------- Sessió 1 · Nombres a l'atzar ---------- */
  const S1 = { id: 'g7-1', t: "Nombres a l'atzar|Números al azar", min: 45, badge: 'g_atzar',
    learn: ["L'atzar fa que un programa no faci sempre el mateix: com un dau, l'ordinador tria i no sabem què sortirà.|El azar hace que un programa no haga siempre lo mismo: como un dado, el ordenador elige y no sabemos qué saldrá.",
      "«Atzar 1-10» tria un número de l'1 al 10 cada vegada que el programa arriba al bloc; per això, si el vols nou a cada volta, va dins del bucle.|«Azar 1-10» elige un número del 1 al 10 cada vez que el programa llega al bloque; por eso, si lo quieres nuevo en cada vuelta, va dentro del bucle.",
      "«Repeteix fins que y < -160» fa baixar un meteorit fins a terra sense comptar voltes; amb «ves a un lloc a l'atzar» i «posa y a 170», cada vegada surt per un lloc diferent.|«Repite hasta que y < -160» hace bajar un meteorito hasta el suelo sin contar vueltas; con «ve a un sitio al azar» y «pon y a 170», cada vez sale por un sitio diferente."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "Recordes la mascota virtual? La <b>gana</b> val 4 i li dones la poma dues vegades: «suma a gana -3», «suma a gana -3». Quant val ara?|¿Recuerdas la mascota virtual? El <b>hambre</b> vale 4 y le das la manzana dos veces: «suma a hambre -3», «suma a hambre -3». ¿Cuánto vale ahora?",
        opts: ['-2|-2', '1|1', '10|10'], a: 0,
        ex: "4 - 3 = 1 i 1 - 3 = -2. Sumar un número negatiu resta, i la variable pot passar per sota de zero.|4 - 3 = 1 y 1 - 3 = -2. Sumar un número negativo resta, y la variable puede pasar por debajo de cero." },
      { k: 'quiz', ph: 'recorda', q: "L'escenari va de x = -240 (esquerra) a x = 240 (dreta). Un personatge és a <b>x = 200</b>. On és?|El escenario va de x = -240 (izquierda) a x = 240 (derecha). Un personaje está en <b>x = 200</b>. ¿Dónde está?",
        opts: ['A prop de la vora dreta|Cerca del borde derecho', 'Al mig|En el centro', 'A prop de la vora esquerra|Cerca del borde izquierdo'], a: 0,
        ex: "Com més gran és la x, més a la dreta. 200 és molt a prop de 240, la vora dreta.|Cuanto más grande es la x, más a la derecha. 200 está muy cerca de 240, el borde derecho." },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'illa', title: "La Nit de les Estrelles|La Noche de las Estrellas",
        t: "Dalt del turó de l'illa hi ha un <b>observatori</b> amb un telescopi enorme. D'aquí a uns dies s'hi farà la <b>Nit de les Estrelles</b>, i l'astrònoma ens ha fet un encàrrec: un videojoc perquè la gent esquivi meteorits amb una nau mentre espera el seu torn al telescopi.|En lo alto de la colina de la isla hay un <b>observatorio</b> con un telescopio enorme. Dentro de unos días se hará la <b>Noche de las Estrellas</b>, y la astrónoma nos ha hecho un encargo: un videojuego para que la gente esquive meteoritos con una nave mientras espera su turno en el telescopio." },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'illa', mood: 'think',
        t: "La Guida ja ha fet una prova i diu que, si els meteorits cauen sempre pel mateix lloc, a la segona partida tothom sap on posar la nau. Necessitem que l'ordinador ens <b>sorprengui</b>: necessitem l'<b>atzar</b>. I, perquè cada meteorit baixi just fins a terra, un bucle nou: <b>repeteix fins que</b>.|Guida ya ha hecho una prueba y dice que, si los meteoritos caen siempre por el mismo sitio, a la segunda partida todo el mundo sabe dónde poner la nave. Necesitamos que el ordenador nos <b>sorprenda</b>: necesitamos el <b>azar</b>. Y, para que cada meteorito baje justo hasta el suelo, un bucle nuevo: <b>repite hasta que</b>." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Atzar|Azar', t: "Què vol dir «a l'atzar»?|¿Qué quiere decir «al azar»?", anim: 'g7dau',
          x: "Quan tires un dau, no saps quin número sortirà. Una cosa passa <span class='hl'>a l'atzar</span> quan ningú no pot saber abans com acabarà: tirar una moneda, treure un paper d'un barret, la carta que et toca…|Cuando tiras un dado, no sabes qué número saldrá. Algo pasa <span class='hl'>al azar</span> cuando nadie puede saber antes cómo acabará: lanzar una moneda, sacar un papel de un sombrero, la carta que te toca…",
          tip: "Als videojocs, l'atzar fa que cada partida sigui una mica diferent i no te la puguis aprendre de memòria.|En los videojuegos, el azar hace que cada partida sea un poco diferente y no te la puedas aprender de memoria." },
        { k: 'Número|Número', t: "Un número a l'atzar|Un número al azar", anim: 'g7num',
          x: "On hi ha un número, pots triar el valor <b>atzar 1-10</b>. Cada vegada que el programa arriba al bloc, l'ordinador tria un número de l'1 al 10 (l'1 i el 10 també poden sortir). El pots guardar en una variable, dir-lo o fer-lo servir per moure't.|Donde hay un número, puedes elegir el valor <b>azar 1-10</b>. Cada vez que el programa llega al bloque, el ordenador elige un número del 1 al 10 (el 1 y el 10 también pueden salir). Lo puedes guardar en una variable, decirlo o usarlo para moverte.",
          tip: "Vols uns altres números? A la finestra del número, a «o un número a l'atzar», escriu-hi de quin a quin: de 5 a 20, de -100 a 100…|¿Quieres otros números? En la ventana del número, en «o un número al azar», escribe de cuál a cuál: de 5 a 20, de -100 a 100…" },
        { k: 'Lloc|Sitio', t: "Ves a un lloc a l'atzar|Ve a un sitio al azar",
          media: { k: 'stage', w: { bg: 'nit', sprites: [EST(0, 0)] }, prog: '@estrella flag{ forever{ gotorand wait:0.6 } }', time: 6 },
          x: "El bloc <b>ves a un lloc a l'atzar</b> tria una x i una y que no sabem i hi porta el personatge de cop. Dins d'un <b>per sempre</b>, l'estrella salta per tot el cel.|El bloque <b>ve a un sitio al azar</b> elige una x y una y que no sabemos y lleva allí al personaje de golpe. Dentro de un <b>por siempre</b>, la estrella salta por todo el cielo." },
        { k: 'Fins que|Hasta que', t: 'Repeteix fins que…|Repite hasta que…',
          media: { k: 'stage', w: { bg: 'espai', sprites: [MET(0, 170)] }, prog: '@meteorit flag{ point:180 sety:170 until:y<-160{ move:6 } say:"Ja sóc a terra!|¡Ya estoy en el suelo!",2 }', varNames: VN, time: 4.5 },
          x: "<b>Repeteix fins que</b> és un bucle que, abans de cada volta, mira una condició. Mentre no es compleix, repeteix; quan es compleix, para i el guió <b>continua</b> amb el bloc següent. Va bé quan no saps quantes voltes calen: «baixa fins que y < -160».|<b>Repite hasta que</b> es un bucle que, antes de cada vuelta, mira una condición. Mientras no se cumple, repite; cuando se cumple, para y el guion <b>continúa</b> con el bloque siguiente. Va bien cuando no sabes cuántas vueltas hacen falta: «baja hasta que y < -160».",
          bad: "Repeteix fins que toca la vora: el meteorit comença a dalt, ja la toca i no es mou.|Repite hasta que toca el borde: el meteorito empieza arriba, ya lo toca y no se mueve.", good: "Repeteix fins que y < -160: baixa i para just quan arriba a terra.|Repite hasta que y < -160: baja y para justo cuando llega al suelo." },
        { k: 'Truc|Truco', t: "Atzar només d'esquerra a dreta|Azar solo de izquierda a derecha",
          media: { k: 'stage', w: { bg: 'espai', sprites: [MET(0, 170)] }, prog: `@meteorit flag{ point:180 forever{ ${FALL(8)} } }`, time: 8 },
          x: "Vols que el meteorit surti sempre <b>per dalt</b>, però cada vegada per un lloc diferent? Primer <b>ves a un lloc a l'atzar</b> i després <b>posa y a 170</b>: la x es queda a l'atzar i la y, a dalt de tot. Després, apunta avall i <b>repeteix fins que y < -160</b>.|¿Quieres que el meteorito salga siempre <b>por arriba</b>, pero cada vez por un sitio diferente? Primero <b>ve a un sitio al azar</b> y después <b>pon y a 170</b>: la x se queda al azar y la y, arriba del todo. Después, apunta abajo y <b>repite hasta que y < -160</b>." },
        { k: 'Compte!|¡Cuidado!', t: "L'atzar es tria quan s'arriba al bloc|El azar se elige al llegar al bloque", anim: 'g7once',
          x: "Si tries el número <b>una sola vegada, abans</b> del bucle, després ja no canvia: és el mateix a cada volta. Si el vols nou cada vegada, el bloc amb l'atzar ha d'anar <b>dins</b> del bucle.|Si eliges el número <b>una sola vez, antes</b> del bucle, después ya no cambia: es el mismo en cada vuelta. Si lo quieres nuevo cada vez, el bloque con el azar tiene que ir <b>dentro</b> del bucle.",
          bad: "Poso «atzar» una vegada abans del «per sempre» i ja canviarà sol.|Pongo «azar» una vez antes del «por siempre» y ya cambiará solo.", good: "Poso el bloc amb «atzar» dins del bucle: a cada volta es tria un número nou.|Pongo el bloque con «azar» dentro del bucle: en cada vuelta se elige un número nuevo." }
      ] },
      { k: 'quiz', ph: 'mans', q: "Quina d'aquestes coses passa <b>a l'atzar</b>?|¿Cuál de estas cosas pasa <b>al azar</b>?",
        opts: ['El número que surt quan tires un dau|El número que sale cuando tiras un dado', "L'hora que surt el sol demà|La hora a la que sale el sol mañana", 'El resultat de 3 + 4|El resultado de 3 + 4'], a: 0,
        ex: "L'hora de sortida del sol i 3 + 4 es poden saber abans. El dau, no: és atzar.|La hora de salida del sol y 3 + 4 se pueden saber antes. El dado, no: es azar." },
      { k: 'unplug', ph: 'mans', ico: '🎲', title: 'El dau dels moviments|El dado de los movimientos',
        t: "Necessites un dau i algú de casa. Fareu un programa amb atzar… amb el cos!|Necesitas un dado y a alguien de casa. Haréis un programa con azar… ¡con el cuerpo!",
        steps: ["Escriviu en un paper: 1 = un salt, 2 = un gir, 3 = picar de mans, 4 = ajupir-se, 5 = un pas enrere, 6 = el que vulgueu.|Escribid en un papel: 1 = un salto, 2 = un giro, 3 = dar una palmada, 4 = agacharse, 5 = un paso atrás, 6 = lo que queráis.",
          "Abans de tirar, digueu quin número creieu que sortirà.|Antes de tirar, decid qué número creéis que saldrá.",
          "Tireu el dau i feu el moviment que toca. Repetiu-ho 10 vegades i apunteu quantes vegades l'heu encertat.|Tirad el dado y haced el movimiento que toca. Repetidlo 10 veces y apuntad cuántas veces lo habéis acertado.",
          "Heu encertat gaires vegades? Amb l'atzar, és molt difícil endevinar què passarà.|¿Habéis acertado muchas veces? Con el azar, es muy difícil adivinar qué pasará."],
        tip: "Si no teniu dau, escriviu els números de l'1 al 6 en papers, doblegueu-los i traieu-ne un d'una bossa (i torneu-lo a posar).|Si no tenéis dado, escribid los números del 1 al 6 en papeles, dobladlos y sacad uno de una bolsa (y volvedlo a meter)." },
      { k: 'sfree', ph: 'prova', q: "Toca <b>Comença</b> i mira l'estrella una estona. Saps on sortirà la propera vegada? Torna mai al mateix lloc?|Toca <b>Empieza</b> y mira la estrella un rato. ¿Sabes dónde saldrá la próxima vez? ¿Vuelve alguna vez al mismo sitio?",
        w: { bg: 'nit', sprites: [EST(0, 0)], time: 8 }, prog: '@estrella flag{ forever{ gotorand wait:0.7 } }' },
      { k: 'sspot', ph: 'investiga', q: "Dues naus fan una cursa. La de dalt va sempre igual de ràpid; la de baix canvia de velocitat a cada pas. <b>Toca el bloc</b> que fa que la nau de baix vagi a l'atzar.|Dos naves hacen una carrera. La de arriba va siempre igual de rápido; la de abajo cambia de velocidad a cada paso. <b>Toca el bloque</b> que hace que la nave de abajo vaya al azar.",
        w: { bg: 'espai', sprites: [{ id: 'nau1', art: 'nau', x: -200, y: 70, rot: 'none', name: 'Nau de dalt|Nave de arriba' }, { id: 'nau2', art: 'nau', x: -200, y: -70, rot: 'none', costume: 1, name: 'Nau de baix|Nave de abajo' }], time: 6 },
        prog: '@nau1 flag{ forever{ move:4 bounce } } @nau2 flag{ forever{ move:rnd:1:10! bounce } }',
        ex: "«Mou-te atzar 1-10 passos» tria un número nou a cada pas: de vegades avança poc i de vegades molt.|«Muévete azar 1-10 pasos» elige un número nuevo a cada paso: a veces avanza poco y a veces mucho." },
      { k: 'quiz', ph: 'investiga', q: "En Numi posa <b>número a atzar 1-10</b> i el diu. Quin d'aquests números <b>no</b> pot dir mai?|Numi pone <b>número a azar 1-10</b> y lo dice. ¿Cuál de estos números <b>no</b> puede decir nunca?",
        opts: ['12|12', '1|1', '10|10'], a: 0,
        ex: "«Atzar 1-10» només tria entre l'1 i el 10; l'1 i el 10 també hi són.|«Azar 1-10» solo elige entre el 1 y el 10; el 1 y el 10 también están." },
      { k: 'quiz', ph: 'investiga', q: "Aquest guió fa: «posa y a 170», «repeteix fins que <b>y < 0</b>: mou-te 10 passos» i, després, «digues Hola!». On diu «Hola!» el meteorit?|Este guion hace: «pon y a 170», «repite hasta que <b>y < 0</b>: muévete 10 pasos» y, después, «di ¡Hola!». ¿Dónde dice «¡Hola!» el meteorito?",
        art: () => `<div class="sdcode">${sgDemoChips(SQ('@meteorit flag{ point:180 sety:170 until:y<0{ move:10 } say:"Hola!|¡Hola!" }'), { w: { bg: 'espai', sprites: [MET(0, 170)] }, varNames: VN })}</div>`,
        opts: ["Una mica per sota del mig de l'escenari|Un poco por debajo del centro del escenario", 'A dalt de tot, abans de moure\'s|Arriba del todo, antes de moverse', 'No ho diu mai: el bucle no s\'acaba|No lo dice nunca: el bucle no se acaba'], a: 0,
        ex: "Baixa de 10 en 10 (170, 160… 10, 0, -10). Quan y < 0 es compleix, el bucle para i el guió continua: diu «Hola!» a y = -10.|Baja de 10 en 10 (170, 160… 10, 0, -10). Cuando y < 0 se cumple, el bucle para y el guion continúa: dice «¡Hola!» en y = -10." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de meteorit! Posa't dret/a, tanca els ulls i compta fins a un número qualsevol de l'1 al 5. Fes tants salts com el número que has triat… i després tants passos a un costat a l'atzar: tu tries cap on!|¡Haz de meteorito! Ponte de pie, cierra los ojos y cuenta hasta un número cualquiera del 1 al 5. Haz tantos saltos como el número que has elegido… y después tantos pasos hacia un lado al azar: ¡tú eliges hacia dónde!" },
      { k: 'stage', ph: 'repte', q: "L'estrella no s'està quieta! Fes que <b>salti a un lloc a l'atzar</b> una vegada i una altra, per sempre, amb una petita espera. Ha de passar per les quatre parts del cel.|¡La estrella no se está quieta! Haz que <b>salte a un sitio al azar</b> una y otra vez, por siempre, con una pequeña espera. Tiene que pasar por las cuatro partes del cielo.",
        w: { bg: 'nit', sprites: [EST(0, 0)], time: 12,
          goal: [{ k: 'reach', s: 'estrella', r: [-240, 10, -10, 180] }, { k: 'reach', s: 'estrella', r: [10, 10, 240, 180] }, { k: 'reach', s: 'estrella', r: [-240, -180, -10, -10] }, { k: 'reach', s: 'estrella', r: [10, -180, 240, -10] }] },
        hats: ['flag'], pal: ['gotorand', 'goto', 'move', 'wait', 'rep', 'forever'],
        sol: '@estrella flag{ forever{ gotorand wait:0.3 } }',
        hint: "Dins d'un «per sempre»: «ves a un lloc a l'atzar» i «espera 0.3 segons».|Dentro de un «por siempre»: «ve a un sitio al azar» y «espera 0.3 segundos»." },
      { k: 'stage', ph: 'repte', q: "Quan toquis en Numi, ha de pensar <b>un número a l'atzar</b> i dir-lo. Posa la variable <b>número</b> a <b>atzar 1-10</b> i després digues la variable.|Cuando toques a Numi, tiene que pensar <b>un número al azar</b> y decirlo. Pon la variable <b>número</b> a <b>azar 1-10</b> y después di la variable.",
        w: { bg: 'nit', sprites: [{ id: 'numi', art: 'numi', x: 0, y: -40, size: 120 }], vars: ['numero'], input: CLICKS('numi', .5, 1.5, 3), time: 5,
          goal: [{ k: 'clicked', s: 'numi' }, { k: 'said', s: 'numi' }, { k: 'var', v: 'numero', min: 1, max: 10 }] },
        hats: ['click'], pal: ['setv', 'chv', 'say', 'wait'], ops: ['rnd'], varNames: VN,
        sol: '@numi click{ setv:numero,rnd:1:10 say:$numero,1 }',
        hint: "Primer «posa número a…» i toca el número per triar «atzar 1-10». Després, «digues» i tria la variable número.|Primero «pon número a…» y toca el número para elegir «azar 1-10». Después, «di» y elige la variable número." },
      { k: 'stage', ph: 'repte', q: "<b>Cara o creu!</b> Cada vegada que toquis la moneda, posa <b>tirada</b> a <b>atzar 1-10</b>. Si tirada > 5, digues «Cara!»; si no, digues «Creu!». Amb molts tocs, han de sortir totes dues.|<b>¡Cara o cruz!</b> Cada vez que toques la moneda, pon <b>tirada</b> a <b>azar 1-10</b>. Si tirada > 5, di «¡Cara!»; si no, di «¡Cruz!». Con muchos toques, tienen que salir las dos.",
        w: { bg: 'nit', sprites: [{ id: 'moneda', art: 'moneda', x: 0, y: -20, size: 170 }], vars: ['tirada'], input: CLICKS('moneda', .5, .35, 16), time: 6.5,
          goal: [{ k: 'said', s: 'moneda', t: 'cara' }, { k: 'said', s: 'moneda', t: 'creu' }] },
        hats: ['click'], pal: ['setv', 'if', 'else', 'cond+', 'say', 'next', 'sound'], ops: ['rnd'], varNames: VN, texts: ['Cara!|¡Cara!', 'Creu!|¡Cruz!'],
        sol: '@moneda click{ setv:tirada,rnd:1:10 if:$tirada>5{ say:"Cara!|¡Cara!",0.3 } else{ say:"Creu!|¡Cruz!",0.3 } }',
        hint: "Al bloc «si», tria «comparar números»: tirada > 5. Toca el bloc «si» per afegir-hi «si no».|En el bloque «si», elige «comparar números»: tirada > 5. Toca el bloque «si» para añadirle «si no»." },
      { k: 'stage', ph: 'repte', q: "Aquest meteorit surt sempre pel mig i només baixa un tros. Fes que baixi <b>fins que y < -160</b> (amb «repeteix fins que») i que surti per dalt <b>en un lloc a l'atzar</b>: ha d'arribar a terra per l'esquerra i per la dreta.|Este meteorito sale siempre por el centro y solo baja un trozo. Haz que baje <b>hasta que y < -160</b> (con «repite hasta que») y que salga por arriba <b>en un sitio al azar</b>: tiene que llegar al suelo por la izquierda y por la derecha.",
        w: { bg: 'espai', sprites: [MET(0, 170)], time: 14,
          goal: [{ k: 'reach', s: 'meteorit', r: [-240, -180, -5, -100] }, { k: 'reach', s: 'meteorit', r: [5, -180, 240, -100] }] },
        hats: ['flag'], pal: ['gotorand', 'goto', 'setx', 'sety', 'point', 'move', 'rep', 'until', 'forever', 'cond+'], ops: ['y'],
        prog: '@meteorit flag{ point:180 forever{ sety:170 rep:4{ move:10 } } }',
        sol: `@meteorit flag{ point:180 forever{ ${FALL(10)} } }`,
        check: P => blocks(P).some(b => b.k === 'until' && /"r":"y"/.test(JSON.stringify(b.c || {}))) ? null : "Fes servir «repeteix fins que» amb la condició «comparar números»: y < -160.|Usa «repite hasta que» con la condición «comparar números»: y < -160.",
        hint: "Canvia el «repeteix 4 vegades» per un «repeteix fins que» i, a la condició, tria «comparar números»: y < -160. Després, abans de «posa y a 170», afegeix «ves a un lloc a l'atzar» (si el poses després, la y també seria a l'atzar!).|Cambia el «repite 4 veces» por un «repite hasta que» y, en la condición, elige «comparar números»: y < -160. Después, antes de «pon y a 170», añade «ve a un sitio al azar» (si lo pones después, ¡la y también sería al azar!)." },
      { k: 'screate', ph: 'crea', name: "La meva nit d'estrelles|Mi noche de estrellas",
        q: "Crea la teva nit al cel de l'observatori! Almenys un personatge ha de fer servir <b>l'atzar dins d'un bucle</b> (un lloc o un número), i alguna cosa s'ha de moure tota l'estona. Pots canviar el fons i fer que diguin coses.|¡Crea tu noche en el cielo del observatorio! Al menos un personaje tiene que usar <b>el azar dentro de un bucle</b> (un sitio o un número), y algo tiene que moverse todo el rato. Puedes cambiar el fondo y hacer que digan cosas.",
        crit: ["Un personatge fa servir l'atzar dins d'un bucle|Un personaje usa el azar dentro de un bucle", "Alguna cosa es mou tota l'estona|Algo se mueve todo el rato", "L'has provat i canvia mentre el mires|Lo has probado y cambia mientras lo miras"],
        w: { bg: 'nit', bgs: ['nit', 'espai', 'cel'], sprites: [EST(0, 100), NAU(-150, -100), MET(160, 140)], vars: ['numero'], time: 4, goal: [{ k: 'running', t: 3.5 }] },
        edit: ['estrella', 'nau', 'meteorit'], hats: ['flag', 'click'],
        pal: ['move', 'turn', 'goto', 'gotorand', 'glide', 'setx', 'sety', 'chx', 'chy', 'point', 'bounce', 'say', 'think', 'next', 'size', 'chsize', 'show', 'hide', 'bg', 'nextbg', 'sound', 'wait', 'rep', 'forever', 'until', 'if', 'else', 'cond+', 'setv', 'chv'],
        ops: ['rnd', 'x', 'y'], varNames: VN, texts: ['Quina nit!|¡Qué noche!', 'Mira, una estrella!|¡Mira, una estrella!'],
        sol: `@estrella flag{ forever{ gotorand wait:0.5 } } @meteorit flag{ point:180 forever{ ${FALL(6)} } } @nau flag{ forever{ move:4 bounce } }`,
        check: P => inLoop(P) ? null : "Encara cap personatge no fa servir l'atzar dins d'un bucle. Prova «ves a un lloc a l'atzar» dins d'un «per sempre».|Todavía ningún personaje usa el azar dentro de un bucle. Prueba «ve a un sitio al azar» dentro de un «por siempre»." },
      { k: 'quiz', ph: 'tanca', q: "Vols que una poma caigui <b>fins a terra</b> i, just llavors, digui «Plof!». Quin bucle fas servir per a la caiguda?|Quieres que una manzana caiga <b>hasta el suelo</b> y, justo entonces, diga «¡Plof!». ¿Qué bucle usas para la caída?",
        opts: ["«repeteix fins que y < -160» i, després, «digues Plof!»|«repite hasta que y < -160» y, después, «di ¡Plof!»", "«per sempre» i, després, «digues Plof!»|«por siempre» y, después, «di ¡Plof!»", "«repeteix 10 vegades», que sempre arriba a terra|«repite 10 veces», que siempre llega al suelo"], a: 0,
        ex: "Del «per sempre» no se'n surt mai i el «digues» no arribaria; amb «repeteix 10» hauries de comptar les voltes. «Fins que» para just quan arriba.|Del «por siempre» no se sale nunca y el «di» no llegaría; con «repite 10» tendrías que contar las vueltas. «Hasta que» para justo cuando llega." },
      { k: 'quiz', ph: 'tanca', q: "Has posat <b>número a atzar 1-10</b> abans del «per sempre», i dins el bucle només dius el número. Què passarà?|Has puesto <b>número a azar 1-10</b> antes del «por siempre», y dentro del bucle solo dices el número. ¿Qué pasará?",
        opts: ['Dirà sempre el mateix número|Dirá siempre el mismo número', 'Dirà un número nou a cada volta|Dirá un número nuevo en cada vuelta', 'No dirà res|No dirá nada'], a: 0,
        ex: "El número es tria quan el programa arriba al bloc. Si és fora del bucle, només s'hi arriba una vegada.|El número se elige cuando el programa llega al bloque. Si está fuera del bucle, solo se llega una vez." },
      { k: 'feel', ph: 'tanca' }
    ] };

  /* ---------- Sessió 2 · Clons ---------- */
  const FACT = (w = 0.5) => `hide point:180 forever{ clone wait:${w} }`;
  const S2 = { id: 'g7-2', t: 'Clons|Clones', min: 45, badge: 'g_clons',
    learn: ["Un clon és una còpia d'un personatge que el mateix personatge crea mentre el programa funciona.|Un clon es una copia de un personaje que el mismo personaje crea mientras el programa funciona.",
      "Cada clon fa pel seu compte el guió «quan començo com a clon»: neix on és l'original i s'ha de moure perquè no quedin tots amuntegats.|Cada clon hace por su cuenta el guion «al empezar como clon»: nace donde está el original y se tiene que mover para que no queden todos amontonados.",
      "Quan un clon ja ha fet la seva feina, «esborra aquest clon» el treu de l'escenari perquè no s'ompli.|Cuando un clon ya ha hecho su trabajo, «borra este clon» lo quita del escenario para que no se llene."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "Vols que el meteorit surti per dalt, cada vegada en un lloc diferent. Quin ordre de blocs va bé?|Quieres que el meteorito salga por arriba, cada vez en un sitio diferente. ¿Qué orden de bloques va bien?",
        opts: ["ves a un lloc a l'atzar → posa y a 170|ve a un sitio al azar → pon y a 170", "posa y a 170 → ves a un lloc a l'atzar|pon y a 170 → ve a un sitio al azar", 'ves a x: 0 y: 170|ve a x: 0 y: 170'], a: 0,
        ex: "Si «ves a un lloc a l'atzar» va després, també canvia la y i el meteorit pot sortir pel mig de l'escenari.|Si «ve a un sitio al azar» va después, también cambia la y y el meteorito puede salir por el centro del escenario." },
      { k: 'quiz', ph: 'recorda', q: "Pot sortir el número <b>0</b> amb «atzar 1-10»?|¿Puede salir el número <b>0</b> con «azar 1-10»?",
        opts: ["No: només surten números de l'1 al 10|No: solo salen números del 1 al 10", 'Sí, de vegades|Sí, a veces', 'Sí, sempre al principi|Sí, siempre al principio'], a: 0 },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'lab',
        t: "L'astrònoma ha vist el nostre meteorit i somriu: «Molt bé! Però en una pluja de meteorits n'hi ha <b>molts</b>, no un de sol». Haurem de dibuixar i programar vint meteorits iguals, un per un?|La astrónoma ha visto nuestro meteorito y sonríe: «¡Muy bien! Pero en una lluvia de meteoritos hay <b>muchos</b>, no uno solo». ¿Tendremos que dibujar y programar veinte meteoritos iguales, uno por uno?" },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'lab', mood: 'happy',
        t: "En Vuit ha tingut una idea als estudis: i si el meteorit fa <b>còpies</b> d'ell mateix mentre el programa funciona? Es diuen <b>clons</b>. Programes un sol personatge… i en surten tants com calgui, cadascun pel seu compte.|Vuit ha tenido una idea en los estudios: ¿y si el meteorito hace <b>copias</b> de sí mismo mientras el programa funciona? Se llaman <b>clones</b>. Programas un solo personaje… y salen tantos como hagan falta, cada uno por su cuenta." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Clon|Clon', t: 'Què és un clon?|¿Qué es un clon?', anim: 'g7clon',
          x: "Un <span class='hl'>clon</span> és una còpia d'un personatge: el mateix dibuix, al mateix lloc, amb la mateixa mida i mirant cap al mateix costat. El bloc <b>crea un clon de mi</b> en fa un de nou cada vegada que s'executa. És com un segell: el mateix dibuix, tantes vegades com vulguis.|Un <span class='hl'>clon</span> es una copia de un personaje: el mismo dibujo, en el mismo sitio, con el mismo tamaño y mirando hacia el mismo lado. El bloque <b>crea un clon de mí</b> hace uno nuevo cada vez que se ejecuta. Es como un sello: el mismo dibujo, tantas veces como quieras." },
        { k: 'Guió del clon|Guion del clon', t: 'Quan començo com a clon|Al empezar como clon',
          media: { k: 'stage', w: { bg: 'nit', sprites: [EST(0, 0)] }, prog: '@estrella flag{ rep:6{ clone wait:0.4 } } clone{ gotorand }', time: 5 },
          x: "Cada clon que neix fa el guió <b>quan començo com a clon</b>, pel seu compte. Aquí, cada clon va a un lloc a l'atzar: per això cadascun acaba en un lloc diferent del cel.|Cada clon que nace hace el guion <b>al empezar como clon</b>, por su cuenta. Aquí, cada clon va a un sitio al azar: por eso cada uno acaba en un sitio diferente del cielo." },
        { k: 'La fàbrica|La fábrica', t: "L'original s'amaga i fa clons|El original se esconde y hace clones",
          media: { k: 'stage', w: { bg: 'espai', sprites: [MET(0, 170)] }, prog: `@meteorit flag{ ${FACT(0.5)} } clone{ gotorand sety:170 show until:y<-160{ move:6 } delclone }`, time: 8 },
          x: "Un truc molt útil: el meteorit original s'<b>amaga</b> i només fa clons, com una fàbrica. Però compte: els clons neixen com l'original… també amagats! Per això el guió del clon té <b>mostra't</b> quan ja és al seu lloc.|Un truco muy útil: el meteorito original se <b>esconde</b> y solo hace clones, como una fábrica. Pero cuidado: los clones nacen como el original… ¡también escondidos! Por eso el guion del clon tiene <b>muéstrate</b> cuando ya está en su sitio." },
        { k: 'Esborrar|Borrar', t: 'Esborra aquest clon|Borra este clon', anim: 'g7vida',
          x: "Quan un clon arriba a baix de tot, ja no serveix: <b>esborra aquest clon</b> el treu de l'escenari. Si no els esborres, s'amunteguen, i l'escenari només n'aguanta 40 alhora: llavors ja no en surten de nous.|Cuando un clon llega abajo del todo, ya no sirve: <b>borra este clon</b> lo quita del escenario. Si no los borras, se amontonan, y el escenario solo aguanta 40 a la vez: entonces ya no salen nuevos." },
        { k: 'Compte!|¡Cuidado!', t: "Un clon neix on és l'original|Un clon nace donde está el original",
          media: { k: 'stage', w: { bg: 'nit', sprites: [EST(0, 0)] }, prog: '@estrella flag{ rep:5{ clone } think:"Som 6, però sembla que només hi sigui jo!|¡Somos 6, pero parece que solo esté yo!",3 }', time: 4 },
          x: "Si els clons no es mouen, queden tots a sota de l'original i sembla que no n'hi hagi cap. Al guió del clon, mou-los: a un lloc a l'atzar, cap avall, cap amunt…|Si los clones no se mueven, quedan todos debajo del original y parece que no haya ninguno. En el guion del clon, muévelos: a un sitio al azar, hacia abajo, hacia arriba…",
          bad: "He fet 5 clons i només en veig un: el bloc no funciona.|He hecho 5 clones y solo veo uno: el bloque no funciona.", good: "Els 5 clons són a sota de l'original: els moc al guió «quan començo com a clon».|Los 5 clones están debajo del original: los muevo en el guion «al empezar como clon»." }
      ] },
      { k: 'seq', ph: 'mans', q: "Ordena el <b>guió del clon</b> de la pluja de meteorits, de dalt a baix.|Ordena el <b>guion del clon</b> de la lluvia de meteoritos, de arriba abajo.",
        items: ['Quan començo com a clon|Al empezar como clon', "Ves a un lloc a l'atzar|Ve a un sitio al azar", 'Posa y a 170|Pon y a 170', "Mostra't|Muéstrate", 'Repeteix fins que y < -160: mou-te 6 passos|Repite hasta que y < -160: muévete 6 pasos', 'Esborra aquest clon|Borra este clon'],
        ex: "Primer es posa al seu lloc, després es mostra, baixa… i quan arriba a baix, s'esborra.|Primero se pone en su sitio, después se muestra, baja… y cuando llega abajo, se borra." },
      { k: 'unplug', ph: 'mans', ico: '🖐️', title: 'Clons de paper|Clones de papel',
        t: "Necessites un full, un llapis i una tapa o una moneda per resseguir. I algú de casa!|Necesitas una hoja, un lápiz y una tapa o una moneda para repasar. ¡Y a alguien de casa!",
        steps: ["Ressegueix la tapa 6 vegades al full: tens un original i 5 clons, tots iguals.|Repasa la tapa 6 veces en la hoja: tienes un original y 5 clones, todos iguales.",
          "Ara, l'altra persona escriu una regla per als clons, com un guió: «quan neixes, posa't ulls i una boca contenta».|Ahora, la otra persona escribe una regla para los clones, como un guion: «cuando naces, ponte ojos y una boca contenta».",
          "Dibuixa la regla a cada clon. Després tireu un dau per a cada clon: si surt parell, li poses un barret.|Dibuja la regla en cada clon. Después tirad un dado para cada clon: si sale par, le pones un sombrero.",
          "Mireu-los: tots han seguit el mateix guió, però amb l'atzar no són exactament iguals.|Miradlos: todos han seguido el mismo guion, pero con el azar no son exactamente iguales."] },
      { k: 'sfree', ph: 'prova', q: "Mira la pluja de meteorits i compta: quants personatges hi ha programats? Mira a sota: només n'hi ha <b>un</b>, el meteorit. Tots els altres són clons!|Mira la lluvia de meteoritos y cuenta: ¿cuántos personajes hay programados? Mira abajo: solo hay <b>uno</b>, el meteorito. ¡Todos los demás son clones!",
        w: { bg: 'espai', sprites: [MET(0, 170)], time: 10 }, prog: `@meteorit flag{ ${FACT(0.4)} } clone{ gotorand sety:170 show until:y<-160{ move:6 } delclone }` },
      { k: 'sspot', ph: 'investiga', q: "Aquesta estrella fa aparèixer i desaparèixer estrelles per tot el cel. <b>Toca el bloc que fa néixer les estrelles noves.</b>|Esta estrella hace aparecer y desaparecer estrellas por todo el cielo. <b>Toca el bloque que hace nacer las estrellas nuevas.</b>",
        w: { bg: 'nit', sprites: [EST(0, 0)], time: 6 }, prog: '@estrella flag{ hide forever{ clone! wait:0.3 } } clone{ gotorand show wait:1 delclone }',
        ex: "«Crea un clon de mi» fa una còpia nova. Com que és dins d'un «per sempre», en fa una cada 0,3 segons.|«Crea un clon de mí» hace una copia nueva. Como está dentro de un «por siempre», hace una cada 0,3 segundos." },
      { k: 'quiz', ph: 'investiga', q: "L'estrella original s'amaga i fa clons. El guió del clon diu «ves a un lloc a l'atzar», però <b>no té «mostra't»</b>. Què es veurà?|La estrella original se esconde y hace clones. El guion del clon dice «ve a un sitio al azar», pero <b>no tiene «muéstrate»</b>. ¿Qué se verá?",
        opts: ['Res: els clons neixen amagats, com l\'original|Nada: los clones nacen escondidos, como el original', "Tots els clons, cadascun al seu lloc|Todos los clones, cada uno en su sitio", "Només l'original|Solo el original"], a: 0,
        ex: "Un clon copia com és l'original en aquell moment, també si està amagat.|Un clon copia cómo es el original en ese momento, también si está escondido." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de clon! Inventa una postura (un braç amunt, una cama doblegada…) i repeteix-la tres vegades exactament igual: són els teus clons. Ara, cada clon fa una cosa diferent: el primer salta, el segon gira i el tercer s'ajup.|¡Haz de clon! Inventa una postura (un brazo arriba, una pierna doblada…) y repítela tres veces exactamente igual: son tus clones. Ahora, cada clon hace una cosa diferente: el primero salta, el segundo gira y el tercero se agacha." },
      { k: 'stage', ph: 'repte', q: "Aquesta estrella fa només <b>un</b> clon. Fes que en faci <b>almenys 8</b>, i que cadascun vagi a un lloc a l'atzar per omplir el cel.|Esta estrella hace solo <b>un</b> clon. Haz que haga <b>al menos 8</b>, y que cada uno vaya a un sitio al azar para llenar el cielo.",
        w: { bg: 'nit', sprites: [EST(0, 0)], time: 3, goal: [{ k: 'clones', min: 8 }] },
        hats: ['flag', 'clone'], pal: ['clone', 'rep', 'forever', 'wait', 'gotorand', 'show', 'hide'],
        prog: '@estrella flag{ clone } clone{ gotorand }', sol: '@estrella flag{ rep:8{ clone } } clone{ gotorand }',
        hint: "Posa «crea un clon de mi» dins d'un «repeteix 8 vegades».|Pon «crea un clon de mí» dentro de un «repite 8 veces»." },
      { k: 'stage', ph: 'repte', q: "La fàbrica de meteorits ja fa clons, però els clons no fan res! Escriu el guió <b>quan començo com a clon</b>: ves a un lloc a l'atzar, posa y a 170, mostra't, baixa fins que y < -160 i, a baix, suma 1 a <b>caiguts</b>. N'han de caure almenys 8.|La fábrica de meteoritos ya hace clones, ¡pero los clones no hacen nada! Escribe el guion <b>al empezar como clon</b>: ve a un sitio al azar, pon y a 170, muéstrate, baja hasta que y < -160 y, abajo, suma 1 a <b>caídos</b>. Tienen que caer al menos 8.",
        w: { bg: 'espai', sprites: [MET(0, 170)], vars: ['caiguts'], time: 8, goal: [{ k: 'var', v: 'caiguts', min: 8 }] },
        hats: ['flag', 'clone'], pal: ['clone', 'hide', 'show', 'gotorand', 'sety', 'point', 'move', 'until', 'forever', 'wait', 'cond+', 'chv'], ops: ['y'], varNames: VN,
        prog: `@meteorit flag{ ${FACT(0.5)} }`,
        sol: `@meteorit flag{ ${FACT(0.5)} } clone{ ${FALL(8).replace('until', 'show until')} chv:caiguts,1 }`,
        hint: "Al guió del clon: «ves a un lloc a l'atzar», «posa y a 170», «mostra't», «repeteix fins que y < -160» amb «mou-te 8 passos» a dins i, després del bucle, «suma a caiguts 1».|En el guion del clon: «ve a un sitio al azar», «pon y a 170», «muéstrate», «repite hasta que y < -160» con «muévete 8 pasos» dentro y, después del bucle, «suma a caídos 1»." },
      { k: 'stage', ph: 'repte', q: "Ui! Aquesta pluja és molt forta… però als pocs segons <b>s'atura de cop</b>. Els clons s'amunteguen a baix i l'escenari s'omple. Arregla-ho perquè en caiguin <b>més de 55</b>.|¡Uy! Esta lluvia es muy fuerte… pero a los pocos segundos <b>se para de golpe</b>. Los clones se amontonan abajo y el escenario se llena. Arréglalo para que caigan <b>más de 55</b>.",
        w: { bg: 'espai', sprites: [MET(0, 170)], time: 8, goal: [{ k: 'clones', min: 56 }] },
        hats: ['flag', 'clone'], pal: ['clone', 'delclone', 'hide', 'show', 'gotorand', 'sety', 'point', 'move', 'until', 'forever', 'wait', 'cond+'], ops: ['y'],
        prog: `@meteorit flag{ ${FACT(0.1)} } clone{ ${FALL(10).replace('until', 'show until')} }`,
        sol: `@meteorit flag{ ${FACT(0.1)} } clone{ ${FALL(10).replace('until', 'show until')} delclone }`,
        hint: "Quan el clon arriba a baix, ja no serveix. Quin bloc el treu de l'escenari?|Cuando el clon llega abajo, ya no sirve. ¿Qué bloque lo quita del escenario?" },
      { k: 'stage', ph: 'repte', q: "Ara, estrelles per caçar! L'estrella s'amaga i fa 6 clons, cadascun en un lloc a l'atzar. Afegeix el guió <b>quan toco aquest personatge</b>: suma 1 a <b>punts</b>, fes un so i esborra aquest clon. Has d'aconseguir 4 punts.|¡Ahora, estrellas para cazar! La estrella se esconde y hace 6 clones, cada uno en un sitio al azar. Añade el guion <b>al tocar este personaje</b>: suma 1 a <b>puntos</b>, haz un sonido y borra este clon. Tienes que conseguir 4 puntos.",
        w: { bg: 'nit', sprites: [EST(0, 0)], vars: ['punts'], input: CLICKS('estrella', 1, .5, 4), time: 3.5, goal: [{ k: 'var', v: 'punts', min: 4 }] },
        hats: ['flag', 'clone', 'click'], pal: ['clone', 'delclone', 'rep', 'hide', 'show', 'gotorand', 'sound', 'chv', 'setv', 'wait'], varNames: VN,
        prog: '@estrella flag{ hide rep:6{ clone } } clone{ gotorand show }',
        sol: '@estrella flag{ hide rep:6{ clone } } clone{ gotorand show } click{ chv:punts,1 sound:pop delclone }',
        hint: "Quan toques un clon, el clon fa el guió «quan toco aquest personatge». Posa-hi «suma a punts 1», «fes el so» i «esborra aquest clon».|Cuando tocas un clon, el clon hace el guion «al tocar este personaje». Pon «suma a puntos 1», «haz el sonido» y «borra este clon»." },
      { k: 'screate', ph: 'crea', name: 'La meva pluja de clons|Mi lluvia de clones',
        q: "Inventa la teva pluja: estrelles, bombolles, meteorits… Un personatge ha de fer <b>almenys 5 clons</b>, cada clon s'ha de moure o canviar al seu guió i, perquè no siguin tots iguals, fes servir l'<b>atzar</b>.|Inventa tu lluvia: estrellas, burbujas, meteoritos… Un personaje tiene que hacer <b>al menos 5 clones</b>, cada clon se tiene que mover o cambiar en su guion y, para que no sean todos iguales, usa el <b>azar</b>.",
        crit: ['Un personatge fa almenys 5 clons|Un personaje hace al menos 5 clones', "Al guió «quan començo com a clon», cada clon fa alguna cosa|En el guion «al empezar como clon», cada clon hace algo", "Fas servir l'atzar perquè no siguin tots iguals|Usas el azar para que no sean todos iguales"],
        w: { bg: 'espai', bgs: ['espai', 'nit', 'cel', 'aquari'], sprites: [EST(-120, 120), { id: 'bombolla', art: 'bombolla', x: 0, y: -150 }, MET(140, 140)], vars: ['punts'], time: 5, goal: [{ k: 'clones', min: 5 }] },
        edit: ['estrella', 'bombolla', 'meteorit'], hats: ['flag', 'clone', 'click'],
        pal: ['move', 'turn', 'goto', 'gotorand', 'glide', 'setx', 'sety', 'chx', 'chy', 'point', 'bounce', 'say', 'next', 'size', 'chsize', 'show', 'hide', 'ghost', 'bg', 'sound', 'wait', 'rep', 'forever', 'until', 'if', 'cond+', 'clone', 'delclone', 'setv', 'chv'],
        ops: ['rnd', 'x', 'y'], varNames: VN,
        sol: '@bombolla flag{ hide forever{ clone wait:0.4 } } clone{ gotorand sety:-170 show until:y>160{ chy:4 } delclone } @estrella flag{ hide forever{ clone wait:0.6 } } clone{ gotorand show wait:1.5 delclone }',
        check: P => { const B = blocks(P); if (!B.some(b => b.k === 'clone')) return "Encara no hi ha cap bloc «crea un clon de mi».|Todavía no hay ningún bloque «crea un clon de mí».";
          if (!Object.values(P).some(H => (H.clone || []).some(l => l.length))) return "Els clons no fan res: escriu el guió «quan començo com a clon».|Los clones no hacen nada: escribe el guion «al empezar como clon».";
          return B.some(usesRnd) ? null : "Afegeix l'atzar (un lloc o un número) perquè els clons no siguin tots iguals.|Añade el azar (un sitio o un número) para que los clones no sean todos iguales."; } },
      { k: 'quiz', ph: 'tanca', q: "Quin guió fa cada clon quan neix?|¿Qué guion hace cada clon cuando nace?",
        opts: ['Quan començo com a clon|Al empezar como clon', 'Quan comença (bandera verda)|Al empezar (bandera verde)', 'Quan toco aquest personatge|Al tocar este personaje'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "Per què va bé <b>esborrar</b> els clons que ja han arribat a baix?|¿Por qué va bien <b>borrar</b> los clones que ya han llegado abajo?",
        opts: ["Perquè l'escenari no s'ompli i en puguin sortir de nous|Para que el escenario no se llene y puedan salir nuevos", 'Perquè els clons canviïn de color|Para que los clones cambien de color', 'Perquè el programa vagi més a poc a poc|Para que el programa vaya más despacio'], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] };

  /* ---------- Sessió 3 · Cada cop més difícil ---------- */
  const ACC = (cap) => `@meteorit flag{ setv:velocitat,3 point:180 forever{ ${FALL('$velocitat')} ${cap ? `if:$velocitat<${cap}{ chv:velocitat,2 }` : 'chv:velocitat,2'} } }`;
  const S3 = { id: 'g7-3', t: 'Cada cop més difícil|Cada vez más difícil', min: 45, badge: 'g_dificultat',
    learn: ["Un bon videojoc comença fàcil i es va fent més difícil a poc a poc.|Un buen videojuego empieza fácil y se va haciendo más difícil poco a poco.",
      "Si el personatge es mou amb «mou-te velocitat passos», va més de pressa cada vegada que la variable velocitat creix.|Si el personaje se mueve con «muévete velocidad pasos», va más deprisa cada vez que la variable velocidad crece.",
      "Cal posar un límit («si velocitat < 12, suma-hi 1») perquè la dificultat no creixi fins a ser impossible.|Hay que poner un límite («si velocidad < 12, súmale 1») para que la dificultad no crezca hasta ser imposible."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "Quin bloc fa una <b>còpia</b> del personatge?|¿Qué bloque hace una <b>copia</b> del personaje?",
        opts: ['crea un clon de mi|crea un clon de mí', "mostra't|muéstrate", 'vestit següent|disfraz siguiente'], a: 0 },
      { k: 'quiz', ph: 'recorda', q: "On va el bloc <b>esborra aquest clon</b> a la pluja de meteorits?|¿Dónde va el bloque <b>borra este clon</b> en la lluvia de meteoritos?",
        opts: ['Al final del guió del clon, quan ja ha arribat a baix|Al final del guion del clon, cuando ya ha llegado abajo', 'Al principi del guió del clon|Al principio del guion del clon', 'Al guió de la bandera verda, abans de fer clons|En el guion de la bandera verde, antes de hacer clones'], a: 0,
        ex: "Si s'esborra al principi, desapareix abans de caure!|Si se borra al principio, ¡desaparece antes de caer!" },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'lab',
        t: "Hem ensenyat la pluja de meteorits a la colla de l'observatori. L'Aina ha esquivat tots els meteorits durant cinc minuts i al final ha badallat: «Massa fàcil!». En canvi, en Pol, que és més petit, diu que al principi li costava molt.|Hemos enseñado la lluvia de meteoritos al grupo del observatorio. Aina ha esquivado todos los meteoritos durante cinco minutos y al final ha bostezado: «¡Demasiado fácil!». En cambio, Pol, que es más pequeño, dice que al principio le costaba mucho." },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'lab', mood: 'think',
        t: "Els estudis de videojocs fan servir un truc: <b>comencen fàcil i es van posant difícils</b> a poc a poc, amb un límit. Així en Pol té temps d'aprendre i l'Aina no s'avorreix. Ho farem amb una variable que puja sola: la <b>velocitat</b>.|Los estudios de videojuegos usan un truco: <b>empiezan fácil y se van poniendo difíciles</b> poco a poco, con un límite. Así Pol tiene tiempo de aprender y Aina no se aburre. Lo haremos con una variable que sube sola: la <b>velocidad</b>." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Dificultat|Dificultad', t: 'Ni massa fàcil ni massa difícil|Ni demasiado fácil ni demasiado difícil', anim: 'g7corba',
          x: "Si un repte és massa fàcil, t'avorreixes. Si és massa difícil, t'enfades i ho deixes. El secret és <b>començar fàcil i pujar la dificultat a poc a poc</b>, com quan aprens a anar amb bicicleta: primer amb rodetes, després sense, després per pujades…|Si un reto es demasiado fácil, te aburres. Si es demasiado difícil, te enfadas y lo dejas. El secreto es <b>empezar fácil y subir la dificultad poco a poco</b>, como cuando aprendes a ir en bicicleta: primero con ruedines, después sin, después por cuestas…" },
        { k: 'Velocitat|Velocidad', t: 'La velocitat és una variable|La velocidad es una variable', anim: 'g7vel',
          x: "Fes una variable <b>velocitat</b> i, al principi, posa-la a 3. El meteorit es mou amb <b>mou-te velocitat passos</b>: com que el número és la variable, quan la variable creix, el meteorit va més de pressa.|Haz una variable <b>velocidad</b> y, al principio, ponla a 3. El meteorito se mueve con <b>muévete velocidad pasos</b>: como el número es la variable, cuando la variable crece, el meteorito va más deprisa." },
        { k: 'En marxa|En marcha', t: 'Cada volta, una mica més|Cada vuelta, un poco más',
          media: { k: 'stage', w: { bg: 'espai', sprites: [MET(0, 170)], vars: ['velocitat'] }, prog: ACC(0), varNames: VN, time: 9 },
          x: "Cada vegada que el meteorit torna a dalt, <b>suma 2 a velocitat</b>. Mira el número de l'escenari: 3, 5, 7, 9… i cada caiguda és més ràpida que l'anterior.|Cada vez que el meteorito vuelve arriba, <b>suma 2 a velocidad</b>. Mira el número del escenario: 3, 5, 7, 9… y cada caída es más rápida que la anterior." },
        { k: 'Altres maneres|Otras maneras', t: 'Més difícil no vol dir només més ràpid|Más difícil no quiere decir solo más rápido',
          media: { k: 'stage', w: { bg: 'nit', sprites: [EST(0, 0, { size: 150 })] }, prog: '@estrella flag{ rep:11{ gotorand wait:0.6 chsize:-10 } }', time: 8 },
          x: "També pots fer que l'objectiu sigui <b>cada vegada més petit</b> (com aquesta estrella), que surtin <b>més clons</b> (esperar menys entre un i l'altre) o que tinguis <b>menys temps</b>.|También puedes hacer que el objetivo sea <b>cada vez más pequeño</b> (como esta estrella), que salgan <b>más clones</b> (esperar menos entre uno y otro) o que tengas <b>menos tiempo</b>." },
        { k: 'Compte!|¡Cuidado!', t: 'Posa-hi un límit|Ponle un límite',
          media: { k: 'stage', w: { bg: 'espai', sprites: [MET(0, 0)], vars: ['velocitat'] }, prog: '@meteorit flag{ setv:velocitat,4 point:45 forever{ move:$velocitat if:touch:edge{ if:$velocitat<14{ chv:velocitat,2 } } bounce } }', varNames: VN, time: 10 },
          x: "Si la velocitat creix sense parar, al cap d'una estona el meteorit va tan de pressa que ningú no el pot esquivar. Suma-hi només <b>si encara és més petita que un límit</b>: aquí, quan arriba a 14, ja no puja més.|Si la velocidad crece sin parar, al cabo de un rato el meteorito va tan deprisa que nadie lo puede esquivar. Súmale solo <b>si todavía es más pequeña que un límite</b>: aquí, cuando llega a 14, ya no sube más.",
          bad: "Sumo velocitat cada vegada, sense límit: com més ràpid, millor.|Sumo velocidad cada vez, sin límite: cuanto más rápido, mejor.", good: "Sumo velocitat només si és més petita que un límit, perquè sigui difícil però possible.|Sumo velocidad solo si es más pequeña que un límite, para que sea difícil pero posible." }
      ] },
      { k: 'quiz', ph: 'mans', q: "La velocitat comença a <b>3</b> i, cada vegada que el meteorit torna a dalt, li <b>sumes 2</b>. Quant valdrà després de <b>4 voltes</b>?|La velocidad empieza en <b>3</b> y, cada vez que el meteorito vuelve arriba, le <b>sumas 2</b>. ¿Cuánto valdrá después de <b>4 vueltas</b>?",
        opts: ['11|11', '9|9', '7|7'], a: 0, ex: "3 → 5 → 7 → 9 → 11: quatre vegades 2 són 8, i 3 + 8 = 11.|3 → 5 → 7 → 9 → 11: cuatro veces 2 son 8, y 3 + 8 = 11." },
      { k: 'unplug', ph: 'mans', ico: '🧦', title: 'Cada cop més lluny|Cada vez más lejos',
        t: "Necessites un parell de mitjons fets una bola (o una pilota tova) i algú de casa.|Necesitas un par de calcetines hechos una bola (o una pelota blanda) y a alguien de casa.",
        steps: ["Poseu-vos a un pas de distància i llanceu-vos la bola. Cada vegada que l'atrapeu, feu un pas enrere: el nivell puja!|Poneos a un paso de distancia y lanzaos la bola. Cada vez que la atrapéis, dad un paso atrás: ¡el nivel sube!",
          "Si cau a terra, torneu un pas endavant.|Si cae al suelo, volved un paso adelante.",
          "Poseu un límit: com a molt, 6 passos. Si no, aviat serà impossible!|Poned un límite: como mucho, 6 pasos. Si no, ¡pronto será imposible!",
          "Parleu-ne: quan era avorrit? Quan era massa difícil? Quin nivell era el més divertit?|Habladlo: ¿cuándo era aburrido? ¿Cuándo era demasiado difícil? ¿Qué nivel era el más divertido?"] },
      { k: 'sfree', ph: 'prova', q: "Toca <b>Comença</b> i fixa't en el número de la <b>velocitat</b> mentre cauen els meteorits. Què passa a cada volta? Quan s'atura de créixer?|Toca <b>Empieza</b> y fíjate en el número de la <b>velocidad</b> mientras caen los meteoritos. ¿Qué pasa en cada vuelta? ¿Cuándo deja de crecer?",
        w: { bg: 'espai', sprites: [MET(0, 170)], vars: ['velocitat'], time: 12 }, varNames: VN, prog: ACC(13) },
      { k: 'sspot', ph: 'investiga', q: "Aquest meteorit va cada vegada més ràpid. <b>Toca el bloc que fa créixer la velocitat.</b>|Este meteorito va cada vez más rápido. <b>Toca el bloque que hace crecer la velocidad.</b>",
        w: { bg: 'espai', sprites: [MET(0, 170)], vars: ['velocitat'], time: 8 }, varNames: VN,
        prog: `@meteorit flag{ setv:velocitat,3 point:180 forever{ ${FALL('$velocitat')} chv:velocitat,2! } }`,
        ex: "«Suma a velocitat 2» fa créixer la variable. I com que «mou-te» fa servir la variable, cada caiguda és més ràpida.|«Suma a velocidad 2» hace crecer la variable. Y como «muévete» usa la variable, cada caída es más rápida." },
      { k: 'quiz', ph: 'investiga', q: "Un meteorit fa <b>mou-te 5 passos</b> i, a cada volta, <b>suma a velocitat 1</b>. Anirà cada vegada més de pressa?|Un meteorito hace <b>muévete 5 pasos</b> y, en cada vuelta, <b>suma a velocidad 1</b>. ¿Irá cada vez más deprisa?",
        opts: ['No: el «mou-te» no fa servir la variable|No: el «muévete» no usa la variable', 'Sí, cada vegada més|Sí, cada vez más', 'Només al principi|Solo al principio'], a: 0,
        ex: "La variable creix, però ningú no la fa servir. Al «mou-te» hi has de posar la variable velocitat en lloc del 5.|La variable crece, pero nadie la usa. En el «muévete» tienes que poner la variable velocidad en lugar del 5." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Pica de mans cada cop més de pressa: 5 picades lentes, 5 de normals, 5 de ràpides… i para! Ara fes-ho al revés, cada cop més a poc a poc, fins a quedar-te quiet/a com una estàtua.|Da palmadas cada vez más deprisa: 5 lentas, 5 normales, 5 rápidas… ¡y para! Ahora hazlo al revés, cada vez más despacio, hasta quedarte quieto/a como una estatua." },
      { k: 'stage', ph: 'repte', q: "Aquest meteorit suma 2 a <b>velocitat</b> a cada volta… però no s'accelera gens! Fes que es mogui <b>amb la variable</b> velocitat. Ha d'arribar a velocitat 12.|Este meteorito suma 2 a <b>velocidad</b> en cada vuelta… ¡pero no se acelera nada! Haz que se mueva <b>con la variable</b> velocidad. Tiene que llegar a velocidad 12.",
        w: { bg: 'espai', sprites: [MET(0, 170)], vars: ['velocitat'], time: 9, goal: [{ k: 'var', v: 'velocitat', min: 12 }] },
        hats: ['flag'], pal: ['move', 'gotorand', 'sety', 'point', 'until', 'forever', 'cond+', 'setv', 'chv'], ops: ['y'], varNames: VN,
        prog: '@meteorit flag{ setv:velocitat,4 point:180 forever{ gotorand sety:170 until:y<-160{ move:4 } chv:velocitat,2 } }',
        sol: '@meteorit flag{ setv:velocitat,4 point:180 forever{ gotorand sety:170 until:y<-160{ move:$velocitat } chv:velocitat,2 } }',
        hint: "Toca el 4 del bloc «mou-te 4 passos» i tria la variable velocitat.|Toca el 4 del bloque «muévete 4 pasos» y elige la variable velocidad." },
      { k: 'stage', ph: 'repte', q: "Aquest cometa rebota per l'espai i, cada vegada que toca la vora, va més de pressa… sense parar! Posa-hi un <b>límit</b>: que només sumi 1 a velocitat <b>si velocitat < 12</b>. Al final ha de quedar a 12 exactament.|Este cometa rebota por el espacio y, cada vez que toca el borde, va más deprisa… ¡sin parar! Ponle un <b>límite</b>: que solo sume 1 a velocidad <b>si velocidad < 12</b>. Al final tiene que quedar en 12 exactamente.",
        w: { bg: 'espai', sprites: [MET(0, 0, { name: 'Cometa|Cometa' })], vars: ['velocitat'], time: 20, noEarly: true, goal: [{ k: 'var', v: 'velocitat', eq: 12 }] },
        hats: ['flag'], pal: ['move', 'point', 'bounce', 'forever', 'if', 'and', 'cond+', 'setv', 'chv'], varNames: VN,
        prog: '@meteorit flag{ setv:velocitat,4 point:45 forever{ move:$velocitat if:touch:edge{ chv:velocitat,1 } bounce } }',
        sol: '@meteorit flag{ setv:velocitat,4 point:45 forever{ move:$velocitat if:touch:edge{ if:$velocitat<12{ chv:velocitat,1 } } bounce } }',
        hint: "Posa un altre «si» dins del «si toca la vora»: si velocitat < 12, llavors suma 1. (O afegeix «i» a la condició.)|Pon otro «si» dentro del «si toca el borde»: si velocidad < 12, entonces suma 1. (O añade «y» a la condición.)" },
      { k: 'stage', ph: 'repte', q: "Una altra manera de fer-ho difícil: cada vegada que toquis l'estrella, suma 1 a <b>punts</b>, fes-la <b>10 més petita</b> i porta-la a un <b>lloc a l'atzar</b>. Cada cop costarà més d'encertar-la!|Otra manera de hacerlo difícil: cada vez que toques la estrella, suma 1 a <b>puntos</b>, hazla <b>10 más pequeña</b> y llévala a un <b>sitio al azar</b>. ¡Cada vez costará más acertarla!",
        w: { bg: 'nit', sprites: [EST(0, 0)], vars: ['punts'], input: CLICKS('estrella', .5, .5, 5), time: 3.5, goal: [{ k: 'var', v: 'punts', min: 5 }, { k: 'size', s: 'estrella', max: 50 }, { k: 'moved', s: 'estrella', min: 60 }] },
        hats: ['click'], pal: ['chsize', 'size', 'gotorand', 'goto', 'chv', 'setv', 'sound'], varNames: VN,
        sol: '@estrella click{ chv:punts,1 chsize:-10 gotorand }',
        hint: "Al guió «quan toco aquest personatge»: «suma a punts 1», «canvia la mida en -10» i «ves a un lloc a l'atzar».|En el guion «al tocar este personaje»: «suma a puntos 1», «cambia el tamaño en -10» y «ve a un sitio al azar»." },
      { k: 'screate', ph: 'crea', name: "El meu repte que s'accelera|Mi reto que se acelera",
        q: "Crea un repte que es faci difícil a poc a poc. Un personatge s'ha de moure amb la variable <b>velocitat</b>, la velocitat ha de <b>créixer</b> mentre funciona el programa i ha de tenir un <b>límit</b> (un «si» que compari velocitat). La resta, tria-la tu: meteorits, la nau, una estrella…|Crea un reto que se haga difícil poco a poco. Un personaje se tiene que mover con la variable <b>velocidad</b>, la velocidad tiene que <b>crecer</b> mientras funciona el programa y tiene que tener un <b>límite</b> (un «si» que compare velocidad). El resto, elígelo tú: meteoritos, la nave, una estrella…",
        crit: ['Un personatge es mou amb la variable velocitat|Un personaje se mueve con la variable velocidad', 'La velocitat creix mentre funciona el programa|La velocidad crece mientras funciona el programa', 'Hi ha un límit perquè no sigui impossible|Hay un límite para que no sea imposible'],
        w: { bg: 'espai', bgs: ['espai', 'nit', 'cel'], sprites: [MET(0, 170), NAU(-150, -130), EST(150, 100)], vars: ['velocitat'], time: 10, goal: [{ k: 'var', v: 'velocitat', min: 6 }] },
        edit: ['meteorit', 'nau', 'estrella'], hats: ['flag', 'click'],
        pal: ['move', 'turn', 'goto', 'gotorand', 'setx', 'sety', 'chx', 'chy', 'point', 'bounce', 'say', 'next', 'size', 'chsize', 'show', 'hide', 'sound', 'wait', 'rep', 'forever', 'until', 'if', 'else', 'and', 'cond+', 'clone', 'delclone', 'setv', 'chv'],
        ops: ['rnd', 'x', 'y'], varNames: VN,
        sol: '@meteorit flag{ setv:velocitat,3 point:180 forever{ gotorand sety:170 until:y<-160{ move:$velocitat } if:$velocitat<14{ chv:velocitat,1 } } }',
        check: P => { const B = blocks(P);
          if (!B.some(b => ['move', 'chx', 'chy'].includes(b.k) && isVar(b.n, 'velocitat'))) return "Cap personatge no es mou amb la variable velocitat. Al «mou-te», tria la variable.|Ningún personaje se mueve con la variable velocidad. En el «muévete», elige la variable.";
          if (!B.some(b => b.k === 'chv' && b.v === 'velocitat')) return "La velocitat no creix: afegeix «suma a velocitat…».|La velocidad no crece: añade «suma a velocidad…».";
          return B.some(b => ['if', 'until', 'waitu'].includes(b.k) && condVar(b.c, 'velocitat')) ? null : "Falta el límit: un «si» que compari velocitat (per exemple, velocitat < 14).|Falta el límite: un «si» que compare velocidad (por ejemplo, velocidad < 14)."; } },
      { k: 'quiz', ph: 'tanca', q: "Què fa que un meteorit vagi <b>cada vegada més ràpid</b>?|¿Qué hace que un meteorito vaya <b>cada vez más rápido</b>?",
        opts: ['Que es mogui amb la variable velocitat i que la variable creixi|Que se mueva con la variable velocidad y que la variable crezca', 'Posar molts blocs «mou-te» seguits|Poner muchos bloques «muévete» seguidos', 'Canviar el fons|Cambiar el fondo'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "Per què posem un <b>límit</b> a la velocitat?|¿Por qué ponemos un <b>límite</b> a la velocidad?",
        opts: ['Perquè no arribi a ser impossible d\'esquivar|Para que no llegue a ser imposible de esquivar', 'Perquè el programa s\'aturi sol|Para que el programa se pare solo', 'Perquè els números grans no es poden fer servir|Porque los números grandes no se pueden usar'], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] };

  /* ---------- Sessió 4 · Projecte: esquiva els meteorits ---------- */
  const GAME_W = (more = {}) => ({ bg: 'espai', sprites: [NAU(0, -140), MET(0, 170)], vars: ['punts', 'vides', 'velocitat'], keys: ['left', 'right'], ...more });
  const NAU_P = 'key:left{ chx:-20 } key:right{ chx:20 }';
  const CLONE_P = v => `clone{ gotorand sety:170 show until:y<-160{ move:${v} if:touch:nau{ chv:vides,-1 sound:xoc delclone } } chv:punts,1 delclone }`;
  const FULL = `@nau flag{ goto:0,-140 setv:vides,3 forever{ if:$vides<1{ say:"Fi!|¡Fin!" stop:all } } } ${NAU_P} @meteorit flag{ hide setv:punts,0 setv:velocitat,4 point:180 forever{ clone wait:0.6 if:$velocitat<12{ chv:velocitat,1 } } } ${CLONE_P('$velocitat')}`;
  const S4 = { id: 'g7-4', t: 'Projecte: esquiva els meteorits|Proyecto: esquiva los meteoritos', min: 45, proj: true, badge: 'g_esquiva',
    learn: ["Un videojoc gran es fa a trossos: la nau, la fàbrica de meteorits, els xocs i les vides, els punts i la dificultat.|Un videojuego grande se hace a trozos: la nave, la fábrica de meteoritos, los choques y las vidas, los puntos y la dificultad.",
      "Cal provar cada tros abans de fer el següent: així, si alguna cosa falla, saps on buscar.|Hay que probar cada trozo antes de hacer el siguiente: así, si algo falla, sabes dónde buscar.",
      "Quan un company/a prova el teu videojoc, descobreixes què és massa fàcil, massa difícil o què no s'entén.|Cuando un compañero/a prueba tu videojuego, descubres qué es demasiado fácil, demasiado difícil o qué no se entiende."],
    steps: [
      { k: 'quiz', ph: 'recorda', q: "La velocitat comença a 4 i, a cada meteorit, li sumes 1, però <b>només si velocitat < 12</b>. Quant val després de 20 meteorits?|La velocidad empieza en 4 y, en cada meteorito, le sumas 1, pero <b>solo si velocidad < 12</b>. ¿Cuánto vale después de 20 meteoritos?",
        opts: ['12|12', '24|24', '20|20'], a: 0, ex: "Puja fins a 12 i allà s'atura: el límit fa que mai no passi de 12.|Sube hasta 12 y ahí se para: el límite hace que nunca pase de 12." },
      { k: 'quiz', ph: 'recorda', q: "La fàbrica de meteorits està amagada. Què ha de fer el clon perquè el vegem?|La fábrica de meteoritos está escondida. ¿Qué tiene que hacer el clon para que lo veamos?",
        opts: ["Mostrar-se quan ja és al seu lloc|Mostrarse cuando ya está en su sitio", "Esborrar-se de seguida|Borrarse enseguida", "Amagar-se una altra vegada|Esconderse otra vez"], a: 0 },
      { k: 'story', ph: 'missio', who: 'numi', scene: 'illa', title: "Demà és la Nit de les Estrelles!|¡Mañana es la Noche de las Estrellas!",
        t: "L'observatori ja té les cadires i el telescopi a punt. Només falta el nostre videojoc: <b>Esquiva els meteorits</b>. Avui ajuntarem tot el que hem après: l'atzar, els clons, les vides, els punts i la dificultat que creix. I després el provarà un company/a!|El observatorio ya tiene las sillas y el telescopio a punto. Solo falta nuestro videojuego: <b>Esquiva los meteoritos</b>. Hoy juntaremos todo lo que hemos aprendido: el azar, los clones, las vidas, los puntos y la dificultad que crece. ¡Y después lo probará un compañero/a!" },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'El pla|El plan', t: 'Les peces del videojoc|Las piezas del videojuego', anim: 'g7pla',
          x: "Abans de programar, fes la llista de peces: <b>1</b> la nau que es mou amb les fletxes, <b>2</b> la fàbrica de meteorits (clons a l'atzar), <b>3</b> els xocs, que treuen vides, <b>4</b> els punts per cada meteorit esquivat, <b>5</b> la velocitat que creix i <b>6</b> la fi de partida.|Antes de programar, haz la lista de piezas: <b>1</b> la nave que se mueve con las flechas, <b>2</b> la fábrica de meteoritos (clones al azar), <b>3</b> los choques, que quitan vidas, <b>4</b> los puntos por cada meteorito esquivado, <b>5</b> la velocidad que crece y <b>6</b> el fin de partida." },
        { k: 'Tros a tros|Trozo a trozo', t: 'Així queda el videojoc|Así queda el videojuego',
          media: { k: 'stage', w: GAME_W(), prog: FULL.replace(NAU_P, '').replace('forever{ if:$vides', 'point:90 forever{ move:5 bounce if:$vides'), varNames: VN, time: 14 },
          x: "Aquí la nau es mou sola perquè la puguis mirar; al teu videojoc la mouràs amb les fletxes. No ho programis tot de cop: fes una peça, <b>prova-la</b> i, quan funcioni, passa a la següent.|Aquí la nave se mueve sola para que la puedas mirar; en tu videojuego la moverás con las flechas. No lo programes todo de golpe: haz una pieza, <b>pruébala</b> y, cuando funcione, pasa a la siguiente." },
        { k: 'Xocs|Choques', t: 'Quan un meteorit toca la nau|Cuando un meteorito toca la nave',
          media: { k: 'stage', w: GAME_W({ sprites: [NAU(0, -140), MET(0, 170)] }), prog: `@meteorit flag{ hide setv:vides,3 point:180 setx:0 sety:170 clone wait:1.5 setx:150 clone wait:1.5 setx:-20 clone } clone{ show until:y<-160{ move:6 if:touch:nau{ chv:vides,-1 sound:xoc delclone } } chv:punts,1 delclone }`, varNames: VN, time: 7 },
          x: "Mentre baixa, el clon mira a cada pas <b>si toca la nau</b>. Si la toca: resta 1 vida, fa un so i <b>s'esborra</b>. Si arriba a baix sense tocar-la, suma 1 punt i també s'esborra.|Mientras baja, el clon mira a cada paso <b>si toca la nave</b>. Si la toca: resta 1 vida, hace un sonido y <b>se borra</b>. Si llega abajo sin tocarla, suma 1 punto y también se borra.",
          bad: "Quan el meteorit toca la nau, resto una vida i el deixo continuar.|Cuando el meteorito toca la nave, resto una vida y lo dejo seguir.", good: "Quan la toca, resto una vida i l'esborro: si no, em treu una vida a cada pas i les perdo totes de cop.|Cuando la toca, resto una vida y lo borro: si no, me quita una vida a cada paso y las pierdo todas de golpe." },
        { k: 'Provar|Probar', t: 'Prova-ho amb algú altre|Pruébalo con otra persona', anim: 'g7corba',
          x: "Tu ja saps com funciona el teu videojoc, i per això et sembla fàcil. Quan el prova un company/a, mira-ho sense ajudar: on s'encalla? S'avorreix o s'enfada? Amb el que vegis, canvia la velocitat, el límit o les vides.|Tú ya sabes cómo funciona tu videojuego, y por eso te parece fácil. Cuando lo prueba un compañero/a, míralo sin ayudar: ¿dónde se atasca? ¿Se aburre o se enfada? Con lo que veas, cambia la velocidad, el límite o las vidas." }
      ] },
      { k: 'seq', ph: 'mans', q: "Ordena els passos per construir el videojoc, tros a tros.|Ordena los pasos para construir el videojuego, trozo a trozo.",
        items: ['La nau es mou amb les fletxes|La nave se mueve con las flechas', "La fàbrica fa clons de meteorits a l'atzar|La fábrica hace clones de meteoritos al azar", 'Si un meteorit toca la nau, perds una vida|Si un meteorito toca la nave, pierdes una vida', 'Cada meteorit esquivat suma un punt|Cada meteorito esquivado suma un punto', 'La velocitat creix, amb un límit|La velocidad crece, con un límite', 'Ho prova un company/a i ho millores|Lo prueba un compañero/a y lo mejoras'],
        ex: "Primer el que es mou, després el que cau, després les regles i, al final, la dificultat i la prova.|Primero lo que se mueve, después lo que cae, después las reglas y, al final, la dificultad y la prueba." },
      { k: 'unplug', ph: 'mans', ico: '📝', title: 'El pla en paper|El plan en papel',
        t: "Abans de programar, fes el pla del teu videojoc en un full (si ja l'has fet a classe, mira'l i repassa'l).|Antes de programar, haz el plan de tu videojuego en una hoja (si ya lo has hecho en clase, míralo y repásalo).",
        steps: ["Dibuixa l'escenari: on és la nau i per on cauen els meteorits.|Dibuja el escenario: dónde está la nave y por dónde caen los meteoritos.",
          "Escriu les regles: com guanyes punts? Com perds vides? Quantes vides tens?|Escribe las reglas: ¿cómo ganas puntos? ¿Cómo pierdes vidas? ¿Cuántas vidas tienes?",
          "Decideix com es fa difícil: a quina velocitat comença, quant puja i quin és el límit.|Decide cómo se hace difícil: a qué velocidad empieza, cuánto sube y cuál es el límite.",
          "Explica el pla a algú de casa. Si hi ha alguna cosa que no s'entén, millora-la.|Explica el plan a alguien de casa. Si hay algo que no se entiende, mejóralo."] },
      { k: 'stage', ph: 'repte', q: "<b>Peça 1: la nau.</b> Fes que la nau es mogui cap a l'esquerra amb la fletxa ← i cap a la dreta amb la fletxa →. Prova-ho amb «Comença» i les fletxes, i després toca <b>Comprova</b>.|<b>Pieza 1: la nave.</b> Haz que la nave se mueva hacia la izquierda con la flecha ← y hacia la derecha con la flecha →. Pruébalo con «Empieza» y las flechas, y después toca <b>Comprueba</b>.",
        w: { bg: 'espai', sprites: [NAU(0, -140)], keys: ['left', 'right'], input: [{ t: .3, key: 'right', dur: 1 }, { t: 1.6, key: 'left', dur: 2 }], time: 4,
          goal: [{ k: 'reach', s: 'nau', r: [60, -180, 240, -100] }, { k: 'reach', s: 'nau', r: [-240, -180, -60, -100] }] },
        hats: ['flag', 'key:left', 'key:right'], pal: ['chx', 'setx', 'goto', 'move', 'point', 'say'],
        sol: `@nau flag{ goto:0,-140 } ${NAU_P}`,
        hint: "Al guió «quan premo la tecla ← fletxa esquerra», posa «canvia x en -20». A la fletxa dreta, «canvia x en 20».|En el guion «al pulsar la tecla ← flecha izquierda», pon «cambia x en -20». En la flecha derecha, «cambia x en 20»." },
      { k: 'stage', ph: 'repte', q: "<b>Peça 2: la fàbrica.</b> El meteorit s'amaga, posa <b>punts</b> a 0 i fa un clon cada 0,6 segons. Cada clon surt per dalt en un lloc a l'atzar, es mostra, baixa i, quan arriba a baix, suma 1 punt i s'esborra.|<b>Pieza 2: la fábrica.</b> El meteorito se esconde, pone <b>puntos</b> a 0 y hace un clon cada 0,6 segundos. Cada clon sale por arriba en un sitio al azar, se muestra, baja y, cuando llega abajo, suma 1 punto y se borra.",
        w: { bg: 'espai', sprites: [NAU(0, -140), MET(0, 170)], vars: ['punts'], time: 8, goal: [{ k: 'clones', min: 10 }, { k: 'var', v: 'punts', min: 6 }, { k: 'hidden', s: 'meteorit' }] },
        edit: ['meteorit'], hats: ['flag', 'clone'], pal: ['hide', 'show', 'clone', 'delclone', 'wait', 'forever', 'gotorand', 'sety', 'point', 'move', 'chy', 'until', 'cond+', 'setv', 'chv'], ops: ['y'], varNames: VN,
        sol: `@meteorit flag{ hide setv:punts,0 point:180 forever{ clone wait:0.6 } } clone{ ${FALL(7).replace('until', 'show until')} chv:punts,1 delclone }`,
        hint: "És com la pluja de meteorits de la sessió de clons, amb «suma a punts 1» abans d'«esborra aquest clon».|Es como la lluvia de meteoritos de la sesión de clones, con «suma a puntos 1» antes de «borra este clon»." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de nau! Els meteorits imaginaris cauen del sostre: esquiva'ls amb un pas a la dreta, un pas a l'esquerra, ajupint-te… Cada vegada més de pressa!|¡Haz de nave! Los meteoritos imaginarios caen del techo: esquívalos con un paso a la derecha, un paso a la izquierda, agachándote… ¡Cada vez más deprisa!" },
      { k: 'stage', ph: 'repte', q: "<b>Peça 3: els xocs.</b> Els clons ja baixen i sumen punts. Dins del bucle del clon, afegeix: <b>si toca la nau</b> → suma a vides -1, fes el so «xoc» i esborra aquest clon. En aquesta prova cauen 4 meteorits i 2 toquen la nau: han de quedar 1 vida i 2 punts.|<b>Pieza 3: los choques.</b> Los clones ya bajan y suman puntos. Dentro del bucle del clon, añade: <b>si toca la nave</b> → suma a vidas -1, haz el sonido «choque» y borra este clon. En esta prueba caen 4 meteoritos y 2 tocan la nave: tienen que quedar 1 vida y 2 puntos.",
        w: { bg: 'espai', sprites: [NAU(0, -140), MET(0, 170)], vars: ['punts', 'vides'], time: 8, goal: [{ k: 'var', v: 'vides', eq: 1 }, { k: 'var', v: 'punts', eq: 2 }] },
        edit: ['meteorit'], hats: ['flag', 'clone'], pal: ['hide', 'show', 'clone', 'delclone', 'wait', 'setx', 'sety', 'point', 'move', 'until', 'if', 'cond+', 'setv', 'chv', 'sound'], ops: ['y'], varNames: VN,
        prog: '@meteorit flag{ hide point:180 setv:vides,3 setv:punts,0 setx:0 sety:170 clone wait:1.6 setx:170 clone wait:1.6 setx:-20 clone wait:1.6 setx:-180 clone } clone{ show until:y<-160{ move:7 } chv:punts,1 delclone }',
        sol: '@meteorit flag{ hide point:180 setv:vides,3 setv:punts,0 setx:0 sety:170 clone wait:1.6 setx:170 clone wait:1.6 setx:-20 clone wait:1.6 setx:-180 clone } clone{ show until:y<-160{ move:7 if:touch:nau{ chv:vides,-1 sound:xoc delclone } } chv:punts,1 delclone }',
        hint: "El «si toca la nau» va dins del «repeteix fins que», just després del «mou-te», perquè ho miri a cada pas. No t'oblidis d'esborrar el clon!|El «si toca la nave» va dentro del «repite hasta que», justo después del «muévete», para que lo mire a cada paso. ¡No te olvides de borrar el clon!" },
      { k: 'sspot', ph: 'investiga', q: "Aquest és el videojoc sencer. <b>Toca el bloc que acaba la partida</b> quan ja no queden vides.|Este es el videojuego entero. <b>Toca el bloque que acaba la partida</b> cuando ya no quedan vidas.",
        w: GAME_W({ time: 10 }), varNames: VN, prog: FULL.replace('stop:all', 'stop:all!'),
        ex: "«Atura tot» para tots els guions de tots els personatges: la partida s'ha acabat. Just abans, la nau diu «Fi!».|«Para todo» detiene todos los guiones de todos los personajes: la partida se ha acabado. Justo antes, la nave dice «¡Fin!»." },
      { k: 'quiz', ph: 'investiga', q: "Si el clon toca la nau, resta una vida… però <b>no s'esborra</b>. Què passa?|Si el clon toca la nave, resta una vida… pero <b>no se borra</b>. ¿Qué pasa?",
        opts: ["Treu una vida a cada pas mentre la toca, i en perds moltes de cop|Quita una vida a cada paso mientras la toca, y pierdes muchas de golpe", 'Treu una sola vida i ja està|Quita una sola vida y ya está', 'No treu cap vida|No quita ninguna vida'], a: 0,
        ex: "El bucle continua i el clon continua tocant la nau uns quants passos. Per això s'ha d'esborrar de seguida.|El bucle sigue y el clon sigue tocando la nave unos cuantos pasos. Por eso se tiene que borrar enseguida." },
      { k: 'screate', ph: 'crea', name: 'Esquiva els meteorits|Esquiva los meteoritos',
        q: "<b>El teu videojoc!</b> Ja tens la nau, la fàbrica, els xocs i els punts. Falta: <b>1</b> que els clons baixin amb la variable <b>velocitat</b>, <b>2</b> que la velocitat <b>creixi amb un límit</b> i <b>3</b> la <b>fi de partida</b>: quan vides < 1, la nau diu «Fi!» i atura-ho tot. Després, personalitza'l: el fons, els sons, les vides…|<b>¡Tu videojuego!</b> Ya tienes la nave, la fábrica, los choques y los puntos. Falta: <b>1</b> que los clones bajen con la variable <b>velocidad</b>, <b>2</b> que la velocidad <b>crezca con un límite</b> y <b>3</b> el <b>fin de partida</b>: cuando vidas < 1, la nave dice «¡Fin!» y lo para todo. Después, personalízalo: el fondo, los sonidos, las vidas…",
        crit: ['Els meteorits baixen amb la variable velocitat|Los meteoritos bajan con la variable velocidad', 'La velocitat creix i té un límit|La velocidad crece y tiene un límite', 'Quan no queden vides, la partida acaba|Cuando no quedan vidas, la partida acaba', 'Ho has provat amb les fletxes|Lo has probado con las flechas'],
        w: GAME_W({ bgs: ['espai', 'nit', 'cel'], input: [{ t: .5, key: 'right', dur: 1.2 }, { t: 2.2, key: 'left', dur: 2.4 }, { t: 5, key: 'right', dur: 1 }], time: 7, goal: [{ k: 'clones', min: 4 }, { k: 'var', v: 'velocitat', min: 8 }, { k: 'moved', s: 'nau', min: 100 }] }),
        edit: ['nau', 'meteorit'], hats: ['flag', 'key:left', 'key:right', 'clone'],
        pal: ['move', 'goto', 'gotorand', 'setx', 'sety', 'chx', 'chy', 'point', 'say', 'next', 'size', 'show', 'hide', 'bg', 'sound', 'wait', 'forever', 'until', 'if', 'else', 'and', 'cond+', 'stop', 'clone', 'delclone', 'setv', 'chv'],
        ops: ['rnd', 'x', 'y'], varNames: VN, texts: ['Fi!|¡Fin!', 'Has guanyat!|¡Has ganado!'],
        prog: `@nau flag{ goto:0,-140 setv:vides,3 } ${NAU_P} @meteorit flag{ hide setv:punts,0 setv:velocitat,4 point:180 forever{ clone wait:0.6 } } ${CLONE_P(4)}`,
        sol: FULL,
        check: P => { const B = blocks(P);
          if (!B.some(b => b.k === 'move' && isVar(b.n, 'velocitat')) && !B.some(b => ['chy', 'chx'].includes(b.k) && isVar(b.n, 'velocitat'))) return "Els clons encara no baixen amb la variable velocitat: toca el 4 del «mou-te» i tria velocitat.|Los clones todavía no bajan con la variable velocidad: toca el 4 del «muévete» y elige velocidad.";
          if (!B.some(b => ['if', 'until', 'waitu'].includes(b.k) && condVar(b.c, 'velocitat'))) return "Falta el límit de la velocitat: «si velocitat < 12, suma a velocitat 1».|Falta el límite de la velocidad: «si velocidad < 12, suma a velocidad 1».";
          if (!B.some(b => b.k === 'stop')) return "Falta la fi de partida: si vides < 1, digues «Fi!» i atura tot.|Falta el fin de partida: si vidas < 1, di «¡Fin!» y para todo.";
          return null; } },
      { k: 'review', ph: 'crea', q: "Ara canvieu de lloc: prova el videojoc d'un company/a (sense que t'ajudi!) i després respon amb sinceritat i amabilitat.|Ahora cambiad de sitio: prueba el videojuego de un compañero/a (¡sin que te ayude!) y después responde con sinceridad y amabilidad.",
        items: [{ q: 'Com era de difícil?|¿Cómo de difícil era?', opts: ['Massa fàcil|Demasiado fácil', 'Bé: difícil però possible|Bien: difícil pero posible', 'Massa difícil|Demasiado difícil'] },
          { q: "S'anava fent més difícil?|¿Se iba haciendo más difícil?", opts: ['Sí, es notava|Sí, se notaba', 'Una mica|Un poco', 'No|No'] },
          { q: 'Què li proposaries?|¿Qué le propondrías?', opts: ['Més vides|Más vidas', 'Un límit de velocitat més alt|Un límite de velocidad más alto', 'Un so o un fons nou|Un sonido o un fondo nuevo'] }] },
      { k: 'quiz', ph: 'tanca', q: "Per què és millor programar el videojoc <b>tros a tros</b>?|¿Por qué es mejor programar el videojuego <b>trozo a trozo</b>?",
        opts: ['Perquè si una cosa falla, saps en quin tros és|Porque si algo falla, sabes en qué trozo está', 'Perquè així té més blocs|Porque así tiene más bloques', "Perquè l'ordinador només en pot fer un|Porque el ordenador solo puede hacer uno"], a: 0 },
      { k: 'quiz', ph: 'tanca', q: "Què fa que cada partida sigui diferent?|¿Qué hace que cada partida sea diferente?",
        opts: ["Que els meteorits surten en llocs a l'atzar|Que los meteoritos salen en sitios al azar", 'Que la nau és blava|Que la nave es azul', 'Que hi ha 3 vides|Que hay 3 vidas'], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] };

  return { t: 'Atzar i dificultat|Azar y dificultad', d: 'Videojocs que sorprenen|Videojuegos que sorprenden', color: '#5B4BD8', s: [S1, S2, S3, S4] };
})();
