/* Tech 3D · Nivell 2 · unitat 3 «Operacions booleanes» · guia del professor (p3-1 … p3-4)
   Material propi de Numi. Classe de 60 minuts; mateix esquema que TGUIDE['r1-1'] (guia completa). Les diapositives
   «media» mostren el programa (amb colors) i el model 3D que en surt (TMEDIA.model); el camp «code» mostra el programa
   en la llengua de la presentació. */
Object.assign(TGUIDE, (() => {
  const J = (...l) => l.join('\n');
  // el programa amb les paraules en castellà (per al camp «code» de les diapositives i les fitxes): "català|castellano"
  const KW = { cub: 'cubo', cilindre: 'cilindro', con: 'cono', mou: 'mueve', uneix: 'une', anell: 'anillo', centrat: 'centrado', tub: 'tubo', falca: 'cuña', cor: 'corazón', blau: 'azul', vermell: 'rojo', groc: 'amarillo', verd: 'verde', lila: 'morado' };
  const CE = s => s + '|' + s.replace(/[A-Za-zÀ-ÿ_·]+/g, w => KW[w] || w);
  const TROFEU = J('uneix {', '  cilindre(30, 6)', '  mou(0, 0, 5) cilindre(10, 30)', '  mou(0, 0, 34) con(10, 16, 28)', '}');
  const TROFEU_MAL = J('uneix {', '  cilindre(30, 6)', '  mou(0, 0, 5) cilindre(10, 30)', '  mou(0, 0, 40) con(10, 16, 28)', '}');
  const CREU = J('color("lila") gira(0, 0, 30) uneix {', '  mou(-20, -4, 0) cub(40, 8, 6)', '  mou(-4, -20, 0) cub(8, 40, 6)', '}');
  const PODI = J('uneix {', '  cub(20, 20, 14)', '  mou(20, 0, 0) cub(20, 20, 20)', '  mou(40, 0, 0) cub(20, 20, 10)', '}');
  const MEDALLA = J('uneix {', '  cilindre(30, 3)', '  mou(0, 19, 0) anell(12, 3)', '}');
  const QUADRE = J('resta {', '  cub(40, 40, 6)', '  mou(20, 20, -1) cilindre(16, 8)', '}');
  const QUADRE_INV = J('resta {', '  mou(20, 20, -1) cilindre(16, 8)', '  cub(40, 40, 6)', '}');
  const GOT = J('resta {', '  cilindre(40, 60)', '  mou(0, 0, 2) cilindre(36, 60)', '}');
  const PENJ = J('resta {', '  uneix {', '    cub(60, 40, 6)', '    cub(6, 40, 50)', '  }', '  mou(35, 20, -1) cilindre(8, 8)', '  mou(-1, 20, 35) gira(0, 90, 0) cilindre(8, 8)', '}');
  const REGLE = J('resta {', '  cub(60, 20, 4)', '  mou(10, 10, -1) cilindre(6, 6)', '  mou(30, 10, -1) cilindre(6, 6)', '  mou(50, 10, -1) cilindre(6, 6)', '}');
  const REGLE_MAL = J('resta {', '  cub(60, 20, 4)', '  mou(10, 10, -1) cilindre(6, 3)', '  mou(30, 10, -1) cilindre(6, 6)', '  mou(50, 10, -1) cilindre(6, 6)', '}');
  const PLANT = J('resta {', '  cub(80, 30, 3)', '  mou(15, 15, -1) cilindre(16, 5)', '  mou(33, 8, -1) cub(14, 14, 5)', '  mou(65, 15, -1) prisma(16, 5)', '}');
  const LENT = J('interseca {', '  mou(0, 0, -8) esfera(40)', '  mou(0, 0, 20) esfera(40)', '}');
  const CUPULA = J('interseca {', '  esfera(40)', '  mou(-20, -20, 0) cub(40, 40, 20)', '}');
  const DAU0 = J('mou(0, 0, 10) interseca {', '  cub(20, centrat)', '  esfera(28)', '}');
  const QUART = J('interseca {', '  cub(20, 20, 10)', '  mou(0, 0, -1) cilindre(40, 12)', '}');
  const BICIL = J('interseca {', '  gira(90, 0, 0) cilindre(30, 40, centrat)', '  gira(0, 90, 0) cilindre(30, 40, centrat)', '}');
  const EIXD = J('interseca {', '  cilindre(10, 20)', '  mou(-5, -5, 0) cub(10, 8, 20)', '}');
  const COS = ['  interseca {', '    cub(20, centrat)', '    esfera(28)', '  }'];
  const P = (x, y, z) => `  mou(${x}, ${y}, ${z}) esfera(4)`;
  const C1 = [P(0, 0, 10)], C2 = [P(-5, -10, 5), P(5, -10, -5)], C3 = [P(10, -5, -5), P(10, 0, 0), P(10, 5, 5)];
  const C6 = [P(-5, -5, -10), P(-5, 0, -10), P(-5, 5, -10), P(5, -5, -10), P(5, 0, -10), P(5, 5, -10)];
  const C5 = [P(-5, 10, -5), P(5, 10, -5), P(0, 10, 0), P(-5, 10, 5), P(5, 10, 5)], C4 = [P(-10, -5, -5), P(-10, 5, -5), P(-10, -5, 5), P(-10, 5, 5)];
  const DAU = (...f) => J('mou(0, 0, 10) resta {', ...COS, ...f.flat(), '}');
  const DAU1 = DAU(C1), DAU12 = DAU(C1, C2), DAU123 = DAU(C1, C2, C3), DAU_TOT = DAU(C1, C2, C3, C6, C5, C4);
  const DAU_MAL = J('mou(0, 0, 10) resta {', ...COS, ...C1, P(-5, -10, 5), P(5, 10, -5), '}');
  return {
  /* ---------- Sessió 1 · Unió: una sola peça ---------- */
  'p3-1': {
    obj: ["L'alumne/a fa servir uneix per combinar diverses formes en una sola peça.|El alumno/a usa une para combinar varias formas en una sola pieza.",
      "L'alumne/a col·loca les formes perquè s'encavalquin una mica i evita els buits i els contactes d'un sol punt.|El alumno/a coloca las formas para que se solapen un poco y evita los huecos y los contactos de un solo punto.",
      "L'alumne/a aplica un mou, un gira o un color a una unió sencera.|El alumno/a aplica un mueve, un gira o un color a una unión entera.",
      "L'alumne/a explica per què un model per imprimir ha de ser un sol sòlid tancat.|El alumno/a explica por qué un modelo para imprimir tiene que ser un solo sólido cerrado."],
    comp: ['Tecnologia i digitalització: disseny assistit per ordinador (CAD 3D) i preparació de models per a la fabricació digital|Tecnología y digitalización: diseño asistido por ordenador (CAD 3D) y preparación de modelos para la fabricación digital',
      'Matemàtiques: operacions amb conjunts (la unió) i posició en l\'espai amb coordenades|Matemáticas: operaciones con conjuntos (la unión) y posición en el espacio con coordenadas',
      'Pensament computacional: agrupar instruccions en blocs i aplicar-los transformacions|Pensamiento computacional: agrupar instrucciones en bloques y aplicarles transformaciones',
      "Aprendre a aprendre: comprovar un model abans de fabricar-lo|Aprender a aprender: comprobar un modelo antes de fabricarlo"],
    vocab: [['Operació booleana|Operación booleana', 'Manera de combinar dues o més formes: unió, diferència o intersecció.|Manera de combinar dos o más formas: unión, diferencia o intersección.'],
      ['Unió (uneix)|Unión (une)', 'Operació que fon les formes en un sol sòlid.|Operación que funde las formas en un solo sólido.'],
      ['Encavalcar|Solapar', 'Fer que dues formes comparteixin una part de l\'espai.|Hacer que dos formas compartan una parte del espacio.'],
      ['Sòlid tancat|Sólido cerrado', "Un objecte amb una sola pell de fora, sense forats a la superfície: el que necessita un fitxer STL.|Un objeto con una sola piel de fuera, sin agujeros en la superficie: lo que necesita un archivo STL."],
      ['Peça solta|Pieza suelta', 'Una part del model que no toca la resta i que la impressora faria a part.|Una parte del modelo que no toca el resto y que la impresora haría aparte.']],
    mat: { aula: ['Un ordinador per alumne/a amb Numi Tech obert a la sessió «Unió: una sola peça»|Un ordenador por alumno/a con Numi Tech abierto en la sesión «Unión: una sola pieza»', 'Projector i la presentació de la sessió|Proyector y la presentación de la sesión', 'Plastilina de dos colors (una bola de cada per parella) i un fil o un regle per tallar-la|Plastilina de dos colores (una bola de cada por pareja) y un hilo o una regla para cortarla'],
      imprimir: ['Fitxa: una peça o més? (una per alumne/a)|Ficha: ¿una pieza o más? (una por alumno/a)'],
      prep: ['Repartir la plastilina en bosses per parelles.|Repartir la plastilina en bolsas por parejas.', "Provar el repte de la medalla: és el primer que demana calcular on comença una forma perquè s'encavalqui sense tapar un forat.|Probar el reto de la medalla: es el primero que pide calcular dónde empieza una forma para que se solape sin tapar un agujero.", 'Si teniu impressora 3D, imprimir el trofeu (uns 50 mm d\'alt) per ensenyar que surt d\'una sola peça.|Si tenéis impresora 3D, imprimir el trofeo (unos 50 mm de alto) para enseñar que sale de una sola pieza.'] },
    plan: [
      { min: 5, t: "L'encàrrec de l'institut|El encargo del instituto", fase: 'inici', fa: "Presenta la unitat: l'institut encarrega trofeus, una plantilla, lents i daus, i per fer-los cal combinar formes. Recordeu la unitat anterior: els girs són al voltant de l'origen i un mou davant d'unes claus mou tot el bloc.|Presenta la unidad: el instituto encarga trofeos, una plantilla, lentes y dados, y para hacerlos hay que combinar formas. Recordad la unidad anterior: los giros son alrededor del origen y un mueve delante de unas llaves mueve todo el bloque.",
        diu: ["Un trofeu té base, columna i copa. Com ho fem perquè la impressora no en faci tres trossos?|Un trofeo tiene base, columna y copa. ¿Cómo lo hacemos para que la impresora no haga tres trozos?"], slides: ['s1', 's2', 's3'], app: 'Encara no: pantalles abaixades.|Todavía no: pantallas bajadas.', org: 'Tot el grup|Todo el grupo' },
      { min: 12, t: 'Unir formes|Unir formas', fase: 'teoria', fa: "Presenta les tres operacions booleanes amb el quadrat i el cercle i centra't en la unió. Amb el trofeu, fes llegir els números: on acaba cada forma i on comença la següent? Explica la regla d'encavalcar 1 mm i què passa amb un buit o amb un sol punt de contacte. Acaba amb la creu girada: un sol gira per a tot el grup.|Presenta las tres operaciones booleanas con el cuadrado y el círculo y céntrate en la unión. Con el trofeo, haz leer los números: ¿dónde acaba cada forma y dónde empieza la siguiente? Explica la regla de solapar 1 mm y qué pasa con un hueco o con un solo punto de contacto. Termina con la cruz girada: un solo gira para todo el grupo.",
        diu: ['On acaba la columna? I on comença la copa?|¿Dónde acaba la columna? ¿Y dónde empieza la copa?', 'Què passaria si la copa comencés a z = 40?|¿Qué pasaría si la copa empezara en z = 40?'], slides: ['s4', 's5', 's6', 's7', 's8'], app: "Encara no: tota l'atenció a la projecció.|Todavía no: toda la atención en la proyección.", org: 'Tot el grup|Todo el grupo' },
      { min: 10, t: 'Unir amb plastilina|Unir con plastilina', fase: 'desconnectat', fa: "Per parelles: columna i bola de plastilina, primer només tocant-se i després encavalcades. Aixequen la figura, la tallen pel mig i dibuixen les dues versions de costat. Posa en comú: quina és més resistent i per què.|Por parejas: columna y bola de plastilina, primero solo tocándose y después solapadas. Levantan la figura, la cortan por la mitad y dibujan las dos versiones de lado. Pon en común: cuál es más resistente y por qué.",
        diu: ['Què ha passat quan només es tocaven?|¿Qué ha pasado cuando solo se tocaban?', 'On es veu, al tall, que les dues formes s\'han fos?|¿Dónde se ve, en el corte, que las dos formas se han fundido?'], slides: ['s9'], app: 'Encara no: plastilina.|Todavía no: plastilina.', org: 'Per parelles|Por parejas' },
      { min: 20, t: 'Predir, trobar i unir|Predecir, encontrar y unir', fase: 'ordinador', fa: "Fan la sessió a l'app: prediccions, trobar l'error del trofeu i els reptes de l'escaire, la medalla i el podi (la medalla d'or és extra). A la medalla, demana que diguin en veu alta on és la vora del disc abans de moure l'anella.|Hacen la sesión en la app: predicciones, encontrar el error del trofeo y los retos de la escuadra, la medalla y el podio (la medalla de oro es extra). En la medalla, pide que digan en voz alta dónde está el borde del disco antes de mover la anilla.",
        diu: ['Mira el model de costat: es toquen de debò?|Mira el modelo de lado: ¿se tocan de verdad?', "La comprovació «És una sola peça» és vermella: on hi ha el buit?|La comprobación «Es una sola pieza» está en rojo: ¿dónde está el hueco?"], slides: ['s10', 's11', 's12'], app: 'Sessió «Unió: una sola peça», fins al trofeu lliure.|Sesión «Unión: una sola pieza», hasta el trofeo libre.', org: 'Individual|Individual' },
      { min: 8, t: 'El teu trofeu|Tu trofeo', fase: 'crea', fa: "Dissenyen el seu trofeu amb almenys 4 formes dins d'un uneix, d'una sola peça i de 80 mm com a molt. Es desa a «Projectes». Qui acabi aviat pot afegir-hi nanses amb anells girats.|Diseñan su trofeo con al menos 4 formas dentro de un une, de una sola pieza y de 80 mm como mucho. Se guarda en «Proyectos». Quien acabe pronto puede añadir asas con anillos girados.",
        diu: ['Totes les formes són dins de les claus de l\'uneix?|¿Todas las formas están dentro de las llaves del une?'], slides: ['s13'], app: 'Pas «El teu trofeu».|Paso «Tu trofeo».', org: 'Individual|Individual' },
      { min: 5, t: 'Tancament|Cierre', fase: 'tancament', fa: 'Repassa les tres idees clau i el tiquet de sortida.|Repasa las tres ideas clave y el ticket de salida.', diu: ["Per què s'han d'encavalcar les formes?|¿Por qué tienen que solaparse las formas?"], slides: ['s14', 's15'], app: "Les últimes preguntes i «Com t'ha anat?».|Las últimas preguntas y «¿Cómo te ha ido?».", org: 'Tot el grup|Todo el grupo' }
    ],
    errors: [["Posa la forma just a tocar per un punt, o deixa un buit, i surten dues peces.|Pone la forma justo tocando por un punto, o deja un hueco, y salen dos piezas.", "Que miri el model des del costat i que calculi en veu alta on acaba la forma de sota. La regla: la de sobre comença 1 mm abans.|Que mire el modelo desde el lado y que calcule en voz alta dónde acaba la forma de abajo. La regla: la de encima empieza 1 mm antes."],
      ["Deixa una forma fora de les claus de l'uneix.|Deja una forma fuera de las llaves del une.", "Als blocs, les formes de dins queden dins del bloc uneix (amb sagnat). Que seleccioni la forma i la mogui amb les fletxes fins que hi entri.|En los bloques, las formas de dentro quedan dentro del bloque une (con sangría). Que seleccione la forma y la mueva con las flechas hasta que entre."],
      ['Creu que uneix acosta les formes fins que es toquen.|Cree que une acerca las formas hasta que se tocan.', "uneix no mou res: cada forma es queda on la posa el seu mou. Mostra-ho amb la pregunta dels dos cubs separats 2 mm.|une no mueve nada: cada forma se queda donde la pone su mueve. Muéstralo con la pregunta de los dos cubos separados 2 mm."]],
    diff: { mes: "Fer la medalla d'or amb l'estrella en relleu i afegir nanses al trofeu amb dos anells girats 90° (gira(90, 0, 0) anell…) que s'encavalquin amb la copa. Exportar el trofeu en STL i obrir-lo en un visor per comprovar que és una sola peça.|Hacer la medalla de oro con la estrella en relieve y añadir asas al trofeo con dos anillos girados 90° (gira(90, 0, 0) anillo…) que se solapen con la copa. Exportar el trofeo en STL y abrirlo en un visor para comprobar que es una sola pieza.",
      menys: "Treballar en parella amb la fitxa al costat, on hi ha on acaba cada forma. Fer primer l'escaire i el podi, que només demanen sumar mides, i deixar la medalla per al final.|Trabajar en pareja con la ficha al lado, donde está dónde acaba cada forma. Hacer primero la escuadra y el podio, que solo piden sumar medidas, y dejar la medalla para el final." },
    aval: { ticket: ["Per què s'han d'encavalcar una mica les formes d'una unió?|¿Por qué tienen que solaparse un poco las formas de una unión?", "Escriu una unió d'un cilindre i una esfera que surti d'una sola peça.|Escribe una unión de un cilindro y una esfera que salga de una sola pieza."],
      rubric: [['Unir formes|Unir formas', "Fa servir uneix i hi posa totes les formes que han d'anar juntes.|Usa une y pone dentro todas las formas que tienen que ir juntas.", "Fa servir uneix, però deixa alguna forma fora del bloc.|Usa une, pero deja alguna forma fuera del bloque."],
        ['Encavalcar|Solapar', 'Calcula la posició perquè les formes entrin una mica l\'una dins de l\'altra.|Calcula la posición para que las formas entren un poco una dentro de la otra.', 'Col·loca les formes a ull i de vegades queden buits.|Coloca las formas a ojo y a veces quedan huecos.'],
        ['Transformar el grup|Transformar el grupo', 'Aplica un sol mou, gira o color a tota la unió.|Aplica un solo mueve, gira o color a toda la unión.', 'Transforma les formes una per una.|Transforma las formas una por una.']] },
    casa: "Busca a casa un objecte fet de diverses parts (una cadira, un llum, una joguina de construcció…). Dibuixa'l de costat i marca on s'uneixen les parts: s'encavalquen, es toquen per una cara o només per un punt?|Busca en casa un objeto hecho de varias partes (una silla, una lámpara, un juguete de construcción…). Dibújalo de lado y marca dónde se unen las partes: ¿se solapan, se tocan por una cara o solo por un punto?",
    intro: "Primera sessió de les operacions booleanes. Després de dues unitats posant formes al seu lloc, l'alumnat descobreix que les formes es poden combinar, i comença per la unió. L'important no és el bloc uneix en si (és fàcil), sinó la idea d'enginyeria que hi ha al darrere: una peça impresa ha de ser un sol sòlid tancat, i això demana que les formes s'encavalquin. A l'activitat amb plastilina ho experimenten amb les mans.|Primera sesión de las operaciones booleanas. Después de dos unidades poniendo formas en su sitio, el alumnado descubre que las formas se pueden combinar, y empieza por la unión. Lo importante no es el bloque une en sí (es fácil), sino la idea de ingeniería que hay detrás: una pieza impresa tiene que ser un solo sólido cerrado, y eso pide que las formas se solapen. En la actividad con plastilina lo experimentan con las manos.",
    claus: ["uneix { } fon totes les formes de dins en un sol sòlid.|une { } funde todas las formas de dentro en un solo sólido.", "Si hi ha un buit, surten dues peces; si es toquen per un sol punt, la peça és fràgil. Regla pràctica: encavalcar 1 mm.|Si hay un hueco, salen dos piezas; si se tocan por un solo punto, la pieza es frágil. Regla práctica: solapar 1 mm.", 'Un mou, un gira o un color davant d\'un uneix afecta tota la unió.|Un mueve, un gira o un color delante de un une afecta a toda la unión.', "uneix no mou les formes: les posicions les decideix cada mou.|une no mueve las formas: las posiciones las decide cada mueve."],
    prev: ["Saber col·locar formes amb mou i que el cilindre i el con tenen la base a z = 0.|Saber colocar formas con mueve y que el cilindro y el cono tienen la base en z = 0.", "Saber que un mou davant d'unes claus { } afecta tot el bloc.|Saber que un mueve delante de unas llaves { } afecta a todo el bloque.", "Saber sumar mides per trobar on acaba una forma.|Saber sumar medidas para encontrar dónde acaba una forma."],
    faq: [["Si les formes ja es veuen juntes, per què cal l'uneix?|Si las formas ya se ven juntas, ¿por qué hace falta el une?", "Visualment no canvia res, però agrupa les formes en un sol objecte: es poden transformar juntes i, a la sessió següent, es podran restar d'un sol cop. També deixa clar a qui llegeix el programa què va junt.|Visualmente no cambia nada, pero agrupa las formas en un solo objeto: se pueden transformar juntas y, en la sesión siguiente, se podrán restar de una vez. También deja claro a quien lee el programa qué va junto."],
      ["Per què 1 mm i no 0,1 mm?|¿Por qué 1 mm y no 0,1 mm?", "Qualsevol encavalcament funciona, però 1 mm és fàcil de calcular i ben segur: la impressora fa capes d'unes dècimes de mil·límetre, i una unió de 0,1 mm seria massa fina.|Cualquier solapamiento funciona, pero 1 mm es fácil de calcular y muy seguro: la impresora hace capas de unas décimas de milímetro, y una unión de 0,1 mm sería demasiado fina."],
      ['Qui era George Boole?|¿Quién era George Boole?', "Un matemàtic anglès del segle XIX que va crear una àlgebra per a la lògica (cert o fals, i, o, no). Avui la fan servir tots els ordinadors, i també els programes de disseny 3D per combinar formes.|Un matemático inglés del siglo XIX que creó un álgebra para la lógica (verdadero o falso, y, o, no). Hoy la usan todos los ordenadores, y también los programas de diseño 3D para combinar formas."]],
    tec: [["La comprovació «És una sola peça» no es posa verda tot i que les formes es toquen.|La comprobación «Es una sola pieza» no se pone verde aunque las formas se tocan.", "Probablement es toquen per un punt o una aresta, o hi ha un buit de dècimes. Que acosti la càmera al punt d'unió o que encavalqui 1 mm.|Probablemente se tocan por un punto o una arista, o hay un hueco de décimas. Que acerque la cámara al punto de unión o que solape 1 mm."],
      ["El bloc de l'anella té números que no s'entenen.|El bloque de la anilla tiene números que no se entienden.", "anell(diàmetre, gruix): el primer número és el diàmetre de fora i el segon, el gruix del tub. Un anell(12, 3) té un forat de 12 − 3 − 3 = 6 mm.|anillo(diámetro, grosor): el primer número es el diámetro de fuera y el segundo, el grosor del tubo. Un anillo(12, 3) tiene un agujero de 12 − 3 − 3 = 6 mm."],
      ['No troben com posar una forma dins de l\'uneix.|No encuentran cómo poner una forma dentro del une.', "Que toquin la ratlla de punts de dins del bloc uneix («els blocs nous van aquí») abans d'afegir la forma.|Que toquen la raya de puntos de dentro del bloque une («los bloques nuevos van aquí») antes de añadir la forma."]],
    seg: ["Plastilina: rentar-se les mans en acabar i no deixar-ne restes als teclats.|Plastilina: lavarse las manos al acabar y no dejar restos en los teclados.", "Si s'ensenya una impressora 3D, no tocar el capçal ni la placa calenta.|Si se enseña una impresora 3D, no tocar el cabezal ni la placa caliente."],
    extra: ["Fer el trofeu amb nanses (anells girats) que s'encavalquin amb la copa.|Hacer el trofeo con asas (anillos girados) que se solapen con la copa.", "Dissenyar una medalla amb el número de la classe fet amb cubs prims en relleu.|Diseñar una medalla con el número de la clase hecho con cubos finos en relieve.", "Escriure un programa amb un error d'unió (un buit) perquè un company el trobi.|Escribir un programa con un error de unión (un hueco) para que un compañero lo encuentre."],
    trans: ['Sessió següent: la diferència (resta) per fer forats i buidats.|Sesión siguiente: la diferencia (resta) para hacer agujeros y vaciados.', 'Matemàtiques: conjunts i diagrames de Venn (unió).|Matemáticas: conjuntos y diagramas de Venn (unión).'],
    slides: [
      { id: 's1', k: 'portada', t: 'Unió: una sola peça|Unión: una sola pieza', x: 'Operacions booleanes · trofeus i medalles per al concurs de problemes|Operaciones booleanas · trofeos y medallas para el concurso de problemas', nota: "Presenta l'encàrrec de l'institut: avui, trofeus i medalles que surtin d'una sola peça.|Presenta el encargo del instituto: hoy, trofeos y medallas que salgan de una sola pieza." },
      { id: 's2', k: 'pregunta', t: 'Tres formes, una peça?|Tres formas, ¿una pieza?', x: "Un trofeu té base, columna i copa. Què ha de passar perquè la impressora en faci una sola peça?|Un trofeo tiene base, columna y copa. ¿Qué tiene que pasar para que la impresora haga una sola pieza?", nota: 'Recull idees («que es toquin», «enganxar-les»). Hi tornarem amb la plastilina.|Recoge ideas («que se toquen», «pegarlas»). Volveremos a ello con la plastilina.' },
      { id: 's3', k: 'repas', t: 'Recordem|Recordamos', punts: ["gira(…) gira al voltant de l'origen.|gira(…) gira alrededor del origen.", 'mou(…) { … } mou tot el bloc.|mueve(…) { … } mueve todo el bloque.', 'Cilindre i con: base a z = 0.|Cilindro y cono: base en z = 0.'], nota: 'Pregunta ràpida: on queda un cilindre(10, 30) després de mou(0, 0, 5)?|Pregunta rápida: ¿dónde queda un cilindro(10, 30) después de mueve(0, 0, 5)?' },
      { id: 's4', k: 'anim', t: 'Tres maneres de combinar formes|Tres maneras de combinar formas', anim: 'p3bool', x: 'uneix, resta i interseca|une, resta e interseca', nota: "Avui només la primera. Pregunta si coneixen els diagrames de Venn de mates: és la mateixa idea.|Hoy solo la primera. Pregunta si conocen los diagramas de Venn de mates: es la misma idea." },
      { id: 's5', k: 'media', t: 'uneix { }: el trofeu|une { }: el trofeo', media: { k: 'model', prog: TROFEU }, nota: "Llegiu els números: la base acaba a 6 i la columna comença a 5; la columna acaba a 35 i la copa comença a 34.|Leed los números: la base acaba en 6 y la columna empieza en 5; la columna acaba en 35 y la copa empieza en 34." },
      { id: 's6', k: 'anim', t: "S'han d'encavalcar|Tienen que solaparse", anim: 'p3overlap', nota: 'Un buit fa dues peces; un sol punt, una peça fràgil; encavalcar, una peça forta.|Un hueco hace dos piezas; un solo punto, una pieza frágil; solapar, una pieza fuerte.' },
      { id: 's7', k: 'media', t: 'Un sol objecte|Un solo objeto', media: { k: 'model', prog: CREU }, nota: 'Un sol gira i un sol color per a les dues barres.|Un solo gira y un solo color para las dos barras.' },
      { id: 's8', k: 'concepte', t: "Abans d'imprimir|Antes de imprimir", x: "El fitxer STL descriu la pell de fora de l'objecte. La unió la calcula: sense parets amagades ni trossos solts.|El archivo STL describe la piel de fuera del objeto. La unión la calcula: sin paredes escondidas ni trozos sueltos.", code: CE(PODI), nota: 'El podi: tres graons que es toquen cara a cara, una sola peça.|El podio: tres escalones que se tocan cara a cara, una sola pieza.' },
      { id: 's9', k: 'activitat', t: 'Unir amb plastilina|Unir con plastilina', timer: 8, punts: ['Columna i bola, només tocant-se: aixequeu.|Columna y bola, solo tocándose: levantad.', 'Ara encavalcades: torneu a aixecar.|Ahora solapadas: volved a levantar.', 'Talleu i dibuixeu les dues versions de costat.|Cortad y dibujad las dos versiones de lado.'], nota: 'Per parelles. Al final, que ensenyin el tall.|Por parejas. Al final, que enseñen el corte.' },
      { id: 's10', k: 'repte', t: "A l'ordinador|En el ordenador", punts: ["L'escaire: dues plaques en L.|La escuadra: dos placas en L.", "La medalla amb l'anella.|La medalla con la anilla.", 'El podi de tres graons.|El podio de tres escalones.'], nota: "La medalla d'or (amb estrella) és un repte extra.|La medalla de oro (con estrella) es un reto extra." },
      { id: 's11', k: 'media', t: 'On és el buit?|¿Dónde está el hueco?', media: { k: 'model', prog: TROFEU_MAL, target: TROFEU }, nota: 'La copa comença a z = 40 i la columna acaba a 35: hi ha un buit de 5 mm.|La copa empieza en z = 40 y la columna acaba en 35: hay un hueco de 5 mm.' },
      { id: 's12', k: 'pregunta', t: 'Una peça o dues?|¿Una pieza o dos?', x: 'Llegiu el programa i decidiu-ho abans d\'executar-lo.|Leed el programa y decididlo antes de ejecutarlo.', code: CE(J('uneix {', '  cub(10)', '  mou(12, 0, 0) cub(10)', '}')), nota: 'Dues: hi ha 2 mm de buit. uneix no acosta les formes.|Dos: hay 2 mm de hueco. une no acerca las formas.' },
      { id: 's13', k: 'repte', t: 'El teu trofeu|Tu trofeo', punts: ["Almenys 4 formes dins d'un uneix.|Al menos 4 formas dentro de un une.", 'Una sola peça, sense buits.|Una sola pieza, sin huecos.', 'Toca la placa i fa 80 mm com a molt.|Toca la placa y mide 80 mm como mucho.'], nota: 'Es desa a «Projectes».|Se guarda en «Proyectos».' },
      { id: 's14', k: 'resum', t: 'Avui hem après…|Hoy hemos aprendido…', punts: ['uneix fon les formes en un sol sòlid.|une funde las formas en un solo sólido.', "Les formes s'han d'encavalcar una mica.|Las formas tienen que solaparse un poco.", 'Un mou o un gira davant d\'un uneix mou tot el grup.|Un mueve o un gira delante de un une mueve todo el grupo.'], nota: 'Llegiu-ho junts.|Leedlo juntos.' },
      { id: 's15', k: 'tiquet', t: 'Tiquet de sortida|Ticket de salida', punts: ["Per què s'han d'encavalcar les formes d'una unió?|¿Por qué tienen que solaparse las formas de una unión?", "Escriu una unió d'un cilindre i una esfera d'una sola peça.|Escribe una unión de un cilindro y una esfera de una sola pieza."], nota: 'En un paper, abans de sortir.|En un papel, antes de salir.' }
    ],
    print: [{ id: 'p1', t: 'Fitxa: una peça o més?|Ficha: ¿una pieza o más?', k: 'fitxa', intro: "Llegeix cada unió i escriu quantes peces imprimiria la Nuvi i per què. Recorda: el cub té una cantonada a l'origen; el cilindre, el centre de la base; l'esfera, el centre.|Lee cada unión y escribe cuántas piezas imprimiría la Nuvi y por qué. Recuerda: el cubo tiene una esquina en el origen; el cilindro, el centro de la base; la esfera, el centro.",
      items: [{ q: CE('uneix { cub(20)  mou(20, 0, 0) cub(20) }'), sol: "Una: es toquen per una cara sencera (x = 20).|Una: se tocan por una cara entera (x = 20)." },
        { q: CE('uneix { cub(20)  mou(22, 0, 0) cub(20) }'), sol: 'Dues: entre els cubs hi ha un buit de 2 mm.|Dos: entre los cubos hay un hueco de 2 mm.' },
        { q: CE('uneix { cilindre(10, 30)  mou(0, 0, 30) esfera(10) }'), sol: "Una: l'esfera té el centre al cim de la columna i s'hi enfonsa la meitat.|Una: la esfera tiene el centro en la cima de la columna y se hunde la mitad." },
        { q: CE('uneix { cub(10)  mou(10, 10, 0) cub(10) }'), sol: "Es toquen només per una aresta (la línia x = 10, y = 10): seria molt fràgil. Cal encavalcar-los, per exemple amb mou(9, 9, 0).|Se tocan solo por una arista (la línea x = 10, y = 10): sería muy frágil. Hay que solaparlos, por ejemplo con mueve(9, 9, 0)." }] }]
  },
  /* ---------- Sessió 2 · Diferència: forats i buidats ---------- */
  'p3-2': {
    obj: ["L'alumne/a fa forats, ranures i buidats amb resta.|El alumno/a hace agujeros, ranuras y vaciados con resta.",
      "L'alumne/a explica que a resta la primera forma és la peça i les altres són eines, i que l'ordre canvia el resultat.|El alumno/a explica que en resta la primera forma es la pieza y las demás son herramientas, y que el orden cambia el resultado.",
      "L'alumne/a fa que l'eina sobresurti 1 mm per cada costat perquè el forat travessi de debò.|El alumno/a hace que la herramienta sobresalga 1 mm por cada lado para que el agujero atraviese de verdad.",
      "L'alumne/a calcula les mides d'un buidat a partir del gruix de la paret i del fons.|El alumno/a calcula las medidas de un vaciado a partir del grosor de la pared y del fondo."],
    comp: ['Tecnologia i digitalització: CAD 3D, forats i buidats per a peces funcionals|Tecnología y digitalización: CAD 3D, agujeros y vaciados para piezas funcionales', 'Matemàtiques: diferència de conjunts i càlcul de mides (diàmetre interior = exterior − 2 · paret)|Matemáticas: diferencia de conjuntos y cálculo de medidas (diámetro interior = exterior − 2 · pared)', 'Pensament computacional: l\'ordre de les instruccions i la depuració|Pensamiento computacional: el orden de las instrucciones y la depuración', 'Sostenibilitat: buidar per fer servir menys material|Sostenibilidad: vaciar para usar menos material'],
    vocab: [['Diferència (resta)|Diferencia (resta)', 'Operació que treu a la primera forma tot el que ocupen les altres.|Operación que quita a la primera forma todo lo que ocupan las demás.'], ['Eina|Herramienta', 'Cada forma que resta: talla la peça i desapareix.|Cada forma que resta: corta la pieza y desaparece.'], ['Forat passant|Agujero pasante', 'Forat que travessa la peça de banda a banda.|Agujero que atraviesa la pieza de lado a lado.'], ['Buidat|Vaciado', 'Treure l\'interior d\'una peça deixant parets i fons.|Quitar el interior de una pieza dejando paredes y fondo.'], ['Cares coincidents|Caras coincidentes', "Dues superfícies just al mateix lloc: l'ordinador no sap si hi ha forat o una pell prima.|Dos superficies justo en el mismo sitio: el ordenador no sabe si hay agujero o una piel fina."]],
    mat: { aula: ['Un ordinador per alumne/a amb Numi Tech obert a la sessió «Diferència: forats i buidats»|Un ordenador por alumno/a con Numi Tech abierto en la sesión «Diferencia: agujeros y vaciados»', 'Projector i la presentació de la sessió|Proyector y la presentación de la sesión', 'Plastilina, un tap de beguda i una palla per parella|Plastilina, un tapón de bebida y una pajita por pareja'],
      imprimir: ['Fitxa: del dibuix a la resta (una per alumne/a)|Ficha: del dibujo a la resta (una por alumno/a)'],
      prep: ['Preparar el material de les galetes de plastilina.|Preparar el material de las galletas de plastilina.', "Provar el repte del penjador: s'ha de ficar dues plaques dins d'un uneix amb les fletxes.|Probar el reto del colgador: hay que meter dos placas dentro de un une con las flechas.", "Tenir a mà un objecte buidat de veritat (un got, un porta-llapis) per mesurar-ne la paret.|Tener a mano un objeto vaciado de verdad (un vaso, un portalápices) para medir su pared."] },
    plan: [
      { min: 5, t: 'Treure material|Quitar material', fase: 'inici', fa: "Presenta l'encàrrec: la plantilla de geometria i el porta-llapis. Pregunta com es fa un forat a una peça de fusta (amb una broca) i connecta-ho amb l'eina que resta. Repàs ràpid de la unió.|Presenta el encargo: la plantilla de geometría y el portalápices. Pregunta cómo se hace un agujero en una pieza de madera (con una broca) y conéctalo con la herramienta que resta. Repaso rápido de la unión.",
        diu: ['Si una broca fa un forat, què fa la broca amb el material que treu?|Si una broca hace un agujero, ¿qué hace la broca con el material que quita?'], slides: ['s1', 's2', 's3'], app: 'Encara no: pantalles abaixades.|Todavía no: pantallas bajadas.', org: 'Tot el grup|Todo el grupo' },
      { min: 13, t: 'La peça menys les eines|La pieza menos las herramientas', fase: 'teoria', fa: "Explica resta amb l'animació i la placa amb forat (les eines translúcides). Mostra què passa si s'inverteix l'ordre: queden dos discos prims. Explica la regla d'1 mm per cada costat amb el tall de la placa i calcula junts el porta-llapis: (40 − 36) / 2 = 2 mm de paret. Acaba amb el penjador: uneix dins de resta.|Explica resta con la animación y la placa con agujero (las herramientas translúcidas). Muestra qué pasa si se invierte el orden: quedan dos discos finos. Explica la regla de 1 mm por cada lado con el corte de la placa y calculad juntos el portalápices: (40 − 36) / 2 = 2 mm de pared. Termina con el colgador: une dentro de resta.",
        diu: ['Quina forma és la que es queda?|¿Qué forma es la que se queda?', 'Quant fa la paret del porta-llapis? I el fons?|¿Cuánto mide la pared del portalápices? ¿Y el fondo?'], slides: ['s4', 's5', 's6', 's7', 's8', 's9'], app: "Encara no: tota l'atenció a la projecció.|Todavía no: toda la atención en la proyección.", org: 'Tot el grup|Todo el grupo' },
      { min: 9, t: 'Galetes de plastilina|Galletas de plastilina', fase: 'desconnectat', fa: "Per parelles: una galeta de plastilina i forats amb una palla i un tap; un forat passant i un clot. Escriuen el programa resta { … } de la seva galeta. Posa en comú: quin és el primer element i per què la palla ha de sortir per sota.|Por parejas: una galleta de plastilina y agujeros con una pajita y un tapón; un agujero pasante y un hoyo. Escriben el programa resta { … } de su galleta. Pon en común: cuál es el primer elemento y por qué la pajita tiene que salir por debajo.",
        diu: ['Què diferencia un forat d\'un clot?|¿Qué diferencia un agujero de un hoyo?'], slides: ['s10'], app: 'Encara no: plastilina.|Todavía no: plastilina.', org: 'Per parelles|Por parejas' },
      { min: 20, t: 'Forats, plantilla i porta-llapis|Agujeros, plantilla y portalápices', fase: 'ordinador', fa: "Fan la sessió a l'app: predir el túnel, trobar els dos errors (el forat curt i l'ordre) i els reptes de l'arandela, la plantilla, el porta-llapis i el penjador (el botó és extra). Al penjador, ajuda'ls a ficar les plaques dins de l'uneix amb les fletxes.|Hacen la sesión en la app: predecir el túnel, encontrar los dos errores (el agujero corto y el orden) y los retos de la arandela, la plantilla, el portalápices y el colgador (el botón es extra). En el colgador, ayúdales a meter las placas dentro del une con las flechas.",
        diu: ['Mira-ho amb el botó «Resultat»: travessa?|Míralo con el botón «Resultado»: ¿atraviesa?', 'On comença i on acaba la teva eina?|¿Dónde empieza y dónde acaba tu herramienta?'], slides: ['s11', 's12'], app: 'Sessió «Diferència: forats i buidats», fins a la peça lliure.|Sesión «Diferencia: agujeros y vaciados», hasta la pieza libre.', org: 'Individual|Individual' },
      { min: 8, t: 'Una peça útil amb forats|Una pieza útil con agujeros', fase: 'crea', fa: "Dissenyen una peça per a la classe amb almenys dues eines: una plantilla, un clauer, un porta-goma… Es desa a «Projectes».|Diseñan una pieza para la clase con al menos dos herramientas: una plantilla, un llavero, un portagomas… Se guarda en «Proyectos».",
        diu: ['Per a què servirà la teva peça? On faràs els forats?|¿Para qué servirá tu pieza? ¿Dónde harás los agujeros?'], slides: ['s13'], app: 'Pas «Una peça útil amb forats».|Paso «Una pieza útil con agujeros».', org: 'Individual|Individual' },
      { min: 5, t: 'Tancament|Cierre', fase: 'tancament', fa: 'Repassa les idees clau i el tiquet de sortida.|Repasa las ideas clave y el ticket de salida.', diu: ['Què queda de resta { A B C }?|¿Qué queda de resta { A B C }?'], slides: ['s14', 's15'], app: "Les últimes preguntes i «Com t'ha anat?».|Las últimas preguntas y «¿Cómo te ha ido?».", org: 'Tot el grup|Todo el grupo' }
    ],
    errors: [["Posa l'eina primer i el resultat és un trosset estrany (o res).|Pone la herramienta primero y el resultado es un trocito extraño (o nada).", "Recorda la regla: la primera forma és la que es queda. Que seleccioni la peça i la pugi a dalt de tot del resta amb la fletxa ↑.|Recuerda la regla: la primera forma es la que se queda. Que seleccione la pieza y la suba arriba del todo del resta con la flecha ↑."],
      ["El forat no travessa: l'eina fa la mateixa alçada que la peça o comença a z = 0.|El agujero no atraviesa: la herramienta mide lo mismo que la pieza o empieza en z = 0.", "Que dibuixi el tall de costat: l'eina ha de començar a −1 i fer 2 mm més que el gruix de la peça.|Que dibuje el corte de lado: la herramienta tiene que empezar en −1 y medir 2 mm más que el grosor de la pieza."],
      ['Al buidat, resta només 2 mm al diàmetre i la paret li queda d\'1 mm.|En el vaciado, resta solo 2 mm al diámetro y la pared le queda de 1 mm.', "La paret hi és a tots dos costats: el diàmetre interior és l'exterior menys 2 vegades la paret. Que ho dibuixi des de dalt.|La pared está a los dos lados: el diámetro interior es el exterior menos 2 veces la pared. Que lo dibuje desde arriba."]],
    diff: { mes: "Fer el botó amb quatre forats i, després, una plantilla pròpia amb formes girades (un quadrat girat 45° és un rombe). Calcular quants cm³ de plàstic s'estalvien buidant el porta-llapis (volum del cilindre ple menys el del buit).|Hacer el botón con cuatro agujeros y, después, una plantilla propia con formas giradas (un cuadrado girado 45° es un rombo). Calcular cuántos cm³ de plástico se ahorran vaciando el portalápices (volumen del cilindro lleno menos el del vacío).",
      menys: "Començar per l'arandela i el porta-llapis, que tenen una sola eina. Tenir el patró resta { peça  mou(…, −1) eina } escrit al costat de l'ordinador.|Empezar por la arandela y el portalápices, que tienen una sola herramienta. Tener el patrón resta { pieza  mueve(…, −1) herramienta } escrito al lado del ordenador." },
    aval: { ticket: ['Què queda de resta { A B C }?|¿Qué queda de resta { A B C }?', "Escriu la resta d'una placa de 4 mm amb un forat de 10 mm que la travessi.|Escribe la resta de una placa de 4 mm con un agujero de 10 mm que la atraviese."],
      rubric: [['Ordre de la resta|Orden de la resta', "Posa sempre la peça primer i, si és un grup, l'uneix.|Pone siempre la pieza primero y, si es un grupo, la une.", 'Posa la peça primer, però no veu que un grup necessita uneix.|Pone la pieza primero, pero no ve que un grupo necesita une.'],
        ['Forats passants|Agujeros pasantes', "Fa les eines 1 mm més llargues per cada costat sense que li ho diguin.|Hace las herramientas 1 mm más largas por cada lado sin que se lo digan.", "Fa forats que de vegades no travessen i els arregla provant.|Hace agujeros que a veces no atraviesan y los arregla probando."],
        ['Buidats|Vaciados', "Calcula el diàmetre interior i on comença l'eina a partir de la paret i el fons.|Calcula el diámetro interior y dónde empieza la herramienta a partir de la pared y el fondo.", "Fa el buidat, però s'equivoca amb el gruix de la paret.|Hace el vaciado, pero se equivoca con el grosor de la pared."]] },
    casa: "Mesura amb un regle un got o un porta-llapis de casa: diàmetre de fora, diàmetre de dins i alçada. Quant fa la paret? Escriu la resta { … } que el faria.|Mide con una regla un vaso o un portalápices de casa: diámetro de fuera, diámetro de dentro y altura. ¿Cuánto mide la pared? Escribe la resta { … } que lo haría.",
    intro: "Sessió de la diferència, l'operació booleana més útil en enginyeria: forats per a cargols, ranures, plantilles i recipients. Hi ha tres idees que convé treballar a fons: la primera forma és la peça (i l'ordre importa), l'eina ha de sobresortir 1 mm per cada costat i, si la peça són diverses formes, s'han d'unir dins de la resta. L'activitat amb plastilina fa visible la diferència entre un forat i un clot.|Sesión de la diferencia, la operación booleana más útil en ingeniería: agujeros para tornillos, ranuras, plantillas y recipientes. Hay tres ideas que conviene trabajar a fondo: la primera forma es la pieza (y el orden importa), la herramienta tiene que sobresalir 1 mm por cada lado y, si la pieza son varias formas, hay que unirlas dentro de la resta. La actividad con plastilina hace visible la diferencia entre un agujero y un hoyo.",
    claus: ['resta { } treu a la primera forma tot el que ocupen les altres.|resta { } quita a la primera forma todo lo que ocupan las demás.', "L'ordre importa: la peça va primer; si són diverses formes, dins d'un uneix.|El orden importa: la pieza va primero; si son varias formas, dentro de un une.", "Eina 1 mm més llarga per cada costat: comença a −1 i fa 2 mm més que la peça.|Herramienta 1 mm más larga por cada lado: empieza en −1 y mide 2 mm más que la pieza.", 'Buidat: diàmetre interior = exterior − 2 · paret; l\'eina comença a l\'alçada del fons.|Vaciado: diámetro interior = exterior − 2 · pared; la herramienta empieza a la altura del fondo.'],
    prev: ['Haver fet la sessió «Unió: una sola peça».|Haber hecho la sesión «Unión: una sola pieza».', 'Saber on té el punt de referència cada forma (cub, cilindre, prisma).|Saber dónde tiene el punto de referencia cada forma (cubo, cilindro, prisma).', 'Fer servir coordenades negatives (z = −1).|Usar coordenadas negativas (z = −1).'],
    faq: [["Per què no es veu l'eina en el resultat final?|¿Por qué no se ve la herramienta en el resultado final?", "Perquè l'eina no és part de la peça: només marca on es talla. Mentre es programa, es veu translúcida per saber on és.|Porque la herramienta no es parte de la pieza: solo marca dónde se corta. Mientras se programa, se ve translúcida para saber dónde está."],
      ["Si les cares coincideixen, el forat no hi és?|Si las caras coinciden, ¿el agujero no está?", "De vegades sí i de vegades no: depèn de com arrodoneix els números l'ordinador. Per això els enginyers sempre fan l'eina una mica més llarga: el resultat no depèn de la sort.|A veces sí y a veces no: depende de cómo redondea los números el ordenador. Por eso los ingenieros siempre hacen la herramienta un poco más larga: el resultado no depende de la suerte."],
      ['Es pot restar una forma que no toca la peça?|¿Se puede restar una forma que no toca la pieza?', "Sí, però no fa res: només es treu el que s'encavalca amb la peça.|Sí, pero no hace nada: solo se quita lo que se solapa con la pieza."]],
    tec: [["No veuen el forat al model.|No ven el agujero en el modelo.", "En mode d'edició l'eina es veu translúcida per sobre del forat. Que toquin el botó «Resultat» o girin la càmera.|En modo de edición la herramienta se ve translúcida por encima del agujero. Que toquen el botón «Resultado» o giren la cámara."],
      ['No saben ficar una forma dins d\'un bloc nou.|No saben meter una forma dentro de un bloque nuevo.', "Selecciona la forma i fes servir les fletxes ↑ ↓: quan arriba a un bloc amb claus, hi entra.|Selecciona la forma y usa las flechas ↑ ↓: cuando llega a un bloque con llaves, entra."],
      ['La comprovació de la paret no es posa verda.|La comprobación de la pared no se pone verde.', "La paret és més prima del que demana el repte: que revisi el diàmetre de l'eina (exterior − 2 · paret).|La pared es más fina de lo que pide el reto: que revise el diámetro de la herramienta (exterior − 2 · pared)."]],
    seg: ["Les palles i els taps, de material reutilitzat i nets. La plastilina no es posa a la boca.|Las pajitas y los tapones, de material reutilizado y limpios. La plastilina no se pone en la boca."],
    extra: ['Fer el botó de quatre forats.|Hacer el botón de cuatro agujeros.', "Dissenyar una plantilla amb lletres fetes de cubs prims (la inicial del nom).|Diseñar una plantilla con letras hechas de cubos finos (la inicial del nombre).", "Calcular el plàstic que s'estalvia buidant el porta-llapis.|Calcular el plástico que se ahorra vaciando el portalápices."],
    trans: ['Sessió següent: la intersecció (lents, cúpules i cubs arrodonits).|Sesión siguiente: la intersección (lentes, cúpulas y cubos redondeados).', 'Matemàtiques: diferència de conjunts; volum del cilindre (π · r² · h) per calcular el material estalviat.|Matemáticas: diferencia de conjuntos; volumen del cilindro (π · r² · h) para calcular el material ahorrado.'],
    slides: [
      { id: 's1', k: 'portada', t: 'Diferència: forats i buidats|Diferencia: agujeros y vaciados', x: 'La plantilla de geometria i el porta-llapis|La plantilla de geometría y el portalápices', nota: "Avui treurem material de les peces.|Hoy quitaremos material de las piezas." },
      { id: 's2', k: 'pregunta', t: 'Com es fa un forat?|¿Cómo se hace un agujero?', x: "Amb fusta, fem servir una broca. I en un model 3D fet amb codi?|Con madera, usamos una broca. ¿Y en un modelo 3D hecho con código?", nota: 'Busquem la idea d\'una forma que «s\'emporta» material.|Buscamos la idea de una forma que «se lleva» material.' },
      { id: 's3', k: 'repas', t: 'Recordem la unió|Recordamos la unión', punts: ["uneix fon les formes en una peça.|une funde las formas en una pieza.", "S'han d'encavalcar una mica.|Tienen que solaparse un poco.", 'Un mou davant de l\'uneix mou tot el grup.|Un mueve delante del une mueve todo el grupo.'], nota: 'Pregunta qui ha acabat la medalla d\'or.|Pregunta quién ha terminado la medalla de oro.' },
      { id: 's4', k: 'anim', t: 'La peça menys les eines|La pieza menos las herramientas', anim: 'p3resta', nota: 'La primera forma és la peça; les altres, eines.|La primera forma es la pieza; las demás, herramientas.' },
      { id: 's5', k: 'media', t: 'Les eines es veuen translúcides|Las herramientas se ven translúcidas', media: { k: 'model', prog: QUADRE, mode: 'edit' }, nota: 'Gira el model per veure el cilindre que travessa la placa.|Gira el modelo para ver el cilindro que atraviesa la placa.' },
      { id: 's6', k: 'media', t: "L'ordre importa|El orden importa", media: { k: 'model', prog: QUADRE_INV }, nota: "Les mateixes formes al revés: queda el que sobra del cilindre, dos discos prims.|Las mismas formas al revés: queda lo que sobra del cilindro, dos discos finos." },
      { id: 's7', k: 'anim', t: '+1 mm per cada costat|+1 mm por cada lado', anim: 'p3through', nota: "Cares coincidents: l'ordinador no sap si hi ha forat. Eina més llarga: forat net.|Caras coincidentes: el ordenador no sabe si hay agujero. Herramienta más larga: agujero limpio." },
      { id: 's8', k: 'media', t: 'Buidar: el porta-llapis|Vaciar: el portalápices', media: { k: 'model', prog: GOT }, nota: "Calculeu junts: (40 − 36) / 2 = 2 mm de paret; fons de 2 mm perquè l'eina comença a z = 2.|Calculad juntos: (40 − 36) / 2 = 2 mm de pared; fondo de 2 mm porque la herramienta empieza en z = 2." },
      { id: 's9', k: 'media', t: "Restar d'un grup|Restar de un grupo", media: { k: 'model', prog: PENJ }, nota: "Sense l'uneix, la segona placa faria d'eina. Amb l'uneix, les dues són la peça.|Sin el une, la segunda placa haría de herramienta. Con el une, las dos son la pieza." },
      { id: 's10', k: 'activitat', t: 'Galetes de plastilina|Galletas de plastilina', timer: 7, punts: ['Feu la galeta: és la peça.|Haced la galleta: es la pieza.', 'Un forat passant i un clot.|Un agujero pasante y un hoyo.', 'Escriviu el programa resta { … }.|Escribid el programa resta { … }.'], nota: 'Per parelles.|Por parejas.' },
      { id: 's11', k: 'repte', t: "A l'ordinador|En el ordenador", punts: ["L'arandela i la plantilla de geometria.|La arandela y la plantilla de geometría.", 'El porta-llapis amb paret de 2 mm.|El portalápices con pared de 2 mm.', 'Arregla el penjador.|Arregla el colgador.'], nota: 'El botó de quatre forats és extra.|El botón de cuatro agujeros es extra.' },
      { id: 's12', k: 'media', t: 'Per què no es veu el primer forat?|¿Por qué no se ve el primer agujero?', media: { k: 'model', prog: REGLE_MAL, target: REGLE, view: 'top' }, nota: "El primer cilindre va de −1 a 2 i la placa fa 4 mm: no arriba a dalt.|El primer cilindro va de −1 a 2 y la placa mide 4 mm: no llega arriba." },
      { id: 's13', k: 'repte', t: 'Una peça útil amb forats|Una pieza útil con agujeros', punts: ['Almenys dues eines.|Al menos dos herramientas.', 'Forats que travessen.|Agujeros que atraviesan.', 'Una sola peça sobre la placa.|Una sola pieza sobre la placa.'], nota: 'Es desa a «Projectes».|Se guarda en «Proyectos».' },
      { id: 's14', k: 'resum', t: 'Avui hem après…|Hoy hemos aprendido…', punts: ['resta: la primera forma menys les altres.|resta: la primera forma menos las demás.', "Si la peça són diverses formes, uneix-les dins del resta.|Si la pieza son varias formas, únelas dentro del resta.", "L'eina sobresurt 1 mm per cada costat.|La herramienta sobresale 1 mm por cada lado."], nota: 'Llegiu-ho junts.|Leedlo juntos.' },
      { id: 's15', k: 'tiquet', t: 'Tiquet de sortida|Ticket de salida', punts: ['Què queda de resta { A B C }?|¿Qué queda de resta { A B C }?', 'Escriu una placa de 4 mm amb un forat de 10 mm que la travessi.|Escribe una placa de 4 mm con un agujero de 10 mm que la atraviese.'], nota: 'En un paper, abans de sortir.|En un papel, antes de salir.' }
    ],
    print: [{ id: 'p1', t: 'Fitxa: del dibuix a la resta|Ficha: del dibujo a la resta', k: 'fitxa', intro: "Escriu el programa de cada peça. Recorda: la peça primer, i les eines 1 mm més llargues per cada costat.|Escribe el programa de cada pieza. Recuerda: la pieza primero, y las herramientas 1 mm más largas por cada lado.",
      items: [{ q: "Una placa de 50 × 30 × 5 mm amb un forat de 10 mm al centre que la travessi.|Una placa de 50 × 30 × 5 mm con un agujero de 10 mm en el centro que la atraviese.", sol: CE('resta { cub(50, 30, 5)  mou(25, 15, -1) cilindre(10, 7) }') },
        { q: "Un got de 30 mm de diàmetre i 40 mm d'alt, amb paret i fons de 2 mm.|Un vaso de 30 mm de diámetro y 40 mm de alto, con pared y fondo de 2 mm.", sol: CE('resta { cilindre(30, 40)  mou(0, 0, 2) cilindre(26, 40) }') },
        { q: CE('Què queda de resta { cilindre(20, 10)  cub(30, 30, 30) }?'), sol: "Tres quarts de cilindre: el cub només tapa el quart del cilindre que té x i y positives.|Tres cuartos de cilindro: el cubo solo tapa el cuarto del cilindro que tiene x e y positivas." }] }]
  },
  /* ---------- Sessió 3 · Intersecció: la part comuna ---------- */
  'p3-3': {
    obj: ["L'alumne/a fa servir interseca per quedar-se amb la part comuna de dues formes.|El alumno/a usa interseca para quedarse con la parte común de dos formas.",
      "L'alumne/a crea formes noves (lents, cúpules, eixos en D, cubs arrodonits) combinant primitives.|El alumno/a crea formas nuevas (lentes, cúpulas, ejes en D, cubos redondeados) combinando primitivas.",
      "L'alumne/a distingeix el resultat d'unir, restar i intersecar les mateixes formes.|El alumno/a distingue el resultado de unir, restar e intersecar las mismas formas.",
      "L'alumne/a relaciona la intersecció amb les vistes (siluetes) d'un objecte.|El alumno/a relaciona la intersección con las vistas (siluetas) de un objeto."],
    comp: ['Tecnologia i digitalització: CAD 3D i formes funcionals (eixos, cúpules)|Tecnología y digitalización: CAD 3D y formas funcionales (ejes, cúpulas)', 'Matemàtiques: intersecció de conjunts, cossos geomètrics, vistes i la diagonal del cub (√3)|Matemáticas: intersección de conjuntos, cuerpos geométricos, vistas y la diagonal del cubo (√3)', 'Pensament computacional: descompondre una forma nova en primitives i operacions|Pensamiento computacional: descomponer una forma nueva en primitivas y operaciones', 'Visió espacial: imaginar un objecte a partir de dues ombres|Visión espacial: imaginar un objeto a partir de dos sombras'],
    vocab: [['Intersecció (interseca)|Intersección (interseca)', 'Operació que es queda només amb el que és dins de totes les formes alhora.|Operación que se queda solo con lo que está dentro de todas las formas a la vez.'], ['Part comuna|Parte común', "L'espai que comparteixen dues formes.|El espacio que comparten dos formas."], ['Lent|Lente', 'Peça gruixuda al mig i prima a la vora: dues esferes intersecades.|Pieza gruesa en el centro y fina en el borde: dos esferas intersecadas.'], ['Eix en D|Eje en D', 'Eix amb una cara plana perquè una roda no hi rellisqui.|Eje con una cara plana para que una rueda no resbale.'], ['Silueta (vista)|Silueta (vista)', "L'ombra d'un objecte vist des d'un costat.|La sombra de un objeto visto desde un lado."]],
    mat: { aula: ['Un ordinador per alumne/a amb Numi Tech obert a la sessió «Intersecció: la part comuna»|Un ordenador por alumno/a con Numi Tech abierto en la sesión «Intersección: la parte común»', 'Projector i la presentació de la sessió|Proyector y la presentación de la sesión', 'Per grup de tres: plastilina, les targetes de siluetes i la llanterna d\'un mòbil|Por grupo de tres: plastilina, las tarjetas de siluetas y la linterna de un móvil'],
      imprimir: ['Targetes de siluetes (un paquet per grup)|Tarjetas de siluetas (un paquete por grupo)', 'Fitxa: uneix, resta o interseca? (una per alumne/a)|Ficha: ¿une, resta o interseca? (una por alumno/a)'],
      prep: ['Imprimir i retallar les targetes de siluetes.|Imprimir y recortar las tarjetas de siluetas.', "Comprovar que l'aula es pot enfosquir una mica per a les ombres.|Comprobar que el aula se puede oscurecer un poco para las sombras.", "Provar el repte del cub arrodonit: és la base del projecte de la sessió següent.|Probar el reto del cubo redondeado: es la base del proyecto de la sesión siguiente."] },
    plan: [
      { min: 5, t: 'Formes que no existeixen|Formas que no existen', fase: 'inici', fa: "Planteja el problema: una lent o un cub arrodonit no són a la llista de formes i no surten ni sumant ni restant. Repàs ràpid de resta i uneix.|Plantea el problema: una lente o un cubo redondeado no están en la lista de formas y no salen ni sumando ni restando. Repaso rápido de resta y une.",
        diu: ["Quin objecte fa una ombra quadrada de davant i rodona de dalt?|¿Qué objeto hace una sombra cuadrada de frente y redonda desde arriba?"], slides: ['s1', 's2', 's3'], app: 'Encara no: pantalles abaixades.|Todavía no: pantallas bajadas.', org: 'Tot el grup|Todo el grupo' },
      { min: 12, t: 'La part comuna|La parte común', fase: 'teoria', fa: "Explica interseca amb els diagrames: només el que és dins de totes. Mostra la lent, la cúpula i el cub arrodonit, i calculeu junts els límits de l'esfera (més gran que 20 i més petita que 20 · √3 ≈ 34,6). Acaba amb les dues ombres.|Explica interseca con los diagramas: solo lo que está dentro de todas. Muestra la lente, la cúpula y el cubo redondeado, y calculad juntos los límites de la esfera (más grande que 20 y más pequeña que 20 · √3 ≈ 34,6). Termina con las dos sombras.",
        diu: ["Què passa si l'esfera fa 20 mm? I si en fa 40?|¿Qué pasa si la esfera mide 20 mm? ¿Y si mide 40?"], slides: ['s4', 's5', 's6', 's7', 's8'], app: "Encara no: tota l'atenció a la projecció.|Todavía no: toda la atención en la proyección.", org: 'Tot el grup|Todo el grupo' },
      { min: 10, t: 'Ombres que es creuen|Sombras que se cruzan', fase: 'desconnectat', fa: "Per grups de tres: cada grup agafa targetes de siluetes, modela amb plastilina un objecte que faci les dues ombres i ho comprova amb la llanterna. La targeta de cercle i cercle té dues solucions (esfera i dos cilindres creuats): discutiu-ho.|Por grupos de tres: cada grupo coge tarjetas de siluetas, modela con plastilina un objeto que haga las dos sombras y lo comprueba con la linterna. La tarjeta de círculo y círculo tiene dos soluciones (esfera y dos cilindros cruzados): discutidlo.",
        diu: ['Hi ha més d\'un objecte que faci aquestes dues ombres?|¿Hay más de un objeto que haga estas dos sombras?'], slides: ['s9'], app: 'Encara no: plastilina i llanterna.|Todavía no: plastilina y linterna.', org: 'Grups de tres|Grupos de tres' },
      { min: 20, t: 'Lents, cúpules i eixos|Lentes, cúpulas y ejes', fase: 'ordinador', fa: "Fan la sessió a l'app: predir la part comuna d'un cub i un cilindre, trobar l'error de la cúpula i els reptes de la lent, la cúpula, l'eix en D i el cub arrodonit (la perla és extra). Al cub arrodonit, comproveu que tothom té una esfera entre 20 i 34,6.|Hacen la sesión en la app: predecir la parte común de un cubo y un cilindro, encontrar el error de la cúpula y los retos de la lente, la cúpula, el eje en D y el cubo redondeado (la perla es extra). En el cubo redondeado, comprobad que todo el mundo tiene una esfera entre 20 y 34,6.",
        diu: ['Quina part és dins de totes dues formes?|¿Qué parte está dentro de las dos formas?', 'Mira-ho de costat: la cúpula toca la placa?|Míralo de lado: ¿la cúpula toca la placa?'], slides: ['s10', 's11', 's12'], app: 'Sessió «Intersecció: la part comuna», fins a la forma nova.|Sesión «Intersección: la parte común», hasta la forma nueva.', org: 'Individual|Individual' },
      { min: 8, t: 'Inventa una forma nova|Inventa una forma nueva', fase: 'crea', fa: "Cada alumne/a inventa una forma amb interseca i l'explica al company del costat: quines formes ha intersecat i per què surt així. Es desa a «Projectes».|Cada alumno/a inventa una forma con interseca y la explica al compañero de al lado: qué formas ha intersecado y por qué sale así. Se guarda en «Proyectos».",
        diu: ['Quines dues formes has fet servir? On s\'encavalquen?|¿Qué dos formas has usado? ¿Dónde se solapan?'], slides: ['s13'], app: 'Pas «Inventa una forma nova».|Paso «Inventa una forma nueva».', org: 'Individual i per parelles|Individual y por parejas' },
      { min: 5, t: 'Tancament|Cierre', fase: 'tancament', fa: 'Repassa les idees clau i el tiquet de sortida.|Repasa las ideas clave y el ticket de salida.', diu: ['Què fa interseca? En què es diferencia de resta?|¿Qué hace interseca? ¿En qué se diferencia de resta?'], slides: ['s14', 's15'], app: "Les últimes preguntes i «Com t'ha anat?».|Las últimas preguntas y «¿Cómo te ha ido?».", org: 'Tot el grup|Todo el grupo' }
    ],
    errors: [["Les formes no s'encavalquen i no surt res.|Las formas no se solapan y no sale nada.", "Si no hi ha part comuna, la intersecció és buida. Que miri el model en mode d'edició per veure on és cada forma i les acosti.|Si no hay parte común, la intersección está vacía. Que mire el modelo en modo de edición para ver dónde está cada forma y las acerque."],
      ["A la cúpula, el cub tapa la meitat equivocada.|En la cúpula, el cubo tapa la mitad equivocada.", "Que digui on comença i on acaba el cub en z: ha d'anar de 0 a 20, la meitat de dalt de l'esfera.|Que diga dónde empieza y dónde acaba el cubo en z: tiene que ir de 0 a 20, la mitad de arriba de la esfera."],
      ["Al cub arrodonit, posa un mou a l'esfera i ja no queda centrada.|En el cubo redondeado, pone un mueve a la esfera y ya no queda centrada.", "El cub és centrat i l'esfera també ho és sense mou: els dos centres coincideixen. Només cal un mou davant de l'interseca per pujar-ho tot.|El cubo es centrado y la esfera también lo es sin mueve: los dos centros coinciden. Solo hace falta un mueve delante del interseca para subirlo todo."]],
    diff: { mes: "Fer la perla del collaret (interseca i resta alhora) i un dau arrodonit de 30 mm calculant la mida de l'esfera (entre 30 i 30 · √3). Investigar la intersecció de tres cilindres creuats en x, y i z.|Hacer la perla del collar (interseca y resta a la vez) y un dado redondeado de 30 mm calculando el tamaño de la esfera (entre 30 y 30 · √3). Investigar la intersección de tres cilindros cruzados en x, y y z.",
      menys: "Treballar amb la fitxa i els diagrames de Venn al costat. Fer primer la lent i la cúpula, on només cal afegir una forma.|Trabajar con la ficha y los diagramas de Venn al lado. Hacer primero la lente y la cúpula, donde solo hay que añadir una forma." },
    aval: { ticket: ['Què fa interseca { A B }?|¿Qué hace interseca { A B }?', "Per fer un cub arrodonit de 20 mm, entre quines mides ha d'estar l'esfera?|Para hacer un cubo redondeado de 20 mm, ¿entre qué medidas tiene que estar la esfera?"],
      rubric: [['Part comuna|Parte común', 'Prediu la part comuna de dues formes abans d\'executar.|Predice la parte común de dos formas antes de ejecutar.', 'Fa la intersecció, però no sap predir-ne el resultat.|Hace la intersección, pero no sabe predecir su resultado.'],
        ['Triar operació|Elegir operación', 'Tria uneix, resta o interseca segons la forma que vol obtenir.|Elige une, resta o interseca según la forma que quiere obtener.', 'Prova les tres operacions fins que una funciona.|Prueba las tres operaciones hasta que una funciona.'],
        ['Mides|Medidas', "Calcula on van les formes (la cúpula, la lent) a partir dels radis.|Calcula dónde van las formas (la cúpula, la lente) a partir de los radios.", 'Col·loca les formes provant números.|Coloca las formas probando números.']] },
    casa: "Busca a casa objectes que siguin la part comuna de dues formes: un ganivet de mantega, una pastilla de sabó, una gomaborra… Dibuixa'n les dues ombres (de davant i de dalt).|Busca en casa objetos que sean la parte común de dos formas: un cuchillo de mantequilla, una pastilla de jabón, una goma de borrar… Dibuja sus dos sombras (de frente y desde arriba).",
    intro: "Sessió de la intersecció, la tercera operació booleana. És la menys intuïtiva, però la que permet fer formes que no són a la llista: lents, cúpules de base plana, eixos amb cara plana i cubs arrodonits. Es treballa la relació amb les vistes (un objecte és la intersecció de les seves siluetes allargades), que també surt a la visió espacial i al dibuix tècnic. El cub arrodonit prepara el projecte del dau.|Sesión de la intersección, la tercera operación booleana. Es la menos intuitiva, pero la que permite hacer formas que no están en la lista: lentes, cúpulas de base plana, ejes con cara plana y cubos redondeados. Se trabaja la relación con las vistas (un objeto es la intersección de sus siluetas alargadas), que también sale en la visión espacial y en el dibujo técnico. El cubo redondeado prepara el proyecto del dado.",
    claus: ['interseca { } es queda només amb el que és dins de totes les formes.|interseca { } se queda solo con lo que está dentro de todas las formas.', "A interseca l'ordre no importa; si les formes no s'encavalquen, no en queda res.|En interseca el orden no importa; si las formas no se solapan, no queda nada.", 'Cub arrodonit: esfera centrada més gran que el costat i més petita que la diagonal (costat · √3).|Cubo redondeado: esfera centrada más grande que el lado y más pequeña que la diagonal (lado · √3).', "Un objecte es pot fer intersecant les seves siluetes allargades.|Un objeto se puede hacer intersecando sus siluetas alargadas."],
    prev: ['Haver fet les sessions de la unió i la diferència.|Haber hecho las sesiones de la unión y la diferencia.', "Saber que l'esfera i les formes centrades tenen el centre a l'origen.|Saber que la esfera y las formas centradas tienen el centro en el origen.", 'Conèixer les vistes de davant, de dalt i de costat.|Conocer las vistas de frente, desde arriba y de lado.'],
    faq: [["Per què l'esfera de 20 mm amb un cub de 20 mm fa una esfera?|¿Por qué la esfera de 20 mm con un cubo de 20 mm hace una esfera?", "Perquè l'esfera hi cap sencera dins del cub (toca el centre de cada cara): tota l'esfera és part comuna.|Porque la esfera cabe entera dentro del cubo (toca el centro de cada cara): toda la esfera es parte común."],
      ["D'on surt el 34,6?|¿De dónde sale el 34,6?", "És la diagonal del cub de 20 mm (de cantonada a cantonada passant pel centre): 20 · √3 ≈ 34,6. Una esfera més gran conté tot el cub.|Es la diagonal del cubo de 20 mm (de esquina a esquina pasando por el centro): 20 · √3 ≈ 34,6. Una esfera más grande contiene todo el cubo."],
      ['Els motors tenen de debò eixos en D?|¿Los motores tienen de verdad ejes en D?', "Molts motors petits, servos i potenciòmetres en tenen: la cara plana fa que la roda o el botó giri amb l'eix sense rellisquar.|Muchos motores pequeños, servos y potenciómetros los tienen: la cara plana hace que la rueda o el botón gire con el eje sin resbalar."]],
    tec: [["Després d'intersecar no es veu res.|Después de intersecar no se ve nada.", "Les formes no s'encavalquen. Que comprovi les posicions en mode d'edició (es veuen totes les formes).|Las formas no se solapan. Que compruebe las posiciones en modo de edición (se ven todas las formas)."],
      ["La cúpula surt per sota de la placa.|La cúpula sale por debajo de la placa.", "El cub ha de començar a z = 0, no a −20.|El cubo tiene que empezar en z = 0, no en −20."],
      ["El botó «centrat» no apareix a l'esfera.|El botón «centrado» no aparece en la esfera.", "L'esfera sempre és centrada: no li cal.|La esfera siempre es centrada: no le hace falta."]],
    seg: ['Llanterna del mòbil: no enfocar als ulls dels companys.|Linterna del móvil: no enfocar a los ojos de los compañeros.'],
    extra: ["Fer la perla del collaret (interseca i resta).|Hacer la perla del collar (interseca y resta).", "Intersecar tres cilindres creuats (en x, y i z) i descriure la forma.|Intersecar tres cilindros cruzados (en x, y y z) y describir la forma.", "Dissenyar una peça a partir de dues siluetes inventades i comprovar-la amb les vistes de l'app.|Diseñar una pieza a partir de dos siluetas inventadas y comprobarla con las vistas de la app."],
    trans: ['Sessió següent: projecte del dau (interseca + resta).|Sesión siguiente: proyecto del dado (interseca + resta).', 'Educació visual i plàstica: vistes i dibuix tècnic.|Educación visual y plástica: vistas y dibujo técnico.'],
    slides: [
      { id: 's1', k: 'portada', t: 'Intersecció: la part comuna|Intersección: la parte común', x: 'Lents, cúpules i cubs arrodonits|Lentes, cúpulas y cubos redondeados', nota: 'Formes que no són a la llista.|Formas que no están en la lista.' },
      { id: 's2', k: 'pregunta', t: 'Dues ombres|Dos sombras', x: "Quin objecte fa una ombra quadrada vist de davant i rodona vist de dalt?|¿Qué objeto hace una sombra cuadrada visto de frente y redonda visto desde arriba?", nota: 'Resposta: un cilindre tan alt com ample. Deixa que ho pensin.|Respuesta: un cilindro tan alto como ancho. Deja que lo piensen.' },
      { id: 's3', k: 'repas', t: 'Recordem|Recordamos', punts: ['uneix: tot junt.|une: todo junto.', 'resta: la primera menys les altres.|resta: la primera menos las demás.', "L'eina sobresurt 1 mm.|La herramienta sobresale 1 mm."], nota: 'Pregunta ràpida: què queda si a resta poses l\'eina primer?|Pregunta rápida: ¿qué queda si en resta pones la herramienta primero?' },
      { id: 's4', k: 'anim', t: 'Només la part comuna|Solo la parte común', anim: 'p3inter', nota: "A interseca l'ordre no importa, com en una multiplicació.|En interseca el orden no importa, como en una multiplicación." },
      { id: 's5', k: 'media', t: 'Una lent|Una lente', media: { k: 'model', prog: LENT }, nota: 'Dues esferes de 40 mm: una acaba a z = 12 i l\'altra comença a z = 0.|Dos esferas de 40 mm: una acaba en z = 12 y la otra empieza en z = 0.' },
      { id: 's6', k: 'media', t: 'Una cúpula|Una cúpula', media: { k: 'model', prog: CUPULA }, nota: "El cub només cobreix la meitat de dalt: base plana, fàcil d'imprimir.|El cubo solo cubre la mitad de arriba: base plana, fácil de imprimir." },
      { id: 's7', k: 'media', t: 'El cub arrodonit|El cubo redondeado', media: { k: 'model', prog: DAU0 }, nota: "Esfera entre 20 (el costat) i 34,6 (la diagonal, 20 · √3).|Esfera entre 20 (el lado) y 34,6 (la diagonal, 20 · √3)." },
      { id: 's8', k: 'anim', t: 'Dues ombres, un objecte|Dos sombras, un objeto', anim: 'p3ombra', nota: "Molts programes de CAD fan objectes intersecant perfils.|Muchos programas de CAD hacen objetos intersecando perfiles." },
      { id: 's9', k: 'activitat', t: 'Ombres que es creuen|Sombras que se cruzan', timer: 8, punts: ['Agafeu una targeta de siluetes.|Coged una tarjeta de siluetas.', "Modeleu l'objecte amb plastilina.|Modelad el objeto con plastilina.", 'Comproveu les ombres amb la llanterna.|Comprobad las sombras con la linterna.'], nota: 'Grups de tres. Enfosquiu una mica l\'aula.|Grupos de tres. Oscureced un poco el aula.' },
      { id: 's10', k: 'media', t: 'Uneix, resta o interseca?|¿Une, resta o interseca?', x: "Les mateixes formes, el resultat d'interseca: un quart de disc.|Las mismas formas, el resultado de interseca: un cuarto de disco.", media: { k: 'model', prog: QUART }, nota: "Pregunta abans: què sortiria amb uneix? I amb resta?|Pregunta antes: ¿qué saldría con une? ¿Y con resta?" },
      { id: 's11', k: 'repte', t: "A l'ordinador|En el ordenador", punts: ['La lent i la cúpula.|La lente y la cúpula.', "L'eix en D del motor.|El eje en D del motor.", 'El cub arrodonit per als daus.|El cubo redondeado para los dados.'], nota: 'La perla és un repte extra.|La perla es un reto extra.' },
      { id: 's12', k: 'media', t: 'Dos cilindres creuats|Dos cilindros cruzados', media: { k: 'model', prog: BICIL }, nota: "No és una esfera: té arestes corbes i, vista de dalt, és un quadrat (sòlid de Steinmetz).|No es una esfera: tiene aristas curvas y, vista desde arriba, es un cuadrado (sólido de Steinmetz)." },
      { id: 's13', k: 'repte', t: 'Inventa una forma nova|Inventa una forma nueva', punts: ['Fes servir interseca.|Usa interseca.', 'Una sola peça sobre la placa.|Una sola pieza sobre la placa.', 'Explica-la a un company.|Explícala a un compañero.'], nota: 'Es desa a «Projectes».|Se guarda en «Proyectos».' },
      { id: 's14', k: 'resum', t: 'Avui hem après…|Hoy hemos aprendido…', punts: ['interseca: només la part comuna.|interseca: solo la parte común.', "Formes noves: lents, cúpules, eixos en D, cubs arrodonits.|Formas nuevas: lentes, cúpulas, ejes en D, cubos redondeados.", 'Un objecte és la intersecció de les seves siluetes.|Un objeto es la intersección de sus siluetas.'], nota: 'Llegiu-ho junts.|Leedlo juntos.' },
      { id: 's15', k: 'tiquet', t: 'Tiquet de sortida|Ticket de salida', punts: ['Què fa interseca { A B }?|¿Qué hace interseca { A B }?', "Entre quines mides ha d'estar l'esfera d'un cub arrodonit de 20 mm?|¿Entre qué medidas tiene que estar la esfera de un cubo redondeado de 20 mm?"], nota: 'Oral o en un paper.|Oral o en un papel.' }
    ],
    print: [{ id: 'p1', t: 'Targetes de siluetes|Tarjetas de siluetas', k: 'targetes', intro: "Una targeta per grup cada vegada. Cada targeta diu les dues ombres d'un objecte: modeleu-lo amb plastilina i comproveu-ho amb la llanterna.|Una tarjeta por grupo cada vez. Cada tarjeta dice las dos sombras de un objeto: modeladlo con plastilina y comprobadlo con la linterna.",
      items: [{ t: 'De davant: quadrat · De dalt: cercle|De frente: cuadrado · Desde arriba: círculo', n: 1 }, { t: 'De davant: triangle · De dalt: quadrat|De frente: triángulo · Desde arriba: cuadrado', n: 1 }, { t: 'De davant: cercle · De dalt: cercle|De frente: círculo · Desde arriba: círculo', n: 1 },
        { t: 'De davant: rectangle llarg · De dalt: cercle|De frente: rectángulo largo · Desde arriba: círculo', n: 1 }, { t: 'De davant: quadrat · De dalt: triangle|De frente: cuadrado · Desde arriba: triángulo', n: 1 }, { t: 'De davant: triangle · De dalt: cercle|De frente: triángulo · Desde arriba: círculo', n: 1 }] },
      { id: 'p2', t: 'Fitxa: uneix, resta o interseca?|Ficha: ¿une, resta o interseca?', k: 'fitxa', intro: "Per a cada parella de formes, dibuixa què surt amb cada operació. Les formes són al mateix lloc en tots tres casos.|Para cada pareja de formas, dibuja qué sale con cada operación. Las formas están en el mismo sitio en los tres casos.",
        items: [{ q: "cub(20, 20, 10) i cilindre(40, 10), amb el centre del cilindre a l'origen. Què fa interseca?|cubo(20, 20, 10) y cilindro(40, 10), con el centro del cilindro en el origen. ¿Qué hace interseca?", sol: 'Un quart de disc de 20 mm de radi i 10 mm de gruix.|Un cuarto de disco de 20 mm de radio y 10 mm de grosor.' },
          { q: "Les mateixes formes amb resta { cilindre  cub }.|Las mismas formas con resta { cilindro  cubo }.", sol: "Un disc de 40 mm al qual falta un quart (com un formatge tallat).|Un disco de 40 mm al que le falta un cuarto (como un queso cortado)." },
          { q: "Dues esferes de 30 mm amb els centres a 10 mm l'una de l'altra. Què fa interseca? I uneix?|Dos esferas de 30 mm con los centros a 10 mm una de la otra. ¿Qué hace interseca? ¿Y une?", sol: "Interseca: una lent gruixuda (20 mm de gruix). Uneix: una forma de cacauet de 40 mm de llarg.|Interseca: una lente gruesa (20 mm de grosor). Une: una forma de cacahuete de 40 mm de largo." }] }]
  },
  /* ---------- Sessió 4 · Projecte: el dau ---------- */
  'p3-4': {
    obj: ["L'alumne/a planifica un model complex com un arbre d'operacions (interseca i resta).|El alumno/a planifica un modelo complejo como un árbol de operaciones (interseca y resta).",
      "L'alumne/a calcula les coordenades de cada punt a partir de la cara i de la posició dins de la cara.|El alumno/a calcula las coordenadas de cada punto a partir de la cara y de la posición dentro de la cara.",
      "L'alumne/a comprova que el dau compleix les especificacions: mida, 21 punts, cares oposades que sumen 7, una sola peça.|El alumno/a comprueba que el dado cumple las especificaciones: medida, 21 puntos, caras opuestas que suman 7, una sola pieza.",
      "L'alumne/a relaciona la simetria del dau amb la probabilitat de cada cara.|El alumno/a relaciona la simetría del dado con la probabilidad de cada cara."],
    comp: ['Tecnologia i digitalització: projecte de disseny amb especificacions i verificació|Tecnología y digitalización: proyecto de diseño con especificaciones y verificación', 'Matemàtiques: coordenades en l\'espai, simetria i probabilitat (1/6)|Matemáticas: coordenadas en el espacio, simetría y probabilidad (1/6)', 'Pensament computacional: descomposició (arbre CSG) i patrons repetits|Pensamiento computacional: descomposición (árbol CSG) y patrones repetidos', 'Autonomia: organitzar un projecte en passos i revisar-lo|Autonomía: organizar un proyecto en pasos y revisarlo'],
    vocab: [['Especificació|Especificación', 'Requisit mesurable que ha de complir un producte (mida, forma, ús).|Requisito medible que tiene que cumplir un producto (medida, forma, uso).'], ['Arbre CSG|Árbol CSG', "Dibuix d'un model com a operacions (unió, resta, intersecció) sobre formes.|Dibujo de un modelo como operaciones (unión, resta, intersección) sobre formas."], ['Desenvolupament|Desarrollo', 'Les cares d\'un cos dibuixades planes, per retallar i plegar.|Las caras de un cuerpo dibujadas planas, para recortar y plegar.'], ['Cares oposades|Caras opuestas', "Les dues cares paral·leles d'un cub; en un dau, sumen 7.|Las dos caras paralelas de un cubo; en un dado, suman 7."], ['Dau just|Dado justo', 'Dau on cada cara té la mateixa probabilitat de sortir: 1/6.|Dado donde cada cara tiene la misma probabilidad de salir: 1/6.']],
    mat: { aula: ['Un ordinador per alumne/a amb Numi Tech obert a la sessió «Projecte: el dau»|Un ordenador por alumno/a con Numi Tech abierto en la sesión «Proyecto: el dado»', 'Projector i la presentació de la sessió|Proyector y la presentación de la sesión', 'Cartolina o paper quadriculat, tisores i cola per al desenvolupament del cub|Cartulina o papel cuadriculado, tijeras y pegamento para el desarrollo del cubo', 'Un dau de veritat per grup (per comprovar la regla del 7)|Un dado de verdad por grupo (para comprobar la regla del 7)'],
      imprimir: ['Fitxa: les coordenades dels punts (una per alumne/a)|Ficha: las coordenadas de los puntos (una por alumno/a)', "Fitxa: l'experiment del dau (per a la classe de matemàtiques)|Ficha: el experimento del dado (para la clase de matemáticas)"],
      prep: ["Dibuixar a la pissarra el dau centrat amb els tres eixos i les sis cares (±10).|Dibujar en la pizarra el dado centrado con los tres ejes y las seis caras (±10).", 'Provar el repte del 6: té sis punts i convé fer servir «Duplica».|Probar el reto del 6: tiene seis puntos y conviene usar «Duplica».', "Si teniu impressora, imprimir un dau (20 mm, uns minuts d'impressió) per ensenyar-lo al final.|Si tenéis impresora, imprimir un dado (20 mm, unos minutos de impresión) para enseñarlo al final."] },
    plan: [
      { min: 5, t: "L'encàrrec dels daus|El encargo de los dados", fase: 'inici', fa: "Llegiu la fitxa tècnica de l'encàrrec: 20 mm, cantonades arrodonides, punts de 4 mm i 2 mm de fondària, cares oposades que sumen 7, una sola peça sobre la placa. Repàs del cub arrodonit.|Leed la ficha técnica del encargo: 20 mm, esquinas redondeadas, puntos de 4 mm y 2 mm de profundidad, caras opuestas que suman 7, una sola pieza sobre la placa. Repaso del cubo redondeado.",
        diu: ["Què hi ha a la cara oposada de l'1 en un dau?|¿Qué hay en la cara opuesta del 1 en un dado?"], slides: ['s1', 's2', 's3'], app: 'Encara no: pantalles abaixades.|Todavía no: pantallas bajadas.', org: 'Tot el grup|Todo el grupo' },
      { min: 10, t: 'Planificar el dau|Planificar el dado', fase: 'teoria', fa: "Dibuixeu junts l'arbre del dau (mou → resta → interseca i 21 esferes) i la taula de cares i coordenades (l'1 a dalt, z = 10…). Explica per què treballem centrat i pugem al final. Calculeu un punt de cada tipus: el centre d'una cara i un punt a 5 mm del centre.|Dibujad juntos el árbol del dado (mueve → resta → interseca y 21 esferas) y la tabla de caras y coordenadas (el 1 arriba, z = 10…). Explica por qué trabajamos centrado y subimos al final. Calculad un punto de cada tipo: el centro de una cara y un punto a 5 mm del centro.",
        diu: ['Si un punt és a la cara del davant, quina coordenada és sempre igual?|Si un punto está en la cara de delante, ¿qué coordenada es siempre igual?'], slides: ['s4', 's5', 's6', 's7', 's8'], app: "Encara no: tota l'atenció a la projecció.|Todavía no: toda la atención en la proyección.", org: 'Tot el grup|Todo el grupo' },
      { min: 8, t: 'El desenvolupament del dau|El desarrollo del dado', fase: 'desconnectat', fa: "Cadascú dibuixa els punts al desenvolupament del cub (cares oposades que sumen 7), el retalla i el plega. Després omple la fitxa amb les coordenades dels punts de les cares 1, 2 i 3.|Cada uno dibuja los puntos en el desarrollo del cubo (caras opuestas que suman 7), lo recorta y lo pliega. Después rellena la ficha con las coordenadas de los puntos de las caras 1, 2 y 3.",
        diu: ["Plegat, l'1 queda davant del 6?|Plegado, ¿el 1 queda frente al 6?"], slides: ['s9'], app: 'Encara no: paper i tisores.|Todavía no: papel y tijeras.', org: 'Individual|Individual' },
      { min: 18, t: 'Les cares 1, 2, 3 i 6|Las caras 1, 2, 3 y 6', fase: 'ordinador', fa: "Fan la sessió a l'app: predir la forma del cos segons l'esfera, trobar el punt mal posat i els reptes de l'1, el 2, el 3 i el 6. Cada repte comprova els punts un per un: si un no es posa verd, que comparin les coordenades amb la fitxa.|Hacen la sesión en la app: predecir la forma del cuerpo según la esfera, encontrar el punto mal puesto y los retos del 1, el 2, el 3 y el 6. Cada reto comprueba los puntos uno por uno: si uno no se pone verde, que comparen las coordenadas con la ficha.",
        diu: ['Quina comprovació falta? Quin punt és?|¿Qué comprobación falta? ¿Qué punto es?', 'Fes servir «Duplica» i canvia només el número que cal.|Usa «Duplica» y cambia solo el número que hace falta.'], slides: ['s10', 's11'], app: 'Sessió «Projecte: el dau», fins a «Acaba el dau de la classe».|Sesión «Proyecto: el dado», hasta «Termina el dado de la clase».', org: 'Individual|Individual' },
      { min: 14, t: 'Acaba el dau|Termina el dado', fase: 'crea', fa: "Completen el 5 (darrere, y = 10) i el 4 (esquerra, x = −10) i el personalitzen. Abans de desar, revisen la fitxa tècnica amb el company del costat: 21 punts, cares oposades, una sola peça. Es desa a «Projectes» i es pot descarregar l'STL.|Completan el 5 (detrás, y = 10) y el 4 (izquierda, x = −10) y lo personalizan. Antes de guardar, revisan la ficha técnica con el compañero de al lado: 21 puntos, caras opuestas, una sola pieza. Se guarda en «Proyectos» y se puede descargar el STL.",
        diu: ['Revisa el dau del company: compleix totes les especificacions?|Revisa el dado del compañero: ¿cumple todas las especificaciones?'], slides: ['s12', 's13'], app: 'Pas «Acaba el dau de la classe».|Paso «Termina el dado de la clase».', org: 'Individual i per parelles|Individual y por parejas' },
      { min: 5, t: 'Tancament: un dau just?|Cierre: ¿un dado justo?', fase: 'tancament', fa: "Pregunta si el dau imprès serà just (els forats treuen material) i proposa l'experiment de la fitxa per a la classe de matemàtiques. Tiquet de sortida.|Pregunta si el dado impreso será justo (los agujeros quitan material) y propone el experimento de la ficha para la clase de matemáticas. Ticket de salida.",
        diu: ['Com podríem comprovar si el nostre dau és just?|¿Cómo podríamos comprobar si nuestro dado es justo?'], slides: ['s14', 's15', 's16'], app: "Les últimes preguntes i «Com t'ha anat?».|Las últimas preguntas y «¿Cómo te ha ido?».", org: 'Tot el grup|Todo el grupo' }
    ],
    errors: [["Posa els punts d'una cara amb la coordenada fixa equivocada (y = 10 en lloc de −10).|Pone los puntos de una cara con la coordenada fija equivocada (y = 10 en lugar de −10).", "Que miri el desenvolupament plegat i el dibuix dels eixos: davant és y negativa, darrere y positiva.|Que mire el desarrollo plegado y el dibujo de los ejes: delante es y negativa, detrás y positiva."],
      ['Posa els punts fora del resta (i surten boles enganxades al dau).|Pone los puntos fuera del resta (y salen bolas pegadas al dado).', "Les esferes han de ser dins del bloc resta, després de l'interseca. Si són fora, es dibuixen sòlides.|Las esferas tienen que estar dentro del bloque resta, después del interseca. Si están fuera, se dibujan sólidas."],
      ["Fa servir coordenades del món (z = 20) en lloc de les del dau centrat.|Usa coordenadas del mundo (z = 20) en lugar de las del dado centrado.", "Dins del mou(0, 0, 10), tot es mesura des del centre del dau: la cara de dalt és a z = 10. El mou ja puja tot el conjunt.|Dentro del mueve(0, 0, 10), todo se mide desde el centro del dado: la cara de arriba está en z = 10. El mueve ya sube todo el conjunto."]],
    diff: { mes: "Fer una versió del dau de 30 mm (esfera de 42, punts de 6 mm a 7,5 mm del centre) i pensar quins números canvien i quins no: és la porta d'entrada a les variables de la unitat següent.|Hacer una versión del dado de 30 mm (esfera de 42, puntos de 6 mm a 7,5 mm del centro) y pensar qué números cambian y cuáles no: es la puerta de entrada a las variables de la unidad siguiente.",
      menys: "Treballar amb la fitxa de coordenades ja començada (cares 1 i 2 fetes a la pissarra) i fer servir «Duplica» per a cada punt nou. Al projecte, fer una sola cara més i deixar l'altra per a casa.|Trabajar con la ficha de coordenadas ya empezada (caras 1 y 2 hechas en la pizarra) y usar «Duplica» para cada punto nuevo. En el proyecto, hacer una sola cara más y dejar la otra para casa." },
    aval: { ticket: ['Quantes esferes resten en un dau complet? Per què?|¿Cuántas esferas restan en un dado completo? ¿Por qué?', "Escriu les coordenades dels dos punts del 2 a la cara del davant (y = −10).|Escribe las coordenadas de los dos puntos del 2 en la cara de delante (y = −10)."],
      rubric: [['Planificació|Planificación', "Explica l'arbre del dau i l'ordre de les operacions.|Explica el árbol del dado y el orden de las operaciones.", 'Fa el dau, però no sap explicar per què va en aquest ordre.|Hace el dado, pero no sabe explicar por qué va en este orden.'],
        ['Coordenades|Coordenadas', 'Calcula les coordenades de tots els punts sense provar.|Calcula las coordenadas de todos los puntos sin probar.', 'Encerta les coordenades amb ajuda de la fitxa o provant.|Acierta las coordenadas con ayuda de la ficha o probando.'],
        ['Especificacions|Especificaciones', 'El dau compleix totes les especificacions i ho comprova.|El dado cumple todas las especificaciones y lo comprueba.', "Li falta alguna especificació (una cara, la regla del 7…).|Le falta alguna especificación (una cara, la regla del 7…)."]] },
    casa: "Llança un dau de casa 60 vegades i anota quantes vegades surt cada cara. Surt cada cara unes 10 vegades? Porta els resultats a classe per ajuntar-los amb els dels companys.|Lanza un dado de casa 60 veces y anota cuántas veces sale cada cara. ¿Sale cada cara unas 10 veces? Trae los resultados a clase para juntarlos con los de los compañeros.",
    intro: "Projecte de la unitat: un dau complet que combina interseca (el cos arrodonit) i resta (21 punts). Abans de programar, es planifica: l'arbre d'operacions, la posició de cada cara i les coordenades dels punts. Els reptes construeixen el dau cara a cara amb comprovacions punt per punt; al projecte, l'alumnat l'acaba i el revisa amb un company. Al tancament es connecta amb la probabilitat (un dau just).|Proyecto de la unidad: un dado completo que combina interseca (el cuerpo redondeado) y resta (21 puntos). Antes de programar, se planifica: el árbol de operaciones, la posición de cada cara y las coordenadas de los puntos. Los retos construyen el dado cara a cara con comprobaciones punto por punto; en el proyecto, el alumnado lo termina y lo revisa con un compañero. En el cierre se conecta con la probabilidad (un dado justo).",
    claus: ["El dau és mou(0, 0, 10) d'una resta: la peça és interseca { cub centrat, esfera } i les eines, 21 esferes.|El dado es mueve(0, 0, 10) de una resta: la pieza es interseca { cubo centrado, esfera } y las herramientas, 21 esferas.", "Centrat a l'origen, cada cara és a ±10: dalt z = 10, davant y = −10, dreta x = 10…|Centrado en el origen, cada cara está a ±10: arriba z = 10, delante y = −10, derecha x = 10…", 'Els punts no centrals es posen a 5 mm del centre de la cara; una esfera de 4 mm fa un clot de 2 mm.|Los puntos no centrales se ponen a 5 mm del centro de la cara; una esfera de 4 mm hace un hoyo de 2 mm.', "Cares oposades: 1-6, 2-5, 3-4 (sumen 7).|Caras opuestas: 1-6, 2-5, 3-4 (suman 7)."],
    prev: ['Haver fet les sessions de resta i interseca (el cub arrodonit).|Haber hecho las sesiones de resta e interseca (el cubo redondeado).', 'Coordenades negatives i formes centrades.|Coordenadas negativas y formas centradas.', 'Saber què és un desenvolupament d\'un cub.|Saber qué es un desarrollo de un cubo.'],
    faq: [["Per què els punts són esferes i no cilindres?|¿Por qué los puntos son esferas y no cilindros?", "Es podrien fer amb cilindres, però l'esfera fa un clot arrodonit, sense cantonades, que s'imprimeix bé i s'omple fàcilment de pintura.|Se podrían hacer con cilindros, pero la esfera hace un hoyo redondeado, sin esquinas, que se imprime bien y se rellena fácilmente de pintura."],
      ['Els forats de sota no fan que el dau quedi coix a la placa?|¿Los agujeros de abajo no hacen que el dado quede cojo en la placa?', "No: la cara de sota continua tenint molta superfície plana; els clots només són buits petits. La impressora imprimeix les primeres capes al voltant dels forats.|No: la cara de abajo sigue teniendo mucha superficie plana; los hoyos solo son huecos pequeños. La impresora imprime las primeras capas alrededor de los agujeros."],
      ['Un dau imprès és just?|¿Un dado impreso es justo?', "No ho sabem per endavant: els forats treuen material i les cares no pesen exactament igual. Per això proposem l'experiment: llançar-lo moltes vegades i comparar els resultats amb 1/6.|No lo sabemos de antemano: los agujeros quitan material y las caras no pesan exactamente igual. Por eso proponemos el experimento: lanzarlo muchas veces y comparar los resultados con 1/6."]],
    tec: [["Hi ha massa blocs i no troben on afegir el punt nou.|Hay demasiados bloques y no encuentran dónde añadir el punto nuevo.", "Que seleccionin l'últim punt i toquin «Duplica»: la còpia queda just a sota, dins del resta.|Que seleccionen el último punto y toquen «Duplica»: la copia queda justo debajo, dentro del resta."],
      ["Una comprovació d'un punt no es posa verda.|Una comprobación de un punto no se pone verde.", "Les comprovacions diuen la posició del punt sobre la placa (amb el dau pujat 10 mm): z = 20 vol dir z = 10 dins del dau.|Las comprobaciones dicen la posición del punto sobre la placa (con el dado subido 10 mm): z = 20 quiere decir z = 10 dentro del dado."],
      ["El dau va lent quan té tots els punts.|El dado va lento cuando tiene todos los puntos.", "Són 23 formes amb operacions: és normal que tardi una mica a recalcular. Esperar un segon entre canvis.|Son 23 formas con operaciones: es normal que tarde un poco en recalcular. Esperar un segundo entre cambios."]],
    seg: ['Tisores: retallar sobre la taula i guardar-les en acabar.|Tijeras: recortar sobre la mesa y guardarlas al acabar.'],
    extra: ['Fer el dau de 30 mm i comparar quins números canvien.|Hacer el dado de 30 mm y comparar qué números cambian.', "Fer un dau amb els números fets de palets (cubs prims que resten) en lloc de punts.|Hacer un dado con los números hechos de palitos (cubos finos que restan) en lugar de puntos.", "Dissenyar una caixa per guardar dos daus (amb resta).|Diseñar una caja para guardar dos dados (con resta)."],
    trans: ['Unitat següent: variables i paràmetres (el dau de qualsevol mida).|Unidad siguiente: variables y parámetros (el dado de cualquier tamaño).', 'Matemàtiques: probabilitat, freqüència relativa i experiments aleatoris.|Matemáticas: probabilidad, frecuencia relativa y experimentos aleatorios.'],
    slides: [
      { id: 's1', k: 'portada', t: 'Projecte: el dau|Proyecto: el dado', x: 'Interseca i resta en un sol producte|Interseca y resta en un solo producto', nota: 'Presenta l\'encàrrec dels daus per a la classe de probabilitat.|Presenta el encargo de los dados para la clase de probabilidad.' },
      { id: 's2', k: 'pregunta', t: 'Com és un dau?|¿Cómo es un dado?', x: "Mireu un dau de veritat: què hi ha a la cara oposada de l'1? I del 2?|Mirad un dado de verdad: ¿qué hay en la cara opuesta del 1? ¿Y del 2?", nota: 'Que ho descobreixin amb els daus: les cares oposades sumen 7.|Que lo descubran con los dados: las caras opuestas suman 7.' },
      { id: 's3', k: 'repas', t: 'El cub arrodonit|El cubo redondeado', punts: ['interseca { cub(20, centrat)  esfera(28) }|interseca { cubo(20, centrado)  esfera(28) }', 'Esfera entre 20 i 34,6 mm.|Esfera entre 20 y 34,6 mm.', 'mou(0, 0, 10) el posa a la placa.|mueve(0, 0, 10) lo pone en la placa.'], nota: 'És el cos del dau.|Es el cuerpo del dado.' },
      { id: 's4', k: 'anim', t: 'Les sis cares|Las seis caras', anim: 'p3dau', nota: 'Aquesta és la distribució que farem servir: l\'1 a dalt, el 2 al davant, el 3 a la dreta.|Esta es la distribución que usaremos: el 1 arriba, el 2 delante, el 3 a la derecha.' },
      { id: 's5', k: 'anim', t: "L'arbre del dau|El árbol del dado", anim: 'p3tree', nota: "Dibuixeu-lo a la pissarra: es llegeix de baix a dalt.|Dibujadlo en la pizarra: se lee de abajo arriba." },
      { id: 's6', k: 'media', t: "La cara de l'1|La cara del 1", media: { k: 'model', prog: DAU1 }, nota: "Un punt al centre de la cara de dalt: mou(0, 0, 10) esfera(4).|Un punto en el centro de la cara de arriba: mueve(0, 0, 10) esfera(4)." },
      { id: 's7', k: 'media', t: 'Les cares 1, 2 i 3|Las caras 1, 2 y 3', media: { k: 'model', prog: DAU123 }, nota: "Al davant y = −10; a la dreta x = 10. Els punts, a 5 mm del centre.|Delante y = −10; a la derecha x = 10. Los puntos, a 5 mm del centro." },
      { id: 's8', k: 'concepte', t: 'La fitxa tècnica|La ficha técnica', punts: ['Cub de 20 mm, cantonades arrodonides.|Cubo de 20 mm, esquinas redondeadas.', 'Punts de 4 mm i 2 mm de fondària.|Puntos de 4 mm y 2 mm de profundidad.', 'Cares oposades que sumen 7.|Caras opuestas que suman 7.', 'Una sola peça sobre la placa.|Una sola pieza sobre la placa.'], nota: "Cada especificació es pot comprovar: és el que farà l'app.|Cada especificación se puede comprobar: es lo que hará la app." },
      { id: 's9', k: 'activitat', t: 'El desenvolupament del dau|El desarrollo del dado', timer: 7, punts: ['Dibuixeu els punts (cares oposades = 7).|Dibujad los puntos (caras opuestas = 7).', 'Retalleu i plegueu.|Recortad y plegad.', 'Ompliu les coordenades de la fitxa.|Rellenad las coordenadas de la ficha.'], nota: 'Individual.|Individual.' },
      { id: 's10', k: 'repte', t: "A l'ordinador|En el ordenador", punts: ["L'1 a dalt (z = 10).|El 1 arriba (z = 10).", 'El 2 al davant (y = −10).|El 2 delante (y = −10).', 'El 3 a la dreta (x = 10) i el 6 a sota.|El 3 a la derecha (x = 10) y el 6 abajo.'], nota: 'Fer servir «Duplica» per als punts.|Usar «Duplica» para los puntos.' },
      { id: 's11', k: 'media', t: 'On és el punt equivocat?|¿Dónde está el punto equivocado?', media: { k: 'model', prog: DAU_MAL, target: DAU12 }, nota: 'Un punt del 2 té y = 10: és al darrere.|Un punto del 2 tiene y = 10: está detrás.' },
      { id: 's12', k: 'repte', t: 'Acaba el dau de la classe|Termina el dado de la clase', punts: ['El 5 al darrere (y = 10).|El 5 detrás (y = 10).', "El 4 a l'esquerra (x = −10).|El 4 a la izquierda (x = −10).", 'Revisa la fitxa tècnica amb un company.|Revisa la ficha técnica con un compañero.'], nota: 'Es desa a «Projectes» amb STL.|Se guarda en «Proyectos» con STL.' },
      { id: 's13', k: 'media', t: 'El dau acabat|El dado terminado', media: { k: 'model', prog: DAU_TOT }, nota: 'Gireu-lo: 21 punts, cares oposades que sumen 7.|Giradlo: 21 puntos, caras opuestas que suman 7.' },
      { id: 's14', k: 'concepte', t: 'Un dau just?|¿Un dado justo?', x: "Cada cara hauria de sortir 1 de cada 6 vegades. Però la cara del 6 té més forats que la de l'1… Com ho podem investigar?|Cada cara debería salir 1 de cada 6 veces. Pero la cara del 6 tiene más agujeros que la del 1… ¿Cómo lo podemos investigar?", nota: "Proposa l'experiment de la fitxa per a la classe de mates.|Propón el experimento de la ficha para la clase de mates." },
      { id: 's15', k: 'resum', t: 'Avui hem après…|Hoy hemos aprendido…', punts: ["Planificar amb un arbre d'operacions.|Planificar con un árbol de operaciones.", "Treballar centrat i pujar al final.|Trabajar centrado y subir al final.", 'Comprovar les especificacions una a una.|Comprobar las especificaciones una a una.'], nota: 'Llegiu-ho junts.|Leedlo juntos.' },
      { id: 's16', k: 'tiquet', t: 'Tiquet de sortida|Ticket de salida', punts: ['Quantes esferes resten en un dau complet?|¿Cuántas esferas restan en un dado completo?', 'Coordenades dels dos punts del 2 (y = −10).|Coordenadas de los dos puntos del 2 (y = −10).'], nota: 'En un paper, abans de sortir.|En un papel, antes de salir.' }
    ],
    print: [{ id: 'p1', t: 'Fitxa: les coordenades dels punts|Ficha: las coordenadas de los puntos', k: 'fitxa', intro: "El dau de 20 mm està centrat a l'origen: cada cara és a ±10 mm. Els punts que no són al centre de la cara van a 5 mm del centre. Si no teniu el desenvolupament imprès, dibuixeu-lo en paper quadriculat: sis quadrats de 4 cm en forma de creu.|El dado de 20 mm está centrado en el origen: cada cara está a ±10 mm. Los puntos que no están en el centro de la cara van a 5 mm del centro. Si no tenéis el desarrollo impreso, dibujadlo en papel cuadriculado: seis cuadrados de 4 cm en forma de cruz.",
      items: [{ q: "Cara de l'1 (a dalt). Coordenades del punt:|Cara del 1 (arriba). Coordenadas del punto:", sol: '(0, 0, 10)|(0, 0, 10)' },
        { q: 'Cara del 2 (al davant, y = −10). Coordenades dels dos punts en diagonal:|Cara del 2 (delante, y = −10). Coordenadas de los dos puntos en diagonal:', sol: '(−5, −10, 5) i (5, −10, −5)|(−5, −10, 5) y (5, −10, −5)' },
        { q: 'Cara del 3 (a la dreta, x = 10). Coordenades dels tres punts:|Cara del 3 (a la derecha, x = 10). Coordenadas de los tres puntos:', sol: '(10, −5, −5), (10, 0, 0) i (10, 5, 5)|(10, −5, −5), (10, 0, 0) y (10, 5, 5)' },
        { q: "Quina coordenada tenen igual tots els punts de la cara del 5? Quant val?|¿Qué coordenada tienen igual todos los puntos de la cara del 5? ¿Cuánto vale?", sol: "La y: y = 10 (és la cara del darrere).|La y: y = 10 (es la cara de detrás)." }] },
      { id: 'p2', t: "Fitxa: l'experiment del dau|Ficha: el experimento del dado", k: 'fitxa', intro: "Per parelles, amb un dau imprès o un de normal. Llanceu-lo 60 vegades i feu una marca per a cada resultat.|Por parejas, con un dado impreso o uno normal. Lanzadlo 60 veces y haced una marca por cada resultado.",
        items: [{ q: "Abans de començar: quantes vegades esperes que surti cada cara en 60 llançaments?|Antes de empezar: ¿cuántas veces esperas que salga cada cara en 60 lanzamientos?", sol: "Unes 10 vegades cada una (60 · 1/6), però el resultat real pot variar una mica.|Unas 10 veces cada una (60 · 1/6), pero el resultado real puede variar un poco." },
          { q: "Apunta els resultats: 1 ___ 2 ___ 3 ___ 4 ___ 5 ___ 6 ___|Apunta los resultados: 1 ___ 2 ___ 3 ___ 4 ___ 5 ___ 6 ___", sol: "Resposta oberta. La suma ha de ser 60.|Respuesta abierta. La suma tiene que ser 60." },
          { q: "Ajunteu els resultats de tota la classe. S'acosten més a 1/6 que els vostres?|Juntad los resultados de toda la clase. ¿Se acercan más a 1/6 que los vuestros?", sol: "Normalment sí: com més llançaments, més s'acosta la freqüència relativa a la probabilitat.|Normalmente sí: cuantos más lanzamientos, más se acerca la frecuencia relativa a la probabilidad." }] }]
  }
  };
})());
