/* Tech 3D · Nivell 2 · unitat 3 «Operacions booleanes» (p3-1 … p3-4)
   Contingut propi de Numi. Fil narratiu: l'estudi d'enginyeria del Taller de Bit rep l'encàrrec del departament de
   matemàtiques de l'institut (trofeus i medalles, una plantilla de geometria, un porta-llapis, lents i, al projecte, els
   daus per a la classe de probabilitat). Conceptes: uneix (una sola peça, encavalcar), resta (la primera menys les eines,
   l'ordre, l'eina que sobresurt 1 mm, buidar, restar d'un grup), interseca (la part comuna, cúpules, eixos en D, el cub
   arrodonit) i l'arbre CSG d'un model. Programes en text (paraules en català; l'app els mostra en blocs i en la llengua
   de l'alumne/a: no tenen variables, per això són els mateixos en les dues llengües). */
Object.assign(TBADGE, {
  p3_unio: { id: 'p3_unio', ico: '🏆', n: 'Una sola peça|Una sola pieza', d: "Uneixes formes que s'encavalquen perquè la impressora en faci una sola peça.|Unes formas que se solapan para que la impresora haga una sola pieza." },
  p3_resta: { id: 'p3_resta', ico: '🕳️', n: 'Mestre/a del forat|Maestro/a del agujero', d: "Fas forats, ranures i buidats amb resta, amb eines que travessen de debò.|Haces agujeros, ranuras y vaciados con resta, con herramientas que atraviesan de verdad." },
  p3_inter: { id: 'p3_inter', ico: '🔍', n: 'La part comuna|La parte común', d: "Crees formes noves (lents, cúpules, eixos en D) quedant-te amb la part comuna de dues formes.|Creas formas nuevas (lentes, cúpulas, ejes en D) quedándote con la parte común de dos formas." },
  p3_dau: { id: 'p3_dau', ico: '🎲', n: 'Fabricant de daus|Fabricante de dados', d: "Has dissenyat un dau arrodonit amb els 21 punts buidats combinant interseca i resta.|Has diseñado un dado redondeado con los 21 puntos vaciados combinando interseca y resta." }
});
COURSE_UNITS[3] = (() => {
  const J = (...l) => l.join('\n');
  /* ---------- p3-1 · models ---------- */
  const MURALLA = J('mou(0, 0, 20) {', '  cub(10, 10, 10)', '  mou(20, 0, 0) cub(10, 10, 10)', '}', 'cub(30, 10, 20)');
  const TROFEU = J('uneix {', '  cilindre(30, 6)', '  mou(0, 0, 5) cilindre(10, 30)', '  mou(0, 0, 34) con(10, 16, 28)', '}');
  const CREU = J('color("lila") gira(0, 0, 30) uneix {', '  mou(-20, -4, 0) cub(40, 8, 6)', '  mou(-4, -20, 0) cub(8, 40, 6)', '}');
  const PODI = J('uneix {', '  cub(20, 20, 14)', '  mou(20, 0, 0) cub(20, 20, 20)', '  mou(40, 0, 0) cub(20, 20, 10)', '}');
  const ESCAIRE = J('uneix {', '  cub(40, 20, 5)', '  mou(35, 0, 0) cub(5, 20, 40)', '}');
  const MEDALLA = J('uneix {', '  cilindre(30, 3)', '  mou(0, 19, 0) anell(12, 3)', '}');
  const OR = J('uneix {', '  cilindre(30, 3)', '  mou(0, 0, 2) estrella(20, 3)', '  mou(0, 19, 0) anell(12, 3)', '}');
  const TPRED = J('uneix {', '  cub(30, 10, 10)', '  mou(10, 0, 0) cub(10, 10, 30)', '}');
  /* ---------- p3-2 · models ---------- */
  const CREUP = J('uneix {', '  cub(40, 10, 10)', '  mou(15, -15, 0) cub(10, 40, 10)', '}');
  const QUADRE = J('resta {', '  cub(40, 40, 6)', '  mou(20, 20, -1) cilindre(16, 8)', '}');
  const QUADRE_INV = J('resta {', '  mou(20, 20, -1) cilindre(16, 8)', '  cub(40, 40, 6)', '}');
  const GOT = J('resta {', '  cilindre(40, 60)', '  mou(0, 0, 2) cilindre(36, 60)', '}');
  const PENJ = J('resta {', '  uneix {', '    cub(60, 40, 6)', '    cub(6, 40, 50)', '  }', '  mou(35, 20, -1) cilindre(8, 8)', '  mou(-1, 20, 35) gira(0, 90, 0) cilindre(8, 8)', '}');
  const PENJ_MAL = J('resta {', '  cub(60, 40, 6)', '  cub(6, 40, 50)', '  mou(35, 20, -1) cilindre(8, 8)', '  mou(-1, 20, 35) gira(0, 90, 0) cilindre(8, 8)', '}');
  const TUNEL = J('resta {', '  cub(30, 30, 30)', '  mou(-1, 10, 10) cub(32, 10, 10)', '}');
  const ARAN = J('resta {', '  cilindre(30, 3)', '  mou(0, 0, -1) cilindre(12, 5)', '}');
  const PLANT1 = J('resta {', '  cub(80, 30, 3)', '  mou(15, 15, -1) cilindre(16, 5)', '}');
  const PLANT = J('resta {', '  cub(80, 30, 3)', '  mou(15, 15, -1) cilindre(16, 5)', '  mou(33, 8, -1) cub(14, 14, 5)', '  mou(65, 15, -1) prisma(16, 5)', '}');
  const REGLE = J('resta {', '  cub(60, 20, 4)', '  mou(10, 10, -1) cilindre(6, 6)', '  mou(30, 10, -1) cilindre(6, 6)', '  mou(50, 10, -1) cilindre(6, 6)', '}');
  const BOTO = J('resta {', '  cilindre(30, 4)', '  mou(-4, -4, -1) cilindre(4, 6)', '  mou(4, -4, -1) cilindre(4, 6)', '  mou(-4, 4, -1) cilindre(4, 6)', '  mou(4, 4, -1) cilindre(4, 6)', '}');
  const CLAUER = J('resta {', '  cub(50, 30, 4)', '  mou(30, 15, -1) estrella(18, 6)', '  mou(8, 15, -1) cilindre(6, 6)', '}');
  /* ---------- p3-3 · models ---------- */
  const PLACA_EST = J('resta {', '  cub(40, 40, 4)', '  mou(20, 20, -1) estrella(24, 6)', '}');
  const LENT = J('interseca {', '  mou(0, 0, -8) esfera(40)', '  mou(0, 0, 20) esfera(40)', '}');
  const CUPULA = J('interseca {', '  esfera(40)', '  mou(-20, -20, 0) cub(40, 40, 20)', '}');
  const EIXD = J('interseca {', '  cilindre(10, 20)', '  mou(-5, -5, 0) cub(10, 8, 20)', '}');
  const DAU0 = J('mou(0, 0, 10) interseca {', '  cub(20, centrat)', '  esfera(28)', '}');
  const QUART = J('interseca {', '  cub(20, 20, 10)', '  mou(0, 0, -1) cilindre(40, 12)', '}');
  const BICIL = J('interseca {', '  gira(90, 0, 0) cilindre(30, 40, centrat)', '  gira(0, 90, 0) cilindre(30, 40, centrat)', '}');
  const PERLA = J('resta {', '  interseca {', '    mou(0, 0, -8) esfera(40)', '    mou(0, 0, 20) esfera(40)', '  }', '  mou(0, 0, -1) cilindre(4, 14)', '}');
  /* ---------- p3-4 · el dau (centrat a l'origen; un sol mou el posa sobre la placa) ---------- */
  const COS = ['  interseca {', '    cub(20, centrat)', '    esfera(28)', '  }'];
  const P = (x, y, z) => `  mou(${x}, ${y}, ${z}) esfera(4)`;
  const C1 = [P(0, 0, 10)];
  const C2 = [P(-5, -10, 5), P(5, -10, -5)];
  const C3 = [P(10, -5, -5), P(10, 0, 0), P(10, 5, 5)];
  const C6 = [P(-5, -5, -10), P(-5, 0, -10), P(-5, 5, -10), P(5, -5, -10), P(5, 0, -10), P(5, 5, -10)];
  const C5 = [P(-5, 10, -5), P(5, 10, -5), P(0, 10, 0), P(-5, 10, 5), P(5, 10, 5)];
  const C4 = [P(-10, -5, -5), P(-10, 5, -5), P(-10, -5, 5), P(-10, 5, 5)];
  const DAU = (...faces) => J('mou(0, 0, 10) resta {', ...COS, ...faces.flat(), '}');
  const DAU_COS = DAU(), DAU1 = DAU(C1), DAU12 = DAU(C1, C2), DAU123 = DAU(C1, C2, C3), DAU1236 = DAU(C1, C2, C3, C6), DAU_TOT = DAU(C1, C2, C3, C6, C5, C4);
  const DAU_SPOT = J('mou(0, 0, 10) resta {', ...COS, ...C1, P(-5, -10, 5), '  mou(5, 10, -5)! esfera(4)', '}');
  const RD = (d) => J('interseca {', '  cub(20, centrat)', `  esfera(${d})`, '}');
  // un punt (esfera que resta) a la posició del món (després del mou(0, 0, 10))
  const PT = (x, y, z) => ({ k: 'part', t: 'sph', hole: true, at: [x, y, z + 10], tol: 0.6, txt: `Hi ha un punt a (${x}, ${y}, ${z + 10})|Hay un punto en (${x}, ${y}, ${z + 10})` });
  const NPT = n => ({ k: 'count', t: 'sph', hole: true, min: n, max: n, txt: `Exactament ${n} ${n === 1 ? 'punt' : 'punts'}|Exactamente ${n} ${n === 1 ? 'punto' : 'puntos'}` });
  const GHOST = "S'assembla al fantasma|Se parece al fantasma";
  const ALL = ['cub', 'cil', 'esf', 'con', 'pir', 'tub', 'anell', 'prisma', 'estrella', 'cor', 'mou', 'gira', 'escala', 'color', 'uneix', 'resta', 'interseca'];
  return {
  t: 'Operacions booleanes|Operaciones booleanas', d: 'Unió, diferència i intersecció|Unión, diferencia e intersección', color: '#D63F8C',
  s: [
    /* =============================== Sessió 1 · Unió =============================== */
    { id: 'p3-1', t: 'Unió: una sola peça|Unión: una sola pieza', min: 45, badge: 'p3_unio',
      learn: ["uneix { } fon totes les formes de dins en un sol sòlid: on s'encavalquen, les parets de dins desapareixen.|une { } funde todas las formas de dentro en un solo sólido: donde se solapan, las paredes de dentro desaparecen.",
        "Perquè surti una sola peça, les formes s'han d'encavalcar una mica: un buit (o un sol punt de contacte) fa trossos solts o fràgils.|Para que salga una sola pieza, las formas tienen que solaparse un poco: un hueco (o un solo punto de contacto) hace trozos sueltos o frágiles.",
        'Una unió es comporta com un sol objecte: un mou, un gira o un color posat just davant l\'afecta sencera.|Una unión se comporta como un solo objeto: un mueve, un gira o un color puesto justo delante la afecta entera.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Recordes la unitat passada? Al Nivell 2, <code>gira(0, 0, 90)</code> fa girar la forma al voltant de…|¿Recuerdas la unidad pasada? En el Nivel 2, <code>gira(0, 0, 90)</code> hace girar la forma alrededor de…',
          opts: ["L'origen (0, 0, 0), com a OpenSCAD|El origen (0, 0, 0), como en OpenSCAD", 'El seu propi centre|Su propio centro', 'La cantonada més alta de la forma|La esquina más alta de la forma'], a: 0,
          ex: "Els girs són al voltant de l'origen: per això, si vols girar una peça sobre si mateixa, primer la gires i després la mous.|Los giros son alrededor del origen: por eso, si quieres girar una pieza sobre sí misma, primero la giras y después la mueves." },
        { k: 'm3predict', ph: 'recorda', q: 'Un <code>mou</code> davant d\'unes claus. <b>Quin model fa?</b>|Un <code>mueve</code> delante de unas llaves. <b>¿Qué modelo hace?</b>', prog: MURALLA,
          opts: [{ prog: MURALLA }, { prog: J('mou(0, 0, 20) cub(10, 10, 10)', 'mou(20, 0, 0) cub(10, 10, 10)', 'cub(30, 10, 20)') }, { prog: J('cub(10, 10, 10)', 'mou(20, 0, 0) cub(10, 10, 10)', 'mou(0, 0, 10) cub(30, 10, 20)') }, { prog: J('mou(0, 0, 20) cub(30, 10, 10)', 'cub(30, 10, 20)') }], a: 0,
          ex: "El mou(0, 0, 20) afecta els dos cubs de dins de les claus: tots dos pugen 20 mm i queden a sobre del mur, com els merlets d'una muralla.|El mueve(0, 0, 20) afecta a los dos cubos de dentro de las llaves: los dos suben 20 mm y quedan encima del muro, como las almenas de una muralla." },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: "L'encàrrec de l'institut|El encargo del instituto",
          t: "El departament de matemàtiques de l'institut ens ha fet un encàrrec gran: <b>trofeus</b> i <b>medalles</b> per al concurs de problemes, una <b>plantilla de geometria</b>, <b>lents</b> per a la classe de ciències i <b>daus</b> per estudiar la probabilitat. Per fer-ho tot necessitem combinar formes de tres maneres: unir-les, restar-les i quedar-nos amb la part comuna. Comencem pels trofeus: la Nuvi els ha d'imprimir <b>d'una sola peça</b>!|El departamento de matemáticas del instituto nos ha hecho un encargo grande: <b>trofeos</b> y <b>medallas</b> para el concurso de problemas, una <b>plantilla de geometría</b>, <b>lentes</b> para la clase de ciencias y <b>dados</b> para estudiar la probabilidad. Para hacerlo todo necesitamos combinar formas de tres maneras: unirlas, restarlas y quedarnos con la parte común. Empezamos por los trofeos: ¡la Nuvi los tiene que imprimir <b>de una sola pieza</b>!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Operacions booleanes|Operaciones booleanas', t: 'Tres maneres de combinar formes|Tres maneras de combinar formas', anim: 'p3bool',
            x: "Fins ara les formes només es posaven l'una al costat de l'altra. Amb les <b>operacions booleanes</b> les combinem: <b>uneix</b> (tot junt en una peça), <b>resta</b> (treure'n un tros) i <b>interseca</b> (quedar-se amb la part comuna). Es diuen així pel matemàtic anglès George Boole, que al segle XIX va inventar una àlgebra per a la lògica.|Hasta ahora las formas solo se ponían una al lado de la otra. Con las <b>operaciones booleanas</b> las combinamos: <b>une</b> (todo junto en una pieza), <b>resta</b> (quitar un trozo) e <b>interseca</b> (quedarse con la parte común). Se llaman así por el matemático inglés George Boole, que en el siglo XIX inventó un álgebra para la lógica." },
          { k: 'Unió|Unión', t: 'uneix { }: tot en un sol sòlid|une { }: todo en un solo sólido', media: { k: 'model', prog: TROFEU },
            x: "Totes les formes que hi ha dins de les claus es fonen en <b>un sol sòlid</b>: on s'encavalquen, les parets de dins desapareixen. Aquest trofeu té tres formes (la base, la columna i la copa), però la Nuvi n'imprimirà <b>una sola peça</b>.|Todas las formas que hay dentro de las llaves se funden en <b>un solo sólido</b>: donde se solapan, las paredes de dentro desaparecen. Este trofeo tiene tres formas (la base, la columna y la copa), pero la Nuvi imprimirá <b>una sola pieza</b>.",
            tip: "Fixa't en els números: la columna comença a z = 5 (la base acaba a 6) i la copa a z = 34 (la columna acaba a 35). Cada forma entra 1 mm dins de la de sota.|Fíjate en los números: la columna empieza en z = 5 (la base acaba en 6) y la copa en z = 34 (la columna acaba en 35). Cada forma entra 1 mm dentro de la de abajo." },
          { k: 'Que es toquin de debò|Que se toquen de verdad', t: "S'han d'encavalcar|Tienen que solaparse", anim: 'p3overlap',
            x: "Si entre dues formes hi ha un buit, encara que sigui d'1 mm, en surten <b>dues peces</b>. Si només es toquen per un punt o per una aresta, la unió és tan prima que es trenca. Si es toquen per una cara sencera, es fonen bé; però el més segur és que <b>s'encavalquin</b> una mica.|Si entre dos formas hay un hueco, aunque sea de 1 mm, salen <b>dos piezas</b>. Si solo se tocan por un punto o por una arista, la unión es tan fina que se rompe. Si se tocan por una cara entera, se funden bien; pero lo más seguro es que <b>se solapen</b> un poco." },
          { k: 'Un sol objecte|Un solo objeto', t: 'Moure, girar i pintar el grup sencer|Mover, girar y pintar el grupo entero', media: { k: 'model', prog: CREU },
            x: "Una unió es comporta com <b>un sol objecte</b>: un <code>mou</code>, un <code>gira</code> o un <code>color</code> posat just davant l'afecta sencera. Aquesta creu són dues barres unides; amb un sol <code>gira(0, 0, 30)</code> gira tota alhora i amb un sol <code>color</code> es pinta tota de lila.|Una unión se comporta como <b>un solo objeto</b>: un <code>mueve</code>, un <code>gira</code> o un <code>color</code> puesto justo delante la afecta entera. Esta cruz son dos barras unidas; con un solo <code>gira(0, 0, 30)</code> gira toda a la vez y con un solo <code>color</code> se pinta toda de lila." },
          { k: "Abans d'imprimir|Antes de imprimir", t: 'Una superfície tancada|Una superficie cerrada', media: { k: 'model', prog: PODI },
            x: "Per imprimir, el fitxer STL ha de descriure <b>una sola superfície tancada</b>, la pell de fora de l'objecte, sense parets amagades a dins. La unió calcula just aquesta pell. Per això, abans d'exportar, comprovem que tot el que ha d'anar junt és dins d'un <code>uneix</code> i sense buits: com aquest podi, de tres graons que es toquen cara a cara.|Para imprimir, el archivo STL tiene que describir <b>una sola superficie cerrada</b>, la piel de fuera del objeto, sin paredes escondidas dentro. La unión calcula justo esta piel. Por eso, antes de exportar, comprobamos que todo lo que tiene que ir junto está dentro de un <code>une</code> y sin huecos: como este podio, de tres escalones que se tocan cara a cara." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🧱', title: 'Unir amb plastilina|Unir con plastilina', t: 'Per parelles, amb plastilina de dos colors:|Por parejas, con plastilina de dos colores:',
          steps: ["Feu un cilindre gruixut (la columna) i una bola (la copa). Poseu la bola a sobre, només tocant-la, i aixequeu la figura per la base. Què passa?|Haced un cilindro grueso (la columna) y una bola (la copa). Poned la bola encima, solo tocándola, y levantad la figura por la base. ¿Qué pasa?",
            "Ara apreteu la bola perquè s'enfonsi una mica dins la columna (s'encavalquen). Torneu a aixecar la figura.|Ahora apretad la bola para que se hunda un poco dentro de la columna (se solapan). Volved a levantar la figura.",
            "Talleu la figura pel mig amb un fil: es veu on les dues formes s'han fos? Dibuixeu a la llibreta les dues versions vistes de costat i marqueu la zona que s'encavalca.|Cortad la figura por la mitad con un hilo: ¿se ve dónde las dos formas se han fundido? Dibujad en la libreta las dos versiones vistas de lado y marcad la zona que se solapa."],
          tip: "La unió fa el mateix que la plastilina apretada: on les formes s'encavalquen, es fonen en una sola peça.|La unión hace lo mismo que la plastilina apretada: donde las formas se solapan, se funden en una sola pieza." },
        { k: 'm3predict', ph: 'prova', q: 'Llegeix la unió. <b>Quin model fa?</b>|Lee la unión. <b>¿Qué modelo hace?</b>', prog: TPRED,
          opts: [{ prog: TPRED }, { prog: J('uneix {', '  cub(30, 10, 10)', '  cub(10, 10, 30)', '}') }, { prog: J('uneix {', '  mou(0, 0, 20) cub(30, 10, 10)', '  mou(10, 0, 0) cub(10, 10, 30)', '}') }, { prog: J('uneix {', '  cub(30, 10, 10)', '  mou(10, 0, 15) cub(10, 10, 30)', '}') }], a: 0,
          ex: "uneix no mou res: cada forma es queda on la posa el seu mou. El cub alt comença a x = 10, al mig de la barra: fan una T cap per avall i, com que s'encavalquen, surt una sola peça.|une no mueve nada: cada forma se queda donde la pone su mueve. El cubo alto empieza en x = 10, en medio de la barra: hacen una T al revés y, como se solapan, sale una sola pieza." },
        { k: 'm3spot', ph: 'investiga', q: 'La Nuvi diu que aquest trofeu li surt en <b>dues peces</b>. Toca la instrucció que en té la culpa.|La Nuvi dice que este trofeo le sale en <b>dos piezas</b>. Toca la instrucción que tiene la culpa.',
          prog: J('uneix {', '  cilindre(30, 6)', '  mou(0, 0, 5) cilindre(10, 30)', '  mou(0, 0, 40)! con(10, 16, 28)', '}'), target: TROFEU,
          ex: "La columna va de z = 5 a z = 35, però la copa comença a z = 40: hi ha un buit de 5 mm i la copa quedaria solta. Ha de començar a z = 34, 1 mm dins de la columna.|La columna va de z = 5 a z = 35, pero la copa empieza en z = 40: hay un hueco de 5 mm y la copa quedaría suelta. Tiene que empezar en z = 34, 1 mm dentro de la columna." },
        { k: 'quiz', ph: 'investiga', q: 'Quantes peces imprimirà la Nuvi amb aquest programa?<br><code>uneix { cub(10)  mou(12, 0, 0) cub(10) }</code>|¿Cuántas piezas imprimirá la Nuvi con este programa?<br><code>une { cubo(10)  mueve(12, 0, 0) cubo(10) }</code>',
          opts: ['Dues: entre els cubs hi ha un buit de 2 mm|Dos: entre los cubos hay un hueco de 2 mm', 'Una: uneix les enganxa encara que no es toquin|Una: une las pega aunque no se toquen', 'Cap: el programa té un error|Ninguna: el programa tiene un error'], a: 0,
          ex: "El primer cub acaba a x = 10 i el segon comença a x = 12. uneix no omple els buits: només fon el que s'encavalca.|El primer cubo acaba en x = 10 y el segundo empieza en x = 12. une no rellena los huecos: solo funde lo que se solapa." },
        { k: 'move', ph: 'pausa', title: 'Uneix i separa|Une y separa', secs: 40, t: "Tothom dret. Quan el professor diu <b>«uneix!»</b>, cada parella s'agafa de les mans: ara sou una sola peça. <b>«Buit!»</b>: us deixeu anar i feu un pas enrere. <b>«Gira el grup!»</b>: la parella fa mitja volta sense deixar-se anar. Repetiu-ho tres vegades, cada cop més ràpid!|Todo el mundo de pie. Cuando el profesor dice <b>«¡une!»</b>, cada pareja se coge de las manos: ahora sois una sola pieza. <b>«¡Hueco!»</b>: os soltáis y dais un paso atrás. <b>«¡Gira el grupo!»</b>: la pareja da media vuelta sin soltarse. ¡Repetidlo tres veces, cada vez más rápido!" },
        { k: 'm3code', ph: 'repte', q: "Fes l'<b>escaire</b> del fantasma per a les prestatgeries de l'aula: una placa de 40 × 20 × 5 mm a terra i una de 5 × 20 × 40 mm dreta a l'altre extrem, totes dues dins de l'<b>uneix</b>.|Haz la <b>escuadra</b> del fantasma para las estanterías del aula: una placa de 40 × 20 × 5 mm en el suelo y una de 5 × 20 × 40 mm de pie en el otro extremo, las dos dentro del <b>une</b>.",
          start: J('uneix {', '  cub(40, 20, 5)', '}'), blocks: ['cub', 'mou', 'uneix'], target: ESCAIRE,
          checks: [{ k: 'match', target: ESCAIRE, th: 0.9, t: GHOST }, { k: 'uses', b: 'union' }, { k: 'one' }, { k: 'onplate' }],
          hint: "La placa dreta fa 5 mm de gruix i ha d'acabar a x = 40, com la de terra: comença a x = 40 − 5 = 35. Posa-la dins de l'uneix, sota la primera.|La placa de pie mide 5 mm de grosor y tiene que acabar en x = 40, como la del suelo: empieza en x = 40 − 5 = 35. Ponla dentro del une, debajo de la primera.",
          sol: ESCAIRE },
        { k: 'm3code', ph: 'repte', q: "La <b>medalla</b> del concurs: un disc de 30 mm de diàmetre i 3 mm de gruix i una <b>anella</b> de 12 mm (gruix 3) per passar-hi la cinta. L'anella s'ha d'encavalcar amb la vora del disc, però el seu forat ha de quedar lliure.|La <b>medalla</b> del concurso: un disco de 30 mm de diámetro y 3 mm de grosor y una <b>anilla</b> de 12 mm (grosor 3) para pasar la cinta. La anilla tiene que solaparse con el borde del disco, pero su agujero tiene que quedar libre.",
          start: J('uneix {', '  cilindre(30, 3)', '}'), blocks: ['cil', 'anell', 'mou', 'uneix'], target: MEDALLA,
          checks: [{ k: 'match', target: MEDALLA, th: 0.85, t: GHOST }, { k: 'count', t: 'torus', min: 1, txt: 'Té una anella|Tiene una anilla' }, { k: 'uses', b: 'union' }, { k: 'one' }],
          hint: "El disc té radi 15: la vora és a y = 15. L'anella fa 12 mm (radi 6). Amb el centre a y = 19, el seu tub entra 2 mm dins del disc i el forat queda fora.|El disco tiene radio 15: el borde está en y = 15. La anilla mide 12 mm (radio 6). Con el centro en y = 19, su tubo entra 2 mm dentro del disco y el agujero queda fuera.",
          sol: MEDALLA },
        { k: 'm3code', ph: 'repte', q: "Ara, el <b>podi</b> per a l'entrega de premis: tres graons de 20 × 20 mm de base, l'un al costat de l'altre. El de l'esquerra (segon lloc) fa 14 mm d'alt, el del mig (primer lloc) 20 i el de la dreta (tercer) 10.|Ahora, el <b>podio</b> para la entrega de premios: tres escalones de 20 × 20 mm de base, uno al lado del otro. El de la izquierda (segundo puesto) mide 14 mm de alto, el del medio (primer puesto) 20 y el de la derecha (tercero) 10.",
          start: J('uneix {', '  cub(20, 20, 14)', '}'), blocks: ['cub', 'mou', 'uneix', 'color'], target: PODI,
          checks: [{ k: 'match', target: PODI, th: 0.9, t: GHOST }, { k: 'size', ax: 'x', v: 60 }, { k: 'size', ax: 'z', v: 20 }, { k: 'one' }],
          hint: "Cada graó fa 20 mm d'ample: el del mig comença a x = 20 i el de la dreta, a x = 40. Es toquen cara a cara, i així es fonen en una sola peça.|Cada escalón mide 20 mm de ancho: el del medio empieza en x = 20 y el de la derecha, en x = 40. Se tocan cara a cara, y así se funden en una sola pieza.",
          sol: PODI },
        { k: 'm3code', ph: 'repte', extra: true, q: "Repte extra: la <b>medalla d'or</b>. Afegeix-hi una <b>estrella</b> en relleu de 20 mm que sobresurti 2 mm per sobre del disc i que s'hi fongui.|Reto extra: la <b>medalla de oro</b>. Añádele una <b>estrella</b> en relieve de 20 mm que sobresalga 2 mm por encima del disco y que se funda con él.",
          start: MEDALLA, blocks: ['cil', 'estrella', 'anell', 'mou', 'uneix', 'color'], target: OR,
          checks: [{ k: 'match', target: OR, th: 0.85, t: GHOST }, { k: 'count', t: 'star', min: 1, txt: 'Té una estrella|Tiene una estrella' }, { k: 'size', ax: 'z', v: 5 }, { k: 'one' }],
          hint: "El disc acaba a z = 3. Una estrella de 3 mm d'alt que comenci a z = 2 entra 1 mm al disc i en sobresurt 2: estrella(20, 3) amb mou(0, 0, 2).|El disco acaba en z = 3. Una estrella de 3 mm de alto que empiece en z = 2 entra 1 mm en el disco y sobresale 2: estrella(20, 3) con mueve(0, 0, 2).",
          sol: OR },
        { k: 'm3free', ph: 'crea', q: "<b>El teu trofeu.</b> Dissenya el trofeu del concurs de problemes: parteix del de la Júlia o fes-ne un de nou, amb formes, colors i, si vols, nanses o una estrella. Ha de sortir d'una sola peça!|<b>Tu trofeo.</b> Diseña el trofeo del concurso de problemas: parte del de Júlia o haz uno nuevo, con formas, colores y, si quieres, asas o una estrella. ¡Tiene que salir de una sola pieza!",
          name: 'El meu trofeu|Mi trofeo', start: TROFEU, blocks: ['cub', 'cil', 'esf', 'con', 'anell', 'estrella', 'mou', 'gira', 'color', 'uneix'],
          crit: ["Almenys 4 formes dins d'un uneix|Al menos 4 formas dentro de un une", 'És una sola peça: res no flota ni es toca només per un punt|Es una sola pieza: nada flota ni se toca solo por un punto', "Toca la placa i fa com a molt 80 mm d'alçada|Toca la placa y mide como mucho 80 mm de altura"],
          checks: [{ k: 'count', min: 4 }, { k: 'uses', b: 'union' }, { k: 'one' }, { k: 'onplate' }, { k: 'zmax', v: 80 }],
          sol: J('uneix {', '  cilindre(30, 6)', '  mou(0, 0, 5) cilindre(10, 30)', '  mou(0, 0, 34) con(10, 16, 28)', '  mou(0, 0, 49) esfera(10)', '}') },
        { k: 'quiz', ph: 'tanca', q: "Per què, en una unió, convé que les formes s'encavalquin una mica?|¿Por qué, en una unión, conviene que las formas se solapen un poco?", opts: ['Perquè es fonguin en una sola peça resistent|Para que se fundan en una sola pieza resistente', 'Perquè la impressora vagi més de pressa|Para que la impresora vaya más deprisa', 'Perquè canviïn de color|Para que cambien de color'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Què passa si poses <code>gira(0, 0, 45)</code> just davant d\'un <code>uneix { … }</code>?|¿Qué pasa si pones <code>gira(0, 0, 45)</code> justo delante de un <code>une { … }</code>?', opts: ['Gira tot el grup alhora|Gira todo el grupo a la vez', 'Només gira la primera forma|Solo gira la primera forma', 'Res: una unió no es pot girar|Nada: una unión no se puede girar'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* =============================== Sessió 2 · Diferència =============================== */
    { id: 'p3-2', t: 'Diferència: forats i buidats|Diferencia: agujeros y vaciados', min: 45, badge: 'p3_resta',
      learn: ['resta { } agafa la primera forma (la peça) i li treu totes les altres (les eines): així es fan forats, ranures i buidats.|resta { } toma la primera forma (la pieza) y le quita todas las demás (las herramientas): así se hacen agujeros, ranuras y vaciados.',
        "L'ordre importa: si la peça té diverses formes, s'uneixen primer dins d'un uneix, perquè resta només conserva la primera.|El orden importa: si la pieza tiene varias formas, se unen primero dentro de un une, porque resta solo conserva la primera.",
        "L'eina ha de sobresortir una mica (1 mm per cada costat) perquè el forat travessi de debò i no quedi cap pell prima.|La herramienta tiene que sobresalir un poco (1 mm por cada lado) para que el agujero atraviese de verdad y no quede ninguna piel fina."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "Dins d'un <code>uneix</code>, dues formes queden separades per un buit d'1 mm. Quantes peces en surten?|Dentro de un <code>une</code>, dos formas quedan separadas por un hueco de 1 mm. ¿Cuántas piezas salen?", opts: ['Dues|Dos', 'Una|Una', 'Cap|Ninguna'], a: 0,
          ex: "uneix només fon el que s'encavalca: el buit les deixa separades.|une solo funde lo que se solapa: el hueco las deja separadas." },
        { k: 'm3predict', ph: 'recorda', q: '<b>Quin model fa</b> aquesta unió?|<b>¿Qué modelo hace</b> esta unión?', prog: CREUP,
          opts: [{ prog: CREUP }, { prog: J('uneix {', '  cub(40, 10, 10)', '  mou(15, 0, 0) cub(10, 40, 10)', '}') }, { prog: J('uneix {', '  cub(40, 10, 10)', '  cub(10, 40, 10)', '}') }, { prog: J('uneix {', '  cub(40, 10, 10)', '  mou(15, -15, 10) cub(10, 40, 10)', '}') }], a: 0,
          ex: "La segona barra comença a y = −15 i fa 40 mm: travessa la primera pel mig i en sobresurt 15 mm per cada costat. Fan una creu plana.|La segunda barra empieza en y = −15 y mide 40 mm: atraviesa la primera por el medio y sobresale 15 mm por cada lado. Hacen una cruz plana." },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: 'Treure material|Quitar material',
          t: "Ara el departament de mates vol una <b>plantilla de geometria</b>: una làmina amb forats per dibuixar un cercle, un quadrat i un hexàgon. I la Júlia ha dissenyat un <b>porta-llapis</b> per a cada taula i un penjador per a la paret. Per a tot això cal <b>treure</b> material de les peces. Avui aprendrem la diferència: <b>resta</b>.|Ahora el departamento de mates quiere una <b>plantilla de geometría</b>: una lámina con agujeros para dibujar un círculo, un cuadrado y un hexágono. Y Júlia ha diseñado un <b>portalápices</b> para cada mesa y un colgador para la pared. Para todo esto hay que <b>quitar</b> material de las piezas. Hoy aprenderemos la diferencia: <b>resta</b>." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Diferència|Diferencia', t: 'La peça menys les eines|La pieza menos las herramientas', anim: 'p3resta',
            x: "<code>resta { … }</code> agafa <b>la primera forma</b> de dins de les claus (la peça) i li treu <b>totes les altres</b> (les eines). És com fer forats amb una broca o retallar galetes amb un motlle: l'eina desapareix i deixa el seu buit.|<code>resta { … }</code> toma <b>la primera forma</b> de dentro de las llaves (la pieza) y le quita <b>todas las demás</b> (las herramientas). Es como hacer agujeros con una broca o recortar galletas con un molde: la herramienta desaparece y deja su hueco." },
          { k: 'Les eines es veuen|Las herramientas se ven', t: 'Peça sòlida, eina translúcida|Pieza sólida, herramienta translúcida', media: { k: 'model', prog: QUADRE, mode: 'edit' },
            x: "Mentre programes, l'app dibuixa les eines <b>translúcides</b>, perquè vegis on tallen. Aquí, un cilindre de 16 mm travessa una placa de 6 mm. Amb el botó <b>Resultat</b> dels reptes veuràs la peça acabada, amb el forat.|Mientras programas, la app dibuja las herramientas <b>translúcidas</b>, para que veas dónde cortan. Aquí, un cilindro de 16 mm atraviesa una placa de 6 mm. Con el botón <b>Resultado</b> de los retos verás la pieza acabada, con el agujero." },
          { k: "L'ordre importa|El orden importa", t: 'Primer la peça, després les eines|Primero la pieza, después las herramientas', media: { k: 'model', prog: QUADRE_INV },
            x: "Aquest programa és igual que l'anterior, però amb les formes al revés: ara la «peça» és el cilindre i l'eina, la placa. El resultat és el que sobra del cilindre: dos discos prims, el de dalt i el de baix. A <code>resta</code>, la <b>primera</b> forma sempre és la que es queda.|Este programa es igual que el anterior, pero con las formas al revés: ahora la «pieza» es el cilindro y la herramienta, la placa. El resultado es lo que sobra del cilindro: dos discos finos, el de arriba y el de abajo. En <code>resta</code>, la <b>primera</b> forma siempre es la que se queda." },
          { k: 'Que travessi|Que atraviese', t: '+1 mm per cada costat|+1 mm por cada lado', anim: 'p3through',
            x: "Si l'eina acaba just a la cara de la peça, les dues superfícies coincideixen i l'ordinador no sap si hi ha forat o una pell finíssima: a OpenSCAD es veu una cara que parpelleja. Els enginyers fan l'eina <b>més llarga</b>: comença 1 mm per sota (<code>z = −1</code>) i acaba 1 mm per sobre. Per a una placa de 6 mm, un cilindre de 8 mm d'alt.|Si la herramienta acaba justo en la cara de la pieza, las dos superficies coinciden y el ordenador no sabe si hay agujero o una piel finísima: en OpenSCAD se ve una cara que parpadea. Los ingenieros hacen la herramienta <b>más larga</b>: empieza 1 mm por debajo (<code>z = −1</code>) y acaba 1 mm por encima. Para una placa de 6 mm, un cilindro de 8 mm de alto." },
          { k: 'Buidar|Vaciar', t: 'Paret i fons|Pared y fondo', media: { k: 'model', prog: GOT },
            x: "Per fer un recipient, la peça és un cilindre ple i l'eina, un cilindre <b>més estret</b> que comença una mica més amunt. La paret fa (40 − 36) / 2 = <b>2 mm</b> i el fons, <b>2 mm</b>, perquè l'eina comença a z = 2. Per dalt l'eina sobresurt (arriba a 62) i el got queda obert.|Para hacer un recipiente, la pieza es un cilindro lleno y la herramienta, un cilindro <b>más estrecho</b> que empieza un poco más arriba. La pared mide (40 − 36) / 2 = <b>2 mm</b> y el fondo, <b>2 mm</b>, porque la herramienta empieza en z = 2. Por arriba la herramienta sobresale (llega a 62) y el vaso queda abierto." },
          { k: "Restar d'un grup|Restar de un grupo", t: "uneix dins de resta|une dentro de resta", media: { k: 'model', prog: PENJ },
            x: "Si la peça són diverses formes, primer les unim: <code>resta</code> només conserva la primera, i totes les altres les treu. Amb l'<code>uneix</code>, les dues plaques d'aquest penjador són «la primera forma» i els dos forats per als cargols les travessen.|Si la pieza son varias formas, primero las unimos: <code>resta</code> solo conserva la primera, y todas las demás las quita. Con el <code>une</code>, las dos placas de este colgador son «la primera forma» y los dos agujeros para los tornillos las atraviesan." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🍪', title: 'Galetes de plastilina|Galletas de plastilina', t: 'Per parelles, amb plastilina, un tap i una palla:|Por parejas, con plastilina, un tapón y una pajita:',
          steps: ["Aplaneu una «galeta» de plastilina d'un dit de gruix: és la peça. El tap i la palla són les eines.|Aplanad una «galleta» de plastilina de un dedo de grosor: es la pieza. El tapón y la pajita son las herramientas.",
            "Feu un forat amb la palla fins a baix de tot i un altre que no arribi al fons. Mireu-los per sota: quin és un forat i quin és un clot?|Haced un agujero con la pajita hasta abajo del todo y otro que no llegue al fondo. Miradlos por debajo: ¿cuál es un agujero y cuál es un hoyo?",
            "Escriviu a la llibreta el programa de la vostra galeta: resta { la peça, i les eines amb el seu mou }. Quin és el primer element? Per què?|Escribid en la libreta el programa de vuestra galleta: resta { la pieza, y las herramientas con su mueve }. ¿Cuál es el primer elemento? ¿Por qué?"],
          tip: "Una eina que travessa ha de ser més llarga que el gruix de la peça: per això la palla ha de sortir per sota.|Una herramienta que atraviesa tiene que ser más larga que el grosor de la pieza: por eso la pajita tiene que salir por debajo." },
        { k: 'm3predict', ph: 'prova', q: 'Llegeix la resta. <b>Quin model fa?</b>|Lee la resta. <b>¿Qué modelo hace?</b>', prog: TUNEL,
          opts: [{ prog: TUNEL }, { prog: J('resta {', '  cub(30, 30, 30)', '  mou(-1, 10, 20) cub(32, 10, 11)', '}') }, { prog: J('resta {', '  mou(-1, 10, 10) cub(32, 10, 10)', '  cub(30, 30, 30)', '}') }, { prog: J('uneix {', '  cub(30, 30, 30)', '  mou(-1, 10, 10) cub(32, 10, 10)', '}') }], a: 0,
          ex: "L'eina (32 mm) és més llarga que el cub (30 mm) i en sobresurt 1 mm per cada costat: fa un túnel quadrat que el travessa de banda a banda, a mitja alçada.|La herramienta (32 mm) es más larga que el cubo (30 mm) y sobresale 1 mm por cada lado: hace un túnel cuadrado que lo atraviesa de lado a lado, a media altura." },
        { k: 'm3spot', ph: 'investiga', q: "Aquest regle de la Júlia hauria de tenir <b>tres forats</b> per a les anelles de l'arxivador, però des de dalt només se'n veuen dos. Toca la instrucció que falla.|Esta regla de Júlia tendría que tener <b>tres agujeros</b> para las anillas del archivador, pero desde arriba solo se ven dos. Toca la instrucción que falla.",
          prog: J('resta {', '  cub(60, 20, 4)', '  mou(10, 10, -1) cilindre(6, 3)!', '  mou(30, 10, -1) cilindre(6, 6)', '  mou(50, 10, -1) cilindre(6, 6)', '}'), target: REGLE,
          ex: "Aquest cilindre va de z = −1 a z = 2: no arriba a la cara de dalt (z = 4), i fa un clot per sota en lloc d'un forat. Ha de fer 6 mm d'alt, com els altres: de −1 a 5.|Este cilindro va de z = −1 a z = 2: no llega a la cara de arriba (z = 4), y hace un hoyo por debajo en lugar de un agujero. Tiene que medir 6 mm de alto, como los otros: de −1 a 5." },
        { k: 'm3spot', ph: 'investiga', q: "I aquest porta-llapis ha quedat reduït a un disc prim que flota! Toca la instrucció que està en mal lloc.|¡Y este portalápices ha quedado reducido a un disco fino que flota! Toca la instrucción que está en mal sitio.",
          prog: J('resta {', '  mou(0, 0, 2)! cilindre(36, 60)', '  cilindre(40, 60)', '}'), target: GOT,
          ex: "La primera forma d'un resta és la que es queda. Aquí la primera és l'eina (el cilindre estret), i el resultat és el tros d'eina que sobresurt per dalt. El cilindre de 40 mm ha d'anar primer.|La primera forma de un resta es la que se queda. Aquí la primera es la herramienta (el cilindro estrecho), y el resultado es el trozo de herramienta que sobresale por arriba. El cilindro de 40 mm tiene que ir primero." },
        { k: 'move', ph: 'pausa', title: 'Fes de forat|Haz de agujero', secs: 40, t: "Fes una <b>O</b> amb els braços davant del pit: ets una arandela. Ara el company hi passa la mà pel mig: és l'eina, i ha de sortir per l'altre costat! Canvieu els papers. Al final, feu tots alhora una O ben gran i una de petita (forat gran, forat petit).|Haz una <b>O</b> con los brazos delante del pecho: eres una arandela. Ahora el compañero pasa la mano por el medio: es la herramienta, ¡y tiene que salir por el otro lado! Cambiad los papeles. Al final, haced todos a la vez una O muy grande y una pequeña (agujero grande, agujero pequeño)." },
        { k: 'm3code', ph: 'repte', q: "Fes l'<b>arandela</b>: un disc de 30 mm de diàmetre i 3 mm de gruix amb un forat de 12 mm al centre que el travessi de debò.|Haz la <b>arandela</b>: un disco de 30 mm de diámetro y 3 mm de grosor con un agujero de 12 mm en el centro que lo atraviese de verdad.",
          start: J('resta {', '  cilindre(30, 3)', '}'), blocks: ['cil', 'mou', 'resta'], target: ARAN,
          checks: [{ k: 'match', target: ARAN, th: 0.85, t: GHOST }, { k: 'hole' }, { k: 'uses', b: 'diff' }],
          hint: "Dins del resta, després del disc, posa l'eina: un cilindre de 12 mm de diàmetre que comenci a z = −1 i faci 5 mm d'alt (sobresurt 1 mm per sota i 1 per sobre).|Dentro del resta, después del disco, pon la herramienta: un cilindro de 12 mm de diámetro que empiece en z = −1 y mida 5 mm de alto (sobresale 1 mm por debajo y 1 por encima).",
          sol: ARAN },
        { k: 'm3code', ph: 'repte', q: "La <b>plantilla de geometria</b>: la làmina ja té el forat del cercle. Afegeix-hi el <b>quadrat</b> (14 × 14 mm) i l'<b>hexàgon</b> (prisma de 16 mm), com al fantasma.|La <b>plantilla de geometría</b>: la lámina ya tiene el agujero del círculo. Añádele el <b>cuadrado</b> (14 × 14 mm) y el <b>hexágono</b> (prisma de 16 mm), como en el fantasma.",
          start: PLANT1, blocks: ['cub', 'cil', 'prisma', 'mou', 'resta'], target: PLANT,
          checks: [{ k: 'match', target: PLANT, th: 0.9, t: GHOST }, { k: 'count', hole: true, min: 3, txt: 'Almenys 3 eines que resten|Al menos 3 herramientas que restan' }, { k: 'hole' }, { k: 'one' }],
          hint: "Quadrat: cub(14, 14, 5) amb la cantonada a (33, 8, −1). Hexàgon: prisma(16, 5), que té el centre a l'origen, amb mou(65, 15, −1). Totes dues eines, dins del resta.|Cuadrado: cubo(14, 14, 5) con la esquina en (33, 8, −1). Hexágono: prisma(16, 5), que tiene el centro en el origen, con mueve(65, 15, −1). Las dos herramientas, dentro del resta.",
          sol: PLANT },
        { k: 'm3code', ph: 'repte', q: "El <b>porta-llapis</b>: buida el cilindre de 40 mm per deixar una paret de <b>2 mm</b> i un fons de <b>2 mm</b>. Per dalt ha de quedar obert.|El <b>portalápices</b>: vacía el cilindro de 40 mm para dejar una pared de <b>2 mm</b> y un fondo de <b>2 mm</b>. Por arriba tiene que quedar abierto.",
          start: J('resta {', '  cilindre(40, 60)', '}'), blocks: ['cil', 'mou', 'resta'], target: GOT,
          checks: [{ k: 'match', target: GOT, th: 0.9, t: GHOST }, { k: 'hole' }, { k: 'wall', min: 1.5 }, { k: 'onplate' }],
          hint: "La paret fa 2 mm per cada costat: l'eina fa 40 − 2 − 2 = 36 mm. Per deixar un fons de 2 mm, comença a z = 2; amb 60 mm d'alt, sobresurt per dalt.|La pared mide 2 mm por cada lado: la herramienta mide 40 − 2 − 2 = 36 mm. Para dejar un fondo de 2 mm, empieza en z = 2; con 60 mm de alto, sobresale por arriba.",
          sol: GOT },
        { k: 'm3code', ph: 'repte', q: "El <b>penjador</b> de la Júlia ha sortit mutilat: la placa dreta ha desaparegut i ha deixat un buit a la de terra! Arregla el programa perquè les dues plaques siguin la peça i els dos forats les travessin.|¡El <b>colgador</b> de Júlia ha salido mutilado: la placa de pie ha desaparecido y ha dejado un hueco en la del suelo! Arregla el programa para que las dos placas sean la pieza y los dos agujeros las atraviesen.",
          start: PENJ_MAL, blocks: ['cub', 'cil', 'mou', 'gira', 'uneix', 'resta'], target: PENJ,
          checks: [{ k: 'match', target: PENJ, th: 0.9, t: GHOST }, { k: 'uses', b: 'union' }, { k: 'hole' }, { k: 'one' }],
          hint: "resta només conserva la primera forma: la segona placa fa d'eina. Afegeix un uneix al principi del resta i fica-hi les dues plaques (selecciona-les i fes servir les fletxes ↑ ↓).|resta solo conserva la primera forma: la segunda placa hace de herramienta. Añade un une al principio del resta y mete dentro las dos placas (selecciónalas y usa las flechas ↑ ↓).",
          sol: PENJ },
        { k: 'm3code', ph: 'repte', extra: true, q: "Repte extra: un <b>botó</b> de 30 mm i 4 mm de gruix amb <b>quatre forats</b> de 4 mm, a 4 mm del centre en x i en y (positius i negatius).|Reto extra: un <b>botón</b> de 30 mm y 4 mm de grosor con <b>cuatro agujeros</b> de 4 mm, a 4 mm del centro en x y en y (positivos y negativos).",
          start: J('resta {', '  cilindre(30, 4)', '}'), blocks: ['cil', 'mou', 'resta'], target: BOTO,
          checks: [{ k: 'match', target: BOTO, th: 0.9, t: GHOST }, { k: 'count', hole: true, min: 4, txt: 'Quatre forats|Cuatro agujeros' }, { k: 'hole' }],
          hint: "Els quatre centres són (4, 4), (−4, 4), (−4, −4) i (4, −4). Cada eina: cilindre(4, 6) que comenci a z = −1. Fes-ne una i duplica-la.|Los cuatro centros son (4, 4), (−4, 4), (−4, −4) y (4, −4). Cada herramienta: cilindro(4, 6) que empiece en z = −1. Haz una y duplícala.",
          sol: BOTO },
        { k: 'm3free', ph: 'crea', q: "<b>Una peça útil amb forats.</b> Dissenya alguna cosa per a la classe amb resta: una plantilla de formes, un clauer amb una figura buidada, un porta-goma… Fes servir almenys dues eines.|<b>Una pieza útil con agujeros.</b> Diseña algo para la clase con resta: una plantilla de formas, un llavero con una figura vaciada, un portagomas… Usa al menos dos herramientas.",
          name: 'La meva peça amb forats|Mi pieza con agujeros', blocks: ALL,
          crit: ['Fa servir resta amb almenys dues eines|Usa resta con al menos dos herramientas', "Els forats travessen de debò (eines 1 mm més llargues per cada costat)|Los agujeros atraviesan de verdad (herramientas 1 mm más largas por cada lado)", 'És una sola peça que toca la placa|Es una sola pieza que toca la placa'],
          checks: [{ k: 'uses', b: 'diff' }, { k: 'count', hole: true, min: 2, txt: 'Almenys 2 eines|Al menos 2 herramientas' }, { k: 'hole' }, { k: 'one' }, { k: 'onplate' }], sol: CLAUER },
        { k: 'quiz', ph: 'tanca', q: 'Què queda de <code>resta { A  B  C }</code>?|¿Qué queda de <code>resta { A  B  C }</code>?', opts: ['A, sense els trossos que ocupen B i C|A, sin los trozos que ocupan B y C', 'B i C, sense A|B y C, sin A', 'Només la part comuna de les tres|Solo la parte común de las tres'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: "Per què l'eina d'un forat ha de sobresortir 1 mm per cada costat?|¿Por qué la herramienta de un agujero tiene que sobresalir 1 mm por cada lado?", opts: ['Perquè travessi de debò i no quedi cap pell prima|Para que atraviese de verdad y no quede ninguna piel fina', 'Perquè la peça pesi menys|Para que la pieza pese menos', 'Perquè l\'eina es vegi de color|Para que la herramienta se vea de color'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* =============================== Sessió 3 · Intersecció =============================== */
    { id: 'p3-3', t: 'Intersecció: la part comuna|Intersección: la parte común', min: 45, badge: 'p3_inter',
      learn: ["interseca { } només es queda amb el que és dins de totes les formes alhora: la seva part comuna.|interseca { } solo se queda con lo que está dentro de todas las formas a la vez: su parte común.",
        'Amb interseca surten formes que no tenim com a primitives: lents, cúpules de base plana, eixos en D o cubs arrodonits.|Con interseca salen formas que no tenemos como primitivas: lentes, cúpulas de base plana, ejes en D o cubos redondeados.',
        "A interseca l'ordre no importa (com a la multiplicació); però si les formes no s'encavalquen, no en queda res.|En interseca el orden no importa (como en la multiplicación); pero si las formas no se solapan, no queda nada."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'A <code>resta { … }</code>, quina forma és la que es queda?|En <code>resta { … }</code>, ¿qué forma es la que se queda?', opts: ['La primera; les altres són eines que hi treuen material|La primera; las demás son herramientas que le quitan material', "L'última|La última", 'La més gran|La más grande'], a: 0 },
        { k: 'm3predict', ph: 'recorda', q: "Una placa i una estrella dins d'un resta. <b>Quin model fa?</b>|Una placa y una estrella dentro de un resta. <b>¿Qué modelo hace?</b>", prog: PLACA_EST,
          opts: [{ prog: PLACA_EST }, { prog: J('uneix {', '  cub(40, 40, 4)', '  mou(20, 20, -1) estrella(24, 6)', '}') }, { prog: J('interseca {', '  cub(40, 40, 4)', '  mou(20, 20, -1) estrella(24, 6)', '}') }, { prog: 'cub(40, 40, 4)' }], a: 0,
          ex: "L'estrella és l'eina: travessa la placa (de z = −1 a 5) i hi deixa un forat en forma d'estrella. Fixa't en l'opció de l'estrella sola: avui aprendràs quina operació la fa!|La estrella es la herramienta: atraviesa la placa (de z = −1 a 5) y deja un agujero en forma de estrella. Fíjate en la opción de la estrella sola: ¡hoy aprenderás qué operación la hace!" },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: 'Formes que no existeixen|Formas que no existen',
          t: "La professora de ciències vol <b>lents</b> per explicar com funciona una lupa, i jo vull uns daus amb les cantonades <b>arrodonides</b>, que rodolin bé. Però a la llista de formes no hi ha cap lent ni cap cub arrodonit! No es poden fer sumant ni restant… Necessitem la tercera operació booleana: <b>interseca</b>.|La profesora de ciencias quiere <b>lentes</b> para explicar cómo funciona una lupa, y yo quiero unos dados con las esquinas <b>redondeadas</b>, que rueden bien. ¡Pero en la lista de formas no hay ninguna lente ni ningún cubo redondeado! No se pueden hacer sumando ni restando… Necesitamos la tercera operación booleana: <b>interseca</b>." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Intersecció|Intersección', t: 'Només la part comuna|Solo la parte común', anim: 'p3inter',
            x: "<code>interseca { … }</code> es queda <b>només</b> amb el que és dins de <b>totes</b> les formes alhora. Si un punt és dins d'una forma però fora d'una altra, desapareix. Per això, a interseca l'ordre no importa, com quan multipliques: A ∩ B és el mateix que B ∩ A.|<code>interseca { … }</code> se queda <b>solo</b> con lo que está dentro de <b>todas</b> las formas a la vez. Si un punto está dentro de una forma pero fuera de otra, desaparece. Por eso, en interseca el orden no importa, como cuando multiplicas: A ∩ B es lo mismo que B ∩ A." },
          { k: 'Una lent|Una lente', t: 'Dues esferes que s\'encavalquen|Dos esferas que se solapan', media: { k: 'model', prog: LENT },
            x: "Dues esferes de 40 mm, l'una a sota de l'altra, que s'encavalquen 12 mm. La part que és dins de <b>les dues</b> és una lent, gruixuda al mig i prima a la vora, com la d'una lupa. La primera esfera acaba a z = 12 i la segona comença a z = 0: la lent queda just sobre la placa.|Dos esferas de 40 mm, una debajo de la otra, que se solapan 12 mm. La parte que está dentro de <b>las dos</b> es una lente, gruesa en el centro y fina en el borde, como la de una lupa. La primera esfera acaba en z = 12 y la segunda empieza en z = 0: la lente queda justo sobre la placa." },
          { k: 'Una cúpula|Una cúpula', t: 'Esfera ∩ cub = mitja esfera|Esfera ∩ cubo = media esfera', media: { k: 'model', prog: CUPULA },
            x: "L'esfera de 40 mm té el centre a l'origen. El cub només cobreix la meitat de dalt (de z = 0 a 20), i la part comuna és una <b>cúpula</b> amb la base plana: una forma perfecta per imprimir, perquè s'aguanta sola sobre la placa.|La esfera de 40 mm tiene el centro en el origen. El cubo solo cubre la mitad de arriba (de z = 0 a 20), y la parte común es una <b>cúpula</b> con la base plana: una forma perfecta para imprimir, porque se aguanta sola sobre la placa." },
          { k: 'El cub arrodonit|El cubo redondeado', t: "L'esfera llima les cantonades|La esfera lima las esquinas", media: { k: 'model', prog: DAU0 },
            x: "Un cub centrat de 20 mm i una esfera centrada de 28 mm: l'esfera talla les cantonades i les arestes, i les cares continuen planes. L'esfera ha de ser <b>més gran que el costat</b> (si fa 20 mm, només queda l'esfera) i <b>més petita que la diagonal del cub</b> (20 · √3, uns 34,6 mm; si és més gran, queda el cub sencer).|Un cubo centrado de 20 mm y una esfera centrada de 28 mm: la esfera corta las esquinas y las aristas, y las caras siguen planas. La esfera tiene que ser <b>más grande que el lado</b> (si mide 20 mm, solo queda la esfera) y <b>más pequeña que la diagonal del cubo</b> (20 · √3, unos 34,6 mm; si es más grande, queda el cubo entero).",
            tip: "Un mou davant de l'interseca el posa sobre la placa: el cub centrat va de −10 a 10, i el pugem 10 mm.|Un mueve delante del interseca lo pone sobre la placa: el cubo centrado va de −10 a 10, y lo subimos 10 mm." },
          { k: 'Dues ombres|Dos sombras', t: 'Un objecte amb dues siluetes|Un objeto con dos siluetas', anim: 'p3ombra',
            x: "Interseca permet fer un objecte a partir de les seves <b>vistes</b>: si allargues el quadrat de la vista de davant i el cercle de la vista de dalt, la part comuna és un cilindre, l'objecte que fa aquestes dues ombres. Molts programes de CAD ho fan així: dibuixes els perfils i el programa en calcula la intersecció.|Interseca permite hacer un objeto a partir de sus <b>vistas</b>: si alargas el cuadrado de la vista de frente y el círculo de la vista de arriba, la parte común es un cilindro, el objeto que hace estas dos sombras. Muchos programas de CAD lo hacen así: dibujas los perfiles y el programa calcula la intersección." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🔦', title: 'Ombres que es creuen|Sombras que se cruzan', t: 'Per grups de tres, amb plastilina, les targetes de siluetes i la llanterna d\'un mòbil:|Por grupos de tres, con plastilina, las tarjetas de siluetas y la linterna de un móvil:',
          steps: ["Agafeu una targeta: té dues siluetes, la de davant i la de dalt (per exemple, un quadrat i un cercle).|Coged una tarjeta: tiene dos siluetas, la de frente y la de arriba (por ejemplo, un cuadrado y un círculo).",
            "Modeleu amb plastilina un objecte que faci aquestes dues ombres. Comproveu-ho enfocant-lo amb la llanterna des de davant i des de dalt.|Modelad con plastilina un objeto que haga estas dos sombras. Comprobadlo enfocándolo con la linterna desde delante y desde arriba.",
            "Proveu la targeta del cercle i el cercle: una esfera funciona, però la intersecció de dos cilindres creuats també! Dibuixeu-los i escriviu quines dues formes intersecaríeu a l'app.|Probad la tarjeta del círculo y el círculo: una esfera funciona, ¡pero la intersección de dos cilindros cruzados también! Dibujadlos y escribid qué dos formas intersecaríais en la app."],
          tip: "La intersecció de les dues siluetes allargades és l'objecte més gran que fa totes dues ombres.|La intersección de las dos siluetas alargadas es el objeto más grande que hace las dos sombras." },
        { k: 'm3predict', ph: 'prova', q: "Un cub i un cilindre gran. <b>Què en queda amb interseca?</b>|Un cubo y un cilindro grande. <b>¿Qué queda con interseca?</b>", prog: QUART,
          opts: [{ prog: QUART }, { prog: J('uneix {', '  cub(20, 20, 10)', '  cilindre(40, 10)', '}') }, { prog: J('resta {', '  cilindre(40, 10)', '  mou(0, 0, -1) cub(20, 20, 12)', '}') }, { prog: J('resta {', '  cub(20, 20, 10)', '  mou(0, 0, -1) cilindre(40, 12)', '}') }], a: 0,
          ex: "El cilindre té el centre a l'origen i radi 20; el cub ocupa de 0 a 20 en x i en y. La part comuna és un <b>quart de disc</b>. Les altres opcions són la unió i les dues restes: amb les mateixes formes, cada operació fa una peça diferent.|El cilindro tiene el centro en el origen y radio 20; el cubo ocupa de 0 a 20 en x y en y. La parte común es un <b>cuarto de disco</b>. Las otras opciones son la unión y las dos restas: con las mismas formas, cada operación hace una pieza distinta." },
        { k: 'm3spot', ph: 'investiga', q: "Aquesta cúpula ha sortit <b>cap per avall</b> i per sota de la placa. Toca la instrucció que falla.|Esta cúpula ha salido <b>boca abajo</b> y por debajo de la placa. Toca la instrucción que falla.",
          prog: J('interseca {', '  esfera(40)', '  mou(-20, -20, -20)! cub(40, 40, 20)', '}'), target: CUPULA,
          ex: "El cub cobreix la meitat de baix de l'esfera (de z = −20 a 0), i la part comuna és un bol sota la placa. El cub ha d'anar de z = 0 a 20: mou(−20, −20, 0).|El cubo cubre la mitad de abajo de la esfera (de z = −20 a 0), y la parte común es un cuenco bajo la placa. El cubo tiene que ir de z = 0 a 20: mueve(−20, −20, 0)." },
        { k: 'm3predict', ph: 'investiga', q: "Dos cilindres creuats, l'un en x i l'altre en y. <b>Quina és la seva part comuna?</b>|Dos cilindros cruzados, uno en x y el otro en y. <b>¿Cuál es su parte común?</b>", prog: BICIL,
          opts: [{ prog: BICIL }, { prog: 'esfera(30)' }, { prog: J('uneix {', '  gira(90, 0, 0) cilindre(30, 40, centrat)', '  gira(0, 90, 0) cilindre(30, 40, centrat)', '}') }, { prog: 'gira(90, 0, 0) cilindre(30, 30, centrat)' }], a: 0,
          ex: "Sembla una esfera, però no ho és: té arestes corbes i, vista de dalt, és un quadrat. És el sòlid que fa una ombra rodona de davant i de costat. En geometria se'n diu sòlid de Steinmetz.|Parece una esfera, pero no lo es: tiene aristas curvas y, vista desde arriba, es un cuadrado. Es el sólido que hace una sombra redonda de frente y de lado. En geometría se llama sólido de Steinmetz." },
        { k: 'move', ph: 'pausa', title: 'La intersecció humana|La intersección humana', secs: 40, t: "Aixeca la <b>mà dreta</b> si portes alguna cosa blava. Aixeca la <b>mà esquerra</b> si portes sabates esportives. Qui té <b>les dues mans</b> enlaire és la intersecció: fa un salt! Ara: mà dreta si tens germans, mà esquerra si t'agrada dibuixar. Salta la intersecció!|Levanta la <b>mano derecha</b> si llevas algo azul. Levanta la <b>mano izquierda</b> si llevas zapatillas deportivas. Quien tiene <b>las dos manos</b> en alto es la intersección: ¡da un salto! Ahora: mano derecha si tienes hermanos, mano izquierda si te gusta dibujar. ¡Salta la intersección!" },
        { k: 'm3code', ph: 'repte', q: "Fes la <b>lent</b> per a la classe de ciències: afegeix la segona esfera de 40 mm perquè la part comuna faci <b>12 mm</b> de gruix i toqui la placa.|Haz la <b>lente</b> para la clase de ciencias: añade la segunda esfera de 40 mm para que la parte común mida <b>12 mm</b> de grosor y toque la placa.",
          start: J('interseca {', '  mou(0, 0, -8) esfera(40)', '}'), blocks: ['esf', 'mou', 'interseca'], target: LENT,
          checks: [{ k: 'match', target: LENT, th: 0.85, t: GHOST }, { k: 'uses', b: 'inter' }, { k: 'size', ax: 'z', v: 12 }, { k: 'onplate' }],
          hint: "La primera esfera acaba a z = −8 + 20 = 12. La segona ha de començar a z = 0: amb radi 20, el seu centre va a z = 20.|La primera esfera acaba en z = −8 + 20 = 12. La segunda tiene que empezar en z = 0: con radio 20, su centro va en z = 20.",
          sol: LENT },
        { k: 'm3code', ph: 'repte', q: "Una <b>cúpula</b> de 40 mm per a la maqueta del planetari: queda't amb la meitat de dalt de l'esfera, amb la base plana a la placa.|Una <b>cúpula</b> de 40 mm para la maqueta del planetario: quédate con la mitad de arriba de la esfera, con la base plana en la placa.",
          start: J('interseca {', '  esfera(40)', '}'), blocks: ['cub', 'esf', 'mou', 'interseca'], target: CUPULA,
          checks: [{ k: 'match', target: CUPULA, th: 0.9, t: GHOST }, { k: 'size', ax: 'z', v: 20 }, { k: 'flatbase', min: 800 }, { k: 'onplate' }],
          hint: "Interseca l'esfera amb un cub de 40 × 40 × 20 que cobreixi només la meitat de dalt: la cantonada del cub a (−20, −20, 0).|Interseca la esfera con un cubo de 40 × 40 × 20 que cubra solo la mitad de arriba: la esquina del cubo en (−20, −20, 0).",
          sol: CUPULA },
        { k: 'm3code', ph: 'repte', q: "Molts motors petits tenen l'eix amb una cara plana, en forma de <b>D</b>, perquè la roda no hi rellisqui. Fes un eix de 10 mm de diàmetre i 20 d'alt amb un costat aplanat: que faci <b>8 mm</b> en y.|Muchos motores pequeños tienen el eje con una cara plana, en forma de <b>D</b>, para que la rueda no resbale. Haz un eje de 10 mm de diámetro y 20 de alto con un lado aplanado: que mida <b>8 mm</b> en y.",
          start: J('interseca {', '  cilindre(10, 20)', '}'), blocks: ['cil', 'cub', 'mou', 'interseca'], target: EIXD,
          checks: [{ k: 'match', target: EIXD, th: 0.9, t: GHOST }, { k: 'size', ax: 'x', v: 10 }, { k: 'size', ax: 'y', v: 8 }, { k: 'uses', b: 'inter' }],
          hint: "El cilindre va de −5 a 5 en x i en y. Un cub de 10 × 8 × 20 amb la cantonada a (−5, −5, 0) arriba fins a y = 3: talla 2 mm del costat de les y positives.|El cilindro va de −5 a 5 en x y en y. Un cubo de 10 × 8 × 20 con la esquina en (−5, −5, 0) llega hasta y = 3: corta 2 mm del lado de las y positivas.",
          sol: EIXD },
        { k: 'm3code', ph: 'repte', q: "Prepara el cos dels <b>daus</b>: tria la mida de l'esfera perquè el cub de 20 mm tingui les cantonades <b>arrodonides</b> però les cares continuïn <b>planes</b>.|Prepara el cuerpo de los <b>dados</b>: elige el tamaño de la esfera para que el cubo de 20 mm tenga las esquinas <b>redondeadas</b> pero las caras sigan <b>planas</b>.",
          start: J('mou(0, 0, 10) interseca {', '  cub(20, centrat)', '}'), blocks: ['cub', 'esf', 'mou', 'interseca'], target: DAU0,
          checks: [{ k: 'match', target: DAU0, th: 0.9, t: GHOST }, { k: 'size', ax: 'x', v: 20 }, { k: 'vol', min: 7.2, max: 7.9, txt: 'Cantonades arrodonides i cares planes|Esquinas redondeadas y caras planas' }, { k: 'onplate' }],
          hint: "Afegeix una esfera dins de l'interseca, sense mou (centrada, com el cub). Ha de ser més gran que 20 mm i més petita que la diagonal (34,6 mm): prova 28.|Añade una esfera dentro del interseca, sin mueve (centrada, como el cubo). Tiene que ser más grande que 20 mm y más pequeña que la diagonal (34,6 mm): prueba 28.",
          sol: DAU0 },
        { k: 'm3code', ph: 'repte', extra: true, q: "Repte extra: converteix la lent en una <b>perla</b> per a un collaret, amb un forat de 4 mm que la travessi pel mig. Necessitaràs interseca <b>i</b> resta!|Reto extra: convierte la lente en una <b>perla</b> para un collar, con un agujero de 4 mm que la atraviese por el medio. ¡Necesitarás interseca <b>y</b> resta!",
          start: LENT, blocks: ['cil', 'esf', 'mou', 'resta', 'interseca'], target: PERLA,
          checks: [{ k: 'match', target: PERLA, th: 0.9, t: GHOST }, { k: 'uses', b: 'inter' }, { k: 'uses', b: 'diff' }, { k: 'hole' }],
          hint: "Posa un resta que envolti l'interseca (l'interseca és la primera forma) i, després, un cilindre de 4 mm que vagi de z = −1 a z = 13.|Pon un resta que envuelva el interseca (el interseca es la primera forma) y, después, un cilindro de 4 mm que vaya de z = −1 a z = 13.",
          sol: PERLA },
        { k: 'm3free', ph: 'crea', q: "<b>Inventa una forma nova.</b> Fes servir interseca per crear una peça que no sigui a la llista de formes: una gemma, un botó bombat, una fitxa arrodonida, un pany en forma de D… Explica després quines formes has intersecat.|<b>Inventa una forma nueva.</b> Usa interseca para crear una pieza que no esté en la lista de formas: una gema, un botón abombado, una ficha redondeada, una cerradura en forma de D… Explica después qué formas has intersecado.",
          name: 'La meva forma nova|Mi forma nueva', blocks: ALL,
          crit: ['Fa servir interseca|Usa interseca', 'És una sola peça que toca la placa|Es una sola pieza que toca la placa', "Saps explicar quines formes has intersecat i per què surt aquesta peça|Sabes explicar qué formas has intersecado y por qué sale esta pieza"],
          checks: [{ k: 'uses', b: 'inter' }, { k: 'one' }, { k: 'onplate' }], sol: EIXD },
        { k: 'quiz', ph: 'tanca', q: 'Què fa <code>interseca { A  B }</code>?|¿Qué hace <code>interseca { A  B }</code>?', opts: ["Es queda només amb la part que és dins d'A i de B alhora|Se queda solo con la parte que está dentro de A y de B a la vez", 'Ajunta A i B en una sola peça|Junta A y B en una sola pieza', 'Treu B d\'A|Quita B de A'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: "Per fer un cub arrodonit de 20 mm, com ha de ser l'esfera centrada?|Para hacer un cubo redondeado de 20 mm, ¿cómo tiene que ser la esfera centrada?", opts: ['Més gran que 20 mm i més petita que la diagonal del cub (uns 34,6 mm)|Más grande que 20 mm y más pequeña que la diagonal del cubo (unos 34,6 mm)', 'Exactament de 20 mm|Exactamente de 20 mm', 'Tan gran com es vulgui|Tan grande como se quiera'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* =============================== Sessió 4 · Projecte: el dau =============================== */
    { id: 'p3-4', t: 'Projecte: el dau|Proyecto: el dado', min: 45, proj: true, badge: 'p3_dau',
      learn: ["Un model complex es planifica com un arbre: l'operació final a dalt i, a sota, de què es fa cada part (el dau és un cub arrodonit amb interseca menys 21 esferes).|Un modelo complejo se planifica como un árbol: la operación final arriba y, debajo, de qué se hace cada parte (el dado es un cubo redondeado con interseca menos 21 esferas).",
        "Treballar amb la peça centrada a l'origen fa les coordenades fàcils (cada cara és a ±10) i un sol mou final la posa sobre la placa.|Trabajar con la pieza centrada en el origen hace las coordenadas fáciles (cada cara está a ±10) y un solo mueve final la pone sobre la placa.",
        "Les especificacions es comproven una a una: mida, cantonades arrodonides, punts de 2 mm de fondària i cares oposades que sumen 7.|Las especificaciones se comprueban una a una: medida, esquinas redondeadas, puntos de 2 mm de profundidad y caras opuestas que suman 7."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Com hem fet el cub arrodonit a la sessió passada?|¿Cómo hicimos el cubo redondeado en la sesión pasada?', opts: ['Amb interseca d\'un cub centrat i una esfera una mica més gran|Con interseca de un cubo centrado y una esfera un poco más grande', 'Amb resta d\'un cub i una esfera|Con resta de un cubo y una esfera', 'Amb uneix de quatre esferes|Con une de cuatro esferas'], a: 0 },
        { k: 'm3predict', ph: 'recorda', q: "Aquest cub de 20 mm s'interseca amb una esfera de <b>24 mm</b>. Quina peça en surt?|Este cubo de 20 mm se interseca con una esfera de <b>24 mm</b>. ¿Qué pieza sale?", prog: RD(24),
          opts: [{ prog: RD(24) }, { prog: RD(20) }, { prog: RD(28) }, { prog: RD(40) }], a: 0,
          ex: "Amb 24 mm, l'esfera és només una mica més gran que el cub: les cares planes són cercles petits i la peça és gairebé rodona. Amb 20 mm seria una esfera; amb 28, un cub ben arrodonit; amb 40, el cub sencer.|Con 24 mm, la esfera es solo un poco más grande que el cubo: las caras planas son círculos pequeños y la pieza es casi redonda. Con 20 mm sería una esfera; con 28, un cubo bien redondeado; con 40, el cubo entero." },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: 'Daus per a la classe de probabilitat|Dados para la clase de probabilidad',
          t: "Arriba l'encàrrec més esperat: <b>daus</b> per a la classe de probabilitat! La fitxa tècnica diu: cub de <b>20 mm</b> amb les cantonades arrodonides, punts buidats de <b>4 mm</b> de diàmetre i 2 mm de fondària, cares oposades que sumen <b>7</b>, d'una sola peça i que s'imprimeixi directament sobre la placa. Avui en serem els enginyers.|Llega el encargo más esperado: ¡<b>dados</b> para la clase de probabilidad! La ficha técnica dice: cubo de <b>20 mm</b> con las esquinas redondeadas, puntos vaciados de <b>4 mm</b> de diámetro y 2 mm de profundidad, caras opuestas que suman <b>7</b>, de una sola pieza y que se imprima directamente sobre la placa. Hoy seremos sus ingenieros." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Les especificacions|Las especificaciones', t: 'Les sis cares del dau|Las seis caras del dado', anim: 'p3dau',
            x: "En un dau normal, les cares <b>oposades sumen 7</b>: l'1 és davant del 6, el 2 davant del 5 i el 3 davant del 4. Abans de programar, decidim on va cada cara: l'1 a dalt, el 6 a sota, el 2 al davant, el 5 al darrere, el 3 a la dreta i el 4 a l'esquerra.|En un dado normal, las caras <b>opuestas suman 7</b>: el 1 está frente al 6, el 2 frente al 5 y el 3 frente al 4. Antes de programar, decidimos dónde va cada cara: el 1 arriba, el 6 abajo, el 2 delante, el 5 detrás, el 3 a la derecha y el 4 a la izquierda." },
          { k: "L'arbre del model|El árbol del modelo", t: 'Pensar abans de programar|Pensar antes de programar', anim: 'p3tree',
            x: "Els enginyers dibuixen el model com un <b>arbre</b>: a dalt, l'última operació; a sota, de què està fet cada tros. El dau és un <b>mou</b> d'una <b>resta</b>: la peça és la intersecció d'un cub i una esfera, i les eines són 21 esferes petites, una per punt.|Los ingenieros dibujan el modelo como un <b>árbol</b>: arriba, la última operación; debajo, de qué está hecho cada trozo. El dado es un <b>mueve</b> de una <b>resta</b>: la pieza es la intersección de un cubo y una esfera, y las herramientas son 21 esferas pequeñas, una por punto." },
          { k: 'Les coordenades|Las coordenadas', t: "Centrat a l'origen|Centrado en el origen", media: { k: 'model', prog: DAU1 },
            x: "Treballem amb el dau <b>centrat a l'origen</b>: la cara de dalt és a z = 10, la de sota a z = −10, la del davant a y = −10, la del darrere a y = 10, la dreta a x = 10 i l'esquerra a x = −10. Al final, un sol <code>mou(0, 0, 10)</code> davant del resta el posa sobre la placa.|Trabajamos con el dado <b>centrado en el origen</b>: la cara de arriba está en z = 10, la de abajo en z = −10, la de delante en y = −10, la de detrás en y = 10, la derecha en x = 10 y la izquierda en x = −10. Al final, un solo <code>mueve(0, 0, 10)</code> delante del resta lo pone sobre la placa." },
          { k: 'Un punt|Un punto', t: 'Una esfera que resta|Una esfera que resta', media: { k: 'model', prog: DAU123 },
            x: "Cada punt és una <code>esfera(4)</code> amb el centre just a la cara: la meitat queda fora i l'altra meitat buida un clot de <b>2 mm</b> de fondària. Els punts del 2, el 3 i els altres es col·loquen a <b>5 mm</b> del centre de la cara. Aquí ja hi ha l'1 (a dalt), el 2 (al davant) i el 3 (a la dreta).|Cada punto es una <code>esfera(4)</code> con el centro justo en la cara: la mitad queda fuera y la otra mitad vacía un hoyo de <b>2 mm</b> de profundidad. Los puntos del 2, el 3 y los demás se colocan a <b>5 mm</b> del centro de la cara. Aquí ya están el 1 (arriba), el 2 (delante) y el 3 (a la derecha)." },
          { k: 'Un dau just?|¿Un dado justo?', t: 'Simetria i probabilitat|Simetría y probabilidad', media: { k: 'model', prog: DAU_TOT },
            x: "Un dau és <b>just</b> si totes les cares tenen la mateixa probabilitat de sortir, 1/6. Per això ha de ser simètric i equilibrat. Pensa-hi: la cara del 6 té més forats que la de l'1. Creus que això pot fer que surti més una cara que una altra? Ho podreu investigar a classe llançant els daus moltes vegades i comptant els resultats.|Un dado es <b>justo</b> si todas las caras tienen la misma probabilidad de salir, 1/6. Por eso tiene que ser simétrico y equilibrado. Piénsalo: la cara del 6 tiene más agujeros que la del 1. ¿Crees que eso puede hacer que salga más una cara que otra? Lo podréis investigar en clase lanzando los dados muchas veces y contando los resultados." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '✂️', title: 'El desenvolupament del dau|El desarrollo del dado', t: 'Individualment, amb el desenvolupament del cub imprès, tisores i cola:|Individualmente, con el desarrollo del cubo impreso, tijeras y pegamento:',
          steps: ["Dibuixeu els punts de cada cara al desenvolupament, de manera que les cares oposades sumin 7.|Dibujad los puntos de cada cara en el desarrollo, de manera que las caras opuestas sumen 7.",
            "Retalleu-lo i plegueu-lo: comproveu que l'1 queda davant del 6, el 2 davant del 5 i el 3 davant del 4.|Recortadlo y plegadlo: comprobad que el 1 queda frente al 6, el 2 frente al 5 y el 3 frente al 4.",
            "A la fitxa, escriviu les coordenades del centre de cada punt de les cares 1, 2 i 3 (el dau centrat a l'origen, cares a ±10).|En la ficha, escribid las coordenadas del centro de cada punto de las caras 1, 2 y 3 (el dado centrado en el origen, caras a ±10)."],
          tip: "En una cara, l'eix que no canvia és el de la cara: tots els punts de la cara de dalt tenen z = 10.|En una cara, el eje que no cambia es el de la cara: todos los puntos de la cara de arriba tienen z = 10." },
        { k: 'quiz', ph: 'prova', q: "Si el dau té l'<b>1</b> a la cara de dalt, quina cara queda a sota, tocant la placa?|Si el dado tiene el <b>1</b> en la cara de arriba, ¿qué cara queda abajo, tocando la placa?", opts: ['El 6|El 6', 'El 2|El 2', 'El 5|El 5'], a: 0,
          ex: "Les cares oposades sumen 7: 1 + 6 = 7.|Las caras opuestas suman 7: 1 + 6 = 7." },
        { k: 'm3spot', ph: 'investiga', q: "Al dau de la Júlia, la cara del <b>2</b> no surt bé: un dels seus punts és a una altra cara. Toca'l.|En el dado de Júlia, la cara del <b>2</b> no sale bien: uno de sus puntos está en otra cara. Tócalo.",
          prog: DAU_SPOT, target: DAU12,
          ex: "Aquest punt té y = 10: és a la cara del darrere! Els dos punts del 2 han de ser a la cara del davant, y = −10: mou(5, −10, −5).|Este punto tiene y = 10: ¡está en la cara de detrás! Los dos puntos del 2 tienen que estar en la cara de delante, y = −10: mueve(5, −10, −5)." },
        { k: 'move', ph: 'pausa', title: 'El dau humà|El dado humano', secs: 40, t: "Tothom dret. El professor diu un número de l'1 al 6: feu <b>tants salts</b> com diu. Després, de pressa, piqueu de mans tantes vegades com la <b>cara oposada</b> (7 menys el número). Qui s'equivoca s'asseu un moment i torna a començar!|Todo el mundo de pie. El profesor dice un número del 1 al 6: dad <b>tantos saltos</b> como dice. Después, deprisa, dad tantas palmadas como la <b>cara opuesta</b> (7 menos el número). ¡Quien se equivoca se sienta un momento y vuelve a empezar!" },
        { k: 'm3code', ph: 'repte', q: "Comencem pel <b>1</b>: buida un punt al centre de la cara de dalt amb una esfera de 4 mm.|Empezamos por el <b>1</b>: vacía un punto en el centro de la cara de arriba con una esfera de 4 mm.",
          start: DAU_COS, blocks: ['esf', 'mou', 'resta'], target: DAU1,
          checks: [NPT(1), PT(0, 0, 10), { k: 'hole' }, { k: 'onplate' }],
          hint: "Dins del resta, després de l'interseca, afegeix mou(0, 0, 10) esfera(4): la cara de dalt del dau centrat és a z = 10.|Dentro del resta, después del interseca, añade mueve(0, 0, 10) esfera(4): la cara de arriba del dado centrado está en z = 10.",
          sol: DAU1 },
        { k: 'm3code', ph: 'repte', q: "Ara el <b>2</b>, a la cara del <b>davant</b> (y = −10): dos punts en diagonal, a 5 mm del centre de la cara.|Ahora el <b>2</b>, en la cara de <b>delante</b> (y = −10): dos puntos en diagonal, a 5 mm del centro de la cara.",
          start: DAU1, blocks: ['esf', 'mou', 'resta'], target: DAU12,
          checks: [NPT(3), PT(-5, -10, 5), PT(5, -10, -5), { k: 'one' }],
          hint: "A la cara del davant, la y sempre és −10; el que canvia és x i z. Els punts: mou(−5, −10, 5) i mou(5, −10, −5), cada un amb una esfera(4).|En la cara de delante, la y siempre es −10; lo que cambia es x y z. Los puntos: mueve(−5, −10, 5) y mueve(5, −10, −5), cada uno con una esfera(4).",
          sol: DAU12 },
        { k: 'm3code', ph: 'repte', q: "El <b>3</b> va a la cara de la <b>dreta</b> (x = 10): tres punts en diagonal, un d'ells al centre.|El <b>3</b> va en la cara de la <b>derecha</b> (x = 10): tres puntos en diagonal, uno de ellos en el centro.",
          start: DAU12, blocks: ['esf', 'mou', 'resta'], target: DAU123,
          checks: [NPT(6), PT(10, -5, -5), PT(10, 0, 0), PT(10, 5, 5), { k: 'one' }],
          hint: "A la cara de la dreta, x = 10 sempre. Els tres punts: (10, −5, −5), (10, 0, 0) i (10, 5, 5). Duplica un punt i canvia-li els números.|En la cara de la derecha, x = 10 siempre. Los tres puntos: (10, −5, −5), (10, 0, 0) y (10, 5, 5). Duplica un punto y cambia sus números.",
          sol: DAU123 },
        { k: 'm3code', ph: 'repte', q: "El <b>6</b> és la cara oposada de l'1: va a <b>sota</b> (z = −10), en dues columnes de tres punts.|El <b>6</b> es la cara opuesta del 1: va <b>abajo</b> (z = −10), en dos columnas de tres puntos.",
          start: DAU123, blocks: ['esf', 'mou', 'resta'], target: DAU1236,
          checks: [NPT(12), PT(-5, -5, -10), PT(5, 0, -10), PT(5, 5, -10), { k: 'onplate' }],
          hint: "Tots sis tenen z = −10. Una columna amb x = −5 i l'altra amb x = 5; en cada columna, y = −5, 0 i 5. Els clots de sota no impedeixen que el dau s'imprimeixi pla.|Los seis tienen z = −10. Una columna con x = −5 y la otra con x = 5; en cada columna, y = −5, 0 y 5. Los hoyos de abajo no impiden que el dado se imprima plano.",
          sol: DAU1236 },
        { k: 'm3free', ph: 'crea', q: "<b>Acaba el dau de la classe.</b> Hi falten el <b>5</b> (al darrere, y = 10) i el <b>4</b> (a l'esquerra, x = −10). Quan tingui els 21 punts, personalitza'l: un color, una mida… Les cares oposades han de sumar 7!|<b>Termina el dado de la clase.</b> Faltan el <b>5</b> (detrás, y = 10) y el <b>4</b> (a la izquierda, x = −10). Cuando tenga los 21 puntos, personalízalo: un color, un tamaño… ¡Las caras opuestas tienen que sumar 7!",
          name: 'El meu dau|Mi dado', start: DAU1236, blocks: ['cub', 'esf', 'mou', 'color', 'escala', 'resta', 'interseca'],
          crit: ['Té les sis cares: 21 punts en total|Tiene las seis caras: 21 puntos en total', 'Les cares oposades sumen 7 (1-6, 2-5 i 3-4)|Las caras opuestas suman 7 (1-6, 2-5 y 3-4)', 'És una sola peça arrodonida que toca la placa|Es una sola pieza redondeada que toca la placa'],
          checks: [NPT(21), { k: 'uses', b: 'inter' }, { k: 'uses', b: 'diff' }, { k: 'one' }, { k: 'onplate' }], sol: DAU_TOT },
        { k: 'quiz', ph: 'tanca', q: 'Quantes esferes resten en un dau complet?|¿Cuántas esferas restan en un dado completo?', opts: ['21 (1 + 2 + 3 + 4 + 5 + 6)|21 (1 + 2 + 3 + 4 + 5 + 6)', '6, una per cara|6, una por cara', '36 (6 × 6)|36 (6 × 6)'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: "Per què hem fet el dau centrat a l'origen i l'hem pujat al final?|¿Por qué hemos hecho el dado centrado en el origen y lo hemos subido al final?", opts: ['Perquè les cares queden a ±10 i les coordenades dels punts són més fàcils|Porque las caras quedan a ±10 y las coordenadas de los puntos son más fáciles', 'Perquè les esferes només funcionen a l\'origen|Porque las esferas solo funcionan en el origen', 'Perquè la impressora ho demana|Porque la impresora lo pide'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] }
  ] };
})();
