/* Tech Robòtica · unitat 1 «Què és un robot?» */
Object.assign(TBADGE, {
  k_robot: { id: 'k_robot', ico: '🤖', n: 'Explorador/a de robots|Explorador/a de robots', d: 'Saps què és un robot: sent amb els sensors, pensa amb el programa i actua amb els motors.|Sabes qué es un robot: siente con los sensores, piensa con el programa y actúa con los motores.' },
  k_motor: { id: 'k_motor', ico: '⚙️', n: 'Mestre/a dels motors|Maestro/a de los motores', d: 'Domines la velocitat dels motors (de 0 a 255), la zona morta i les dues direccions.|Dominas la velocidad de los motores (de 0 a 255), la zona muerta y las dos direcciones.' },
  k_gir: { id: 'k_gir', ico: '🔄', n: 'Gir perfecte|Giro perfecto', d: 'Fas girar el robot sobre si mateix i en arc, i saps calibrar un gir.|Haces girar el robot sobre sí mismo y en arco, y sabes calibrar un giro.' },
  k_passeig: { id: 'k_passeig', ico: '🗺️', n: 'Guia de la fira|Guía de la feria', d: 'Has planificat i programat el teu primer passeig complet, amb trams i girs.|Has planificado y programado tu primer paseo completo, con tramos y giros.' }
});
ROBOTICA_UNITS[1] = { t: 'Què és un robot?|¿Qué es un robot?', d: 'Sensors, cervell i motors|Sensores, cerebro y motores', color: '#E2574C', s: [
  /* ---------- Sessió 1 · Robots al nostre voltant ---------- */
  { id: 'k1-1', t: 'Robots al nostre voltant|Robots a nuestro alrededor', min: 40, badge: 'k_robot',
    learn: ['Un robot sent amb els sensors, pensa amb el programa i actua amb els motors.|Un robot siente con los sensores, piensa con el programa y actúa con los motores.',
      'El cervell del Maqueen és la micro:bit: hi guardem el programa.|El cerebro del Maqueen es la micro:bit: allí guardamos el programa.',
      "«Espera» deixa passar el temps; sense «atura», els motors no paren.|«Espera» deja pasar el tiempo; sin «para», los motores no se detienen."],
    steps: [
      { k: 'story', ph: 'missio', who: 'both', scene: 'taller', title: 'El taller de robòtica|El taller de robótica',
        t: "Benvingut/da al <b>taller de robòtica de l'illa</b>! Ha arribat una caixa plena de robots <b>Maqueen</b>: durant el curs els programaràs per fer missions de veritat. Però primer: <b>què és, exactament, un robot?</b>|¡Bienvenido/a al <b>taller de robótica de la isla</b>! Ha llegado una caja llena de robots <b>Maqueen</b>: durante el curso los programarás para hacer misiones de verdad. Pero primero: <b>¿qué es, exactamente, un robot?</b>" },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy',
        t: "BIP! Jo visc en una illa de caselles, però el Maqueen és un robot <b>de veritat</b>: es mou per centímetres i graus. El del simulador es comporta com el de l'aula: el que aprenguis aquí et servirà allà.|¡BIP! Yo vivo en una isla de casillas, pero el Maqueen es un robot <b>de verdad</b>: se mueve por centímetros y grados. El del simulador se comporta como el del aula: lo que aprendas aquí te servirá allí." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Robot|Robot', t: 'Què és un robot?|¿Qué es un robot?', anim: 'k1cycle',
          x: "Un <span class='hl'>robot</span> és una màquina que fa tres coses, una vegada i una altra: <b>sent</b> amb els <b>sensors</b>, <b>pensa</b> amb el <b>programa</b> i <b>actua</b> amb els motors, els llums o el so.|Un <span class='hl'>robot</span> es una máquina que hace tres cosas, una y otra vez: <b>siente</b> con los <b>sensores</b>, <b>piensa</b> con el <b>programa</b> y <b>actúa</b> con los motores, las luces o el sonido.",
          tip: "Les parts que fan coses (motors, llums, brunzidor) es diuen <b>actuadors</b>.|Las partes que hacen cosas (motores, luces, zumbador) se llaman <b>actuadores</b>." },
        { k: 'Al nostre voltant|A nuestro alrededor', t: 'Robots de cada dia|Robots de cada día', anim: 'k1life',
          x: "Un robot aspirador nota els mobles i canvia de direcció. Un braç robot d'una fàbrica repeteix el mateix moviment milers de vegades. I els vehicles robot de Mart fan fotos on cap persona no pot anar.|Un robot aspirador nota los muebles y cambia de dirección. Un brazo robot de una fábrica repite el mismo movimiento miles de veces. Y los vehículos robot de Marte hacen fotos donde ninguna persona puede ir.",
          tip: "Tots tres tenen sensors, un programa i motors.|Los tres tienen sensores, un programa y motores." },
        { k: 'Robots i persones|Robots y personas', t: 'Qui decideix?|¿Quién decide?', anim: 'k1ethic',
          x: "Els robots ens ajuden en feines pesades o perilloses, però només fan el que diu el programa: les <b>persones</b> decidim per a què els fem servir i en som responsables. La investigadora <b>Carme Torras</b>, de Barcelona, crea robots que ajuden la gent a casa i pensa com han de ser per tractar-nos bé.|Los robots nos ayudan en trabajos pesados o peligrosos, pero solo hacen lo que dice el programa: las <b>personas</b> decidimos para qué los usamos y somos responsables. La investigadora <b>Carme Torras</b>, de Barcelona, crea robots que ayudan a la gente en casa y piensa cómo tienen que ser para tratarnos bien.",
          tip: "Quina feina t'agradaria que fes un robot? I quina no?|¿Qué trabajo te gustaría que hiciera un robot? ¿Y cuál no?" },
        { k: 'El Maqueen|El Maqueen', t: 'Coneix el Maqueen Lite|Conoce el Maqueen Lite', anim: 'k1parts',
          x: "Fa uns 8 × 8,5 cm. Al davant, els <b>ultrasons</b> mesuren distàncies amb l'eco d'un so que no sentim. A sota, <b>3 sensors de línia</b>. Als costats, <b>2 motors amb rodes</b>. I a dalt, el cervell: la <b>micro:bit</b>, un ordinador petit amb 25 llums i els botons A i B.|Mide unos 8 × 8,5 cm. Delante, los <b>ultrasonidos</b> miden distancias con el eco de un sonido que no oímos. Debajo, <b>3 sensores de línea</b>. A los lados, <b>2 motores con ruedas</b>. Y arriba, el cerebro: la <b>micro:bit</b>, un ordenador pequeño con 25 luces y los botones A y B." },
        { k: 'Programa|Programa', t: 'El primer programa|El primer programa',
          robo: { w: { w: 120, h: 50, bot: [15, 25, 90], zones: [{ id: 'm', r: [66, 13, 24, 24], col: 'green', label: 'META|META' }] }, prog: 'start{ run:all,fwd,150 wait:4000 stop:all }' },
          x: "El que hi ha dins d'<b>en iniciar</b> es fa una vegada, <b>de dalt a baix</b>: engega els motors, <b>espera</b> 4000 ms mentre avança i després els <b>atura</b>.|Lo que hay dentro de <b>al iniciar</b> se hace una vez, <b>de arriba abajo</b>: enciende los motores, <b>espera</b> 4000 ms mientras avanza y después los <b>para</b>.",
          tip: "1000 ms (mil·lisegons) són 1 segon. 4000 ms són 4 segons.|1000 ms (milisegundos) son 1 segundo. 4000 ms son 4 segundos." },
        { k: 'Compte!|¡Cuidado!', t: "Esperar no vol dir parar|Esperar no quiere decir parar",
          robo: { w: { w: 120, h: 50, bot: [15, 25, 90], walls: [[104, 8, 8, 34]], time: 7 }, prog: 'start{ run:all,fwd,150 wait:2000 }' },
          x: "Mentre espera, el robot <b>continua fent el que feia</b>. Aquest programa no té cap «atura»… i els motors giren fins que el robot xoca amb la caixa!|Mientras espera, el robot <b>sigue haciendo lo que hacía</b>. Este programa no tiene ningún «para»… ¡y los motores giran hasta que el robot choca con la caja!",
          bad: "Quan el programa s'acaba, el robot s'atura sol.|Cuando el programa se termina, el robot se para solo.", good: "Si no hi ha cap bloc «atura», els motors continuen girant.|Si no hay ningún bloque «para», los motores siguen girando." }
      ] },
      { k: 'quiz', ph: 'prova', q: 'Quina part del Maqueen fa de <b>cervell</b>?|¿Qué parte del Maqueen hace de <b>cerebro</b>?',
        opts: ['La micro:bit, on hi ha el programa|La micro:bit, donde está el programa', 'Els ultrasons del davant|Los ultrasonidos de delante', 'Les rodes i els motors|Las ruedas y los motores'], a: 0,
        ex: "Els ultrasons senten i els motors actuen. Qui decideix és el programa de la micro:bit.|Los ultrasonidos sienten y los motores actúan. Quien decide es el programa de la micro:bit." },
      { k: 'seq', ph: 'mans', q: 'Un robot aspirador troba una cadira pel camí. <b>Ordena</b> el que passa, des que la nota fins que continua netejant.|Un robot aspirador encuentra una silla en el camino. <b>Ordena</b> lo que pasa, desde que la nota hasta que sigue limpiando.',
        items: ['SENT: el sensor nota la pota de la cadira|SIENTE: el sensor nota la pata de la silla', 'PENSA: el programa decideix que ha de girar|PIENSA: el programa decide que tiene que girar', 'ACTUA: els motors fan girar el robot|ACTÚA: los motores hacen girar el robot', 'Torna a començar: avança i continua netejant|Vuelve a empezar: avanza y sigue limpiando'],
        ex: 'Sentir, pensar i actuar, una vegada i una altra: així funcionen tots els robots.|Sentir, pensar y actuar, una y otra vez: así funcionan todos los robots.' },
      { k: 'unplug', ph: 'mans', ico: '🤖', title: 'El robot de dues persones|El robot de dos personas',
        t: "Amb algú de casa, en un espai lliure, sense res que es pugui trencar.|Con alguien de casa, en un espacio libre, sin nada que se pueda romper.",
        steps: ["Una persona fa de <b>motors</b>: tanca els ulls i només pot caminar a poc a poc o quedar-se quieta.|Una persona hace de <b>motores</b>: cierra los ojos y solo puede caminar despacio o quedarse quieta.",
          "L'altra fa de <b>sensors i cervell</b>: mira el camí i només pot dir «endavant» o «atura't».|La otra hace de <b>sensores y cerebro</b>: mira el camino y solo puede decir «adelante» o «para».",
          "Poseu un coixí a terra: el cervell ha de fer aturar els motors just abans de tocar-lo.|Poned un cojín en el suelo: el cerebro tiene que parar los motores justo antes de tocarlo.",
          'Canvieu els papers. Qui ho ha tingut més difícil? Per què?|Cambiad los papeles. ¿Quién lo ha tenido más difícil? ¿Por qué?'],
        tip: 'Els motors sols no veuen res: sense sensors ni cervell, un robot va a cegues.|Los motores solos no ven nada: sin sensores ni cerebro, un robot va a ciegas.' },
      { k: 'story', ph: 'prova', who: 'numi',
        t: "Al simulador hi ha els mateixos blocs que a <b>MakeCode</b>, on més endavant passaràs el programa al robot de l'aula (allà els blocs del Maqueen surten en anglès). Avui en necessites tres:|En el simulador están los mismos bloques que en <b>MakeCode</b>, donde más adelante pasarás el programa al robot del aula (allí los bloques del Maqueen salen en inglés). Hoy necesitas tres:",
        box: "<ul><li><b>motor … a velocitat …</b>: engega els motors.</li><li><b>espera … ms</b>: deixa passar el temps.</li><li><b>atura el motor</b>: para els motors.</li></ul>Van dins d'<b>en iniciar</b>, en ordre, de dalt a baix.|<ul><li><b>motor … a velocidad …</b>: enciende los motores.</li><li><b>espera … ms</b>: deja pasar el tiempo.</li><li><b>para el motor</b>: para los motores.</li></ul>Van dentro de <b>al iniciar</b>, en orden, de arriba abajo." },
      { k: 'rpredict', ph: 'prova', q: 'Aquest robot avança durant 3 segons. <b>On acabarà?</b> Tria A, B o C i després executa el programa.|Este robot avanza durante 3 segundos. <b>¿Dónde terminará?</b> Elige A, B o C y después ejecuta el programa.',
        w: { w: 120, h: 60, bot: [15, 30, 90], walls: [[104, 12, 8, 36]], marks: { A: [36, 30], B: [62, 30], C: [94, 30] } }, scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:3000 stop:all }', a: 'B',
        ex: "L'espera de 3000 ms el fa avançar 3 segons i «atura» para els motors abans de la caixa.|La espera de 3000 ms lo hace avanzar 3 segundos y «para» detiene los motores antes de la caja." },
      { k: 'rspot', ph: 'investiga', q: 'Aquest robot s\'atura massa aviat i no arriba a la meta. <b>Toca el bloc que cal canviar.</b>|Este robot se para demasiado pronto y no llega a la meta. <b>Toca el bloque que hay que cambiar.</b>',
        w: { w: 120, h: 60, bot: [15, 30, 90], zones: [{ id: 'm', r: [70, 18, 24, 24], col: 'green', label: 'META|META' }] }, scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:1000! stop:all }',
        yes: "Exacte! L'espera decideix quanta estona avança el robot.|¡Exacto! La espera decide cuánto rato avanza el robot.",
        ex: "És l'espera: 1000 ms és només 1 segon de camí. Amb més espera, arribaria més lluny.|Es la espera: 1000 ms es solo 1 segundo de camino. Con más espera, llegaría más lejos." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de Maqueen, sense moure't del lloc! «Motors endavant»: camina al lloc. «Espera 3 segons»: compta fins a 3 sense parar. «Atura»: estàtua! Repetiu-ho tres vegades, cada cop més de pressa.|¡Haz de Maqueen, sin moverte del sitio! «Motores adelante»: camina en el sitio. «Espera 3 segundos»: cuenta hasta 3 sin parar. «Para»: ¡estatua! Repetidlo tres veces, cada vez más deprisa." },
      { k: 'robo', ph: 'repte', q: '<b>El teu primer programa!</b> Porta el Maqueen fins a la <b>META</b> i fes que s\'hi aturi. Necessites tres blocs: motor, espera i atura.|<b>¡Tu primer programa!</b> Lleva el Maqueen hasta la <b>META</b> y haz que se pare allí. Necesitas tres bloques: motor, espera y para.',
        w: { w: 120, h: 60, bot: [15, 30, 90], zones: [{ id: 'm', r: [68, 18, 26, 24], col: 'green', label: 'META|META' }], goal: [{ k: 'zone', id: 'm', stop: true }, { k: 'nohit' }], env: [{ t: 9 }], time: 14 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:4300 stop:all }',
        hint: "Si s'atura abans de la meta, fes l'espera més llarga; si se'n passa, més curta. Prova amb uns 4000 ms.|Si se para antes de la meta, haz la espera más larga; si se pasa, más corta. Prueba con unos 4000 ms." },
      { k: 'robo', ph: 'repte', q: 'Ui! Aquest robot no s\'atura mai i acaba xocant amb la paret. <b>Arregla el programa</b> perquè s\'aturi a la zona de càrrega.|¡Uy! Este robot no se para nunca y acaba chocando con la pared. <b>Arregla el programa</b> para que se pare en la zona de carga.',
        w: { w: 120, h: 60, bot: [15, 30, 90], zones: [{ id: 'c', r: [50, 18, 24, 24], col: 'yellow', label: 'CÀRREGA|CARGA' }], goal: [{ k: 'zone', id: 'c', stop: true }, { k: 'nohit' }], env: [{ t: 7 }], time: 10 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:3000 }', sol: 'start{ run:all,fwd,150 wait:3000 stop:all }',
        hint: 'Falta un bloc al final del programa. Quin bloc fa parar els motors?|Falta un bloque al final del programa. ¿Qué bloque hace parar los motores?' },
      { k: 'robo', ph: 'repte', q: "Ara la meta és a l'altra punta del taller, just davant de la paret. Arriba-hi i atura't <b>sense tocar la paret</b>.|Ahora la meta está en la otra punta del taller, justo delante de la pared. Llega y párate <b>sin tocar la pared</b>.",
        w: { w: 140, h: 60, bot: [15, 30, 90], zones: [{ id: 'm', r: [106, 18, 26, 24], col: 'blue', label: 'META|META' }], goal: [{ k: 'zone', id: 'm', stop: true }, { k: 'nohit' }], env: [{ t: 11 }], time: 16 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:6700 stop:all }',
        hint: "A velocitat 150 fa uns 15 cm cada segon: 4 s → 60 cm, 6 s → 90 cm, 7 s → 105 cm. Per fer-ne uns 100, prova entre 6500 i 7000 ms.|A velocidad 150 hace unos 15 cm cada segundo: 4 s → 60 cm, 6 s → 90 cm, 7 s → 105 cm. Para hacer unos 100, prueba entre 6500 y 7000 ms." },
      { k: 'rcreate', ph: 'crea', name: 'El bus del taller|El autobús del taller',
        q: "<b>Crea el teu programa!</b> El Maqueen fa de bus del taller: ha de fer <b>una parada</b> a la zona groga (s'hi atura una estona) i continuar fins a la zona verda, on s'atura del tot. Tu tries les velocitats i els temps.|<b>¡Crea tu programa!</b> El Maqueen hace de autobús del taller: tiene que hacer <b>una parada</b> en la zona amarilla (se para un rato) y seguir hasta la zona verde, donde se para del todo. Tú eliges las velocidades y los tiempos.",
        crit: ["S'atura una estona a la parada groga|Se para un rato en la parada amarilla", 'Acaba aturat a la zona verda|Termina parado en la zona verde', 'No xoca amb res|No choca con nada'],
        w: { w: 140, h: 60, bot: [15, 30, 90], zones: [{ id: 'p', r: [48, 18, 22, 24], col: 'yellow', label: 'PARADA|PARADA' }, { id: 'f', r: [106, 18, 26, 24], col: 'green', label: 'FINAL|FINAL' }], goal: [{ k: 'zone', id: 'f', stop: true }, { k: 'nohit' }], env: [{ t: 16 }], time: 24 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:2800 stop:all wait:1500 run:all,fwd,150 wait:3800 stop:all }',
        // la parada: el robot ha d'estar quiet almenys mig segon dins la zona groga
        check(P) { const W = roboWorld(this.w), M = roboMachine(W, P), z = W.zones[0]; let q = 0;
          for (let i = 0; i < 2400; i++) { M.tick(); const S = M.S; if (roboInZone(S.x, S.y, z) && Math.abs(S.vl) < .3 && Math.abs(S.vr) < .3) { q += ROBO.DT; if (q >= .5) return null; } else q = 0; }
          return "Arriba al final, però no s'atura a la parada groga. Posa-hi un «atura» i una espera quan el robot sigui a la parada.|Llega al final, pero no se para en la parada amarilla. Pon un «para» y una espera cuando el robot esté en la parada."; } },
      { k: 'quiz', ph: 'tanca', q: 'Quines són les tres coses que fa sempre un robot?|¿Cuáles son las tres cosas que hace siempre un robot?',
        opts: ['Sent, pensa i actua|Siente, piensa y actúa', 'Parla, escolta i dorm|Habla, escucha y duerme', 'Corre, salta i neda|Corre, salta y nada'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: 'Un programa té «motor endavant» i «espera 2000 ms», però no té cap «atura». Què farà el robot?|Un programa tiene «motor adelante» y «espera 2000 ms», pero no tiene ningún «para». ¿Qué hará el robot?',
        opts: ['Continuarà avançant fins que xoqui o s\'apagui|Seguirá avanzando hasta que choque o se apague', "S'aturarà sol al cap de 2 segons|Se parará solo a los 2 segundos", 'No es mourà gens|No se moverá nada'], a: 0,
        ex: "L'espera només deixa passar el temps. Per parar els motors cal «atura».|La espera solo deja pasar el tiempo. Para detener los motores hace falta «para»." },
      { k: 'feel', ph: 'tanca' }
    ] },
  /* ---------- Sessió 2 · Motors i velocitat ---------- */
  { id: 'k1-2', t: 'Motors i velocitat|Motores y velocidad', min: 40, badge: 'k_motor',
    learn: ['La velocitat del motor va de 0 a 255: a 255, el Maqueen fa uns 29 cm cada segon.|La velocidad del motor va de 0 a 255: a 255, el Maqueen hace unos 29 cm cada segundo.',
      'Per sota de 30 el motor no té prou força i no es mou: és la zona morta.|Por debajo de 30 el motor no tiene fuerza suficiente y no se mueve: es la zona muerta.',
      'Cada motor pot anar endavant o enrere; amb la mateixa velocitat i el mateix temps, el robot torna on era.|Cada motor puede ir adelante o atrás; con la misma velocidad y el mismo tiempo, el robot vuelve a donde estaba.'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Recordes què fa el bloc <b>espera 2000 ms</b>?|¿Recuerdas qué hace el bloque <b>espera 2000 ms</b>?',
        opts: ['Deixa passar 2 segons i el robot continua fent el que feia|Deja pasar 2 segundos y el robot sigue haciendo lo que hacía', 'Para el robot durant 2 segons|Para el robot durante 2 segundos', 'Fa que el robot vagi el doble de ràpid|Hace que el robot vaya el doble de rápido'], a: 0 },
      { k: 'story', ph: 'missio', who: 'both', scene: 'lab', title: 'El banc de proves|El banco de pruebas',
        t: "Avui som al <b>laboratori</b>, al banc de proves dels motors. Què vol dir exactament <b>velocitat 150</b>? I per què, de vegades, un robot <b>no es mou</b> encara que el programa li ho mani?|Hoy estamos en el <b>laboratorio</b>, en el banco de pruebas de los motores. ¿Qué quiere decir exactamente <b>velocidad 150</b>? ¿Y por qué, a veces, un robot <b>no se mueve</b> aunque el programa se lo mande?" },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Velocitat|Velocidad', t: 'Un número de 0 a 255|Un número de 0 a 255', anim: 'k1speed',
          x: "Al bloc del motor hi poses la <span class='hl'>velocitat</span>: de <b>0</b> (aturat) a <b>255</b> (al màxim). Cada segon, el Maqueen fa uns <b>9 cm</b> a 100, uns <b>15 cm</b> a 150 i gairebé <b>30 cm</b> a 255.|En el bloque del motor pones la <span class='hl'>velocidad</span>: de <b>0</b> (parado) a <b>255</b> (al máximo). Cada segundo, el Maqueen hace unos <b>9 cm</b> a 100, unos <b>15 cm</b> a 150 y casi <b>30 cm</b> a 255.",
          tip: "Per què 255? És el número més gran que la micro:bit pot enviar al xip dels motors d'un sol cop.|¿Por qué 255? Es el número más grande que la micro:bit puede enviar al chip de los motores de una sola vez." },
        { k: 'Zona morta|Zona muerta', t: 'Massa fluix: no es mou!|Demasiado flojo: ¡no se mueve!', anim: 'k1dead',
          x: "Per sota de velocitat <b>30</b>, el motor no té prou força per vèncer el fregament: fa un brunzit, però <b>el robot no es mou</b>. És la <span class='hl'>zona morta</span>, i al robot de veritat passa igual.|Por debajo de velocidad <b>30</b>, el motor no tiene fuerza suficiente para vencer el rozamiento: zumba, pero <b>el robot no se mueve</b>. Es la <span class='hl'>zona muerta</span>, y en el robot de verdad pasa igual.",
          bad: 'Velocitat 20 és molt lent, però es mou.|Velocidad 20 es muy lento, pero se mueve.', good: 'Velocitat 20 és dins la zona morta: no es mou.|Velocidad 20 está dentro de la zona muerta: no se mueve.' },
        { k: 'Endavant i enrere|Adelante y atrás', t: 'Les dues direccions|Las dos direcciones',
          robo: { w: { w: 120, h: 50, bot: [20, 25, 90], zones: [{ id: 'b', r: [8, 13, 24, 24], col: 'blue', label: 'BASE|BASE' }] }, prog: 'start{ run:all,fwd,150 wait:3000 stop:all wait:500 run:all,back,150 wait:3000 stop:all }' },
          x: "Al bloc del motor també tries la direcció: <b>endavant</b> o <b>enrere</b>. Si torna enrere a la mateixa velocitat i el mateix temps, desfà el camí i torna on era.|En el bloque del motor también eliges la dirección: <b>adelante</b> o <b>atrás</b>. Si vuelve atrás a la misma velocidad y el mismo tiempo, deshace el camino y vuelve a donde estaba." },
        { k: 'Canvis de marxa|Cambios de marcha', t: 'A poc a poc i després de pressa|Despacio y después deprisa',
          robo: { w: { w: 140, h: 50, bot: [15, 25, 90], zones: [{ id: 'e', r: [28, 9, 30, 32], col: 'yellow', label: 'LENT|LENTO' }] }, prog: 'start{ run:all,fwd,60 wait:3500 run:all,fwd,255 wait:2500 stop:all }' },
          x: "Un bloc de motor nou enmig del camí no atura el robot: només <b>canvia la velocitat</b>. Fixa't que tarda una mica a accelerar i a frenar: és la <b>inèrcia</b>.|Un bloque de motor nuevo en medio del camino no para el robot: solo <b>cambia la velocidad</b>. Fíjate en que tarda un poco en acelerar y en frenar: es la <b>inercia</b>.",
          tip: 'Com més de pressa va, més li costa aturar-se just on vols.|Cuanto más deprisa va, más le cuesta pararse justo donde quieres.' },
        { k: 'Energia|Energía', t: 'Les piles del robot|Las pilas del robot', anim: 'k1bat',
          x: "El Maqueen funciona amb <b>3 piles AA</b>. Quan es gasten, el robot va més lent i gira menys. Les piles gastades <b>mai a la brossa</b>: al contenidor de piles, perquè tenen metalls que contaminen i es poden reciclar.|El Maqueen funciona con <b>3 pilas AA</b>. Cuando se gastan, el robot va más lento y gira menos. Las pilas gastadas <b>nunca a la basura</b>: al contenedor de pilas, porque tienen metales que contaminan y se pueden reciclar.",
          tip: "Apaga el robot quan no el facis servir: fas menys residus.|Apaga el robot cuando no lo uses: generas menos residuos." }
      ] },
      { k: 'seq', ph: 'mans', q: 'Ordena aquests motors del <b>més lent</b> al <b>més ràpid</b>.|Ordena estos motores del <b>más lento</b> al <b>más rápido</b>.',
        items: ['Velocitat 20 (no es mou: zona morta)|Velocidad 20 (no se mueve: zona muerta)', 'Velocitat 60|Velocidad 60', 'Velocitat 150|Velocidad 150', 'Velocitat 255|Velocidad 255'],
        ex: 'Com més gran és el número, més ràpid va. Però per sota de 30, res de res!|Cuanto más grande es el número, más rápido va. ¡Pero por debajo de 30, nada de nada!' },
      { k: 'unplug', ph: 'mans', ico: '⏱️', title: 'El banc de proves humà|El banco de pruebas humano',
        t: "Amb algú de casa, un passadís lliure, tres mitjons i un rellotge per comptar el temps.|Con alguien de casa, un pasillo libre, tres calcetines y un reloj para contar el tiempo.",
        steps: ["Una persona fa de robot i l'altra de programador/a, que diu una velocitat: <b>60</b> (passos de formiga), <b>150</b> (caminar normal) o <b>255</b> (caminar molt de pressa, sense córrer).|Una persona hace de robot y la otra de programador/a, que dice una velocidad: <b>60</b> (pasos de hormiga), <b>150</b> (caminar normal) o <b>255</b> (caminar muy deprisa, sin correr).",
          "El robot camina durant 5 segons exactes i s'atura. Deixeu un mitjó on ha arribat.|El robot camina durante 5 segundos exactos y se para. Dejad un calcetín donde ha llegado.",
          'Repetiu-ho amb les tres velocitats, sempre des del mateix lloc.|Repetidlo con las tres velocidades, siempre desde el mismo sitio.',
          "I amb velocitat <b>20</b>? No es mou: zona morta! Compareu on han quedat els mitjons.|¿Y con velocidad <b>20</b>? No se mueve: ¡zona muerta! Comparad dónde han quedado los calcetines."],
        tip: 'Mateix temps i més velocitat: més distància. Ho mesurarem amb el Maqueen a la unitat 2.|Mismo tiempo y más velocidad: más distancia. Lo mediremos con el Maqueen en la unidad 2.' },
      { k: 'rpredict', ph: 'prova', q: 'El robot va endavant 3 segons i després enrere 1,5 segons, a la mateixa velocitat. <b>On acabarà?</b>|El robot va adelante 3 segundos y después atrás 1,5 segundos, a la misma velocidad. <b>¿Dónde terminará?</b>',
        w: { w: 120, h: 60, bot: [15, 30, 90], marks: { A: [38, 30], B: [62, 30], C: [86, 30] } }, scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:3000 run:all,back,150 wait:1500 stop:all }', a: 'A',
        ex: 'Avança 3 segons i torna enrere la meitat del temps: desfà la meitat del camí.|Avanza 3 segundos y vuelve atrás la mitad del tiempo: deshace la mitad del camino.' },
      { k: 'rpredict', ph: 'prova', q: 'Ara va <b>2 segons</b> a velocitat <b>255</b>. On acabarà?|Ahora va <b>2 segundos</b> a velocidad <b>255</b>. ¿Dónde terminará?',
        w: { w: 120, h: 60, bot: [15, 30, 90], marks: { A: [33, 30], B: [52, 30], C: [74, 30] } }, scripts: ['start'],
        prog: 'start{ run:all,fwd,255 wait:2000 stop:all }', a: 'C',
        ex: "A 255 fa gairebé 30 cm cada segon: uns 60 cm en 2 segons.|A 255 hace casi 30 cm cada segundo: unos 60 cm en 2 segundos." },
      { k: 'rspot', ph: 'investiga', q: "La Laia vol que el robot arribi a la meta, però <b>no es mou gens</b>. <b>Toca el bloc que falla.</b>|Laia quiere que el robot llegue a la meta, pero <b>no se mueve nada</b>. <b>Toca el bloque que falla.</b>",
        w: { w: 120, h: 60, bot: [15, 30, 90], zones: [{ id: 'm', r: [70, 18, 24, 24], col: 'green', label: 'META|META' }] }, scripts: ['start'],
        prog: 'start{ run:all,fwd,20! wait:4000 stop:all }',
        yes: 'Molt bé! Velocitat 20 és dins la zona morta.|¡Muy bien! Velocidad 20 está dentro de la zona muerta.',
        ex: 'És el motor: a velocitat 20 no té prou força. Amb 150 arribaria a la meta.|Es el motor: a velocidad 20 no tiene fuerza suficiente. Con 150 llegaría a la meta.' },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de motor, al lloc! Algú diu un número: <b>20</b> → quiet/a (zona morta!), <b>80</b> → lent, <b>150</b> → normal, <b>255</b> → molt ràpid. I ara: <b>enrere</b>! Dos passets enrere, amb compte.|¡Haz de motor, en el sitio! Alguien dice un número: <b>20</b> → quieto/a (¡zona muerta!), <b>80</b> → lento, <b>150</b> → normal, <b>255</b> → muy rápido. Y ahora: ¡<b>atrás</b>! Dos pasitos atrás, con cuidado." },
      { k: 'robo', ph: 'repte', q: 'Aquest robot té <b>3 segons</b> per arribar a la zona de càrrega, però no es mou. <b>Canvia la velocitat</b> perquè hi arribi i s\'hi aturi.|Este robot tiene <b>3 segundos</b> para llegar a la zona de carga, pero no se mueve. <b>Cambia la velocidad</b> para que llegue y se pare allí.',
        w: { w: 120, h: 60, bot: [15, 30, 90], zones: [{ id: 'c', r: [50, 18, 24, 24], col: 'yellow', label: 'CÀRREGA|CARGA' }], goal: [{ k: 'zone', id: 'c', stop: true }, { k: 'nohit' }], env: [{ t: 6 }], time: 10 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'], max: 3,
        prog: 'start{ run:all,fwd,20 wait:3000 stop:all }', sol: 'start{ run:all,fwd,150 wait:3000 stop:all }',
        hint: 'Amb 20 no es mou. Toca el número de la velocitat i prova un número més gran, com 150.|Con 20 no se mueve. Toca el número de la velocidad y prueba un número más grande, como 150.' },
      { k: 'robo', ph: 'repte', q: "Porta l'eina fins al <b>punt 1</b>, al costat de la caixa, i <b>torna enrere</b> fins a la base sense girar. Has d'acabar aturat a la base.|Lleva la herramienta hasta el <b>punto 1</b>, al lado de la caja, y <b>vuelve atrás</b> hasta la base sin girar. Tienes que terminar parado en la base.",
        w: { w: 120, h: 60, bot: [18, 30, 90], walls: [[104, 12, 8, 36]], zones: [{ id: 'b', r: [6, 18, 24, 24], col: 'blue', label: 'BASE|BASE' }], goal: [{ k: 'cps', pts: [[88, 30]], r: 8 }, { k: 'zone', id: 'b', stop: true }, { k: 'nohit' }], env: [{ t: 13 }], time: 18 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:4500 stop:all run:all,back,150 wait:4500 stop:all }',
        hint: 'Primer endavant fins al punt 1. Després, el mateix temps <b>enrere</b> per tornar al lloc.|Primero adelante hasta el punto 1. Después, el mismo tiempo <b>atrás</b> para volver al sitio.' },
      { k: 'robo', ph: 'repte', q: "<b>Contrarellotge!</b> El robot ha d'arribar a la meta i aturar-s'hi en <b>menys de 5 segons</b>. Tria bé la velocitat.|<b>¡Contrarreloj!</b> El robot tiene que llegar a la meta y pararse en <b>menos de 5 segundos</b>. Elige bien la velocidad.",
        w: { w: 140, h: 60, bot: [15, 30, 90], zones: [{ id: 'm', r: [100, 18, 26, 24], col: 'green', label: 'META|META' }], goal: [{ k: 'at', t: 5, zone: 'm', moving: false, why: "Al segon 5 el robot encara no és aturat a la meta: ha d'arribar-hi abans, més de pressa.|En el segundo 5 el robot todavía no está parado en la meta: tiene que llegar antes, más deprisa." }, { k: 'zone', id: 'm', stop: true }, { k: 'nohit' }], time: 12 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,255 wait:3200 stop:all }',
        hint: "A velocitat 150 tarda més de 6 segons. Quina és la velocitat màxima?|A velocidad 150 tarda más de 6 segundos. ¿Cuál es la velocidad máxima?" },
      { k: 'robo', ph: 'repte', extra: true, q: "<b>⭐ Repte extra: el cargol.</b> El robot ha d'anar tan a poc a poc que, al segon 5, <b>encara es mogui</b> però no hagi sortit de la zona groga. Busca la velocitat més baixa que el fa moure's!|<b>⭐ Reto extra: el caracol.</b> El robot tiene que ir tan despacio que, en el segundo 5, <b>todavía se mueva</b> pero no haya salido de la zona amarilla. ¡Busca la velocidad más baja que lo hace moverse!",
        w: { w: 120, h: 60, bot: [18, 30, 90], zones: [{ id: 'z', r: [10, 16, 32, 28], col: 'yellow', label: 'CARGOL|CARACOL' }], goal: [{ k: 'at', t: 5, moving: true, zone: 'z', why: "Al segon 5 el robot ha de continuar movent-se i ser dins la zona groga: ni quiet, ni massa ràpid.|En el segundo 5 el robot tiene que seguir moviéndose y estar dentro de la zona amarilla: ni quieto, ni demasiado rápido." }], time: 9 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,45 wait:6000 stop:all }',
        hint: 'Amb 20 es queda quiet (zona morta) i amb 100 surt de la zona. Prova números entre 30 i 70.|Con 20 se queda quieto (zona muerta) y con 100 sale de la zona. Prueba números entre 30 y 70.' },
      { k: 'rcreate', ph: 'crea', name: "El carrer de l'escola|La calle del colegio",
        q: "<b>Crea-ho tu!</b> Davant de l'escola, els vehicles van <b>a poc a poc</b>. El robot ha de passar per la zona de l'escola a velocitat <b>100 o menys</b>, accelerar després (<b>200 o més</b>) i aturar-se a la meta.|<b>¡Créalo tú!</b> Delante del colegio, los vehículos van <b>despacio</b>. El robot tiene que pasar por la zona del colegio a velocidad <b>100 o menos</b>, acelerar después (<b>200 o más</b>) y pararse en la meta.",
        crit: ["Passa per l'escola a 100 o menys|Pasa por el colegio a 100 o menos", 'Després accelera a 200 o més|Después acelera a 200 o más', 'Acaba aturat a la meta sense xocar|Termina parado en la meta sin chocar'],
        w: { w: 140, h: 60, bot: [15, 30, 90], zones: [{ id: 'e', r: [28, 12, 42, 36], col: 'yellow', label: 'ESCOLA|COLEGIO' }, { id: 'm', r: [108, 18, 24, 24], col: 'green', label: 'META|META' }], goal: [{ k: 'zone', id: 'm', stop: true }, { k: 'nohit' }], env: [{ t: 14 }], time: 22 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,100 wait:6400 run:all,fwd,255 wait:1500 stop:all }',
        // dins la zona de l'escola, com a molt la velocitat d'un motor a ~105; i en algun moment, 200 o més
        check(P) { const W = roboWorld(this.w), M = roboMachine(W, P), z = W.zones[0], fast = (ROBO.VMAX * (200 - ROBO.DEAD) / (255 - ROBO.DEAD)) - .3; let top = 0, ok = false;
          for (let i = 0; i < 2400; i++) { M.tick(); const S = M.S, v = Math.max(Math.abs(S.vl), Math.abs(S.vr)); if (roboInZone(S.x, S.y, z) && v > 9.8) return "El robot passa massa de pressa per davant de l'escola: hi ha d'anar a velocitat 100 o menys.|El robot pasa demasiado deprisa por delante del colegio: tiene que ir a velocidad 100 o menos."; top = Math.max(top, v); }
          return top >= fast ? null : 'Molt prudent! Però després de l\'escola ha d\'accelerar a velocitat 200 o més.|¡Muy prudente! Pero después del colegio tiene que acelerar a velocidad 200 o más.'; } },
      { k: 'quiz', ph: 'tanca', q: 'Quin és el número de velocitat <b>més gran</b> que pots posar al motor?|¿Cuál es el número de velocidad <b>más grande</b> que puedes poner en el motor?',
        opts: ['255|255', '100|100', '1000|1000'], a: 0, ex: "De 0 a 255: a 255, gairebé 30 cm cada segon.|De 0 a 255: a 255, casi 30 cm cada segundo." },
      { k: 'quiz', ph: 'tanca', q: 'Quants mil·lisegons és <b>mig segon</b>?|¿Cuántos milisegundos es <b>medio segundo</b>?',
        opts: ['500 ms|500 ms', '50 ms|50 ms', '5000 ms|5000 ms'], a: 0, ex: '1 segon són 1000 ms; la meitat, 500 ms.|1 segundo son 1000 ms; la mitad, 500 ms.' },
      { k: 'feel', ph: 'tanca' }
    ] },
  /* ---------- Sessió 3 · Girar sobre si mateix ---------- */
  { id: 'k1-3', t: 'Girar sobre si mateix|Girar sobre sí mismo', min: 45, badge: 'k_gir',
    learn: ['El robot gira quan les rodes van a velocitats diferents: cap al costat de la roda més lenta.|El robot gira cuando las ruedas van a velocidades diferentes: hacia el lado de la rueda más lenta.',
      'Una roda endavant i l\'altra enrere: gira sobre si mateix (90° en uns 600 ms a velocitat 100). Amb una sola roda, gira en arc.|Una rueda adelante y la otra atrás: gira sobre sí mismo (90° en unos 600 ms a velocidad 100). Con una sola rueda, gira en arco.',
      'Calibrar és provar, mesurar i ajustar fins que el gir surt bé al robot de veritat.|Calibrar es probar, medir y ajustar hasta que el giro sale bien en el robot de verdad.'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Per sota de quina velocitat el motor del Maqueen <b>no es mou</b>?|¿Por debajo de qué velocidad el motor del Maqueen <b>no se mueve</b>?',
        opts: ['30|30', '100|100', '255|255'], a: 0, ex: 'És la zona morta: el motor no té prou força.|Es la zona muerta: el motor no tiene fuerza suficiente.' },
      { k: 'story', ph: 'missio', who: 'both', scene: 'moll', title: 'Al port|En el puerto',
        t: "Ens n'anem al <b>port</b>! Els robots del moll porten caixes d'un vaixell a l'altre, però el camí té cantonades: cal <b>girar</b>. Com gira un robot que no té volant?|¡Nos vamos al <b>puerto</b>! Los robots del muelle llevan cajas de un barco a otro, pero el camino tiene esquinas: hay que <b>girar</b>. ¿Cómo gira un robot que no tiene volante?" },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Sense volant|Sin volante', t: 'Com gira un robot de dues rodes?|¿Cómo gira un robot de dos ruedas?', anim: 'k1spin',
          x: "El Maqueen gira fent anar les rodes <b>a velocitats diferents</b>. Si van igual, va recte. Si una va més a poc a poc (o enrere), el robot es tomba cap al costat d'aquesta roda.|El Maqueen gira haciendo ir las ruedas <b>a velocidades diferentes</b>. Si van igual, va recto. Si una va más despacio (o hacia atrás), el robot se gira hacia el lado de esa rueda.",
          tip: 'Les excavadores i els tancs giren de la mateixa manera: es diu <b>tracció diferencial</b>.|Las excavadoras y los tanques giran de la misma manera: se llama <b>tracción diferencial</b>.' },
        { k: 'Sobre si mateix|Sobre sí mismo', t: "Una endavant i l'altra enrere|Una adelante y la otra atrás",
          robo: { w: { w: 100, h: 60, bot: [50, 30, 90] }, prog: 'start{ run:L,fwd,100 run:R,back,100 wait:600 stop:all wait:700 run:L,fwd,100 run:R,back,100 wait:600 stop:all wait:700 run:L,fwd,100 run:R,back,100 wait:600 stop:all wait:700 run:L,fwd,100 run:R,back,100 wait:600 stop:all }' },
          x: "Esquerre <b>endavant</b> i dret <b>enrere</b>: el robot gira <b>sense moure's del lloc</b>, cap a la dreta. A velocitat 100, un quart de volta (90°) tarda uns <b>600 ms</b>. Quatre quarts de volta… i torna a mirar on mirava!|Izquierdo <b>adelante</b> y derecho <b>atrás</b>: el robot gira <b>sin moverse del sitio</b>, hacia la derecha. A velocidad 100, un cuarto de vuelta (90°) tarda unos <b>600 ms</b>. Cuatro cuartos de vuelta… ¡y vuelve a mirar donde miraba!",
          tip: "A l'esquerra, a l'inrevés: l'esquerre enrere i el dret endavant. Girs a velocitat 100: 45° ≈ 300 ms · 90° ≈ 600 ms · 180° ≈ 1200 ms.|A la izquierda, al revés: el izquierdo atrás y el derecho adelante. Giros a velocidad 100: 45° ≈ 300 ms · 90° ≈ 600 ms · 180° ≈ 1200 ms." },
        { k: 'En arc|En arco', t: 'Girar amb una sola roda|Girar con una sola rueda',
          robo: { w: { w: 100, h: 60, bot: [30, 42, 90] }, prog: 'start{ run:L,fwd,100 wait:1200 stop:all wait:700 run:all,fwd,120 wait:2500 stop:all }' },
          x: "Si només va <b>una roda</b>, el robot gira al voltant de la que està aturada i fa un <b>arc</b>: més suau, però més lent. A velocitat 100, 90° tarden uns <b>1200 ms</b>, el doble que sobre si mateix.|Si solo va <b>una rueda</b>, el robot gira alrededor de la que está parada y hace un <b>arco</b>: más suave, pero más lento. A velocidad 100, 90° tardan unos <b>1200 ms</b>, el doble que sobre sí mismo." },
        { k: 'Compte!|¡Cuidado!', t: 'Cada robot és una mica diferent|Cada robot es un poco diferente', anim: 'k1calib',
          x: "Al robot de veritat, el mateix programa pot girar 80° o 100°: depèn de les piles, del terra i de cada motor. Per això cal <span class='hl'>calibrar</span>: proves el gir, el mesures i ajustes l'espera.|En el robot de verdad, el mismo programa puede girar 80° o 100°: depende de las pilas, del suelo y de cada motor. Por eso hay que <span class='hl'>calibrar</span>: pruebas el giro, lo mides y ajustas la espera.",
          bad: 'Si al simulador gira 90°, al robot de veritat sortirà exactament igual.|Si en el simulador gira 90°, en el robot de verdad saldrá exactamente igual.', good: "Al robot de veritat, prova el gir i ajusta l'espera.|En el robot de verdad, prueba el giro y ajusta la espera." }
      ] },
      { k: 'unplug', ph: 'mans', ico: '👫', title: 'Fes de rodes|Haz de ruedas',
        t: "Amb algú de casa: poseu-vos un al costat de l'altre i agafeu-vos del braç. Sou les dues rodes d'un robot!|Con alguien de casa: poneos uno al lado del otro y cogeos del brazo. ¡Sois las dos ruedas de un robot!",
        steps: ['Camineu tots dos endavant al mateix ritme: el robot va recte.|Caminad los dos hacia delante al mismo ritmo: el robot va recto.',
          "Ara la persona de l'esquerra fa passets endavant i la de la dreta, enrere: gireu sobre el lloc!|Ahora la persona de la izquierda da pasitos hacia delante y la de la derecha, hacia atrás: ¡giráis sobre el sitio!",
          "Després, la de la dreta es queda quieta i l'altra camina endavant: feu un arc al voltant de la que està quieta.|Después, la de la derecha se queda quieta y la otra camina hacia delante: hacéis un arco alrededor de la que está quieta.",
          'Quin gir ocupa menys espai? Quin és més suau?|¿Qué giro ocupa menos espacio? ¿Cuál es más suave?'],
        tip: 'A poc a poc i sense estirar: les rodes d\'un robot no s\'empenyen!|Despacio y sin tirar: ¡las ruedas de un robot no se empujan!' },
      { k: 'seq', ph: 'mans', q: 'Ordena els passos per <b>calibrar</b> un gir de 90° al robot de veritat.|Ordena los pasos para <b>calibrar</b> un giro de 90° en el robot de verdad.',
        items: ['Programa el gir amb una espera de prova (600 ms)|Programa el giro con una espera de prueba (600 ms)', 'Prova el programa al robot|Prueba el programa en el robot', "Mesura l'angle que ha girat|Mide el ángulo que ha girado", "Si s'ha passat, escurça l'espera; si no hi arriba, allarga-la|Si se ha pasado, acorta la espera; si no llega, alárgala", 'Torna-ho a provar fins que surti 90°|Vuelve a probarlo hasta que salga 90°'],
        ex: "Provar, mesurar, ajustar i tornar a provar: així treballen els enginyers i les enginyeres de robots.|Probar, medir, ajustar y volver a probar: así trabajan los ingenieros y las ingenieras de robots." },
      { k: 'rpredict', ph: 'prova', q: 'El robot mira cap a la dreta de la pantalla. Gira amb l\'<b>esquerre endavant</b> i el <b>dret enrere</b>, i després avança. <b>On acabarà?</b>|El robot mira hacia la derecha de la pantalla. Gira con el <b>izquierdo adelante</b> y el <b>derecho atrás</b>, y después avanza. <b>¿Dónde terminará?</b>',
        w: { w: 120, h: 80, bot: [30, 40, 90], marks: { A: [30, 10], B: [30, 71], C: [61, 40] } }, scripts: ['start'],
        prog: 'start{ run:L,fwd,100 run:R,back,100 wait:600 stop:all wait:300 run:all,fwd,150 wait:2000 stop:all }', a: 'B',
        ex: "Gira 90° cap a la seva dreta: si mirava cap a la dreta de la pantalla, ara mira avall.|Gira 90° hacia su derecha: si miraba hacia la derecha de la pantalla, ahora mira hacia abajo." },
      { k: 'rpredict', ph: 'prova', q: 'Ara només funciona el motor <b>dret</b>, endavant, i després avança. <b>On acabarà?</b>|Ahora solo funciona el motor <b>derecho</b>, adelante, y después avanza. <b>¿Dónde terminará?</b>',
        w: { w: 120, h: 80, bot: [30, 46, 90], marks: { A: [33, 12], B: [33, 74], C: [62, 46] } }, scripts: ['start'],
        prog: 'start{ run:R,fwd,100 wait:1200 stop:all wait:300 run:all,fwd,150 wait:2000 stop:all }', a: 'A',
        ex: "Només va la roda dreta: el robot gira al voltant de l'esquerra, cap a l'esquerra, i queda mirant amunt.|Solo va la rueda derecha: el robot gira alrededor de la izquierda, hacia la izquierda, y queda mirando hacia arriba." },
      { k: 'rspot', ph: 'investiga', q: 'Aquest robot havia de fer un quart de volta, però en fa <b>mitja</b>. <b>Toca el bloc que cal canviar.</b>|Este robot tenía que dar un cuarto de vuelta, pero da <b>media</b>. <b>Toca el bloque que hay que cambiar.</b>',
        w: { w: 100, h: 60, bot: [50, 30, 90] }, scripts: ['start'],
        prog: 'start{ run:L,fwd,100 run:R,back,100 wait:1200! stop:all }',
        yes: "Exacte! L'espera decideix quant gira.|¡Exacto! La espera decide cuánto gira.",
        ex: "És l'espera: 1200 ms a velocitat 100 fan mitja volta (180°). Per a 90°, la meitat: uns 600 ms.|Es la espera: 1200 ms a velocidad 100 hacen media vuelta (180°). Para 90°, la mitad: unos 600 ms." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Gira com el Maqueen! Braços estirats com dues rodes: <b>un quart de volta</b> a la dreta, un altre, un altre i un altre… On mires ara? Ara un <b>arc</b>: un peu quiet i l'altre camina al seu voltant.|¡Gira como el Maqueen! Brazos estirados como dos ruedas: <b>un cuarto de vuelta</b> a la derecha, otro, otro y otro… ¿Dónde miras ahora? Ahora un <b>arco</b>: un pie quieto y el otro camina a su alrededor." },
      { k: 'robo', ph: 'repte', q: '<b>Quart de volta.</b> El robot ha de quedar mirant cap a la porta del magatzem (avall a la pantalla) i aturat. Fes-lo girar sobre si mateix.|<b>Cuarto de vuelta.</b> El robot tiene que quedar mirando hacia la puerta del almacén (abajo en la pantalla) y parado. Hazlo girar sobre sí mismo.',
        w: { w: 100, h: 70, bot: [50, 30, 90], zones: [{ id: 'p', r: [36, 56, 28, 14], col: 'blue', label: 'PORTA|PUERTA' }], goal: [{ k: 'face', h: 180, tol: 12 }, { k: 'stopped' }, { k: 'nohit' }], env: [{ t: 5 }], time: 8 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:L,fwd,100 run:R,back,100 wait:600 stop:all }',
        hint: "Motor esquerre endavant i motor dret enrere, tots dos a velocitat 100. Prova una espera d'uns 600 ms i ajusta-la.|Motor izquierdo adelante y motor derecho atrás, los dos a velocidad 100. Prueba una espera de unos 600 ms y ajústala." },
      { k: 'robo', ph: 'repte', q: "Porta la caixa al <b>moll B</b>: avança fins a la cantonada, gira a l'esquerra i continua fins a la zona.|Lleva la caja al <b>muelle B</b>: avanza hasta la esquina, gira a la izquierda y sigue hasta la zona.",
        w: { w: 120, h: 80, bot: [18, 62, 90], walls: [[28, 6, 46, 40]], zones: [{ id: 'm', r: [78, 8, 26, 24], col: 'green', label: 'MOLL B|MUELLE B' }], goal: [{ k: 'zone', id: 'm', stop: true }, { k: 'nohit' }], env: [{ t: 13 }], time: 18 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:4700 stop:all run:L,back,100 run:R,fwd,100 wait:600 stop:all run:all,fwd,150 wait:2700 stop:all }',
        hint: "A trossos: primer el tram recte fins sota la zona verda, després el gir a l'esquerra (esquerre enrere, dret endavant, 600 ms) i l'últim tram.|A trozos: primero el tramo recto hasta debajo de la zona verde, después el giro a la izquierda (izquierdo atrás, derecho adelante, 600 ms) y el último tramo." },
      { k: 'robo', ph: 'repte', q: "Deixa el paquet al <b>punt 1</b>, fes <b>mitja volta</b> i torna a la base anant <b>endavant</b> (mirant cap a la base).|Deja el paquete en el <b>punto 1</b>, da <b>media vuelta</b> y vuelve a la base yendo <b>adelante</b> (mirando hacia la base).",
        w: { w: 120, h: 60, bot: [20, 30, 90], zones: [{ id: 'b', r: [8, 18, 24, 24], col: 'blue', label: 'BASE|BASE' }], goal: [{ k: 'cps', pts: [[86, 30]], r: 8 }, { k: 'zone', id: 'b', stop: true }, { k: 'face', h: 270, tol: 20 }, { k: 'nohit' }], env: [{ t: 15 }], time: 20 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:4300 stop:all run:L,fwd,100 run:R,back,100 wait:1200 stop:all run:all,fwd,150 wait:4300 stop:all }',
        hint: 'Mitja volta són dos quarts de volta. Si un quart tarda uns 600 ms, quant tarda mitja?|Media vuelta son dos cuartos de vuelta. Si un cuarto tarda unos 600 ms, ¿cuánto tarda media?' },
      { k: 'robo', ph: 'repte', extra: true, q: "<b>⭐ Repte extra: el passadís de caixes.</b> Fes-lo passar entre les piles de caixes fins al moll C. Compta els girs: n'hi ha dos!|<b>⭐ Reto extra: el pasillo de cajas.</b> Hazlo pasar entre las pilas de cajas hasta el muelle C. Cuenta los giros: ¡hay dos!",
        w: { w: 140, h: 80, bot: [15, 20, 90], walls: [[30, 34, 25, 46], [80, 0, 25, 46]], zones: [{ id: 'm', r: [104, 48, 26, 24], col: 'green', label: 'MOLL C|MUELLE C' }], goal: [{ k: 'zone', id: 'm', stop: true }, { k: 'nohit' }], env: [{ t: 16 }], time: 22 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:3200 stop:all run:L,fwd,100 run:R,back,100 wait:600 stop:all run:all,fwd,150 wait:2600 stop:all run:L,back,100 run:R,fwd,100 wait:600 stop:all run:all,fwd,150 wait:3300 stop:all }',
        hint: 'Tram, gir a la dreta, tram, gir a l\'esquerra, tram. Prova el programa cada vegada que afegeixes un tros.|Tramo, giro a la derecha, tramo, giro a la izquierda, tramo. Prueba el programa cada vez que añades un trozo.' },
      { k: 'rcreate', ph: 'crea', name: 'La ruta del port|La ruta del puerto',
        q: "<b>Dissenya la teva ruta!</b> El robot ha de passar pels <b>dos vaixells</b> (punts 1 i 2) en ordre i acabar aturat al <b>garatge</b>, sense tocar el magatzem del mig. Gira com vulguis: sobre si mateix o en arc.|<b>¡Diseña tu ruta!</b> El robot tiene que pasar por los <b>dos barcos</b> (puntos 1 y 2) en orden y terminar parado en el <b>garaje</b>, sin tocar el almacén del medio. Gira como quieras: sobre sí mismo o en arco.",
        crit: ['Passa pels punts 1 i 2 en ordre|Pasa por los puntos 1 y 2 en orden', 'Fa girs sobre si mateix o en arc|Hace giros sobre sí mismo o en arco', 'Acaba aturat al garatge sense xocar|Termina parado en el garaje sin chocar'],
        w: { w: 140, h: 80, bot: [15, 65, 90], walls: [[50, 30, 40, 20]], zones: [{ id: 'g', r: [8, 6, 26, 24], col: 'purple', label: 'GARATGE|GARAJE' }], goal: [{ k: 'cps', pts: [[110, 65], [110, 18]], r: 9 }, { k: 'zone', id: 'g', stop: true }, { k: 'nohit' }], env: [{ t: 22 }], time: 30 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:6100 stop:all run:L,back,100 run:R,fwd,100 wait:600 stop:all run:all,fwd,150 wait:3000 stop:all run:L,back,100 run:R,fwd,100 wait:600 stop:all run:all,fwd,150 wait:5700 stop:all }' },
      { k: 'quiz', ph: 'tanca', q: 'Per girar <b>sobre si mateix</b>, com han d\'anar les dues rodes?|Para girar <b>sobre sí mismo</b>, ¿cómo tienen que ir las dos ruedas?',
        opts: ["Una endavant i l'altra enrere|Una adelante y la otra atrás", 'Totes dues endavant a la mateixa velocitat|Las dos adelante a la misma velocidad', "Una endavant i l'altra aturada|Una adelante y la otra parada"], a: 0,
        ex: 'Amb una roda aturada, el robot gira en arc.|Con una rueda parada, el robot gira en arco.' },
      { k: 'quiz', ph: 'tanca', q: 'Què vol dir <b>calibrar</b> un gir?|¿Qué quiere decir <b>calibrar</b> un giro?',
        opts: ['Provar-lo, mesurar-lo i ajustar els números fins que surti bé|Probarlo, medirlo y ajustar los números hasta que salga bien', 'Fer-lo tan ràpid com es pugui|Hacerlo tan rápido como se pueda', "Copiar els números d'un company/a|Copiar los números de un compañero/a"], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] },
  /* ---------- Sessió 4 · Projecte: el passeig ---------- */
  { id: 'k1-4', t: 'Projecte: el passeig de la fira|Proyecto: el paseo de la feria', min: 45, proj: true, badge: 'k_passeig',
    learn: ['Descompondre és partir la ruta en trams rectes i girs, i programar-los un a un.|Descomponer es partir la ruta en tramos rectos y giros, y programarlos uno a uno.',
      "El botó MakeCode obre el programa en blocs i, amb el cable USB i «Descarrega», el passa a la micro:bit del robot de veritat.|El botón MakeCode abre el programa en bloques y, con el cable USB y «Descargar», lo pasa a la micro:bit del robot de verdad.",
      'Has acabat el teu primer projecte de robòtica!|¡Has terminado tu primer proyecto de robótica!'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Motor esquerre <b>enrere</b> i motor dret <b>endavant</b>. Cap on gira el robot?|Motor izquierdo <b>atrás</b> y motor derecho <b>adelante</b>. ¿Hacia dónde gira el robot?',
        opts: ["Cap a l'esquerra, sense moure's del lloc|Hacia la izquierda, sin moverse del sitio", 'Cap a la dreta, sense moure\'s del lloc|Hacia la derecha, sin moverse del sitio', 'Recte enrere|Recto hacia atrás'], a: 0,
        ex: 'Gira cap al costat de la roda que va enrere: l\'esquerra.|Gira hacia el lado de la rueda que va atrás: la izquierda.' },
      { k: 'story', ph: 'missio', who: 'both', scene: 'poble', title: 'La fira de robòtica|La feria de robótica',
        t: "Dissabte hi ha la <b>fira de robòtica</b> a la plaça, i el Maqueen hi farà de <b>guia</b>: passejarà els visitants per les parades i els tornarà a la sortida. És el projecte de la unitat!|El sábado hay <b>feria de robótica</b> en la plaza, y el Maqueen hará de <b>guía</b>: pasará a los visitantes por los puestos y los devolverá a la salida. ¡Es el proyecto de la unidad!" },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Descompondre|Descomponer', t: 'La ruta, a trossos|La ruta, a trozos',
          robo: { w: { w: 120, h: 70, bot: [15, 55, 90], zones: [{ id: 'f', r: [62, 6, 26, 22], col: 'green', label: 'FINAL|FINAL' }], goal: [{ k: 'cps', pts: [[75, 55], [75, 17]], r: 6 }] }, prog: 'start{ run:all,fwd,150 wait:3900 stop:all run:L,back,100 run:R,fwd,100 wait:600 stop:all run:all,fwd,150 wait:2400 stop:all }' },
          x: "Abans de posar blocs, parteix el camí en <b>trams</b>: «recte fins al punt 1; gir a l'esquerra; recte fins al punt 2». Cada tros és un problema petit. Això es diu <span class='hl'>descompondre</span>.|Antes de poner bloques, parte el camino en <b>tramos</b>: «recto hasta el punto 1; giro a la izquierda; recto hasta el punto 2». Cada trozo es un problema pequeño. Esto se llama <span class='hl'>descomponer</span>.",
          tip: "Un tram són tres blocs: motor els dos, espera i atura. Un gir, quatre: els dos motors en direccions contràries, espera i atura.|Un tramo son tres bloques: motor los dos, espera y para. Un giro, cuatro: los dos motores en direcciones contrarias, espera y para." },
        { k: 'Al robot de veritat|Al robot de verdad', t: 'Del simulador a la micro:bit|Del simulador a la micro:bit', anim: 'k1usb',
          x: "Quan el programa funcioni, toca el botó <b>MakeCode</b>: s'obre MakeCode aquí mateix, amb el teu programa ja fet amb blocs (els del Maqueen surten en anglès). Connecta la micro:bit amb el cable USB i prem <b>Descarrega</b>. Desconnecta el cable, encén el robot… i a provar!|Cuando el programa funcione, toca el botón <b>MakeCode</b>: se abre MakeCode aquí mismo, con tu programa ya hecho con bloques (los del Maqueen salen en inglés). Conecta la micro:bit con el cable USB y pulsa <b>Descargar</b>. Desconecta el cable, enciende el robot… ¡y a probar!" },
        { k: 'Provar|Probar', t: 'Prova, mesura i ajusta|Prueba, mide y ajusta', anim: 'k1calib',
          x: "El robot de veritat no farà exactament el mateix que el del simulador: les piles, el terra i els motors canvien una mica. Prova el passeig <b>tram a tram</b> i ajusta només el número del tram que falla.|El robot de verdad no hará exactamente lo mismo que el del simulador: las pilas, el suelo y los motores cambian un poco. Prueba el paseo <b>tramo a tramo</b> y ajusta solo el número del tramo que falla.",
          bad: "Si falla, ho esborro tot i començo de nou.|Si falla, lo borro todo y empiezo de nuevo.", good: "Si falla, busco el tram que falla i canvio només aquell número.|Si falla, busco el tramo que falla y cambio solo ese número." }
      ] },
      { k: 'seq', ph: 'mans', q: 'Aquest és el pla del passeig més curt. <b>Ordena els trossos</b>.|Este es el plan del paseo más corto. <b>Ordena los trozos</b>.',
        items: ['Tram 1: recte fins a la parada de les fruites|Tramo 1: recto hasta el puesto de las frutas', "Primer gir: un quart de volta a l'esquerra|Primer giro: un cuarto de vuelta a la izquierda", 'Tram 2: recte fins a la parada dels llibres|Tramo 2: recto hasta el puesto de los libros', "Segon gir: un altre quart de volta a l'esquerra|Segundo giro: otro cuarto de vuelta a la izquierda", "Tram 3: recte fins a la sortida i atura't|Tramo 3: recto hasta la salida y párate"],
        ex: 'Tram, gir, tram, gir, tram: un problema gran convertit en cinc de petits.|Tramo, giro, tramo, giro, tramo: un problema grande convertido en cinco pequeños.' },
      { k: 'unplug', ph: 'mans', ico: '🗺️', title: 'El mapa del passeig|El mapa del paseo',
        t: 'Amb algú de casa, un full i un llapis.|Con alguien de casa, una hoja y un lápiz.',
        steps: ["Dibuixa el plànol d'una habitació i marca-hi tres «parades» (la porta, una cadira, la finestra…).|Dibuja el plano de una habitación y marca tres «paradas» (la puerta, una silla, la ventana…).",
          'Escriu el pla del passeig en trams i girs: «tram 1: 4 passos; gir a la dreta; tram 2: 3 passos…».|Escribe el plan del paseo en tramos y giros: «tramo 1: 4 pasos; giro a la derecha; tramo 2: 3 pasos…».',
          "L'altra persona fa de robot i segueix el pla exactament, sense mirar el plànol.|La otra persona hace de robot y sigue el plan exactamente, sin mirar el plano.",
          'Si es desvia, no esborreu tot el pla: busqueu el tram que falla i corregiu només aquell.|Si se desvía, no borréis todo el plan: buscad el tramo que falla y corregid solo ese.'],
        tip: "Això és calibrar: les passes de cadascú fan una llargada diferent!|Esto es calibrar: ¡los pasos de cada uno miden una longitud diferente!" },
      { k: 'rpredict', ph: 'prova', q: 'Tram, gir i tram. <b>On acabarà</b> el robot guia?|Tramo, giro y tramo. <b>¿Dónde terminará</b> el robot guía?',
        w: { w: 120, h: 80, bot: [20, 45, 90], marks: { A: [69, 14], B: [69, 76], C: [100, 45] } }, scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:3200 stop:all run:L,back,100 run:R,fwd,100 wait:600 stop:all run:all,fwd,150 wait:2000 stop:all }', a: 'A',
        ex: "L'esquerre va enrere i el dret endavant: gira a l'esquerra i queda mirant amunt.|El izquierdo va atrás y el derecho adelante: gira a la izquierda y queda mirando hacia arriba." },
      { k: 'rspot', ph: 'investiga', q: 'En Pau ha programat un passeig, però el robot <b>xoca amb la parada dels llibres</b>. Executa-ho i <b>toca el bloc que cal canviar.</b>|Pau ha programado un paseo, pero el robot <b>choca con el puesto de los libros</b>. Ejecútalo y <b>toca el bloque que hay que cambiar.</b>',
        w: { w: 120, h: 70, bot: [15, 58, 90], walls: [[56, 4, 26, 12]] }, scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:3500 stop:all run:L,back,100 run:R,fwd,100 wait:600 stop:all run:all,fwd,150 wait:4000! stop:all }',
        yes: "Molt bé! L'últim tram és massa llarg.|¡Muy bien! El último tramo es demasiado largo.",
        ex: "És l'espera de l'últim tram: 4000 ms el porta fins a la parada. Amb menys espera, s'aturaria al davant.|Es la espera del último tramo: 4000 ms lo llevan hasta el puesto. Con menos espera, se pararía delante." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de robot guia! <b>Tram</b> de 4 passos, <b>quart de volta</b> a l'esquerra, tram de 3 passos, quart de volta a l'esquerra, tram de 4 passos… i saluda els visitants!|¡Haz de robot guía! <b>Tramo</b> de 4 pasos, <b>cuarto de vuelta</b> a la izquierda, tramo de 3 pasos, cuarto de vuelta a la izquierda, tramo de 4 pasos… ¡y saluda a los visitantes!" },
      { k: 'robo', ph: 'repte', q: 'En Pau ha començat el programa: el <b>tram 1</b> ja funciona. Afegeix-hi el <b>gir</b> i el <b>tram 2</b> perquè el robot s\'aturi a la parada de les fruites.|Pau ha empezado el programa: el <b>tramo 1</b> ya funciona. Añade el <b>giro</b> y el <b>tramo 2</b> para que el robot se pare en el puesto de las frutas.',
        w: { w: 120, h: 80, bot: [15, 62, 90], walls: [[26, 6, 34, 38]], zones: [{ id: 'f', r: [64, 8, 26, 24], col: 'orange', label: 'FRUITES|FRUTAS' }], goal: [{ k: 'zone', id: 'f', stop: true }, { k: 'nohit' }], env: [{ t: 12 }], time: 16 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:3800 stop:all }', sol: 'start{ run:all,fwd,150 wait:3800 stop:all run:L,back,100 run:R,fwd,100 wait:600 stop:all run:all,fwd,150 wait:2700 stop:all }',
        hint: "El gir és a l'esquerra: esquerre enrere i dret endavant, a 100, uns 600 ms. Després, un tram recte més curt que el primer.|El giro es a la izquierda: izquierdo atrás y derecho adelante, a 100, unos 600 ms. Después, un tramo recto más corto que el primero." },
      { k: 'robo', ph: 'repte', q: "<b>La volta a les flors.</b> Fes que el robot envolti la parada de les flors: tram, gir a la dreta, tram, gir a la dreta i tram fins a la zona dels visitants.|<b>La vuelta a las flores.</b> Haz que el robot rodee el puesto de las flores: tramo, giro a la derecha, tramo, giro a la derecha y tramo hasta la zona de los visitantes.",
        w: { w: 120, h: 80, bot: [15, 15, 90], walls: [[20, 30, 62, 22]], zones: [{ id: 'v', r: [6, 56, 28, 22], col: 'purple', label: 'VISITANTS|VISITANTES' }], goal: [{ k: 'zone', id: 'v', stop: true }, { k: 'nohit' }], env: [{ t: 18 }], time: 24 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:5200 stop:all run:L,fwd,100 run:R,back,100 wait:600 stop:all run:all,fwd,150 wait:3300 stop:all run:L,fwd,100 run:R,back,100 wait:600 stop:all run:all,fwd,150 wait:4900 stop:all }',
        hint: 'Prova el programa després de cada tram: si el primer tram ja va bé, no el toquis més.|Prueba el programa después de cada tramo: si el primer tramo ya va bien, no lo toques más.' },
      { k: 'robo', ph: 'repte', extra: true, q: "<b>⭐ Repte extra: passeig exprés.</b> El forner necessita el pa a la parada del forn en <b>menys de 6 segons</b>. Fes els trams més de pressa (i recalcula les esperes!).|<b>⭐ Reto extra: paseo exprés.</b> El panadero necesita el pan en el puesto del horno en <b>menos de 6 segundos</b>. Haz los tramos más deprisa (¡y recalcula las esperas!).",
        w: { w: 120, h: 80, bot: [15, 66, 90], walls: [[28, 4, 42, 44]], zones: [{ id: 'f', r: [76, 6, 28, 22], col: 'red', label: 'FORN|HORNO' }], goal: [{ k: 'at', t: 6, zone: 'f', moving: false, why: "Al segon 6 el robot encara no és aturat a la parada del forn: ha d'arribar-hi abans. Fes els trams més de pressa.|En el segundo 6 el robot todavía no está parado en el puesto del horno: tiene que llegar antes. Haz los tramos más deprisa." }, { k: 'zone', id: 'f', stop: true }, { k: 'nohit' }], time: 14 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:4600 stop:all run:L,back,100 run:R,fwd,100 wait:600 stop:all run:all,fwd,150 wait:3100 stop:all }',
        sol: 'start{ run:all,fwd,255 wait:2450 stop:all run:L,back,100 run:R,fwd,100 wait:600 stop:all run:all,fwd,255 wait:1600 stop:all }',
        hint: "A 255 va gairebé el doble de ràpid que a 150: cada espera dels trams ha de ser una mica més de la meitat. El gir pot quedar igual.|A 255 va casi el doble de rápido que a 150: cada espera de los tramos tiene que ser un poco más de la mitad. El giro puede quedar igual." },
      { k: 'rcreate', ph: 'crea', name: 'El passeig de la fira|El paseo de la feria',
        q: "<b>Projecte final de la unitat!</b> El robot guia ha de passar per les <b>3 parades</b> en ordre (punts 1, 2 i 3) i acabar <b>aturat a la sortida</b>, sense tocar cap parada ni la font. Planifica-ho a trams i prova-ho tros a tros.|<b>¡Proyecto final de la unidad!</b> El robot guía tiene que pasar por los <b>3 puestos</b> en orden (puntos 1, 2 y 3) y terminar <b>parado en la salida</b>, sin tocar ningún puesto ni la fuente. Planifícalo a tramos y pruébalo trozo a trozo.",
        crit: ['Passa per les 3 parades en ordre|Pasa por los 3 puestos en orden', 'Acaba aturat a la sortida|Termina parado en la salida', 'No toca cap parada ni la font|No toca ningún puesto ni la fuente'],
        w: { w: 140, h: 90, bot: [15, 75, 90], walls: [[52, 84, 26, 6], [126, 32, 10, 26], [57, 2, 26, 8], [40, 38, 56, 22]], zones: [{ id: 's', r: [16, 8, 28, 24], col: 'green', label: 'SORTIDA|SALIDA' }], goal: [{ k: 'cps', pts: [[65, 75], [115, 45], [70, 20]], r: 9 }, { k: 'zone', id: 's', stop: true }, { k: 'nohit' }], env: [{ t: 24 }], time: 34 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:6400 stop:all run:L,back,100 run:R,fwd,100 wait:600 stop:all run:all,fwd,150 wait:3500 stop:all run:L,back,100 run:R,fwd,100 wait:600 stop:all run:all,fwd,150 wait:5300 stop:all }' },
      { k: 'story', ph: 'crea', who: 'numi',
        t: "Ho vols provar al <b>Maqueen de veritat</b>? Obre el teu projecte (a «Projectes») i toca el botó <b>MakeCode</b>: connecta la micro:bit amb el cable USB, prem <b>Descarrega</b> i prova el passeig a la pista de cinta de l'aula.|¿Lo quieres probar en el <b>Maqueen de verdad</b>? Abre tu proyecto (en «Proyectos») y toca el botón <b>MakeCode</b>: conecta la micro:bit con el cable USB, pulsa <b>Descargar</b> y prueba el paseo en la pista de cinta del aula.",
        box: "<ol><li>Prova el passeig sencer i mira on es desvia.</li><li>Calibra primer els <b>girs</b>.</li><li>Després, els <b>trams</b>.</li><li>Canvia un sol número cada vegada.</li></ol>|<ol><li>Prueba el paseo entero y mira dónde se desvía.</li><li>Calibra primero los <b>giros</b>.</li><li>Después, los <b>tramos</b>.</li><li>Cambia un solo número cada vez.</li></ol>" },
      { k: 'quiz', ph: 'tanca', q: 'Què vol dir <b>descompondre</b> una ruta?|¿Qué quiere decir <b>descomponer</b> una ruta?',
        opts: ['Partir-la en trams i girs més petits|Partirla en tramos y giros más pequeños', 'Fer-la tota de cop sense pensar|Hacerla toda de golpe sin pensar', 'Esborrar el programa i començar de nou|Borrar el programa y empezar de nuevo'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: 'El teu passeig funciona al simulador, però al robot de veritat <b>gira una mica massa</b>. Què fas?|Tu paseo funciona en el simulador, pero en el robot de verdad <b>gira un poco de más</b>. ¿Qué haces?',
        opts: ["Calibro: escurço una mica l'espera del gir i ho torno a provar|Calibro: acorto un poco la espera del giro y vuelvo a probarlo", 'Res: el simulador sempre té raó|Nada: el simulador siempre tiene razón', 'Canvio tot el programa|Cambio todo el programa'], a: 0,
        ex: 'Un robot real sempre és una mica diferent: per això es calibra.|Un robot real siempre es un poco diferente: por eso se calibra.' },
      { k: 'feel', ph: 'tanca' }
    ] }
] };
