/* Tech Robòtica · unitat 1 «Què és un robot?» */
Object.assign(TBADGE, {
  k_robot: { id: 'k_robot', ico: '🤖', n: 'Explorador/a de robots|Explorador/a de robots', d: 'Saps què és un robot: sent amb els sensors, pensa amb el programa i actua amb els motors.|Sabes qué es un robot: siente con los sensores, piensa con el programa y actúa con los motores.' },
  k_motor: { id: 'k_motor', ico: '⚙️', n: 'Mestre/a dels motors|Maestro/a de los motores', d: 'Domines la velocitat dels motors (de 0 a 255), la zona morta i les dues direccions.|Dominas la velocidad de los motores (de 0 a 255), la zona muerta y las dos direcciones.' },
  k_gir: { id: 'k_gir', ico: '🔄', n: 'Gir perfecte|Giro perfecto', d: 'Fas girar el robot sobre si mateix i en arc, i saps calibrar un gir.|Haces girar el robot sobre sí mismo y en arco, y sabes calibrar un giro.' },
  k_passeig: { id: 'k_passeig', ico: '🗺️', n: 'Guia de la fira|Guía de la feria', d: 'Has planificat i programat el teu primer passeig complet, amb trams i girs.|Has planificado y programado tu primer paseo completo, con tramos y giros.' }
});
ROBOTICA_UNITS[1] = { t: 'Què és un robot?|¿Qué es un robot?', d: 'Sensors, cervell i motors|Sensores, cerebro y motores', color: '#E2574C', s: [
  /* ---------- Sessió 1 · Robots al nostre voltant ---------- */
  { id: 'k1-1', t: 'Robots al nostre voltant|Robots a nuestro alrededor', min: 40, badge: 'k_robot',
    learn: ['Un robot sent amb els sensors, pensa amb el programa i actua amb els motors.|Un robot siente con los sensores, piensa con el programa y actúa con los motores.',
      'El cervell del Maqueen és la micro:bit: hi guardem el programa.|El cerebro del Maqueen es la micro:bit: allí guardamos el programa.',
      "«Espera» deixa passar el temps; sense «atura», els motors no paren.|«Espera» deja pasar el tiempo; sin «para», los motores no se detienen."],
    steps: [
      { k: 'story', ph: 'missio', who: 'both', scene: 'taller', title: 'El taller de robòtica|El taller de robótica',
        t: "Benvingut/da al <b>taller de robòtica de l'illa</b>! Avui ha arribat una caixa plena de robots <b>Maqueen</b>. Durant el curs els programaràs per fer missions de veritat: seguir camins, esquivar obstacles, rescats… Però primer, una pregunta: <b>què és, exactament, un robot?</b>|¡Bienvenido/a al <b>taller de robótica de la isla</b>! Hoy ha llegado una caja llena de robots <b>Maqueen</b>. Durante el curso los programarás para hacer misiones de verdad: seguir caminos, esquivar obstáculos, rescates… Pero primero, una pregunta: <b>¿qué es, exactamente, un robot?</b>" },
      { k: 'story', ph: 'missio', who: 'bit', mood: 'happy',
        t: "BIP! Jo visc en una illa de caselles, però el Maqueen és un robot <b>de veritat</b>: té motors, rodes i sensors, i es mou per centímetres i graus. El del simulador es comporta igual que el que teniu a l'aula, així que el que aprenguis aquí et servirà allà.|¡BIP! Yo vivo en una isla de casillas, pero el Maqueen es un robot <b>de verdad</b>: tiene motores, ruedas y sensores, y se mueve por centímetros y grados. El del simulador se comporta igual que el que tenéis en el aula, así que lo que aprendas aquí te servirá allí." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Robot|Robot', t: 'Què és un robot?|¿Qué es un robot?', anim: 'k1cycle',
          x: "Un <span class='hl'>robot</span> és una màquina que fa tres coses, una vegada i una altra: <b>sent</b> el que passa amb els <b>sensors</b>, <b>pensa</b> què ha de fer amb el seu <b>programa</b> i <b>actua</b> amb els motors, els llums o el so.|Un <span class='hl'>robot</span> es una máquina que hace tres cosas, una y otra vez: <b>siente</b> lo que pasa con los <b>sensores</b>, <b>piensa</b> qué tiene que hacer con su <b>programa</b> y <b>actúa</b> con los motores, las luces o el sonido.",
          tip: "Les parts que fan coses (motors, llums, brunzidor) es diuen <b>actuadors</b>.|Las partes que hacen cosas (motores, luces, zumbador) se llaman <b>actuadores</b>." },
        { k: 'Al nostre voltant|A nuestro alrededor', t: 'Robots de cada dia|Robots de cada día', anim: 'k1life',
          x: "Un robot aspirador nota les parets i els mobles i canvia de direcció. Un braç robot d'una fàbrica repeteix el mateix moviment milers de vegades sense cansar-se. I els vehicles robot que exploren Mart fan fotos i mesures on cap persona no pot anar.|Un robot aspirador nota las paredes y los muebles y cambia de dirección. Un brazo robot de una fábrica repite el mismo movimiento miles de veces sin cansarse. Y los vehículos robot que exploran Marte hacen fotos y medidas donde ninguna persona puede ir.",
          tip: "Tots tres tenen sensors, un programa i motors.|Los tres tienen sensores, un programa y motores." },
        { k: 'El Maqueen|El Maqueen', t: 'Coneix el Maqueen Lite|Conoce el Maqueen Lite', anim: 'k1parts',
          x: "El nostre robot fa només 8 × 8,5 cm. Al davant hi ha els <b>ultrasons</b>: dos «ulls» que mesuren distàncies (un envia un so i l'altre n'escolta l'eco). A sota, <b>3 sensors de línia</b>. Als costats, <b>2 motors amb rodes</b>. I a dalt, el cervell: la <b>micro:bit</b>, un ordinador petit amb 25 llums i dos botons, A i B.|Nuestro robot mide solo 8 × 8,5 cm. Delante están los <b>ultrasonidos</b>: dos «ojos» que miden distancias (uno envía un sonido y el otro escucha su eco). Debajo, <b>3 sensores de línea</b>. A los lados, <b>2 motores con ruedas</b>. Y arriba, el cerebro: la <b>micro:bit</b>, un ordenador pequeño con 25 luces y dos botones, A y B." },
        { k: 'Programa|Programa', t: 'El primer programa|El primer programa',
          robo: { w: { w: 120, h: 50, bot: [15, 25, 90], zones: [{ id: 'm', r: [66, 13, 24, 24], col: 'green', label: 'META|META' }] }, prog: 'start{ run:all,fwd,150 wait:4000 stop:all }' },
          x: "El Maqueen es programa amb blocs. Tot el que hi ha dins d'<b>en iniciar</b> es fa una vegada, quan s'encén el robot, <b>de dalt a baix</b>: engega els motors endavant, <b>espera</b> 4000 ms mentre avança i després els <b>atura</b>.|El Maqueen se programa con bloques. Todo lo que hay dentro de <b>al iniciar</b> se hace una vez, cuando se enciende el robot, <b>de arriba abajo</b>: enciende los motores hacia delante, <b>espera</b> 4000 ms mientras avanza y después los <b>para</b>.",
          tip: "1000 ms (mil·lisegons) són 1 segon. 4000 ms són 4 segons.|1000 ms (milisegundos) son 1 segundo. 4000 ms son 4 segundos." },
        { k: 'Compte!|¡Cuidado!', t: "Esperar no vol dir parar|Esperar no quiere decir parar",
          robo: { w: { w: 120, h: 50, bot: [15, 25, 90], walls: [[104, 8, 8, 34]], time: 7 }, prog: 'start{ run:all,fwd,150 wait:2000 }' },
          x: "Mentre espera, el robot <b>continua fent el que feia</b>. Aquest programa s'acaba sense cap «atura»… i els motors continuen girant fins que el robot xoca amb la caixa!|Mientras espera, el robot <b>sigue haciendo lo que hacía</b>. Este programa se termina sin ningún «para»… ¡y los motores siguen girando hasta que el robot choca con la caja!",
          bad: "Quan el programa s'acaba, el robot s'atura sol.|Cuando el programa se termina, el robot se para solo.", good: "Si no hi ha cap bloc «atura», els motors continuen girant.|Si no hay ningún bloque «para», los motores siguen girando." }
      ] },
      { k: 'quiz', ph: 'prova', q: 'Quina part del Maqueen fa de <b>cervell</b>?|¿Qué parte del Maqueen hace de <b>cerebro</b>?',
        opts: ['La micro:bit, on hi ha el programa|La micro:bit, donde está el programa', 'Els ultrasons del davant|Los ultrasonidos de delante', 'Les rodes i els motors|Las ruedas y los motores'], a: 0,
        ex: 'Els ultrasons són un sensor (senten) i els motors són actuadors (actuen). Qui decideix és el programa de la micro:bit.|Los ultrasonidos son un sensor (sienten) y los motores son actuadores (actúan). Quien decide es el programa de la micro:bit.' },
      { k: 'seq', ph: 'mans', q: 'Un robot aspirador troba una cadira pel camí. <b>Ordena</b> el que passa, des que la nota fins que continua netejant.|Un robot aspirador encuentra una silla en el camino. <b>Ordena</b> lo que pasa, desde que la nota hasta que sigue limpiando.',
        items: ['SENT: el sensor nota la pota de la cadira|SIENTE: el sensor nota la pata de la silla', 'PENSA: el programa decideix que ha de girar|PIENSA: el programa decide que tiene que girar', 'ACTUA: els motors fan girar el robot|ACTÚA: los motores hacen girar el robot', 'Torna a començar: avança i continua netejant|Vuelve a empezar: avanza y sigue limpiando'],
        ex: 'Sentir, pensar i actuar, una vegada i una altra: així funcionen tots els robots.|Sentir, pensar y actuar, una y otra vez: así funcionan todos los robots.' },
      { k: 'quiz', ph: 'prova', q: "Quin d'aquests és un <b>sensor</b> del Maqueen?|¿Cuál de estos es un <b>sensor</b> del Maqueen?",
        opts: ['Els ultrasons: noten si hi ha alguna cosa al davant|Los ultrasonidos: notan si hay algo delante', 'Els motors: fan girar les rodes|Los motores: hacen girar las ruedas', 'El brunzidor: fa sonar notes|El zumbador: hace sonar notas'], a: 0,
        ex: 'Un sensor <b>recull informació</b> del món. Els motors i el brunzidor <b>fan</b> coses: són actuadors.|Un sensor <b>recoge información</b> del mundo. Los motores y el zumbador <b>hacen</b> cosas: son actuadores.' },
      { k: 'unplug', ph: 'mans', ico: '🤖', title: 'El robot de dues persones|El robot de dos personas',
        t: "Amb algú de casa, en un espai lliure, sense res que es pugui trencar.|Con alguien de casa, en un espacio libre, sin nada que se pueda romper.",
        steps: ["Una persona fa de <b>motors</b>: tanca els ulls i només pot caminar a poc a poc endavant o quedar-se quieta.|Una persona hace de <b>motores</b>: cierra los ojos y solo puede caminar despacio hacia delante o quedarse quieta.",
          "L'altra fa de <b>sensors i cervell</b>: mira el camí i només pot dir «endavant» o «atura't».|La otra hace de <b>sensores y cerebro</b>: mira el camino y solo puede decir «adelante» o «para».",
          'Poseu un coixí a terra: el cervell ha de fer aturar els motors just abans de tocar-lo.|Poned un cojín en el suelo: el cerebro tiene que hacer parar los motores justo antes de tocarlo.',
          'Canvieu els papers. Qui ho ha tingut més difícil? Per què?|Cambiad los papeles. ¿Quién lo ha tenido más difícil? ¿Por qué?'],
        tip: 'Els motors sols no veuen res: sense sensors ni cervell, un robot va a cegues.|Los motores solos no ven nada: sin sensores ni cerebro, un robot va a ciegas.' },
      { k: 'story', ph: 'prova', who: 'numi',
        t: "Al simulador, el Maqueen es programa amb els mateixos blocs que a <b>MakeCode</b>, el programa que fareu servir amb el robot de l'aula. Avui en necessites tres:|En el simulador, el Maqueen se programa con los mismos bloques que en <b>MakeCode</b>, el programa que usaréis con el robot del aula. Hoy necesitas tres:",
        box: "<ul><li><b>motor … a velocitat …</b>: engega els motors.</li><li><b>espera … ms</b>: deixa passar el temps (el robot continua fent el que feia).</li><li><b>atura el motor</b>: para els motors.</li></ul>Tots van dins d'<b>en iniciar</b>, i el robot els fa en ordre, de dalt a baix.|<ul><li><b>motor … a velocidad …</b>: enciende los motores.</li><li><b>espera … ms</b>: deja pasar el tiempo (el robot sigue haciendo lo que hacía).</li><li><b>para el motor</b>: para los motores.</li></ul>Todos van dentro de <b>al iniciar</b>, y el robot los hace en orden, de arriba abajo." },
      { k: 'rpredict', ph: 'prova', q: 'Aquest robot avança durant 3 segons. <b>On acabarà?</b> Tria A, B o C i després executa el programa.|Este robot avanza durante 3 segundos. <b>¿Dónde terminará?</b> Elige A, B o C y después ejecuta el programa.',
        w: { w: 120, h: 60, bot: [15, 30, 90], walls: [[104, 12, 8, 36]], marks: { A: [36, 30], B: [62, 30], C: [94, 30] } }, scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:3000 stop:all }', a: 'B',
        ex: "L'espera de 3000 ms el fa avançar 3 segons i després «atura» para els motors: no arriba a la caixa.|La espera de 3000 ms lo hace avanzar 3 segundos y después «para» detiene los motores: no llega a la caja." },
      { k: 'rspot', ph: 'investiga', q: 'Aquest robot s\'atura massa aviat i no arriba a la meta. <b>Toca el bloc que cal canviar.</b>|Este robot se para demasiado pronto y no llega a la meta. <b>Toca el bloque que hay que cambiar.</b>',
        w: { w: 120, h: 60, bot: [15, 30, 90], zones: [{ id: 'm', r: [70, 18, 24, 24], col: 'green', label: 'META|META' }] }, scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:1000! stop:all }',
        yes: "Exacte! L'espera decideix quanta estona avança el robot.|¡Exacto! La espera decide cuánto rato avanza el robot.",
        ex: "És l'espera: 1000 ms és només 1 segon de camí. Amb una espera més llarga, el robot arribaria més lluny.|Es la espera: 1000 ms es solo 1 segundo de camino. Con una espera más larga, el robot llegaría más lejos." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de Maqueen, sense moure't del lloc! Quan algú digui «motors endavant», camina al lloc; «espera 3 segons», compta fins a 3 sense parar de caminar; «atura», queda't quiet/a com una estàtua. Repetiu-ho tres vegades, cada vegada més de pressa.|¡Haz de Maqueen, sin moverte del sitio! Cuando alguien diga «motores adelante», camina en el sitio; «espera 3 segundos», cuenta hasta 3 sin dejar de caminar; «para», quédate quieto/a como una estatua. Repetidlo tres veces, cada vez más deprisa." },
      { k: 'robo', ph: 'repte', q: '<b>El teu primer programa!</b> Porta el Maqueen fins a la <b>META</b> i fes que s\'hi aturi. Necessites tres blocs: motor, espera i atura.|<b>¡Tu primer programa!</b> Lleva el Maqueen hasta la <b>META</b> y haz que se pare allí. Necesitas tres bloques: motor, espera y para.',
        w: { w: 120, h: 60, bot: [15, 30, 90], zones: [{ id: 'm', r: [68, 18, 26, 24], col: 'green', label: 'META|META' }], goal: [{ k: 'zone', id: 'm', stop: true }, { k: 'nohit' }], env: [{ t: 9 }], time: 14 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:4300 stop:all }',
        hint: "Si s'atura abans de la meta, fes l'espera més llarga; si se'n passa, més curta. Prova amb uns 4000 ms.|Si se para antes de la meta, haz la espera más larga; si se pasa, más corta. Prueba con unos 4000 ms." },
      { k: 'robo', ph: 'repte', q: 'Ui! Aquest robot no s\'atura mai i acaba xocant amb la paret. <b>Arregla el programa</b> perquè s\'aturi a la zona de càrrega.|¡Uy! Este robot no se para nunca y acaba chocando con la pared. <b>Arregla el programa</b> para que se pare en la zona de carga.',
        w: { w: 120, h: 60, bot: [15, 30, 90], zones: [{ id: 'c', r: [50, 18, 24, 24], col: 'yellow', label: 'CÀRREGA|CARGA' }], goal: [{ k: 'zone', id: 'c', stop: true }, { k: 'nohit' }], env: [{ t: 7 }], time: 10 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:3000 }', sol: 'start{ run:all,fwd,150 wait:3000 stop:all }',
        hint: 'Falta un bloc al final del programa. Quin bloc fa parar els motors?|Falta un bloque al final del programa. ¿Qué bloque hace parar los motores?' },
      { k: 'robo', ph: 'repte', q: "Ara la meta és a l'altra punta del taller, just davant de la paret. Arriba-hi i atura't <b>sense tocar la paret</b>.|Ahora la meta está en la otra punta del taller, justo delante de la pared. Llega y párate <b>sin tocar la pared</b>.",
        w: { w: 140, h: 60, bot: [15, 30, 90], zones: [{ id: 'm', r: [106, 18, 26, 24], col: 'blue', label: 'META|META' }], goal: [{ k: 'zone', id: 'm', stop: true }, { k: 'nohit' }], env: [{ t: 11 }], time: 16 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:6700 stop:all }',
        hint: 'Pensa-ho així: a velocitat 150, en 4 segons feia uns 60 cm. Quant de temps li cal per fer-ne uns 100?|Piénsalo así: a velocidad 150, en 4 segundos hacía unos 60 cm. ¿Cuánto tiempo necesita para hacer unos 100?' },
      { k: 'rcreate', ph: 'crea', name: 'El bus del taller|El autobús del taller',
        q: "<b>Crea el teu programa!</b> El Maqueen fa de bus del taller: ha de fer <b>una parada</b> a la zona groga (s'hi atura una estona) i després continuar fins a la zona verda, on s'atura del tot. Tu decideixes les velocitats i els temps.|<b>¡Crea tu programa!</b> El Maqueen hace de autobús del taller: tiene que hacer <b>una parada</b> en la zona amarilla (se para un rato) y después seguir hasta la zona verde, donde se para del todo. Tú decides las velocidades y los tiempos.",
        crit: ["S'atura una estona a la parada groga|Se para un rato en la parada amarilla", 'Acaba aturat a la zona verda|Termina parado en la zona verde', 'No xoca amb res|No choca con nada'],
        w: { w: 140, h: 60, bot: [15, 30, 90], zones: [{ id: 'p', r: [48, 18, 22, 24], col: 'yellow', label: 'PARADA|PARADA' }, { id: 'f', r: [106, 18, 26, 24], col: 'green', label: 'FINAL|FINAL' }], goal: [{ k: 'zone', id: 'f', stop: true }, { k: 'nohit' }], env: [{ t: 16 }], time: 24 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:2800 stop:all wait:1500 run:all,fwd,150 wait:3800 stop:all }',
        // la parada: el robot ha d'estar quiet almenys mig segon dins la zona groga
        check(P) { const W = roboWorld(this.w), M = roboMachine(W, P), z = W.zones[0]; let q = 0;
          for (let i = 0; i < 2400; i++) { M.tick(); const S = M.S; if (roboInZone(S.x, S.y, z) && Math.abs(S.vl) < .3 && Math.abs(S.vr) < .3) { q += ROBO.DT; if (q >= .5) return null; } else q = 0; }
          return "Arriba al final, però no s'atura a la parada groga. Posa-hi un «atura» i una espera quan el robot sigui a la parada.|Llega al final, pero no se para en la parada amarilla. Pon un «para» y una espera cuando el robot esté en la parada."; } },
      { k: 'quiz', ph: 'tanca', q: 'Quines són les tres coses que fa sempre un robot?|¿Cuáles son las tres cosas que hace siempre un robot?',
        opts: ['Sent, pensa i actua|Siente, piensa y actúa', 'Parla, escolta i dorm|Habla, escucha y duerme', 'Corre, salta i neda|Corre, salta y nada'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: 'Un programa té «motor endavant» i «espera 2000 ms», però no té cap «atura». Què farà el robot?|Un programa tiene «motor adelante» y «espera 2000 ms», pero no tiene ningún «para». ¿Qué hará el robot?',
        opts: ['Continuarà avançant fins que xoqui o s\'apagui|Seguirá avanzando hasta que choque o se apague', "S'aturarà sol al cap de 2 segons|Se parará solo a los 2 segundos", 'No es mourà gens|No se moverá nada'], a: 0,
        ex: "L'espera només deixa passar el temps. Per parar els motors, cal el bloc «atura».|La espera solo deja pasar el tiempo. Para detener los motores, hace falta el bloque «para»." },
      { k: 'feel', ph: 'tanca' }
    ] },
  /* ---------- Sessió 2 · Motors i velocitat ---------- */
  { id: 'k1-2', t: 'Motors i velocitat|Motores y velocidad', min: 40, badge: 'k_motor',
    learn: ['La velocitat del motor va de 0 a 255: a 255, el Maqueen fa uns 29 cm cada segon.|La velocidad del motor va de 0 a 255: a 255, el Maqueen hace unos 29 cm cada segundo.',
      'Per sota de 30 el motor no té prou força i no es mou: és la zona morta.|Por debajo de 30 el motor no tiene fuerza suficiente y no se mueve: es la zona muerta.',
      'Cada motor pot anar endavant o enrere; amb la mateixa velocitat i el mateix temps, el robot torna on era.|Cada motor puede ir adelante o atrás; con la misma velocidad y el mismo tiempo, el robot vuelve a donde estaba.'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Recordes què fa el bloc <b>espera 2000 ms</b>?|¿Recuerdas qué hace el bloque <b>espera 2000 ms</b>?',
        opts: ['Deixa passar 2 segons i el robot continua fent el que feia|Deja pasar 2 segundos y el robot sigue haciendo lo que hacía', 'Para el robot durant 2 segons|Para el robot durante 2 segundos', 'Fa que el robot vagi el doble de ràpid|Hace que el robot vaya el doble de rápido'], a: 0 },
      { k: 'story', ph: 'missio', who: 'both', scene: 'lab', title: 'El banc de proves|El banco de pruebas',
        t: "Avui som al <b>laboratori</b> del taller, al banc de proves dels motors. Les preguntes del dia: què vol dir exactament <b>velocitat 150</b>? I per què, de vegades, un robot <b>no es mou</b> encara que el programa li ho mani?|Hoy estamos en el <b>laboratorio</b> del taller, en el banco de pruebas de los motores. Las preguntas del día: ¿qué quiere decir exactamente <b>velocidad 150</b>? ¿Y por qué, a veces, un robot <b>no se mueve</b> aunque el programa se lo mande?" },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Velocitat|Velocidad', t: 'Un número de 0 a 255|Un número de 0 a 255', anim: 'k1speed',
          x: "Al bloc del motor hi poses la <span class='hl'>velocitat</span>: un número de <b>0</b> (aturat) a <b>255</b> (al màxim). El Maqueen, a 255, fa uns <b>29 cm cada segon</b>; a 150, uns 15 cm; a 100, uns 9 cm.|En el bloque del motor pones la <span class='hl'>velocidad</span>: un número de <b>0</b> (parado) a <b>255</b> (al máximo). El Maqueen, a 255, hace unos <b>29 cm cada segundo</b>; a 150, unos 15 cm; a 100, unos 9 cm.",
          tip: 'Per què 255? Perquè la micro:bit envia la velocitat al xip dels motors en <b>un byte</b>: 8 bits, que compten de 0 a 255.|¿Por qué 255? Porque la micro:bit envía la velocidad al chip de los motores en <b>un byte</b>: 8 bits, que cuentan de 0 a 255.' },
        { k: 'Zona morta|Zona muerta', t: 'Massa fluix: no es mou!|Demasiado flojo: ¡no se mueve!', anim: 'k1dead',
          x: "Per sota de velocitat <b>30</b>, el motor no té prou força per vèncer el fregament de les rodes i dels engranatges: fa un brunzit, però <b>el robot no es mou</b>. És la <span class='hl'>zona morta</span>, i al robot de veritat passa igual.|Por debajo de velocidad <b>30</b>, el motor no tiene fuerza suficiente para vencer el rozamiento de las ruedas y de los engranajes: zumba, pero <b>el robot no se mueve</b>. Es la <span class='hl'>zona muerta</span>, y en el robot de verdad pasa igual.",
          bad: 'Velocitat 20 és molt lent, però es mou.|Velocidad 20 es muy lento, pero se mueve.', good: 'Velocitat 20 és dins la zona morta: no es mou.|Velocidad 20 está dentro de la zona muerta: no se mueve.' },
        { k: 'Endavant i enrere|Adelante y atrás', t: 'Les dues direccions|Las dos direcciones',
          robo: { w: { w: 120, h: 50, bot: [20, 25, 90], zones: [{ id: 'b', r: [8, 13, 24, 24], col: 'blue', label: 'BASE|BASE' }] }, prog: 'start{ run:all,fwd,150 wait:3000 stop:all wait:500 run:all,back,150 wait:3000 stop:all }' },
          x: "Al bloc del motor també tries la direcció: <b>endavant</b> o <b>enrere</b>. Si torna enrere a la mateixa velocitat i durant el mateix temps, el robot desfà el camí i torna on era.|En el bloque del motor también eliges la dirección: <b>adelante</b> o <b>atrás</b>. Si vuelve atrás a la misma velocidad y durante el mismo tiempo, el robot deshace el camino y vuelve a donde estaba." },
        { k: 'Canvis de marxa|Cambios de marcha', t: 'A poc a poc i després de pressa|Despacio y después deprisa',
          robo: { w: { w: 140, h: 50, bot: [15, 25, 90], zones: [{ id: 'e', r: [28, 9, 30, 32], col: 'yellow', label: 'LENT|LENTO' }] }, prog: 'start{ run:all,fwd,60 wait:3500 run:all,fwd,255 wait:2500 stop:all }' },
          x: "Pots posar un bloc de motor nou enmig del camí: el robot no s'atura, només <b>canvia de velocitat</b>. Fixa't que tarda una mica a accelerar i a frenar: és la <b>inèrcia</b>, i en el robot real també hi és.|Puedes poner un bloque de motor nuevo en medio del camino: el robot no se para, solo <b>cambia de velocidad</b>. Fíjate en que tarda un poco en acelerar y en frenar: es la <b>inercia</b>, y en el robot real también está.",
          tip: 'Com més de pressa va, més li costa aturar-se just on vols.|Cuanto más deprisa va, más le cuesta pararse justo donde quieres.' }
      ] },
      { k: 'seq', ph: 'mans', q: 'Ordena aquests motors del <b>més lent</b> al <b>més ràpid</b>.|Ordena estos motores del <b>más lento</b> al <b>más rápido</b>.',
        items: ['Velocitat 20 (no es mou: zona morta)|Velocidad 20 (no se mueve: zona muerta)', 'Velocitat 60|Velocidad 60', 'Velocitat 150|Velocidad 150', 'Velocitat 255|Velocidad 255'],
        ex: 'Com més gran és el número, més ràpid va. Però per sota de 30, res de res!|Cuanto más grande es el número, más rápido va. ¡Pero por debajo de 30, nada de nada!' },
      { k: 'unplug', ph: 'mans', ico: '⏱️', title: 'El banc de proves humà|El banco de pruebas humano',
        t: 'Amb algú de casa, un passadís lliure, tres mitjons i un rellotge o un mòbil per comptar el temps.|Con alguien de casa, un pasillo libre, tres calcetines y un reloj o un móvil para contar el tiempo.',
        steps: ["Una persona fa de robot i l'altra de programador/a. El programador/a diu una velocitat: <b>60</b> (passos de formiga), <b>150</b> (caminar normal) o <b>255</b> (caminar molt de pressa, sense córrer).|Una persona hace de robot y la otra de programador/a. El programador/a dice una velocidad: <b>60</b> (pasos de hormiga), <b>150</b> (caminar normal) o <b>255</b> (caminar muy deprisa, sin correr).",
          "El robot camina durant 5 segons exactes i s'atura. Deixeu un mitjó on ha arribat.|El robot camina durante 5 segundos exactos y se para. Dejad un calcetín donde ha llegado.",
          'Repetiu-ho amb les tres velocitats, sempre des del mateix lloc.|Repetidlo con las tres velocidades, siempre desde el mismo sitio.',
          "I amb velocitat <b>20</b>? El robot no es mou: zona morta! Compareu on han quedat els mitjons.|¿Y con velocidad <b>20</b>? El robot no se mueve: ¡zona muerta! Comparad dónde han quedado los calcetines."],
        tip: 'Mateix temps i més velocitat: més distància. Ho mesurarem amb el Maqueen a la unitat 2.|Mismo tiempo y más velocidad: más distancia. Lo mediremos con el Maqueen en la unidad 2.' },
      { k: 'rpredict', ph: 'prova', q: 'El robot va endavant 3 segons i després enrere 1,5 segons, a la mateixa velocitat. <b>On acabarà?</b>|El robot va adelante 3 segundos y después atrás 1,5 segundos, a la misma velocidad. <b>¿Dónde terminará?</b>',
        w: { w: 120, h: 60, bot: [15, 30, 90], marks: { A: [38, 30], B: [62, 30], C: [86, 30] } }, scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:3000 run:all,back,150 wait:1500 stop:all }', a: 'A',
        ex: 'Avança 3 segons i torna enrere la meitat del temps: desfà la meitat del camí.|Avanza 3 segundos y vuelve atrás la mitad del tiempo: deshace la mitad del camino.' },
      { k: 'rpredict', ph: 'prova', q: 'Ara va <b>2 segons</b> a velocitat <b>255</b>. On acabarà?|Ahora va <b>2 segundos</b> a velocidad <b>255</b>. ¿Dónde terminará?',
        w: { w: 120, h: 60, bot: [15, 30, 90], marks: { A: [33, 30], B: [52, 30], C: [74, 30] } }, scripts: ['start'],
        prog: 'start{ run:all,fwd,255 wait:2000 stop:all }', a: 'C',
        ex: 'A 255 va al màxim: uns 29 cm cada segon, gairebé 60 cm en 2 segons.|A 255 va al máximo: unos 29 cm cada segundo, casi 60 cm en 2 segundos.' },
      { k: 'quiz', ph: 'investiga', q: 'Un programa posa els dos motors a <b>velocitat 20</b> durant 5 segons. Què fa el robot?|Un programa pone los dos motores a <b>velocidad 20</b> durante 5 segundos. ¿Qué hace el robot?',
        opts: ['No es mou: 20 és dins la zona morta|No se mueve: 20 está dentro de la zona muerta', 'Avança molt a poc a poc|Avanza muy despacio', 'Va enrere|Va hacia atrás'], a: 0,
        ex: 'El motor fa un brunzit, però no té prou força per moure les rodes.|El motor zumba, pero no tiene fuerza suficiente para mover las ruedas.' },
      { k: 'rspot', ph: 'investiga', q: 'La Laia vol que el robot arribi a la meta, però <b>no es mou gens</b>. Pots executar-lo per veure-ho. <b>Toca el bloc que falla.</b>|Laia quiere que el robot llegue a la meta, pero <b>no se mueve nada</b>. Puedes ejecutarlo para verlo. <b>Toca el bloque que falla.</b>',
        w: { w: 120, h: 60, bot: [15, 30, 90], zones: [{ id: 'm', r: [70, 18, 24, 24], col: 'green', label: 'META|META' }] }, scripts: ['start'],
        prog: 'start{ run:all,fwd,20! wait:4000 stop:all }',
        yes: 'Molt bé! Velocitat 20 és dins la zona morta.|¡Muy bien! Velocidad 20 está dentro de la zona muerta.',
        ex: 'És el motor: a velocitat 20 no té prou força. Amb 150 arribaria a la meta.|Es el motor: a velocidad 20 no tiene fuerza suficiente. Con 150 llegaría a la meta.' },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de motor, al lloc! Algú diu un número: <b>20</b> → quiet/a (zona morta!), <b>80</b> → marxa lenta, <b>150</b> → marxa normal, <b>255</b> → marxa molt ràpida. I ara la paraula màgica: <b>enrere</b>! Dos passets enrere, amb compte.|¡Haz de motor, en el sitio! Alguien dice un número: <b>20</b> → quieto/a (¡zona muerta!), <b>80</b> → marcha lenta, <b>150</b> → marcha normal, <b>255</b> → marcha muy rápida. Y ahora la palabra mágica: ¡<b>atrás</b>! Dos pasitos atrás, con cuidado." },
      { k: 'robo', ph: 'repte', q: 'Aquest robot té <b>3 segons</b> per arribar a la zona de càrrega, però no es mou. <b>Canvia la velocitat</b> perquè hi arribi i s\'hi aturi.|Este robot tiene <b>3 segundos</b> para llegar a la zona de carga, pero no se mueve. <b>Cambia la velocidad</b> para que llegue y se pare allí.',
        w: { w: 120, h: 60, bot: [15, 30, 90], zones: [{ id: 'c', r: [50, 18, 24, 24], col: 'yellow', label: 'CÀRREGA|CARGA' }], goal: [{ k: 'zone', id: 'c', stop: true }, { k: 'nohit' }], env: [{ t: 6 }], time: 10 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'], max: 3,
        prog: 'start{ run:all,fwd,20 wait:3000 stop:all }', sol: 'start{ run:all,fwd,150 wait:3000 stop:all }',
        hint: 'Amb 20 no es mou. Toca el número de la velocitat i prova un número més gran, com 150.|Con 20 no se mueve. Toca el número de la velocidad y prueba un número más grande, como 150.' },
      { k: 'robo', ph: 'repte', q: "Porta l'eina fins al <b>punt 1</b>, al costat de la caixa, i <b>torna enrere</b> fins a la base sense girar. Has d'acabar aturat a la base.|Lleva la herramienta hasta el <b>punto 1</b>, al lado de la caja, y <b>vuelve atrás</b> hasta la base sin girar. Tienes que terminar parado en la base.",
        w: { w: 120, h: 60, bot: [18, 30, 90], walls: [[104, 12, 8, 36]], zones: [{ id: 'b', r: [6, 18, 24, 24], col: 'blue', label: 'BASE|BASE' }], goal: [{ k: 'cps', pts: [[88, 30]], r: 8 }, { k: 'zone', id: 'b', stop: true }, { k: 'nohit' }], env: [{ t: 13 }], time: 18 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:4500 stop:all run:all,back,150 wait:4500 stop:all }',
        hint: 'Primer endavant fins al punt 1. Després, el mateix temps <b>enrere</b> per tornar al lloc.|Primero adelante hasta el punto 1. Después, el mismo tiempo <b>atrás</b> para volver al sitio.' },
      { k: 'robo', ph: 'repte', q: "<b>Contrarellotge!</b> El robot ha d'arribar a la meta i aturar-s'hi en <b>menys de 5 segons</b>. Tria bé la velocitat.|<b>¡Contrarreloj!</b> El robot tiene que llegar a la meta y pararse en <b>menos de 5 segundos</b>. Elige bien la velocidad.",
        w: { w: 140, h: 60, bot: [15, 30, 90], zones: [{ id: 'm', r: [100, 18, 26, 24], col: 'green', label: 'META|META' }], goal: [{ k: 'at', t: 5, zone: 'm', moving: false, why: "Al segon 5 el robot encara no és aturat a la meta: ha d'arribar-hi abans, més de pressa.|En el segundo 5 el robot todavía no está parado en la meta: tiene que llegar antes, más deprisa." }, { k: 'zone', id: 'm', stop: true }, { k: 'nohit' }], time: 12 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,255 wait:3200 stop:all }',
        hint: 'A velocitat 150 tarda més de 6 segons. Quina és la velocitat màxima del motor?|A velocidad 150 tarda más de 6 segundos. ¿Cuál es la velocidad máxima del motor?' },
      { k: 'robo', ph: 'repte', q: "<b>El repte del cargol.</b> El robot ha d'anar tan a poc a poc que, al segon 5, <b>encara es mogui</b> però no hagi sortit de la zona groga. Busca la velocitat més baixa que el fa moure's!|<b>El reto del caracol.</b> El robot tiene que ir tan despacio que, en el segundo 5, <b>todavía se mueva</b> pero no haya salido de la zona amarilla. ¡Busca la velocidad más baja que lo hace moverse!",
        w: { w: 120, h: 60, bot: [18, 30, 90], zones: [{ id: 'z', r: [10, 16, 32, 28], col: 'yellow', label: 'CARGOL|CARACOL' }], goal: [{ k: 'at', t: 5, moving: true, zone: 'z', why: "Al segon 5 el robot ha de continuar movent-se i ser dins la zona groga: ni quiet, ni massa ràpid.|En el segundo 5 el robot tiene que seguir moviéndose y estar dentro de la zona amarilla: ni quieto, ni demasiado rápido." }], time: 9 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,45 wait:6000 stop:all }',
        hint: 'Amb 20 es queda quiet (zona morta) i amb 100 surt de la zona. Prova números entre 30 i 70.|Con 20 se queda quieto (zona muerta) y con 100 sale de la zona. Prueba números entre 30 y 70.' },
      { k: 'rcreate', ph: 'crea', name: "El carrer de l'escola|La calle del colegio",
        q: "<b>Crea-ho tu!</b> Davant de l'escola, els vehicles van <b>a poc a poc</b>. Programa el robot perquè passi per la zona de l'escola a velocitat <b>100 o menys</b> i després acceleri (<b>200 o més</b>) fins a la meta, on s'ha d'aturar.|<b>¡Créalo tú!</b> Delante del colegio, los vehículos van <b>despacio</b>. Programa el robot para que pase por la zona del colegio a velocidad <b>100 o menos</b> y después acelere (<b>200 o más</b>) hasta la meta, donde tiene que pararse.",
        crit: ["Passa per l'escola a 100 o menys|Pasa por el colegio a 100 o menos", 'Després accelera a 200 o més|Después acelera a 200 o más', 'Acaba aturat a la meta sense xocar|Termina parado en la meta sin chocar'],
        w: { w: 140, h: 60, bot: [15, 30, 90], zones: [{ id: 'e', r: [28, 12, 42, 36], col: 'yellow', label: 'ESCOLA|COLEGIO' }, { id: 'm', r: [108, 18, 24, 24], col: 'green', label: 'META|META' }], goal: [{ k: 'zone', id: 'm', stop: true }, { k: 'nohit' }], env: [{ t: 14 }], time: 22 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,100 wait:6400 run:all,fwd,255 wait:1500 stop:all }',
        // dins la zona de l'escola, com a molt la velocitat d'un motor a ~105; i en algun moment, 200 o més
        check(P) { const W = roboWorld(this.w), M = roboMachine(W, P), z = W.zones[0], fast = (ROBO.VMAX * (200 - ROBO.DEAD) / (255 - ROBO.DEAD)) - .3; let top = 0, ok = false;
          for (let i = 0; i < 2400; i++) { M.tick(); const S = M.S, v = Math.max(Math.abs(S.vl), Math.abs(S.vr)); if (roboInZone(S.x, S.y, z) && v > 9.8) return "El robot passa massa de pressa per davant de l'escola: hi ha d'anar a velocitat 100 o menys.|El robot pasa demasiado deprisa por delante del colegio: tiene que ir a velocidad 100 o menos."; top = Math.max(top, v); }
          return top >= fast ? null : 'Molt prudent! Però després de l\'escola ha d\'accelerar a velocitat 200 o més.|¡Muy prudente! Pero después del colegio tiene que acelerar a velocidad 200 o más.'; } },
      { k: 'quiz', ph: 'tanca', q: 'Quin és el número de velocitat <b>més gran</b> que pots posar al motor?|¿Cuál es el número de velocidad <b>más grande</b> que puedes poner en el motor?',
        opts: ['255|255', '100|100', '1000|1000'], a: 0, ex: 'De 0 a 255: a 255, uns 29 cm cada segon.|De 0 a 255: a 255, unos 29 cm cada segundo.' },
      { k: 'quiz', ph: 'tanca', q: 'Quants mil·lisegons és <b>mig segon</b>?|¿Cuántos milisegundos es <b>medio segundo</b>?',
        opts: ['500 ms|500 ms', '50 ms|50 ms', '5000 ms|5000 ms'], a: 0, ex: '1 segon són 1000 ms; la meitat, 500 ms.|1 segundo son 1000 ms; la mitad, 500 ms.' },
      { k: 'feel', ph: 'tanca' }
    ] },
  /* ---------- Sessió 3 · Girar sobre si mateix ---------- */
  { id: 'k1-3', t: 'Girar sobre si mateix|Girar sobre sí mismo', min: 45, badge: 'k_gir',
    learn: ['El robot gira quan les rodes van a velocitats diferents: cap al costat de la roda més lenta.|El robot gira cuando las ruedas van a velocidades diferentes: hacia el lado de la rueda más lenta.',
      'Una roda endavant i l\'altra enrere: gira sobre si mateix (90° en uns 590 ms a velocitat 100). Amb una sola roda, gira en arc.|Una rueda adelante y la otra atrás: gira sobre sí mismo (90° en unos 590 ms a velocidad 100). Con una sola rueda, gira en arco.',
      'Calibrar és provar, mesurar i ajustar fins que el gir surt bé al robot de veritat.|Calibrar es probar, medir y ajustar hasta que el giro sale bien en el robot de verdad.'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Per sota de quina velocitat el motor del Maqueen <b>no es mou</b>?|¿Por debajo de qué velocidad el motor del Maqueen <b>no se mueve</b>?',
        opts: ['30|30', '100|100', '255|255'], a: 0, ex: 'És la zona morta: el motor no té prou força.|Es la zona muerta: el motor no tiene fuerza suficiente.' },
      { k: 'story', ph: 'missio', who: 'both', scene: 'moll', title: 'Al port|En el puerto',
        t: "Ens n'anem al <b>port</b>! Els robots del moll porten caixes d'un vaixell a l'altre, però el camí no és recte: cal <b>girar</b> a cada cantonada. Avui descobriràs com gira un robot que no té volant.|¡Nos vamos al <b>puerto</b>! Los robots del muelle llevan cajas de un barco a otro, pero el camino no es recto: hay que <b>girar</b> en cada esquina. Hoy descubrirás cómo gira un robot que no tiene volante." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Sense volant|Sin volante', t: 'Com gira un robot de dues rodes?|¿Cómo gira un robot de dos ruedas?', anim: 'k1spin',
          x: "El Maqueen no té volant: gira fent anar les rodes <b>a velocitats diferents</b>. Si les dues van igual, va recte. Si una va més a poc a poc (o enrere), el robot es tomba cap al costat d'aquesta roda.|El Maqueen no tiene volante: gira haciendo ir las ruedas <b>a velocidades diferentes</b>. Si las dos van igual, va recto. Si una va más despacio (o hacia atrás), el robot se gira hacia el lado de esa rueda.",
          tip: 'Les excavadores i els tancs giren de la mateixa manera: es diu <b>tracció diferencial</b>.|Las excavadoras y los tanques giran de la misma manera: se llama <b>tracción diferencial</b>.' },
        { k: 'Sobre si mateix|Sobre sí mismo', t: "Una endavant i l'altra enrere|Una adelante y la otra atrás",
          robo: { w: { w: 100, h: 60, bot: [50, 30, 90] }, prog: 'start{ run:L,fwd,100 run:R,back,100 wait:590 stop:all wait:700 run:L,fwd,100 run:R,back,100 wait:590 stop:all wait:700 run:L,fwd,100 run:R,back,100 wait:590 stop:all wait:700 run:L,fwd,100 run:R,back,100 wait:590 stop:all }' },
          x: "Si el motor <b>esquerre</b> va endavant i el <b>dret</b> enrere, el robot gira <b>sense moure's del lloc</b>, cap a la dreta. A velocitat 100, un quart de volta (90°) tarda uns <b>590 ms</b>. Quatre quarts de volta… i torna a mirar on mirava!|Si el motor <b>izquierdo</b> va adelante y el <b>derecho</b> atrás, el robot gira <b>sin moverse del sitio</b>, hacia la derecha. A velocidad 100, un cuarto de vuelta (90°) tarda unos <b>590 ms</b>. Cuatro cuartos de vuelta… ¡y vuelve a mirar donde miraba!",
          tip: "Per girar a l'esquerra, a l'inrevés: l'esquerre enrere i el dret endavant.|Para girar a la izquierda, al revés: el izquierdo atrás y el derecho adelante." },
        { k: 'En arc|En arco', t: 'Girar amb una sola roda|Girar con una sola rueda',
          robo: { w: { w: 100, h: 60, bot: [30, 42, 90] }, prog: 'start{ run:L,fwd,100 wait:1180 stop:all wait:700 run:all,fwd,120 wait:2500 stop:all }' },
          x: "Si només va <b>una roda</b>, el robot gira al voltant de la que està aturada i fa un <b>arc</b>. És un gir més suau, però més lent: a velocitat 100, 90° tarden uns <b>1180 ms</b>, el doble que sobre si mateix.|Si solo va <b>una rueda</b>, el robot gira alrededor de la que está parada y hace un <b>arco</b>. Es un giro más suave, pero más lento: a velocidad 100, 90° tardan unos <b>1180 ms</b>, el doble que sobre sí mismo." },
        { k: 'Compte!|¡Cuidado!', t: 'Cada robot és una mica diferent|Cada robot es un poco diferente', anim: 'k1calib',
          x: "Al robot de veritat, el mateix programa pot girar 80° o 100°: depèn de les piles, del terra i de cada motor. Per això cal <span class='hl'>calibrar</span>: proves el gir, el mesures i ajustes l'espera fins que surt bé.|En el robot de verdad, el mismo programa puede girar 80° o 100°: depende de las pilas, del suelo y de cada motor. Por eso hay que <span class='hl'>calibrar</span>: pruebas el giro, lo mides y ajustas la espera hasta que sale bien.",
          bad: 'Si al simulador gira 90°, al robot de veritat sortirà exactament igual.|Si en el simulador gira 90°, en el robot de verdad saldrá exactamente igual.', good: "Al robot de veritat, prova el gir i ajusta l'espera.|En el robot de verdad, prueba el giro y ajusta la espera." }
      ] },
      { k: 'quiz', ph: 'prova', q: 'Motor <b>esquerre endavant</b> i motor <b>dret enrere</b>. Cap on gira el robot?|Motor <b>izquierdo adelante</b> y motor <b>derecho atrás</b>. ¿Hacia dónde gira el robot?',
        opts: ["Cap a la dreta, sense moure's del lloc|Hacia la derecha, sin moverse del sitio", "Cap a l'esquerra, sense moure's del lloc|Hacia la izquierda, sin moverse del sitio", 'Va recte endavant|Va recto adelante'], a: 0,
        ex: 'Gira cap al costat de la roda que va enrere: la dreta.|Gira hacia el lado de la rueda que va atrás: la derecha.' },
      { k: 'unplug', ph: 'mans', ico: '👫', title: 'Fes de rodes|Haz de ruedas',
        t: "Amb algú de casa, en un espai lliure. Poseu-vos un al costat de l'altre i agafeu-vos del braç: sou les dues rodes d'un robot.|Con alguien de casa, en un espacio libre. Poneos uno al lado del otro y cogeos del brazo: sois las dos ruedas de un robot.",
        steps: ['Camineu tots dos endavant al mateix ritme: el robot va recte.|Caminad los dos hacia delante al mismo ritmo: el robot va recto.',
          "Ara la persona de l'esquerra fa passets endavant i la de la dreta, enrere: gireu sobre el lloc!|Ahora la persona de la izquierda da pasitos hacia delante y la de la derecha, hacia atrás: ¡giráis sobre el sitio!",
          "Després, la de la dreta es queda quieta i l'altra camina endavant: feu un arc al voltant de la que està quieta.|Después, la de la derecha se queda quieta y la otra camina hacia delante: hacéis un arco alrededor de la que está quieta.",
          'Quin gir ocupa menys espai? Quin és més suau?|¿Qué giro ocupa menos espacio? ¿Cuál es más suave?'],
        tip: 'A poc a poc i sense estirar: les rodes d\'un robot no s\'empenyen!|Despacio y sin tirar: ¡las ruedas de un robot no se empujan!' },
      { k: 'seq', ph: 'mans', q: 'Ordena els passos per <b>calibrar</b> un gir de 90° al robot de veritat.|Ordena los pasos para <b>calibrar</b> un giro de 90° en el robot de verdad.',
        items: ['Programa el gir amb una espera de prova (590 ms)|Programa el giro con una espera de prueba (590 ms)', 'Prova el programa al robot|Prueba el programa en el robot', "Mesura l'angle que ha girat|Mide el ángulo que ha girado", "Si s'ha passat, escurça l'espera; si no hi arriba, allarga-la|Si se ha pasado, acorta la espera; si no llega, alárgala", 'Torna-ho a provar fins que surti 90°|Vuelve a probarlo hasta que salga 90°'],
        ex: 'Provar, mesurar, ajustar i tornar a provar: així treballen els enginyers de robots.|Probar, medir, ajustar y volver a probar: así trabajan los ingenieros de robots.' },
      { k: 'rpredict', ph: 'prova', q: 'El robot mira cap a la dreta de la pantalla. Gira amb l\'<b>esquerre endavant</b> i el <b>dret enrere</b>, i després avança. <b>On acabarà?</b>|El robot mira hacia la derecha de la pantalla. Gira con el <b>izquierdo adelante</b> y el <b>derecho atrás</b>, y después avanza. <b>¿Dónde terminará?</b>',
        w: { w: 120, h: 80, bot: [30, 40, 90], marks: { A: [30, 10], B: [30, 71], C: [61, 40] } }, scripts: ['start'],
        prog: 'start{ run:L,fwd,100 run:R,back,100 wait:590 stop:all wait:300 run:all,fwd,150 wait:2000 stop:all }', a: 'B',
        ex: "Gira 90° cap a la seva dreta: si mirava cap a la dreta de la pantalla, ara mira avall.|Gira 90° hacia su derecha: si miraba hacia la derecha de la pantalla, ahora mira hacia abajo." },
      { k: 'rpredict', ph: 'prova', q: 'Ara només funciona el motor <b>dret</b>, endavant, i després avança. <b>On acabarà?</b>|Ahora solo funciona el motor <b>derecho</b>, adelante, y después avanza. <b>¿Dónde terminará?</b>',
        w: { w: 120, h: 80, bot: [30, 46, 90], marks: { A: [33, 12], B: [33, 74], C: [62, 46] } }, scripts: ['start'],
        prog: 'start{ run:R,fwd,100 wait:1180 stop:all wait:300 run:all,fwd,150 wait:2000 stop:all }', a: 'A',
        ex: "Només va la roda dreta: el robot gira al voltant de l'esquerra, cap a l'esquerra, i queda mirant amunt.|Solo va la rueda derecha: el robot gira alrededor de la izquierda, hacia la izquierda, y queda mirando hacia arriba." },
      { k: 'rspot', ph: 'investiga', q: 'Aquest robot havia de fer un quart de volta, però en fa <b>mitja</b>. <b>Toca el bloc que cal canviar.</b>|Este robot tenía que dar un cuarto de vuelta, pero da <b>media</b>. <b>Toca el bloque que hay que cambiar.</b>',
        w: { w: 100, h: 60, bot: [50, 30, 90] }, scripts: ['start'],
        prog: 'start{ run:L,fwd,100 run:R,back,100 wait:1180! stop:all }',
        yes: "Exacte! L'espera decideix quant gira.|¡Exacto! La espera decide cuánto gira.",
        ex: "És l'espera: 1180 ms a velocitat 100 fan 180°. Per a 90°, cal la meitat: uns 590 ms.|Es la espera: 1180 ms a velocidad 100 hacen 180°. Para 90°, hace falta la mitad: unos 590 ms." },
      { k: 'move', ph: 'pausa', secs: 30, t: "Gira com el Maqueen! Braços estirats com si fossin dues rodes: fes <b>un quart de volta</b> a la dreta, un altre, un altre i un altre… On mires ara? Ara fes un <b>arc</b>: un peu quiet i l'altre camina al seu voltant.|¡Gira como el Maqueen! Brazos estirados como si fueran dos ruedas: da <b>un cuarto de vuelta</b> a la derecha, otro, otro y otro… ¿Dónde miras ahora? Ahora haz un <b>arco</b>: un pie quieto y el otro camina a su alrededor." },
      { k: 'robo', ph: 'repte', q: '<b>Quart de volta.</b> El robot ha de quedar mirant cap a la porta del magatzem (avall a la pantalla) i aturat. Fes-lo girar sobre si mateix.|<b>Cuarto de vuelta.</b> El robot tiene que quedar mirando hacia la puerta del almacén (abajo en la pantalla) y parado. Hazlo girar sobre sí mismo.',
        w: { w: 100, h: 70, bot: [50, 30, 90], zones: [{ id: 'p', r: [36, 56, 28, 14], col: 'blue', label: 'PORTA|PUERTA' }], goal: [{ k: 'face', h: 180, tol: 12 }, { k: 'stopped' }, { k: 'nohit' }], env: [{ t: 5 }], time: 8 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:L,fwd,100 run:R,back,100 wait:590 stop:all }',
        hint: "Motor esquerre endavant i motor dret enrere, tots dos a velocitat 100. Prova una espera d'uns 600 ms i ajusta-la.|Motor izquierdo adelante y motor derecho atrás, los dos a velocidad 100. Prueba una espera de unos 600 ms y ajústala." },
      { k: 'robo', ph: 'repte', q: "Porta la caixa al <b>moll B</b>: avança fins a la cantonada, gira a l'esquerra i continua fins a la zona.|Lleva la caja al <b>muelle B</b>: avanza hasta la esquina, gira a la izquierda y sigue hasta la zona.",
        w: { w: 120, h: 80, bot: [18, 62, 90], walls: [[28, 6, 46, 40]], zones: [{ id: 'm', r: [78, 8, 26, 24], col: 'green', label: 'MOLL B|MUELLE B' }], goal: [{ k: 'zone', id: 'm', stop: true }, { k: 'nohit' }], env: [{ t: 13 }], time: 18 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:4700 stop:all run:L,back,100 run:R,fwd,100 wait:590 stop:all run:all,fwd,150 wait:2700 stop:all }',
        hint: "Fes-ho a trossos: primer el tram recte fins sota la zona verda, després el gir a l'esquerra (esquerre enrere, dret endavant) i, al final, l'últim tram.|Hazlo a trozos: primero el tramo recto hasta debajo de la zona verde, después el giro a la izquierda (izquierdo atrás, derecho adelante) y, al final, el último tramo." },
      { k: 'robo', ph: 'repte', q: "Deixa el paquet al <b>punt 1</b>, fes <b>mitja volta</b> i torna a la base anant <b>endavant</b> (mirant cap a la base).|Deja el paquete en el <b>punto 1</b>, da <b>media vuelta</b> y vuelve a la base yendo <b>adelante</b> (mirando hacia la base).",
        w: { w: 120, h: 60, bot: [20, 30, 90], zones: [{ id: 'b', r: [8, 18, 24, 24], col: 'blue', label: 'BASE|BASE' }], goal: [{ k: 'cps', pts: [[86, 30]], r: 8 }, { k: 'zone', id: 'b', stop: true }, { k: 'face', h: 270, tol: 20 }, { k: 'nohit' }], env: [{ t: 15 }], time: 20 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:4300 stop:all run:L,fwd,100 run:R,back,100 wait:1180 stop:all run:all,fwd,150 wait:4300 stop:all }',
        hint: 'Mitja volta són dos quarts de volta. Si un quart tarda uns 590 ms, quant tarda mitja?|Media vuelta son dos cuartos de vuelta. Si un cuarto tarda unos 590 ms, ¿cuánto tarda media?' },
      { k: 'robo', ph: 'repte', q: "<b>El passadís de caixes.</b> Fes-lo passar entre les piles de caixes fins al moll C. Compta els girs: n'hi ha dos!|<b>El pasillo de cajas.</b> Hazlo pasar entre las pilas de cajas hasta el muelle C. Cuenta los giros: ¡hay dos!",
        w: { w: 140, h: 80, bot: [15, 20, 90], walls: [[30, 34, 25, 46], [80, 0, 25, 46]], zones: [{ id: 'm', r: [104, 48, 26, 24], col: 'green', label: 'MOLL C|MUELLE C' }], goal: [{ k: 'zone', id: 'm', stop: true }, { k: 'nohit' }], env: [{ t: 16 }], time: 22 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:3200 stop:all run:L,fwd,100 run:R,back,100 wait:590 stop:all run:all,fwd,150 wait:2600 stop:all run:L,back,100 run:R,fwd,100 wait:590 stop:all run:all,fwd,150 wait:3300 stop:all }',
        hint: 'Tram, gir a la dreta, tram, gir a l\'esquerra, tram. Prova el programa cada vegada que afegeixes un tros.|Tramo, giro a la derecha, tramo, giro a la izquierda, tramo. Prueba el programa cada vez que añades un trozo.' },
      { k: 'rcreate', ph: 'crea', name: 'La ruta del port|La ruta del puerto',
        q: "<b>Dissenya la teva ruta!</b> El robot ha de passar pels <b>dos vaixells</b> (punts 1 i 2) en ordre i acabar aturat al <b>garatge</b>, sense tocar el magatzem del mig. Pots girar sobre si mateix, en arc o de les dues maneres: tu tries.|<b>¡Diseña tu ruta!</b> El robot tiene que pasar por los <b>dos barcos</b> (puntos 1 y 2) en orden y terminar parado en el <b>garaje</b>, sin tocar el almacén del medio. Puedes girar sobre sí mismo, en arco o de las dos maneras: tú eliges.",
        crit: ['Passa pels punts 1 i 2 en ordre|Pasa por los puntos 1 y 2 en orden', 'Fa girs sobre si mateix o en arc|Hace giros sobre sí mismo o en arco', 'Acaba aturat al garatge sense xocar|Termina parado en el garaje sin chocar'],
        w: { w: 140, h: 80, bot: [15, 65, 90], walls: [[50, 30, 40, 20]], zones: [{ id: 'g', r: [8, 6, 26, 24], col: 'purple', label: 'GARATGE|GARAJE' }], goal: [{ k: 'cps', pts: [[110, 65], [110, 18]], r: 9 }, { k: 'zone', id: 'g', stop: true }, { k: 'nohit' }], env: [{ t: 22 }], time: 30 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:6100 stop:all run:L,back,100 run:R,fwd,100 wait:590 stop:all run:all,fwd,150 wait:3000 stop:all run:L,back,100 run:R,fwd,100 wait:590 stop:all run:all,fwd,150 wait:5700 stop:all }' },
      { k: 'quiz', ph: 'tanca', q: 'Per girar <b>sobre si mateix</b>, com han d\'anar les dues rodes?|Para girar <b>sobre sí mismo</b>, ¿cómo tienen que ir las dos ruedas?',
        opts: ["Una endavant i l'altra enrere|Una adelante y la otra atrás", 'Totes dues endavant a la mateixa velocitat|Las dos adelante a la misma velocidad', "Una endavant i l'altra aturada|Una adelante y la otra parada"], a: 0,
        ex: 'Amb una roda aturada, el robot gira en arc.|Con una rueda parada, el robot gira en arco.' },
      { k: 'quiz', ph: 'tanca', q: 'Què vol dir <b>calibrar</b> un gir?|¿Qué quiere decir <b>calibrar</b> un giro?',
        opts: ['Provar-lo, mesurar-lo i ajustar els números fins que surti bé|Probarlo, medirlo y ajustar los números hasta que salga bien', 'Fer-lo tan ràpid com es pugui|Hacerlo tan rápido como se pueda', "Copiar els números d'un company/a|Copiar los números de un compañero/a"], a: 0 },
      { k: 'feel', ph: 'tanca' }
    ] },
  /* ---------- Sessió 4 · Projecte: el passeig ---------- */
  { id: 'k1-4', t: 'Projecte: el passeig de la fira|Proyecto: el paseo de la feria', min: 45, proj: true, badge: 'k_passeig',
    learn: ['Descompondre és partir la ruta en trams rectes i girs, i programar-los un a un.|Descomponer es partir la ruta en tramos rectos y giros, y programarlos uno a uno.',
      'El botó </> dona el codi per a MakeCode, i amb un cable USB passa a la micro:bit del robot de veritat.|El botón </> da el código para MakeCode, y con un cable USB pasa a la micro:bit del robot de verdad.',
      'Has acabat el teu primer projecte de robòtica!|¡Has terminado tu primer proyecto de robótica!'],
    steps: [
      { k: 'quiz', ph: 'recorda', q: 'Motor esquerre <b>enrere</b> i motor dret <b>endavant</b>. Cap on gira el robot?|Motor izquierdo <b>atrás</b> y motor derecho <b>adelante</b>. ¿Hacia dónde gira el robot?',
        opts: ["Cap a l'esquerra, sense moure's del lloc|Hacia la izquierda, sin moverse del sitio", 'Cap a la dreta, sense moure\'s del lloc|Hacia la derecha, sin moverse del sitio', 'Recte enrere|Recto hacia atrás'], a: 0,
        ex: 'Gira cap al costat de la roda que va enrere: l\'esquerra.|Gira hacia el lado de la rueda que va atrás: la izquierda.' },
      { k: 'story', ph: 'missio', who: 'both', scene: 'poble', title: 'La fira de robòtica|La feria de robótica',
        t: "Aquest dissabte hi ha la <b>fira de robòtica</b> a la plaça del poble, i el nostre Maqueen hi farà de <b>guia</b>: passejarà els visitants per les parades i els tornarà a la sortida. És el projecte de la unitat: hi faràs servir tot el que has après.|Este sábado hay <b>feria de robótica</b> en la plaza del pueblo, y nuestro Maqueen hará de <b>guía</b>: pasará a los visitantes por los puestos y los devolverá a la salida. Es el proyecto de la unidad: usarás todo lo que has aprendido." },
      { k: 'learn', ph: 'descobreix', cards: [
        { k: 'Descompondre|Descomponer', t: 'La ruta, a trossos|La ruta, a trozos',
          robo: { w: { w: 120, h: 70, bot: [15, 55, 90], zones: [{ id: 'f', r: [62, 6, 26, 22], col: 'green', label: 'FINAL|FINAL' }], goal: [{ k: 'cps', pts: [[75, 55], [75, 17]], r: 6 }] }, prog: 'start{ run:all,fwd,150 wait:3900 stop:all run:L,back,100 run:R,fwd,100 wait:590 stop:all run:all,fwd,150 wait:2400 stop:all }' },
          x: "Abans de posar blocs, parteix el camí en <b>trams</b>: «tram 1, recte fins al punt 1; gir a l'esquerra; tram 2, recte fins al punt 2». Cada tros és un problema petit i fàcil. Això es diu <span class='hl'>descompondre</span>.|Antes de poner bloques, parte el camino en <b>tramos</b>: «tramo 1, recto hasta el punto 1; giro a la izquierda; tramo 2, recto hasta el punto 2». Cada trozo es un problema pequeño y fácil. Esto se llama <span class='hl'>descomponer</span>.",
          tip: "Un tram són tres blocs: motor els dos, espera i atura. Un gir, quatre: els dos motors en direccions contràries, espera i atura.|Un tramo son tres bloques: motor los dos, espera y para. Un giro, cuatro: los dos motores en direcciones contrarias, espera y para." },
        { k: 'Al robot de veritat|Al robot de verdad', t: 'Del simulador a la micro:bit|Del simulador a la micro:bit', anim: 'k1usb',
          x: "Quan el programa funciona, toca el botó <b>&lt;/&gt;</b>: et dona el mateix programa en el llenguatge de <b>MakeCode</b>. Allà el descarregues i el passes a la <b>micro:bit</b> amb un cable USB. Desconnecta el cable, encén el robot… i a provar!|Cuando el programa funciona, toca el botón <b>&lt;/&gt;</b>: te da el mismo programa en el lenguaje de <b>MakeCode</b>. Allí lo descargas y lo pasas a la <b>micro:bit</b> con un cable USB. Desconecta el cable, enciende el robot… ¡y a probar!" },
        { k: 'Provar|Probar', t: 'Prova, mesura i ajusta|Prueba, mide y ajusta', anim: 'k1calib',
          x: "A la pista de cinta, el robot de veritat no farà exactament el mateix que el del simulador: les piles, el terra i els motors canvien una mica. Prova el passeig <b>tram a tram</b>, mira on es desvia i ajusta només aquell número.|En la pista de cinta, el robot de verdad no hará exactamente lo mismo que el del simulador: las pilas, el suelo y los motores cambian un poco. Prueba el paseo <b>tramo a tramo</b>, mira dónde se desvía y ajusta solo ese número.",
          bad: "Si falla, ho esborro tot i començo de nou.|Si falla, lo borro todo y empiezo de nuevo.", good: "Si falla, busco el tram que falla i canvio només aquell número.|Si falla, busco el tramo que falla y cambio solo ese número." }
      ] },
      { k: 'seq', ph: 'mans', q: 'Aquest és el pla del passeig més curt. <b>Ordena els trossos</b>.|Este es el plan del paseo más corto. <b>Ordena los trozos</b>.',
        items: ['Tram 1: recte fins a la parada de les fruites|Tramo 1: recto hasta el puesto de las frutas', "Primer gir: un quart de volta a l'esquerra|Primer giro: un cuarto de vuelta a la izquierda", 'Tram 2: recte fins a la parada dels llibres|Tramo 2: recto hasta el puesto de los libros', "Segon gir: un altre quart de volta a l'esquerra|Segundo giro: otro cuarto de vuelta a la izquierda", "Tram 3: recte fins a la sortida i atura't|Tramo 3: recto hasta la salida y párate"],
        ex: 'Tram, gir, tram, gir, tram: un problema gran convertit en cinc de petits.|Tramo, giro, tramo, giro, tramo: un problema grande convertido en cinco pequeños.' },
      { k: 'unplug', ph: 'mans', ico: '🗺️', title: 'El mapa del passeig|El mapa del paseo',
        t: 'Amb algú de casa, un full i un llapis.|Con alguien de casa, una hoja y un lápiz.',
        steps: ["Dibuixa el plànol d'una habitació de casa i marca-hi tres «parades» (la porta, una cadira, la finestra…).|Dibuja el plano de una habitación de casa y marca tres «paradas» (la puerta, una silla, la ventana…).",
          'Escriu el pla del passeig en trams i girs: «tram 1: 4 passos; gir a la dreta; tram 2: 3 passos…».|Escribe el plan del paseo en tramos y giros: «tramo 1: 4 pasos; giro a la derecha; tramo 2: 3 pasos…».',
          "L'altra persona fa de robot i segueix el pla exactament, sense mirar el plànol.|La otra persona hace de robot y sigue el plan exactamente, sin mirar el plano.",
          'Si es desvia, no esborreu tot el pla: busqueu el tram que falla i corregiu només aquell.|Si se desvía, no borréis todo el plan: buscad el tramo que falla y corregid solo ese.'],
        tip: "Això és calibrar: les passes de cadascú fan una llargada diferent!|Esto es calibrar: ¡los pasos de cada uno miden una longitud diferente!" },
      { k: 'rpredict', ph: 'prova', q: 'Tram, gir i tram. <b>On acabarà</b> el robot guia?|Tramo, giro y tramo. <b>¿Dónde terminará</b> el robot guía?',
        w: { w: 120, h: 80, bot: [20, 45, 90], marks: { A: [69, 14], B: [69, 76], C: [100, 45] } }, scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:3200 stop:all run:L,back,100 run:R,fwd,100 wait:590 stop:all run:all,fwd,150 wait:2000 stop:all }', a: 'A',
        ex: "L'esquerre va enrere i el dret endavant: gira a l'esquerra i queda mirant amunt.|El izquierdo va atrás y el derecho adelante: gira a la izquierda y queda mirando hacia arriba." },
      { k: 'rspot', ph: 'investiga', q: 'En Pau ha programat un passeig, però el robot <b>xoca amb la parada dels llibres</b>. Executa-ho i <b>toca el bloc que cal canviar.</b>|Pau ha programado un paseo, pero el robot <b>choca con el puesto de los libros</b>. Ejecútalo y <b>toca el bloque que hay que cambiar.</b>',
        w: { w: 120, h: 70, bot: [15, 58, 90], walls: [[56, 4, 26, 12]] }, scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:3500 stop:all run:L,back,100 run:R,fwd,100 wait:590 stop:all run:all,fwd,150 wait:4000! stop:all }',
        yes: "Molt bé! L'últim tram és massa llarg.|¡Muy bien! El último tramo es demasiado largo.",
        ex: "És l'espera de l'últim tram: 4000 ms el porta fins a la parada. Amb una espera més curta, s'aturaria al davant.|Es la espera del último tramo: 4000 ms lo llevan hasta el puesto. Con una espera más corta, se pararía delante." },
      { k: 'quiz', ph: 'investiga', q: 'Quants blocs necessites per programar <b>un tram recte</b>?|¿Cuántos bloques necesitas para programar <b>un tramo recto</b>?',
        opts: ['Tres: motor els dos, espera i atura|Tres: motor los dos, espera y para', 'Un: motor els dos|Uno: motor los dos', 'Quatre: dos motors, espera i atura|Cuatro: dos motores, espera y para'], a: 0,
        ex: 'Els quatre blocs són per a un gir sobre si mateix, amb els motors en direccions contràries.|Los cuatro bloques son para un giro sobre sí mismo, con los motores en direcciones contrarias.' },
      { k: 'move', ph: 'pausa', secs: 30, t: "Fes de robot guia! Imagina la plaça: <b>tram</b> de 4 passos, <b>quart de volta</b> a l'esquerra, tram de 3 passos, quart de volta a l'esquerra, tram de 4 passos… i saluda els visitants!|¡Haz de robot guía! Imagina la plaza: <b>tramo</b> de 4 pasos, <b>cuarto de vuelta</b> a la izquierda, tramo de 3 pasos, cuarto de vuelta a la izquierda, tramo de 4 pasos… ¡y saluda a los visitantes!" },
      { k: 'robo', ph: 'repte', q: 'En Pau ha començat el programa: el <b>tram 1</b> ja funciona. Afegeix-hi el <b>gir</b> i el <b>tram 2</b> perquè el robot s\'aturi a la parada de les fruites.|Pau ha empezado el programa: el <b>tramo 1</b> ya funciona. Añade el <b>giro</b> y el <b>tramo 2</b> para que el robot se pare en el puesto de las frutas.',
        w: { w: 120, h: 80, bot: [15, 62, 90], walls: [[26, 6, 34, 38]], zones: [{ id: 'f', r: [64, 8, 26, 24], col: 'orange', label: 'FRUITES|FRUTAS' }], goal: [{ k: 'zone', id: 'f', stop: true }, { k: 'nohit' }], env: [{ t: 12 }], time: 16 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:3800 stop:all }', sol: 'start{ run:all,fwd,150 wait:3800 stop:all run:L,back,100 run:R,fwd,100 wait:590 stop:all run:all,fwd,150 wait:2700 stop:all }',
        hint: "El gir és a l'esquerra: motor esquerre enrere i dret endavant, a 100, uns 590 ms. Després, un tram recte com el primer, però més curt.|El giro es a la izquierda: motor izquierdo atrás y derecho adelante, a 100, unos 590 ms. Después, un tramo recto como el primero, pero más corto." },
      { k: 'robo', ph: 'repte', q: "<b>La volta a les flors.</b> Fes que el robot envolti la parada de les flors: tram, gir a la dreta, tram, gir a la dreta i tram fins a la zona dels visitants.|<b>La vuelta a las flores.</b> Haz que el robot rodee el puesto de las flores: tramo, giro a la derecha, tramo, giro a la derecha y tramo hasta la zona de los visitantes.",
        w: { w: 120, h: 80, bot: [15, 15, 90], walls: [[20, 30, 62, 22]], zones: [{ id: 'v', r: [6, 56, 28, 22], col: 'purple', label: 'VISITANTS|VISITANTES' }], goal: [{ k: 'zone', id: 'v', stop: true }, { k: 'nohit' }], env: [{ t: 18 }], time: 24 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:5200 stop:all run:L,fwd,100 run:R,back,100 wait:590 stop:all run:all,fwd,150 wait:3300 stop:all run:L,fwd,100 run:R,back,100 wait:590 stop:all run:all,fwd,150 wait:4900 stop:all }',
        hint: 'Prova el programa després de cada tram: si el primer tram ja va bé, no el toquis més.|Prueba el programa después de cada tramo: si el primer tramo ya va bien, no lo toques más.' },
      { k: 'robo', ph: 'repte', q: "<b>Passeig exprés.</b> El forner necessita el pa a la parada del forn en <b>menys de 6 segons</b>. Fes els trams més de pressa (i recalcula les esperes!).|<b>Paseo exprés.</b> El panadero necesita el pan en el puesto del horno en <b>menos de 6 segundos</b>. Haz los tramos más deprisa (¡y recalcula las esperas!).",
        w: { w: 120, h: 80, bot: [15, 66, 90], walls: [[28, 4, 42, 44]], zones: [{ id: 'f', r: [76, 6, 28, 22], col: 'red', label: 'FORN|HORNO' }], goal: [{ k: 'at', t: 6, zone: 'f', moving: false, why: "Al segon 6 el robot encara no és aturat a la parada del forn: ha d'arribar-hi abans. Fes els trams més de pressa.|En el segundo 6 el robot todavía no está parado en el puesto del horno: tiene que llegar antes. Haz los tramos más deprisa." }, { k: 'zone', id: 'f', stop: true }, { k: 'nohit' }], time: 14 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        prog: 'start{ run:all,fwd,150 wait:4600 stop:all run:L,back,100 run:R,fwd,100 wait:590 stop:all run:all,fwd,150 wait:3100 stop:all }',
        sol: 'start{ run:all,fwd,255 wait:2450 stop:all run:L,back,100 run:R,fwd,100 wait:590 stop:all run:all,fwd,255 wait:1600 stop:all }',
        hint: 'A 255 va gairebé el doble de ràpid que a 150, així que cada espera dels trams ha de ser una mica més de la meitat. El gir el pots deixar igual.|A 255 va casi el doble de rápido que a 150, así que cada espera de los tramos tiene que ser un poco más de la mitad. El giro lo puedes dejar igual.' },
      { k: 'rcreate', ph: 'crea', name: 'El passeig de la fira|El paseo de la feria',
        q: "<b>Projecte final de la unitat!</b> Programa el passeig de la fira: el robot guia ha de passar per les <b>3 parades</b> en ordre (punts 1, 2 i 3) i acabar <b>aturat a la sortida</b>, sense tocar cap parada ni la font. Planifica-ho a trams i prova-ho tros a tros.|<b>¡Proyecto final de la unidad!</b> Programa el paseo de la feria: el robot guía tiene que pasar por los <b>3 puestos</b> en orden (puntos 1, 2 y 3) y terminar <b>parado en la salida</b>, sin tocar ningún puesto ni la fuente. Planifícalo a tramos y pruébalo trozo a trozo.",
        crit: ['Passa per les 3 parades en ordre|Pasa por los 3 puestos en orden', 'Acaba aturat a la sortida|Termina parado en la salida', 'No toca cap parada ni la font|No toca ningún puesto ni la fuente'],
        w: { w: 140, h: 90, bot: [15, 75, 90], walls: [[52, 84, 26, 6], [126, 32, 10, 26], [57, 2, 26, 8], [40, 38, 56, 22]], zones: [{ id: 's', r: [16, 8, 28, 24], col: 'green', label: 'SORTIDA|SALIDA' }], goal: [{ k: 'cps', pts: [[65, 75], [115, 45], [70, 20]], r: 9 }, { k: 'zone', id: 's', stop: true }, { k: 'nohit' }], env: [{ t: 24 }], time: 34 },
        pal: ['run', 'stop', 'wait'], ops: [], vars: [], scripts: ['start'],
        sol: 'start{ run:all,fwd,150 wait:6400 stop:all run:L,back,100 run:R,fwd,100 wait:590 stop:all run:all,fwd,150 wait:3500 stop:all run:L,back,100 run:R,fwd,100 wait:590 stop:all run:all,fwd,150 wait:5300 stop:all }' },
      { k: 'story', ph: 'crea', who: 'numi',
        t: "Ho vols provar al <b>Maqueen de veritat</b>? Torna al teu projecte (a «Projectes») i toca el botó <b>&lt;/&gt;</b>: et dona el codi per a MakeCode. Enganxa'l, descarrega'l a la micro:bit i prova'l a la pista de cinta de l'aula.|¿Lo quieres probar en el <b>Maqueen de verdad</b>? Vuelve a tu proyecto (en «Proyectos») y toca el botón <b>&lt;/&gt;</b>: te da el código para MakeCode. Pégalo, descárgalo en la micro:bit y pruébalo en la pista de cinta del aula.",
        box: "<ol><li>Prova el passeig sencer i mira on es desvia.</li><li>Calibra primer els <b>girs</b> (l'espera de cada gir).</li><li>Després ajusta els <b>trams</b> (l'espera de cada tram).</li><li>Canvia un sol número cada vegada i torna-ho a provar.</li></ol>|<ol><li>Prueba el paseo entero y mira dónde se desvía.</li><li>Calibra primero los <b>giros</b> (la espera de cada giro).</li><li>Después ajusta los <b>tramos</b> (la espera de cada tramo).</li><li>Cambia un solo número cada vez y vuelve a probarlo.</li></ol>" },
      { k: 'quiz', ph: 'tanca', q: 'Què vol dir <b>descompondre</b> una ruta?|¿Qué quiere decir <b>descomponer</b> una ruta?',
        opts: ['Partir-la en trams i girs més petits|Partirla en tramos y giros más pequeños', 'Fer-la tota de cop sense pensar|Hacerla toda de golpe sin pensar', 'Esborrar el programa i començar de nou|Borrar el programa y empezar de nuevo'], a: 0 },
      { k: 'quiz', ph: 'tanca', q: 'El teu passeig funciona al simulador, però al robot de veritat <b>gira una mica massa</b>. Què fas?|Tu paseo funciona en el simulador, pero en el robot de verdad <b>gira un poco de más</b>. ¿Qué haces?',
        opts: ["Calibro: escurço una mica l'espera del gir i ho torno a provar|Calibro: acorto un poco la espera del giro y vuelvo a probarlo", 'Res: el simulador sempre té raó|Nada: el simulador siempre tiene razón', 'Canvio tot el programa|Cambio todo el programa'], a: 0,
        ex: 'Un robot real sempre és una mica diferent: per això es calibra.|Un robot real siempre es un poco diferente: por eso se calibra.' },
      { k: 'feel', ph: 'tanca' }
    ] }
] };
