/* Tech 3D · Nivell 2 · unitat 6 «Mòduls» (p6-1 … p6-4)
   Contingut propi de Numi. Fil narratiu: l'Ajuntament encarrega a l'estudi d'enginyeria del Taller de Bit la maqueta
   del «barri del futur» per a una exposició: desenes de fanals, bancs, arbres i edificis. Conceptes: «defineix nom() { }»
   i les crides (definir no construeix), mòduls amb paràmetres (l'ordre dels valors, càlculs amb paràmetres, mòduls amb
   bucles), la biblioteca de peces (comentaris, noms clars, convenció de l'origen, llegir codi d'altres) i el projecte de
   la ciutat modular (mòduls + bucles + una variable per a tot el barri).
   · Els programs tenen versió catalana i castellana ("ca|es"): els noms dels mòduls, dels paràmetres i els comentaris es
     tradueixen amb ES i CM; les paraules del llenguatge les tradueix l'app. Les variables globals que fan servir les
     comprovacions «param» (n, pisos) són iguals en les dues llengües. Els objectius de «match» van en català (la
     geometria és la mateixa). Els comentaris sempre en una línia a part. */
Object.assign(TBADGE, {
  p6modul: { id: 'p6modul', ico: '🧩', n: 'Creador/a de mòduls|Creador/a de módulos', d: 'Has definit els teus mòduls i els has fet servir moltes vegades.|Has definido tus módulos y los has usado muchas veces.' },
  p6param: { id: 'p6param', ico: '🎛️', n: 'Mestre/a dels paràmetres|Maestro/a de los parámetros', d: 'Has fet famílies de peces amb mòduls que reben valors.|Has hecho familias de piezas con módulos que reciben valores.' },
  p6biblio: { id: 'p6biblio', ico: '📚', n: 'Bibliotecari/ària de peces|Bibliotecario/a de piezas', d: "Has organitzat, documentat i ampliat una biblioteca de peces que fa servir tot l'estudi.|Has organizado, documentado y ampliado una biblioteca de piezas que usa todo el estudio." },
  p6ciutat: { id: 'p6ciutat', ico: '🏙️', n: 'Urbanista digital|Urbanista digital', d: 'Projecte acabat: una illa de la ciutat modular feta amb mòduls, paràmetres i bucles.|Proyecto terminado: una manzana de la ciudad modular hecha con módulos, parámetros y bucles.' }
});

COURSE_UNITS[6] = (() => {
  // noms dels mòduls i dels paràmetres en castellà, i els comentaris
  const ES = { arbre: 'árbol', fanal: 'farola', banc: 'banco', finestra: 'ventana', façana: 'fachada', edifici: 'edificio', tanca: 'valla', esglaó: 'peldaño', llargada: 'largo', alçada: 'altura', gruix: 'grosor', mida: 'tamaño', costat: 'lado', bloc: 'bloque', porta: 'puerta', amplada: 'ancho', font: 'fuente', filera: 'hilera', xemeneia: 'chimenea', pilar: 'pilar' };
  const CM = {
    'banc 1': 'banco 1', 'banc 2': 'banco 2',
    '===== Biblioteca de la maqueta =====': '===== Biblioteca de la maqueta =====',
    'fanal(alçada): pal de 3 mm i un llum a dalt': 'farola(altura): poste de 3 mm y una luz arriba',
    'banc(llargada): seient, potes i respatller, centrat': 'banco(largo): asiento, patas y respaldo, centrado',
    'arbre(mida): tronc i copa; mida = alçada del tronc': 'árbol(tamaño): tronco y copa; tamaño = altura del tronco',
    "===== L'escena: la plaça =====": '===== La escena: la plaza =====',
    'tronc': 'tronco', 'copa': 'copa',
    'porta(amplada, alçada): un marc en forma de U invertida': 'puerta(ancho, altura): un marco en forma de U invertida',
    'font(d): bassa i sortidor; d = diàmetre': 'fuente(d): estanque y surtidor; d = diámetro',
    'filera(n): n arbres en fila, cada 25 mm': 'hilera(n): n árboles en fila, cada 25 mm',
    'edifici(pisos): bloc amb finestres i terrat': 'edificio(pisos): bloque con ventanas y azotea',
    '1 · Paràmetres del barri': '1 · Parámetros del barrio', '2 · Mòduls': '2 · Módulos', "3 · L'escena": '3 · La escena',
    'la base de la illa': 'la base de la manzana', 'els carrers': 'las calles'
  };
  const es = s => s.split('\n').map(l => { const c = l.indexOf('//'); const code = c < 0 ? l : l.slice(0, c), rem = c < 0 ? null : l.slice(c + 2).trim();
    return code.replace(/[A-Za-zÀ-ÿ_·][A-Za-z0-9_À-ÿ·]*/g, w => ES[w] || w) + (rem == null ? '' : '// ' + (CM[rem] ?? rem)); }).join('\n');
  const B = s => s + '|' + es(s);
  const ck = (k, o) => ({ k, ...o });
  const GH = "S'assembla al fantasma|Se parece al fantasma";
  /* ---------- sessió 1 · Definir un mòdul ---------- */
  const TREES = `repeteix i de 0 a 2 {\n  mou(i * 30, 0, 0) cilindre(4, 12)\n  mou(i * 30, 0, 16) esfera(14)\n}`;
  const ARBRE = `defineix arbre() {\n  cilindre(4, 12)\n  mou(0, 0, 16) esfera(14)\n}`;
  const DEF3 = `${ARBRE}\narbre()\nmou(30, 0, 0) arbre()\nmou(60, 10, 0) arbre()`;
  const FANAL = `defineix fanal() {\n  cilindre(10, 2)\n  cilindre(3, 30)\n  mou(0, 0, 32) esfera(8)\n}`;
  const STREET = `${FANAL}\nrepeteix i de 0 a 3 {\n  mou(i * 30, 0, 0) fanal()\n}`;
  const ARBREC = `defineix arbre() {\n  cilindre(4, 10)\n  mou(0, 0, 8) con(16, 22)\n}`;
  const CITY1 = `${ARBREC}\nrepeteix i de 0 a 3 {\n  mou(i * 25, 0, 0) arbre()\n}`;
  const FAN3 = `${FANAL}\nfanal()\nmou(30, 0, 0) fanal()\nmou(60, 0, 0) fanal()`;
  const BANCX = `// banc 1\nmou(0, 0, 8) cub(30, 10, 3)\nmou(2, 2, 0) cub(4, 6, 8)\nmou(24, 2, 0) cub(4, 6, 8)\nmou(0, 8, 11) cub(30, 2, 8)\n// banc 2\nmou(50, 0, 8) cub(30, 10, 3)\nmou(52, 2, 0) cub(4, 6, 8)\nmou(74, 2, 0) cub(4, 6, 8)\nmou(50, 8, 11) cub(30, 2, 8)`;
  const BANCM = `defineix banc() {\n  mou(0, 0, 8) cub(30, 10, 3)\n  mou(2, 2, 0) cub(4, 6, 8)\n  mou(24, 2, 0) cub(4, 6, 8)\n  mou(0, 8, 11) cub(30, 2, 8)\n}\nbanc()\nmou(50, 0, 0) banc()`;
  const ROW5T = `${ARBRE}\nrepeteix i de 0 a 4 {\n  mou(i * 25, 0, 0) arbre()\n}`;
  const CASA = `defineix casa() {\n  cub(20, 20, 16)\n  mou(10, 10, 16) piramide(24, 24, 12)\n}`;
  const CASAX = `defineix casa() {\n  cub(20, 20, 16)\n  mou(10, 10, 16) piramide(24, 24, 12)\n  mou(13, 4, 18) cub(4, 4, 12)\n}`;
  const CALLS3 = `\ncasa()\nmou(35, 0, 0) casa()\nmou(70, 0, 0) casa()`;
  const FIN = `defineix finestra() {\n  color("cel") cub(8, 2, 10)\n}`;
  const FAC0 = `${FIN}\ndefineix façana() {\n  cub(40, 6, 40)\n}\nfaçana()\nmou(50, 0, 0) façana()`;
  const FAC = `${FIN}\ndefineix façana() {\n  cub(40, 6, 40)\n  repeteix p de 0 a 2 {\n    repeteix f de 0 a 2 {\n      mou(4 + f * 12, -1, 4 + p * 12) finestra()\n    }\n  }\n}\nfaçana()\nmou(50, 0, 0) façana()`;
  const STREETFREE = `${ARBRE}\n${FANAL}\nrepeteix i de 0 a 3 {\n  mou(i * 30, 0, 0) arbre()\n  mou(i * 30 + 15, 20, 0) fanal()\n}`;
  /* ---------- sessió 2 · Mòduls amb paràmetres ---------- */
  const TORRE = `defineix torre(alçada, gruix) {\n  cilindre(gruix, alçada)\n  mou(0, 0, alçada) con(gruix + 6, 12)\n}`;
  const TORRES = `${TORRE}\ntorre(30, 14)\nmou(30, 0, 0) torre(50, 14)\nmou(60, 0, 0) torre(40, 22)`;
  const EDI = `defineix edifici(pisos) {\n  color("blau") cub(24, 20, pisos * 10)\n  repeteix p de 0 a (pisos - 1) {\n    repeteix f de 0 a 1 {\n      mou(4 + f * 10, -1, 3 + p * 10) color("groc") cub(6, 2, 5)\n    }\n  }\n}`;
  const EDI0 = `defineix edifici(pisos) {\n  color("blau") cub(24, 20, pisos * 10)\n}`;
  const ECALLS = `\nedifici(2)\nmou(34, 0, 0) edifici(4)\nmou(68, 0, 0) edifici(6)`;
  const PILAR = `defineix pilar(alçada) {\n  cilindre(10, alçada)\n}\npilar(10)\nmou(20, 0, 0) pilar(30)\nmou(40, 0, 0) pilar(20)`;
  const T0 = `defineix torre() {\n  cilindre(14, 40)\n  mou(0, 0, 40) con(20, 12)\n}\ntorre()\nmou(30, 0, 0) torre()\nmou(60, 0, 0) torre()`;
  const T1 = `defineix torre(alçada) {\n  cilindre(14, alçada)\n  mou(0, 0, alçada) con(20, 12)\n}\ntorre(30)\nmou(30, 0, 0) torre(45)\nmou(60, 0, 0) torre(60)`;
  const TANCA0 = `defineix tanca(n) {\n  repeteix i de 0 a (n - 1) {\n    mou(i * 12, 0, 0) cub(4, 4, 20)\n  }\n  mou(0, 1, 12) cub((n - 1) * 12 + 4, 2, 4)\n}\ntanca(5)\nmou(0, 30, 0) tanca(8)`;
  const TANCA = `defineix tanca(n, alçada) {\n  repeteix i de 0 a (n - 1) {\n    mou(i * 12, 0, 0) cub(4, 4, alçada)\n  }\n  mou(0, 1, alçada - 8) cub((n - 1) * 12 + 4, 2, 4)\n}\ntanca(5, 20)\nmou(0, 30, 0) tanca(8, 30)`;
  const TFAM = `${TORRE}\nrepeteix i de 0 a 4 {\n  mou(i * 25, 0, 0) torre(20 + i * 10, 12)\n}`;
  const SPIRAL0 = `defineix esglaó(llargada) {\n  cub(llargada, 10, 4)\n}\ncilindre(10, 76)`;
  const SPIRAL = `${SPIRAL0}\nrepeteix i de 0 a 11 {\n  mou(0, 0, i * 6) gira(0, 0, i * 30) mou(0, -5, 0) esglaó(30)\n}`;
  const FAMFREE = `${TORRE}\nrepeteix i de 0 a 3 {\n  mou(i * 28, 0, 0) torre(25 + i * 8, 10 + i * 3)\n}`;
  /* ---------- sessió 3 · La biblioteca de peces ---------- */
  const LFANAL = `// fanal(alçada): pal de 3 mm i un llum a dalt\ndefineix fanal(alçada) {\n  cilindre(10, 2)\n  cilindre(3, alçada)\n  mou(0, 0, alçada + 2) esfera(8)\n}`;
  const LBANC = `// banc(llargada): seient, potes i respatller, centrat\ndefineix banc(llargada) {\n  mou(-llargada / 2, -5, 8) cub(llargada, 10, 3)\n  mou(-llargada / 2 + 2, -3, 0) cub(4, 6, 8)\n  mou(llargada / 2 - 6, -3, 0) cub(4, 6, 8)\n  mou(-llargada / 2, 3, 11) cub(llargada, 2, 8)\n}`;
  const LBANCBAD = `// banc(llargada): seient, potes i respatller, centrat\ndefineix banc(llargada) {\n  mou(0, -5, 8)! cub(llargada, 10, 3)\n  mou(-llargada / 2 + 2, -3, 0) cub(4, 6, 8)\n  mou(llargada / 2 - 6, -3, 0) cub(4, 6, 8)\n  mou(-llargada / 2, 3, 11) cub(llargada, 2, 8)\n}`;
  const LARBRE = `// arbre(mida): tronc i copa; mida = alçada del tronc\ndefineix arbre(mida) {\n  cilindre(mida / 4, mida)\n  mou(0, 0, mida) esfera(mida)\n}`;
  const LIB = `// ===== Biblioteca de la maqueta =====\n${LFANAL}\n${LBANC}\n${LARBRE}`;
  const PLACA = `\n// ===== L'escena: la plaça =====\nmou(-30, 0, 0) fanal(30)\nmou(30, 0, 0) fanal(30)\nbanc(36)\nmou(0, 30, 0) arbre(16)`;
  const ARBREBAD = `defineix arbre(mida) {\n  // tronc\n  cilindre(mida / 4, mida)\n  // copa\n  mou(0, 0, 16) esfera(mida)\n}\narbre(8)\nmou(25, 0, 0) arbre(16)\nmou(60, 0, 0) arbre(24)`;
  const ARBREOK = `defineix arbre(mida) {\n  // tronc\n  cilindre(mida / 4, mida)\n  // copa\n  mou(0, 0, mida) esfera(mida)\n}\narbre(8)\nmou(25, 0, 0) arbre(16)\nmou(60, 0, 0) arbre(24)`;
  const PORTA = `// porta(amplada, alçada): un marc en forma de U invertida\ndefineix porta(amplada, alçada) {\n  cub(4, 6, alçada)\n  mou(amplada - 4, 0, 0) cub(4, 6, alçada)\n  mou(0, 0, alçada) cub(amplada, 6, 4)\n}`;
  const BANCS4 = `\nrepeteix i de 0 a 3 {\n  gira(0, 0, i * 90) mou(0, 35, 0) banc(30)\n}`;
  const LFONT = `// font(d): bassa i sortidor; d = diàmetre\ndefineix font(d) {\n  cilindre(d, 2)\n  tub(d, 8, 2)\n  cilindre(4, 14)\n  mou(0, 0, 14) esfera(8)\n}`;
  const FILERA = `${LARBRE}\n// filera(n): n arbres en fila, cada 25 mm\ndefineix filera(n) {\n  repeteix i de 0 a (n - 1) {\n    mou(i * 25, 0, 0) arbre(12)\n  }\n}\nfilera(4)\nmou(0, 40, 0) filera(6)`;
  const PLAZAN = `n = 4\n${LBANC}\n${LFONT}\nfont(30)\nrepeteix i de 0 a (n - 1) {\n  gira(0, 0, i * 360 / n) mou(0, 35, 0) banc(30)\n}`;
  /* ---------- sessió 4 · La ciutat modular ---------- */
  const EDIF = `// edifici(pisos): bloc amb finestres i terrat\ndefineix edifici(pisos) {\n  cub(20, 20, pisos * 10)\n  repeteix p de 0 a (pisos - 1) {\n    mou(4, -1, 3 + p * 10) color("groc") cub(12, 2, 5)\n  }\n  mou(-1, -1, pisos * 10) color("gris") cub(22, 22, 2)\n}`;
  const EDIF0 = `defineix edifici(pisos) {\n  cub(20, 20, pisos * 10)\n}\nedifici(2)\nmou(30, 0, 0) edifici(3)\nmou(60, 0, 0) edifici(5)`;
  const EDIF1 = `${EDIF}\nedifici(2)\nmou(30, 0, 0) edifici(3)\nmou(60, 0, 0) edifici(5)`;
  const ROWC = `${EDIF}\nrepeteix i de 0 a 3 {\n  mou(i * 30, 0, 0) edifici(2 + i)\n}`;
  const BASE = `// la base de la illa\ncolor("gris") cub(120, 120, 3)`;
  const BLOCK = `${BASE}\n${EDIF}\nrepeteix j de 0 a 2 {\n  repeteix i de 0 a 2 {\n    mou(10 + i * 40, 10 + j * 40, 3) edifici(1 + i + j)\n  }\n}`;
  const BLOCKN = `// 1 · Paràmetres del barri\nn = 3\n// 2 · Mòduls\n${EDIF}\n// 3 · L'escena\ncolor("gris") cub(n * 40, n * 40, 3)\nrepeteix j de 0 a (n - 1) {\n  repeteix i de 0 a (n - 1) {\n    mou(10 + i * 40, 10 + j * 40, 3) edifici(1 + i + j)\n  }\n}`;
  const CITYFREE = `${BASE}\n${EDIF}\n${LARBRE}\nrepeteix j de 0 a 1 {\n  repeteix i de 0 a 1 {\n    mou(15 + i * 60, 15 + j * 60, 3) edifici(2 + i + 2 * j)\n    mou(50 + i * 60, 25 + j * 60, 3) arbre(8)\n  }\n}`;
  return {
  t: 'Mòduls|Módulos', d: 'Les teves pròpies peces|Tus propias piezas', color: '#D63F8C',
  s: [
    /* =================================================================== p6-1 */
    { id: 'p6-1', t: 'Definir un mòdul|Definir un módulo', min: 40, badge: 'p6modul',
      learn: ["<code>defineix nom() { … }</code> guarda un grup d'instruccions amb un nom; la definició sola no construeix res.|<code>define nombre() { … }</code> guarda un grupo de instrucciones con un nombre; la definición sola no construye nada.",
        "Cada crida <code>nom()</code> construeix les peces del mòdul allà on diuen el mou i el gira que té davant.|Cada llamada <code>nombre()</code> construye las piezas del módulo donde dicen el mueve y el gira que tiene delante.",
        "Els mòduls eviten repetir codi: si canvies la definició, canvien totes les còpies alhora.|Los módulos evitan repetir código: si cambias la definición, cambian todas las copias a la vez."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Quants cubs fa <code>repeteix i de 0 a 5 { … cub(10) }</code>?|¿Cuántos cubos hace <code>repite i de 0 a 5 { … cubo(10) }</code>?', opts: ['6|6', '5|5', '4|4'], a: 0, ex: '5 − 0 + 1 = 6.|5 − 0 + 1 = 6.' },
        { k: 'm3predict', ph: 'recorda', q: 'Aquest bucle té dues instruccions a dins. <b>Quin model fa?</b>|Este bucle tiene dos instrucciones dentro. <b>¿Qué modelo hace?</b>', prog: TREES,
          opts: [{ prog: TREES }, { prog: `repeteix i de 0 a 2 {\n  mou(i * 30, 0, 0) cilindre(4, 12)\n  mou(i * 30, 0, 0) esfera(14)\n}` }, { prog: `repeteix i de 0 a 1 {\n  mou(i * 30, 0, 0) cilindre(4, 12)\n  mou(i * 30, 0, 16) esfera(14)\n}` }], a: 0,
          ex: "Tres arbres: a cada volta es fa el tronc i, a sobre, la copa. Fixa't que el tronc i la copa sempre van junts… són una peça que es repeteix.|Tres árboles: en cada vuelta se hace el tronco y, encima, la copa. Fíjate en que el tronco y la copa siempre van juntos… son una pieza que se repite." },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: 'La maqueta del barri|La maqueta del barrio',
          t: "L'Ajuntament ens encarrega la <b>maqueta del barri del futur</b> per a una exposició. Hi haurà 40 fanals, 25 bancs, 60 arbres i molts edificis! Cada fanal té tres peces… Si les escrivim totes, el programa farà quilòmetres. Avui aprendrem a crear les nostres pròpies peces amb nom: els <b>mòduls</b>.|El Ayuntamiento nos encarga la <b>maqueta del barrio del futuro</b> para una exposición. ¡Habrá 40 farolas, 25 bancos, 60 árboles y muchos edificios! Cada farola tiene tres piezas… Si las escribimos todas, el programa medirá kilómetros. Hoy aprenderemos a crear nuestras propias piezas con nombre: los <b>módulos</b>." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Mòduls|Módulos', t: 'Una peça amb nom|Una pieza con nombre', anim: 'p6def',
            x: "Un <b>mòdul</b> és com un segell: el dissenyes una vegada (la <b>definició</b>) i després el fas servir tantes vegades com vulguis (les <b>crides</b>), cada vegada en un lloc diferent. És la mateixa idea que les funcions dels altres llenguatges de programació.|Un <b>módulo</b> es como un sello: lo diseñas una vez (la <b>definición</b>) y después lo usas tantas veces como quieras (las <b>llamadas</b>), cada vez en un sitio distinto. Es la misma idea que las funciones de los otros lenguajes de programación." },
          { k: 'Definir i cridar|Definir y llamar', t: 'defineix arbre() { … } i arbre()|define árbol() { … } y árbol()', media: { k: 'model', prog: B(DEF3) },
            x: "Dins de <code>defineix arbre() { }</code> hi ha el tronc i la copa, a l'origen. Cada <code>arbre()</code> construeix un arbre. Si davant hi ha un <code>mou</code>, l'arbre sencer es mou, com si fos un bloc <code>{ }</code>.|Dentro de <code>define árbol() { }</code> están el tronco y la copa, en el origen. Cada <code>árbol()</code> construye un árbol. Si delante hay un <code>mueve</code>, el árbol entero se mueve, como si fuera un bloque <code>{ }</code>." },
          { k: 'Compte!|¡Cuidado!', t: 'Definir no és construir|Definir no es construir', media: { k: 'model', prog: B(STREET) },
            x: "La definició és la <b>recepta</b>: si no la crides, la placa queda buida. La pots escriure al principi o al final del programa: el taller llegeix primer totes les definicions. I les crides poden anar dins d'un bucle: aquí, 4 fanals amb una sola línia.|La definición es la <b>receta</b>: si no la llamas, la placa queda vacía. La puedes escribir al principio o al final del programa: el taller lee primero todas las definiciones. Y las llamadas pueden ir dentro de un bucle: aquí, 4 farolas con una sola línea.",
            bad: 'Només defineix fanal() { … }: no surt res.|Solo define farola() { … }: no sale nada.', good: 'defineix fanal() { … } i després fanal(): surt un fanal.|define farola() { … } y después farola(): sale una farola.' },
          { k: 'Avantatge|Ventaja', t: 'Canvies una vegada, canvia tot|Cambias una vez, cambia todo', media: { k: 'model', prog: B(CITY1) },
            x: "L'Ajuntament prefereix arbres en forma de con? Només cal canviar la <b>definició</b>, i els 4 arbres (o els 60!) canvien alhora. Menys codi vol dir menys errors i canvis més ràpids: és el que fan els enginyers de veritat.|¿El Ayuntamiento prefiere árboles en forma de cono? Solo hay que cambiar la <b>definición</b>, y los 4 árboles (¡o los 60!) cambian a la vez. Menos código quiere decir menos errores y cambios más rápidos: es lo que hacen los ingenieros de verdad." },
          { k: 'Noms|Nombres', t: 'Com es diu un mòdul|Cómo se llama un módulo', media: { k: 'model', prog: B(CASA + CALLS3) },
            x: "El nom d'un mòdul diu <b>què és</b>: <code>casa</code>, <code>fanal</code>, <code>banc</code>. En minúscules, sense espais i sense fer servir paraules del llenguatge (no es pot dir <code>cub</code>). Els parèntesis hi van sempre, a la definició i a cada crida.|El nombre de un módulo dice <b>qué es</b>: <code>casa</code>, <code>farola</code>, <code>banco</code>. En minúsculas, sin espacios y sin usar palabras del lenguaje (no se puede llamar <code>cubo</code>). Los paréntesis van siempre, en la definición y en cada llamada.",
            tip: "Si crides un mòdul que no existeix, el taller t'avisa i et proposa el nom més semblant.|Si llamas a un módulo que no existe, el taller te avisa y te propone el nombre más parecido." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🖨️', title: 'La fàbrica de segells|La fábrica de sellos', t: 'Per parelles, amb paper quadriculat i llapis:|Por parejas, con papel cuadriculado y lápiz:',
          steps: ["Una persona escriu a la fitxa la definició d'un mòdul: <b>casa()</b> = un quadrat de 2 × 2 caselles amb un triangle a sobre.|Una persona escribe en la ficha la definición de un módulo: <b>casa()</b> = un cuadrado de 2 × 2 casillas con un triángulo encima.",
            "L'altra llegeix les crides i dibuixa: <b>mou(0, 0) casa() · mou(4, 0) casa() · mou(8, 2) casa()</b>.|La otra lee las llamadas y dibuja: <b>mueve(0, 0) casa() · mueve(4, 0) casa() · mueve(8, 2) casa()</b>.",
            "Ara la definició canvia: totes les cases tenen porta. Quantes coses heu de canviar al paper? I al codi?|Ahora la definición cambia: todas las casas tienen puerta. ¿Cuántas cosas tenéis que cambiar en el papel? ¿Y en el código?"],
          tip: "Al paper, has de redibuixar cada casa; al codi, només canvies la definició. Aquesta és la força dels mòduls.|En el papel, tienes que redibujar cada casa; en el código, solo cambias la definición. Esta es la fuerza de los módulos." },
        { k: 'm3predict', ph: 'prova', q: 'Llegeix la definició i les crides. <b>On queden els arbres?</b>|Lee la definición y las llamadas. <b>¿Dónde quedan los árboles?</b>', prog: B(`${ARBRE}\narbre()\nmou(25, 0, 0) arbre()\nmou(0, 25, 0) arbre()`),
          opts: [{ prog: B(`${ARBRE}\narbre()\nmou(25, 0, 0) arbre()\nmou(0, 25, 0) arbre()`) }, { prog: B(`${ARBRE}\narbre()\nmou(25, 0, 0) arbre()\nmou(50, 0, 0) arbre()`) }, { prog: B(`${ARBRE}\narbre()\nmou(25, 0, 0) arbre()`) }], a: 0,
          ex: "Tres crides, tres arbres: un a l'origen, un 25 mm cap a la dreta (x) i un 25 mm cap al fons (y). Fan una L.|Tres llamadas, tres árboles: uno en el origen, uno 25 mm hacia la derecha (x) y uno 25 mm hacia el fondo (y). Forman una L." },
        { k: 'quiz', ph: 'prova', q: "Un programa té <code>defineix fanal() { … }</code> però <b>cap crida</b>. Què surt a la placa?|Un programa tiene <code>define farola() { … }</code> pero <b>ninguna llamada</b>. ¿Qué sale en la placa?", opts: ['Res: la definició sola no construeix|Nada: la definición sola no construye', 'Un fanal a l\'origen|Una farola en el origen', 'Un error|Un error'], a: 0,
          ex: "La definició és com una recepta guardada al calaix: fins que no la fas servir, no hi ha pastís.|La definición es como una receta guardada en el cajón: hasta que no la usas, no hay pastel." },
        { k: 'm3spot', ph: 'investiga', q: 'Tots els fanals tenen el <b>llum flotant</b>. Toca la instrucció que falla.|Todas las farolas tienen la <b>luz flotando</b>. Toca la instrucción que falla.', prog: B(`defineix fanal() {\n  cilindre(10, 2)\n  cilindre(3, 30)\n  mou(0, 0, 40)! esfera(8)\n}\nrepeteix i de 0 a 3 {\n  mou(i * 30, 0, 0) fanal()\n}`), target: STREET,
          ex: "L'error és dins del mòdul: el pal fa 30 mm i el llum (de 8) ha d'anar a z = 32, no a 40. Per això falla a tots els fanals… i arreglant una sola línia s'arreglen tots.|El error está dentro del módulo: el poste mide 30 mm y la luz (de 8) tiene que ir en z = 32, no en 40. Por eso falla en todas las farolas… y arreglando una sola línea se arreglan todas." },
        { k: 'm3spot', ph: 'investiga', q: "Hi ha d'haver 4 arbres en fila, però només se'n veuen 3. Quina crida està malament?|Tiene que haber 4 árboles en fila, pero solo se ven 3. ¿Qué llamada está mal?", prog: B(`${ARBRE}\narbre()\nmou(30, 0, 0) arbre()\nmou(60, 0, 0) arbre()\nmou(30, 0, 0)! arbre()`), target: `${ARBRE}\narbre()\nmou(30, 0, 0) arbre()\nmou(60, 0, 0) arbre()\nmou(90, 0, 0) arbre()`,
          ex: "L'última crida té la mateixa posició que la segona: els dos arbres queden un dins de l'altre. Ha d'anar a x = 90.|La última llamada tiene la misma posición que la segunda: los dos árboles quedan uno dentro del otro. Tiene que ir en x = 90." },
        { k: 'move', ph: 'pausa', title: 'Defineix una coreografia|Define una coreografía', secs: 40,
          t: "Tota la classe defineix <b>salutació()</b> = mans amunt, una volta, una picada de mans. Ara el professor/a només diu les crides: <b>salutació() · salta · salutació() · salutació()</b>.|Toda la clase define <b>saludo()</b> = manos arriba, una vuelta, una palmada. Ahora el profesor/a solo dice las llamadas: <b>saludo() · salta · saludo() · saludo()</b>." },
        { k: 'm3code', ph: 'repte', text: true, q: "El mòdul <code>fanal()</code> ja està definit, però la placa és buida. <b>Crida'l</b> per posar 3 fanals a x = 0, 30 i 60.|El módulo <code>farola()</code> ya está definido, pero la placa está vacía. <b>Llámalo</b> para poner 3 farolas en x = 0, 30 y 60.", start: B(FANAL), blocks: ['call', 'mou', 'rep'],
          target: FAN3, checks: [ck('match', { target: FAN3, th: 0.9, t: GH }), ck('uses', { b: 'call' }), ck('count', { t: 'sph', min: 3, max: 3, txt: '3 fanals (3 llums)|3 farolas (3 luces)' })],
          hint: "Afegeix el bloc «usa el mòdul» (fanal()) i, per als altres dos, posa'l dins d'un mou(30, 0, 0) i d'un mou(60, 0, 0).|Añade el bloque «usa el módulo» (farola()) y, para los otros dos, ponlo dentro de un mueve(30, 0, 0) y de un mueve(60, 0, 0).", sol: B(FAN3) },
        { k: 'm3code', ph: 'repte', text: true, q: "Aquest programa fa <b>dos bancs</b> amb 8 línies. Crea el mòdul <code>banc()</code> amb les 4 línies del primer i fes els dos bancs amb dues crides.|Este programa hace <b>dos bancos</b> con 8 líneas. Crea el módulo <code>banco()</code> con las 4 líneas del primero y haz los dos bancos con dos llamadas.", start: B(BANCX), blocks: ['def', 'call', 'cub', 'mou'],
          target: BANCM, checks: [ck('match', { target: BANCM, th: 0.95, t: GH }), ck('uses', { b: 'def' }), ck('uses', { b: 'call' }), ck('count', { min: 8, max: 8, txt: 'Exactament 8 peces: 2 bancs, sense còpies de més|Exactamente 8 piezas: 2 bancos, sin copias de más' })],
          hint: "Embolcalla les 4 línies del banc 1 amb defineix banc() { … }, esborra les del banc 2 i escriu banc() i mou(50, 0, 0) banc().|Envuelve las 4 líneas del banco 1 con define banco() { … }, borra las del banco 2 y escribe banco() y mueve(50, 0, 0) banco().", sol: B(BANCM) },
        { k: 'm3code', ph: 'repte', text: true, q: "Mòdul i bucle junts: fes una <b>fila de 5 arbres</b>, un cada 25 mm, cridant <code>arbre()</code> dins d'un bucle.|Módulo y bucle juntos: haz una <b>fila de 5 árboles</b>, uno cada 25 mm, llamando a <code>árbol()</code> dentro de un bucle.", start: B(ARBRE), blocks: ['call', 'mou', 'rep'],
          target: ROW5T, checks: [ck('match', { target: ROW5T, th: 0.9, t: GH }), ck('uses', { b: 'rep' }), ck('uses', { b: 'call' }), ck('count', { t: 'sph', min: 5, max: 5, txt: 'Exactament 5 arbres|Exactamente 5 árboles' })],
          hint: "repeteix i de 0 a 4 { mou(i * 25, 0, 0) arbre() }|repite i de 0 a 4 { mueve(i * 25, 0, 0) árbol() }", sol: B(ROW5T) },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Un canvi, tres cases.</b> L'Ajuntament vol que totes les cases tinguin <b>xemeneia</b>: un cub de 4 × 4 × 12 mm a (13, 4, 18). Canvia només el mòdul.|<b>Un cambio, tres casas.</b> El Ayuntamiento quiere que todas las casas tengan <b>chimenea</b>: un cubo de 4 × 4 × 12 mm en (13, 4, 18). Cambia solo el módulo.", start: B(CASA + CALLS3), blocks: ['cub', 'pir', 'mou', 'def', 'call'],
          target: CASAX + CALLS3, checks: [ck('match', { target: CASAX + CALLS3, th: 0.92, t: GH }), ck('count', { t: 'box', min: 6, max: 6, txt: 'Cada casa té cos i xemeneia (6 caixes)|Cada casa tiene cuerpo y chimenea (6 cajas)' }), ck('uses', { b: 'def' })],
          hint: "Afegeix mou(13, 4, 18) cub(4, 4, 12) dins de les claus de defineix casa(). Les crides no cal tocar-les!|Añade mueve(13, 4, 18) cubo(4, 4, 12) dentro de las llaves de define casa(). ¡Las llamadas no hace falta tocarlas!", sol: B(CASAX + CALLS3) },
        { k: 'm3code', ph: 'repte', text: true, extra: true, q: "⭐ <b>Un mòdul dins d'un altre.</b> Completa <code>façana()</code> perquè tingui 3 × 3 finestres: crida <code>finestra()</code> dins de dos bucles, a x = 4 + f × 12 i z = 4 + p × 12.|⭐ <b>Un módulo dentro de otro.</b> Completa <code>fachada()</code> para que tenga 3 × 3 ventanas: llama a <code>ventana()</code> dentro de dos bucles, en x = 4 + f × 12 y z = 4 + p × 12.", start: B(FAC0), blocks: ['call', 'mou', 'rep', 'cub', 'def'],
          target: FAC, checks: [ck('match', { target: FAC, th: 0.88, t: GH }), ck('count', { t: 'box', min: 20, max: 20, txt: '2 façanes amb 9 finestres cada una|2 fachadas con 9 ventanas cada una' }), ck('uses', { b: 'rep' })],
          hint: "Dins de façana(), després del cub: repeteix p de 0 a 2 { repeteix f de 0 a 2 { mou(4 + f * 12, -1, 4 + p * 12) finestra() } }.|Dentro de fachada(), después del cubo: repite p de 0 a 2 { repite f de 0 a 2 { mueve(4 + f * 12, -1, 4 + p * 12) ventana() } }.", sol: B(FAC) },
        { k: 'm3free', ph: 'crea', text: true, q: "<b>El carrer de la maqueta.</b> Defineix almenys un mòdul teu (un arbre, un fanal, un banc, una paperera…) i fes-lo servir moltes vegades per fer un carrer.|<b>La calle de la maqueta.</b> Define al menos un módulo tuyo (un árbol, una farola, un banco, una papelera…) y úsalo muchas veces para hacer una calle.",
          name: 'El meu carrer|Mi calle', blocks: ['cub', 'cil', 'esf', 'con', 'pir', 'mou', 'gira', 'color', 'rep', 'def', 'call'],
          crit: ["Defineix almenys un mòdul amb un nom clar|Define al menos un módulo con un nombre claro", "El fa servir almenys 3 vegades (amb crides o amb un bucle)|Lo usa al menos 3 veces (con llamadas o con un bucle)", "Tot toca la placa|Todo toca la placa"],
          checks: [ck('uses', { b: 'def' }), ck('uses', { b: 'call' }), ck('count', { min: 6, txt: 'Almenys 6 peces|Al menos 6 piezas' }), ck('onplate')], sol: B(STREETFREE) },
        { k: 'quiz', ph: 'tanca', q: "Què passa si defineixes un mòdul i no el crides mai?|¿Qué pasa si defines un módulo y no lo llamas nunca?", opts: ['No es construeix res d\'aquell mòdul|No se construye nada de ese módulo', "Es construeix una vegada a l'origen|Se construye una vez en el origen", 'El programa dona error|El programa da error'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: "Has fet 20 fanals amb el mòdul <code>fanal()</code>. Ara els vols tots més alts. Què canvies?|Has hecho 20 farolas con el módulo <code>farola()</code>. Ahora las quieres todas más altas. ¿Qué cambias?", opts: ['La definició del mòdul, una sola vegada|La definición del módulo, una sola vez', 'Les 20 crides, una per una|Las 20 llamadas, una por una', 'Res: els mòduls no es poden canviar|Nada: los módulos no se pueden cambiar'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* =================================================================== p6-2 */
    { id: 'p6-2', t: 'Mòduls amb paràmetres|Módulos con parámetros', min: 40, badge: 'p6param',
      learn: ["<code>defineix torre(alçada, gruix) { … }</code>: els paràmetres són variables que només existeixen dins del mòdul.|<code>define torre(altura, grosor) { … }</code>: los parámetros son variables que solo existen dentro del módulo.",
        "Cada crida dona els valors en el mateix ordre que els paràmetres: <code>torre(40, 16)</code> fa alçada = 40 i gruix = 16.|Cada llamada da los valores en el mismo orden que los parámetros: <code>torre(40, 16)</code> hace altura = 40 y grosor = 16.",
        "Un mòdul paramètric fa tota una família de peces: la mateixa forma amb mides diferents, fins i tot des d'un bucle.|Un módulo paramétrico hace toda una familia de piezas: la misma forma con medidas distintas, incluso desde un bucle."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "Què construeix <code>defineix fanal() { … }</code> si no hi ha cap <code>fanal()</code> al programa?|¿Qué construye <code>define farola() { … }</code> si no hay ninguna <code>farola()</code> en el programa?", opts: ['Res|Nada', 'Un fanal|Una farola', 'Un fanal per cada línia|Una farola por cada línea'], a: 0 },
        { k: 'm3predict', ph: 'recorda', q: 'Quin model fa?|¿Qué modelo hace?', prog: B(`${CASA}\ncasa()\nmou(0, 30, 0) casa()`),
          opts: [{ prog: B(`${CASA}\ncasa()\nmou(0, 30, 0) casa()`) }, { prog: B(`${CASA}\ncasa()\nmou(30, 0, 0) casa()`) }, { prog: B(`${CASA}\ncasa()`) }], a: 0,
          ex: 'Dues crides: una casa a l\'origen i una altra 30 mm cap al fons (y).|Dos llamadas: una casa en el origen y otra 30 mm hacia el fondo (y).' },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: 'Edificis de totes les mides|Edificios de todos los tamaños',
          t: "La maqueta avança, però l'Ajuntament vol <b>varietat</b>: torres altes i baixes, arbres petits i grans, edificis de 2, 4 i 7 pisos. Un mòdul per a cada mida? Ni pensar-hi! Farem mòduls que reben <b>paràmetres</b>: la mateixa recepta, amb les mides que tu diguis a cada crida.|La maqueta avanza, pero el Ayuntamiento quiere <b>variedad</b>: torres altas y bajas, árboles pequeños y grandes, edificios de 2, 4 y 7 pisos. ¿Un módulo para cada tamaño? ¡Ni pensarlo! Haremos módulos que reciben <b>parámetros</b>: la misma receta, con las medidas que tú digas en cada llamada." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Paràmetres|Parámetros', t: 'Els forats de la recepta|Los huecos de la receta', anim: 'p6param',
            x: "Un <b>paràmetre</b> és un buit de la recepta que s'omple a cada crida. A <code>torre(alçada)</code>, el mòdul no sap quina alçada tindrà fins que el crides: <code>torre(20)</code>, <code>torre(40)</code> o <code>torre(60)</code> fan tres torres diferents amb el mateix codi.|Un <b>parámetro</b> es un hueco de la receta que se rellena en cada llamada. En <code>torre(altura)</code>, el módulo no sabe qué altura tendrá hasta que lo llamas: <code>torre(20)</code>, <code>torre(40)</code> o <code>torre(60)</code> hacen tres torres distintas con el mismo código." },
          { k: 'Definició|Definición', t: 'defineix torre(alçada, gruix)|define torre(altura, grosor)', media: { k: 'model', prog: B(TORRES) },
            x: "Dins del mòdul, <code>alçada</code> i <code>gruix</code> funcionen com variables: el cilindre fa <code>gruix</code> d'ample i <code>alçada</code> d'alt, i el con es posa a z = <code>alçada</code>. Fora del mòdul no existeixen: són només seves.|Dentro del módulo, <code>altura</code> y <code>grosor</code> funcionan como variables: el cilindro mide <code>grosor</code> de ancho y <code>altura</code> de alto, y el cono se pone en z = <code>altura</code>. Fuera del módulo no existen: son solo suyas." },
          { k: "L'ordre|El orden", t: 'El primer valor, al primer paràmetre|El primer valor, al primer parámetro', media: { k: 'model', prog: B(`${TORRE}\ntorre(40, 16)\nmou(40, 0, 0) torre(16, 40)`) },
            x: "Els valors s'assignen <b>per ordre</b>: <code>torre(40, 16)</code> és una torre de 40 d'alt i 16 de gruix; <code>torre(16, 40)</code> és una torre baixa i grossa. El programa no s'equivoca: fa exactament el que li diem.|Los valores se asignan <b>por orden</b>: <code>torre(40, 16)</code> es una torre de 40 de alto y 16 de grosor; <code>torre(16, 40)</code> es una torre baja y gruesa. El programa no se equivoca: hace exactamente lo que le decimos.",
            bad: 'torre(16, 40): 16 d\'alt i 40 de gruix|torre(16, 40): 16 de alto y 40 de grosor', good: 'torre(40, 16): 40 d\'alt i 16 de gruix|torre(40, 16): 40 de alto y 16 de grosor' },
          { k: 'Càlculs|Cálculos', t: 'Paràmetres, càlculs i bucles|Parámetros, cálculos y bucles', media: { k: 'model', prog: B(EDI + ECALLS) },
            x: "Amb els paràmetres es pot calcular i repetir: <code>edifici(pisos)</code> fa un bloc de <code>pisos * 10</code> mm d'alt i un bucle de 0 a <code>(pisos - 1)</code> hi posa les finestres de cada pis. Amb 2, 4 o 6 pisos, tot quadra sol.|Con los parámetros se puede calcular y repetir: <code>edificio(pisos)</code> hace un bloque de <code>pisos * 10</code> mm de alto y un bucle de 0 a <code>(pisos - 1)</code> le pone las ventanas de cada piso. Con 2, 4 o 6 pisos, todo cuadra solo." },
          { k: 'Disseny|Diseño', t: 'Què ha de ser un paràmetre?|¿Qué tiene que ser un parámetro?', media: { k: 'model', prog: B(TFAM) },
            x: "Converteix en paràmetre <b>el que canvia</b> d'una còpia a l'altra; el que és sempre igual, deixa-ho dins del mòdul. Si una crida porta més o menys valors que paràmetres, el taller t'avisa. I pots cridar un mòdul des d'un bucle: <code>torre(20 + i * 10, 12)</code> fa una família de torres creixents.|Convierte en parámetro <b>lo que cambia</b> de una copia a otra; lo que es siempre igual, déjalo dentro del módulo. Si una llamada lleva más o menos valores que parámetros, el taller te avisa. Y puedes llamar a un módulo desde un bucle: <code>torre(20 + i * 10, 12)</code> hace una familia de torres crecientes." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🏠', title: 'Receptes amb buits|Recetas con huecos', t: 'Per parelles, amb paper quadriculat:|Por parejas, con papel cuadriculado:',
          steps: ["Llegiu el mòdul de la fitxa: <b>casa(amplada, alçada)</b> = un rectangle d'amplada × alçada caselles amb un triangle de teulada a sobre.|Leed el módulo de la ficha: <b>casa(ancho, altura)</b> = un rectángulo de ancho × altura casillas con un triángulo de tejado encima.",
            "Una persona diu crides i l'altra dibuixa: <b>casa(4, 3) · casa(2, 5) · casa(6, 2)</b>. Després canvieu els papers.|Una persona dice llamadas y la otra dibuja: <b>casa(4, 3) · casa(2, 5) · casa(6, 2)</b>. Después cambiad los papeles.",
            "Repte: la persona que dicta diu una crida amb els valors girats, <b>casa(3, 4)</b>. Què canvia al dibuix?|Reto: la persona que dicta dice una llamada con los valores girados, <b>casa(3, 4)</b>. ¿Qué cambia en el dibujo?"],
          tip: "Abans de dibuixar, digueu en veu alta quin valor va a cada paràmetre: amplada = 4, alçada = 3.|Antes de dibujar, decid en voz alta qué valor va a cada parámetro: ancho = 4, altura = 3." },
        { k: 'm3predict', ph: 'prova', q: 'Quin model fa?|¿Qué modelo hace?', prog: B(PILAR),
          opts: [{ prog: B(PILAR) }, { prog: B(`defineix pilar(alçada) {\n  cilindre(10, alçada)\n}\npilar(10)\nmou(20, 0, 0) pilar(20)\nmou(40, 0, 0) pilar(30)`) }, { prog: B(`defineix pilar(alçada) {\n  cilindre(10, alçada)\n}\npilar(30)\nmou(20, 0, 0) pilar(30)\nmou(40, 0, 0) pilar(30)`) }], a: 0,
          ex: 'Tres pilars de 10, 30 i 20 mm: baix, alt i mitjà, en aquest ordre.|Tres pilares de 10, 30 y 20 mm: bajo, alto y mediano, en este orden.' },
        { k: 'm3predict', ph: 'prova', q: 'Compte amb l\'ordre dels valors. Quin bloc surt?|Cuidado con el orden de los valores. ¿Qué bloque sale?', prog: B(`defineix bloc(costat, alçada) {\n  cub(costat, costat, alçada)\n}\nbloc(30, 10)`),
          opts: [{ prog: 'cub(30, 30, 10)' }, { prog: 'cub(10, 10, 30)' }, { prog: 'cub(30, 10, 10)' }], a: 0,
          ex: 'costat = 30 i alçada = 10: una placa quadrada de 30 × 30 i 10 mm d\'alt.|lado = 30 y altura = 10: una placa cuadrada de 30 × 30 y 10 mm de alto.' },
        { k: 'm3spot', ph: 'investiga', q: 'Els edificis tenen una <b>fila de finestres de més</b>, per sobre del terrat. Toca la instrucció que falla.|Los edificios tienen una <b>fila de ventanas de más</b>, por encima de la azotea. Toca la instrucción que falla.', prog: B(`defineix edifici(pisos) {\n  color("blau") cub(24, 20, pisos * 10)\n  repeteix p de 0 a (pisos)! {\n    repeteix f de 0 a 1 {\n      mou(4 + f * 10, -1, 3 + p * 10) color("groc") cub(6, 2, 5)\n    }\n  }\n}${ECALLS}`), target: EDI + ECALLS,
          ex: "De 0 a pisos fa pisos + 1 voltes: l'última fila de finestres surt per sobre del terrat. Ha de ser de 0 a (pisos − 1).|De 0 a pisos da pisos + 1 vueltas: la última fila de ventanas sale por encima de la azotea. Tiene que ser de 0 a (pisos − 1)." },
        { k: 'm3spot', ph: 'investiga', q: "La tercera torre havia de ser alta i prima, però ha sortit <b>baixa i grossa</b>. Quina crida està malament?|La tercera torre tenía que ser alta y delgada, pero ha salido <b>baja y gruesa</b>. ¿Qué llamada está mal?", prog: B(`${TORRE}\ntorre(30, 14)\nmou(30, 0, 0) torre(50, 14)\nmou(60, 0, 0) torre(22, 40)!`), target: `${TORRE}\ntorre(30, 14)\nmou(30, 0, 0) torre(50, 14)\nmou(60, 0, 0) torre(40, 22)`,
          ex: "Els valors estan girats: torre(22, 40) fa 22 d'alt i 40 de gruix. El primer valor és l'alçada: torre(40, 22).|Los valores están girados: torre(22, 40) mide 22 de alto y 40 de grosor. El primer valor es la altura: torre(40, 22)." },
        { k: 'move', ph: 'pausa', title: 'Salta(n)|Salta(n)', secs: 30,
          t: "El mòdul <b>salta(n)</b> vol dir fer n salts. El professor/a diu crides i tothom les fa: <b>salta(2) · salta(5) · salta(1)</b>. I ara un mòdul amb dos paràmetres: <b>gira_i_salta(voltes, salts)</b>!|El módulo <b>salta(n)</b> quiere decir dar n saltos. El profesor/a dice llamadas y todos las hacen: <b>salta(2) · salta(5) · salta(1)</b>. ¡Y ahora un módulo con dos parámetros: <b>gira_y_salta(vueltas, saltos)</b>!" },
        { k: 'm3code', ph: 'repte', text: true, q: "Les tres torres són iguals perquè <code>torre()</code> no té paràmetres. Afegeix-li el paràmetre <code>alçada</code> perquè facin <b>30, 45 i 60 mm</b>, com el fantasma.|Las tres torres son iguales porque <code>torre()</code> no tiene parámetros. Añádele el parámetro <code>altura</code> para que midan <b>30, 45 y 60 mm</b>, como el fantasma.", start: B(T0), blocks: ['def', 'call', 'cil', 'con', 'mou'],
          target: T1, checks: [ck('match', { target: T1, th: 0.9, t: GH }), ck('uses', { b: 'def' }), ck('size', { ax: 'z', v: 72 })],
          hint: "defineix torre(alçada): canvia el 40 del cilindre i el del mou per alçada. Després, crida torre(30), torre(45) i torre(60).|define torre(altura): cambia el 40 del cilindro y el del mueve por altura. Después, llama a torre(30), torre(45) y torre(60).", sol: B(T1) },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Dos paràmetres.</b> La tanca ja té el paràmetre <code>n</code> (quants pals). Afegeix-li <code>alçada</code>: els pals fan alçada mm i la travessa va a alçada − 8. Fes una tanca de 5 pals de 20 mm i una de 8 pals de 30 mm.|<b>Dos parámetros.</b> La valla ya tiene el parámetro <code>n</code> (cuántos postes). Añádele <code>altura</code>: los postes miden altura mm y el travesaño va en altura − 8. Haz una valla de 5 postes de 20 mm y una de 8 postes de 30 mm.", start: B(TANCA0), blocks: ['def', 'call', 'cub', 'mou', 'rep'],
          target: TANCA, checks: [ck('match', { target: TANCA, th: 0.88, t: GH }), ck('count', { t: 'box', min: 15, max: 15, txt: '5 + 8 pals i 2 travesses|5 + 8 postes y 2 travesaños' }), ck('size', { ax: 'z', v: 30 })],
          hint: "defineix tanca(n, alçada); al cub dels pals posa alçada i a la z de la travessa, alçada - 8. Crides: tanca(5, 20) i mou(0, 30, 0) tanca(8, 30).|define valla(n, altura); en el cubo de los postes pon altura y en la z del travesaño, altura - 8. Llamadas: valla(5, 20) y mueve(0, 30, 0) valla(8, 30).", sol: B(TANCA) },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Edificis amb finestres.</b> Afegeix al mòdul <code>edifici(pisos)</code> dues finestres grogues de 6 × 2 × 5 mm per pis (a x = 4 i 14, y = −1 i z = 3 + p × 10). Les crides ja hi són.|<b>Edificios con ventanas.</b> Añade al módulo <code>edificio(pisos)</code> dos ventanas amarillas de 6 × 2 × 5 mm por piso (en x = 4 y 14, y = −1 y z = 3 + p × 10). Las llamadas ya están.", start: B(EDI0 + ECALLS), blocks: ['def', 'cub', 'mou', 'color', 'rep'],
          target: EDI + ECALLS, checks: [ck('match', { target: EDI + ECALLS, th: 0.9, t: GH }), ck('uses', { b: 'rep' }), ck('count', { t: 'box', min: 27, max: 27, txt: '3 edificis i 24 finestres|3 edificios y 24 ventanas' })],
          hint: "Dins del mòdul: repeteix p de 0 a (pisos - 1) { repeteix f de 0 a 1 { mou(4 + f * 10, -1, 3 + p * 10) color(\"groc\") cub(6, 2, 5) } }.|Dentro del módulo: repite p de 0 a (pisos - 1) { repite f de 0 a 1 { mueve(4 + f * 10, -1, 3 + p * 10) color(\"amarillo\") cubo(6, 2, 5) } }.", sol: B(EDI + ECALLS) },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>La família de torres.</b> Amb el mòdul <code>torre(alçada, gruix)</code> i un bucle, fes 5 torres de gruix 12, una cada 25 mm, de 20, 30, 40, 50 i 60 mm d'alt.|<b>La familia de torres.</b> Con el módulo <code>torre(altura, grosor)</code> y un bucle, haz 5 torres de grosor 12, una cada 25 mm, de 20, 30, 40, 50 y 60 mm de alto.", start: B(TORRE), blocks: ['call', 'mou', 'rep'],
          target: TFAM, checks: [ck('match', { target: TFAM, th: 0.9, t: GH }), ck('uses', { b: 'rep' }), ck('uses', { b: 'call' }), ck('count', { t: 'cone', min: 5, max: 5, txt: 'Exactament 5 torres|Exactamente 5 torres' }), ck('size', { ax: 'z', v: 72 })],
          hint: "L'alçada depèn del comptador: torre(20 + i * 10, 12). La posició: mou(i * 25, 0, 0).|La altura depende del contador: torre(20 + i * 10, 12). La posición: mueve(i * 25, 0, 0).", sol: B(TFAM) },
        { k: 'm3code', ph: 'repte', text: true, extra: true, q: "⭐ <b>L'escala de cargol.</b> Fes 12 esglaons amb <code>esglaó(30)</code>: cada un puja 6 mm i gira 30° més que l'anterior al voltant de la columna. Cada esglaó, centrat sobre el radi.|⭐ <b>La escalera de caracol.</b> Haz 12 peldaños con <code>peldaño(30)</code>: cada uno sube 6 mm y gira 30° más que el anterior alrededor de la columna. Cada peldaño, centrado sobre el radio.", start: B(SPIRAL0), blocks: ['call', 'mou', 'gira', 'rep'],
          target: SPIRAL, checks: [ck('match', { target: SPIRAL, th: 0.85, t: GH }), ck('count', { t: 'box', min: 12, max: 12, txt: 'Exactament 12 esglaons|Exactamente 12 peldaños' }), ck('one'), ck('uses', { b: 'call' })],
          hint: "repeteix i de 0 a 11 { mou(0, 0, i * 6) gira(0, 0, i * 30) mou(0, -5, 0) esglaó(30) }: puja, gira i centra (l'esglaó fa 10 de fons).|repite i de 0 a 11 { mueve(0, 0, i * 6) gira(0, 0, i * 30) mueve(0, -5, 0) peldaño(30) }: sube, gira y centra (el peldaño mide 10 de fondo).", sol: B(SPIRAL) },
        { k: 'm3free', ph: 'crea', text: true, q: "<b>La família de peces.</b> Crea un mòdul amb almenys un paràmetre (una torre, un arbre, un pont, una font…) i crida'l almenys 3 vegades amb valors diferents.|<b>La familia de piezas.</b> Crea un módulo con al menos un parámetro (una torre, un árbol, un puente, una fuente…) y llámalo al menos 3 veces con valores distintos.",
          name: 'La meva família de peces|Mi familia de piezas', blocks: ['cub', 'cil', 'esf', 'con', 'pir', 'tub', 'mou', 'gira', 'color', 'rep', 'def', 'call', 'var'],
          crit: ["El mòdul té almenys un paràmetre amb un nom clar|El módulo tiene al menos un parámetro con un nombre claro", "Hi ha almenys 3 crides amb valors diferents|Hay al menos 3 llamadas con valores distintos", "Les peces toquen la placa|Las piezas tocan la placa"],
          checks: [ck('uses', { b: 'def' }), ck('uses', { b: 'call' }), ck('count', { min: 6, txt: 'Almenys 6 peces|Al menos 6 piezas' }), ck('onplate')], sol: B(FAMFREE) },
        { k: 'quiz', ph: 'tanca', q: "Amb <code>defineix torre(alçada, gruix)</code>, què fa <code>torre(50, 10)</code>?|Con <code>define torre(altura, grosor)</code>, ¿qué hace <code>torre(50, 10)</code>?", opts: ["Una torre de 50 mm d'alt i 10 de gruix|Una torre de 50 mm de alto y 10 de grosor", "Una torre de 10 mm d'alt i 50 de gruix|Una torre de 10 mm de alto y 50 de grosor", "50 torres de 10 mm|50 torres de 10 mm"], a: 0 },
        { k: 'quiz', ph: 'tanca', q: "On existeix el paràmetre <code>alçada</code> de <code>torre(alçada)</code>?|¿Dónde existe el parámetro <code>altura</code> de <code>torre(altura)</code>?", opts: ['Només dins del mòdul torre|Solo dentro del módulo torre', 'A tot el programa|En todo el programa', 'Només a la primera crida|Solo en la primera llamada'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* =================================================================== p6-3 */
    { id: 'p6-3', t: 'La biblioteca de peces|La biblioteca de piezas', min: 40, badge: 'p6biblio',
      learn: ["Una biblioteca de peces agrupa mòduls amb noms clars i un comentari que diu què fan i què vol dir cada paràmetre.|Una biblioteca de piezas agrupa módulos con nombres claros y un comentario que dice qué hacen y qué quiere decir cada parámetro.",
        "Un programa ben organitzat té tres parts: les variables principals, la biblioteca de mòduls i l'escena que els fa servir.|Un programa bien organizado tiene tres partes: las variables principales, la biblioteca de módulos y la escena que los usa.",
        "Per fer servir el mòdul d'una altra persona, llegeixo el comentari i la definició: el nom, els paràmetres en ordre i on té l'origen.|Para usar el módulo de otra persona, leo el comentario y la definición: el nombre, los parámetros en orden y dónde tiene el origen."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "Amb <code>defineix porta(amplada, alçada)</code>, què fa <code>porta(30, 20)</code>?|Con <code>define puerta(ancho, altura)</code>, ¿qué hace <code>puerta(30, 20)</code>?", opts: ["Una porta de 30 mm d'ample i 20 d'alt|Una puerta de 30 mm de ancho y 20 de alto", "Una porta de 20 mm d'ample i 30 d'alt|Una puerta de 20 mm de ancho y 30 de alto", "Dues portes|Dos puertas"], a: 0 },
        { k: 'quiz', ph: 'recorda', q: "Què fa una línia que comença amb <code>//</code>?|¿Qué hace una línea que empieza con <code>//</code>?", opts: ["És un comentari: el taller no la fa, és per a les persones|Es un comentario: el taller no la hace, es para las personas", 'Divideix el model en dues parts|Divide el modelo en dos partes', 'Esborra la línia de sota|Borra la línea de abajo'], a: 0 },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: "La biblioteca de l'estudi|La biblioteca del estudio",
          t: "Ara som tres enginyers fent la maqueta i cadascú ha programat els seus mòduls: fanals, bancs, arbres… Però hi ha mòduls que es diuen <code>m1</code>, <code>cosa</code> o <code>prova2</code>, i ningú sap quins paràmetres tenen! Avui muntarem una <b>biblioteca de peces</b> ben organitzada, perquè un codi s'escriu una vegada… i es llegeix moltes.|Ahora somos tres ingenieros haciendo la maqueta y cada uno ha programado sus módulos: farolas, bancos, árboles… Pero hay módulos que se llaman <code>m1</code>, <code>cosa</code> o <code>prueba2</code>, ¡y nadie sabe qué parámetros tienen! Hoy montaremos una <b>biblioteca de piezas</b> bien organizada, porque un código se escribe una vez… y se lee muchas." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Organització|Organización', t: 'Les tres parts d\'un programa|Las tres partes de un programa', anim: 'p6lib',
            x: "Un programa llarg s'entén molt millor si sempre té el mateix ordre: <b>1</b>, les variables principals (les que algú voldrà canviar); <b>2</b>, la biblioteca de mòduls; <b>3</b>, l'escena, que crida els mòduls. Com un llibre de receptes: primer els ingredients, després les receptes i al final el menú.|Un programa largo se entiende mucho mejor si siempre tiene el mismo orden: <b>1</b>, las variables principales (las que alguien querrá cambiar); <b>2</b>, la biblioteca de módulos; <b>3</b>, la escena, que llama a los módulos. Como un libro de recetas: primero los ingredientes, después las recetas y al final el menú." },
          { k: 'Comentaris|Comentarios', t: '// per a les persones|// para las personas', media: { k: 'model', prog: B(`${LFANAL}\nfanal(30)\nmou(25, 0, 0) fanal(20)`) },
            x: "El taller ignora el que hi ha després de <code>//</code>. Per això hi escrivim el que una altra persona necessita saber: <b>què fa</b> el mòdul, <b>què vol dir cada paràmetre</b> i en quines unitats. Escriu el comentari en una línia a part, just a sobre del mòdul.|El taller ignora lo que hay después de <code>//</code>. Por eso escribimos lo que otra persona necesita saber: <b>qué hace</b> el módulo, <b>qué quiere decir cada parámetro</b> y en qué unidades. Escribe el comentario en una línea aparte, justo encima del módulo." },
          { k: 'Noms|Nombres', t: 'Noms que expliquen|Nombres que explican', media: { k: 'model', prog: B(`${PORTA}\nporta(30, 20)`) },
            x: "Compara <code>m1(a, b)</code> amb <code>porta(amplada, alçada)</code>: el segon s'entén sense obrir-lo. Fes servir paraules senceres, en minúscules, i si en necessites dues, uneix-les amb una ratlla baixa: <code>banc_parc</code>. Per a mesures molt conegudes, una lletra també val (d = diàmetre).|Compara <code>m1(a, b)</code> con <code>puerta(ancho, altura)</code>: el segundo se entiende sin abrirlo. Usa palabras enteras, en minúsculas, y si necesitas dos, únelas con un guion bajo: <code>banco_parque</code>. Para medidas muy conocidas, una letra también vale (d = diámetro).",
            bad: 'defineix m1(a, b) { … }|define m1(a, b) { … }', good: 'defineix porta(amplada, alçada) { … }|define puerta(ancho, altura) { … }' },
          { k: 'Convenció|Convención', t: "On és l'origen de cada mòdul?|¿Dónde está el origen de cada módulo?", media: { k: 'model', prog: B(`${LBANC}\nbanc(36)\nmou(0, 25, 0) banc(20)`) },
            x: "Si cada mòdul té l'origen en un lloc diferent, és molt difícil col·locar-los. A la nostra biblioteca, la <b>convenció</b> és: tots els mòduls tenen l'origen <b>al centre de la base</b>. Per això el banc comença a <code>-llargada / 2</code>: així <code>mou(x, y, 0) banc(…)</code> el posa centrat a (x, y) i tocant la placa.|Si cada módulo tiene el origen en un sitio distinto, es muy difícil colocarlos. En nuestra biblioteca, la <b>convención</b> es: todos los módulos tienen el origen <b>en el centro de la base</b>. Por eso el banco empieza en <code>-largo / 2</code>: así <code>mueve(x, y, 0) banco(…)</code> lo pone centrado en (x, y) y tocando la placa." },
          { k: 'Llegir codi|Leer código', t: "Fer servir mòduls d'altres|Usar módulos de otros", media: { k: 'model', prog: B(LIB + PLACA) },
            x: "Per fer servir un mòdul que no has escrit tu: llegeix el <b>comentari</b>, mira els <b>paràmetres</b> i el seu ordre, <b>prediu</b> què farà i fes una crida de prova. És el mateix mètode de sempre: predir, executar, investigar i modificar.|Para usar un módulo que no has escrito tú: lee el <b>comentario</b>, mira los <b>parámetros</b> y su orden, <b>predice</b> qué hará y haz una llamada de prueba. Es el mismo método de siempre: predecir, ejecutar, investigar y modificar." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '📇', title: 'El catàleg de peces|El catálogo de piezas', t: 'En grups de 3, amb les fitxes de catàleg:|En grupos de 3, con las fichas de catálogo:',
          steps: ["Cada persona tria un element de la maqueta (paperera, parada d'autobús, gronxador…) i omple una fitxa de catàleg: nom del mòdul, què fa, paràmetres amb unitats, una crida d'exemple i un esbós amb l'origen marcat.|Cada persona elige un elemento de la maqueta (papelera, parada de autobús, columpio…) y rellena una ficha de catálogo: nombre del módulo, qué hace, parámetros con unidades, una llamada de ejemplo y un boceto con el origen marcado.",
            "Passeu la fitxa a la persona de la dreta. Sense preguntar res, ha d'escriure una crida per posar aquell element en un lloc concret de la plaça.|Pasad la ficha a la persona de la derecha. Sin preguntar nada, tiene que escribir una llamada para poner ese elemento en un sitio concreto de la plaza.",
            "Torneu-vos les fitxes: la crida fa el que esperava qui l'ha escrita? Què faltava a la fitxa?|Devolveos las fichas: ¿la llamada hace lo que esperaba quien la ha escrito? ¿Qué faltaba en la ficha?"],
          tip: "Una bona documentació respon totes les preguntes abans que ningú les faci.|Una buena documentación responde todas las preguntas antes de que nadie las haga." },
        { k: 'm3predict', ph: 'prova', q: "Llegeix el comentari i el mòdul d'un company. <b>Quina porta surt?</b>|Lee el comentario y el módulo de un compañero. <b>¿Qué puerta sale?</b>", prog: B(`${PORTA}\nporta(30, 20)`),
          opts: [{ prog: B(`${PORTA}\nporta(30, 20)`) }, { prog: B(`${PORTA}\nporta(20, 30)`) }, { prog: B(`${PORTA}\nporta(30, 8)`) }], a: 0,
          ex: "El comentari diu porta(amplada, alçada): 30 mm d'ample i 20 d'alt, amb la llinda (el cub de dalt) a z = 20.|El comentario dice puerta(ancho, altura): 30 mm de ancho y 20 de alto, con el dintel (el cubo de arriba) en z = 20." },
        { k: 'm3spot', ph: 'investiga', q: "Els bancs de la plaça tenen el <b>seient desplaçat</b> respecte de les potes. Toca la instrucció del mòdul que no segueix la convenció.|Los bancos de la plaza tienen el <b>asiento desplazado</b> respecto a las patas. Toca la instrucción del módulo que no sigue la convención.", prog: B(`${LBANCBAD}\nbanc(36)\nmou(0, 25, 0) banc(20)`), target: `${LBANC}\nbanc(36)\nmou(0, 25, 0) banc(20)`,
          ex: "La convenció diu que el banc està centrat: el seient ha de començar a x = −llargada / 2, com el respatller. Amb x = 0 queda mig banc fora de les potes.|La convención dice que el banco está centrado: el asiento tiene que empezar en x = −largo / 2, como el respaldo. Con x = 0 queda medio banco fuera de las patas." },
        { k: 'm3spot', ph: 'investiga', q: "L'entrada de la plaça havia de ser una porta <b>ampla i baixa</b> (30 d'ample i 20 d'alt), però ha sortit estreta i alta. Quina instrucció falla?|La entrada de la plaza tenía que ser una puerta <b>ancha y baja</b> (30 de ancho y 20 de alto), pero ha salido estrecha y alta. ¿Qué instrucción falla?", prog: B(`${PORTA}\nporta(20, 30)!`), target: `${PORTA}\nporta(30, 20)`,
          ex: "El mòdul està bé: l'error és a la crida. El comentari diu porta(amplada, alçada), per tant ha de ser porta(30, 20).|El módulo está bien: el error está en la llamada. El comentario dice puerta(ancho, altura), por lo tanto tiene que ser puerta(30, 20)." },
        { k: 'move', ph: 'pausa', title: 'La biblioteca humana|La biblioteca humana', secs: 30,
          t: "Cada fila de la classe és un mòdul: <b>fila 1 = picar de mans(n)</b>, <b>fila 2 = saltar(n)</b>, <b>fila 3 = girar(graus)</b>. El professor/a crida i només s'aixeca la fila del mòdul cridat: <b>saltar(3) · girar(180) · picar de mans(4)</b>.|Cada fila de la clase es un módulo: <b>fila 1 = dar palmadas(n)</b>, <b>fila 2 = saltar(n)</b>, <b>fila 3 = girar(grados)</b>. El profesor/a llama y solo se levanta la fila del módulo llamado: <b>saltar(3) · girar(180) · dar palmadas(4)</b>." },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Fes servir la biblioteca.</b> Llegeix els comentaris i munta la plaça del fantasma: dos fanals de 30 mm a x = −30 i x = 30, un banc de 36 mm al centre i un arbre de mida 16 a (0, 30).|<b>Usa la biblioteca.</b> Lee los comentarios y monta la plaza del fantasma: dos farolas de 30 mm en x = −30 y x = 30, un banco de 36 mm en el centro y un árbol de tamaño 16 en (0, 30).", start: B(LIB), blocks: ['call', 'mou', 'rem'],
          target: LIB + PLACA, checks: [ck('match', { target: LIB + PLACA, th: 0.88, t: GH }), ck('uses', { b: 'call' }), ck('count', { t: 'sph', min: 3, max: 3, txt: '2 llums i 1 copa (3 esferes)|2 luces y 1 copa (3 esferas)' })],
          hint: "Escriu l'escena a sota de la biblioteca: mou(-30, 0, 0) fanal(30), mou(30, 0, 0) fanal(30), banc(36) i mou(0, 30, 0) arbre(16).|Escribe la escena debajo de la biblioteca: mueve(-30, 0, 0) farola(30), mueve(30, 0, 0) farola(30), banco(36) y mueve(0, 30, 0) árbol(16).", sol: B(LIB + PLACA) },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Arregla el mòdul que no s'adapta.</b> L'arbre de mida 16 surt bé, però el petit té la copa flotant i el gran, enfonsada. Fes que la copa vagi sempre a dalt del tronc, sigui quina sigui la mida.|<b>Arregla el módulo que no se adapta.</b> El árbol de tamaño 16 sale bien, pero el pequeño tiene la copa flotando y el grande, hundida. Haz que la copa vaya siempre encima del tronco, sea cual sea el tamaño.", start: B(ARBREBAD), blocks: ['def', 'call', 'cil', 'esf', 'mou'],
          target: ARBREOK, checks: [ck('match', { target: ARBREOK, th: 0.92, t: GH }), ck('count', { t: 'sph', min: 3, max: 3, txt: '3 arbres|3 árboles' }), ck('zmax', { v: 36.5, t: "L'arbre gran fa 24 + 12 = 36 mm|El árbol grande mide 24 + 12 = 36 mm" })],
          hint: "El tronc fa mida d'alt: la copa ha d'anar a z = mida, no a 16. Un número fix dins d'un mòdul amb paràmetres sol ser sospitós!|El tronco mide tamaño de alto: la copa tiene que ir en z = tamaño, no en 16. ¡Un número fijo dentro de un módulo con parámetros suele ser sospechoso!", sol: B(ARBREOK) },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Afegeix un mòdul a la biblioteca.</b> Defineix <code>font(d)</code>: una base <code>cilindre(d, 2)</code>, una bassa <code>tub(d, 8, 2)</code>, un sortidor <code>cilindre(4, 14)</code> i una bola de 8 mm a z = 14. Posa una font de 30 mm al centre de la plaça.|<b>Añade un módulo a la biblioteca.</b> Define <code>fuente(d)</code>: una base <code>cilindro(d, 2)</code>, un estanque <code>tubo(d, 8, 2)</code>, un surtidor <code>cilindro(4, 14)</code> y una bola de 8 mm en z = 14. Pon una fuente de 30 mm en el centro de la plaza.", start: B(`${LBANC}${BANCS4}`), blocks: ['def', 'call', 'cil', 'tub', 'esf', 'mou', 'rem'],
          target: `${LBANC}\n${LFONT}\nfont(30)${BANCS4}`, checks: [ck('match', { target: `${LBANC}\n${LFONT}\nfont(30)${BANCS4}`, th: 0.88, t: GH }), ck('count', { t: 'tube', min: 1, max: 1, txt: 'Hi ha la bassa (un tub)|Está el estanque (un tubo)' }), ck('uses', { b: 'def' })],
          hint: "Com els altres mòduls: un comentari a sobre i l'origen al centre de la base. defineix font(d) { cilindre(d, 2) tub(d, 8, 2) cilindre(4, 14) mou(0, 0, 14) esfera(8) } i, a l'escena, font(30).|Como los otros módulos: un comentario encima y el origen en el centro de la base. define fuente(d) { cilindro(d, 2) tubo(d, 8, 2) cilindro(4, 14) mueve(0, 0, 14) esfera(8) } y, en la escena, fuente(30).", sol: B(`${LBANC}\n${LFONT}\nfont(30)${BANCS4}`) },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Un mòdul que fa servir la biblioteca.</b> Defineix <code>filera(n)</code>, que posa n arbres de mida 12 en fila, un cada 25 mm. Després fes una filera de 4 i, 40 mm més al fons, una de 6.|<b>Un módulo que usa la biblioteca.</b> Define <code>hilera(n)</code>, que pone n árboles de tamaño 12 en fila, uno cada 25 mm. Después haz una hilera de 4 y, 40 mm más al fondo, una de 6.", start: B(LARBRE), blocks: ['def', 'call', 'mou', 'rep', 'rem'],
          target: FILERA, checks: [ck('match', { target: FILERA, th: 0.9, t: GH }), ck('uses', { b: 'rep' }), ck('count', { t: 'sph', min: 10, max: 10, txt: '4 + 6 = 10 arbres|4 + 6 = 10 árboles' })],
          hint: "defineix filera(n) { repeteix i de 0 a (n - 1) { mou(i * 25, 0, 0) arbre(12) } }. Crides: filera(4) i mou(0, 40, 0) filera(6).|define hilera(n) { repite i de 0 a (n - 1) { mueve(i * 25, 0, 0) árbol(12) } }. Llamadas: hilera(4) y mueve(0, 40, 0) hilera(6).", sol: B(FILERA) },
        { k: 'm3code', ph: 'repte', text: true, extra: true, q: "⭐ <b>La plaça paramètrica.</b> Amb la variable <code>n</code>, reparteix n bancs al voltant de la font, girats 360 / n, a 35 mm del centre. Ha de funcionar amb qualsevol n.|⭐ <b>La plaza paramétrica.</b> Con la variable <code>n</code>, reparte n bancos alrededor de la fuente, girados 360 / n, a 35 mm del centro. Tiene que funcionar con cualquier n.", start: B(`n = 4\n${LBANC}\n${LFONT}\nfont(30)`), blocks: ['call', 'mou', 'gira', 'rep', 'var'], vars: ['n'],
          target: PLAZAN, checks: [ck('count', { t: 'box', min: '4 * n', max: '4 * n', txt: 'n bancs de 4 peces cada un|n bancos de 4 piezas cada uno' }), ck('uses', { b: 'gira' }), ck('param', { v: 'n', vals: [3, 6] })],
          hint: "Un patró circular amb el mòdul: repeteix i de 0 a (n - 1) { gira(0, 0, i * 360 / n) mou(0, 35, 0) banc(30) }.|Un patrón circular con el módulo: repite i de 0 a (n - 1) { gira(0, 0, i * 360 / n) mueve(0, 35, 0) banco(30) }.", sol: B(PLAZAN) },
        { k: 'm3free', ph: 'crea', text: true, q: "<b>Amplia la biblioteca.</b> Afegeix-hi un mòdul teu, ben documentat (paperera, gronxador, parada de bus, escultura…), i fes-lo servir almenys dues vegades en una escena amb els mòduls de la biblioteca.|<b>Amplía la biblioteca.</b> Añade un módulo tuyo, bien documentado (papelera, columpio, parada de bus, escultura…), y úsalo al menos dos veces en una escena con los módulos de la biblioteca.",
          name: 'La meva plaça|Mi plaza', start: B(`${LIB}\n// ===== L'escena: la plaça =====\nbanc(36)`), blocks: ['cub', 'cil', 'esf', 'con', 'pir', 'tub', 'mou', 'gira', 'color', 'rep', 'def', 'call', 'var', 'rem'],
          crit: ["El teu mòdul té un comentari que explica què fa i els seus paràmetres|Tu módulo tiene un comentario que explica qué hace y sus parámetros", "Té un nom clar i l'origen al centre de la base, com els altres|Tiene un nombre claro y el origen en el centro de la base, como los demás", "L'escena fa servir el teu mòdul almenys 2 vegades|La escena usa tu módulo al menos 2 veces"],
          checks: [ck('uses', { b: 'def' }), ck('uses', { b: 'call' }), ck('count', { min: 8, txt: 'Almenys 8 peces|Al menos 8 piezas' }), ck('onplate')], sol: B(`${LIB}\n${LFONT}\nfont(30)\nmou(-40, 0, 0) fanal(30)\nmou(40, 0, 0) fanal(30)\nmou(0, -35, 0) banc(30)\nmou(-40, 35, 0) arbre(14)\nmou(40, 35, 0) arbre(14)`) },
        { k: 'quiz', ph: 'tanca', q: "En quin ordre és més fàcil de llegir un programa llarg?|¿En qué orden es más fácil leer un programa largo?", opts: ["Variables, després mòduls i al final l'escena|Variables, después módulos y al final la escena", "L'escena, després les variables, i els mòduls barrejats|La escena, después las variables, y los módulos mezclados", "No importa gens|No importa nada"], a: 0 },
        { k: 'quiz', ph: 'tanca', q: "Quin comentari ajuda més qui farà servir el teu mòdul <code>banc(llargada)</code>?|¿Qué comentario ayuda más a quien usará tu módulo <code>banco(largo)</code>?", opts: ["// banc(llargada): seient, potes i respatller, centrat; llargada en mm|// banco(largo): asiento, patas y respaldo, centrado; largo en mm", '// el meu banc|// mi banco', '// prova 2|// prueba 2'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    /* =================================================================== p6-4 */
    { id: 'p6-4', t: 'Projecte: la ciutat modular|Proyecto: la ciudad modular', min: 45, proj: true, badge: 'p6ciutat',
      learn: ["Un model gran es dissenya per parts: primer els mòduls (la biblioteca) i després l'escena que els combina.|Un modelo grande se diseña por partes: primero los módulos (la biblioteca) y después la escena que los combina.",
        "Mòduls, bucles i paràmetres fan una ciutat sencera amb poques línies: canviant una variable canvia tot el barri.|Módulos, bucles y parámetros hacen una ciudad entera con pocas líneas: cambiando una variable cambia todo el barrio.",
        "Un projecte d'enginyeria es planifica (esbós, mòduls, paràmetres), es construeix a poc a poc i es prova sovint.|Un proyecto de ingeniería se planifica (boceto, módulos, parámetros), se construye poco a poco y se prueba a menudo."],
      steps: [
        { k: 'm3predict', ph: 'recorda', q: 'Mòdul i bucle junts. <b>Quin carrer surt?</b>|Módulo y bucle juntos. <b>¿Qué calle sale?</b>', prog: B(`${EDIF}\nrepeteix i de 0 a 2 {\n  mou(i * 30, 0, 0) edifici(3 - i)\n}`),
          opts: [{ prog: B(`${EDIF}\nrepeteix i de 0 a 2 {\n  mou(i * 30, 0, 0) edifici(3 - i)\n}`) }, { prog: B(`${EDIF}\nrepeteix i de 0 a 2 {\n  mou(i * 30, 0, 0) edifici(1 + i)\n}`) }, { prog: B(`${EDIF}\nrepeteix i de 0 a 2 {\n  mou(i * 30, 0, 0) edifici(2)\n}`) }], a: 0,
          ex: "i val 0, 1 i 2: els edificis tenen 3, 2 i 1 pisos. El carrer baixa d'esquerra a dreta.|i vale 0, 1 y 2: los edificios tienen 3, 2 y 1 pisos. La calle baja de izquierda a derecha." },
        { k: 'quiz', ph: 'recorda', q: "Per què el mòdul <code>edifici</code> fa el bucle de 0 a <code>(pisos - 1)</code>?|¿Por qué el módulo <code>edificio</code> hace el bucle de 0 a <code>(pisos - 1)</code>?", opts: ["Perquè així hi ha exactament una fila de finestres per pis|Porque así hay exactamente una fila de ventanas por piso", 'Perquè el primer pis no té finestres|Porque el primer piso no tiene ventanas', "Perquè els bucles no poden arribar a pisos|Porque los bucles no pueden llegar a pisos"], a: 0 },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'estudi', title: 'El barri del futur|El barrio del futuro',
          t: "Arriba el gran encàrrec: la maqueta del <b>barri del futur</b> per a l'exposició de l'Ajuntament. Cada enginyer de l'estudi dissenyarà una <b>illa de cases</b> de 120 × 120 mm, i les ajuntarem totes com un trencaclosques. La teva illa ha de sortir d'un programa amb mòduls, bucles i paràmetres. La Nuvi imprimirà les illes una a una!|Llega el gran encargo: la maqueta del <b>barrio del futuro</b> para la exposición del Ayuntamiento. Cada ingeniero del estudio diseñará una <b>manzana</b> de 120 × 120 mm, y las juntaremos todas como un rompecabezas. Tu manzana tiene que salir de un programa con módulos, bucles y parámetros. ¡La Nuvi imprimirá las manzanas una a una!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Pla|Plan', t: 'Com es fa un projecte gran|Cómo se hace un proyecto grande', anim: 'p6plan',
            x: "No es comença escrivint codi: <b>1</b> esbós en paper (vista de dalt, mides), <b>2</b> llista de mòduls i els seus paràmetres, <b>3</b> programar i provar cada mòdul sol, <b>4</b> muntar l'escena amb bucles, <b>5</b> comprovar que es pot imprimir. Si alguna cosa falla, tornes al pas que toca.|No se empieza escribiendo código: <b>1</b> boceto en papel (vista de arriba, medidas), <b>2</b> lista de módulos y sus parámetros, <b>3</b> programar y probar cada módulo solo, <b>4</b> montar la escena con bucles, <b>5</b> comprobar que se puede imprimir. Si algo falla, vuelves al paso que toca." },
          { k: 'Mòdul|Módulo', t: 'El mòdul edifici(pisos)|El módulo edificio(pisos)', media: { k: 'model', prog: B(EDIF1) },
            x: "Un bloc de 20 × 20 mm i <code>pisos * 10</code> d'alt, una finestra per pis i un terrat que sobresurt 1 mm. Com tots els mòduls de la biblioteca, es prova sol amb diverses crides abans de fer-lo servir a la ciutat.|Un bloque de 20 × 20 mm y <code>pisos * 10</code> de alto, una ventana por piso y una azotea que sobresale 1 mm. Como todos los módulos de la biblioteca, se prueba solo con varias llamadas antes de usarlo en la ciudad." },
          { k: 'Escena|Escena', t: "La illa: graella d'edificis|La manzana: rejilla de edificios", media: { k: 'model', prog: B(BLOCK) },
            x: "Dos bucles niats col·loquen 3 × 3 edificis sobre la base, cada 40 mm, i el nombre de pisos depèn de la posició: <code>edifici(1 + i + j)</code>. Els edificis de la cantonada del fons són els més alts. Nou edificis… amb tres línies!|Dos bucles anidados colocan 3 × 3 edificios sobre la base, cada 40 mm, y el número de pisos depende de la posición: <code>edificio(1 + i + j)</code>. Los edificios de la esquina del fondo son los más altos. Nueve edificios… ¡con tres líneas!" },
          { k: 'Paràmetres|Parámetros', t: 'Una variable per a tot el barri|Una variable para todo el barrio', media: { k: 'model', prog: B(BLOCKN) },
            x: "Amb <code>n</code> al principi, la base fa <code>n * 40</code> i els bucles van de 0 a <code>(n - 1)</code>: canviant un sol número, l'illa té 4, 9 o 16 edificis. Les tres parts del programa (paràmetres, mòduls i escena) es veuen d'un cop d'ull.|Con <code>n</code> al principio, la base mide <code>n * 40</code> y los bucles van de 0 a <code>(n - 1)</code>: cambiando un solo número, la manzana tiene 4, 9 o 16 edificios. Las tres partes del programa (parámetros, módulos y escena) se ven de un vistazo.",
            tip: "Per imprimir: tot sobre la base (una sola peça), res fora dels 120 × 120 mm i res que floti.|Para imprimir: todo sobre la base (una sola pieza), nada fuera de los 120 × 120 mm y nada que flote." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🗺️', title: "L'esbós de la teva illa|El boceto de tu manzana", t: 'Individualment, amb la fitxa del projecte:|Individualmente, con la ficha del proyecto:',
          steps: ["Dibuixa la vista de dalt de la teva illa al quadrat de 12 × 12 caselles (cada casella fa 10 mm): carrers, edificis, places, arbres…|Dibuja la vista de arriba de tu manzana en el cuadrado de 12 × 12 casillas (cada casilla mide 10 mm): calles, edificios, plazas, árboles…",
            "Fes la llista de mòduls: nom, paràmetres amb unitats i què fan. Almenys dos, i un amb paràmetres.|Haz la lista de módulos: nombre, parámetros con unidades y qué hacen. Al menos dos, y uno con parámetros.",
            "Marca què es repeteix al dibuix: allà hi aniran els bucles. Quina variable faria canviar tot el barri?|Marca qué se repite en el dibujo: ahí irán los bucles. ¿Qué variable haría cambiar todo el barrio?"],
          tip: "Un bon esbós estalvia moltes proves: si el dibuix quadra, el codi també quadrarà.|Un buen boceto ahorra muchas pruebas: si el dibujo cuadra, el código también cuadrará." },
        { k: 'm3spot', ph: 'investiga', q: "En aquesta illa els edificis es <b>trepitgen</b> els uns als altres. Toca la instrucció que falla.|En esta manzana los edificios se <b>pisan</b> unos a otros. Toca la instrucción que falla.", prog: B(`${BASE}\n${EDIF}\nrepeteix j de 0 a 2 {\n  repeteix i de 0 a 2 {\n    mou(10 + i * 15, 10 + j * 40, 3)! edifici(1 + i + j)\n  }\n}`), target: BLOCK,
          ex: "El pas en x és de 15 mm, però els edificis fan 20 (22 amb el terrat): es fiquen uns dins dels altres. Amb un pas de 40 queda un carrer de 18 mm entre edificis.|El paso en x es de 15 mm, pero los edificios miden 20 (22 con la azotea): se meten unos dentro de otros. Con un paso de 40 queda una calle de 18 mm entre edificios." },
        { k: 'm3spot', ph: 'investiga', q: "Ara els terrats <b>floten</b> per sobre dels edificis. On és l'error?|Ahora las azoteas <b>flotan</b> por encima de los edificios. ¿Dónde está el error?", prog: B(`// edifici(pisos): bloc amb finestres i terrat\ndefineix edifici(pisos) {\n  cub(20, 20, pisos * 10)\n  repeteix p de 0 a (pisos - 1) {\n    mou(4, -1, 3 + p * 10) color("groc") cub(12, 2, 5)\n  }\n  mou(-1, -1, pisos * 12)! color("gris") cub(22, 22, 2)\n}\nedifici(2)\nmou(30, 0, 0) edifici(3)\nmou(60, 0, 0) edifici(5)`), target: EDIF1,
          ex: "El bloc fa pisos × 10 mm d'alt, i el terrat s'hi ha de posar a sobre: a z = pisos × 10. Amb × 12 se'n separa 2 mm per pis.|El bloque mide pisos × 10 mm de alto, y la azotea tiene que ponerse encima: en z = pisos × 10. Con × 12 se separa 2 mm por piso." },
        { k: 'move', ph: 'pausa', title: 'La ciutat humana|La ciudad humana', secs: 40,
          t: "Tota la classe fa una ciutat: el professor/a diu <b>edifici(pisos)</b> i cada persona fa d'edifici: <b>edifici(1)</b> ajupit, <b>edifici(2)</b> dret, <b>edifici(3)</b> amb els braços amunt. Ara un bucle: cada fila fa <b>edifici(1 + fila)</b>!|Toda la clase hace una ciudad: el profesor/a dice <b>edificio(pisos)</b> y cada persona hace de edificio: <b>edificio(1)</b> agachado, <b>edificio(2)</b> de pie, <b>edificio(3)</b> con los brazos arriba. Ahora un bucle: ¡cada fila hace <b>edificio(1 + fila)</b>!" },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Pas 1: el mòdul.</b> Completa <code>edifici(pisos)</code>: una finestra groga de 12 × 2 × 5 mm per pis (a x = 4, y = −1, z = 3 + p × 10) i un terrat gris de 22 × 22 × 2 a (−1, −1, pisos × 10).|<b>Paso 1: el módulo.</b> Completa <code>edificio(pisos)</code>: una ventana amarilla de 12 × 2 × 5 mm por piso (en x = 4, y = −1, z = 3 + p × 10) y una azotea gris de 22 × 22 × 2 en (−1, −1, pisos × 10).", start: B(EDIF0), blocks: ['def', 'cub', 'mou', 'color', 'rep'],
          target: EDIF1, checks: [ck('match', { target: EDIF1, th: 0.9, t: GH }), ck('uses', { b: 'rep' }), ck('count', { t: 'box', min: 16, max: 16, txt: '3 blocs, 10 finestres i 3 terrats|3 bloques, 10 ventanas y 3 azoteas' })],
          hint: "Dins del mòdul: repeteix p de 0 a (pisos - 1) { mou(4, -1, 3 + p * 10) color(\"groc\") cub(12, 2, 5) } i, després, mou(-1, -1, pisos * 10) color(\"gris\") cub(22, 22, 2).|Dentro del módulo: repite p de 0 a (pisos - 1) { mueve(4, -1, 3 + p * 10) color(\"amarillo\") cubo(12, 2, 5) } y, después, mueve(-1, -1, pisos * 10) color(\"gris\") cubo(22, 22, 2).", sol: B(EDIF1) },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Pas 2: el carrer.</b> Amb un bucle, posa 4 edificis cada 30 mm, de 2, 3, 4 i 5 pisos.|<b>Paso 2: la calle.</b> Con un bucle, pon 4 edificios cada 30 mm, de 2, 3, 4 y 5 pisos.", start: B(EDIF), blocks: ['call', 'mou', 'rep'],
          target: ROWC, checks: [ck('match', { target: ROWC, th: 0.9, t: GH }), ck('uses', { b: 'rep' }), ck('uses', { b: 'call' })],
          hint: "repeteix i de 0 a 3 { mou(i * 30, 0, 0) edifici(2 + i) }|repite i de 0 a 3 { mueve(i * 30, 0, 0) edificio(2 + i) }", sol: B(ROWC) },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Pas 3: la illa sencera.</b> Sobre la base de 120 × 120 mm, posa 3 × 3 edificis cada 40 mm, començant a (10, 10, 3), amb <code>edifici(1 + i + j)</code> pisos. Ha de ser una sola peça que càpiga a la placa de la Nuvi.|<b>Paso 3: la manzana entera.</b> Sobre la base de 120 × 120 mm, pon 3 × 3 edificios cada 40 mm, empezando en (10, 10, 3), con <code>edificio(1 + i + j)</code> pisos. Tiene que ser una sola pieza que quepa en la placa de la Nuvi.", start: B(`${BASE}\n${EDIF}`), blocks: ['call', 'mou', 'rep'],
          target: BLOCK, checks: [ck('match', { target: BLOCK, th: 0.88, t: GH }), ck('uses', { b: 'rep' }), ck('one'), ck('onplate'), ck('fit', { box: [120, 120, 60] })],
          hint: "Dos bucles niats: repeteix j de 0 a 2 { repeteix i de 0 a 2 { mou(10 + i * 40, 10 + j * 40, 3) edifici(1 + i + j) } }.|Dos bucles anidados: repite j de 0 a 2 { repite i de 0 a 2 { mueve(10 + i * 40, 10 + j * 40, 3) edificio(1 + i + j) } }.", sol: B(BLOCK) },
        { k: 'm3code', ph: 'repte', text: true, q: "<b>Pas 4: un barri paramètric.</b> Afegeix una variable <code>n</code> (edificis per costat) al principi: la base ha de fer n × 40 mm i els bucles han d'anar de 0 a (n − 1). Ha de funcionar amb n = 2 i n = 4.|<b>Paso 4: un barrio paramétrico.</b> Añade una variable <code>n</code> (edificios por lado) al principio: la base tiene que medir n × 40 mm y los bucles tienen que ir de 0 a (n − 1). Tiene que funcionar con n = 2 y n = 4.", start: B(BLOCK), blocks: ['call', 'mou', 'rep', 'var', 'cub', 'color'], vars: ['n'],
          target: BLOCKN, checks: [ck('size', { ax: 'x', v: 'n * 40', t: 'La base fa n × 40 mm|La base mide n × 40 mm' }), ck('one'), ck('onplate'), ck('uses', { b: 'var' }), ck('param', { v: 'n', vals: [2, 4] })],
          hint: "Escriu n = 3 a la primera línia. Després: cub(n * 40, n * 40, 3) i els dos bucles de 0 a (n - 1), amb parèntesis.|Escribe n = 3 en la primera línea. Después: cubo(n * 40, n * 40, 3) y los dos bucles de 0 a (n - 1), con paréntesis.", sol: B(BLOCKN) },
        { k: 'm3free', ph: 'crea', text: true, q: "<b>Projecte: la teva illa de la ciutat modular.</b> Segueix el teu esbós: mòduls propis (un amb paràmetres), bucles per a tot el que es repeteix i una base de 120 × 120 mm. Organitza el programa en tres parts amb comentaris.|<b>Proyecto: tu manzana de la ciudad modular.</b> Sigue tu boceto: módulos propios (uno con parámetros), bucles para todo lo que se repite y una base de 120 × 120 mm. Organiza el programa en tres partes con comentarios.",
          name: 'La meva illa|Mi manzana', start: B(`${BASE}\n${EDIF}`), blocks: ['cub', 'cil', 'esf', 'con', 'pir', 'tub', 'mou', 'gira', 'escala', 'color', 'rep', 'resta', 'uneix', 'def', 'call', 'var', 'rem'],
          crit: ["Almenys dos mòduls teus, i un amb paràmetres|Al menos dos módulos tuyos, y uno con parámetros", "Fa servir bucles per a tot el que es repeteix|Usa bucles para todo lo que se repite", "Cap dins de 120 × 120 mm, és una sola peça i toca la placa|Cabe dentro de 120 × 120 mm, es una sola pieza y toca la placa", "El programa té les tres parts (paràmetres, mòduls, escena) i comentaris|El programa tiene las tres partes (parámetros, módulos, escena) y comentarios"],
          checks: [ck('uses', { b: 'def' }), ck('uses', { b: 'call' }), ck('uses', { b: 'rep' }), ck('fit', { box: [120, 120, 120] }), ck('one'), ck('onplate')], sol: B(CITYFREE) },
        { k: 'story', ph: 'crea', who: 'bit', scene: 'estudi', title: "L'exposició|La exposición",
          t: "Quina illa més ben pensada! Descarrega l'<b>STL</b> per a la Nuvi i el <b>.scad</b> des de «Projectes». Quan totes les illes de l'estudi estiguin impreses, les posarem juntes i el barri del futur estarà llest per a l'exposició. Prepara't per explicar-la: quins mòduls has fet i quina variable canvia tot el barri.|¡Qué manzana tan bien pensada! Descarga el <b>STL</b> para la Nuvi y el <b>.scad</b> desde «Proyectos». Cuando todas las manzanas del estudio estén impresas, las pondremos juntas y el barrio del futuro estará listo para la exposición. Prepárate para explicarla: qué módulos has hecho y qué variable cambia todo el barrio." },
        { k: 'quiz', ph: 'tanca', q: "En un projecte gran, què és millor fer primer?|En un proyecto grande, ¿qué es mejor hacer primero?", opts: ["Un esbós i la llista de mòduls amb els seus paràmetres|Un boceto y la lista de módulos con sus parámetros", "Escriure tot el programa de cop i provar-lo al final|Escribir todo el programa de golpe y probarlo al final", "Triar els colors|Elegir los colores"], a: 0 },
        { k: 'quiz', ph: 'tanca', q: "Amb <code>n = 4</code> a la illa paramètrica, quants edificis hi ha?|Con <code>n = 4</code> en la manzana paramétrica, ¿cuántos edificios hay?", opts: ['16|16', '8|8', '4|4'], a: 0, ex: 'Dos bucles de 0 a 3: 4 × 4 = 16.|Dos bucles de 0 a 3: 4 × 4 = 16.' },
        { k: 'feel', ph: 'tanca' }
      ] }
  ] };
})();
