/* Tech 3D · Nivell 1 · unitat 1 «L'espai 3D» (m1-1 … m1-4)
   Contingut propi de Numi (unitat de mostra del motor: scripts/TECH-3D.md). Fil narratiu: el Taller de Bit, amb la Nuvi,
   la impressora 3D. Hi ha passos a m1-1 (mirar i girar la vista: m3look, primera peça amb m3free) i a m1-3 (coordenades:
   m3look, m3build amb fantasma, m3fix i m3free amb comprovacions). m1-2 i m1-4 són per als agents de contingut.
   Models: peces { id, t, s: [x, y, z] (mm), p: centre, r: graus, c: color, hole }, placa de 200 × 200 mm centrada a l'origen. */
COURSE_UNITS[1] = (() => {
  const P = (id, t, s, p, c, o = {}) => ({ id, t, s, p, r: o.r || [0, 0, 0], c, ...o });
  // la casa de la Nuvi (amb una estrella amagada al darrere)
  const CASA = [P('base', 'box', [40, 30, 24], [0, 0, 12], '#F5893A'), P('teulada', 'pyr', [46, 36, 18], [0, 0, 33], '#E8453C'), P('porta', 'box', [10, 2, 14], [0, -15.5, 7], '#A0683A'), P('xemeneia', 'cyl', [7, 7, 14], [12, 6, 38], '#9AA3B5')];
  const AMAGADA = [...CASA, P('estrella', 'star', [16, 16, 4], [0, 28, 9], '#F7C531', { r: [90, 0, 0] })];
  const TORRE = [P('t1', 'box', [30, 30, 10], [0, 0, 5], '#3D7BF4'), P('t2', 'cyl', [20, 20, 16], [0, 0, 18], '#2FB36D'), P('t3', 'box', [16, 16, 10], [0, 0, 31], '#F7C531'), P('t4', 'cone', [18, 18, 14], [0, 0, 43], '#E8453C')];
  const TRES = [P('caixa', 'box', [24, 24, 14], [-30, 10, 7], '#3D7BF4'), P('cilindre', 'cyl', [16, 16, 36], [0, -10, 18], '#2FB36D'), P('con', 'cone', [20, 20, 24], [30, 10, 12], '#EC5FA8')];
  const ROBOT = [P('cos', 'box', [26, 16, 26], [0, 0, 21], '#7C5CFF'), P('cap', 'box', [18, 14, 14], [0, 0, 41], '#5BC0EB'), P('ull1', 'sph', [5, 5, 5], [-4, -7, 43], '#2A2F3A'), P('ull2', 'sph', [5, 5, 5], [4, -7, 43], '#2A2F3A'),
    P('roda1', 'cyl', [12, 12, 6], [-16, 0, 6], '#2A2F3A', { r: [0, 90, 0] }), P('roda2', 'cyl', [12, 12, 6], [16, 0, 6], '#2A2F3A', { r: [0, 90, 0] }), P('antena', 'cyl', [2, 2, 8], [0, 0, 52], '#9AA3B5'), P('bola', 'sph', [5, 5, 5], [0, 0, 57], '#E8453C')];
  const EIXOS = [P('c0', 'box', [10, 10, 10], [0, 0, 5], '#9AA3B5'), P('cx', 'box', [10, 10, 10], [40, 0, 5], '#E5484D'), P('cy', 'box', [10, 10, 10], [0, 40, 5], '#22A06B'), P('cz', 'box', [10, 10, 10], [0, 0, 45], '#2F5BEA')];
  const PUNTS = [P('p1', 'cyl', [14, 14, 14], [-20, 20, 7], '#E8453C'), P('p2', 'cyl', [14, 14, 14], [20, 20, 7], '#3D7BF4'), P('p3', 'cyl', [14, 14, 14], [-20, -20, 7], '#2FB36D'), P('p4', 'cyl', [14, 14, 14], [20, -20, 7], '#F7C531')];
  const cub = (x, y, z = 0, id = 'a1', c = '#7C5CFF') => P(id, 'box', [20, 20, 20], [x, y, z + 10], c);
  return {
  t: "L'espai 3D|El espacio 3D", d: 'Mirar en tres dimensions|Mirar en tres dimensiones', color: '#7C5CFF',
  s: [
    { id: 'm1-1', t: 'Benvinguts al taller 3D|Bienvenidos al taller 3D', min: 40,
      learn: ["Un objecte 3D té tres mides: amplada, fondària i alçada.|Un objeto 3D tiene tres medidas: anchura, fondo y altura.",
        "Al taller, les peces es posen sobre la placa d'impressió, que té una quadrícula de quadrets de 10 mm.|En el taller, las piezas se ponen sobre la placa de impresión, que tiene una cuadrícula de cuadritos de 10 mm.",
        "Per veure un model per tots els costats, gires la vista: un dit gira, dos dits apropen o allunyen.|Para ver un modelo por todos los lados, giras la vista: un dedo gira, dos dedos acercan o alejan."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "Quina d'aquestes coses té <b>amplada, fondària i alçada</b> (la pots agafar i girar)?|¿Cuál de estas cosas tiene <b>anchura, fondo y altura</b> (la puedes coger y girar)?",
          opts: ['Una capsa de sabates|Una caja de zapatos', 'Una ratlla dibuixada en un paper|Una raya dibujada en un papel', "L'ombra d'un arbre a terra|La sombra de un árbol en el suelo"], a: 0,
          ex: "La capsa ocupa espai en tres direccions: de costat a costat, de davant a darrere i de baix a dalt. Una ratlla o una ombra són planes.|La caja ocupa espacio en tres direcciones: de lado a lado, de delante a detrás y de abajo arriba. Una raya o una sombra son planas." },
        { k: 'quiz', ph: 'recorda', q: "Vols veure el <b>darrere</b> d'una joguina que és a la taula. Què fas?|Quieres ver la <b>parte de atrás</b> de un juguete que está en la mesa. ¿Qué haces?",
          opts: ['La giro o camino al seu voltant|Lo giro o camino a su alrededor', 'Tanco un ull|Cierro un ojo', "M'hi apropo sense moure'm del lloc|Me acerco sin moverme del sitio"], a: 0,
          ex: 'Per veure una cosa per tots els costats l\'has de girar o canviar de lloc. Al taller 3D farem el mateix amb la càmera.|Para ver una cosa por todos los lados tienes que girarla o cambiar de sitio. En el taller 3D haremos lo mismo con la cámara.' },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'taller', title: 'El Taller de Bit|El Taller de Bit',
          t: "Benvinguts al meu <b>taller de fabricació digital</b>! Aquesta és la <b>Nuvi</b>, la nostra impressora 3D: construeix objectes de veritat capa a capa. Però abans d'imprimir res, hem d'aprendre a <b>mirar en 3D</b>: com és un objecte per davant, per darrere i per dalt. Som-hi!|¡Bienvenidos a mi <b>taller de fabricación digital</b>! Esta es <b>Nuvi</b>, nuestra impresora 3D: construye objetos de verdad capa a capa. Pero antes de imprimir nada, tenemos que aprender a <b>mirar en 3D</b>: cómo es un objeto por delante, por detrás y por arriba. ¡Vamos!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Un objecte 3D|Un objeto 3D', t: 'Tres mides: amplada, fondària i alçada|Tres medidas: anchura, fondo y altura', media: { k: 'model', model: { parts: [P('m', 'box', [40, 30, 20], [0, 0, 10], '#7C5CFF')] } },
            x: "Tot el que pots agafar té <b>tres mides</b>: l'<b>amplada</b> (d'esquerra a dreta), la <b>fondària</b> (de davant a darrere) i l'<b>alçada</b> (de baix a dalt). Al taller les mesurem en <b>mil·límetres</b> (mm): 10 mm és 1 cm.|Todo lo que puedes coger tiene <b>tres medidas</b>: la <b>anchura</b> (de izquierda a derecha), el <b>fondo</b> (de delante a detrás) y la <b>altura</b> (de abajo arriba). En el taller las medimos en <b>milímetros</b> (mm): 10 mm es 1 cm.",
            tip: 'Aquesta caixa fa 40 mm d\'amplada, 30 mm de fondària i 20 mm d\'alçada.|Esta caja mide 40 mm de anchura, 30 mm de fondo y 20 mm de altura.' },
          { k: 'La placa|La placa', t: "La placa d'impressió|La placa de impresión", media: { k: 'model', model: { parts: [P('a', 'box', [10, 10, 10], [0, 0, 5], '#2FB36D'), P('b', 'box', [20, 10, 10], [30, 20, 5], '#3D7BF4')] }, view: 'top' },
            x: "Les peces es posen sobre la <b>placa</b>, com a la impressora. La placa té una <b>quadrícula</b>: cada quadret fa <b>10 mm</b> de costat. Així pots comptar quadrets per saber quant mesura una peça.|Las piezas se ponen sobre la <b>placa</b>, como en la impresora. La placa tiene una <b>cuadrícula</b>: cada cuadrito mide <b>10 mm</b> de lado. Así puedes contar cuadritos para saber cuánto mide una pieza.",
            tip: 'El cub verd ocupa 1 quadret; la peça blava, 2 quadrets de llarg.|El cubo verde ocupa 1 cuadrito; la pieza azul, 2 cuadritos de largo.' },
          { k: 'Girar la vista|Girar la vista', t: 'Mira el model per tots els costats|Mira el modelo por todos los lados', media: { k: 'model', model: { parts: CASA } },
            x: "Arrossega amb <b>un dit</b> (o amb el ratolí) per <b>girar la càmera</b> al voltant del model. Amb <b>dos dits</b> (o la roda del ratolí) t'hi apropes o t'allunyes. El model no es mou: ets tu qui hi camina al voltant.|Arrastra con <b>un dedo</b> (o con el ratón) para <b>girar la cámara</b> alrededor del modelo. Con <b>dos dedos</b> (o la rueda del ratón) te acercas o te alejas. El modelo no se mueve: eres tú quien camina a su alrededor.",
            tip: 'Prova-ho ara: gira la casa i busca la porta.|Pruébalo ahora: gira la casa y busca la puerta.' },
          { k: 'Les vistes|Las vistas', t: 'Perspectiva, davant, dalt i costat|Perspectiva, delante, arriba y lado', anim: 'm3views',
            x: "Els botons de dalt de la vista et porten de cop a una <b>vista</b>: la <b>perspectiva</b> (es veuen tres cares), <b>davant</b>, <b>dalt</b> i <b>costat</b>. Si et perds, el botó de centrar et torna a portar al model.|Los botones de arriba de la vista te llevan de golpe a una <b>vista</b>: la <b>perspectiva</b> (se ven tres caras), <b>delante</b>, <b>arriba</b> y <b>lado</b>. Si te pierdes, el botón de centrar te vuelve a llevar al modelo." }
        ] },
        { k: 'unplug', ph: 'mans', ico: '📏', title: 'Mesura una capsa|Mide una caja', t: 'Amb un regle i una capsa (de sabates, de llapis o de cereals):|Con una regla y una caja (de zapatos, de lápices o de cereales):',
          steps: ["Posa la capsa a la taula i digues quina és l'amplada, la fondària i l'alçada.|Pon la caja en la mesa y di cuál es la anchura, el fondo y la altura.", 'Mesura cada mida amb el regle i apunta-la en mil·límetres (1 cm = 10 mm).|Mide cada medida con la regla y apúntala en milímetros (1 cm = 10 mm).', 'Gira la capsa i torna a mesurar: les mides canvien de nom però no de valor?|Gira la caja y vuelve a medir: ¿las medidas cambian de nombre pero no de valor?'],
          tip: "Si gires la capsa, el que abans era l'alçada pot passar a ser l'amplada.|Si giras la caja, lo que antes era la altura puede pasar a ser la anchura." },
        { k: 'm3look', ph: 'prova', q: "A la casa de la Nuvi hi ha una <b>estrella amagada</b>. <b>Gira la vista</b> per trobar-la i toca-la.|En la casa de Nuvi hay una <b>estrella escondida</b>. <b>Gira la vista</b> para encontrarla y tócala.",
          model: { parts: AMAGADA }, pick: 'estrella', yes: "L'has trobada! Era al darrere de la casa.|¡La has encontrado! Estaba detrás de la casa.", ex: 'Des de davant la tapava la casa: per això cal girar la vista.|Desde delante la tapaba la casa: por eso hay que girar la vista.' },
        { k: 'm3look', ph: 'prova', q: "Quantes <b>peces</b> té aquesta torre? Gira-la si cal.|¿Cuántas <b>piezas</b> tiene esta torre? Gírala si hace falta.", model: { parts: TORRE },
          opts: ['3|3', '4|4', '5|5'], a: 1, ex: 'Té 4 peces: una caixa a baix, un cilindre, una caixa petita i un con a dalt de tot.|Tiene 4 piezas: una caja abajo, un cilindro, una caja pequeña y un cono arriba del todo.' },
        { k: 'm3look', ph: 'investiga', q: 'Toca la peça <b>més alta</b> (la que arriba més amunt).|Toca la pieza <b>más alta</b> (la que llega más arriba).', model: { parts: TRES }, pick: 'cilindre', no: "Aquesta no arriba tan amunt. Mira'ls des del costat per comparar-les.|Esta no llega tan arriba. Míralas desde el lado para compararlas.",
          ex: 'El cilindre fa 36 mm d\'alçada; el con, 24 mm, i la caixa, 14 mm. Des del costat es veu molt bé.|El cilindro mide 36 mm de altura; el cono, 24 mm, y la caja, 14 mm. Desde el lado se ve muy bien.' },
        { k: 'move', ph: 'pausa', title: 'Fes-te 3D!|¡Hazte 3D!', secs: 30, t: "Estira't ben amunt (<b>alçada</b>), obre els braços (<b>amplada</b>) i fes un pas endavant i un enrere (<b>fondària</b>). Ara gira sobre tu mateix com la càmera del taller!|Estírate bien arriba (<b>altura</b>), abre los brazos (<b>anchura</b>) y da un paso adelante y uno atrás (<b>fondo</b>). ¡Ahora gira sobre ti mismo como la cámara del taller!" },
        { k: 'm3look', ph: 'repte', q: "Aquest robot té un <b>botó vermell</b> amagat. Gira la vista i troba'l.|Este robot tiene un <b>botón rojo</b> escondido. Gira la vista y encuéntralo.", model: { parts: ROBOT }, pick: 'bola', view: 'front', yes: 'Molt bé! És la bola de dalt de l\'antena.|¡Muy bien! Es la bola de arriba de la antena.', ex: 'Des de davant quedava tapada pel cap. Des de dalt o des del costat ja es veu.|Desde delante quedaba tapada por la cabeza. Desde arriba o desde el lado ya se ve.' },
        { k: 'm3look', ph: 'repte', q: 'Des d\'on mirem aquest model?|¿Desde dónde miramos este modelo?', model: { parts: TORRE }, view: 'top', lock: true,
          opts: ['Des de dalt|Desde arriba', 'Des de davant|Desde delante', 'Des del costat|Desde el lado'], a: 0, ex: 'Des de dalt, totes les peces semblen planes: veiem la caixa quadrada, el cercle del cilindre i la punta del con al mig.|Desde arriba, todas las piezas parecen planas: vemos la caja cuadrada, el círculo del cilindro y la punta del cono en el medio.' },
        { k: 'm3look', ph: 'repte', extra: true, q: 'Quantes peces té el robot? Gira\'l per comptar les que no es veuen.|¿Cuántas piezas tiene el robot? Gíralo para contar las que no se ven.', model: { parts: ROBOT },
          opts: ['6|6', '7|7', '8|8'], a: 2, ex: 'Té 8 peces: cos, cap, dos ulls, dues rodes, antena i bola.|Tiene 8 piezas: cuerpo, cabeza, dos ojos, dos ruedas, antena y bola.' },
        { k: 'm3free', ph: 'crea', q: "<b>La teva primera peça.</b> Toca formes de la paleta per posar-les a la placa i mira-les de tots els costats. Quan t'agradi, desa-ho.|<b>Tu primera pieza.</b> Toca formas de la paleta para ponerlas en la placa y míralas desde todos los lados. Cuando te guste, guárdalo.",
          name: 'La meva primera peça|Mi primera pieza', palette: ['box', 'cyl', 'sph', 'cone', 'pyr', 'star', 'heart'],
          crit: ['Hi ha almenys 2 formes a la placa|Hay al menos 2 formas en la placa', "L'has mirat des de davant, de dalt i del costat|Lo has mirado desde delante, desde arriba y desde el lado"],
          checks: [{ k: 'count', min: 2 }, { k: 'onplate' }], sol: { parts: [P('a1', 'box', [20, 20, 20], [0, 0, 10], '#7C5CFF'), P('a2', 'sph', [20, 20, 20], [30, 0, 10], '#FF8A3D')] } },
        { k: 'quiz', ph: 'tanca', q: 'Quines són les tres mides d\'un objecte 3D?|¿Cuáles son las tres medidas de un objeto 3D?', opts: ['Amplada, fondària i alçada|Anchura, fondo y altura', 'Color, forma i pes|Color, forma y peso', 'Davant, darrere i dalt|Delante, detrás y arriba'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Al taller, com veus el darrere d\'un model?|En el taller, ¿cómo ves la parte de atrás de un modelo?', opts: ['Arrossego amb el dit per girar la vista|Arrastro con el dedo para girar la vista', 'Esborro el model i el torno a fer|Borro el modelo y lo vuelvo a hacer', 'No es pot veure|No se puede ver'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    { id: 'm1-2', t: 'Davant, dalt i costat|Delante, arriba y lado' },
    { id: 'm1-3', t: 'Els eixos x, y, z|Los ejes x, y, z', min: 40,
      learn: ["Les coordenades x, y, z diuen on és una peça: x d'esquerra a dreta, y de davant a darrere i z cap amunt.|Las coordenadas x, y, z dicen dónde está una pieza: x de izquierda a derecha, y de delante a detrás y z hacia arriba.",
        "L'origen (0, 0, 0) és el centre de la placa; els números negatius van a l'altre costat.|El origen (0, 0, 0) es el centro de la placa; los números negativos van al otro lado.",
        "Una peça amb z = 0 toca la placa; si no, flota i la impressora no la podria fer.|Una pieza con z = 0 toca la placa; si no, flota y la impresora no podría hacerla."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Amb quina vista veus un model <b>des de dalt</b>, com si fossis un ocell?|¿Con qué vista ves un modelo <b>desde arriba</b>, como si fueras un pájaro?', opts: ['La vista de dalt (planta)|La vista de arriba (planta)', 'La vista de davant (alçat)|La vista de delante (alzado)', 'La vista del costat (perfil)|La vista del lado (perfil)'], a: 0 },
        { k: 'm3look', ph: 'recorda', q: 'Quina vista és aquesta?|¿Qué vista es esta?', model: { parts: CASA }, view: 'front', lock: true, opts: ['Davant (alçat)|Delante (alzado)', 'Dalt (planta)|Arriba (planta)', 'Perspectiva|Perspectiva'], a: 0,
          ex: 'Veiem la porta de cara i la teulada com un triangle: és la vista de davant.|Vemos la puerta de cara y el tejado como un triángulo: es la vista de delante.' },
        { k: 'story', ph: 'missio', who: 'bit', scene: 'taller', title: 'Números per a la Nuvi|Números para Nuvi',
          t: "Tenim un encàrrec de la biblioteca: una figura amb peces col·locades <b>exactament</b> al seu lloc. Però a la Nuvi no li podem dir «una mica més a la dreta»: només entén <b>números</b>. Avui aprendrem les <b>coordenades x, y, z</b>!|Tenemos un encargo de la biblioteca: una figura con piezas colocadas <b>exactamente</b> en su sitio. Pero a Nuvi no le podemos decir «un poco más a la derecha»: solo entiende <b>números</b>. ¡Hoy aprenderemos las <b>coordenadas x, y, z</b>!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Els eixos|Los ejes', t: 'Tres direccions amb nom: x, y, z|Tres direcciones con nombre: x, y, z', anim: 'm3axes',
            x: "L'eix <b style=\"color:#E5484D\">x</b> (vermell) va d'esquerra a dreta, l'eix <b style=\"color:#22A06B\">y</b> (verd) va de davant cap a darrere i l'eix <b style=\"color:#2F5BEA\">z</b> (blau) va cap amunt. Les línies de colors de la placa són els eixos x i y.|El eje <b style=\"color:#E5484D\">x</b> (rojo) va de izquierda a derecha, el eje <b style=\"color:#22A06B\">y</b> (verde) va de delante hacia detrás y el eje <b style=\"color:#2F5BEA\">z</b> (azul) va hacia arriba. Las líneas de colores de la placa son los ejes x e y." },
          { k: "L'origen|El origen", t: 'El punt (0, 0, 0)|El punto (0, 0, 0)', media: { k: 'model', model: { parts: EIXOS } },
            x: "On es creuen les línies de la placa hi ha l'<b>origen</b>: x = 0, y = 0, z = 0. El cub gris hi és a sobre. El vermell és a <b>x = 40</b>, el verd a <b>y = 40</b> i el blau és 40 mm <b>amunt</b> (z = 40).|Donde se cruzan las líneas de la placa está el <b>origen</b>: x = 0, y = 0, z = 0. El cubo gris está encima. El rojo está en <b>x = 40</b>, el verde en <b>y = 40</b> y el azul está 40 mm <b>arriba</b> (z = 40).",
            tip: 'Gira la vista per veure que el blau no toca la placa.|Gira la vista para ver que el azul no toca la placa.' },
          { k: 'Números negatius|Números negativos', t: "A l'altre costat de l'origen|Al otro lado del origen", media: { k: 'model', model: { parts: PUNTS }, view: 'top' },
            x: "Si una peça és a l'<b>esquerra</b> de l'origen, la seva x és <b>negativa</b> (x = −20). Si és <b>davant</b>, la y és negativa. El cilindre verd és a x = −20, y = −20; el groc, a x = 20, y = −20.|Si una pieza está a la <b>izquierda</b> del origen, su x es <b>negativa</b> (x = −20). Si está <b>delante</b>, la y es negativa. El cilindro verde está en x = −20, y = −20; el amarillo, en x = 20, y = −20." },
          { k: 'La posició|La posición', t: 'On és una peça: x, y del centre i z de la base|Dónde está una pieza: x, y del centro y z de la base', media: { k: 'model', model: { parts: [cub(30, 10, 0, 'q', '#7C5CFF')] } },
            x: "A la pestanya <b>Posició</b> hi ha tres números: <b>x</b> i <b>y</b> són on és el <b>centre</b> de la peça a la placa, i <b>z</b> és a quina alçada queda la seva <b>base</b>. Amb z = 0, la peça toca la placa.|En la pestaña <b>Posición</b> hay tres números: <b>x</b> e <b>y</b> son dónde está el <b>centro</b> de la pieza en la placa, y <b>z</b> es a qué altura queda su <b>base</b>. Con z = 0, la pieza toca la placa.",
            tip: 'Aquest cub és a x = 30, y = 10, z = 0.|Este cubo está en x = 30, y = 10, z = 0.' }
        ] },
        { k: 'unplug', ph: 'mans', ico: '🧭', title: 'La placa humana|La placa humana', t: "A terra de l'aula, amb cinta adhesiva, hi ha dues línies que es creuen (x i y). Per parelles:|En el suelo del aula, con cinta adhesiva, hay dos líneas que se cruzan (x e y). Por parejas:",
          steps: ["Una persona diu unes coordenades (per exemple, x = 2 passes, y = −1 passa).|Una persona dice unas coordenadas (por ejemplo, x = 2 pasos, y = −1 paso).", "L'altra surt de l'origen i hi va, primer en x i després en y.|La otra sale del origen y va hasta allí, primero en x y después en y.", "Per a la z, aixeca els braços: z = 0 a terra, z = 1 a la cintura, z = 2 al cap!|Para la z, levanta los brazos: z = 0 en el suelo, z = 1 en la cintura, ¡z = 2 en la cabeza!"],
          tip: "Si us poseu tots mirant cap al mateix costat, «endavant» és la y positiva per a tothom.|Si os ponéis todos mirando hacia el mismo lado, «adelante» es la y positiva para todos." },
        { k: 'm3look', ph: 'prova', q: 'El cub és a sobre de la línia vermella (y = 0). Quina és la seva <b>x</b>?|El cubo está encima de la línea roja (y = 0). ¿Cuál es su <b>x</b>?', model: { parts: [cub(30, 0, 0, 'q', '#7C5CFF')] }, view: 'top',
          opts: ['x = 30|x = 30', 'x = −30|x = −30', 'x = 0|x = 0'], a: 0, ex: "És a la dreta de l'origen, a 3 quadrets: x = 30 mm.|Está a la derecha del origen, a 3 cuadritos: x = 30 mm." },
        { k: 'm3look', ph: 'investiga', q: 'Toca el cilindre que és a <b>x = −20, y = 20</b>.|Toca el cilindro que está en <b>x = −20, y = 20</b>.', model: { parts: PUNTS }, view: 'top', pick: 'p1',
          no: 'Aquest no. Recorda: x negativa és a l\'esquerra i y positiva és cap al fons.|Este no. Recuerda: x negativa es a la izquierda e y positiva es hacia el fondo.', ex: "x = −20 és a l'esquerra de l'origen i y = 20 és cap al fons.|x = −20 es a la izquierda del origen e y = 20 es hacia el fondo." },
        { k: 'move', ph: 'pausa', title: 'Eixos amb el cos|Ejes con el cuerpo', secs: 30, t: 'Braç dret a la dreta: <b>x positiva</b>! Braç esquerre: <b>x negativa</b>! Un pas endavant: <b>y</b>! Salta: <b>z</b>! Ara al revés, cada cop més de pressa.|Brazo derecho a la derecha: ¡<b>x positiva</b>! Brazo izquierdo: ¡<b>x negativa</b>! Un paso adelante: ¡<b>y</b>! Salta: ¡<b>z</b>! Ahora al revés, cada vez más rápido.' },
        { k: 'm3build', ph: 'repte', q: "Mou el cub fins al <b>fantasma</b>: a <b>x = 30</b>, y = 0. Pots arrossegar-lo o escriure els números a <b>Posició</b>.|Mueve el cubo hasta el <b>fantasma</b>: a <b>x = 30</b>, y = 0. Puedes arrastrarlo o escribir los números en <b>Posición</b>.",
          start: { parts: [cub(0, 0)] }, palette: ['box'], target: { parts: [cub(30, 0)] }, checks: [{ k: 'match', target: { parts: [cub(30, 0)] }, th: 0.92, t: 'El cub és dins del fantasma|El cubo está dentro del fantasma' }, { k: 'onplate' }],
          hint: 'Toca el cub, obre la pestanya Posició i posa 30 a la x.|Toca el cubo, abre la pestaña Posición y pon 30 en la x.', sol: { parts: [cub(30, 0)] } },
        { k: 'm3build', ph: 'repte', q: 'Ara al fantasma de <b>x = −20, y = 30</b>. Compte amb el signe menys!|Ahora al fantasma de <b>x = −20, y = 30</b>. ¡Cuidado con el signo menos!',
          start: { parts: [cub(0, 0)] }, palette: ['box'], target: { parts: [cub(-20, 30)] }, checks: [{ k: 'match', target: { parts: [cub(-20, 30)] }, th: 0.92, t: 'El cub és dins del fantasma|El cubo está dentro del fantasma' }, { k: 'onplate' }],
          hint: "x = −20 és a l'esquerra i y = 30 és cap al fons. Pots escriure −20 al camp de la x.|x = −20 es a la izquierda e y = 30 es hacia el fondo. Puedes escribir −20 en el campo de la x.", sol: { parts: [cub(-20, 30)] } },
        { k: 'm3build', ph: 'repte', q: "Fes una torre: posa el cub lila <b>a sobre</b> del blau. Quina ha de ser la seva <b>z</b>?|Haz una torre: pon el cubo lila <b>encima</b> del azul. ¿Cuál tiene que ser su <b>z</b>?",
          start: { parts: [cub(0, 0, 0, 'base', '#3D7BF4'), cub(40, 0, 0, 'a1')] }, palette: ['box'], target: { parts: [cub(0, 0, 0, 'g1'), cub(0, 0, 20, 'g2')] },
          checks: [{ k: 'match', target: { parts: [cub(0, 0, 0, 'g1'), cub(0, 0, 20, 'g2')] }, th: 0.92, t: 'La torre és com el fantasma|La torre es como el fantasma' }, { k: 'one' }, { k: 'onplate' }],
          hint: 'El cub blau fa 20 mm d\'alt: el lila ha de començar a z = 20 i estar a x = 0.|El cubo azul mide 20 mm de alto: el lila tiene que empezar en z = 20 y estar en x = 0.', sol: { parts: [cub(0, 0, 0, 'base', '#3D7BF4'), cub(0, 0, 20, 'a1')] } },
        { k: 'm3fix', ph: 'repte', q: "Ui! Aquest pont <b>flota</b> i la Nuvi no el podria imprimir. <b>Arregla'l</b> perquè toqui la placa.|¡Uy! Este puente <b>flota</b> y Nuvi no podría imprimirlo. <b>Arréglalo</b> para que toque la placa.",
          start: { parts: [P('a1', 'box', [60, 20, 10], [0, 0, 20], '#2FB36D')] }, fix: ['a1'], palette: ['box'], checks: [{ k: 'onplate' }, { k: 'part', t: 'box', s: [60, 20, 10], txt: 'El pont fa 60 × 20 × 10 mm|El puente mide 60 × 20 × 10 mm' }],
          hint: 'A la pestanya Posició, posa la z a 0.|En la pestaña Posición, pon la z en 0.', sol: { parts: [P('a1', 'box', [60, 20, 10], [0, 0, 5], '#2FB36D')] } },
        { k: 'm3fix', ph: 'repte', extra: true, q: "Ara una peça s'ha <b>enfonsat</b> a la placa (la seva z és negativa). Arregla la torre perquè cada peça estigui a sobre de l'altra.|Ahora una pieza se ha <b>hundido</b> en la placa (su z es negativa). Arregla la torre para que cada pieza esté encima de la otra.",
          start: { parts: [P('b1', 'cyl', [30, 30, 10], [0, 0, -2], '#3D7BF4'), P('b2', 'cyl', [20, 20, 10], [0, 0, 13], '#F7C531')] }, fix: ['b1'], palette: ['cyl'],
          checks: [{ k: 'onplate' }, { k: 'one' }, { k: 'size', ax: 'z', v: 20 }], hint: 'Primer posa la base a z = 0. Després posa el cilindre groc a z = 10, just a sobre.|Primero pon la base en z = 0. Después pon el cilindro amarillo en z = 10, justo encima.',
          sol: { parts: [P('b1', 'cyl', [30, 30, 10], [0, 0, 5], '#3D7BF4'), P('b2', 'cyl', [20, 20, 10], [0, 0, 15], '#F7C531')] } },
        { k: 'm3free', ph: 'crea', q: "<b>L'encàrrec de la biblioteca.</b> Fes una figura amb una peça a <b>x = −30</b>, una a <b>x = 30</b> i una al mig, <b>més alta</b> que les altres. Tria les formes i els colors que vulguis.|<b>El encargo de la biblioteca.</b> Haz una figura con una pieza en <b>x = −30</b>, una en <b>x = 30</b> y una en el medio, <b>más alta</b> que las otras. Elige las formas y los colores que quieras.",
          name: 'La figura de la biblioteca|La figura de la biblioteca', crit: ['Una peça a x = −30 i una a x = 30|Una pieza en x = −30 y una en x = 30', 'Una peça al mig més alta|Una pieza en el medio más alta', 'Totes toquen la placa|Todas tocan la placa'],
          checks: [{ k: 'part', at: [-30, null, null], tol: 1.5, t: 'Hi ha una peça a x = −30|Hay una pieza en x = −30' }, { k: 'part', at: [30, null, null], tol: 1.5, t: 'Hi ha una peça a x = 30|Hay una pieza en x = 30' }, { k: 'count', min: 3 }, { k: 'onplate' }],
          sol: { parts: [P('a1', 'cyl', [16, 16, 20], [-30, 0, 10], '#3D7BF4'), P('a2', 'cone', [20, 20, 40], [0, 0, 20], '#EC5FA8'), P('a3', 'cyl', [16, 16, 20], [30, 0, 10], '#3D7BF4')] } },
        { k: 'quiz', ph: 'tanca', q: 'Quin eix va <b>cap amunt</b>?|¿Qué eje va <b>hacia arriba</b>?', opts: ["L'eix z|El eje z", "L'eix x|El eje x", "L'eix y|El eje y"], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Una peça a <b>x = 0, y = 0</b> és…|Una pieza en <b>x = 0, y = 0</b> está…', opts: ['Al centre de la placa|En el centro de la placa', "A la cantonada de l'esquerra|En la esquina de la izquierda", 'Fora de la placa|Fuera de la placa'], a: 0 },
        { k: 'feel', ph: 'tanca' }
      ] },
    { id: 'm1-4', t: 'Projecte: la meva primera escultura|Proyecto: mi primera escultura', proj: true }
  ] };
})();
