/* Tech Creadors · unitat 8 «L'estudi de videojocs» (g8-1 … g8-4) · projecte final del curs
   L'alumnat treballa com un estudi: document de disseny (g8-1, pas «review»: protagonista, premi, enemic i fons) i versió 1,
   construcció per peces i nivells (g8-2), proves amb dades i ajust de la dificultat (g8-3) i publicació amb títol,
   instruccions i crèdits (g8-4). Les sessions continuen sempre des de l'última versió desada al portafoli. Els personatges
   tenen sempre els mateixos ids (heroi, premi, enemic): així les solucions de prova funcionen amb qualsevol tria. */
Object.assign(TBADGE, {
  g_u8idea: { id: 'g_u8idea', ico: '💡', n: 'Dissenyador/a de videojocs|Diseñador/a de videojuegos', d: "Has escrit el document de disseny del teu videojoc i n'has fet la versió 1.|Has escrito el documento de diseño de tu videojuego y has hecho la versión 1." },
  g_u8build: { id: 'g_u8build', ico: '🛠️', n: 'Constructor/a de videojocs|Constructor/a de videojuegos', d: 'Has construït el teu videojoc peça a peça.|Has construido tu videojuego pieza a pieza.' },
  g_u8prova: { id: 'g_u8prova', ico: '🤝', n: 'Provador/a amb dades|Probador/a con datos', d: "Has fet partides de prova, n'has apuntat les dades i has ajudat a ajustar la dificultat.|Has hecho partidas de prueba, has apuntado los datos y has ayudado a ajustar la dificultad." },
  g_u8grad: { id: 'g_u8grad', ico: '🎓', n: 'Creador/a de videojocs|Creador/a de videojuegos', d: 'Has acabat Tech Creadors i has publicat el teu videojoc.|Has terminado Tech Creadores y has publicado tu videojuego.' }
});
COURSE_UNITS[8] = (() => {
  /* ---------- El videojoc de l'alumne/a ---------- */
  const HER = [['numi', 'lr'], ['gat', 'lr'], ['nau', 'none'], ['peix', 'lr'], ['drac', 'lr'], ['ocell', 'lr'], ['gos', 'lr'], ['guineu', 'lr']];
  const PRE = ['moneda', 'estrella', 'poma', 'cor', 'regal', 'platan', 'diamant', 'maduixa'];
  const ENE = [['meteorit', 'all'], ['cranc', 'lr'], ['medusa', 'none'], ['roca', 'none'], ['pilota', 'all'], ['cocodril', 'lr'], ['foc', 'none'], ['llamp', 'none']];
  const FONS = ['espai', 'aquari', 'bosc', 'ciutat', 'platja', 'parc', 'nit', 'laberint'];
  const ALLBG = [...FONS, 'cel', 'escenari'];
  const ts = () => { try { return typeof TS_ === 'function' ? TS_() : null; } catch (e) { return null; } };
  // les peces triades a g8-1 (respostes del pas «review»); si encara no n'hi ha, unes de mostra
  const kit = () => { const t = ts(), r = t && t.rev && t.rev['g8-1'], a = (r && Array.isArray(r.a)) ? r.a : []; const g = (i, n) => (Number.isInteger(a[i]) && a[i] >= 0 && a[i] < n ? a[i] : 0); return [g(0, HER.length), g(1, PRE.length), g(2, ENE.length), g(3, FONS.length)]; };
  const kitW = () => { const [h, p, e, f] = kit(); return { bg: FONS[f], bgs: ALLBG, vars: ['punts', 'vides'], keys: ['left', 'right', 'up', 'down', 'space'],
    sprites: [{ id: 'heroi', art: HER[h][0], rot: HER[h][1], x: -170, y: -110, size: 70 }, { id: 'premi', art: PRE[p], x: 150, y: 80, size: 80 }, { id: 'enemic', art: ENE[e][0], rot: ENE[e][1], x: 20, y: 110, size: 80 }] }; };
  // l'última versió desada del videojoc (portafoli)
  const last = () => { const t = ts(); if (!t || !Array.isArray(t.port)) return null; for (let i = t.port.length - 1; i >= 0; i--) { const p = t.port[i]; if (p && p.kind === 'stage' && /^g8-/.test(p.sid || '') && p.w && p.progs && (p.w.sprites || []).some(s => s.id === 'heroi')) return p; } return null; };
  const myW = (goal, input, time, fresh) => { const p = fresh ? null : last(), w = p ? p.w : kitW(); return { ...w, sprites: (w.sprites || []).map(s => ({ ...s })), goal, input, time }; };
  const myP = () => { const p = last(); return p ? p.progs : undefined; };
  const ED = ['heroi', 'premi', 'enemic'];
  const flat = l => (l || []).flatMap(b => [b, ...flat(Array.isArray(b.b) ? b.b : []), ...flat(b.e)]);
  const blocks = (P, hat) => ED.flatMap(id => Object.entries((P && P[id]) || {}).filter(([h]) => !hat || h === hat).flatMap(([, scr]) => (scr || []).flatMap(flat)));
  const has = (P, ks, hat) => blocks(P, hat).some(b => ks.includes(b.k));
  const nProg = P => ED.filter(id => Object.values((P && P[id]) || {}).some(scr => (scr || []).some(l => l && l.length))).length;
  const sig = P => JSON.stringify(ED.map(id => Object.entries((P && P[id]) || {}).map(([h, scr]) => [h, (scr || []).filter(l => l && l.length)]).filter(x => x[1].length).sort((a, b) => a[0] < b[0] ? -1 : 1)), (k, v) => k === '_id' ? undefined : v);
  const IN = [{ t: .1, mouse: [80, 40] }, { t: .2, key: 'right', dur: .5 }, { t: .5, click: 'heroi' }, { t: .8, key: 'left', dur: .4 }, { t: 1.3, key: 'up', dur: .3 }, { t: 1.7, key: 'down', dur: .3 }, { t: 2.1, key: 'space', dur: .2 }];
  const PAL = ['move', 'turn', 'goto', 'gotorand', 'glide', 'setx', 'sety', 'chx', 'chy', 'point', 'pointto', 'bounce', 'say', 'think', 'costume', 'next', 'size', 'chsize', 'show', 'hide', 'ghost', 'front', 'bg', 'nextbg', 'sound', 'send', 'wait', 'rep', 'forever', 'until', 'waitu', 'stop', 'clone', 'delclone', 'if', 'else', 'and', 'setv', 'chv', 'timer0', 'cond+'];
  const HATS = ['flag', 'key:left', 'key:right', 'key:up', 'key:down', 'key:space', 'click', 'clone', 'msg:fi'];
  const VN = { punts: 'punts|puntos', vides: 'vides|vidas' };
  const TXT = ['Has guanyat!|¡Has ganado!', 'Has perdut!|¡Has perdido!', 'Ai!|¡Ay!', 'Som-hi!|¡Vamos!', 'Nivell 2!|¡Nivel 2!', 'Fes servir les fletxes!|¡Usa las flechas!'];
  const MINE = { edit: ED, hats: HATS, pal: PAL, ops: ['x', 'y', 'rnd', 'timer', 'mx', 'my'], texts: TXT, msgs: ['fi'], varNames: VN };
  // una solució de prova: un videojoc complet de recollir i esquivar (funciona amb totes les peces)
  const GAME = `@heroi flag{ setv:punts,0 setv:vides,3 goto:-170,-110 say:"Recull 10 premis!|¡Recoge 10 premios!",1 forever{ if:key:right{ chx:6 } if:key:left{ chx:-6 } if:key:up{ chy:6 } if:key:down{ chy:-6 } if:touch:enemic{ chv:vides,-1 sound:xoc goto:-170,-110 wait:0.5 } if:$vides<1{ say:"Has perdut!|¡Has perdido!" stop:all } if:$punts>9{ say:"Has guanyat!|¡Has ganado!" stop:all } } }
    @premi flag{ forever{ if:touch:heroi{ chv:punts,1 sound:moneda gotorand } } }`;
  const GAME_E = ` @enemic flag{ goto:20,110 forever{ pointto:heroi move:2 } }`;
  // miniatures per triar les peces
  const th = svg => `<span class="sthumb" style="margin:0 auto 6px">${svg}</span>`;
  const pickArt = (a) => () => th(sgCostume(a, 0)) + tx(STG_ART[a].name);
  const pickBg = (b) => () => th(STG_BG[b].svg()) + tx(STG_BG[b].name);

  /* ---------- Mons dels reptes ---------- */
  const W_DEMO = { bg: 'parc', sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -60 }, { id: 'moneda', art: 'moneda', x: 120, y: 60 }], vars: ['punts'], time: 9 };
  const P_DEMO = '@gat flag{ setv:punts,0 forever{ pointto:moneda move:4 } } @moneda flag{ forever{ next wait:0.1 if:touch:gat{ chv:punts,1 sound:moneda gotorand } } }';
  const W_BOSC = { bg: 'bosc', keys: ['left', 'right'], vars: ['punts', 'vides'], sprites: [{ id: 'numi', art: 'numi', rot: 'lr', x: -160, y: -100, size: 80 }, { id: 'estrella', art: 'estrella', x: 100, y: 60 }, { id: 'roca', art: 'roca', x: 160, y: -100 }] };
  const P_BOSC = `@numi flag{ setv:punts,0 setv:vides,3 setx:-160 sety:-100 forever{ if:key:right{ chx:6 } if:key:left{ chx:-6 } if:touch:roca{ chv:vides,-1 setx:-160 wait:0.5 } if:$vides<1!{ say:"Has perdut!|¡Has perdido!" stop:all } } }
    @estrella flag{ forever{ if:touch:numi{ chv:punts,1 sound:moneda gotorand } } } @roca flag{ forever{ rep:40{ chx:-5 } rep:40{ chx:5 } } }`;
  const W_VUIT = { bg: 'nit', keys: ['left', 'right', 'up', 'down'], vars: ['punts'], sprites: [{ id: 'vuit', art: 'vuit', rot: 'lr', x: -150, y: -80, size: 80 }, { id: 'estrella', art: 'estrella', x: 120, y: 80 }] };
  const P_VUIT = '@vuit flag{ setv:punts,0 goto:-150,-80 } key:right{ chx:15 } key:left{ chx:-15 } key:up{ chy:15 } key:down{ chy:-15 } @estrella flag{ forever{ if:touch:vuit{ chv:punts,1 sound:moneda gotorand } } }';

  return { t: "L'estudi de videojocs|El estudio de videojuegos", d: 'Projecte final: document de disseny, construcció, proves amb dades i publicació|Proyecto final: documento de diseño, construcción, pruebas con datos y publicación', color: '#C2410C', s: [
    /* ---------- Sessió 1 · El document de disseny ---------- */
    { id: 'g8-1', t: 'El document de disseny|El documento de diseño', min: 45, badge: 'g_u8idea',
      learn: ['Un estudi de videojocs comença amb un document de disseny: peces, regles, final i nivells.|Un estudio de videojuegos empieza con un documento de diseño: piezas, reglas, final y niveles.',
        'Cada regla diu quan passa i quina variable canvia: toco el premi → punts +1.|Cada regla dice cuándo pasa y qué variable cambia: toco el premio → puntos +1.',
        'Guanyar i perdre són comparacions (punts = 10, vides = 0), i un nivell nou canvia un número.|Ganar y perder son comparaciones (puntos = 10, vidas = 0), y un nivel nuevo cambia un número.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "Comencem l'última unitat! Vols que un meteorit surti per dalt <b>cada vegada en un lloc diferent</b> i baixi fins a terra. Quins blocs fas servir?|¡Empezamos la última unidad! Quieres que un meteorito salga por arriba <b>cada vez en un sitio diferente</b> y baje hasta el suelo. ¿Qué bloques usas?",
          opts: ["Ves a un lloc a l'atzar, posa y a 170 i repeteix fins que y < -160|Ve a un sitio al azar, pon y a 170 y repite hasta que y < -160", 'Ves a x: 0 y: 170 i, per sempre, mou-te|Ve a x: 0 y: 170 y, por siempre, muévete', "Espera 1 segons i amaga't|Espera 1 segundos y escóndete"], a: 0,
          ex: "L'atzar tria la x, «posa y a 170» el porta a dalt i el bucle «fins que» el fa baixar just fins a terra.|El azar elige la x, «pon y a 170» lo lleva arriba y el bucle «hasta que» lo hace bajar justo hasta el suelo." },
        { k: 'quiz', ph: 'recorda', q: 'La partida ha d\'acabar quan ja no queden vides. Quina condició poses al «si»?|La partida tiene que acabar cuando ya no quedan vidas. ¿Qué condición pones en el «si»?',
          opts: ['vides < 1|vidas < 1', 'vides > 3|vidas > 3', 'punts = 0|puntos = 0'], a: 0,
          ex: 'Quan vides val 0 (o menys), «vides < 1» es compleix i el «si» acaba la partida.|Cuando vidas vale 0 (o menos), «vidas < 1» se cumple y el «si» acaba la partida.' },
        { k: 'story', ph: 'missio', who: 'numi', scene: 'taller', title: "L'estudi de videojocs|El estudio de videojuegos",
          t: "Benvinguts a l'<b>estudi de videojocs</b> de l'illa! D'aquí a quatre setmanes, a la <b>Fira de Videojocs</b> de la plaça, cada persona de l'estudi hi <b>publicarà un videojoc propi</b> perquè el faci servir qualsevol visitant. La Guida, en Vuit i la Tuga ja tenen l'escriptori a punt… i tu també!|¡Bienvenidos al <b>estudio de videojuegos</b> de la isla! Dentro de cuatro semanas, en la <b>Feria de Videojuegos</b> de la plaza, cada persona del estudio <b>publicará un videojuego propio</b> para que lo use cualquier visitante. Guida, Vuit y Tuga ya tienen el escritorio a punto… ¡y tú también!" },
        { k: 'story', ph: 'missio', who: 'numi', mood: 'happy', title: 'Com treballa un estudi|Cómo trabaja un estudio',
          t: "Els estudis de veritat no comencen programant. Primer escriuen un <b>document de disseny</b>; després construeixen per peces, fan <b>proves amb dades</b> i, quan tot funciona, el <b>publiquen</b> amb instruccions. Farem el mateix, una fase cada setmana.|Los estudios de verdad no empiezan programando. Primero escriben un <b>documento de diseño</b>; después construyen por piezas, hacen <b>pruebas con datos</b> y, cuando todo funciona, lo <b>publican</b> con instrucciones. Haremos lo mismo, una fase cada semana.",
          box: "<ol><li><b>Setmana 1:</b> el document de disseny i la versió 1.</li><li><b>Setmana 2:</b> la construcció, peça a peça, amb nivells.</li><li><b>Setmana 3:</b> les proves amb dades i l'ajust de la dificultat.</li><li><b>Setmana 4:</b> la publicació i l'estrena.</li></ol>|<ol><li><b>Semana 1:</b> el documento de diseño y la versión 1.</li><li><b>Semana 2:</b> la construcción, pieza a pieza, con niveles.</li><li><b>Semana 3:</b> las pruebas con datos y el ajuste de la dificultad.</li><li><b>Semana 4:</b> la publicación y el estreno.</li></ol>" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Les peces|Las piezas', t: 'Quatre peces i un final|Cuatro piezas y un final', anim: 'g8parts',
            x: "Tot videojoc té un <b>protagonista</b> que controles, un <b>objectiu</b>, un <b>obstacle</b> i unes <b>regles</b>. Escriu-les al document de disseny abans de tocar cap bloc: si en falta una, ho veuràs al paper i no a mitja programació.|Todo videojuego tiene un <b>protagonista</b> que controlas, un <b>objetivo</b>, un <b>obstáculo</b> y unas <b>reglas</b>. Escríbelas en el documento de diseño antes de tocar ningún bloque: si falta una, lo verás en el papel y no a media programación." },
          { k: 'Regles|Reglas', t: 'Cada regla canvia una variable|Cada regla cambia una variable', media: { k: 'stage', w: W_DEMO, prog: P_DEMO, varNames: { punts: 'punts|puntos' } },
            x: "Una regla té dues parts: <b>quan</b> passa i <b>quina variable</b> canvia. Aquí, quan el gat toca la moneda → <b>punts +1</b> i la moneda salta a l'atzar. Al document, escriu-les així: «toco el premi → punts +1», «m'atrapa l'enemic → vides −1».|Una regla tiene dos partes: <b>cuándo</b> pasa y <b>qué variable</b> cambia. Aquí, cuando el gato toca la moneda → <b>puntos +1</b> y la moneda salta al azar. En el documento, escríbelas así: «toco el premio → puntos +1», «me atrapa el enemigo → vidas −1»." },
          { k: 'Final|Final', t: 'Guanyar i perdre són comparacions|Ganar y perder son comparaciones', anim: 'g8win',
            x: "El final també és una regla: <b>si punts = 10</b> → «Has guanyat!»; <b>si vides = 0</b> → «Has perdut!». En tots dos casos, «<b>atura tot</b>» acaba la partida. Escriu al document el número exacte: és el primer que ajustaràs a les proves.|El final también es una regla: <b>si puntos = 10</b> → «¡Has ganado!»; <b>si vidas = 0</b> → «¡Has perdido!». En los dos casos, «<b>para todo</b>» termina la partida. Escribe en el documento el número exacto: es lo primero que ajustarás en las pruebas.",
            tip: 'També pots fer servir el temps: guanyes si aguantes fins que el cronòmetre arriba a 30.|También puedes usar el tiempo: ganas si aguantas hasta que el cronómetro llega a 30.' },
          { k: 'Document|Documento', t: 'El document de disseny|El documento de diseño', anim: 'g8doc',
            x: "Una pàgina amb el títol, un esbós de l'escenari i una taula de regles: <b>quan…</b> i <b>què canvia</b>. Hi afegeixes els <b>nivells</b>: què canvia quan passes al nivell 2 (més velocitat, un altre fons, més enemics). Cada fila es convertirà en uns quants blocs.|Una página con el título, un boceto del escenario y una tabla de reglas: <b>cuándo…</b> y <b>qué cambia</b>. Le añades los <b>niveles</b>: qué cambia cuando pasas al nivel 2 (más velocidad, otro fondo, más enemigos). Cada fila se convertirá en unos cuantos bloques." },
          { k: 'Versió 1|Versión 1', t: 'Primer, una versió 1 petita|Primero, una versión 1 pequeña', anim: 'g8small',
            x: "L'estudi no ho programa tot de cop. La <b>versió 1</b> només fa una cosa, però la fa bé: el protagonista es mou. Després, cada vegada s'hi afegeix una fila del document i es torna a provar.|El estudio no lo programa todo de golpe. La <b>versión 1</b> solo hace una cosa, pero la hace bien: el protagonista se mueve. Después, cada vez se le añade una fila del documento y se vuelve a probar.",
            bad: 'Programo les vint regles del document i ho provo al final.|Programo las veinte reglas del documento y lo pruebo al final.', good: 'Programo una fila, la provo i passo a la següent.|Programo una fila, la pruebo y paso a la siguiente.' }
        ] },
        { k: 'quiz', ph: 'mans', q: 'Quina fila del document de disseny està escrita perquè es pugui <b>programar</b>?|¿Qué fila del documento de diseño está escrita para que se pueda <b>programar</b>?',
          opts: ["Quan el gat toca la moneda → punts +1 i la moneda va a l'atzar|Cuando el gato toca la moneda → puntos +1 y la moneda va al azar", 'El gat ha de ser ràpid i simpàtic|El gato tiene que ser rápido y simpático', 'Ha de ser emocionant de principi a final|Tiene que ser emocionante de principio a final'], a: 0,
          ex: "Una fila programable diu <b>quan</b> (el gat toca la moneda) i <b>què canvia</b> (punts +1, la moneda a l'atzar). «Ràpid» o «emocionant» són desitjos: cal convertir-los en números.|Una fila programable dice <b>cuándo</b> (el gato toca la moneda) y <b>qué cambia</b> (puntos +1, la moneda al azar). «Rápido» o «emocionante» son deseos: hay que convertirlos en números." },
        { k: 'seq', ph: 'mans', q: 'Com treballa un estudi de videojocs? <b>Ordena les fases.</b>|¿Cómo trabaja un estudio de videojuegos? <b>Ordena las fases.</b>',
          items: ['Escric el document de disseny: peces, regles, final i nivells|Escribo el documento de diseño: piezas, reglas, final y niveles', 'Programo una versió 1 petita|Programo una versión 1 pequeña', "Hi afegeixo les regles i els nivells, d'un en un|Le añado las reglas y los niveles, de uno en uno", 'Faig proves amb dades i ajusto els números|Hago pruebas con datos y ajusto los números', 'El publico amb títol i instruccions|Lo publico con título e instrucciones'],
          ex: 'Disseny, versió petita, construcció per peces, proves amb dades i publicació: així treballen els estudis.|Diseño, versión pequeña, construcción por piezas, pruebas con datos y publicación: así trabajan los estudios.' },
        { k: 'unplug', ph: 'mans', ico: '📄', title: 'Prototip de paper|Prototipo de papel', t: "En parella (o amb algú de casa), proveu el document de disseny sense pantalla: una persona fa de <b>pilot/a</b> i mou el protagonista; l'altra fa d'<b>ordinador</b> i aplica les regles al peu de la lletra.|En pareja (o con alguien de casa), probad el documento de diseño sin pantalla: una persona hace de <b>piloto/a</b> y mueve el protagonista; la otra hace de <b>ordenador</b> y aplica las reglas al pie de la letra.",
          steps: ["Dibuixeu l'escenari en un full gran i retalleu el protagonista, el premi i l'enemic. Al costat, un marcador: punts 0, vides 3.|Dibujad el escenario en una hoja grande y recortad el protagonista, el premio y el enemigo. Al lado, un marcador: puntos 0, vidas 3.",
            "L'ordinador/a llegeix les regles en veu alta i, a cada xoc, canvia el marcador només si hi ha una fila del document que ho digui.|El ordenador/a lee las reglas en voz alta y, en cada choque, cambia el marcador solo si hay una fila del documento que lo diga.",
            'Feu tres partides i apunteu quant dura cadascuna (comptant segons) i com acaba: guanyada o perduda.|Haced tres partidas y apuntad cuánto dura cada una (contando segundos) y cómo acaba: ganada o perdida.',
            "Hi ha hagut algun moment en què l'ordinador/a no sabia què fer? Falta una fila! Escriviu-la al document.|¿Ha habido algún momento en que el ordenador/a no sabía qué hacer? ¡Falta una fila! Escribidla en el documento."],
          tip: 'Si totes les partides duren molt poc o no acaben mai, canvieu un número del document (vides, punts per guanyar) i torneu-ho a provar.|Si todas las partidas duran muy poco o no acaban nunca, cambiad un número del documento (vidas, puntos para ganar) y volvedlo a probar.' },
        { k: 'sspot', ph: 'prova', q: "La Guida ha programat «La roca rodolant». Prova-la amb les fletxes i mira els guions d'en Numi: <b>toca la regla que compara una variable per acabar la partida</b>.|Guida ha programado «La roca rodante». Pruébala con las flechas y mira los guiones de Numi: <b>toca la regla que compara una variable para acabar la partida</b>.",
          w: W_BOSC, prog: P_BOSC,
          ex: "És el «si vides < 1»: la fila «vides = 0 → Has perdut!» del document, convertida en blocs.|Es el «si vidas < 1»: la fila «vidas = 0 → ¡Has perdido!» del documento, convertida en bloques." },
        { k: 'sfree', ph: 'investiga', q: "En Vuit ja té un prototip: recull estrelles amb les fletxes. <b>Prova'l</b> una estona (Comença i les fletxes) i compara'l amb les quatre peces i el final: què hi trobes a faltar?|Vuit ya tiene un prototipo: recoge estrellas con las flechas. <b>Pruébalo</b> un rato (Empieza y las flechas) y compáralo con las cuatro piezas y el final: ¿qué echas de menos?",
          w: W_VUIT, prog: P_VUIT },
        { k: 'quiz', ph: 'investiga', q: "Quines files li falten al document d'en Vuit?|¿Qué filas le faltan al documento de Vuit?",
          opts: ["Un obstacle i el final: ara els punts pugen sense límit i la partida no s'acaba mai|Un obstáculo y el final: ahora los puntos suben sin límite y la partida no se acaba nunca", 'Un fons amb més colors|Un fondo con más colores', 'Que en Vuit digui més frases|Que Vuit diga más frases'], a: 0,
          ex: "Té protagonista, objectiu i una regla de punts, però cap obstacle ni final. Amb «m'atrapa l'enemic → vides −1» i «punts = 10 → Has guanyat!» ja seria complet.|Tiene protagonista, objetivo y una regla de puntos, pero ningún obstáculo ni final. Con «me atrapa el enemigo → vidas −1» y «puntos = 10 → ¡Has ganado!» ya estaría completo." },
        { k: 'move', ph: 'pausa', secs: 30, t: "Fes de protagonista! Posa't dret/a: quan diguis «dreta», salta cap a la dreta; «esquerra», cap a l'esquerra. Ui, un meteorit! <b>Ajup-te</b> ràpid. I ara una estrella: <b>salta</b> amb els braços amunt i crida «+1»!|¡Haz de protagonista! Ponte de pie: cuando digas «derecha», salta hacia la derecha; «izquierda», hacia la izquierda. ¡Uy, un meteorito! <b>Agáchate</b> rápido. Y ahora una estrella: <b>salta</b> con los brazos arriba y grita «+1»!" },
        { k: 'stage', ph: 'repte', q: "<b>Fila del document: «toco el premi → punts +1».</b> L'ocell vola sol cap a l'estrella. Programa l'estrella: <b>si</b> toca l'ocell, suma 1 als punts i salta a un lloc a l'atzar. Ha de passar <b>moltes vegades</b>!|<b>Fila del documento: «toco el premio → puntos +1».</b> El pájaro vuela solo hacia la estrella. Programa la estrella: <b>si</b> toca el pájaro, suma 1 a los puntos y salta a un sitio al azar. ¡Tiene que pasar <b>muchas veces</b>!",
          w: { bg: 'cel', vars: ['punts'], time: 6, sprites: [{ id: 'ocell', art: 'ocell', rot: 'lr', x: -160, y: 40, prog: '@ocell flag{ forever{ pointto:estrella move:5 } }' }, { id: 'estrella', art: 'estrella', x: 120, y: 60 }],
            goal: [{ k: 'var', v: 'punts', min: 3, max: 40 }, { k: 'running', t: 5.5 }] },
          edit: ['estrella'], hats: ['flag'], pal: ['forever', 'if', 'setv', 'chv', 'gotorand', 'goto', 'wait', 'sound'], varNames: { punts: 'punts|puntos' },
          sol: '@estrella flag{ setv:punts,0 forever{ if:touch:ocell{ chv:punts,1 gotorand } } }',
          hint: "Necessites un «per sempre» amb un «si toca l'ocell» a dins. Si l'estrella no se'n va a un altre lloc, els punts pugen sense parar!|Necesitas un «por siempre» con un «si toca el pájaro» dentro. Si la estrella no se va a otro sitio, ¡los puntos suben sin parar!" },
        { k: 'stage', ph: 'repte', q: "<b>Fila del document: «m'atrapa l'enemic → vides −1».</b> La medusa baixa i puja sense parar. Programa la tortuga: comença amb <b>3 vides</b> i, <b>si</b> toca la medusa, en perd <b>una</b>. Compte: una sola vida per cada xoc!|<b>Fila del documento: «me atrapa el enemigo → vidas −1».</b> La medusa baja y sube sin parar. Programa la tortuga: empieza con <b>3 vidas</b> y, <b>si</b> toca la medusa, pierde <b>una</b>. Cuidado: ¡una sola vida por cada choque!",
          w: { bg: 'aquari', vars: ['vides'], time: 4.5, sprites: [{ id: 'tuga', art: 'tuga', rot: 'lr', x: 0, y: -90, size: 90 }, { id: 'medusa', art: 'medusa', x: 0, y: 120, prog: '@medusa flag{ forever{ glide:1,0,-90 glide:1,0,120 } }' }],
            goal: [{ k: 'touched', a: 'tuga', b: 'medusa' }, { k: 'var', v: 'vides', min: 1, max: 2 }, { k: 'running', t: 4.2 }] },
          edit: ['tuga'], hats: ['flag'], pal: ['forever', 'if', 'setv', 'chv', 'wait', 'say', 'sound'], varNames: { vides: 'vides|vidas' },
          sol: '@tuga flag{ setv:vides,3 forever{ if:touch:medusa{ chv:vides,-1 sound:xoc wait:1 } } }',
          hint: "Després de perdre una vida, espera una mica perquè la medusa tingui temps d'allunyar-se. Si no, cada instant que es toquen compta com un xoc nou!|Después de perder una vida, espera un poco para que la medusa tenga tiempo de alejarse. Si no, ¡cada instante que se tocan cuenta como un choque nuevo!" },
        { k: 'stage', ph: 'repte', q: "<b>Fila del document: «punts = 5 → Has guanyat!».</b> El gat ja persegueix monedes i la moneda compta els punts. Afegeix al guió del gat aquesta regla: <b>si</b> els punts arriben a <b>5</b>, digues «Has guanyat!» i <b>atura-ho tot</b>.|<b>Fila del documento: «puntos = 5 → ¡Has ganado!».</b> El gato ya persigue monedas y la moneda cuenta los puntos. Añade al guion del gato esta regla: <b>si</b> los puntos llegan a <b>5</b>, di «¡Has ganado!» y <b>páralo todo</b>.",
          w: { bg: 'parc', vars: ['punts'], time: 14, sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -80 }, { id: 'moneda', art: 'moneda', x: 120, y: 60, prog: '@moneda flag{ setv:punts,0 forever{ next wait:0.05 if:touch:gat{ chv:punts,1 sound:moneda gotorand } } }' }],
            goal: [{ k: 'var', v: 'punts', min: 5 }, { k: 'said', s: 'gat', t: 'guanyat' }, { k: 'stopped' }] },
          edit: ['gat'], hats: ['flag'], pal: ['move', 'pointto', 'forever', 'if', 'say', 'stop', 'wait', 'cond+'], texts: ['Has guanyat!|¡Has ganado!', 'Has perdut!|¡Has perdido!'], varNames: { punts: 'punts|puntos' },
          prog: '@gat flag{ forever{ pointto:moneda move:6 } }',
          sol: '@gat flag{ forever{ pointto:moneda move:6 if:$punts>4{ say:"Has guanyat!|¡Has ganado!" stop:all } } }',
          hint: "Posa un «si» dins del «per sempre», a sota de «mou-te». Toca la condició i tria «comparar números»: punts > 4 vol dir que ja en tens 5 (també pots triar ≥ i posar-hi un 5).|Pon un «si» dentro del «por siempre», debajo de «muévete». Toca la condición y elige «comparar números»: puntos > 4 quiere decir que ya tienes 5 (también puedes elegir ≥ y poner un 5)." },
        { k: 'review', ph: 'crea', who: 'numi', btn: 'Desa les peces|Guarda las piezas', q: "<b>El teu document de disseny, a l'app.</b> Tria les peces que has escrit al paper: protagonista, premi, enemic i escenari. Quan les tinguis, desa-les amb el botó de baix: seran la base de totes les versions.|<b>Tu documento de diseño, en la app.</b> Elige las piezas que has escrito en el papel: protagonista, premio, enemigo y escenario. Cuando las tengas, guárdalas con el botón de abajo: serán la base de todas las versiones.",
          items: [
            { q: 'Qui és el protagonista?|¿Quién es el protagonista?', opts: HER.map(([a]) => pickArt(a)) },
            { q: 'Què ha de recollir?|¿Qué tiene que recoger?', opts: PRE.map(pickArt) },
            { q: "Què l'atrapa o què ha d'esquivar?|¿Qué lo atrapa o qué tiene que esquivar?", opts: ENE.map(([a]) => pickArt(a)) },
            { q: 'On passa?|¿Dónde pasa?', opts: FONS.map(pickBg) }
          ] },
        { k: 'screate', ph: 'crea', name: 'El meu videojoc (versió 1)|Mi videojuego (versión 1)', ...MINE, hats: ['flag', 'key:left', 'key:right', 'key:up', 'key:down', 'key:space', 'click'],
          get w() { return myW([{ k: 'moved', s: 'heroi', min: 20 }, { k: 'said', s: 'heroi' }], [...IN, { t: 2.5, key: 'right', dur: .6 }, { t: 3.2, key: 'left', dur: .5 }], 4, true); },
          q: "<b>La versió 1.</b> Aquí tens les peces del teu document. Fes que el protagonista <b>es mogui amb les fletxes</b> i que, en començar, <b>digui el títol del teu videojoc</b>. Prova-la amb Comença i, quan funcioni, toca <b>Comprova</b> i desa-la.|<b>La versión 1.</b> Aquí tienes las piezas de tu documento. Haz que el protagonista <b>se mueva con las flechas</b> y que, al empezar, <b>diga el título de tu videojuego</b>. Pruébala con Empieza y, cuando funcione, toca <b>Comprueba</b> y guárdala.",
          crit: ['El protagonista es mou amb les fletxes|El protagonista se mueve con las flechas', 'En començar, diu el títol del videojoc|Al empezar, dice el título del videojuego', 'Si vols, ja hi pots posar una fila del document|Si quieres, ya puedes poner una fila del documento'],
          sol: '@heroi flag{ say:"La gran aventura|La gran aventura",2 } key:right{ chx:10 } key:left{ chx:-10 } key:up{ chy:10 } key:down{ chy:-10 }',
          hint: "Fes servir els guions «Quan premo la tecla…»: un per a cada fletxa, amb «canvia x en» o «canvia y en». El títol, amb «digues» al guió de la bandera.|Usa los guiones «Al pulsar la tecla…»: uno para cada flecha, con «cambia x en» o «cambia y en». El título, con «di» en el guion de la bandera." },
        { k: 'quiz', ph: 'tanca', q: 'La Tuga vol començar a programar sense document de disseny. Què li pot passar?|Tuga quiere empezar a programar sin documento de diseño. ¿Qué le puede pasar?',
          opts: ['Que a mitja feina no sàpiga quines regles i variables necessita|Que a media tarea no sepa qué reglas y variables necesita', "Que l'ordinador no la deixi programar|Que el ordenador no la deje programar", 'Res: el document només serveix per decorar|Nada: el documento solo sirve para decorar'], a: 0,
          ex: 'El document és el mapa: diu quines variables cal crear, quines regles les canvien i com acaba la partida.|El documento es el mapa: dice qué variables hay que crear, qué reglas las cambian y cómo acaba la partida.' },
        { k: 'quiz', ph: 'tanca', q: 'Al document hi ha el protagonista, el premi i «toco el premi → punts +1». Què hi falta perquè estigui complet?|En el documento están el protagonista, el premio y «toco el premio → puntos +1». ¿Qué falta para que esté completo?',
          opts: ['Un obstacle i com es guanya o es perd|Un obstáculo y cómo se gana o se pierde', 'Un segon protagonista|Un segundo protagonista', 'Més colors al fons|Más colores en el fondo'], a: 0,
          ex: "Sense obstacle és massa fàcil, i sense final la partida no s'acaba. Un enemic amb «vides −1» i un «punts = 10 → Has guanyat!» ho completen.|Sin obstáculo es demasiado fácil, y sin final la partida no se acaba. Un enemigo con «vidas −1» y un «puntos = 10 → ¡Has ganado!» lo completan." },
        { k: 'feel', ph: 'tanca' }
      ] },

    /* ---------- Sessió 2 · Construeix-lo peça a peça ---------- */
    { id: 'g8-2', t: 'Construeix-lo peça a peça|Constrúyelo pieza a pieza', min: 45, badge: 'g_u8build',
      learn: ['Cada personatge té els seus guions, i tots funcionen alhora.|Cada personaje tiene sus guiones, y todos funcionan a la vez.',
        'En començar, cal posar-ho tot a lloc: punts a 0, vides a 3, posicions.|Al empezar, hay que ponerlo todo en su sitio: puntos a 0, vidas a 3, posiciones.',
        'Un videojoc es construeix peça a peça, provant cada peça abans de la següent.|Un videojuego se construye pieza a pieza, probando cada pieza antes de la siguiente.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'La setmana passada vas escriure el document de disseny. Què diu cada fila de regles?|La semana pasada escribiste el documento de diseño. ¿Qué dice cada fila de reglas?',
          opts: ['Quan passa una cosa i quina variable canvia|Cuándo pasa algo y qué variable cambia', 'Quins colors té el fons|Qué colores tiene el fondo', 'Quantes tecles té el teclat|Cuántas teclas tiene el teclado'], a: 0,
          ex: 'Per exemple: «toco el premi → punts +1». Avui convertiràs cada fila en blocs.|Por ejemplo: «toco el premio → puntos +1». Hoy convertirás cada fila en bloques.' },
        { k: 'quiz', ph: 'recorda', q: 'Per què va bé començar amb una <b>versió petita</b> del videojoc?|¿Por qué va bien empezar con una <b>versión pequeña</b> del videojuego?',
          opts: ["Perquè és fàcil de provar i d'arreglar abans d'afegir-hi més peces|Porque es fácil de probar y de arreglar antes de añadir más piezas", 'Perquè els videojocs petits són millors|Porque los videojuegos pequeños son mejores', 'Perquè no cal provar-la|Porque no hace falta probarla'], a: 0 },
        { k: 'story', ph: 'missio', who: 'numi', scene: 'lab', title: "El taller de l'estudi|El taller del estudio",
          t: "Avui l'estudi es converteix en un <b>taller</b>: cada fila del document de disseny és una peça. <b>Una fila, la proves; una altra fila, la proves</b>… fins que la versió 1 tingui totes les regles, el final i, si vols, un <b>nivell 2</b>.|Hoy el estudio se convierte en un <b>taller</b>: cada fila del documento de diseño es una pieza. <b>Una fila, la pruebas; otra fila, la pruebas</b>… hasta que la versión 1 tenga todas las reglas, el final y, si quieres, un <b>nivel 2</b>." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Del paper als blocs|Del papel a los bloques', t: 'Cada fila, uns quants blocs|Cada fila, unos cuantos bloques', anim: 'g8plan',
            x: "Agafa el document i ves fila per fila. «Fletxes: moure» es converteix en «si tecla → canvia x»; «toco el premi → punts +1», en un «si toca» amb «suma a punts 1». Quan una fila funciona, la marques al paper i passes a la següent.|Coge el documento y ve fila por fila. «Flechas: mover» se convierte en «si tecla → cambia x»; «toco el premio → puntos +1», en un «si toca» con «suma a puntos 1». Cuando una fila funciona, la marcas en el papel y pasas a la siguiente." },
          { k: 'Guions|Guiones', t: 'Cada personatge, els seus guions|Cada personaje, sus guiones', anim: 'g8who',
            x: "No cal posar-ho tot al protagonista. Cada personatge s'encarrega de les seves regles: el protagonista es mou i compta les vides, la moneda suma els punts quan la toquen i el meteorit cau. Quan toques la bandera, <b>tots els guions comencen alhora</b>.|No hace falta ponerlo todo en el protagonista. Cada personaje se encarga de sus reglas: el protagonista se mueve y cuenta las vidas, la moneda suma los puntos cuando la tocan y el meteorito cae. Cuando tocas la bandera, <b>todos los guiones empiezan a la vez</b>." },
          { k: 'Començar|Empezar', t: 'Tot a lloc en començar|Todo en su sitio al empezar', media: { k: 'stage', w: { bg: 'ciutat', vars: ['punts', 'vides'], time: 5, sprites: [{ id: 'cotxe', art: 'cotxe', x: 60, y: 40, size: 70 }, { id: 'moneda', art: 'moneda', x: 140, y: -120 }] }, prog: '@cotxe flag{ setv:punts,0 setv:vides,3 goto:-160,-120 show say:"Som-hi!|¡Vamos!",1 forever{ chx:4 if:touch:moneda{ chv:punts,1 } } } @moneda flag{ forever{ next wait:0.1 } }', varNames: { punts: 'punts|puntos', vides: 'vides|vidas' } },
            x: "El primer guió de la bandera sempre fa el mateix: <span class='hl'>ho posa tot a lloc</span>. Punts a 0, vides a 3, el protagonista al seu punt de sortida i visible. Així cada vegada que tornes a començar, el videojoc comença igual.|El primer guion de la bandera siempre hace lo mismo: <span class='hl'>lo pone todo en su sitio</span>. Puntos a 0, vidas a 3, el protagonista en su punto de salida y visible. Así cada vez que vuelves a empezar, el videojuego empieza igual.",
            bad: 'No poso els punts a 0: ja començaran bé.|No pongo los puntos a 0: ya empezarán bien.', good: 'Al principi: posa punts a 0, vides a 3 i ves a la sortida.|Al principio: pon puntos a 0, vidas a 3 y ve a la salida.' },
          { k: 'Nivells|Niveles', t: 'Un nivell nou: canvia el fons i va més de pressa|Un nivel nuevo: cambia el fondo y va más deprisa', media: { k: 'stage', w: { bg: 'bosc', bgs: ['bosc', 'nit'], vars: ['punts', 'velocitat'], time: 9, sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -80 }, { id: 'poma', art: 'poma', x: 120, y: 60 }] }, prog: '@gat flag{ bg:bosc setv:punts,0 setv:velocitat,3 forever{ pointto:poma move:$velocitat if:$punts>2{ bg:nit setv:velocitat,8 } } } @poma flag{ forever{ if:touch:gat{ chv:punts,1 sound:moneda gotorand } } }', varNames: { punts: 'punts|puntos', velocitat: 'velocitat|velocidad' } },
            x: "Un nivell és una fila més del document: quan el gat arriba a 3 punts, passa al <b>nivell 2</b>, el fons es fa de nit i la variable <b>velocitat</b> passa de 3 a 8. Com que el gat es mou «velocitat» passos, ara corre molt més. Un sol número canvia la dificultat!|Un nivel es una fila más del documento: cuando el gato llega a 3 puntos, pasa al <b>nivel 2</b>, el fondo se hace de noche y la variable <b>velocidad</b> pasa de 3 a 8. Como el gato se mueve «velocidad» pasos, ahora corre mucho más. ¡Un solo número cambia la dificultad!" },
          { k: 'Clons|Clones', t: 'Molts enemics amb un sol guió|Muchos enemigos con un solo guion', media: { k: 'stage', w: { bg: 'espai', time: 6, sprites: [{ id: 'meteorit', art: 'meteorit', x: 0, y: 170, size: 70 }] }, prog: '@meteorit flag{ hide forever{ clone wait:0.6 } } clone{ gotorand sety:170 show forever{ chy:-5 if:y<-170{ delclone } } }' },
            x: "Si vols una pluja de meteorits, no cal dibuixar-ne vint: un sol meteorit amagat crea <b>clons</b>, i cada clon fa el guió «Quan començo com a clon»: surt a dalt en un lloc a l'atzar, cau i s'esborra a baix.|Si quieres una lluvia de meteoritos, no hace falta dibujar veinte: un solo meteorito escondido crea <b>clones</b>, y cada clon hace el guion «Al empezar como clon»: sale arriba en un sitio al azar, cae y se borra abajo.",
            tip: "Esborra els clons quan surten de l'escenari: si no, se'n van acumulant.|Borra los clones cuando salen del escenario: si no, se van acumulando." }
        ] },
        { k: 'seq', ph: 'mans', q: 'Ordena el guió de la bandera del protagonista d\'un videojoc.|Ordena el guion de la bandera del protagonista de un videojuego.',
          items: ['Quan comença (bandera verda)|Al empezar (bandera verde)', 'Posa punts a 0 i vides a 3|Pon puntos a 0 y vidas a 3', 'Ves a la sortida i digues el nom del videojoc|Ve a la salida y di el nombre del videojuego', 'Per sempre: si premo una fletxa, mou-te|Por siempre: si pulso una flecha, muévete', 'Dins del per sempre: si toco l\'enemic, vides −1|Dentro del por siempre: si toco al enemigo, vidas −1'],
          ex: "Primer el que passa una sola vegada (posar-ho tot a lloc) i després el bucle amb les regles que es comproven tota l'estona.|Primero lo que pasa una sola vez (ponerlo todo en su sitio) y después el bucle con las reglas que se comprueban todo el rato." },
        { k: 'quiz', ph: 'mans', q: 'On poses el bloc «posa punts a 0»?|¿Dónde pones el bloque «pon puntos a 0»?',
          opts: ['Al principi del guió de la bandera, abans del «per sempre»|Al principio del guion de la bandera, antes del «por siempre»', 'Dins del «per sempre»|Dentro del «por siempre»', 'Al guió de la moneda, quan la toquen|En el guion de la moneda, cuando la tocan'], a: 0,
          ex: 'Dins del «per sempre», els punts tornarien a 0 a cada volta i no podrien pujar mai.|Dentro del «por siempre», los puntos volverían a 0 en cada vuelta y no podrían subir nunca.' },
        { k: 'sspot', ph: 'prova', q: "En aquest videojoc el gat atrapa monedes, però el marcador <b>sempre marca 0</b>. Prova'l i <b>toca el bloc que ho espatlla</b>.|En este videojuego el gato atrapa monedas, pero el marcador <b>siempre marca 0</b>. Pruébalo y <b>toca el bloque que lo estropea</b>.",
          w: { bg: 'parc', vars: ['punts'], time: 8, sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -80 }, { id: 'moneda', art: 'moneda', x: 120, y: 60 }] },
          prog: '@gat flag{ forever{ setv:punts,0! pointto:moneda move:5 } } @moneda flag{ forever{ if:touch:gat{ chv:punts,1 sound:moneda gotorand } } }',
          ex: "«Posa punts a 0» és dins del «per sempre»: cada volta torna a deixar els punts a 0. S'ha de posar abans del bucle.|«Pon puntos a 0» está dentro del «por siempre»: cada vuelta vuelve a dejar los puntos a 0. Hay que ponerlo antes del bucle." },
        { k: 'stage', ph: 'investiga', q: "<b>Arregla-ho:</b> el meteorit cau una sola vegada i desapareix per sota. Fes que, <b>si</b> arriba a baix (y < −170), torni a dalt (y = 170) en un lloc a l'atzar i torni a caure.|<b>Arréglalo:</b> el meteorito cae una sola vez y desaparece por debajo. Haz que, <b>si</b> llega abajo (y < −170), vuelva arriba (y = 170) en un sitio al azar y vuelva a caer.",
          w: { bg: 'espai', time: 3, sprites: [{ id: 'meteorit', art: 'meteorit', x: 0, y: 170 }], goal: [{ k: 'reach', s: 'meteorit', r: [-240, -180, 240, -140] }, { k: 'at', s: 'meteorit', r: [-240, -60, 240, 180] }, { k: 'running', t: 2.8 }] },
          edit: ['meteorit'], hats: ['flag'], pal: ['chy', 'sety', 'setx', 'gotorand', 'goto', 'forever', 'if', 'cond+'], ops: ['x', 'y'],
          prog: '@meteorit flag{ goto:0,170 forever{ chy:-6 } }', sol: '@meteorit flag{ goto:0,170 forever{ chy:-6 if:y<-170{ gotorand sety:170 } } }',
          hint: "Dins del «per sempre», posa un «si» amb «comparar números»: posició y < −170. A dins: «ves a un lloc a l'atzar» i després «posa y a 170».|Dentro del «por siempre», pon un «si» con «comparar números»: posición y < −170. Dentro: «ve a un sitio al azar» y después «pon y a 170»." },
        { k: 'move', ph: 'pausa', secs: 30, t: "Sou una pluja de meteorits! Quan diguis «clon», un company/a s'aixeca i «cau» a poc a poc fins a ajupir-se. Si no hi ha companys a prop, fes-ho tu: aixeca't de puntetes, baixa a poc a poc fins a terra… i torna a dalt d'un salt!|¡Sois una lluvia de meteoritos! Cuando digas «clon», un compañero/a se levanta y «cae» despacio hasta agacharse. Si no hay compañeros cerca, hazlo tú: ponte de puntillas, baja despacio hasta el suelo… ¡y vuelve arriba de un salto!" },
        { k: 'stage', ph: 'repte', q: "<b>Peça: el nivell 2.</b> El gat ja recull pomes. Afegeix-hi una regla: <b>si</b> els punts passen de 2, canvia el fons a <b>nit</b> i digues «Nivell 2!».|<b>Pieza: el nivel 2.</b> El gato ya recoge manzanas. Añade una regla: <b>si</b> los puntos pasan de 2, cambia el fondo a <b>noche</b> y di «¡Nivel 2!».",
          w: { bg: 'bosc', bgs: ['bosc', 'nit'], vars: ['punts'], time: 10, sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -80 }, { id: 'poma', art: 'poma', x: 120, y: 60, prog: '@poma flag{ setv:punts,0 forever{ if:touch:gat{ chv:punts,1 sound:moneda gotorand } } }' }],
            goal: [{ k: 'var', v: 'punts', min: 3 }, { k: 'bg', n: 'nit' }, { k: 'said', s: 'gat', t: 'Nivell 2' }] },
          edit: ['gat'], hats: ['flag'], pal: ['move', 'pointto', 'forever', 'if', 'bg', 'say', 'wait', 'cond+'], texts: ['Nivell 2!|¡Nivel 2!', 'Som-hi!|¡Vamos!'], varNames: { punts: 'punts|puntos' },
          prog: '@gat flag{ bg:bosc forever{ pointto:poma move:6 } }', sol: '@gat flag{ bg:bosc forever{ pointto:poma move:6 if:$punts>2{ bg:nit say:"Nivell 2!|¡Nivel 2!" } } }',
          hint: "Com al repte de guanyar: un «si» dins del «per sempre» amb «comparar números» (punts > 2). A dins, «canvia el fons a» i «digues».|Como en el reto de ganar: un «si» dentro del «por siempre» con «comparar números» (puntos > 2). Dentro, «cambia el fondo a» y «di»." },
        { k: 'stage', ph: 'repte', q: "<b>Peça: cada cop més de pressa.</b> Fes que el meteorit caigui <b>velocitat</b> passos cada vegada. Comença amb velocitat 5 i, cada vegada que arriba a baix i torna a dalt, <b>suma 1 a la velocitat</b>. Ha d'arribar com a mínim a 7!|<b>Pieza: cada vez más deprisa.</b> Haz que el meteorito caiga <b>velocidad</b> pasos cada vez. Empieza con velocidad 5 y, cada vez que llega abajo y vuelve arriba, <b>suma 1 a la velocidad</b>. ¡Tiene que llegar como mínimo a 7!",
          w: { bg: 'espai', vars: ['velocitat'], time: 7, sprites: [{ id: 'meteorit', art: 'meteorit', x: 0, y: 170 }], goal: [{ k: 'var', v: 'velocitat', min: 7 }, { k: 'running', t: 6.5 }] },
          edit: ['meteorit'], hats: ['flag'], pal: ['move', 'point', 'goto', 'gotorand', 'sety', 'forever', 'if', 'setv', 'chv', 'cond+'], ops: ['y'], varNames: { velocitat: 'velocitat|velocidad' },
          sol: '@meteorit flag{ setv:velocitat,5 goto:0,170 point:180 forever{ move:$velocitat if:y<-170{ gotorand sety:170 chv:velocitat,1 } } }',
          hint: "«Apunta en direcció 180» fa mirar avall. Després, «mou-te» amb el valor de la variable velocitat. Quan torni a dalt, suma 1 a la velocitat.|«Apunta en dirección 180» hace mirar abajo. Después, «muévete» con el valor de la variable velocidad. Cuando vuelva arriba, suma 1 a la velocidad." },
        { k: 'stage', ph: 'repte', q: "<b>Peça: una pluja d'estrelles.</b> L'estrella s'amaga i crea <b>almenys 6 clons</b>, un cada mig segon. Cada clon surt en un lloc a l'atzar, a dalt de tot, i cau. Quan arriba a baix, s'esborra.|<b>Pieza: una lluvia de estrellas.</b> La estrella se esconde y crea <b>al menos 6 clones</b>, uno cada medio segundo. Cada clon sale en un sitio al azar, arriba del todo, y cae. Cuando llega abajo, se borra.",
          w: { bg: 'nit', time: 5, sprites: [{ id: 'estrella', art: 'estrella', x: 0, y: 170 }], goal: [{ k: 'clones', min: 6 }, { k: 'running', t: 4.5 }] },
          edit: ['estrella'], hats: ['flag', 'clone'], pal: ['hide', 'show', 'gotorand', 'sety', 'chy', 'clone', 'delclone', 'wait', 'rep', 'forever', 'if', 'cond+'], ops: ['y'],
          sol: '@estrella flag{ hide rep:6{ clone wait:0.5 } } clone{ gotorand sety:170 show forever{ chy:-4 if:y<-170{ delclone } } }',
          hint: "Al guió de la bandera: amaga't i repeteix 6 vegades «crea un clon de mi» i «espera 0.5». Al guió del clon: ves a l'atzar, posa y a 170, mostra't i cau.|En el guion de la bandera: escóndete y repite 6 veces «crea un clon de mí» y «espera 0.5». En el guion del clon: ve al azar, pon y a 170, muéstrate y cae." },
        { k: 'story', ph: 'crea', who: 'numi', title: 'Ara, el teu videojoc!|¡Ahora, tu videojuego!',
          t: "Ja tens totes les peces a punt. Obre la versió 1 i ves <b>fila per fila</b> del teu document. Després de cada fila, toca <b>Comença</b> i prova-la amb les fletxes!|Ya tienes todas las piezas a punto. Abre la versión 1 y ve <b>fila por fila</b> de tu documento. Después de cada fila, ¡toca <b>Empieza</b> y pruébala con las flechas!",
          box: "<ol><li>El protagonista es mou (ja ho tens!).</li><li>Toco el premi → punts +1.</li><li>L'enemic es mou; si m'atrapa → vides −1.</li><li>Com guanyo i com perdo.</li><li>Nivell 2: què canvia (fons, velocitat, clons…).</li></ol>|<ol><li>El protagonista se mueve (¡ya lo tienes!).</li><li>Toco el premio → puntos +1.</li><li>El enemigo se mueve; si me atrapa → vidas −1.</li><li>Cómo gano y cómo pierdo.</li><li>Nivel 2: qué cambia (fondo, velocidad, clones…).</li></ol>" },
        { k: 'screate', ph: 'crea', name: 'El meu videojoc (versió 2)|Mi videojuego (versión 2)', ...MINE,
          get w() { return myW([{ k: 'running', t: 2.5 }], IN, 2.5); }, get prog() { return myP(); },
          q: "<b>Construeix el teu videojoc.</b> Continua la versió que vas desar i afegeix-hi les files del teu document de disseny. Toca <b>Comença</b> per provar-lo tantes vegades com vulguis. Quan estigui a punt, toca <b>Comprova</b> i desa'l.|<b>Construye tu videojuego.</b> Continúa la versión que guardaste y añádele las filas de tu documento de diseño. Toca <b>Empieza</b> para probarlo tantas veces como quieras. Cuando esté a punto, toca <b>Comprueba</b> y guárdalo.",
          crit: ['Té protagonista, objectiu i obstacle|Tiene protagonista, objetivo y obstáculo', 'Fa servir una variable (punts o vides)|Usa una variable (puntos o vidas)', 'Té almenys una regla amb «si…»|Tiene al menos una regla con «si…»', 'Es pot guanyar o perdre|Se puede ganar o perder'],
          check: P => !has(P, ['setv', 'chv']) ? 'Ja funciona! Ara fes servir una variable: per exemple, suma 1 als punts quan toquis el premi.|¡Ya funciona! Ahora usa una variable: por ejemplo, suma 1 a los puntos cuando toques el premio.'
            : !has(P, ['if', 'until', 'waitu']) ? 'Molt bé! Ara afegeix-hi una regla amb «si…»: per exemple, si toques l\'enemic, vides −1.|¡Muy bien! Ahora añade una regla con «si…»: por ejemplo, si tocas al enemigo, vidas −1.'
            : nProg(P) < 2 ? "Ja gairebé hi és! Programa també un altre personatge: el premi o l'enemic.|¡Ya casi está! Programa también otro personaje: el premio o el enemigo." : null,
          sol: GAME + GAME_E,
          hint: "Ves peça a peça: primer el premi (si toca el protagonista, punts +1 i ves a l'atzar), després l'enemic (es mou i, si et toca, vides −1) i al final com guanyes i com perds.|Ve pieza a pieza: primero el premio (si toca al protagonista, puntos +1 y ve al azar), después el enemigo (se mueve y, si te toca, vidas −1) y al final cómo ganas y cómo pierdes." },
        { k: 'quiz', ph: 'tanca', q: 'Has afegit una peça nova al teu videojoc. Què fas abans de posar-ne una altra?|Has añadido una pieza nueva a tu videojuego. ¿Qué haces antes de poner otra?',
          opts: ['El provo per veure si la peça funciona|Lo pruebo para ver si la pieza funciona', "N'afegeixo cinc més de cop|Añado cinco más de golpe", 'Esborro la peça anterior|Borro la pieza anterior'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Vols molts meteorits que caiguin alhora. Quina és la manera més curta?|Quieres muchos meteoritos que caigan a la vez. ¿Cuál es la manera más corta?',
          opts: ['Un meteorit que crea clons|Un meteorito que crea clones', 'Dibuixar vint meteorits iguals|Dibujar veinte meteoritos iguales', 'Un meteorit molt gran|Un meteorito muy grande'], a: 0,
          ex: 'Tots els clons fan el mateix guió, «Quan començo com a clon». Si el canvies, canvien tots.|Todos los clones hacen el mismo guion, «Al empezar como clon». Si lo cambias, cambian todos.' },
        { k: 'feel', ph: 'tanca' }
      ] },

    /* ---------- Sessió 3 · Proves amb dades ---------- */
    { id: 'g8-3', t: 'Proves amb dades|Pruebas con datos', min: 45, badge: 'g_u8prova',
      learn: ["A les proves, una altra persona fa partides i n'apunta les dades: quant duren, quants punts fa i quantes vides li queden.|En las pruebas, otra persona hace partidas y apunta los datos: cuánto duran, cuántos puntos hace y cuántas vidas le quedan.",
        "Les dades diuen quin número cal ajustar: la velocitat, les vides o els punts per guanyar. D'un en un!|Los datos dicen qué número hay que ajustar: la velocidad, las vidas o los puntos para ganar. ¡De uno en uno!",
        "Un informe de prova explica què ha passat, amb dades, i proposa un canvi concret.|Un informe de prueba explica qué ha pasado, con datos, y propone un cambio concreto."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'La setmana passada vas construir el teu videojoc. Què ha de fer el guió de la bandera <b>abans</b> del «per sempre»?|La semana pasada construiste tu videojuego. ¿Qué tiene que hacer el guion de la bandera <b>antes</b> del «por siempre»?',
          opts: ['Posar-ho tot a lloc: punts a 0, vides a 3 i la sortida|Ponerlo todo en su sitio: puntos a 0, vidas a 3 y la salida', 'Esborrar tots els guions|Borrar todos los guiones', 'Res: el per sempre ja ho fa tot|Nada: el por siempre ya lo hace todo'], a: 0 },
        { k: 'quiz', ph: 'recorda', q: 'Quin guió fa cada clon quan neix?|¿Qué guion hace cada clon cuando nace?',
          opts: ['«Quan començo com a clon»|«Al empezar como clon»', '«Quan comença (bandera verda)»|«Al empezar (bandera verde)»', 'Cap: els clons no fan res|Ninguno: los clones no hacen nada'], a: 0 },
        { k: 'story', ph: 'missio', who: 'numi', scene: 'poble', title: 'La sala de proves|La sala de pruebas',
          t: "A la plaça ja munten la Fira. Abans de publicar, cada videojoc de l'estudi passa per la <b>sala de proves</b>: una altra persona en fa unes quantes partides i n'apunta les <b>dades</b>. Amb les dades sabrem si és massa fàcil, massa difícil… o al punt.|En la plaza ya montan la Feria. Antes de publicar, cada videojuego del estudio pasa por la <b>sala de pruebas</b>: otra persona hace unas cuantas partidas y apunta los <b>datos</b>. Con los datos sabremos si es demasiado fácil, demasiado difícil… o está en su punto." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Ulls nous|Ojos nuevos', t: 'Per què ho ha de provar algú altre?|¿Por qué lo tiene que probar otra persona?', media: { k: 'stage', w: { bg: 'ciutat', time: 5, sprites: [{ id: 'cotxe', art: 'cotxe', x: -160, y: -130, size: 70 }] }, prog: '@cotxe flag{ goto:-160,-130 say:"Vaig cap a la dreta…|Voy hacia la derecha…",1 forever{ chx:6 } }' },
            x: "Tu saps com funciona el teu videojoc i el proves sempre igual. Una persona nova fa coses que no esperaves i troba <b>bugs</b> (errors del programa), com aquest cotxe que surt de l'escenari i no torna. Per això els estudis fan <span class='hl'>proves amb usuaris</span>.|Tú sabes cómo funciona tu videojuego y lo pruebas siempre igual. Una persona nueva hace cosas que no esperabas y encuentra <b>bugs</b> (errores del programa), como este coche que sale del escenario y no vuelve. Por eso los estudios hacen <span class='hl'>pruebas con usuarios</span>." },
          { k: 'Dades|Datos', t: 'Mesura cada partida|Mide cada partida', anim: 'g8data',
            x: "A cada partida, el provador/a apunta tres dades: quant <b>dura</b>, quants <b>punts</b> fa i quantes <b>vides</b> li queden. Si totes duren 3 segons i no fa cap punt, no és mala sort: és massa difícil. Les dades ho demostren.|En cada partida, el probador/a apunta tres datos: cuánto <b>dura</b>, cuántos <b>puntos</b> hace y cuántas <b>vidas</b> le quedan. Si todas duran 3 segundos y no hace ningún punto, no es mala suerte: es demasiado difícil. Los datos lo demuestran." },
          { k: 'Ajustar|Ajustar', t: 'Canvia un número i torna a mesurar|Cambia un número y vuelve a medir', anim: 'g8tune',
            x: "Per ajustar la dificultat n'hi ha prou amb <b>un número</b>: la velocitat de l'enemic, les vides del principi o els punts per guanyar. Canvia'n <b>només un</b> cada vegada i torna a fer partides: si les dades milloren, saps quin canvi ho ha fet.|Para ajustar la dificultad basta con <b>un número</b>: la velocidad del enemigo, las vidas del principio o los puntos para ganar. Cambia <b>solo uno</b> cada vez y vuelve a hacer partidas: si los datos mejoran, sabes qué cambio lo ha hecho." },
          { k: 'Informe|Informe', t: "L'informe de prova|El informe de prueba", anim: 'g8feedback',
            x: "Un <span class='hl'>informe de prova</span> és útil quan és concret: <b>què ha passat</b> (amb dades), <b>què funciona</b> i <b>quin canvi</b> proposes. Parla del videojoc, no de la persona que l'ha fet.|Un <span class='hl'>informe de prueba</span> es útil cuando es concreto: <b>qué ha pasado</b> (con datos), <b>qué funciona</b> y <b>qué cambio</b> propones. Habla del videojuego, no de la persona que lo ha hecho.",
            bad: '«És massa difícil i avorrit.»|«Es demasiado difícil y aburrido.»', good: "«Tres partides de 2 a 4 segons. La pluja funciona; i si el cranc anés a velocitat 4?»|«Tres partidas de 2 a 4 segundos. La lluvia funciona; ¿y si el cangrejo fuera a velocidad 4?»" },
          { k: 'Espia|Espía', t: 'Mira què passa per dins|Mira qué pasa por dentro', media: { k: 'stage', w: { bg: 'parc', vars: ['punts'], time: 8, sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -80 }, { id: 'moneda', art: 'moneda', x: 120, y: 60 }] }, prog: '@gat flag{ setv:punts,0 forever{ pointto:moneda move:4 say:$punts } } @moneda flag{ forever{ if:touch:gat{ chv:punts,1 sound:moneda gotorand } } }', varNames: { punts: 'punts|puntos' } },
            x: "Quan un bug costa de trobar, fes que un personatge <b>digui el valor d'una variable</b> mentre el videojoc funciona: és com posar-hi un aparell de mesura. Aquí el gat diu els punts tota l'estona. Quan hagis trobat el bug, treu el bloc.|Cuando un bug cuesta de encontrar, haz que un personaje <b>diga el valor de una variable</b> mientras el videojuego funciona: es como ponerle un aparato de medida. Aquí el gato dice los puntos todo el rato. Cuando hayas encontrado el bug, quita el bloque.",
            tip: "Al bloc «digues», toca el text i tria la variable.|En el bloque «di», toca el texto y elige la variable." }
        ] },
        { k: 'quiz', ph: 'mans', q: "Quin informe de prova ajuda més l'autor/a?|¿Qué informe de prueba ayuda más al autor/a?",
          opts: ["«He fet 3 partides: han durat 4, 5 i 3 segons i no he passat de 2 punts. El cranc és massa ràpid.»|«He hecho 3 partidas: han durado 4, 5 y 3 segundos y no he pasado de 2 puntos. El cangrejo es demasiado rápido.»", '«És molt difícil.»|«Es muy difícil.»', '«He perdut, però no sé per què.»|«He perdido, pero no sé por qué.»'], a: 0,
          ex: "Té dades (quant duren les partides, quants punts) i diu què canviaria. Amb això l'autor/a ja sap quin número ha de tocar.|Tiene datos (cuánto duran las partidas, cuántos puntos) y dice qué cambiaría. Con eso el autor/a ya sabe qué número tiene que tocar." },
        { k: 'seq', ph: 'mans', q: 'Una sessió a la sala de proves. <b>Ordena els passos.</b>|Una sesión en la sala de pruebas. <b>Ordena los pasos.</b>',
          items: ["L'autor/a explica només les instruccions|El autor/a explica solo las instrucciones", 'El provador/a fa tres partides sense ajuda|El probador/a hace tres partidas sin ayuda', 'Apunta el temps, els punts i les vides de cada partida|Apunta el tiempo, los puntos y las vidas de cada partida', "Escriu l'informe: què ha passat i quin canvi proposa|Escribe el informe: qué ha pasado y qué cambio propone", "L'autor/a canvia un número i torna a mesurar|El autor/a cambia un número y vuelve a medir"],
          ex: "Primer les instruccions i les partides; després, les dades, l'informe i un sol canvi… i a tornar a mesurar.|Primero las instrucciones y las partidas; después, los datos, el informe y un solo cambio… y a volver a medir." },
        { k: 'sfree', ph: 'prova', q: "Ets a la sala de proves! La Flama ha fet «Pluja de meteorits»: mou la nau amb les fletxes i esquiva'ls. Fes <b>tres partides</b> i compta quants segons dura cadascuna.|¡Estás en la sala de pruebas! Flama ha hecho «Lluvia de meteoritos»: mueve la nave con las flechas y esquívalos. Haz <b>tres partidas</b> y cuenta cuántos segundos dura cada una.",
          w: { bg: 'espai', keys: ['left', 'right'], vars: ['vides'], sprites: [{ id: 'nau', art: 'nau', rot: 'none', x: 0, y: -130, size: 70 }, { id: 'meteorit', art: 'meteorit', x: 0, y: 170, size: 90 }] },
          prog: `@nau flag{ setv:vides,3 goto:0,-130 forever{ if:key:right{ chx:7 } if:key:left{ chx:-7 } if:touch:meteorit{ chv:vides,-1 sound:xoc wait:0.6 } if:$vides<1{ say:"Has perdut!|¡Has perdido!" stop:all } } }
            @meteorit flag{ hide forever{ clone wait:0.25 } } clone{ gotorand sety:170 show point:180 forever{ move:14 if:y<-170{ delclone } } }` },
        { k: 'quiz', ph: 'prova', q: 'Les teves tres partides a «Pluja de meteorits» han durat 3, 2 i 4 segons. Què diuen les dades?|Tus tres partidas en «Lluvia de meteoritos» han durado 3, 2 y 4 segundos. ¿Qué dicen los datos?',
          opts: ['Que és massa difícil: cal que els meteorits caiguin més a poc a poc o que en surtin menys|Que es demasiado difícil: hace falta que los meteoritos caigan más despacio o que salgan menos', 'Que és massa fàcil: cal posar-hi més meteorits|Que es demasiado fácil: hay que poner más meteoritos', 'Res: les partides curtes són mala sort|Nada: las partidas cortas son mala suerte'], a: 0,
          ex: 'Amb «mou-te 6» en lloc de «mou-te 14», o «espera 0.6» entre clons, les partides ja duren prou per esquivar.|Con «muévete 6» en lugar de «muévete 14», o «espera 0.6» entre clones, las partidas ya duran lo suficiente para esquivar.' },
        { k: 'stage', ph: 'investiga', q: "<b>Informe de prova:</b> «Tres partides: el cranc m'ha atrapat en menys de 2 segons cada vegada.» El gat fuig tot sol. Ajusta <b>la velocitat del cranc</b> perquè el gat arribi a escapar… però que el cranc es continuï movent!|<b>Informe de prueba:</b> «Tres partidas: el cangrejo me ha atrapado en menos de 2 segundos cada vez.» El gato huye solo. Ajusta <b>la velocidad del cangrejo</b> para que el gato llegue a escapar… ¡pero que el cangrejo siga moviéndose!",
          w: { bg: 'platja', time: 6, sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -110, prog: '@gat flag{ goto:-150,-110 glide:3,-150,130 glide:3,180,130 }' }, { id: 'cranc', art: 'cranc', rot: 'lr', x: 160, y: -110 }],
            goal: [{ k: 'notouch', a: 'gat', b: 'cranc' }, { k: 'moved', s: 'cranc', min: 60 }] },
          edit: ['cranc'], hats: ['flag'], pal: ['move', 'pointto', 'goto', 'forever', 'wait'],
          prog: '@cranc flag{ goto:160,-110 forever{ pointto:gat move:9 } }', sol: '@cranc flag{ goto:160,-110 forever{ pointto:gat move:2 } }',
          hint: "El número de «mou-te» és la velocitat del cranc: com més petit, més lent. Prova'n uns quants fins que el gat tingui temps d'escapar.|El número de «muévete» es la velocidad del cangrejo: cuanto más pequeño, más lento. Prueba unos cuantos hasta que el gato tenga tiempo de escapar." },
        { k: 'move', ph: 'pausa', secs: 30, t: "Fes de provador/a de videojocs: mou els polzes com si premessis les fletxes (dreta, dreta, esquerra!), salta per esquivar un meteorit imaginari i, quan acabis, fes un «m'agrada» amb el polze ben amunt!|Haz de probador/a de videojuegos: mueve los pulgares como si pulsaras las flechas (¡derecha, derecha, izquierda!), salta para esquivar un meteorito imaginario y, cuando acabes, ¡haz un «me gusta» con el pulgar bien arriba!" },
        { k: 'stage', ph: 'repte', q: "<b>Bug de l'informe:</b> «Si mantinc premuda una fletxa, el cotxe se'n va de l'escenari!» Afegeix dues regles: <b>si</b> x > 200, posa x a 200; i <b>si</b> x < −200, posa x a −200. Quan ho tinguis, toca <b>Comprova</b>.|<b>Bug del informe:</b> «¡Si mantengo pulsada una flecha, el coche se va del escenario!» Añade dos reglas: <b>si</b> x > 200, pon x a 200; y <b>si</b> x < −200, pon x a −200. Cuando lo tengas, toca <b>Comprueba</b>.",
          w: { bg: 'ciutat', keys: ['left', 'right'], time: 7, sprites: [{ id: 'cotxe', art: 'cotxe', x: 0, y: -130, size: 80 }],
            input: [{ t: .2, key: 'right', dur: 3 }, { t: 3.5, key: 'left', dur: 3.2 }],
            goal: [{ k: 'reach', s: 'cotxe', r: [150, -180, 240, 0] }, { k: 'at', s: 'cotxe', r: [-240, -180, -150, 0] }, { k: 'running', t: 6.8 }] },
          edit: ['cotxe'], hats: ['flag'], pal: ['chx', 'setx', 'forever', 'if', 'cond+'], ops: ['x'],
          prog: '@cotxe flag{ forever{ if:key:right{ chx:6 } if:key:left{ chx:-6 } } }',
          sol: '@cotxe flag{ forever{ if:key:right{ chx:6 } if:key:left{ chx:-6 } if:x>200{ setx:200 } if:x<-200{ setx:-200 } } }',
          hint: "Dins del «per sempre», afegeix un «si» amb «comparar números»: posició x > 200. A dins, «posa x a 200». Després, el mateix per a l'altra vora.|Dentro del «por siempre», añade un «si» con «comparar números»: posición x > 200. Dentro, «pon x a 200». Después, lo mismo para el otro borde." },
        { k: 'stage', ph: 'repte', q: "<b>Informe:</b> «No sabia què havia de fer!» Afegeix unes <b>instruccions</b>: en començar, en Numi ha de dir «Fes servir les fletxes!» durant 2 segons i, després, <b>enviar el missatge «som-hi»</b> perquè la pilota es posi en marxa.|<b>Informe:</b> «¡No sabía qué tenía que hacer!» Añade unas <b>instrucciones</b>: al empezar, Numi tiene que decir «¡Usa las flechas!» durante 2 segundos y, después, <b>enviar el mensaje «som-hi»</b> para que la pelota se ponga en marcha.",
          w: { bg: 'escenari', time: 4, sprites: [{ id: 'numi', art: 'numi', x: -140, y: -60, size: 90 }, { id: 'pilota', art: 'pilota', x: 120, y: 40, prog: '@pilota msg:som-hi{ point:45 forever{ move:6 bounce } }' }],
            goal: [{ k: 'said', s: 'numi', t: 'fletxes' }, { k: 'msg', m: 'som-hi' }, { k: 'moved', s: 'pilota', min: 60 }] },
          edit: ['numi'], hats: ['flag'], pal: ['say', 'wait', 'send', 'sound'], texts: ['Fes servir les fletxes!|¡Usa las flechas!', 'Recull 5 estrelles!|¡Recoge 5 estrellas!', 'Hola!|¡Hola!'], msgs: ['som-hi'],
          sol: '@numi flag{ say:"Fes servir les fletxes!|¡Usa las flechas!",2 send:som-hi }',
          hint: "Primer «digues… durant 2 segons» i, a sota, «envia el missatge som-hi». La pilota ja sap què ha de fer quan el rep.|Primero «di… durante 2 segundos» y, debajo, «envía el mensaje som-hi». La pelota ya sabe qué tiene que hacer cuando lo recibe." },
        { k: 'story', ph: 'crea', who: 'numi', title: 'Ara, la prova de veritat|Ahora, la prueba de verdad',
          t: "Toca la prova de veritat: <b>intercanvieu els ordinadors</b> amb el company/a (a casa, deixa el teu a algú de la família). Els dos passos següents són per al provador/a, que farà les partides i n'apuntarà les dades.|Toca la prueba de verdad: <b>intercambiad los ordenadores</b> con el compañero/a (en casa, deja el tuyo a alguien de la familia). Los dos pasos siguientes son para el probador/a, que hará las partidas y apuntará los datos.",
          box: "<ol><li>L'autor/a llegeix les instruccions i ja no diu res més.</li><li>El provador/a fa tres partides i apunta temps, punts i vides.</li><li>L'autor/a observa i apunta on s'encalla.</li></ol>|<ol><li>El autor/a lee las instrucciones y ya no dice nada más.</li><li>El probador/a hace tres partidas y apunta tiempo, puntos y vidas.</li><li>El autor/a observa y apunta dónde se atasca.</li></ol>" },
        { k: 'sfree', ph: 'crea', get w() { return myW([], [], 30); }, get prog() { return myP(); }, varNames: VN,
          q: "Hola, provador/a! Toca <b>Comença</b> i fes <b>tres partides</b> del videojoc del teu company/a. De cada partida, apunta en un paper quant ha durat, quants punts has fet i quantes vides et quedaven.|¡Hola, probador/a! Toca <b>Empieza</b> y haz <b>tres partidas</b> del videojuego de tu compañero/a. De cada partida, apunta en un papel cuánto ha durado, cuántos puntos has hecho y cuántas vidas te quedaban." },
        { k: 'review', ph: 'crea', q: "<b>Informe de prova.</b> Contesta a partir del que has apuntat al paper: les dades valen més que les impressions.|<b>Informe de prueba.</b> Contesta a partir de lo que has apuntado en el papel: los datos valen más que las impresiones.",
          items: [
            { q: 'Era clar què havia de fer?|¿Estaba claro qué tenía que hacer?', opts: ['Sí, des del principi|Sí, desde el principio', "Ho he entès a la segona partida|Lo he entendido en la segunda partida", "No ho he entès|No lo he entendido"] },
            { q: 'Quant duraven les partides?|¿Cuánto duraban las partidas?', opts: ['Menys de 10 segons|Menos de 10 segundos', 'Entre 10 i 60 segons|Entre 10 y 60 segundos', "Més d'un minut|Más de un minuto"] },
            { q: 'Com acabaven?|¿Cómo acababan?', opts: ['Perdia sempre|Perdía siempre', 'De vegades guanyava i de vegades perdia|A veces ganaba y a veces perdía', 'Guanyava sempre|Ganaba siempre', "No s'acabaven mai|No se acababan nunca"] },
            { q: 'Has trobat algun bug?|¿Has encontrado algún bug?', opts: ['No, cap|No, ninguno', 'Sí, un de petit|Sí, uno pequeño', 'Sí, un que espatlla la partida|Sí, uno que estropea la partida'] },
            { q: 'Quin número canviaries?|¿Qué número cambiarías?', opts: ["La velocitat de l'enemic|La velocidad del enemigo", 'Les vides del principi|Las vidas del principio', 'Els punts per guanyar|Los puntos para ganar', 'Cap: està al punt|Ninguno: está en su punto'] }
          ] },
        { k: 'story', ph: 'crea', who: 'numi', mood: 'wave', title: "L'informe, en mà|El informe, en mano",
          t: "Abans de tornar a l'ordinador, el provador/a dona el paper amb les dades de les tres partides a l'autor/a i li explica en una frase quin número canviaria i per què. Llavors, cadascú al seu ordinador.|Antes de volver al ordenador, el probador/a da el papel con los datos de las tres partidas al autor/a y le explica en una frase qué número cambiaría y por qué. Entonces, cada uno a su ordenador." },
        { k: 'screate', ph: 'crea', name: 'El meu videojoc (versió 3)|Mi videojuego (versión 3)', ...MINE,
          get w() { return myW([{ k: 'running', t: 2.5 }], IN, 2.5); }, get prog() { return myP(); },
          q: "Ja tens l'informe. <b>Ajusta el teu videojoc</b>: arregla els bugs i canvia el número que indiquen les dades. Fes un canvi cada vegada i torna-ho a provar. Quan estigui llest, toca <b>Comprova</b> i desa'l.|Ya tienes el informe. <b>Ajusta tu videojuego</b>: arregla los bugs y cambia el número que indican los datos. Haz un cambio cada vez y vuelve a probarlo. Cuando esté listo, toca <b>Comprueba</b> y guárdalo.",
          crit: ["Has fet almenys un canvi a partir de l'informe|Has hecho al menos un cambio a partir del informe", "Els bugs de l'informe estan arreglats|Los bugs del informe están arreglados", "L'has tornat a provar i les partides duren el que volies|Lo has vuelto a probar y las partidas duran lo que querías"],
          check: P => { const p = last(); return p && sig(P) === sig(p.progs) ? 'Funciona, però encara és igual que la versió que vas desar. Fes-hi almenys una millora!|Funciona, pero aún es igual que la versión que guardaste. ¡Hazle al menos una mejora!' : null; },
          sol: GAME + ` @enemic flag{ goto:20,110 forever{ pointto:heroi move:2 if:$punts>4{ bg:nit } } }`,
          hint: "Mira l'informe. Partides de pocs segons? Fes l'enemic més lent o dona més vides. Guanya sempre? Demana més punts per guanyar. Un bug? Busca el bloc que el provoca. No era clar? Afegeix-hi instruccions amb «digues».|Mira el informe. ¿Partidas de pocos segundos? Haz el enemigo más lento o da más vidas. ¿Gana siempre? Pide más puntos para ganar. ¿Un bug? Busca el bloque que lo provoca. ¿No estaba claro? Añade instrucciones con «di»." },
        { k: 'quiz', ph: 'tanca', q: 'Per què és millor canviar <b>un sol número</b> cada vegada?|¿Por qué es mejor cambiar <b>un solo número</b> cada vez?',
          opts: ['Perquè, si les dades canvien, saps quin canvi ho ha fet|Porque, si los datos cambian, sabes qué cambio lo ha hecho', "Perquè l'app només en deixa canviar un|Porque la app solo deja cambiar uno", 'Perquè els números grans no funcionen|Porque los números grandes no funcionan'], a: 0,
          ex: "Si en canvies tres alhora i millora, no sabràs quin dels tres ha servit (ni quin l'ha empitjorat).|Si cambias tres a la vez y mejora, no sabrás cuál de los tres ha servido (ni cuál lo ha empeorado)." },
        { k: 'quiz', ph: 'tanca', q: 'El provador/a ha guanyat les tres partides en menys de 10 segons. Què pots fer?|El probador/a ha ganado las tres partidas en menos de 10 segundos. ¿Qué puedes hacer?',
          opts: ["Demanar més punts per guanyar o fer l'enemic més ràpid|Pedir más puntos para ganar o hacer el enemigo más rápido", 'Esborrar-lo tot|Borrarlo todo', 'Treure-li les vides|Quitarle las vidas'], a: 0,
          ex: 'Amb «si punts > 9» en lloc de «> 4», o un número més gran a «mou-te», la partida dura més i costa més.|Con «si puntos > 9» en lugar de «> 4», o un número más grande en «muévete», la partida dura más y cuesta más.' },
        { k: 'feel', ph: 'tanca' }
      ] },

    /* ---------- Sessió 4 · Publicació i estrena ---------- */
    { id: 'g8-4', t: 'Publicació i estrena|Publicación y estreno', min: 40, proj: true, badge: 'g_u8grad',
      learn: ['Publicar és deixar el videojoc a punt per a algú que no et coneix: títol, instruccions i crèdits.|Publicar es dejar el videojuego a punto para alguien que no te conoce: título, instrucciones y créditos.',
        "A l'estrena expliques una regla del document i un canvi que vas fer gràcies a les dades.|En el estreno explicas una regla del documento y un cambio que hiciste gracias a los datos.",
        'Ja treballes com un estudi: dissenyes, construeixes per peces, proves amb dades, ajustes i publiques.|Ya trabajas como un estudio: diseñas, construyes por piezas, pruebas con datos, ajustas y publicas.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "A les proves, les partides duraven 3 segons i has baixat la velocitat de l'enemic de 9 a 4. Com saps si ha funcionat?|En las pruebas, las partidas duraban 3 segundos y has bajado la velocidad del enemigo de 9 a 4. ¿Cómo sabes si ha funcionado?",
          opts: ['Torno a fer partides i miro si ara duren més|Vuelvo a hacer partidas y miro si ahora duran más', 'No cal provar-ho: 4 és més petit que 9|No hace falta probarlo: 4 es más pequeño que 9', 'Pregunto si agrada el fons|Pregunto si gusta el fondo'], a: 0,
          ex: "Un canvi s'ha de tornar a mesurar: les dades noves diuen si ara està al punt.|Un cambio hay que volver a medirlo: los datos nuevos dicen si ahora está en su punto." },
        { k: 'story', ph: 'missio', who: 'numi', scene: 'illa', mood: 'dance', title: "L'estrena|El estreno",
          t: "Avui s'obre la <b>Fira de Videojocs</b>! Cada persona de l'estudi <b>publicarà</b> el seu videojoc a la pantalla gegant de la plaça i explicarà com l'ha fet. Al final, la Guida lliurarà els <b>diplomes</b>. Del primer actor a l'escenari a un videojoc publicat: quin camí!|¡Hoy se abre la <b>Feria de Videojuegos</b>! Cada persona del estudio <b>publicará</b> su videojuego en la pantalla gigante de la plaza y explicará cómo lo ha hecho. Al final, Guida entregará los <b>diplomas</b>. Del primer actor en el escenario a un videojuego publicado: ¡qué camino!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'El viatge|El viaje', t: 'Vuit unitats, un curs sencer|Ocho unidades, un curso entero', anim: 'g8journey',
            x: "Vas començar posant actors a l'escenari i fent-los parlar. Després vas aprendre a <b>animar</b>, a fer servir <b>tecles i missatges</b>, les <b>coordenades</b>, les <b>condicions</b>, les <b>variables</b>, l'<b>atzar</b> i els <b>clons</b>. Ara tot això és dins d'un videojoc teu, a punt per publicar.|Empezaste poniendo actores en el escenario y haciéndolos hablar. Después aprendiste a <b>animar</b>, a usar <b>teclas y mensajes</b>, las <b>coordenadas</b>, las <b>condiciones</b>, las <b>variables</b>, el <b>azar</b> y los <b>clones</b>. Ahora todo eso está dentro de un videojuego tuyo, a punto para publicar." },
          { k: 'Benvinguda|Bienvenida', t: 'La pantalla de títol|La pantalla de título', media: { k: 'stage', w: { bg: 'espai', time: 6, sprites: [{ id: 'nau', art: 'nau', rot: 'none', x: 0, y: -120, size: 70 }, { id: 'estrella', art: 'estrella', x: 0, y: 60, size: 140 }] }, prog: '@estrella flag{ size:140 show say:"La pluja de meteorits|La lluvia de meteoritos",2 say:"Esquiva\'ls amb les fletxes!|¡Esquívalos con las flechas!",2 hide send:fi } @nau msg:fi{ forever{ chx:4 bounce } }' },
            x: "Qui obre el teu videojoc per primera vegada no sap què ha de fer. Una <b>pantalla de títol</b> diu el nom i unes <b>instruccions</b> curtes (controls i objectiu) i, després, posa la partida en marxa amb un missatge.|Quien abre tu videojuego por primera vez no sabe qué tiene que hacer. Una <b>pantalla de título</b> dice el nombre y unas <b>instrucciones</b> cortas (controles y objetivo) y, después, pone la partida en marcha con un mensaje.",
            bad: 'Instruccions llarguíssimes que ningú no llegeix.|Instrucciones larguísimas que nadie lee.', good: 'El títol i una frase: què has de fer i amb quines tecles.|El título y una frase: qué tienes que hacer y con qué teclas.' },
          { k: 'Fitxa|Ficha', t: 'La fitxa de publicació|La ficha de publicación', anim: 'g8pub',
            x: "Les botigues de videojocs mostren una <b>fitxa</b> de cada videojoc: el títol, una frase de què va, els <b>controls</b>, com es guanya i es perd i els <b>crèdits</b> (qui l'ha fet i qui l'ha provat). El número de <b>versió</b> diu quantes millores porta.|Las tiendas de videojuegos muestran una <b>ficha</b> de cada videojuego: el título, una frase de qué va, los <b>controles</b>, cómo se gana y se pierde y los <b>créditos</b> (quién lo ha hecho y quién lo ha probado). El número de <b>versión</b> dice cuántas mejoras lleva." },
          { k: 'Estrena|Estreno', t: "Explica com l'has fet|Explica cómo lo has hecho", anim: 'g8who',
            x: "A l'estrena, el públic vol saber <b>com funciona per dins</b>. Ensenya una fila del document i el guió que la fa («toco el premi → punts +1») i explica <b>un canvi que vas fer gràcies a les dades</b>: «les partides duraven 3 segons; amb el cranc a 4, ara en duren 20».|En el estreno, el público quiere saber <b>cómo funciona por dentro</b>. Enseña una fila del documento y el guion que la hace («toco el premio → puntos +1») y explica <b>un cambio que hiciste gracias a los datos</b>: «las partidas duraban 3 segundos; con el cangrejo a 4, ahora duran 20».",
            tip: "Assaja-ho una vegada en veu alta amb el company/a: n'hi ha prou amb un minut.|Ensáyalo una vez en voz alta con el compañero/a: basta con un minuto." }
        ] },
        { k: 'seq', ph: 'mans', q: 'Publiques el teu videojoc. <b>Ordena les tasques</b>, de la primera a l\'última.|Publicas tu videojuego. <b>Ordena las tareas</b>, de la primera a la última.',
          items: ["Escric el títol i una frase que expliqui de què va|Escribo el título y una frase que explique de qué va", 'Poso instruccions al començament: controls i objectiu|Pongo instrucciones al principio: controles y objetivo', 'Comprovo que es pot guanyar i perdre|Compruebo que se puede ganar y perder', "Afegeixo els crèdits: qui l'ha fet i qui l'ha provat|Añado los créditos: quién lo ha hecho y quién lo ha probado", "L'estreno i deixo que algú del públic el provi|Lo estreno y dejo que alguien del público lo pruebe"],
          ex: "Primer, que s'entengui i que funcioni; després, els crèdits… i, a l'estrena, que el provi algú que no l'ha vist mai.|Primero, que se entienda y que funcione; después, los créditos… y, en el estreno, que lo pruebe alguien que no lo ha visto nunca." },
        { k: 'quiz', ph: 'prova', q: '<b>Repàs del curs.</b> Un personatge és a x: 0, y: 0 i fa «canvia x en 100». On és ara?|<b>Repaso del curso.</b> Un personaje está en x: 0, y: 0 y hace «cambia x en 100». ¿Dónde está ahora?',
          opts: ['A la dreta del centre (x: 100, y: 0)|A la derecha del centro (x: 100, y: 0)', 'A dalt del centre (x: 0, y: 100)|Encima del centro (x: 0, y: 100)', "A l'esquerra (x: −100, y: 0)|A la izquierda (x: −100, y: 0)"], a: 0,
          ex: 'La x creix cap a la dreta i la y, cap amunt.|La x crece hacia la derecha y la y, hacia arriba.' },
        { k: 'quiz', ph: 'prova', q: 'Per a què serveix el bloc «envia el missatge»?|¿Para qué sirve el bloque «envía el mensaje»?',
          opts: ['Per avisar els altres personatges perquè facin alguna cosa|Para avisar a los otros personajes para que hagan algo', 'Per escriure un text a la pantalla|Para escribir un texto en la pantalla', "Per esborrar un personatge|Para borrar un personaje"], a: 0,
          ex: 'Els personatges que tenen «Quan rebo el missatge…» comencen aquell guió quan arriba el missatge.|Los personajes que tienen «Al recibir el mensaje…» empiezan ese guion cuando llega el mensaje.' },
        { k: 'sspot', ph: 'prova', q: "<b>Repàs.</b> Cada vegada que el gat atrapa la moneda, ella salta a un lloc nou. <b>Quin bloc ho fa?</b>|<b>Repaso.</b> Cada vez que el gato atrapa la moneda, ella salta a un sitio nuevo. <b>¿Qué bloque lo hace?</b>",
          w: W_DEMO, prog: '@gat flag{ setv:punts,0 forever{ pointto:moneda move:4 } } @moneda flag{ forever{ next wait:0.1 if:touch:gat{ chv:punts,1 sound:moneda gotorand! } } }',
          ex: "«Ves a un lloc a l'atzar» tria una posició nova cada vegada que el gat toca la moneda.|«Ve a un sitio al azar» elige una posición nueva cada vez que el gato toca la moneda." },
        { k: 'quiz', ph: 'investiga', q: 'Per què sembla que el peix neda quan fa «per sempre: vestit següent, espera 0.2»?|¿Por qué parece que el pez nada cuando hace «por siempre: disfraz siguiente, espera 0.2»?',
          opts: ['Perquè canvia de dibuix ràpidament, com els fulls d\'un llibre animat|Porque cambia de dibujo rápidamente, como las hojas de un libro animado', 'Perquè es mou cap a la dreta|Porque se mueve hacia la derecha', 'Perquè fa un so|Porque hace un sonido'], a: 0,
          ex: "Una <b>animació</b> és canviar de vestit a poc a poc i sense parar: l'ull ho veu com un moviment.|Una <b>animación</b> es cambiar de disfraz poco a poco y sin parar: el ojo lo ve como un movimiento." },
        { k: 'move', ph: 'pausa', secs: 30, t: "Assaig d'estrena! Posa't dret/a, saluda el públic imaginari, digues fluixet el nom del teu videojoc i fes una reverència. Ara fes veure que tothom aplaudeix… i aplaudeix tu també!|¡Ensayo de estreno! Ponte de pie, saluda al público imaginario, di en voz baja el nombre de tu videojuego y haz una reverencia. Ahora haz como si todo el mundo aplaudiera… ¡y aplaude tú también!" },
        { k: 'stage', ph: 'repte', q: "<b>Repte de la fira: la cursa.</b> En Numi diu «3, 2, 1» i envia el missatge «som-hi». Programa el cotxe: <b>quan rebi «som-hi»</b>, ha de lliscar fins a la meta (x: 180, y: −130) i, quan hi arribi, dir «He guanyat!».|<b>Reto de la feria: la carrera.</b> Numi dice «3, 2, 1» y envía el mensaje «som-hi». Programa el coche: <b>cuando reciba «som-hi»</b>, tiene que deslizarse hasta la meta (x: 180, y: −130) y, cuando llegue, decir «¡He ganado!».",
          w: { bg: 'ciutat', time: 7, sprites: [{ id: 'numi', art: 'numi', x: -170, y: 40, size: 80, prog: '@numi flag{ say:"3|3",1 say:"2|2",1 say:"1|1",1 send:som-hi }' }, { id: 'cotxe', art: 'cotxe', x: -150, y: -130, size: 80 }, { id: 'bandera', art: 'bandera', x: 200, y: -110, size: 70 }],
            goal: [{ k: 'msg', m: 'som-hi' }, { k: 'at', s: 'cotxe', r: [150, -160, 220, -100] }, { k: 'said', s: 'cotxe', t: 'guanyat' }] },
          edit: ['cotxe'], hats: ['msg:som-hi'], msgs: ['som-hi'], pal: ['glide', 'goto', 'say', 'sound', 'next', 'wait'], texts: ['He guanyat!|¡He ganado!', 'Som-hi!|¡Vamos!'],
          sol: '@cotxe msg:som-hi{ glide:2,180,-130 say:"He guanyat!|¡He ganado!" }',
          hint: "El guió «Quan rebo el missatge som-hi» ja hi és: posa-hi «llisca en 2 s fins a x: 180 y: −130» i, a sota, «digues».|El guion «Al recibir el mensaje som-hi» ya está: pon «desliza en 2 s hasta x: 180 y: −130» y, debajo, «di»." },
        { k: 'stage', ph: 'repte', q: "<b>Repte de la fira: la papallona de la festa.</b> Fes que la papallona voli per tot l'escenari <b>rebotant a les vores</b> i <b>batent les ales</b> (vestit següent) sense parar.|<b>Reto de la feria: la mariposa de la fiesta.</b> Haz que la mariposa vuele por todo el escenario <b>rebotando en los bordes</b> y <b>batiendo las alas</b> (disfraz siguiente) sin parar.",
          w: { bg: 'cel', time: 5, sprites: [{ id: 'papallona', art: 'papallona', x: 0, y: 0, dir: 45 }], goal: [{ k: 'costumes', s: 'papallona', min: 10 }, { k: 'moved', s: 'papallona', min: 150 }, { k: 'turned', s: 'papallona' }, { k: 'running', t: 4.5 }] },
          edit: ['papallona'], hats: ['flag'], pal: ['move', 'turn', 'point', 'bounce', 'next', 'wait', 'rep', 'forever'],
          sol: '@papallona flag{ point:45 forever{ move:8 bounce next wait:0.1 } }',
          hint: "Dins d'un «per sempre»: mou-te, si toques la vora rebota, vestit següent i una espera curta.|Dentro de un «por siempre»: muévete, si tocas el borde rebota, disfraz siguiente y una espera corta." },
        { k: 'screate', ph: 'crea', name: 'El meu videojoc (versió per publicar)|Mi videojuego (versión para publicar)', ...MINE,
          get w() { return myW([{ k: 'running', t: 2.5 }], IN, 2.5); }, get prog() { return myP(); },
          q: "<b>La versió per publicar.</b> Posa-hi una <b>pantalla de títol</b>: en començar, amb «digues», el títol i les instruccions (controls i objectiu). Si vols, afegeix-hi els crèdits o un so de final. Quan estigui llest, toca <b>Comprova</b> i desa'l.|<b>La versión para publicar.</b> Ponle una <b>pantalla de título</b>: al empezar, con «di», el título y las instrucciones (controles y objetivo). Si quieres, añade los créditos o un sonido de final. Cuando esté listo, toca <b>Comprueba</b> y guárdalo.",
          crit: ['En començar, diu el títol i les instruccions|Al empezar, dice el título y las instrucciones', 'Es pot guanyar o perdre|Se puede ganar o perder', "Els crèdits diuen qui l'ha fet i qui l'ha provat|Los créditos dicen quién lo ha hecho y quién lo ha probado"],
          check: P => has(P, ['say', 'think'], 'flag') ? null : 'Funciona! Ara afegeix al guió de la bandera un «digues» amb el títol o les instruccions.|¡Funciona! Ahora añade al guion de la bandera un «di» con el título o las instrucciones.',
          sol: GAME + GAME_E,
          hint: "Al guió «Quan comença» del protagonista, just al principi, posa «digues [títol] durant 2 segons» i «digues [instruccions] durant 2 segons».|En el guion «Al empezar» del protagonista, justo al principio, pon «di [título] durante 2 segundos» y «di [instrucciones] durante 2 segundos»." },
        { k: 'sfree', ph: 'crea', get w() { return myW([], [], 30); }, get prog() { return myP(); }, varNames: VN,
          q: "<b>L'estrena!</b> Quan et toqui, publica el teu videojoc al projector: llegeix la fitxa (títol, controls, com es guanya), explica una regla i el canvi que vas fer amb les dades, i deixa que algú del públic en faci una partida.|<b>¡El estreno!</b> Cuando te toque, publica tu videojuego en el proyector: lee la ficha (título, controles, cómo se gana), explica una regla y el cambio que hiciste con los datos, y deja que alguien del público haga una partida." },
        { k: 'diploma', ph: 'tanca', skills: [
          'Crear personatges, escenes i diàlegs|Crear personajes, escenas y diálogos',
          'Animar amb vestits, esperes i bucles|Animar con disfraces, esperas y bucles',
          'Programar tecles, tocs i missatges|Programar teclas, toques y mensajes',
          'Moure personatges amb coordenades|Mover personajes con coordenadas',
          'Decidir amb condicions: «si… si no…»|Decidir con condiciones: «si… si no…»',
          'Comptar punts, vides i temps amb variables|Contar puntos, vidas y tiempo con variables',
          "Fer servir l'atzar i els clons|Usar el azar y los clones",
          'Dissenyar, construir, provar amb dades i publicar un videojoc propi|Diseñar, construir, probar con datos y publicar un videojuego propio'] },
        { k: 'story', ph: 'tanca', who: 'numi', mood: 'win', t: "Enhorabona, creador/a! Has acabat Tech Creadors i el teu videojoc ja és públic. Durant el curs has après a treballar com un estudi: una idea es dissenya, es construeix per peces, es mesura i es millora. Aquest mètode et servirà per a qualsevol projecte: un videojoc, una animació o una història.|¡Enhorabuena, creador/a! Has terminado Tech Creadores y tu videojuego ya es público. Durante el curso has aprendido a trabajar como un estudio: una idea se diseña, se construye por piezas, se mide y se mejora. Este método te servirá para cualquier proyecto: un videojuego, una animación o una historia." },
        { k: 'quiz', ph: 'tanca', q: "Ja l'has publicat i algú t'avisa: «Si mantinc premuda una fletxa, la nau surt de l'escenari.» Què fas?|Ya lo has publicado y alguien te avisa: «Si mantengo pulsada una flecha, la nave sale del escenario.» ¿Qué haces?",
          opts: ['Ho provo fins que em passa, busco el bloc que falla, l\'arreglo i publico una versió nova|Lo pruebo hasta que me pasa, busco el bloque que falla, lo arreglo y publico una versión nueva', 'Res: ja està publicat|Nada: ya está publicado', "L'esborro i en començo un altre|Lo borro y empiezo otro"], a: 0,
          ex: 'Els estudis publiquen versions noves (1.1, 1.2…) quan algú troba un bug. Trobar-ne després de publicar és normal; el que compta és saber-lo arreglar.|Los estudios publican versiones nuevas (1.1, 1.2…) cuando alguien encuentra un bug. Encontrarlos después de publicar es normal; lo que cuenta es saber arreglarlo.' },
        { k: 'feel', ph: 'tanca' }
      ] }
  ] };
})();
