/* Tech Creadors · unitat 8 «El meu videojoc» (g8-1 … g8-4) · projecte final del curs
   Cada alumne/a tria les peces del seu videojoc (g8-1, pas «review»: protagonista, premi, enemic i fons), en fa una
   primera versió i la desa al portafoli. Les sessions següents continuen sempre des de l'última versió desada
   (g8-2 la construeix, g8-3 la prova un company/a i es millora, g8-4 es presenta). Els personatges del videojoc tenen
   sempre els mateixos ids (heroi, premi, enemic): així les solucions de prova funcionen amb qualsevol tria. */
Object.assign(TBADGE, {
  g_u8idea: { id: 'g_u8idea', ico: '💡', n: 'Inventor/a de videojocs|Inventor/a de videojuegos', d: 'Has pensat la idea i el pla del teu propi videojoc.|Has pensado la idea y el plan de tu propio videojuego.' },
  g_u8build: { id: 'g_u8build', ico: '🛠️', n: 'Constructor/a de videojocs|Constructor/a de videojuegos', d: 'Has construït el teu videojoc peça a peça.|Has construido tu videojuego pieza a pieza.' },
  g_u8prova: { id: 'g_u8prova', ico: '🤝', n: 'Provador/a amable|Probador/a amable', d: "Has provat el videojoc d'un company/a i li has donat comentaris amables i útils.|Has probado el videojuego de un compañero/a y le has dado comentarios amables y útiles." },
  g_u8grad: { id: 'g_u8grad', ico: '🎓', n: 'Creador/a de videojocs|Creador/a de videojuegos', d: 'Has acabat el curs Tech Creadors i has presentat el teu videojoc.|Has terminado el curso Tech Creadores y has presentado tu videojuego.' }
});
COURSE_UNITS[8] = (() => {
  /* ---------- El videojoc de l'alumne/a ---------- */
  const HER = [['numi', 'lr'], ['gat', 'lr'], ['nau', 'none'], ['peix', 'lr'], ['drac', 'lr'], ['ocell', 'lr'], ['gos', 'lr'], ['guineu', 'lr']];
  const PRE = ['moneda', 'estrella', 'poma', 'cor', 'regal', 'platan', 'diamant', 'maduixa'];
  const ENE = [['meteorit', 'all'], ['cranc', 'lr'], ['medusa', 'none'], ['roca', 'none'], ['pilota', 'all'], ['cocodril', 'lr'], ['foc', 'none'], ['llamp', 'none']];
  const FONS = ['espai', 'aquari', 'bosc', 'ciutat', 'platja', 'parc', 'nit', 'laberint'];
  const ALLBG = [...FONS, 'cel', 'escenari'];
  const ts = () => { try { return typeof TS_ === 'function' ? TS_() : null; } catch (e) { return null; } };
  // les peces triades a g8-1 (respostes del pas «review»); si encara no n'hi ha, unes de mostra
  const kit = () => { const t = ts(), r = t && t.rev && t.rev['g8-1'], a = (r && Array.isArray(r.a)) ? r.a : []; const g = (i, n) => (Number.isInteger(a[i]) && a[i] >= 0 && a[i] < n ? a[i] : 0); return [g(0, HER.length), g(1, PRE.length), g(2, ENE.length), g(3, FONS.length)]; };
  const kitW = () => { const [h, p, e, f] = kit(); return { bg: FONS[f], bgs: ALLBG, vars: ['punts', 'vides'], keys: ['left', 'right', 'up', 'down', 'space'],
    sprites: [{ id: 'heroi', art: HER[h][0], rot: HER[h][1], x: -170, y: -110, size: 70 }, { id: 'premi', art: PRE[p], x: 150, y: 80, size: 80 }, { id: 'enemic', art: ENE[e][0], rot: ENE[e][1], x: 20, y: 110, size: 80 }] }; };
  // l'última versió desada del videojoc (portafoli)
  const last = () => { const t = ts(); if (!t || !Array.isArray(t.port)) return null; for (let i = t.port.length - 1; i >= 0; i--) { const p = t.port[i]; if (p && p.kind === 'stage' && /^g8-/.test(p.sid || '') && p.w && p.progs && (p.w.sprites || []).some(s => s.id === 'heroi')) return p; } return null; };
  const myW = (goal, input, time, fresh) => { const p = fresh ? null : last(), w = p ? p.w : kitW(); return { ...w, sprites: (w.sprites || []).map(s => ({ ...s })), goal, input, time }; };
  const myP = () => { const p = last(); return p ? p.progs : undefined; };
  const ED = ['heroi', 'premi', 'enemic'];
  const flat = l => (l || []).flatMap(b => [b, ...flat(Array.isArray(b.b) ? b.b : []), ...flat(b.e)]);
  const blocks = (P, hat) => ED.flatMap(id => Object.entries((P && P[id]) || {}).filter(([h]) => !hat || h === hat).flatMap(([, scr]) => (scr || []).flatMap(flat)));
  const has = (P, ks, hat) => blocks(P, hat).some(b => ks.includes(b.k));
  const nProg = P => ED.filter(id => Object.values((P && P[id]) || {}).some(scr => (scr || []).some(l => l && l.length))).length;
  const sig = P => JSON.stringify(ED.map(id => Object.entries((P && P[id]) || {}).map(([h, scr]) => [h, (scr || []).filter(l => l && l.length)]).filter(x => x[1].length).sort((a, b) => a[0] < b[0] ? -1 : 1)), (k, v) => k === '_id' ? undefined : v);
  const IN = [{ t: .1, mouse: [80, 40] }, { t: .2, key: 'right', dur: .5 }, { t: .5, click: 'heroi' }, { t: .8, key: 'left', dur: .4 }, { t: 1.3, key: 'up', dur: .3 }, { t: 1.7, key: 'down', dur: .3 }, { t: 2.1, key: 'space', dur: .2 }];
  const PAL = ['move', 'turn', 'goto', 'gotorand', 'glide', 'setx', 'sety', 'chx', 'chy', 'point', 'pointto', 'bounce', 'say', 'think', 'costume', 'next', 'size', 'chsize', 'show', 'hide', 'ghost', 'front', 'bg', 'nextbg', 'sound', 'send', 'wait', 'rep', 'forever', 'until', 'waitu', 'stop', 'clone', 'delclone', 'if', 'else', 'and', 'setv', 'chv', 'timer0', 'cond+'];
  const HATS = ['flag', 'key:left', 'key:right', 'key:up', 'key:down', 'key:space', 'click', 'clone', 'msg:fi'];
  const VN = { punts: 'punts|puntos', vides: 'vides|vidas' };
  const TXT = ['Has guanyat!|¡Has ganado!', 'Has perdut!|¡Has perdido!', 'Ai!|¡Ay!', 'Som-hi!|¡Vamos!', 'Nivell 2!|¡Nivel 2!', 'Fes servir les fletxes!|¡Usa las flechas!'];
  const MINE = { edit: ED, hats: HATS, pal: PAL, ops: ['x', 'y', 'rnd', 'timer', 'mx', 'my'], texts: TXT, msgs: ['fi'], varNames: VN };
  // una solució de prova: un videojoc complet de recollir i esquivar (funciona amb totes les peces)
  const GAME = `@heroi flag{ setv:punts,0 setv:vides,3 goto:-170,-110 say:"Recull 10 premis!|¡Recoge 10 premios!",1 forever{ if:key:right{ chx:6 } if:key:left{ chx:-6 } if:key:up{ chy:6 } if:key:down{ chy:-6 } if:touch:enemic{ chv:vides,-1 sound:xoc goto:-170,-110 wait:0.5 } if:$vides<1{ say:"Has perdut!|¡Has perdido!" stop:all } if:$punts>9{ say:"Has guanyat!|¡Has ganado!" stop:all } } }
    @premi flag{ forever{ if:touch:heroi{ chv:punts,1 sound:moneda gotorand } } }`;
  const GAME_E = ` @enemic flag{ goto:20,110 forever{ pointto:heroi move:2 } }`;
  // miniatures per triar les peces
  const th = svg => `<span class="sthumb" style="margin:0 auto 6px">${svg}</span>`;
  const pickArt = (a) => () => th(sgCostume(a, 0)) + tx(STG_ART[a].name);
  const pickBg = (b) => () => th(STG_BG[b].svg()) + tx(STG_BG[b].name);

  /* ---------- Mons dels reptes ---------- */
  const W_DEMO = { bg: 'parc', sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -60 }, { id: 'moneda', art: 'moneda', x: 120, y: 60 }], vars: ['punts'], time: 9 };
  const P_DEMO = '@gat flag{ setv:punts,0 forever{ pointto:moneda move:4 } } @moneda flag{ forever{ next wait:0.1 if:touch:gat{ chv:punts,1 sound:moneda gotorand } } }';
  const W_BOSC = { bg: 'bosc', keys: ['left', 'right'], vars: ['punts', 'vides'], sprites: [{ id: 'numi', art: 'numi', rot: 'lr', x: -160, y: -100, size: 80 }, { id: 'estrella', art: 'estrella', x: 100, y: 60 }, { id: 'roca', art: 'roca', x: 160, y: -100 }] };
  const P_BOSC = `@numi flag{ setv:punts,0 setv:vides,3 setx:-160 sety:-100 forever{ if:key:right{ chx:6 } if:key:left{ chx:-6 } if:touch:roca{ chv:vides,-1 setx:-160 wait:0.5 } if:$vides<1!{ say:"Has perdut!|¡Has perdido!" stop:all } } }
    @estrella flag{ forever{ if:touch:numi{ chv:punts,1 sound:moneda gotorand } } } @roca flag{ forever{ rep:40{ chx:-5 } rep:40{ chx:5 } } }`;
  const W_VUIT = { bg: 'nit', keys: ['left', 'right', 'up', 'down'], vars: ['punts'], sprites: [{ id: 'vuit', art: 'vuit', rot: 'lr', x: -150, y: -80, size: 80 }, { id: 'estrella', art: 'estrella', x: 120, y: 80 }] };
  const P_VUIT = '@vuit flag{ setv:punts,0 goto:-150,-80 } key:right{ chx:15 } key:left{ chx:-15 } key:up{ chy:15 } key:down{ chy:-15 } @estrella flag{ forever{ if:touch:vuit{ chv:punts,1 sound:moneda gotorand } } }';

  return { t: 'El meu videojoc|Mi videojuego', d: 'Projecte final: idea, construcció, proves i presentació|Proyecto final: idea, construcción, pruebas y presentación', color: '#C2410C', s: [
    /* ---------- Sessió 1 · La idea i el pla ---------- */
    { id: 'g8-1', t: 'La idea i el pla|La idea y el plan', min: 45, badge: 'g_u8idea',
      learn: ['Un videojoc té quatre peces: protagonista, objectiu, obstacle i regles.|Un videojuego tiene cuatro piezas: protagonista, objetivo, obstáculo y reglas.',
        'Cada regla és un «si…» amb una variable: si toca la moneda, suma 1 punt.|Cada regla es un «si…» con una variable: si toca la moneda, suma 1 punto.',
        'Primer es fa el pla en paper i una versió petita; després, més peces.|Primero se hace el plan en papel y una versión pequeña; después, más piezas.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "Comencem l'última unitat! Recordes quin bloc fa que un meteorit surti <b>cada vegada en un lloc diferent</b>?|¡Empezamos la última unidad! ¿Recuerdas qué bloque hace que un meteorito salga <b>cada vez en un sitio diferente</b>?",
          opts: ["Ves a un lloc a l'atzar|Ve a un sitio al azar", 'Ves a x: 0 y: 0|Ve a x: 0 y: 0', 'Espera 1 segons|Espera 1 segundos'], a: 0,
          ex: "Amb l'<b>atzar</b>, el programa tria un lloc nou cada vegada: així el videojoc sorprèn.|Con el <b>azar</b>, el programa elige un sitio nuevo cada vez: así el videojuego sorprende." },
        { k: 'quiz', ph: 'recorda', q: 'Tens <b>3 vides</b> i un enemic et toca. Quin bloc fas servir perquè en perdis una?|Tienes <b>3 vidas</b> y un enemigo te toca. ¿Qué bloque usas para perder una?',
          opts: ['Suma a vides −1|Suma a vidas −1', 'Posa vides a 3|Pon vidas a 3', 'Suma a punts 1|Suma a puntos 1'], a: 0,
          ex: 'Sumar −1 és el mateix que restar 1: de 3 vides en queden 2.|Sumar −1 es lo mismo que restar 1: de 3 vidas quedan 2.' },
        { k: 'story', ph: 'missio', who: 'both', scene: 'taller', title: 'La Fira de Videojocs|La Feria de Videojuegos',
          t: "Gran notícia a l'illa: d'aquí a quatre setmanes se celebra la <b>Fira de Videojocs</b>! A la plaça hi haurà una pantalla gegant i cada creador/a hi presentarà <b>un videojoc inventat per ell o ella</b>. I tu també hi seràs!|¡Gran noticia en la isla: dentro de cuatro semanas se celebra la <b>Feria de Videojuegos</b>! En la plaza habrá una pantalla gigante y cada creador/a presentará <b>un videojuego inventado por él o ella</b>. ¡Y tú también estarás!" },
        { k: 'story', ph: 'missio', who: 'bit', mood: 'happy', title: 'El pla de les quatre setmanes|El plan de las cuatro semanas',
          t: 'BIP BIP! Ja saps fer totes les peces: personatges que es mouen, bucles, tecles, coordenades, condicions, variables, atzar i clons. Ara les ajuntaràs en un videojoc teu!|¡BIP BIP! Ya sabes hacer todas las piezas: personajes que se mueven, bucles, teclas, coordenadas, condiciones, variables, azar y clones. ¡Ahora las juntarás en un videojuego tuyo!',
          box: '<ol><li><b>Avui:</b> la idea i el pla.</li><li><b>Setmana 2:</b> el construeixes.</li><li><b>Setmana 3:</b> el prova un company/a i el millores.</li><li><b>Setmana 4:</b> el presentes a la fira.</li></ol>|<ol><li><b>Hoy:</b> la idea y el plan.</li><li><b>Semana 2:</b> lo construyes.</li><li><b>Semana 3:</b> lo prueba un compañero/a y lo mejoras.</li><li><b>Semana 4:</b> lo presentas en la feria.</li></ol>' },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Les peces|Las piezas', t: "Les quatre peces d'un videojoc|Las cuatro piezas de un videojuego", anim: 'g8parts',
            x: "Un videojoc té quatre peces: un <b>protagonista</b> que controles, un <b>objectiu</b> (què has d'aconseguir), un <b>obstacle</b> (què t'ho posa difícil) i unes <b>regles</b> (què passa quan…). Si en falta una, el videojoc no funciona bé: sense obstacle és massa fàcil i sense objectiu no se sap què cal fer.|Un videojuego tiene cuatro piezas: un <b>protagonista</b> que controlas, un <b>objetivo</b> (qué tienes que conseguir), un <b>obstáculo</b> (qué te lo pone difícil) y unas <b>reglas</b> (qué pasa cuando…). Si falta una, el videojuego no funciona bien: sin obstáculo es demasiado fácil y sin objetivo no se sabe qué hay que hacer." },
          { k: 'Regles|Reglas', t: 'Cada regla és un «si…»|Cada regla es un «si…»', media: { k: 'stage', w: W_DEMO, prog: P_DEMO, varNames: { punts: 'punts|puntos' } },
            x: "En aquest videojoc petit, el gat persegueix la moneda. La regla és: <b>si</b> el gat toca la moneda → <b>suma 1</b> als punts i la moneda salta a un lloc <b>a l'atzar</b>. Ja coneixes totes aquestes eines: una condició, una variable i l'atzar!|En este videojuego pequeño, el gato persigue la moneda. La regla es: <b>si</b> el gato toca la moneda → <b>suma 1</b> a los puntos y la moneda salta a un sitio <b>al azar</b>. ¡Ya conoces todas estas herramientas: una condición, una variable y el azar!" },
          { k: 'Guanyar i perdre|Ganar y perder', t: "Com s'acaba?|¿Cómo se termina?", anim: 'g8win',
            x: "Un bon videojoc diu clarament com guanyes i com perds. Per exemple: <b>si punts = 10</b> → «Has guanyat!»; <b>si vides = 0</b> → «Has perdut!». En tots dos casos, el bloc «<b>atura tot</b>» acaba el programa.|Un buen videojuego dice claramente cómo ganas y cómo pierdes. Por ejemplo: <b>si puntos = 10</b> → «¡Has ganado!»; <b>si vidas = 0</b> → «¡Has perdido!». En los dos casos, el bloque «<b>para todo</b>» termina el programa.",
            tip: 'També pots guanyar arribant a una bandera o aguantant fins que el cronòmetre arriba a 30.|También puedes ganar llegando a una bandera o aguantando hasta que el cronómetro llega a 30.' },
          { k: 'El pla|El plan', t: 'Primer, en paper|Primero, en papel', anim: 'g8plan',
            x: "Abans de programar, fes un <span class='hl'>esbós</span>: dibuixa l'escenari i on comença cada personatge. Al costat, escriu les regles amb paraules: «fletxes: moure», «estrella: +1 punt». Després, cada regla es convertirà en uns quants blocs.|Antes de programar, haz un <span class='hl'>boceto</span>: dibuja el escenario y dónde empieza cada personaje. Al lado, escribe las reglas con palabras: «flechas: mover», «estrella: +1 punto». Después, cada regla se convertirá en unos cuantos bloques." },
          { k: 'Compte!|¡Cuidado!', t: 'Comença petit|Empieza pequeño', anim: 'g8small',
            x: 'Els creadors de videojocs no ho fan tot de cop. Primer fan una <b>versió 1</b> molt petita que funcioni (el protagonista es mou), la proven i després hi afegeixen peces: estrelles i punts, un enemic i vides, nivells…|Los creadores de videojuegos no lo hacen todo de golpe. Primero hacen una <b>versión 1</b> muy pequeña que funcione (el protagonista se mueve), la prueban y después le añaden piezas: estrellas y puntos, un enemigo y vidas, niveles…',
            bad: 'Ho vull tot de cop: deu nivells i vint enemics.|Lo quiero todo de golpe: diez niveles y veinte enemigos.', good: 'Primer una versió petita que funcioni; després, més peces.|Primero una versión pequeña que funcione; después, más piezas.' }
        ] },
        { k: 'quiz', ph: 'mans', q: 'Quina d\'aquestes frases és una <b>regla</b> que es pot programar?|¿Cuál de estas frases es una <b>regla</b> que se puede programar?',
          opts: ['Si el gat toca la moneda, suma 1 punt.|Si el gato toca la moneda, suma 1 punto.', 'El gat és molt simpàtic.|El gato es muy simpático.', 'El videojoc ha de ser divertit.|El videojuego tiene que ser divertido.'], a: 0,
          ex: "Una regla diu <b>quan</b> passa alguna cosa i <b>què</b> passa: «si… → …». Això es converteix en un bloc «si» amb blocs a dins.|Una regla dice <b>cuándo</b> pasa algo y <b>qué</b> pasa: «si… → …». Eso se convierte en un bloque «si» con bloques dentro." },
        { k: 'seq', ph: 'mans', q: 'Com es crea un videojoc? <b>Ordena els passos.</b>|¿Cómo se crea un videojuego? <b>Ordena los pasos.</b>',
          items: ['Penso una idea: qui és el protagonista i què ha de fer?|Pienso una idea: ¿quién es el protagonista y qué tiene que hacer?', 'Dibuixo el pla en paper i escric les regles|Dibujo el plan en papel y escribo las reglas', 'Programo una versió petita que funcioni|Programo una versión pequeña que funcione', 'La provo i hi afegeixo més peces|La pruebo y le añado más piezas', 'La presento a la fira|La presento en la feria'],
          ex: 'Pensar, planificar, programar petit, provar i millorar… i, al final, presentar-lo!|Pensar, planificar, programar pequeño, probar y mejorar… ¡y, al final, presentarlo!' },
        { k: 'unplug', ph: 'mans', ico: '✂️', title: 'Un videojoc de paper|Un videojuego de papel', t: 'Amb algú de casa, feu una versió de paper del teu videojoc.|Con alguien de casa, haced una versión de papel de tu videojuego.',
          steps: ["Dibuixa l'escenari en un full i retalla el protagonista, el premi i l'enemic en paper.|Dibuja el escenario en una hoja y recorta el protagonista, el premio y el enemigo en papel.",
            'Escriu les regles en un altre full: «si toca el premi → +1 punt», «si toca l\'enemic → −1 vida».|Escribe las reglas en otra hoja: «si toca el premio → +1 punto», «si toca el enemigo → −1 vida».',
            "L'altra persona mou el protagonista amb el dit i tu mous l'enemic i apuntes els punts i les vides.|La otra persona mueve el protagonista con el dedo y tú mueves el enemigo y apuntas los puntos y las vidas.",
            "Les regles s'entenien? Hi havia una manera de guanyar i una de perdre? Canvieu el que calgui.|¿Se entendían las reglas? ¿Había una manera de ganar y una de perder? Cambiad lo que haga falta."],
          tip: 'Si una regla costa d\'explicar, segurament també costarà de programar: fes-la més senzilla.|Si una regla cuesta de explicar, seguramente también costará de programar: hazla más sencilla.' },
        { k: 'sspot', ph: 'prova', q: "Aquest és el videojoc «En Numi i la roca». Pots provar-lo amb les fletxes. Ara mira els guions d'en Numi i <b>toca el bloc que fa que es pugui perdre</b>.|Este es el videojuego «Numi y la roca». Puedes probarlo con las flechas. Ahora mira los guiones de Numi y <b>toca el bloque que hace que se pueda perder</b>.",
          w: W_BOSC, prog: P_BOSC,
          ex: "És el «si vides < 1»: quan ja no queden vides, en Numi diu «Has perdut!» i s'atura tot.|Es el «si vidas < 1»: cuando ya no quedan vidas, Numi dice «¡Has perdido!» y se para todo." },
        { k: 'sfree', ph: 'investiga', q: "En Vuit ha fet aquest videojoc: recull estrelles amb les fletxes. <b>Prova'l</b> una estona (toca Comença i fes servir les fletxes) i fixa't bé en què passa.|Vuit ha hecho este videojuego: recoge estrellas con las flechas. <b>Pruébalo</b> un rato (toca Empieza y usa las flechas) y fíjate bien en qué pasa.",
          w: W_VUIT, prog: P_VUIT },
        { k: 'quiz', ph: 'investiga', q: "Què li falta al videojoc d'en Vuit?|¿Qué le falta al videojuego de Vuit?",
          opts: ["Un obstacle i una manera de guanyar o de perdre: ara els punts pugen i pugen i no s'acaba mai|Un obstáculo y una manera de ganar o de perder: ahora los puntos suben y suben y no se termina nunca", 'Més colors al fons|Más colores en el fondo', 'Que en Vuit parli més|Que Vuit hable más'], a: 0,
          ex: "Té protagonista i objectiu, però cap obstacle ni cap final. Amb un enemic i una regla «si punts = 10 → Has guanyat!» ja seria un videojoc complet.|Tiene protagonista y objetivo, pero ningún obstáculo ni ningún final. Con un enemigo y una regla «si puntos = 10 → ¡Has ganado!» ya sería un videojuego completo." },
        { k: 'move', ph: 'pausa', secs: 30, t: "Fes de protagonista! Posa't dret/a: quan diguis «dreta», salta cap a la dreta; «esquerra», cap a l'esquerra. Ui, un meteorit! <b>Ajup-te</b> ràpid. I ara una estrella: <b>salta</b> amb els braços amunt i crida «+1»!|¡Haz de protagonista! Ponte de pie: cuando digas «derecha», salta hacia la derecha; «izquierda», hacia la izquierda. ¡Uy, un meteorito! <b>Agáchate</b> rápido. Y ahora una estrella: <b>salta</b> con los brazos arriba y grita «+1»!" },
        { k: 'stage', ph: 'repte', q: "<b>La regla de recollir.</b> L'ocell vola sol cap a l'estrella. Programa l'estrella: <b>si</b> toca l'ocell, suma 1 als punts i salta a un lloc a l'atzar. Ha de passar <b>moltes vegades</b>!|<b>La regla de recoger.</b> El pájaro vuela solo hacia la estrella. Programa la estrella: <b>si</b> toca el pájaro, suma 1 a los puntos y salta a un sitio al azar. ¡Tiene que pasar <b>muchas veces</b>!",
          w: { bg: 'cel', vars: ['punts'], time: 6, sprites: [{ id: 'ocell', art: 'ocell', rot: 'lr', x: -160, y: 40, prog: '@ocell flag{ forever{ pointto:estrella move:5 } }' }, { id: 'estrella', art: 'estrella', x: 120, y: 60 }],
            goal: [{ k: 'var', v: 'punts', min: 3, max: 40 }, { k: 'running', t: 5.5 }] },
          edit: ['estrella'], hats: ['flag'], pal: ['forever', 'if', 'setv', 'chv', 'gotorand', 'goto', 'wait', 'sound'], varNames: { punts: 'punts|puntos' },
          sol: '@estrella flag{ setv:punts,0 forever{ if:touch:ocell{ chv:punts,1 gotorand } } }',
          hint: "Necessites un «per sempre» amb un «si toca l'ocell» a dins. Si l'estrella no se'n va a un altre lloc, els punts pugen sense parar!|Necesitas un «por siempre» con un «si toca el pájaro» dentro. Si la estrella no se va a otro sitio, ¡los puntos suben sin parar!" },
        { k: 'stage', ph: 'repte', q: "<b>La regla de perdre una vida.</b> La medusa baixa i puja sense parar. Programa la tortuga: comença amb <b>3 vides</b> i, <b>si</b> toca la medusa, en perd <b>una</b>. Compte: una sola vida per cada xoc!|<b>La regla de perder una vida.</b> La medusa baja y sube sin parar. Programa la tortuga: empieza con <b>3 vidas</b> y, <b>si</b> toca la medusa, pierde <b>una</b>. Cuidado: ¡una sola vida por cada choque!",
          w: { bg: 'aquari', vars: ['vides'], time: 4.5, sprites: [{ id: 'tuga', art: 'tuga', rot: 'lr', x: 0, y: -90, size: 90 }, { id: 'medusa', art: 'medusa', x: 0, y: 120, prog: '@medusa flag{ forever{ glide:1,0,-90 glide:1,0,120 } }' }],
            goal: [{ k: 'touched', a: 'tuga', b: 'medusa' }, { k: 'var', v: 'vides', min: 1, max: 2 }, { k: 'running', t: 4.2 }] },
          edit: ['tuga'], hats: ['flag'], pal: ['forever', 'if', 'setv', 'chv', 'wait', 'say', 'sound'], varNames: { vides: 'vides|vidas' },
          sol: '@tuga flag{ setv:vides,3 forever{ if:touch:medusa{ chv:vides,-1 sound:xoc wait:1 } } }',
          hint: "Després de perdre una vida, espera una mica perquè la medusa tingui temps d'allunyar-se. Si no, cada instant que es toquen compta com un xoc nou!|Después de perder una vida, espera un poco para que la medusa tenga tiempo de alejarse. Si no, ¡cada instante que se tocan cuenta como un choque nuevo!" },
        { k: 'stage', ph: 'repte', q: "<b>La regla de guanyar.</b> El gat ja persegueix monedes i la moneda compta els punts. Afegeix al guió del gat una regla nova: <b>si</b> els punts arriben a <b>5</b>, digues «Has guanyat!» i <b>atura-ho tot</b>.|<b>La regla de ganar.</b> El gato ya persigue monedas y la moneda cuenta los puntos. Añade al guion del gato una regla nueva: <b>si</b> los puntos llegan a <b>5</b>, di «¡Has ganado!» y <b>páralo todo</b>.",
          w: { bg: 'parc', vars: ['punts'], time: 14, sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -80 }, { id: 'moneda', art: 'moneda', x: 120, y: 60, prog: '@moneda flag{ setv:punts,0 forever{ next wait:0.05 if:touch:gat{ chv:punts,1 sound:moneda gotorand } } }' }],
            goal: [{ k: 'var', v: 'punts', min: 5 }, { k: 'said', s: 'gat', t: 'guanyat' }, { k: 'stopped' }] },
          edit: ['gat'], hats: ['flag'], pal: ['move', 'pointto', 'forever', 'if', 'say', 'stop', 'wait', 'cond+'], texts: ['Has guanyat!|¡Has ganado!', 'Has perdut!|¡Has perdido!'], varNames: { punts: 'punts|puntos' },
          prog: '@gat flag{ forever{ pointto:moneda move:6 } }',
          sol: '@gat flag{ forever{ pointto:moneda move:6 if:$punts>4{ say:"Has guanyat!|¡Has ganado!" stop:all } } }',
          hint: "Posa un «si» dins del «per sempre», a sota de «mou-te». Toca la condició i tria «comparar números»: punts > 4 vol dir que ja en tens 5 (també pots triar ≥ i posar-hi un 5).|Pon un «si» dentro del «por siempre», debajo de «muévete». Toca la condición y elige «comparar números»: puntos > 4 quiere decir que ya tienes 5 (también puedes elegir ≥ y poner un 5)." },
        { k: 'review', ph: 'crea', who: 'bit', btn: 'Desa les peces|Guarda las piezas', q: "<b>Ara, el teu videojoc!</b> Tria les peces que has pensat al teu pla. Quan les tinguis totes, toca el botó de baix per desar-les: les faràs servir les setmanes que vénen.|<b>¡Ahora, tu videojuego!</b> Elige las piezas que has pensado en tu plan. Cuando las tengas todas, toca el botón de abajo para guardarlas: las usarás las próximas semanas.",
          items: [
            { q: 'Qui és el protagonista?|¿Quién es el protagonista?', opts: HER.map(([a]) => pickArt(a)) },
            { q: 'Què ha de recollir?|¿Qué tiene que recoger?', opts: PRE.map(pickArt) },
            { q: "Què l'atrapa o què ha d'esquivar?|¿Qué lo atrapa o qué tiene que esquivar?", opts: ENE.map(([a]) => pickArt(a)) },
            { q: 'On passa?|¿Dónde pasa?', opts: FONS.map(pickBg) }
          ] },
        { k: 'screate', ph: 'crea', name: 'El meu videojoc (versió 1)|Mi videojuego (versión 1)', ...MINE, hats: ['flag', 'key:left', 'key:right', 'key:up', 'key:down', 'key:space', 'click'],
          get w() { return myW([{ k: 'moved', s: 'heroi', min: 20 }, { k: 'said', s: 'heroi' }], [...IN, { t: 2.5, key: 'right', dur: .6 }, { t: 3.2, key: 'left', dur: .5 }], 4, true); },
          q: "<b>La versió 1 del teu videojoc.</b> Aquí tens les peces que has triat. Fes que el protagonista <b>es mogui amb les fletxes</b> i que, en començar, <b>digui el nom del teu videojoc</b>. Prova'l amb Comença i, quan funcioni, toca <b>Comprova</b> i desa'l.|<b>La versión 1 de tu videojuego.</b> Aquí tienes las piezas que has elegido. Haz que el protagonista <b>se mueva con las flechas</b> y que, al empezar, <b>diga el nombre de tu videojuego</b>. Pruébalo con Empieza y, cuando funcione, toca <b>Comprueba</b> y guárdalo.",
          crit: ['El protagonista es mou amb les fletxes|El protagonista se mueve con las flechas', 'En començar, diu el nom del videojoc|Al empezar, dice el nombre del videojuego', 'Si vols, ja pots posar-hi alguna regla del teu pla|Si quieres, ya puedes poner alguna regla de tu plan'],
          sol: '@heroi flag{ say:"La gran aventura|La gran aventura",2 } key:right{ chx:10 } key:left{ chx:-10 } key:up{ chy:10 } key:down{ chy:-10 }',
          hint: "Fes servir els guions «Quan premo la tecla…»: un per a cada fletxa, amb «canvia x en» o «canvia y en». El nom, amb «digues» al guió de la bandera.|Usa los guiones «Al pulsar la tecla…»: uno para cada flecha, con «cambia x en» o «cambia y en». El nombre, con «di» en el guion de la bandera." },
        { k: 'quiz', ph: 'tanca', q: 'Per què és bona idea fer el pla en paper abans de programar?|¿Por qué es buena idea hacer el plan en papel antes de programar?',
          opts: ['Per pensar la idea i les regles abans de posar blocs|Para pensar la idea y las reglas antes de poner bloques', "Perquè l'ordinador no funciona sense paper|Porque el ordenador no funciona sin papel", 'Per fer-lo més llarg|Para hacerlo más largo'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Quina peça li falta a un videojoc on el protagonista recull estrelles però <b>res no l\'hi posa difícil</b>?|¿Qué pieza le falta a un videojuego donde el protagonista recoge estrellas pero <b>nada se lo pone difícil</b>?',
          opts: ['Un obstacle|Un obstáculo', 'Un protagonista|Un protagonista', 'Un objectiu|Un objetivo'], a: 0,
          ex: 'Sense obstacle és massa fàcil. Un enemic, un meteorit o un cronòmetre el fan més emocionant.|Sin obstáculo es demasiado fácil. Un enemigo, un meteorito o un cronómetro lo hacen más emocionante.' },
        { k: 'feel', ph: 'tanca' }
      ] },

    /* ---------- Sessió 2 · Construeix-lo peça a peça ---------- */
    { id: 'g8-2', t: 'Construeix-lo peça a peça|Constrúyelo pieza a pieza', min: 45, badge: 'g_u8build',
      learn: ['Cada personatge té els seus guions, i tots funcionen alhora.|Cada personaje tiene sus guiones, y todos funcionan a la vez.',
        'En començar, cal posar-ho tot a lloc: punts a 0, vides a 3, posicions.|Al empezar, hay que ponerlo todo en su sitio: puntos a 0, vidas a 3, posiciones.',
        'Un videojoc es construeix peça a peça, provant cada peça abans de la següent.|Un videojuego se construye pieza a pieza, probando cada pieza antes de la siguiente.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: "La setmana passada vas pensar el teu videojoc. Quines són les quatre peces d'un videojoc?|La semana pasada pensaste tu videojuego. ¿Cuáles son las cuatro piezas de un videojuego?",
          opts: ['Protagonista, objectiu, obstacle i regles|Protagonista, objetivo, obstáculo y reglas', 'Fons, so, color i música|Fondo, sonido, color y música', 'Teclat, ratolí, pantalla i altaveus|Teclado, ratón, pantalla y altavoces'], a: 0 },
        { k: 'quiz', ph: 'recorda', q: 'Per què va bé començar amb una <b>versió petita</b> del videojoc?|¿Por qué va bien empezar con una <b>versión pequeña</b> del videojuego?',
          opts: ["Perquè és fàcil de provar i d'arreglar abans d'afegir-hi més peces|Porque es fácil de probar y de arreglar antes de añadir más piezas", 'Perquè els videojocs petits són millors|Porque los videojuegos pequeños son mejores', 'Perquè no cal provar-la|Porque no hace falta probarla'], a: 0 },
        { k: 'story', ph: 'missio', who: 'both', scene: 'lab', title: 'El laboratori de videojocs|El laboratorio de videojuegos',
          t: "Benvingut/da al <b>laboratori de videojocs</b>! Aquí els creadors construeixen com qui fa una torre de peces: <b>una peça, la proven; una altra peça, la proven</b>… Avui faràs créixer la versió 1 del teu videojoc fins que tingui totes les peces.|¡Bienvenido/a al <b>laboratorio de videojuegos</b>! Aquí los creadores construyen como quien hace una torre de piezas: <b>una pieza, la prueban; otra pieza, la prueban</b>… Hoy harás crecer la versión 1 de tu videojuego hasta que tenga todas las piezas." },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Guions|Guiones', t: 'Cada personatge, els seus guions|Cada personaje, sus guiones', anim: 'g8who',
            x: "No cal posar-ho tot al protagonista. Cada personatge s'encarrega de les seves regles: el protagonista es mou i compta les vides, la moneda suma els punts quan la toquen i el meteorit cau. Quan toques la bandera, <b>tots els guions comencen alhora</b>.|No hace falta ponerlo todo en el protagonista. Cada personaje se encarga de sus reglas: el protagonista se mueve y cuenta las vidas, la moneda suma los puntos cuando la tocan y el meteorito cae. Cuando tocas la bandera, <b>todos los guiones empiezan a la vez</b>." },
          { k: 'Començar|Empezar', t: 'Tot a lloc en començar|Todo en su sitio al empezar', media: { k: 'stage', w: { bg: 'ciutat', vars: ['punts', 'vides'], time: 5, sprites: [{ id: 'cotxe', art: 'cotxe', x: 60, y: 40, size: 70 }, { id: 'moneda', art: 'moneda', x: 140, y: -120 }] }, prog: '@cotxe flag{ setv:punts,0 setv:vides,3 goto:-160,-120 show say:"Som-hi!|¡Vamos!",1 forever{ chx:4 if:touch:moneda{ chv:punts,1 } } } @moneda flag{ forever{ next wait:0.1 } }', varNames: { punts: 'punts|puntos', vides: 'vides|vidas' } },
            x: "El primer guió de la bandera sempre fa el mateix: <span class='hl'>ho posa tot a lloc</span>. Punts a 0, vides a 3, el protagonista al seu punt de sortida i visible. Així cada vegada que tornes a començar, el videojoc comença igual.|El primer guion de la bandera siempre hace lo mismo: <span class='hl'>lo pone todo en su sitio</span>. Puntos a 0, vidas a 3, el protagonista en su punto de salida y visible. Así cada vez que vuelves a empezar, el videojuego empieza igual.",
            bad: 'No poso els punts a 0: ja començaran bé.|No pongo los puntos a 0: ya empezarán bien.', good: 'Al principi: posa punts a 0, vides a 3 i ves a la sortida.|Al principio: pon puntos a 0, vidas a 3 y ve a la salida.' },
          { k: 'Nivells|Niveles', t: 'Un nivell nou: canvia el fons i va més de pressa|Un nivel nuevo: cambia el fondo y va más deprisa', media: { k: 'stage', w: { bg: 'bosc', bgs: ['bosc', 'nit'], vars: ['punts', 'velocitat'], time: 9, sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -80 }, { id: 'poma', art: 'poma', x: 120, y: 60 }] }, prog: '@gat flag{ bg:bosc setv:punts,0 setv:velocitat,3 forever{ pointto:poma move:$velocitat if:$punts>2{ bg:nit setv:velocitat,8 } } } @poma flag{ forever{ if:touch:gat{ chv:punts,1 sound:moneda gotorand } } }', varNames: { punts: 'punts|puntos', velocitat: 'velocitat|velocidad' } },
            x: "Quan el gat arriba a 3 punts, passa al <b>nivell 2</b>: el fons es fa de nit i la variable <b>velocitat</b> passa de 3 a 8. Com que el gat es mou «velocitat» passos, ara corre molt més. Un sol número canvia la dificultat!|Cuando el gato llega a 3 puntos, pasa al <b>nivel 2</b>: el fondo se hace de noche y la variable <b>velocidad</b> pasa de 3 a 8. Como el gato se mueve «velocidad» pasos, ahora corre mucho más. ¡Un solo número cambia la dificultad!" },
          { k: 'Clons|Clones', t: 'Molts enemics amb un sol guió|Muchos enemigos con un solo guion', media: { k: 'stage', w: { bg: 'espai', time: 6, sprites: [{ id: 'meteorit', art: 'meteorit', x: 0, y: 170, size: 70 }] }, prog: '@meteorit flag{ hide forever{ clone wait:0.6 } } clone{ gotorand sety:170 show forever{ chy:-5 if:y<-170{ delclone } } }' },
            x: "Si vols una pluja de meteorits, no cal dibuixar-ne vint: un sol meteorit amagat crea <b>clons</b>, i cada clon fa el guió «Quan començo com a clon»: surt a dalt en un lloc a l'atzar, cau i s'esborra a baix.|Si quieres una lluvia de meteoritos, no hace falta dibujar veinte: un solo meteorito escondido crea <b>clones</b>, y cada clon hace el guion «Al empezar como clon»: sale arriba en un sitio al azar, cae y se borra abajo.",
            tip: "Esborra els clons quan surten de l'escenari: si no, se'n van acumulant.|Borra los clones cuando salen del escenario: si no, se van acumulando." }
        ] },
        { k: 'seq', ph: 'mans', q: 'Ordena el guió de la bandera del protagonista d\'un videojoc.|Ordena el guion de la bandera del protagonista de un videojuego.',
          items: ['Quan comença (bandera verda)|Al empezar (bandera verde)', 'Posa punts a 0 i vides a 3|Pon puntos a 0 y vidas a 3', 'Ves a la sortida i digues el nom del videojoc|Ve a la salida y di el nombre del videojuego', 'Per sempre: si premo una fletxa, mou-te|Por siempre: si pulso una flecha, muévete', 'Dins del per sempre: si toco l\'enemic, vides −1|Dentro del por siempre: si toco al enemigo, vidas −1'],
          ex: "Primer el que passa una sola vegada (posar-ho tot a lloc) i després el bucle amb les regles que es comproven tota l'estona.|Primero lo que pasa una sola vez (ponerlo todo en su sitio) y después el bucle con las reglas que se comprueban todo el rato." },
        { k: 'quiz', ph: 'mans', q: 'On poses el bloc «posa punts a 0»?|¿Dónde pones el bloque «pon puntos a 0»?',
          opts: ['Al principi del guió de la bandera, abans del «per sempre»|Al principio del guion de la bandera, antes del «por siempre»', 'Dins del «per sempre»|Dentro del «por siempre»', 'Al guió de la moneda, quan la toquen|En el guion de la moneda, cuando la tocan'], a: 0,
          ex: 'Dins del «per sempre», els punts tornarien a 0 a cada volta i no podrien pujar mai.|Dentro del «por siempre», los puntos volverían a 0 en cada vuelta y no podrían subir nunca.' },
        { k: 'sspot', ph: 'prova', q: "En aquest videojoc el gat atrapa monedes, però el marcador <b>sempre marca 0</b>. Prova'l i <b>toca el bloc que ho espatlla</b>.|En este videojuego el gato atrapa monedas, pero el marcador <b>siempre marca 0</b>. Pruébalo y <b>toca el bloque que lo estropea</b>.",
          w: { bg: 'parc', vars: ['punts'], time: 8, sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -80 }, { id: 'moneda', art: 'moneda', x: 120, y: 60 }] },
          prog: '@gat flag{ forever{ setv:punts,0! pointto:moneda move:5 } } @moneda flag{ forever{ if:touch:gat{ chv:punts,1 sound:moneda gotorand } } }',
          ex: "«Posa punts a 0» és dins del «per sempre»: cada volta torna a deixar els punts a 0. S'ha de posar abans del bucle.|«Pon puntos a 0» está dentro del «por siempre»: cada vuelta vuelve a dejar los puntos a 0. Hay que ponerlo antes del bucle." },
        { k: 'stage', ph: 'investiga', q: "<b>Arregla-ho:</b> el meteorit cau una sola vegada i desapareix per sota. Fes que, <b>si</b> arriba a baix (y < −170), torni a dalt (y = 170) en un lloc a l'atzar i torni a caure.|<b>Arréglalo:</b> el meteorito cae una sola vez y desaparece por debajo. Haz que, <b>si</b> llega abajo (y < −170), vuelva arriba (y = 170) en un sitio al azar y vuelva a caer.",
          w: { bg: 'espai', time: 3, sprites: [{ id: 'meteorit', art: 'meteorit', x: 0, y: 170 }], goal: [{ k: 'reach', s: 'meteorit', r: [-240, -180, 240, -140] }, { k: 'at', s: 'meteorit', r: [-240, -60, 240, 180] }, { k: 'running', t: 2.8 }] },
          edit: ['meteorit'], hats: ['flag'], pal: ['chy', 'sety', 'setx', 'gotorand', 'goto', 'forever', 'if', 'cond+'], ops: ['x', 'y'],
          prog: '@meteorit flag{ goto:0,170 forever{ chy:-6 } }', sol: '@meteorit flag{ goto:0,170 forever{ chy:-6 if:y<-170{ gotorand sety:170 } } }',
          hint: "Dins del «per sempre», posa un «si» amb «comparar números»: posició y < −170. A dins: «ves a un lloc a l'atzar» i després «posa y a 170».|Dentro del «por siempre», pon un «si» con «comparar números»: posición y < −170. Dentro: «ve a un sitio al azar» y después «pon y a 170»." },
        { k: 'move', ph: 'pausa', secs: 30, t: "Sou una pluja de meteorits! Quan diguis «clon», un company/a s'aixeca i «cau» a poc a poc fins a ajupir-se. Si no hi ha companys a prop, fes-ho tu: aixeca't de puntetes, baixa a poc a poc fins a terra… i torna a dalt d'un salt!|¡Sois una lluvia de meteoritos! Cuando digas «clon», un compañero/a se levanta y «cae» despacio hasta agacharse. Si no hay compañeros cerca, hazlo tú: ponte de puntillas, baja despacio hasta el suelo… ¡y vuelve arriba de un salto!" },
        { k: 'stage', ph: 'repte', q: "<b>Peça: el nivell 2.</b> El gat ja recull pomes. Afegeix-hi una regla: <b>si</b> els punts passen de 2, canvia el fons a <b>nit</b> i digues «Nivell 2!».|<b>Pieza: el nivel 2.</b> El gato ya recoge manzanas. Añade una regla: <b>si</b> los puntos pasan de 2, cambia el fondo a <b>noche</b> y di «¡Nivel 2!».",
          w: { bg: 'bosc', bgs: ['bosc', 'nit'], vars: ['punts'], time: 10, sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -80 }, { id: 'poma', art: 'poma', x: 120, y: 60, prog: '@poma flag{ setv:punts,0 forever{ if:touch:gat{ chv:punts,1 sound:moneda gotorand } } }' }],
            goal: [{ k: 'var', v: 'punts', min: 3 }, { k: 'bg', n: 'nit' }, { k: 'said', s: 'gat', t: 'Nivell 2' }] },
          edit: ['gat'], hats: ['flag'], pal: ['move', 'pointto', 'forever', 'if', 'bg', 'say', 'wait', 'cond+'], texts: ['Nivell 2!|¡Nivel 2!', 'Som-hi!|¡Vamos!'], varNames: { punts: 'punts|puntos' },
          prog: '@gat flag{ bg:bosc forever{ pointto:poma move:6 } }', sol: '@gat flag{ bg:bosc forever{ pointto:poma move:6 if:$punts>2{ bg:nit say:"Nivell 2!|¡Nivel 2!" } } }',
          hint: "Com al repte de guanyar: un «si» dins del «per sempre» amb «comparar números» (punts > 2). A dins, «canvia el fons a» i «digues».|Como en el reto de ganar: un «si» dentro del «por siempre» con «comparar números» (puntos > 2). Dentro, «cambia el fondo a» y «di»." },
        { k: 'stage', ph: 'repte', q: "<b>Peça: cada cop més de pressa.</b> Fes que el meteorit caigui <b>velocitat</b> passos cada vegada. Comença amb velocitat 5 i, cada vegada que arriba a baix i torna a dalt, <b>suma 1 a la velocitat</b>. Ha d'arribar com a mínim a 7!|<b>Pieza: cada vez más deprisa.</b> Haz que el meteorito caiga <b>velocidad</b> pasos cada vez. Empieza con velocidad 5 y, cada vez que llega abajo y vuelve arriba, <b>suma 1 a la velocidad</b>. ¡Tiene que llegar como mínimo a 7!",
          w: { bg: 'espai', vars: ['velocitat'], time: 7, sprites: [{ id: 'meteorit', art: 'meteorit', x: 0, y: 170 }], goal: [{ k: 'var', v: 'velocitat', min: 7 }, { k: 'running', t: 6.5 }] },
          edit: ['meteorit'], hats: ['flag'], pal: ['move', 'point', 'goto', 'gotorand', 'sety', 'forever', 'if', 'setv', 'chv', 'cond+'], ops: ['y'], varNames: { velocitat: 'velocitat|velocidad' },
          sol: '@meteorit flag{ setv:velocitat,5 goto:0,170 point:180 forever{ move:$velocitat if:y<-170{ gotorand sety:170 chv:velocitat,1 } } }',
          hint: "«Apunta en direcció 180» fa mirar avall. Després, «mou-te» amb el valor de la variable velocitat. Quan torni a dalt, suma 1 a la velocitat.|«Apunta en dirección 180» hace mirar abajo. Después, «muévete» con el valor de la variable velocidad. Cuando vuelva arriba, suma 1 a la velocidad." },
        { k: 'stage', ph: 'repte', q: "<b>Peça: una pluja d'estrelles.</b> L'estrella s'amaga i crea <b>almenys 6 clons</b>, un cada mig segon. Cada clon surt en un lloc a l'atzar, a dalt de tot, i cau. Quan arriba a baix, s'esborra.|<b>Pieza: una lluvia de estrellas.</b> La estrella se esconde y crea <b>al menos 6 clones</b>, uno cada medio segundo. Cada clon sale en un sitio al azar, arriba del todo, y cae. Cuando llega abajo, se borra.",
          w: { bg: 'nit', time: 5, sprites: [{ id: 'estrella', art: 'estrella', x: 0, y: 170 }], goal: [{ k: 'clones', min: 6 }, { k: 'running', t: 4.5 }] },
          edit: ['estrella'], hats: ['flag', 'clone'], pal: ['hide', 'show', 'gotorand', 'sety', 'chy', 'clone', 'delclone', 'wait', 'rep', 'forever', 'if', 'cond+'], ops: ['y'],
          sol: '@estrella flag{ hide rep:6{ clone wait:0.5 } } clone{ gotorand sety:170 show forever{ chy:-4 if:y<-170{ delclone } } }',
          hint: "Al guió de la bandera: amaga't i repeteix 6 vegades «crea un clon de mi» i «espera 0.5». Al guió del clon: ves a l'atzar, posa y a 170, mostra't i cau.|En el guion de la bandera: escóndete y repite 6 veces «crea un clon de mí» y «espera 0.5». En el guion del clon: ve al azar, pon y a 170, muéstrate y cae." },
        { k: 'story', ph: 'crea', who: 'numi', title: 'Ara, el teu videojoc!|¡Ahora, tu videojuego!',
          t: "Ja tens totes les peces a punt. Obre la versió 1 del teu videojoc i fes-la créixer <b>peça a peça</b>. Després de cada peça, toca <b>Comença</b> i prova-la amb les fletxes!|Ya tienes todas las piezas a punto. Abre la versión 1 de tu videojuego y hazla crecer <b>pieza a pieza</b>. Después de cada pieza, ¡toca <b>Empieza</b> y pruébala con las flechas!",
          box: "<ol><li>El protagonista es mou (ja ho tens!).</li><li>El premi: si el toques, punts +1.</li><li>L'enemic es mou: si et toca, vides −1.</li><li>Com guanyes i com perds.</li><li>Extres: sons, nivells, clons…</li></ol>|<ol><li>El protagonista se mueve (¡ya lo tienes!).</li><li>El premio: si lo tocas, puntos +1.</li><li>El enemigo se mueve: si te toca, vidas −1.</li><li>Cómo ganas y cómo pierdes.</li><li>Extras: sonidos, niveles, clones…</li></ol>" },
        { k: 'screate', ph: 'crea', name: 'El meu videojoc (versió 2)|Mi videojuego (versión 2)', ...MINE,
          get w() { return myW([{ k: 'running', t: 2.5 }], IN, 2.5); }, get prog() { return myP(); },
          q: "<b>Construeix el teu videojoc.</b> Continua la versió que vas desar i afegeix-hi les peces del teu pla. Toca <b>Comença</b> per provar-lo tantes vegades com vulguis. Quan estigui a punt, toca <b>Comprova</b> i desa'l.|<b>Construye tu videojuego.</b> Continúa la versión que guardaste y añádele las piezas de tu plan. Toca <b>Empieza</b> para probarlo tantas veces como quieras. Cuando esté a punto, toca <b>Comprueba</b> y guárdalo.",
          crit: ['Té protagonista, objectiu i obstacle|Tiene protagonista, objetivo y obstáculo', 'Fa servir una variable (punts o vides)|Usa una variable (puntos o vidas)', 'Té almenys una regla amb «si…»|Tiene al menos una regla con «si…»', 'Es pot guanyar o perdre|Se puede ganar o perder'],
          check: P => !has(P, ['setv', 'chv']) ? 'Ja funciona! Ara fes servir una variable: per exemple, suma 1 als punts quan toquis el premi.|¡Ya funciona! Ahora usa una variable: por ejemplo, suma 1 a los puntos cuando toques el premio.'
            : !has(P, ['if', 'until', 'waitu']) ? 'Molt bé! Ara afegeix-hi una regla amb «si…»: per exemple, si toques l\'enemic, vides −1.|¡Muy bien! Ahora añade una regla con «si…»: por ejemplo, si tocas al enemigo, vidas −1.'
            : nProg(P) < 2 ? "Ja gairebé hi és! Programa també un altre personatge: el premi o l'enemic.|¡Ya casi está! Programa también otro personaje: el premio o el enemigo." : null,
          sol: GAME + GAME_E,
          hint: "Ves peça a peça: primer el premi (si toca el protagonista, punts +1 i ves a l'atzar), després l'enemic (es mou i, si et toca, vides −1) i al final com guanyes i com perds.|Ve pieza a pieza: primero el premio (si toca al protagonista, puntos +1 y ve al azar), después el enemigo (se mueve y, si te toca, vidas −1) y al final cómo ganas y cómo pierdes." },
        { k: 'quiz', ph: 'tanca', q: 'Has afegit una peça nova al teu videojoc. Què fas abans de posar-ne una altra?|Has añadido una pieza nueva a tu videojuego. ¿Qué haces antes de poner otra?',
          opts: ['El provo per veure si la peça funciona|Lo pruebo para ver si la pieza funciona', "N'afegeixo cinc més de cop|Añado cinco más de golpe", 'Esborro la peça anterior|Borro la pieza anterior'], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'Vols molts meteorits que caiguin alhora. Quina és la manera més curta?|Quieres muchos meteoritos que caigan a la vez. ¿Cuál es la manera más corta?',
          opts: ['Un meteorit que crea clons|Un meteorito que crea clones', 'Dibuixar vint meteorits iguals|Dibujar veinte meteoritos iguales', 'Un meteorit molt gran|Un meteorito muy grande'], a: 0,
          ex: 'Tots els clons fan el mateix guió, «Quan començo com a clon». Si el canvies, canvien tots.|Todos los clones hacen el mismo guion, «Al empezar como clon». Si lo cambias, cambian todos.' },
        { k: 'feel', ph: 'tanca' }
      ] },

    /* ---------- Sessió 3 · Provar-lo i millorar-lo ---------- */
    { id: 'g8-3', t: 'Provar-lo i millorar-lo|Probarlo y mejorarlo', min: 45, badge: 'g_u8prova',
      learn: ['Un videojoc es prova amb una altra persona: té ulls nous i troba bugs.|Un videojuego se prueba con otra persona: tiene ojos nuevos y encuentra bugs.',
        'La dificultat s\'ajusta canviant números: velocitat, vides, punts per guanyar.|La dificultad se ajusta cambiando números: velocidad, vidas, puntos para ganar.',
        "Un bon comentari diu què t'ha agradat i una idea per millorar.|Un buen comentario dice qué te ha gustado y una idea para mejorar."],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'La setmana passada vas construir el teu videojoc. Què ha de fer el guió de la bandera <b>abans</b> del «per sempre»?|La semana pasada construiste tu videojuego. ¿Qué tiene que hacer el guion de la bandera <b>antes</b> del «por siempre»?',
          opts: ['Posar-ho tot a lloc: punts a 0, vides a 3 i la sortida|Ponerlo todo en su sitio: puntos a 0, vidas a 3 y la salida', 'Esborrar tots els guions|Borrar todos los guiones', 'Res: el per sempre ja ho fa tot|Nada: el por siempre ya lo hace todo'], a: 0 },
        { k: 'quiz', ph: 'recorda', q: 'Quin guió fa cada clon quan neix?|¿Qué guion hace cada clon cuando nace?',
          opts: ['«Quan començo com a clon»|«Al empezar como clon»', '«Quan comença (bandera verda)»|«Al empezar (bandera verde)»', 'Cap: els clons no fan res|Ninguno: los clones no hacen nada'], a: 0 },
        { k: 'story', ph: 'missio', who: 'both', scene: 'poble', title: 'La sala de proves|La sala de pruebas',
          t: "A la plaça del poble ja munten la Fira de Videojocs. Abans de l'estrena, tots els videojocs passen per la <b>sala de proves</b>: un company/a provarà el teu i et dirà què li ha agradat i què milloraria. I tu faràs el mateix amb el seu!|En la plaza del pueblo ya montan la Feria de Videojuegos. Antes del estreno, todos los videojuegos pasan por la <b>sala de pruebas</b>: un compañero/a probará el tuyo y te dirá qué le ha gustado y qué mejoraría. ¡Y tú harás lo mismo con el suyo!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'Ulls nous|Ojos nuevos', t: 'Per què ho ha de provar algú altre?|¿Por qué lo tiene que probar otra persona?', media: { k: 'stage', w: { bg: 'ciutat', time: 5, sprites: [{ id: 'cotxe', art: 'cotxe', x: -160, y: -130, size: 70 }] }, prog: '@cotxe flag{ goto:-160,-130 say:"Vaig cap a la dreta…|Voy hacia la derecha…",1 forever{ chx:6 } }' },
            x: "Tu saps com funciona el teu videojoc i sempre el proves igual. Una persona nova prova coses que no esperaves… i troba <b>bugs</b> (errors del programa), com aquest cotxe que se'n va de l'escenari i ja no torna. Els creadors en diuen <span class='hl'>provar amb usuaris</span>.|Tú sabes cómo funciona tu videojuego y siempre lo pruebas igual. Una persona nueva prueba cosas que no esperabas… y encuentra <b>bugs</b> (errores del programa), como este coche que se va del escenario y ya no vuelve. Los creadores lo llaman <span class='hl'>probar con usuarios</span>." },
          { k: 'Dificultat|Dificultad', t: 'Ni massa fàcil ni massa difícil|Ni demasiado fácil ni demasiado difícil', anim: 'g8tune',
            x: "Si el provador/a guanya en un segon, és massa fàcil. Si perd sempre, és massa difícil i fa ràbia. Per ajustar-ho, n'hi ha prou amb <b>canviar un número</b>: la velocitat de l'enemic, les vides del principi o els punts que calen per guanyar.|Si el probador/a gana en un segundo, es demasiado fácil. Si pierde siempre, es demasiado difícil y da rabia. Para ajustarlo, basta con <b>cambiar un número</b>: la velocidad del enemigo, las vidas del principio o los puntos que hacen falta para ganar." },
          { k: 'Comentaris|Comentarios', t: 'Un comentari amable i útil|Un comentario amable y útil', anim: 'g8feedback',
            x: "Un bon <span class='hl'>comentari</span> té dues parts: primer, <b>una cosa que t'ha agradat</b>; després, <b>una idea per millorar</b>. Parla del videojoc, no de la persona, i digues coses concretes.|Un buen <span class='hl'>comentario</span> tiene dos partes: primero, <b>algo que te ha gustado</b>; después, <b>una idea para mejorar</b>. Habla del videojuego, no de la persona, y di cosas concretas.",
            bad: '«És avorrit.»|«Es aburrido.»', good: "«M'agrada la pluja d'estrelles. I si l'enemic anés més lent?»|«Me gusta la lluvia de estrellas. ¿Y si el enemigo fuera más lento?»" },
          { k: 'Espia|Espía', t: 'Mira què passa per dins|Mira qué pasa por dentro', media: { k: 'stage', w: { bg: 'parc', vars: ['punts'], time: 8, sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -80 }, { id: 'moneda', art: 'moneda', x: 120, y: 60 }] }, prog: '@gat flag{ setv:punts,0 forever{ pointto:moneda move:4 say:$punts } } @moneda flag{ forever{ if:touch:gat{ chv:punts,1 sound:moneda gotorand } } }', varNames: { punts: 'punts|puntos' } },
            x: "Quan un bug costa de trobar, fes que un personatge <b>digui el valor d'una variable</b>: així veus com canvia mentre el videojoc funciona. Aquí el gat diu els punts tota l'estona. Quan hagis trobat el bug, treu el bloc.|Cuando un bug cuesta de encontrar, haz que un personaje <b>diga el valor de una variable</b>: así ves cómo cambia mientras el videojuego funciona. Aquí el gato dice los puntos todo el rato. Cuando hayas encontrado el bug, quita el bloque.",
            tip: "Al bloc «digues», toca el text i tria la variable.|En el bloque «di», toca el texto y elige la variable." }
        ] },
        { k: 'quiz', ph: 'mans', q: "Un company/a ha provat el teu videojoc. Quin comentari t'ajuda més?|Un compañero/a ha probado tu videojuego. ¿Qué comentario te ayuda más?",
          opts: ["«M'agraden els sons. Però l'enemic és tan ràpid que no hi ha temps de fugir.»|«Me gustan los sonidos. Pero el enemigo es tan rápido que no hay tiempo de huir.»", '«No m\'agrada.»|«No me gusta.»', '«El meu és millor.»|«El mío es mejor.»'], a: 0,
          ex: "Diu una cosa bona i explica exactament què costa. Amb això ja saps quin número has de canviar!|Dice algo bueno y explica exactamente qué cuesta. ¡Con eso ya sabes qué número tienes que cambiar!" },
        { k: 'seq', ph: 'mans', q: 'Com es fa de bon provador/a? <b>Ordena els passos.</b>|¿Cómo se hace de buen probador/a? <b>Ordena los pasos.</b>',
          items: ["Escolto o llegeixo les instruccions del videojoc|Escucho o leo las instrucciones del videojuego", "El provo sense que l'autor/a m'ajudi|Lo pruebo sin que el autor/a me ayude", "Dic una cosa que m'ha agradat|Digo algo que me ha gustado", 'Proposo una idea per millorar-lo|Propongo una idea para mejorarlo', "Dono les gràcies a l'autor/a|Doy las gracias al autor/a"],
          ex: 'Primer cal provar-lo de veritat; després, una cosa bona, una idea i les gràcies.|Primero hay que probarlo de verdad; después, algo bueno, una idea y las gracias.' },
        { k: 'sfree', ph: 'prova', q: "Ets a la sala de proves! La Flama ha fet «Pluja de meteorits»: mou la nau amb les fletxes i esquiva'ls. <b>Prova'l</b> unes quantes vegades. Com és de difícil?|¡Estás en la sala de pruebas! Flama ha hecho «Lluvia de meteoritos»: mueve la nave con las flechas y esquívalos. <b>Pruébalo</b> unas cuantas veces. ¿Cómo de difícil es?",
          w: { bg: 'espai', keys: ['left', 'right'], vars: ['vides'], sprites: [{ id: 'nau', art: 'nau', rot: 'none', x: 0, y: -130, size: 70 }, { id: 'meteorit', art: 'meteorit', x: 0, y: 170, size: 90 }] },
          prog: `@nau flag{ setv:vides,3 goto:0,-130 forever{ if:key:right{ chx:7 } if:key:left{ chx:-7 } if:touch:meteorit{ chv:vides,-1 sound:xoc wait:0.6 } if:$vides<1{ say:"Has perdut!|¡Has perdido!" stop:all } } }
            @meteorit flag{ hide forever{ clone wait:0.25 } } clone{ gotorand sety:170 show point:180 forever{ move:14 if:y<-170{ delclone } } }` },
        { k: 'quiz', ph: 'prova', q: 'Gairebé tothom perd de seguida a «Pluja de meteorits». Com el faries més just?|Casi todo el mundo pierde enseguida en «Lluvia de meteoritos». ¿Cómo lo harías más justo?',
          opts: ['Fent que els meteorits caiguin més a poc a poc o que en surtin menys|Haciendo que los meteoritos caigan más despacio o que salgan menos', 'Posant-hi més meteorits|Poniendo más meteoritos', 'Traient la nau|Quitando la nave'], a: 0,
          ex: 'Amb «mou-te 6» en lloc de «mou-te 14», o «espera 0.6» entre clons, ja hi ha temps per esquivar-los.|Con «muévete 6» en lugar de «muévete 14», o «espera 0.6» entre clones, ya hay tiempo para esquivarlos.' },
        { k: 'stage', ph: 'investiga', q: "<b>Comentari del provador/a:</b> «El cranc m'atrapa de seguida, és impossible!» El gat fuig tot sol. Canvia <b>només un número</b> perquè el cranc vagi més lent i no l'atrapi… però que es continuï movent!|<b>Comentario del probador/a:</b> «¡El cangrejo me atrapa enseguida, es imposible!» El gato huye solo. Cambia <b>solo un número</b> para que el cangrejo vaya más lento y no lo atrape… ¡pero que siga moviéndose!",
          w: { bg: 'platja', time: 6, sprites: [{ id: 'gat', art: 'gat', rot: 'lr', x: -150, y: -110, prog: '@gat flag{ goto:-150,-110 glide:3,-150,130 glide:3,180,130 }' }, { id: 'cranc', art: 'cranc', rot: 'lr', x: 160, y: -110 }],
            goal: [{ k: 'notouch', a: 'gat', b: 'cranc' }, { k: 'moved', s: 'cranc', min: 60 }] },
          edit: ['cranc'], hats: ['flag'], pal: ['move', 'pointto', 'goto', 'forever', 'wait'],
          prog: '@cranc flag{ goto:160,-110 forever{ pointto:gat move:9 } }', sol: '@cranc flag{ goto:160,-110 forever{ pointto:gat move:2 } }',
          hint: "El número de «mou-te» és la velocitat del cranc: com més petit, més lent. Prova'n uns quants fins que el gat tingui temps d'escapar.|El número de «muévete» es la velocidad del cangrejo: cuanto más pequeño, más lento. Prueba unos cuantos hasta que el gato tenga tiempo de escapar." },
        { k: 'move', ph: 'pausa', secs: 30, t: "Fes de provador/a de videojocs: mou els polzes com si premessis les fletxes (dreta, dreta, esquerra!), salta per esquivar un meteorit imaginari i, quan acabis, fes un «m'agrada» amb el polze ben amunt!|Haz de probador/a de videojuegos: mueve los pulgares como si pulsaras las flechas (¡derecha, derecha, izquierda!), salta para esquivar un meteorito imaginario y, cuando acabes, ¡haz un «me gusta» con el pulgar bien arriba!" },
        { k: 'stage', ph: 'repte', q: "<b>Bug trobat:</b> «Si mantinc premuda una fletxa, el cotxe se'n va de l'escenari!» Afegeix dues regles: <b>si</b> x > 200, posa x a 200; i <b>si</b> x < −200, posa x a −200. Quan ho tinguis, toca <b>Comprova</b>.|<b>Bug encontrado:</b> «¡Si mantengo pulsada una flecha, el coche se va del escenario!» Añade dos reglas: <b>si</b> x > 200, pon x a 200; y <b>si</b> x < −200, pon x a −200. Cuando lo tengas, toca <b>Comprueba</b>.",
          w: { bg: 'ciutat', keys: ['left', 'right'], time: 7, sprites: [{ id: 'cotxe', art: 'cotxe', x: 0, y: -130, size: 80 }],
            input: [{ t: .2, key: 'right', dur: 3 }, { t: 3.5, key: 'left', dur: 3.2 }],
            goal: [{ k: 'reach', s: 'cotxe', r: [150, -180, 240, 0] }, { k: 'at', s: 'cotxe', r: [-240, -180, -150, 0] }, { k: 'running', t: 6.8 }] },
          edit: ['cotxe'], hats: ['flag'], pal: ['chx', 'setx', 'forever', 'if', 'cond+'], ops: ['x'],
          prog: '@cotxe flag{ forever{ if:key:right{ chx:6 } if:key:left{ chx:-6 } } }',
          sol: '@cotxe flag{ forever{ if:key:right{ chx:6 } if:key:left{ chx:-6 } if:x>200{ setx:200 } if:x<-200{ setx:-200 } } }',
          hint: "Dins del «per sempre», afegeix un «si» amb «comparar números»: posició x > 200. A dins, «posa x a 200». Després, el mateix per a l'altra vora.|Dentro del «por siempre», añade un «si» con «comparar números»: posición x > 200. Dentro, «pon x a 200». Después, lo mismo para el otro borde." },
        { k: 'stage', ph: 'repte', q: "<b>Comentari:</b> «No sabia què havia de fer!» Afegeix unes <b>instruccions</b>: en començar, en Numi ha de dir «Fes servir les fletxes!» durant 2 segons i, després, <b>enviar el missatge «som-hi»</b> perquè la pilota es posi en marxa.|<b>Comentario:</b> «¡No sabía qué tenía que hacer!» Añade unas <b>instrucciones</b>: al empezar, Numi tiene que decir «¡Usa las flechas!» durante 2 segundos y, después, <b>enviar el mensaje «som-hi»</b> para que la pelota se ponga en marcha.",
          w: { bg: 'escenari', time: 4, sprites: [{ id: 'numi', art: 'numi', x: -140, y: -60, size: 90 }, { id: 'pilota', art: 'pilota', x: 120, y: 40, prog: '@pilota msg:som-hi{ point:45 forever{ move:6 bounce } }' }],
            goal: [{ k: 'said', s: 'numi', t: 'fletxes' }, { k: 'msg', m: 'som-hi' }, { k: 'moved', s: 'pilota', min: 60 }] },
          edit: ['numi'], hats: ['flag'], pal: ['say', 'wait', 'send', 'sound'], texts: ['Fes servir les fletxes!|¡Usa las flechas!', 'Recull 5 estrelles!|¡Recoge 5 estrellas!', 'Hola!|¡Hola!'], msgs: ['som-hi'],
          sol: '@numi flag{ say:"Fes servir les fletxes!|¡Usa las flechas!",2 send:som-hi }',
          hint: "Primer «digues… durant 2 segons» i, a sota, «envia el missatge som-hi». La pilota ja sap què ha de fer quan el rep.|Primero «di… durante 2 segundos» y, debajo, «envía el mensaje som-hi». La pelota ya sabe qué tiene que hacer cuando lo recibe." },
        { k: 'story', ph: 'crea', who: 'numi', title: 'Canvi de lloc!|¡Cambio de sitio!',
          t: "Arriba el moment més important: <b>canvieu de lloc</b> amb el company/a. Tu seus al seu ordinador i ell o ella, al teu. (A casa, demana a algú de la família que segui al teu lloc.) Els dos passos següents són per al provador/a!|Llega el momento más importante: <b>cambiad de sitio</b> con el compañero/a. Tú te sientas en su ordenador y él o ella, en el tuyo. (En casa, pide a alguien de la familia que se siente en tu sitio.) ¡Los dos pasos siguientes son para el probador/a!",
          box: "<ol><li>L'autor/a explica només les instruccions.</li><li>El provador/a el prova sense ajuda, almenys tres vegades.</li><li>L'autor/a mira i calla… i apunta què costa!</li></ol>|<ol><li>El autor/a explica solo las instrucciones.</li><li>El probador/a lo prueba sin ayuda, al menos tres veces.</li><li>El autor/a mira y calla… ¡y apunta qué cuesta!</li></ol>" },
        { k: 'sfree', ph: 'crea', get w() { return myW([], [], 30); }, get prog() { return myP(); }, varNames: VN,
          q: "Hola, provador/a! Aquest és el videojoc del teu company/a. Toca <b>Comença</b> i prova'l de veritat, almenys tres vegades. Fixa't en què t'agrada i en què costa.|¡Hola, probador/a! Este es el videojuego de tu compañero/a. Toca <b>Empieza</b> y pruébalo de verdad, al menos tres veces. Fíjate en qué te gusta y en qué cuesta." },
        { k: 'review', ph: 'crea', q: "Ara valora el videojoc, provador/a. Respon amb sinceritat i amabilitat: les teves respostes ajudaran l'autor/a a millorar-lo.|Ahora valora el videojuego, probador/a. Responde con sinceridad y amabilidad: tus respuestas ayudarán al autor/a a mejorarlo.",
          items: [
            { q: 'Era clar què havia de fer?|¿Estaba claro qué tenía que hacer?', opts: ['Sí, molt clar|Sí, muy claro', 'Més o menys|Más o menos', 'No gaire|No mucho'] },
            { q: 'Com era de difícil?|¿Cómo de difícil era?', opts: ['Massa fàcil|Demasiado fácil', 'Al punt|En su punto', 'Massa difícil|Demasiado difícil'] },
            { q: 'Has trobat algun bug?|¿Has encontrado algún bug?', opts: ['No, cap|No, ninguno', 'Sí, un de petit|Sí, uno pequeño', 'Sí, un que espatlla el videojoc|Sí, uno que estropea el videojuego'] },
            { q: 'Què milloraries?|¿Qué mejorarías?', opts: ['Les instruccions|Las instrucciones', 'La velocitat|La velocidad', 'Més enemics o premis|Más enemigos o premios', 'Un final més clar|Un final más claro', 'Ja està molt bé|Ya está muy bien'] }
          ] },
        { k: 'story', ph: 'crea', who: 'bit', mood: 'wave', title: 'Torneu al vostre lloc|Volved a vuestro sitio',
          t: "Gràcies, provador/a! Abans de tornar al teu ordinador, explica de paraula a l'autor/a <b>una cosa que t'ha agradat</b> i <b>una idea per millorar</b>. Després, torneu cadascú al vostre lloc.|¡Gracias, probador/a! Antes de volver a tu ordenador, explica de palabra al autor/a <b>algo que te ha gustado</b> y <b>una idea para mejorar</b>. Después, volved cada uno a vuestro sitio." },
        { k: 'screate', ph: 'crea', name: 'El meu videojoc (versió 3)|Mi videojuego (versión 3)', ...MINE,
          get w() { return myW([{ k: 'running', t: 2.5 }], IN, 2.5); }, get prog() { return myP(); },
          q: "Ja ets al teu lloc. Pensa en els comentaris i <b>millora el teu videojoc</b>: arregla els bugs, ajusta la dificultat o afegeix-hi el que t'han proposat. Tu decideixes! Quan estigui llest, toca <b>Comprova</b> i desa'l.|Ya estás en tu sitio. Piensa en los comentarios y <b>mejora tu videojuego</b>: arregla los bugs, ajusta la dificultad o añade lo que te han propuesto. ¡Tú decides! Cuando esté listo, toca <b>Comprueba</b> y guárdalo.",
          crit: ['Has fet almenys un canvi a partir dels comentaris|Has hecho al menos un cambio a partir de los comentarios', 'Els bugs que han trobat estan arreglats|Los bugs que han encontrado están arreglados', 'Continua funcionant de principi a final|Sigue funcionando de principio a final'],
          check: P => { const p = last(); return p && sig(P) === sig(p.progs) ? 'Funciona, però encara és igual que la versió que vas desar. Fes-hi almenys una millora!|Funciona, pero aún es igual que la versión que guardaste. ¡Hazle al menos una mejora!' : null; },
          sol: GAME + ` @enemic flag{ goto:20,110 forever{ pointto:heroi move:2 if:$punts>4{ bg:nit } } }`,
          hint: "Mira què van respondre al pas de la valoració. Massa difícil? Fes l'enemic més lent. Un bug? Busca el bloc que el provoca. No era clar? Afegeix-hi instruccions amb «digues».|Mira qué respondieron en el paso de la valoración. ¿Demasiado difícil? Haz el enemigo más lento. ¿Un bug? Busca el bloque que lo provoca. ¿No estaba claro? Añade instrucciones con «di»." },
        { k: 'quiz', ph: 'tanca', q: 'Per què és important que el teu videojoc el provi algú altre?|¿Por qué es importante que tu videojuego lo pruebe otra persona?',
          opts: ['Perquè té ulls nous i troba coses que jo no veig|Porque tiene ojos nuevos y encuentra cosas que yo no veo', "Perquè així no l'he d'acabar jo|Porque así no lo tengo que terminar yo", "Perquè m'ho digui tot bé|Para que me lo diga todo bien"], a: 0 },
        { k: 'quiz', ph: 'tanca', q: 'El provador/a diu que el teu videojoc és <b>massa fàcil</b>. Què pots fer?|El probador/a dice que tu videojuego es <b>demasiado fácil</b>. ¿Qué puedes hacer?',
          opts: ["Fer l'enemic més ràpid o demanar més punts per guanyar|Hacer el enemigo más rápido o pedir más puntos para ganar", 'Esborrar-lo tot|Borrarlo todo', 'Treure-li les vides|Quitarle las vidas'], a: 0,
          ex: 'Amb un número més gran a «mou-te» o a «si punts >», el videojoc es fa més difícil.|Con un número más grande en «muévete» o en «si puntos >», el videojuego se hace más difícil.' },
        { k: 'feel', ph: 'tanca' }
      ] },

    /* ---------- Sessió 4 · Presentació i diploma ---------- */
    { id: 'g8-4', t: 'Presentació i diploma|Presentación y diploma', min: 40, proj: true, badge: 'g_u8grad',
      learn: ["Presentar un videojoc és explicar què has fet, com funciona i què t'ha costat.|Presentar un videojuego es explicar qué has hecho, cómo funciona y qué te ha costado.",
        'Un bon videojoc té títol i instruccions perquè tothom sàpiga què ha de fer.|Un buen videojuego tiene título e instrucciones para que todo el mundo sepa qué tiene que hacer.',
        'Ja ets creador/a: penses, planifiques, programes, proves i millores.|Ya eres creador/a: piensas, planificas, programas, pruebas y mejoras.'],
      steps: [
        { k: 'quiz', ph: 'recorda', q: 'Quines dues parts té un bon comentari?|¿Qué dos partes tiene un buen comentario?',
          opts: ["Una cosa que m'ha agradat i una idea per millorar|Algo que me ha gustado y una idea para mejorar", 'Una crítica i una altra crítica|Una crítica y otra crítica', 'Només «molt bé»|Solo «muy bien»'], a: 0 },
        { k: 'story', ph: 'missio', who: 'both', scene: 'illa', mood: 'dance', title: "L'estrena|El estreno",
          t: "Avui és el gran dia: s'obre la <b>Fira de Videojocs</b>! Cada creador/a presentarà el seu videojoc a la pantalla gegant i, al final, en Bit lliurarà els <b>diplomes</b>. Has fet un camí molt llarg: des del teu primer personatge fins a un videojoc sencer!|¡Hoy es el gran día: se abre la <b>Feria de Videojuegos</b>! Cada creador/a presentará su videojuego en la pantalla gigante y, al final, Bit entregará los <b>diplomas</b>. Has hecho un camino muy largo: ¡desde tu primer personaje hasta un videojuego entero!" },
        { k: 'learn', ph: 'descobreix', cards: [
          { k: 'El viatge|El viaje', t: 'Vuit unitats, un curs sencer|Ocho unidades, un curso entero', anim: 'g8journey',
            x: "Vas començar movent un personatge i fent-lo parlar. Després vas aprendre a <b>animar</b> amb vestits i bucles, a fer servir <b>tecles i missatges</b>, les <b>coordenades</b>, les <b>condicions</b>, les <b>variables</b>, l'<b>atzar</b> i els <b>clons</b>. I ara ho has ajuntat tot en un videojoc teu!|Empezaste moviendo un personaje y haciéndolo hablar. Después aprendiste a <b>animar</b> con disfraces y bucles, a usar <b>teclas y mensajes</b>, las <b>coordenadas</b>, las <b>condiciones</b>, las <b>variables</b>, el <b>azar</b> y los <b>clones</b>. ¡Y ahora lo has juntado todo en un videojuego tuyo!" },
          { k: 'Presentar|Presentar', t: 'Tres preguntes per presentar|Tres preguntas para presentar', media: { k: 'stage', w: W_DEMO, prog: P_DEMO, varNames: { punts: 'punts|puntos' } },
            x: "Per presentar el teu videojoc, respon tres preguntes: <b>Què he fet?</b> (el nom i de què va), <b>Com funciona?</b> (ensenya un guió i explica una regla) i <b>Què m'ha costat?</b> (un bug, un canvi, una millora). Després, fes que algú del públic el provi!|Para presentar tu videojuego, responde tres preguntas: <b>¿Qué he hecho?</b> (el nombre y de qué va), <b>¿Cómo funciona?</b> (enseña un guion y explica una regla) y <b>¿Qué me ha costado?</b> (un bug, un cambio, una mejora). Después, ¡haz que alguien del público lo pruebe!",
            tip: 'Parla a poc a poc i mira el públic. Si estàs nerviós/a, respira fondo: tothom està de la teva part.|Habla despacio y mira al público. Si estás nervioso/a, respira hondo: todo el mundo está de tu parte.' },
          { k: 'Benvinguda|Bienvenida', t: 'Títol i instruccions|Título e instrucciones', media: { k: 'stage', w: { bg: 'espai', time: 6, sprites: [{ id: 'nau', art: 'nau', rot: 'none', x: 0, y: -120, size: 70 }, { id: 'estrella', art: 'estrella', x: 0, y: 60, size: 140 }] }, prog: '@estrella flag{ size:140 show say:"La pluja de meteorits|La lluvia de meteoritos",2 say:"Esquiva\'ls amb les fletxes!|¡Esquívalos con las flechas!",2 hide send:fi } @nau msg:fi{ forever{ chx:4 bounce } }' },
            x: "Quan algú obre el teu videojoc per primera vegada, no sap què ha de fer. Comença amb un <b>títol</b> i unes <b>instruccions</b> curtes («Esquiva'ls amb les fletxes!») i, després, posa'l en marxa amb un missatge.|Cuando alguien abre tu videojuego por primera vez, no sabe qué tiene que hacer. Empieza con un <b>título</b> y unas <b>instrucciones</b> cortas («¡Esquívalos con las flechas!») y, después, ponlo en marcha con un mensaje.",
            bad: 'Sense instruccions: «Ja ho endevinaran.»|Sin instrucciones: «Ya lo adivinarán.»', good: 'Un títol i una frase: què has de fer i amb quines tecles.|Un título y una frase: qué tienes que hacer y con qué teclas.' },
          { k: 'Com ho has fet|Cómo lo has hecho', t: 'Ensenya els guions|Enseña los guiones', anim: 'g8who',
            x: "El públic no només vol veure el videojoc: també vol saber <b>com l'has fet</b>. Tria un personatge, ensenya el seu guió i explica una regla amb paraules: «Si la moneda toca el gat, suma 1 punt i salta a un lloc a l'atzar.»|El público no solo quiere ver el videojuego: también quiere saber <b>cómo lo has hecho</b>. Elige un personaje, enseña su guion y explica una regla con palabras: «Si la moneda toca al gato, suma 1 punto y salta a un sitio al azar.»" }
        ] },
        { k: 'seq', ph: 'mans', q: 'Prepara la teva presentació. <b>Posa-la en ordre.</b>|Prepara tu presentación. <b>Ponla en orden.</b>',
          items: ['Dic el nom del meu videojoc i de què va|Digo el nombre de mi videojuego y de qué va', 'Ensenyo un guió i explico una regla|Enseño un guion y explico una regla', "Explico què m'ha costat i com ho he millorat|Explico qué me ha costado y cómo lo he mejorado", 'Algú del públic el prova|Alguien del público lo prueba', 'Dono les gràcies i responc preguntes|Doy las gracias y respondo preguntas'],
          ex: 'Primer què és, després com funciona i què has après… i, al final, que el provin!|Primero qué es, después cómo funciona y qué has aprendido… ¡y, al final, que lo prueben!' },
        { k: 'quiz', ph: 'prova', q: '<b>Repàs del curs.</b> Un personatge és a x: 0, y: 0 i fa «canvia x en 100». On és ara?|<b>Repaso del curso.</b> Un personaje está en x: 0, y: 0 y hace «cambia x en 100». ¿Dónde está ahora?',
          opts: ['A la dreta del centre (x: 100, y: 0)|A la derecha del centro (x: 100, y: 0)', 'A dalt del centre (x: 0, y: 100)|Encima del centro (x: 0, y: 100)', "A l'esquerra (x: −100, y: 0)|A la izquierda (x: −100, y: 0)"], a: 0,
          ex: 'La x creix cap a la dreta i la y, cap amunt.|La x crece hacia la derecha y la y, hacia arriba.' },
        { k: 'quiz', ph: 'prova', q: 'Per a què serveix el bloc «envia el missatge»?|¿Para qué sirve el bloque «envía el mensaje»?',
          opts: ['Per avisar els altres personatges perquè facin alguna cosa|Para avisar a los otros personajes para que hagan algo', 'Per escriure un text a la pantalla|Para escribir un texto en la pantalla', "Per esborrar un personatge|Para borrar un personaje"], a: 0,
          ex: 'Els personatges que tenen «Quan rebo el missatge…» comencen aquell guió quan arriba el missatge.|Los personajes que tienen «Al recibir el mensaje…» empiezan ese guion cuando llega el mensaje.' },
        { k: 'sspot', ph: 'prova', q: "<b>Repàs.</b> En aquest videojoc, la moneda apareix cada vegada en un lloc diferent. <b>Toca el bloc que ho fa.</b>|<b>Repaso.</b> En este videojuego, la moneda aparece cada vez en un sitio diferente. <b>Toca el bloque que lo hace.</b>",
          w: W_DEMO, prog: '@gat flag{ setv:punts,0 forever{ pointto:moneda move:4 } } @moneda flag{ forever{ next wait:0.1 if:touch:gat{ chv:punts,1 sound:moneda gotorand! } } }',
          ex: "«Ves a un lloc a l'atzar» tria una posició nova cada vegada que el gat toca la moneda.|«Ve a un sitio al azar» elige una posición nueva cada vez que el gato toca la moneda." },
        { k: 'quiz', ph: 'investiga', q: 'Per què sembla que el peix neda quan fa «per sempre: vestit següent, espera 0.2»?|¿Por qué parece que el pez nada cuando hace «por siempre: disfraz siguiente, espera 0.2»?',
          opts: ['Perquè canvia de dibuix ràpidament, com els fulls d\'un llibre animat|Porque cambia de dibujo rápidamente, como las hojas de un libro animado', 'Perquè es mou cap a la dreta|Porque se mueve hacia la derecha', 'Perquè fa un so|Porque hace un sonido'], a: 0,
          ex: "Una <b>animació</b> és canviar de vestit a poc a poc i sense parar: l'ull ho veu com un moviment.|Una <b>animación</b> es cambiar de disfraz poco a poco y sin parar: el ojo lo ve como un movimiento." },
        { k: 'move', ph: 'pausa', secs: 30, t: "Assaig d'estrena! Posa't dret/a, saluda el públic imaginari, digues fluixet el nom del teu videojoc i fes una reverència. Ara fes veure que tothom aplaudeix… i aplaudeix tu també!|¡Ensayo de estreno! Ponte de pie, saluda al público imaginario, di en voz baja el nombre de tu videojuego y haz una reverencia. Ahora haz como si todo el mundo aplaudiera… ¡y aplaude tú también!" },
        { k: 'stage', ph: 'repte', q: "<b>Repte de la fira: la cursa.</b> En Numi diu «3, 2, 1» i envia el missatge «som-hi». Programa el cotxe: <b>quan rebi «som-hi»</b>, ha de lliscar fins a la meta (x: 180, y: −130) i, quan hi arribi, dir «He guanyat!».|<b>Reto de la feria: la carrera.</b> Numi dice «3, 2, 1» y envía el mensaje «som-hi». Programa el coche: <b>cuando reciba «som-hi»</b>, tiene que deslizarse hasta la meta (x: 180, y: −130) y, cuando llegue, decir «¡He ganado!».",
          w: { bg: 'ciutat', time: 7, sprites: [{ id: 'numi', art: 'numi', x: -170, y: 40, size: 80, prog: '@numi flag{ say:"3|3",1 say:"2|2",1 say:"1|1",1 send:som-hi }' }, { id: 'cotxe', art: 'cotxe', x: -150, y: -130, size: 80 }, { id: 'bandera', art: 'bandera', x: 200, y: -110, size: 70 }],
            goal: [{ k: 'msg', m: 'som-hi' }, { k: 'at', s: 'cotxe', r: [150, -160, 220, -100] }, { k: 'said', s: 'cotxe', t: 'guanyat' }] },
          edit: ['cotxe'], hats: ['msg:som-hi'], msgs: ['som-hi'], pal: ['glide', 'goto', 'say', 'sound', 'next', 'wait'], texts: ['He guanyat!|¡He ganado!', 'Som-hi!|¡Vamos!'],
          sol: '@cotxe msg:som-hi{ glide:2,180,-130 say:"He guanyat!|¡He ganado!" }',
          hint: "El guió «Quan rebo el missatge som-hi» ja hi és: posa-hi «llisca en 2 s fins a x: 180 y: −130» i, a sota, «digues».|El guion «Al recibir el mensaje som-hi» ya está: pon «desliza en 2 s hasta x: 180 y: −130» y, debajo, «di»." },
        { k: 'stage', ph: 'repte', q: "<b>Repte de la fira: la papallona de la festa.</b> Fes que la papallona voli per tot l'escenari <b>rebotant a les vores</b> i <b>batent les ales</b> (vestit següent) sense parar.|<b>Reto de la feria: la mariposa de la fiesta.</b> Haz que la mariposa vuele por todo el escenario <b>rebotando en los bordes</b> y <b>batiendo las alas</b> (disfraz siguiente) sin parar.",
          w: { bg: 'cel', time: 5, sprites: [{ id: 'papallona', art: 'papallona', x: 0, y: 0, dir: 45 }], goal: [{ k: 'costumes', s: 'papallona', min: 10 }, { k: 'moved', s: 'papallona', min: 150 }, { k: 'turned', s: 'papallona' }, { k: 'running', t: 4.5 }] },
          edit: ['papallona'], hats: ['flag'], pal: ['move', 'turn', 'point', 'bounce', 'next', 'wait', 'rep', 'forever'],
          sol: '@papallona flag{ point:45 forever{ move:8 bounce next wait:0.1 } }',
          hint: "Dins d'un «per sempre»: mou-te, si toques la vora rebota, vestit següent i una espera curta.|Dentro de un «por siempre»: muévete, si tocas el borde rebota, disfraz siguiente y una espera corta." },
        { k: 'screate', ph: 'crea', name: 'El meu videojoc (versió final)|Mi videojuego (versión final)', ...MINE,
          get w() { return myW([{ k: 'running', t: 2.5 }], IN, 2.5); }, get prog() { return myP(); },
          q: "<b>Últims retocs abans de l'estrena!</b> Obre el teu videojoc i posa-hi un <b>títol i unes instruccions</b> al començament (amb «digues» al guió de la bandera). Si vols, afegeix-hi un so o un final més bonic. Quan estigui llest, toca <b>Comprova</b> i desa'l.|<b>¡Últimos retoques antes del estreno!</b> Abre tu videojuego y ponle un <b>título y unas instrucciones</b> al empezar (con «di» en el guion de la bandera). Si quieres, añade un sonido o un final más bonito. Cuando esté listo, toca <b>Comprueba</b> y guárdalo.",
          crit: ['En començar, diu el títol i què has de fer|Al empezar, dice el título y qué tienes que hacer', 'Es pot guanyar o perdre|Se puede ganar o perder', 'Està a punt per presentar-lo|Está a punto para presentarlo'],
          check: P => has(P, ['say', 'think'], 'flag') ? null : 'Funciona! Ara afegeix al guió de la bandera un «digues» amb el títol o les instruccions.|¡Funciona! Ahora añade al guion de la bandera un «di» con el título o las instrucciones.',
          sol: GAME + GAME_E,
          hint: "Al guió «Quan comença» del protagonista, just al principi, posa «digues [títol] durant 2 segons» i «digues [instruccions] durant 2 segons».|En el guion «Al empezar» del protagonista, justo al principio, pon «di [título] durante 2 segundos» y «di [instrucciones] durante 2 segundos»." },
        { k: 'sfree', ph: 'crea', get w() { return myW([], [], 30); }, get prog() { return myP(); }, varNames: VN,
          q: "<b>És la teva estrena!</b> Quan et toqui, ensenya el teu videojoc al projector. Respon les tres preguntes (què he fet, com funciona, què m'ha costat) i deixa que algú del públic el provi.|<b>¡Es tu estreno!</b> Cuando te toque, enseña tu videojuego en el proyector. Responde las tres preguntas (qué he hecho, cómo funciona, qué me ha costado) y deja que alguien del público lo pruebe." },
        { k: 'diploma', ph: 'tanca', skills: [
          'Crear personatges, escenes i diàlegs|Crear personajes, escenas y diálogos',
          'Animar amb vestits, esperes i bucles|Animar con disfraces, esperas y bucles',
          'Programar tecles, tocs i missatges|Programar teclas, toques y mensajes',
          'Moure personatges amb coordenades|Mover personajes con coordenadas',
          'Decidir amb condicions: «si… si no…»|Decidir con condiciones: «si… si no…»',
          'Comptar punts, vides i temps amb variables|Contar puntos, vidas y tiempo con variables',
          "Fer servir l'atzar i els clons|Usar el azar y los clones",
          'Inventar, provar, millorar i presentar un videojoc propi|Inventar, probar, mejorar y presentar un videojuego propio'] },
        { k: 'story', ph: 'tanca', who: 'bit', mood: 'win', t: "BIP BIP BIP! Enhorabona, creador/a! Has acabat el curs. Recorda el que hem après junts: una idea gran es fa <b>peça a peça</b>, provant i millorant. Ara ja pots inventar tots els videojocs, històries i animacions que vulguis!|¡BIP BIP BIP! ¡Enhorabuena, creador/a! Has terminado el curso. Recuerda lo que hemos aprendido juntos: una idea grande se hace <b>pieza a pieza</b>, probando y mejorando. ¡Ahora ya puedes inventar todos los videojuegos, historias y animaciones que quieras!" },
        { k: 'quiz', ph: 'tanca', q: 'Ara ja ho saps: què fa un creador/a quan el seu videojoc té un bug?|Ahora ya lo sabes: ¿qué hace un creador/a cuando su videojuego tiene un bug?',
          opts: ['Busca el bloc que falla, el canvia i ho torna a provar|Busca el bloque que falla, lo cambia y lo vuelve a probar', 'Es rendeix|Se rinde', "Diu que és culpa de l'ordinador|Dice que es culpa del ordenador"], a: 0,
          ex: 'Equivocar-se forma part de crear, i ho has fet molt bé durant tot el curs. Enhorabona!|Equivocarse forma parte de crear, y lo has hecho muy bien durante todo el curso. ¡Enhorabuena!' },
        { k: 'feel', ph: 'tanca' }
      ] }
  ] };
})();
